### ISSUE TITLE
Check permissions on AVUs

### ISSUE THREAD

**Issue by trel** [irods/irods#1595]
_Originally Opened: @adetorcy (2013-07-23 13:01:08_)

Just to put this on the radar: When we merge the community and enterprise code we should make sure that the imeta and iquest loopholes have been closed.
## 

From: https://code.renci.org/gf/project/e-irods/tracker/?action=TrackerItemEdit&tracker_item_id=1595

**Comment by korydraughn** [comment]
I can understand expanding permissions to AVUs, but no one is asking for that AFAIK. This would affect many things and could have a negative impact on everything (i.e. performance, complexity).

Given there hasn't been any movement on this, I think this is safe to close.

@trel Thoughts?

**Comment by trel** [comment]
I don't think this is reasonable in the near or medium term.

We can provide some policy workbook examples if we want to keep this open.

**Comment by korydraughn** [comment]
I vote we close this unless you have ideas for what would make a good policy cookbook example.

**Comment by trel** [comment]
Close it.
