### ISSUE TITLE
object counts should use uint64_t everywhere

### ISSUE THREAD

**Issue by trel** [irods/irods#1703]
_Originally Opened: @trel (2013-09-30 12:20:15_)

object counts should use `uint64_t` everywhere
## 

From: https://code.renci.org/gf/project/e-irods/tracker/?action=TrackerItemEdit&tracker_item_id=1703

**Comment by kellerb** [comment]
As of 4.2, iRODS no longer caches the per-resource object counts in `r_resc_main`.
