### ISSUE TITLE
refactor devtest - inheritance for compound resource flavors

### ISSUE THREAD

**Issue by trel** [irods/irods#1711]
_Originally Opened: @trel (2013-10-02 10:51:35_)

have MockArchive and UniversalMSS inherit from the UnixFileSystem flavor of Compound Resource test class - no need for 3x duplication
## 

From: https://code.renci.org/gf/project/e-irods/tracker/?action=TrackerItemEdit&tracker_item_id=1711

**Comment by trel** [comment]
Happy 6th Birthday!  🎂

**Comment by trel** [comment]
@korydraughn does this still make sense?

**Comment by korydraughn** [comment]
The current setup isn't broken and adjusting that particular piece of code could be tricky.

I think we should leave it as is until we determine there's a need for a change.

**Comment by alanking** [comment]
Is the issue about de-duplicating the code between regular compound, mockarchive, and univmss? They do seem to be... remarkably similar (in the case of mockarchive and univmss, they are actually using the same univmss script):

https://github.com/irods/irods/blob/7b8b97a1966bce4f18bd863997ca977a07485e5b/scripts/irods/test/test_resource_types.py#L2152-L2169

https://github.com/irods/irods/blob/7b8b97a1966bce4f18bd863997ca977a07485e5b/scripts/irods/test/test_resource_types.py#L1449-L1462

https://github.com/irods/irods/blob/7b8b97a1966bce4f18bd863997ca977a07485e5b/scripts/irods/test/test_resource_types.py#L1795-L1808

**Comment by korydraughn** [comment]
I believe so.

**Comment by trel** [comment]
yes, that was the original intent.   but now... maybe we don't need to spend the time/effort.   coming up on an 11th birthday cake...

**Comment by korydraughn** [comment]
Right. I don't think we need to spend time on this. There are more important things for us to focus on and putting time/effort into this just takes away from that.

Let's close this. The test is working. If someone determines the test needs to be changed later, then we can open a new issue for that.

**Comment by trel** [comment]
agreed.   closing.
