### ISSUE TITLE
boost::condition_variable::~condition_variable(): Assertion `!ret' failed

### ISSUE THREAD

**Issue by trel** [irods/irods#1747]
_Originally Opened: @trel (2013-10-15 22:01:52_)

seeing this in the log on ubuntu12...

irodsServer: /tmp/hudson-irodsbuild/workspace/eirods-build-deb-icat-postgres/external/boost_1_54_0/boost/thread/pthread/condition_variable_fwd.hpp:81: boost::condition_variable::~condition_variable(): Assertion `!ret' failed.

to recreate...

1) install from .deb
2) become eirods
3) ./iRODS/irodsctl restart

the server will go down, and leave this in the rodsLog.

--

From: https://code.renci.org/gf/project/e-irods/tracker/?action=TrackerItemEdit&tracker_item_id=1747

**Comment by trel** [comment]
control plane fixes this.

**Comment by Tectract** [comment]
what is "control plane"? I'm seeing this in another build and interested if there's any info on how to solve it without restarting the server?

**Comment by kellerb** [comment]
You are seeing those messages when not restarting the server?

Do you have replication steps?

Which version of iRODS?

**Comment by kellerb** [comment]
More background:
Normally those messages are seen when stopping an iRODS server with `irodsctl`. `irodsctl` basically `kill -9`'s the processes, which does not play nicely with the condition variables.

The "control plane" is a feature added to the upcoming 4.1 release [described here](http://irods.org/post/irods-development-update-march-2015/) that stops the server more gently, no longer triggering the assertion failures.

**Comment by Tectract** [comment]
Actually we were seeing this in a cryptocurrency daemon installation. It looks like it was related to a libdb version issue.
