### ISSUE TITLE
repl code does not honor existing read and/or write locks

### ISSUE THREAD

**Issue by trel** [irods/irods#1781]
- [x] master
- [x] 4-2-stable
--------

_Originally Opened: @trel (2013-10-31 09:59:44_)

repl code does not honor existing read and/or write locks

investigate whether the repl code can honor existing read/write locks.  we are seeing a race condition when coordinating resources have maintenance operations to perform (i.e. make replicas) - when multiple concurrent puts are happening to the root of the resource tree in question.

if repl can be made to honor the --wlock being created by put, then the window of contention could be reduced/eliminated.
## 

From: https://code.renci.org/gf/project/e-irods/tracker/?action=TrackerItemEdit&tracker_item_id=1781

**Comment by alanking** [comment]
Cannot check boxes, but I think this can be closed.
