### ISSUE TITLE
python testing framework needs a flag indicating that the tests are being run on an icat server

### ISSUE THREAD

**Issue by jasoncoposky** [irods/irods#1884]
some tests can only be run on an icat server, a global flag needs set to indicate the flavor of server such that those tests may be skipped.  this will allow trasparent topology testing.

**Comment by trel** [comment]
Cloud Month!

**Comment by kellerb** [comment]
https://github.com/irods/irods/commit/15c1614c3d29bb6cf7d0c450139e44bd19809fe8
