### ISSUE TITLE
Bugzilla 146 - iCommands mishandling SIGPIPE

### ISSUE THREAD

**Issue by trel** [irods/irods#1970]
Martin Pollard 2012-02-28 09:29:44 PST
iCommands are currently mishandling SIGPIPE by writing an error message to
standard error whenever an attempt is made to write to the broken pipe.  This
error message originates from rcConnect.c:63 and seems to be an attempt to
detect a broken connection to the server.  This however causes problems with
utilities such as head on POSIX operating systems because they will generate a
broken pipe whenever there is an attempt to write to STDOUT which is closed (as
head does).

Example of broken behaviour from iQuest:
```
./iquest --no-page -z seq "select DATA_NAME where META_DATA_ATTR_VALUE like
'SEQCAP_Whole_Genome_Sequencing_of_Crohns_Disease_Patients'" | head
Zone is seq
DATA_NAME = 6503_6#0.bam
------------------------------------------------------------
DATA_NAME = 6503_6#1.bam
------------------------------------------------------------
DATA_NAME = 6503_6#2.bam
------------------------------------------------------------
DATA_NAME = 6503_6#3.bam
------------------------------------------------------------
DATA_NAME = 6503_7#0.bam
Client Caught broken pipe signal. Connection to server may be down
Client Caught broken pipe signal. Connection to server may be down
Client Caught broken pipe signal. Connection to server may be down
Client Caught broken pipe signal. Connection to server may be down
Client Caught broken pipe signal. Connection to server may be down
```

The "Client Caught broken pipe signal. Connection to server may be down" is
repeated as many times as there are results.

This could be fixed by changing:
        signal (SIGPIPE, (void (*)(int)) rcPipSigHandler);
to:
        signal (SIGPIPE, SIG_IGN);

The signal handler should be superfluous if the writes to the server are error
checked.

**Comment by jmarshall** [comment]
If a third-party client application has set its own SIGPIPE handler, it won't be expecting `rcConnect()` to rearrange things to ignoring SIGPIPE.

And in fact, SIG_IGN is not the right thing for the `irodsclient | head` scenario either: `irodsclient` will run to completion (which might be a long time for large data files) rather than exiting after it has supplied `head`'s input needs.

As Martin wrote,
> The signal handler should be superfluous if the writes to the server are error checked.

...in which case, how about just not touching SIGPIPE at all?

**Comment by trel** [comment]
We'll look at this again today.

**Comment by trel** [comment]
pinging @mp15 @jmarshall @dkj @keithj 

Does this look sufficient?  We've updated rcConnect and all icommands.

**Comment by mp15** [comment]
Looks good to me

**Comment by trel** [comment]
excellent - thanks.
