### ISSUE TITLE
Bugzilla 170 - iput -f allows me to put multiple different files with the same name in the same collection - BUG or feature?

### ISSUE THREAD

**Issue by trel** [irods/irods#1973]
Irina 2014-03-12 05:30:20 PDT
Hi,

I am not sure if this is a bug or is meant to be a feature, but iRODS allows me
to iput different files with the same name in the same collection. Basically
I've ended up having something like:
```
  usr1           1 irods-ddn-rd10a-4           14344 2014-03-11.18:43  
results.txt
  usr1           2 irods-ddn-gg07-2           217896 2014-03-12.11:42 &
results.txt
  usr1           4 irods-ddn-rd10a-5           14344 2014-03-11.18:44  
results.txt
  usr1           5 irods-ddn-rd10a-6           16297 2014-03-11.18:51  
results.txt
  usr1           6 irods-ddn-rd10a-7          217896 2014-03-12.11:42 &
results.txt
```
where results.txt is the file I intend to store in iRODS. As you can see there
are 3 different files with the same name (on different resources) having
different sizes, but all in the same collection.

This is the result of running iput -f, which basically ignored the existing
dataObjects with the same name stored in the destination collection, and just
uploaded the one given as parameter on the resource mentioned regardless of
what already exists. If I run iput without -f flag, I receive an error saying:

status = -312000 status = -312000 OVERWRITE_WITHOUT_FORCE_FLAG

which sounds a bit misleading, given the fact that if I run iput with force
flag it doesn't actually overwrite anything.

**Comment by kellerb** [comment]
We are unable to replicate this on master. We did encounter a slightly different `iput -f -R...` issue, tracked here: #2651
