### ISSUE TITLE
"iput -r ./" will create a collection named "."

### ISSUE THREAD

**Issue by trel** [irods/irods#2010]
- [x] master
- [x] 4-2-stable
---------

This is a surprise and is unusable.

Ideally, the "./" will get interpreted and converted to a real basename value.

Trailing slash is a tricky problem.

**Comment by andrew-irods** [comment]
Possibly fixed with #3658 - test to prove.

**Comment by trel** [comment]
The above table of options is no longer deemed desirable.

We are now resolving the `.` and `./` early and `iput -r` will create the target collection if it doesn't already exist.  `irsync` and `icp` now behave very similarly.

Confirmed fixed in 4.2.3.
