### ISSUE TITLE
doxygen dependency on Debian pulls in nearly 1 Gb of packages

### ISSUE THREAD

**Issue by keithj** [irods/irods#2024]
Having a mandatory doxygen dependency for building on Debian pulls in nearly 1 Gb of external packages, most of which is due to the transitive dependency on latex. It would be more reasonable to build the docs only if doxygen is present or check the dependency only if the docs target is given.

The entire OS is occupying 2.6 Gb currently, so an extra 972 Mb (636Mb download) is significant.

**Comment by trel** [comment]
We're now driven by CMake.    Not sure the current status of any extraneous dependencies.

**Comment by SwooshyCueb** [comment]
Given that docs generation is not currently part of our buildsystem, I think this issue can be closed.

**Comment by trel** [comment]
Agreed - closing.
