### ISSUE TITLE
minor bug report -- iinit usage w/ GSI authentication

### ISSUE THREAD

**Issue by Wayne-Schroeder** [irods/irods#2029]
This was first reported on irod-chat by Peter Danecek of ingv.it March 26 by the same title, https://groups.google.com/forum/#!topic/iROD-Chat/z0ll_wC0LUc .  This is a failure in the 3.3.1 `iinit` functionality that sets up an .irodsEnv file if the user doesn't have one, when the site is using GSI authentication only.  Peter and I had some follow-up discussion in email off-list and I tried to reproduce the problem here at DICE-UCSD on a Linux host, setting up GSI using CI-Logon infrastructure, but it worked fine for me.  I'm not sure what's different between his environment and mine, but I believe that `iinit` functionality works fine in most cases and even some GSI cases.  He and I thought we should move it to Github for tracking so I'm doing that now.
- Wayne -

**Comment by trel** [comment]
We no longer are supporting GSI - closing.
