### ISSUE TITLE
Current behavior when doing recursive iputs involving symlinks is possibly surprising.

### ISSUE THREAD

**Issue by tempoz** [irods/irods#2053]
Currently we do not follow symlinks to directories in iRODS on a recursive iput, and no warning is given. This can be particularly surprising when the explicit target of the iput is a symlink, as the command will succeed and no data whatsoever will be put.

"Correct" behavior for this sort of put is not actually clear: as iRODS does not have a robust support for linking, simulating the linking occurring is not really an option; following the links and implementing them as directories could result in data being put multiple times; building the directory structure in memory and resolving duplication of data isn't really an option because the size of the data structure could easily exceed memory. We may need to provide options regarding recursive puts as well as implement links in iRODS to fully cover this issue.

**Comment by trel** [comment]
related to https://github.com/irods/irods/issues/3623

**Comment by trel** [comment]
I think this is fixed - will investigate.

**Comment by korydraughn** [comment]
What is the expected behavior for this?
What are we investigating here?

**Comment by trel** [comment]
I think the scenarios include:
 - good links
 - bad / dangling links
 - link cycles / loops (links pointing to self or parent)

The behavior now is:
 - Follow and include the contents (dereference) of the symlink as the file content
 - If `--link` is passed, that link is just ignored, nothing is created in iRODS.

Work done for #3988, #4009, #4013 for 4.2.4 appears to cover all these cases (see https://github.com/irods/irods/commit/3e6c08a58cfbab723cdf327834c86b4e93bb7eec).
