### ISSUE TITLE
iRODS streaming of files

### ISSUE THREAD

**Issue by michael-conway** [irods/irods#2055]
There are multiple code-paths to put data on iRODS and get this data back.  A common use case is the use of input and output streams over get and put mechanisms.

We need to get streaming on an equal footing with get/put

*the performance is questionable.  There are elements in Jargon and PHP to look at here too, so it is an end-to-end question.  I highly suspect we can extract better transfer performance.

*Policy enforcement points should be normalized so that a file put using iPut and a file 'put' using streaming behave the same

**Comment by trel** [comment]
being handled by https://github.com/DICE-UNC/chunky
