### ISSUE TITLE
Plug-ins for ImageMagic?

### ISSUE THREAD

**Issue by michael-conway** [irods/irods#2058]
This is a nice-to-have, we do an awful lot of image processing, especially thumbnailing, and it would be really nice to have standard plug-ins and rules/microservices to accomplish bread and butter image manipulation to power interfaces that do gallery views and previews

**Comment by michael-conway** [comment]
This is becoming a need-to-have for the consortium request to add a gallery view to various interfaces.

We need to have

a) a standard rule to call that will return the abspath of a thumbnail

b) have that standard rule either discover a pre-generated thumbnail OR generate a thumbnail on demand.

The client needs to be able to have a consistent hook across installations to accomplish the thumbnailing, and I would like to suggest a common microservice hook as a plugin that could resolve this as a sort of 'abstract interface'.  In this manner, installations could take a default behavior or extend it as long as the getThumbnail(irodsPath) function returns a valid absPath?

If thumbnails are generated as a sidecar to an actual image, as in a postprocforput rule, then a standard convention or metadata tag to associate the thumbnail is needed.  It can vary as long as the microservice is encoded to respect the installation-specific scheme.

I'd like to ask that we prioritize this as it is part of a consortium member request.

**Comment by sgworth** [comment]
Mike,
Does this have to use ImageMagic or do you refer to it as a reference?  In
general, I would advise staying away from ImageMagic due to its licensing
terms.

**Comment by michael-conway** [comment]
I am hoping to come to some general agreement on 'abstract' interfaces,
perhaps with a reference implementation and the ability to extend.

So some protocol, microservice, or rule like  getImageForPrevieew()
returning an iRODS path is great. Then one could have any strategy (on
demand, pre-rendered) for returning a thumbnail.

I figure an isPreviewSupported() or some sort of standard way of letting a
client know what services are available is important

The way to standardize such common capabilities would help DFC as we try to
have generalizable services that don't limit the options of a particular
institution.

**Comment by trel** [comment]
This can now be handled via the rcClientHints API.
