### ISSUE TITLE
A grab bag of questions and previews of DFC noted client enhancements

### ISSUE THREAD

**Issue by michael-conway** [irods/irods#2060]
There are several items on the work list that are worth reviewing, some already discussed, but I'll put them here and at some point we could match priorities or you could waive me off on things that are dumb to try.

1) locking?  Should I bother at this point.  I seem to be hearing don't bother right now...

2) long file restart?  This is a hot client request, and I'll be looking at Mike Wan's code for restarting long transfers mid-flight, this is a big reliability factor for Jargon.

3) when we start talking about protocols, are there plans to look at identifying multi-step fine-grained operations on the client that can be replaced by new course-grained protocol operations.  A big question here is providing streams of callbacks on recursive operations, and do we have a strategy for this?  XMessage?

Along with this, I have GSI authentication, TLS support, and I need to better handle PAM authentication and this idea that I need to cache temporary passwords and not re-auth with the PAM credentials repeatedly, yet be able to handle those temporary passwords aging out and seamlessly recover.

I am also really keen to see some form of registry and discovery and wonder if ProtoBuf is really a pre-requisite?  If we do have, for example, an ImageMagic plug-in, how do I know it's available otherwise?

Anyhow, this is the catch-all ticket for randomness.

**Comment by trel** [comment]
no actionable items here - closing.    any specific items should get their own new issues.
