### ISSUE TITLE
Server availability is not properly tested in Perl scripts

### ISSUE THREAD

**Issue by AndreyNevolin** [irods/irods#2108]
Consider a fragment from "irods_setup.pl" (/var/lib/irods/iRODS/scripts/perl/irods_setup.pl):

       # Start iRODS.
        printStatus( "Starting iRODS server...\n" );
        printLog( "\nStarting iRODS server...\n" );
        if ( startIrods( ) == 0 )
        {
                printError( "\nInstall problem:\n" );
                printError( "    Cannot start iRODS server.\n" );
                printLog( "\nCannot start iRODS server.\n" );
                cleanAndExit( 1 );
        }

        # Connect.
        printStatus( "Opening iRODS connection...\n" );
        printLog( "\nOpening iRODS connection...\n" );
        my ($status,$output) = run( "$iinit $IRODS_ADMIN_PASSWORD" );

Here "startIrods()" returns non-zero if iRODS server process was successfully started. After that "iinit" is executed.

The problem is that iRODS server process may be successfully started but the service it provides may be unavailable at the point where "iinit" is executed.

That's how it happens:
1) the server process starts and begins negotiation with iCAT server
2) after the server initialization is complete, the server starts listening to client requests
3) if client request comes during the server initialization the fail occurs since nobody is listening the client

In most cases the problem is not critical because of the following code in "connectToRhostWithTout":

    while ( timeoutCnt < MAX_CONN_RETRY_CNT ) {
        status = connect( sock, sin, sizeof( struct sockaddr ) );

I.e. there are three attempts (MAX_CONN_RETRY_CNT = 3) to connect to the server. So it's very likely that the server will finish the initialization while the client loop is executed. But in some cases the negotiation between iCAT and the resource server may take a long time (for example, in the case when iCAT is very distant from the resource server). In this case "iinit" will be unable to connect to the server.

I suppose that the server should provide direct response about its availability. Some "reasonable" time should be spent while waiting for the server reply.

Other iRODS Perl scripts suffer from the same issue.

**Comment by trel** [comment]
This will be handled in the python code - part of moving away from perl completely #2756
