### ISSUE TITLE
RFC / Enhancement irods log file location

### ISSUE THREAD

**Issue by PeteClapham** [irods/irods#2112]
Hello,
I wonder if it would be possible to point irods logs to /var/log/irods or similar as the current 4.x points them to a less usual /var/lib/irods/iRODS/server/logs dir which is catching some people out

Many thanks

**Comment by bzizou** [comment]
Same thing for the pid files that should be stored into /var/run imho

**Comment by trel** [comment]
RFC for new logging overhaul here
https://github.com/irods/irods_rfcs/blob/master/0001_logging.md
