### ISSUE TITLE
windows i-commands

### ISSUE THREAD

**Issue by edwins** [irods/irods#2121]
We have users who have asked for windows i-commands, rather than having to use a gui client.  In particular, this would help in the automation for Windows.  The last version of i-commands is 3.0 alpha, found here: https://wiki.irods.org/index.php/windows#Windows_i-commands.  If at all possible, it would be best if the updated windows i-commands was backward compatible with iRODS server v3.3+ until data providers can upgrade to 4.0.

**Comment by trel** [comment]
We have heard reports in the wild that with Windows 10, users can now install and run the Ubuntu14 iCommands packages in the Windows Subsystem for Linux.

Closing this issue for now - as any further updates will involve both the client and the server code and be in a new issue.

**Comment by tedgin** [comment]
Some of our users are unhappy with running iCommands on the Windows Subsystem for Linux.  They will be happy to know version 4.3 of iCommands will run natively on Windows.

(Sorry guys. I'm just a messenger.)

**Comment by trel** [comment]
We don't support iCommands on Windows, natively.

You can also consider launching a Docker container with the iCommands installed.
