### ISSUE TITLE
Metadata Templates

### ISSUE THREAD

**Issue by michael-conway** [irods/irods#2205]
This is a DFC task that seems broadly useful, that is, a mechanism to specify metadata templates for use in interfaces in a standard way (across languages, across specific interface implementations).  We're planning on supporting code to discover and facilitate metadata editing through a template scheme as part of this .irods hidden folder construct.

This is useful on the iRODS side as microservices could similarly interpret these metadata templates, either for icommands, or for server side validation of entered metadata.

Rick Skarbez did a great write up of the JSON schema approach to metadata templates, which we've put in the iDROP issues here

https://github.com/DICE-UNC/idrop/issues/35

**Comment by trel** [comment]
we're working on this - as a series of specs and plugins.  they won't be a part of this repository.
