### ISSUE TITLE
Deallocation of 'rodsDirent' objects

### ISSUE THREAD

**Issue by AndreyNevolin** [irods/irods#2218]
'rodsDirent' objects are allocated inside resource plugins. But I cannot find the place where they are freed. Seems such place doesn't exist.

Currently that doesn't appear to be a problem since all 'rodsDirent' objects die together with Agent. And Agents die frequently since every Agent invocation is intended for a single action.

But if Agent usage model changes or very big directories come into action (i.e. a lot of 'rodsDirent' objects are created during a single Agent run) memory consumption by the objects may become a problem.

That not necessarily to become the case. Consider all above just as information for reflection :)

**Comment by jasoncoposky** [comment]
here are a few places the directory entries are deallocated:

iRODS/server/api/src/rsQuerySpecColl.cpp:256:        free( rodsDirent );
iRODS/server/api/src/rsPhyPathReg.cpp:640:            free( rodsDirent );
iRODS/server/api/src/rsPhyPathReg.cpp:646:            free( rodsDirent ); // JMC - backport 4835
iRODS/server/api/src/rsPhyPathReg.cpp:655:            free( rodsDirent );
iRODS/server/api/src/rsPhyPathReg.cpp:674:            free( rodsDirent ); // JMC - backport 4835
iRODS/server/api/src/rsPhyPathReg.cpp:683:                    free( rodsDirent ); // JMC - backport 4835
iRODS/server/api/src/rsPhyPathReg.cpp:703:        free( rodsDirent ); // JMC - backport 4835
iRODS/server/api/src/rsDataObjRename.cpp:585:        free( rodsDirent );

also the rodsDirent_t is also an out-variable to the API call at which point the outgoing variable is also deallocated by the response to the API call after it is sent over the wire.
