### ISSUE TITLE
Unclear logic of "unix_file_readdir_plugin"

### ISSUE THREAD

**Issue by AndreyNevolin** [irods/irods#2226]
Please look at the following code:

```
            struct dirent * tmp_dirent = readdir( fco->directory_pointer() );

            // =-=-=-=-=-=-=-
            // handle error cases
            if ( ( result = ASSERT_ERROR( tmp_dirent != NULL, -1, "End of directory list reached." ) ).ok() ) {

                // =-=-=-=-=-=-=-
                // alloc dirent as necessary
                if ( !( *_dirent_ptr ) ) {
                    ( *_dirent_ptr ) = new rodsDirent_t;
                }

                // =-=-=-=-=-=-=-
                // convert standard dirent to rods dirent struct
                int status = direntToRodsDirent( ( *_dirent_ptr ), tmp_dirent );
                if ( status < 0 ) {
                    irods::log( ERROR( status, "direntToRodsDirent failed." ) );
                }

#if defined(solaris_platform)
                rstrcpy( ( *_dirent_ptr )->d_name, tmp_dirent->d_name, MAX_NAME_LEN );
#endif
            }
            else {
                // =-=-=-=-=-=-=-
                // cache status in out variable
                int status = UNIX_FILE_READDIR_ERR - errno;
                if ( ( result = ASSERT_ERROR( errno == 0, status, "Readdir error, status = %d, errno= \"%s\".",
                                              status, strerror( errno ) ) ).ok() ) {
                    result.code( -1 );
                }
            }
```

It can be deduced from the code above that when "readdir" returns zero, "unix_file_readdir_plugin" returns an error.

"readdir" returns zero in two cases:
1) invalid directory descriptor was provided to the system call
2) end of the directory was reached

"unix_file_readdir_plugin" doesn't differentiate between these cases. In both cases "-1" is returned as a status code.

One might expect the following behavior of the 'Readdir' plugin interface:
1) end of a directory is not reached, call is successful: status == 0, _dirent_ptr points to a corresponding object
2) call is successful but end of a directory is reached: status == 0, _dirent_ptr is zero
3) fail occurred: _dirent_ptr is zero, status == UNIX_FILE_READDIR_ERR - errno

But this logic is not expected by iRODS. Consider the function "chkEmptyDir":
```
    irods::error readdir_err = fileReaddir( rsComm, cacheDir_obj, &myFileDirent );
    while ( readdir_err.ok() && 0 == readdir_err.code() ) {
        ...................
        readdir_err = fileReaddir( rsComm, cacheDir_obj, &myFileDirent );
    }
```
So the function expects that error will be returned by "Readdir" when the end of a directory is reached. Seems this logic explains 'magical' -1 coded inside "unix_file_readdir_plugin".

This logic should be fixed. Resource plugin developers do not expect that "Readdir" should return an error code in case of successful execution.

**Comment by jasoncoposky** [comment]
bumping this to 4.2 as it will affect all resource plugins, and client implementations.

**Comment by jasoncoposky** [comment]
There are two issues with this fix:

1. The packstruct code does not properly handle null pointers.  The dirent pointer is not NULL when it is sent over the wire which prevents the code from properly detecting an end of directory.

2. The 3.X code follows the same semantics, and this fix would cause issues with federation.
