### ISSUE TITLE
irodsFs -o -f <mountpoint> causes mount to just hang

### ISSUE THREAD

**Issue by jerry57** [irods/irods#2277]
issuing a:
`irodsFs -o -f $HOME/fuse_mount`
causes the mount attempt to just hang.
removing `-o -f` allows mount to go through

OS was:
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.2 LTS
Release:	12.04
Codename:	precise

**Comment by trel** [comment]
@iychoi @xu-hao is this still a problem?

**Comment by iychoi** [comment]
In my environment, this is not reproducible. How about @xu-hao?

**Comment by xu-hao** [comment]
@iychoi, thanks for testing it.

**Comment by xu-hao** [comment]
Do we need to add a test to the CI?

**Comment by trel** [comment]
I can replicate the behavior using the master branch and Ubuntu 14.

**Comment by trel** [comment]
The `foreground` option **should** just run in the foreground until `fusermount -u <mountpoint>` is run (in a separate terminal).

Bench testing shows that listing the mounted directory works while `irodsFs` is in foreground mode.  `irodsFs -o -f <mountpoint>` returns no error message and a returncode of `0` (after a second or three) once unmounted.

```bash
$ irodsFs -o -f awesome/
$ echo $?
0
```

```bash
$ ls awesome
foo
$ fusermount -u awesome/
$ ls awesome
$
```

After looking a bit closer, I think this is working as expected.

@jerry57 ?

**Comment by iychoi** [comment]
This works well in current version as expected. Previously in 3.3.x, when I mount the fuse under user's home directory, it hung and got not able to access the mounted volume. Now it works well.
