### ISSUE TITLE
core.re cache not updating after rapid sequential changes to core.re

### ISSUE THREAD

**Issue by kellerb** [irods/irods#2279]
- [x] main
- [X] 4-2-stable
- [x] main - remove all sleep()s
- [x] 4-3-stable - remove all sleep()s
------

Use hash (in addition to / instead of ) file timestamp to determine if core.re has been modified. Expected to resolve issues seen in #2276.

Once fixed, revert devtest workaround 2942df8ff405ab9df8d3401edb9418c396c2be0a.

**Comment by trel** [comment]
if i get a vote, i'd say let's leave 4.2 as is.   the sleeps are only in the tests, right?

**Comment by korydraughn** [comment]
I agree. Let's leave the sleeps in 4-2-stable and only target 4-3-stable for this.

**Comment by korydraughn** [comment]
@MartinFlores751 Don't forget to cherry-pick #6765 to 4-3-stable.

**Comment by trel** [comment]
and then this becomes a 4.2.12, yes?

**Comment by korydraughn** [comment]
Because of the original work?

**Comment by korydraughn** [comment]
Changed milestone to 4.2.12 because this issue is linked to commits that predate 4.2.

**Comment by alanking** [comment]
So... we do need to remove the sleeps from 4-2-stable before closing?

**Comment by trel** [comment]
> I agree. Let's leave the sleeps in 4-2-stable and only target 4-3-stable for this.


nopes.

**Comment by korydraughn** [comment]
The removal of sleeps are for 4.3 only.

And given this comment, https://github.com/irods/irods/issues/2279#issuecomment-1363391140, there is no more work to do here.

Closing.
