### ISSUE TITLE
add initial control plane implementation to the iRODS server and agents

### ISSUE THREAD

**Issue by trel** [irods/irods#2298]
This will allow back-channel communication for all manner of useful work.

Initial efforts will include graceful agent shutdown #2297.

Additionally referenced by: #1747, #1859, #2179

**Comment by trel** [comment]
seeing this in server log...

```
Jan 21 13:13:07 pid:9280 ERROR: server_control_executor - icat_host_name is localhost, not a fqdn
```

doesn't feel like a real error?

**Comment by jasoncoposky** [comment]
it is not a critical error, it is a placeholder error which will turn into an exception as we will not support 'localhost' in the future for hostnames.
