### ISSUE TITLE
move magic numbers to server_config.json

### ISSUE THREAD

**Issue by trel** [irods/irods#2303]
- rule engine random salt string bytelength, currently 40
- parallel transfer threshold, currently 32MB
- default number of threads for parallel transfer, currently 4
- sys connection count, currently 3
- max SQL rows, currently 256

For consideration:
* rodsDef.hpp
  * HEADER_TYPE_LEN
  * TIME_LEN
  * NAME_LEN
  * CHKSUM_LEN
  * LONG_NAME_LEN
  * MAX_PATH_ALLOWED
  * MAX_NAME_LEN
  * HUGE_NAME_LEN
  * META_STR_LEN
  * SHORT_STR_LEN
  * PTR_ARRAY_MALLOC_LEN
  * MAX_SZ_FOR_SINGLE_BUF
  * INIT_SZ_FOR_EXECMD_BUF
  * MAX_SZ_FOR_EXECMD_BUF
  * MIN_SZ_FOR_PARA_TRAN
  * TRANS_BUF_SZ
  * CRYPT_BUF_SZ
  * TRANS_SZ
  * LARGE_SPACE
  * UNKNOWN_FILE_SZ
  * MIN_RESTART_SIZE
  * RESTART_FILE_UPDATE_SIZE
  * DEF_NUM_TRAN_THR
  * MAX_NUM_CONFIG_TRAN_THR
  * SZ_PER_TRAN_THR
  * SELECT_TIMEOUT_FOR_CONN
  * SYS_SVR_TO_CLI_MSI_REQUEST
  * SYS_SVR_TO_CLI_COLL_STAT
  * SYS_CLI_TO_SVR_COLL_STAT_REPLY
  * SYS_SVR_TO_CLI_PUT_ACTION
  * SYS_SVR_TO_CLI_GET_ACTION
  * SYS_RSYNC_TARGET_MODIFIED
  * MAX_NUM_BULK_OPR_FILES
  * MAX_BULK_OPR_FILE_SIZE
  * BULK_OPR_BUF_SIZE
  * TAR_OVERHEAD

**Comment by jasoncoposky** [comment]
also include the temporary password times from db_plugin.cpp:
#define TEMP_PASSWORD_TIME 120
#define TEMP_PASSWORD_MAX_TIME 1000

**Comment by jasoncoposky** [comment]
Targeted for 4.1:

- [ ] MAX_PASSWORD_LEN
- [ ] DEF_NUM_TRAN_THR
- [ ] MAX_NUM_CONFIG_TRAN_THR
- [ ] TRANS_SZ
- [ ] TRANS_BUF_SZ
- [ ] SZ_PER_TRAN_THR
- [ ] TEMP_PASSWORD_TIME
- [ ] TEMP_PASSWORD_MAX_TIME

**Comment by trel** [comment]
re: `maximum_password_length`, consider also the database table... currently 250:

https://github.com/irods/irods/blob/master/plugins/database/src/icatSysTables.sql.pp#L354
```
create table R_USER_PASSWORD
 (
   user_id              INT64TYPE not null,
   rcat_password        varchar(250) not null,
   pass_expiry_ts       varchar(32) not null,
   create_ts            varchar(32),
   modify_ts            varchar(32)
 ) ;
```
/cc @pontus

**Comment by jasoncoposky** [comment]
MAX_NUM_CONFIG_TRAN_THR will not be refactored as it is used in the table for packing instructions and is also referenced by the restart data structures within rcConnect.hpp.
