### ISSUE TITLE
OSX build problems

### ISSUE THREAD

**Issue by danielhanlon** [irods/irods#2326]
I'm having problems building the iCommands on OSX 10.9.4

If I use the 4.0.3 tarball it fails with lots of errors like:

```
/Users/djn/irods-4.0.3/external/boost_1_55_0z/boost/atomic/detail/gcc-atomic.hpp:961:64: error: no matching constructor for initialization of 'storage_type' (aka 'boost::atomics::detail::storage128_type')
    explicit base_atomic(value_type const& v) BOOST_NOEXCEPT : v_(0)
                                                               ^  ~
/Users/djn/irods-4.0.3/external/boost_1_55_0z/boost/atomic/detail/gcc-atomic.hpp:932:28: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'int' to 'const boost::atomics::detail::storage128_type'
      for 1st argument
struct BOOST_ALIGNMENT(16) storage128_type
```

i.e. the same as: https://github.com/irods/irods/issues/2167

Looking at https://github.com/irods/irods/issues/2266 and assuming that boost 1.56 would solve the problem, I tried to build from the current master. I get:

```
make[2]: *** No rule to make target `/Users/djn/irods/external/boost_1_56_0/stage/lib/libboost_system.a', needed by `/Users/djn/irods/iRODS/lib/core/obj/base64.o'.  Stop.
```

The irods_external_.tar.gz contains boost_1_55_0z so presumably that's what's causing the problem.

Sorry if I'm missing something here but what is the current recommended way to get the icommands/irodsFS on OSX?

**Comment by trel** [comment]
This should be working fine now on 4-1-stable, and probably on master as well.
