### ISSUE TITLE
Memory leak in "getFile" (really critical)

### ISSUE THREAD

**Issue by AndreyNevolin** [irods/irods#2338]
Hi All,

There is a significant memory leak in `getFile` function. The function is used for single-stream reading of data.

Buffer allocated inside `rcDataObjRead( conn, &dataObjReadInp, &dataObjReadInpBBuf )` is not freed, but pointer to the buffer is overwritten to point to a newly allocated buffer at each "while" loop iteration.

Because of that, `getFile` actually keeps the whole file copy in memory (in addition to a copy committed to a disk).

There is a call to "free" just below the "while" loop:

`free( dataObjReadInpBBuf.buf );`

To fix the bug, the call should be moved three lines up (just before the "while" loop closing bracket).

**Comment by jasoncoposky** [comment]
closing, fixed in #2538
