### ISSUE TITLE
hard coded oracle client PATH

### ISSUE THREAD

**Issue by PeteClapham** [irods/irods#2342]
Hello,
On running through a --run-in-place it appears that the oracle client location is hard coded in:

`irods/plugins/database/oracle/Makefile`

Could this be set relative to `$ORACLE_HOME` instead ?

Similarly this is also the case in :
`find_odbc_oracle.sh`

This makes life interesting when testing code against the src.

Many thanks
Pete

**Comment by trel** [comment]
This is complete - and has been backported for a release of the database plugins v1.4 [#2466].

Closing.
