### ISSUE TITLE
incorporate ifind, ipc, and ienv extensions

### ISSUE THREAD

**Issue by trel** [irods/irods#2343]
These are three commits from Aug 2014 into SVN by @Wayne-Schroeder.

They are:
- ifind - https://github.com/irods/irods-legacy/commit/b0886925fb7682c03886bb738fa2511b45dfe633
- ipc - https://github.com/irods/irods-legacy/commit/ef00f4fe7718d0b4b6fa4cf944436d8d949671fd
- ienv - https://github.com/irods/irods-legacy/commit/382b9f2858a82b975129f92584c7be51f73997f5

and from Sept 2014
- ihelp - https://github.com/irods/irods-legacy/commit/98e9bcbfb279d1b6141fc3f6ba49fb0467cba604

**Comment by jasoncoposky** [comment]
now referenced in this repository - irods/additional_legacy_icommands#1
