### ISSUE TITLE
deleted files on iRODS not retransferred if restart file used

### ISSUE THREAD

**Issue by seandavi** [irods/irods#2348]
Using iRODS-4.0.3, I initiated an `iput` with a restart file.  If the transfer is interrupted, removed some files in iRODS using `irm` (files that were in the restart file as having been transferred).  I, then, restarted the transfer. The deleted files were not retransferred.  This was a bit unexpected.  I might have thought that iRODS would at least check for file existence and perhaps size before consulting the restart file to see if the file had been transferred.

**Comment by jasoncoposky** [comment]
closing due to no further discussion
