### ISSUE TITLE
MAX_PASSWORD_LEN 50 is not enough ( iRODS/lib/api/include/authenticate.hpp)

### ISSUE THREAD

**Issue by pontus** [irods/irods#2353]
MAX_PASSWORD_LEN is set to 50 in iRODS/lib/api/include/authenticate.hpp.

We have a use case where we use Yubikeys for 2 factor authentication (via PAM). The way this works is that the user gives their password but presses on the Yubikey instead of Enter. The password transmitted is then the "real" password followed by a Yubikey token (made up of an otp and some identifiers).

As the Yuibkey token is 44 octets long, limiting the password to 50 bytes or similar means our users are effectively limited to 5 charcter passwords, which we consider unfortunate.

Can this be raised? I naturally don't know all the nuances but guess it wouldn't be noticable if we bumped it to 512 or 1024.

**Comment by jasoncoposky** [comment]
Note: MAX_PASSWORD_LEN is used by the packing instructions directly which prevents a run-time configurable size until we move to a new serialization technology ( Avro )
