### ISSUE TITLE
Create .irodsEnv parameter for default client NumThreads

### ISSUE THREAD

**Issue by trel** [irods/irods#2374]
From @agreif on iRODS-Chat:
  https://groups.google.com/forum/#!topic/irod-chat/RSXiyed7Hi0

This would apply initially for `iput` and `iget`.

`.irodsEnv` parameter could be `irodsClientSetNumThreads` or just `irodsSetNumThreads`

This would mirror the acSetNumThreads rule on the server side, but take precedence like the existing `-N` flag on both `iput` and `iget`.  If `-N` were used directly, it would take precedence over this setting.

**Comment by jasoncoposky** [comment]
thie feature is already supported by the irods_environment.json parameter: irods_default_number_of_transfer_threads
