### ISSUE TITLE
acpostprocforput rule to do compression on server after uploaded fails with  -344000 for large files

### ISSUE THREAD

**Issue by michael-conway** [irods/irods#2375]
on behalf of Humanshu [from irod-chat](https://groups.google.com/forum/#!topic/iROD-Chat/JWr2mnuXGqE):

***

I develop one `acPostProcForPut` rule as below to automatically compress file on server after uploading it with iput command:

```
acPostProcForPut { ON($objPath like "\*tif")  { msiSplitPath($filePath,*fileDir,*fileName);  writeLine("serverLog","After Filename is *fileName and full path is" ++$filePath); msiExecCmd("script.sh",$filePath,"null","null","null",*Junk);  } }


script.sh
lz4mt -q $1 $1.lz4
iput $1.lz4
```

It works fine when I upload small size file using below command:
```
iput -v filename

bash-4.1$ ils
/tempZone/home/raj:
  filename.tif
  filename.tif.lz4
```

But when I use files of big size then it is giving me error:
```
bash-4.1$ iput -v filename.tif

   filename.tif           624.073 MB | 1.928 sec | 16 thr | 323.675 MB/s
Level 0: DEBUG: execMicroService3: error when executing microservice
line 270, col 177, rule base core
acPostProcForPut { ON($objPath like "\*tif")  { msiSplitPath($filePath,*fileDir,*fileName);  writeLine("serverLog","After Filename is *fileName and full path is" ++$filePath);  msiExecCmd("script.sh",$filePath,"null","null","null",*Junk);  } }
                                                                                                                                                                                 ^

caused by: DEBUG: msiExecCmd: rsExecCmd failed for script.sh, status = -344000
```

My perception is that in case of big file iRODS is still writing it to server, while in between that time iRODS scehedule the `acPostProcForPut` rule and while some threads are still writing file, above `acPostProcForPut` rule tries to compress the file which is not possible thats why it is giving error.
Please tell me how to make sure that file is written to disk and after that only my `acPostProcForPut` rule gets executes.

I have used delay also in this case but I am not sure how much time to delay it as it depends on file size.

Thanks in advance!

Humanshu

**Comment by jasoncoposky** [comment]
acPostProcForPut in non-bulk operations is only called in rsDataObjClose, at which point all the data will be at rest.

**Comment by trel** [comment]
@jasoncoposky this a candidate for 4.2?  or is this just a documentation issue?

**Comment by jasoncoposky** [comment]
i have not been able to reproduce this error on the master branch using gzip.  closing for now.
