### ISSUE TITLE
Add libcurl3-gnutls as package dependency on Debian

### ISSUE THREAD

**Issue by grawinkel** [irods/irods#2382]
A fresh stable Debian installation cannot run iRODS4.0.3.

ldd /var/lib/irods/iRODS/server/bin/irodsServer shows that the dependency on 'libcurl-gnutls.so.4' is unsatisfied. This can be fixed by installing 'libcurl3-gnutls'.

**Comment by trel** [comment]
4.1.0 is building and installing fine on Debian 7.

Bumping this to 4.2.0 for packages since we don't have Debian in CI yet.  New OS combinations should be added quickly after 4.1.0 is out the door.

**Comment by SwooshyCueb** [comment]
`irodsServer` no longer depends on any variant of `libcurl`.
