### ISSUE TITLE
icommands - imeta add interprets values starting with minus as options, instead of strings

### ISSUE THREAD

**Issue by irinaColgiu** [irods/irods#2390]
Hi,

I think this is a bug: I am trying to add an AVU for temperature - let's say, where the value is negative, but it seems that the minus is interpreted as an option, rather than as a string together with whatever follows:

```
$ imeta add -d test.txt degrees -3
imeta: invalid option -- '3'
ERROR: parseCmdLineOpt: Option -3 not supported status = -318000 USER_INPUT_OPTION_ERR
Use -h for help.

$ imeta add -d test.txt degrees "-3"
imeta: invalid option -- '3'
ERROR: parseCmdLineOpt: Option -3 not supported status = -318000 USER_INPUT_OPTION_ERR
Use -h for help.

$ imeta add -d test.txt degrees +3
$ imeta ls -d test.txt
AVUs defined for dataObj test.txt:
attribute: degrees
value: +3
units: 
```

I am running version 3.3 - I am not sure if this has been fixed in the following versions.

Cheers,
Irina

**Comment by trel** [comment]
closing this issue - migrating to https://github.com/irods/irods_client_icommands/issues/20
