### ISSUE TITLE
remove storageadmin role

### ISSUE THREAD

**Issue by trel** [irods/irods#2400]
As found by Albert Heyrovsky:

> Nov  3 13:41:10 pid:13108 NOTICE: rsApiHandler: User has no permission for apiNumber 702

Setting up a resource server using 'storageadmin' role, rather than a 'rodsadmin' role, generates this message in the iCAT server log as the resource server cannot call rsGenQuery on the iCAT server when trying to register a file into the iCAT (among other operations).

**Comment by jasoncoposky** [comment]
include removing rodscurators and domainadmin as they were never implemented.

**Comment by jasoncoposky** [comment]
this needs to be removed from the database on an upgrade
