### ISSUE TITLE
Incorrect 'irodsCwd' results in wrong behavior

### ISSUE THREAD

**Issue by AndreyNevolin** [irods/irods#2405]
Hi,

Please try the following experiment:
1. Open `.irodsEnv`
2. Change `irodsCwd` to something like `/exist_1/exist_2/exist_3/not_exist`, where collections `exist_x` are registered with iRODS and `not_exist` is a non-existing collection
3. `iput` some_file

The last command will be successful! But... the result will be unexpected. `some_file` will be transferred to a storage device and will be registered with iRODS but under a different name:
`/exist_1/exist_2/exist_3/not_exist` (yes, `some_file` has now the name `not_exist`).

Suppose, that should be fixed. `.irodsEnv` is available for editing, hence its content should be verified. Perfect users don't exist and mistypes are always possible :)

**Comment by jasoncoposky** [comment]
This is fixed in master:
```
irods@avogadro:~$ ipwd
/tempZone/home/rods/nopes
irods@avogadro:~$ iput VERSION.json foo
ERROR: putUtil: put error for /tempZone/home/rods/nopes/foo, status = -814000 status = -814000 CAT_UNKNOWN_COLLECTION
Level 0: collection '/tempZone/home/rods/nopes' is unknown

```
