### ISSUE TITLE
Request to make releases available via apt-repositories

### ISSUE THREAD

**Issue by daikema** [irods/irods#2422]
At present [the install documentation](ftp://ftp.renci.org/pub/irods/releases/4.0.3/irods-manual-4.0.3.pdf) lists the following commands to be run to install the iCAT server:

``` shell
$ (sudo) dpkg -i irods-icat-4.0.3-64bit.deb irods-database-plugin-postgres-1.3.deb
$ (sudo) apt-get -f install
```

That second command is required due to dpkg not installing required dependencies and thus the original installation failing to complete.  If iRODS was instead released via an apt repository, in the case of the Debian-based install outlined in the manual, then this second step would not be required as the dependencies would then be automatically managed.

To release in the form of an apt repository also doesn't appear to be particularly complicated.  I was able  [to setup a local repository](https://help.ubuntu.com/community/Repositories/Personal) to use when 
while beginning work on a means of installing iRODS locally via [Puppet](http://puppetlabs.com/).

There are also [available instructions for making a more general purpose APT repository](https://wiki.debian.org/SettingUpSignedAptRepositoryWithReprepro) for setting up a more-general purpose repository.  This would have the further benefit of enabling more secure package distribution as repropro can handle automatic package signing, and by releasing the corresponding public key over HTTPS on the main iRODS website that packages haven't been corrupted could be confirmed.

As previously mentioned, the documentation could then be updated and simplified.  Setup instructions for an iRODS install could then become something like the following:

``` shell
$ wget -O - https://www.irods.org/path-to-signing.key | sudo apt-key add -
$ sudo wget -O /etc/apt/sources.list.d/irods.list https://www.irods.org/somepath/irods.list
$ sudo apt-get update
$ sudo apt-get install irods-icat irods-database-plugin-postgres # or some other set of irods packages
```

**Comment by trel** [comment]
This is being handled via https://packages.irods.org now (we currently only have the new irods-externals packages hosted there).   Please let us know if it works as expected.  Thanks.

**Comment by daikema** [comment]
I seem to be able to use the package mentioned there to setup the repo (which I'd discovered separately a few days back when I don't think it had been working).  I was able to install one of the new irods-externals packages although, without packages for iRODS itself there, it's not yet ready to fully install a node from.

**Comment by trel** [comment]
Excellent - external confirmation that the system is working is useful.

You are correct about the full installation not being available yet.

The iRODS packages themselves are not ready to be hosted there (we're still a few issues away, [see the 4.2.0 milestone](https://github.com/irods/irods/milestones/4.2.0)) - we will release 4.2.0 packages from that repository.

**Comment by daikema** [comment]
Good to see progress being made.  I'd discovered packages.irods.org a couple of days back but IIRC then there were still a few issues with the format. ... seems to be working now though.

Any possibility of getting, e.g., iRODS 4.1.8 packages added to the repo to allow for broader tests or would that break whatever mechanism you've got for populating your repository?  (Coincidentally - AKA my self-serving underlying reason :) - I could then get rid of the hack I've got in my puppet script which automate-creates a local iRODS repo to install from).

**Comment by trel** [comment]
Probably not.   We're most interested in having a clean slate moving forward.

4.2.0 is a major refactoring of the compiler and build system, the packages (single server, no more icat vs resource), the underlying architecture, and the source files themselves.  We don't want to have an `apt` or `yum` update to surprise any users if they weren't ready for this upgrade.

**Comment by daikema** [comment]
Fair enough.  If you've got a prerelease build you want to put in the repo and have someone test let me know. 

(BTW, at the moment as far as the configuration of iRODS goes, should I expect that to change much with iRODS 4.2 - or just the packaging?  Do you have any have stuff now available for non-interactively setting up iRODS or creating iRODS cached password files or would I need to create something using pseudo-terminals to interact with what's currently there?).

**Comment by trel** [comment]
Yes, the configuration system is largely still the same (JSON files), but all of the scripts and control points have been refactored to use Python only.  You can follow the XBB-2 branch (and soon the master branch itself) if you want to see what is happening before the documentation catches up.

There is a planned feature for giving the setup script a json file to populate a new installation (#2790).

**Comment by trel** [comment]
Everything is ready - closing this as the release of 4.2.0 is imminent.
