### ISSUE TITLE
Is it possible to query for all the data objects that DO NOT have a specific AVU at all?

### ISSUE THREAD

**Issue by irinaColgiu** [irods/irods#2437]
Hi,

I was wondering if it is possible to query for all the data objects that DO NOT have a specific AVU at all? 
For example I've got a bunch of files that have an avu like:

```
attribute: alignment_filter
value: phix
units: 
```

and other files that don't have this AVU at all. What I need to do is to select all the data objects that don't have this AVU at all defined. Synonym to an "exists" operator on the AVUs...
Is this possible?

Cheers,
Irina

**Comment by trel** [comment]
This question is asked and answered.  No further work to be done - closing the issue.

**Comment by othmar-weber** [comment]
@trel Is the status still the same? Can a predefined queries also be used in an iRODS rule?

**Comment by trel** [comment]
They cannot.  They are available via client libraries and `iquest --sql`.

I've opened a new issue to capture rule language availability https://github.com/irods/irods/issues/3616

**Comment by othmar-weber** [comment]
Doing some tests I found that the above select has in issue with duplicate file names. This can be fixed referencing the IDs instead:
```
select coll_name, data_name from r_data_main as d1 join r_coll_main as c on d1.coll_id = c.coll_id where not exists (select 1 from r_data_main as d2 join r_objt_metamap on d2.data_id = r_objt_metamap.object_id join r_meta_main on r_meta_main.meta_id = r_objt_metamap.meta_id where meta_attr_name = ? and meta_attr_value = ? and d1.data_id = d2.data_id);
```
With restriction to a certain directory:
```
select coll_name, data_name from r_data_main as d1 join r_coll_main as c on d1.coll_id = c.coll_id where c.coll_name like ? and not exists (select 1 from r_data_main as d2 join r_objt_metamap on d2.data_id = r_objt_metamap.object_id join r_meta_main on r_meta_main.meta_id = r_objt_metamap.meta_id where meta_attr_name = ? and meta_attr_value = ? and d1.data_id = d2.data_id);
```

**Comment by trel** [comment]
very nice.   thanks.
