### ISSUE TITLE
Add optional clean up of partial files from failed upload

### ISSUE THREAD

**Issue by jasoncoposky** [irods/irods#2444]
add option to server_config.json which by default would be off

**Comment by jasoncoposky** [comment]
This requires further discussion:

1. Does this include the transfer of large files?  They are registered into the catalog before data transfer happens, which means they would need be removed from the catalog.  This instance also breaks the ability for restarts.

2.  For single buffer puts ( small files ), registration does not happen until after the file is written to disk which may be the primary use case: failure to register.

**Comment by trel** [comment]
being handled via https://github.com/DICE-UNC/chunky
