### ISSUE TITLE
Usernames with the @

### ISSUE THREAD

**Issue by fconagy** [irods/irods#2445]
Hello,

When I try to create a user with the `@` (at sign) in the username string I got:
```
-bash-4.1$ iadmin mkuser abcd@domain rodsuser
ERROR: rcGeneralAdmin failed with error -130000 SYS_INVALID_INPUT_PARAM
Level 0: DEBUG: execMicroService3: error when executing microservice
line 22, col 2, rule base core
   msiCreateUser  :::  msiRollback;
   ^
```
The same error is shown in the server log.
Tried with many random strings with the `@` so it seems to be consistent. I also notice the same problem with one or two character userids, i.e. a, aa, bb and the like.

This is on 4.0.3. I don't seem to have the same problem with older versions.

Janos

**Comment by trel** [comment]
The database plugins have been released as 1.4.  However, they do not incorporate the username updates from this ticket.  The code that handles the username policy is not only in the database plugin code (yet) (it still lives in the main Agent).  Therefore, it will first be released in 4.1.0 - aiming for spring/summer 2015.
