### ISSUE TITLE
Move of collection to another coll under the same parent results in -833000

### ISSUE THREAD

**Issue by michael-conway** [irods/irods#2448]
this was reported under jargon as

https://github.com/DICE-UNC/jargon/issues/63

And (see the tests in the final few comments) it appears to originate in iRODS.  Have a unit test that replicates per the user report.

**Comment by trel** [comment]
Cannot reproduce the error at this time.

The new test ( in 0b017da ) should duplicate the jargon test ( from https://github.com/DICE-UNC/jargon/commit/b992aa81dc31b1beff6ce4014161b79ee2e36a2b ).

But it passes here.

**Comment by kellerb** [comment]
Commented on original Jargon issue.
