### ISSUE TITLE
propagating checksums under replication resources

### ISSUE THREAD

**Issue by trel** [irods/irods#2451]
From [Jorma on irod-chat](https://groups.google.com/forum/#!topic/irod-chat/mXNTKJTunSM):

> What is the proper way to calculate checksum for replicated files in a rule in irods4 when using a hierarchical resource type that replicates a file automatically?

> I have two servers, icat server and resource server and the resource setup is:
```
[irods@irods5-test ~]$ ilsresc --tree
rrepl:replication
├── rr1
└── rr2
```

> If only `acPostProcForPut` contains `msiSysChksumDataObj` then only one replica of the file has a checksum:

> ```
[irods@irods7-test ~]$ ils -L
/ida/home/rods/rc-no:
  rods              0 rrepl;rr2         1024 2014-12-19.14:42 & iput-icat-host
    sha2:X3C/GKCGAHAW6UiwSu07ghA6Nr6kF1W2zd+vEKzjxu8=    rrepl    generic    /irods/rr2/home/rods/rc-no/iput-icat-host
  rods              1 rrepl;rr1         1024 2014-12-19.14:42 & iput-icat-host
        rrepl    generic    /irods/rr1/home/rods/rc-no/iput-icat-host
```

> If both acPostProcForPut and acPostProcForRepl contain msiSysChksumDataObj (both servers) then it almost works like I expected. If the `iput` is done to the server that runs icat then both replicas have checksum:

> ```
  rods              0 rrepl;rr2         1024 2014-12-19.14:37 & iput-icat-host
    sha2:X3C/GKCGAHAW6UiwSu07ghA6Nr6kF1W2zd+vEKzjxu8=    rrepl    generic    /irods/rr2/home/rods/rc-yes/iput-icat-host
  rods              1 rrepl;rr1         1024 2014-12-19.14:37 & iput-icat-host
    sha2:X3C/GKCGAHAW6UiwSu07ghA6Nr6kF1W2zd+vEKzjxu8=    rrepl    generic    /irods/rr1/home/rods/rc-yes/iput-icat-host
```

> but if the `iput` is done to the resource server then there is only one checksum:

> ```
  rods              0 rrepl;rr1         1024 2014-12-19.14:39 & iput-resc-host
    sha2:X3C/GKCGAHAW6UiwSu07ghA6Nr6kF1W2zd+vEKzjxu8=    rrepl    generic    /irods/rr1/home/rods/rc-yes/iput-resc-host
  rods              1 rrepl;rr2         1024 2014-12-19.14:39 & iput-resc-host
        rrepl    generic    /irods/rr2/home/rods/rc-yes/iput-resc-host
```

**Comment by trel** [comment]
write a test first - this may already be fixed.

**Comment by jasoncoposky** [comment]
This has been fixed in master.

In bench testing, i have added msiSysChksumDataObj to both acPostProcForPut & acPostProcForRepl on an iCAT server and a Resource server.  In a two child replication hierarchy with a child on each server i have done a put from each server and each data object has a checksum for both replicas.
