### ISSUE TITLE
Use newer version of OpenSSL

### ISSUE THREAD

**Issue by kellerb** [irods/irods#2456]
Currently link against libssl0.9.8, for CentOS 5 compatiblity. Need to find newest library version that is available on all supported platforms.

**Comment by trel** [comment]
Ubuntu 12 and 14 - confirmed `libssl1.0.0`
Debian - confirmed `libssl1.0.0`
CentOS6 and CentOS7 - confirmed `openssl`
Suse12 and Suse13 - confirmed `libopenssl1_0_0`

**Comment by trel** [comment]
Awaiting a bit more testing, but should land soon.

**Comment by trel** [comment]
closing this for now - everything appears to be working.
