### ISSUE TITLE
Allow only TLS 1.1 and 1.2

### ISSUE THREAD

**Issue by kellerb** [irods/irods#2457]
This will break SSL federation with 4.0.3 until an updated 4.0.3 SSL plugin is released.

* Ubuntu 12 stock OpenSSL does not support TLSv1.2
* OpenSSL 0.9.8 (used in 4.0.3) does not support TLSv1.1 or 1.2 [link](https://www.suse.com/communities/conversations/tls-1-2/)

Examine wire contents to insure that the correct version of TLS is being used.

Based on information from: https://trac.torproject.org/projects/tor/ticket/11598

**Comment by trel** [comment]
awaiting federation tests
