### ISSUE TITLE
irsync behavior - always syncs every file every time

### ISSUE THREAD

**Issue by michael-conway** [irods/irods#2467]
Per Jon Crabtree, iRODS 4.0.3 on mumble Linux.

He is doing an `irsync -r -K` between DataVerse (local) and iRODS and sees every file sync'ed every time, even old files with no changes.

We sat together and did an `irsync -l` and it indeed presented all the old files for resync.

We can mine logs, etc., as needed.

**Comment by jasoncoposky** [comment]
you need to use the -K (capital) for comparison and -k(lowercase) to keep the checksum in the database.  try -Kk.

**Comment by michael-conway** [comment]
cool.  Passed that on to Jon.

OK(K)

Mike

**Comment by trel** [comment]
probably related to #2424

**Comment by trel** [comment]
Can you please check this again on the master branch?  We think this is behaving as expected now.
/cc @akio-sone

**Comment by trel** [comment]
awaiting test
