### ISSUE TITLE
Adding a non-existent resource as a child to an existing resource gives a misleading error

### ISSUE THREAD

**Issue by tempoz** [irods/irods#2468]
`iadmin addchildtoresc existing_parent non_existent_resource`
yields:
`Level 0: db_add_child_resc_op - Resource 'non_existent_resource' already has a parent.`

**Comment by trel** [comment]
I think the first error message is still wrong - requesting more eyes please.

Also, we need a test to make sure this doesn't regress later.

**Comment by tempoz** [comment]
482dd27 fixes the error message.
