### ISSUE TITLE
expose global JSON object within the rule engine

### ISSUE THREAD

**Issue by trel** [irods/irods#2470]
- would like to use the dot syntax for access
- will contain the new Avro generated data structures for every dynamic PEP as JSON objects

**Comment by korydraughn** [comment]
Avro is not used for anything in the server now that #7988 has been merged.

@trel Is this related to #5955?

**Comment by trel** [comment]
it could be related... but I honestly don't remember.

this was from the time when we first made dollar variables and runtime variables available in dot notation to the rule engine? and we were envisioning some kind of unified data structure...

we can probably close this if we cannot decode my early 2015 meaning any better...

**Comment by korydraughn** [comment]
Ok. Closing.
