### ISSUE TITLE
Pluggable API table and C clients in 4.x

### ISSUE THREAD

**Issue by keithj** [irods/irods#2478]
I'm in the process of building baton against 4.x (4.0.3 and master). I notice that the some (all?) of the official clients now do this:

````
   // initialize pluggable api table
   irods::api_entry_table&  api_tbl = irods::get_client_api_table();
   irods::pack_entry_table& pk_tbl  = irods::get_pack_table();
   init_api_table( api_tbl, pk_tbl );
````

There is no version of these methods with C linkage. What are the consequences for C clients of
not calling this?

Thanks.

**Comment by jasoncoposky** [comment]
this is the method used to initialize the client side api plugin table.  it is statically linked with the expected rc versions of the apis and then dynamically populated from the plugins/api directory on the client side.  we do not call this in our port of baton as baton does not yet call out to any of the api plugins.

**Comment by keithj** [comment]
Thanks, that's very helpful. I was unsure because in some of the official clients I could not see any plugins being used, yet the table was being initialised.
