### ISSUE TITLE
build.sh does not pre-check dependency perl-json

### ISSUE THREAD

**Issue by btwe** [irods/irods#2490]
I have a fresh debian 7.8 netinst with minimal amount of packages. I just fixed the dependency issues which the build script was complaining about.

During the build.sh run a missing dependency to perl-json stopped the process.

**Comment by trel** [comment]
Thanks!

This package is newly required - and it's named differently for Ubuntu, `libjson-perl`.

Will work to make sure this is consistent across different operating systems before release.

**Comment by btwe** [comment]
@trel wait. I misnamed the package.
I also installed `apt-get install libjson-perl`

Sorry for the confusion.  But anyways, the pre-check wasn't made for this.

**Comment by trel** [comment]
Excellent.

On CentOS6 it is `perl-JSON`.

**Comment by trel** [comment]
This should behave as expected.  Re-open if necessary.
