### ISSUE TITLE
4.0.3 client libraries print a debug message to STDOUT

### ISSUE THREAD

**Issue by keithj** [irods/irods#2492]
I have built client programs against 4.0.3. These are Unix filter style programs that print JSON to STDOUT. In addition to the expected JSON, I am seeing the following, also on STDOUT, making the whole invalid to downstream JSON parsers.

````
cliReconnManager: while !exit flg
````

There seem to be some debug printing statements left in rcConnect.hpp. The above is the only one I see (it happens every time). However, there are others that I haven't triggered yet. Please could the libraries only log and not print to STDOUT (or even STDERR).

**Comment by jasoncoposky** [comment]
this message has been removed from 4.1.

there is no client-side log, but we could redirect the output to stderr if that would help.

**Comment by keithj** [comment]
For writing client applications, I think it's reasonable to make the client responsible for logging in
whichever way it chooses. I think it's best for the library code to avoid writing to STDERR also. The
client might be doing something specific with it. I'd prefer that information about bad things
happening arrive through error conditions and that the client then has the choice of how it
presents these to the user.

**Comment by trel** [comment]
new facility in rodsLog which takes `rError_t` - and then redirect output to `rError_t` when the process type is `CLIENT_PT`

**Comment by jasoncoposky** [comment]
closing, any further errant client messages can be cleaned up in a future issue.
