### ISSUE TITLE
Policy on locating libirods_client for 4.x client programs

### ISSUE THREAD

**Issue by keithj** [irods/irods#2494]
Hi,

What is best practice on 4.x for managing how client programs locate the shared libraries (libirods_client.so and libirods_client_api.so) at runtime? On Ubuntu the naming and location of these is different from most packages.

Thanks.

**Comment by trel** [comment]
The locations of libraries and files installed from packages are always up for discussion as we continue to move to a compete system for binary installations - if you have suggestions and/or best practices, please share.  We want to place things in the most expected/normal locations for every platform.

**Comment by keithj** [comment]
In the current .deb release , the client libraries are in ````/usr/lib/irods````, which is not picked up by ldconfig. Therefore clients have to be built by hard coding the library path or users must set LD_LIBRARY_PATH at runtime. Both of these options have their detractors.

I can understand why /usr/lib/irods is not in /etc/ld.so.conf - there are other libraries in there that could clash with things installed as packages in /usr/lib. According to the Debian/Ubuntu manuals for packaging shared libraries it is more usual for libraries to be linked be in /usr/lib (with approriate SONAME etc) so that they are picked up by ldconfig (which should be run automatically when the package is installed) and for the packages-specific subdirectory of /usr/lib to contain files not to be interacted with manually by users.

**Comment by kellerb** [comment]
As part of another issue: https://github.com/irods/irods/issues/2332, the `irods-runtime` package now creates the file `/etc/ld.so.conf.d/irods.conf`, which adds `/usr/lib/irods` to the list of directories searched for libraries.

Based on what @keithj is saying, we may want to move the iRODS-proper libraries (e.g. `libirods_client_api.so`, `libirods_client.so`) to `/usr/lib` and use `/usr/lib/irods` for the external libraries that are included for convenience (e.g. `libjansson.so`).

We may also want to consider putting the plugin libraries in `/usr/lib/irods/plugins..`.

Also, we may want to adopt the ["real name" "soname" "linker name"](http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html) naming scheme.

**Comment by keithj** [comment]
The problem of ````/usr/lib/irods```` being added to the search path has just bitten me. The iRODS packages (built from master) have installed an old version of ````libcheck```` which causes the build of baton I'm testing against iRODS to fail because it uses a newer verion of ````libcheck````. I have the newer version installed in ````/usr/local```` which being superseded by the iRODS one.

**Comment by kellerb** [comment]
`/etc/ld.so.conf.d/irods.conf` is no longer installed, so `/usr/lib/irods` should no longer be in the DSO search path.

The iRODS DSO's (`libirods_client.so`, `libirods_client_api.so`, `libirods_server.so`) are now being installed to `/usr/lib`, so client programs should be able to access them normally.

[This DSO naming convention](http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html) is now being followed by the iRODS DSO's. The version numbers have all started at `1.0.0`.

`DT_SONAME` of the iRODS DSO's is now set, as part of using the above naming convention.

The iRODS Consortium plugins have not been updated with the new DSO locations yet. Trying to build them against `master` will probably fail.

Please (anyone reading this) voice any comments, suggestions, thoughts, concerns, etc. We want to make our packages as textbook as possible for the next release.
