### ISSUE TITLE
Request to keep -p for packaging

### ISSUE THREAD

**Issue by btwe** [irods/irods#2496]
Please keep the portability flag `-p` for the build.sh

I really appreciate the way to install a daemon into a dedicated directory.

**Comment by trel** [comment]
The portability flag had been added for internal and experimental use.  Since it was complicating the build process we removed it earlier this week.

Can you write a bit more about the use case where it would be helpful to you?

Thanks.

**Comment by btwe** [comment]
@trel I prefer using this approach when installing any packages/tools/daemons which do not originate from the main repository of the os distribution.
I like to clone the source distribution and usually configure it with --prefix.

- Still, there are dependencies to the os most of the time, but these can be solved like it is done for irods, too.
- Troubles like the one I face right now with not-updated build procedures of .deb packages ca be avoided.
- But, what I like most is that multiple versions of the same daemon can be installed next to each other
  - no overwriting of configs/libs/binaries happen on installation of a new version 
  - and falling back to an older version is immediately possible, when detecting an issue on the latest installed version

**Comment by trel** [comment]
We will now support a `--run-in-place` option for targeting custom installations and testing.
