### ISSUE TITLE
Installing failure caused by MySQL ODBC: [unixODBC][Driver Manager]Can't open lib '/usr/lib64/libmyodbc5w.so

### ISSUE THREAD

**Issue by klin938** [irods/irods#2506]
Hi guys,

I am having issue with the installation which uses remote MySQL server. I have fixed the first installation issue which is described in here:

https://github.com/irods/irods/issues/2318

Then I was given another error:

```
 ===================================================================
Updating irods.config...


Stopping iRODS server...
Found 0 processes:
        There are no iRODS servers running.

-----------------------------
Running irods_setup.pl...

Step 1 of 5:  Configuring database user...
    Skipped.  For MySQL, database configured by DBA.

Step 2 of 5:  Creating database and tables...
    CreateDatabase Skipped.  For MySQL, DBA creates the instance.
    Updating the .odbc.ini...
    Creating iCAT tables...
        Inserting iCAT tables...

Step 3 of 5:  Configuring database security...
    Configuring security...
        Skipped.  MySQL database security configured by DBA.
    Testing database communications...

Configuration problem:
    Communications with the database failed.
        ERROR: cllConnect: SQLConnect failed: -1
        ERROR: cllConnect: SQLConnect failed:odbcEntry=mysql,user=nobita,pass=XXXXX
        ERROR: cllConnect:          SQLSTATE: 01000
        ERROR: cllConnect:  Native Error Code: 0
        ERROR: cllConnect: [unixODBC][Driver Manager]Can't open lib '/usr/lib64/libmyodbc5w.so /usr/lib64/libmyodbc5a.so' : file not found
        userName=nobita
        password=XXXXX
        cllConnect failed with error -1.
Found 0 processes:
        There are no iRODS servers running.
```

However, I checked the database via ODBC, and tables are created successfully and my ODBC works fine:

```
#:~$ isql dsnicat1
+---------------------------------------+
| Connected!                            |
|                                       |
| sql-statement                         |
| help [tablename]                      |
| quit                                  |
|                                       |
+---------------------------------------+
SQL> show tables;
+-----------------------------------------------------------------+
| Tables_in_icat                                                  |
+-----------------------------------------------------------------+
| r_coll_main                                                     |
| r_data_main                                                     |
| r_grid_configuration                                            |
| r_meta_main                                                     |
| r_microsrvc_main                                                |
| r_microsrvc_ver                                                 |
| r_objectid_seq_tbl                                              |
| r_objt_access                                                   |
| r_objt_audit                                                    |
| r_objt_deny_access                                              |
| r_objt_filesystem_meta                                          |
| r_objt_metamap                                                  |
| r_quota_main                                                    |
| r_quota_usage                                                   |
| r_resc_group                                                    |
| r_resc_main                                                     |
| r_rule_base_map                                                 |
| r_rule_dvm                                                      |
| r_rule_dvm_map                                                  |
| r_rule_exec                                                     |
| r_rule_fnm                                                      |
| r_rule_fnm_map                                                  |
| r_rule_main                                                     |
| r_server_load                                                   |
| r_server_load_digest                                            |
| r_specific_query                                                |
| r_ticket_allowed_groups                                         |
| r_ticket_allowed_hosts                                          |
| r_ticket_allowed_users                                          |
| r_ticket_main                                                   |
| r_tokn_main                                                     |
| r_user_auth                                                     |
| r_user_group                                                    |
| r_user_main                                                     |
| r_user_password                                                 |
| r_user_session_key                                              |
| r_zone_main                                                     |
+-----------------------------------------------------------------+
SQLRowCount returns 37
37 rows fetched
SQL>
```

I am running CentOS 6.0 and using MySQL connector mysql-connector-odbc-5.3.4-1.el6.x86_64.rpm

Thanks
Derrick

**Comment by trel** [comment]
It appears that the driver entry in your `.odbc.ini` file has two files listed, rather than just one.

This probably means that the `./plugins/database/packaging/find_odbc_mysql.sh` script found more than one.

You can confirm by running the `find_odbc_mysql.sh` script directly.  If this is the case, you can either change the files that are on disk, or update the shell script to be more selective.

We'll try to reproduce this at RENCI.

**Comment by klin938** [comment]
Hi trel,

The .odbc.ini is empty or if there is another .odbc.ini in another location?

```
:~$ cat /var/lib/irods/.odbc.ini
:~$
```
The find_odbc_mysql.sh found two entries indeed, but the code does not rely on any odbc.ini files, it searches the file system directly.
```
:~$ sudo /var/lib/irods/packaging/find_odbc_mysql.sh
/usr/lib64/libmyodbc5w.so /usr/lib64/libmyodbc5a.so
```
I will hack around find_odbc_mysql.sh and see if it helps...

cheers

**Comment by klin938** [comment]
Okay, I updated the shell script to be:
```
# Fallthrough
if [ "$ODBC" == "" ]; then
    ODBC=`find /usr -name "libmyodbc*.so" 2> /dev/null | head -1`
fi
```
SO when falling through using wildcard, it makes sense to just pick one of the results. In my case I just pick the first one. Then my installation went a bit further.

**Comment by trel** [comment]
Good - yes, this script is not as robust as it needs to be - if you have general improvements, we'll gladly look them over.  The MySQL path is not as well worn as the PostgreSQL path.

**Comment by klin938** [comment]
Thanks Trel, my installation seems to go until the very end but it threw another error:
```
Done.  Additional detailed information is in the log file:
    /var/lib/irods/iRODS/installLogs/irods_setup.log
 
-----------------------------
Running update_catalog_schema.py...
Traceback (most recent call last):
  File "./packaging/update_catalog_schema.py", line 221, in <module>
    main()
  File "./packaging/update_catalog_schema.py", line 216, in main
    update_database_to_latest_version()
  File "./packaging/update_catalog_schema.py", line 161, in update_database_to_latest_version
    current_schema_version = get_current_schema_version(cfg)
  File "./packaging/update_catalog_schema.py", line 16, in get_current_schema_version
    and option_name='schema_version';")
  File "/var/lib/irods/packaging/server_config.py", line 211, in exec_sql_cmd
    return self.exec_mysql_cmd(sql)
  File "/var/lib/irods/packaging/server_config.py", line 117, in exec_mysql_cmd
    (returncode, myout, myerr) = self.exec_mysql_file(sqlfile)
  File "/var/lib/irods/packaging/server_config.py", line 138, in exec_mysql_file
    db_host = self.values['Server']
KeyError: 'Server'
```
No obvious errors from the installation log:
```

Creating iRODS group 'public'...

Creating iRODS user account...

Setting iRODS directory ownership...
    chown /
    chown /GarvanZone...
    chown /GarvanZone/home...
    chown /GarvanZone/trash...
    chown /GarvanZone/trash/home...

Setting iRODS user password...

Checking for iRODS boot user...

Removing iRODS boot user...

Stopping iRODS server...

Configuring iRODS user and starting server...
------------------------------------------------------------------------
Sat Feb  7 10:37:29 2015

Updating iRODS user's ~/.irods/.irodsEnv...

Starting iRODS server...

Opening iRODS connection...

Creating default resource...
    ... Success [demoResc] [/var/lib/irods/iRODS/Vault]

Testing resource...

Done.
Sat Feb  7 10:37:34 2015
```
and no errors from reLogs and rodsLogs either....

**Comment by kellerb** [comment]
Can you show us the contents of `/var/lib/irods/.odbc.ini`

**Comment by klin938** [comment]
Well, it's a empty file still...
```
:~$ cat /var/lib/irods/.odbc.ini
:~$
```

**Comment by klin938** [comment]
After more tries, here is what I found, during Step 2 of the installation, it generates/updates a .odbc.ini under the service user home dir such as /home/pwbcapp/.odbc.ini
```
Step 2 of 5:  Creating database and tables...
    CreateDatabase Skipped.  For MySQL, DBA creates the instance.
    Updating the .odbc.ini...
    Creating iCAT tables...
        Skipped.  Tables already created.
```
But at the very last stage when executing update_catalog_schema.py, it tries to access the info from /var/lib/irods/.odbc.ini which is empty.

I simply copied the .odbc.ini across, the error didn't happen anymore.

Will be nice to know if I have missed something such as env variable????

**Comment by jasoncoposky** [comment]
if a .odbc.ini file exisits another will not be written.  this is an artifact of the multiple runs of the installer.  if you remove the empty file another would be written by the installer with the expected paramters.


-
Jason Coposky
Chief Technologist, iRODS Consortium
RENCI at the University of North Carolina at Chapel Hill
(919)445-9<tel:(919)445-0632>675
jasonc@renci.org<mailto:danb@renci.org>

irods.org<http://irods.org/> - Take Control of Your Data




On Feb 6, 2015, at 8:20 PM, klin938 <notifications@github.com<mailto:notifications@github.com>> wrote:


After more tries, here is what I found, during Step 2 of the installation, it generates/updates a .odbc.ini under the service user home dir such as /home/pwbcapp/.odbc.ini

Step 2 of 5:  Creating database and tables...
    CreateDatabase Skipped.  For MySQL, DBA creates the instance.
    Updating the .odbc.ini...
    Creating iCAT tables...
        Skipped.  Tables already created.


But at the very last stage when executing update_catalog_schema.py, it tries to access the info from /var/lib/irods/.odbc.ini which is empty.

I simply copied the .odbc.ini across, the error didn't happen anymore.

Will be nice to know if I have missed something such as env variable????

-

**Comment by kellerb** [comment]
Both the creation of the empty `.odbc.ini` file and the reading of the incorrect `.odbc.ini` file (looking in `/var/lib/irods/` instead of `~/`) are bugs in the iRODS 4.0.3 package (#2378). They have been fixed in the master branch.

You can either overwrite the empty `/var/lib/irods/.odbc.ini` file with the `~/.odbc.ini` file, or you can delete the empty file completely (leaving the populated one in `~/`). Once you have done this, run `update_catalog_schema.py` directly.

Please let us know if you have any more trouble, and feel free to close this issue once everything is working.
