### ISSUE TITLE
[unixODBC][Driver Manager] error with psqlodbs.so

### ISSUE THREAD

**Issue by childers** [irods/irods#2508]
I was attempting to run `./plugins/database/packaging/setup_irods_database.sh` on a built-in-place instance of 4-0-stable and the process fails on step 3 of 5:
```bash
Step 3 of 5:  Configuring database security...
    Configuring security...
        Skipped.  Existing Postgres configured by DBA.
    Testing database communications...

Configuration problem:
    Communications with the database failed.
        ERROR: cllConnect: SQLConnect failed: -1
        ERROR: cllConnect: SQLConnect failed:odbcEntry=postgres,user=irods,pass=XXXXX
        ERROR: cllConnect:          SQLSTATE: 01000
        ERROR: cllConnect:  Native Error Code: 0
        ERROR: cllConnect: [unixODBC][Driver Manager]Can't open lib '/usr/pgsql-9.3/lib/psqlodbc.so /usr/lib64/psqlodbc.so' : file not found 
        userName=irods
        password=XXXXX
        cllConnect failed with error -1.
Found 0 processes:
        There are no iRODS servers running.
Abort.
```
The error shows the odbc files are present and I can see that they are there, and ```./find_odbc_postgres.sh``` returns results;
```bash
$ ./find_odbc_postgres.sh
/usr/pgsql-9.3/lib/psqlodbc.so /usr/lib64/psqlodbc.so
```
Is this behavior cause by the fact that there are two psqlodbc.so files found?  

Thanks,

**Comment by trel** [comment]
Yes, this is due only to the fact that there are two .so files found.

If you can rename or remove one of them, the other will get picked up and installation should get a bit further.

**Comment by childers** [comment]
Thanks, that was it! and as you predicted, it failed right after that.  I'll keep working on it, thanks for the help!
