### ISSUE TITLE
unable to build icommands on Mac OS X 10.9.5

### ISSUE THREAD

**Issue by jerry57** [irods/irods#2509]
iplants-MacBook-Pro:iRODS jerry$ ./packaging/build.sh icommands

+------------------------------------+
| RENCI iRODS Build Script           |
+------------------------------------+
Mon Feb  9 08:25:02 MST 2015

Detecting Build Environment
Detected Packaging Directory [/Users/jerry/iRODS/packaging]
Build Directory set to [/Users/jerry/iRODS]
Detected iRODS Version to Build [4.1.0]
Detected iRODS Version Integer [401000]
Detected OS [MacOSX]
Detected OS Version [10.9.5]
Detected curl [/usr/bin/curl] v[7.30.0]
Detected wget [/usr/local/bin/wget] v[1.12]
Detected help2man [/usr/local/bin/help2man] v[1.46.5]
#######################################################
ERROR :: build.sh requires some software to be installed

      :: download from: http://sourceforge.net/projects/fuse/files/fuse-2.X/      :: download from: http://curl.haxx.se/download.html      :: download from: http://www.bzip.org/downloads.html      :: download from: http://zlib.net/      :: download from: http://sourceforge.net/projects/openpam/files/openpam/      :: download from: http://www.openssl.org/source/      :: download from: http://www.xmlsoft.org/downloads.html      :: download from: http://web.mit.edu/kerberos/dist/index.html
#######################################################
iplants-MacBook-Pro:iRODS jerry$

**Comment by trel** [comment]
This was addressed in 4.1.x by using the `brew` tool to handle installation of `osxfuse`.

Since 10.10, Apple is limiting unsigned kernel extensions so we must use a binary installation of OSXFUSE.

**Comment by jerry57** [comment]
Is brew the only way to get the binary installed?  We have had problems with brew altering system applications and stopped using it.

**Comment by trel** [comment]
The OSXFUSE binary distribution comes from the website http://osxfuse.github.io (they have a signed kernel extension, so is allowed).

I think `brew` is the best package manager on the Mac right now.

Definitely would like to make sure this is all as well-behaved as possible.  I've just cherry-picked this commit back to 4-1-stable as well - so any feedback before we release would be greatly appreciated.

**Comment by jmarshall** [comment]
@jerry57 is only building the icommands, so the missing fuse is irrelevant.  So one solution is to use `-i` to ignore the irrelevant missing prerequisite:

    $ packaging/build.sh --run-in-place --ignore-prereqs icommands

(However this is currently ineffective on 10.10+ — see line note on 186da172e126c61d027f8deb1ecdbd4e3b1b2038.)

Ideally the build scripts would only check for fuse headers if it was actually building iRODS/clients/fuse, and similarly for the other prerequisites.  Hopefully this is something that can be considered as part of the transition to CMake..?  (`--ignore-prereqs` is a quick-and-nasty bandaid to allow building the parts that can be built, but more granular prerequisites would be a much better solution.)

**Comment by trel** [comment]
Until we separate the packaging and Makefiles out a bit more (slated for 4.2, alongside/with CMake), the `irodsFs` client is packaged and shipped with the iCommands.  Unfortunately, this means the `fuse.h` file is still necessary for the 4.1 family.
