### ISSUE TITLE
Where should the server's SSL environment variables be set?

### ISSUE THREAD

**Issue by klin938** [irods/irods#2515]
Hi guys,

I am trying to setup SSL to use PAM authentication, I am not sure where is the best place to do this:

> 20.3.3.6 Set SSL environment variables
> The server needs to read these variables on startup:
> irods@hostname:~/ $ irodsSSLCertificateChainFile=/var/lib/irods/iRODS/server/config/chain.pem`
> irods@hostname:~/ $ export irodsSSLCertificateChainFile
> irods@hostname:~/ $ irodsSSLCertificateKeyFile=/var/lib/irods/iRODS/server/config/server.key
> irods@hostname:~/ $ export irodsSSLCertificateKeyFile
> irods@hostname:~/ $ irodsSSLDHParamsFile=/var/lib/irods/iRODS/server/config/dhparams.pem
> irods@hostname:~/ $ export irodsSSLDHParamsFile

Currently I put these into `/etc/profile.d/irods.sh`, so it's global system variables. But it still does not work, I was given the `SSL_HANDSHAKE_ERROR` when tried to run `iinit` and the server log shows:
```
Feb 12 20:35:35 pid:3445 ERROR: sslAccept: error calling SSL_accept. SSL error: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
Feb 12 20:35:35 pid:3445 ERROR: sslAccept failed in agentMain with status -2103000
Feb 12 20:35:35 pid:3445 ERROR: [-]     iRODS/server/core/src/rsApiHandler.cpp:484:readAndProcClientMsg :  status [SYS_HEADER_READ_LEN_ERR]  errno []                                                          -- message []
        [-]     iRODS/lib/core/src/sockComm.cpp:195:readMsgHeader :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read head                                                         er']
                [-]     libtcp.cpp:240:tcp_read_msg_header :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [read 0 expected 4]
```
A post states that "no shared cipher" indicates something wrong in those SSL env variables.

I am using self-signed so I used `server.crt` as the chain file.

Thanks

**Comment by kellerb** [comment]
The first step is to confirm that the environment variables are making it into the server process. The following should print all of the server's environment variables to the screen:

``` bash
IRODS_PID=`ps ux | grep irodsServer | grep -v grep | awk '{print $2}'`; cat /proc/$IRODS_PID/environ | sed 's/\x00/\x0a/g'
```

---

As to the best place to put the environment variable definitions and exports, one option is in `/var/lib/irods/iRODS/irodsctl`, directly below the `IRODS_HOME=/var/lib/irods/iRODS` line. Make sure they are above the `$IRODS_HOME/scripts/runperl --dir $IRODS_HOME --script $IRODS_HOME/scripts/perl/irodsctl.pl $*` line.

**Comment by klin938** [comment]
Thanks kellerb, the variables set inside profile.d didn't make it to the process. So I took your advice and set them up in irodsctl, and confirmed they are set. But my iinit still failed, another error message seems related to my self-signed cert itself:
```
Feb 12 22:58:59 pid:3424 ERROR: sslAccept: error calling SSL_accept. SSL error: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
```
I just fellow the step in 4.0.3 manual.

Cheers,

**Comment by klin938** [comment]
Okay, I setup the SSL client settings inside ~/.irods/.irodsEnv but it gave above error. I exported them as variables then seems to be working:
```
~$ export irodsSSLCACertificateFile=/var/lib/irods/iRODS/server/config/server.crt
~$ export irodsSSLVerifyServer=cert
```

**Comment by kellerb** [comment]
That is expected; in 4.0.3 the SSL environment variables have to be set directly in the environment, not in `~/.irods/.irodsEnv`.

In the upcoming 4.1, you will be able to set them either in the environment, or in the new `~/.irods/irods_environment.json`.
