### ISSUE TITLE
PAM_AUTH_PASSWORD_FAILED when running iinit and PamAuthCheck does not run properly either

### ISSUE THREAD

**Issue by klin938** [irods/irods#2516]
Hi again,

After fixing database, SSL I am finally in the step of doing authentication. My group prefer to use LDAP via PAM. iRODS is install on a CentOS box which has had LDAP auth configured and working properly.

I have created a new irods user but didn't assign password. And in the new user's .irodsEnv, i enabled PAM auth as per documentation. When trying iinit, the client received:
```
:~$ iinit
Enter your current PAM password:[-]     libpam.cpp:244:pam_auth_client_request :  status [PAM_AUTH_PASSWORD_FAILED]  errno [] -- message [call to rcAuthRequest failed.]

 failed with error -993000 PAM_AUTH_PASSWORD_FAILED
```
and server log looks like:
```
Feb 13 00:01:39 pid:2465 NOTICE: Agent process 4050 started for puser=derlin and cuser=derlin from 192.168.1.251
Not Authenticated
Feb 13 00:01:49 pid:4050 ERROR: [-]     iRODS/server/api/src/rsAuthPluginRequest.cpp:85:rsAuthPluginRequest :  status [PAM_AUTH_PASSWORD_FAILED]  errno [] -- message []
        [-]     libpam.cpp:417:pam_auth_agent_request :  status [PAM_AUTH_PASSWORD_FAILED]  errno [] -- message [pam auth check failed]

Feb 13 00:01:49 pid:4050 ERROR: [-]     iRODS/server/core/src/rsApiHandler.cpp:484:readAndProcClientMsg :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message []
        [-]     iRODS/lib/core/src/sockComm.cpp:195:readMsgHeader :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']
                [-]     libtcp.cpp:240:tcp_read_msg_header :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [read 0 expected 4]
```
A old post suggest to debug with PamAuthCheck, I tried but the program didn't seem to work, it didn't ask for password. If I hit enter straight or I type my password in visible plain txt, it display "Not Authenticated":
```
$ /var/lib/irods/iRODS/server/bin/PamAuthCheck pwbcad
xxxxxxx
Not Authenticated
```
I also tried to find out more about the PAM settings in server.config, but couldn't find any info from icatHighLevelRoutines.cpp.

Cheers,

**Comment by jasoncoposky** [comment]
PamAuthCheck takes the password from stdin for security reasons, so you need to ingest it via the command line with the '<' operator:  PamAuthCheck username < password_in_a_file.txt.

-
Jason Coposky
Chief Technologist, iRODS Consortium
RENCI at the University of North Carolina at Chapel Hill
(919)445-9675
jasonc@renci.org<mailto:jasonc@renci.org>

irods.org<http://irods.org/> - Take Control of Your Data


On Feb 12, 2015, at 12:43 AM, klin938 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi again,

After fixing database, SSL I am finally in the step of doing authentication. My group prefer to use LDAP via PAM. iRODS is install on a CentOS box which has had LDAP auth configured and working properly.

I have created a new irods user but didn't assign password. And in the new user's .irodsEnv, i enabled PAM auth as per documentation. When trying iinit, the client received:

:~$ iinit
Enter your current PAM password:[-]     libpam.cpp:244:pam_auth_client_request :  status [PAM_AUTH_PASSWORD_FAILED]  errno [] -- message [call to rcAuthRequest failed.]

 failed with error -993000 PAM_AUTH_PASSWORD_FAILED


and server log looks like:

Feb 13 00:01:39 pid:2465 NOTICE: Agent process 4050 started for puser=derlin and cuser=derlin from 192.168.1.251
Not Authenticated
Feb 13 00:01:49 pid:4050 ERROR: [-]     iRODS/server/api/src/rsAuthPluginRequest.cpp:85:rsAuthPluginRequest :  status [PAM_AUTH_PASSWORD_FAILED]  errno [] -- message []
        [-]     libpam.cpp:417:pam_auth_agent_request :  status [PAM_AUTH_PASSWORD_FAILED]  errno [] -- message [pam auth check failed]

Feb 13 00:01:49 pid:4050 ERROR: [-]     iRODS/server/core/src/rsApiHandler.cpp:484:readAndProcClientMsg :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message []
        [-]     iRODS/lib/core/src/sockComm.cpp:195:readMsgHeader :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']
                [-]     libtcp.cpp:240:tcp_read_msg_header :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [read 0 expected 4]


A old post suggest to debug with PamAuthCheck, I tried but the program didn't seem to work, it didn't ask for password. If I hit enter straight or I type my password in visible plain txt, it display "Not Authenticated":

$ /var/lib/irods/iRODS/server/bin/PamAuthCheck pwbcad
xxxxxxx
Not Authenticated


I also tried to find out more about the PAM settings in server.config, but couldn't find any info from icatHighLevelRoutines.cpp.

Cheers,

-

**Comment by klin938** [comment]
Thanks! I will give it a try. I don't think /etc/pam.d/irods is covered in the manual, but I guess I will need to configure it like others under /etc/pam.d/

**Comment by kellerb** [comment]
You are correct that we should explain `/etc/pam.d/irods` in the manual. There is an open issue for that here: https://github.com/irods/irods/issues/2324.

A quick explanation is that PAM has the concept of a "service", an example of which could be "an application that uses PAM for authentication". Administrators control how PAM interacts with services by editing the file `/etc/pam.d/<service-name>`. iRODS interacts with PAM through the service named `irods`, so to adjust how PAM authenticates iRODS' passwords, one would edit the `/etc/pam.d/irods` file.

In your case, you want PAM to use LDAP for authentication (with the end result being that iRODS uses LDAP for authentication). To achieve this, you will edit your configuration file for the PAM service `irods` (`/etc/pam.d/irods`) to have PAM use your LDAP server.

**Comment by klin938** [comment]
Thanks, I configured the /etc/pam.d/irods and PamAuthCheck is finally working with LDAP:
```
derlin@nerv-geofront:~$ /var/lib/irods/iRODS/server/bin/PamAuthCheck derlin
PASSWORD
Authenticated
```
Then I created a user "derlin" in iRODS"
```
iadmin>lu
derlin#GarvanZone
rods#GarvanZone
```
Follow the manual, I tried to run iinit as derlin, I was given CAT_INVALID_USER error:
```
derlin@nerv-geofront:~$ iinit
Enter your current iRODS password:
[-]     libnative.cpp:340:native_auth_client_response :  status [CAT_INVALID_USER]  errno [] -- message [Call to rcAuthResponseFailed.]

 failed with error -827000 CAT_INVALID_USER
```
From the manual:
```
Error Code: CAT_INVALID_USER -827000
This error can occur when the iRODS user is unknown or invalid in some way (for instance, no password
has been defined for the user, or the user does not exist in that Zone). This error is most common while
debugging configuration issues with Zone Federation.
```
The user "derlin" exists, but I didn't assign the password because this how LDAP auth works??

Or I am also guessing I should still assign a password to derlin but just leave it blank.

**Comment by beppodb** [comment]
Have you set the irodsAuthScheme environment variable?

$ irodsAuthScheme=PAM
$ export irodsAuthScheme
$ iinit
Enter your current PAM password:
                   ^^^

The prompt should say "PAM password" rather than "iRODS password" if iRODS is expecting the PAM auth mechanism.

Dan

**Comment by klin938** [comment]
This variable needs to be set on user env as well, not inside .irodsEnv
```
export irodsAuthScheme=PAM
```

**Comment by kellerb** [comment]
4.0.3 has a number of environment variables that must be set directly, not in `.irodsEnv`. These are not documented very well, and are definitely confusing.

One of the improvements 4.1 will bring is unifying the environment variables with the environment configuration file (to be called `irods_environment.json` instead of `.irodsEnv`), so that they can all be set either way.

If this is now working for you, please feel free to close the issue.
