### ISSUE TITLE
KeyError: 'catalog_database_type' on upgrade from 4.0.2 to 4.0.3

### ISSUE THREAD

**Issue by beppodb** [irods/irods#2520]
This was using .deb packages. Existing installation was 4.0.2 with postgres plugin version 1.2. I attempted to upgrade using 

```
sudo dpkg -i irods-icat-4.0.3-64bit.deb 
```

**Comment by trel** [comment]
This requires upgrading the database plugin first (or at least at the same time).

`sudo dpkg -i irods-database-plugin-postgres-1.3.deb irods-icat-4.0.3-64bit.deb`
