### ISSUE TITLE
typo in the ibun manpage

### ISSUE THREAD

**Issue by childers** [irods/irods#2526]
This is very minor, but I wanted to tag it before I forget. The man page for ibun hasa typo right before the Options section. 
```
The -b option when used with the -x option, specifies bulk registration
which does up to 50 rgistrations at a time to reduce overhead.
```
Let me know if there is a better place to report issues like this.

**Comment by kellerb** [comment]
Thank you for reporting the typo, we definitely are interested in fixing these sorts of things.

When reporting typos, it can be useful to see if they are still present in the `master` branch, as we are constantly stamping them out. It looks like this one was corrected here: https://github.com/irods/irods/commit/bc9deee632ffb91ea3cc0ac738140a2a0e9784bf.

For future reporting, we use https://github.com/irods/irods/issues/858 for typo-tracking (among other things), so you could make a comment on that issue.

**Comment by childers** [comment]
Great, thanks for pointing me in the right direction.

Best,
Chris
