### ISSUE TITLE
Parallel make too aggressive when choosing number of CPUs

### ISSUE THREAD

**Issue by keithj** [irods/irods#2529]
````
-------------------------------------
Detected CPUs:    32
Compiling with:   make -j 35
-------------------------------------
-----------------------------
Configuring and Building iRODS
````

On a large (therefore probably shared) machine this is almost always too many. This doesn't
appear to be configurable. I tried setting the environment variable myself, but it looks like it
gets overwritten.

**Comment by kellerb** [comment]
FYI, this is possible in the (currently unreleased) early-stage CMake (https://github.com/irods/irods/issues/2239) transition we are working on. So worst-case-scenario, this will be available after the CMake switch.

**Comment by trel** [comment]
@keithj Please check out the new -j option and close this issue if satisfied.

**Comment by keithj** [comment]
Looks good, thanks. I've updated our build to use it.
