### ISSUE TITLE
Regression building C clients against 4.1.0 master

### ISSUE THREAD

**Issue by keithj** [irods/irods#2535]
C clients cannot be build against master at the moment. I've illustrated the problem in a pull request irods/irods#2534

**Comment by trel** [comment]
closing as duplicate of #2534

**Comment by keithj** [comment]
This is broken again in 5164451

**Comment by trel** [comment]
Sorry about that.

**Comment by trel** [comment]
We should now have a Makefile-style blocker before doing this to you the next time.

Please re-close if you're satisfied for now :)

**Comment by keithj** [comment]
Thanks. I've merged yesterday's changes into our 4.1.0 WIP release branch, made a packaged release and successfully built baton against it.
