### ISSUE TITLE
'federation broken' for DFC

### ISSUE THREAD

**Issue by michael-conway** [irods/irods#2550]
This may be a grab bag at first, and may end up being multiple issues. This may be a mix of things we can do in iRODS, through new rules, or even in jargon and the mid-tier so DE can pick it up. This may absorb https://github.com/irods/irods/issues/2191

The general statement from iPlant to DFC is that federation in iRODS has bugs and behaviors that make DE across federated zones, and thus DFC, problematic.  The end state would be smooth behavior of federations, and interoperability in DE.

In order to better define this issue, it seems that step 1 would be to stand up, in CI, a 2+1 topology (2 federated zones, one with a distributed storage resource) so that the jargon tests, including the federation tests and assertions, could run.  We can augment those tests with specific iPlant edge cases as they can be identified.  Nirav is getting his team to enumerate the blockers in getting DFC to work with iPlant's infrastructure.

**Comment by trel** [comment]
Also, consider what else is open in the https://github.com/irods/irods/labels/federation label - this may have already been noticed/logged.

**Comment by michael-conway** [comment]
sure we can consolidate.  This might be first about an enhancement to get base federations in the shiny new topologies to execute these tests.

**Comment by trel** [comment]
federation now in CI.
