### ISSUE TITLE
"iquota -a usage" segfault

### ISSUE THREAD

**Issue by mcast** [irods/irods#2555]
Apologies for basing my report on 3.3.1 (which we are developing against here), @PeteClapham confirmed it also happens in 4.0.3
```
 $ iquota usage
 No records found, run 'iadmin cu' to calculate usage
 $ iadmin cu
 $ iquota -a usage
 Resource      User            Data-stored (bytes)
 demoResc      irods-dev         1,331,261 (1 million)
[...]
 Segmentation fault
```
I see that the test script has included "iquota -a usage" since irods@a192493b or irods-legacy@d6ef5119, but I didn't check that it isn't failing fast and quiet with the "run 'iadmin cu'" message.

Also I should say I don't need this fixed, and there are workarounds.
I'm just reporting it so you know it's broken.

**Comment by kellerb** [comment]
Thank you for reporting. We definitely want to know about any segfaults.

I'm not seeing the segfault on master (ddb0b5da60c219057a071f6cb8865c4dab17f7d4).

**Comment by keithj** [comment]
How many users is your test reporting? I think it will only segfault if it reports usage for more users (rows) than there are table columns (5). From my reading of the code, the bug is present in master (line 404, resulting in segfault at 405).

**Comment by PeteClapham** [comment]
Confirmed in latest. I think Keith may be onto something here 

Pete 

> How many users is your test reporting? I think it will only segfault if it reports usage for more users (rows) than there are table columns (5). From my reading of the code, the bug is present in master (line 404, resulting in segfault at 405). 
> 
> --
> Reply to this email directly or view it on GitHub [1].

 

Links:
------
[1] https://github.com/irods/irods/issues/2555#issuecomment-77417192



-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by kellerb** [comment]
Thanks for the additional information. Fine with 5 users, segfaults with 6.

**Comment by kellerb** [comment]
The segfault should be fixed now.

`iquota -a usage` will still only show the usage of 256 users. I have made a new issue for that here: https://github.com/irods/irods/issues/2556.
