### ISSUE TITLE
Kerberos 5 Keytab support for iRODS HPSS Resource Plugin

### ISSUE THREAD

**Issue by johnalankennedy** [irods/irods#2559]
The current implementation of the hpss resource plugin will only work with a unix keytab.

This is hard coded in the hpss_SetLoginCred call (libhpss.cpp lines 284-288)

```
int status = hpss_SetLoginCred( const_cast<char*>( user.c_str() ),
hpss_authn_mech_unix,
hpss_rpc_cred_client,
hpss_rpc_auth_type_keytab,
const_cast<char*>( keytab.c_str() ) );
```

I believe the "hpss_authn_mech_unix" is what's causing us problems.

This causes the plugin to fail for anyone using Kerberos5 and not unix keytabs (like us).

I've seen cases where
`hpss_Getenv("HPSS_PRIMARY_AUTHN_MECH");`
is used to allow the HPSS env to be the source of the authn_mechanism, thus allowing either unix or krb5 to be used/defined.

Can you modify the plugin to cover Kerberos5 as well please.

**Comment by jasoncoposky** [comment]
closing this issue here as it belongs in the HPSS repository:  irods/irods_resource_plugin_hpss#1842
