### ISSUE TITLE
irods setup script fails if passwords start with '-' sign

### ISSUE THREAD

**Issue by johnalankennedy** [irods/irods#2560]
The irods setup script (setup_irods.sh) fails if you start a password with a - sign.

Here's the output from the logfile (with a bit of added debug to highlight the problem)

```
Updating iRODS server.config...
    Getting scrambled admin password...
    From -This.is.a.password ...
run( /var/lib/irods/iRODS/clients/icommands/bin/iadmin spass -This.is.a.password 123 ) 

Cannot scramble adminstrator password.

Abort.
```

The problem comes from the wrapping of the iadmin command in the perl script irods_setup.pl.

The  scramblePassword subroutine has the following

`my ($status,$output) = run( "$iadmin spass '$password' $DB_KEY" );`

replacing this by

`my ($status,$output) = run( "$iadmin -- spass '$password' $DB_KEY" );`

solves the problem (at least in my test script).

And yes I did make a mental "note to self" that starting a password with a - sign is asking for trouble, but since it's still a valid password I thought it worth the bug report.

**Comment by trel** [comment]
This looks good - will incorporate soon.

**Comment by keithj** [comment]
Given that the `run` function uses backticks, either the contents of $password still need to be sanitised (thus limiting the available passwords) or `run` should be changed to avoid invoking a shell.

**Comment by trel** [comment]
i'm going to make the initial "--" edit for now.

we have a plan to refactor the remaining perl into python very soon, so `run` will also be addressed then.

**Comment by trel** [comment]
In investigating a bit more, that 'spass' was already removed in the
`irods.config` purge #2292 - 52cdc6682e497ad96f6c5b63b73e093b99fcf3fd

I am still adding a test to remember this behavior.
