### ISSUE TITLE
UTF-8 to ASCII encoding/decoding support for iRODS HPSS resource plugin

### ISSUE THREAD

**Issue by johnalankennedy** [irods/irods#2561]
The use case is currently bound to Archive Resources (in our case HPSS).

We currently use the the univMSSInterface.sh script when creating our HPSS Archive resource. However, we're exploring the possibility of using the iRODS-HPSS resource plugin.

Since HPSS does not support UTF-8 (just plain ASCII) we need to encode/decode both the path and filename when staging data to/from HPSS.  

To do this we use the Basic UTF-8 manipulation routines by Jeff Bezanson which have been available in the public domain since the Autumn of 2005.

The addition of the encode/decode step is something we ourselves can do when using the univMSSInterface.sh script - but the iRODS-HPSS resource plugin would need modifications to the source code to enable this functionality within the plugin (which is what we're requesting).

For us the addition of the encode/decode functionality to the HPSS plugin would suffice. However it may be a good idea to consider if the encoding could be performed at a higher level (closer to irods core) thus any other resource backend that speaks just ASCII could easily benefit from this.

**Comment by jasoncoposky** [comment]
closing here as this belongs in the HPSS repo: irods/irods_resource_plugin_hpss#1843
