### ISSUE TITLE
Parallel timeouts experienced in desk testing 4.0.3 at docker

### ISSUE THREAD

**Issue by michael-conway** [irods/irods#2577]
This originated from

https://github.com/DICE-UNC/jargon/issues/81

And involve broken pipe or other connection dropping issues during parallel transfers. These are apparently moderated using the -lfrestart, however, it may indicate some other issue.

Where we saw and fixed several iPlant issues against 3.3.1 via Jargon and icommands.  In desk testing at iPlant (Tony) and RENCI (Hao) via Docker 4.0.3 these apparent errors still occurred.

This is a place holder to track this issue and Hao's and iPlant's testing.

**Comment by jasoncoposky** [comment]
there is currently no reliability within the parallel transfer mechanism.  if an error occurs during the transfer of a chunk the entire process is aborted.  we can investigate adding confirmation to the transfer and retries at the chunk level.
