### ISSUE TITLE
Unable to add mySQL database as a resource to iServ

### ISSUE THREAD

**Issue by okeashwin** [irods/irods#2583]
Hello All,
I was trying to setup an iRODS system . I have a postgreSQL ICAT enabled server. 
I wished to add a mySQL DB as a data resource on an iServ. 
Looked at `mkresc` command, but wasn't able to figure out a matching resource type for that.
Could anybody help me to figure out a way of doing this?

Any help is highly appreciated.

Thank you.

**Comment by trel** [comment]
covered at https://groups.google.com/forum/#!topic/irod-chat/zNsdMMnHXzI
