### ISSUE TITLE
Delayed rules running twice in 4.0.3

### ISSUE THREAD

**Issue by ilarik** [irods/irods#2584]
Note from @kellerb: We are using this issue to address the multiple rule execution error and #2521 to address the memory use error.

---

When running rules as delayed rules from the rule exec queue I have run into some peculiar issues which I were unable to solve. First of all the rule engine server seems to run my queued rules twice in a row. 

The more serious problem though is a crash of the irodsReServer process from a memory management exception where glibc suggests that the heap is either corrupted or `free()` has been called on an already freed memory pointer. At first (and for a while) I thought this was an error in my code that maybe I had misused some convention or something. I tried everything and finally took my MSI module out of the equation entirely and tried with a simplified rule where my msi call is commented out: 

```
acExtractImageMetadata
{
      writeLine("serverLog", "rule acExtractImageMetadata is being evaluated");
      msiAddKeyVal(*imgAttrs, "fi.jyu.irods.metadata.generator", "msiJyuImageGetAttributes");
#     msiJyuImageGetAttributes($objPath, *imgAttrs);
      msiSetKeyValuePairsToObj(*imgAttrs, $objPath, "-d");
}
```

The previous rule is being hooked into `core.re` rule `acPostProcForPut` simply using 

```
delay("<PLUSET>0m</PLUSET>") { acExtractImageMetadata; }
```

I’m thinking this is a bug in the rule engine or then I’m doing something terribly wrong. Probably at least my rule shouldn’t crash the server. The rule engine log has the following (and more):

```
Mar 29 22:19:11 pid:3046 NOTICE: reServerMain: checking the queue for jobs
Mar 29 22:19:11 pid:3077 NOTICE: writeLine: inString = rule acExtractImageMetadata is being evaluated
Mar 29 22:19:11 pid:3079 NOTICE: execCmd: argv:
Mar 29 22:19:11 pid:3077 NOTICE: chlSetAVUMetadata found metaId 18168
Mar 29 22:19:11 pid:3077 NOTICE: chlSetAVUMetadata found metaId 18169
*** glibc detected *** irodsReServer: double free or corruption (!prev): 0x000000000220bb80 ***
======= Backtrace: =========
/lib64/libc.so.6[0x30f7e75e66]
/lib64/libc.so.6[0x30f7e789b3]
irodsReServer(clearKeyVal+0x42)[0x4936b2]
irodsReServer(freeDataObjInfo+0x15)[0x493765]
irodsReServer(freeAllDataObjInfo+0x1c)[0x4937bc]
irodsReServer(_Z25freeRuleExecInfoInternalsP12RuleExecInfoi+0x67)[0x71a547]
irodsReServer(_Z22freeRuleExecInfoStructP12RuleExecInfoi+0x9)[0x71a5d9]
irodsReServer(_Z11runRuleExecP12reExecProc_t+0x78)[0x536528]
irodsReServer(_Z16postForkExecProcP8rsComm_tP12reExecProc_t+0x5a)[0x536bda]
irodsReServer(_Z17runQueuedRuleExecP8rsComm_tP8reExec_tPP11GenQueryOutli+0x155)[0x538aa5]
irodsReServer(_Z12reServerMainP8rsComm_tPc+0xa4)[0x486d74]
irodsReServer(main+0x410)[0x487520]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x30f7e1ed5d]
irodsReServer[0x485759]
======= Memory map: ========
... (memory map) ...
Mar 29 22:19:11 pid:3081 NOTICE: writeLine: inString = rule acExtractImageMetadata is being evaluated
Mar 29 22:19:11 pid:3083 NOTICE: execCmd: argv:
Mar 29 22:19:11 pid:3081 NOTICE: chlSetAVUMetadata found metaId 18168
Mar 29 22:19:11 pid:3081 NOTICE: chlSetAVUMetadata found metaId 18169
*** glibc detected *** irodsReServer: free(): invalid pointer: 0x000000000220bff0 ***
======= Backtrace: =========
/lib64/libc.so.6[0x30f7e75e66]
irodsReServer(clearKeyVal+0x42)[0x4936b2]
irodsReServer(freeDataObjInfo+0x15)[0x493765]
irodsReServer(freeAllDataObjInfo+0x1c)[0x4937bc]
irodsReServer(_Z25freeRuleExecInfoInternalsP12RuleExecInfoi+0x67)[0x71a547]
irodsReServer(_Z22freeRuleExecInfoStructP12RuleExecInfoi+0x9)[0x71a5d9]
irodsReServer(_Z11runRuleExecP12reExecProc_t+0x78)[0x536528]
irodsReServer(_Z16postForkExecProcP8rsComm_tP12reExecProc_t+0x5a)[0x536bda]
irodsReServer(_Z17runQueuedRuleExecP8rsComm_tP8reExec_tPP11GenQueryOutli+0x155)[0x538aa5]
irodsReServer(_Z12reServerMainP8rsComm_tPc+0xea)[0x486dba]
irodsReServer(main+0x410)[0x487520]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x30f7e1ed5d]
irodsReServer[0x485759]
======= Memory map: ========
... (memory map) ...
Mar 29 22:19:11 pid:3046 ERROR: waitAndFreeReThr: 18260 executed but still in iCat. Job deleted
Mar 29 22:19:11 pid:3046 NOTICE: reServerMain: checking the queue for jobs
```

My workaround for this is to not use delayed execution at all. When I take delay out of the equation everything (including my microservice module for metadata extraction) works perfectly.

**Comment by kellerb** [comment]
The memory corruption portion of this issue is being addressed in #2521. I have copied your report to a comment in that thread.

We will use this issue to address the double execution of the rule.

**Comment by xu-hao** [comment]
y

**Comment by kellerb** [comment]
I replicated the multiple rule execution in 4.0.3 but was not able to replicate on master (af839a6d7219573f86f8cbc70044f956daefc790). I have pushed a test that catches the rule repetition experienced in 4.0.3. Please let us know / re-open this issue if you see this behavior on a commit at or later than af839a6d7219573f86f8cbc70044f956daefc790.
