### ISSUE TITLE
Rule base updates not reloaded by irodsReServer other than for core.re

### ISSUE THREAD

**Issue by ilarik** [irods/irods#2585]
When a rule base other than `core.re` is changed the file is not automatically reloaded in to the rule engine (e.g. for delay rules). If for example I would update two files `core.re` and `myrules.re`, both of which are specified in the `/etc/irods/server.config` file as

```
reRuleSet   core,myrules
```

then only the `core.re` file is reloaded into the `irodsReServer` which is notified in the `reLog` file as

```
Mar 29 21:01:07 pid:1552 NOTICE: chkAndResetRule: reconf file /etc/irods/core.re has been changed. re-initializing
Mar 29 21:01:07 pid:1552 NOTICE: reServerMain: checking the queue for jobs
```

It would be more convenient if all the rule bases would be reloaded when changed. I usually just restart the server just in case.

**Comment by xu-hao** [comment]
closing pending tests

**Comment by jasoncoposky** [comment]
refactor test for delayed execution rule
