### ISSUE TITLE
irsync not working with SHA256 checksumming

### ISSUE THREAD

**Issue by ilarik** [irods/irods#2586]
Checksumming with SHA256 at least with `irsync` doesn’t seem to work when `~/.irods/.irodsEnv` has the default value (also in iRODS 4.0.3 Manual)

```
irodsDefaultHashScheme 'SHA256'
```

When trying to run `irsync` on a collection it transfers everything even though files haven’t changed 

```
$ irsync -Krv Uuidtest.study i:Uuidtest.study
C- /jyu/home/testuser/Uuidtest.study:
   IM-0001-0001.dcm                0.503 MB | 0.244 sec | 0 thr |  2.061 MB/s
   testfile.txt                    0.000 MB | 0.155 sec | 0 thr |  0.001 MB/s
```

I found in the header file `irods/iRODS/lib/hasher/include/SHA256Strategy.hpp` a definition

```
const std::string SHA256_NAME( "sha256" );
```

And when using the lower case `sha256` as the hash scheme name in `~/.irods/.irodsEnv` everything works:

```
$ irsync -Krv Uuidtest.study i:Uuidtest.study 
C- /jyu/home/testuser/Uuidtest.study:
   IM-0001-0001.dcm                0.503 MB --- a match no sync required 
   testfile.txt                    0.000 MB --- a match no sync required 
```

**Comment by kellerb** [comment]
Addressed in #2391.
