### ISSUE TITLE
Compiler options for compiling iRODS 4 with GCC on OS X

### ISSUE THREAD

**Issue by ilarik** [irods/irods#2588]
I haven't had luck with compiling iRODS 4 on OS X 10.8 / 10.9 / 10.10 with the system provided clang compiler and thus have done my compiling with an installation of GCC 4.9 (worked also with GCC 4.8) from the Fink package repository. I believe this is because of some intrinsics in the Boost library version that the iRODS build is being linked against which just simply won’t compile with clang. GCC 4.8 or later builds iRODS flawlessly with the following change.

When compiling with GCC in OS X the linker option `-rdynamic` cannot  be used since the target is not ELF. In the makefile template `irods/iRODS/config/platform.mk.template` the following works:
``` make
# =-=-=-=-=-=-=-
# JMC :: build using iRODS Extensions
#     :: currently this is only the microservice plugins
#     :: also enable C++ 0x capabilities
CCFLAGS += -fPIC
ifeq ($(OS_platform), osx_platform)
LDRFLAGS += -ldl
else
LDRFLAGS += -ldl -rdynamic
endif
```

**Comment by kellerb** [comment]
I have altered the proposed change slightly.

If it works, please feel free to close the issue.
