### ISSUE TITLE
Package installs should only look for config files in /etc/irods

### ISSUE THREAD

**Issue by kellerb** [irods/irods#2595]
Perhaps create and use the following:
* `bool is_package_install()`
* `std::string get_config_dir()`

[Current code](https://github.com/irods/irods/blob/2fed9d60ace52e8dbd04f32ef940b034495b5f02/iRODS/lib/core/src/irods_get_full_path_for_config_file.cpp#L29) that ends up checking other directories, with inverted priority.

**Comment by trel** [comment]
this was handled before 4.1.0?

**Comment by kellerb** [comment]
Implemented by https://github.com/irods/irods/commit/c5b026596b8ad86eca12b8b79be12c3e62552ef1
