### ISSUE TITLE
Populate control plane settings during setup

### ISSUE THREAD

**Issue by kellerb** [irods/irods#2609]

**Comment by trel** [comment]
we will only prompt for control plane port and key during setup.
  -  "server_control_plane_port": 1248,
  -  "server_control_plane_key": "TEMPORARY__32byte_ctrl_plane_key",

the other three will live in `advanced_settings` in `server_config.json`
  -  "server_control_plane_encryption_algorithm": "AES-256-CBC",
  -  "server_control_plane_encryption_num_hash_rounds": 16,
  -  "server_control_plane_timeout_milliseconds": 10000,

**Comment by trel** [comment]
forgot the docs
