### ISSUE TITLE
test_local_iput_interrupt_XXX failing intermittently

### ISSUE THREAD

**Issue by kellerb** [irods/irods#2634]
- [x] main
- [x] 4-3-stable

---

Reactivate test when fixed.

If the process is killed too quickly, the zero length file is not removed from the database.
If the process is killed too slowly, the upload completes, or the process is killed while writing the restart file, resulting in malformed XML that breaks the restart attempt.

Possibly add lever (e.g. command line arg, or env var) into `iput` to guarantee a clean failure (simulating lost network connection).

**Comment by trel** [comment]
try sending SIGINT

**Comment by alanking** [comment]
Just adding an update here... I ran `test_local_iput_interrupt_directory` 100+ times and did indeed see a failure after... 70-80 successes. So, I guess this problem still exists.

**Comment by alanking** [comment]
I rewrote these tests with some more specific assertions and observed both passing 100+ times in a row. I think we can unskip the tests with the rewrite.

**Comment by korydraughn** [comment]
Excellent!
