### ISSUE TITLE
parseUserName function gone from C API

### ISSUE THREAD

**Issue by keithj** [irods/irods#2647]
baton uses the `parseUserName` function from the C API which was present in iRODS 3.3.1 and retained in 4.0.x. This function seems to have been removed recently from the C API. Is there a suitable alternative in 4.1.x?

Would it be possible to deprecate functions prior to their removal?

**Comment by tempoz** [comment]
The C API available one is now splitUserName, due to #2465. Normally it would be possible to deprecate it, but in this case parseUserName had to be moved and there would have been naming conflicts.

**Comment by keithj** [comment]
Given that you have control over both the public client API and the DB plugins and therefore the naming of the functions in each, I have to say that this seems like a weak argument.

baton also has to support 3.3.1 and 4.0.x which have `parseUserName`, not `splitUserName`

**Comment by tempoz** [comment]
If it's a problem for you, I can change it, no worries. Unfortunately, the "C API" consists of nearly every function available on the client side in iRODS, so it's not always clear what people are actually using and what it is that needs to remain constant. I'm sorry that this moved underneath you.

**Comment by keithj** [comment]
I appreciate the difficulty of maintaining a large public API. Once it's been released you can expect people to be using any part of it, so it's not safe to make changes to it unilaterally. If you go through a deprecation cycle then anyone using your API can tell you whether they are using the parts that you would like to change.

The process can be made smoother by e.g. making deprecated functions warn the user at compile time by taking advantage of compiler pragmas or by providing shim header files to keep the API constant.

**Comment by keithj** [comment]
Right now I'm building iRODS releases packages regularly from `master` and using them as a base for testing our client programs in advance of the code freeze. It looks like there will be about 4 weeks available for testing before the next release and I don't want to be sending you bug reports close to the deadline. However, at the moment the tests are able to run:

https://travis-ci.org/keithj/baton/builds/59620697

**Comment by tempoz** [comment]
Fix will be pushed within 5 minutes.

**Comment by keithj** [comment]
Thanks. That's fixed that build error. Unfortunately other functions appear to have been renamed too (MD5 API related to #1998, a  change was scheduled for 5.0).

**Comment by trel** [comment]
That happened due to https://github.com/irods/irods/issues/2578#issuecomment-86418530

**Comment by kellerb** [comment]
Closing this because `parseUserName` is back.

I think the current plan is to stay with the MD5 function renaming, due to that fixing a Mac-specific collision.

Please let us know in a new issue if another function moves out from under you.
