### ISSUE TITLE
irods::error object within C linked client API functions

### ISSUE THREAD

**Issue by jasoncoposky** [irods/irods#2648]

**Comment by jmarshall** [comment]
I see that in recent commits attached to this issue, various `*.hpp` headers have been reverted to being named `*.h`, as they had been named in 3.3.x.

The third-party client I maintain, [hfile_irods.c](https://github.com/samtools/htslib/blob/develop/hfile_irods.c), includes the following iRODS API headers:

```c
#include <rcConnect.h>
#include <dataObjOpen.h>
#include <dataObjRead.h>
#include <dataObjWrite.h>
#include <dataObjLseek.h>
#include <dataObjClose.h>
```

As you see, it was written against the 3.3.x API.  I am in the process of making it work against 4.1.0 too.

`rcConnect.hpp` has just been renamed back to `.h` in 00b78660acbccbe78fa2c319a0a47c552334d8fd.

Will `dataObjOpen.hpp`/`Read`/`Write`/`Lseek`/`Close.hpp` also be renamed back to `.h`?

**Comment by keithj** [comment]
Can you expand on what you have in mind following the `.h` versus `.hpp` division? Are all the current API functions with C linkage going to be migrating to the `.h` copy, or something like that?

**Comment by tempoz** [comment]
The idea is that all the header files that are part of the C API will be `.h` files, with the dev package still containing links with the 4.0.x `.hpp` files pointing back at the newly (un?)renamed `.h` files.

**Comment by keithj** [comment]
The C API is pretty extensive, so I imagine that there are many more files to be renamed. I'm wondering whether I should hold off trying to build C clients against master for a while, until things stabilise.

**Comment by jmarshall** [comment]
Well then, do you consider `dataObjOpen.hpp`/`Read`/`Write`/`Lseek`/`Close.hpp` to be part of of the C API?

(I have a C client that uses them and they don't contain anything C++-specific, so I certainly would hope that you do!)

**Comment by tempoz** [comment]
Yes, all of those should be included. When I've finished moving them, let me know if you think I've missed anything that ought to be C-linkable.

**Comment by tempoz** [comment]
Also, I intend to finish this today, and the `.hpp` files shouldn't move out from under you anyway, so hopefully it shouldn't impede your workflow too much :)

**Comment by tempoz** [comment]
This should be finished. Closing now, will re-open if anyone encounters problems with this solution.
