### ISSUE TITLE
iput -f -R <rescName> not honoring rescName

### ISSUE THREAD

**Issue by kellerb** [irods/irods#2651]
```
irods:~$ iadmin mkresc unixResc unixfilesystem `hostname`:/var/lib/irods/iRODS/unixResc
Creating resource:
Name:           "unixResc"
Type:           "unixfilesystem"
Host:           "icat.example.org"
Path:           "/var/lib/irods/iRODS/unixResc"
Context:        ""

irods:~$ iput VERSION.json 

irods:~$ echo contents > other.file

irods:~$ ils -L
/tempZone/home/rods:
  rods              0 demoResc          475 2015-04-23.14:47 & VERSION.json
        generic    /var/lib/irods/iRODS/Vault/home/rods/VERSION.json

irods:~$ iput -f -R unixResc other.file VERSION.json 

irods:~$ ils -L
/tempZone/home/rods:
  rods              0 demoResc            9 2015-04-23.14:48 & VERSION.json
        generic    /var/lib/irods/iRODS/Vault/home/rods/VERSION.json

irods:~$ iget VERSION.json -
contents
```

Note in the second `ils -L` that the data object `VERSION.json` is still on `demoResc` even though the `iput -f -R unixResc...` specified `unixResc`.

After discussion, it was determined that a new replica of `VERSION.json` should be created on `unixResc` containing the new contents, with the replica on `demoResc` marked dirty.

**Comment by jasoncoposky** [comment]
we have decided to treat this as an error case in order to not confuse functionality between iput and irepl regarding the creation of replicas.

**Comment by jasoncoposky** [comment]
need to add a more comprehensive search through the list of replicas.  rsObjStat is not honoring the dest resc keyword.
