### ISSUE TITLE
Add client checks for missing config variables created in 2303

### ISSUE THREAD

**Issue by keithj** [irods/irods#2654]
Note from @kellerb
#2303 Moved a number of hardcoded server configuration numbers into `server_config.json`, some of which must also be in `irods_environment.json`. Need to check for these, and error out if missing.

- [ ] `irods_transfer_buffer_size_for_parallel_transfer_in_megabytes`

---

I've been building iRODS Ubuntu packages from master regularly over the past few weeks to test baton. Last night (22nd April) I built one which seems to have problems with `iput` on a fresh install. Every `iput` yields:

````
ERROR: putFile: totalWritten 0 dataSize 1 mismatch
ERROR: putDirUtil: put ../tests/data/lorem_1b.txt failed. status = -27000 status = -27000 SYS_COPY_LEN_ERR
````
I am unable to check whether this affecting you because your public facing CI server at http://ci-dev.renci.org/hudson/view/iRODS/ is down (404).

I'm getting this on Precise both on Travis CI and my local Precise VM. The packages were installed by selecting the defaults for everything except usernames/passwords and the Travis script has been used on many previous builds with no apparent problems.

**Comment by kellerb** [comment]
Do you know which iRODS commit was used in the build?

You can check the contents of the `VERSION.json` file.

**Comment by keithj** [comment]
The last commit on your side was bb71bdac076470dca1bb0a41dc2aec5df4debbb4

(The VERSION.json shows a different commit because I merge your master into a new branch where I have .travis.yml set up to deploy the built packages over to github.)

If your CI is not showing any problems on HEAD, then I should probably merge to that point and rebuild before you spend any time looking at this.

**Comment by kellerb** [comment]
I recommend 0387ff49e67dc62bab47be800a9b508baf918741 as a recent commit that is working. Our testing infrastructure is undergoing some storage maintenance currently, which is probably why hudson is down, and is causing our tests to be slightly behind master.

**Comment by keithj** [comment]
Thanks for the info. I'll kick off a build from there.

**Comment by keithj** [comment]
That build failed too. I notice that it's no longer respecting irods_authentication_file_name (described in the Admin Guide). Our tests are set up with this client environment.

````
{
"irods_zone_name": "tempZone",
"irods_host": "localhost",
"irods_port": 1247,
"irods_user_name": "travis",
"irods_authentication_file_name": "/home/travis/.irods/auth_token",
"irods_home": "/tempZone/home/travis",
"irods_default_resource": "demoResc",
"irods_default_hash_scheme": "MD5",
"irods_match_hash_policy": "strict"
}
````

This was working a day ago (https://travis-ci.org/keithj/baton/builds/59517875) but in this build `iinit` creates a `.irodsA` file instead of the requested `auth_token` file.

**Comment by kellerb** [comment]
That variable is now `irods_authentication_file`.

The full schema for the environment file is here: https://github.com/irods/irods_schema_configuration/blob/master/v2/service_account_environment.json

**Comment by trel** [comment]
Note that v2 of that schema is not fixed until we ship - so if you find errors in the schema itself, please file issues there as well.

**Comment by keithj** [comment]
Thanks. It looks like the token filename is a side issue because it's name is not critical to the test setup. However, I suspect that I'm being hit by a client configuration issue that is causing the SYS_COPY_LEN_ERR error. However, I'm not getting any error messages about the config contents.

**Comment by kellerb** [comment]
Are all the failing `iput`'s large enough to trigger the parallel transfer mechanism? Or, do you know if `iput`'s that are not using the parallel transfer mechanism are also failing?

**Comment by keithj** [comment]
I have a 28 byte file that fails.

I've narrowed it down to the `irods_transfer_buffer_size_for_parallel_transfer_in_megabytes` by doing a binary chop. If that is missing then I get this error.

**Comment by kellerb** [comment]
If `iinit` prompted for that, would your issue have been caught before the `iput` failed?

Several of the hardcoded server configuration variables were recently pulled into the environment, and we need to add guards around them now.

**Comment by keithj** [comment]
In fact, if it's present but somehow invalid I get the error. I don't know what the expected range is. Nonsense values such as -1, 0.9, "yak" and 20000000000 are silently accepted.

**Comment by keithj** [comment]
No, it wouldn't have been caught because I'm running `iiint` unattended in a script, directing to `/dev/null` and checking the exit code.

**Comment by keithj** [comment]
Thanks. I'll follow this up later... it's 2 AM in the UK.

**Comment by kellerb** [comment]
I've added a preamble to your original post, we will use this issue to track adding checks for these variables.

Thank you for finding this.

**Comment by jasoncoposky** [comment]
should these values be missing in the future, they will default to the original values.
