### ISSUE TITLE
add validation configuration to irods_setup.sh and server_config.json

### ISSUE THREAD

**Issue by trel** [irods/irods#2664]
Validation will be a configuration variable.

Default prompt values will be 'on' and 'https://schemas.irods.org/configuration'.  The version information will be appended to the URI from `configuration_schema_version` in `VERSION.json`

This will allow validation to be turned off completely or redirected to retrieve the schemas from a self-hosted or internal server (behind a firewall).

Need to update the `server_config.json` schema as well as the `irods_setup.sh` script, template file, and .input files for CI.

**Comment by keithj** [comment]
The validation currently seems to have a bug in dealing with the server response:

````
$ ./irodsctl start
Starting iRODS server...
ERROR: Validation Failed for [/var/lib/irods/.irods/irods_environment.json]
  AttributeError: 'Response' object has no attribute 'text'
Preflight Check problem:
   JSON Configuration Validation failed.
````

**Comment by trel** [comment]
I haven't seen an attribute error before in my testing - is this possibly due to being behind a firewall or a network issue?

**Comment by kellerb** [comment]
[Preliminary searching](http://stackoverflow.com/questions/22689334/attributeerror-response-object-has-no-attribute-text) suggests this can be caused by an older version of the Python `requests` module.

We'll check on that and update the script for robustness against that case if necessary.

**Comment by trel** [comment]
confirmed - i had requests version 2.3.0 initially... when dropping back to Ubuntu 12.04 default packages... i see

```
$ python -c "import requests; print requests.__version__"
0.8.2
```

**Comment by keithj** [comment]
Yes, this is 0.8.2 on Ubuntu Precise. Sorry, I should have given the platform earlier.

**Comment by trel** [comment]
@keithj you should be insulated now

**Comment by keithj** [comment]
Thanks, I can confirm that this is working for me now.

**Comment by trel** [comment]
if the entered string does not start with http or https, the validation will be skipped.

the suggested value for that behavior is 'off'.

ready to be closed, pending code review.
