### ISSUE TITLE
Add IRODSVERSIONINT or similar to rodsVersion.h

### ISSUE THREAD

**Issue by jmarshall** [irods/irods#2671]
It would be useful if `rodsVersion.h` supplied the iRODS version you were building against in a way usable by the C preprocessor, akin to [BOOST_VERSION](http://www.boost.org/doc/libs/1_58_0/libs/config/doc/html/boost_config/boost_macro_reference.html#config_info_macros).  This could be via the build infrastructure's existing `IRODSVERSIONINT` or perhaps by constructing a number with the same XYYYZZ digit scheme as `BOOST_VERSION`.

This would for example allow third-party C client source code that needs to compile either against 3.3.x or 4.1.0 to write something along the lines of

```c
#if defined RODS_NUM_VERSION && RODS_NUM_VERSION >= 400000
    ret = clientLogin(irods.conn, NULL, NULL);
#else
    ret = clientLogin(irods.conn);
#endif
```

I could write a configure script to detect which form of `clientLogin()` exists (and software that wants to support 4.0.x will need to do that), but this would be generally useful for the future.

**Comment by trel** [comment]
This is a great idea.

In the spirit of Boost and g++, I suggest a new file `iRODS/lib/core/irods_version.h.template`:
```c
#ifndef IRODS_VERSION_H
#define IRODS_VERSION_H

#define IRODS_VERSION_MAJOR             TEMPLATE_IRODS_VERSION_MAJOR
#define IRODS_VERSION_MINOR             TEMPLATE_IRODS_VERSION_MINOR
#define IRODS_VERSION_POINT             TEMPLATE_IRODS_VERSION_POINT

#define IRODS_VERSION_INTEGER           (TEMPLATE_IRODS_VERSION_MAJOR*1000000 + TEMPLATE_IRODS_VERSION_MINOR*1000 + TEMPLATE_IRODS_VERSION_POINT)
#define IRODS_VERSION_STRING            "TEMPLATE_IRODS_VERSION_MAJOR.TEMPLATE_IRODS_VERSION_MINOR.TEMPLATE_IRODS_VERSION_POINT"

#define IRODS_RELEASE_DATE_STRING       "TEMPLATE_IRODS_RELEASE_DATE"

#endif  /* IRODS_VERSION_H */
```

which would be populated at build time to `iRODS/lib/core/irods_version.h`:
```c
#ifndef IRODS_VERSION_H
#define IRODS_VERSION_H

#define IRODS_VERSION_MAJOR             4
#define IRODS_VERSION_MINOR             1
#define IRODS_VERSION_POINT             0

#define IRODS_VERSION_INTEGER           (4*1000000 + 1*1000 + 0)
#define IRODS_VERSION_STRING            "4.1.0"

#define IRODS_RELEASE_DATE_STRING       "20150601"

#endif  /* IRODS_VERSION_H */
```

And then `irods_version.h` would be included in `rodsVersion.h` for backwards compatibility.

Does that sound sufficient?  Any additions/suggestions?

**Comment by jmarshall** [comment]
Thanks.  Almost sufficient, but (2) below is a necessary addition IMHO:

1. It's **critical** that these macros get defined when third-party code #includes some header that already existed in ancient iRODS releases.  We can't directly #include a new header like `irods_version.h` as that will immediately fail when compiling against 3.3 headers!  So including it in `rodsVersion.h` isn't so much for backwards compatibility as it is the entire point of the exercise.

2. Please also #define `IRODS_VERSION` or some such name as `(100000 * IRODS_VERSION_MAJOR + 100 * IRODS_VERSION_MINOR + IRODS_VERSION_POINT)`.  With only the triumvirate added in 209b7a4b12bbfbacdd1e47a914940197c6e5bdab, in the future to check for e.g. v4.2.3 or later we will need to use

        #if defined IRODS_VERSION_MAJOR && (IRODS_VERSION_MAJOR > 4 || (IRODS_VERSION_MAJOR == 4 && IRODS_VERSION_MINOR > 2) || (IRODS_VERSION_MAJOR == 4 && IRODS_VERSION_MINOR == 2 && IRODS_VERSION_POINT >= 3))

    or do the multiplication trick ourselves, either of which is a pain in the neck compared to just

        #if defined IRODS_VERSION && IRODS_VERSION >= 400203

3. (Everybody else—GCC and Clang—calls the third-level number `PATCHLEVEL` rather than `POINT`.)

**Comment by trel** [comment]
No problem...

1) Already taken care of as far as I know.
It is the `#include` here
https://github.com/irods/irods/commit/209b7a4b12bbfbacdd1e47a914940197c6e5bdab#diff-dac9fe7396c739c2fefeef614cc812baR7

2) We're looking at a set of macros that will not duplicate the definitions. 

3) Definitely, I'll update it all to use `PATCHLEVEL`

**Comment by tempoz** [comment]
Hopefully this commit fully addresses your concerns, @jmarshall. If you are satisfied that this solution handles 2) for you, I'll close the issue.

**Comment by tempoz** [comment]
Well, after this commit, which fixes the macros I just added :P

**Comment by trel** [comment]
@jmarshall this look good?

**Comment by jmarshall** [comment]
If I write

```c
#if IRODS_VERSION_IS_AT_LEAST(4,1,0)
    ret = clientLogin(irods.conn, NULL, NULL);
#else
    ret = clientLogin(irods.conn);
#endif
```

(or even if I write `#if defined IRODS_VERSION_IS_AT_LEAST && IRODS_VERSION_IS_AT_LEAST(4,1,0)`) then when I compile it against 3.3 I get

> error: missing binary operator before token "("

because `IRODS_VERSION_IS_AT_LEAST` is not defined.  To work around this, I would need to write

```c
#ifdef IRODS_VERSION_IS_AT_LEAST
  #if IRODS_VERSION_IS_AT_LEAST(4,1,0)
    ret = clientLogin(irods.conn, NULL, NULL);
  #else
    ret = clientLogin(irods.conn);
  #endif
#else
    ret = clientLogin(irods.conn);
#endif
```

or perhaps I could define a fall-back `IRODS_VERSION_IS_AT_LEAST` and then be able to use the sane code:

```c
#ifndef IRODS_VERSION_IS_AT_LEAST
#define IRODS_VERSION_IS_AT_LEAST(major, minor, patchlevel)  0
#endif
// ...
#if IRODS_VERSION_IS_AT_LEAST(4,1,0)
    ret = clientLogin(irods.conn, NULL, NULL);
#else
    ret = clientLogin(irods.conn);
#endif
```

The former would be crazy, and the latter – making each of your API users define such macros themselves – would be unfortunate at best.

----

By comparison, if you define a single integer `IRODS_VERSION` (in addition to the unpacked `IRODS_VERSION_MAJOR`/etc), then your API users will just be able to write

```c
#if IRODS_VERSION >= 400100
```

and all will be well, since if `IRODS_VERSION` is undefined the preprocessor interprets it as 0.

I thought boost, libcurl, the C++ standard et al did this `XYYYZZ` digit-packing thing because they liked simplicity, but it turns out it just works better too :smile:

**Comment by jmarshall** [comment]
Perhaps you could add a digit-packed `IRODS_VERSION` alongside the `IS_AT_LEAST`/etc macros, for the benefit of those of us who need to support 3.3.  Then in the glorious future when we only need to support 4.1+ platforms we will be able to transition to using the fancy macros instead.

**Comment by trel** [comment]
We have been convinced.   `IRODS_VERSION_INTEGER` coming up.

**Comment by trel** [comment]
The glorious future should be here now.   Please confirm.

**Comment by jmarshall** [comment]
That does the trick nicely.  Thanks!
