### ISSUE TITLE
Difficulties linking libRodsAPIs using run-in-place build on master

### ISSUE THREAD

**Issue by keithj** [irods/irods#2676]
On Ubuntu Precise I have a simple program that does nothing but call `getRodsEnv` (actually an autoconf test program to detect a run-in-place install). I'm getting an error related to Jansson when trying to link against `libRodsAPIs`:

````
gcc -std=gnu99 -o conftest -g -O2 -I/home/keith/dev/irods.git/iRODS/../external/boost_1_58_0/boost  -I/home/keith/dev/irods.git/iRODS/lib/api/include -I/home/keith/dev/irods.git/iRODS/lib/core/include -I/home/keith/dev/irods.git/iRODS/server/core/include -I/home/keith/dev/irods.git/iRODS/server/drivers/include -I/home/keith/dev/irods.git/iRODS/server/icat/include -I/home/keith/dev/irods.git/iRODS/server/re/include -L/home/keith/dev/irods.git/iRODS/../external/boost_1_58_0/stage/lib  -L/home/keith/dev/irods.git/iRODS/lib/core/obj conftest.c -lRodsAPIs -ldl -lboost_system -lboost_filesystem -lboost_regex -lboost_thread -lboost_chrono -lboost_program_options -lstdc++ -lssl -lcrypto -ljansson -lgssapi_krb5 -lpthread -lm -lrt  >&5
/home/keith/dev/irods.git/iRODS/lib/core/obj/libRodsAPIs.a(irods_configuration_parser.o): In function `irods::configuration_parser::parse_json_object(json_t*, irods::lookup_table<boost::any, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, irods::irods_string_hash>&)':
/home/keith/dev/irods.git/iRODS/lib/core/src/irods_configuration_parser.cpp:116: undefined reference to `json_object_key_to_iter'
/home/keith/dev/irods.git/iRODS/lib/core/src/irods_configuration_parser.cpp:116: undefined reference to `json_object_key_to_iter'
````

It's clear that I need to link against Jansson. However, there is no way to calculate the location of the Jansson library for run-in-place. It is over in external, in a subdirectory whose name is dependent on the Jansson version (and consequently has changed over time).

The same problem occurred with Boost and I worked around it by forcing users to look in the externals directory first and manually supply a configure option `--with-boost-version` from which I can calculate a path to the library location in external. It's not viable to do this with other libraries too.

I think that this could be solved by the run-in-place build creating the same shared libraries as are built with the packaged version. The build stops short of making libraries at the moment. This would simplify the job of detecting what iRODS setup a user has when building clients.

The composition of a run-in-place build has progressively diverged from a packaged one (the latest change being that the packaged build will have differently named headers due to symlinking that occurs only during packaging). It's getting quite complex to support.

**Comment by trel** [comment]
This will be rectified with the move to CMake.  https://github.com/irods/irods/issues/2239

**Comment by kellerb** [comment]
This should be fixed by making all of our external dependencies `.so` instead of `.a` and having the development libraries link against them by setting `rpath` correctly.

Users of the development libraries should not need to managing the development libraries internal dependencies.
