### ISSUE TITLE
irodsFs (FUSE) hangs with some usage pattern

### ISSUE THREAD

**Issue by mcast** [irods/irods#2680]
Hi,

When using `irodsFs` to supply data files to a web application, I sometimes get a lock-up that freezes the fuse mount.  This then freezes every process that touches the mountpoint, until `killall -9 irodsFs`  - then they all resume with errors.

I have tried to produce a small work pattern or test case to show the problem.  https://gist.github.com/mcast/875f50127eb3e7f6e249 is where I started, but it doesn't yet cause the hang.  I'm still working on that, but wanted to let you know there is a problem.

I'm running this with irods v3.3.1 but will also test with a v4 when I have a way to do that.

The application stack is currently rather complex,
- Data files up to about 100 GiB
  - currently presented by NFS
  - `ireg` of those into irods-3.3.1
  - this is for testing purpose, not a long term solution
- `irodsFs` (FUSE)
- `nginx` running in Linux `sendfile` mode.  I don't yet know if the mode makes a difference.
- [JBrowse 1.11.6](http://jbrowse.org/) interactive genome browser.  This generates multiple concurrent GET requests for byte-ranges of the large .bam files we are looking at.
- Surfing around it for a few minutes will tend to provoke the error.

I planned to boil this down to a small script to provoke the error, but it is taking longer than I expected.  My current approach is to translate the `strace` output from watching `nginx` bring it down, into some kind of small script that you could include as test code.

Any advice appreciated!

**Comment by trel** [comment]
irodsFs on master has moved forward quite a bit.  4-1-stable is also much better.

Please try to reproduce this with the newer code and let us know how it goes.

Thanks.

/cc @iychoi @xu-hao

**Comment by mcast** [comment]
On Mon, Sep 14, 2015 at 12:29:55PM -0700, Terrell Russell wrote:

> irodsFs on master has moved forward quite a bit.  4-1-stable is also
> much better.
> 
> Please try to reproduce this with the newer code and let us know how
> it goes.

I will, but it may be a few weeks (sorry) until we get our 4.1 test
system.

I do still have the tool that reproduced the error, and the data to
feed it.  I didn't get the data distilled down into something minimal
or redistributable though.

-- 
Matthew


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by alexlemann** [comment]
We were thinking about using this same approach for hydroshare (nginx + irodsfs) for resource downloads.
* Do you have any update @mcast on how this has been working for you?
* Also, @trel, or @xu-hao were you able to reproduce the issue?

**Comment by iychoi** [comment]
The issue was due to a deadlock in v3.x of irodsFs. At v4.1, irodsFs was reimplemented and didn't hear any reports of deadlocks so far.

**Comment by mcast** [comment]
We worked around the irodsFs failure in 3.3.1 by exporting the `unix file system` vault directories over nfs, and making that available for the use cases that need it.  Ugly but effective.

We postponed migration to irods 4.1 because of a couple of bugs (#3146 and I think #3195), so I haven't exercised irodsFs 4.1.  Even after migration I'm not sure we will want the extra complexity.

**Comment by trel** [comment]
Fuse is now in a separate repository - https://github.com/irods/irods_client_fuse.

If this is still an issue, please recreate it there.
