### ISSUE TITLE
irodsAgent processes writing to an old log file

### ISSUE THREAD

**Issue by triitaojcsc** [irods/irods#2684]
Hi,

in iRODS 4.X log files are saved under the `/var/lib/irods/iRODS/server/log/` directory, under which the `irodsServer` and `irodsAgent` processes both write logs to `rodsLog.YEAR.MONTH.DAY` files.
# The problem

In case where there are _very_ long file transfers, two log files might simultaneously contain up-to-date log entries:

```
# lsof rodsLog.2015.04.26
COMMAND     PID  USER   FD   TYPE DEVICE  SIZE/OFF    NODE NAME
irodsAgen 19892 irods    0u   REG 253,15 531587021 2097567 rodsLog.2015.04.26
irodsAgen 19892 irods    1u   REG 253,15 531587021 2097567 rodsLog.2015.04.26
irodsAgen 19892 irods    2u   REG 253,15 531587021 2097567 rodsLog.2015.04.26
irodsAgen 21084 irods    0u   REG 253,15 531587021 2097567 rodsLog.2015.04.26
irodsAgen 21084 irods    1u   REG 253,15 531587021 2097567 rodsLog.2015.04.26
irodsAgen 21084 irods    2u   REG 253,15 531587021 2097567 rodsLog.2015.04.26
#
# lsof rodsLog.2015.05.11 
COMMAND     PID  USER   FD   TYPE DEVICE SIZE/OFF    NODE NAME
irodsServ  2967 irods    0u   REG 253,15   247386 2098367 rodsLog.2015.05.11
irodsServ  2967 irods    1u   REG 253,15   247386 2098367 rodsLog.2015.05.11
irodsServ  2967 irods    2u   REG 253,15   247386 2098367 rodsLog.2015.05.11
irodsAgen 13521 irods    0u   REG 253,15   247386 2098367 rodsLog.2015.05.11
irodsAgen 13521 irods    1u   REG 253,15   247386 2098367 rodsLog.2015.05.11
irodsAgen 13521 irods    2u   REG 253,15   247386 2098367 rodsLog.2015.05.11
irodsAgen 13550 irods    0u   REG 253,15   247386 2098367 rodsLog.2015.05.11
irodsAgen 13550 irods    1u   REG 253,15   247386 2098367 rodsLog.2015.05.11
irodsAgen 13550 irods    2u   REG 253,15   247386 2098367 rodsLog.2015.05.11
#
```

The irodsAgent processes that have a handle on `rodsLog.2015.04.26` have been running for ~300 hours, but during that time the log has been rotated to `rodsLog.2015.05.11`.
# Desired outcome

It would be better if all the logs would be written to the new file (`rodsLog.2015.05.11`).

Bonus: From a sysadmin point-of-view, it would be nice if the log files were named with the suffix `.log`.

-- Taneli Riitaoja / CSC

**Comment by trel** [comment]
part of https://github.com/irods/irods/issues/2112

**Comment by trel** [comment]
@korydraughn can this be closed?   everything in master is now going through syslog now...

**Comment by korydraughn** [comment]
If this is only for master, then yes.

**Comment by trel** [comment]
Definitely - we're not retooling any of the logging for 4.2.x.    Closing.
