### ISSUE TITLE
iinit prefers legacy environment file, even when new file is present

### ISSUE THREAD

**Issue by keithj** [irods/irods#2686]
4.1.0-pre, Ubuntu Precise.

I have a valid irods_environment.json file in the correct location. `iinit` ignores it and instead uses my `.irodsEnv` file (which is used when I connect to an iRODS 3.3.1 server) and then warns me that it is a legacy file.

**Comment by jasoncoposky** [comment]
we believe what is happening is that the irods_environment.json is not properly formatted and the legacy configuration is the fall back.  i will add error messages should that be the case.

**Comment by jasoncoposky** [comment]
in rereading the ticket i see that you say the irods_environment.json is valid.  is this according to our  included server startup validation?

**Comment by keithj** [comment]
I checked the config by eye, but as you suspected, there was an error in it - a trailing comma, so it was hard to spot. Your fix above means that I'm now seeing a useful error message, thanks.

**Comment by jasoncoposky** [comment]
good to hear, closing.
