### ISSUE TITLE
.deb package install fails in setup_irods.sh

### ISSUE THREAD

**Issue by keithj** [irods/irods#2687]
I'm building .debs from 819fd707b9ae59de8b8c093d2a640952116a8c66 to test a recent bug fix. I've had no trouble building and installing them until now.

I built the packages with `./packaging/build.sh icat postgres` then installed with `sudo dpkg -i ./build/irods-icat-4.1.0-64bit.deb ./build/irods-database-plugin-postgres-1.5.deb`. The irods home directory is clean before the package install.

I run `sudo /var/lib/irods/packaging/setup_irods.sh` and use the defaults for all the settings. This happens:

````
-------------------------------------------
iRODS Zone:                 tempZone
iRODS Port:                 1247
Range (Begin):              20000
Range (End):                20199
Vault Directory:            /var/lib/irods/iRODS/Vault
zone_key:                   TEMPORARY_zone_key
negotiation_key:            TEMPORARY_32byte_negotiation_key
Control Plane Port:         1248
Control Plane Key:          TEMPORARY__32byte_ctrl_plane_key
Schema Validation Base URI: https://schemas.irods.org/configuration
Administrator Username:     irods
Administrator Password:     Not Shown
-------------------------------------------
Please confirm these settings [yes]: 

Updating /etc/irods/server_config.json...
Preparing /var/lib/irods/iRODS/server/icat/src/icatSetupValues.sql...
mv: cannot move `/tmp/irods/icatsetupvalues.txt' to `/var/lib/irods/iRODS/server/icat/src/icatSetupValues.sql': Permission denied
````

The SQL in /tmp that is being copied belongs to the service user `irods`. The newly created directory `/var/lib/irods/iRODS/server` is owned by me, which doesn't look right. I uninstalled the packages, deleted everything in the `irods` user's home, cleaned, rebuilt and reinstalled the packages with the same result.

**Comment by jasoncoposky** [comment]
for a complete reinstall you need to remove all directories previously owned by the irods service account:
```
sudo rm -rf /etc/irods /tmp/irods /var/lib/irods
```
in order to prevent collisions.  there were certain upgrade paths which cause a trigger of the clean up in the packaging scripts.  in order to prevent any possible loss of data we no longer clean up any residual directories, which leads to more work for the resinstallation.

**Comment by kellerb** [comment]
Note: I believe that if `sudo` is not used with `./packaging/build.sh`, the packaged files will be owned by `$BUILD_USER` instead of `root`. I don't think that is involved in this issue, however.

**Comment by keithj** [comment]
The packaging system should really use fakeroot to set the file permissions. I don't want to be running builds as root!

**Comment by trel** [comment]
The `fakeroot` looks like a viable solution for the permissions... We would need to check its behavior across platforms and we're too late in the release cycle now for 4.1.0.

As for the build / cleanup issue, also bumping this until after the release.

**Comment by trel** [comment]
we're not scripting the use of `sudo`, so i'll close this.
