### ISSUE TITLE
sketch of a chunked transfer

### ISSUE THREAD

**Issue by michael-conway** [irods/irods#2688]
chunked transfer proposal.

This would be an alternative to current parallel algo and restart, and could be used by REST api for chunked file transfer when streaming i/o is used too.

Large files are broken up and sent as chunks to be concat on iRODS server for put, and on client for get.  Clients will determine chunk size by heuristic, multiple threads can send independent chunks decorated with a temporary file name convention (e.g. ~ prefix), or chunks can be sent using streaming i/o (e.g. REST api)

Files are transferred and held in a ‘.hidden’ directory as segments.  PEPs need to be wired by rule or convention to ignore these locations at multiple points for puts.

Put: Client can call a reassembly rule that includes a total length, # chunks, desired iRODS path and optional checksum
Get: Client does same operation with the above info from iRODS

File is concatenated, moved to appropriate final location  appropriate PEPs are then called as if the file was put/get. Cleanups are done.

Failure mode:

Chunk sizes are reasonable enough that simple retransmission of a chunk is recovery.  Files could have a _N_of_N_ suffix.  With a standard chunk size the location and recreation of those segments should be rather easy.

Should chunk sizes be above or below 32MB minimum?  How big is big enough to make parallel transfer of chunks reasonable over standard ‘put with data’?  Is there a case that there should be a target maximum number of segments?  Or is it better to just have a ton of small segments for a huge file?

Some sort of reaper for abandoned transfers?  

Detection of availability of this algo?

On the source side of chunking, in order to seamlessly fit into the iRODS server, the chunks would have to be segmented and then transferred using normal channels.

service sketch for put

```
put {
    transfer() {
        compute status()
        initializeTransfer()
        transferBasedOnMap()
        on error call restart() n times and then fail
        completeTransfer()
    }

    restart() {
        computeStatus()
        initializeTransfer()
        transferBasedOnMap()
        completeTransfer()
    }

    computeStatus() {
        client compute map [create list of chunks and their sizes]
        look for any existing chunks and add boolean complete/not complete to map
    }

    initializeTransfer() {
        given status map, compute # threads and initialize each thread
        r/a file seek to start of chunk
    }

    transferBasedOnMap() {
        given chunk map and worker pool, each thread grabs the next chunk, transfers it
        on error in chunk, mark as bad in map
    }

    completeTransfer() {
        given map, checksum, length, # chunks, etc reassemble, call any peps
        cleanupTransfer()
    }

    cleanupTransfer() {
        clean up old chunks, either by timestamp, or given a transfer path
        used by normal process and by reaper process
    }
}
```

**Comment by michael-conway** [comment]
comment...via Reagan



We do need to know if each chunk is transmitted successfully.  For tracking restarts across network interruptions, we will have to manage state information.  We will need to know which transfers are in progress, which have not completed, and which have completed.  This information can be in a restart file, or a structure in memory, or in iCAT.

I see no real difference between state for partial I/O, and state for separate chunks.  For chunks, the status information is in the iCAT catalog.

**Comment by edwins** [comment]
I suggest calculating hash per chunk (ala torrent) to aid in the verification of transfer; if this is the case, you probably want the iCAT to precompute and store the hash size based on file size (or other heuristic).  Transfer state information could then be associated at the location where the partially transfered chunks reside on the client side. I believe torrents have a max chunk size of 1M.

For the above comment (via Reagan), why would the iCAT need to track the state/status of transfers? If it's strictly for analytics, that makes sense and the amount of information would be minimal.

**Comment by tedgin** [comment]
I like this idea. I don't think you'll need a reaper process to clean up after abandoned transfers. The cleanup could be called with the server side of the put detects that the transfer has been abandoned.

**Comment by michael-conway** [comment]
since the 'chunks' in the proposal are iRODS files, hash's could be stored
in iCAT.

Do you think that's a lot of overhead versus one verification hash?  If the
chunk size is regular, all chunks save the last one will have a common icat
length.

I think what state is needed is an open question.  We are trying to develop
this in a way that would run on 4.0.3 and even 3.3.1.

I fully expect this will work, and details can be hashed out.  One thing I
am concerned about is estimating the impact of the presence of these chunks
on existing policies.  I don't think we want these chunks replicated and
assigned DOIs for example.  A solveable problem ,but there is a potential
to pollute policies with these intermediate files.

The upside is that we can solve these nagging transfer reliability and
restart problems on unreliable networks once and for all.

And the same algo would allow us to have chunked transfers for web and REST
based apps.

**Comment by edwins** [comment]
I would say that the benefits to send and verify chunks independently and to truly restart transfers at any point, is probably worth the overhead, though investigation on how other protocols handle the verification of chunked transfers efficiently would be a good idea.

One though, that probably wouldn't be compatible for 3.x deployments, is that by moving to chunked transfers, you could design a transfer scheme that leverages replication resources.  Meaning, let say two or more resources are designated as replicas and have replicas of the file(s) in question, then they could participate in sending different chunks to the client, potentially increasing the transfer performance or at least spreading the transfer load across multiple server.

FYI - I'm supportive of not backporting functionality, unless it's a security or critical feature.

**Comment by xu-hao** [comment]
It seems that one easy way to go forward is starting from the BitTorrent protocol which Edwin mentioned in his comments, and see what we can implement using microservices, etc. I understand that BitTorrent is designed for a different usage scenario, but it seems that there are many elements which are shared between BitTorrent and what we want. Like checksums, stop/resume, parallel transfer, and transfer from multiple replicas. The iCAT server can act as a tracker. We can store the BitTorrent metadata as AVUs on data objects. We can have microservice plugins such as "getUsingBitTorrent" and "putUsingBitTorrent".

**Comment by trel** [comment]
being handled in https://github.com/DICE-UNC/chunky
