### ISSUE TITLE
inconsistent enforcement of zone name validity

### ISSUE THREAD

**Issue by trel** [irods/irods#2706]
a. `validate_zone_name()` currently does not allow periods in the `zone_name`, and allows hyphens.

b. `validate_zone_name()` is not called on `iadmin mkzone` or `iadmin modzone`

c. configuration schema for `server_config.json` does not match that in `validate_zone_name()`

three action items:
 - [x]  `validate_zone_name()` should be changed to allow periods and disallow hyphens
 - [x]  `validate_zone_name()` should be updated to be called everywhere it is relevant
 - [x]  schema should be made consistent to allow periods and disallow hyphens

**Comment by jasoncoposky** [comment]
db_reg_zone_op does call validate_zone_name.  it is also now called in db_mod_zone_op.
