### ISSUE TITLE
Tickets do not handle write-bytes correctly

### ISSUE THREAD

**Issue by tempoz** [irods/irods#2719]
- [x] master
- [x] 4-2-stable
--------

If the bytes written when using a ticket are equal in number to the bytes already on disk, write-bytes is not updated.

**Comment by trel** [comment]
waves at @alanking

**Comment by alanking** [comment]
This is fixed as of changes for #5642 

Should I link this in the commit, @trel?

**Comment by trel** [comment]
yes, please - and then this should be pulled into 4.2.9, right?

**Comment by alanking** [comment]
Yes, I believe that would be appropriate. CI tests are running now so should have results for that shortly.

**Comment by trel** [comment]
checkboxed.
