### ISSUE TITLE
Move handling of log renaming from rodsLog to external service

### ISSUE THREAD

**Issue by kellerb** [irods/irods#2730]
Have rodsLog write to a constant filename.

Rotation, etc. can be provided by external services such as logrotate.

This has the side-effect of making it easier to find the active logs from other programs, e.g. when scanning the log from tests.

**Comment by trel** [comment]
related to  #2112

**Comment by bzizou** [comment]
+1
The filename should be constant, but the location of the logfiles should also be customizable.
It would be also great to provide a default logrotate config file.

**Comment by iychoi** [comment]
I felt the same as @bzizou . How about a existing log libraries such as log4c?

**Comment by bzizou** [comment]
I also noticed that I have a lot of log files into /var/lib/irods/iRODS/server/bin ! 32000 files, 500MB  in a week. Anyway to disable this?

**Comment by jasoncoposky** [comment]
can you provide the list of files in server/bin?

**Comment by bzizou** [comment]
[...]
-rw------- 1 irods irods     273 Sep 18 11:08 9931.log
-rw------- 1 irods irods     273 Sep 18 11:08 9933.log
-rw------- 1 irods irods     273 Sep 18 11:08 9935.log
-rw------- 1 irods irods     273 Sep 18 11:08 9937.log
-rw------- 1 irods irods     273 Sep 18 11:08 9939.log
-rw------- 1 irods irods     273 Sep 18 11:08 9941.log
-rw------- 1 irods irods     273 Sep 18 11:08 9943.log
-rw------- 1 irods irods     273 Sep 18 11:08 9945.log
-rw------- 1 irods irods     273 Sep 18 11:08 9947.log
-rw------- 1 irods irods     273 Sep 18 11:08 9949.log
-rw------- 1 irods irods     273 Sep 18 11:08 9951.log
-rw------- 1 irods irods     273 Sep 18 11:08 9953.log
-rw------- 1 irods irods     273 Sep 18 11:08 9956.log
-rw------- 1 irods irods     273 Sep 18 11:08 9958.log
-rw------- 1 irods irods     273 Sep 18 11:08 9960.log
-rw------- 1 irods irods     273 Sep 18 11:08 9962.log
-rw------- 1 irods irods     273 Sep 18 11:08 9964.log
-rw------- 1 irods irods     273 Sep 18 11:09 9966.log
[...]
And each file contains:
DSN info: DSN='postgres',server='127.0.0.1',port='5433',dbase='icat',user='',passwd='xxxxx'
          onlyread='no',protocol='',showoid='',fakeoidindex='',showsystable=''
          conn_settings='', conn_encoding='(null)'
          translation_dll='',translation_option=''

Seems like a debug file is trigged for each agent?
I'm using irods 4.1.5
Maybe I should have open another issue for that...

**Comment by kellerb** [comment]
I made a new issue for @bzizou 's extra log files here: https://github.com/irods/irods/issues/2898

I'm going to remove those comments (including this one) from this issue.

**Comment by trel** [comment]
similar to https://github.com/irods/irods/issues/2112
