### ISSUE TITLE
irods 4.1.2 (and 4.1.1) install using Ubuntu 14 packages report file conflicts

### ISSUE THREAD

**Issue by daikema** [irods/irods#2738]
Installing the DEBs for irods on an Ubuntu machine I'm getting various errors like the following:

```
Unpacking irods-icommands (4.1.2) ...
dpkg: error processing archive /var/lib/local-packages/./irods-icommands-4.1.2-ubuntu14-x86_64.deb (--unpack):
 trying to overwrite '/usr/share/man/man1/irule.1.gz', which is also in package irods-icat 4.1.2
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Preparing to unpack .../irods-resource-4.1.2-ubuntu14-x86_64.deb ...
Unpacking irods-resource (4.1.2) ...
dpkg: error processing archive /var/lib/local-packages/./irods-resource-4.1.2-ubuntu14-x86_64.deb (--unpack):
 trying to overwrite '/usr/share/doc/irods/RELEASE_NOTES', which is also in package irods-icat 4.1.2
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
```

I've been using a locally built APT repo for the install setup roughly as I outlined in #2422, but this is a dpkg error I'm getting and I think this is unrelated to my use of apt over dpkg.

As a temporary workaround I've added '-o Dpkg::Options::="--force-overwrite"' to my apt-get command as described [here](https://raphaelhertzog.com/2011/08/01/understanding-dpkgs-file-overwrite-error/).

**Comment by kellerb** [comment]
The `icommands` package does not need to be installed on a computer that already has the `irods-icat` package installed. The packages are conflicting because they are attempting to install the same files to the same place.

I have made an issue (#2739) to make this clearer to the user.

**Comment by daikema** [comment]
That might explain one of those issues, but is there any reason why I shouldn't be able to install both irods-icat and irods-resource packages on the same machine (which was the other example conflict reported above)?

**Comment by kellerb** [comment]
I'm sorry I didn't read all the way through the output. The `irods-resource` package also conflicts with the `irods-icat` package in a similar way to the `irods-icommands` package. I will update #2739 to address that as well.

This could be documented more clearly: when installing iRODS on a computer, only one of the following should be performed:

* Install `irods-icat` and a database plugin of the appropriate flavor
* Install `irods-resource`
* Install `irods-icommands`

The development and runtime packages can be installed along any of the above packages.

**Comment by daikema** [comment]
So, to clarify, irods-icat also installs the stuff in the irods-resource package?

(I'd somewhat prefer that irods-icommands handle the installation of the icommands and then be labelled a dependency of the other packages ... but I'm just a user here)

**Comment by kellerb** [comment]
Your clarification is correct.

I agree with your desire for the icommands package to be a dependency of the icat package. That is part of #2739.

**Comment by kellerb** [comment]
Don't worry about being "just a user", users make the world go round :smiley:
