### ISSUE TITLE
There appears to be a typo in core.re shipped in rpm for iRODS 4.1.2

### ISSUE THREAD

**Issue by burnce** [irods/irods#2741]
````
# 18) acPreProcForCollCreate - This is the PreProcessing rule for creating
# a collection. Currently there is no function written specifically
# for this rule.
# acPreprocForCollCreate {writeLine("serverLog","TEST:acPreProcForCollCreate:"++$collName); }
acPreprocForCollCrate { }
````

Last line of quote: Crate --> Create

**Comment by kellerb** [comment]
I am not able to replicate this yet.

Which database plugin are you using?

Is this using CentOS 6?

Are you using the packages linked from http://irods.org/download ?

**Comment by burnce** [comment]
I ran the update using the Centos 6 packages including the postgres 9.3 plugin.

**Comment by trel** [comment]
We cannot find an instance of "Crate" anywhere in the source in 4.0.3 or 4.1.x.

Perhaps it is just a typo?

**Comment by burnce** [comment]
I did not have any reason to edit that line, but I cannot exclude a case of fat fingers in vi while merging my old core.re with the one deployed through the upgrade. I will keep an eye out for this when we upgrade other environments and let you know/. I'm happy to let you close the issue for now.

**Comment by trel** [comment]
Got it - thank you.
