### ISSUE TITLE
CentOS 6 MySQL SSL tests failing with "dh key too small"

### ISSUE THREAD

**Issue by kellerb** [irods/irods#2742]
Need to determine why this is only a problem with the MySQL db plugin.

Tests have been appeased by increasing the size of the key.

https://jenkins.irods.org/job/standalone-test-centos6-mysql/81/

```
error:14082174:SSL routines:SSL3_CHECK_CERT_AND_ALGORITHM:dh key too small
```

**Comment by trel** [comment]
closing - solved for now.
