### ISSUE TITLE
missing runtime dependency for 4.1.0 on OSX 10.7.5

### ISSUE THREAD

**Issue by keithj** [irods/irods#2744]
Running `./plugins/database/packaging/setup_irods_database.sh` on a fresh build I get this error message (having accepted the defaults):

````
Step 4 of 4:  Configuring iRODS user and starting server...
    Updating iRODS user's ~/.irods/irods_environment.json...
    Starting iRODS server...
Could not start iRODS server.
    Starting iRODS server...
Confirming catalog_schema_version... Success
Traceback (most recent call last):
  File "/Users/keith/dev/work/irods.git/iRODS/scripts/python/validate_json.py", line 4, in <module>
    import requests
ImportError: No module named requests
Preflight Check problem:
   JSON Configuration Validation failed.


Install problem:
    Cannot start iRODS server.
Found 0 processes:
        There are no iRODS servers running.

Abort.
````

I guess the build missed a dependency...

**Comment by keithj** [comment]
Having installed `pip` and the Python module `requests`, the script gets further. Installing this dependency should be handled or at least documented as a manual step, I think.

**Comment by keithj** [comment]
A different error is revealed once the script is able to run:
````
Step 4 of 4:  Configuring iRODS user and starting server...
    Updating iRODS user's ~/.irods/irods_environment.json...
    Starting iRODS server...
    Confirming catalog_schema_version... Success
    WARNING: Validation Failed for [/Users/keith/.irods/irods_environment.json] -- jsonschema not installed
    WARNING: Validation Failed for [/Users/keith/dev/work/irods.git/iRODS/server/config/server_config.json] -- jsonschema not installed
    WARNING: Validation Failed for [/Users/keith/dev/work/irods.git/iRODS/server/config/hosts_config.json] -- jsonschema not installed
    WARNING: Validation Failed for [/Users/keith/dev/work/irods.git/iRODS/server/config/host_access_control_config.json] -- jsonschema not installed
    WARNING: Validation Failed for [/Users/keith/dev/work/irods.git/iRODS/server/config/database_config.json] -- jsonschema not installed
    Opening iRODS connection...
    Updating admin user...
    Creating default resource...
        Skipped.  Resource [demoResc] already created.
    Testing resource...

Install problem:
    Cannot remove test file from iRODS:
        ERROR: rmUtil: rm error for /tempZone/home/irods/irods_put_localhost.tmp, status = -807000 status = -807000 CAT_GET_ROW_ERR
Found 0 processes:
        There are no iRODS servers running.

Abort.
````

That test file is certainly in the vault (I checked). Concerned about skipping validation, I installed `jsonschema` and ran the script again:

````
Step 4 of 4:  Configuring iRODS user and starting server...
    Updating iRODS user's ~/.irods/irods_environment.json...
    Starting iRODS server...
    Confirming catalog_schema_version... Success
    Validating [/Users/keith/dev/work/irods.git/iRODS/server/config/database_config.json]... Success
    Opening iRODS connection...
    Updating admin user...
    Creating default resource...
        Skipped.  Resource [demoResc] already created.
    Testing resource...

Install problem:
    Cannot put test file into iRODS:
        ERROR: putUtil: put error for /tempZone/home/irods/irods_put_localhost.tmp, status = -312000 status = -312000 OVERWRITE_WITHOUT_FORCE_FLAG
Found 0 processes:
        There are no iRODS servers running.

Abort.
````

**Comment by keithj** [comment]
I dropped the ICAT database and created it, with the correct `GRANT` for the iRODS database user. I deleted the irods_put_localhost.tmp from the Vault directory manually. I think that should set me up for another clean run of `setup_irods_database.sh`:

Step 4 of 4:  Configuring iRODS user and starting server...
    Updating iRODS user's ~/.irods/irods_environment.json...
    Starting iRODS server...
    Confirming catalog_schema_version... Success
    Validating [/Users/keith/dev/work/irods.git/iRODS/server/config/database_config.json]... Success
    Opening iRODS connection...
    Updating admin user...
    Creating default resource...
        Skipped.  Resource [demoResc] already created.
    Testing resource...

Install problem:
    Cannot get test file from iRODS:
        ERROR: getUtil: get error for irods_get.localhost.tmp status = -312000 OVERWRITE_WITHOUT_FORCE_FLAG
Found 0 processes:
        There are no iRODS servers running.

Abort.
````

So this time it can't `get` the file (because of a local copy in the filesystem that avoids overwriting?!).

**Comment by keithj** [comment]
`cleanAndExit` in `irods_setup.pl` does not clean up its temporary files, leaving them for subsequent runs to fall over, should there be any error.

**Comment by keithj** [comment]
With everything reset (manually deleting the temporary files, manually deleting the file from the vault, dropping and recreating an empty ICAT and granting the correct permissions on that database) I get the first error again:

````
Install problem:
    Cannot remove test file from iRODS:
        ERROR: rmUtil: rm error for /tempZone/home/irods/irods_put_localhost.tmp, status = -807000 status = -807000 CAT_GET_ROW_ERR
````

**Comment by trel** [comment]
More dependencies are now handled for run-in-place by the build.sh script.
