### ISSUE TITLE
4.1.0 - irods_setup.pl mistakenly kills unrelated processes on the same host

### ISSUE THREAD

**Issue by keithj** [irods/irods#2746]
I've been noticing that some of my programs and scripts would die (get killed) unexpectedly. Some were iRODS servers, some were shell scripts or daemons related to iRODS. I tracked down the cause when two iRODS servers (on different) ports, a handful of scripts got taken down at once and a daemon got bounced at the same time.

`irods_setup.pl` tries to find the pid of a running server by looking for a pid file in /tmp. If it doesn't find one it then runs `kill -9` on any and all processes belonging to you on that host having names matching `irods[A|S|R|X]`. This killed two 3.3.1 servers, and scripts called `irodsReporter` etc.

I'm building with `--run-in-place` to test and develop. I shouldn't have to worry about a localised dev install bringing down other services.

**Comment by trel** [comment]
We've updated the approach and are now using `fuser` and checking the fullpath of the binaries involved.

This should exhibit more expected behavior in the presence of multiple other servers/processes.
