### ISSUE TITLE
choose a compiler for 4.2+

### ISSUE THREAD

**Issue by trel** [irods/irods#2758]
Required for:
- the pluggable rule engine
- the new API

Must support:
- C++14
- all current platforms and build flags
- OSX

Candidates include:
- Clang 3.4+
- g++ 4.9+

This will be transparently provided by the build system (CMake #2239).

**Comment by sgworth** [comment]
If you are looking for opinions stay with g++.  More widely available and
used.

**Comment by trel** [comment]
We have selected clang.
