### ISSUE TITLE
add rule priority to delayed rules

### ISSUE THREAD

**Issue by xu-hao** [irods/irods#2759]
- [x] master
- [x] 4-2-stable
----------

This feature defines priority order of execution after time-based selection, it does not create an interrupt-based system for rules to preempt currently/already executing rules.

- [x] `iqmod` can manipulate priority
- [x] `delay` "hints" should support setting `PRI` (varchar in db, but use as integer, larger is higher priority)
- [x] set default priority at `5` for all rules (allows new rules to be defined ahead or behind default)
- [x] `irodsReServer` should sort selected/ready rules by priority for execution
- [x] update documentation (plugins/pluggable_rule_engine/#delay-execution) to include `<PRI>`

- valid priority values will be integers within 1-9, inclusive
- invalid priority values will be set/interpreted as default value of `5`

**Comment by trel** [comment]
@hao, can you write more about what this issue is meant to cover?

And what would be affected?

**Comment by xu-hao** [comment]
Added more details. The only thing that was not clear to me was "upgrade support default rule". (This issue was originally based on a request from Jean-Yves.)

**Comment by trel** [comment]
Okay, this seems to be two separate issues.   Maybe we can break them up...

1) One for the priority system (w/ iCommand support and tests), and
2) the other for naming the delay queue (w/ iCommand support and tests).

I'm not sure what "upgrade support default rule" should mean either, @nief?

**Comment by nief** [comment]
I don't know what it means too :-).
I looked back at the email exchanges with you and Hao and I did not find anything related to this mysterious item: I think you can safely forget about it.

**Comment by trel** [comment]
Okay, I've split this issue into two...

#2759 add rule priority to delayed rules

#3796 add rule name to delayed rules

**Comment by xu-hao** [comment]
thanks

**Comment by trel** [comment]
checkboxes checked.   closing!
