### ISSUE TITLE
Update RPM_INSTALLATION_HOWTO.txt

### ISSUE THREAD

**Issue by kellerb** [irods/irods#2762]
- Need to install [EPEL repository](http://www.rackspace.com/knowledge_center/article/install-epel-and-additional-repositories-on-centos-and-red-hat)
- Explain postgres plugin version 8 vs. 9
- Use `yum localinstall ----nogpgcheck` instead of listing the dependencies for manual install

**Comment by trel** [comment]
This file is out of date - our packaging and newer OS combinations mean this file is no longer necessary.  Any new documentation will be put into the main installation docs.
