### ISSUE TITLE
Remove messaging schema submodule

### ISSUE THREAD

**Issue by kellerb** [irods/irods#2768]
Switch to possibly clone'ing or wget'ing the files from a CMake cache variable url

**Comment by trel** [comment]
We're going to include the single messaging_schema file in the main repository.  No more submodules.

**Comment by korydraughn** [comment]
Did we decide on where this should go?

In a directory of the same name at the same location?
In the configuration schemas v4 directory?
Somewhere else?

**Comment by trel** [comment]
@SwooshyCueb had a very obvious plan, but I do not remember it.

**Comment by SwooshyCueb** [comment]
Definitely not in a directory of the same name. If we can avoid it, we never want to use the path `/irods_schema_messaging` in this repo again.

**Comment by korydraughn** [comment]
The file inside that remote repo is an Avro schema. See https://avro.apache.org/docs/1.6.1/api/cpp/html/index.html.

Placing it in `configuration_schemas/v4` feels wrong (those files follow a different spec). However, creating a new directory in `configuration_schemas` doesn't seem so bad. We'd need to adjust the directory structure to include specification info. For example:
```bash
configuration_schemas/avro/
configuration_schemas/json_schema/v4/
```
This would require some tweaks to the README in `configuration_schemas` (or maybe we just remove the README and other files). The CMake wouldn't need to change anything except the source path used to find the JSON schema v4 files.

Or maybe we just put the file at the root of the project? It is only used as input to `avrogencpp` during compilation. It is not included in any package either.

Is there a better way to do this without creating a new external dependency?

References to `server_control_plane_command.json` in the code:
```bash
$ grep -Inr server_control_plane_command.json
CMakeLists.txt:54:if (NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/irods_schema_messaging/v1/server_control_plane_command.json")
CMakeLists.txt:55:  message(FATAL_ERROR "Missing file: ${CMAKE_CURRENT_SOURCE_DIR}/irods_schema_messaging/v1/server_control_plane_command.json
server/control_plane/CMakeLists.txt:11:  COMMAND "${CMAKE_COMMAND}" -E env LD_LIBRARY_PATH="${IRODS_EXTERNALS_FULLPATH_BOOST}/lib" "${IRODS_EXTERNALS_FULLPATH_AVRO}/bin/avrogencpp" -n irods -o "${CMAKE_CURRENT_BINARY_DIR}/include/irods/server_control_plane_command.hpp" -i "${CMAKE_IRODS_SOURCE_DIR}/irods_schema_messaging/v1/server_control_plane_command.json"
server/control_plane/CMakeLists.txt:12:  MAIN_DEPENDENCY "${CMAKE_IRODS_SOURCE_DIR}/irods_schema_messaging/v1/server_control_plane_command.json"
```

**Comment by trel** [comment]
How about `messaging_schemas` at the top level (alongside `configuration_schemas`), and then... v1/ inside with this single `server_control_plane_command.json` file...

```
/configuration_schemas/v4/*
/messaging_schemas/v1/server_control_plane_command.json
```

Seems... to satisfy our goals?
 - distinct from configuration
 - independently versioned
 - included in irods/irods

**Comment by korydraughn** [comment]
I feel that having multiple top-level directories for schemas is slighly incorrect.

While that would work, why not just have a single top-level directory that contains all different schemas?

This makes it easy for new developers to find any schema they're interested in. It is clear where new schemas should go too.

```bash
/schemas/
/schemas/json_schema/configuration/v4
/schemas/avro
```
... or ...
```bash
/schemas/
/schemas/json_schema/configuration/v4
/schemas/avro/messaging
```

This essentially creates the following directory scheme: `/schemas/<spec>/whatever-directory-structure-you-want`

**Comment by trel** [comment]
I like a single top-level directory...

```
/schemas/<why>/v<n>/<schemafiles>
```

so...

```
/schemas/configuration/v4/*
/schemas/messaging/v1/server_control_plane_command.json
```

I don't see much value (yet?) in naming the spec/flavor of the schema files in the directory structure.

If we change where the configuration schema files live, we'll also have to consider the upgrade path (aka, do we update/edit the existing server_config.json default value to the new default value?).  If it's already non-standard, then we don't touch/upgrade it to the new location.

**Comment by korydraughn** [comment]
I included the spec as a hint to the developer.

When I originally looked at the control plane file, I expected a JSON schema style file, but it looked nothing like that. I was a bit confused. I had to go hunting to see what type of file it was. I only figured it out because I spotted a reference to it on the same line as `avrogencpp`.

As for the upgrade path, I don't think we have to worry about that. We can keep the same structure for now because no other schema files are installed except the v4 schemas. The control plane file we've been discussing here is used only during the compilation process as input to `avrogencpp`. It is never installed.

**Comment by trel** [comment]
oh, so we would install the configuration schema files into the same location via package install?    hmm, that would work, but was not obvious as an option...

so in the repository...

```
/schemas/configuration/v4/*
/schemas/messaging/v1/server_control_plane_command.json
```

and the package installs the configuration files into the same place as they currently do (but now v4)...

```
/var/lib/irods/configuration_schemas/v4/*
```

----

and regarding the spec... can we just include a README.md in the schemas directory to help the future developers?

**Comment by korydraughn** [comment]
That's correct.

> and regarding the spec... can we just include a README.md in the schemas directory to help the future developers?

Sure, that could work. Two questions:
Q. Where will the READMEs live? In the inner most directory? (i.e. one README for each directory containing schema files)
Q. How do we detect when a PR attempts to place a new schema file into the wrong directory?

These questions only really matter if/when we start adding new schema files and types. If we don't feel this is important to handle now, then we can capture this in a separate issue and handle it later.

**Comment by trel** [comment]
i was thinking a single `/schemas/README.md` to describe things.   We can make it as detailed as is useful - perhaps nothing more than to describe the two subdirectories and their specs and designed uses.

If we don't describe exactly every file in there... we don't have to worry too much about a PR adding a new file - but perhaps we can engineer something to help us remember - some CMake magic to count files and assert a number?

**Comment by korydraughn** [comment]
Oh, right. A single top-level README can capture all of those details.

> If we don't describe exactly every file in there... we don't have to worry too much about a PR adding a new file - but perhaps we can engineer something to help us remember - some CMake magic to count files and assert a number?

I'm definitely against describing each file in the README. Describing what a directory contains is the better approach.

I'm sure we can automate the process. My concern with that is the time needed to develop and maintain it. Unless the solution is trivial, I don't feel it is a good use of our time given that things can change and there are simpler solutions that can help the developer (and the core team) understand where things should live.

`/schemas/messaging/v1` is only allowed to contain avro schemas, right?

**Comment by trel** [comment]
> /schemas/messaging/v1 is only allowed to contain avro schemas, right?

I guess so - we only have the one right now, right?

--

And definitely agreed on the automation part - we don't add files very often, I think we're okay.

**Comment by korydraughn** [comment]
Yes. We only have one avro schema afaik.

**Comment by trel** [comment]
Sold.

**Comment by trel** [comment]
re-opening to make changes in github actions - no longer need to pull down submodules
