### ISSUE TITLE
"lsof" may not be in $PATH on CentOS

### ISSUE THREAD

**Issue by kellerb** [irods/irods#2775]
`/usr/sbin/lsof` on CentOS 6 may not be in `$PATH` of `irods` Linux account

Check for lsof in path and error out accordingly if not available.

**Comment by trel** [comment]
I have just tested on a bare-bones CentOS 6 installation, and with the `lsof` package installed (#2772), the new `irods` unix service account had `lsof` in the path.

```
-bash-4.1$ cat /etc/redhat-release 
CentOS release 6.6 (Final)
-bash-4.1$ whoami
irods
-bash-4.1$ pwd
/var/lib/irods
-bash-4.1$ ils
/tempZone/home/rods:
-bash-4.1$ which lsof
/usr/sbin/lsof
-bash-4.1$ echo $PATH
/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin
```

In what scenario did you not find `lsof`?

**Comment by trel** [comment]
add a check before calling `lsof` and complain loudly if not found in the path
