### ISSUE TITLE
build.sh run-in-place detection

### ISSUE THREAD

**Issue by keithj** [irods/irods#2784]
On the stable branch, after the latest fix for detecting run-in-place, I can see another [similar instance](https://github.com/irods/irods/blob/473d6fad9851cdd3cae5e4798f39941d64e1233f/packaging/build.sh#L1081) that looks to me like it won't succeed:

```` bash
# for --run-in-place, also declare the runtime dependencies here
# (otherwise, these would be picked up by the package managers)
if [ "RUNINPLACE" == "1" ] ; then

````

**Comment by trel** [comment]
similar to https://github.com/irods/irods/issues/2781
