### ISSUE TITLE
irods-grid issue on 4.1.3

### ISSUE THREAD

**Issue by nief** [irods/irods#2791]
``` bash
irods-grid status --hosts="ccirods01.in2p3.fr"
[-]     iRODS/clients/icommands/src/irods-grid.cpp:377:main :  status [Unknown iRODS error]  errno [] -- message []
        [-]     iRODS/clients/icommands/src/irods-grid.cpp:243:decrypt_response :  status [Unknown iRODS error]  errno [] -- message []
                [-]     iRODS/lib/core/src/irods_buffer_encryption.cpp:340:decrypt :  status [Unknown iRODS error]  errno [] -- message [failed in EVP_DecryptFinal_ex - error:06065064:lib(6):func(101):reason(100)]
```

hello,
      I have an issue with `irods-grid` on 4.1.3, OS=SL6 (closed to RHEL6).
The client command is ran on the very same server as the iCAT (i.e. `ccirods01`) enabled server.

``` bash
irods-grid  --hosts="ccirods01.in2p3.fr" status
[-]     iRODS/clients/icommands/src/irods-grid.cpp:377:main :  status [Unknown iRODS error]  errno [] -- message []
        [-]     iRODS/clients/icommands/src/irods-grid.cpp:243:decrypt_response :  status [Unknown iRODS error]  errno [] -- message []
                [-]     iRODS/lib/core/src/irods_buffer_encryption.cpp:340:decrypt :  status [Unknown iRODS error]  errno [] -- message [failed in EVP_DecryptFinal_ex - error:06065064:lib(6):func(101):reason(100)]
```

In the log, I see the same kind of error.
thanks,
JY

**Comment by kellerb** [comment]
In `/etc/irods/server_config.json`, there should be an entry for `server_control_plane_key`. Is this the same as the entry `irods_server_control_plane_key` in your `~/.irods/irods_environment.json`?

**Comment by nief** [comment]
yes, that was it. However the origin of the mistake is related to the relocation of irods_environment.json that I did: it was picking up the default one build in the home dir and that is not the one I meant to use. I am using the IRODS_ENVIRNOMENT_FILE or IRODS_ENVIRONMENT_FILE env variable (looks like there is a typo in irodsctl.pl) to point to the correct location of the file. None of them are working.
By the way, irods-grid is a nice feature! It might be good to have a status flag in the message sent to the client in case the irods servers are paused.
cheers,
JY

**Comment by kellerb** [comment]
The environment variable you want is `IRODS_ENVIRONMENT_FILE` (the correctly spelled version).

I tried using `IRODS_ENVIRONMENT_FILE` with `irods-grid` just now, and it appears to be working. Are you setting the environment variable to the full path of the file?

Can you give some more detail on the status flag for paused servers that you mentioned?

**Comment by nief** [comment]
yes, I am providing the full path for the json file for the client. As for the server side, I want to point the json connection file to a given location rather than the default one $HOME/.irods. I was not able to do so, for example by using $irodsEnvFile in irodscl.pl....

As for the status flag thing: I was thinking about the server sending a message to the client saying that is in pause mode. I was thinking that it could be possible to send it to the client using a hook: the server status should be available through a session variable to do it for example.

**Comment by kellerb** [comment]
Pointing an iRODS 4.1+ process (whether it's an icommand or a server) at a different `irods_environment.json` file should be done by setting the `IRODS_ENVIRONMENT_FILE` environment variable.

`irodsctl.pl` is no longer a good source of information for iRODS environment variables.

**Comment by nief** [comment]
I have noticed some references to irods_environment.json. On the server side, should it be located in server/config ?

**Comment by kellerb** [comment]
Are you using a package installation or run-in-place?

**Comment by nief** [comment]
I forgot to mention that I am installing iRODS from scratch with the run-in-place option.

**Comment by kellerb** [comment]
Unless `IRODS_ENVIRONMENT_FILE` is set, an iRODS process will always look for `irods_environment.json` in `$HOME/.irods`.

`irods_environment.json` is the 4.1+ replacement for the `.irodsEnv` file.

**Comment by nief** [comment]
that's what I understood but I was under the impression that it was not working properly.
In server/config/server_config.json, I have:
"environment_variables": {
        "ORACLE_HOME": "/usr/local/oracle/product/11.2.0.3",
        "IRODS_ENVIRONMENT_FILE": "/whatever/irods_environment.json"
    },
I am going to check again and will get back to you on this.

**Comment by kellerb** [comment]
The server loads the environment file before updating its environment with the values in `server_config.environment_variables`. I have made an issue for this here: #2801.

You will need to inject the `IRODS_ENVIRONMENT_FILE` environment variable into the server process manually before launching it (e.g. `export IRODS_ENVIRONMENT_FILE=...`).

Thanks for finding this, this is a tricky order-of-operations issue.

**Comment by nief** [comment]
in order to avoid this easily, the script which is starting the server (irodsctl.pl or whatever replacement to it) could parse the server_config.json in order to catch all the env variables needed to start the server. All the config params (even the env variable) are defined in one place (I guess that is your goal with 4.x) and you solve the issue.

**Comment by trel** [comment]
I don't see any remaining action items here...  @nief, can we close this issue?

**Comment by nief** [comment]
it can be closed.
