### ISSUE TITLE
ipasswd behavior 

### ISSUE THREAD

**Issue by kellerb** [irods/irods#2797]
About **ipasswd** - See issue #3580 as well for recent work and #3910 for related future work. 

For this issue, we are attempting to define the desired behavior, and will update this issue with what the plan is. 

The description previously provided (by me) showing inconsistent treatment of the .irodsA file was inaccurate.  The ipasswd and iinit utilities both zero out the .irodsA file as quickly as they can at runtime, and will overwrite the file with the new password entered (encrypted) regardless of whether or not it is the correct password.

The storing of the encrypted password in .irodsA only takes place from within iinit or ipasswd.

As a workaround, both ipasswd and iinit utilities proide an optional "-v" flag (verbose) which will query the user whether or not the .irodsA file should be written out, and will correctly avoid overwriting the file while the authentication challenges are issued and responded to.

However, the eventual writing out of the file will take place unconditionally after password verification, correct or not.  

I believe this is the desired functionality, with the optional "-v" flag providing users who prefer to be asked, a workaround to the issue originally described here (see below).

Recommend this be closed with no action taken.

**Comment by trel** [comment]
What is the current behavior regarding connecting to a catalog consumer?  Do we issue a nice helpful error?

The other behavior seems okay.

**Comment by andrew-irods** [comment]
Will investigate catalog-consumer operation and report back.

**Comment by trel** [comment]
After investigation, the catalog-consumer operation of `ipasswd` works as expected.
