### ISSUE TITLE
Problem with irods_setup.pl: empty string leads to /psql invocation instead of psql

### ISSUE THREAD

**Issue by kellerb** [irods/irods#2800]
From John Helly on [iRODS Chat](https://groups.google.com/d/msg/irod-chat/tjT-hJAe8F8/q-wVv8bvuyYJ)

---

There are 2 occurrences of this: line 2426 and line 1850. The cause is that `$PSQL` is empty.

**Comment by keithj** [comment]
There was a fix for this in ee93bfe (see #2747) to check for empty $PSQL

**Comment by trel** [comment]
Agreed!

Fixed on 4-1-stable, and master will be refactored to python very shortly.
