### ISSUE TITLE
icp / iput large files (455MB) across zones as differing users throws numThreads error

### ISSUE THREAD

**Issue by donsizemore** [irods/irods#2813]
from Odum Institute on behalf of Reagan Moore, Jon Crabtree (and me) on CentOS 6.6

(4.1.4 preview) client says:

```
ERROR: rcExecMyRule error.  status = -33000 SYS_INVALID_PORTAL_OPR
Level 0: DEBUG: execMicroService3: error when executing microservice
line 38, col 6
      msiDataObjCopy(*Src1,*Dest1,"destRescName=*Res++++forceFlag=", *Status);
      ^
caused by: DEBUG: msiDataObjCopy: rsDataObjCopy failed for /dvnZONE/home/odum_fed/stage/odumdvn_backuppreservation/backups/Fri_Jul_17_2015_dvnBackup.sql, status = -33000
```

(4.1.4 preview) destination rodsLog says:

```
Jul 24 15:13:31 pid:26801 NOTICE: Agent process 7036 started for puser=dvnirods and cuser=odum_fed from 152.2.220.203
Jul 24 15:13:33 pid:7036 ERROR: [-]     iRODS/server/core/src/objDesc.cpp:309:getNumThreads :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message [getNumThreads - failed in get_loc_for_hier_string]
        [-]     iRODS/server/core/src/irods_resource_backport.cpp:665:get_loc_for_hier_string :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message [get_loc_for_hier_string - failed in get_resource_property]
                [-]     iRODS/server/core/include/irods_resource_backport.hpp:50:get_resource_property :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message [failed to resolve resource [resource_property_location]]
                        [-]     iRODS/server/core/src/irods_resource_manager.cpp:50:resolve :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message [empty key]

Jul 24 15:13:33 pid:7036 NOTICE: svrPortalPut: numThreads -2 out of range
Jul 24 15:13:33 pid:7036 NOTICE: readAndProcClientMsg: received disconnect msg from client
Jul 24 15:21:07 pid:7102 NOTICE: recursiveFlag 0
Jul 24 15:21:07 pid:7102 NOTICE: dataObjChksumAndRegInfo - rsModDataObjMeta status 0
Jul 24 15:21:07 pid:7102 NOTICE: rsDataObjChksum - returning status 0
Jul 24 15:21:08 pid:7102 NOTICE: recursiveFlag 0
Jul 24 15:21:08 pid:7102 NOTICE: dataObjChksumAndRegInfo - rsModDataObjMeta status 0
Jul 24 15:21:08 pid:7102 NOTICE: rsDataObjChksum - returning status 0
Jul 24 15:21:09 pid:7102 ERROR: [-]     iRODS/server/core/src/objDesc.cpp:309:getNumThreads :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message [getNumThreads - failed in get_loc_for_hier_string]
        [-]     iRODS/server/core/src/irods_resource_backport.cpp:665:get_loc_for_hier_string :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message [get_loc_for_hier_string - failed in get_resource_property]
                [-]     iRODS/server/core/include/irods_resource_backport.hpp:50:get_resource_property :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message [failed to resolve resource [resource_property_location]]
                        [-]     iRODS/server/core/src/irods_resource_manager.cpp:50:resolve :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message [empty key]

Jul 24 15:21:09 pid:7102 NOTICE: svrPortalPut: numThreads -2 out of range
Jul 24 15:21:09 pid:7102 NOTICE: readAndProcClientMsg: received disconnect msg from client
```

**Comment by donsizemore** [comment]
Reagan would like to add that we first noticed the error using msiDataObjCopy.

**Comment by donsizemore** [comment]
I had been running Terrell's 4.1.4 preview from July 19th, and just updated to Terrell's 4.1.4 preview from July 23rd, but the error persisted.

**Comment by jasoncoposky** [comment]
how would this be reproduced?

**Comment by donsizemore** [comment]
myStagingRule {
# Loop over files in a collection, /dvnZONE/home/dvnbackup
# Put all files into a staging collection
#  /dvnbackup/home/odum_fed/stage
  *Src= "/dvnZONE/home/odum_fed/stage/odumdvn_backuppreservation";
  *Dest = "/OdumStagingZone/home/odum_fed#dfcmain/odumdvn_backuppreservation";
  *Len = strlen(*Src);

#=============get current time, Timestamp is YYY-MM-DD.hh:mm:ss  ======================
  msiGetSystemTime(*TimeH,"human");
  msiGetSystemTime(*TimeA,"unix");

#============ create a collection for log files if it does not exist ===============
  *LPath = "*Src/log";
  isColl(*LPath,*Status);

#============ create file into which results will be written =========================
  *Lfile = "*LPath/Check-*TimeH";
  *Dfile = "destRescName=*Res++++forceFlag=";
  msiDataObjCreate(*Lfile, *Dfile, *L_FD);

#============ find files to stage
  *Query = select DATA_NAME, DATA_CHECKSUM,COLL_NAME where COLL_NAME like '*Src%';
  foreach(*Row in *Query) {
    *File = *Row.DATA_NAME;
    *Check = *Row.DATA_CHECKSUM;
    *Coll = *Row.COLL_NAME;
    *L1 = strlen(*Coll);
    *Src1 = *Coll ++ "/" ++ *File;
    *C1 = substr(*Coll,*Len,*L1);
    *Dest1 = *Dest ++ *C1 ++ "/" ++ *File;
    if(strlen(*C1)==0) {
       *Dest2 = *Dest;
       *Dest1 = *Dest ++ "/" ++ *File;
    } else {
       *Dest2 = *Dest ++ *C1;
    }
      isColl(*Dest2,*Status);
      msiDataObjCopy(*Src1,*Dest1,"destRescName=*Res++++forceFlag=", *Status);
      msiSetACL("default","own","odum_fed#dfcmain", *Dest1);
      msiDataObjChksum(*Dest1, "forceChksum=", *Chksum);
      if (*Check != *Chksum) {
        writeLine("*Lfile", "Bad checksum for file *Dest1");
      }
      else { writeLine("*Lfile", "Moved file *Src1 to *Dest1");
         # Delete file from staging area if checksum is good
         #msiDataObjUnlink("objPath=*Src1++++forceFlag=", *Status);
         writeLine("stdout","Moved file *Src1 to *Dest1");
    }
  }
}
isColl (*LPath,*Status) {
  *Query0 = select count(COLL_ID) where COLL_NAME = '*LPath';
  foreach(*Row0 in *Query0) {*Result = *Row0.COLL_ID;}
  if(*Result == "0" ) {
    msiCollCreate(*LPath, "1", *Status);
    if(*Status < 0) {
      writeLine("serverlog","Could not create log collection");
      fail;
    }  # end of check on status
   writeLine("stdout","*LPath");
  }  # end of log collection creation
}

INPUT *Res=$"dvnbackuphome"
OUTPUT ruleExecOut
