### ISSUE TITLE
iRODS packages for Fedora

### ISSUE THREAD

**Issue by wadudmiah** [irods/irods#2814]
Hello,

Do you have instructions for building iRODS with PostgreSQL?

Thanks in advance,

**Comment by kellerb** [comment]
Which operating system and PostgreSQL version?

**Comment by wadudmiah** [comment]
Hi, this is for Fedora 21 and PostgreSQL 9.3.9. 

Regards,

**Comment by kellerb** [comment]
Have you tried using the CentOS 6 RPM's?

iCAT RPM ftp://ftp.renci.org/pub/irods/releases/4.1.3/centos6/irods-icat-4.1.3-centos6-x86_64.rpm

Postgres 9.3 DB plugin RPM ftp://ftp.renci.org/pub/irods/releases/4.1.3/centos6/irods-database-plugin-postgres93-1.5-centos6-x86_64.rpm

Links come from https://irods.org/download/

If that doesn't work (and please let us know if it doesn't) I'll write up the build procedure tomorrow. We are in the process of redoing the build for 4.2, currently building for a new platform is slightly convoluted.

**Comment by wadudmiah** [comment]
Hi,

Fedora 21 is based on RHEL 7 which is significantly different from RHEL 6 (which is what CentOS is based on). I am trying to build it from source, but the source builds against MySQL as well as PostgreSQL, so I was wondering if there is an option just for PostgreSQL. If not, I will just continue trying to build it for Fedora 21.

**Comment by kellerb** [comment]
Building for a new platform generally has two steps:

* Building the external dependencies
```
cd externals
make generate
```
* Building iRODS proper
```
packaging/build.sh -r icat postgres
```

The externals `Makefile` builds the externals for all database types. I'm guessing that it can be edited to remove the MySQL targets without affecting any of the other targets.

When building the iCAT package for iRODS, the second argument is the database flavor, which should (when given postgres) not build the MySQL portions.

FYI, we are working on a CentOS 7 build for 4.1 (rough estimate, two weeks?), so depending on your time frame and the likelihood of the CentOS 7 RPMs working on Fedora 21, you may be able to wait for that.

**Comment by wadudmiah** [comment]
Hi,

Thanks for all the info. I can wait for the CentOS 7 build or I will try to build for Fedora 21. In no rush for it, so take your time. 

Best regards,

**Comment by trel** [comment]
@wadudmiah you can try to build our master branch now - we are passing tests on CentOS 7.

**Comment by trel** [comment]
related to #2834

**Comment by trel** [comment]
we now have a centos7 package.

**Comment by wadudmiah** [comment]
Hi Terrell,

Thanks for letting me know. I will give it a go installing it on Centos 7.

Regards,

On 26 October 2015 at 15:27, Terrell Russell <notifications@github.com>
wrote:

> we now have a centos7 package.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/irods/irods/issues/2814#issuecomment-151174471>.
>



-- 
web: http://miahw.wordpress.com
mobile: 07905 755604
gnupg: 2E29 B22F
