### ISSUE TITLE
icommands: ensure error messages are printed, and return codes are !=0, if operations are not entirely successful

### ISSUE THREAD

**Issue by carsten-jahn** [irods/irods#2822]
We have observed that there can be situations in which `irsync` and `iget` return without error message, even if they cannot complete their transfers. This has happened with the `-K` switch being present, which should make sure checksums are correct. The user ended up with one incomplete file and multiple missing files on the local file system, when getting data from iRODS using `irsync` or `iget`.

I think there is an open task of reviewing code (e.g. for icommands, maybe also for the server itself) and identifying all situations in which an error message could be obtained from the iRODS peer or the operating system (e.g. networking issue, I/O issue...). Further error handling must ensure that a message is printed to stderr and the command should return with an exit code different to 0. If transfers are interrupted in any way, incomplete files should be deleted on the other end, if possible (for `iget`/`iput` there could be an exception to this rule, if the user specified the resume file option). 

Due to their nature, file systems (on the iRODS server side and on the user side) and networks are not guaranteed to be available all the time. All typical linux tools (even `cat`...) react to I/O errors and print error messages. It is essential that this behavior is adopted in iRODS as well. For user-triggered operations, like a file transfer, it is not sufficient to put errors in the server logfile, since the user might choose to delete local files directly after a transfer to iRODS which looked successful, but wasn't.

This issue is of highest importance to us. It is about the basic capability of iRODS to transfer files, and an organization to not lose data.

**Comment by carsten-jahn** [comment]
Hi Jason, can you add this topic to the upcoming release planning? We've heard that better error handling will be implemented in the next milestone (4.2?), but I can't see any planning for this issue at the moment.

**Comment by jasoncoposky** [comment]
carsten, we had discussed prioritizing icommands for this effort in order to align with your use cases for this request.  can you or one of your team add that list to this issue for planning purposes?

**Comment by carsten-jahn** [comment]
Hi Jason, for us, the most important icommands are: iget, iput, ichmod, ichksum, ifsck and also itrim, irepl (which will get more use in the future).
We don’t use irsync, it does not have many additional capabilities compared to iput and iget (at least in 4.0.3).

**Comment by adetorcy** [comment]
Hi Carsten, I am trying to reproduce your error(s). Do you know if this was observed with single buffer or parallel transfer? Were any other options used? Thanks.

**Comment by carsten-jahn** [comment]
Hi Antoine, first of all I should mention that this happened when the local file system, i.e. the one that iget was writing to, became unavailable for a short period of time. (I've mentioned this in email but found that this piece of information was lacking in my github issue.)
Of course iRODS is not responsible for the local filesystem being unavailable - my point is just that  commands like iget should raise I/O errors and other errors to the user.

This might be difficult to reproduce. I had hoped that you can go through the code and see where filesystem or network calls may fail without any exception being propagated up?

The command used was quite simple: `iget -Kr $IRODS_STUDY_PATH $WORKING_DIR`
Thanks for looking into this!

**Comment by trel** [comment]
Closing - if we need more specific fixes, we can open new issues.
