### ISSUE TITLE
Failure when reading file in fuse mount

### ISSUE THREAD

**Issue by kellerb** [irods/irods#2830]
This appears to affect all reads through FUSE (e.g. `cat`, `mv`, `cp`) of a file from a FUSE mount point.

From [iRODS-Chat](https://groups.google.com/d/msg/irod-chat/B8tok_f027c/GpdB63_6HgAJ):

---

Was having issues with irods 4.1.3 and about to post some debug output from `irodsFs` then noticed that 4.1.4 had just been released with what looks to be some fairly substantial changes to the FUSE driver code.  I just completed an upgrade from 4.1.3 to 4.1.4 on the pair of machines that I've been using as a test platform (both running Ubuntu 14 LTS), but am still having `irodsFs` issues.

New debug logs (running 4.1.4) ends as follows:

```
prog : irodsFs
debug : 1
opt : -odirect_io
mountpoint : /newcalgary
--- snip ---
read[139791186270304] 65536 bytes from 0 flags: 0x8000
   read[139791186270304] 65536 bytes from 0
   unique: 22, success, outsize: 65552
unique: 23, opcode: READ (15), nodeid: 5, insize: 80, pid: 30786
read[139791186270304] 65536 bytes from 65536 flags: 0x8000
   read[139791186270304] 65536 bytes from 65536
   unique: 23, success, outsize: 65552
unique: 24, opcode: READ (15), nodeid: 5, insize: 80, pid: 30786
read[139791186270304] 65536 bytes from 131072 flags: 0x8000
   read[139791186270304] 48259 bytes from 131072
   unique: 24, success, outsize: 48275
unique: 25, opcode: READ (15), nodeid: 5, insize: 80, pid: 30786
read[139791186270304] 65536 bytes from 179331 flags: 0x8000
irodsFs: /home/irodsbuild/irods/iRODS/clients/fuse/src/iFuse.BufferedFS.cpp:579: int iFuseBufferedFsRead(iFuseFd_t*, char*, off_t, size_t): Assertion `curSize > 0' failed.
```

**Comment by kellerb** [comment]
When all of the readable bytes in the current buffer have been read (aka `blockSize == inBlockOffset`), which occurs when the read offset equals the file size, [this assert](https://github.com/irods/irods/blob/4.1.4/iRODS/clients/fuse/src/iFuse.BufferedFS.cpp#L579) will fail. When this happens, we should be returning 0 instead of asserting. Returning 0 informs the caller of EOF.

This was missed in testing because all of our file reads were on files with sizes multiples of 1 MiB. When this is the case, [_readBlock()](https://github.com/irods/irods/blob/4.1.4/iRODS/clients/fuse/src/iFuse.BufferedFS.cpp#L559) returns 0, which triggers early exit.

**Comment by daikema** [comment]
Thanks for tracking this down.

Is this issue the likely cause for failures with both 4.1.3 and 4.1.4 despite the somewhat different symptoms?

Am I correct that most files not a multiple of 1 MiB will likely cause this same failure?

**Comment by kellerb** [comment]
> Is this issue the likely cause for failures with both 4.1.3 and 4.1.4 despite the somewhat different symptoms?

4.1.3 fuse is most likely failing for an unrelated reason.

> Am I correct that most files not a multiple of 1 MiB will likely cause this same failure?

Yes. In fact, I expect this failure to occur for *all* files not a multiple of 1 MiB.

I have a candidate fix for this locally and am currently adding more tests to the fuse suite. We are working towards another 4.1 point release to add support for building iRODS on POWER8 for IBM. I expect the POWER8 work to be finished in the short term, and the plan is to roll this fix in with that release.

If you are interested, I can give you an engineering build (4.1.4 + this fix) of the fuse client (`irodsFs`) for testing. You would just need to copy it over the current version (located at `/usr/bin/irodsFs`).

**Comment by daikema** [comment]
> 4.1.3 fuse is most likely failing for an unrelated reason.

Hopefully nothing that'll crop up again - seemed to be some pretty extensive changes to the FUSE driver which was why I was a bit surprised to see them both failing.

> If you are interested, I can give you an engineering build (4.1.4 + this fix) of the fuse client (irodsFs) for testing. You would just need to copy it over the current version (located at /usr/bin/irodsFs).

That would helpful.  Thanks.

**Comment by kellerb** [comment]
[Here](http://people.renci.org/~kellerb/ubuntu14_irods4.1.4wfix_fuse_client/irodsFs) is an engineering build of the fuse client for Ubuntu 14.04.

You should be able to just copy it on top of `/usr/bin/irodsFs`.

It passed the new battery of tests. Please let us know if you run into anything. We appreciate you testing this out.

**Comment by daikema** [comment]
Thanks.  Downloaded the fix and after putting it on a test VM and poking around at a few files, the files on the FUSE mount remain accessible.  Will let you know if I encounter more issues with it.
