### ISSUE TITLE
PAM authentication fails when password contains "=" or ";"

### ISSUE THREAD

**Issue by kellerb** [irods/irods#2835]
`rsAuthPluginRequest()` takes an `authPluginReqInp_t` whose `context_` member is a string-encoded `keyValPair_t` (i.e. uses `=` to separate keys from values and `;` to separate successive key-value pairs).

`libpam.cpp`'s implementation of `AUTH_AGENT_AUTH_REQUEST` calls [parse_kvp_string](https://github.com/irods/irods/blob/4.1.4/plugins/auth/pam/libpam.cpp#L385), which fails when the associative token (`=`) or delimiter token (`;`) are present in the value (i.e. the password).

Plan for the fix is to have `rsAuthPluginRequest()`'s `context_` argument be an escaped-string-encoded `keyValPair_t`, using `\` as the escape character.

[Reported on iRODS-Chat](https://groups.google.com/d/msg/irod-chat/5RNi8vCq0eM/2-pdNt_VIAAJ)

---

Password contains `=`
in rodsLog:

```
Aug 12 09:09:00 pid:15940 ERROR: [-]    iRODS/server/api/src/rsAuthPluginRequest.cpp:85:rsAuthPluginRequest :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message []
    [-] libpam.cpp:395:pam_auth_agent_request :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message [user or ttl or password key missing]
```

on command line:

```
[-]     libpam.cpp:243:pam_auth_client_request :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message [call to rcAuthRequest failed.]
 failed with error -130000 SYS_INVALID_INPUT_PARAM
```

Password contains `;` 
in rodsLog:

```
Aug 12 09:07:25 pid:15519 ERROR: [-]    iRODS/server/api/src/rsAuthPluginRequest.cpp:85:rsAuthPluginRequest :  status [PAM_AUTH_PASSWORD_FAILED]  errno [] -- message []
    [-] libpam.cpp:410:pam_auth_agent_request :  status [PAM_AUTH_PASSWORD_FAILED]  errno [] -- message [pam auth check failed]
```

on command line:

```
[-]     libpam.cpp:243:pam_auth_client_request :  status [PAM_AUTH_PASSWORD_FAILED]  errno [] -- message [call to rcAuthRequest failed.]
 failed with error -993000 PAM_AUTH_PASSWORD_FAILED
```

**Comment by mihondo** [comment]
We still see this problem on 4.1.6 and 4.1.9 when logging into irods via PAM.

The following characters still cannot be in the password:   @, &, =, and ;  (at, ampersand, equals, and semicolon).

**Comment by burnce** [comment]
Hello, we also appear to have hit this issue:

```
 ERROR: [-]     iRODS/server/api/src/rsAuthPluginRequest.cpp:85:rsAuthPluginRequest :  status [SYS_BAD
_INPUT]  errno [] -- message []
        [-]     libpam.cpp:399:pam_auth_agent_request :  status [SYS_BAD_INPUT]  errno [] -- message []
                [-]     iRODS/lib/core/src/irods_kvp_string_parser.cpp:172:parse_escaped_kvp_string :  status [SYS_BAD_INPUT]
 errno [] -- message [unescaped _assoc token encountered in key or value]

```

**Comment by trel** [comment]
Placing this back into 4.1.5 - the original commits were included in that release.

I have opened #3528 for any new work.
