### ISSUE TITLE
Memory leak at clearDataObjSqlResult at miscUtil.cpp

### ISSUE THREAD

**Issue by iychoi** [irods/irods#2837]
Hi, 

Current implementation of fuse uses `rclOpenCollection`/`rclReadCollection`/`rclCloseCollection` functions.
Within these functions, `collHandle_t.dataObjSqlResult.resc_hier.value` field is set to have a pointer to a heap memory (`malloc`'d) and this isn't `free`'d during `clearDataObjSqlResult` function called by `rclCloseCollection`. Also, `dataType` field in the `DataObjSqlResult` structure is not handled.

This caused small memory leak on running iRodsFuse.

**Comment by kellerb** [comment]
Thanks for reporting this. Do you have a commit that fixes this in your repo?

**Comment by iychoi** [comment]
No I didn't fixed it on the same file in my repo since I don't know whether
it is intended for some reasons or missed mistakenly. But I manually
freed it at the fuse side.

**Comment by kellerb** [comment]
We are going to fix this by adding the two missing `free()`'s (`resc_hier.value` and `dataType.value`) to `clearDataObjSqlResult()`

**Comment by iychoi** [comment]
Thanks!
