### ISSUE TITLE
setup_irods.sh should check for presence of home directory and abort

### ISSUE THREAD

**Issue by kript** [irods/irods#2839]
I know this is a bit of an edge case, but its affected our testing somewhat.. For historical/histerical reasons, we have the home directory for our irods user set to `/usr/local/iRODS` When installed 4.1.4 from ubuntu12 packages, I found the `setup_irods.sh` script would get as far as step 2 and fail, because that directory didn't exist on that server (yet);

```
Step 2 of 4:  Creating database and tables...
    Checking whether iCAT database exists...
        [ICAT] on [localhost] found.
    Updating user's .odbc.ini...
        Touching... /.odbc.ini
        Skipped.  File doesn't exist. - /.odbc.ini
    Creating iCAT tables...
        Skipped.  Tables already created.
    Testing database communications...

Configuration problem:
    Communications with the database failed.
        ERROR: cllConnect: SQLConnect failed: -1
        ERROR: cllConnect: SQLConnect failed:odbcEntry=postgres,user=irods,pass=XXXXX
        ERROR: cllConnect:          SQLSTATE: IM002
        ERROR: cllConnect:  Native Error Code: 0
        ERROR: cllConnect: [unixODBC][Driver Manager]Data source name not found, and no default driver specified 
        userName=irods
        password=XXXXX
        cllConnect failed with error -1.
```

Creating and chwoning the directory to irods allows the installation to continue, but I suggest the script should check for the homedir and that it can write a file there or fail early on.

**Comment by trel** [comment]
Earlier detection done by #2917
