### ISSUE TITLE
Define meaning of '&' in ils output in help.

### ISSUE THREAD

**Issue by kript** [irods/irods#2840]
- [x] master
- [x] 4-2-stable
---------

I recently found out about the meaning of the `&` in the `ils -l` output; i.e. that it is a clean replica. Can information about this be added to the man/-h page please?

**Comment by mcast** [comment]
When this information is written, please can it also note that "clean replica" means cleanly written to the filesystem. It does not mean that all data has reached permanent storage!

I've just cleaned up 91 files which went through a cycle like this,
1. they had two replicas, one each in trees named `green` and `purple`; purple is a migration-out tree for retiring hardware, and in this case the resource was formerly a member of the `red` tree.
2. we were doing large numbers of `irepl -Rred ...` including these 91 files, to copy to newer hardware in the `red` tree
3. power failure in a rack brought down multiple hosts without warning
4. built in RAID controller protection seems to have been... not completely protective
    * one RAID controller gave an error upon its return, that the cache battery was unhealthy
    * another RAID controller gave no error condition
    * @kript supposed this may be because files were in the OS cache before hitting the RAID controller's cache. He might have more info about exactly what happened, but it's probably not relevant to this issue.
5. `ifsck` of the erroring host turned up 36 broken files, `ichksum` of files modified on the second in a 2hr time window before turned up 55 more.
    * all these files were ~1430 bytes long; this might be coincidence
    * the majority were found in the `unixfilesystem` vault to have zero bytes, but some were simply absent (`UNIX_FILE_OPEN_ERR, No such file or directory`)
    * I don't have a record for all of them, but the majority where I have terminal scrollback show `&` in `ils -L` output. *The iCAT thought they were valid copies.*
6. cleanup generally is to trim the bad replica, take a new one and then `ichksum` again
    * in this context of ongoing migration: `irepl -Sgreen -Rpurple $file` got a second copy before `itrim`ming from red, then it went around migration again

I think we'll be going round the `fsync` conversation again. 😁

**Comment by trel** [comment]
Definitely.

The intermediate replica status should make navigating the above scenario much easier if/when it happens again.
