### ISSUE TITLE
The distributed version of irods-auth-plugin-krb (version 1.1) is not compatible with iRODS 4.1.x

### ISSUE THREAD

**Issue by ilarik** [irods/irods#2849]
Just a reminder and a wish to get the irods-auth-plugin-krb-1.2 distributed by RENCI as CentOS 6 RPM.
Apparently there's an incompatiblity with the boost library versions between iRODS 4.0.x and iRODS 4.1.x or something?

The updated module itself builds great from the github repo source code and produces a fully working RPM package, this was great. Currently I'm building the package from our Jenkins which gets your repo and builds the RPM package inside a Docker container and spits out the RPM package and deploys it into my local package repo :)

**Comment by jasoncoposky** [comment]
We intend to bring this up to date and release a new version for the iRODS 4.1.x series as soon as it is brought into our new CI system.  We are working to spin up the GSI environment in our cloud system first then will work on the Kerberos next.  Just an FYI, you can use the issue tracker for the Kerberos repository for related issues.

Thanks!
