### ISSUE TITLE
iticket occasionally generates malformed ticket ids

### ISSUE THREAD

**Issue by tedgin** [irods/irods#2854]
`iticket` generated a single character ticket. When trying to use `iticket ls` to display it no results occur. Here's an example.

```
-bash-4.1$ iticket create write /iplant/home/qa-user/DataStore_Regression/ACL_Issue/nexus/Basic.nex
ticket:2
-bash-4.1$ iticket ls 2
-bash-4.1$
```
Two asides:
1) Should single character tickets be allowed?  It seems those would be easy to guess, reducing the security of the ticket.
2) The iticket documentation still states that it generates 16 character tickets. Please update the docs.

**Comment by trel** [comment]
Thanks @tedgin - what version of iRODS/iticket is this?

**Comment by tedgin** [comment]
This is iticket version 4.1.4 interacting with iRODS version 4.1.4.

**Comment by trel** [comment]
Can you look into the database and see the stored string?  I expect there may be a null character...

I have not been able to reproduce this locally, yet.

**Comment by trel** [comment]
Nevermind - we've identified the problem - A random null (or other non-printable character) may be returned within the string.

https://github.com/irods/irods/blob/4-1-stable/iRODS/clients/icommands/src/iticket.cpp#L495

**Comment by trel** [comment]
And we'll update the help text to be correct.

**Comment by kellerb** [comment]
From the commit fix message:
> `buf1` was modulo'd to find an offset into an array of printable
characters, but `buf1` was of type (`char[]`), and `char` behaves as `signed`
on x86, and e.g. `-15 % 62` is `-15`. The negative number was indexing
the array of printable characters and returning whatever happened to
be on the stack in that location.
