### ISSUE TITLE
packaging build script uses very slow find for locating things

### ISSUE THREAD

**Issue by seandavi** [irods/irods#2861]
I'm not sure what the best approach is here, but the current build script seems to use the linux/unix find command to look for specific files. On our system, the /usr tree contains 10's of millions of files, for example, so find for "Python.h" for example finds literally hundreds of examples and runs for 12 hours.  I know this may be a local system issue, but it does essentially preclude irods from being built on this system.  Are there alternatives?

**Comment by trel** [comment]
Acknowledged.

The short answer is no, for now.

We're moving to CMake ASAP (https://github.com/irods/irods/issues/2239), and the `find` will be replaced with something more standardized.  CMake is currently on the boards for 4.2.

**Comment by trel** [comment]
You may also be able to manipulate the particular `find` that is slow, and make it more targeted to where you know the `Python.h` (among others) are already located.

**Comment by seandavi** [comment]
Thanks. CMake should be a nice improvement.
