### ISSUE TITLE
Runtime libraries are linked improperly

### ISSUE THREAD

**Issue by AndreyNevolin** [irods/irods#2867]
Client library `libirods_client.so` cannot by loaded at runtime because of the following error:

```
[/usr/lib/libirods_client.so.1: undefined symbol: _ZNK5boost15program_options29value_semantic_codecvt_helperIcE5parseERNS_3anyERKSt6vectorISsSaISsEEb]]
```

Demangled version of the symbol:
```
boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const
```

The error occurs because `program_options` Boost library is used inside `iRODS/lib/core/src/irods_parse_command_line_options.cpp` but is not linked explicitly with the iRODS client library.

The error is reproduced with iRODS version 4.1.5

**Comment by jasoncoposky** [comment]
I am guessing this library is loaded from a resource plugin?

Until we get the client and server libraries properly separated from 
the server build we recommend that the get_plugin_interface() free
function is defined locally within the plugin, which removes the need
to link against the libraries.

**Comment by AndreyNevolin** [comment]
> I am guessing this library is loaded from a resource plugin?

True

>  we recommend that the get_plugin_interface()  free function is defined 

What's this? How is it used?

**Comment by kellerb** [comment]
I, and @adetorcy while working on the [gsi plugin](https://github.com/irods/irods_auth_plugin_gsi), have replicated the issue. Options for fixing are:

1. Removing `irods_parse_command_line_options.o` from `libirods_client.so`
2. Linking `libirods_client.so` against `libboost_program_options.a` (or `.so`)

The creation of `libirods_client.so` occurs [here](https://github.com/irods/irods/blob/4.1.5/packaging/make_irods_dev_archive.sh#L43).

**Comment by trel** [comment]
We will be implementing option 1 above.
