### ISSUE TITLE
normal operation ports... only 1247 or also 1248

### ISSUE THREAD

**Issue by agreif** [irods/irods#2870]
Hi, 

I found a discrepancy in the needed ports for an iRODS installation:

ftp://ftp.renci.org/pub/irods/releases/4.0.3/RPM_INSTALLATION_HOWTO.txt

        Add the following to your /etc/sysconfig/iptables:
        -A INPUT -m state --state NEW -m tcp -p tcp --dport 1247 -j ACCEPT

http://irods.org/wp-content/uploads/2015/06/GettingStartedwiRODS4.1.pdf

        iRODS servers use a number of ports for network communication. By default, these are:
        1247 and 1248 for normal operation

Now, are both ports needed, or only 1247?

thanks,
Alex.

**Comment by trel** [comment]
You are correct - both are needed for normal operation.

1247 is the traditional iRODS port for handshakes and data transfer.

We added the control plane in 4.1.0 and that uses port 1248 by default.

You will need to add a separate line for opening 1248 in any iptables configuration.
