### ISSUE TITLE
Warnings "jsonschema too old v[0.2]" when starting server from fresh 4.1.5 install

### ISSUE THREAD

**Issue by bzizou** [irods/irods#2872]
When we start an iserver from a fresh install from package irods-resource-4.1.5-ubuntu12-x86_64.deb, even after initialization (/var/lib/irods/packaging/setup_irods.sh), we get the following warnings:

```
Starting iRODS server...
WARNING: Validation Failed for [/home/irods/.irods/irods_environment.json] -- jsonschema too old v[0.2]
WARNING: Validation Failed for [/etc/irods/server_config.json] -- jsonschema too old v[0.2]
WARNING: Validation Failed for [/etc/irods/hosts_config.json] -- jsonschema too old v[0.2]
WARNING: Validation Failed for [/etc/irods/host_access_control_config.json] -- jsonschema too old v[0.2]
```
Same thing with the icat.

**Comment by trel** [comment]
Yes, these are warnings - not errors.  The server is still working, you just cannot validate using the older library.

If you were to install a newer jsonschema (or install on Ubuntu 14), the validation would succeed.
