### ISSUE TITLE
Provide ability to modify META_COLL_ATTR_UNITS

### ISSUE THREAD

**Issue by rwmoore** [irods/irods#2896]
Needed for modifying tag metadata

**Comment by rwmoore** [comment]
Using the iPlant collaborative micro-service
          msiSetAVU ("-d", *Dest1, *Attn, *Attv, *Attu);

**Comment by d-w-moore** [comment]
Now modifying the 3.x microservice **msiSetAVU** to wrap **rsModAVUMetadata** with a microservice
```
msiModAVUMetadata( *objectType, *objName, *operation, *attName,*attValue,*attUnits )
```
where operation can be one of `add`, `set`, `rm`, or `rmw`. Planning it as part of the 4.2.7 release.

**Comment by trel** [comment]
Done in https://github.com/irods/irods/issues/4521
