### ISSUE TITLE
password visible in debug log while using PAM and SSL

### ISSUE THREAD

**Issue by trel** [irods/irods#2902]
- [x] main
- [x] 4-2-stable
---
found by @michael-conway 

> In rodsLog...
> 
> ```
> received header: len = 135
> <MsgHeader_PI><type>RODS_API_REQ</type><msgLen>132</msgLen><errorLen>0</errorLen><bsLen>0</bsLen><intInfo>1201</intInfo></MsgHeader_PI>
> received msg: 
> <authPlugReqInp_PI><auth_scheme_>PAM</auth_scheme_>
> <context_>a_user=mconway;a_pw=mypasswordhere;a_ttl=0</context_>
> </authPlugReqInp_PI>
> ```

**Comment by trel** [comment]
This is intended behavior when debugging is turned on.

**Comment by Pete-C** [comment]
May we request that this not be the case for auditing purposes. It would be unfortunate to be in the position of having to pass on logs that may include debug and hence password details within our logs :)Pete 

    On Tuesday, 16 February 2016, 18:08, Terrell Russell <notifications@github.com> wrote:
 

 This is intended behavior when debugging is turned on.—

**Comment by trel** [comment]
Fair enough - reopening.

**Comment by jasoncoposky** [comment]
We will skip logging XML which include `authPlugReqInp_PI` and `PAM`.  If you find any other thing that need skipped, please open another ticket.

**Comment by Pete-C** [comment]
Thanks for looking at this 

    On Wednesday, 17 February 2016, 15:19, Jason M. Coposky <notifications@github.com> wrote:
 

 We will skip logging XML which include authPlugReqInp_PI and PAM. If you find any other thing that need skipped, please open another ticket.—

**Comment by trel** [comment]
Need to confirm this is still happening, and if so - remove the XML logging with any `authPlugReqInp_PI` or `PAM` information.

**Comment by korydraughn** [comment]
Confirmed this information is still shown on the client and server side.

Reproduced using the following steps:
1. configure SSL
2. configure PAM
3. set `irods_log_level` in irods_environment.json to 8
4. call `irodsProt=1 init` and enter password

**Comment by korydraughn** [comment]
@alanking Please add the checkboxes for this issue. Thanks!

**Comment by alanking** [comment]
Done. Please confirm that this is in the right milestone and close
