### ISSUE TITLE
error building zeromq on Mac OS X

### ISSUE THREAD

**Issue by jerry57** [irods/irods#2916]
I am trying to build icommands for Mac OS X (10.10.4)

I am seeing the following error in the stdout:

```
make[4]: Nothing to be done for 'all'.
Making all in src
configure: error: cannot find install-sh, install.sh, or shtool in config "."/config
[ 41%] make[4]: Nothing to be done for 'all'.
```

Ultimately it ends with:

```
The following directory should be added to linker library paths:

    /Users/jerry/trunk/irods/external/boost_1_58_0z/stage/lib

make: *** [external] Error 2
```

Tried attaching full output as .txt and .pdf, but every time I get:

```
Something went really wrong, and we can't process that file.  Try again.
```

**Comment by trel** [comment]
I just did a clean installation on 10.10.5 - and it succeeded.

Can you try to run `make` again in the external directory, without any multiple jobs... and the error will not be interleaved with other success.

**Comment by jerry57** [comment]
What do you mean by "external directory"?  Also, you want me to run make and not "./packaging/build.sh --run-in-place icommands"?

**Comment by trel** [comment]
Sorry - the `packaging/build.sh` script pulls down a bunch of software into `irods/external` which is then built directly with it's own `irods/external/Makefile`.

Now that the build is prepped, you should be able to drop into that external directory and run make directly.

```
$ cd external
$ make
```

Then, the `./packaging/build.sh --run-in-place icommands` from the top level should get further (since the externals will all be satisfied).

**Comment by trel** [comment]
By default, our `build.sh` uses the multiple jobs (-j) option of `make`, and will interleave all the stdout, making it harder to read.

Running a singular `make` will help debug the problem.

**Comment by jerry57** [comment]
ah, now I understand  Will give this a try and let you know.
./packaging/build.sh --run-in-place icommands
when that fails
cd external
make
cd ../
./packaging/build.sh --run-in-place icommands

Hopefully will make it through all this :)

**Comment by jerry57** [comment]
ended with Error 1

[100%] Build target avrogencpp
configure: error: cannot find install-sh, install.sh, or shtoo in config "."/config
maek: *** [zeromq-4.1.0/Makefile] Error 1

brew install shtool     shows:
Warning: shtool-2.0.8 already installed

**Comment by jerry57** [comment]
I have tried various iterations of make, make generate, make clean etc in the external directory and no joy.  Here is my latest fail:

zeromq-4.1.0.tar.gz              100%[============================================================>]   1.31M  1.75MB/s   in 0.7s   

2015-09-30 15:29:25 (1.75 MB/s) - 'zeromq-4.1.0.tar.gz' saved [1369267]

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I config --force -I config
autoreconf: configure.ac: tracing
autoreconf: configure.ac: subdirectory foreign/openpgm/build-staging/openpgm/pgm/ not present
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoconf --include=config --force
configure.ac:57: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:58: error: possibly undefined macro: AC_PROG_LIBTOOL
configure:5386: error: possibly undefined macro: AC_DISABLE_STATIC
configure:5390: error: possibly undefined macro: AC_ENABLE_STATIC
autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1
autogen.sh: error: autoreconf exited with status 0
make: *** [zeromq-4.1.0/configure] Error 1

**Comment by trel** [comment]
I think this is the secret key...

```
autoreconf: configure.ac: not using Libtool
```

try

```
$ brew install libtool
```

**Comment by jerry57** [comment]
okay, I did a completely new clean OS install,
installed OSXFuse
Installed XCode and activated it
Installed Brew
brew installed wget help2man mysql pcre libtool
did a "git clone https://github.com/irods/irods"
cd irods
git submodule init ; git submodule update
./packaging/build.sh --run-in-place icommands

Now getting:
./packaging/build.sh --run-in-place icommands

+------------------------------------+
| RENCI iRODS Build Script           |
+------------------------------------+
Fri Oct  2 10:24:16 MST 2015

--run-in-place detected -- Building for in-place execution

Detecting Build Environment
Detected Packaging Directory [/Users/jerry/trunk/irods/packaging]
Build Directory set to [/Users/jerry/trunk/irods]
Detected iRODS Version to Build [4.2.0]
Detected iRODS Version Integer [4002000]
Detected OS [MacOSX]
Detected OS Version [10.10.5]
Detected curl [/usr/bin/curl] v[7.43.0]
Detected wget [/usr/local/bin/wget] v[1.16.3]
Detected help2man [/usr/local/bin/help2man] v[1.47.2]
Detected libfuse library [/usr/local/include/osxfuse/fuse/fuse.h
/usr/local/include/osxfuse/fuse.h]
#######################################################
ERROR :: build.sh requires some software to be installed







      :: download from: http://curl.haxx.se/download.html      :: download from: http://www.bzip.org/downloads.html      :: download from: http://zlib.net/      :: download from: http://sourceforge.net/projects/openpam/files/openpam/      :: download from: http://www.openssl.org/source/      :: download from: http://www.xmlsoft.org/downloads.html      :: download from: http://web.mit.edu/kerberos/dist/index.html
#######################################################

**Comment by jerry57** [comment]
It appears that using XCode 7 or Command Line Tools 7 is a problem.  I was able to build the master by following these instructions:

Currently there is no binary bundle to download and install.  You must build the icommands from source for Mac OS X


install XCode and activate
(appears that v6.4 of XCode works, v7.0 does not)
Install from AppStore
Run app at least once to activate
from:  https://developer.apple.com/downloads/
download and install using defaults:  Command_Line_Tools_OS_X_10.10_for_Xcode_6.4.dmg
I actually installed only commandline tools v6.4 but have also built with XCode 6.4 on other systems.


install OSXFuse
---------------
http://osxfuse.github.io
Download latest stable dmg
I installed osxfuse-2.8.1.dmg
run/install pkg and accept defaults


Install Brew (I used a test system so I could remove brew)

ruby -e "$(curl) -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew install wget help2man mysql pcre libtool


to build 4.1.x you have to install JSON.pm
brew isntall cpanm
sudo cpan JSON
(you will be prompted to configure cpan and then it will install JSON.  Just accept defaults)
(you may have to do the sudo cpan JSON twice to get it to actually install JSON module)

The above it NOT required to build 4.2.x or above


cd $HOME/trunk

git clone https://github.com/irods/irods
cd $HOME/trunk/irods
git submodule init ; git submodule update


cd $HOME/trunk/irods
./packaging/build.sh --run-in-place icommands

Appears to end with ERROR #2

cd external
make clean ; make
(note I had to run make at least twice to get a clean build without make clean in there)
(brew install autoconf automake)
(make clean ; make)
cd ..
./packaging/build.sh --run-in-place icommands

NOTE:
I did have to run "make clean ; make" or "make" several times in the external directory.  Once it built without error then I could backup to top level and build the actual icommands.  Have yet to test them all out though.

**Comment by trel** [comment]
closing - not targeting mac builds anymore.
