### ISSUE TITLE
compound resource should re-stage data from archive to cache

### ISSUE THREAD

**Issue by jasoncoposky** [irods/irods#2918]
this will be implemented as a configurable policy by a key-value within the context string

**Comment by cookie33** [comment]
HI,

I don’t think this extra step is needed. Especially when I saw that in iRODS 4.1.6 a “stat" is done to check the status of a just copied file. The sequence for a put in iRODS 4.1.6 is:
mkdir <directory>
chmod <directory>
syncToArch <input_file> <output_file>
chmod <output_file>
stat <output_file>

This should suffice. Copying it back will make the process slower. Especially if you have big files.

Greetings,

Robert Verkerk

**Comment by jasoncoposky** [comment]
ok, thanks.  closing.
