### ISSUE TITLE
add -r option to ireg

### ISSUE THREAD

**Issue by trel** [irods/irods#2919]
This is for consistency with the rest of iRODS.

`-r` should mean recursive and replace the functionality of the current `-C` option.

The `-C` option should remain in the code, but marked as deprecated.

**Comment by alanking** [comment]
Should we mark `-C` as deprecated in 4.2.12?  I'm wondering if that would be too later, and the removal of `-C` should be a 4.4.0 issue, with deprecation occurring in 4.3.0. Thoughts?

**Comment by trel** [comment]
well, we won't actually remove the `-C`.   just... not talk about it anymore.

**Comment by alanking** [comment]
Ah, I didn't read that very carefully. Got it

**Comment by trel** [comment]
i'm fine with removing things - but not sure of the upside in this case.

**Comment by alanking** [comment]
Leaving a note here...

The `-C` option actually accepts a value (see https://man7.org/linux/man-pages/man3/getopt.3.html)

> optstring is a string containing the legitimate option
       characters.  A legitimate option character is any visible one
       byte [ascii(7)](https://man7.org/linux/man-pages/man7/ascii.7.html) character (for which [isgraph(3)](https://man7.org/linux/man-pages/man3/isgraph.3.html) would return
       nonzero) that is not '-', ':', or ';'.  If such a character is
       followed by a colon, the option requires an argument, so getopt()
       places a pointer to the following text in the same argv-element,
       or the text of the following argv-element, in optarg.

This whole time, `-C` has actually been placing the physical path which follows it in the `collectionString` of the `rodsArgs` struct. This is never used in any of the iCommands, so it has largely gone unnoticed.

**Comment by alanking** [comment]
Wait... wrong again. Dang.

That is the default optstring when none is provided by the caller. `ireg` provides an optstring, and `C` does not have a colon:
https://github.com/irods/irods_client_icommands/blob/6b2b0285ce5f1cabd7e022767fd47bae9a536fbe/src/ireg.cpp#L31

Please disregard
