### ISSUE TITLE
Can't locate JSON.pm in @INC (you may need to install the JSON module)

### ISSUE THREAD

**Issue by jerry57** [irods/irods#2922]
I am trying to build icommands.  I have a system where I can build the master (4.2.0) just fine, but when I try to build either 4.1.5 or 4.1.6, I get the above error:

```
git clone https://github.com/irods/irods
cd irods
git submodule init ; git submodule update
./packaging/build.sh --run-in-place icommands
```
all builds without error

```
git checkout 4.1.5 or 4.1.6
git submodule init ; git submodule update
make clean
./packaging/build.sh --run-in-place icommands

-------------------------------------
Detected CPUs:    2
Compiling with:   make --no-print-directory -j 5
-------------------------------------
-----------------------------
Configuring and Building iRODS
-----------------------------
Can't locate JSON.pm in @INC (you may need to install the JSON module) (@INC contains: .. /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /Users/jerry/trunk/irods/iRODS/scripts/perl/utils_file.pl line 25.
BEGIN failed--compilation aborted at /Users/jerry/trunk/irods/iRODS/scripts/perl/utils_file.pl line 25.
Compilation failed in require at ./scripts/perl/configure.pl line 103.
```

reverting back to master and it builds normally
```
git checkout master
make clean
./packaging/build.sh --run-in-place icommands

To add the iCommands to your path, please run:
  export PATH=$PATH:/Users/jerry/trunk/irods/iRODS/clients/icommands/bin

+------------------------------------+
| RENCI iRODS Build Script           |
|                                    |
|   Completed in 22m27s              |
+------------------------------------+
```

Environment is:
Mac OS X 10.10.5
XCode installed and activated
Version 6.4 (6E35b)
OSXFuse installed using defaults
```
brew --version
0.9.5 (git revision f5a3d; last commit 2015-09-24)
brew list
help2man   	libtool		mysql		openssl		pcre		wget
```

**Comment by beppodb** [comment]
4.1.x requires the JSON.pm perl module. Try:

brew install cpanm
sudo cpanm JSON

(Note, there may be other, better ways to satisfy this dependency)


On Oct 2, 2015, at 6:07 PM, Jerry Schneider <notifications@github.com<mailto:notifications@github.com>> wrote:


I am trying to build icommands. I have a system where I can build the master (4.2.0) just fine, but when I try to build either 4.1.5 or 4.1.6, I get the above error:

git clone https://github.com/irods/irods
cd irods
git submodule init ; git submodule update
./packaging/build.sh --run-in-place icommands
all builds without error

git checkout 4.1.5 or 4.1.6
git submodule init ; git submodule update
make clean
./packaging/build.sh --run-in-place icommands

________________________________

Detected CPUs: 2

Compiling with: make --no-print-directory -j 5
________________________________
Configuring and Building iRODS

Can't locate JSON.pm in @INC<https://github.com/INC> (you may need to install the JSON module) (@INC<https://github.com/INC> contains: .. /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /Users/jerry/trunk/irods/iRODS/scripts/perl/utils_file.pl line 25.
BEGIN failed--compilation aborted at /Users/jerry/trunk/irods/iRODS/scripts/perl/utils_file.pl line 25.
Compilation failed in require at ./scripts/perl/configure.pl line 103.

reverting back to master and it builds normally
git checkout master
make clean
./packaging/build.sh --run-in-place icommands

To add the iCommands to your path, please run:
export PATH=$PATH:/Users/jerry/trunk/irods/iRODS/clients/icommands/bin

+------------------------------------+
| RENCI iRODS Build Script |
| |
| Completed in 22m27s |
+------------------------------------+

Environment is:
Mac OS X 10.10.5
XCode installed and activated
Version 6.4 (6E35b)
OSXFuse installed using defaults
brew --version
0.9.5 (git revision f5a3d; last commit 2015-09-24)
brew list
help2man libtool mysql openssl pcre wget

**Comment by jerry57** [comment]
I think you meant the following to install the JSON module

sudo cpan JSON
it then walks through all the cpan configuration and installs JSON
there is no such command as "cpanm" that I can find
