### ISSUE TITLE
Errors when performing recursive itrim

### ISSUE THREAD

**Issue by burnce** [irods/irods#2927]
Hello,

I performed a recursive `itrim` on a collection. The command succeeded in trimming a number of copies, but after a while encountered 5 or six `status = -806000 status = -806000 CAT_SQL_ERR` errors followed by a sequence of `status = -856000 status = -856000 CAT_BIND_VARIABLE_LIMIT_EXCEEDED` errors. Rerunning the command allowed it to run past the already trimmed data objects and trim new ones, but each time it only progressed so far before the same issue cropped up again. There were over 600 data objects in the collection and its subcollections.

I am running irods version 4.0.3
The exact flags used were: `itrim -N 1 -S $RESC_NAME -Vr -M $COLLECTION`

Cheers,

Bernhard

**Comment by trel** [comment]
We've got a recursive itrim in the tests - but will probably need to add a new test that creates more replicas first.

https://github.com/irods/irods/blob/4-1-stable/tests/pydevtest/test_chunkydevtest.py#L249

**Comment by trel** [comment]
The first step will be to reproduce on a 4-1-stable (4.1.6) installation.

**Comment by trel** [comment]
@burnce Is this still an issue for you?

**Comment by burnce** [comment]
Hi trel,

I have not encountered it again. However, I have not performed big trim operations recently. Regarding your comment on testing for this, it is the number of objects (possibly, the number of objects in a single collection) rather than the number of replicas which was high.

Cheers,
Bernhard

**Comment by trel** [comment]
Closing without specific use case that triggers the error.   4.0.x and 4.1.x were a long time ago.

We'll open a new issue if we see this again.
