### ISSUE TITLE
On delete of file in compound resource with no trashcan on iRODS 4.1.6 data is restored from archive and than deleted.

### ISSUE THREAD

**Issue by cookie33** [irods/irods#2930]
We deleted a file which was in a compound resource. It was only in the archive and not in the cache at that time:

```
rods$ ils -l
/<zone>/home/rods:
...
  rods              1 eudat;eudatPnfs         5493 2015-04-30.14:52 & rct_accounting.pl
...

rods$ irm rct_accounting.pl
```
This caused a retrieval of the file from the archive before deleting it.
The same happens if you use:
```
irm -f <filename>
```
```
2015:10:21-07:52:22.364418156  338 univMSSInterface.sh[5441][v1.10,stageToCache,d2]: : entering stageToCache()=/pnfs/<fqdn>/data/irods/home/rods/rct_accounting.pl /eudatCache/Vault/home/rods/rct_accounting.pl
2015:10:21-07:52:22.371534850  338 univMSSInterface.sh[5441][v1.10,stageToCache,d2]: : executing: /usr/bin/uberftp -wait "gsiftp://<fqdn1>/pnfs/<fqdn>/data/irods/home/rods/rct_accounting.pl" "file:/eudatCache/Vault/home/rods/rct_accounting.pl"
2015:10:21-07:52:35.850074277  338 univMSSInterface.sh[5441][v1.10,stageToCache,d2]: : The status is 0 (OK)
2015:10:21-07:52:35.905463303  29201 univMSSInterface.sh[5634][v1.10,rm,d2]: : entering rm()=/pnfs/<fqdn>/data/irods/home/rods/rct_accounting.pl
2015:10:21-07:52:35.908576445  29201 univMSSInterface.sh[5634][v1.10,rm,d2]: : executing: /usr/bin/uberftp -rm  "gsiftp://<fqdn2>/pnfs/<fqdn>/data/irods/home/rods/rct_accounting.pl"
2015:10:21-07:52:36.031372950  29201 univMSSInterface.sh[5634][v1.10,rm,d2]: : The status is 0 (OK)
```
In core.re we have stated:

```
rods$   grep ^acTrashPolicy core.re
acTrashPolicy {msiNoTrashCan; }
```

Why the retrieval of the file to cache before deleting it when there is no trashcan set or explicitly preventing the use of a trashcan with the `-f` flag? This makes it very slow if all the files have to come from tape one by one. And we are shoe shining the tape drive heads. This is sub-optimal.

Can this be fixed so it checks for the policy in core.re or the -f flag before retrieving the file?

**Comment by jasoncoposky** [comment]
We will take a look.  Ultimately we want the resource plugins to only speak to the internal iRODS API, which means honoring the ALL_KW and FORCE_KW flags.  We will need to audit the agent code to ensure the appropriate flags are set given the policy settings.
