### ISSUE TITLE
iRODS 4 installation fails for locale different than en_US.UTF-8 with psql

### ISSUE THREAD

**Issue by kellerb** [irods/irods#2931]
[From iRODS-Chat](https://groups.google.com/d/msg/irod-chat/WDDcFdUyWqQ/tg0_wIrBDgAJ)

The installation of iRODS 4 fails with postgresql if the locale is different than `en_US.UTF-8`. After investigation, the reason is that the installation script `irods_setup.pl` contains a test based on a locale value:

This test checks a string that is only meaningful for `en_US.UTF-8`:
        `if ( $output =~ /List of databases/i )`

If the locale is set to a different language (eg. `FR.UTF-8`) then postgresql returns the string `Liste des bases de données`.

**Comment by tempoz** [comment]
4.2 does not parse raw postgres output.
