### ISSUE TITLE
define the rebalance operation for random and roundrobin resource plugins

### ISSUE THREAD

**Issue by jasoncoposky** [irods/irods#2938]
per discussion on iRODS-Chat
https://groups.google.com/forum/#!searchin/irod-chat/14424/irod-chat/9-ZvEfgdehQ/fyclceXDDgAJ

---

```
FILLED_RESOURCE=the most filled resource of the roundrobin set
EMPTY_RESOURCE=the least filled resource of the roundrobin set
HIGH=percentage of space used on FILLED_RESOURCE (for example 90%)
LOW=percentage of space used on EMPTY_RESOURCE (for example 1%)
DIFF=HIGH-LOW
while DIFF > 1:
   randomly pick a file into FILLED_RESOURCE
        and move it into EMPTY_RESOURCE
   re-evaluate FILLED_RESOURCE, EMPTY_RESOURCE and DIFF
```

Sounds easy like that, but of course, some special cases to consider:
for example, it will never converge if a very big file uses 50% of a resource by itself...

**Comment by trel** [comment]
The roundrobin resource has been marked deprecated in 4.2.x (https://github.com/irods/irods/issues/3778) and removed for 4.3.0 (https://github.com/irods/irods/issues/3779).

The rebalance operation for the random resource is a no-op.

I don't think there is anything to do here.   Closing.
