### ISSUE TITLE
rule engine 'substr' documentation inconsistent

### ISSUE THREAD

**Issue by trel** [irods/irods#2947]
As per https://groups.google.com/forum/#!topic/irod-chat/WFZLEf9OTpU:

Either

1)
The documentation is incorrect, and the third parameter should be 'end position'
https://github.com/irods/irods/blob/4.1.6/docs/manual/rule_language.md#271
```
writeLine("stdout", substr("This is a string.", 5, 4));
# Output: is a
```
should be
```
writeLine("stdout", substr("This is a string.", 5, 5+4));
# Output: is a
```

OR

2)
The code should be changed to have the third parameter be 'length', like many other languages.
https://github.com/irods/irods/blob/4.1.6/iRODS/server/re/src/functions.cpp#L2058
This choice requires consideration of backwards compatibility.

**Comment by cookie33** [comment]
HI,

To make things even worse. There is a microservice which does the same: https://docs.irods.org/4.1.6/doxygen/msiHelper_8cpp.html#a271ff188cf4498826958fdcad58938b3

This is `msiSubstr`. This uses: the offset en length to get a sub string from a string.

**Comment by trel** [comment]
We've decided to go with option 1.  We'll update the documentation to be correct.
