### ISSUE TITLE
connectToRhostWithTout() misreports connect() failures on OS X

### ISSUE THREAD

**Issue by jmarshall** [irods/irods#2948]
With environment files pointing to a host on which an iRODS server is no longer running, we expect an error message saying _Connection refused_.  Instead on Mac OS X we get

> $ `iget foobar.bam -`
> ERROR: _rcConnect: connectToRhost error, server on blahblah.sanger.ac.uk:1247 is probably down status = -305022 USER_SOCK_CONNECT_ERR, Invalid argument

which makes it hard to diagnose the problem.

`connectToRhostWithTout()` retries the connection attempt three times (MAX_CONN_RETRY_CNT).  With increased verbosity, on Linux we see

> $ `iget -V foobar.bam -`
> NOTICE: connectToRhostWithTout: connect error, errno = 111    _(ECONNREFUSED)_
> NOTICE: connectToRhostWithTout: connect error, errno = 103    _(ECONNABORTED)_
> NOTICE: connectToRhostWithTout: connect error, errno = 111    _(ECONNREFUSED)_
> NOTICE: connectToRhost: connect to host blahblah.sanger.ac.uk on port 1247 failed, status = -305111 status = -305111 USER_SOCK_CONNECT_ERR, Connection refused
> ERROR: _rcConnect: connectToRhost error, server on blahblah.sanger.ac.uk:1247 is probably down status = -305111 USER_SOCK_CONNECT_ERR, Connection refused

more or less as expected.

However on OS X we see

> $ `iget -V foobar.bam -`
> NOTICE: connectToRhostWithTout: connect error, errno = 61    _(ECONNREFUSED)_
> NOTICE: connectToRhostWithTout: connect error, errno = 22    _(EINVAL)_
> NOTICE: connectToRhostWithTout: connect error, errno = 22    _(EINVAL)_
> NOTICE: connectToRhost: connect to host blahblah.sanger.ac.uk on port 1247 failed, status = -305022 status = -305022 USER_SOCK_CONNECT_ERR, Invalid argument
> ERROR: _rcConnect: connectToRhost error, server on blahblah.sanger.ac.uk:1247 is probably down status = -305022 USER_SOCK_CONNECT_ERR, Invalid argument

Calling `connect(2)` again on a socket that is in the process of connecting seems dubious, so this retrying seems dubious.  It appears that it is partly luck that the right errno is reported in this scenario on Linux (perhaps it wouldn't if MAX_CONN_RETRY_CNT was even!), and it seems that OS X complains loudly about `connect()`-on-an-already-connecting-socket, leading to the misleading error message.  (I wonder what the BSDs do?)

**Comment by kellerb** [comment]
[This](http://stackoverflow.com/questions/9646550/what-does-econnaborted-mean-when-trying-to-connect-a-socket) stackoverflow echoes the "don't call connect again on the same socket after failure" message.

We'll probably need to change `connectToRhostWithTout()` and its calling function `connectToRhostWithRaddr()` to create a new socket after each failure.

**Comment by kellerb** [comment]
The fix I am working on involves changing the behavior and signature of [`connectToRhostWithTout()`](https://github.com/irods/irods/blob/4.1.6/iRODS/lib/core/src/sockComm.cpp#L983). Please let me know if anyone is using this function. It does not appear to be used by baton.

**Comment by jmarshall** [comment]
Both baton and htslib use the higher-level `rcConnect()` and wouldn't have any business using these lower-level `connectToRhost*` functions.  It seems like more of an internal function than part of the iRODS-related API, so IMHO changing the signature is no problem for us.
