### ISSUE TITLE
Oracle database plugin for Ubuntu

### ISSUE THREAD

**Issue by andyjp94** [irods/irods#2949]
Your iRODS release files available via ftp do not include the oracle plugins after 4.0.3. Is the oracle ubuntu plugin in 4.0.3 the one to use for all later releases of iRODS 4? Could you also verify what version of Oracle the plugin is compiled against?

**Comment by kellerb** [comment]
There is not currently an Ubuntu version of the Oracle database plugin that works with iRODS versions after 4.0.3.

The Oracle database plugins that do exist are compiled against Oracle version 11.2

**Comment by Pete-C** [comment]
Hello guys, I'm not sure I follow, does this mean that Oracle support for Ubuntu has stopped after 4.0.3 ? 
 


     On Wednesday, 4 November 2015, 18:47, kellerb <notifications@github.com> wrote:
   

 There is not currently an Ubuntu version of the Oracle database plugin that works with iRODS versions after 4.0.3.The Oracle database plugins that do exist are compiled against Oracle version 11.2—

**Comment by kellerb** [comment]
Yes, Oracle support for Ubuntu was stopped after 4.0.3. This was caused by the intersection of not seeing a demand for it and Oracle not providing (to my knowledge) .deb's of the client libraries.

**Comment by Pete-C** [comment]
That's unfortunate, we are currently Ubuntu based. We use the Oracle supplied tarball for the client and throughout the 3.x stream, we had the option of exporting ORACLE_HOME to point to the relevant location. So this seems to be a retrograde step.
 


     On Wednesday, 4 November 2015, 19:58, kellerb <notifications@github.com> wrote:
   

 Yes, Oracle support for Ubuntu was stopped after 4.0.3. This was caused by the intersection of not seeing a demand for it and Oracle not providing (to my knowledge) .deb's of the client libraries.—

**Comment by jasoncoposky** [comment]
If there is sufficient interest in maintaining support for an Oracle / Ubuntu platform we can add it to the CI system.  We began with the major distributions and databases with the old system and migrated the combinations of database and distribution that had the most interest.

**Comment by kellerb** [comment]
Sorry @Pete-C, thought you were using CentOS w/ Oracle.

We are adding the Ubuntu/Oracle combination to CI currently, and everything appears to be working correctly. Current plan is to include an Ubuntu Oracle database plugin w/ iRODS 4.1.7. @andyjp94 this will also be compiled against Oracle 11.2.

**Comment by Pete-C** [comment]
Many thanks to you both for the update. We're starting 4.x migration testing this week, so this is welcome news. As an aside we've shared the google test sheet with your team, so hopefully you will be able to track our progress.
 


     On Monday, 9 November 2015, 20:51, kellerb <notifications@github.com> wrote:
   

 Sorry @Pete-C, thought you were using CentOS w/ Oracle.We are adding the Ubuntu/Oracle combination to CI currently, and everything appears to be working correctly. Current plan is to include an Ubuntu Oracle database plugin w/ iRODS 4.1.7. @andyjp94 this will also be compiled against Oracle 11.2.—

**Comment by kellerb** [comment]
The tests have passed. Oracle Ubuntu 12 and 14 is ready for 4.1.7.
