### ISSUE TITLE
C code broken by rodsErrorTable.h's #defines to const ints change

### ISSUE THREAD

**Issue by jmarshall** [irods/irods#2950]
In releases up to the current 4.1.6 and in the **4-1-stable** branch, [rodsErrorTable.h](https://github.com/irods/irods/blob/4-1-stable/iRODS/lib/core/include/rodsErrorTable.h) looks like this:

	#define SYS_SOCK_OPEN_ERR                           -1000
	#define SYS_SOCK_BIND_ERR                           -2000
	…

However on **master** as of f189815174ea9d9d19dc336f10d25494630b78e8 it lists these error names as `const ints` rather than `#defines`:

	#define NEW_ERROR(err_name, err_code) const int err_name = err_code;
	…
	NEW_ERROR(SYS_SOCK_OPEN_ERR,                           -1000);
	NEW_ERROR(SYS_SOCK_BIND_ERR,                           -2000);
	…

This breaks C code that uses these named errors in `switch` statements, e.g.,

	int status_errno(int status) {
	    switch (status) {
	    case CAT_NO_ROWS_FOUND: return ENOENT;
	    case CATALOG_ALREADY_HAS_ITEM_BY_THAT_NAME: return EEXIST;
	    …

as a `const int` is not an _integer constant expression_ in C so can't be used as a `case` value.

It would be useful for those writing iRODS clients in C if this could be reverted to a list of `#defines`.  Alternatively (as there is benefit in having these names available to the compiler and debugger) the `NEW_ERROR` macro could be changed to build up an `enum` containing the list.  Enumerators are valid for `case` in both C and C++.

**Comment by tempoz** [comment]
Yeah, we can build up an enum in the macro. Thanks for letting us know about this.
