### ISSUE TITLE
Request for Upgrade procedure to cover run-in-place (esp. 3.3.1)

### ISSUE THREAD

**Issue by kript** [irods/irods#2968]
At present the section in the manual covers upgrading from packages, particularly that which covers upgrading from 3.3.1 (which is my current concern). If you have not built your iRODS server infrastructure using the package installs (we have 'legacy' 3.3.1 installations), then there is no procedure for upgrading to a new run-in-place, whether from 3.3.1-4.1.7 or 4.1.6 to 4.1.7. 

Is run-in-place supported for production installs?

Thanks!

**Comment by trel** [comment]
We strongly recommend not running production iRODS with the `--run-in-place` option.  It has been made available for testing and backwards compatibility.

It will probably be best for all involved to run packaged software in production.  Ease of upgrades alone, coupled with a growing array of possible plugin combinations, will make sustaining a `--run-in-place` installation much more challenging.

It is possible that in the 5.0 timeframe, with the plans for a proper plugin registry, that this could be handled more gracefully.

**Comment by jasoncoposky** [comment]
I have bench-tested a RIP 'upgrade':
*  `git checkout 4.1.7`
* `./packaging/build.sh --run-in-place -rf icat postgres`
* `./plugins/database/packaging/setup_irods_database.sh`
* tested the installation
* `git checkout 4-1-stable`
* `./packaging/build.sh --run-in-place -rf icat postgres`
* `./plugins/database/packaging/setup_irods_database.sh`
* tested the installation again

As @trel has noted, this is not recommended for a production installation.
