### ISSUE TITLE
Compound resources, msiDataObjTrim/msiDataObjUnlink, msisync_to_archive + WOS confusion

### ISSUE THREAD

**Issue by danielhanlon** [irods/irods#2972]
Hello!

Apologies if I'm missing some documentation here but I'm having difficulties with managing the cache in a compound resource for WOS.

We're running iRODS 4.1 (tracking the releases so 4.1.7) with irods-resource-plugin-wos-1.2 on Debian Jessie and a resource hierarchy of:

```
wos:compound
├── wosArchive:wos
└── wosCache
```

This all works fine most of the time with files replicated to wosArchive on write and brought back to wosCache for re-reading.

However, we have the following problems:
1. Every now and again, the replicate to archive seems to fail so objects are left with just a copy in cache
2. Attempting to clean the cache with "itrim -N1" sometimes seems to delete the archive copy, not the cache copy.

To deal with both of these I've got the following rule which
- finds all files in the cache
- searches for all replicas of each file
- if there's no archive copy it replicates to archive
- if there IS an archive copy it attempts to trim the cache copy.

```
  1 tidyWosCache {
  2         msiGetIcatTime(*icatTime,'icat');
  3         writeLine("stdout","Executing tidyWosCache at *icatTime");
  4         foreach ( *CacheFile in SELECT DATA_ID, DATA_PATH, COLL_NAME, DATA_NAME WHERE DATA_RESC_HIER = 'wos;wosCache' ){
  5                 *ArchiveRepl = '';
  6                 *CacheRepl = '';
  7                 foreach ( *Row in SELECT DATA_REPL_NUM, DATA_RESC_HIER WHERE DATA_ID = (*CacheFile.DATA_ID) ){
  8                         if (*Row.DATA_RESC_HIER=="wos;wosCache") then {
  9                                 *CacheRepl = *Row.DATA_REPL_NUM;
 10                         } else if (*Row.DATA_RESC_HIER=="wos;wosArchive") then {
 11                                 *ArchiveRepl = *Row.DATA_REPL_NUM;
 12                         } else {
 13                                 writeLine("stdout","Unknown resource=*D.DATA_RESC_HIER");
 14                         }
 15                 }
 16                 *PATH_IN_IRODS=(*CacheFile.COLL_NAME)++'/'++(*CacheFile.DATA_NAME);
 17                 if ( *ArchiveRepl == '') then {
 18                         # writeLine("stdout","DataID="++*CacheFile.DATA_ID++" not in archive");
 19                         # Force replication to archive - needs path in cache resource (DATA_PATH), path in irods (COLL_NAME+/+DATA_NAME) and cache resource name (DATA_RESC_HIER)
 20                         *sync_err = msisync_to_archive('wos;wosCache', (*CacheFile.DATA_PATH), *PATH_IN_IRODS);
 21                         if ( 0 != *sync_err ) {
 22                                 writeLine( "stdout", "Error, *sync_err" );
 23                         } else {
 24                                 writeLine( "stdout", "*PATH_IN_IRODS sync'd to archive" );
 25                         }
 26                 } else {
 27                         # writeLine("stdout","DataID="++*CacheFile.DATA_ID++" has replica *ArchiveRepl in archive and replica *CacheRepl in cache");
 28                         # Probably need to check the cache copy isn't isn't really NEWER than the archive copy....
 29                         # msiDataObjUnlink("objPath=*SourceFile++++replNum=1",*Status); --returns 0 on success
 30                         *inp.objPath=*PATH_IN_IRODS;
 31                         *inp.replNum=*CacheRepl;
 32                         *inp.forceFlag="";
 33                         #*trim_err = msiDataObjUnlink(str(*inp),*status);
 34                         *trim_err = msiDataObjTrim(*PATH_IN_IRODS,'wos',*CacheRepl,"1","irodsAdmin",*status);
 35                         if ( 0 != *trim_err ) {
 36                                 writeLine( "stdout", "msiDataObjTrim error, *trim_err, with status, *status after trying to remove replica number *CacheRepl of *PATH_IN_IRODS" );
 37                         } else {
 38                                 writeLine( "stdout", "*PATH_IN_IRODS replica *CacheRepl trimmed." );
 39                         }
 40                 }
 41         }
 42 }
 43
 44 INPUT null
 45 OUTPUT ruleExecOut
```

Issue 1 is dealt with using `msisync_to_archive` on line 20. I've not noticed any problems with forcing replication this way.

I've tried to solve issue 2 with a couple of approaches (lines 33 and 34, the former commented out here).

Using `msiDataObjTrim` as on line 34, I get the same behaviour as with `itrim` i.e. the archive copy is deleted instead of the cache copy for certain files. Presumably this is a bug that's appearing in both? The microservice returns an error e.g.

```
msiDataObjTrim error, 1, with status, 1
```

and I'm not sure what this means...

Using `msiDataObjUnlink` as on line 33, I can reliably delete the cache copy but I can't see how to do this as an admin user so would have to run the rule once for each irods user to catch all files.

I'm concerned that I'm going about this the wrong way as it seems more complicated than it should be so I'd appreciate any comments and suggestions as to how to achieve what I want.

Thanks in advance!

Daniel.

P.S. This is probably a red herring, but I've noticed that `DATA_MODIFY_TIME` for the archive resource / cache resource reflects when the replication happens, not when the file was uploaded to the compound resource. This means that once a copy is pulled back to cache, the cache copy appears newer than the archive copy. I wondered whether this is sometimes getting in they way of removing the cache copy with `itrim`/`msiDataObjTrim` as the man page says "The old copies will be trimmed first, then the  'cache'  class copies." Having said this, I can't trigger the behaviour above by going through these steps...

**Comment by cookie33** [comment]
HI,

This might be better asked in the irods-chat@googlegroups.nl.

The problem #1 might be solved if you force it to use async copy from cache to archive. Set the context of the wos service to "auto_repl=off" and use `acPostProcForPut`. You will also need to create one for acPostProcForRepl.
```
# on put action
# if the name of the resource group is "eudat" replicate it to eudatPnfs in a delayed function
# include destination filepath "eudatCache" only. A replication should not be done twice.
# eudatCache is local disk cache
# eudatPnfs is dCache
acPostProcForPut {
        ON($rescName like "eudat" && $filePath like "/var/lib/eudatCache/*" ) {
                # writeLine("serverLog","Execute command to replicate $objPath to eudatPnfs using eudat, because of put");
                delay("<PLUSET>1m</PLUSET><EF>1h DOUBLE UNTIL SUCCESS OR 6 TIMES</EF>") { 
                        #writeLine("serverLog","filePath: $filePath");
                        *CompoundRescName="eudat"
                        *CacheRescName   ="*CompoundRescName;eudatCache";
                        *ArchiveRescName ="*CompoundRescName;eudatPnfs";
                        writeLine("serverLog","Execute command to replicate (in resource *CompoundRescName) $objPath ($filePath) to *ArchiveRescName, because of put");
                        msisync_to_archive("*CacheRescName", $filePath, $objPath );
                }
        }
}
```
 
The problem #2 might be solved if you retrieve the version of the file first from iRODS before using the trim function. We use the following statement to get the files to trim.
```
foreach ( *ROW in SELECT DATA_NAME, COLL_NAME, DATA_REPL_NUM, DATA_SIZE, order(DATA_CREATE_TIME) WHERE DATA_RESC_HIER = '*CacheRescName' AND COLL_NAME like '*Collection%') {

```

Greetings,

Robert Verkerk

**Comment by cookie33** [comment]
The correct email address: irod-chat@googlegroups.com

**Comment by trel** [comment]
@danielhanlon what can we do to help you with this?  do you still have questions and/or things that are not explained by @cookie33's suggestions?

**Comment by trel** [comment]
Regarding your 2)...

See https://github.com/irods/irods_resource_plugin_wos/issues/1572#issuecomment-286435559

The test there demonstrates the need to remove the `-S` option from `itrim`.

Otherwise, I think specifying the replica to trim by number should be working as expected.  We will write a few more tests to confirm.

**Comment by trel** [comment]
@danielhanlon considering closing this and marking 'workaround'...

**Comment by trel** [comment]
If we see this again or have a problem - please open a new issue.
