### ISSUE TITLE
irods json documentation 

### ISSUE THREAD

**Issue by andyjp94** [irods/irods#2973]
All the json documentation that I have seen at docs.irods.org uses single quotes, according to http://tools.ietf.org/html/rfc7158#section-7, JSON RFC 7159 requires that double quotes must be used. This has caused issues when I have copied and pasted JSON variables from docs.rods.org into the irods JSON files.

**Comment by trel** [comment]
Tested and confirmed.  Server will not start with single quotes in the JSON.

Double quotes required.  Thanks Andy.

**Comment by trel** [comment]
These single quotes appear only on the 4-1-stable branch as far as I can tell.  Please point to any instances on the master branch that use single quotes.

If there is a 4.1.8 release, these updates will be included.
