### ISSUE TITLE
Unixfilesystem resource enhancement high water mark

### ISSUE THREAD

**Issue by andyjp94** [irods/irods#2981]
Our users sometimes want to write to files in place and have the updates replicated. With the current configuration of the unixfilesystem, we can only prevent writes on a completely full resource. We would like to be able to set a high water mark to allow some headroom for in-place file modification. This would be very useful for our 2016 migration where presently we manage this through moving resources between resource groups on 3.3.1

**Comment by kript** [comment]
Could we have some notes in the documentation about how to implement this please? I looked in the master branch of the docs, but I couldn't see anything, apologies if I've missed it..

**Comment by trel** [comment]
yes, documenting all the things before 4.1.8 ships.  thanks.
