### ISSUE TITLE
Oracle environment variable documentation

### ISSUE THREAD

**Issue by andyjp94** [irods/irods#2982]
I am trying to create irods servers on ubuntu12 with an Oracle database on a separate server. To do this I install the .deb files you provide. I am then advised to run the setup_irods.sh script. This script fails, and when I look at the log file I see that it is because the irods user that is created by setup_irods.sh doesn't contain the environment variables that are required to connect to an Oracle xe database. These values are:

1. ORACLE_HOME
2. LD_LIBRARY_PATH
3. ORACLE_SID

and for good measure I include the path to the oracle client as well. These variables are all set for my logged in user and as advised I was using sudo to run the setup_irods.sh script. My current workaround is to create a .bash_profile file at /var/lib/irods after installing the .deb files and before running setup_irods.sh. It would be helpful if this was included in the documentation as a necessary step unless you have a better suggestion?

**Comment by kript** [comment]
Hi Andy,

Following on from the call today, I think the suggested solution is to add the environment variables to the /etc/irods/server_config.json

```
    "environment_variables": {
        "ORACLE_HOME": "/opt/oracle/instantclient_11_2"
    },
```

..which IIRC is only created post setup script, so add after setup and then bring down/up to test?

**Comment by jasoncoposky** [comment]
you can add this before setup is run as the json is in /etc/irods upon a clean installation.  what might need be added is any configuration from your legacy 3.x system.

**Comment by trel** [comment]
Yes, update the .json files between installation and setup.  Setup will use any existing files, as `setup_irods.sh` is idempotent.

You can update individual JSON values with the tool in `packaging`:

```
python /var/lib/irods/packaging/update_json.py server_config.json string zone_name theZone
```

**Comment by andyjp94** [comment]
I wasn't aware setup_irods.sh is idempotent, the first time it is run it asks for the account name and the group name but if it is rerun then it doesn't. This is an impedance for automation using vagrant as one cannot run commands such as "vagrant provision" without extra work. This is because "vagrant provision" will rerun all provisioners including the setup_irods.sh and feeds it the same text file as the first time. This fails because it doesn't need the account name and group name so the text file effectively has an off by 2 error.

**Comment by trel** [comment]
Ah, yes, except for that.

You could create the service account and group first yourself and write down the information in the tempfile that stores the state.  You've probably already done this.

We are changing all of the setup mechanism for 4.2 with the removal of bash and perl scripts (will all be Python).

**Comment by andyjp94** [comment]
Adding the environment variables to service_config.json as above appears to have no effect, here is my environment variables section:
 "environment_variables": {
       "LC_ALL": "en_GB.UTF-8",
       "LD_LIBRARY_PATH": "/opt/oracle/instantclient_11_2/",
       "NLS_LANG": "AMERICAN_AMERICA.AL32UTF8",
       "ORACLE_HOME": "/opt/oracle/instantclient_11_2/",
       "ORACLE_SID": "XE",
       "PATH": "/usr/bin:/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/vagrant/.local/bin:/home/vagrant/bin:/opt/oracle/instantclient_11_2:/usr/local/iRODS/clients/icommands/bin:/sbin"
   },
and in the irods_setup.log file the environment variables are:
Environment:
    HOME = /var/lib/irods
    LOGNAME = irods
    SHLVL = 2
    OLDPWD = /var/lib/irods
    _ = /usr/bin/perl
    PATH = /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/opt/vagrant_ruby/bin
    LC_ALL = en_US
    SHELL = /bin/bash
    MAIL = /var/mail/irods
    TERM = xterm-256color
    PWD = /var/lib/irods/iRODS
    USER = irods

**Comment by jasoncoposky** [comment]
That is not a valid test as these environment variables will not make it into the irods_setup.log.  They are only in the perl execution environment.  The server_config.json environment variables are in the iRODS Server process environment only.

**Comment by trel** [comment]
@andyjp94  Is this still something that needs attention?   Or is your understanding that you've gotten past this hurdle in your migration?  Are there any changes that you think need to be made in code or documentation?

**Comment by trel** [comment]
closing per phone call this morning.
