### ISSUE TITLE
4.1.7 run-in-place linking problems

### ISSUE THREAD

**Issue by andyjp94** [irods/irods#2987]
I am running `./packaging/build.sh --run-in-place icat oracle` and I get the following error:
```
Compile database plugin oracle...
Link server test test_cll...
/usr/bin/ld: cannot find -lclntsh
/usr/bin/ld: cannot find -lclntsh
/usr/bin/ld: cannot find -locci
/usr/bin/ld: cannot find -lnnz11
collect2: ld returned 1 exit status
make[1]: *** [.././test_cll] Error 1
make: *** [oracle] Error 2
```
I have set the `LD_LIBRARY_PATH` to the oracle library files, I have also added the path to `/etc/ld.so.conf`, and yet it still can't seem to find the files. The files definitely exist and are 64-bit, as is the machine. I then tried adding to the `iRODS/server/Makefile` variable `LDFLAGS` which didn't help. Is there something I am missing?

**Comment by keithj** [comment]
Have you set ORACLE_HOME? See `find_oracle_lib.sh`

**Comment by andyjp94** [comment]
ORACLE_HOME, ORACLE_SID and the PATH are all set (I believe) correctly

**Comment by jasoncoposky** [comment]
This is how we prepare our VMs for building for Oracle in CI which i just tested for a run-in-place build for both master and the 4-1-stable branches:
https://github.com/irods/irods_testing_zone_bundle/blob/master/ansible_modules/irods_installation_icat_server.py#L174-L195
