### ISSUE TITLE
setup_irods.sh doesn't preserve PATH or LD_LIBRARY_PATH settings on upgrade using Oracle. Should it?

### ISSUE THREAD

**Issue by kript** [irods/irods#2989]
I noticed this when upgrading a 3.3.1 run-in-place system to 4.1.7 Packaged setup, both using Oracle 11.2  instant client.  To get the oracle libraries to work, I needed to set the following variables so that iRODS and sqlplus could find all the right binaries;

``` bash
export ORACLE_HOME=/opt/oracle/instantclient_11_2/
export LD_LIBRARY_PATH=/opt/oracle/instantclient_11_2/
export PATH=$PATH:/opt/oracle/instantclient_11_2/ 
```

After this, setup goes as expected. However, upon restart using the init.d script, the server fails to start with;

```
root@icat:~# /etc/init.d/irods start
Starting iRODS server...
Traceback (most recent call last):
  File "/var/lib/irods/iRODS/scripts/python/get_db_schema_version.py", line 77, in <module>
    current_schema_version = get_current_schema_version(cfg)
  File "/var/lib/irods/iRODS/scripts/python/get_db_schema_version.py", line 39, in get_current_schema_version
    and option_name='schema_version';")
  File "/var/lib/irods/packaging/server_config.py", line 200, in exec_sql_cmd
    return self.exec_oracle_cmd(sql)
  File "/var/lib/irods/packaging/server_config.py", line 169, in exec_oracle_cmd
    returncode, myout, myerr = self.exec_oracle_file(sqlfile)
  File "/var/lib/irods/packaging/server_config.py", line 180, in exec_oracle_file
    raise RuntimeError('Failed to find oracle binary. stdout[{0}] stderr[{1}]'.format(stdout, stderr))
RuntimeError: Failed to find oracle binary. stdout[] stderr[]
Confirming catalog_schema_version... Success
Validating [/var/lib/irods/.irods/irods_environment.json]... Success
Validating [/etc/irods/server_config.json]... Success
Validating [/etc/irods/hosts_config.json]... Success
Validating [/etc/irods/host_access_control_config.json]... Success
Validating [/etc/irods/database_config.json]... Success
iRODS server failed to start.
```

I had to add 
```
export PATH=$PATH:/opt/oracle/instantclient_11_2/bin
export LD_LIBRARY_PATH=/opt/oracle/instantclient_11_2/
```

to `/var/lib/irods/iRODS/irodsctl` at the start to have iRODS find the oracle binary.

Its perfectly reasonable to say that you need to have these things set in your path (perhaps for the iRODS user on the iCAT?), but it could also be argued that they should be captured in the `/var/lib/irods/.irods/irods_environment.json` file?

**Comment by trel** [comment]
These can be set in the `/etc/irods/server_config.json` file - similar to how the UTF-8 environment variables were demonstrated in https://github.com/irods/irods/issues/2991#issuecomment-164830765

```json
{
    "environment_variables": {
        "ORACLE_HOME": "/opt/oracle/instantclient_11_2/",
        "LD_LIBRARY_PATH": "/opt/oracle/instantclient_11_2/"
    }
}
```

I'm not sure about how the `PATH` variable would behave with the use of `$PATH`.

**Comment by trel** [comment]
closing as this can be handled by existing features and upgrades from here forward will be preserved (via `server_config.json`).
