### ISSUE TITLE
Oracle Upgrade from 3.3.1 to 4.1.7 requires additional undocumented Oracle packages and change to .odbc.ini

### ISSUE THREAD

**Issue by kript** [irods/irods#2990]
In trying to upgrade to 4.1.7 packaged install from 3.3.1 run-in-place on Ubuntu 12.04, I found that I also needed to add:
- the unixodbc package (and its dependencies)
- Oracle's instantclient-odbc-linux-11.2.0.4.0.zip (for ibsqora.so.11.1)

and change the irods users .odbc file to include the database server and path to the libsqora.so.11.1 file;

``` diff
sudo diff /var/lib/irods/.odbc.ini /var/lib/irods/.odbc.ini.backup 
2c2
< Driver=/opt/oracle/instantclient_11_2/libsqora.so.11.1

---
> Driver=/usr/lib/oracle/11.2/client64/lib/libsqora.so.11.1
4c4
< Servername=db

---
> Servername=DEFAULTHOST
```

For the Oracle plugin to work in the `setup_irods.sh` script. This script then appears to overwrite the Driver location with a nonfunctional one, but continues to work (see also #2989 )

**Comment by trel** [comment]
Can you explain why you needed to install unixodbc for Oracle to connect?

In 4.2 this will be much simplified (the database connection information will only be recorded in a single location).

**Comment by kript** [comment]
My apologies, I can't find the reason in the notes other than, if we didn't, the /var/lib/irods/.odbc.ini file didn't seem to get referenced, and hence the rest didn't work. Unfortunately, I can't find my logs of this..

**Comment by trel** [comment]
Okay, we'll push this to the 4.2 milestone so we don't forget it...   And make sure it is all resolved properly in the python scripts.

**Comment by trel** [comment]
This should be fixed by the move to Python.  If not, we'll open a new issue as the players involved will have changed.
