### ISSUE TITLE
Oracle Database Plugin requires environment variables to be set to support unicode - should be in database_config.json?

### ISSUE THREAD

**Issue by kript** [irods/irods#2991]
This came out of the 3.3.1, but I couldn't find it documented anywhere in the Oracle plugin docs, or the iRODS manual.

I'm using Oracle 11.2.0.4.0, but I presume this is the same for other Oracle variants.

The following need to be set (I did this on `/var/lib/irods/iRODS/irodsctl`, but I think there is an argument that this should be held in the `database_config.json`, or just added to the `irodsctl` as default, unless there is a good reason why not);

``` bash
export LC_ALL=en_GB.UTF-8
export NLS_LANG=AMERICAN_AMERICA.AL32UTF8
```

Before doing this, putting in a file containing `ɸ` gives a filename from `ils` output of `irods_unicode_��_test.txt`, but after, gives `irods_unicode_ɸ_test3.txt` (for e.g.)

**Comment by kript** [comment]
I believe from an out-of-band conversation we had, that the right place to set these post installation is actually /etc/irods/server_config.json, where we add them to the environment_variables stanza - is that correct?

It would be nice to be able to identify some env variables we want preserved during the setup (but this also comes back to #2790  so can be taken as heartfelt support for that. :-) )

**Comment by kellerb** [comment]
That is correct.

That portion of your `/etc/irods/server_config.json` would look like:

``` json
{
    "environment_variables": {
        "LC_ALL": "en_GB.UTF-8",
        "NLS_LANG": "AMERICAN_AMERICA.AL32UTF8"
    }
}
```

**Comment by trel** [comment]
closing in light of the work being done on #2790 and python/JSON setup in general.
