### ISSUE TITLE
update_json.py valid variable enhancement

### ISSUE THREAD

**Issue by andyjp94** [irods/irods#2994]
I really like the update_json.py script, it works really well, however it would be nice if it would only allow you to add json variables that are valid for the json file. As I say in the title, this would be a nice enhancement, but is not required for our upgrade. Could there also be documentation for it as I only found out about it due to a response to an issue.

**Comment by trel** [comment]
To determine validity, the script would actually have to validate against a schema.   I think this is beyond the scope of the script.  Am I understanding the request correctly?

Documentation, we can do...  It was designed as an internal utility, but it does seem to aid your "scripting a migration" use case.

**Comment by andyjp94** [comment]
Yes, that was the request, no worries, I suppose it is overkill to check the schemas everytime a json file is  changed. But documentation would be great
