### ISSUE TITLE
4-1-0 run-in-place undefined symbol: operation_rule_execution_manager_factory

### ISSUE THREAD

**Issue by keithj** [irods/irods#3009]
I find that my pre- 4.1.7 client builds no longer work with 4.1.7 run-in-place. I get no compile-time errors, but at runtime I see this:

````
$ jq -n '{coll: "/tempZone/home/irods"}' | ~/baton_test/bin/baton-list 
/home/keith/baton_test/bin/baton-list: symbol lookup error: /home/keith/dev/work/renci/irods.git/plugins/network/libtcp.so: undefined symbol: operation_rule_execution_manager_factory
````

Should I be linking against additional libraries? Thanks.

**Comment by jasoncoposky** [comment]
no additional libraries are needed but the client side plugins require that symbol from the executable.  add a call to `init_client_api_table();` which will include that symbol in the client executable.

**Comment by keithj** [comment]
I do call this, immediately after connection (have done since 4.0.3). Do I need to call it in a particular context?

**Comment by jasoncoposky** [comment]
That looks correct, I think misunderstood the issue.  You have a baton client built against a version of the iRODS development library that is of a version less than 4.1.7?  You then run the client connecting to a 4.1.7 server?  Which version of the plugins do you have installed on the client side?

**Comment by keithj** [comment]
I'm on Ubuntu trusty. On the 4-1-stable branch at tag 4.1.6 I can run `./packaging/build.sh --run-in-place icat postgres`, build iRODS, run the post build database setup, start the server and then build baton against the result. When I run a baton client I get this result:

````
$ jq -n '{coll: "/tempZone/home/irods"}' | ~/baton_test/bin/baton-list
INFO: init_client_api_table called
{"collection": "/tempZone/home/irods"}
````

The little INFO message is just a print statment I added to confirm that the `init_client_api_table` was called (it's in an `ifdef` to enable support for both iRODS 3.3.x and 4.x).

However, when I do all of the above against the same branch at tag 4.1.7 (having fully cleaned, rebuilt and reconfigured), I get this:

````
$ jq -n '{coll: "/tempZone/home/irods"}' | ~/baton_test/bin/baton-list 
/home/keith/baton_test/bin/baton-list: symbol lookup error: /home/keith/dev/work/renci/irods.git/plugins/network/libtcp.so: undefined symbol: operation_rule_execution_manager_factory
````

I find that baton built against 4.1.6 will connect to a 4.1.6 server, while baton built against 4.1.7 will not connect to a 4.1.7 server.

**Comment by jasoncoposky** [comment]
Understood, can you perform the same test against the head of 4-1-stable?  I believe this issue was fixed for 4.1.8.

**Comment by keithj** [comment]
With 4.1.8 the behaviour is different. My [autoconf test](https://github.com/wtsi-npg/baton/blob/bbd2dfb38493f12591104328cc81ba4d5886b2be/configure.ac#L295-L297) to detect the iRODS library by testing the ability to link wrt `getRodsEnv` no longer works:

````
configure:17629: gcc -std=gnu99 -o conftest -g -O2 -I/home/keith/dev/work/renci/
irods.git/iRODS/../external/boost_1_58_0z/boost  -I/home/keith/dev/work/renci/ir
ods.git/iRODS/lib/api/include -I/home/keith/dev/work/renci/irods.git/iRODS/lib/c
ore/include -I/home/keith/dev/work/renci/irods.git/iRODS/lib/md5/include -I/home
/keith/dev/work/renci/irods.git/iRODS/lib/sha1/include -I/home/keith/dev/work/re
nci/irods.git/iRODS/server/core/include -I/home/keith/dev/work/renci/irods.git/i
RODS/server/drivers/include -I/home/keith/dev/work/renci/irods.git/iRODS/server/
icat/include -I/home/keith/dev/work/renci/irods.git/iRODS/server/re/include -L/h
ome/keith/dev/work/renci/irods.git/iRODS/../external/boost_1_58_0z/stage/lib  -L
/home/keith/dev/work/renci/irods.git/iRODS/lib/core/obj conftest.c -lRodsAPIs -l
dl -lboost_system -lboost_filesystem -lboost_regex -lboost_thread -lboost_chrono
 -lboost_program_options -lstdc++ -lssl -lcrypto -ljansson -lgssapi_krb5 -lpthre
ad -lm -lrt  >&5
/home/keith/dev/work/renci/irods.git/iRODS/lib/core/obj/libRodsAPIs.a(apiHandler
.o): In function `init_client_api_table':
/home/keith/dev/work/renci/irods.git/iRODS/lib/core/src/apiHandler.cpp:274: unde
fined reference to `operation_rule_execution_manager_factory'
collect2: error: ld returned 1 exit status
````

Where should I be looking for this symbol? Without being able to link, all autoconf checks for the iRODS library will fail.

**Comment by jasoncoposky** [comment]
Yes, that symbol has been separated from that particular legacy library as that library is also currently linked into the server.  We needed a method to clearly separate them in order to provide different implementations of that function for both the client and the server.  That symbol is provided by the libirods_client_plugins.a library.

**Comment by keithj** [comment]
After building from the head of 4-1-stable, my build tree contains no such library. I've recursively grepped the entire thing, so it looks like it's not being built.

**Comment by jasoncoposky** [comment]
You can run `./packaging/make_irods_dev_archive.sh` to generate the development libraries.  They are not generated if you use the `-f` option.

**Comment by keithj** [comment]
Thanks. I've run that and the libraries have been generated. However, I did not use the `-f` option, but rather ran with `--run-in-place icat postgres`. Perhaps this is documented somewhere? Sorry if I've overlooked it. This version is the first release where this extra step is required, isn't it?

**Comment by jasoncoposky** [comment]
No apologies necessary, that script is run by build.sh to generate the libraries for packaging the dev and runtime packages.  This is the first time that a difference exists between the legacy library and our collection of libraries which would require it be run in order to build your client.

**Comment by keithj** [comment]
As both the packaged and run-in-place options now require `./packaging/make_irods_dev_archive.sh` to be run, perhaps `./packaging/build.sh` could do this unconditionally?

It would seem feasible for anyone using run-in-place to use the libs generated by  `./packaging/make_irods_dev_archive.sh` instead of using `libRodsAPIs.a`, giving a route to phase out the legacy archive.

With the dev libraries in place, I can get a successful client build, if I make some changes to the baton `configure.ac`.  The dev libraries are in somewhat of a strange place, being above the level of `IRODS_HOME` (`./iRODS`) and autoconf is not able to find them without some additional help.

**Comment by jasoncoposky** [comment]
That is fair, the build has been mainly tailored to a binary packaging not the run in place option.  We can update build.sh for run-in-place and add a iRODS/ directory to capture the development libraries.

**Comment by jasoncoposky** [comment]
@keithj please test the 4-1-stable branch and confirm.

**Comment by keithj** [comment]
I've tested this on 4-1-stable and everything looks good, thanks.

**Comment by trel** [comment]
Excellent - thanks.
