### ISSUE TITLE
kerberos documentation not in json format

### ISSUE THREAD

**Issue by andyjp94** [irods/irods#3015]
Hi guys,

On the 4.1.7 documentation for kerberos it states that:
> The /etc/irods/server_config.json must be updated to include:
> 
> ```
kerberos_service_principal=irodsserver/serverhost.example.org@EXAMPLE.ORG
kerberos_keytab=/var/lib/irods/irods.keytab
```

I assume this should be:
> The /etc/irods/server_config.json must be updated to include:
>
> ```
"kerberos_service_principal": "irodsserver/serverhost.example.org@EXAMPLE.ORG",
"kerberos_keytab": "/var/lib/irods/irods.keytab" 
```

**Comment by trel** [comment]
definitely - missed that in the move to json syntax.
