### ISSUE TITLE
irsync -R <inCaseThisIsTypePassthruResource> fails

### ISSUE THREAD

**Issue by jenspeters** [irods/irods#3016]
Hi there,

in case somebody tries to write to a "passthru" type Resource Name from foreign zone (irsync -R \<name\>), this fails. 

I think the new RescGroup parent/child setting is not evaluated, it is taken as child's value.
```
  7 16:02:18 pid:12486 ERROR: [-]	iRODS/server/api/src/rsFilePut.cpp:40:rsFilePut :  status [INVALID_LOCATION]  errno [] -- message [failed in call to irods::get_host_for_hier_string]
	[-]	iRODS/server/core/src/irods_resource_backport.cpp:636:get_host_for_hier_string :  status [INVALID_LOCATION]  errno [] -- message [get_host_for_hier_string - Host from hierarchy string:
```

Kind regards,
Jens

**Comment by trel** [comment]
A couple questions...

- What version of iRODS is this?
- Is there more to the last line you posted from the rodsLog?  It ends with a colon, but no hierarchy string is printed...

**Comment by jenspeters** [comment]
This is version 4.1.7 of IRODS clean install.
Yes, I just stripped the last few characters:
´´´
Jan  7 16:02:18 pid:12486 NOTICE: rsDataObjChksum - returning status -808000
Jan  7 16:02:18 pid:12486 ERROR: [-]	iRODS/server/api/src/rsFilePut.cpp:40:rsFilePut :  status [INVALID_LOCATION]  errno [] -- message [failed in call to irods::get_host_for_hier_string]
	[-]	iRODS/server/core/src/irods_resource_backport.cpp:636:get_host_for_hier_string :  status [INVALID_LOCATION]  errno [] -- message [get_host_for_hier_string - Host from hierarchy string: "lza" is NULL]
```

**Comment by jenspeters** [comment]
iadmin lr lza 
shows:
resc_children: lzavt3{}

**Comment by trel** [comment]
Because you said 'foreign' zone, you have a federation of two zones?  One is v4.1.7 - what is the other?

Can you run `ilsresc` on each zone and share the results?

Where was the `irsync` run?  And the target resource is in the other zone (along with the target logical path)?

Please share as much specificity as you can, and we'll get it trapped and fixed.

**Comment by jenspeters** [comment]
Thank you for your help. Ok,let me be as accurate as possible. 
Server A: 
ilsresc
cache
demoResc
lza:passthru
└── lzavt3

Server B:
 ilsresc
cache
lza:passthru
└── lzavt2

Both Servers are 4.1.7, Server A, B have a federation. Server B is executing irsync -R lza <DAO>, Server A rodsLog is listed in the post listed above.

Kind regards, Jens

**Comment by jasoncoposky** [comment]
i see that they are both named lza which may be causing confusion, is that correct?

**Comment by jenspeters** [comment]
Yes, this is correct. It's some kind of naming convention in our federation all having a group called "lza" on which foreign irsync commands can write to.
