### ISSUE TITLE
Add API endpoint in support of execution of rule code across all rule plugins

### ISSUE THREAD

**Issue by kellerb** [irods/irods#3019]
In support of #3018, `irule` needs the ability to execute rule code given a specific rule plugin instance name.

Will be the only access to new rule engine operation defined in https://github.com/irods/irods/issues/3018

Security will be enforced (by default) by #3017

**Comment by trel** [comment]
This has been replaced by the addition of the `default_rule_engine_instance` entry in `server_config.json`.
