### ISSUE TITLE
using update_json.py with lists and having syntax issues

### ISSUE THREAD

**Issue by andyjp94** [irods/irods#3020]
I’m having a go at automating adding `.re` files to `server_config.json` and I can’t seem to get the syntax right.
The first command I tried was:
`sudo /var/lib/irods/packaging/update_json.py /etc/irods/server_config.json string re_rulebase_set,filename test`
And I got:

```
  File "/var/lib/irods/packaging/update_json.py", line 49, in <module>
update_recursive(data, make_nested_dict_from_key_list(key_list, the_value))
File "/var/lib/irods/packaging/update_json.py", line 39, in update_recursive
tmp = update_recursive(orig_dict.get(key, {}), val)
File "/var/lib/irods/packaging/update_json.py", line 44, in update_recursive
orig_dict[key] = new_dict[key]
TypeError: list indices must be integers, not str
```

So I added an index value for the list I wanted to add too and used the command:
`/var/lib/irods/packaging/update_json.py /etc/irods/server_config.json string re_rulebase_set,1,filename test`

And I got:
```
  File "/var/lib/irods/packaging/update_json.py", line 49, in <module>
update_recursive(data, make_nested_dict_from_key_list(key_list, the_value))
File "/var/lib/irods/packaging/update_json.py", line 39, in update_recursive
tmp = update_recursive(orig_dict.get(key, {}), val)
File "/var/lib/irods/packaging/update_json.py", line 39, in update_recursive
tmp = update_recursive(orig_dict.get(key, {}), val)
AttributeError: 'list' object has no attribute 'get'
```

I’m not clear on what I am doing wrong.

**Comment by jasoncoposky** [comment]
examples of usage can be found here:
https://github.com/irods/irods/blob/master/packaging/setup_irods_configuration.sh#L452

**Comment by kellerb** [comment]
`update_json.py` will not be able to add new entries to `re_rulebase_set`. `update_json.py` assumes all non-leaf objects in the updated structure are dictionaries, but for `re_rulebase_set` there is an array in the middle.

If you make the following Python code into a script named `append_to_re_rulebase_set.py` and `chmod u+x` it, you should be able to call it like:
`append_to_re_rulebase_set.py /etc/irods/server_config.json test`.

``` python
#!/usr/bin/env python

import json
import sys

def main(path_to_server_config, name_of_new_rule_file):
    with open(path_to_server_config, 'r+') as f:
        server_config = json.load(f)
        server_config['re_rulebase_set'].append({'filename': name_of_new_rule_file})
        f.seek(0)
        json.dump(server_config, f, indent=4, sort_keys=True)
        f.truncate()

if __name__ == '__main__':
    if len(sys.argv) != 3:
        sys.exit('Usage: {0} path_to_server_config name_of_new_rule_to_add'.format(sys.argv[0]))
    path_to_server_config = sys.argv[1]
    name_of_new_rule_to_add = sys.argv[2]
    main(path_to_server_config, name_of_new_rule_to_add)

```

**Comment by Pete-C** [comment]
Fantastic, many thanks for your help here, it's much appreciated ! 

    On Tuesday, 12 January 2016, 16:22, kellerb <notifications@github.com> wrote:
 

 update_json.py will not be able to add new entries to re_rulebase_set. update_json.py assumes all non-leaf objects in the updated structure are dictionaries, but for re_rulebase_set there is an array in the middle.If you make the following Python code into a script named append_to_re_rulebase_set.py and chmod u+x it, you should be able to call it like:
append_to_re_rulebase_set.py /etc/irods/server_config.json test.#!/usr/bin/env python

import json
import sys

def main(path_to_server_config, name_of_new_rule_file):
    with open(path_to_server_config, 'r+') as f:
        server_config = json.load(f)
        server_config['re_rulebase_set'].append({'filename': name_of_new_rule_file})
        f.seek(0)
        json.dump(server_config, f, indent=4, sort_keys=True)
        f.truncate()

if __name__ == '__main__':
    if len(sys.argv) != 3:
        sys.exit('Usage: {0} path_to_server_config name_of_new_rule_to_add'.format(sys.argv[0]))
    path_to_server_config = sys.argv[1]
    name_of_new_rule_to_add = sys.argv[2]
    main(path_to_server_config, name_of_new_rule_to_add)

**Comment by kellerb** [comment]
Note that this script will append rule bases, meaning that the rules in `core.re` will still take precedence. If you want to prepend rule bases (and thus preempt rules in `core.re`), replace

```python
server_config['re_rulebase_set'].append({'filename': name_of_new_rule_file})
```

with

```python
server_config['re_rulebase_set'].insert(0, {'filename': name_of_new_rule_file})
```

and perhaps rename the functions so it's clear the script prepends instead of appends.
