### ISSUE TITLE
rule base file is ignored

### ISSUE THREAD

**Issue by andyjp94** [irods/irods#3021]
I added an additional rule file to the relevant section in `server_config.json` as shown:
```
"re_rulebase_set": [
{
"filename": "create",
"filename": "core"
}
],
```
The create.re file contents:
```
acSetRescSchemeForCreate {msiSetDefaultResc("ROOT","null"); }
```

If I run `iput -K file.txt` from a non-admin user it only writes to demoResc rather than ROOT. If I edit the core.re line to the same as the create.re file contents then it writes to ROOT. So I assumed I had got the .re file order of precedence wrong. I therefore rearranged the `server_config.json` file section to 
```
    "re_rulebase_set": [
       {
            "filename": "core"
            "filename": "create"
        }
    ],
```
but that gave the following error:
```
ERROR: read_client_server_negotiation_message :: received error message -38000
ERROR: _rcConnect: connectToRhost error, server on icat:1247 is probably down status = -38000 SYS_AGENT_INIT_ERR
```

So I don't know what I am doing wrong and I can't find any documentation on using additional .re files, though I may well just be looking in the wrong places. Also a more specific error for this would be useful as it is an easy mistake to make.

**Comment by jasoncoposky** [comment]
please reference the schema https://github.com/irods/irods_schema_configuration/blob/v3/schemas/server_config.json#L46
where each rule base is contained within a separate object:
```
"re_rulebase_set":[
{
    "filename": "create"
},
{
    "filename": "core"
} ],

**Comment by andyjp94** [comment]
cheers :) that makes a lot of sense

**Comment by andyjp94** [comment]
that will probably also explain issue 3020

**Comment by jasoncoposky** [comment]
can this be closed?

**Comment by andyjp94** [comment]
yep, thank you very much

**Comment by andyjp94** [comment]
So we have accidentally been using both forms of the layout and the schema doesn't seem to pick this up. Is this a problem with the schema?
```
"re_rulebase_set":[
{
    "filename": "create"
},
{
    "filename": "core"
} ],
```
```
"re_rulebase_set": [
{
    "filename": "core"
    "filename": "create"
}
],
```

As an example here is the diff between two versions of a server_config.json:
```
diff /etc/irods/server_config.json /var/tmp/server_config.json 
44c44,46
<             "filename": "seq-dev",
---
>             "filename": "seq-dev"
>         },
>         {
```
and both are validated by the schema:
```
python /var/lib/irods/iRODS/scripts/python/validate_json.py /var/tmp/server_config.json file:///etc/irods/irods_schemas/v2/server_config.json
Validating [/var/tmp/server_config.json]... Success
python /var/lib/irods/iRODS/scripts/python/validate_json.py /etc/irods/server_config.json file:///etc/irods/irods_schemas/v2/server_config.json
Validating [/etc/irods/server_config.json]... Success
```

**Comment by kellerb** [comment]
The internet has differing [opinions](http://stackoverflow.com/questions/21832701/does-json-syntax-allow-duplicate-keys-in-an-object) on whether or not a json object with duplicate keys (`"filename"`) is valid json. In our case, it appears that Python's json parser keeps the last entry for each repeated key:

``` python
>>> json.loads('''{
    "filename": "core",
    "filename": "create"
}''')
{'filename': 'create'}
```

This occurs before schema validation, so we cannot detect this type of error at the schema level.

**Comment by trel** [comment]
re-closing.   if there is something actionable (tightening up the schema definition), please open a new issue.   thanks.
