### ISSUE TITLE
$rescVaultPath no longer available in rule engine

### ISSUE THREAD

**Issue by burnce** [irods/irods#3024]
Session attributes are not documented in the 4.1 branch documentation.

Are these still available. Moving from 4.0 to 4.1 branch, I have rules giving errors in a rule called by `acPostProcForPut`:

    Level 0: DEBUG: error: unable to read session variable $rescVaultPath.

Is this expected?

**Comment by trel** [comment]
Not expected - it will be added back in.

This was due to the rescInfo removal.

Roughly this list of items was removed and should be considered for reinclusion.
https://github.com/irods/irods/blob/4-0-stable/iRODS/server/config/reConfigs/core.dvm#L38-L71

**Comment by adetorcy** [comment]
Resource related rule variables are now available, where applicable, as follows:
```
$KVPairs.zoneName
$KVPairs.freeSpace
$KVPairs.quotaLimit
$KVPairs.rescStatus
$KVPairs.rescId
$KVPairs.rescName
$KVPairs.rescType
$KVPairs.rescLoc
$KVPairs.rescClass
$KVPairs.rescVaultPath
$KVPairs.rescInfo
$KVPairs.rescComments
$KVPairs.rescCreate
$KVPairs.rescModify
```
