### ISSUE TITLE
client side irods_environment.json schema

### ISSUE THREAD

**Issue by andyjp94** [irods/irods#3026]
We want to automatically change our users irodsEnv files to irods_environment.json. To this end it would be nice if we could validate against a schema to ensure that the format matches that which is required. However testing against the current schema fails as it requires fields that aren't appropriate for the client side. We could create our own schema but vanilla ones would be ideal.

**Comment by trel** [comment]
Agreed.

Should be able to split the schemas into two:
- `client_environment.json`
- `service_account_environment.json`

And then use `allOf` in the `service_account_environment.json` to include the client schema.
