### ISSUE TITLE
compiling oracle plugin with Oracle 12 installation

### ISSUE THREAD

**Issue by nief** [irods/irods#3028]
hello,

```
    Oracle had the great idea to change the organization of the client installation between Oracle 11 and 12.
```

With Oracle 12, the dynamic libraries are directly present in the root directory of the installation. The header files are in sdk/include/...
The DBAs told me that there is no alternative for the installation.
Obviously, it has an impact for the irods compilation as the lib/Makefile and server/Makefile are not prepared for this:
Compile database plugin oracle...
In file included from ../src/low_level_oracle.cpp:15:0:
../../../iRODS/../plugins/database/include/low_level_oracle.hpp:10:17: fatal error: oci.h: No such file or directory
 #include "oci.h"

I did a hack for the 3.3.1 instances that we have. I can give you some of the modifications needed, however it will not be adapted to both cases (v12 and pre-12 versions). I just did it so it could compile with Oracle 12.
I don't know if you have already fixed that in the master release (I am using 4.1.7). Let me know if you need the mods.
cheers,
JY

**Comment by kript** [comment]
Is this addressed by https://docs.irods.org/4.2.2/system_overview/troubleshooting/#connecting-to-oracle-via-odbc-on-centos and is the same thing applicable to 4.1.x, I wonder?
We're looking to move to 12.2 soon, so this is of interest to us.

cheers

John

**Comment by trel** [comment]
I would imagine/hope the ODBC connection to Oracle in 4.2+ makes compiling against oracle libraries specifically... very moot.  But yes, @nief please confirm and close the loop.  Thanks.

**Comment by nief** [comment]
for 4.2+, I did not try to compile the code (not very convenient for these new versions), so we are installing directly the binaries from the rpms (and relocate them). And yes, as we are avoiding the compilation step for the time being, using Oracle 12 client libraries does not make any difference and works smoothly.

**Comment by trel** [comment]
Closing this one...

If there is a known problem with this type of installation/configuration, please open a new issue.
