### ISSUE TITLE
find_oracle_lib.sh and the Oracle instant client

### ISSUE THREAD

**Issue by srfraser** [irods/irods#3038]
`find_oracle_lib.sh` returns $ORACLE_HOME if it is set (and survives the configuration process, see https://github.com/irods/irods/pull/3037), but the Oracle instant client puts libraries directly in the root of its unpacked area, not in a `lib/` subdirectory as this snippet of `plugins/database/oracle/Makefile` expects:

```
EXTRA_LDRFLAGS = \
        -L${ORACLE_HOME_LIB}/lib/ \
        -lclntsh -locci -lnnz11
```

The instant client library also needs two symlinks creating:
```
libclntsh.so -> libclntsh.so.11.1
libocci.so -> libocci.so.11.1
```

I'm unsure whether the best approach is to have a warning (if so, where and how should it be displayed?) or modify the scripts to try and cope with the variation. Either way would be an improvement over the current failure mode.

**Comment by trel** [comment]
Seems bold to be updating symlinks somewhere else in the system that iRODS doesn't own.

If there's a place in the build steps where we/you can detect the instantclient, that seems the right place to sniff for the needed symlinks, and error out with a suggestion of how to create them if they don't already exist.

We're pressed on getting 4.1.8 out the door - if you can take a swipe at some detection/suggestion code, we'll be happy to get it included ASAP.

Thanks.

**Comment by srfraser** [comment]
I've updated https://github.com/irods/irods/pull/3047 with the changes to the library handling, since it depends on the changes to the include path as well. 

It still won't account for the need to symlink those two libraries, but as you say that seems outside the scope of this project. It will ensure the proper lib directory is reported, however.

**Comment by trel** [comment]
got it - thanks - i've got a merged branch in CI now.

**Comment by trel** [comment]
The symlinks appear to be installed by the `oracle-instantclient11.2-devel` package.   I'm going to close this for now and get #3047 cleanly through CI.  It failed a couple nights ago due to no `ORACLE_HOME` being set on our build machine.
