### ISSUE TITLE
refactor use of resource hierarchies in r_data_main to leaf storage node resource ids

### ISSUE THREAD

**Issue by jasoncoposky** [irods/irods#3039]
As of the 4.1.x release resource hierarchies are stored in the system metadata table ( r_data_main) as a semicolon delimited string from root to the child.  While this followed the existing convention, and was query friendly, a change in the hierarchy is computationally expensive.

Moving to a resource id allows for:
* proper abstraction - ID only changes on physical move of the data
* instant changes in resource name
* instant changes in resource hierarchy - a significant feature of the 4.x series

**Comment by trel** [comment]
Green in CI on master.
