### ISSUE TITLE
PamAuthRequest with negative TTL parm causes random binary chars in XML response

### ISSUE THREAD

**Issue by tsmeele** [irods/irods#3050]
![image](https://cloud.githubusercontent.com/assets/11386611/13111210/e268f866-d584-11e5-9985-4871db4f844d.png)

Not sure if this leaks sensitive data from the iRODS agents memory?  

The incorrect behavior has been detected in both iRODS 3.3.1 and iRODS 4.1.4

**Comment by kellerb** [comment]
Caused by the same code issue as #3051.
