### ISSUE TITLE
PamAuthRequest with authenticated user not in iRODS leads to random XML output

### ISSUE THREAD

**Issue by tsmeele** [irods/irods#3051]
issue detected in iRODS 4..1.4.  When we use PAM authentication connected to an LDAP server and the user is registered in LDAP but not in iRODS then iRODS agent process returns a `pamAuthRequestOut` response with random binary data in the XML `irodsPamPassword` field.   

![image](https://cloud.githubusercontent.com/assets/11386611/13111441/196b1730-d586-11e5-8834-e02a6c5893b5.png)

**Comment by jasoncoposky** [comment]
Did you get a viable error in the authentication process?  How does this otherwise break?

**Comment by tsmeele** [comment]
Hi Jason,

We encountered this error today when we tested PAM and login using the PHP PRODS library which then throws an exception (bad XML) that we can catch and act upon.

So no immediate impact on our systems, yet I am concerned that server memory is leaked.

P.S. a similar issue occurs when the client specifies TTL= -1 upon PAM login.   Earlier we have created a workaround for that one (simply in PRODS lib set a TTL value, not depend on default) but it appears not fixed yet.

Met vriendelijke groet, kind regards,

Ton

**Comment by kellerb** [comment]
Thank you for reporting this.

You are correct that uninitialized server memory was being included in the response. A fix for this will be included in 4.1.8.

Note that the server API endpoint that triggers this behavior, `rsPamAuthRequest`, has been superseded by `rsAuthPluginRequest`, which does not have the leak. This means that newer clients will not be triggering the bug.
