### ISSUE TITLE
iadmin addchildtoresc truncates resc_children db entry

### ISSUE THREAD

**Issue by kellerb** [irods/irods#3053]
https://github.com/irods/irods/blob/53288ff93d3f6833433bb79c603bcd6012108668/plugins/database/src/db_plugin.cpp#L630

`resc_children` entry read into `char children[MAX_PATH_ALLOWED];`. This operation is not checked for truncation. The code will continue on to add the child to the now malformed `resc_children` string, leading to a bad entry in the db. Found by infinite loop while testing schema change for #3052.

**Comment by jasoncoposky** [comment]
closing, solved by #3039
