### ISSUE TITLE
ilsresc used std::map::operator[] for retrieval

### ISSUE THREAD

**Issue by kellerb** [irods/irods#3054]
https://github.com/irods/irods/blob/53288ff93d3f6833433bb79c603bcd6012108668/iRODS/clients/icommands/src/ilsresc.cpp#L237

`std::map::operator[]` returns a default value if the key is not found. In this case, a missing key is an error.

Testing a change to the db schema for #3052 resulted in an infinite loop of `ilsresc`. iRODS is truncating without warning the `resc_children` string ( #3053 ), which leads to `ilsresc` getting a list of children that is not correct. When the bogus children (from the truncation) are looked up in the `resc_map`, they get an index of `0`, which starts the loop over.

**Comment by trel** [comment]
reopening for inclusion in 4.1.9
