### ISSUE TITLE
iput removes trailing "~" and "^" from filenames of single file puts

### ISSUE THREAD

**Issue by kellerb** [irods/irods#3060]
- [x] master
- [x] 4-2-stable

E.g. `iput file~` will be registered into iRODS as a data object with name `file`.

Issue exacerbated by e.g. Emacs backups.

Investigate files ending in `.`.

https://github.com/irods/irods/blob/6001a51ae70db2a2561a681dbb4292d0c8e41ced/iRODS/lib/core/src/rodsPath.cpp#L691-L698

**Comment by trel** [comment]
This requires a bit more investigation - moving to 4.2.

**Comment by stsnel** [comment]
Files with trailing dots have the same issue.
