### ISSUE TITLE
genQuery uses ordered strstr() to find where condition keywords

### ISSUE THREAD

**Issue by kellerb** [irods/irods#3064]
- [x] main
- [x] 4-3-stable

[From iRODS-Chat](https://groups.google.com/d/topic/irod-chat/YGWwev4-CEU/discussion)

https://github.com/irods/irods/blob/536ce44e9c393a37e5cbb258966e07912ab13d31/plugins/database/src/general_query.cpp#L1361-L1367

A result of this is that when handling the clause `META_COLL_ATTR_NAME IN ('originalVersionId')"`, genQuery will find the `in` in `originalVersionId`, note that it is not at the beginning of the condition (`cp == condStart`), then move on.

A workaround for this case is to always use the lower-case `in` keyword.

**Comment by trel** [comment]
This will be fixed by #3902

**Comment by korydraughn** [comment]
Resolved by the GenQuery2 parser (#7570).

Just needs a test.
