### ISSUE TITLE
Documentation update: Environment variable

### ISSUE THREAD

**Issue by kript** [irods/irods#3065]
Searching iRODs chat regarding the equivalent of irodsEnvFile for V4 brought me to this update; https://irods.org/2015/01/irods-development-update-january-2015/, to whit;

> Additionally, any client environment value provided as a shell environment variable will follow the same convention, but using upper case letters. For example, IRODS_HOST or IRODS_AUTHENTICATION_FILE.

Can this section regarding environment variables be added to the documentation please, as its not at the moment (that I could find), and its _terribly_useful when running tests as other users et al..

**Comment by mcast** [comment]
Also the new equivalent of `$irodsEnvFile` please.  I guess `$IRODS_ENV_FILE` from the recipe..?

**Comment by kellerb** [comment]
FYI `$irodsEnvFile` -> `$IRODS_ENVIRONMENT_FILE`

**Comment by mcast** [comment]
Thanks.  This would be nice to have in a "I'm used to v3, what do I need to know for v4?" sort of FAQ entry.

**Comment by trel** [comment]
This is provided in the new https://github.com/irods/irods_docs repository
