### ISSUE TITLE
data object size treated as 0 when checking high_water_mark

### ISSUE THREAD

**Issue by kellerb** [irods/irods#3068]
## Original issue contents

Because of the nature of parallel puts, the newly created file is treated as having a file size of 0 when determining if the file will cause the `unixfilesystem` resource to exceed its `high_water_mark`.

Add this to documentation.

## Updated issue contents

The `file_obj` [created](https://github.com/irods/irods/blob/427c049a6e886ea72ee2cbe21f1cc90c9fc3fdcc/iRODS/server/core/src/irods_resource_redirect.cpp#L500) in `resolve_resource_hierarchy` does not have the file size from the `_data_obj_inp`. This means that the file size used when [checking](https://github.com/irods/irods/blob/427c049a6e886ea72ee2cbe21f1cc90c9fc3fdcc/iRODS/server/core/src/irods_resource_redirect.cpp#L572) the `high_water_mark` (for both redirect and create) is always zero.

**Comment by keithj** [comment]
@kellerb to be sure I understand the issue, an `iput` of a file >32 Mb (triggering parallel transfer) will not trigger `high_water_mark` even if it would overfill the resource?

**Comment by keithj** [comment]
I can see that `test_unix_filesystem_highwater_mark__2981` in `Test_Resource_Unixfilesystem` shows that I don't understand because it's demonstrating that the `iput` returns `USER_FILE_TOO_LARGE` for a 64 MiB file!

**Comment by kellerb** [comment]
The intended behavior of the `high_water_mark` context string is to disallow data object creation on a `unixfilesystem` resource if `the size of the data object to be created` plus `the bytes currently used on the disk drive backing the unixfilesystem resource's vault path` exceeds the `high_water_mark`.

This means, for example, that if we have a `unixfilesystem` resource with its vault on the same disk that the iRODS server is installed on, and we set its `high_water_mark` to 10,000,000 bytes, we expect to not be able to create *any* data objects on that resource, because its `bytes currently used on the disk drive backing the unixfilesystem resource's vault path` will already exceed 10,000,000 because the iRODS server binaries themselves use up over 10 MB.

The test you mentioned expects the put to fail because the `high_water_mark` is set to 100, which is already exceeded by the other files on the disk. I'm guessing the missing information is that all the files on the hard drive (including files stored in other resources that have the same underlying hard drive, as well as files on the hard drive that are not involved with iRODS at all) count against the `high_water_mark`, not just the replicas stored on that resource in iRODS.

With all that being said, there is a bug such that `the size of the data object to be created` is always treated as zero when checking the `high_water_mark`. This means that the `high_water_mark` will currently only be triggered when the amount of data already stored on the disk exceeds the `high_water_mark`. There is, in a sense, an off-by-one error, in that users will be able to create one more data object than the `high_water_mark` would suggest. If the data objects being created tend to be much smaller than the difference between the `high_water_mark` and the maximum capacity of the drive, then this will not be much of an issue. If the data objects being created are closer to that intended safety margin, then this could be more of an issue.

**Comment by keithj** [comment]
Thanks, that's a very helpful explanation.
