### ISSUE TITLE
iadmin addchildtoresc permits invalid passthru hierarchy to be constructed

### ISSUE THREAD

**Issue by keithj** [irods/irods#3069]
`passthru` is documented as having only one child, however, `iadmin addchildtoresc` will allow multiple children to be added:

```
passthru_0:passthru
├── replication_0:replication
│   ├── random_0:random
│   │   ├── unixfs_0
│   │   ├── unixfs_1
│   │   └── unixfs_2
│   └── random_1:random
│       ├── unixfs_3
│       ├── unixfs_4
│       └── unixfs_5
└── replication_1:replication
    ├── random_2:random
    │   ├── unixfs_6
    │   ├── unixfs_7
    │   └── unixfs_8
    └── random_3:random
        ├── unixfs_10
        ├── unixfs_11
        └── unixfs_9
```

**Comment by trel** [comment]
This is only evaluated when executed.  The addition of children is only a database operation.  I'll fix this with documentation around expected behavior when there is more than one child (the first child returned by the database will be honored).
