### ISSUE TITLE
iget doesn't use parameter irods_default_resource

### ISSUE THREAD

**Issue by nono-gdv** [irods/irods#3071]
Hello,

I have an iRODS zone with two resource servers (with deferred resources for scalability but I'm only using two resources at the moment):

```
sysadm@irods-client-vanves:~$ ilsresc 
Augy:deferred
└── AugyR1:deferred
    └── AugyR1U1
Vanves:deferred
└── VanvesR1:deferred
    └── VanvesR1U1
```

I have the same data stored in both resources:

```
sysadm@irods-client-vanves:~$ ils -l
/papy/home/rods:
  rods              0 Vanves;VanvesR1;VanvesR1U1    657784832 2016-02-24.15:38 & debian-8.3.0-mipsel-CD-1.iso
  rods              1 Augy;AugyR1;AugyR1U1    657784832 2016-02-24.15:40 & debian-8.3.0-mipsel-CD-1.iso
```

The client is configured for using resource Vanves as a default:

```
sysadm@irods-client-vanves:~$ cat .irods/irods_environment.json 
{
    "irods_port": 1247,
    "irods_host": "irods-icat-vanves.frymghq.ymagis.com",
    "irods_user_name": "rods",
    "irods_zone_name": "papy",
    "irods_default_resource": "Vanves"
}
```

AFAICT `iput` uses the `irods_default_resource` parameter but `iget` does not (confirmed by monitoring the network traffic on both storage servers when running iget). I can use the `-R` option to `iget` (it works) but there should be a better way. :-)

**Comment by trel** [comment]
Confirmed on both counts: `iput` honors the setting, `iget` does not.

I was able to replicate this by changing the value on the disk of one of the replicas, and then showing the output with `iget foo -` and seeing the changed data.

Thanks.

**Comment by tempoz** [comment]
Voting (largely locality of reference) and resource hierarchies are supposed to determine which resource is used to retrieve a replica; the `irods_default_resource` is intended to apply only for puts. The behavior desired in this issue is contrary to the intended design of iRODS. If you want to retrieve from a specific resource, use `iget -R <rescname>`.
