### ISSUE TITLE
4.1.8 - ilsresc object count in resource less than total object count in children

### ISSUE THREAD

**Issue by keithj** [irods/irods#3073]
I have this resource hierarchy:

```
demoResc
passthru_0:passthru
└── random_0:random
    ├── unixfs_0
    ├── unixfs_1
    ├── unixfs_2
    ├── unixfs_3
    ├── unixfs_4
    ├── unixfs_5
    ├── unixfs_6
    ├── unixfs_7
    ├── unixfs_8
    └── unixfs_9
```

I have inserted 32 files into the even-numbered unixfs resources. `ilsresc` reports this for `random_0`

```
resource name: random_0
id: 10062
zone: tempZone
type: random
class: cache
location: EMPTY_RESC_HOST
vault: EMPTY_RESC_PATH
free space: 
free space time: : Never
status: 
info: 
comment: 
create time: 01456347548: 2016-02-24.20:59:08
modify time: 01456349239: 2016-02-24.21:27:19
children: unixfs_0{};unixfs_1{};unixfs_2{};unixfs_3{};unixfs_4{};unixfs_5{};unixfs_6{};unixfs_7{};unixfs_8{};unixfs_9{}
context: 
parent: passthru_0
object count: 32
```

The object counts for all the children add up to 32. However, the object count for the parent is 30:

```
resource name: passthru_0
id: 10029
zone: tempZone
type: passthru
class: cache
location: EMPTY_RESC_HOST
vault: EMPTY_RESC_PATH
free space: 
free space time: : Never
status: 
info: 
comment: 
create time: 01456262193: 2016-02-23.21:16:33
modify time: 01456349239: 2016-02-24.21:27:19
children: random_0{}
context: 
parent: 
object count: 30
```

When I delete all the files, the object count here becomes negative.

```
resource name: passthru_0
id: 10029
zone: tempZone
type: passthru
class: cache
location: EMPTY_RESC_HOST
vault: EMPTY_RESC_PATH
free space: 
free space time: : Never
status: 
info: 
comment: 
create time: 01456262193: 2016-02-23.21:16:33
modify time: 01456350426: 2016-02-24.21:47:06
children: random_0{}
context: 
parent: 
object count: -2
```

**Comment by kellerb** [comment]
How did you insert files into only the even numbered unixfilesystem resources?

**Comment by keithj** [comment]
All the odd-numbered resources have `high_water_mark=1000`

**Comment by kellerb** [comment]
Did you create the hierarchy as shown first, and then add all the data objects, or did some of the unixfilesystem resources have data objects before they were added to the random resource.

Below is what I ran in a failed attempt to reproduce:

``` bash
iadmin mkresc passthru passthru
iadmin mkresc random random
iadmin addchildtoresc passthru random
for i in {00..09}; do iadmin mkresc unix$i unixfilesystem `hostname`:/var/lib/irods/newVaults/unix$i; done
for i in {01..09..2}; do iadmin modresc unix01 context high_water_mark=1000; done
for i in {00..09}; do iadmin addchildtoresc random unix$i; done
for i in {00..31}; do iput -R passthru VERSION.json file$i; done
```

**Comment by keithj** [comment]
All created empty. Then I inserted the 32 files simultaneously using `iput -K -f` driving with GNU parallel.

**Comment by keithj** [comment]
Running the whole process from the top it's clear that it doesn't happen every time. I'll try to reproduce it. I wouldn't have reported it, except that I had a roundrobin resource end up containing -2 objects earlier today and it seemed like too much of a coincidence to ignore.

**Comment by kellerb** [comment]
Reproducing this could have a lot to do with the database's [transaction isolation settings](http://www.postgresql.org/docs/9.4/static/transaction-iso.html). What database and isolation settings are you using?

FYI, here is the script with `parallel` I'm using now. I haven't reproduced yet, I'll try with different database settings.

``` bash
iadmin mkresc passthru passthru
iadmin mkresc random random
iadmin addchildtoresc passthru random
for i in {00..09}; do iadmin mkresc unix$i unixfilesystem `hostname`:/var/lib/irods/newVaults/unix$i; done
for i in {01..09..2}; do iadmin modresc unix01 context high_water_mark=1000; done
for i in {00..09}; do iadmin addchildtoresc random unix$i; done
parallel 'iput -R passthru -K -f VERSION.json data_object{}' ::: `seq -f %03g 0 200`
```

This could also depend on the tran

**Comment by keithj** [comment]
The isolation level I'm using is `READ_COMMITTED`

**Comment by trel** [comment]
`r_resc_main.resc_objcount` is now a stale column.

Closing this as resolved.
