### ISSUE TITLE
Writes to load_balanced resource are very slow

### ISSUE THREAD

**Issue by nono-gdv** [irods/irods#3078]
Hello,

I have a load_balanced resource with two unixfilesystem backends.
```
iadmin mkresc lbb1 unixfilesystem $(hostname):/mnt/vdb/lb/lbb1
iadmin mkresc lbb2 unixfilesystem $(hostname):/mnt/vdb/lb/lbb2
iadmin mkresc lb load_balanced
iadmin addchildtoresc lb lbb1
iadmin addchildtoresc lb lbb2
```
I have assigned weights of 1 to lbb1 and 10 to lbb2 in table r_server_load_digest in the database (I just INSERT'ed the data into the table, is there a better way?). Then I upload a file:
```
iput -vP -R lb debian-8.3.0-i386-CD-2.iso
```
It works, but it is vvvveeeeeeerrrrrrryyyyyyyyyyy sssllooooooooooooooooooooow (think maybe 30 seconds for 10MB). Have I missed something?

**Comment by nono-gdv** [comment]
My bad, there was a script I had forgotten about which was sleeping a lot for debug. No issue, then.

**Comment by trel** [comment]
Thanks - you had us very confused.
