### ISSUE TITLE
iput should be able to create replicas

### ISSUE THREAD

**Issue by nono-gdv** [irods/irods#3079]
Hello,

Let's say we have two iRODS resources on two sites, with a small network link between them (basically enough for metadata exchange but we cannot replicate data through this link). We are looking into a manual replication workflow; here is what we can do at the moment:
- `iput` the data on site 1,
- transfer the data to site 2 by other means (USB drive or whatever),
- on site 2, copy the data to one of our storage machines,
- use `ireg --repl` to tell iRODS it has a replica of the data on site 2.

It would make sense to be able to use `iput` on site 2 too and letting iRODS manage the whole process (except the USB drive part); our workflow would look like this:
- `iput` on site 1,
- get our USB drive to site 2,
- `iput --repl` (or whatever) on site 2.

Does this make sense?

**Comment by trel** [comment]
What would this allow you to do other than use `iput`, rather than `ireg`?

Generally... An `iput` copies the data over the wire (into a Vault), and then registers it into the catalog.

If the data is already on the disk, then you only need the registration step (hence the `ireg`).

**Comment by nono-gdv** [comment]
iput would allow me to let iRODS choose the actual storage resource (in my case, this means the actual storage node) by itself, instead of making this choice myself before running _ireg_.

My initial question was not precise enough, sorry about that. «One resource per site» actually means one aggregate resource per site (load_balanced or deferred, not sure yet), with several actual storage nodes.

**Comment by trel** [comment]
If the data is already on-site, you know which resource it will be registered into, and so you would use `ireg` with the appropriate target resource.

`iput` operates on the logical object.
`ireg` operates on a physical replica.

Closing.  I don't think there is any action to be taken here.
