### ISSUE TITLE
include man page for izonereport

### ISSUE THREAD

**Issue by kript** [irods/irods#3099]
Can we get man pages please? I can see why a run-in-place might not install them, but packages installs should install man pages as well, so we don't get

```
irods-dev@irods-test-dev:~$ man izonereport
No manual entry for izonereport
See 'man 7 undocumented' for help when manual pages are not available.
```

**Comment by trel** [comment]
Thanks.

Man pages exist for most of the icommands.

I confirm that there is no man page available for `izonereport`.

**Comment by trel** [comment]
Included as part of https://github.com/irods/irods_client_icommands/issues/8
