### ISSUE TITLE
Graceful error on signature mismatch for dynamic policy enforcement points

### ISSUE THREAD

**Issue by jasoncoposky** [irods/irods#3100]
currently the native rule engine segfaults if there is a signature mismatch between the expected signature and the implemented signature.

**Comment by trel** [comment]
This is now working as expected - need to link to the correct commit.

**Comment by trel** [comment]
This was added in e3347df06405d103596cb117e7e515138edc8ee6 as part of https://github.com/irods/irods/issues/2542.

A signature mismatch will now look something like this in the rodsLog:

```
Nov 12 09:57:30 pid:25245 DEBUG: error: cannot find rule for action "pep_resource_resolve_hierarchy_pre" available: 103.
line 0, col 0
pep_resource_resolve_hierarchy_pre(*ARG0,*ARG1,*ARG2,*ARG3,*ARG4,*ARG5,*ARG6)
^
```
