### ISSUE TITLE
new dataobject via fusemount not triggering replication

### ISSUE THREAD

**Issue by trel** [irods/irods#3103]
Via https://groups.google.com/forum/#!topic/irod-chat/K6WM4o8Q2_U:

I use iRODS Fuse client included in the iRODs icommand 4.1.7
I also set up a 'resource composition' with two resources on a tree with replication mode:

```
#ilsresc 
replResc:replication
├── inragrid-mtpResource
└── inragrid-tlsResource
```

i mount my irods home collection as a file system on a Ubuntu client on /tmp/fmount

On the client:

```
$ df -h
Sys. de fichiers Taille Utilisé Dispo Uti% Monté sur
../..
none               100M     36K  100M   1% /run/user
irodsFs            7,5T    3,8T  3,8T  50% /tmp/fmount

$ ls -l
total 11251927
-rw-r--r-- 1 pmoreau pmoreau    31158640 févr. 23 15:22 DC_0910.h5
-rw-rw---- 1 pmoreau pmoreau   258998272 févr.  9 10:03 debian-8.2.0-amd64-netinst.iso
-rw-r--r-- 1 pmoreau pmoreau      808569 févr. 22 16:33 fdt.jar
-rw-r--r-- 1 pmoreau pmoreau        1173 févr. 26 15:59 ghosttest.c
-rw-r--r-- 1 pmoreau pmoreau     6878766 févr. 22 16:33 IMG_1327.JPG
-rw-r--r-- 1 pmoreau pmoreau    12979764 févr. 12 15:01 irods-webdav.war

$ ils -l
/INRAgrid/home/rods:
  rods              0 replResc;inragrid-mtpResource     31158640 2016-02-23.15:22 & DC_0910.h5
  rods              1 replResc;inragrid-tlsResource     31158640 2016-02-23.15:22 & DC_0910.h5
  rods              0 replResc;inragrid-mtpResource    258998272 2016-02-09.10:03 & debian-8.2.0-amd64-netinst.iso
  rods              1 replResc;inragrid-tlsResource    258998272 2016-02-10.16:24 & debian-8.2.0-amd64-netinst.iso
  rods              0 replResc;inragrid-mtpResource       808569 2016-02-22.16:33 & fdt.jar
  rods              1 replResc;inragrid-tlsResource       808569 2016-02-23.10:06 & fdt.jar
  rods              0 replResc;inragrid-mtpResource         1173 2016-02-26.15:59 & ghosttest.c
  rods              1 replResc;inragrid-tlsResource         1173 2016-02-26.15:59 & ghosttest.c
  rods              0 replResc;inragrid-mtpResource      6878766 2016-02-22.16:33 & IMG_1327.JPG
  rods              1 replResc;inragrid-tlsResource      6878766 2016-02-23.10:06 & IMG_1327.JPG
  rods              0 replResc;inragrid-tlsResource     12979764 2016-02-12.15:01 & irods-webdav.war
  rods              1 replResc;inragrid-mtpResource     12979764 2016-02-12.15:01 & irods-webdav.war
```

When i modify a file, for example ghosttest.c with an editor, the change is recorded on the 2 replicates. 
But when i copy a file with cp on /tmp/fmount, the file is only copied on one replicat:

```
$ cp lightdm.conf /tmp/fmount
$ ils -l
/INRAgrid/home/rods:
  rods              0 replResc;inragrid-mtpResource     31158640 2016-02-23.15:22 & DC_0910.h5
  rods              1 replResc;inragrid-tlsResource     31158640 2016-02-23.15:22 & DC_0910.h5
  rods              0 replResc;inragrid-mtpResource    258998272 2016-02-09.10:03 & debian-8.2.0-amd64-netinst.iso
  rods              1 replResc;inragrid-tlsResource    258998272 2016-02-10.16:24 & debian-8.2.0-amd64-netinst.iso
  rods              0 replResc;inragrid-mtpResource       808569 2016-02-22.16:33 & fdt.jar
  rods              1 replResc;inragrid-tlsResource       808569 2016-02-23.10:06 & fdt.jar
  rods              0 replResc;inragrid-mtpResource         1173 2016-02-26.15:59 & ghosttest.c
  rods              1 replResc;inragrid-tlsResource         1173 2016-02-26.15:59 & ghosttest.c
  rods              0 replResc;inragrid-mtpResource      6878766 2016-02-22.16:33 & IMG_1327.JPG
  rods              1 replResc;inragrid-tlsResource      6878766 2016-02-23.10:06 & IMG_1327.JPG
  rods              0 replResc;inragrid-tlsResource     12979764 2016-02-12.15:01 & irods-webdav.war
  rods              1 replResc;inragrid-mtpResource     12979764 2016-02-12.15:01 & irods-webdav.war
  rods              0 replResc;inragrid-mtpResource           70 2016-02-26.16:24 & lightdm.conf
```

only a single replica of lightdm.conf.

the default resource is set to replResc for this zone.

**Comment by JosKer29** [comment]
Hello,

I have the same trouble with my irods install.
My replication works when i use iput but not with a cp to irodsFuse mount. 

Do you know if this bug is corrected ? I use irods 4.1.10

Best regards, 

Joseph

**Comment by trel** [comment]
This issue is still open.
I don't think this has been addressed or has been fixed by other work at this time.

The replication is not firing - I thought perhaps because of https://github.com/irods/irods/issues/2713, but that was included in 4.1.9.

**Comment by JosKer29** [comment]
I think is that too.
Add files with irodsFs don't firing the replication because replication works when i execute the cmd "iadmin modresc _myResc_ rebalance" after add files.

So if i understand i need to force replication in acSetRescSchemeForCreate function ?

**Comment by trel** [comment]
I'm not sure of the fix at this time.   Have you tested this scenario with 4.2+?

**Comment by JosKer29** [comment]
My client has 4.2.0 (install via yum) 
And my servers (icat and resource) have 4.1.10

**Comment by trel** [comment]
This mismatch of client and server could very well be part of the reason for the trouble.

Can you try this scenario with a 4.1.10 client?   That will help narrow the scope of the bug report.

**Comment by JosKer29** [comment]
Still the same problem with irodsFS install via rpm from this link : ftp://ftp.renci.org/pub/irods/releases/4.1.10/centos7/irods-icommands-4.1.10-centos7-x86_64.rpm

i'll try with this plugin now : 
https://github.com/irods/irods_client_fuse

**Comment by trel** [comment]
Upon further reflection, the fuse client is streaming and not hitting the same codepaths as an iput.

This is most likely a bug in the fuse client - the flags need to be set appropriately.

Your current workaround of using `iadmin modresc replResc rebalance` often is probably the best path forward until the flags get updated.

**Comment by JosKer29** [comment]
ok, thanks i'll be waiting for update or try to find a solution to automate the replication. 

Thanks for your help 
Joseph

**Comment by trel** [comment]
closing this issue - have opened https://github.com/irods/irods_client_fuse/issues/12 to track progress.
