### ISSUE TITLE
iadmin aua not idempotent with same values

### ISSUE THREAD

**Issue by kript** [irods/irods#3104]
If I run `iadmin aua` twice with the same values it puts two copies of the same value in (which on v3 meant neither looked up correctly);

```
irods-dev@irods-sanger1-dev:~$ iadmin aua test test@TEST.SANGER.AC.UK
irods-dev@irods-sanger1-dev:~$ iadmin lua test
test test@TEST.SANGER.AC.UK
irods-dev@irods-sanger1-dev:~$ iadmin aua test test@TEST.SANGER.AC.UK
irods-dev@irods-sanger1-dev:~$ iadmin lua test
test test@TEST.SANGER.AC.UK
test test@TEST.SANGER.AC.UK
```

I suggest that if the same inputs are provided, 'aua' should do nothing, thus being idempotent.
This would help our automation, allowing us to run a home-brew user addition script as many times as our service desk wish without breaking anything..

**Comment by kript** [comment]
I have, naively, no idea how much work this is, but any chance we could get this for 4.1.11 if its easy?

**Comment by trel** [comment]
Seems pretty straightforward.
