### ISSUE TITLE
permit comments in irods_environment.json ?

### ISSUE THREAD

**Issue by mcast** [irods/irods#3107]
### What I see

Trying to put `// foo` or `/* foo */`comments in the irods_environment.json provokes parser errors.

This complies with a strict reading of the JSON spec, but is inconvenient _e.g._ for showing annotated configuration files in documentation.
### What I would like

It would be nice if you could extend the JSON parser to ignore Javascript comments.  Or at least detect them and make the rejection more explicit.
### Supporting links

For going against the JSON spec
- http://stackoverflow.com/questions/244777/can-i-use-comments-inside-a-json-file
- http://blog.getify.com/json-comments/ (I'm not suggesting you bring `JSON.minify()` into `iRODS/lib/core/src/irods_configuration_parser.cpp`)
- https://plus.google.com/+DouglasCrockfordEsq/posts/RK8qyGVaGSr
### What the error message looks like

When I include `// rejected` in my config

```
mca@irods-sanger1-dev:~/.irods$ IRODS_ENVIRONMENT_FILE=~/.irods/irods_environment-cgp.json ils 
ERROR: [-]      iRODS/lib/core/src/irods_configuration_parser.cpp:100:load_json_object :  status [Unknown iRODS error]  errno [Operation not permitted] -- message [failed to load file [/nfs/users/nfs_m/mca/.irods/irods_environment-cgp.json] json error [string or '}' expected near '/']]

Warning: use of legacy configuration [/nfs/users/nfs_m/mca/.irods/irods_environment-cgp.json] is deprecated.
ERROR: _rcConnect: setRhostInfo error, irodsHost is probably not set correctly status = -302000 USER_RODS_HOST_EMPTY
2@irods-sanger1-dev:~/.irods$ 
```

using `ils` from 4.1.8 .
### Workaround

The 4.1.8 icommands seem to be happy with a `"_comment"` field.

**Comment by trel** [comment]
This was one of the negatives of choosing to standardize on JSON, but the benefits were far more important (interoperability, consistency, schema-backed, integration with Python tools, etc.)

We're using the 'comment' workaround ourselves here, in the new externals repository:  https://github.com/irods/externals/blob/master/versions.json#L8

**Comment by mcast** [comment]
Actually, I wonder if the "ignore unknown keys" approach isn't going to cause more problems.

Ignoring certain classes of key makes sense, but to ignore those starting with `irods_` allows silent and hard-to-spot configuration omissions.  I'm not sure what's the best thing to do here, because you also need forwards and backwards compatibilty of config across versions.  Should I raise a separate issue?

I'm sure one of these files is incorrect,
```
mca@irods-sanger1-dev:~$ grep _def .irods/*.json*
.irods/irods_environment-cgp.json:    "irods_default_resource": "cgp-green",
.irods/irods_environment-dev.json:    "irods_def_resource": "demoResc",
```
but I would have to check [the docs](https://docs.irods.org/master/manual/configuration/#irodsirods_environmentjson), or configure a default different to the server's and `iput` a file, to know that the `-dev` one is being ignored.

**Comment by trel** [comment]
Does the `ienv` command show what is 'in effect' enough for you to diagnose what is going on?

**Comment by mcast** [comment]
`ienv` does tell me which values are used, so it answers the `irods_def_resource` question thank you.  It doesn't tell me about keys which are being ignored though, at least at default log level.

Having looked at `ienv` though, I had some other thoughts so I made a separate issue #3113 for that.

**Comment by trel** [comment]
Good.

I'll close this, as there's nothing actionable.  Thanks.

**Comment by mcast** [comment]
I was giving the `irods_def_resource` problem as an example of why I might want Javascript comments, and not JSON-ignored-value comments, in the config file.  (Actually that's two separate but related actionable items.)

Seeing `irods_default_resource` state isn't the main problem I had when I created this issue, and I wouldn't suggest that using ienv solves the comments-in-config-files problem.  If you would still accept the enhancement, could you reopen please?

**Comment by trel** [comment]
I strongly expect we won't be adding comment stripping to all our Python and C++ code that uses these configuration files.  But I'll reopen and push it back to 4.3 for later discussion once the move to JSON for everyone has had a bit more time to play out.

**Comment by mcast** [comment]
Thanks, it will be good to see whether anyone else wants it.

**Comment by trel** [comment]
Closing again due to inactivity.
