### ISSUE TITLE
documentation for irods_log_level values / icommands failing silently

### ISSUE THREAD

**Issue by mcast** [irods/irods#3112]
Having inherited a client config file which set `"irods_log_level": 2`, I was puzzled that failing icommands (v4.1.8) were giving no output and just a non-zero exit code.

Please can [the docs for client config](https://docs.irods.org/master/manual/configuration/#irodsirods_environmentjson), or some other places linked from it, describe the useful values?  Currently it just says

> `irods_log_level` (optional) - Desired verbosity of the iRODS logging

and I found it surprising that 2 is quieter than not setting a value.

**Comment by trel** [comment]
The default is set to 5 I believe (LOG_NOTICE).

https://docs.irods.org/4.1.8/manual/troubleshooting/#debugging-levels
