### ISSUE TITLE
iRODS rule engine "substr" behavior not aligned with c++ substr nor generated docs

### ISSUE THREAD

**Issue by beppodb** [irods/irods#3115]
Whereas C++ "substr" takes arguments for starting position and the number of characters to subset, iRODS RE "substr" appears to be using the arguments as starting position and ending position.

```
*TESTSTRING = "01234567890";
*SUBSTRING = substr(*TESTSTRING,3,5);
writeLine("serverLog", "SUBSTRING = *SUBSTRING");
```

yields "SUBSTRING = 34" rather than the expected "SUBSTRING = 34567".

**Comment by mcast** [comment]
Is this related to #2947 ?  (I just remembered seeing it go past a while ago)

**Comment by beppodb** [comment]
My mistake. Seems the 4.1.5 docs came up first on Google, and I was looking at those.
