### ISSUE TITLE
python database upgrade step

### ISSUE THREAD

**Issue by jasoncoposky** [irods/irods#3121]
the database schema update needs a programmatic mechanism in python to allow for complex changes to the database during upgrade.  in this instance when moving to referencing resource parents by ID ( #3052 ) the parent-child relationship has changed how it is captured in the `r_resc_main` table.

given a parent resource p_resc with a `RESC_CHILDREN`:
`a_child{a_ctx};b_child{b_ctx};c_child{c_ctx}`

split the string on the semicolon, capture the context within the {} and assign that string to the child as the `RESC_PARENT_CONTEXT`. also verify the parent id is the parent in question ( p_resc ).

**Comment by tempoz** [comment]
To test this, upgrade from catalog schema version 4 with a compound resource.
