### ISSUE TITLE
Group access to rodsLog

### ISSUE THREAD

**Issue by kript** [irods/irods#3131]
(as per irods-chat post, creating an issue/feature request  so it doesn't get lost)
Hi Folks,

I have a development server that the developers want to see the rodslog for as they write their code. Now that its possible to set the group for the irods processes in `/etc/irods/service_account.config`, I thought I'd change the group to one that the developers are members of, chown the `/var/lib/irods` and `/etc/irods` and off they go.

Unfortunately, the rodslog files are set to be read by the irods user only;

```
me@irods-dev:~$ ls -lah /var/lib/irods/iRODS/server/log/
total 1.9M
drwxr-xr-x 3 irods-user-dev irods 4.0K Mar 30 12:04 .
drwxr-xr-x 8 irods-user-dev irods 4.0K Mar 22 15:52 ..
drwx------ 2 irods-user-dev irods 4.0K Mar 30 12:09 proc
-rw------- 1 irods-user-dev irods 722K Mar 26 00:18 reLog.2016.03.21
-rw------- 1 irods-user-dev irods 993K Mar 30 14:53 reLog.2016.03.26
-rw------- 1 irods-user-dev irods 132K Mar 30 12:04 rodsLog.2016.03.21
-rw------- 1 irods-user-dev irods 5.6K Mar 30 12:09 rodsLog.2016.03.26
```

Any ideas how I change the umask for rodslog files, or a similar solution? Any better ideas for providing access to the logs for the developers?

**Comment by kript** [comment]
Any chance of getting this into 4.1.9 if its not a big change?

**Comment by trel** [comment]
Yes, we'll get it included.

A change to the permissions on creation of the log file should be a minimal tweak.

**Comment by trel** [comment]
Something like... `server/core/src/rodsServer.cpp:240`:

```diff
#else
     LogFd = open( logFile, O_CREAT | O_WRONLY | O_APPEND, 0644 );
+    close(LogFd);
+    // get username and groupname from service_account.config file?
+    chown( logFile, getpwnam(username)->pw_uid, getgrnam(groupname)->gr_gid );
+    LogFd = open( logFile, O_CREAT | O_WRONLY | O_APPEND, 0644 );
#endif
```

**Comment by trel** [comment]
Alternately...

@kript If it suits you, I think you can change the `umask( 077 )` of the server process in the `iRODS/scripts/perl/irodsctl.pl` script.  In 4-1-stable, it can be changed to `umask( 037 )` and the `rodsLog*` should then be `640`.

We have already removed all the perl in 4.2+, so if you're willing to change this yourself, we can leave the default to be locked down by default in 4-1-stable.

**Comment by kript** [comment]
Apologies for the delay!

I'll give that a try on 4.1.8 thanks (I presume it will stay the same for 4.1.9 also?).

Thanks,

John

**Comment by trel** [comment]
Awaiting confirmation that the `037` local perl fix is enough for now.

If so, we'll bump this to 4.2.0 and then decide whether to loosen the default `077` umask.

**Comment by kript** [comment]
Apologies for dragging this one on, but I wanted some best practice guidance.

At the moment, we have a group set in /etc/irods/service_account.config on the system we want to try the irodsctl.pl fix on, which is not the group that want access to the logs. The clearest way to do this it would seem is to change the group to one that does include those people, however, is there a way to comprehensively change all the permissions once the service_account.config file has been created?

For example, after shutting down the server I could run a find that looks for group memberships and changes them and then update the file, or I could recursively change the resource directories, change the service_account.config file and then rerun the setup and expect it to reset all the permissions. Which approach would you recommend, or do you have a better one?

cheers

John

**Comment by trel** [comment]
If you're willing to bounce the iRODS server... I'd think you could just move any logs that you want out of the directory and save them wherever makes the most sense, with whatever permissions you want.  The server will recreate any log files it needs when it comes back up.

I'd be hesitant to get in the habit of re-running the setup script again.  In 4.2, this won't be allowed - to prevent the accidental loss of any important data/settings.

**Comment by trel** [comment]
moving milestone 4.2.0 - Sanger has said updating the perl script manually in 4.1.x is okay for their use case at the moment.

**Comment by kript** [comment]
Just a quick update to say that the perl umask change only appears to take affect on rotation ;

```
ls -lah /var/lib/irods/iRODS/server/log/rodsLog.2016.0*
-rw------- 1 irods-cgp-test group-test 132K Mar 30 12:04 /var/lib/irods/iRODS/server/log/rodsLog.2016.03.21
-rw------- 1 irods-cgp-test group-test  22K Apr 12 11:55 /var/lib/irods/iRODS/server/log/rodsLog.2016.03.26
-rw------- 1 irods-cgp-test group-test  91M Apr 21 10:32 /var/lib/irods/iRODS/server/log/rodsLog.2016.04.11
-rw------- 1 irods-cgp-test group-test 6.1K Apr 28 10:54 /var/lib/irods/iRODS/server/log/rodsLog.2016.04.21
-rw------- 1 irods-cgp-test group-test 5.1K May 24 14:55 /var/lib/irods/iRODS/server/log/rodsLog.2016.05.01
-rw-r----- 1 irods-cgp-test group-test 2.1K Jun  3 09:44 /var/lib/irods/iRODS/server/log/rodsLog.2016.05.26
-rw------- 1 irods-cgp-test irods   971 Jun 16 14:59 /var/lib/irods/iRODS/server/log/rodsLog.2016.06.16
```
Which is no use of @mcast wants to view the logs of an issue from last night, for example..

**Comment by kript** [comment]
Just a quick update to say that the perl umask change only appears to take affect on rotation ;

```
ls -lah /var/lib/irods/iRODS/server/log/rodsLog.2016.0*
-rw------- 1 irods-cgp-test group-test 132K Mar 30 12:04 /var/lib/irods/iRODS/server/log/rodsLog.2016.03.21
-rw------- 1 irods-cgp-test group-test  22K Apr 12 11:55 /var/lib/irods/iRODS/server/log/rodsLog.2016.03.26
-rw------- 1 irods-cgp-test group-test  91M Apr 21 10:32 /var/lib/irods/iRODS/server/log/rodsLog.2016.04.11
-rw------- 1 irods-cgp-test group-test 6.1K Apr 28 10:54 /var/lib/irods/iRODS/server/log/rodsLog.2016.04.21
-rw------- 1 irods-cgp-test group-test 5.1K May 24 14:55 /var/lib/irods/iRODS/server/log/rodsLog.2016.05.01
-rw-r----- 1 irods-cgp-test group-test 2.1K Jun  3 09:44 /var/lib/irods/iRODS/server/log/rodsLog.2016.05.26
-rw------- 1 irods-cgp-test irods   971 Jun 16 14:59 /var/lib/irods/iRODS/server/log/rodsLog.2016.06.16
```
Which is no use of @mcast wants to view the logs of an issue from last night, for example..

**Comment by trel** [comment]
Expecting this to be remedied by moving to rsyslog in 4.3.0
