### ISSUE TITLE
syslog export of rodsLog

### ISSUE THREAD

**Issue by kript** [irods/irods#3132]
Related to #3131 and [this thread](https://groups.google.com/forum/#!topic/irod-chat/xMltK0UDuNo) in irods-chat, its not clear how one redirects the rodsLog to go to syslog instead. Under V3 this was a compile option in the config/config.mk, but there is nothing in the documentation about how to do this in 4.X, and compilation is no longer the recommended way to deploy a production instance.

If we could redirect to syslog, we could also allow another group access to it, control rotation etc, so that would be helpful.

**Comment by trel** [comment]
related to https://github.com/irods/irods/issues/2730 and https://github.com/irods/irods/issues/2112

**Comment by korydraughn** [comment]
I think this can be closed.
