### ISSUE TITLE
`ilsresc -l` cross-version failure

### ISSUE THREAD

**Issue by mcast** [irods/irods#3136]
I'm briefly testing the use of v4-icommands against v3-servers (4.1.8 and 3.3.1), and I have both
- failure, in that the v4-ilsresc provokes an error.  
  I don't need this cross-version access to work, we just wondered if it might ease some rollout problems.
- bad return code, when run as `ilsresc -l`.  
  This is bad, because callers might well assume nothing is wrong.

```
mca@irods-cgp-dev:~$ echo $IRODS_ENVIRONMENT_FILE 
/nfs/users/nfs_m/mca/.irods/irods_environment-cgpro.json
mca@irods-cgp-dev:~$ ilsresc -h |& tail -n1
iRODS Version 4.1.8                Feb 2016                      ilsresc
mca@irods-cgp-dev:~$ which ilsresc
/usr/bin/ilsresc
mca@irods-cgp-dev:~$ ilsresc; echo $?
rcGenQuery failed with error -823000 CAT_UNKNOWN_TABLE 
40
mca@irods-cgp-dev:~$ ilsresc -l; echo $?
rcGenQuery failed with error -823000 CAT_UNKNOWN_TABLE 
0
```

In both cases, error text is to stderr and stdout is empty.

[edit: fixed my [unusual prompt display](http://mcra.t8o.org/2016/03/08/exit-code-in-bash-prompt.html) where I chopped a line out of the transcript]

**Comment by trel** [comment]
Closing - we've seen federation with 3.x work for a while.
