### ISSUE TITLE
-R and -N0 interference results in iget error

### ISSUE THREAD

**Issue by AndreyNevolin** [irods/irods#3140]
iget fails when options -R[resource_name] and -N0 (or -N1) are used simultaneously.

iget obj_name succeeds
iget -Rresc_name obj_name succeeds
iget -N0 obj_name succeeds

But "iget -Rresc_name -N0 obj_name" fails

![1](https://cloud.githubusercontent.com/assets/7734325/14526805/034d42b8-0257-11e6-9652-4d1c0545ebe5.png)

No rules were added or modified to produce this example. iRODS 4.1.8 was used.

**Comment by trel** [comment]
needs cherry-picking to XBB-2
