### ISSUE TITLE
icommands (4.1.8) return nothing, exit zero

### ISSUE THREAD

**Issue by mcast** [irods/irods#3142]
I have seen several instances of icommands returning exit code zero and empty stdout, including

* `iput -h`
* `isysmeta ls -d <ipath>`
* `imv <here> <there>`  
  The fact that the empty return with no action is indistinguishable from a successful run is a particular problem, and so I regard this as a serious bug.
* `ils /`

I think this is an intermittent failure mode of many or all the (compiled?) icommands.  I believe the significant factors in provoking it are

* simultaneous running of the command
* on one host
* to the same iCAT
* possibly, using an NFS home directory
* possibly, using `$HOME` not equal to the user's real homedir

I am currently running a script to repeatedly exercise `iput -h` and `ils /` in two or four processes, on a couple of dev zones here.

**Comment by mcast** [comment]
The rodsLog contains some entries which I believe are relevant - I don't have times for the errors, but there wasn't anything else happening.  I don't have direct access to the rodsLog (#3131) and have to wait for a sysad to send me relevant lines.

```
Apr 13 21:33:02 pid:28037 ERROR: [-]    iRODS/server/core/src/rsApiHandler.cpp:470:readAndProcClientMsg :  status [SYS_HEADER_READ_LEN_ERR]  errno [No such file or directory] -- message []
Apr 13 22:05:18 pid:3598 ERROR: [-]     iRODS/server/core/src/rodsAgent.cpp:241:main :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message []
Apr 13 22:05:25 pid:3619 ERROR: [-]     iRODS/server/core/src/rodsAgent.cpp:241:main :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message []
Apr 14 11:44:46 pid:5452 ERROR: [-]     iRODS/server/core/src/rodsAgent.cpp:241:main :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message []
```

I'm running the icommands on the iCAT host, and the other iRes servers are down (awaiting upgrade from 3.3.1 to 4.1.8).

I now find that I can't provoke the problem, so I will try giving the machine (VM with 8G RAM, 4G swap) some memory pressure.  The `irodsReServer` had vsize=11.2G until the OOMkiller killed it, so I suspect this is why the bug has gone into hiding.

**Comment by mcast** [comment]
What I hadn't realised is that when the OOMkiller zapped irodsReServer, it didn't come back...  I didn't miss it because I have no rules in this dev zone (but #3143!).

* I found an old memory leak bug #2349.  We are using Oracle for the iCAT, but I can't tell whether it's a regression.  Certainly there was a leak.
* The irodsReServer was sitting on vsize=11.2G when I found it
* Recent history (atop) showed 80M/day growth inside a 10 minute window, around either 07:30 or 08:30, but the time change was somewhat after the GMT->BST localtime change so I don't know why the time of day moved.  Then it stopped.  Possibly a cronjob was modified over this period.
* Before that, lost off the atop record, the machine overall showed a steady growth of 2.5 GB to 11.8 GB over 5 days, levelling out when all RAM and most of the swap was used.

When the irodsReServer was restarted, and memory pressure was still artificially applied, I got the no-action-no-error bug again.

**Comment by mcast** [comment]
I spent a chunk of Friday trying to reproduce this and failed, so I will make an end run around the lot: when I expect a command to have side effects, I will check they happened.  Slow but sure.

Thanks for reading...  I'll leave you to close this issue.

**Comment by trel** [comment]
Thanks @mcast - I'll close this for now - if you do identify a particular issue, reopen this one or a new one.
