### ISSUE TITLE
Docs: describe 4.2 process model

### ISSUE THREAD

**Issue by mcast** [irods/irods#3143]
I found the irodsReServer had died (OOMkiller, #3142) and was not restarted automatically.  I didn't notice any symptoms, and wondered what I had lost.

As I suspected from the name, it is the [iRODS Rule Execution server](https://github.com/irods/irods/blob/4.1.8/iRODS/server/core/src/irodsReServer.cpp).

Please could the docs list the names of processes which may be seen with ps, what they're doing, how long they should last and guidelines on how much memory they are likely to use?

**Comment by trel** [comment]
This is provided in the new https://github.com/irods/irods_docs repository.
