### ISSUE TITLE
Request for config file checking tool / linter & validation of JSON

### ISSUE THREAD

**Issue by kript** [irods/irods#3145]
Hi Folks,

If one makes a mistake in editing the JSON for one of the config files (/etc/irods/server_config.json say), such as an incorrect value, wrong quote or some such, then an already running server will crash.

Is it possible to syntax check the JSON before having it applied? The simplest way would appear to be to have a tool that uses the existing schema settings to validate a file parsed via command line that can then be copied over the top of the working config, but having the server check and put a message in the log for incorrect files might also work (and would give better survivability for 'fat finger' moments)..

Apologies if this might be two issues, depending on how (or if of course!) its solved..

**Comment by trel** [comment]
If I'm interpreting what you're asking for correctly... I think we already have that?  It's the same tool that the server uses before it stands up.

In 4.2 and beyond, this will be in the top level `scripts` directory:
```
$ ./scripts/validate_json.py 
Usage: ./scripts/validate_json.py <configuration_file> <schema_url>
```

Does that look sufficient?   I think, you could build your own workflow to satisfy whatever preflights/checks you may need.

**Comment by kript** [comment]
Sorry for the delay, I thought I'd replied!

yes thats just what we want, along as the schema url can handle a file path.
Could this be incorporated into 4.1.9, if its 'just' a standalone script?

Thanks!

John

**Comment by trel** [comment]
In 4-1-stable (aka 4.1.8 and soon, 4.1.9) the file is already located at `iRODS/scripts/python/validate_json.py` and should take a file path just fine.

**Comment by kript** [comment]
I don't think this is in 4.1.8. Am I missing something obvious?;

```
irods-dev@irods-sanger1-dev:~$ pwd
/usr/local/iRODS
irods-dev@irods-sanger1-dev:~$ scripts/python/validate_json.py ./server_config.json_seq-dev 
-bash: scripts/python/validate_json.py: No such file or directory
irods-dev@irods-sanger1-dev:~$ pwd
/usr/local/iRODS
irods-dev@irods-sanger1-dev:~$ ls scripts/
admin	   finishSetup	    irodsprompt   notify  README.txt  uninstallPostgres
configure  installPostgres  izoneinfo.sh  perl	  runperl
irods-dev@irods-sanger1-dev:~$ find ./ -iname validate_json.py
```

**Comment by trel** [comment]
In 4-1-stable, it's still in ./iRODS/...

```
11:08AM (4-1-stable):~/irods $ find . -name validate_json.py
./iRODS/scripts/python/validate_json.py
```

**Comment by kript** [comment]
Well, thats embarrassing, looking in the wrong directory, sorry!

Now that I've found it, I'm having issue getting it to work with a file URI;
```
python /var/lib/irods/iRODS/scripts/python/validate_json.py server_config.json_sanger1-dev file:///etc/irods/irods_schemas
ERROR: Validation Failed for [server_config.json_sanger1-dev]
     : against [file:///etc/irods/irods_schemas]
  IOError: [Errno 21] Is a directory: '/etc/irods/irods_schemas'
```
Is that expected behavior ?

For that matter, I'm clearly using it wrong;

```
python /var/lib/irods/iRODS/scripts/python/validate_json.py 
Usage: /var/lib/irods/iRODS/scripts/python/validate_json.py <configuration_file> <schema_url>
...
python /var/lib/irods/iRODS/scripts/python/validate_json.py server_config.json_sanger1-dev https://schemas.irods.org/configuration
WARNING: Validation Failed for [server_config.json_sanger1-dev]
       : against [https://schemas.irods.org/configuration]
  ValueError: No JSON object could be decoded
```
Both examples are against a copy of /etc/irods/server_config.json that I wanted to validate before copying back, so should be a good file, before my modifications...

**Comment by trel** [comment]
The schema URL needs to be a specific file that you are validating against.  Not the entire directory.

```
python /var/lib/irods/iRODS/scripts/python/validate_json.py server_config.json_sanger1-dev https://schemas.irods.org/configuration/v2/server_config.json
```

local `file:///` locations should work as well:
 https://github.com/irods/irods/blob/4-1-stable/iRODS/scripts/python/validate_json.py#L36

**Comment by kript** [comment]
Thanks, that worked well both using the URL and file URI. I've added it to our documentation/tips and tricks page!
