### ISSUE TITLE
iRODS 'rebalance' is pretty much unusable in complex environments

### ISSUE THREAD

**Issue by triitaojcsc** [irods/irods#3147]
The 'rebalance' functionality introduced in iRODS 4.X.X requires fixes/improvements to make it usable in environments with non-trivial resource trees and file amounts.

This ticket is quite long due to explanations that I felt were needed to understand the situation. But the short version of how to reproduce these problems is:

#### / Start short version

1. Have a large environment with a resource tree, whose root is of type 'replication'.
2. Have a lot of files.
3. Have a lot of files, which only have one replica (type A files). You want to balance these files using 'rebalance', because 'irepl' doesn't work for 'replication' nodes or their children.
4. Have hundreds or thousands of files (type B files) with a mismatching/missing checksum/size/anything that causes 'rebalance' to crash. Rebalance will always crash when attempting to balance a "broken" file.
5. Can't rebalance type A files until you've manually fixed type B files, because rebalance crashes.
6. Too many type B files to manually fix, so unable to balance type A files.
7. Rebalance can only be run for the 'replication' root so impossible to divide & conquer resources separately.

### Environment

```
[irods@localhost ~]$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.7 (Santiago)
```
```
[irods@localhost ~]$ rpm -qa | grep irods
irods-icat-4.1.8-1.x86_64
irods-database-plugin-postgres93-1.8_4.1.8-1.x86_64
```

(And the same 4.1.8-1 version for resource servers.)

```
[irods@localhost ~]$ ilsresc --tree
repl-group:replication
├── host-group:random
│   ├── disk-group-1:random
│   │   ├── disk-1.1:unix file system
│   │   ├── disk-1.2:unix file system
│   │   ...
│   │   └── disk-1.y:unix file system
│   ├── disk-group-2:random
│   │   ├── disk-2.1:unix file system
│   │   ├── disk-2.2:unix file system
│   │   ...
│   │   └── disk-2.y:unix file system
│   ...
│   ...
│   └── disk-group-x:random
│       ├── disk-x.1:unix file system
│       ├── disk-x.2:unix file system
│       ...
│       └── disk-x.y:unix file system
└── weightResc:passthru
    └── tape-group:random
        ├── tape-1:unix file system
        └── tape-2:unix file system
```
(In the above, x and y can be big numbers.)

### Starting situation

Lets assume that different users have uploaded millions of files that have been replicated throughout the "repl-group" tree, so that one replica is stored under a random leaf in "host-group" and another replica is stored under a random leaf in "weightResc". Two proper uploaded files might look like this:

(Ideal situation)

File A:

```
[irods@localhost ~]$ ils -LA test_file_A.dat
  triitaoj          0 repl-group;host-group;disk-group-1;disk-1.3         1609 2016-04-20.13:30 & test_file_A.dat
    sha2:ddY+JHLAcAfaDSi24divfk3rRwMHVOfb95QqjDaCrE0=    data file    /resources/disk-1.3/test/triitaoj/test_file_A.dat
        ACL - rodsadmin#ida:own   test.triitaoj#ida:own   rods#ida:own   
  triitaoj          1 repl-group;weightResc;tape-group;tape-1         1609 2016-04-20.13:30 & test_file_A.dat
    sha2:ddY+JHLAcAfaDSi24divfk3rRwMHVOfb95QqjDaCrE0=    data file    /nfs/tape-1/test/triitaoj/test_file_A.dat
        ACL - rodsadmin#ida:own   test.triitaoj#ida:own   rods#ida:own
```

File B:

```
[irods@localhost ~]$ ils -LA test_file_B.dat
  triitaoj          0 repl-group;host-group;disk-group-2;disk-2.6         1609 2016-04-20.13:30 & test_file_B.dat
    sha2:ddY+JHLAcAfaDSi24divfk3rRwMHVOfb95QqjDaCrE0=    data file    /resources/disk-2.6/test/triitaoj/test_file_B.dat
        ACL - rodsadmin#ida:own   test.triitaoj#ida:own   rods#ida:own   
  triitaoj          1 repl-group;weightResc;tape-group;tape-1         1609 2016-04-20.13:30 & test_file_B.dat
    sha2:ddY+JHLAcAfaDSi24divfk3rRwMHVOfb95QqjDaCrE0=    data file    /nfs/tape-2/test/triitaoj/test_file_B.dat
        ACL - rodsadmin#ida:own   test.triitaoj#ida:own   rods#ida:own   
```

Now, if we assume that sometimes unexpected things happen when transfering files in the real world, the files might actually look like this:

(Real world)

File A:

```
[irods@localhost ~]$ ils -LA test_file_A.dat
  triitaoj          0 repl-group;host-group;disk-group-1;disk-1.3         1609 2016-04-20.13:30 & test_file_A.dat
    sha2:ddY+JHLAcAfaDSi24divfk3rRwMHVOfb95QqjDaCrE0=    data file    /resources/disk-1.3/test/triitaoj/test_file_A.dat
        ACL - rodsadmin#ida:own   test.triitaoj#ida:own   rods#ida:own   
```

The 'tape-1' and 'tape-2' resources were not available during the transfer (a common occurrence in the real world when remote resources are occasionally unavailable), so the replication tree gives us only one replica. The reason _why_ this happened is not relevant to this ticket/problem.

File B:

```
[irods@localhost ~]$ ils -LA test_file_B.dat
  triitaoj          0 repl-group;host-group;disk-group-2;disk-2.6         0 2016-04-20.13:30 & test_file_B.dat
    sha2:ddY+JHLAcAfaDSi24divfk3rRwMHVOfb95QqjDaCrE0=    data file    /resources/disk-2.6/test/triitaoj/test_file_B.dat
        ACL - rodsadmin#ida:own   test.triitaoj#ida:own   rods#ida:own   
```

(In the above, I've just set the size to zero to "show" the replica is broken. The size on the physical resource might be correct.)

The client, or the server, messed up the file transfer. The reason _why_ this happened is not relevant to this ticket/problem. Maybe the client cancelled an 'iput' file transfer and then used 'iput' again with the -f option immediately afterwards, or maybe the irodsServer process just decided to segfault. Maybe two users with different clients were handling the same file. Maybe some optimistic person tried to use davfs with iRODS.

For testing purposes you can simulate a broken transfer easily (for example, break the other replica with `$ echo "foobar" >> /nfs/tape-2/test/triitaoj/test_file_B.dat`).

### The problem

Before iRODS 4.X.X and the 'replication' resource, we could have used 'irepl' to generate the missing replica for file A. But the 'replication' resource and its children aren't valid destination resources for irepl. Instead of irepl, we must use the 'rebalance' command.

If all the files that require fixing were similar to file A, running 'rebalance' wouldn't be a problem. But unfortunately "broken" files of type B exist too.

The 'rebalance' command isn't actually a command, but rather an option to the 'iadmin modresc' command. The syntax is '`iadmin modresc <resource> rebalance`' and the help text for this option is simply "'rebalance' will trigger the rebalancing operation on a coordinating resource node."

Running 'rebalance' causes it to crash if it encounters "broken" files of type B. The command typically produces an error message that isn't very useful (ERROR: rcGeneralAdmin failed with error -1 Unknown iRODS error Operation not permitted). Luckily, iRODS logs on the main ICAT typically show the offending file in a rebalance related error message, so it can be manually fixed. After the file has been manually fixed, rebalance can be executed again.

Now imagine if there are _a lot_ of A type files and maybe hundreds or thousands of B type files. The '`iadmin modresc <resource> rebalance`' command will only accept the root of the replication tree as the `<resource>`. Each time rebalance is executed, the command will query the database to determine what needs to be "balanced" under the root. This premilinary phase can take a lot of time. After this phase is done, rebalance starts the actual balancing (replication) of files. That is, until it runs in to the first file of type B and crashes.

So, fixing all the files of type A in an iRODS instance that also contains files of type B is pretty much impossible if the resource tree is large and there are a lot of files.

### Severity

Rebalance is currently pretty much unusable in large environments due to large amount of manual work required. This results in heaps of unreplicated files with no way to balance them.

### Proposed solution

Rebalance would be usable if some of the fixes/improvements below would be implemented:

1. Make rebalance a binary command instead of an option to iadmin modresc.
2. Give rebalance an option to SKIP files of type B when encountering them instead of crashing. Not sure if crashing is intended as a feature. But it shouldn't be.
3. Give rebalance an option to target ANY resource (for example disk-2.6). Instead of going through all the files of "repl-group" in the premilinary phase, it should just examine files in "disk-2.6", "tape-1" and "tape-2". (Starting from disk-2.6, go up to find the 'replication' parent resource; determine what branches already have a replica; don't touch those branches!) (Note: If you're thinking that this could result in extra replicas, it's the smaller of the two problems as the 'itrim' command works (unlike irepl) and it's a lot more fun to have useless extra replicas instead of missing replicas.)
4. Give rebalance an option to print out files that it has "balanced", like the -P option to iput.
5. Give rebalance an option to print out files that it will handle, like the --dryrun option to iput.

-- Taneli Riitaoja / CSC - IT Center for Science Ltd.

**Comment by trel** [comment]
This is an amazingly thorough write up - thank you.

To paraphrase/relabel the scenarios:

- Type A = missing good replica(s)
- Type B = the only replica is broken/stale

Without reproducing all of this myself, it seems this is the blocker/crux of this particular issue:

> Running 'rebalance' causes it to crash if it encounters "broken" files of type B. The command typically produces an error message that isn't very useful (ERROR: rcGeneralAdmin failed with error -1 Unknown iRODS error Operation not permitted). Luckily, iRODS logs on the main ICAT typically show the offending file in a rebalance related error message, so it can be manually fixed. After the file has been manually fixed, rebalance can be executed again.

Regarding the proposed solution items:

1. a new binary, is confusing to me - this is already an operation on the server side - it's just a question of how it gets implemented.  Is that correct?

2. skip option, seems like the easiest partial solution.  If files are encountered that are in a broken state (Type B - aka, NO good replicas)... the code currently exits on the server-side with the error you described (it doesn't crash/segfault) and stops all other rebalance progress. (If there *is* a good replica available, the rebalance should heal that dataobject's other bad/missing replicas - making the scenario a Type A scenario).

3. sub-tree targeting, is interesting - we'll need to think through its ramifications - definitely a new feature request.

4. verbosity/progress, is a helpful feature request.

5. dry-run, is a helpful feature request.

**Comment by jasoncoposky** [comment]
Thank you for the detailed report, we will reproduce this and get it fixed immediately.  Per Terrell's comments above:

1.  Making the rebalance a separate icommand would imply that it is available for all users to run?  Otherwise the fact that it is a subcomand of iadmin isolates it for use by rodsadmin users only.

2.  Agreed, should no good replicas exist we should skip them entirely otherwise repliicate from a good known instance.  This should already be the behavior of the replication API which is most likely the source of the bug.

3.  Agreed, this would be a useful capability.  I can see no immediate down side.

4.  Agreed.

5.  Agreed, although this could take a while to compute on large systems.

**Comment by jasoncoposky** [comment]
Can you provide any errors you have in the rodsLog related to the rebalance?

Do you get a SYS_COPY_LEN_ERR for the broken replicas ( type B )?

**Comment by triitaojcsc** [comment]
Hi,

"--a new binary, is confusing to me - this is already an operation on the server side - it's just a question of how it gets implemented. Is that correct?"

Basically yes. My list of propositions was supposed to be unordered, but Github markup failed me again. This was more like an afterthought. For such an important tool as rebalance, I'd like to see it have a proper help text/some documentation too.

"--the code currently exits on the server-side with the error you described (it doesn't crash/segfault)--"

Ah, yes, true. I should've said it exits instead of crashes.

Your suggestions sound very sound.

"Can you provide any errors you have in the rodsLog related to the rebalance?"

Sure thing, I realize that the information I gave to reproduce these problems was a bit lacking:

### Test replication tree

```
[irods@icat-test ~]$ ilsresc --tree
random-host-tape-repl:replication
├── random-host-group:random
│   ├── random-disk-group-host1:random
│   │   ├── stored-1.1:unix file system
│   │   └── stored-1.2:unix file system
│   └── random-disk-group-host2:random
│       ├── stored-2.1:unix file system
│       └── stored-2.2:unix file system
└── weightResc:passthru
    └── random-tape-group:random
        ├── stored-3.1:unix file system
        └── stored-3.2:unix file system
```

### Create test data:

```
[triitaoj@localhost ~]$ echo "iRODS + rebalance = test" > test_data.txt
```

I'll do all these tests with a single replica. These problems can occur with two or more replicas, when one or both of them have problems, but I'm pretty sure the error messages are the same.

### Appending test:

Transfer the file using iput

```
[triitaoj@localhost ~]$ iput test_data.txt
```
```
[triitaoj@localhost ~]$ ils -LA test_data.txt
  triitaoj          0 random-host-tape-repl;random-host-group;random-disk-group-host1;stored-1.1           25 2016-04-22.10:49 & test_data.txt
    sha2:JDJjWoLtT3e/CWMU/4kaAnm+CcZvfkdWj1DB+jfouKg=    ascii text    /irods/stored-1.1/datu/test/triitaoj/test_data.txt
        ACL - rods#testzone:own   datu#testzone:own   triitaoj#testzone:own   rodsadmin#testzone:own   datu.test#testzone:own   
  triitaoj          1 random-host-tape-repl;weightResc;random-tape-group;stored-3.1           25 2016-04-22.10:49 & test_data.txt
    sha2:JDJjWoLtT3e/CWMU/4kaAnm+CcZvfkdWj1DB+jfouKg=    ascii text    /irods/stored-3.1/datu/test/triitaoj/test_data.txt
        ACL - rods#testzone:own   datu#testzone:own   triitaoj#testzone:own   rodsadmin#testzone:own   datu.test#testzone:own   
[triitaoj@localhost ~]$ 
```

Trim the second replica

```
[irods@icat-test ~]$ itrim -M -n 1 -N 1 /testzone/datu/test/triitaoj/test_data.txt
```

Check that trimming was ok

```
[triitaoj@localhost ~]$ ils -LA test_data.txt
  triitaoj          0 random-host-tape-repl;random-host-group;random-disk-group-host1;stored-1.1           25 2016-04-22.10:49 & test_data.txt
    sha2:JDJjWoLtT3e/CWMU/4kaAnm+CcZvfkdWj1DB+jfouKg=    ascii text    /irods/stored-1.1/datu/test/triitaoj/test_data.txt
        ACL - rods#testzone:own   datu#testzone:own   triitaoj#testzone:own   rodsadmin#testzone:own   datu.test#testzone:own   
[triitaoj@localhost ~]$ 
```

Append text to the remaining replica

```
[irods@resource-test triitaoj]$ echo "I should make more automated tests..." >> /irods/stored-1.1/datu/test/triitaoj/test_data.txt
[irods@resource-test triitaoj]$ cat /irods/stored-1.1/datu/test/triitaoj/test_data.txt
iRODS + rebalance = test
I should make more automated tests...
```

Execute rebalance

```
[irods@icat-test ~]$ date; time iadmin modresc random-host-tape-repl rebalance; date
Fri Apr 22 10:52:48 EEST 2016

real	0m2.140s
user	0m0.012s
sys	0m0.003s
Fri Apr 22 10:52:50 EEST 2016
[irods@icat-test ~]$ 
```

Rebalance encountered no problems and finished execution.

Check rodsLog

```
Apr 22 10:52:50 pid:9201 NOTICE: writeLine: inString = ADMIN (acPostProcForRepl): Started acPostProcForRepl for /testzone/datu/test/triitaoj/test_data.txt (25 bytes)
...
...
Apr 22 10:52:50 pid:9201 NOTICE: writeLine: inString = ADMIN (acPostProcForRepl): Finished acPostProcForRepl for /testzone/datu/test/triitaoj/test_data.txt (25 bytes)
```

Rebalancing was a success, it seems.

Check the file

```
[triitaoj@localhost ~]$ ils -LA test_data.txt
  triitaoj          0 random-host-tape-repl;random-host-group;random-disk-group-host1;stored-1.1           25 2016-04-22.10:49 & test_data.txt
    sha2:JDJjWoLtT3e/CWMU/4kaAnm+CcZvfkdWj1DB+jfouKg=    ascii text    /irods/stored-1.1/datu/test/triitaoj/test_data.txt
        ACL - rods#testzone:own   datu#testzone:own   triitaoj#testzone:own   rodsadmin#testzone:own   datu.test#testzone:own   
  triitaoj          1 random-host-tape-repl;weightResc;random-tape-group;stored-3.2           25 2016-04-22.10:52 & test_data.txt
    sha2:JDJjWoLtT3e/CWMU/4kaAnm+CcZvfkdWj1DB+jfouKg=    ascii text    /irods/stored-3.2/datu/test/triitaoj/test_data.txt
        ACL - rods#testzone:own   datu#testzone:own   triitaoj#testzone:own   rodsadmin#testzone:own   datu.test#testzone:own   
[triitaoj@localhost ~]$ 
```

Check the replicated second replica

```
[root@resource3-test ~]# cat /irods/stored-3.2/datu/test/triitaoj/test_data.txt
iRODS + rebalance = test
[root@resource3-test ~]#
```

No appended text in the resulting replica. Did iRODS replicate only up to the first 25 bytes (size in the database)? And calculated the checksum only for that part?

### Prepending test:

(Skipping explanations for identical commands)

```
[triitaoj@localhost ~]$ iput test_data.txt
```
```
[triitaoj@localhost ~]$ ils -LA test_data.txt
  triitaoj          0 random-host-tape-repl;random-host-group;random-disk-group-host1;stored-1.2           25 2016-04-22.11:02 & test_data.txt
    sha2:JDJjWoLtT3e/CWMU/4kaAnm+CcZvfkdWj1DB+jfouKg=    ascii text    /irods/stored-1.2/datu/test/triitaoj/test_data.txt
        ACL - rods#testzone:own   datu#testzone:own   triitaoj#testzone:own   rodsadmin#testzone:own   datu.test#testzone:own   
  triitaoj          1 random-host-tape-repl;weightResc;random-tape-group;stored-3.1           25 2016-04-22.11:02 & test_data.txt
    sha2:JDJjWoLtT3e/CWMU/4kaAnm+CcZvfkdWj1DB+jfouKg=    ascii text    /irods/stored-3.1/datu/test/triitaoj/test_data.txt
        ACL - rods#testzone:own   datu#testzone:own   triitaoj#testzone:own   rodsadmin#testzone:own   datu.test#testzone:own   
[triitaoj@localhost ~]$ 
```

```
[irods@icat-test ~]$ itrim -M -n 1 -N 1 /testzone/datu/test/triitaoj/test_data.txt
```

```
[triitaoj@localhost ~]$ ils -LA test_data.txt
  triitaoj          0 random-host-tape-repl;random-host-group;random-disk-group-host1;stored-1.2           25 2016-04-22.11:02 & test_data.txt
    sha2:JDJjWoLtT3e/CWMU/4kaAnm+CcZvfkdWj1DB+jfouKg=    ascii text    /irods/stored-1.2/datu/test/triitaoj/test_data.txt
        ACL - rods#testzone:own   datu#testzone:own   triitaoj#testzone:own   rodsadmin#testzone:own   datu.test#testzone:own   
[triitaoj@localhost ~]$
```

Prepend text to the remaining replica

```
[irods@resource-test triitaoj]$ vim /irods/stored-1.2/datu/test/triitaoj/test_data.txt
[irods@resource-test triitaoj]$ cat /irods/stored-1.2/datu/test/triitaoj/test_data.txt
42
iRODS + rebalance = test
[irods@resource-test triitaoj]$ 
```

```
[irods@icat-test ~]$ date; time iadmin modresc random-host-tape-repl rebalance; date
Fri Apr 22 11:06:58 EEST 2016
ERROR: rcGeneralAdmin failed with error -1 Unknown iRODS error Operation not permitted

real	0m1.783s
user	0m0.013s
sys	0m0.001s
Fri Apr 22 11:07:00 EEST 2016
[irods@icat-test ~]$ 
```

Note the error message given by the rebalance command.

```
Apr 22 11:07:00 pid:10449 NOTICE: procChksumForClose: chksum mismatch for for /testzone/datu/test/triitaoj/test_data.txt src [sha2:JDJjWoLtT3e/CWMU/4kaAnm+CcZvfkdWj1DB+jfouKg=] new [sha2:JPWlI9tRfEHW7Z+nq21B1IVR1ib6EwuEHw06PKz64oM=]
Apr 22 11:07:00 pid:10449 NOTICE: rsDataObjRepl - Failed to replicate data object.
Apr 22 11:07:00 pid:10449 ERROR: [-]    iRODS/server/api/src/rsGeneralAdmin.cpp:607:_rsGeneralAdmin :  status [USER_CHKSUM_MISMATCH]  errno [] -- message [failed to rebalance resource]
        [-]     librepl.cpp:1668:replRebalance :  status [USER_CHKSUM_MISMATCH]  errno [] -- message []
                [-]     irods_repl_rebalance.cpp:559:proc_results_for_rebalance :  status [USER_CHKSUM_MISMATCH]  errno [] -- message []
                        [-]     irods_repl_rebalance.cpp:59:repl_for_rebalance :  status [USER_CHKSUM_MISMATCH]  errno [] -- message [Failed to replicate the data object [/testzone/datu/test/triitaoj/test_data.txt]]

Apr 22 11:07:00 pid:10449 NOTICE: rsGeneralAdmin: rcGeneralAdmin error -1
Apr 22 11:07:00 pid:10449 NOTICE: readAndProcClientMsg: received disconnect msg from client
Apr 22 11:07:00 pid:10449 NOTICE: Agent exiting with status = 0
Apr 22 11:07:00 pid:13992 NOTICE: Agent process 10449 exited with status 0
Apr 22 11:07:00 pid:13992 NOTICE: Agent process 10453 exited with status 0
```

We get a checksum error, which stops rebalance.

```
[triitaoj@localhost ~]$ ils -LA test_data.txt
  triitaoj          0 random-host-tape-repl;random-host-group;random-disk-group-host1;stored-1.2           25 2016-04-22.11:02 & test_data.txt
    sha2:JDJjWoLtT3e/CWMU/4kaAnm+CcZvfkdWj1DB+jfouKg=    ascii text    /irods/stored-1.2/datu/test/triitaoj/test_data.txt
        ACL - rods#testzone:own   datu#testzone:own   triitaoj#testzone:own   rodsadmin#testzone:own   datu.test#testzone:own   
[triitaoj@localhost ~]$ 
```
This time rebalance didn't replicate the file, which is a good thing.

### Substituting test:

```
[triitaoj@localhost ~]$ iput test_data.txt
```
```
[triitaoj@localhost ~]$ ils -LA test_data.txt
  triitaoj          0 random-host-tape-repl;random-host-group;random-disk-group-host2;stored-2.1           25 2016-04-22.11:14 & test_data.txt
    sha2:JDJjWoLtT3e/CWMU/4kaAnm+CcZvfkdWj1DB+jfouKg=    ascii text    /irods/stored-2.1/datu/test/triitaoj/test_data.txt
        ACL - rods#testzone:own   datu#testzone:own   triitaoj#testzone:own   rodsadmin#testzone:own   datu.test#testzone:own   
  triitaoj          1 random-host-tape-repl;weightResc;random-tape-group;stored-3.2           25 2016-04-22.11:14 & test_data.txt
    sha2:JDJjWoLtT3e/CWMU/4kaAnm+CcZvfkdWj1DB+jfouKg=    ascii text    /irods/stored-3.2/datu/test/triitaoj/test_data.txt
        ACL - rods#testzone:own   datu#testzone:own   triitaoj#testzone:own   rodsadmin#testzone:own   datu.test#testzone:own   
[triitaoj@localhost ~]$ 
```

```
[irods@icat-test ~]$ itrim -M -n 1 -N 1 /testzone/datu/test/triitaoj/test_data.txt
```

```
[triitaoj@localhost ~]$ ils -LA test_data.txt
  triitaoj          0 random-host-tape-repl;random-host-group;random-disk-group-host2;stored-2.1           25 2016-04-22.11:14 & test_data.txt
    sha2:JDJjWoLtT3e/CWMU/4kaAnm+CcZvfkdWj1DB+jfouKg=    ascii text    /irods/stored-2.1/datu/test/triitaoj/test_data.txt
        ACL - rods#testzone:own   datu#testzone:own   triitaoj#testzone:own   rodsadmin#testzone:own   datu.test#testzone:own   
[triitaoj@localhost ~]$ 
```

Substitute a letter (keeping the size in bytes same)

```
[root@resource2-test ~]# sed -i 's/test/best/g' /irods/stored-2.1/datu/test/triitaoj/test_data.txt && cat /irods/stored-2.1/datu/test/triitaoj/test_data.txt
iRODS + rebalance = best
[root@resource2-test ~]# 
```

```
[irods@icat-test ~]$ date; time iadmin modresc random-host-tape-repl rebalance; date
Fri Apr 22 11:16:06 EEST 2016
ERROR: rcGeneralAdmin failed with error -1 Unknown iRODS error Operation not permitted

real	0m1.797s
user	0m0.011s
sys	0m0.003s
Fri Apr 22 11:16:08 EEST 2016
[irods@icat-test ~]$ 
```

Note the error message given by the rebalance command.

```
Apr 22 11:16:08 pid:11292 NOTICE: procChksumForClose: chksum mismatch for for /testzone/datu/test/triitaoj/test_data.txt src [sha2:JDJjWoLtT3e/CWMU/4kaAnm+CcZvfkdWj1DB+jfouKg=] new [sha2:jwTmMsKbV8kn4Q9f91oNdHXN7q9YAm8frd9Pd8q23Vc=]
Apr 22 11:16:08 pid:11292 NOTICE: rsDataObjRepl - Failed to replicate data object.
Apr 22 11:16:08 pid:11292 ERROR: [-]    iRODS/server/api/src/rsGeneralAdmin.cpp:607:_rsGeneralAdmin :  status [USER_CHKSUM_MISMATCH]  errno [] -- message [failed to rebalance resource]
        [-]     librepl.cpp:1668:replRebalance :  status [USER_CHKSUM_MISMATCH]  errno [] -- message []
                [-]     irods_repl_rebalance.cpp:559:proc_results_for_rebalance :  status [USER_CHKSUM_MISMATCH]  errno [] -- message []
                        [-]     irods_repl_rebalance.cpp:59:repl_for_rebalance :  status [USER_CHKSUM_MISMATCH]  errno [] -- message [Failed to replicate the data object [/testzone/datu/test/triitaoj/test_data.txt]]

Apr 22 11:16:08 pid:11292 NOTICE: rsGeneralAdmin: rcGeneralAdmin error -1
Apr 22 11:16:08 pid:11292 NOTICE: readAndProcClientMsg: received disconnect msg from client
Apr 22 11:16:08 pid:11292 NOTICE: Agent exiting with status = 0
Apr 22 11:16:08 pid:13992 NOTICE: Agent process 11292 exited with status 0
Apr 22 11:16:08 pid:13992 NOTICE: Agent process 11296 exited with status 0
```

We get a checksum error, which stops rebalance.

```
[triitaoj@localhost ~]$ ils -LA test_data.txt
  triitaoj          0 random-host-tape-repl;random-host-group;random-disk-group-host2;stored-2.1           25 2016-04-22.11:14 & test_data.txt
    sha2:JDJjWoLtT3e/CWMU/4kaAnm+CcZvfkdWj1DB+jfouKg=    ascii text    /irods/stored-2.1/datu/test/triitaoj/test_data.txt
        ACL - rods#testzone:own   datu#testzone:own   triitaoj#testzone:own   rodsadmin#testzone:own   datu.test#testzone:own   
```

### Subtracting test:

```
[triitaoj@localhost ~]$ iput test_data.txt
[triitaoj@localhost ~]$ ils -LA test_data.txt
  triitaoj          0 random-host-tape-repl;random-host-group;random-disk-group-host2;stored-2.2           25 2016-04-22.11:27 & test_data.txt
    sha2:JDJjWoLtT3e/CWMU/4kaAnm+CcZvfkdWj1DB+jfouKg=    ascii text    /irods/stored-2.2/datu/test/triitaoj/test_data.txt
        ACL - rods#testzone:own   datu#testzone:own   triitaoj#testzone:own   rodsadmin#testzone:own   datu.test#testzone:own   
  triitaoj          1 random-host-tape-repl;weightResc;random-tape-group;stored-3.2           25 2016-04-22.11:27 & test_data.txt
    sha2:JDJjWoLtT3e/CWMU/4kaAnm+CcZvfkdWj1DB+jfouKg=    ascii text    /irods/stored-3.2/datu/test/triitaoj/test_data.txt
        ACL - rods#testzone:own   datu#testzone:own   triitaoj#testzone:own   rodsadmin#testzone:own   datu.test#testzone:own   
[triitaoj@localhost ~]$ 
```

```
[irods@icat-test ~]$ itrim -M -n 1 -N 1 /testzone/datu/test/triitaoj/test_data.txt
```

```
[triitaoj@localhost ~]$ ils -LA test_data.txt
  triitaoj          0 random-host-tape-repl;random-host-group;random-disk-group-host2;stored-2.2           25 2016-04-22.11:27 & test_data.txt
    sha2:JDJjWoLtT3e/CWMU/4kaAnm+CcZvfkdWj1DB+jfouKg=    ascii text    /irods/stored-2.2/datu/test/triitaoj/test_data.txt
        ACL - rods#testzone:own   datu#testzone:own   triitaoj#testzone:own   rodsadmin#testzone:own   datu.test#testzone:own   
[triitaoj@localhost ~]$ 
```

Remove some characters

```
[root@resource2-test ~]# vim /irods/stored-2.2/datu/test/triitaoj/test_data.txt
[root@resource2-test ~]# cat /irods/stored-2.2/datu/test/triitaoj/test_data.txt
iRODS rebalance test
[root@resource2-test ~]# 
```

```
[irods@icat-test ~]$ date; time iadmin modresc random-host-tape-repl rebalance; date
Fri Apr 22 11:29:29 EEST 2016
ERROR: rcGeneralAdmin failed with error -1 Unknown iRODS error Operation not permitted

real	0m1.972s
user	0m0.008s
sys	0m0.006s
Fri Apr 22 11:29:31 EEST 2016
[irods@icat-test ~]$ 
```

```
...
Apr 22 11:29:30 pid:12487 NOTICE: remoteFilePut: rcFilePut failed for /irods/stored-3.1/datu/test/triitaoj/test_data.txt
...
Apr 22 11:29:31 pid:12487 NOTICE: _rsDataObjClose: size in vault 21 != target size 25
Apr 22 11:29:31 pid:12487 NOTICE: rsDataObjRepl - Failed to replicate data object.
Apr 22 11:29:31 pid:12487 ERROR: [-]    iRODS/server/api/src/rsGeneralAdmin.cpp:607:_rsGeneralAdmin :  status [SYS_COPY_LEN_ERR]  errno [] -- message [failed to rebalance resource]
        [-]     librepl.cpp:1668:replRebalance :  status [SYS_COPY_LEN_ERR]  errno [] -- message []
                [-]     irods_repl_rebalance.cpp:559:proc_results_for_rebalance :  status [SYS_COPY_LEN_ERR]  errno [] -- message []
                        [-]     irods_repl_rebalance.cpp:59:repl_for_rebalance :  status [SYS_COPY_LEN_ERR]  errno [] -- message [Failed to replicate the data object [/testzone/datu/test/triitaoj/test_data.txt]]

Apr 22 11:29:31 pid:12487 NOTICE: rsGeneralAdmin: rcGeneralAdmin error -1
Apr 22 11:29:31 pid:12487 NOTICE: readAndProcClientMsg: received disconnect msg from client
Apr 22 11:29:31 pid:12487 NOTICE: Agent exiting with status = 0
Apr 22 11:29:31 pid:13992 NOTICE: Agent process 12487 exited with status 0
Apr 22 11:29:31 pid:13992 NOTICE: Agent process 12493 exited with status 0
```

We get a size related error (the SYS_COPY_LEN_ERR you were asking for).

```
[triitaoj@localhost ~]$ ils -LA test_data.txt
  triitaoj          0 random-host-tape-repl;random-host-group;random-disk-group-host2;stored-2.2           25 2016-04-22.11:27 & test_data.txt
    sha2:JDJjWoLtT3e/CWMU/4kaAnm+CcZvfkdWj1DB+jfouKg=    ascii text    /irods/stored-2.2/datu/test/triitaoj/test_data.txt
        ACL - rods#testzone:own   datu#testzone:own   triitaoj#testzone:own   rodsadmin#testzone:own   datu.test#testzone:own   
[triitaoj@localhost ~]$ 
```

Those are some examples I can think of the top of my head. Let me know if you need more information.

-- Taneli Riitaoja / CSC - IT Center for Science Ltd.

**Comment by jasoncoposky** [comment]
iRODS only knows the size of the replica in the catalog, not at rest in storage.  If you append data to the file on disk then do an iget you will only get the number of bytes that iRODS understands as the size of the file. If for some reason the file is larger that will not result in an error as iRODS is still able to read the appropriate number of bytes.  If for some reason the file at rest is smaller then this results in a read error as you have reproduced and a SYS_COPY_LEN_ERR results.

What we can do for the moment is log failed replications, respond with those data objects to the client via the error stack and continue the rebalance rather than making this a hard stop.

I would consider this a viable candidate for a 4.1.9 release.  Is this issue currently a blocker for you in production?

**Comment by trel** [comment]
We'll close this when solution item 2 is implemented.   The other feature requests should have their own issues created.

**Comment by triitaojcsc** [comment]
> iRODS only knows the size of the replica in the catalog, not at rest in storage.

Yes, that makes sense.

> Is this issue currently a blocker for you in production?

Yes, very much so.

Thanks for the response.

-- Taneli Riitaoja / CSC - IT Center for Science Ltd.

**Comment by trel** [comment]
reopening for cherry-pick to XBB-2
