### ISSUE TITLE
iRODS - Database [testdb] on [localhost] cannot be found

### ISSUE THREAD

**Issue by ElMerendero** [irods/irods#3149]
Hi everyone,
I have a problem with irods on my Ubuntu LTS 14.04. I have installed PostgreSQL 9.4 and I have created a database called testdb owned by testpg. If I check the status of the database I get:

     $ /etc/init.d/postgresql status
     9.4/main (port 5432): online

Then I have installed irods and now I'm trying to configure it with the command:

    sudo /var/lib/irods/packaging/setup_irods.sh

and this is my configuration:

    -------------------------------------------
    Database Type:     postgres
    Hostname or IP:    localhost
    Database Port:     5432
    Database Name:     testdb
    Database User:     testpg
    Database Password: Not Shown
    -------------------------------------------

But when I try to run it I get:

     Stopping iRODS server...

     -----------------------------
     Running irods_setup.pl...

     Step 1 of 4:  Configuring database user...
         Updating user's .pgpass...
            Skipped.  File already uptodate.

     Step 2 of 4:  Creating database and tables...
         Checking whether iCAT database exists...

     Install problem:
     Database [testdb] on [localhost] cannot be found.
                                       Lista dei database
      Nome        | Proprietario | Codifica | Ordinamento |    Ctype    | Privilegi di accesso
    --------------+--------------+----------+-------------+-------------+-----------------------
     postgres     | postgres     | UTF8     | it_IT.UTF-8 | it_IT.UTF-8 | 
     template0    | postgres     | UTF8     | it_IT.UTF-8 | it_IT.UTF-8 | =c/postgres + postgres=CTc/postgres
     template1    | postgres     | UTF8     | it_IT.UTF-8 | it_IT.UTF-8 | =c/postgres + postgres=CTc/postgres
     testdb       | testpg       | UTF8     | it_IT.UTF-8 | it_IT.UTF-8 | 
    (4 rows)

Can you help me?

**Comment by trel** [comment]
Is there any more information in `/var/lib/irods/iRODS/installLogs/irods_setup.log`?

**Comment by ElMerendero** [comment]
This is what I found:

```
iRODS setup
------------------------------------------------------------------------
Tue Apr 26 10:42:11 2016

Script:
    Script:  ./scripts/perl/irods_setup.pl
    CWD:  /var/lib/irods/iRODS

Perl:
    Perl path:  /usr/bin/perl
    Perl version:  5.018002

System:
    OS:  Linux
    User:  irods
    User ID:  999
    Host name:  carlo-desktop
    Host addresses:

Environment:
    SHLVL = 2
    LANG = it_IT.UTF-8
    COLORTERM = gnome-terminal
    NODE_PATH = /usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript
    OLDPWD = /var/lib/irods
    DISPLAY = :0
    PWD = /var/lib/irods/iRODS
    SHELL = /bin/bash
    LOGNAME = irods
    HOME = /var/lib/irods
    JAVA_HOME = /usr/lib/jvm/java-8-oracle
    MAIL = /var/mail/irods
    XDG_VTNR = 7
    XAUTHORITY = /home/carlo/.Xauthority
    XDG_SESSION_ID = c1
    PATH = /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
    _ = /usr/bin/perl
    USER = irods
    QT_QPA_PLATFORMTHEME = appmenu-qt5
    XDG_SEAT = seat0
    TERM = xterm

Script versions:
    utils_print.pl = Apr 2015
    utils_file.pl = September 2011
    utils_config.pl = Feb 2015
    utils_prompt.pl = March 2010
    utils_platform.pl = September 2011
    utils_paths.pl = January 2015
    irods_setup.pl = Feb 2015

Configuring database user...
------------------------------------------------------------------------
Tue Apr 26 10:42:11 2016

Updating user's .pgpass...
    Skipped.  File already uptodate.

Creating database and tables...
------------------------------------------------------------------------
Tue Apr 26 10:42:11 2016


Checking whether iCAT database exists...
    Connecting with: /usr/bin/psql -U testpg -p 5432 -l testdb

Install problem:
    Database [testdb] on [localhost] cannot be found.
                                       Lista dei database
   Nome    | Proprietario | Codifica | Ordinamento |    Ctype    | Privilegi di accesso
-----------+--------------+----------+-------------+-------------+-----------------------
 postgres  | postgres     | UTF8     | it_IT.UTF-8 | it_IT.UTF-8 |
 template0 | postgres     | UTF8     | it_IT.UTF-8 | it_IT.UTF-8 | =c/postgres          +
           |              |          |             |             | postgres=CTc/postgres
 template1 | postgres     | UTF8     | it_IT.UTF-8 | it_IT.UTF-8 | =c/postgres          +
           |              |          |             |             | postgres=CTc/postgres
 testdb    | testpg       | UTF8     | it_IT.UTF-8 | it_IT.UTF-8 |
(4 righe)



Abort.
```

**Comment by trel** [comment]
Looks pretty normal....

Does the connection command work manually?

`/usr/bin/psql -U testpg -p 5432 -l testdb`

**Comment by ElMerendero** [comment]
Yes, with this command I get the list of the databases

**Comment by trel** [comment]
Well, unfortunately, the answer is that the perl script is matching on 'List of databases'... which doesn't exist in your output...

https://github.com/irods/irods/blob/4-1-stable/iRODS/scripts/perl/irods_setup.pl#L1837

Fortunately, if you update the `irods_setup.pl` file on your deployment to check for 'Lista dei database', the setup should complete.

This has already been refactored for the upcoming 4.2+ (no more perl).

**Comment by ElMerendero** [comment]
Ok, this problem seems to be solved (if I understand, the main problem is that my ubuntu is not in english). However now I get another error:

```
Stopping iRODS server...

-----------------------------
Running irods_setup.pl...

Step 1 of 4:  Configuring database user...
    Updating user's .pgpass...
        Skipped.  File already uptodate.

Step 2 of 4:  Creating database and tables...
    Checking whether iCAT database exists...
        [testdb] on [localhost] found.
    Updating user's .odbc.ini...
    Creating iCAT tables...
        Skipped.  Tables already created.
    Testing database communications...

Step 3 of 4:  Configuring iRODS server...
    Updating /etc/irods/server_config.json...
    Updating /etc/irods/database_config.json...

Step 4 of 4:  Configuring iRODS user and starting server...
    Updating iRODS user's ~/.irods/irods_environment.json...
    Starting iRODS server...
Could not start iRODS server.
    Starting iRODS server...
Traceback (most recent call last):
  File "/var/lib/irods/iRODS/scripts/python/get_db_schema_version.py", line 77, in <module>
    current_schema_version = get_current_schema_version(cfg)
  File "/var/lib/irods/iRODS/scripts/python/get_db_schema_version.py", line 61, in get_current_schema_version
    'get_current_schema_version: failed to find result line for schema_version\n\n{}'.format(format_cmd_result(result)))
RuntimeError: get_current_schema_version: failed to find result line for schema_version


return code: [0]
stdout:

stderr:
ERRORE:  la relazione "r_grid_configuration" non esiste
RIGA 1: ...option_value                                 from R_GRID_CON...
                                                             ^

Confirming catalog_schema_version... Success
Validating [/var/lib/irods/.irods/irods_environment.json]... Success
Validating [/etc/irods/server_config.json]... Success
Validating [/etc/irods/hosts_config.json]... Success
Validating [/etc/irods/host_access_control_config.json]... Success
Validating [/etc/irods/database_config.json]... Success
iRODS server failed to start.


Install problem:
    Cannot start iRODS server.
Found 0 processes:
        There are no iRODS servers running.

Abort.
```
Is this related with the previous one?

**Comment by trel** [comment]
I think this is due to a partial install (when you hit the language difference error).

The detection for whether the tables were all installed was very basic, so if you drop and recreate your database (with no tables), and re-run setup, I think it should complete successfully.

something like this for postgres (and table named 'testdb'):

`sudo su - postgres -c "dropdb testdb; createdb testdb"`

**Comment by trel** [comment]
@ElMerendero did this work for you?

**Comment by trel** [comment]
no action items remaining - please open a new issue if the problem remains.  thanks.
