### ISSUE TITLE
fix documentation for server_config.json

### ISSUE THREAD

**Issue by carsten-jahn** [irods/irods#3157]
The page https://docs.irods.org/master/manual/configuration/#etcirodsserver_configjson says that elements in `advanced_settings` are optional, but removing them leads to `failed with error -1800000 KEY_NOT_FOUND`.

BTW, why not package the contents of https://schemas.irods.org/configuration/ directly in the iRODS RPMs? I don't see a benefit for having internet access here, and the local installation is extra complexity.

**Comment by trel** [comment]
The JSON was external to begin with as we wanted to make sure we understood the mechanisms before baking them in directly.  The schemas will be included in 4.2.0.

The documentation, conversely, is being separated - to allow us to update it after a particular release.

**Comment by trel** [comment]
The advanced settings are now marked as required in the new https://github.com/irods/irods_docs repository.
