### ISSUE TITLE
irodsEnvFile environment variable not working in 4.1.8

### ISSUE THREAD

**Issue by jerry57** [irods/irods#3158]
With ver 3.3.1, we could set irodsEnvFile to point to an alternative `.irodsEnv` file and everything worked as expected.  With iRODS 4.1.x, this is not working.  It prompts for `irodsHost`

If i use the irodsEnv file as "irods_environment.json", it works normally.

**Comment by kellerb** [comment]
The environment variable for changing the location of the environment file is now `IRODS_ENVIRONMENT_FILE`.

Does your second paragraph mean that you have renamed the non-json environment file to `irods_environment.json`?

**Comment by jerry57** [comment]
No the irodsEnv file I was referring to for 4.1 would be a valid "irods_environment.json" file.  I am testing both 3.3.1 and 4.1.8 right now so spend a lot of time bouncing between the two, sorry.

I will try using the new "IRODS_ENVIRONMENT_FILE" variable and see what happens, thx

**Comment by jerry57** [comment]
The new IRODS_ENVIRONMENT_FILE variable seems to be working as expected.  Not sure why the variable name was changed, would have been nice to maintain backwards compatibility overall I think.  If you want to close based on new var name, go for it.
