### ISSUE TITLE
Shoud iRODS stop making PID file?

### ISSUE THREAD

**Issue by kellerb** [irods/irods#3162]
https://github.com/irods/irods/blob/9e376c3017da08d64e178694086074a6c51d4c09/server/core/src/rodsServer.cpp#L921-L970

**Comment by jmarshall** [comment]
Why?

**Comment by kellerb** [comment]
I don't think it is being used anymore. Do you have a use for it?

**Comment by jmarshall** [comment]
Not being used anymore by whom: iRODS itself, or others?

I would use it in the normal way for a pidfile (even though its contents are not quite normal for a pidfile) as one of the tools for monitoring server processes, if I were monitoring an iRODS server.  But I am not a sysadmin, and perhaps actual sysadmins gravitate towards `pgrep` et al these days.

**Comment by Pete-C** [comment]
To stop, and restart of services.  Monitor present "upness". To ensure a previous instance of the daemon exited cleanly as part of a shutdown or recovery. These would be my main reasons with a sys-admin hat on.  

    On Tuesday, 10 May 2016, 10:20, John Marshall <notifications@github.com> wrote:
 

 Not being used anymore by whom: iRODS itself, or others?I would use it in the normal way for a pidfile (even though its contents are not quite normal for a pidfile) as one of the tools for monitoring server processes, if I were monitoring an iRODS server. But I am not a sysadmin, and perhaps actual sysadmins gravitate towards pgrep et al these days.—

**Comment by kellerb** [comment]
If I'm reading between the lines correctly, this sounds like a couple votes for leaving the PID file.

**Comment by Pete-C** [comment]
Please, unless there is a reason to get rid of it
 

    On Tuesday, 10 May 2016, 16:30, kellerb <notifications@github.com> wrote:
 

 If I'm reading between the lines correctly, this sounds like a couple votes for leaving the PID file.—
