### ISSUE TITLE
iinit initialize irods_environment.json with PAM

### ISSUE THREAD

**Issue by tsmeele** [irods/irods#3164]
- [x] main
- [x] 4-3-stable
---
Feature request: If no `irods_environment.json` file exist then `iinit` will create one. In PAM oriented environments however the user still would need to modify the json file to update the authentication scheme.   Is it possible to add a switch to iinit that will create a json file with PAM authentication?

**Comment by alanking** [comment]
I think I may have accidentally duplicated this with #6398...

Work has started here: https://github.com/irods/irods_client_icommands/pull/338
