### ISSUE TITLE
Making Rules

### ISSUE THREAD

**Issue by katbeaulieu** [irods/irods#3165]
Hi there, not sure if this is the appropriate place to post this but I am looking for a guide to making my own rules in iRods as well as editing current ones such as acPostProcForPut but everything seems to be outdated and doesn't apply to the current system. Does anyone know where I could look or could someone provide some help as to how I should go about it? Right now all I am trying to do is get acPostProcForPut to write hello world to the console when I move a file over to irods. Any help would be appreciated.

**Comment by trel** [comment]
Hi, you can use `writeLine()` in the `acPostProcForPut()` and demonstrate logging to the server.

You can play with the existing example comments in core.re:

  https://github.com/irods/irods/blob/4-1-stable/packaging/core.re.template#L251

And of course, read more about the rule language itself here:

  https://docs.irods.org/4.1.8/manual/rule_language/

What have you found that was outdated?  We're actively purging things that are no longer true, as we find them.

**Comment by katbeaulieu** [comment]
Which core.re file? I have /etc/irods/core.re and /var/lib/irods/packaging/core.re.template and my acPostProcForPut in both those files looks like this:
acPostProcForPut{
writeLine("stdout", "Hello world");
} 
Still nothing occurs when I run iput.
As for what I have been reading, I have been going through books (2 of them) on irods and looking through the documentation.

**Comment by katbeaulieu** [comment]
The file transfers to the irods file system but nothing gets printed to the console

**Comment by jasoncoposky** [comment]
Try "serverLog" instead of "stdout".  Also you only need to modify /etc/irods/core.re as that is the one that is used by the server.

**Comment by trel** [comment]
The logging will go to the rodsLog in `/var/lib/irods/iRODS/server/log/rodsLog*`

**Comment by katbeaulieu** [comment]
Thank you for the help, it seems something did print to the server log, also thank you for pointing me in the direction of the logs. Any idea why it won't print to the console though?

**Comment by trel** [comment]
The server is the one running the rule engine in this case (using a policy enforcement point to fire on an `iput`) - not the client.

If you run a rule through `irule -F`, then you can get information back to the console via `stdout` (and `ruleExecOut`)
