### ISSUE TITLE
iRODS S3 interface does not leverage multi-part upload.  Times our during rename of large 18 GB file.

### ISSUE THREAD

**Issue by sgworth** [irods/irods#3168]
An EMC customer is using the iRODS S3 resource driver to talk with an EMC ECS (Elastic Cloud Storage) device.   During a large file transfer/rename to the ECS frame the resource driver is timing out after 15 seconds trying to rename a large 18GB file which has been written to the ECS.   At first we thought this was an ECS problem.  However, after more research, we realized that the S3 driver as-is will never support files >5GB on AWS S3 because it doesn’t use multipart upload and multipart copy (AWS limits single PUTs to 5GB).  The only reason it worked at all for such a large file was that ECS does not enforce the 5GB maximum blob size.

So, there seems to be a real deficiency in the S3 resource driver.  At a minimum, it needs to:

1.	Support Multipart Uploads during `iput`
2.	Use multipart copy for objects >5GB during rename

Above and beyond that, it is also single-threaded so there’s likely lots of room for performance improvements too.  We found an old slide deck that seems to imply that the original authors were aware of these limitations, but thus far nothing has been done to remediate them.  Is this correct?

To get our customer back operational we need assistance with either an iRODS workaround for this or the implementation of Multipart uploads.   Please advise.

**Comment by adetorcy** [comment]
We have updates in flight that will address both issues.
I am working on irods/irods_resource_plugin_s3#1830 and we will be merging irods/irods_resource_plugin_s3#1827 once it has been run through CI.

**Comment by trel** [comment]
Closing this here.  The libs3 included in the 4.1.9 externals will support multipart and the other two issues in the s3 plugin should handle the work to be done.
