### ISSUE TITLE
Creation of usernames containing the string "_ts"

### ISSUE THREAD

**Issue by ccacciari** [irods/irods#3170]
- [x] master
- [x] 4-2-stable
----

Hi,

when I create a new user in iRODS:
`iadmin mkuser myusername rodsuser`
if _myusername_ contains the string "_ts", and I issue:
`iadmin lu myusername`
I got this:

```
user_id: 41396629
user_name 1970-01-01.01:00:00
user_type_name: rodsuser
zone_name: MyZone
user_info: 
r_comment:
create_ts 2016-05-16.18:07:55
modify_ts 2016-05-17.10:13:04
```

The field _user_name_ is clearly wrong.
I'm using iRODS 4.1.7 on CentOS 7.2 with character encoding "en_US.UTF-8".

**Comment by adetorcy** [comment]
Strings with "_ts" are valid user names but are not displayed properly on the command line by `iadmin lu`. [This line](https://github.com/irods/irods_client_icommands/blob/master/src/iadmin.cpp#L57) is the likely culprit.
