### ISSUE TITLE
Further testing for UnixFileSystem high_water_mark feature

### ISSUE THREAD

**Issue by jasoncoposky** [irods/irods#3173]
per observed behavior at a member site, the high_water_mark requires further testing and possible fixes.

**Comment by trel** [comment]
found a bug in the calculation of currently used space on disk.

we'll bracket the tests - before, during, and after exceeding the high_water_mark.

**Comment by trel** [comment]
need cherry pick into XBB-2, then close.

**Comment by trel** [comment]
oops, found a bug in the test.  reopening.
