### ISSUE TITLE
Miscellaneous problems in latest build (a1db0f5)

### ISSUE THREAD

**Issue by triitaojcsc** [irods/irods#3177]
Hi,

I tried the latest (a1db0f5defa9a34f72be3be1e4f8ae24965f9187) build (though it claims to be 4.2.0 instead of 4.1.9) in our testing environment last week and ran into a few problems, which I've detailed below.

## Environment

```
[root@localhost ]# cat /etc/redhat-release 
CentOS release 6.7 (Final)
```

```
[root@localhost ]# rpm -qa | grep irods
irods-database-plugin-postgres93-2.0_4.2.0_a1db0f5def-1.x86_64
irods-icat-4.2.0-1.x86_64
```

## Configuration problems

The 'server_config.json' configuration file has some new required parameters. I tried my best to understand what they're about, but as there isn't any documentation available that I could find (apart from the server_config schema), I had trouble understanding what values I should assign to them.

```
[root@localhost ]# egrep -A 6 "rule_engines|catalog_service_role" /etc/irods/server_config.json 
    "catalog_service_role": "provider",
    "rule_engines": [
	{
	        "instance_name": "irodsReServer",
	        "plugin_name": "irodsReServer",
	        "plugin_specific_configuration": {}
	}
    ]
```

The 'catalog_service_role' has the possible values of {'provider', 'consumer', 'proxy'}. The 'provider' value seems to work. I'm assuming that it refers to the ICAT server's role? What would 'consumer' and 'proxy' do?

The 'rule_engines' had me scratching my head. Eventually I came up with the above configuration, which seems to at least allow the irods service to start. These were just guesses: what should I really use the 'rule_engines' attribute for?

## Graceful shutdown problem

When shutting down the irods service on the ICAT host, graceful shutdown fails:

```
[root@localhost ]# service irods stop
Stopping iRODS server...
Error encountered in graceful shutdown.
iRODS server processes remain after "irods-grid shutdown".
irodsServer :
  Process 20508
Killing forcefully...
Killing /var/lib/irods/iRODS/server/bin/irodsServer, pid 20508
iRODS child processes remain after "irods-grid shutdown".
irodsReServer :
  Process 20509
Killing forcefully...
Killing /var/lib/irods/iRODS/server/bin/irodsReServer, pid 20509
Success
```

And the following error message appears in rodsLog:

```
May 20 14:58:56 pid:20508 ERROR: [-]    iRODS/server/core/src/irods_server_control_plane.cpp:1284:process_operation :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message []
        [-]     iRODS/server/core/src/irods_server_control_plane.cpp:993:validate_host_list :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message [invalid server hostname [localhost]]
```

Am I still missing some configuration? A list of (valid) hosts? Is it the 'rule_engines' configuration that's invalid?

## Bugs in the scripts

The script "database_connect.py" has a few typos:

```
[root@localhost ]# egrep -n "odbc\[section\]" /var/lib/irods/scripts/irods/database_connect.py
32:            if key in odbc[section]:
34:            odbc[section][key] = value
[root@localhost ]# 
```

(Should be 'odbc_dict' instead of 'odbc')

The script "controller.py" has a few typos:

```
[root@localhost ]# grep -n "get_root_directory" /var/lib/irods/scripts/irods/controller.py
264:        lib.get_root_directory(),
271:        lib.get_root_directory(),
[root@localhost ]#
```

(Should be paths.get_root_directory() instead of lib.get_root_directory(), and also need to import paths)

That's all for now.

-- Taneli Riitaoja / CSC - IT Center for Science Ltd.

**Comment by trel** [comment]
The XBB-2 branch will be merged into master ASAP.  This will become 4.2, when it's ready.

If you're looking for 4.1.9, you should be building the 4-1-stable branch at this time.

The producer/consumer/proxy is the new runtime configuration for whether a server is holding a connection to the iCAT database.

The rule_engines entries are in support of the unreleased (4.2+) pluggable rule engine framework.

**Comment by trel** [comment]
Closing.  If this is still an issue for you, please reopen after testing the recently updated master branch.
