### ISSUE TITLE
provide packages for ubuntu16

### ISSUE THREAD

**Issue by bpow** [irods/irods#3190]
Unable to compile on Ubuntu 16.04 (the current LTS release of Ubuntu). The Makefile in `external` tries to download ftp://ftp.renci.org/pub/irods/build/irods_external_4.2.0_Ubuntu16.tar.gz but no such file exists.

Also, it would be nice if there were some sort of error message produced when curl (being called by the makefile) does not find the tar.gz bundle of external libraries. Right now it just goes on its merry way, and the error that shows up is something about avrocpp not being present.

**Comment by adetorcy** [comment]
We haven't made externals for Ubuntu 16 yet. Please run `make generate` in irods/external

**Comment by trel** [comment]
iRODS is now a CMake project - we need to build and provide externals for Ubuntu16, and then get them into CI.   This won't make the 4.2.0 deadline.

**Comment by trel** [comment]
will cherry-pick back to 4-2-stable
