### ISSUE TITLE
package upgrade from 4.1.8 to 4.1-stable doesn't check service_account.config for service accounts

### ISSUE THREAD

**Issue by kript** [irods/irods#3199]
When upgrading from 4.1.8 to 4.1-stable on an Ubuntu12 system I ran into this error;

```
sudo dpkg -i irods-icat-4.1.9-64bit.deb irods-database-plugin-oracle-1.9.deb 
(Reading database ... 223574 files and directories currently installed.)
Preparing to replace irods-icat 4.1.8 (using irods-icat-4.1.9-64bit.deb) ...
utils_config.pl:load_json_file: Can't open /etc/irods/server_config.json: Permission denied
dpkg: error processing irods-icat-4.1.9-64bit.deb (--install):
 subprocess new pre-installation script returned error exit status 13
 System start/stop links for /etc/init.d/irods already exist.

=======================================================================

Welcome to iRODS.

This installation of an iCAT server is currently incomplete and
needs a database plugin to be installed and configured before
it can be started and used.

Please consult the documentation for further instructions.

=======================================================================


Preparing to replace irods-database-plugin-oracle 1.9 (using irods-database-plugin-oracle-1.9.deb) ...
Unpacking replacement irods-database-plugin-oracle ...
Setting up irods-database-plugin-oracle (1.9) ...
Errors were encountered while processing:
 irods-icat-4.1.9-64bit.deb
```
This was a bit odd as it had worked on other systems. The permissions were 0700 for the user defined in /etc/irods/service_account.config.

However! The preconfig script in /var/lib/dpkg/info/irods-icat.preinst contains;

```
if [ "$PACKAGEUPGRADE" = "true" ] ; then
  # detect current service account information
  MYACCTNAME=`ls -l /etc/irods/core.re | awk '{print $3}'`
  MYGROUPNAME=`ls -l /etc/irods/core.re | awk '{print $4}'`
```

which for reasons I'm ashamed to admit in a public forum, show a different user than the one set in service_account.config.

While this is a silly situation for us to find ourselves in, it does beg the question why have a config file that determines id/guid and not check it if it exists? :-)  

Also, rather than backticks, I'm told you might prefer the safer 
`stat --format "%U" /etc/irods/core.re`

**Comment by trel** [comment]
Ha.  Thanks.

That logic has already been moved in what will be 4.2.  The packaging no longer handles the upgrades itself, everything is handled in the python control scripts.

We're reducing/removing the need for shell logic, too - but thanks for the heads up on the backticks.

I see no immediate action item, but I'll leave this open as a reminder to check for backticks and other upgrade logic.
