### ISSUE TITLE
building iRODS 4 without root and without using or requiring OS packages

### ISSUE THREAD

**Issue by jrandall** [irods/irods#3202]
The iRODS 4.1.8 build process seems to be conflated with the process of packaging iRODS using OS-specific packaging systems (such as apt on Ubuntu/Debian). 

I would like to build and install iRODS as a non-root user into a non-standard prefix, and using prerequisites that are also installed by non-root users into (other) non-standard prefixes.

We use the Environment Modules system to maintain different versions of tools, and so we routinely install software into a custom prefix named by the version. This is not an unusual requirement and we have had few issues in installing hundreds of software packages in this manner. Most packages use the autoconf/automake build system and trivially support installation in an alternative prefix using `./configure --prefix /path/to/prefix`. Others require passing an argument to make such as `make PREFIX=/path/to/prefix`. Some use more exotic build systems such as `cmake` which can also be build into a prefix by changing settings in the build config. A handful didn't contemplate this requirement and do require modification of a few lines of Makefile in order to make them work. 

With iRODS, I'm not even sure where to start making this work, as system paths are hardcoded all over the cobbled together mess of shell scripts, Makefiles, and Makefile fragments that comprise the "build system". It seems that the only supported way of installing prerequisites is to install them using the operating systems package manager, and there don't even seem to be any hooks in the Makefiles that can be overridden to specific alternate locations. 

It would be great if it was possible to configure, build, and install iRODS 4 from source without involving packaging systems of any kind. This would include:
- a `make install` target that installs the built software into a configurable prefix (by default `/usr`)
- the ability to specify the locations of prerequisite libraries (even if it was just by allowing one to set variables such as `xx_CFLAGS` and `xx_LIBS` for a prerequisite called `xx`)
- the elimination of hardcoded system paths anywhere in the build process or runtime (i.e. no assuming config will always be in `/etc/irods`, libraries will be in `/usr/lib`, or headers in `/usr/include`)

I appreciate many people who install iRODS will have root on the system (or at least within a VM or Container they may have access to). However, sometimes VMs and/or containers are not an option, and I'm sure that I am not the only one who has a use-case for installation of iRODS (especially clients and client plugins) on systems for which root is not available or on which by policy software is not installed in system locations (this is certainly typical of HPC facilities that use the Environment Modules system to manage software environments).

**Comment by trel** [comment]
Thank you for the thorough justification.

We have spent the better part of the last year retooling the internals, separating packages, and converting the entire project to CMake [https://github.com/irods/irods/issues/2239].  As we grow more comfortable with CMake and the assumptions that may no longer need to be made about paths, we can improve the configurability of the system.  Of course, input will continue to be welcome.

The XBB-2 branch currently builds with CMake.  This will be merged with master, and released as 4.2 ASAP.  We're using github milestones to prioritize the remaining work.

We will not be changing the 4-1-stable branch to use this new build system.

**Comment by jrandall** [comment]
I see - I had been preparing a PR against 4.1.8 that would implement a minimal set of changes to the Makefiles and `packaging/build.sh` to allow one to compile using the Makefiles without packaging, but it sounds like this will be a complete waste of time if the XBB-2 branch has abandoned make in favor of CMake. I'll take a look at that branch and see if I can get it to build into a specified prefix.

**Comment by kellerb** [comment]
Let me preface this by saying that everything below is open to change. We are aware that iRODS has been very particular about how it is built and installed. One of the goals of the "build system revamp" is to make iRODS an upstanding citizen in this regard. I personally do not have a lot of knowledge about how software is built/packaged/distributed/run in HPC environments, so I greatly appreciate any advice of that nature.

The current 4.2 plan for supporting custom installation prefixes and/or non-package installs is to allow an iRODS installation's base directory to be chosen at build time to be anywhere in the filesystem. This means that all iRODS files would exist inside some chosen parent directory, call it `INSTALL_BASE`. For a normal package installation, `INSTALL_BASE` is `/`. If `INSTALL_BASE` were `/tmp/irods-install`, then the iRODS installation would have files like `/tmp/irods-install/etc/irods/core.re` and `/tmp/irods-install/var/lib/irods/plugins/network/libtcp_client.so` and `/tmp/irods-install/usr/lib/libirods_server.so.4.2.0`, etc.

XBB-2 implements the `INSTALL_BASE` concept with the CMake variable `CMAKE_INSTALL_PREFIX` and with three custom make targets that handle installing the desired database plugin:
* `non-package-install-postgres`
* `non-package-install-mysql`
* `non-package-install-oracle`

Before building the iRODS server, the external dependencies need to be built/installed. iRODS has two classes of external dependencies: 

1. Dependencies that can be met by packages in the OS's standard package repository (e.g. can be `apt-get install`ed on a clean Ubuntu machine)
2. Dependencies that are not available from the OS's standard package repository (b/c the specific external is not available at all, or iRODS wants a different version)

Through 4.1, iRODS incorporated externals of the second class directly into the iRODS server build process. For 4.2, the code for building these externals has been moved to its [own repository](https://github.com/irods/externals). They can be built and packaged by following the instructions in that repository (the build itself will take at least an hour). Alternatively, for development work or pre-release testing, the externals can be installed from [the iRODS Consortium's core-dev package repository](https://core-dev.irods.org/). Note that the `core-dev` package repositories are used *only for development*, and their contents could be changed at any time. Once a version of iRODS is released that depends upon a specific version of these external packages, a copy of the external packages will be put on [the official iRODS repository](https://packages.irods.org/) (aka the only iRODS Consortium repository that a production iRODS installation should have installed).

An example of building the iRODS server and the postgres database plugin follows (assuming that the externals were built into `/tmp/irods-externals`. Note that if the externals were installed from the `core-dev` repository, then they will all be in `/opt/irods-externals` and they will be detected automatically by all of the following scripts.

Once the externals are built or installed, the `cmake` binaries need to be added to the `PATH`. If installed from the repository:
``` bash
export PATH=/opt/irods-externals/cmake3.5.2-0/bin:$PATH
```
if built locally in `/tmp/irods-externals`:
``` bash
export PATH=/tmp/irods-externals/cmake3.5.2-0/bin:$PATH
```

Now to build and install the iRODS server, postgres database plugin, development and runtime files:

``` bash
IRODS_SOURCE_DIR=/tmp/irods-source
git clone https://github.com/irods/irods $IRODS_SOURCE_DIR
cd $IRODS_SOURCE_DIR
git checkout XBB-2
git submodule update --init --recursive
IRODS_BUILD_DIR=/tmp/irods-build
mkdir $IRODS_BUILD_DIR && cd $IRODS_BUILD_DIR
IRODS_INSTALL_DIR=/tmp/irods-install
cmake $IRODS_SOURCE_DIR -DCMAKE_INSTALL_PREFIX=$IRODS_INSTALL_DIR -DIRODS_EXTERNALS_PACKAGE_ROOT=/tmp/irods-externals
make -j`getconf _NPROCESSORS_ONLN` non-package-install-postgres
```

Once the iRODS server is installed, but before the setup script is run, the icommands need to be built and installed (the icommands have been moved to [their own repository](https://github.com/irods/irods_client_icommands) for 4.2 to, among other reasons, require us to use our own development libraries).

``` bash
ICOMMANDS_SOURCE_DIR=/tmp/icommands-source
git clone https://github.com/irods/irods_client_icommands $ICOMMANDS_SOURCE_DIR
ICOMMANDS_BUILD_DIR=/tmp/icommands-build
mkdir $ICOMMANDS_BUILD_DIR && cd $ICOMMANDS_BUILD_DIR
cmake $ICOMMANDS_SOURCE_DIR -DIRODS_DIR=$IRODS_INSTALL_DIR/usr/lib/irods/cmake -DCMAKE_INSTALL_PREFIX=$IRODS_INSTALL_DIR
make -j`getconf _NPROCESSORS_ONLN` install
```

All of the required files should now be installed into `$IRODS_INSTALL_DIR`.

To set up and run the server, we first need to adjust some environment variables:
``` bash
export LD_LIBRARY_PATH=$IRODS_INSTALL_DIR/usr/lib
export PATH=$IRODS_INSTALL_DIR/usr/bin:$IRODS_INSTALL_DIR/usr/sbin:$PATH
```

The setup script can now be run:
``` bash
cd $IRODS_INSTALL_DIR/var/lib/irods
python scripts/setup_irods.py 
```

Again, please let us know if/when one of these steps goes wrong and if there are things we can change to improve this process.

**Comment by jrandall** [comment]
Thanks so much for the in-depth explanation! I am proceeding to attempt to build using the XBB-2 branch. However, rather than using the irods/externals repository to build the prerequisites (both class 1 and 2), which still requires root, I am building them myself from source and installing them also into our version-prefixed software environment.

My minimal expectation for a system that requires prerequisite packages would be that it documents what the prerequisites are and what version(s) are required. iRODS 4.2 meets that requirement in the form of https://github.com/irods/externals/blob/master/versions.json (and in addition it gives helpful hints as to how it wants them configured and built). I am hopeful this will work - will report back on how I get on. 

One thing that I haven't found is any documentation as to whether a smaller set of those prerequisites would be required if one only requires clients (or client libraries). I assume `epm` is not actually required if not using packaging, but it isn't clear which other components are needed for a client build.

**Comment by trel** [comment]
Closing - this has worked for a few years now.
