### ISSUE TITLE
iput adds ".0" to physical files, after having them unregistered before

### ISSUE THREAD

**Issue by jenspeters** [irods/irods#3206]
Hello,

we've got a strange behaviour while putting files to iRODS 4.1.7, while unregistered them before.
On one installation (in total we've got 5 installations all running fine as expected) a ".0" is being added to the files. 

Even putting them twice, it results in files on pysical storage like "test.txt.0.0".
We think this might be some configuration mistake, but aren't sure. Do you have any ideas, what might be the clue here?

```
iput test.txt /home/rods
irm -rU test.txt
iput test.txt /home/rods -> test.txt.0 
iput test.txt /home/rods -> test.txt.0.0

```

Kind regards,
Jens

**Comment by trel** [comment]
Does the rodsLog say anything interesting when this happens?   I cannot reproduce this locally.

A `.0` is appended when there is conflict within the Vault, sometimes orphan files are moved out of the way.  Why are you only unregistering a file that is in the Vault?  Why not just remove it in the standard way?

**Comment by jenspeters** [comment]
Hi Terrell,

we found it: orphan Directory did have different permissions compared to the rest. Thanks for your help. Kind regards, Jens
