### ISSUE TITLE
iphymv does not copy from the "right" replica

### ISSUE THREAD

**Issue by nono-gdv** [irods/irods#3207]
Hello,

Here is a strange issue I came across with iRODS 4.1.8. First my resource hierarchy:

```
$ ilsresc --tree
PAPY:passthru
└── PAPY_primary:load_balanced
    ├── node-0003
    └── regina
PAPY_secondary:load_balanced
├── margarita
└── node-0006
```

The four "final" resources (regina, margarita and the node-000Xs) are unixfilesystems, each on its own server.

I would like to decommission margarita, so I need to move all of its content to node-0006. Easy, that's what `iphymv` is for.

```
$ ils -l /PAPY/home/rods/LesFetesGalantes_DSM_loop3/data/objects/RENDER_ARCHIVAGE/BOB1_1201/PATRIMOINE/GRD10_BOB1_ETAL_2411/2048x1296/import_backup/004940.dpx
  rods              0 PAPY;PAPY_primary;regina     10620928 2016-06-16.02:02 & 004940.dpx
  rods              1 PAPY_secondary;margarita     10620928 2016-06-22.15:32 & 004940.dpx
$ iphymv -S margarita -R node-0006 -v /PAPY/home/rods/LesFetesGalantes_DSM_loop3/data/objects/RENDER_ARCHIVAGE/BOB1_1201/PATRIMOINE/GRD10_BOB1_ETAL_2411/2048x1296/import_backup/004940.dpx
ERROR: phymvUtil: phymv error for /PAPY/home/rods/LesFetesGalantes_DSM_loop3/data/objects/RENDER_ARCHIVAGE/BOB1_1201/PATRIMOINE/GRD10_BOB1_ETAL_2411/2048x1296/import_backup/004940.dpx, status = -121000 status = -121000 SYS_USER_NO_PERMISSION
Level 0: unable to open /PAPY/home/rods/LesFetesGalantes_DSM_loop3/data/objects/RENDER_ARCHIVAGE/BOB1_1201/PATRIMOINE/GRD10_BOB1_ETAL_2411/2048x1296/import_backup/004940.dpx for unlink
```

Wot? Looking in the server logs on the iCAT (which is also the server my client is connecting to):

```
Jun 28 10:29:55 pid:31188 NOTICE: connectToRhostWithTout: myval error, errno = 113
Jun 28 10:29:58 pid:31188 NOTICE: connectToRhostWithTout: myval error, errno = 113
Jun 28 10:30:01 pid:21442 NOTICE: Agent process 31255 started for puser=rods and cuser=rods from 10.20.101.31
Jun 28 10:30:01 pid:31188 NOTICE: connectToRhostWithTout: myval error, errno = 113
Jun 28 10:30:01 pid:31188 NOTICE: connectToRhost: connect to host regina.storage.papy.eclair-preservation.com on port 1247 failed, status = -305113 status = -305113 USER_SOCK_CONNECT_ERR, No route to host
Jun 28 10:30:01 pid:31188 ERROR: _rcConnect: connectToRhost error, server on regina.storage.papy.eclair-preservation.com:1247 is probably down status = -305113 USER_SOCK_CONNECT_ERR, No route to host
Jun 28 10:30:01 pid:31188 ERROR: [-]    iRODS/server/api/src/rsDataObjPhymv.cpp:296:rsDataObjPhymv :  status [SYS_USER_NO_PERMISSION]  errno [] -- message []
        [-]     iRODS/server/api/src/rsDataObjPhymv.cpp:93:test_source_replica_for_write_permissions :  status [SYS_USER_NO_PERMISSION]  errno [] -- message [unable to open /PAPY/home/rods/LesFetesGalantes_DSM_loop3/data/objects/RENDER_ARCHIVAGE/BOB1_1201/PATRIMOINE/GRD10_BOB1_ETAL_2411/2048x1296/import_backup/004940.dpx for unlink]

Jun 28 10:30:01 pid:31188 NOTICE: readAndProcClientMsg: received disconnect msg from client
Jun 28 10:30:01 pid:31188 NOTICE: Agent exiting with status = 0
```

Tcpdump confirms the iCAT server tries to talk to regina, but never to margarita.

Of course, regina won't answer as it is currently off (the server broke down, so there's no way I'm switching it on). But I don't understand why iphymv tries to read from regina and not from margarita?

**Comment by trel** [comment]
Interesting.  We'll try to replicate this behavior.

**Comment by nono-gdv** [comment]
The broken server is back on line and iphymv now works again. I'm not sure I understand what is going on; the files are definitely copied from margarita, but the iCAT talks to regina too. From poking around a bit with tcpdump and strace, it looks like the iCAT just asks regina about each file; regina then opens the file, does nothing with it that I could see and closes it. I don't know enough about the internals of iRODS to make any sense of it.

**Comment by nono-gdv** [comment]
I'm not sure the culprit is iphymv itself; ichksum exhibits the same kind of behaviour.

I have emptied regina and margarita; now all my data is duplicated on node-0003 and node-0006. However running ichksum forks irodsAgents on regina and margarita (I can see PID files in /var/lib/irods/iRODS/server/log/proc), even though they have no data left.

**Comment by nono-gdv** [comment]
Looks like the bug is on my side. I was calling a script in pep_resource_resolve_hierarchy_post, and I just understood it was getting called for each resource in the hierarchy, and not just for the ones I was actually accessing.

Sorry about the noise.

**Comment by trel** [comment]
Excellent.

What pep did you end up using, rather than `pep_resource_resolve_hierarchy_post`?
