### ISSUE TITLE
Improved documentation for irods-grid command

### ISSUE THREAD

**Issue by kript** [irods/irods#3208]
Can we have the examples from the slides; http://slides.com/irods/monitoring-irods-zones#/ included in the manual please?

Also, there is no man page in the packaging, and the help output from -h would be improved by the addition of pages 8 & 9 from the above presentation.

**Comment by trel** [comment]
Agreed - we'll get some examples into the usage output.

And we'll get the man pages squared up again - those had fallen off the radar in the restructuring.
