### ISSUE TITLE
Request: izonereport to display current rules

### ISSUE THREAD

**Issue by kript** [irods/irods#3209]
Currently the output of izonereport doesn't show which rules are being used by the server; it shows which .re files are included, and then an encoded block.

It would be helpful to have a way to view the rules the server is currently using (rather than what is in config files) so any differences can be audited.

If the rules are not displayed due to security;
1. why? AFAIK only zoneadmins can run the command (and if this isn't true, can the documentation be updated to show which roles can)
2. can a rodsadmin be allowed to show the rules, perhaps with an additional flag (like the -M admin flag to some other icommands)

Thank you!

**Comment by trel** [comment]
The obfuscation is not due to security - it is due to encoding.  There could be all manner of syntax in the rulebase file(s), so we base64 encode it to make sure it plays well within the JSON syntax of the zonereport itself.

You can decode the base64 block by piping into `base64 --decode`.

**Comment by kript** [comment]
> On 30 Jun 2016, at 14:57, Terrell Russell <notifications@github.com> wrote:
> 
> The obfuscation is not due to security - it is due to encoding. There could be all manner of syntax in the rulebase file(s), so we base64 encode it to make sure it plays well within the JSON syntax of the zonereport itself.
> 
> You can decode the base64 block by piping into base64 --decode.
> 
> 

Thanks, that make sense. Can we get this added to the docs and the man page for izonereport please?
