### ISSUE TITLE
remove idbug

### ISSUE THREAD

**Issue by andyjp94** [irods/irods#3211]
This is the first time I have tried to use idbug so I may just be getting the syntax wrong. However I've tried driving it several different ways that I _think_ might work.  
Going off the help message there are no required arguments. So just running `idbug` should work but produces `ERROR: _rcConnect: setRhostInfo error, irodsHost is probably not set correctly status = -302000 USER_RODS_HOST_EMPTY
rcConnectXmsg error...Will try again`

The irods_host is set correctly and all other icommands that I use normally such as ils, iput and iget all work

**Comment by trel** [comment]
`idbug` worked with the XMsgServer, which is not being maintained on the 4.1 branch.  We will be removing `idbug` from the distribution in 4.2.

**Comment by andyjp94** [comment]
In that case could idbug be removed from the 4.1.x documentation please

**Comment by trel** [comment]
It's still distributed in 4.1.x, but deprecated - If you start the `irodsXmsgServer`, `idbug` may still work as expected.
