### ISSUE TITLE
irods config issues

### ISSUE THREAD

**Issue by andyjp94** [irods/irods#3212]
I cannot seem to customise irods rules on 4-1-stable, changing the server_config.json file doesn't seem to have any effect. Nor does including the extra rules file in the core.re.

The relevant section in the server_config.json shows:  
```
    "re_rulebase_set": [
        {
            "filename": "seq-dev"
        },
        {
            "filename": "core"
        }
    ],
```
The seq-dev.re has the following contents:  
```
acSetRescSchemeForCreate {
        if ($objPath like regex '/seq-dev/illumina/library_merge/.*\.(bam|cram)$') {
                msiSetDefaultResc("noReplRoot","null");
        }
        else {
                msiSetDefaultResc("root","null");
        }
}
acPreprocForDataObjOpen{ msiSetDataObjPreferredResc("root"); }

#do we need the more involved one here
acPostProcForPut {msiSysChksumDataObj; }
```
From this I would expect that putting a file with a ".cram" extension into the /seq-dev/illumina/library_merge/ collection should mean that the file will be stored in the noReplRoot resource.  
However this doesn't appear to be the case:
```
$ ipwd
/seq-dev/illumina/library_merge
$ iput 10000_not_a.cram 
$ ils -l 10000_not_a.cram
  ap21_testing      0 root;replicate;red;red3;irods-xxxxxxxx         1024 2016-07-04.15:17 & 10000_not_a.cram
  ap21_testing      1 root;replicate;green;green7;irods-yyyyyyy         1024 2016-07-04.15:17 & 10000_not_a.cram

```
To debug this I tried adding ```writeLine``` statements to all the rules in seq-dev.re to write to stdout but they returned nothing. I added ```writeLine``` commands to the core.re as well and they also did not appear to work so either I have misunderstood how to use ```writeLine``` or there is also something wrong with ```writeLine``` rule? The syntax I used was ```writeLine("stdout","a debugging message here");```. 

I had the debugging turned up to level 10 on all servers and the user in their respective irods_environment.json which was captured in the ```ienv```.  The logs seemed to show nothing. I couldn't use the idbug command as documented in my previous github issue. I'm at a bit of a loss as to what more I can do to debug this

**Comment by trel** [comment]
Try `writeLine("serverLog", $string)` rather than `stdout`.

**Comment by trel** [comment]
Closing.

I think the work on #2713 will clear up the server resource selection behavior.
