### ISSUE TITLE
Oracle Database Plugin connection pooling

### ISSUE THREAD

**Issue by kript** [irods/irods#3213]
Apologies if this is a duplicate request, but I couldn't find it in the list of issues.

At present iRODS creates a new connection for each operation; can it be made to use connection pooling?

Thanks!

John

**Comment by keithj** [comment]
Found the previous issue here #2063

**Comment by Pete-C** [comment]
If we are closing this as a duplicate, can we please re-activate the original and see if we can progress ? At scale, this rapidly hits the irods and iCAT services very hard and prevents scalability of service 

    On Friday, 8 July 2016, 16:19, kellerb <notifications@github.com> wrote:
 

 Closed #3213.—

**Comment by trel** [comment]
Yes, we'll be talking about it at the TWG if you want.  It can be part of the 4.2+ work.

**Comment by Pete-C** [comment]
Thanks for the update and for raising at the TWG. For reference only, this is limiting our ability to scale our current service. 

    On Friday, 8 July 2016, 20:46, Terrell Russell <notifications@github.com> wrote:
 

 Yes, we'll be talking about it at the TWG if you want. It can be part of the 4.2+ work.—

**Comment by trel** [comment]
Thanks not needed, you're the member.  You get to decide what iRODS looks like :)
