### ISSUE TITLE
slow ils -A across federation

### ISSUE THREAD

**Issue by trel** [irods/irods#3215]
Originally seen with 4.x<->3.x federations, this has now been reproduced on 4.x<->4.x federations as well.

With 500 dataobjects to list in the remote zone's collection...

With the ACL listing:
```
irods@icat:~$ time ils -A /otherZone/home/rods#tempZone/ > /dev/null

real    0m31.867s
user    0m0.192s
sys     0m0.035s
```
Without the ACL listing:
```
irods@icat:~$ time ils /otherZone/home/rods#tempZone/ > /dev/null

real    0m0.553s
user    0m0.015s
sys     0m0.004s
```

Upon inspection of the rodsLog, the -A listing is creating a single Agent (the PID remains the same), but creating a new database connection for every data object (to get the permissions).

**Comment by jasoncoposky** [comment]
inadvertent commit to #3125 for 4-1-stable branch 7bdac12ac0cbe11cb2751ca1c3ee782e3cf2490c
