### ISSUE TITLE
Allow irepl to handle resource hierarchies properly

### ISSUE THREAD

**Issue by tledoux** [irods/irods#3217]
Currently, only `iadmin` rebalance allow for properly rebalancing replicas under a replication resource. This is an admin-only command.

It would be useful to allow `irepl` to be able to act on a hierarchy (in a similar form that `ireg`, see #1934) so that the following command works 
`irepl -S element1 -R element2 record1`

The use case is the following.

Given the following hierarchy:

```
capsule:replication
├──gate1:passthru
│   └──element1:unixfilesystem, vault=/sas/element1
├──gate2:passthru
    └──element2:unixfilesystem, vault=/sas/element2
```

We might need to close the element2 for maintenance for example by
`iadmin modresc gate2 context "read=0.0;write=0.0"`

During this period, some records are put
`iput -K -R capsule record1` ...

After some time, we put back the element2 resource with
`iadmin modresc gate2 context "read=1.0;write=1.0"`

At this point, either we rebalance (but we will not know how many records there are, how long it will take, and when it will be finished), or we find the missing replicas (see #2100) and then we can plan for their rebalancing by the proposed command
`irepl -S element1 -R element2 record1`

**Comment by alanking** [comment]
This has been determined to be "working as designed". Resource hierarchies encode the administrator's policy, so allowing this behavior would be circumventing that policy. See: https://docs.irods.org/4.2.8/plugins/composable_resources/#replication

Suggested workaround - hierarchy manipulation (admin only):
 - Remove from the hierarchy the leaf resource which is to receive the replica (`iadmin rmchildfromresc`)
 - Replicate to the target resource (`irepl -R <target resource>`)
 - Add target leaf resource back to the hierarchy (`iadmin addchildtoresc`)

This workaround allows "repair" of a particular data object in a replicating resource hierarchy without the invocation of a full rebalance.

---

As of 4.2.9, an alternate workaround:
 - Physical move to a different leaf resource in the same replicating hierarchy (`iphymv -R <target resource>`)
 - Replication is triggered automatically to other children in the replicating hierarchy

**Comment by alanking** [comment]
Given the workaround described above and the resolution of #4010, I think this can be closed.
