### ISSUE TITLE
Listing the root of a Federated Zone

### ISSUE THREAD

**Issue by carrgilson** [irods/irods#3218]
The root of a Federated Zone will not successfully list, returning no results despite user permissions being applied and running with the Standard ACL policy.

I've tested this where both deployed zones are running with code from the 4.1.8 RPMs.
This is the case when using both the ils iCommand or using Cyberduck.

Discussions occurred here: https://groups.google.com/forum/#!topic/irod-chat/NQL-rgY5J0I

**Comment by kript** [comment]
👍 we have the same issue

**Comment by trel** [comment]
We have a fix in CI for 4.1.9, but cannot push a test for it as the test framework does not yet support changing the `core.re` on a remoteZone.  Leaving open with a TODO for later.
