### ISSUE TITLE
Dashes in zone names

### ISSUE THREAD

**Issue by jenspeters** [irods/irods#3223]
Hello, 

While creating Zone names with dashes (e.g. `iadmin mkzone abc-test remote localhost`) iRODS 4.1.8 answers `ERROR: rcGeneralAdmin failed with error -130000 SYS_INVALID_INPUT_PARAM `. No escaping /masquerading seems to be accepted. What are the allowed characters for zone names in 4.x?

Kind regards, Jens

**Comment by kellerb** [comment]
Alphanumeric characters, periods, and underscores.

`.0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz`
