### ISSUE TITLE
check range on irods_log_level

### ISSUE THREAD

**Issue by andyjp94** [irods/irods#3225]
With the irods_log_level variable set to zero irods does not display messages that I would consider fatal.

```
ienv
NOTICE: Release Version = rods4.1.8, API Version = d
NOTICE: irods_session_environment_file - /nfs/users/nfs_a/ap21/.irods/irods_environment.json_seq_dev.cwd
NOTICE: irods_user_name - ap21_testing
NOTICE: irods_host - irods-g1-dev.internal.sanger.ac.uk
NOTICE: xmsg_host is not defined
NOTICE: irods_home - /seq-dev/home/ap21_testing
NOTICE: irods_cwd - /seq-dev/illumina/library_merge
NOTICE: irods_authentication_scheme - native
NOTICE: irods_port - 1247
NOTICE: xmsg_port is not defined
NOTICE: irods_default_resource is not defined
NOTICE: irods_zone_name - seq-dev
NOTICE: irods_client_server_policy is not defined
NOTICE: irods_client_server_negotiation is not defined
NOTICE: irods_encryption_key_size is not defined
NOTICE: irods_encryption_salt_size is not defined
NOTICE: irods_encryption_num_hash_rounds is not defined
NOTICE: irods_encryption_algorithm is not defined
NOTICE: irods_default_hash_scheme is not defined
NOTICE: irods_match_hash_policy is not defined
NOTICE: irods_gsi_server_dn is not defined
NOTICE: irods_debug is not defined
NOTICE: irods_log_level - 0
icd /seq-dev/
ipwd
/seq-dev/illumina/library_merge
```
After removing the irods_log_level variable and typing icd /seq-dev/ again I get:
```
ERROR: _rcConnect: connectToRhost error, server on irods-g1-dev.internal.sanger.ac.uk:1247 is probably down status = -305113 USER_SOCK_CONNECT_ERR, No route to host
```
So technically this is reporting correctly. As error messages shouldn't show up with a debugging level of 0 according to https://docs.irods.org/4.1.8/manual/troubleshooting/#debugging-levels. However I would expect this to be a fatal error as it's hard to get much more fatal than "I can't find the server". I may have misunderstood the purpose of the fatal logging, if so could you explain it in more detail?

**Comment by trel** [comment]
Should we mark an `irods_log_level` setting of `0` as a warning itself?
(Perhaps actually check the range of known good values?)

Otherwise, I'm not sure what a fix for this would look like.  Suggestions welcome.

**Comment by trel** [comment]
We'll check the range when reading the environment.
