### ISSUE TITLE
[XBB-2 branch] Missing libboost_filesystem dependencies

### ISSUE THREAD

**Issue by jmarshall** [irods/irods#3227]
Building HTSlib's iRODS plugin (which is plain C code that does not itself use boost or anything else other than various iRODS functions) against 4.2-to-be in the **XBB-2** branch is successful when linked against `-lirods_common -lirods_client_core -lirods_plugin_dependencies -lirods_client_api_table` and nothing else. (Is there documentation of what these various iRODS libraries are and which ones various kinds of client code should need to link against?)

However the resulting object file does not work:

> [W::load_plugin] can't load plugin "/home/jm18/build/plugins/hfile_irods.so": /home/jm18/build/irods/libirods_plugin_dependencies.so.4.2.0: undefined symbol: _ZNK5boost10filesystem4path4stemEv

It appears that code in _libirods_plugin_dependencies.so_ uses `boost::filesystem`, and so its `target_link_libraries` stanza needs to list _libboost_filesystem.so_.  Adding that and rebuilding _libirods_plugin_dependencies.so_ results in a running _hfile_irods.so_ plugin.

Grepping various libirods libraries for undefined `boost::filesystem` symbols, it appears that at least _libirods_client_core.so_, _libirods_common.so_, and _libirods_plugin_dependencies.so_ each use `boost::filesystem` but are currently not linked against it.  Indeed, by changing the order in which the libraries are linked against, the error message can be made to come from any of these three.

**Comment by kellerb** [comment]
Issue for documenting the iRODS libraries has been made [here](https://github.com/irods/irods/issues/3228).

Thank you for reporting this. There are still some circular dependencies between the iRODS libraries, so we have not yet been able to add the build time check for missing symbols (`-Wl,-z,defs`).

Please let us know if this issue has been fixed, and feel free to close it if it has.

**Comment by jmarshall** [comment]
Thanks, that does the trick.
