### ISSUE TITLE
cannot install irods-icat  irods-database-plugin-postgres

### ISSUE THREAD

**Issue by AlfredoKCL** [irods/irods#3242]
I am trying to install irods on ubuntu 13 following the instructions: http://irods.org/wp-content/uploads/2015/06/GettingStartedwiRODS4.1.pdf

running:

`sudo dpkg -i irods-icat-4.1.9-ubuntu12-x86_64.deb irods-database-plugin-postgres-1.9-ubuntu12-x86_64.deb training-example-1.0.deb`

and 

`sudo apt-get -f install`

all I get is 

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 191 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up irods-icat (4.1.9) ...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
IOError: [Errno 2] No such file or directory: '/var/lib/irods/VERSION.json.previous'
dpkg: error processing irods-icat (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of irods-database-plugin-postgres:
 irods-database-plugin-postgres depends on irods-icat; however:
  Package irods-icat is not configured yet.

dpkg: error processing irods-database-plugin-postgres (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                          Errors were encountered while processing:
 irods-icat
 irods-database-plugin-postgres
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Can anybody help me?

**Comment by kellerb** [comment]
Did the computer have an older version of iRODS already installed?
Had you tried to install this version of iRODS at least once already and had it fail?

If there is no data on this installation yet, often the simplest way forward is to delete everything and start over:

1. `sudo dpkg -P irods-icat irods-database-plugin-postgres`
2. Drop and re-create your database
3. `sudo rm -rf /var/lib/irods /etc/irods /tmp/irods`
4. Re-install the packages and run the setup script

Make sure the above steps are performed in that order.

**Comment by trel** [comment]
closing - this works as far as we know.  please open a new issue if there is a similar problem.
