### ISSUE TITLE
izonereport fails if a server is decommissioned

### ISSUE THREAD

**Issue by kript** [irods/irods#3246]
Found this while upgrading a Zone from 3.3.1 to 4.1.9, running `izonereport` on the iCAT gave an error (which I omitted to capture, sorry). Looking through logs there was
```
Aug  4 14:51:13 pid:25520 ERROR: gethostbyname unrecoverable NULL return. retry count: [0] hostname: [irods-hum-r2.xxxxx.ac.uk] h_errno [1] hstrerror [Unknown host]
```
which I was then able to correlated to a demoResc from a  decommissioned server. So, not surprising per se, but perhaps also not the expected behavior from a reporting tool?
I'd have expected it to skip over the missing entry, perhaps dumping an error to STDERR, rather than crash.

**Comment by jasoncoposky** [comment]
We are now injecting an error object into the resource_servers array:

```
"resource_servers": [
    {   
        "ERROR": "failed in svrToSvrConnect for resource [invalidResc], at hostname [invalid_hostname], error code -303000"
    }
]
```
