### ISSUE TITLE
ifsck does not work with long path names

### ISSUE THREAD

**Issue by carsten-jahn** [irods/irods#3249]
I’ve discovered that both in 4.0.3 and 4.1.8, long physical paths (resulting from long iRODS paths) bring ifsck to a halt - it also won’t check further directories. The cutoff seems to be around char 255.

```
$ cp t.metadata longdir/abcdefghijklmnopqrstuvwxyz01234567890/abcdefghijklmnopqrstuvwxyz01234567890/abcdefghijklmnopqrstuvwxyz01234567890/abcdefghijklmnopqrstuvwxyz01234567890/abcdefghijklmnopqrstuvwxyz01234567890/GREATERTHAN256/dfhsdhjkfdhsjkszuzurefgnhjdsahjdsazuzuhjrehjew/dshjsdhjdhuhdshjkguzgufdhjdsfhuzughjgf
$ iput -r longdir /bhctestZone/home/sgpeo/longdir

$ ifsck -r /irods/vault/home/sgpeo/longdir/abcdefghijklmnopqrstuvwxyz01234567890/abcdefghijklmnopqrstuvwxyz01234567890/abcdefghijklmnopqrstuvwxyz01234567890/abcdefghijklmnopqrstuvwxyz01234567890/abcdefghijklmnopqrstuvwxyz01234567890/
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::file_size: No such file or directory: "/irods/vault/home/sgpeo/longdir/abcdefghijklmnopqrstuvwxyz01234567890/abcdefghijklmnopqrstuvwxyz01234567890/abcdefghijklmnopqrstuvwxyz01234567890/abcdefghijklmnopqrstuvwxyz01234567890/abcdefghijklmnopqrstuvwxyz01234567890/GREATERTHAN256/dfhsdhjkfdhsjkszuz"
Aborted
```

Please decide what lengths are acceptable for the whole set of tools, and change iRODS so that it won’t accept deviating data. E.g. if ifsck or ichksum or any other command fail with a certain file, path, physical path, ACL group or user name length, etc., the user or admin shouldn’t even have the option of bringing that data into iRODS.

**Comment by tsmeele** [comment]
ifsck is a crucial tool to us help us detect inconsistencies between icat registration and data files e.g. as a result of transfer problems. The 255 byte limitation on physical file path renders this tool inoperable for most of our iRODS environments.

**Comment by kellerb** [comment]
There appear to be two places where a limit of 255-ish characters is implicitly or explicitly enforced:

https://github.com/irods/irods/blob/d6e1aef03c2848d9b922b968da463481b55bd242/lib/core/src/fsckUtil.cpp#L47-L51

https://github.com/irods/irods/blob/d6e1aef03c2848d9b922b968da463481b55bd242/lib/core/src/fsckUtil.cpp#L88-L89
