### ISSUE TITLE
iscan exits with supposedly incorrect error code

### ISSUE THREAD

**Issue by AndreyNevolin** [irods/irods#3256]
Hi,

Please see the picture below. It depicts two scenarios for iscan:

1) object is registered with iRODS but is absent on disk. In this case error message is printed but **exit code is zero**
2) object is not registered with iRODS but exists on disc. In this case error message is printed and **exit code is non-zero**

![screenshot-2016- -12-611-pm](https://cloud.githubusercontent.com/assets/7734325/17625314/fdff31dc-60b0-11e6-98f8-827ca94c9b5f.png)

**Comment by jaking92** [comment]
This issue is resolved with the solution to #3681

**Comment by trel** [comment]
moved to 4.1.12 and closing - thanks!
