### ISSUE TITLE
iadmin rmchildfromresc fails

### ISSUE THREAD

**Issue by nono-gdv** [irods/irods#3258]
```
irods@icat-0115:~$ ilsresc 
PAPY:passthru
└── PAPY_primary:load_balanced
    ├── node-0003
    └── node-0005
PAPY_secondary:load_balanced
├── node-0006
└── node-0007
irods@icat-0115:~$ iadmin rmchildfromresc PAPY_secondary node-0006
irods@icat-0115:~$ echo $?
4
irods@icat-0115:~$ ilsresc 
PAPY:passthru
└── PAPY_primary:load_balanced
    ├── node-0003
    └── node-0005
PAPY_secondary:load_balanced
├── node-0006
└── node-0007
```

Here are the relevant lines from the log file:
```
Aug 16 12:38:38 pid:336 NOTICE: rsGeneralAdmin remove child "node-0006" from resource "PAPY_secondary"
Aug 16 12:38:38 pid:336 NOTICE: chlDelChildResc aborted. Resource update error, status = -819000
Aug 16 12:38:38 pid:336 NOTICE: chlDelChildResc cmlExecuteNoAnswerSql(rollback) succeeded
Aug 16 12:38:38 pid:336 NOTICE: rsGeneralAdmin: rcGeneralAdmin error -819000
Aug 16 12:38:38 pid:336 NOTICE: readAndProcClientMsg: received disconnect msg from client
Aug 16 12:38:38 pid:336 NOTICE: Agent exiting with status = 0
```

Resource node-0006 is supposed to be empty, but ilsresc disagrees:
```
irods@icat-0115:~$ iquest "select DATA_ID where RESC_NAME = 'node-0006'"
CAT_NO_ROWS_FOUND: Nothing was found matching your query
irods@icat-0115:~$ ilsresc -l node-0006 | grep count
object count: 24
```

This makes me suspect an inconsistency in the database. However I unsure where it comes from and how to fix it.

**Comment by trel** [comment]
Yes, the 24 appears to be at odds with the database.

```
$ ierror 819000
irods error: -819000 CAT_SUCCESS_BUT_WITH_NO_INFO
```

Is this on 4.1.9?

Are any of the other resources 'out of sync'?

If you increase the logging a bit, can you see any more detail about what happened?

https://docs.irods.org/4.1.9/manual/troubleshooting/#debugging-levels

**Comment by nono-gdv** [comment]
This is on 4.1.8 and as far as I can tell the other resources look right.

I have enabled SQL debugging but I'm not familiar enough with iRODS to make sense of it.

{code}
Aug 17 08:21:38 pid:27521 NOTICE: Agent process 27552 started for puser=rods and cuser=rods from 10.20.101.31
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: select count(*) from pg_settings limit 1
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 result: SUCCESS
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: select name, setting from pg_settings
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 result: SUCCESS
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: select distinct R_ZONE_MAIN.zone_name ,R_ZONE_MAIN.zone_type_name ,R_ZONE_MAIN.zone_conn_string ,R_ZONE_MAIN.r_comment  from  R_ZONE_MAIN 
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 result: SUCCESS
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: select distinct R_RESC_MAIN.resc_id ,R_RESC_MAIN.resc_name ,R_RESC_MAIN.zone_name ,R_RESC_MAIN.resc_type_name ,R_RESC_MAIN.resc_class_name ,R_RESC_MAIN.resc_net ,R_RESC_MAIN.resc_def_path  ,R_RESC_MAIN.free_space ,R_RESC_MAIN.resc_info ,R_RESC_MAIN.r_comment ,R_RESC_MAIN.create_ts ,R_RESC_MAIN.modify_ts  ,R_RESC_MAIN.resc_status ,R_RESC_MAIN.resc_children  ,R_RESC_MAIN.resc_context  ,R_RESC_MAIN.resc_parent  ,R_RESC_MAIN.resc_objcount   from  R_RESC_MAIN 
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 result: SUCCESS
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar[1]=rods
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar[2]=rulelogging
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: select distinct r_user_meta_main.meta_attr_value  from  R_META_MAIN r_user_meta_main , R_OBJT_METAMAP r_user_metamap , R_USER_MAIN  where R_USER_MAIN.user_name = ?  AND r_user_meta_main.meta_attr_name = ?  AND R_USER_MAIN.user_id = r_user_metamap.object_id  AND r_user_metamap.meta_id = r_user_meta_main.meta_id 
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 result: SUCCESS
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar1=rods
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar2=PAPY
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: select rcat_password, pass_expiry_ts, R_USER_PASSWORD.create_ts, R_USER_PASSWORD.modify_ts from R_USER_PASSWORD, R_USER_MAIN where user_name=? and zone_name=? and R_USER_MAIN.user_id = R_USER_PASSWORD.user_id
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 result: SUCCESS
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar1=rods
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar2=PAPY
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: select user_type_name from R_USER_MAIN where user_name=? and zone_name=? limit 1
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 result: SUCCESS
Aug 17 08:21:38 pid:27552 NOTICE: rsGeneralAdmin remove child "node-0006" from resource "PAPY_secondary"
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar1=local
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: select zone_name from R_ZONE_MAIN where zone_type_name=? limit 1
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 result: SUCCESS
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar1=PAPY_secondary
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar2=PAPY
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: select resc_id from R_RESC_MAIN where resc_name=? and zone_name=? limit 1
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 result: SUCCESS
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar1=node-0006
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar2=PAPY
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: select resc_id from R_RESC_MAIN where resc_name=? and zone_name=? limit 1
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 result: SUCCESS
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: begin
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 result: SUCCESS
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar[1]=
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar[2]=01471422098
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar[3]=2217177
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: update R_RESC_MAIN set resc_parent=?, modify_ts=? where resc_id=?
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 result: SUCCESS
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar1=779319
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: select resc_children from R_RESC_MAIN where resc_id=? limit 1
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 result: SUCCESS
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar[1]=node-0007{}
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar[2]=01471422098
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar[3]=779319
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: update R_RESC_MAIN set resc_children=?, modify_ts=? where resc_id=?
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 result: SUCCESS
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar1=node-0006
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: select resc_objcount from R_RESC_MAIN where resc_name=? limit 1
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 result: SUCCESS
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar1=PAPY_secondary
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar2=PAPY
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: select resc_parent from R_RESC_MAIN where resc_name=? and zone_name=? limit 1
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 result: SUCCESS
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar1=node-0006
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: select resc_objcount from R_RESC_MAIN where resc_name=? limit 1
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 result: SUCCESS
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar1=PAPY_secondary
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar2=PAPY
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: select resc_id from R_RESC_MAIN where resc_name=? and zone_name=? limit 1
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 result: SUCCESS
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar[1]=01471422098
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar[2]=779319
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: update R_RESC_MAIN set resc_objcount=resc_objcount+-24, modify_ts=? where resc_id=?
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 result: SUCCESS
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar[1]=node-0006
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar[2]=PAPY_secondary;node-0006
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar[3]=PAPY_secondary;node-0006
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar[4]=PAPY_secondary;node-0006;%
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: update R_DATA_MAIN set resc_hier = ? || substring(resc_hier from (char_length(?)+1)) where resc_hier = ? or resc_hier like ?
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 result: SUCCESS
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar[1]=node-0006
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar[2]=node-0006
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar[3]=node-0006
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: bindVar[4]=node-0006;%
Aug 17 08:21:38 pid:27552 LOG_SQL: pid: 27552 sql: update R_DATA_MAIN set resc_name = ?, resc_group_name = ? where resc_hier = ? or resc_hier like ?
Aug 17 08:21:39 pid:27552 LOG_SQL: pid: 27552 result: SUCCESS
Aug 17 08:21:39 pid:27552 NOTICE: chlDelChildResc aborted. Resource update error, status = -819000
Aug 17 08:21:39 pid:27552 LOG_SQL: pid: 27552 sql: rollback
Aug 17 08:21:39 pid:27552 LOG_SQL: pid: 27552 result: SUCCESS
Aug 17 08:21:39 pid:27552 NOTICE: chlDelChildResc cmlExecuteNoAnswerSql(rollback) succeeded
Aug 17 08:21:39 pid:27552 LOG_SQL: pid: 27552 sql: rollback
Aug 17 08:21:39 pid:27552 LOG_SQL: pid: 27552 result: SUCCESS_WITH_INFO
Aug 17 08:21:39 pid:27552 NOTICE: rsGeneralAdmin: rcGeneralAdmin error -819000
Aug 17 08:21:39 pid:27552 NOTICE: readAndProcClientMsg: received disconnect msg from client
Aug 17 08:21:39 pid:27552 NOTICE: Agent exiting with status = 0
Aug 17 08:21:39 pid:27521 NOTICE: Agent process 27552 exited with status 0
{code}

**Comment by nono-gdv** [comment]
Any idea about this? Is it OK if I just change r_resc_main.resc_objcount by hand in the database, or do I risk further breakage?

**Comment by trel** [comment]
Please check to make sure there is nothing in the Trash that might still be on that resource.

@jasoncoposky, do any of the resource operations get a new 'dead reckoning' count and reset the resc_objcount value?  Rebalance?

Otherwise, I think it will be safe in this instance to manually reset the database value for resc_objcount for this resource.

**Comment by jasoncoposky** [comment]
Yes for the 4.0 and 4.1 series, given this resource hierarchy, resetting the object count in the catalog will work.  I would run an iquest, or a query directly against the database to verify that there is nothing lurking with that particular resource hierarchy first.

**Comment by nono-gdv** [comment]
I have reset the counter to 0 in the database after triple-checking the resource server was actually empty. So far so good.

Thanks for your time!
