### ISSUE TITLE
iquest post-data-CAT_NO_ROWS_FOUND

### ISSUE THREAD

**Issue by mcast** [irods/irods#3262]
- [x] 4-1-stable
- [x] 4-2-stable
- [x] master

---

I'm reporting this for 3.3.1 (icommands and server) just so it is "out there" to find, but I'm not expecting a fix.
1. We have about 2e6 files in our production system.
2. We need to run iquest to find classes of file and run checks against them.
3. To split the work into manageable and parallelisable chunks,
   - `select min(DATA_ID), max(DATA_ID), count(DATA_ID) where $WANTED`
   - then chop the window down, like so...
   - `select min(DATA_ID), max(DATA_ID), count(DATA_ID) where $WANTED and DATA_ID between '22389155' '27093278'`
   - `select min(DATA_ID), max(DATA_ID), count(DATA_ID) where $WANTED and DATA_ID between '27093279' '31797401'`
   - (WANTED=`META_DATA_ATTR_NAME = 'id_ifile'`)
4. with a list of binned window sizes, I run the query I actually wanted in smaller bites
   - `select order(DATA_ID), order(DATA_REPL_NUM), DATA_REPL_STATUS, COLL_NAME, DATA_NAME, DATA_CHECKSUM, DATA_SIZE, RESC_NAME where $WANTED and DATA_ID between '22389155' '22406771'`

This works fine quite often...  but some window edges cause `iquest` to emit (on stdout, with exit code zero [as documented](https://groups.google.com/forum/#!topic/irod-chat/vueiG1a3MIg)) the `CAT_NO_ROWS_FOUND: Nothing was found matching your query\n\n` message **after** tens of thousands of valid data rows.

I tried to binary-chop the window size down to produce a single invalid DATA_ID, but the error goes away.

Now I'm using that response as a workaround to the problem, I'll just chop the window and try again.

**Comment by trel** [comment]
Can we confirm the behavior is still around in a newer installation?   How often do you see the edge case occur - 1 in ? queries?

**Comment by mcast** [comment]
On Thu, Aug 25, 2016 at 05:37:13AM -0700, Terrell Russell wrote:

> Can we confirm the behavior is still around in a newer installation?

I'm not ready to do that, but do expect to be going to 4.1.9 in a few
months.

> How often do you see the edge case occur - 1 in ? queries?

Possibly 1:60 but not for all types of query.

With the queries I was running earlier, which had more restrictive
WHERE terms, it simply didn't happen.  Maybe I was just lucky, but it
feels more like a data-dependent bug.

The queries I'm running cut the ~2e6 files (4,202,261 file-replicas)
into chunks, and usually get one failure.  The coordinates of the
failure seem to depend on the window size but are stable.  I'm not
changing any of the files in the window, but I can't promise they
won't change later.

Upon splitting the broken window in two, my code continues.  I haven't
seen two failures in one run...  oh, until I tried tiny bins.

```
 binsize	bin count	failure at DATA_ID	takes
 -------	---------	--------------------	----
  50k		 60		23093807 .. 23129039	15 min
  20k		126		22424388 .. 22442004
  10k		249		23551830 .. 23560638	25 min
  80k		 32		no fail			14 min

   1k		3603		22897826 ..  22898376	151 min	66 failures, some nested
				 22898101 .. 22898376
				22900028 .. 22900578
				23286485 .. 23287035
				23288687 .. 23289237
				23289239 .. 23289787
				23300247 .. 23300796
				23322819 .. 23323369
				23427966 .. 23428515
				23427966  .. 23428240
				 23428103 .. 23428240
				23905257 .. 23905807
				24026920 .. 24027469
				24026920 ..  24027194
				24268501 .. 24269012
				24268501 ..  24268756
				24268501 ..   24268628
				24269013 .. 24269524
				24269013 ..  24269268
				24269013 ..   24269140
				24269525 .. 24270036
				24269525 ..  24269780
				24269525 ..   24269652
				24271063 .. 24271574
				24271063 ..  24271318
				24271063 ..   24271190
				24271575 .. 24272086
				24271575 ..  24271830
				24271575 ..   24271702
				24272087 .. 24272598
				24272087 ..  24272342
				24272087 ..   24272214
				24273112 .. 24273623
				24273112 ..  24273367
				24273112 ..   24273239
				24273624 .. 24274135
				24273624 ..  24273879
				24273624 ..   24273751
				24274136 .. 24274647
				24274136 ..  24274391
				24274136 ..   24274263
				24274648 .. 24275159
				24274648 ..  24274903
				24274648 ..   24274775
				24275160 .. 24275671
				24275160 ..  24275415
				24275160 ..   24275287
				24275672 .. 24276183
				24275672 ..  24275927
				24275672 ..   24275799
				24276184 .. 24276695
				24276184 ..  24276439
				24276184 ..   24276311
				24277721 .. 24278232
				24277721 ..  24277976
				24277721 ..   24277848
				24278233 .. 24278744
				24278233 ..  24278488
				24278233 ..   24278360
				24278745 .. 24279256
				24278745 ..  24279000
				24278745 ..   24278872
				24279257 .. 24279768
				24279257 ..  24279512
				24279257 ..   24279384
				31624442 .. 31626406
```

It's interesting that the windows don't overlap!


I haven't attempted to run the same query through the Python API or
equivalent.  Also I haven't tried changing the output field set.

-- 
Matthew


[1] For given binsize this usually puts the boundaries in the same
place, so I'll see failures repeating at the same place on subsequent
runs.


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by carsten-jahn** [comment]
Hi, I stumbled upon the same behavior (iquest outputting data correctly, then a last line "CAT_NO_ROWS_FOUND: Nothing was found matching your query" and then returning with exit code 0) in iRODS 4.1.9.

There are 513 lines of output - so not considering the message line, it looks as if iquest gets a 512 line block of its result set, then tries to fetch the next block, but its empty, and outputs the message. (This is speculation of course ;-) )

I fix would be great for this - we have a couple of processes which get data with iquest.

**Comment by trel** [comment]
related to...

https://github.com/irods/irods/issues/3404
https://github.com/irods/irods/issues/3405
https://github.com/irods/irods/issues/3406

**Comment by mcast** [comment]
Thanks for investigating

**Comment by kellerb** [comment]
It appears to be an issue of having the number of results be a multiple of [256](https://github.com/irods/irods/blob/4.1.10/iRODS/lib/core/include/rodsGenQuery.h#L16).

Can be replicated as:
``` bash
for i in {000..255}; do iput VERSION.json file_$i; done
```
```
iquest --no-page "select DATA_ID" | tail                                                                                                                                                    
------------------------------------------------------------
DATA_ID = 10340
------------------------------------------------------------
DATA_ID = 10284
------------------------------------------------------------
DATA_ID = 10448
------------------------------------------------------------
DATA_ID = 10328
------------------------------------------------------------
CAT_NO_ROWS_FOUND: Nothing was found matching your query
```

**Comment by kellerb** [comment]
The problem is probably that `CAT_NO_ROWS_FOUND` is not being handled appropriately [here](https://github.com/irods/irods/blob/4.1.10/iRODS/server/re/src/functions.cpp#L395-L397).
