### ISSUE TITLE
Bump CMake required version and externals version to 3.7.0 once it is released

### ISSUE THREAD

**Issue by mcv21** [irods/irods#3266]
Hi,

The current master branch (which I believe will become 4.2)'s build system requires cmake 3.5.0 or higher to build; this means it will only be buildable on Ubuntu 16.04 or later; Ubuntu 12 shipped with 2.8.7 and Ubuntu 14 shipped with 2.8.12:

http://packages.ubuntu.com/search?keywords=cmake

Regards,

Matthew

**Comment by kript** [comment]
Hi Folks, @mcv21 is our new colleage, so he needs the coveted `consortium member` status, please. :-)

Also, at present we run on 12.04, so if the OS is to be deprecated we need to know a while in advance..

cheers

John

**Comment by trel** [comment]
Yes, this is by design.

We are using consistent versions of all our build tools for 4.2+ - all provided by the https://github.com/irods/externals repository.

The toolchain will be provided pre-compiled for our supported platforms via apt and yum repositories.  Otherwise, they'll need to be compiled from source.

**Comment by kellerb** [comment]
Note that our externals build a custom version of cmake that has one modification on top of cmake 3.5.2 [commits here](https://github.com/irods/CMake/commits/v3.5.2-irods-modifications), [direct link to custom commit](https://github.com/irods/CMake/commit/5ffa0d5d35b13b540c386995ce19aef5b66064b7). You will need to make sure that if you are building cmake, you use this change (or figure out how to edit our cmake files to make the change unnecessary. If you figure this out, please let us know.).

**Comment by mcv21** [comment]
What do cmake's authors think of this patch?

**Comment by kellerb** [comment]
I sent an email to the cmake mailing list, and I don't believe there have been any responses yet.

https://cmake.org/pipermail/cmake/2016-May/063380.html

**Comment by kellerb** [comment]
We may be able to set `CPACK_PACKAGING_INSTALL_PREFIX` to `///` instead of `/`, which should properly be treated as `/`, while also allowing for the appending of additional `/`s.

**Comment by kellerb** [comment]
Nevermind, that won't work. I forgot the specifics of the issue.

I sent an email to the cmake-developer mailing list, with a little more detail:

https://cmake.org/pipermail/cmake-developers/2016-September/029329.html

**Comment by kellerb** [comment]
The cmake devs have accepted the patch, so we should be able to switch back to pure upstream when they release the next version.

https://github.com/Kitware/CMake/commit/290e4ce8a89819d6617fa404513d8a1629cafea7

**Comment by kellerb** [comment]
The patch has been included in [3.7.0-rc1](https://github.com/Kitware/CMake/tree/v3.7.0-rc1).

**Comment by trel** [comment]
Done!
