### ISSUE TITLE
inter-dependencies between irods packages too restrictive

### ISSUE THREAD

**Issue by mcv21** [irods/irods#3271]
The 4.2.0 packaging system uses CPack, and builds Debian packages with `CPACK_PACKAGE_VERSION` set, but `CPACK_DEBIAN_PACKAGE_VERSION` unset ; CPack then uses `CPACK_PACKAGE_VERSION`.

This means that if we want to build our own packages, we can set `CPACK_DEBIAN_PACKAGE_VERSION` on the command-line, and things mostly work - notably we get packages with the correct Version, so we can later tell which version we have installed (the older build system lacks this facility).

Unfortunately, the inter-dependencies between the Debian packages are set to be `IRODS_VERSION` rather than `CPACK_DEBIAN_PACKAGE_VERSION` e.g. in cmake/server.cmake:

```
cmake/server.cmake:set(CPACK_DEBIAN_${IRODS_PACKAGE_COMPONENT_SERVER_NAME_UPPERCASE}_PACKAGE_DEPENDS "${IRODS_PACKAGE_DEPENDENCIES_STRING}, irods-runtime (= ${IRODS_VERSION}), irods-icommands (= ${IRODS_VERSION}), libc6, sudo, libssl1.0.0, libfuse2, python, openssl, python-psutil, python-requests, lsof")
```

If this (and the related dependencies on irods-server and irods-icommands were set to `CPACK_DEBIAN_PACKAGE_VERSION`, then it would be much easier to build correctly-numbered packages.

I think there is a similar issue with rpm packages, but I've not looked into that in detail

**Comment by kellerb** [comment]
1. What if CMakeLists.txt were changed to let you optionally set `IRODS_VERSION`?

2. Are you assigning a value to `CPACK_DEBIAN_PACKAGE_VERSION` that won't ever conflict with any other consortium released version? If so, what value?

3. What if CMakeLists.txt were changed to let you optionally append something to the package names, (e.g. `made-by-sanger`) but still have the "provides irods" etc. settings.

4. How are the packages you are building different?

**Comment by mcv21** [comment]
1. That would probably work, but feels like a slightly odd place to make this change - after all, you already define CPACK_PACKAGE_VERSION, and, in general packages might have slightly different version numbers to the upstream source they're built from (to pick a random example: pcre 8.31has become pcre3 version 1:8.31-2ubuntu2.3 on this machine).

2. In much the way that, say, Debian would, by appending to your version number (e.g. 4.1.9-1); in extremis there might be an epoch pre-pended too. I would expect to follow Debian policy ( https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version )

3. Package names are, I think, the wrong place to make this change - analogously to a distribution, we are building a slightly different version of irods-server (say), not a different piece of software, and you might reasonably want to upgrade between a locally-modified version and an upstream one; that goes much more smoothly with packages with the same name and different versions!

Relatedly, changing the .deb filename doesn't help - you want to be able to go dpkg -s irods-runtime | grep Version and get a useful answer that can tell you what version you're running.

4. I'm new here, but I see from our local repos that we've sometimes backported a bugfix or enhancement from your master to our production packages. Similarly, if we fix a bug locally, we would build a new version for testing and so on.

**Comment by jmarshall** [comment]
:+1: especially to @mcv21's point 3.  We have backports, local experiments, or (historically) just different build environments (cf first paragraph of #3260), all of which would be usefully annotated by appending to the version number.  Recently trying to track down what was on a particular machine when by looking at _/var/log/dpkg.log_ I was presented with

> 2016-08-09 15:34:34 status installed irods-dev 4.1.9
2016-08-09 15:38:59 upgrade irods-dev 4.1.9 4.1.9
2016-08-09 15:38:59 status half-configured irods-dev 4.1.9
[…]
2016-08-09 15:39:17 status installed irods-dev 4.1.9
2016-08-26 13:24:17 upgrade irods-dev 4.1.9 4.1.9
2016-08-26 13:24:17 status half-configured irods-dev 4.1.9

which represents three or four different packages, some of which worked and some of which did not.  Not very useful.

**Comment by kellerb** [comment]
You should be able to use `CPACK_DEBIAN_PACKAGE_VERSION` now. I have passed that value on through the development package (via `IRODSConfig.cmake`) so that the icommands will be built with the correct `requires`.
