### ISSUE TITLE
refactor irods shared libraries

### ISSUE THREAD

**Issue by kellerb** [irods/irods#3272]
- [x] remove cyclic dependencies

**Comment by jmarshall** [comment]
In #3006 third-party clients were told that they must call `init_client_api_table()`.  c611e6a2c422e6b60d224490b15c93692f4bc38c disappears that function.  What's up?

**Comment by kellerb** [comment]
Sorry, in my deletion fury I forgot about the c clients. I will add it back in a more conspicuous manor.

**Comment by kellerb** [comment]
`init_client_api_table()` should be back now.

**Comment by jmarshall** [comment]
Thanks.  However I took from discussions in #3205 that _libRodsAPIs.a_ was deprecated and I shouldn't be using it.  Moreover it fails to build when using it from a shared library / plugin:

```
$ gcc -shared -Wl,-E -pthread -L../../mhome/thirdparty/irods/lib -L../irods -o hfile_irods.so hfile_irods.o -lirods_client -lirods_plugin_dependencies -lirods_common -lRodsAPIs
/usr/bin/ld: ../irods/libRodsAPIs.a(irods_c_api.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
../irods/libRodsAPIs.a: error adding symbols: Bad value
```

Can an appropriate _irods_c_api.o_ be added to one of the client shared libraries too, please?  I believe it was previously in _libirods_plugin_dependencies.so_, though I don't know whether that particularly makes sense (cf #3228) and I guess this shared library refactoring is an opportunity to rearrange this…

**Comment by kellerb** [comment]
`init_client_api_table()` should now be in `libirods_client.so`.

**Comment by kellerb** [comment]
With regard to the "C API" and us accidentally breaking it all the time, could you give us a list of all the symbols you are using from the irods shared libraries?

There's a python script [here](https://github.com/kellerb/object_file_interdependencies/blob/master/object_file_interdependencies.py) that could be helpful for this. Use it like:

```
python object_file_interdependencies.py path/to/hfile_irods.so path/to/libirods_client.so path/to/libirods_common.so path/to/libirods_plugin_dependencies.so
```

It should print a json object to standard output that contains the symbol dependencies between the object files.

Once we have the symbols you need, we can create a `libirods_c_api.so` and a `irods_c_api.h` that should be the only shared library that you need to directly link against and the only header you need to include.

**Comment by jmarshall** [comment]
Source code for both [hfile_irods.c](https://github.com/samtools/htslib-plugins) and [baton](https://github.com/wtsi-npg/baton) is generally available should you wish to test compiling them yourselves from time to time.

The list of items that _hfile_irods.c_ is currently directly using is below; perhaps @keithj can comment on what baton currently uses.

```json
   "hfile_irods.so": {
        "../irods/libirods_client.so": [
            "clientLogin", "init_client_api_table", "rcConnect", 
            "rcDataObjClose", "rcDataObjLseek", "rcDataObjOpen", 
            "rcDataObjRead", "rcDataObjWrite", "rcDisconnect"
        ], 
        "../irods/libirods_common.so": [
            "addKeyVal", "getRodsEnv", "parseRodsPath", "rodsLogLevel"
        ]
    }
```

> Once we have the symbols you need, we can create a libirods_c_api.so and a irods_c_api.h that should be the only shared library that you need to directly link against and the only header you need to include.

This doesn't really sound very workable to me.  The functions above are just what _hfile_irods.c_ uses at the moment, and other clients doing other things will use different subsets.  It seems to me that e.g. _libirods_client.so_ and _rodsClient.h_ already play this library and header role for third-party clients.

**Comment by kellerb** [comment]
Thank you for running that script.

We would like to explicitly define the irods c api interface and to implement (and enforce) it through a library that contains and exports only those symbols described in the interface definition. That way it is clear to new developers of irods clients which irods functions they can use directly and to developers of irods internals which irods functions they can change.

`libirods_client.so` in its current form is unsuitable for this purpose because it contains and exports a tremendous number of irods functions, which makes the current de facto api too large to easily support.

Because there are many irods clients already in existence, the plan at this point is to take the "greatest hits" of irods client functions, plus those functions being used by known clients, and use them as the basis for the api. I should have been clearer on not basing the api interface only on those functions used by `hfile_irods.so`.

Thank you and please continue to give feedback on this. Half of the purpose of this proposed library is to ease the development and maintenance of irods clients.

**Comment by keithj** [comment]
`baton` at version 0.16.4 is using the following functions:
````
addKeyVal
clientLogin
getAttrNameFromAttrId
getRodsEnv
getRodsObjType
init_client_api_table
parseRodsPath
parseUserName
rcConnect
rcDataObjChksum
rcDataObjClose
rcDataObjOpen
rcDataObjRead
rcDisconnect
rcGenQuery
rcModAVUMetadata
rcModAccessControl
rcSpecificQuery
rclCloseCollection
rclOpenCollection
rclReadCollection
rodsErrorName
````

From browsing the header files over time I've observed a pattern of

````
/* prototype for the client call */
/* rcFoo */
int rcFoo();
````

I presumed that the `rc` is a mnemonic for "rods client" and that those are the functions that constitute the client API. It's clearly not universally true because (see above) there are other functions that are essential to get anything done.

If there are to be seismic changes in the API, please may we have a public deprecation strategy so that we know what to expect and can plan accordingly?

**Comment by trel** [comment]
This effort was handled from the server's perspective in 4.2.8 by https://github.com/irods/irods/issues/4768.
