### ISSUE TITLE
iput -K does not set iCAT checksum for 0 byte long files

### ISSUE THREAD

**Issue by carsten-jahn** [irods/irods#3275]
It's a bit strange that all files transmitted with `iput -K` receive a checksum unless they are 0 bytes long. iRODS does all kinds of operations with the 0 byte file. In a compound resource, it gets replicated to the archive leaf (although one could wonder why a 0 byte file ever makes it to a resource storage backend at all - tracking it in iCAT would be enough.) `ichksum -K` will add a checksum to a 0 byte file.

My assumption is that iput does not include the checksum in 0 byte file transfers. (Based on the assumption that iCAT initially stores the checksum received by the client, not calculated by iCAT itself.)

The point of having the checksum already transmitted with iput is to enable the server to verify that it actually gets a 0 byte file for real, not by accident (because of an error during a transfer).

**Comment by trel** [comment]
Agreed - all files should be treated equally - we cannot know all possible use cases for placeholder files.

There used to be many shortcuts taken with zero-length files (which would occasionally surprise users - and admins).  We will get this shortcut removed as well.

Thanks.
