### ISSUE TITLE
irodsReServer logging UNIX_FILE_STAT_ERR 

### ISSUE THREAD

**Issue by kript** [irods/irods#3286]
Post upgrade from 3.3.1 to 4.1.9, the reLog on some of our iCAT servers has this being logged a lot ~2k in 10 mins is not unusual;

```
ERROR: fillExecSubmitInp: stat error for rei file /usr
/local/iRODS/server/config/packedRei/rei.irods.167905643, id 152148 rule 
  msiServerMonPerf("default", "default");
  | status = -516002 UNIX_FILE_STAT_ERR, No such file or directory
Sep 15 12:14:16 pid:24951 ERROR: fillExecSubmitInp: stat error for rei file /usr/local/iRODS/server/config/packedRei/rei.irods.977775641, id 152149 rule
```

The rules we have defined are;
```
acSetRescSchemeForCreate {msiSetDefaultResc("root","forced"); }
acPostProcForPut {msiSysChksumDataObj; }
acAclPolicy{}
acTrashPolicy{  msiNoTrashCan; }
```

On a couple of the zones we also have `acRescQuotaPolicy {msiSetRescQuotaPolicy("on"); }` defined, but one zone has the errors, and the other does not.

This is filling the disk, but appears to have no other ill effects. As it can generate 8GB of logs in a week, we would like a workaround, but not necessarily a fix unless it has other implications.

**Comment by trel** [comment]
Please check to see that emptying / resetting anything in the delayed queue affects this behavior (using `iqstat`, `iqmod`, and `iqdel`).

**Comment by kript** [comment]
Yes, there appear to be a some 'stuck';

```
id: 382973
name: 
  msiServerMonPerf("default", "default");
  |
rei_file_path: ../config/packedRei/rei.irods.833733906
user_name: irods
address: 
time: 1470315233 : 2016-08-04.13:53:53
frequency: 10m
priority: 
estimated_exe_time: 
notification_addr: 
last_exe_time: 1470314633
exec_status: 
irods@irods-humgen-g1-vm:~$ iqstat -l | grep id | wc -l
63
irods@irods-humgen-g1-vm:~$ iqstat -l | grep msiServerMonPerf | wc -l
61

```
Are the stuck items indicative of another problem? Is it safe to clear them? er. What do they do?
I found https://docs.irods.org/master/doxygen/reIn2p3SysRule_8cpp.html#a1823d5206d4410feff126528f3c51efa which implies its server monitoring, although I didn't realize that was running by default.

The times are all over the place, including recently;

```
iqstat -l | grep time: | grep 2016
...
time: 1474018325 : 2016-09-16.10:32:05
time: 1474018325 : 2016-09-16.10:32:05
time: 1474018326 : 2016-09-16.10:32:06
time: 1470315213 : 2016-08-04.13:53:33
time: 1470315218 : 2016-08-04.13:53:38
```

**Comment by trel** [comment]
Ah, then in the past, this delayed microservice was fired and it was put into the queue.  Then, on upgrade or shutdown/restart, those packedRei files were moved/deleted/stranded.

I'm guessing that now the server is leaking due to not finding the packedRei file and exiting without freeing the memory (#3287).  Removing the bad queued job(s) I would assume would prevent hitting the memory leak.

I see no downsides to deleting (`iqdel`) the queued `msiServerMonPerf` jobs.

What are the two (63-61=2) that were not `msiServerMonPerf`?.

**Comment by kript** [comment]
```
irods@irods-humgen-g1-vm:~$  iqstat -l | grep -C 2 name | grep -v msiServerMonPerf | grep msi
    msiQuota;
    msiQuota;
```
deleting the delayed rules gave me;
```
irods@irods-humgen-g1-vm:~$ iqdel -a
Level 0: Rule was removed but unlink of rei file failed
Level 1: rei file: /usr/local/iRODS/server/config/packedRei/rei.irods.167905643
rcRuleExecDel failed with error -515002 UNIX_FILE_UNLINK_ERR No such file or directory
ERROR: qdelUtil: rmDelayedRule 152148 error. status = -515002
Level 0: Rule was removed but unlink of rei file failed
Level 1: rei file: /usr/local/iRODS/server/config/packedRei/rei.irods.977775641
rcRuleExecDel failed with error -515002 UNIX_FILE_UNLINK_ERR No such file or directory
```
but appears to have cleared things out;
```
iqstat -l 
No delayed rules pending for user irods
```
and the reFile is no logging throwing errors.

**Comment by trel** [comment]
Excellent - these were just leftovers.

I'm going to mark this as closed - please reopen if there is any action you think should be taken.

**Comment by bh9** [comment]
@kript and I are now seeing these `fillExecSubmitInp` error problems again, in a clean 4.1.10 install, a 4.1.10 install that was upgraded from 3.3.1 and 4.1.9, and a 4.1.12 upgraded from 4.1.8 via .9, .10 & .11. All of them seem to be msiQuota, with all 3 reporting each instance of the error 8 times a minute

**Comment by trel** [comment]
There is nothing in the `iqstat -l` AND you're seeing these errors?

**Comment by bh9** [comment]
I didn't check iqstat -l, but I would assume that it would be msiQuota; a large number of times. I'll check in the morning. The problem was that they aren't automatically cleaned up. The original assumption by @kript was that these errors were caused by an unsupported upgrade path. The fact that we still have them proves that they aren't, but instead being produced by the day to day actions of our iRODS servers. 
We can clear them up, but it would be better if they weren't produced in the first place

**Comment by bh9** [comment]
As predicted, 
```
iqstat -l | grep -C 2 name | grep msi
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
    msiQuota;
```

**Comment by trel** [comment]
Yes, and so each of those delayed rules has a 'RuleExecInfo' (or rei) file that is written down in `/usr/local/iRODS/server/config/packedRei/` that stores the context for the rule.  If you're seeing `UNIX_FILE_UNLINK_ERR` errors when the server wakes up and tries to stat those rei files, then something is happening to the rei files along the way.  Are they being moved around?  Are they being deleted by some other process?

Can you share the full output of one of the delay rules' information stored in the catalog?  You would use `iqstat -l nnnn` where `nnnn` is one of the ruleId values (`id:`).

And then also the `ls -l` of the rei file listed for that rule?

**Comment by bh9** [comment]
It's not UNLINKs we're getting, it's UNIX_FILE_STAT_ERR, No such file or directory

**Comment by trel** [comment]
Oh, right, sorry - I just copied the wrong error message from above when writing my reply.   Yes, the file is not there, so there is a `UNIX_FILE_STAT_ERR` error when the server tries to read it.

**Comment by bh9** [comment]
I found the files, they're in /usr/local/iRODS/server/config/packedRei 
Looks like they weren't moved when we upgraded from 3.x to 4.1, so the jobs started looking in a new place but the files stayed in the old one

**Comment by trel** [comment]
Ah, good find - explains the upgrade path problem.

You mentioned that this happened on a clean 4.1.10 install, too?

And I'm still curious about the relative path being stored in the catalog.

**Comment by bh9** [comment]
The clean install is an ies, which is reporting exactly the same missing files as the upgraded ies in the same zone, so I'm willing to believe this is due to issues with federation (though I don't know)
I also am still curious about the relative path, though don't even know where to start looking for the cause

**Comment by RubenGarcia** [comment]
Is there a way to permanently remove these rules so that they don't appear again after an irods restart?

**Comment by trel** [comment]
@RubenGarcia `iqdel` will remove queued jobs.  New jobs coming into the delay queue are due to users placing things in the delay queue or policy that is firing in your zone placing things in the delay queue.
