### ISSUE TITLE
irodsReServer logging waitAndFreeReThr and not releasing memory

### ISSUE THREAD

**Issue by kript** [irods/irods#3287]
Our monitoring systems notified us that one of our 4.1.9 iCAT had creeping memory utilization/leak;

![screenshot-cutdown](https://cloud.githubusercontent.com/assets/958908/18552097/00bcbc20-7b53-11e6-8cb6-41a178cefded.png)

and in the logs we found

```
Sep 10 05:29:07 pid:1954 NOTICE: reServerMain: checking the queue for jobs
Sep 10 05:29:08 pid:1954 NOTICE: waitAndFreeReThr: no outstanding child. but runCnt=1
Sep 10 05:29:08 pid:1954 NOTICE: getNextQueuedRuleExec: reId 55589 in RUNNING state. Run again
Sep 10 05:29:08 pid:1954 NOTICE: waitAndFreeReThr: no outstanding child. but runCnt=1
```

This might be related to #3286 as the problem occurred on one of the systems affected by that issue - or that might be a red herring.
The time correlated with a user session, but that was from a different monitoring session that checks connections every minute, and had been doing so since before the upgrade, so its unlikely to have caused it via a problematic command.

Once the server was restarted the memory use went back to normal and the issues hasn't reoccured.

**Comment by lstillwe** [comment]
This has occurred in the DFC environment as well.

**Comment by trel** [comment]
@lstillwe, also on 4.1.9, right?

**Comment by lstillwe** [comment]
Have not attempted to run delayed execution rules since I have upgraded to 4.1.9 - so not sure.
[RENCI]<http://www.renci.org>

Lisa Stillwell
Research Software Developer/GIS Specialist



On Sep 15, 2016, at 3:52 PM, Terrell Russell <notifications@github.com<mailto:notifications@github.com>> wrote:


@lstillwe<https://github.com/lstillwe>, also on 4.1.9, right?

**Comment by trel** [comment]
This was resolved by removing old/stale recurring rules in the delayed queue #3286.

However, perhaps the leak can still be prevented, even if the packedRei is not available?
A `free()` before returning/exiting?

**Comment by trel** [comment]
Pretty sure this is now fixed / addressed.

@alanking please confirm we're not leaking.

**Comment by alanking** [comment]
The delayed execution server was rewritten in 4.2.5 (see https://github.com/irods/irods/commit/5dfb85ada91f35529b8491df9a58df308eaf1558 for initial implementation). None of the code above exists anymore and memory profiling detects no leaks at this time.

**Comment by trel** [comment]
Awesome - closing.   Thanks.
