### ISSUE TITLE
ibun -x fails with .tar of certain size

### ISSUE THREAD

**Issue by trel** [irods/irods#3291]
Confirming https://groups.google.com/forum/#!topic/iROD-Chat/XugffHs3ZIY:

With iRODS 4.1.9 on Ubuntu14, using `test_ibun_x.sh`:

``` bash
#!/bin/bash
filesizemb=3
for c in $(seq 7508 1 7509); do
    echo "STARTING ${c}..."
    mkdir exp${c}
    cd exp${c}
    for i in $(seq ${c}); do truncate -s${filesizemb}M file${i}; done
    cd ..
    echo "  ${c}... tar -chlf"
    tar -chlf exp${c}.tar exp${c}/
    echo "  ${c}... iput -Dtar"
    iput -Dtar exp${c}.tar
    ils -l
    echo "  ${c}... ibun -x"
    ibun -x exp${c}.tar exp${c}i
    echo "  ${c}... ils | wc"
    ils exp${c}i/exp${c} | wc -l
    echo "  ${c}... rm and irm"
    rm -rf exp${c}*
    irm -rf exp${c}.tar exp${c}i
    echo "  ${c}... COMPLETE"
done
```

   937 24MiB files (tar file size 23580866560) ... works
   938 24MiB files (tar file size 23606026240) ... works
   939 24MiB files (tar file size 23631196160) ... ibun -x fails silently
   940 24MiB files (tar file size 23656366080) ... ibun -x fails silently

   1875 12MiB files (tar file size 23593922560) ... works
   1876 12MiB files (tar file size 23606507520) ... works
   1877 12MiB files (tar file size 23619092480) ... works
   1878 12MiB files (tar file size 23631677440) ... ibun -x fails silently
   1879 12MiB files (tar file size 23644262400) ... ibun -x fails silently
   1880 12MiB files (tar file size 23656847360) ... ibun -x fails silently

   7508 3MiB files (tar file size 23621980160) ... works
   7509 3MiB files (tar file size 23625123840) ... ibun -x fails silently

   22516 1MiB files (tar file size 23621273600) ... works
   22517 1MiB files (tar file size 23622318080) ... works
   22518 1MiB files (tar file size 23623372800) ... ibun -x fails silently

**Comment by trel** [comment]
From [Patrick](https://groups.google.com/d/msg/iROD-Chat/XugffHs3ZIY/fgdupbu0AgAJ):

> In addition I did a test with the same files on a iRODS area with iCAT server Oracle: the ibun command works fine.
> 
> My initial failure is on a iRODS area with iCAT server postgresql.
>

**Comment by tedgin** [comment]
I'm using postgresql version 9.3 with iRODS 4.1.10, and I see a similar problem.  I have four test cases.

1)  64GiB tar file containing 66,957 directories and 1,303,792 files.  `ibun -x` fails silently.
2)  64GiB tar file containing 0 directories and 1 file. `ibun -x` works.
3)  1.3GiB tar file containing 0 directories and 1,303,792 files. `ibun -x` works.
4)  1.3GiB tar file containing 66,957 directores and 1,303,792 files. `ibun -x` works.

There is definitely a size component, but the failure is not exclusively due to size.

**Comment by trel** [comment]
Is this just related to the amount of free memory on the server?

**Comment by tedgin** [comment]
I don't think it's related to system memory.  In the case I mentioned about, the resource server where the tar file resided has 256 GB of total memory with around 5 - 7 GB typically in use.  The IES has 128 GB of total memory with around 20 - 30 GB typically in use.

**Comment by trel** [comment]
Moving back to 4.2.x for RENCI.   HydroShare project has hit this behavior.

**Comment by trel** [comment]
@nief at CC-IN2P3 has now hit this in testing 4-2-stable.

> It works fine for 22 MB archive (350 files). But going for example for 3.9 GB file, it fails. Error code is 0 on the client side and on the server side there are no errors being registered.

**Comment by trel** [comment]
candidate fix is to upgrade libarchive.   working through CI now.
