### ISSUE TITLE
irule support for multiple rule engine plugins (languages)

### ISSUE THREAD

**Issue by trel** [irods/irods#3296]
Consider new `irule` options:
- `-a, --available` - list available rule engine plugin instances on the server to which `irule` is connecting (to be used with `-r`)
- `-r, --rule-engine-plugin-instance` - use specified rule engine plugin instance to execute rulefile text (default: irods-rule-language-instance)

This is deterministic (no confusion as to which plugin instance is being used), discoverable (new users can learn what they *can* use), and allows regular users to learn/text/execute their own policies without having access to the admin-only rulebases on the server(s).

If a rule is sent to a different server (via remote()), then if that other server does not have a compatible rule engine plugin instance, a syntax error will be returned.

Additional motivation is to not have to ship a `default_rule_engine_instance` in the `server_config.json` which is confusing and a (yet another) zone-wide setting.

**Comment by rskarbez** [comment]
Default is not irods-rule-language-instance, it is whichever instance comes first in the rule_plugins stanza in server_config.json.
