### ISSUE TITLE
rei.rods.xxxxxx file pile-up

### ISSUE THREAD

**Issue by burnce** [irods/irods#3302]
Hello,

We have hit an issue in iRODS 4.1.7. While running a large number of remote exec rules, we have run out of inodes on the icat server. looking into where these inodes are being used, we discovered over a million files in `/var/lib/irods/iRODS/server/config/packedRei/`. Also, `iqstat` appears to show a similar number of entries for remote execution rules.

1. Why is this pile-up occurring? The rules appear to have finished executing.
1. Is there a way to clear the pile-up more efficiently?
1. The number of rei files / iqstat entries appears to be considerably larger than the number of rules being executed. Is this normal?
1. Is there a way to throttle things such that this pile-up does not occur?

Thanks,

Bernhard

**Comment by trel** [comment]
If they appear to be complete - you should be able to 'iqdel' them.

This sounds very similar to https://github.com/irods/irods/issues/3286 and https://github.com/irods/irods/issues/3287. I think there is a bug in the process of upgrading/shuttingdown/restarting that is not handling existing queued rules cleanly.

**Comment by burnce** [comment]
Hi trel,

Sorry for the delay in getting back. I have found the issue and cleaned up the backlog. The rules were due to a delayed, remote execution in our access policy setter which was suboptimal in the number of times it was triggered. I am rearranging it to improve this.

It was not a bug in iRODS itself after all.

Thanks,

Bernhard

**Comment by trel** [comment]
Ah, excellent.   The best of news.
