### ISSUE TITLE
msiCheckAccess not honoring ownership of collection via group

### ISSUE THREAD

**Issue by trel** [irods/irods#3309]
- [x] master
- [x] 4-2-stable
-------

From @arthurguerra on https://groups.google.com/forum/#!topic/iROD-Chat/uPbA2aGjsvU:

> I'm trying to check via rules whether or not a particular user has ownership permission on a particular collection. 
> 
> In order to do that, I'm using the msiCheckAccess microservice. 
> 
> It works fine in most cases, except when users have permissions on collections through groups. For example,
> 
> ```
> myTestRule {
>      msiCheckAccess(/path/to/your/collection, "own", *result);
> 
>      if (*result == 0) {
>           writeLine("serverLog", "The current user DOES NOT have OWN permission on /path/to/your/collection");
>      }
> }
> ```
> 
> A user U has ownership permission on a collection C via group G, *result is 0, meaning that user DOES NOT have ownership permission on that collection. It should figure out the group G owns C and the user U is part of G, then U is also an owner of C.
> 
> I was wondering if the msiCheckAccess microservice checks permissions through groups or only permission granted directly to the user?

**Comment by JustinKyleJames** [comment]
Closed after passing tests on master and 4-2-stable.

**Comment by trel** [comment]
skipped - closing.
