### ISSUE TITLE
feature request: ichksum a resource

### ISSUE THREAD

**Issue by kript** [irods/irods#3317]
Hi folks,

It would be nice to be able to point ichksum et al at a resource for it to verify each object in that resource; at present we can only target a file, and its not easy to target ichksum at a specific replica without determining that ahead, which is several queries that don't easily interlink.

cheers

John

**Comment by kript** [comment]
edit to remove ifsck, since you can do this by pointing at the directory.

**Comment by rskarbez** [comment]
Is it not already possible to run ichksum pointing it at a directory? Or is this not sufficient for your use case? Apologies if I've misunderstood.

-rick

```
$ imkdir testColl
$ ils
/tempZone/home/rods:
  C- /tempZone/home/rods/testColl
$ icd testColl
$ iput -K foo 
$ iput -K emptyfile.txt 
$ ils -L
/tempZone/home/rods/testColl:
  rods              0 demoResc            0 2016-11-21.08:13 & emptyfile.txt
    sha2:47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=    generic    /home/rskarbez/irods-debug/var/lib/irods/Vault/home/rods/testColl/emptyfile.txt
  rods              0 demoResc          224 2016-11-21.08:13 & foo
    sha2:bVtizKfxYWJPTUfIFT9iNMFpbampOGkzVLjlT0ijOZA=    generic    /home/rskarbez/irods-debug/var/lib/irods/Vault/home/rods/testColl/foo
$ icd ..
$ ils
/tempZone/home/rods:
  C- /tempZone/home/rods/testColl
$ ichksum testColl
C- /tempZone/home/rods/testColl:
    emptyfile.txt                     sha2:47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=
    foo                               sha2:bVtizKfxYWJPTUfIFT9iNMFpbampOGkzVLjlT0ijOZA=
Total checksum performed = 2, Failed checksum = 0
```

**Comment by kript** [comment]
Sorry for taking so long to respond, just hit the issue again which reminded me I needed to..

I mean a directory as in a filesystem path, in the example above you're using a collection.
My use case is that I want to run a command against the top level file system directory of a resource, and have it validate each object is both present on disk and has the appropriate checksum.

iscan checks a physical directory, but not the checksum of same, AFAIK

**Comment by trel** [comment]
I think `ifsck -K` does what you are requesting.

**Comment by kript** [comment]
it does, thanks, which gives me a workaround for now, but it would be easier to be able to point the tool at a resource and ask it to verify everything, without having to go through the intermediate step of constructing and feeding it the list. That functionality would also be helpful for us to have fire off in a cron job every now and then to 'scrub' the data and ensure there has been no silent data corruption and the like, well before a user actually requests the file (since we can't rely on them using the -K flag as they may be streaming).

**Comment by trel** [comment]
Apologies - I'm still confused.

1. To recursively scan a physical path, with checksums:
    `ifsck -r -K <local_physical_path>`

2. To recursively scan a logical path on a particular resource:
    `ichksum -r -R <resource> <logical_path>`

Can you show me what your proposed command would look like?

**Comment by trel** [comment]
So, that already exists... have you tried it?

**Comment by trel** [comment]
@kript can we close this?

**Comment by kript** [comment]
Sorry for missing the update.. perhaps a better example would be;

`ichksum -R <root;replicate;seq-red;red3;irods-seq-i16-bc`

as `ichksum -R root` would take too long. Have I misunderstood?

**Comment by trel** [comment]
Right - so a full hierarchy does not currently get parsed in that way.

Can you try targeting a non-root resource with `ichksum -R`?

So... `ichksum -R red3` ?

**Comment by kript** [comment]
Didn't work for me on 4.1.10;

```
irods-g1-dev@irods-g1-dev:~$ iadmin lr irods-seq-i16-bc
resc_id: 12417
resc_name: irods-seq-i16-bc
zone_name: seq-dev
resc_type_name: unixfilesystem
resc_net: irods-r2-dev
resc_def_path: /irods-seq-i16-bc
free_space: 560541696
free_space_ts 2016-11-11.11:41:46
resc_info: 
r_comment: 
resc_status: up
create_ts 2016-06-14.11:49:05
modify_ts 2017-01-31.10:19:18
resc_children: 
resc_context: minimum_free_space_for_create_in_bytes=620294963
resc_parent: red3
resc_objcount: 4
irods-g1-dev@irods-g1-dev:~$ ichksum -R irods-seq-i16-bc
ERROR: ichksum: no input
Use -h for help.
```

**Comment by trel** [comment]
Sorry, please give it a target 'logical_path'?

**Comment by kript** [comment]
I may have misunderstood;
```
irods-g1-dev@irods-g1-dev:~$ ichksum -R 'root;replicate;red;red3;irods-seq-i16-bc'
ERROR: ichksum: no input
Use -h for help.
```

**Comment by kript** [comment]
misunderstanding differently;
```
irods-r2-dev@irods-r2-dev:~$ ichksum -R /irods-seq-i16-bc
ERROR: ichksum: no input
Use -h for help.
```

**Comment by trel** [comment]
The error message is saying you're missing a logical path of the dataObj or Collection you're trying to checksum.

It is not saying that very well :)

**Comment by kript** [comment]
Understanding dawns 🌤 So we would need to know a collection path *and* limit it to the resource we want to check?

Oooh;
```
irods-r2-dev@irods-r2-dev:~$ ichksum -R irods-seq-i16-bc /seq-dev
C- /seq-dev:
C- /seq-dev/home:
...
Total checksum performed = 0, Failed checksum = 0
...
If I understand the `iadmin lr` output above, then that should have checked 4 objects, but no results. I tried it on another couple of resources that I knew had files, same thing;

```
irods-r2-dev@irods-r2-dev:~$ ils -L /seq-dev/home/jc18#Sanger1-dev/jc18_test_today
  jc18              0 root;replicate;red;red1;irods-seq-i04-fg      1048576 2016-08-23.16:25 & jc18_test_today
    b6d81b360a5672d80c27430f39153e2c    generic    /irods-seq-i04-fg/home/jc18#Sanger1-dev/jc18_test_today
  jc18              1 root;replicate;green;green9;irods-seq-sr03-ddn-gg07-57-58-59      1048576 2016-08-23.16:25 & jc18_test_today
    b6d81b360a5672d80c27430f39153e2c    generic    /irods-seq-sr03-ddn-gg07-57-58-59/home/jc18#Sanger1-dev/jc18_test_today

ichksum -R irods-seq-i04-fg /seq-dev
...
Total checksum performed = 0, Failed checksum = 0
```
I may however, be holding it wrong (again)..

**Comment by trel** [comment]
Remember that, without `-f`, `ichksum` doesn't calculate anything new if the results are already available in the catalog.  Does that explain what you're seeing?

**Comment by trel** [comment]
@kript any update?   can we close this?

**Comment by kript** [comment]
Sorry, I thought I had! Let me check tomorrow.

**Comment by kript** [comment]
It doesn't appear to actually run any checks even with `-f`;
```
ichksum -f -R irods-seq-i04-fg /seq-dev
...
Total checksum performed = 0, Failed checksum = 0
irods-r2-dev@irods-r2-dev:~$ ils -L /seq-dev/home/jc18#Sanger1-dev/jc18_test_today
  jc18              0 root;replicate;red;red1;irods-seq-i04-fg      1048576 2016-08-23.16:25 & jc18_test_today
    b6d81b360a5672d80c27430f39153e2c    generic    /irods-seq-i04-fg/home/jc18#Sanger1-dev/jc18_test_today
  jc18              1 root;replicate;green;green9;irods-seq-sr03-ddn-gg07-57-58-59      1048576 2016-08-23.16:25 & jc18_test_today
    b6d81b360a5672d80c27430f39153e2c    generic    /irods-seq-sr03-ddn-gg07-57-58-59/home/jc18#Sanger1-dev/jc18_test_today
```

**Comment by trel** [comment]
I'm wondering if the stdout is true (reporting `Total checksum performed = 0`).

Can you run a test on a data object that has a bad checksum in the catalog, first to just report the bad one, then recalculate and return the new one?

Running `ichksum` should return the bad checksum from the catalog.

Running `ichksum -f` should calculate, save, and return the new checksum.

**Comment by kript** [comment]
Sorry for the delay, I wonder if this might explain something (or just spread more FUD ;-) );
```
irods-g1-dev@irods-g1-dev:~$ ichksum /seq-dev/home/jc18#Sanger1-dev/jc18_test_today
ERROR: chksumDataObjUtil: rcDataObjChksum error for /seq-dev/home/jc18#Sanger1-dev/jc18_test_today status = -818000 CAT_NO_ACCESS_PERMISSION
ERROR: chksumUtil: chksum error for /seq-dev/home/jc18#Sanger1-dev/jc18_test_today, status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
Total checksum performed = 1, Failed checksum = 1
irods-g1-dev@irods-g1-dev:~$ ils -A !$
ils -A /seq-dev/home/jc18#Sanger1-dev/jc18_test_today
  /seq-dev/home/jc18#Sanger1-dev/jc18_test_today
        ACL - jc18#Sanger1-dev:own   
irods-g1-dev@irods-g1-dev:~$ iuserinfo irods-g1-dev
name: irods-g1-dev
id: 10007
type: rodsadmin
zone: seq-dev
info: 
comment: 
create time: 01394547709: 2014-03-11.14:21:49
modify time: 01395067464: 2014-03-17.14:44:24
member of group: irods-g1-dev
member of group: public
```
I would have assumed that ichksum had admin rights when run as a rods admin account, so wouldn't get permission issues? Same issue as #3503 ?

**Comment by trel** [comment]
I believe that error/limitation is the same as https://github.com/irods/irods/issues/3265, rather.

I think this issue can be closed, we can checksum a resource.
