### ISSUE TITLE
Log message on *.re change incorrect

### ISSUE THREAD

**Issue by burnce** [irods/irods#3318]
Hello,

I just noticed the following message in my `reLog` (on v4.1.7)

```
Oct  5 15:42:13 pid:16436 NOTICE: chkAndResetRule: reconf file /etc/irods/core.re has been changed. re-initializing`
```

However, I changed a custom `*.re` rather than `core.re`.

Cheers,

Bernhard

**Comment by trel** [comment]
Is your custom `*.re` included using @ notation in `core.re`... or is `*.re` specified completely separately in your `server_config.json`?

**Comment by burnce** [comment]
I am using the `/etc/irods/server_config.json`

````
    "re_rulebase_set": [
        {
            "filename": "custom"
        },
        {
            "filename": "core"
        }
    ],
````

````
$ grep -c '@' /etc/irods/core.re
0
````

**Comment by xu-hao** [comment]
Reserver refactoring in 4.2 has already removed this bug.

**Comment by trel** [comment]
ah, very good - closing...
