### ISSUE TITLE
iCommands default to MD5 hash

### ISSUE THREAD

**Issue by kellerb** [irods/irods#3321]
`server_config.json` defaults to `SHA256`
service account environment file defaults to `SHA256`
[documentation alleges](https://docs.irods.org/4.1.8/manual/configuration/) default for 4.0+ is `SHA256`. 

From [iRODS Chat](https://groups.google.com/d/msg/irod-chat/CeFlOJkkS-c/I-eBfgJUAQAJ)

https://github.com/irods/irods/blob/c765f375daa6e4debb65217e8467d7837e7555bb/lib/hasher/src/checksum.cpp#L44-L48

**Comment by trel** [comment]
Switch unset default to use `SHA256`.
