### ISSUE TITLE
signalExit/cleanupAndExit should not contain rodsLog calls

### ISSUE THREAD

**Issue by rskarbez** [irods/irods#3326]
Since a signal can interrupt execution of the program at any arbitrary point, it is unsafe to call rodsLog inside a signal handler.

**Comment by rskarbez** [comment]
Such statements were `#if 0`'ed out on:
`server/core/src/initServer.cpp:573` in `cleanupAndExit()`
`server/core/src/initServer.cpp:591` in `signalExit()`
`server/core/src/irods_signal.cpp:17` in `segv_handler()`
`server/core/src/rodsServer.cpp:601` in `serverExit()`

Want to change these `#if 0`s to `#ifdef DEBUG_MODE` when we are able to add such a flag to the CMake build process.

**Comment by trel** [comment]
Want to reopen and bump?  Rather than close?

**Comment by rskarbez** [comment]
Such statements were also `#if 0'ed` out on:
`server/core/src/irodsReServer.cpp:41` in `cleanupAndExit()`
`server/core/src/irodsReServer.cpp:56` in `signalExit()`

**Comment by korydraughn** [comment]
All calls to `rodsLog()` have been removed from the signal handlers.
