### ISSUE TITLE
"Error encountered in graceful shutdown" with iRODS 4.2 rodsServer/rodsAgent

### ISSUE THREAD

**Issue by rskarbez** [irods/irods#3333]

**Comment by rskarbez** [comment]
This seems to be fixed for any combination of the irods_rule_language and cpp_default_policy rule engines.

When adding the python RE as a third rule engine, though, the issue seems to reappear.

**Comment by trel** [comment]
Please close if we think this is no longer a problem.

**Comment by alanking** [comment]
I haven't been able to reproduce this, so I will close this.
