### ISSUE TITLE
mkresc unixfilesystem type not showing in ilsresc

### ISSUE THREAD

**Issue by tedgin** [irods/irods#3345]
When I create a new resource, `ilsresc` doesn't show the type.

```
prompt> iadmin mkresc newRes 'unix file system' irods-2.cyverse.org:/var/lib/irods/Vault2
Creating resource:
Name:       "newRes"
Type:       "unix file system"
Host:       "irods-2.cyverse.org"
Path:       "/var/lib/irods/Vault2"
Context:    ""

prompt> ilsresc
demoResc:unix file system
newRes
```

If I change the type of the resource to the same type, `ilsresc` will show the correct type.

```
prompt> iadmin modresc newRes type 'unix file system'                                                                                      
prompt> ilsresc
demoResc:unix file system
newRes:unix file system
```

If I create the resource as type `unixfilesystem` instead, nearly the same thing happens.  The only difference is that  after the `iadmin modresc newRes type unixfilesystem`, `ilsresc` still doesn't show the type.

**Comment by trel** [comment]
The `modresc` is apparently not going through the same codepath.  On `mkresc`, we are removing the spaces and saving the type in the catalog as `unixfilesystem`.

We should make the `modresc` consistent.

Separately, we should consider always displaying the resource type with `ilsresc`.
