### ISSUE TITLE
itrim does not remove the requested replica 

### ISSUE THREAD

**Issue by danielhanlon** [irods/irods#3346]
- [x] master
- [x] 4-2-stable
- [x] itrim help text, master
- [x] itrim help text, 4-2-stable
---------------

**Infrastructure:**

iRODS 4.1.8
ilsresc
wos:compound
├── wosArchive:wos
└── wosCache
wosArchive has a high level of resiliency, cache does not.

**Use case:**
1. Compound resource with a copy of a file existing in archive with checksum.
2. User uploads a new copy of the /same/ file - goes to cache resource
3. Admin can see that the checksums are identical and wants to trim the cache copy

**Problem:**

Cache copy has newer date stamp so the trim is ignored by itrim (and msiDataObjTrim)

**Effect:**

Archive copy has to be trimmed first to remove cache copy, therefore losing the already established resilience of the archive resource.

**Example:**

$ sha256sum ./test.txt | xxd -r -p | base64
GJShnIW6FTrL90OsTkP8AEyJFgSyb4xp4eg+oq/HxI8=

$ iput test.txt

_acPostProcForPut triggered -> msiDataObjChksum + msisync_to_archive + msiDataObjTrim_

$ ils -L test.txt
  irods             1 wos;wosArchive           12 2016-10-29.09:48 & test.txt
    sha2:GJShnIW6FTrL90OsTkP8AEyJFgSyb4xp4eg+oq/HxI8=    generic    NBMbBsOEA16iaCAGFhbz8b8dXE91kGBFF9afGznM

_user uploads the same file again - CLI shown here but normally done via Cyberduck etc)_

$ iput -f test.txt
$ ils -L test.txt
  irods             1 wos;wosArchive           12 2016-10-29.09:48   test.txt
    sha2:GJShnIW6FTrL90OsTkP8AEyJFgSyb4xp4eg+oq/HxI8=    generic    NBMbBsOEA16iaCAGFhbz8b8dXE91kGBFF9afGznM
  irods             2 wos;wosCache           12 2016-10-29.09:51 & test.txt
    sha2:GJShnIW6FTrL90OsTkP8AEyJFgSyb4xp4eg+oq/HxI8=    generic    /var/lib/irods/iRODS/wosCache/live/rd0000/djn/test.txt

_identical file uploads so acPostProcForPut attempts to trim cache file, CLI equivalent shown here_

$ itrim -N1 -n2 test.txt
$ ils -L test.txt
  irods             1 wos;wosArchive           12 2016-10-29.09:48   test.txt
    sha2:GJShnIW6FTrL90OsTkP8AEyJFgSyb4xp4eg+oq/HxI8=    generic    NBMbBsOEA16iaCAGFhbz8b8dXE91kGBFF9afGznM
  irods             2 wos;wosCache           12 2016-10-29.09:51 & test.txt
    sha2:GJShnIW6FTrL90OsTkP8AEyJFgSyb4xp4eg+oq/HxI8=    generic    /var/lib/irods/iRODS/wosCache/live/rd0000/djn/test.txt

_i.e. not trimmed. Only way to remove cache copy is to trim archive copy and re-sync..._

$ itrim -N1 test.txt
$ ils -L
/rdZone/live/rd0000/djn:
  irods             2 wos;wosCache           12 2016-10-29.09:51 & test.txt
    sha2:GJShnIW6FTrL90OsTkP8AEyJFgSyb4xp4eg+oq/HxI8=    generic    /var/lib/irods/iRODS/wosCache/live/rd0000/djn/test.txt

_background async rule needed to spot cache copy and sync to archive..._

**Comment by trel** [comment]
In discussing this, a general tool that might be applicable would be a new `itouch` command.

It would duplicate the functionality of some or all of the [unix `touch` command](https://en.wikipedia.org/wiki/Touch_(Unix)#Usage).

Does that sound like a reasonable solution?  Any shortcomings to that approach?

**Comment by trel** [comment]
Agreed though, `itrim` silently ignoring the lowercase n when it is specified is a bug.

**Comment by danielhanlon** [comment]
Agree with both comments above. I think an itouch command would have more general use too...
