### ISSUE TITLE
Microservice msiStrArray2String broken

### ISSUE THREAD

**Issue by tedgin** [irods/irods#3355]
The microservice `msiStrArray2String` messes up the first term in the list.  Here's an example.

```
prompt> cat test-msiStrArray2String.r
test {
  *props=list("one", "two");
  msiStrArray2String(*props, *kvStr);
  writeLine('stdout', *kvStr);
}
INPUT null
OUTPUT ruleExecOut

prompt> irule -F test-msiStrArray2String.r null null
onetwo%two
```

**Comment by rskarbez** [comment]
What version of irods are you using when this occurs? I was unable to produce the issue with your test code running the most recent github build.

**Comment by tedgin** [comment]
I was running version 4.1.9.  

Cool!  I'm guessing the list() microservice fix, #3304, also fixed this one.

**Comment by trel** [comment]
Probably so - please try 4.1.10 yourself and confirm - and we'll close this.  Thanks.

**Comment by tedgin** [comment]
Just go ahead and close it if you can't reproduce it.  It's going to be a few weeks before I can play with 4.1.10.

**Comment by trel** [comment]
Got it - thanks.
