### ISSUE TITLE
irodsFs really slow for file listing operations

### ISSUE THREAD

**Issue by tedgin** [irods/irods#3363]
In iRODS 4.1.9, a FUSE mount made through irodsFs has really poor performance for file listting operations.  This used to not be the case in iRODS 3.3.1.

Listing the contents of one irodsFs 4.1.9 mounted collection takes about 100 seconds while listing the contents of the same collection mounted with irodsFs 3.3.1 takes about 0.4 seconds.

**Comment by trel** [comment]
From @iychoi 

> The significant performance drop is due to two reasons.
> 
> 1. No metadata cache. 
> In iRODS3 FUSE, metadata is cached locally. However, it caused data inconsistency and deadlocks thus it is removed in irods4 fuse. Reimplementing the metadata cache layer is needed.
> 
> 2. Mysql db driver support.
> During the development of iRODS4 FUSE, I found Mysql driver and Postgresql driver behave differently for transactions. Mysql driver does not guarantee data consistency when multi-transactions are made via multiple network connections. To solve this issue, I forced the iRODS4 FUSE to use a new network connection when Mysql is used. Establishing a new network connection at every metadata operation is problematic. If a client will work only with iCAT servers that are configured with the postgresql driver, you can make the iRODS4 FUSE reuse network connections for metadata operations.

**Comment by iychoi** [comment]
This is fixed in the following commit.

https://github.com/irods/irods_client_fuse/commit/25619a7ff6bf43306a7f6a6b28650eec60f4686b
