### ISSUE TITLE
segmentation fault - iCommands CentOS RPM packages

### ISSUE THREAD

**Issue by carrgilson** [irods/irods#3374]
The binaries within versions 4.1.9 and 4.1.10 of the CentOS 7 RPM packages cause a segmentation fault when executed.

I'm still relying on the version 4.1.8 where the package installed and the binaries are stable.

**Comment by trel** [comment]
This is curious.   We have all these binaries running in Continuous Integration.

Can you share any debugging/log information you see when this happens?   Are the plugins up to date as well?

**Comment by trel** [comment]
@carrgilson Is this still the case?  Can we close this?

**Comment by trel** [comment]
Closing - please open another issue if this is still the case.
