### ISSUE TITLE
cross federation error report not showing same error

### ISSUE THREAD

**Issue by kript** [irods/irods#3381]
Upgrading to 4.1.10 on our dev systems, I did a test put of a 2G file into my user home collection on a federated Zone. I mistakenly used the wrong user/zone and I got an error message that was' reflective of the underlying error;

From the `iput` I got;

```
ERROR: putUtil: put error for /archive-dev/home/jc18#Sanger1, status = -24000 status = -24000 SYS_INTERNAL_NULL_INPUT_ERR
```
and on the Federated Zone's iCAT, the logged error was;
```
Nov 11 12:00:47 pid:917 ERROR: [-]      iRODS/server/api/src/rsAuthResponse.cpp:74:rsAuthResponse :  status [CAT_INVALID_USER]  errno [] -- message []
        [-]     libnative.cpp:394:native_auth_agent_response :  status [CAT_INVALID_USER]  errno [] -- message [rcAuthCheck failed.]
```
I would be helpful when errors are given in a federated zone that they are reported upstream.

Cheers

John

**Comment by trel** [comment]
Good report - agreed errors should propagate back.  If we can get it back over the federation connection, we will.

Thanks.

**Comment by trel** [comment]
Needs testing on 4.2.x.

**Comment by alanking** [comment]
Using two 4.2.11 zones...

In `tempZone`:
```bash
$ iadmin lu
rods#tempZone
rods#otherZone
constable#otherZone
```

In `otherZone`, as user local user `constable` connected to the local zone's catalog service provider on localhost:
```bash
$ ls -l big
-rw-r--r-- 1 root root 524288000 Mar 21 17:49 big
$ iput big /tempZone/home/constable#otherZone/foo
$ ils -l /tempZone/home/constable#otherZone/foo
  constable         0 demoResc    524288000 2022-03-21.17:50 & foo
$ iput big /tempZone/home/constable#nope/foo
remote addresses: 127.0.0.1 ERROR: putUtil: put error for /tempZone/home/constable#nope/foo, status = -814000 status = -814000 CAT_UNKNOWN_COLLECTION
$ iput big /tempZone/home/rods/foo
remote addresses: 127.0.0.1 ERROR: putUtil: put error for /tempZone/home/rods/foo, status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
```

All of these error messages make sense and align with what's in the rodsLog on the remote zone's server. Is there something else I need to try here?

**Comment by trel** [comment]
This looks pretty good to me.

If so, let's link some relevant issues/fixes that have already been merged, and call it 'done'.

@kript ?

**Comment by alanking** [comment]
Great, thanks!
