### ISSUE TITLE
ireg silence failure in registrations of files

### ISSUE THREAD

**Issue by tomla1963** [irods/irods#3392]
`ireg` seems to silence fail to notificat the user when ireg fail to registrate files.

If you try to registrate files with ireg that has no name in the /etc/pasword files only a UID on the resource server, it silence fail.

So there are two problems.
1. ireg will fail if the user don't exist in /etc/passwd on the resource server.
2. ireg is silence of the error from fail ireg (1.)
 
Regards
tom

**Comment by trel** [comment]
What is the smallest/simplest set of conditions that will help us reproduce this error?

Requiring a UID on the server doing the registration is part of the policy in `core.re` - I think that part is working as expected.

**Comment by trel** [comment]
What version of iRODS is this?

**Comment by trel** [comment]
Closing - not sure what can be done for this.
