### ISSUE TITLE
irods 4.2.0 tarball contains nothing into irods_schema_messaging subfolder

### ISSUE THREAD

**Issue by bzizou** [irods/irods#3394]
So, it's impossible to build from the tarball...

**Comment by kellerb** [comment]
The download option from github does not include the content of git submodules. I'm not sure if there is a way to work around this outside of no longer using submodules.

**Comment by bzizou** [comment]
Could you then create a custom tarball and put it somewhere outside of github?

**Comment by trel** [comment]
I have updated the release for 4.2.0 - it now has irods-4.2.0.tar.gz
 - https://github.com/irods/irods/releases/tag/4.2.0

This tarball was generated from a generic script that can provide a tarball of any git super-project (including submodules):
 - https://github.com/irods/contrib/blob/master/generate_targz_with_submodules.sh

You can run it yourself:
```
wget --no-check-certificate https://raw.githubusercontent.com/irods/contrib/master/generate_targz_with_submodules.sh
bash generate_targz_with_submodules.sh 4.2.0
```

**Comment by bzizou** [comment]
Great! Thanks, and see you soon!
