### ISSUE TITLE
Set RUNPATH instead of RPATH

### ISSUE THREAD

**Issue by kellerb** [irods/irods#3397]
- [ ] main
- [ ] 4-3-stable
---
https://cmake.org/pipermail/cmake/2011-August/045927.html
Specifically, `SET(CMAKE_EXE_LINKER_FLAGS "-Wl,--enable-new-dtags")`

Also, use `set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)`

**Comment by SwooshyCueb** [comment]
We're already passing `--enable-new-dtags` to the linker.

I'm going to be looking into whether or not it makes sense for us to define `CMAKE_BUILD_WITH_INSTALL_RPATH` when I start working on #6052.

**Comment by alanking** [comment]
Let me know if we consider this task done and I can check the boxes. It seems that the two parts of the OP are addressed now.

**Comment by SwooshyCueb** [comment]
Yeah it's done, check away
