### ISSUE TITLE
Need to check existence of _comm before populating rei and checking peps

### ISSUE THREAD

**Issue by rskarbez** [irods/irods#3401]

**Comment by trel** [comment]
@korydraughn please check this for any remaining work.

can close if it's not clear/obvious.

**Comment by korydraughn** [comment]
will do

**Comment by korydraughn** [comment]
it's not clear what the potential issue here is other than a possible segfault.

i think this can be closed.

**Comment by trel** [comment]
excellent.

**Comment by trel** [comment]
This was included as part of 4.2.1.
