### ISSUE TITLE
document rebalance command, dry-run, throttling, etc.

### ISSUE THREAD

**Issue by kript** [irods/irods#3409]
At present the `admin modresc XXX rebalance` command is somewhat 'black box' at the moment, making running it a somewhat high risk endeavor when you potentially have TB to PB of data to replicate.

Can we have options for;

1. a 'dry run' showing what it would do
2. a way to throttle to X files at a time
3. a way to log what it is doing, from where to where

Also, can we have some documentation on;

1. what happens if it gets interrupted
2. where it runs and is this dependent on where the command is run
3. how it deals with 'dirty' copies (missing `&` in output)

If I've missed something in the docs about this, please accept my apologies and point me at the right bit?

cheers

John

**Comment by trel** [comment]
The rebalance behavior is resource-plugin-specific.  The only meaningful one to date is the one defined for the replication coordinating resource.  The other coordinating nodes just pass the operation to their own children.

We can certainly get this into the documentation, but I wanted to continue the conversation here first to make sure we cover what you're asking for...

The replication coordinating resource implementation gathers and then iterates over [500](https://github.com/irods/irods/blob/4-1-stable/plugins/resources/replication/librepl.cpp#L96) data objects at a time.  It gathers only good replicas that need to be replicated to other leaf nodes in the tree.

1. If the rebalance operation is interrupted, then the next time it is run, any unfinished work would still be 'unbalanced' and will appear in the next gathered set.

2. The behavior is independent of where the command is issued.

3. 'dirty' / 'stale' copies are overwritten by good replicas as the 'stale' replicas are not matched in the gathering stage.


To address the requests for features...
1. **Dry-Run** - this is hard, but we can think through how good a representation it would be (it's a dynamic system, so a dry-run might give you a really bad out-of-date calculation)
2. **Throttle** - 500 data objects at a time, and it's interruptible... can you explain a bit more about what this feature would do?
3. **Logging** - interesting... it's just firing the replication code path underneath, so... would need to think through what this means.

**Comment by jasoncoposky** [comment]
**1. Dry-Run** - the gather operation is simply a query provided by the database plugin.  For a given resource hierarchy i imagine a python script could be written to implement a dry run tool.

**2. Throttle** - the dynPEP for the rebalance operation allows you to set the batch size per iteration.  By default this is 500, but to modify it for 4-1-stable the implementation would be:
```
pep_resource_rebalance_pre(*OUT) {
    *OUT="replication_rebalance_limit=200";
}
````
keep in mind that the rebalance operation runs until there is no work to do, but this feature can keep the batch sizes small to manage the load.

**3. Logging** - For the 4-1-stable series I do not believe there is a way to log which data objects are automatically rebalanced.  For the 4.2 series the additional dynPEPs for the API would allow us to log those results.

**Comment by kript** [comment]
Thanks for this, and apologies for taking so long to come back. Is the query you mentioned in 1. above, an iRODs stored query? Either way, its useful to know that since we could then use `iquest` to generate the file list anytime we wanted, unless I've misunderstood..

**Comment by kript** [comment]
@jasoncoposky when you say the 'batch size per iteration' is 500, is this a parallel or seal operation, and is it the iCat server crying out the replication, or the iRES which hosts the single replica?

Thank you!

**Comment by trel** [comment]
These are definitely sequential operations of the 500 within the batch.   I believe the server handling the request is the one carrying out the replication operation - but the data movement is point to point.

**Comment by trel** [comment]
Logging a rebalance is now #3463

**Comment by PeteClapham** [comment]
On large scale iRODS installations with a large file number and large file sizes, it would be very advantageous to have a parallelise option for the re balance. I think current predictions for an existing run is currently 4 - 5 months. Perhaps splitting the initial file and running the sub-components in parallel could be a quick win ?

**Comment by tledoux** [comment]
As stated by @PeteClapham, we envision rebalance as very lengthy operations that we need to have some control over. It could be nice if we can add scope what is rebalanced by means of :
- a AVU request (like in imeta qu)
- or requesting a specific information (like modification date or comment ?).

**Comment by trel** [comment]
Parallelization of rebalance has been pulled out into #3529.

Scoping a rebalance is now #3530.


To re-cap:

1) Dry-Run - can be a stored specific query to get a count
2) Throttle - can be done with pep_resource_rebalance_pre()
3) Logging - #3463
4) Parallel - #3529
5) Scoping - #3530

Is there any other work remaining on this issue?

**Comment by kript** [comment]
Regarding 1 & 2 above, could we have them documented in the section of the manual that covers the rebalance command please? 
Having the query that shows how many objects need rebalancing documented I can imagine to be very helpful (well, it is for us :-) ), for e.g. automated alerting of rebalance being required, or the aforementioned dry-run. At the moment, we are doing this with two queries, where the total rebalance is the sum of both of them;

```
DirtyReplicasRoot
select count(*) from r_data_main where resc_name = 'root' and data_is_dirty = '0'
---
RebalanceRequiredCount
select count(*) from (select data_id from r_data_main where resc_name = 'root' group by data_id having count(*) = 1)
```

wrt documentation,  [your comment above](https://github.com/irods/irods/issues/3409#issuecomment-263572070) was very helpful in describing how rebalance goes about sign what it is, so I'd encourage that to be included in some form as well.

**Comment by trel** [comment]
Definitely.  Agreed.
