### ISSUE TITLE
iquest specific query issue on composite resource structure

### ISSUE THREAD

**Issue by kript** [irods/irods#3416]
Hi Folks,

I have a query that returns a list of objects that have only one replica;
`iadmin asq 'select coll_name, data_name from r_data_main join r_coll_main using(coll_id) where resc_name = ? group by coll_name, data_name having count(data_id) = 1' only_one_replica_by_resource`

When I run it against demoResc (which is not part of a composite resource structure), I get the expected results.

When I run it against a resource that is part of a compound resource structure, I need to provide the entire structure, or it doesn't match;

```
iquest --sql only_one_replica_by_resource root;replicate;seq-red;red4;irods-seq-i21-de
/seq/8025/InterOp
QMetricsOut.bin
----
/seq/8260/InterOp
CorrectedIntMetricsOut.bin
----
```
but then I get the query terminating suddenly with;
```
----
/seq/illumina/library_merge/13813929.CCXX.paired310.4090269666
13813929.CCXX.paired310.4090269666.cram
----
/seq/sequenom/c8/b3/89
W36249_Replication454288_454290_454411_454282_20160728_G24.csv
-bash: replicate: command not found
-bash: seq-red: command not found
-bash: red4: command not found
-bash: irods-seq-i21-de: command not found
```

Attempting to modify the query to use 'like' means passing the '%' signs via iquest, which doesn't match anything;

```
irods-g1@irods-g1:~$ iadmin asq 'select coll_name, data_name from r_data_main join r_coll_main using(coll_id) where resc_name LIKE ? group by coll_name, data_name having count(data_id) = 1' only_one_replica_by_LIKE_resource
irods-g1@irods-g1:~$ iquest --no-page  --sql only_one_replica_by_resource %irods-seq-i21-de% | tee irods-seq-i21-de_no_replicas_20161208.txt
No rows found
irods-g1@irods-g1:~$ iquest --no-page  --sql only_one_replica_by_resource \%irods-seq-i21-de\% | tee irods-seq-i21-de_no_replicas_20161208.txt
No rows found
```

NB all of this is o 4.1.9-preview3, with an Oracle database backend

**Comment by trel** [comment]
What happens if you put the `?` within double quotes in the query....    `"?"`

**Comment by kript** [comment]
with the modified query;

`iadmin asq 'select coll_name, data_name from r_data_main join r_coll_main using(coll_id) where resc_name = "?" group by coll_name, data_name having count(data_id) = 1' only_one_replica_by_resource_quoted2`

I get

```
Dec  8 15:04:08 pid:2192 ERROR: cllExecNoResult: OCIBindByName failed: -1
Dec  8 15:04:08 pid:2192 ERROR: sql:select coll_name, data_name from r_data_main join r_coll_main using(coll_id) where resc_name = ":1" group by coll_name, data_name having count(data_id) = 1
Dec  8 15:04:08 pid:2192 ERROR: OCI_Error: ORA-01036: illegal variable name/number
Dec  8 15:04:08 pid:2192 ERROR: bindVar[1]=:irods-seq-sr04-ddn-gc10-9-10-11:
Dec  8 15:04:08 pid:2192 NOTICE: chlSpecificQuery cmlGetFirstRowFromSql failure -839000
Dec  8 15:04:08 pid:2192 NOTICE: _rsSpecificQuery: specificQuery status = -839000
Dec  8 15:04:08 pid:2192 NOTICE: rsSpecificQuery: rcSpecificQuery failed, status = -839000
Dec  8 15:04:08 pid:2192 NOTICE: readAndProcClientMsg: received disconnect msg from client
Dec  8 15:04:08 pid:2192 NOTICE: Agent exiting with status = 0
```

**Comment by kript** [comment]
Could we get some feedback as to why this is targeted for 4.3 please?

**Comment by kellerb** [comment]
Speaking in generalities, all new issues that we plan to work on soon will be marked as 4.3 unless there is a specific request to pull them into a 4.2 point release.

**Comment by kript** [comment]
Thanks @kellerb that makes sense, but as its affecting us on 4.1.10, and the production release is 4.2.0, I was expecting it to be a 4.2.1 fix. Except I'm not sure how much of an issue it is 'under the hood' - the bump to future release implied to me it was a big issue that needed a lot of refactoring..

**Comment by jasoncoposky** [comment]
Our process is to hold issues in the next minor release and then pull them back into any point release we might ship from the stable branch.  If necessary this issue could be cherry picked back to 4.1.x or 4.2.x.

**Comment by kellerb** [comment]
Do you have a specific query that handles this use case now? Aka. is this issue close-able?

**Comment by kript** [comment]
I do, let me add it on Monday so others searching this can find it. From memory, this references another bug, as to why the search doesn't work on a composable resource as  expected, as we should probably link to that, or write up here why it happens and the workaround until one is able to upgrade to 4.2, which IIRC doesn't have this.

**Comment by trel** [comment]
I believe this was resolved with the use of `resc_hier` rather than `resc_name`.

**Comment by kript** [comment]
Thanks to folks here, we got to a few queries that may be of help to others on 4.1.X;
Given a resource called `irods-seq-i16-bc` in a tree of root->replicate->seq-red->redX->irods-seq-i16-bc, and wanting a list of single objects, but the query to return collection/object name;
```
ListSingleObjectsByResourceReturningPathsForRootReplicateSeq-redRed3Irods-seq-i16-bc
select coll_name || '/' || data_name from r_data_main inner join r_coll_main on r_data_main.coll_id = r_coll_main.coll_id where resc_hier = 'root;replicate;seq-red;red3;irods-seq-i16-bc' and data_id in (select data_id from r_data_main group by data_id having count(data_id) = 1)
```
The same but just the data objects;
```
ListSingleObjectsByResource
select data_id from r_data_main where resc_hier = 'root;replicate;seq-red;red3;irods-seq-i16-bc' and data_id in (select data_id from r_data_main group by data_id having count(data_id) = 1)
```
