### ISSUE TITLE
Binary build or installer for icommands on Mac and/or windows?

### ISSUE THREAD

**Issue by seandavi** [irods/irods#3417]
Are there plans to provide a binary build or packages for Mac (my interest) or Windows for 4.2+?

**Comment by trel** [comment]
There is interest, but no current plan/priority at this time from our membership.

We would have to have a Mac or Windows machine in CI to release under the consortium namespace.

**Comment by seandavi** [comment]
Thanks. I wish I had a machine to offer right now.  In the meantime, we'll just build locally.

**Comment by kript** [comment]
> We would have to have a Mac or Windows machine in CI to release under the consortium namespace.

No promises, but if you let us know what you'd need in terms of hardware and firewall ports, we can see if we could offer something. Even better if its a VM.. ;-)

**Comment by jjkoehorst** [comment]
I know this is an old thread but if there is documentation somewhere I might be able (no promises) to find an old iMac we have here for building purposes. Also how often do these builds need to be done?

**Comment by trel** [comment]
The README.md at https://github.com/irods/irods_client_icommands/ has the steps required.

I don't believe they build on Mac or Windows at this time.
