### ISSUE TITLE
imeta misinterpreting AVU as command line flag

### ISSUE THREAD

**Issue by marchoeppner** [irods/irods#3435]
I noticed that certain types of meta data values cause problems with the imeta command - if they start with a hypen:
```
imeta add -d some_file Temperature -80°C temperature
```
The `-80°C` gets interpreted as a command line option and thus produces a failure. Encapsulating the value in `""` or trying to escape it with `\` doesn't fix the problem either. 

Is this behavior intended?

**Comment by kellerb** [comment]
This is not intended, this is a bug in the parsing of command line arguments.

**Comment by rskarbez** [comment]
Duplicate of #2770.
