### ISSUE TITLE
Feature request: add --json flag to icommands

### ISSUE THREAD

**Issue by matthdsm** [irods/irods#3444]
Hi,

Would it be possible to add a `--json` flag to iCommands, to force output in json format? This would be very useful to use the output programatically.

Thanks!
M

**Comment by kript** [comment]
👍

**Comment by trel** [comment]
Is `ils` at the top of the list?

**Comment by matthdsm** [comment]
Preferably, I think json output will be of most use there. 
Thanks for the quick reply!
M

**Comment by trel** [comment]
@matthdsm you meant to close this issue?
