### ISSUE TITLE
Feature request - Authentication plugin - OAuth2

### ISSUE THREAD

**Issue by matthdsm** [irods/irods#3445]
Hi

Would it be possible to add an authentication plugin to support authentication with OAuth2? Or is this already possible in some way?

Thanks
M

**Comment by trel** [comment]
It is possible.  But we do not have an OAuth2 plugin today.

Do you have a specific use case in mind?  Presumably, the client code would look very similar to the other authentication plugins.  Solid testing is always the complicated part.

**Comment by matthdsm** [comment]
Well, I'm being a bit selfish right now, but we're planning to implement an institution wide openAuth sever, so all of our services can use the same username/password. It would be nice if we could let people authenticate to iRODS using the same mechanism.

**Comment by ccacciari** [comment]
+1

**Comment by PeteClapham** [comment]
It may be that this would link well with the global alliance API's. Perhaps something very much worth visiting from a strategic position.

**Comment by carsten-jahn** [comment]
+1, we're also looking into using OAuth in our organization

**Comment by trel** [comment]
You can currently get to OAuth via CAS via PAM.

**Comment by ccacciari** [comment]
Thanks!
Is there any example available?
Is the idea to use the Yale CAS client PAM module (https://wiki.jasig.org/display/CASC/PAM+Module) to "CASify" iRODS and then to use CAS as an OAuth client?

**Comment by trel** [comment]
pinging @michael-conway

**Comment by ccacciari** [comment]
I found a solution, which is described here:
https://github.com/ccacciari/pam-oauth2

**Comment by trel** [comment]
Ah, very good.   With the pointer in place to your fork, I'm going to close this issue so any future searchers will find their way to the PAM plugin.
