### ISSUE TITLE
Feature request: autocompletion

### ISSUE THREAD

**Issue by matthdsm** [irods/irods#3446]
Hi,

Sorry for spamming you guys with so many issues and request, but here's another one:
Would it be possible to have built-in path autocompletion in the iCommands with tab? e.g. like you have in bash. Or are there some technical complications that make this impossible? I do realize this would greatly increase the load on the server, but it would make for u huge increase in user friendliness.

Thanks
M

**Comment by trel** [comment]
No worries.

There is a script in the 4-1-stable branch that provided this feature.

  https://github.com/irods/irods/blob/4-1-stable/iRODS/irods_completion.bash

As you wrote, this increases back and forth with the server, and could very well be unusable over a longer link due to latency.

**Comment by matthdsm** [comment]
Allright! You learn something new every day!
Thanks for the quick response

Cheers,
M
