### ISSUE TITLE
Feature request - ticket based access with `irsync`

### ISSUE THREAD

**Issue by matthdsm** [irods/irods#3447]
Hi

Would it be possible to add ticket based access to the `irsync` command?

Thanks!
M

**Comment by trel** [comment]
iRODS can be on either or both ends of an `irsync`:

```
1 - irsync foo1 i:foo2
2 - irsync i:foo1 foo2
3 - irsync i:foo1 i:foo2
```

We'll need to think through how that works - if a ticket is used, and both ends are iRODS (Case 3)... how do we specify where the ticket is to be used?  Is it required that the ticket have access to both?  Maybe ticket-based usage is not allowed in Case 3.

**Comment by matthdsm** [comment]
perhaps you can include the ticket string into the path?  e.g.

```
1 - irsync foo1 ticket1@i:foo2
2 - irsync ticket2@i:foo1 foo2
3 - irsync ticket3@i:foo1 ticket4@i:foo2
```

Although this doesn't look very clean on second thought, it might be a solution.

Thanks for the quick reply.
M

**Comment by trel** [comment]
`iget` and `iput` use `-t`, so that would be the default plan... but they only ever go in one direction at a time.

**Comment by matthdsm** [comment]
True, but I have found iRsync more reliable in the past + it provides file checks so no unnecessary transfers are done. So I prefer to use irsync, but this is of course, highly objective.

**Comment by trel** [comment]
Oh yes, I'm only suggesting a default plan regarding which flag to implement (`-t`).   Sorry that wasn't clear.

**Comment by matthdsm** [comment]
oh, I that case, I fully agree `-t` would be the best choice. Perhaps the flag can be used to signal that a ticket string should be parsed from the path names. Or the argument could be specified multiple times and the position should then define which path it refers to?

**Comment by trel** [comment]
@matthdsm you meant to close this issue?
