### ISSUE TITLE
Remote rule execution SYS_PACK_INSTRUCT_FORMAT_ERR

### ISSUE THREAD

**Issue by ajguerra** [irods/irods#3448]
I am working with remote rules and I have written the following rule:

```
testRule {
    remote("rescServer.com", "") {
           test_microservice(*out);
    }
}
INPUT null
OUTPUT *out
```

If I run the rule above and change the host from `rescServer.com` to `iCAT.com`, I get the expected output. But running the rule as is shows an error message saying `ERROR: rcExecMyRule error.  status = -15000 SYS_PACK_INSTRUCT_FORMAT_ERR`.

Am I allowed to return an output value from a rule that is executed in a server different from the iCAT server? BTW, if I replace `*out` by `ruleExecOut`, the rule executes just fine.

Thanks in advance!

**Comment by ajguerra** [comment]
Trying to understand what was going on, I found out something interesting. 

If I execute a remote rule from the iCAT to another resource server (like the example in the post above), I get a `SYS_PACK_INSTRUCT_FORMAT_ERR` error. 

However, if I run the same rule on the resource server and change the remote server to be my iCAT host, the rule does work.

This rule __does not__ work (running it from the iCAT):
```
testRule {
    remote("rescServer.com", "") {
           test_microservice(*out);
    }
}
INPUT null
OUTPUT *out
```

This rule __does__ work (running it from the resource server):

```
testRule {
    remote("icat.com", "") {
           test_microservice(*out);
    }
}
INPUT null
OUTPUT *out
```

This is all I know so far.

**Comment by ajguerra** [comment]
Logs

```
Jan 26 10:27:59 pid:2623 ERROR: resolveStrInItem: Cannot resolve type in inOutStruct
Jan 26 10:27:59 pid:2623 ERROR: sendApiRequest: packStruct error, status = -15000 status = -15000 SYS_PACK_INSTRUCT_FORMAT_ERR
Jan 26 10:27:59 pid:2623 ERROR: executeRuleAction Failed for remoteExec status = -15000 SYS_PACK_INSTRUCT_FORMAT_ERR

```

**Comment by trel** [comment]
what iRODS version?   both servers are the same version?

**Comment by ajguerra** [comment]
4.1.10 and all servers run the same version.

I noticed that if I redirect the output to `ruleExecOut` the rule works fine. So, I am still not able to get the response back from my MSI, but at least I see no errors. My rule looks like:

```
testRule {
    remote("icat.com", "") {
           test_microservice(*out);
    }
}
INPUT null
OUTPUT ruleExecOut
```

It worked in both directions: from the iCAT to another resc server B and from B to iCAT.

**Comment by ajguerra** [comment]
@trel we finally got it!

iRODS was complaning because the variable `*out` inside the `remote` rule wasn't declared within `testRule`. This `*out` variable existed only in the scope of `remote`, it did not exist at all in the scope of `testRule`. 

To fix it, we had to declare the variable inside `testRule` too. This will create the variable inside testRule's scope, replaced by the MSI and can be accessed by `OUTPUT`.

So, `testRule` looks like this now:

```
testRule {
    *out = "";
    remote("icat.com", "") {
           test_microservice(*out);
    }
}
INPUT null
OUTPUT *out
```

This solution may help other people debugging their rules since it's not present in the rule documentation.

Thx!

**Comment by ajguerra** [comment]
I agree with you, it does feel a bit inconsistent. 

I'm not sure if that's is the right way to do it, but it worked for us. If it still ok to leave it as is I can try to working something out for documentation. Otherwise, we can work out a better solution.
