### ISSUE TITLE
Disallow the three characters { } ; in resource child context strings

### ISSUE THREAD

**Issue by tedgin** [irods/irods#3449]
- [x] 4-1-stable
- [x] 4-2-stable
- [x] master

---

I tried to attach a child resource to a parent resource with a context string containing the character `}`. It successfully attached the child. I then removed the child from the parent.  Afterwards, when I used `ilsresc` to list the resources, the command failed generating a backtrace.

Please either define which characters are allowed in context strings or allow context strings to contain any character.

(Do I win an award for the most silly issue ever?}

**Comment by trel** [comment]
Which version of iRODS?

I did not reproduce with the following sequence, using 4.1.9:
```
$ iadmin addchildtoresc demoResc newresc 'asdfs}asfdsf'
$ ilsresc
demoResc
└── newresc:random
$ iadmin rmchildfromresc demoResc newresc
$ ilsresc
demoResc
newresc:random
```
or
```
$ iadmin addchildtoresc demoResc newresc asdfs}asfdsf
$ ilsresc
demoResc
└── newresc:random
$ iadmin rmchildfromresc demoResc newresc
$ ilsresc
demoResc
newresc:random
```

**Comment by tedgin** [comment]
Oops!  It appears that it's the combination of a `{` and a `;` that causes the problem.
```
$ iadmin addchildtoresc parentResc child2Resc '};'
? iadmin rmchildfromresc parentResc child2Resc
? ilsresc parentResc
parentResc:replication
├── child1Resc:random
ERROR: Caught irods::exception
=-=-=-=-=-=-=-
iRODS Exception:
    code: -24000
    message:
        Missing node in resc_map: [}]
stack trace:
--------------

Dumping stack trace
<0>	irods::exception::exception(long, std::string const&, std::string const&, unsigned int, std::string const&)                                                                                                                                                                                                      	Offset: 0x67	Address: 0x4de6b7
<1>	printRescTree(std::string const&, std::string const&, std::vector<std::string, std::allocator<std::string> > const&, std::vector<std::string, std::allocator<std::string> > const&, std::map<std::string, int, std::less<std::string>, std::allocator<std::pair<std::string const, int> > > const&, DrawingStyle)	Offset: 0x2d0	Address: 0x45f020
<2>	printRescTree(std::string const&, std::string const&, std::vector<std::string, std::allocator<std::string> > const&, std::vector<std::string, std::allocator<std::string> > const&, std::map<std::string, int, std::less<std::string>, std::allocator<std::pair<std::string const, int> > > const&, DrawingStyle)	Offset: 0x4cf	Address: 0x45f21f
<3>	showRescTree(char const*, char const*, rcComm_t*, DrawingStyle)                                                                                                                                                                                                                                                  	Offset: 0x5a5	Address: 0x45fa45
<4>	ilsresc(main+0x1d3) [0x447273]                                                                                                                                                                                                                                                                                   	Offset: 	Address: 0x447273
<5>	/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7fc912e4c830]                                                                                                                                                                                                                                         	Offset: 	Address: 0x7fc912e4c830
<6>	ilsresc() [0x45dd57]                                                                                                                                                                                                                                                                                             	Offset: 	Address: 0x45dd57

=-=-=-=-=-=-=-
└──                                                                                                                                                            ```

I'm using iRODS version 4.1.9 like you guessed.

**Comment by trel** [comment]
I'm pretty sure this is a 4-1-stable-only bug.

We refactored how parent/child relationships were handled in the database in 4-2-stable.

A test should be included for 4-1-stable, 4-2-stable, and master that exercises this usage.

**Comment by kellerb** [comment]
The proposed fix is to disallow `;`, `{`, and `}` in child context strings in 4.1.11. 

For 4.2, we will need to either also disallow those characters or change [the handling code](https://github.com/irods/irods/blob/4.2.0/lib/core/src/irods_children_parser.cpp#L110-L164).

**Comment by tedgin** [comment]
Isn't the `;` character used to separate values in context strings?  Maybe only `{` and `}` should be disallowed.

**Comment by kellerb** [comment]
There are two types of context string in iRODS:
1. Context strings used to label resources (nodes in the resource hierarchy). These are created with `iadmin mkresc ...` and edited with `iadmin modresc ...`.
2. Context strings used to label parent-child relationships (edges in the resource hierarchy). These are created with `iadmin addchildtoresc ...`.

The first type of context string commonly uses `;` to separate `key=value` entries. The second type of context string, as far as I know, is used mainly by the `compound` resource to denote which child is the `archive` and which child is the `cache`.

It would be better, of course, to have the same rules for each type of context string. Because of the way that the second type of context string is stored in the database in 4.1, this cannot be done without adding additional handling.

Do you have a resource plugin that uses `;` in the second type of context string?

**Comment by tedgin** [comment]
I don't have any resource plugins that require a `;` in the parent-child relationship context.

**Comment by kript** [comment]
While we don't have those characters in our resource names, I would ask that we don't disallow them in a future release - this will likely break the path of least surprise for people who may not have noticed this change, and while you could add code in the upgrade process to rename the resources during the upgrade, this may then break rulesets and code written assuming a naming convention.
If you're going to do that, I'd suggest doing it in the v5 release as compatibility for 3.x is also deprecated, as I recall..

**Comment by kellerb** [comment]
@kript Those characters are already disallowed in resource names, this issue is about disallowing them in the context string of parent-child relationships. I expect that if other installations were using those characters in said context strings there would have been issues reported earlier, because the characters break many uses of iRODS, and I believe require direct database access to fix.
