### ISSUE TITLE
IRODSConfig.cmake missing IRODS_LINUX_DISTRIBUTION_VERSION_CODENAME

### ISSUE THREAD

**Issue by kellerb** [irods/irods#3453]
- [ ] master
- [x] 4-2-stable
---------

**Comment by RubenGarcia** [comment]
I am also affected

**Comment by RubenGarcia** [comment]
In  iRODS 4.2.8, after installing package irods-dev, the file becomes available, so this bug can be closed now.

**Comment by trel** [comment]
@SwooshyCueb This may already be handled with the new CMake work.  Please confirm/deny/close.

**Comment by SwooshyCueb** [comment]
It's not fixed yet, but will be as part of my work on #5250

**Comment by trel** [comment]
got it - so another knob for later if necessary.   thanks.
