### ISSUE TITLE
ichmod -r loops forever

### ISSUE THREAD

**Issue by carsten-jahn** [irods/irods#3456]
I found a directory tree that makes `ichmod -r` loop forever. This was reproducible in a second iRODS instance (both 4.1.9). Apparently, lots of empty collections are needed to show the issue.

``` bash
imkdir /ourZone/home/rods/stresstest
for i in `seq 1 1 1000`; do imkdir /ourZone/home/rods/stresstest/dir$i; done
ichmod -r own rods /ourZone/home/rods/stresstest
```

The command does not return. A `writeLine` audit log rule shows that each directory gets its permission set, then it starts over, instead of finishing after one recursive execution.

Let's see if you can reproduce this ;-)

**Comment by kellerb** [comment]
I ran the listed bash (changing only the name of the zone) and was not able to reproduce the hang on 4.1.9.
* Is it possible there are rules in your `/etc/irods/core.re` that are triggering the loop?
* Which flavor of database plugin are you using?

**Comment by carsten-jahn** [comment]
Hi, the problem is in fact related to the rule. I thought it is just a simple writeLine, but in this case there is more logic involved. So we can certainly fix this in our rule.
