### ISSUE TITLE
restore ability to run specific queries across federation

### ISSUE THREAD

**Issue by kript** [irods/irods#3466]
In 3.3.1 we could run a query hosted on a federated zone from a federation master. 
After upgrade we can still run queries that were added with `iadmin asq` before the upgrade but post upgrade (w're on 4.1.9~preview3 ATM), new queries added won't run across Federation (although this might be because the new queries we added don't have an '?' in them, it occurs to me), and need to be run within the zone.

```
$ iquest --sql only_one_replica -z seq
Level 0: The SQL is not pre-defined.
  See 'iadmin h asq' (add specific query)
rcSpecificQuery failed with error -853000 CAT_UNKNOWN_SPECIFIC_QUERY 
ERROR: iquest Error: specificQuery (sql-query) failed status = -853000 CAT_UNKNOWN_SPECIFIC_QUERY

$ iquest -z seq --sql only_one_replica
Level 0: The SQL is not pre-defined.
  See 'iadmin h asq' (add specific query)
rcSpecificQuery failed with error -853000 CAT_UNKNOWN_SPECIFIC_QUERY 
ERROR: iquest Error: specificQuery (sql-query) failed status = -853000 CAT_UNKNOWN_SPECIFIC_QUERY

$ iquest -z seq --sql "select DATA_NAME, DATA_ID where DATA_NAME = '13655_1_test.cram'"
Level 0: The SQL is not pre-defined.
  See 'iadmin h asq' (add specific query)
rcSpecificQuery failed with error -853000 CAT_UNKNOWN_SPECIFIC_QUERY 
ERROR: iquest Error: specificQuery (sql-query) failed status = -853000 CAT_UNKNOWN_SPECIFIC_QUERY
```

**Comment by trel** [comment]
Can you show an example of a successful cross-zone specific query run?

**Comment by kript** [comment]
query is;
```
----
dataModifiedIdOnly
SELECT DISTINCT Data.data_id AS data_id FROM R_DATA_MAIN Data WHERE CAST(Data.modify_ts AS INT) > CAST(? AS INT) AND CAST(Data.modify_ts AS INT) <= CAST(? AS INT)
----
```
$ iquest -z seq --sql dataModifiedIdOnly 1480103390 1486133981
1050884
----
1050873
----
1082445
----
1088251
----
1082443
----
1082444
----
1054269
----
1050897
----
1089012
----
1053131
----
1082442
```

**Comment by kript** [comment]
No chance of getting this in for 4.1.11 is there?

**Comment by trel** [comment]
For you sir.  It is done.
