### ISSUE TITLE
question: support for byte range request

### ISSUE THREAD

**Issue by matthdsm** [irods/irods#3471]
Hi,

Does iRODS currently support byte range requests? preferably with user authentication.

Thanks!
M

**Comment by jasoncoposky** [comment]
Matthias,

The rcDataObjOpen, rcDataObjLSeek, rcDataObjRead and rcDataObjWrite APIs will allow for offset reads and writes.  Jargon and the python APIs also support these calls.

Thanks,

—
Jason Coposky
Executive Director, iRODS Consortium
RENCI at the University of North Carolina at Chapel Hill
w: (919)445-9675<tel:%28919%29445-9675>
m: (919)522-0517<tel:%28919%29445-9675>
jasonc@renci.org<mailto:jasonc@renci.org>
linkedin<https://www.linkedin.com/in/jason-coposky-06bab01>
twitter<https://twitter.com/jason_coposky>
irods.org<http://irods.org/> — Take Control of Your Data

**Comment by matthdsm** [comment]
Hi Jason, 
Thank you for your reply!
I'm actually looking to set up a way for IGV to read files from iRODS, which of the above API's are the most appropriate for this, in your opinion? 

Thanks again
M

**Comment by jasoncoposky** [comment]
Matthias,

Have you tried the fuse interface to iRODS?  Otherwise does IGV have an API or some way to utilize other means of I/O?  If so the APIs I mentioned will be what you would use.

Thanks,

—
Jason Coposky
Executive Director, iRODS Consortium
RENCI at the University of North Carolina at Chapel Hill
w: (919)445-9675<tel:%28919%29445-9675>
m: (919)522-0517<tel:%28919%29445-9675>
jasonc@renci.org<mailto:jasonc@renci.org>
linkedin<https://www.linkedin.com/in/jason-coposky-06bab01>
twitter<https://twitter.com/jason_coposky>
irods.org<http://irods.org/> — Take Control of Your Data

**Comment by matthdsm** [comment]
To be complete, we're actually trying to get IGV.js to work in a webinterface, so local files are not an option. I was checking out Jargon, and I think we'll give the REST api a shot.

Thanks for the help.
M

**Comment by jasoncoposky** [comment]
Yes that would be the best choice for a web application, unless you wanted to try to integrate it with gorods.

Thanks,

—
Jason Coposky
Executive Director, iRODS Consortium
RENCI at the University of North Carolina at Chapel Hill
w: (919)445-9675<tel:%28919%29445-9675>
m: (919)522-0517<tel:%28919%29445-9675>
jasonc@renci.org<mailto:jasonc@renci.org>
linkedin<https://www.linkedin.com/in/jason-coposky-06bab01>
twitter<https://twitter.com/jason_coposky>
irods.org<http://irods.org/> — Take Control of Your Data

**Comment by matthdsm** [comment]
Personally, I'd prefer to "go" with goRODS, since I'm no fan of java (highly subjective), but I'm not familiar at all with golang. If there was some kind of tutorial I could follow set things up, that'd be great, but for now I think Jargon has the best docs. (Unless you can point me to some magic resource I happen to have missed).

Thanks
M

**Comment by trel** [comment]
The GoRODS docs are here: https://godoc.org/github.com/jjacquay712/GoRODS
GoRODS itself is here:  https://github.com/jjacquay712/GoRODS

cc/ @jjacquay712

**Comment by jjacquay712** [comment]
@matthdsm here is the usage guide I put together, demonstrating common iRODS use cases (including byte range seeks): https://github.com/jjacquay712/GoRODS/blob/master/HOWTO.md

Feel free to shoot me a message if you have any questions or encounter problems. 

-JJ

**Comment by matthdsm** [comment]
Hi John, 

Thanks for the info. We'll be sure to give this a shot. I'll keep you posted on the progress!

Thanks again,
M

**Comment by trel** [comment]
I'm going to close this issue as there does not appear to be anything actionable in this repository.  If you need something else, please create a new issue.  Thanks.
