### ISSUE TITLE
Investigate async safe logging of stack trace in signal handler for release builds

### ISSUE THREAD

**Issue by kellerb** [irods/irods#3479]

**Comment by mcv21** [comment]
Hi,

Can you add the consortium_member tag to this and #3326 please? I've been looking at a race condition elsewhere in the code, and found the undefined behaviour in irods_signal.cpp. I was going to report it, but I found these two issues about it already.

Thanks :)

**Comment by korydraughn** [comment]
the following code needs to be investigated as well.
https://github.com/irods/irods/blob/1467ffd6fb83c83bf4f031218900a3698fe88925/server/core/src/irodsReServer.cpp#L623-L633
