### ISSUE TITLE
ifsck size check corruption should have non-zero return code

### ISSUE THREAD

**Issue by kript** [irods/irods#3492]
- [x] 4-1-stable
- [x] 4-2-stable
- [x] master

---

As the subject says. Waiting to hear if this also applies to `iget -K` as well
```
irods@irods-seq-sr03:~$ md5sum /irods-seq-sr03-ddn-gg07-12-13-14//7766/7766_2#147.bam
2ab8aa628665f18f6dc133e6506b92ab  /irods-seq-sr03-ddn-gg07-12-13-14//7766/7766_2#147.bam
irods@irods-seq-sr03:~$ ls -l /irods-seq-sr03-ddn-gg07-12-13-14//7766/7766_2#147.bam
-rw------- 1 irods irods 6336560777 Apr  9  2012 /irods-seq-sr03-ddn-gg07-12-13-14//7766/7766_2#147.bam
…
irods@irods-seq-i05:~$ md5sum /irods-seq-i05-de/7766/7766_2#147.bam
a52836f2b4db323e5f01c43c6d433111  /irods-seq-i05-de/7766/7766_2#147.bam
ls -l /irods-seq-i05-de/7766/7766_2#147.bam
-rw------- 1 irods irods 6336560777 Apr  9  2012 /irods-seq-i05-de/7766/7766_2#147.bam
```
iRODS hasn't marked either of the replicas as stale (thats OK, in principle - silent data corruption is a thing, as is file corruption at rest);
```
 ils -L /seq/7766/7766_2#147.bam
  srpipe            0 root;replicate;seq-green;green3;irods-seq-sr03-ddn-gg07-12-13-14   6336560777 2012-04-09.03:46 & 7766_2#147.bam
    2ab8aa628665f18f6dc133e6506b92ab    generic    /irods-seq-sr03-ddn-gg07-12-13-14/7766/7766_2#147.bam
  srpipe            1 root;replicate;seq-red;red1;irods-seq-i05-de   6336560777 2012-04-09.03:49 & 7766_2#147.bam
    2ab8aa628665f18f6dc133e6506b92ab    generic    /irods-seq-i05-de/7766/7766_2#147.bam
```
More worrying, the tools we rely on to validate the files on retrieval don't seem to be flagging the issue;
```
$ ichksum -n 1 /seq/7766/7766_2#147.bam
    7766_2#147.bam                    2ab8aa628665f18f6dc133e6506b92ab
Total checksum performed = 1, Failed checksum = 0
$ ichksum -n 0 /seq/7766/7766_2#147.bam
    7766_2#147.bam                    2ab8aa628665f18f6dc133e6506b92ab
Total checksum performed = 1, Failed checksum = 0
...
irods-seq-i05:~$ ifsck  -K /irods-seq-i05-de/7766/7766_2#147.bam
...
irods-seq-sr03:~$ ifsck -K /irods-seq-sr03-ddn-gg07-12-13-14/7766/7766_2#147.bam
```

**Comment by kript** [comment]
Confirmed that `iget -K` gives an error when downloading the corrupt replica.

**Comment by trel** [comment]
As per the `ichksum` help text:
```
By default, objects are silently ignored if they already have a catalog checksum.
```

`ichksum` won't validate the value in the catalog without the use of `-K`.

`$ ichksum -K -n 1 /seq/7766/7766_2#147.bam` should recalculate and validate.


`ifsck` may have a bug, but it appears on first pass that `ichksum` is behaving as expected.

**Comment by kript** [comment]
> By default, objects are silently ignored if they already have a catalog checksum.

I can't find this in the man page on 4.1.10 or in `-h`;

```
**@irods-g1:~$ ichksum -h
Usage: ichksum [-harvV] [-K|f] [-n replNum] [-R resource] [--silent]
           dataObj|collection ... 
Checksum one or more data-object or collection from iRODS space.
Options are:
 -f  force - checksum data-objects even if a checksum already exists in iCAT
 -a  checksum all replicas. ils -L should be used to list the values of all replicas
 -K  verify the checksum value in iCAT. If the checksum value does not exist,
     compute and register one.
 -n  replNum  - the replica to checksum; use -a to checksum all replicas.
 -R  resource  - the resource of the replica to checksum,
 -r  recursive - checksum the whole subtree; the collection, all data-objects
     in the collection, and any subcollections and sub-data-objects in the
     collection.
 --silent  - No checksum output except error
 -v  verbose
 -V  Very verbose
 -h  this help

iRODS Version 4.1.10                Nov 2016                      ichksum
```

> ichksum won't validate the value in the catalog without the use of -K.

We've avoided using that on the assumption that ichksum did checksum validation by default, and because thats not the _only_ thing the `-K` flag does, according to the man page it also; `If the checksum value does not exist, compute and register one.`. This has a real risk that if a file was replicated and a bad replica is checksummed (assuming say, on-disk or silent corruption, so unbeknown to iRODS) then we mark a valid file as dirty.

Could we have a `-k` flag that allows checksumming but fails if there isn't a checksum present?

**Comment by trel** [comment]
Ah, I forgot the help text was added to the 4.2 branch (https://github.com/irods/irods/issues/3264).

Regarding the possible new `-k`... what happens if some replicas have checksums, and others do not?

Would `-n` be required to be used alongside `-k`?

**Comment by kript** [comment]
My thought would be that `-k` should error (perhaps with `CHECKSUM_MISTMATCH`?) if there isn't a checksum. That way you can catch the missing checksums. `-n` would allow more specific targeting, but I don't think it should be required, personally.

**Comment by kript** [comment]
Reading the linked issue #3264, does 4.1.10 work the same way as 4.1.2 w.r.t the `-K` flag? If so, we might be able to use at the moment that as long as we are sure it won't over-write existing checksums;

```
 -K  verify the checksum value in iCAT. If the catalog checksum value does not exist,
     compute and register one. If the catalog checksum exists and the file checksum
     differs, log the difference to command output.
```
I would still like there to be a `-k` however, as we may not want to compute checksums, and just use as a safe check method.

**Comment by trel** [comment]
Okay.  And can you confirm that `ifsck` is definitely not doing what you'd expect?   I tested it a little bit manually, and it seemed to do what I expected.

Can you show an instance of when checksums are good/bad and files are good/bad and what the `ifsck` output is and what you'd expect?   These are the test cases we need to get into the test suite.

If we can confirm there is an issue with `ifsck`, we may open another issue for the new `ichksum -k` option.

**Comment by trel** [comment]
And to answer your question, yes, I'm pretty sure the functionality didn't change, just the documentation for 4.2.0.    As always, please confirm before rolling to production (and update here with that confirmation :) ).

**Comment by kript** [comment]
W.R.T. ifsck;
In the initial issue raised, above, I aimed to show that the files on disk for a particular object had different md5sum's but that running `ifsck -K` against each physical file did not report that the checksum of the file did not match the one in iRODS for one of the files, which is my understanding of what the -K flag should do from the docs.  
If I've misunderstood, or you would like it shown in a different way, can you let me know, as I'm not sure how else to demonstrate it.

**Comment by kript** [comment]
In this use case (where a md5sum exists for both replicas), iRODS does correctly show that one of the replica's is incorrect, and does not modify the checksum value;

```
irods-g1@irods-g1:~$ ils -L ils -L /seq/7766/7766_2#147.bam
ERROR: lsUtil: srcPath /seq/home/irods-g1/ils does not exist or user lacks access permission
  srpipe            0 root;replicate;seq-green;green3;irods-seq-sr03-ddn-gg07-12-13-14   6336560777 2012-04-09.03:46 & 7766_2#147.bam
    2ab8aa628665f18f6dc133e6506b92ab    generic    /irods-seq-sr03-ddn-gg07-12-13-14/7766/7766_2#147.bam
  srpipe            1 root;replicate;seq-red;red1;irods-seq-i05-de   6336560777 2012-04-09.03:49 & 7766_2#147.bam
    2ab8aa628665f18f6dc133e6506b92ab    generic    /irods-seq-i05-de/7766/7766_2#147.bam
irods-g1@irods-g1:~$ ichksum -K -n 1 /seq/7766/7766_2#147.bam
ERROR: chksumDataObjUtil: rcDataObjChksum error for /seq/7766/7766_2#147.bam status = -314000 USER_CHKSUM_MISMATCH
ERROR: chksumUtil: chksum error for /seq/7766/7766_2#147.bam, status = -314000 status = -314000 USER_CHKSUM_MISMATCH
Total checksum performed = 1, Failed checksum = 1
irods-g1@irods-g1:~$ ils -L /seq/7766/7766_2#147.bam
  srpipe            0 root;replicate;seq-green;green3;irods-seq-sr03-ddn-gg07-12-13-14   6336560777 2012-04-09.03:46 & 7766_2#147.bam
    2ab8aa628665f18f6dc133e6506b92ab    generic    /irods-seq-sr03-ddn-gg07-12-13-14/7766/7766_2#147.bam
  srpipe            1 root;replicate;seq-red;red1;irods-seq-i05-de   6336560777 2012-04-09.03:49 & 7766_2#147.bam
    2ab8aa628665f18f6dc133e6506b92ab    generic    /irods-seq-i05-de/7766/7766_2#147.bam
irods-g1@irods-g1:~$ ichksum -K -n 0 /seq/7766/7766_2#147.bam
    7766_2#147.bam                    2ab8aa628665f18f6dc133e6506b92ab
Total checksum performed = 1, Failed checksum = 0

irods-g1@irods-g1:~$ ichksum -K -a /seq/7766/7766_2#147.bam
ERROR: chksumDataObjUtil: rcDataObjChksum error for /seq/7766/7766_2#147.bam status = -314000 USER_CHKSUM_MISMATCH
ERROR: chksumUtil: chksum error for /seq/7766/7766_2#147.bam, status = -314000 status = -314000 USER_CHKSUM_MISMATCH
Total checksum performed = 1, Failed checksum = 1
```
Could you suggest a query that would show if we have any replica's without checksums? I thought of `iquest "%s/%s" "select COLL_NAME, DATA_ID where DATA_CHECKSUM = ''"` but I'm not sure what's exactly right, or will catch everything...

**Comment by kript** [comment]
Another us case I've just found is where an object doesn't have an checksum;

```
ils -L /seq/20808/log/20160929_160916_HS21_20808_A_H32HNBCXY.log.tar.xz
  srpipe            0 root;replicate;seq-red;red3;irods-seq-i20-fg            0 2016-09-29.18:25 & 20160929_160916_HS21_20808_A_H32HNBCXY.log.tar.xz
        generic    /irods-seq-i20-fg/20808/log/20160929_160916_HS21_20808_A_H32HNBCXY.log.tar.xz

...

ls -l /irods-seq-i20-fg/20808/log/20160929_160916_HS21_20808_A_H32HNBCXY.log.tar.xz
-rw------- 1 irods irods 18342946 Sep 29 18:25 /irods-seq-i20-fg/20808/log/20160929_160916_HS21_20808_A_H32HNBCXY.log.tar.xz

md5sum /irods-seq-i20-fg/20808/log/20160929_160916_HS21_20808_A_H32HNBCXY.log.tar.xz
1ef0d2a51984284df875a568cdbc31a9  /irods-seq-i20-fg/20808/log/20160929_160916_HS21_20808_A_H32HNBCXY.log.tar.xz

irods@irods-seq-i20:~$ ifsck -K /irods-seq-i20-fg/20808/log/20160929_160916_HS21_20808_A_H32HNBCXY.log.tar.xz
irods@irods-seq-i20:~$ ifsck  /irods-seq-i20-fg/20808/log/20160929_160916_HS21_20808_A_H32HNBCXY.log.tar.xz
irods@irods-seq-i20:~$ 
ichksum -f /seq/20808/log/20160929_160916_HS21_20808_A_H32HNBCXY.log.tar.xz
    20160929_160916_HS21_20808_A_H    1ef0d2a51984284df875a568cdbc31a9
Total checksum performed = 1, Failed checksum = 0
irods-g1@irods-g1:~$ ichksum -K /seq/20808/log/20160929_160916_HS21_20808_A_H32HNBCXY.log.tar.xz
    20160929_160916_HS21_20808_A_H    1ef0d2a51984284df875a568cdbc31a9
Total checksum performed = 1, Failed checksum = 0
irods-g1@irods-g1:~$ ils -L /seq/20808/log/20160929_160916_HS21_20808_A_H32HNBCXY.log.tar.xz
  srpipe            0 root;replicate;seq-red;red3;irods-seq-i20-fg            0 2016-09-29.18:25 & 20160929_160916_HS21_20808_A_H32HNBCXY.log.tar.xz
    1ef0d2a51984284df875a568cdbc31a9    generic    /irods-seq-i20-fg/20808/log/20160929_160916_HS21_20808_A_H32HNBCXY.log.tar.xz

```
So if there is no checksum, neither `ifsck` or `ichksum` complain, but they _do_ generate a new checksum if required.

**Comment by kript** [comment]
Not sure if this needs a separate issue or not, but can we have `ichksum -K` report back when it updates the checksum (as above).

**Comment by kript** [comment]
Any thoughts on `ifsck` not reporting checksum validation failures? This was in the original issue, but may have been obscured by subsequent discussions. We need to check all our files, and would rather not write our own tool when this is available.

**Comment by trel** [comment]
I made a 6-byte file with two checksummed replicas.

```
$ iget foo -
12345
$ ils -L foo
  rods              0 demoResc            6 2017-03-22.15:56 & foo
    sha2:8zrjvJoizXVkmQp5R4mVRAmXcBOWb7Go9Dw1d2uDOpU=    generic    /var/lib/irods/iRODS/Vault/home/rods/foo
  rods              1 ufs            6 2017-03-23.11:35 & foo
    sha2:8zrjvJoizXVkmQp5R4mVRAmXcBOWb7Go9Dw1d2uDOpU=    generic    /tmp/irods/ufsvault/home/rods/foo
```

Then I changed the `12345` to `12346` in replica 1 (`/tmp/irods/ufsvault/home/rods/foo`), keeping the file size consistent.

Then I ran `ifsck` on the two replicas' physical paths.

Replica 0 passed both checks - no problems found.
```
$ ifsck /var/lib/irods/iRODS/Vault/home/rods/foo; echo $?
0
$ ifsck -K /var/lib/irods/iRODS/Vault/home/rods/foo; echo $?
0
```

Replica 1 passed the size check, but failed the checksum check.
```
$ ifsck /tmp/irods/ufsvault/home/rods/foo; echo $?
0
$ ifsck -K /tmp/irods/ufsvault/home/rods/foo; echo $?
CORRUPTION: local file /tmp/irods/ufsvault/home/rods/foo checksum not consistent with iRODS object /tempZone/home/rods/foo checksum.
112
```

These results are working as I expected.

Are you seeing a different behavior?

**Comment by trel** [comment]
I changed the `12346` to `123467`, making the file size incorrect as well.

```
$ ifsck /tmp/irods/ufsvault/home/rods/foo; echo $?
CORRUPTION: local file /tmp/irods/ufsvault/home/rods/foo size not consistent with iRODS object /tempZone/home/rods/foo size.
0
```

The size corruption was detected correctly, but the return code should be non-zero.

**Comment by kript** [comment]
We're seeing different behaviour from you, I think. I expect the same things you're seeing, but in the initial comment opening the issue I show a file with two replicas where on-disk one of them has a different checksum (the one on irods-seq-i05-de), and `ifsck` doesn't pick this up when run against the on-disk file.

**Comment by trel** [comment]
So, if the original files in this thread have not been touched... can you please run again...

```
irods-seq-i05:~$ ienv | grep Version
```

```
irods-seq-i05:~$ ifsck -K /irods-seq-i05-de/7766/7766_2#147.bam; echo $?
```

**Comment by mcv21** [comment]
```irods@irods-seq-i05:~$ ienv | grep Version
NOTICE: Release Version = rods4.1.10, API Version = d
irods@irods-seq-i05:~$ ifsck -K /irods-seq-i05-de/7766/7766_2#147.bam ; echo $?
192
```

**Comment by trel** [comment]
Okay, confirmed - I was also using 4.1.10.

This means that some other error is occurring and is silently returning and resulting in a 192 return code.  We'll look into increasing the clarity of what is happening.

Are the permissions good on /irods-seq-i05-de/7766/7766_2#147.bam?

**Comment by mcv21** [comment]
Right, I understand. The problem is that `status` ends up being set to -808000 and then that is passed unvarnished to `exit`. This is unfortunate, as exit does the equivalent of `& 0xff`, which is why we end up with a return value of 192.

irods probably doesn't want to be doing that - notably, the following error values, if fed to `exit` in this manner will result in a return code of 0 (i.e. success):
```
SYS_INVALID_RESC_INPUT -32000
SYS_COLLINFO_2_FORMAT_ERR -64000
SYS_SRC_DEST_RESC_COMPOUND_TYPE -96000
CANT_REG_IN_VAULT_FILE -128000
SYS_SOCK_LISTEN_ERROR -160000
USER_DIRECT_RESC_INPUT_ERR -320000
NO_MORE_RESULT -352000
UNIX_FILE_READ_ERR -512000
HDFS_FILE_STAT_ERR -736000
CAT_INVALID_CLIENT_USER -832000
CAT_TICKET_WRITE_USES_EXCEEDED -896000
GSI_ERROR_TOKEN_TOO_LARGE -928000
KRB_SOCKET_READ_ERROR -960000
PAM_AUTH_NOT_BUILT_INTO_SERVER -992000
DESTRESCNAME_EMPTY_IN_STRUCT_ERR -1024000
COLLCOMMENTS_EMPTY_IN_STRUCT_ERR -1056000
RETRY_WITHOUT_RECOVERY_ERR -1088000
RE_PATTERN_NOT_MATCHED -1216000
PHP_EXEC_SCRIPT_ERR -1600000
CLIENT_NEGOTIATION_ERROR -1824000
NETCDF_UNMATCHED_NAME_ERR -2016000
OOI_JSON_NO_ANSWER_ERR -2208000
```

-808000 is `CAT_NO_ROWS_FOUND`, and indeed:
```
irods@irods-seq-i05:~$ ils /irods-seq-i05-de/7766/7766_2#147.bam
ERROR: lsUtil: srcPath /irods-seq-i05-de/7766/7766_2#147.bam does not exist or user lacks access permission
```

ISTM that ifsck should report an error more along these lines than exiting silently with a misleading error code

**Comment by kellerb** [comment]
I have a build of `ifsck` that logs the two (that I've found so far) ignored error cases. I'll email you the link.

The `if` statements with unhandled `else`s are [a](https://github.com/irods/irods/blob/4.1.10/iRODS/lib/core/src/fsckUtil.cpp#L135) and [b](https://github.com/irods/irods/blob/4.1.10/iRODS/lib/core/src/fsckUtil.cpp#L144).

**Comment by kript** [comment]
Just to confirm, we get the same result if we add the `irods` user with read permissions and try the same `ifsck`

**Comment by mcv21** [comment]
With the add of a debug-enabled build and gdb, I observe that the query that `ifsck` is running is equivalent to:
```irods@irods-seq-i05:~$ iquest "SELECT DATA_NAME, COLL_NAME, DATA_SIZE, DATA_CHECKSUM WHERE DATA_PATH ='/irods-seq-i05-de/7766/7766_2#147.bam' AND RESC_LOC like 'irods-seq-i05%' || ='irods-seq-i05'"
CAT_NO_ROWS_FOUND: Nothing was found matching your query
```

The problem is `RESC_LOC`, because it isn't set:
```irods@irods-seq-i05:~$ iquest "SELECT DATA_NAME, COLL_NAME, DATA_SIZE, DATA_CHECKSUM, RESC_LOC WHERE DATA_PATH ='/irods-seq-i05-de/7766/7766_2#147.bam'"
DATA_NAME = 7766_2#147.bam
COLL_NAME = /seq/7766
DATA_SIZE = 6336560777
DATA_CHECKSUM = 2ab8aa628665f18f6dc133e6506b92ab
RESC_LOC = EMPTY_RESC_HOST
------------------------------------------------------------
```

The query is constructed in `chkObjConsistency` in fsckUtil.cpp ll 122-132:
```
    memset( &genQueryInp, 0, sizeof( genQueryInp ) );
    addInxIval( &genQueryInp.selectInp, COL_DATA_NAME, 1 );
    addInxIval( &genQueryInp.selectInp, COL_COLL_NAME, 1 );
    addInxIval( &genQueryInp.selectInp, COL_DATA_SIZE, 1 );
    addInxIval( &genQueryInp.selectInp, COL_D_DATA_CHECKSUM, 1 );
    genQueryInp.maxRows = MAX_SQL_ROWS;

    snprintf( condStr, MAX_NAME_LEN, "='%s'", inpPath );
    addInxVal( &genQueryInp.sqlCondInp, COL_D_DATA_PATH, condStr );
    snprintf( condStr, MAX_NAME_LEN, "like '%s%s' || ='%s'", hostname, "%", hostname );
    addInxVal( &genQueryInp.sqlCondInp, COL_R_LOC, condStr );
```
How terrible an idea would it be to comment out the last 2 lines (so removing the `RESC_LOC` condition)? A quick iquest suggests that essentially none of our records have it defined:
```
irods@irods-seq-i05:~$ iquest "SELECT COUNT(DATA_ID)"
DATA_ID = 61670819
------------------------------------------------------------
irods@irods-seq-i05:~$ iquest "SELECT COUNT(DATA_ID) WHERE RESC_LOC = 'EMPTY_RESC_HOST'"
DATA_ID = 61670831
------------------------------------------------------------
```

**Comment by mcv21** [comment]
Better might be...?
```diff
diff --git a/iRODS/lib/core/src/fsckUtil.cpp b/iRODS/lib/core/src/fsckUtil.cpp
index 325d648..483550e 100644
--- a/iRODS/lib/core/src/fsckUtil.cpp
+++ b/iRODS/lib/core/src/fsckUtil.cpp
@@ -128,7 +128,7 @@ chkObjConsistency( rcComm_t *conn, rodsArguments_t *myRodsAr
 
     snprintf( condStr, MAX_NAME_LEN, "='%s'", inpPath );
     addInxVal( &genQueryInp.sqlCondInp, COL_D_DATA_PATH, condStr );
-    snprintf( condStr, MAX_NAME_LEN, "like '%s%s' || ='%s'", hostname, "%", hos
+    snprintf( condStr, MAX_NAME_LEN, "like '%s%%' || ='%s' || ='EMPTY_RESC_HOST
     addInxVal( &genQueryInp.sqlCondInp, COL_R_LOC, condStr );
 
     status =  rcGenQuery( conn, &genQueryInp, &genQueryOut );
```

**Comment by kript** [comment]
Confirming that a debug build with the patch above runs for us and correctly reports a failed checksum.
@trel were you using a compound resource when you had trouble replicating our results? We think that RESC_LOC is only set if compound resources _aren't_ in use..

**Comment by keithj** [comment]
Is #3288 relevant?

**Comment by keithj** [comment]
On a fresh install of 4.1.10 I have `iput` and `ichksum`d a file (containing the string `hello`) into both a regular resource (file name `hello`) and a compound resource (file name`hello2`). 

````
$ ils -lL /tempZone/home/ubuntu
  ubuntu            0 root;random1;unixbar            6 2017-03-31.09:07 & hello
    b1946ac92492d2347c6235b4d2611184    generic    /mnt/bar/home/ubuntu/hello
  ubuntu            0 demoResc            6 2017-03-31.12:33 & hello2
    b1946ac92492d2347c6235b4d2611184    generic    /var/lib/irods/iRODS/Vault/home/ubuntu/hello2
````
I corrupted the files on disk by editing them to contain the word `lemon` instead and then ran `ifsck` on them:

````
$ cat /mnt/bar/home/ubuntu/hello
lemon
$ cat  /var/lib/irods/iRODS/Vault/home/ubuntu/hello2
lemon
$ md5sum  /mnt/bar/home/ubuntu/hello /var/lib/irods/iRODS/Vault/home/ubuntu/hello2
89d5a65aa64edf045412a78ce4e1c1fe  /mnt/bar/home/ubuntu/hello
89d5a65aa64edf045412a78ce4e1c1fe  /var/lib/irods/iRODS/Vault/home/ubuntu/hello2
````

Running `ifsck`:

````
$ ifsck -K /mnt/bar/home/ubuntu/hello ; echo $?
192
$ ifsck -K /var/lib/irods/iRODS/Vault/home/ubuntu/hello2 ; echo $?
CORRUPTION: local file /var/lib/irods/iRODS/Vault/home/ubuntu/hello2 checksum not consistent with iRODS object /tempZone/home/ubuntu/hello2 checksum.
112
````
````
ICAT=# select distinct R_DATA_MAIN.data_name ,R_COLL_MAIN.coll_name ,R_DATA_MAIN.data_size ,R_DATA_MAIN.data_checksum  from  R_DATA_MAIN , R_COLL_MAIN , R_RESC_MAIN  where R_DATA_MAIN.data_path ='/mnt/bar/home/ubuntu/hello'  AND (  R_RESC_MAIN.resc_net like 'ifscktest%'  OR  R_RESC_MAIN.resc_net  ='ifscktest'  )  AND R_COLL_MAIN.coll_id = R_DATA_MAIN.coll_id  AND R_RESC_MAIN.resc_name = R_DATA_MAIN.resc_name  order by R_COLL_MAIN.coll_name, R_DATA_MAIN.data_name;
 data_name | coll_name | data_size | data_checksum 
-----------+-----------+-----------+---------------
````
````
ICAT=# select distinct R_DATA_MAIN.data_name ,R_COLL_MAIN.coll_name ,R_DATA_MAIN.data_size ,R_DATA_MAIN.data_checksum  from  R_DATA_MAIN , R_COLL_MAIN , R_RESC_MAIN  where R_DATA_MAIN.data_path ='/var/lib/irods/iRODS/Vault/home/ubuntu/hello2'  AND (  R_RESC_MAIN.resc_net like 'ifscktest%'  OR  R_RESC_MAIN.resc_net  ='ifscktest'  )  AND R_COLL_MAIN.coll_id = R_DATA_MAIN.coll_id  AND R_RESC_MAIN.resc_name = R_DATA_MAIN.resc_name  order by R_COLL_MAIN.coll_name, R_DATA_MAIN.data_name;
 data_name |       coll_name       | data_size |          data_checksum           
-----------+-----------------------+-----------+----------------------------------
 hello2    | /tempZone/home/ubuntu |         6 | b1946ac92492d2347c6235b4d2611184
(1 row)
````

The "hostname" that is expected to match the constraint `'ifscktest%` is always `EMPTY_RESC_HOST`
in the compound resource:

````
ICAT=# select distinct R_DATA_MAIN.data_name, R_COLL_MAIN.coll_name, R_DATA_MAIN.data_size ,R_DATA_MAIN.data_checksum, R_RESC_MAIN.resc_net from  R_DATA_MAIN , R_COLL_MAIN , R_RESC_MAIN  where R_DATA_MAIN.data_path ='/mnt/bar/home/ubuntu/hello'  AND R_COLL_MAIN.coll_id = R_DATA_MAIN.coll_id  AND R_RESC_MAIN.resc_name = R_DATA_MAIN.resc_name  order by R_COLL_MAIN.coll_name, R_DATA_MAIN.data_name;

 data_name |       coll_name       | data_size |          data_checksum           |    resc_net     
-----------+-----------------------+-----------+----------------------------------+-----------------
 hello     | /tempZone/home/ubuntu |         6 | b1946ac92492d2347c6235b4d2611184 | EMPTY_RESC_HOST
(1 row)
````

Whereas in a regular resource it is a hostname:

````
ICAT=# select distinct R_DATA_MAIN.data_name, R_COLL_MAIN.coll_name, R_DATA_MAIN.data_size ,R_DATA_MAIN.data_checksum, R_RESC_MAIN.resc_net from  R_DATA_MAIN , R_COLL_MAIN , R_RESC_MAIN  where R_DATA_MAIN.data_path ='/var/lib/irods/iRODS/Vault/home/ubuntu/hello2'  AND R_COLL_MAIN.coll_id = R_DATA_MAIN.coll_id  AND R_RESC_MAIN.resc_name = R_DATA_MAIN.resc_name  order by R_COLL_MAIN.coll_name, R_DATA_MAIN.data_name;
 data_name |       coll_name       | data_size |          data_checksum           | resc_net  
-----------+-----------------------+-----------+----------------------------------+-----------
 hello2    | /tempZone/home/ubuntu |         6 | b1946ac92492d2347c6235b4d2611184 | ifscktest
(1 row)
````


Is it fair to conclude that `ifsck -K`  does not work on compound resources?

**Comment by kellerb** [comment]
Thank you for all of this investigation, everything that has been said appears correct to me.

I think, as you all have pointed out, that the core problem is that genquery, in 4.1, links a data object replica against the resource that is at the root of the hierachy. This is why, e.g.
```
iquest "SELECT COUNT(DATA_ID) WHERE RESC_LOC = 'EMPTY_RESC_HOST'"
```
counts basically all of your data objects; most of your data objects are in the big hierarchy that has the `passthru` resource at the top, and the `RESC_LOC` of a `passthru` resource is empty (as it is for all coordinating resources).

With regard to changing the genquery used by `ifsck -K`, the concern would be making sure that the genquery only returns the one, correct result. The `ifsck` code just uses the [values from the first row returned by the genquery](https://github.com/irods/irods/blob/4.1.10/iRODS/lib/core/src/fsckUtil.cpp#L136-L139), so if we remove the hostname check (or allow `EMPTY_RESC_HOST` which will match on basically all of your data objects) we need to make sure that the physical path condition is enough to filter out the unwanted rows. I believe that with each of your resources having different vault paths (they have the server name in them I believe), this would work for your case. We'll have to do some more thinking about what this change would do in general.

The good-news™ is that in iRODS 4.2, genquery should return the `RESC_LOC` of the actual resource the replica is on (the leaf resource instead of the root), suggesting that in theory `ifsck -K` should work. I have not tested this yet. Also, this doesn't help you currently, of course.

**Comment by kellerb** [comment]
Wrt. the `EMPTY_RESC_HOST` issue, for 4.1 we may be able to augment `ifsck` to accept a `-R <full_resource_hierarchy>` option. This would, if used, replace the hostname check in the genquery.

**Comment by kript** [comment]
So, that would be running `ifsck -K -R root;random1;unixbar /mnt/bar/home/ubuntu/hello` (using @keithj most recent example)? 
I'm pretty sure that could be made to work for us, thank you. I'd have to figure out some way to script/extract that value for each of our hundred or so resources, as we'd want to put in a cron job for each resource at some frequency, and hand writing that many would be tedious and error prone.. ;-)

**Comment by kellerb** [comment]
Yes, except you would need to put the resource hierarchy in quotes so that your shell doesn't get upset about the semicolons.
