### ISSUE TITLE
federated irm exits with success when fails to delete file owned by another user

### ISSUE THREAD

**Issue by keithj** [irods/irods#3493]
- [x] 4-1-stable
- [x] 4-2-stable
- [x] master

---

````
$ dpkg -l | grep rods
ii  wtsi-irods-auth-plugin-kerberos         4.1.10-RENCI1.4-sanger4                             wtsi-irods-auth-plugin-kerberos
ii  wtsi-irods-icommands                    4.1.10~sanger2                                      wtsi-irods-icommands

$ ienv
NOTICE: Release Version = rods4.1.10, API Version = d
NOTICE: irods_session_environment_file -
/nfs/users/nfs_k/kdj/.irods/irods_environment.json.cwd
NOTICE: irods_user_name - kdj
[...]

 ils -A /seq/21626/21626_1#4_phix_F0x900.stats.557705391
  /seq/21626/21626_1#4_phix_F0x900.stats.557705391
        ACL - trace#Sanger1:read object   dnap_ro#seq:read object
srpipe#Sanger1:own   rodsBoot#seq:own   irods-g1#seq:own   public#seq:read
object   psdpipe#Sanger1:read object
````

I don't have permission to delete the above file. Expected behaviour is that when I try
I get an error message and `irm` exits with a non-zero code. Observed behaviour is
that it appears superficially that the file is deleted.

````
$ irm /seq/21626/21626_1#4_phix_F0x900.stats.557705391
$ echo $?
0
````

However, it is not deleted (see below), rather the exit code is incorrect and error message
is missing.

````
$ ils /seq/21626/21626_1#4_phix_F0x900.stats.557705391
  /seq/21626/21626_1#4_phix_F0x900.stats.557705391
````

Please may this be included in 4.1.11?

**Comment by kellerb** [comment]
What zone is `kdj` a member of? Which iRODS server does the `irm` connect to, i.e what is the `irods_host` entry in your `irods_environment.json`, and is that a resource server or the iCAT server, and in which zone?

**Comment by kellerb** [comment]
I have replicated the error by having a user from `zoneA`, connected to `zoneA`'s iCAT, attempt to delete a data object in `zoneB`, when the user only has `read object` permission on the data object.

**Comment by kellerb** [comment]
The local icat is redirecting the unlink to the remote icat, but then [ignoring the return code](https://github.com/irods/irods/blob/4.1.10/iRODS/server/api/src/rsDataObjUnlink.cpp#L54-L55).

Returning the value from `rcDataObjUnlink()` does cause `irm` to have a return code of `3` and to print the following:

```
ERROR: rmUtil: rm error for /tempZone/home/share/file, status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
```

**Comment by keithj** [comment]
Thanks for looking at this; yes, I was in one zone, connected to its iCAT, while the data object was in a federated zone.
