### ISSUE TITLE
ichksum -a should report which file fails the checksum validation

### ISSUE THREAD

**Issue by kript** [irods/irods#3499]
- [x] 4-1-stable
- [x] 4-2-stable
- [x] master

---

Currently `ichksum` doesn't tell you which replica is bad when run with `-a`

```
 ichksum -r -v -a -K /seq/13566/13566_1#8.bam
ERROR: chksumDataObjUtil: rcDataObjChksum error for /seq/13566/13566_1#8.bam status = -314000 USER_CHKSUM_MISMATCH
ERROR: chksumUtil: chksum error for /seq/13566/13566_1#8.bam, status = -314000 status = -314000 USER_CHKSUM_MISMATCH
Total checksum performed = 1, Failed checksum = 1
```
The behavior is the same if one uses `-V` instead of `-v`

The only way to get this information is to get the number of replicas for the file and then run ichksum for each replica, so could we have ichksum report which replica failed please?

**Comment by kript** [comment]
Due to our misunderstanding of the default behavior of `ichksum` we have quite a backlog to go through to verify files, so could we get this added to 4.1.11 please?

**Comment by kellerb** [comment]
How does this look?

```
$ ichksum -r -v -a -K /tempZone/home/rods/file1
ERROR: chksumDataObjUtil: rcDataObjChksum error for /tempZone/home/rods/file1 status = -314000 USER_CHKSUM_MISMATCH
Level 0: verifyDatObjChksum: computed chksum [sha2:iak9YgrDs9s62l0OxCW5E7GOWRVnvu57wu0cCfb+AdE=] != icat value [sha2:YgvjqkSllN2X86jidSsntULdIScEzTwK6O4ybFQS99I=] for [/tempZone/home/rods/file1] hierarchy [demoResc] replNum [0]
ERROR: chksumUtil: chksum error for /tempZone/home/rods/file1, status = -314000 status = -314000 USER_CHKSUM_MISMATCH
Total checksum performed = 1, Failed checksum = 1
```

Incidentally, the checksum verification for a given data object stops at the first bad replica found.

**Comment by kript** [comment]
Thank you, yes.  Does the Level 0 correspond to a DEBUG level, or is it printed no matter the level, if so, what does it refer to (apologies if this is in the man page, can't check right now)?

Do the checks have to stop at the first value? That would imply that the rest are OK, and re-running the tool N times for N replicas doesn't sound optimal.  Its hard to tell from the output how many checksums _could_ have been performed, so IMHO, I think it should continue to check, but if that would break other behaviour, perhaps it could so so only if another flag was defined (e.g. `-C` for Continue)?

**Comment by kellerb** [comment]
Wrt. `Level 0`: that is the default way that the client prints error strings sent from the server. Had the server sent two error strings, the first would be `Level 0` and the second would be `Level 1`. In this particular instance, it doesn't really mean anything. If the code were changed to report all bad replicas, then then more levels would be used.

Wrt. no longer stopping at the first bad replica: I will confer with the chiefs and try to get an idea of what changing that would affect.

**Comment by kellerb** [comment]
I have made a [new issue](https://github.com/irods/irods/issues/3536) for the "don't stop checking replica checksums at the first mismatch" request.
