### ISSUE TITLE
ifsck fails for data in resource hierarchies

### ISSUE THREAD

**Issue by kript** [irods/irods#3503]
- [x] master
- [x] 4-2-stable
- [x] 4-1-stable
----

In issue #3492 we found that one of the errors `ifsck` was giving was related to permissions. This is probably due to how we have our iRODS systems deployed - often (but not always) the rods server acting as the interface to the iCAT runs as a different username than the iRES servers, e.g. `irods-icat` and `irods`.  This gives us a problem with command like `ichksum` (#3265) are run on the local filesystem, as the files will have gone into iRODS with, e.g. irods-icat#NPGZone as an owner/read access but the tool running the checksum on the iRES is irods#NPGZone, and so we get permission denied errors, even though both are `rodsadmin` users.

Other commands have the admin flag (`-M`) to help with this, it would be helpful here as well.

**Comment by jaking92** [comment]
This appears to be similar to #3419 in that the root issue is 4.1's handling of resource hierarchies. This has been fixed in 4.2, but we will continue to investigate back-porting a solution for 4.1.

**Comment by jaking92** [comment]
Hi @kript - what version of iRODS are you running? I believe this issue has been resolved in **[this commit](https://github.com/irods/irods/commit/2663b949b68dc200fb4d0c7f277ccc6d07e7a679)**, which is in 4.1.11. Not sure if you had a chance to **[try this out](https://github.com/irods/irods/issues/3492#issuecomment-291281996)**, but if it fixes the issue, then I think we can close this out. Thanks!

**Comment by kript** [comment]
Ah, we're on 4.1.10 live and 4.1.11 in dev, I'll give it a try, thanks!

**Comment by alanking** [comment]
Better late than never! Did you try running this with the `-R` flag that was added along with the full resource hierarchy as described here: https://github.com/irods/irods/issues/3492#issuecomment-291265388?

**Comment by alanking** [comment]
Did you mean to use `ifsck` in the above? `ichksum` is run against data objects and you appear to be providing physical paths as arguments.

**Comment by kript** [comment]
🤦‍♂️ well, that's what I get for trying to rush and do too many things at once! You are of course, quite right.

So yes, this fixes the issue!

```
:~$ ifsck  -R 'root;replicate;green;green1;irods-seq-sr01-ddn-ra08-36-37-38' -r /irods-seq-sr01-ddn-ra08-36-37-38/home/jc18#Sanger1-dev/
:~$ echo "CORRUPTIONTEST" >> /irods-seq-sr01-ddn-ra08-36-37-38/home/jc18#Sanger1-dev/24174_5#888.cram
:~$ ifsck  -R 'root;replicate;green;green1;irods-seq-sr01-ddn-ra08-36-37-38' -r /irods-seq-sr01-ddn-ra08-36-37-38/home/jc18#Sanger1-dev/
CORRUPTION: local file [/irods-seq-sr01-ddn-ra08-36-37-38/home/jc18#Sanger1-dev/24174_5#888.cram] size not consistent with iRODS object [/seq-dev/home/jc18#Sanger1-dev/24174_5#888.cram] size.
```
🎆 🍾 
Can I ask that the -R flag get added to the man page and command line help, please, along with an illustrative example for ~when I forget this conversation~ future me?

cheers

John

**Comment by trel** [comment]
Working on the help text - input welcome - see PR https://github.com/irods/irods/pull/4087

Will then get the same text into 4.2+.
