### ISSUE TITLE
API dynPEPs signatures are malformed

### ISSUE THREAD

**Issue by jasoncoposky** [irods/irods#3511]
`pep_api_data_obj_put_pre(*ARG0,*ARG1,*ARG2,*ARG3,*ARG4) {}` 

currently requires an additional `_api` to trigger:

`pep_api_api_data_obj_put_pre(*ARG0,*ARG1,*ARG2,*ARG3,*ARG4) {}`

due to the incorrect building of the dynPEP rule name in `apiHandler.hpp:call_handler()`

**Comment by trel** [comment]
4-2-stable cherry-pick please
