### ISSUE TITLE
Clients can still write when quota is exceeded

### ISSUE THREAD

**Issue by kellerb** [irods/irods#3513]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
-----

https://github.com/irods/python-irodsclient/issues/68

**Comment by trel** [comment]
Is this still true?

**Comment by korydraughn** [comment]
I've verified that quotas are enforced.

I'll write some tests for this before closing it.

**Comment by korydraughn** [comment]
Closing as resolved.

See conversation starting at https://github.com/irods/irods/pull/6962#issue-1622286517 for additional info.
