### ISSUE TITLE
irepl and ils can't handle data objects with long paths

### ISSUE THREAD

**Issue by tedgin** [irods/irods#3515]
I'm using iRODS 4.1.9 with the postgresql 9.3 plugin.

When I attempt to replicate a data object with a long path name, `irepl` tells me that it doesn't exist.  The cut off for the path length seems to be around 400 characters, way short of the 2700 character limit.

`ils` has the same problem and generates the same error message in the server logs.

Here's an example.

```
ipc_admin@prod? irepl -M -R taccCorralRes '/iplant/home/XXXXXXXXXXXXX/phytoMorph/kinematicsGravitropism/2016_9_10_21_23/{date^160906}{genotype^fer-4_01}{treatment^ hypoosmotic (75 mM mannitol), hyperosmotic (150 mM mannitol)}{rest^2d strat, 1-4 MS, 1% suc, 1% agar 150 mM mannitol, pH 5.8_5d}_before/{date^160902}{genotype^WT_01}{treatment^ hypoosmotic (100 mM mannitol), hyperosmotic (150 mM mannitol)}{rest^2d strat, 1-4 MS, 1% suc, 1% agar 150 mM mannitol, pH 5.8_5d}_hyper_angle_graph.tif'
ERROR: replUtil: srcPath /iplant/home/XXXXXXXXXXXXX/phytoMorph/kinematicsGravitropism/2016_9_10_21_23/{date^160906}{genotype^fer-4_01}{treatment^ hypoosmotic (75 mM mannitol), hyperosmotic (150 mM mannitol)}{rest^2d strat, 1-4 MS, 1% suc, 1% agar 150 mM mannitol, pH 5.8_5d}_before/{date^160902}{genotype^WT_01}{treatment^ hypoosmotic (100 mM mannitol), hyperosmotic (150 mM mannitol)}{rest^2d strat, 1-4 MS, 1% suc, 1% agar 150 mM mannitol, pH 5.8_5d}_hyper_angle_graph.tif does not exist
ERROR: replUtil: invalid repl objType 0 for /iplant/home/XXXXXXXXXXXXX/phytoMorph/kinematicsGravitropism/2016_9_10_21_23/{date^160906}{genotype^fer-4_01}{treatment^ hypoosmotic (75 mM mannitol), hyperosmotic (150 mM mannitol)}{rest^2d strat, 1-4 MS, 1% suc, 1% agar 150 mM mannitol, pH 5.8_5d}_before/{date^160902}{genotype^WT_01}{treatment^ hypoosmotic (100 mM mannitol), hyperosmotic (150 mM mannitol)}{rest^2d strat, 1-4 MS, 1% suc, 1% agar 150 mM mannitol, pH 5.8_5d}_hyper_angle_graph.tif

```

Here's the corresponding server log.

```
§• Apr 13 09:20:28 pid:4470 NOTICE: Agent process 36417 started for puser=ipc_admin and cuser=ipc
_admin from 128.196.38.31
 • Apr 13 09:20:28 pid:36417 ERROR: rstrcpy not enough space in dest, slen:449, maxLen:395
 • Apr 13 09:20:28 pid:36417 NOTICE: _rsGenQuery: genQuery status = -306000
 • Apr 13 09:20:28 pid:36417 NOTICE: rsGenQuery: _rsGenQuery failed, status = -306000
 • Apr 13 09:20:28 pid:36417 NOTICE: readAndProcClientMsg: received disconnect msg from client
 • Apr 13 09:20:28 pid:36417 NOTICE: Agent exiting with status = 0
 • Apr 13 09:20:28 pid:4470 NOTICE: Agent process 36417 exited with status 0
```

**Comment by kellerb** [comment]
[This](https://github.com/irods/irods/blob/4.1.10/plugins/database/src/general_query.cpp#L1198-L1199) is the call to `rstrcpy()` that is complaining. [`addInClauseToWhereForParentOf()`](https://github.com/irods/irods/blob/4.1.10/plugins/database/src/general_query.cpp#L1171-L1212) uses [space](https://github.com/irods/irods/blob/4.1.10/plugins/database/src/general_query.cpp#L1176) quadratic in (the number of ` ` + the number of `/`) in the logical path. The space reserved for this is currently defined at compile time to be 12,000 bytes. Your path would require only about 1,500 more bytes. A worse-case-scenario string of 1,024 spaces needs about a megabyte.

**Comment by tedgin** [comment]
Is there a work around?

**Comment by kellerb** [comment]
Not that I am aware of. We will make the [buffer](https://github.com/irods/irods/blob/4.1.10/plugins/database/src/general_query.cpp#L1176) a little bit bigger in 4.1.11 so that your example works.
