### ISSUE TITLE
'ireg --repl' should disallow coordinating resource as target resource

### ISSUE THREAD

**Issue by trel** [irods/irods#3517]
From https://github.com/irods/irods/issues/3495#issuecomment-290225229 ...

```
@irods-seq-i01:~$ ireg -Kk --repl -R root /irods-seq-i01-de/21052/qc/21052_3#188.insert_size.json /seq/21052/qc/21052_3#188.insert_size.json

@irods-g1:~$ ils -L /seq/21052/qc/21052_3#188.insert_size.json
  srpipe            0 root;replicate;seq-red;red1;irods-seq-i01-bc            0 2016-10-26.06:14 & 21052_3#188.insert_size.json
    a0893189a7d929f9dbd351d86a5f6a40    generic    /irods-seq-i01-bc/21052/qc/21052_3#188.insert_size.json
  srpipe            1 root;replicate;seq-red;red1;irods-seq-i01-bc            0 2017-03-29.15:56 & 21052_3#188.insert_size.json
    a0893189a7d929f9dbd351d86a5f6a40    generic    /irods-seq-i01-de/21052/qc/21052_3#188.insert_size.json
```

`ireg --repl` should not allow users to specify a coordinating resource as the target resource for the newly to-be-registered replica (in this case, `root` should not be allowed).

Only leaf resources should be allowed (in this case, `irods-seq-i01-de`).

**Comment by trel** [comment]
just so not forgotton... need to cherry-pick https://github.com/irods/irods/commit/4dd53841669dd92171d9ff667cea2a0cc6d32e9c to master

**Comment by rskarbez** [comment]
It's in there, isn't it? https://github.com/irods/irods/commit/6008f51c322dcf5fc74363ac19ec690e2c29b2b1

**Comment by trel** [comment]
ah, i missed the commit 20min after you closed.  apologies.
