### ISSUE TITLE
gethostbyname() is obsolete - irods should use getaddrinfo() instead

### ISSUE THREAD

**Issue by mcv21** [irods/irods#3518]
- [x] 4-1-stable
- [x] 4-2-stable
- [x] master

---

We discussed this in our concall today, and agreed that an issue should be created.

Briefly - `gethostbyname()` is obsolete, and irods should be using `getaddrinfo()` instead. Quoting from their man-pages:

> The gethostbyname*(), gethostbyaddr*(), herror(), and hstrerror() functions  are  obsolete.  Applications should use getaddrinfo(3), getnameinfo(3), and gai_strerror(3) instead.

> The getaddrinfo() function combines the functionality provided by the gethostbyname(3) and getservbyname(3) functions into a single  interface,  but  unlike  the latter functions, getaddrinfo() is reentrant and allows programs to eliminate  IPv4-versus-IPv6  dependencies.

**Comment by kellerb** [comment]
Note to self:
Per local testing and Zookeeper bug threads [a](https://issues.apache.org/jira/browse/ZOOKEEPER-2298) and [b](https://issues.apache.org/jira/browse/MESOS-2186), `getaddrinfo()` can return `EAI_NONAME` for temporary, re-tryable errors (which appears at odds with its documentation), so when using `getaddrinfo()` we need to retry on both `EAI_AGAIN` and `EAI_NONAME`.

**Comment by kellerb** [comment]
Additional note to self:
Also seeing `EAI_NODATA` intermittently. I believe this stops happening if `hint.ai_family = AF_INET`, i.e. if we are not requesting IPv6 addresses. Could be an issue with the RENCI name servers.
