### ISSUE TITLE
iRODS not well suited to myriad tiny files storage?

### ISSUE THREAD

**Issue by markehammons** [irods/irods#3521]
Hi all,
I'm trying to replicate my data using irsync, and it's taking unbelievably long. And it's not because my transfer speed is low, but rather because I have a ton of 4MB files on my irods and it takes 0.3 seconds to transfer each. I also noticed while using jargon that traversing the file tree and getting a flat list of files in a directory takes a heinously long amount of time using File.listfiles() and File.isDirectory/isFile. Am I using iRODS wrong? should I be storing larger artifacts? Is there a method in jargon which will hand me file paths of all files (not directories) in a directory tree faster than using IRODSFile? 
Thanks

**Comment by jasoncoposky** [comment]
iRODS has a bulk option for a number of commands, depending on the direction of your irsync you can use the ibun command to create a tar file of the small object which can then be sync'ed across iRODS.  From there you can unbundle the file which will bulk register the subfiles.

For issues regarding Jargon you can post issues here: https://github.com/DICE-UNC/jargon

**Comment by trel** [comment]
@markehammons is there anything else we can do for you in this issue?  if not, i'll close it.  thanks.

**Comment by markehammons** [comment]
@trel I've found that there are lower level abstractions that work better for me. So I consider the issue resolved. Thanks 👍

**Comment by trel** [comment]
Works for me.  Thanks.
