### ISSUE TITLE
PAM passwords not allowing @, &, =, or ;

### ISSUE THREAD

**Issue by trel** [irods/irods#3528]
Originally this was #2835 - but was closed for 4.1.5.

The following behavior is still observed on 4-1-stable.

When logging into iRODS via PAM, the following characters still cannot be in the password: `@`, `&`, `=`, and `;` (at, ampersand, equals, and semicolon).

rodsLog:
```
 ERROR: [-]     iRODS/server/api/src/rsAuthPluginRequest.cpp:85:rsAuthPluginRequest :  status [SYS_BAD_INPUT]  errno [] -- message []
        [-]     libpam.cpp:399:pam_auth_agent_request :  status [SYS_BAD_INPUT]  errno [] -- message []
                [-]     iRODS/lib/core/src/irods_kvp_string_parser.cpp:172:parse_escaped_kvp_string :  status [SYS_BAD_INPUT] errno [] -- message [unescaped _assoc token encountered in key or value]
```

**Comment by kellerb** [comment]
@burnce , @mihondo 

Which clients (e.g. icommands) are you using when you see this error?

I am unable to replicate the failure on 4-2-stable or 4.1.10 so far.

**Comment by mihondo** [comment]
Password issues were with PAM authentication - for instance via CyberDuck.

**Comment by kellerb** [comment]
It is possible that this is now an issue with the client code, e.g. CyberDuck.

The clients will need to change the way they send passwords to the iRODS server (i.e. by escaping them per https://github.com/irods/irods/issues/2835).

I believe `@`, `&`, `=`, and `;` should be working with the icommands.

**Comment by burnce** [comment]
@kellerb

We encountered this while using the cloud-browser. The icat is running 4.1.7.

**Comment by mihondo** [comment]
We had problems with cloud browser too... but we didn't use that in production.

We were thinking it is a general PAM issue.

**Comment by kellerb** [comment]
I'm pretty sure this is a problem with the clients. I have let the Jargon people (Jargon is the Java iRODS client implementation used by the cloud-browser and Cyberduck) know.

**Comment by michael-conway** [comment]
the ; is passed properly by the client in the context string and the parsing of the context string is thus confused in the pam auth module.

**Comment by michael-conway** [comment]
We're hitting this, how does one 'escape' said chars? Can we add code on the packing side to do this escaping?

This is happening via MetaLnx.

**Comment by michael-conway** [comment]
...replicated and have a fix on the Jargon side.
