### ISSUE TITLE
ichksum -K does not compare size in database to size in Vault

### ISSUE THREAD

**Issue by kript** [irods/irods#3537]
- [x] 4-1-stable
- [x] 4-2-stable
- [x] master

---

We have found a situation in 4.1.10 (with rebalance debug binary) where an object reported by iRODS as zero length file (incorrectly so - contains data on disk, out of the scope of this issue..), having a checksum, is not flagged bad by `ichksum` but causes the `rebalance` operation to fail with a checksum error. 

error from rebalance;
```
~/sanger-replication-rebalance-debug/trial_002$ iadmin modresc root rebalance
ERROR: rcGeneralAdmin failed with error -314000 USER_CHKSUM_MISMATCH
Level 0: [-]    irods_repl_rebalance.cpp:570:proc_results_for_rebalance :  status [USER_CHKSUM_MISMATCH]  errno [] -- message []
        [-]     irods_repl_rebalance.cpp:62:repl_for_rebalance :  status [USER_CHKSUM_MISMATCH]  errno [] -- message [Failed to replicate the data object [/seq/sequenom/ce/8f/68/W35520_Replication300152_300153_300154_300155_20140416_M22.csv]]

Level 1: [-]    irods_repl_rebalance.cpp:570:proc_results_for_rebalance :  status [USER_CHKSUM_MISMATCH]  errno [] -- message []
        [-]     irods_repl_rebalance.cpp:62:repl_for_rebalance :  status [USER_CHKSUM_MISMATCH]  errno [] -- message [Failed to replicate the data object [/seq/sequenom/5c/b5/48/W35520_Replication300176_300177_300178_300179_20140416_P12.csv]]
```

ichksum reporting OK;
```
$ ichksum -f -a -v /seq/sequenom/5c/b5/48/W35520_Replication300176_300177_300178_300179_20140416_P12.csv
    W35520_Replication300176_30017    5cb54857c6188a5b3c030e57f2c3db92
   W35520_Replication300176_  0.695 sec
Total checksum performed = 1, Failed checksum = 0
```

**Comment by trel** [comment]
Please provide `ils -L` for this data object.  Thanks.

**Comment by kript** [comment]
Apologies, that item's now been removed by our bioinformatics pipeline.  Heres another example, though;

```
$ ils -L /seq/sequenom/5c/b5/48/W35520_Replication300176_300177_300178_300179_20140416_P12.csv
  srpipe            0 root;replicate;seq-green;green4;irods-seq-sr04-ddn-gc10-27-28-29            0 2014-05-06.18:50 & W35520_Replication300176_300177_300178_300179_20140416_P12.csv
    5cb54857c6188a5b3c030e57f2c3db92    generic    /irods-seq-sr04-ddn-gc10-27-28-29/replica/sequenom/5c/b5/48/W35520_Replication300176_300177_300178_300179_20140416_P12.csv.939651593
```

**Comment by trel** [comment]
This isn't just a file that has not yet completed?  A placeholder with zero length until the full transfer is complete?

I notice the full physical path has an extension (`.939651593`):
`/irods-seq-sr04-ddn-gc10-27-28-29/replica/sequenom/5c/b5/48/W35520_Replication300176_300177_300178_300179_20140416_P12.csv.939651593`

Can you also show:

`ls -l /irods-seq-sr04-ddn-gc10-27-28-29/replica/sequenom/5c/b5/48/W35520_Replication300176_300177_300178_300179_20140416_P12.csv.939651593`

and

`md5sum /irods-seq-sr04-ddn-gc10-27-28-29/replica/sequenom/5c/b5/48/W35520_Replication300176_300177_300178_300179_20140416_P12.csv.939651593`

**Comment by trel** [comment]
If this is the case, perhaps we should consider marking the replica as 'stale' (so it will appear without the `&`) until the transfer is complete.

**Comment by kript** [comment]
I do apologise, I thought I'd responded to this.

```
irods@irods-seq-sr04:~$ md5sum /irods-seq-sr04-ddn-gc10-27-28-29/replica/sequenom/5c/b5/48/W35520_Replication300176_300177_300178_300179_20140416_P12.csv.939651593
5cb54857c6188a5b3c030e57f2c3db92  /irods-seq-sr04-ddn-gc10-27-28-29/replica/sequenom/5c/b5/48/W35520_Replication300176_300177_300178_300179_20140416_P12.csv.939651593
```

**Comment by trel** [comment]
So the catalog has a bad filesize, but a good checksum.  Presumably, fixing the filesize manually would allow `ichksum` and `rebalance` to both be happy in this case.

Without fixing the filesize manually, we want `rebalance` to give a more correct error.  It seems that the `USER_CHKSUM_MISMATCH` is the wrong error to throw -- it should probably convey that the filesizes in the catalog and on the disk are different.

The filesize mismatch check should occur before the checksum mismatch check.

**Comment by kellerb** [comment]
I believe what is happening is that:

1. the checksum code used by `ichksum` generates a checksum for the entire file on disk, ignoring the size in the database
2. this means that if there is a 10 GB file in the vault, with the checksum in the database corresponding to the checksum of the full 10 GB, `ichksum` will recalculate the "correct" checksum, even if the database says the size of the file is 0
3. the replication code only replicates up to the size in the database, i.e. if there is a 10 GB file on disk with a registered-in-database size of 0, a replication will create a size 0 file in the vault of the target resource
4. this means that after the replication, when the checksum of the new replica is computed, it will be the checksum of the size 0 file in the new vault, which will not match the checksum in the database

A possible fix to this would be to have `ichksum` compare both the checksums and the sizes. I'm not sure how difficult of a change that would be.

**Comment by kellerb** [comment]
To compare size-in-vault with size-in-database in addition to comparing checksums, we have added a new flag `--verify`, to be used e.g. `ichksum -K --verify <data_object>`.

**Comment by kript** [comment]
In 4-1 stable branch (aka 4.1.12 with the binaries provided), while this doesn't generate errors, it only appears to check one object, when the object is replicated, and the `--verify` isn't in the help (or the man page);

```
 ichksum -h | grep verify
 -K  verify the checksum value in iCAT. If the checksum value does not exist,
```

test file with two replicas;
```
 ils -L /seq-dev/home/jc18#Sanger1-dev/24174_5#888.cram
  jc18              0 root;replicate;red;red2;irods-seq-i13-bc    190766099 2018-07-31.16:05 & 24174_5#888.cram
    97d72409f603c275c5e37debef9839db    generic    /irods-seq-i13-bc/home/jc18#Sanger1-dev/24174_5#888.cram
  jc18              1 root;replicate;green;green1;irods-seq-sr01-ddn-ra08-36-37-38    190766099 2018-07-31.16:05 & 24174_5#888.cram
    97d72409f603c275c5e37debef9839db    generic    /irods-seq-sr01-ddn-ra08-36-37-38/home/jc18#Sanger1-dev/24174_5#888.cram
```
run the checksum from an iRES where the file is located;
```
$ ichksum -M --verify -K /seq-dev/home/jc18#Sanger1-dev/24174_5#888.cram
    24174_5#888.cram                  97d72409f603c275c5e37debef9839db
Total checksum performed = 1, Failed checksum = 0
```

run the checksum from the IES;
```
:~$ ichksum -M --verify -K /seq-dev/home/jc18#Sanger1-dev/24174_5#888.cram
    24174_5#888.cram                  97d72409f603c275c5e37debef9839db
Total checksum performed = 1, Failed checksum = 0
```
Apologies if this should be opened in the irods-client-icommands repo instead of reopening this issue...
