### ISSUE TITLE
Disallow '.' as a collection name

### ISSUE THREAD

**Issue by tedgin** [irods/irods#3543]
We are using iRODS 4.1.10.

Somehow one of our users created a collection named `.` and managed to add a data object into it. We are using a unix filesystem for storage, so the corresponding directory wasn't created.  The `.` was interpreted to mean current directory, so the data object's file was written into the directory corresponding to `.`'s parent.  Here's an example.

```
root@dirk:~/irods-adm# ils -L -r
  C- /iplant/home/XXXXX/.
/iplant/home/XXXXX/.:
  XXXXX             0 gatsbyRes      6763367 2015-10-30.05:34 & ERR690825_SFF_nt_reads.fasta
    caab612bc2fed0fb4722795bc635fb2f    generic    /irods_vault/home/XXXXX/./ERR690825_SFF_nt_reads.fasta
root@dirk:~/irods-adm# ssh -q gatsby ls -al /irods_vault/home/XXXXX
total 6676
drwxr-x---    8 irods irods    4096 Apr 26  2016 .
drwxr-x--- 1582 irods irods   36864 Dec 12 14:17 ..
-rw-------    1 irods irods 6763367 Oct 30  2015 ERR690825_SFF_nt_reads.fasta
```

If the user were to add a data object named `/iplant/home/XXXXX/ERR690825_SFF_nt_reads.fasta`, and its file were written to the `gatsbyRes` resource, it would silently overwrite the file corresponding to the data object `/iplant/home/XXXXX/./ERR690825_SFF_nt_reads.fasta`.

Less severely, the user cannot use icd to navigate into the collection `/iplant/home/XXXXX/.`. The `.` is interpreted as current directory, so icd takes the user to the collection `/iplant/home/XXXXX`.

Please make `.` an illegal name for a collection.

**Comment by trel** [comment]
Do you know what version you were using on Oct 30, 2015?

Could this be related to #2010?

**Comment by tedgin** [comment]
We were using version 3.3.1 at that time.  

Hehe.  I bet this issue is related to #2010.

**Comment by trel** [comment]
closing as duplicate/related to #2010
