### ISSUE TITLE
Use the cpp rule engine to backstop static peps instead of default empty rules

### ISSUE THREAD

**Issue by tempoz** [irods/irods#3549]
Ship `core.re.template` without empty default rules. Now that we have the cpp rule engine, we don't need to have empty rules to prevent lookup failures, and empty rules can cause unexpected fallthroughs in the case of rule failures.

**Comment by trel** [comment]
Seems good for 4.3?   Gives all the new 4.2 behavior a chance to settle.

**Comment by tempoz** [comment]
It won't change people's existing core.re, it will just make it easier for someone setting up a new iRODS installation/rulebase. I think it's good for 4.2, if for no other reason than because of the unintuitive behavior seen by acChkHostAccessControl in the presence of both an empty default rule and a rule attempting to limit access (namely, it logs a refusal of the connection and then allows access). This also means that if people's rules they've written fail they won't fall through to empty default rules and give the illusion of success. A rule failing *ought to,* by default, cause the "transaction" (insomuch as we can call them that) to fail and inform the user of the failure, otherwise we are likely to mislead users into believing rules are firing correctly and, depending on their assumptions, they may lose data.

**Comment by trel** [comment]
Ah, I see, just change the template for new installs, upgrades would already have a `core.re` and not be affected.

**Comment by tempoz** [comment]
That was the thought, yes. 4.2?

**Comment by trel** [comment]
Yes - let's just comment out the empty rules for 4.2.1.   We'll extract and document them elsewhere later.
