### ISSUE TITLE
Document orphan file creation behavior

### ISSUE THREAD

**Issue by kript** [irods/irods#3550]
As discussed on the conference call yesterday, could you document the behavior of the orphan file creation functionality (e.g. where a file is moved to a new location starting with orphan/ within a resource when it is overwritten using `iput -f`), ideally starting in 4.1.10 and also then covering any changes in 4.1.11 and 4.2.X

Apologies if this is in the wrong repo.

**Comment by trel** [comment]
Bench testing with 4.1.10:

1) removing a dataobject, without the force flag, consisting of a single replica, on a resource currently marked down:
    - results in a HIERARCHY_ERROR
    - no catalog movement
    - no data movement on disk

2) removing a dataobject, with the force flag, consisting of a single replica, on a resource currently marked down:
    - results in a SYS_RESC_IS_DOWN error
    - the dataobject is moved to `/myZone/trash/orphan/myUser#myZone/filename.10digitrandomsuffix`
    - no data movement on disk

3) removing a dataobject, without the force flag, consisting of one replica on resource marked up, and the other on a resource marked down:
    - results in a SYS_RESC_IS_DOWN error
    - catalog is updated, dataobject now in the trash, as expected
    - replica on up resource, phypath updated, file moved on disk accordingly
    - replica on down resource, phypath untouched, file on disk untouched

4) removing a dataobject, with the force flag, consisting of one replica on resource marked up, and the other on a resource marked down:
    - results in a SYS_RESC_IS_DOWN error
    - catalog is updated, dataobject now at `/myZone/trash/orphan/myUser#myZone/filename.10digitrandomsuffix`
    - replica on up resource is gone
    - replica on down resource, phypath untouched, file on disk untouched

5) putting a dataobject, with or without the force flag, onto a resource where a file already resides where the new dataobject's replica will reside
    - results in SUCCESS
    - new data is where it is expected, catalog and disk
    - old/existing data is not in catalog (as expected), but has been moved aside in the vault area to `physicalvaultpath/orphan/home/myUser/filename.10digitrandomsuffix`

6) replicating a dataobject onto a resource where a file already resides where the new replica will reside
    - results in SUCCESS
    - new replica data is where it is expected, catalog and disk
    - old/existing data is not in catalog (as expected), but has been moved aside in the vault area to `physicalvaultpath/orphan/home/myUser/filename.10digitrandomsuffix`

**Comment by trel** [comment]
Confirmed identical behavior as above (1-6) with 4-2-stable through 79c40d7248b58e18c0655a4c5270991fd6240ba6 (May 19)

**Comment by trel** [comment]
```
acTrashPolicy {msiNoTrashCan; }
```
has no effect on any of the above behavior in 4.1 or 4.2
