### ISSUE TITLE
Tickets cannot be retrieved if its String contains only numbers.  

### ISSUE THREAD

**Issue by mtamie** [irods/irods#3553]
- [x] 4-1-stable
- [x] 4-2-stable
- [x] master

-------

Tickets can be created with a Ticket String that contains *only numbers*, but they cannot be retrieved using `iticket ls <TICKET STRING>` command.  

Steps to reproduce:

1. Create a ticket using a number as the Ticket String: 
    ` iticket create write file.txt 35776`
2. Get the new ticket information:
     `iticket ls 35776`
3. No information is displayed *unless* another existing ticket ID is 35776.  But the ticket can be found by using `iticket ls`.

**Comment by trel** [comment]
I'm considering simply disallowing any new ticket string that is only numbers.

Is this a sufficient solution for your use case?
Does this prevent anything you are trying to do?

Something like this:
```diff
--- a/plugins/database/src/db_plugin.cpp
+++ b/plugins/database/src/db_plugin.cpp
@@ -14594,6 +14594,11 @@ irods::error db_mod_ticket_op(
 
     /* create */
     if ( strcmp( _op_name, "create" ) == 0 ) {
+
+        if (isInteger((char*)_ticket_string)) {
+                return ERROR( CAT_TICKET_INVALID, "ticket string cannot be a number" );
+        }
+
         status = splitPathByKey( _arg4,
                                  logicalParentDirName, MAX_NAME_LEN, logicalEndName, MAX_NAME_LEN, '/' );
         if ( strlen( logicalParentDirName ) == 0 ) {
```

**Comment by mtamie** [comment]
Yes, that'll solve our problem and it won't prevent anything we're planning to do.
Thanks!

**Comment by trel** [comment]
Excellent.
