### ISSUE TITLE
rsComm_t should be passed to all functions in icatHighLevelRoutines

### ISSUE THREAD

**Issue by trel** [irods/irods#3557]
and therefore also passed to every database plugin operation invocation

This will provide all the rsComm contexts to all database dynPEPs

**Comment by trel** [comment]
need 4.2.1 for training at UGM2017, bumping to 4.2.2

**Comment by korydraughn** [comment]
I think this can be closed.  Nearly all of the functions in the database plugin are passed the rsComm_t.

**Comment by trel** [comment]
excellent - thanks.
