### ISSUE TITLE
After iexit full with PAM, icommands ask for Native irods password.

### ISSUE THREAD

**Issue by RobvanSchip** [irods/irods#3564]
- [x] main
- [x] 4-3-stable
---
Version 4.1.8

Using PAM authentication (in the .irods/irods_environment.json) , when I do a "iexit full" and then a icommand for example:

[rob@elitebook ~]$ ils
Enter your current iRODS password:

It asks for my iRODS password instead of my PAM password. 

What I think it should do, is check if I use Native or PAM and act accordingly:

So in my case ask: "Enter your current PAM password:"

**Comment by trel** [comment]
Hi @RobvanSchip - this is an artifact of the authentication mechanism being handled primarily by `iinit`.  I think `clientLogin()` can be adjusted to handle this case for all the other iCommands.  We'll look into it.   Thanks.

**Comment by alanking** [comment]
Related to efforts in #5479

**Comment by alanking** [comment]
I think this has been resolved in 4.3.0:
```bash
$ ils
/tempZone/home/bobby:
$ iexit full
$ ils
Enter your current PAM password:
/tempZone/home/bobby:
```
However, I see the following in the server log after the `ils` completes which prompts for the password:
```
$ tail -n2 /var/log/irods/irods.log | jq '.log_message'
"[-]\t/irods_source/server/core/src/rodsAgent.cpp:588:int runIrodsAgentFactory(sockaddr_un) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [failed to call 'agent stop']\n\t[-]\t/irods_source/lib/core/src/sockComm.cpp:160:irods::error sockAgentStop(irods::network_object_ptr) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [failed to call 'agent stop']\n\t\t[-]\t/irods_source/plugins/network/src/ssl.cpp:850:irods::error ssl_agent_stop(irods::plugin_context &) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [error completing shutdown of SSL connection]\n\n"
"Agent process [4444] exited with status [1]"
```
This does not happen with native authentication while SSL is enabled, so we will need to investigate why that is happening.

**Comment by alanking** [comment]
Note: The message only appears in the catalog service provider's log when the client is connected to a catalog service consumer using `pam_password` authentication and SSL is enabled. When the client is connected directly to the catalog service provider, things work fine.

**Comment by alanking** [comment]
This can be resolved by checking to see if SSL is enabled before attempting to shut it down in the plugin. This is currently not being done, as shown here:
https://github.com/irods/irods/blob/c3c62ad4cfe8064bcc1475839cc79f362d0e1caa/plugins/auth/src/pam_password.cpp#L274-L278

This is already being done if no redirection occurs:
https://github.com/irods/irods/blob/c3c62ad4cfe8064bcc1475839cc79f362d0e1caa/plugins/auth/src/pam_password.cpp#L189-L202

**Comment by alanking** [comment]
@korydraughn / @trel - Are we interested in getting a fix for this in 4.2.12? The issue has been resolved in 4.3.0 by virtue of the new auth plugin framework and some tweaks to `iinit`. A 4.2.12 solution would be possible, but perhaps non-trivial.

**Comment by korydraughn** [comment]
I agree that this doesn't seem critical. However, if you can **brain out** what is needed to fix this and it's trivial, I think it is fine to go ahead and fix.

**Comment by alanking** [comment]
The issue appears to be that `iinit` is super special in how it handles different authentication schemes with respect to `clientLogin`. As @trel mentioned back in 2017, `clientLogin` can be adjusted to handle this case for all iCommands. The logic for determining whether to "override" the authentication scheme from the environment would need to be ported to `clientLogin`. I do not know at this time how this interaction will play out for other authentication plugins (e.g. OpenID).

So, possible, but not trivial, IMO.
