### ISSUE TITLE
ipasswd issues (was: stty path hard-coded in clientLogin.cpp)

### ISSUE THREAD

**Issue by onmh** [irods/irods#3580]
- [x] master
- [x] master icommands
- [x] 4-2-stable
- [x] 4-2-stable icommands
-----

This issue has been restated and expanded to include other issues found in ipasswd during implementation of the bug fix.  Associated issues:  #2797  (ipasswd behavior) and #3910 (code cleanup).

The original issue focused on the "stty" utilty being hardcoded as "/bin/stty" in clientLogin.cpp. 

While digging into this issue, other issues emerged, and the issue has been expanded to deal with them:

1.  Remove all implementations of "/bin/stty" from the C/C++ code.  Instead use termios(3) - tcgetattr() and tcsetattr() to turn echo on and off instead.  **DONE**

2. A possible endless loop exists in the code which asks for new password in ipasswd.  Limit it to three tries, and then abort. **DONE**

3. Part of the endless-loop issue is caused by not distinguishing between EOF, error condition, or empty line entered (using std::getline). **DONE**

4. When entering a new password which is short, the message asks for at least 3 characters, but in fact only accepts passwords that are at least 4 characters long.  Modify the behavior so that the 3-count is implemented correctly.  **DONE**

5. There is only partial implementation of the "-e" flag (echo the password as entered).  The flag is impelented in the original challenge for a password, but completely ignored while entering the new password, and echo is turned off regardless of that flag. This has to be fixed. **DONE**

6. In obf.cpp the fgets() of the password input is not checked for error or EOF. Fix. **DONE**

7. Identify all other places where tcgetattr() and tcgetattr() are used to control echo on/off, and improve to include the above functionality (see full list in a comment below) - **See new issue #3910 submitted including uses of repetitious code that works.**

Lastly, the CI test for ipasswd has to be drastically expanded to cover most basic functionality.  **DONE - see attached spreadsheet in comment below.**

The original statement of the issue is below the line.  It is completely addressed by item (1) above:
--------------------------------------------------------------------

Path to stty is hard coded in clientLogin.cpp:

```
        path p( "/bin/stty" );

            if ( 0 != system( "/bin/stty -echo 2> /dev/null" ) ) {

            if ( 0 != system( "/bin/stty echo 2> /dev/null" ) ) {

```
Some systems (e.g. NixOS) don't have /bin/stty and login throws an error:

`sh: /bin/stty: No such file or directory`

The call could be replaced by:

`/usr/bin/env stty -echo`

which would probably be more generic.

**Comment by bzizou** [comment]
Same problem into `lib/core/src/obf.cpp`

**Comment by andrew-irods** [comment]
Plan is to create a simple small test case and run it through jenkins for all platforms and os's we support. See if the env utility does a better job than /bin/stty (it will include both).

**Comment by andrew-irods** [comment]
An alternative solution is to eliminate the use of stty altogether, in favor of making termios(3) calls to turn echo on and off  - tcgetattr() and tcsetattr().  I'd appreciate your input on this question (all of you who are following this issue).

Thanks!

**Comment by andrew-irods** [comment]
Turns out that both iadmin and ipasswd themselves have password challenges that turn echo off.  In those places, the termios(3) functions tcgetattr() and tcsetattr() are already currently used (correctly) to turn off echo, rather than calling the 'stty -echo' and 'stty +echo' utilities.  I'm going to extend this method into the two places in the code the use "/bin/stty" hardcoded, and that should be that.

**Comment by andrew-irods** [comment]
Preliminary CI run: job 809: successful

http://172.25.14.125:8080/view/2.%20Personal/job/irods-build-and-test-workflow/809/

**Comment by andrew-irods** [comment]
Implementation plan:   

There are a total of 5 places in the irods lib and plugins directories where the same sequence of code repeats to turn echo off then on during the process of authentication.  In addition, iadmin and ipasswd also contain the same sequences of code.  All of these code snippets have warning and error printf's that are not formatted correctly (missing newlines), and incorrect reading of password input lines that do not distinguish between end of file and empty lines.  

We are going to create two library functions that turn off echo,  and turn it on again (for a parameter file descriptor), and print the error and warnings about passwords showing in clear text, and clean up these seven files in the source code -- they all implement the same thing. 

The current implementation of these challenges will not change current behavior, other than to make the errors and warnings cleaner, and have all of this code in one place.

This may be a good opportunity to clean out Windows related ifdefs that are not supported any longer.

And all the calls to /bin/stty are all gone now.

Comments are welcome.

**Comment by andrew-irods** [comment]
Or maybe a single simplistic c++ class that sets everything related to echo-off and echo-on, and interacts well with the c-like style of the existing code.  That class could then be extended to other terminal capabilities as needed in the future.

**Comment by andrew-irods** [comment]
Pushed the initial version of termiosUtil.hpp - with a class that does the work (both irods and icommands branches above). More to come.

**Comment by andrew-irods** [comment]
All sections in the description marked as **DONE** have been pushed to the branches above.

**Comment by andrew-irods** [comment]
CI for the checked in code thus far: successful.

http://172.25.14.125:8080/view/2.%20Personal/job/irods-build-and-test-workflow/825/

**Comment by andrew-irods** [comment]
The spreadsheet below is the initial revision.  Not all the tests have been run yet.  Comments are welcome. 

[ipasswd-testcases-05-01-2018.xlsx](https://github.com/irods/irods/files/1965488/ipasswd-testcases-05-01-2018.xlsx)

**Comment by andrew-irods** [comment]
What should be the final CI test is running: http://172.25.14.125:8080/view/2.%20Personal/job/irods-build-and-test-workflow/861/

**Comment by trel** [comment]
checkboxes and close!
