### ISSUE TITLE
imeta regression in 4.2.1 vs 4.1.10

### ISSUE THREAD

**Issue by kript** [irods/irods#3594]
With 4.1.10 icommands against  4.1.10 server (via Federation) we can do;

```
$ imeta qu -z seq -d target = 1 and study_id = 4616 and type = 'fastq' and target = 1 and library_type = 'Chromium genome' and sample_public_name = "fDanDra1"
collection: /seq/22577/longranger/fastq
dataObj: 22577_1_AACCGTAA_S4_L001_I1_001.fastq.gz
----
...
```

with 4.2.1 icommands (from RENCI repo package install on Ubuntu 12.04) we get;
```
$ ienv
irods_version - 4.2.1
irods_session_environment_file - /home/ubuntu/.irods/irods_environment.json.1208
irods_environment_file - /home/ubuntu/.irods/irods_environment.json
irods_zone_name - Sanger1
irods_ssl_ca_certificate_file - /etc/irods/ca.pem
irods_host - irods-sanger1.research.ac.uk
irods_home - /Sanger1/home/jc18-test
irods_port - 1247
irods_def_resource - wtsiusers
irods_cwd - /Sanger1/home/jc18-test
irods_authentication_scheme - native
irods_user_name - jc18-test

$ imeta qu -z seq -d target = 1 and study_id = 4616 and type = 'fastq' and target = 1 and library_type = 'Chromium genome' and sample_public_name = "fDanDra1"
XXXXX cmdToken[cmdIx] = 
rcGenQuery failed with error -816000 CAT_INVALID_ARGUMENT 
```

**Comment by JustinKyleJames** [comment]
This was caused during the move to clang.  The original code relied on using std::string::c_str() to populate a c style character pointer which is undefined behavior that just happened to work in g++.

The strings are being stored in a vector of std::string and the c_str() seems to be reliable as long as the vector is pre-allocated with enough space.  The original code did pre-allocate the size of the vector but was using variable for the size that did not make sense in the context it was used and was not large enough.

**Comment by JustinKyleJames** [comment]
Closed after passing tests on master and 4-2-stable.
