### ISSUE TITLE
irule: memory leak in infinite "while" loop with database query

### ISSUE THREAD

**Issue by kuntzagk** [irods/irods#3595]
- [x] master
- [x] 4-2-stable
- [x] 4-1-stable
------

Hi,

by accident I constructed a rule with a database query inside an infinite while loop. Seems when this rule is run it is leaking memory (actually the started irodsAgent)
I can see memory consumption steadily raising. I had to kill it at 2GB memory consumed.

``` php
emptyLoop {
     *RescToCheck = "NotExisting"
     while ( *RescToCheck != "" ) {
          foreach ( *ROW in SELECT RESC_PARENT WHERE RESC_NAME like '*RescToCheck') {
                 *RescToCheck = *ROW.RESC_PARENT;
           }
     }

}

OUTPUT ruleExecOut

```

This is on iRODS 4.1.9

Btw.: What would be the "correct" way to stop the irodsAgent? I justed used `kill -9`

**Comment by kellerb** [comment]
There is not a better way to stop the irodsAgent than `kill`.

Wrt. the leak, I believe that the [language integrated general query](https://docs.irods.org/4.2.1/plugins/irods_rule_language/#language-integrated-general-query), `*ROW in SELECT RESC_PARENT WHERE RESC_NAME like '*RescToCheck'`, when used inside a `foreach` leaks structures related to the use of general query. It may be possible to free them manually if written in a more verbose manner. @xu-hao may know more.

**Comment by xu-hao** [comment]
The variable in question is a keyValPair so, it can be freed in the same
way as the more verbose version. However, it seems that this can be fixed
as a bug, since we can automatically free the variable at the end of each
loop, which is probably what the user expect.

**Comment by kellerb** [comment]
The genQueryOut_t from the LIGQ is getting free'd?
