### ISSUE TITLE
iadmin modrescdatapaths fails to update paths

### ISSUE THREAD

**Issue by jasoncoposky** [irods/irods#3598]
resc_name improperly used, should use resc_id.

**Comment by kript** [comment]
Would it be possible to have this in 4.1.11 as well, please? I can see us needing this before we get to 4.2.x

thanks

John

**Comment by trel** [comment]
The change from resc_name to resc_id was made in 4.2.0.

This is not working on 4.1.x for you?

**Comment by kript** [comment]
Oh, my mistake. When I read it I thought it was a 4.x change, as the last time I used it was in 3.3.1. I'll test it and let you know.

**Comment by bh9** [comment]
We're seeing modrescdatapaths return CAT_INVALID_ARGUMENT on 4.1.12, is this the exact opposite happening?

**Comment by trel** [comment]
I don't think so... 4.1.12 doesn't know about `resc_id` from the future.

**Comment by trel** [comment]
Unless you're pointing 4.1.12 `iadmin` at 4.2.x servers... that's probably not going to go well.

**Comment by bh9** [comment]
This is all on one of the 4.1.12 zones, using the 4.1.12 icommands installed on the IES

**Comment by trel** [comment]
well that is very confusing.   if you can share anything happening in the rodsLog, that could be a separate issue (which... if we cannot reproduce in 4.2.x... we won't fix).

**Comment by bh9** [comment]
Nothing in the rodsLog on the IES except `Apr  6 13:47:14 pid:27655 NOTICE: rsGeneralAdmin: rcGeneralAdmin error -816000` (816000 is CAT_INVALID_ARGUMENT)

**Comment by alanking** [comment]
I was able to reproduce these observations on 4.1.12 and 4.2.7. It turns out that when I used a trailing slash, it worked as expected.

For completeness/posterity...

I wanted to note here that this is for making sweeping changes to the physical paths of data objects which are tied to a particular resource. The name led me to believe this was similar to `iadmin modresc` changing the vault path, but that is not the case.

This is the SQL being run for `modrescdatapaths`:
https://github.com/irods/irods/blob/c48b524a12bc726cb616044d3460554cf70def1e/plugins/database/src/db_plugin.cpp#L8783

I was getting `CAT_INVALID_ARGUMENT` when running the following scenario (shown is 4.1.12, but also works on 4.2.7):
```
$ ienv | grep Version
NOTICE: Release Version = rods4.1.12, API Version = d
$ iadmin mkresc pathresc unixfilesystem `hostname`:/var/lib/irods/pathvault
Creating resource:
Name:           "pathresc"
Type:           "unixfilesystem"
Host:           "44dbf97d39c0"
Path:           "/var/lib/irods/pathvault"
Context:        ""
$ iput -R pathresc VERSION.json pathfoo
$ ils -L pathfoo
  rods              0 pathresc          476 2020-04-15.16:06 & pathfoo
        generic    /var/lib/irods/pathvault/home/rods/pathfoo
$ iadmin modresc pathresc path /var/lib/irods/pathvault_new
Level 0: Previous resource path: /var/lib/irods/pathvault
$ iadmin modrescdatapaths pathresc /var/lib/irods/pathvault /var/lib/irods/pathvault_new
Warning, this command, more than others, is relying on your direct
input to modify iCAT tables (potentially, many rows).  It will do a
string pattern find and replace operation on the main data-object
table for the paths at which the physical files are stored. If you
are not sure what you are doing, do not run this command.  You may
want to backup the iCAT database before running this.  See the help
text for more information.

Are you sure you want to run this command? [y/N]:y
OK, performing the resource data paths update
ERROR: rcGeneralAdmin failed with error -816000 CAT_INVALID_ARGUMENT
```
I then tried again with a trailing slash and it worked:
```
$ iadmin modrescdatapaths pathresc /var/lib/irods/pathvault/ /var/lib/irods/pathvault_new/
Warning, this command, more than others, is relying on your direct
input to modify iCAT tables (potentially, many rows).  It will do a
string pattern find and replace operation on the main data-object
table for the paths at which the physical files are stored. If you
are not sure what you are doing, do not run this command.  You may
want to backup the iCAT database before running this.  See the help
text for more information.

Are you sure you want to run this command? [y/N]:y
OK, performing the resource data paths update
Level 0: 1 rows updated
$ ils -L pathfoo
  rods              0 pathresc          476 2020-04-15.16:06 & pathfoo
        generic    /var/lib/irods/pathvault_new/home/rods/pathfoo
```
To be clear, both of these are catalog-only operations, so the data on disk still resides at `/var/lib/irods/pathvault/home/rods/pathfoo`.
