### ISSUE TITLE
remove iphybun

### ISSUE THREAD

**Issue by trel** [irods/irods#3603]
marked deprecated in 4.2.0 (https://github.com/irods/irods/issues/3012)

**Comment by PaulVanSchayck** [comment]
Hi Terrell, is the deprecation of iphybun only planned for the iCommand or also planned for the `msiPhyBundleColl`. Or is even the whole bundleResource feature being removed?

**Comment by trel** [comment]
We haven't decided specifically - but input is welcome.

Are you depending on the `phyBundleColl` feature-set?

Candidates include:
- `rsPhyBundleColl`
- `rcPhyBundleColl`
- `remotePhyBundleColl`
- `msiPhyBundleColl`
- `iphybun`

**Comment by PaulVanSchayck** [comment]
Hi Terrell. Thanks for your answer. We're actually considering using the bundle collections for a project that involves moving data to tape, while preserving objects and metadata. 

This is a project together with Matthew Saum (@Msaum87) from SURFsara. He is drafting a reply for this on irods-chat.

**Comment by PaulVanSchayck** [comment]
Matthew started [this conversation](https://groups.google.com/forum/#!topic/irod-chat/CjDTUQ-BSFM) on irods-chat.

**Comment by trel** [comment]
@msaum87 @PaulVanSchayck what is the status on your efforts with this?   Are you using this interface in a way that is helpful/successful?

We're leaning into the release of 4.3.0 and don't want to remove something that is serving a use case for you (or anyone else) without providing good justification or an alternate codepath/functionality.

**Comment by PaulVanSchayck** [comment]
Nope.. we're not using it. We considered, but found another (better) solution not involving tar balls. Using tarballs made us very unhappy.

**Comment by trel** [comment]
Ah, very good.   Excellent news :)

Can you share what you ended up doing?  To help anyone else who finds this discussion later and needs to solve a similar challenge.

---

We're interested in removing this functionality because it's a fixed, inflexible implementation and doesn't preserve the metadata or keep objects and subcollections searchable.

proposal:
 - remove these functions/iCommands
 - move to a more abstract model.... based on annotation and policy invocation
 - this would separate any operations (the what) from their invocation (the when)

new universe:
 - this work would be related to / part of the work on refactoring special collections (using libarchive methods in-memory, rather than with files in a (fake) resource, aka `bundleResc`)
 - new policy for most common use cases could be shipped with the iRODS Server

**Comment by PaulVanSchayck** [comment]
So we were considering tarballs to overcome the issue that tape doesn't like small files. In the end, we are only moving objects over a threshold in size (256 MiB) to tape. Leaving smaller objects on the starting resource. I think we or @Msaum87  or Arthur Newton of SURF presented this at the UGM. Exactly for the reason of keeping metadata intact.

I can't overseen the implications of your proposal fully. But do note that we (Maastricht University) are using special collections. But then the mounted type. See also issue #5457.

**Comment by trel** [comment]
Good - thank you.

We'll proceed with the plan to remove the `iphybun` and related functionality and to think through alternative approaches for particular use cases.

**Comment by alanking** [comment]
This is just removing the iCommand, correct? In other words, we won't be touching the affiliated API endpoints and microservices.

**Comment by trel** [comment]
Definitely removing iphybun itself.   Please inventory the other bit and see how much they are entwined with other bit and pieces.   If we cannot cleanly get rid of them for 4.3.0, we can mark them as deprecated for 4.3.0.
