### ISSUE TITLE
server fails to start in rr intermittently

### ISSUE THREAD

**Issue by kellerb** [irods/irods#3612]
Seems like there is a race condition in server start involving the agent spawner that is generally only hit when running in `rr` (which single-threads everything).

```
Jul 21 15:56:45 pid:23713 NOTICE: Agent factory process pid = [23714]
Jul 21 15:56:51 pid:23713  ERROR: Error connecting to agent factory socket, errno = [2]: No such file or directory
```

**Comment by trel** [comment]
have we seen this recently?   @alanking @korydraughn

**Comment by korydraughn** [comment]
I can't remember a time where I've experienced this.

Maybe `rr` has been patched since this issue. It has always worked for me just fine.

**Comment by trel** [comment]
Closing.   Thanks.
