### ISSUE TITLE
Add `-L` argument to irsync

### ISSUE THREAD

**Issue by holtgrewe** [irods/irods#3623]
This is a very useful flag from `rsync` that transforms symlinks into their resolved file/directory.

This way, it is easy to select subsets of items to be transferred.

From `man rsync`:

```
-L, --copy-links            transform symlink into referent file/dir
```

**Comment by trel** [comment]
Hi @holtgrewe,

I believe the default behavior of `irsync` is to follow any source-side symlinks and 'bake' them on the far side, aka transform just like the `rsync -L` option you mention.

Are you seeing an example where this is not the case?

**Comment by holtgrewe** [comment]
It's working as intented.

**Comment by trel** [comment]
Excellent - thanks.
