### ISSUE TITLE
Uninstallation of irods-server package is not complete

### ISSUE THREAD

**Issue by sviscapi** [irods/irods#3645]
Hi all,

Uninstalling irods-server-4.2.1-1 package does not remove the /var/lib/irods directory + all depending packages on CentOS 7.3 x86_64.

Cheers, Samuel from CINES

**Comment by trel** [comment]
Hi @sviscapi,

We intentionally only remove the files that we are sure we put on the machine.  The other files, including those in `/var/lib/irods` contain the Vault of the `demoResc` that we create upon initial setup of an iRODS server.  We will never delete a Vault that might contain important data files (even if you've decided to uninstall the iRODS server package(s)).

That said, you may still have found something that we have not intended.

Can you provide a list of the files on your machine that you expected to be removed/deleted when you removed the `irods-server-4.2.1-1` package?

**Comment by sviscapi** [comment]
Hi @trel ,

Thanks for replying so quickly, it's really appreciated.

We expected to see all the files belonging to the following packages removed, along with irods-server-4.2.1-1.x86_64:

irods-icommands-4.2.1-1.x86_64
irods-externals-boost1.60.0-0-1.0-1.x86_64
irods-database-plugin-postgres-4.2.1-1.x86_64
irods-externals-avro1.7.7-0-1.0-1.x86_64
irods-externals-clang-runtime3.8-0-1.0-1.x86_64
irods-externals-libarchive3.1.2-0-1.0-1.x86_64
irods-externals-jansson2.7-0-1.0-1.x86_64
irods-externals-zeromq4-14.1.3-0-1.0-1.x86_64
irods-runtime-4.2.1-1.x86_64

Regarding demoResc, wouldn't it be better to put the vault in a different place, say in /var/opt ? Or keep the demo vault in /var/lib but move the bulk of iRODS files from /var/lib/irods to somewhere else, maybe /opt (à la EUDAT) or /srv ? 

Just my 2 cents ;)

Cheers, Samuel

**Comment by kellerb** [comment]
Does removing a package on CentOS 7 normally remove all of its dependencies (I suppose assuming that the dependencies are not needed by another package that is not being removed)?

**Comment by sviscapi** [comment]
Hi all,

@kellerb : yes, I think it does.

The package irods-server requires the following to be installed:

[viscapi@helios ~]$ rpm -qR irods-server
irods-externals-libarchive3.1.2-0
irods-externals-avro1.7.7-0
irods-externals-boost1.60.0-0
irods-externals-clang-runtime3.8-0
irods-externals-jansson2.7-0
irods-externals-zeromq4-14.1.3-0
irods-runtime = 4.2.1
irods-icommands = 4.2.1
openssl
python
python-psutil
python-requests
python-jsonschema
/bin/sh
/bin/sh
/bin/sh
/bin/sh
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(PayloadIsXz) <= 5.2-1

Some of those packages should be removed along with irods-server, provided they are no longer required of course. We'll do some more installing / uninstalling tests on our end and report here ASAP.

"With this tag a package can require another with the matching name or Provides to be installed (if the package containign the Requires: is going to be installed). This is checked when a new package is installed and if a package with a matching Provides: is removed."

http://rpm.org/user_doc/dependencies.html

Cheers, Samuel

**Comment by kellerb** [comment]
That quote talks about the `Requires` section of an RPM and how such dependencies can be met by a package with a matching `Provides`, but it doesn't say anything about automatically removing no-longer-needed dependencies. If you ask `yum` to remove a package, it will also remove all of the packages that depend on said package, but that is the opposite of what you are interested in.

It looks like `sudo yum remove --setopt=clean_requirements_on_remove=1 irods-server` may do what you want.

Do you have an example of an RPM that, on removal, also automatically removes all of the other packages it depends on as well? That seems like something that should be handled by the package manager and not the package.

**Comment by trel** [comment]
Closing this as I believe our packages are handling uninstallation as expected/designed.
