### ISSUE TITLE
Version 7 Centos/RedHat support for Oracle

### ISSUE THREAD

**Issue by kript** [irods/irods#3653]
I was slightly surprised to find that 4.1.10 doesn't have Centos 7 RPM for `irods-database-plugin-oracle-1.10`, although there are other Centos 7 RPM's for all the other packages.

Is this intentional, and if not, could we get one built please? We're looking at migrating from Ubuntu 12 to Red Hat 7.4, and have some installs to get working.

thanks,

John

**Comment by trel** [comment]
Not intentional, just wasn't ever automated.  I'll see how portable our Oracle incantations are.

**Comment by kript** [comment]
Any news on this? We can't deploy on Centos without it...

**Comment by trel** [comment]
I have shared a build of 4.1.10 and 4.1.11 oracle database plugins for centos7.

I am closing this issue - we do not plan to formally release builds from earlier release dates.  The code builds, but we are focusing on adding CI machines for future release dates at this time.

**Comment by trel** [comment]
I have added this to the 4-2-stable branch milestone... we'll get Oracle on CentOS7 into CI moving forward.

**Comment by trel** [comment]
This is being run now and will be included in 4.2.5
