### ISSUE TITLE
add invocation timestamp to rebalance operation

### ISSUE THREAD

**Issue by kript** [irods/irods#3665]
- [x] master
- [x] 4-2-stable
- [x] 4-1-stable
---------

Seen on 4.1.10 but with debug binaries with the rebalance and replication code for 4.1.11

Our resource tree is setup to make a replica at each of our data centres.

One of our zone owners alerted me to a load of three replica files, e.g.;

```
  srpipe            0 root;replicate;seq-red;red4;irods-seq-i22-de     12389710 2017-09-01.05:23 & 23615_1#0.cram
        1cc513d95d964e5ed4b6ba765d77704a    generic /irods-seq-i22-de/23615/23615_1#0.cram
  srpipe            1 root;replicate;seq-green;green1;irods-seq-sr01-ddn-ra08-15-16-17     12389710 2017-09-01.05:23 & 23615_1#0.cram
        1cc513d95d964e5ed4b6ba765d77704a    generic /irods-seq-sr01-ddn-ra08-15-16-17/23615/23615_1#0.cram
  srpipe            0 root;replicate;seq-red;red4;irods-seq-i21-bc         1265 2017-09-01.05:31 & 23615_1#0.cram.crai
        3833e72568c357d7b312e934d9f5a64b    generic /irods-seq-i21-bc/23615/23615_1#0.cram.crai
  srpipe            1 root;replicate;seq-green;green1;irods-seq-sr01-ddn-ra08-15-16-17         1265 2017-09-01.05:31 & 23615_1#0.cram.crai
        3833e72568c357d7b312e934d9f5a64b    generic /irods-seq-sr01-ddn-ra08-15-16-17/23615/23615_1#0.cram.crai
  srpipe            2 root;replicate;seq-green;green5;irods-seq-sr05-bc 1265 2017-09-01.05:31 & 23615_1#0.cram.crai
        3833e72568c357d7b312e934d9f5a64b    generic /irods-seq-sr05-bc/23615/23615_1#0.cram.crai
```

That entire collection was loaded fresh from the sequencing pipeline, so isn't a retry or overwrite; it was a straight upload.  I've checked the two servers that have a replica where there should only be one (i.e the irods-seq-sr* systems).

On one of them we have what looks fairly standard;

```
Sep  1 05:30:47 pid:2987 NOTICE: Agent process 740 started for puser=irods-g1 and cuser=irods-g1 from 172.17.10.10
Sep  1 05:35:03 pid:627 NOTICE: readAndProcClientMsg: received disconnect msg from client
Sep  1 05:35:03 pid:627 NOTICE: Agent exiting with status = 0
Sep  1 05:35:03 pid:554 NOTICE: readAndProcClientMsg: received disconnect msg from client
Sep  1 05:35:03 pid:554 NOTICE: Agent exiting with status = 0
Sep  1 05:35:03 pid:628 NOTICE: readAndProcClientMsg: received disconnect msg from client
Sep  1 05:35:03 pid:628 NOTICE: Agent exiting with status = 0
Sep  1 05:35:03 pid:537 NOTICE: readAndProcClientMsg: received disconnect msg from client
Sep  1 05:35:03 pid:537 NOTICE: Agent exiting with status = 0
Sep  1 05:35:03 pid:643 NOTICE: readAndProcClientMsg: received disconnect msg from client
Sep  1 05:35:03 pid:643 NOTICE: Agent exiting with status = 0
Sep  1 05:35:03 pid:555 NOTICE: readAndProcClientMsg: received disconnect msg from client
Sep  1 05:35:03 pid:555 NOTICE: Agent exiting with status = 0
Sep  1 05:35:03 pid:715 NOTICE: readAndProcClientMsg: received disconnect msg from client
Sep  1 05:35:03 pid:715 NOTICE: Agent exiting with status = 0
Sep  1 05:35:03 pid:601 NOTICE: readAndProcClientMsg: received disconnect msg from client
Sep  1 05:35:03 pid:601 NOTICE: Agent exiting with status = 0
Sep  1 05:35:03 pid:629 NOTICE: readAndProcClientMsg: received disconnect msg from client
Sep  1 05:35:03 pid:629 NOTICE: Agent exiting with status = 0
Sep  1 05:35:03 pid:685 NOTICE: readAndProcClientMsg: received disconnect msg from client
Sep  1 05:35:03 pid:685 NOTICE: Agent exiting with status = 0
Sep  1 05:35:03 pid:2987 NOTICE: Agent process 537 exited with status 0
Sep  1 05:35:03 pid:2987 NOTICE: Agent process 554 exited with status 0
Sep  1 05:35:03 pid:2987 NOTICE: Agent process 555 exited with status 0
Sep  1 05:35:03 pid:2987 NOTICE: Agent process 601 exited with status 0
Sep  1 05:35:03 pid:2987 NOTICE: Agent process 627 exited with status 0
Sep  1 05:35:03 pid:2987 NOTICE: Agent process 628 exited with status 0
Sep  1 05:35:03 pid:2987 NOTICE: Agent process 629 exited with status 0
Sep  1 05:35:03 pid:2987 NOTICE: Agent process 643 exited with status 0
Sep  1 05:35:03 pid:2987 NOTICE: Agent process 685 exited with status 0
Sep  1 05:35:03 pid:2987 NOTICE: Agent process 715 exited with status 0
```
But on the other we have something less helpful;

```
Sep  1 05:30:47 pid:15681 NOTICE: Agent process 47807 started for puser=irods and cuser=irods from 172.17.158.15
Sep  1 05:30:48 pid:47807 NOTICE: readAndProcClientMsg: received disconnect msg from client
Sep  1 05:30:48 pid:47807 NOTICE: Agent exiting with status = 0
Sep  1 05:30:48 pid:15681 NOTICE: Agent process 47807 exited with status 0
Sep  1 05:31:13 pid:14747 DEBUG: <unknown source type>
Sep  1 05:31:20 pid:14748 DEBUG: <unknown source type>
Sep  1 05:31:30 pid:16245 DEBUG: <unknown source type>
Sep  1 05:31:32 pid:16245 DEBUG: <unknown source type>
Sep  1 05:31:40 pid:14748 DEBUG: <unknown source type>
Sep  1 05:31:40 pid:46763 NOTICE: readAndProcClientMsg: received disconnect msg from client
Sep  1 05:31:40 pid:46763 NOTICE: Agent exiting with status = 0
Sep  1 05:31:41 pid:15681 NOTICE: Agent process 46763 exited with status 0
Sep  1 05:31:50 pid:14747 DEBUG: <unknown source type>
Sep  1 05:31:51 pid:14747 DEBUG: <unknown source type>
Sep  1 05:32:00 pid:16157 DEBUG: <unknown source type>
Sep  1 05:32:08 pid:14748 DEBUG: <unknown source type>
Sep  1 05:32:33 pid:14747 DEBUG: <unknown source type>
Sep  1 05:32:42 pid:14748 DEBUG: <unknown source type>
Sep  1 05:32:43 pid:16157 DEBUG: <unknown source type>
Sep  1 05:32:52 pid:14747 DEBUG: <unknown source type>
Sep  1 05:33:04 pid:14748 DEBUG: <unknown source type>
Sep  1 05:33:16 pid:14747 DEBUG: <unknown source type>
Sep  1 05:33:18 pid:16157 DEBUG: <unknown source type>
Sep  1 05:33:31 pid:16157 DEBUG: <unknown source type>
Sep  1 05:33:40 pid:16157 DEBUG: <unknown source type>
Sep  1 05:33:41 pid:14748 DEBUG: <unknown source type>
Sep  1 05:33:55 pid:16157 DEBUG: <unknown source type>
Sep  1 05:34:20 pid:14748 DEBUG: <unknown source type>
Sep  1 05:34:41 pid:16157 DEBUG: <unknown source type>
Sep  1 05:34:50 pid:16152 DEBUG: <unknown source type>
Sep  1 05:34:59 pid:14748 DEBUG: <unknown source type>
```
(some previous lines to show that the DEBUG line wasn't an ongoing issue)

The IES log is normal for this time.

The file is identical on both hosts and matches the md5sum that the pipeline records when it uploads it.

I'm looking into some network congestion issues on the IES, and I see some errors and overruns on the network port (since fixed by upping the tcp ring buffers on the ethernet cards), but I would have expected other error messages had it been a networking issue (and I can't correlate the network error counts with the time of this file, so may be a red herring -ongoing analysis has seen latency of up to 15 ms between federation master and federee IES).

The DEBUG messages continue after apply the additional PEP definitions as per https://docs.irods.org/4.1.10/manual/troubleshooting/#missing-static-pep-definitions

We've then run a rebalance to clear up a number of dirty replicas and single replica objects, and I was idly watching the logs when I noticed this;

```
Sep 22 11:37:39 pid:15348 NOTICE: proc_results_for_rebalance: rebalancing data id [111822782] from [root;replicate;seq-green;green5;irods-seq-sr06-fg] to [root;replicate;seq-green;green1;irods-seq-sr01-ddn-ra08-21-22-23]
Sep 22 11:38:10 pid:15348 NOTICE: proc_results_for_rebalance: rebalancing data id [111837502] from [root;replicate;seq-green;green1;irods-seq-sr01-ddn-ra08-42-43-44] to [root;replicate;seq-green;green5;irods-seq-sr05-fg]
Sep 22 11:38:55 pid:15348 NOTICE: proc_results_for_rebalance: rebalancing data id [111833599] from [root;replicate;seq-green;green2;irods-seq-sr02-ddn-rd10-33-34-35] to [root;replicate;seq-green;green2;irods-seq-sr02-ddn-ra08-6-7-8]
..
```
and more, until I stopped the rebalance.

i.e. the rebalance is balancing only within the green zone, often within the same server. I stopped the rebalance as soon as realised this.

This implies the issue is within the replication code, as it occurs both on ingest and on replication.

Also... it means that we have no way of fixing dirty replicas and single file issues now...

More detailed logs and configuration sent via email.

**Comment by PeteClapham** [comment]
We are being asked by colleagues if they should look to use this mechanism to manage their infrastructure as they look to spinout. This is a significant issue that will be a blocker for their migration plans.

Pete

**Comment by trel** [comment]
We have sent new debug binaries built from 173215c1822c309337b58ad03a8f4014a6845714.

**Comment by trel** [comment]
I believe the new binaries are working as expected.

Will close once confirmed by Sanger.

**Comment by trel** [comment]
We have identified a race condition between:
1) a new iput which will normally result in two replicas due to a replication resource in the target hierarchy, and
2) an independently running rebalance operation.

With a bit of logging on the server, we have seen the race condition:
```
Oct 11 09:59:59 pid:6270 NOTICE: writeLine: inString = writing to root
Oct 11 09:59:59 pid:3442 NOTICE: writeLine: inString = writing to root
Oct 11 09:59:59 pid:6270 NOTICE: writeLine: inString = writing to root
```

We see a first PID (6270) twice for the put&repl and a single different PID (3442) for the rebalance that detected a missing-replica and did work while the original replication was still in flight.

To address this, we will register the second replica as a 0-length replica as soon as possible.  This will prevent the rebalance code from detecting a 'missing-replica' case and making, what turns out to be, an unnecessary third replica.

**Comment by trel** [comment]
The 0-length plan above has been determined to be less-than-optimal since a failed put (network, ctrl-c, other error, etc) will end up with some number of registered 0-length replicas that would need to be paved over later with a force flag.  This creates more maintenance overhead for external monitoring scripts.


Two alternate ways to deal with the race condition:

1) Live with the race condition, and create a separate periodic trimrule() to reduce the number of replicas of over-abundant data objects.

2) Add a 'rebalance-delay-in-seconds' or 'rebalance-age-in-seconds' or 'rebalance-mtime-in-seconds' parameter to the rebalance operation (probably via replication resource context string) which would allow very new data objects to avoid being picked up by the rebalance operation.  More research would be necessary to decide on a default value -- I would guess a few seconds (5?) would be enough to reduce the race condition cases to nearly zero.

**Comment by keithj** [comment]
We do not have any rebalancing running at them moment. However, we are still seeing 3 replicates being created in many cases. On the same iRODS connection we will see data objects added without error having either 2 or 3 replicates.

I am trying to create a reduced test case, but it's proving difficult. For example, I tried adding hundreds of 128 KiB random data files in a loop on one connection using `baton-put` - all got 2 replicates. Likewise for 2 GiB files.

In production a single connection is used for all metadata and ACL changes, in addition to putting, so that simple put loop is maybe simplified too much.

One thing that I have noticed is that often the first files loaded get 2 replicates but after a certain amount of data, time or files (or combination thereof) most of the subsequent files get 3 replicates.

**Comment by trel** [comment]
We looked at the rodsLog for the three PID case above, and the middle PID (`pid:3442`) was definitely appearing and doing lots of work throughout the log, which is very strong evidence it was a rebalance operation.

There are only two places in the code where a new replica is created - the replication resource discovering its number of children for an initial `put`.  And the `rebalance` code.

Are you really, really sure there's no rebalance running somewhere?  Can you check the processes/crontab on the hostname of the originating `pid:3442` above?

**Comment by keithj** [comment]
I wil check with @kript. I agree that the PID evidence points to a race condition.

**Comment by kript** [comment]
I am somewhat at a loss on how to see if a rebalance is running or not.

Because the rebalance stops often, we wrap it in a shell loop that restarts it if the `iadmin modresc root rebalance` command exits with a non-zero error code.
Sometimes this fails to restart, and I need to control-C the running script and start again, so its possible there is a left over process hanging around. However, we see no evidence of it doing any rebalancing, until we run the iadmin command again.

Process tree on that server at the moment is;
```
       ├─irodsServer(7566)─┬─irodsAgent(1671)
        │                   ├─irodsAgent(3787)
        │                   ├─irodsAgent(10650)
        │                   ├─irodsAgent(10655)
        │                   ├─irodsAgent(10699)
        │                   ├─irodsAgent(10765)
        │                   ├─irodsAgent(10833)
        │                   ├─irodsAgent(10876)
        │                   ├─irodsAgent(10932)
        │                   ├─irodsAgent(10977)
        │                   ├─irodsAgent(11139)
        │                   ├─irodsAgent(11374)
        │                   ├─irodsAgent(11907)
        │                   ├─irodsAgent(11962)
        │                   ├─irodsAgent(11980)
        │                   ├─irodsAgent(11985)
        │                   ├─irodsAgent(11999)
        │                   ├─irodsAgent(12049)
        │                   ├─irodsAgent(12052)
        │                   ├─irodsAgent(12055)
        │                   ├─irodsAgent(14963)
        │                   ├─irodsAgent(14964)
        │                   ├─irodsAgent(14968)
        │                   ├─irodsAgent(14969)
        │                   ├─irodsAgent(14970)
        │                   ├─irodsAgent(14972)
        │                   ├─irodsAgent(15025)
        │                   ├─irodsAgent(15028)
        │                   ├─irodsAgent(15036)
        │                   ├─irodsAgent(15039)
        │                   ├─irodsAgent(16453)
        │                   ├─irodsAgent(18905)
        │                   ├─irodsAgent(18955)
        │                   ├─irodsAgent(19001)
        │                   ├─irodsAgent(19047)
        │                   ├─irodsAgent(19076)
        │                   ├─irodsAgent(19089)
        │                   ├─irodsAgent(19093)
        │                   ├─irodsAgent(19099)
        │                   ├─irodsAgent(19104)
        │                   ├─irodsAgent(19110)
        │                   ├─irodsAgent(19118)
        │                   ├─irodsAgent(19120)
        │                   ├─irodsAgent(19160)
        │                   ├─irodsAgent(19162)
        │                   ├─irodsAgent(19179)
        │                   ├─irodsAgent(19190)
        │                   ├─irodsAgent(19193)
        │                   ├─irodsAgent(19194)
        │                   ├─irodsAgent(19200)
        │                   ├─irodsAgent(19214)
        │                   ├─irodsAgent(20251)
        │                   ├─irodsAgent(20266)
        │                   ├─irodsAgent(20340)
        │                   ├─irodsAgent(20344)
        │                   ├─irodsAgent(20402)
        │                   ├─irodsAgent(20429)
        │                   ├─irodsAgent(20456)
        │                   ├─irodsAgent(20483)
        │                   ├─irodsAgent(20486)
        │                   ├─irodsAgent(20494)
        │                   ├─irodsAgent(20509)
        │                   ├─irodsAgent(20535)
        │                   ├─irodsAgent(20589)
        │                   ├─irodsAgent(20601)
        │                   ├─irodsAgent(20663)
        │                   ├─irodsAgent(20674)
        │                   ├─irodsAgent(20686)
        │                   ├─irodsAgent(20692)
        │                   ├─irodsAgent(20711)
        │                   ├─irodsAgent(20716)
        │                   ├─irodsAgent(20780)
        │                   ├─irodsAgent(20789)
        │                   ├─irodsAgent(20815)
        │                   ├─irodsAgent(20868)
        │                   ├─irodsAgent(20946)
        │                   ├─irodsAgent(21003)
        │                   ├─irodsAgent(21009)
        │                   ├─irodsAgent(21124)
        │                   ├─irodsAgent(21164)
        │                   ├─irodsAgent(21250)
        │                   ├─irodsAgent(21298)
        │                   ├─irodsAgent(21343)
        │                   ├─irodsAgent(21431)
        │                   ├─irodsAgent(21492)
        │                   ├─irodsAgent(21546)
        │                   ├─irodsAgent(21662)
        │                   ├─irodsAgent(21692)
        │                   ├─irodsAgent(21784)
        │                   ├─irodsAgent(21975)
        │                   ├─irodsAgent(21979)
        │                   ├─irodsAgent(22064)
        │                   ├─irodsAgent(22377)
        │                   ├─irodsAgent(22745)
        │                   ├─irodsAgent(22784)
        │                   ├─irodsAgent(23324)
        │                   ├─irodsAgent(23505)
        │                   ├─irodsAgent(23806)
        │                   ├─irodsAgent(24056)
        │                   ├─irodsAgent(24064)
        │                   ├─irodsAgent(24753)
        │                   ├─irodsAgent(24758)
        │                   ├─irodsAgent(25421)
        │                   ├─irodsAgent(25422)
        │                   ├─irodsAgent(25423)
        │                   ├─irodsAgent(28146)
        │                   ├─irodsAgent(31113)
        │                   ├─irodsAgent(31813)
        │                   ├─irodsReServer(7567)
        │                   ├─{irodsServer}(7568)
        │                   ├─{irodsServer}(7569)
        │                   ├─{irodsServer}(7570)
        │                   ├─{irodsServer}(7571)
        │                   ├─{irodsServer}(7572)
        │                   ├─{irodsServer}(7573)
        │                   ├─{irodsServer}(7574)
        │                   ├─{irodsServer}(7575)
        │                   ├─{irodsServer}(7576)
        │                   └─{irodsServer}(7577)
```

**Comment by kript** [comment]
We only run the rebalance manually, not via cron, BTW.

**Comment by trel** [comment]
I know it's only manual :)

To see the 'evidence' of the rebalance...
```
grep "writing to root" irods_g1_rodsLog.2017.10.11
```
This showed a similar pid (3442) a large number of times.

```
grep "pid:3442" irods_g1_rodsLog.2017.10.11
```
This showed a long string of work being done with nearly consecutive timestamps.

**Comment by kript** [comment]
So it appears we have three problems;

1. No visibility of rebalance running 
2. if a rebalance is in a shell wrapper it may not terminate when wrapper is exited
3. There is nothing to stop  more than one rebalance being run in a zone at any one time.

All of these are in fact the first problem. :-)

This leads to the hypothesis that the only way to know a rebalance is not active after one has been run is to restart the iRODS server process?

I can schedule a restart of the service with @keithj and team's agreement, but unless we have some kind of flag to show rebalance is running, the only sensible course is to schedule a restart after every rebalance catchup, which is rather disruptive.

**Comment by trel** [comment]
I'm going to bump this to 4.1.12 and implement option 2) above.

> Add a 'rebalance-delay-in-seconds' or 'rebalance-age-in-seconds' or 'rebalance-mtime-in-seconds' parameter to the rebalance operation (probably via replication resource context string) which would allow very new data objects to avoid being picked up by the rebalance operation. More research would be necessary to decide on a default value -- I would guess a few seconds (5?) would be enough to reduce the race condition cases to nearly zero.

Knowing whether a rebalance is currently running might be done by writing `PID` files for the rsGenAdmin() function.  That would be a new issue.

**Comment by keithj** [comment]
Following a server restart to ensure that all rebalance jobs are killed, we are still seeing an extra replicate appearing on many (but not all) new data objects. I've checked that the jobs were started after the server restart - the first process doing this connected about 30 seconds after the restart, the second 60 minutes after the restart.

There is something going on here in addition to any race between replication and rebalancing, I think. What exactly, I don't know yet.

**Comment by jasoncoposky** [comment]
@keithj can you check the PIDs in the logs for the creation of the 3 replicas?  Is it a 2+1 scenario where 2 replicas were created by the same PID and then a mysterious 2nd PID created the 3rd replica?

**Comment by kript** [comment]
I've been grepping through the logs trying to find a pattern to show, but its quite tricky due to #3480 and `baton-do` reusing the connection (as I understand reading the logs). I've uploaded the logs to the usual place for you as `irods-g1_rodsLog.2017.10.16.gz`.  
The only thing I can see is that somehow pid 9116 appears to survive the reboot, but isn't in the process table (checking just now there are no irodsAgent processes older than about 40 mins and the service restart was done yesterday, so I may be misreading that.

**Comment by trel** [comment]
I think it's a misread...  PID 9116 was never a server PID, it was always an Agent, and so, never 'survived' a reboot.

PID 9116 entries in your logfile are independent, regular Agents, living and dying every hour or so due to PID rollover on the server.  This is normal and expected.

Eventually, a rebalance comes along, happens to get Agent PID 9116, do a lot of work for just over two hours, and then exit cleanly as well.

```
Oct 18 12:39:16 pid:14063 NOTICE: Agent process 9116 started for puser=xxxxx and cuser=xxxxx from xxx.xxx.xxx.xxx
Oct 18 12:39:18 pid:9116 NOTICE: writeLine: inString = writing to root
...
Oct 18 14:42:34 pid:9116 NOTICE: writeLine: inString = writing to root
Oct 18 14:42:35 pid:9116 NOTICE: readAndProcClientMsg: received disconnect msg from client
Oct 18 14:42:35 pid:9116 NOTICE: Agent exiting with status = 0
Oct 18 14:42:35 pid:14063 NOTICE: Agent process 9116 exited with status 0
```

Then the rolling-over, unrelated Agent PIDs numbered 9116 begin appearing again every hour or so, still normal and expected.

```
Oct 18 15:37:31 pid:14063 NOTICE: Agent process 9116 started for puser=xxxxx and cuser=xxxxx from xxx.xxx.xxx.xxx
Oct 18 15:37:57 pid:9116 NOTICE: readAndProcClientMsg: received disconnect msg from client
Oct 18 15:37:57 pid:9116 NOTICE: Agent exiting with status = 0
Oct 18 15:37:57 pid:14063 NOTICE: Agent process 9116 exited with status 0
Oct 18 16:35:22 pid:14063 NOTICE: Agent process 9116 started for puser=xxxxx and cuser=xxxxx from xxx.xxx.xxx.xxx
Oct 18 16:35:23 pid:9116 NOTICE: readAndProcClientMsg: received disconnect msg from client
Oct 18 16:35:23 pid:9116 NOTICE: Agent exiting with status = 0
Oct 18 16:35:23 pid:14063 NOTICE: Agent process 9116 exited with status 0
```

If you can identify a particular data object that has three replicas with the same timestamps, we can find the PIDs that created those replicas.

So far, all evidence has suggested the PID that creates an unwanted third replica is different from the PID that creates the other two replicas.  We have only seen the PID pattern of 1-2-1 when creating the three replicas.  A pattern in the logfile of 1-1-2 would be strange since there would already be two good replicas created by PID 1 and PID 2 wouldn't be necessary.

The smoking gun for a misbehaving `iput` would be three replicas written by the same PID (pattern of 1-1-1).

**Comment by trel** [comment]
If we add a timestamp check to the rebalance operation SQL, we can limit any new work to be on replicas that existed *only before* the rebalance was called.  This is similar to, but more definitive than, the above-mentioned proposal of 'rebalance-delay-in-seconds' in the context string.

This new SQL would prevent the paging from picking up files created-after-invocation that need to be replicated (perhaps doubling up work being done by the replication node itself, resulting in too many replicas). Any files created-after-invocation would be picked up by the next rebalance run.

**Comment by keithj** [comment]
We don't have any rebalance running at the moment and we are seeing 3 replicates from `iput`:

````
  srpipe            0 root;replicate;seq-red;red3;irods-seq-i15-fg   1348248521 2018-03-05.15:25 & 25242_2#0.cram
    27d03a769340517ecedd1bfc401b6af6    generic    /irods-seq-i15-fg/25242/25242_2#0.cram
  srpipe            1 root;replicate;seq-green;green5;irods-seq-sr06-bc   1348248521 2018-03-05.15:25 & 25242_2#0.cram
    27d03a769340517ecedd1bfc401b6af6    generic    /irods-seq-sr06-bc/25242/25242_2#0.cram
  srpipe            2 root;replicate;seq-green;green5;irods-seq-sr08-bc   1348248521 2018-03-05.15:25 & 25242_2#0.cram
    27d03a769340517ecedd1bfc401b6af6    generic    /irods-seq-sr08-bc/25242/25242_2#0.cram
````

**Comment by jasoncoposky** [comment]
@keithj Do you have the logs for those servers?

**Comment by keithj** [comment]
I don't have access to the logs, I'm afraid - I'll talk to @kript.

**Comment by keithj** [comment]
@jasoncoposky relevant logs will be sent by @kript (thanks!)

**Comment by kript** [comment]
logs were provided in a screen share/conf call with @trel yesterday - if you need more/ the full files, please do say.

**Comment by jasoncoposky** [comment]
@kript does ips return any iadmin commands in flight for the zone?

**Comment by kript** [comment]
Yes, but as we use `iadmin` quite extensively for getting resource information, thats not a good metric. OTOH, none of the sessions are very long lived;

```
$ ips | grep iadmin
    15567 irods#seq  0:00:01  iadmin  172.24.64.13
    15603 irods#seq  0:00:00  iadmin  172.17.10.144
    15608 irods#seq  0:00:00  iadmin  172.24.64.39
```

**Comment by trel** [comment]
Can you do a quick check on 'all servers'?

`ips -a | grep iadmin`

**Comment by kript** [comment]
Running that, as of now, shows no `iadmin` sessions whatsoever.

**Comment by kript** [comment]
So as you know, we've had to kick off another rebalance as the number of dirty and single replica file was growing beyond what was comfortable to leave. It ran for ~12 hours before crashing with;
```
Mar 27 08:18:52 pid:7785 NOTICE: proc_results_for_rebalance: replicating data id [142451415] from [root;replicate;seq-red;red3;irods-seq-i18-de] to [root;replicate;seq-green;green5;irods-seq-sr07-bc]
Mar 27 08:18:52 pid:7785 NOTICE: proc_results_for_rebalance: replicating data id [142451964] from [root;replicate;seq-red;red4;irods-seq-i24-bc] to [root;replicate;seq-green;green2;irods-seq-sr02-ddn-rd10-39-40-41]
Mar 27 08:18:52 pid:7785 ERROR: [-]     libpassthru.cpp:793:passthru_file_rebalance :  status [UNIX_FILE_OPEN_ERR]  errno [No such file or directory] -- message []
                [-]     irods_repl_rebalance.cpp:571:proc_results_for_rebalance :  status [UNIX_FILE_OPEN_ERR]  errno [No such file or directory] -- message []
                        [-]     irods_repl_rebalance.cpp:63:repl_for_rebalance :  status [UNIX_FILE_OPEN_ERR]  errno [No such file or directory] -- message [Failed to replicate the data object [/seq/20808/20808_1#163_quality_error.txt]]
Mar 27 08:18:52 pid:7785 ERROR: [-]     iRODS/server/api/src/rsGeneralAdmin.cpp:623:_rsGeneralAdmin :  status [UNIX_FILE_OPEN_ERR]  errno [No such file or directory] -- message [failed to rebalance resource]
        [-]     libpassthru.cpp:799:passthru_file_rebalance :  status [UNIX_FILE_OPEN_ERR]  errno [No such file or directory] -- message []
                        [-]     irods_repl_rebalance.cpp:571:proc_results_for_rebalance :  status [UNIX_FILE_OPEN_ERR]  errno [No such file or directory] -- message []
                                [-]     irods_repl_rebalance.cpp:63:repl_for_rebalance :  status [UNIX_FILE_OPEN_ERR]  errno [No such file or directory] -- message [Failed to replicate the data object [/seq/20808/20808_1#163_quality_error.txt]]
```
Which implies to me that the rebalance was trying to replicate a file already being copied in..

**Comment by keithj** [comment]
I have added a `--wlock` CLI option to our client (`baton-do` in https://github.com/wtsi-npg/baton/pull/202) and run a comparison between our current production code and our production code using this client with locking enabled.

1. Extra data object replicates were present after loading with our current production code.

2. Extra data object replicates were present after loading with our current production code with `--wlock` enabled.

The latter result was reproducible over as many attempts as I tried (upwards of 20), each time a different subset of newly added data objects would get an extra replicate. The frequency of extra replication varied between attempts. The test data objects were deleted manually from iRODS after each attempt.

**Comment by trel** [comment]
This has only been seen in production so far.   We have not been able to reproduce this behavior somewhere else.  The best approach at this time appears to be increasing the logging available to the production system in order to determine what is happening.

**Comment by trel** [comment]
We are also planning to add an `invocation_timestamp` to the rebalance operation so that data objects already in the catalog at that time are the only ones queued for rebalance. ( see above https://github.com/irods/irods/issues/3665#issuecomment-364560848 )
