### ISSUE TITLE
add context flag to replication node indicating recursive rebalance

### ISSUE THREAD

**Issue by jasoncoposky** [irods/irods#3672]
The replication resource plugin should have an option to not recurse the resource hierarchy in order to improve the performance of a rebalance operation.  The side effect will be that the leaf nodes will not update their object counts, if out of sync.  Also interior replication nodes will not be rebalanced.

Example:
```
iadmin modresc repl_resc context "recursive_rebalance=false"
```

**Comment by kript** [comment]
Could you elaborate a little please as to the impact of turning this off? 

Its not clear to me what "interior replication nodes" refers to. 
Also, does  "leaf nodes will not update their object counts, if out of sync" mean the `resc_objcount` in `admin lr ` output, or something more internal?

Thanks.

**Comment by jasoncoposky** [comment]
If you have a replication node at the root of the tree and the recursive descent is disabled then any nodes below that root will not have rebalance invoked.  In your case you have a single replication node, which will be fine.

You are correct regarding object counts.  The rebalance operation will perform a query and update that value when asked to rebalance, which may take quite a while given a large number of objects.

**Comment by trel** [comment]
To be a bit more specific,

In 4.1.x, the rebalance operation on a unixfilesystem resource will perform a query and update the `resc_objcount`, which may take quite a while given a large number of objects (and number of unixfilesystems at the bottom of the tree being asked to recursively rebalance).

The unixfilesystem resource no longer performs that query and update in a 4.2+ installation.
