### ISSUE TITLE
chlUpdatePamPassword verbose notice

### ISSUE THREAD

**Issue by tsmeele** [irods/irods#3673]
Oct  2 17:52:57 pid:47464 NOTICE: chlUpdateIrodsPamPassword :: getting a new password [.E_E2'usPtJNx.d*zNT,Pq] has a single quote
on iRODS 4.1.8 server
This message is frequently reported in log although it seems harmless.  Apparently iRODS will generate a new password if it finds a quote in a generated password.
Remove notice?

**Comment by trel** [comment]
Could easily downgrade it from `LOG_NOTICE` to `LOG_DEBUG`.

**Comment by tsmeele** [comment]
excellent solution :)

**Comment by trel** [comment]
loop added in https://github.com/irods/irods/commit/6dbad209f165567389dc495f446fd8d013ca2190 because odbc on suse12 was unhappy.

https://github.com/irods/irods/blob/c715a1d37b6389805e06ad401d5cf05f151f90c6/plugins/database/src/db_plugin.cpp#L7525-L7528
