### ISSUE TITLE
occasional test failure in Test_Resource_Replication.test_num_repl_policy__ticket_2851

### ISSUE THREAD

**Issue by trel** [irods/irods#3706]
- [x] master
- [x] 4-2-stable

--
irods.test.test_resource_types.Test_Resource_Replication.test_num_repl_policy__ticket_2851

Sometimes, an assertion error occurs:

```
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_resource_types.py", line 3569, in test_num_repl_policy__ticket_2851
    assert len(hier_ctr) == 3
AssertionError
```

seen on:
- ub16-mysql

Not enough determinism in this assertion:
  https://github.com/irods/irods/blob/130279ec1e4181af0daed1925750af4f1bba2068/scripts/irods/test/test_resource_types.py#L3568-L3569

Need a better test.

**Comment by jaking92** [comment]
Just saw this on cen7-mysql

**Comment by trel** [comment]
and on ub16-psql

**Comment by trel** [comment]
rewrite test to just count the number of replicas for each of `num_repl=1` through `num_repl=3`.
