### ISSUE TITLE
Mysql case errors in table names for group queries

### ISSUE THREAD

**Issue by michael-conway** [irods/irods#3717]
- [x] master
- [x] 4-2-stable
- [x] 4-1-stable
-------

Apparently the direct sql for mysql gets angry with the case of the table names...

See https://github.com/DICE-UNC/jargon/issues/272 for logs, etc

**Comment by trel** [comment]
It's been wrong for more than four years...  table names need to be upper cased.

https://github.com/irods/irods/blame/4-2-stable/plugins/database/src/mid_level_routines.cpp#L1670
