### ISSUE TITLE
www.irods.org has different hostname in certificate

### ISSUE THREAD

**Issue by cookie33** [irods/irods#3718]
The web page ```www.irods.org``` has a certificate for the hostname ```irods.org```. It is valid till the 5th of February 2018.

Some browsers will now complain that it is not valid.. Safari does complain.

![screen shot 2017-11-08 at 09 35 34](https://user-images.githubusercontent.com/5128107/32539127-ba54a90e-c468-11e7-81a2-096b1e75af3c.png)

It might be time to replace it..

**Comment by trel** [comment]
Thanks for the report.

The website is currently an auto-redirect to irods.org (without www), where the cert is valid.  Like you say, the other browsers forward without complaint, and then certify correctly.  Safari catches the intermediate hop and complains.

EFF's Certbot will begin issuing wildcard certs in January 2018 - and we will be in line when they are rolled out.  This issue should resolve itself at that time.

  https://certbot.eff.org/faq/#will-let-s-encrypt-issue-wildcard-certificates

I'll leave this open until we get it squared away.

**Comment by cookie33** [comment]
It might also be worth a while to use alt names in the certificate: https://en.wikipedia.org/wiki/Subject_Alternative_Name

**Comment by trel** [comment]
Ah... very possible.

https://certbot.eff.org/faq/#can-i-get-a-certificate-for-multiple-domain-names-san-certificates

**Comment by trel** [comment]
Well, this took way too long to fix.

Done!

<img width="371" alt="www irods org-secure" src="https://user-images.githubusercontent.com/55238/186796731-e2ca3abe-cc5f-4209-b100-15246fddd3ee.png">
