### ISSUE TITLE
msiServerMonPerf not working in 4.2+

### ISSUE THREAD

**Issue by trel** [irods/irods#3736]
- [x] master
- [x] 4-2-stable

---
As per conversation at https://groups.google.com/forum/#!topic/irod-chat/1EOuXzLlJIY:

> quick fix:
>
> - edit /var/lib/irods/msiExecCmd_bin/irodsServerMonPerf
> 
> in line 141 remove one “..” to point to an existing directory /var/lib/irods/config/
>
> - put your scriptMonPerf.config in /var/lib/irods/config/

this is presumably due to moving most of the source up a directory in 4.2.0 from /var/lib/irods/iRODS/ to /var/lib/irods/

**Comment by trel** [comment]
Just need to:
- update https://github.com/irods/irods/blob/4-2-stable/msiExecCmd_bin/irodsServerMonPerf#L134
- add a test to capture this basic usage

**Comment by jaking92** [comment]
We need to skip test_msiServerMonPerf_default_3736 when the native rule language rule engine plugin is not being used because it breaks the test suite for the python rule engine plugin (and probably others).

**Comment by trel** [comment]
skipped - closing.
