### ISSUE TITLE
Include resource 'comment' and 'info' in izonereport

### ISSUE THREAD

**Issue by mcv21** [irods/irods#3739]
- [x] main
- [x] 4-3-stable
---
Hi,
Unless I'm missing something (always a possibility ;-) ), `izonereport` doesn't include the size of a resource in its output, at least in 4.1. Could this be added, please? We have scripts that use `izonereport` for collecting data on resources, and currently we have to infer the resource size based on the `minimum_free_space_for_create_in_bytes` context string...

**Comment by trel** [comment]
You are interested in knowing how much physical space a particular resource could use?

What if it is S3 or other object store or ceph rados cluster than can be added to without bound?

**Comment by trel** [comment]
You could add another `key=value` of your choosing to the context string which would be included in the `izonereport`...

**Comment by mcv21** [comment]
In our case, each resource is a filesystem. We'd like `izonereport` output apropos those resources to contain the size of the filesystem.
We run a ceph cluster (nothing to do with iRODS), and it definitely has bounded size ;-) That notwithstanding, you could either omit the size field or set it to `-1` or `NaN` or `None` or somesuch for resources where their size isn't well-defined...
[similar could be applied to `iadmin lr` apropos unixfilesystem resources]

**Comment by trel** [comment]
Understood - but we don't want to have special cases of treating the plugins differently from 'above'.

Annotating the resources with the size information you care about seems like the most flexible solution.  You could populate that information at the same time you're setting the `minimum_free_space_for_create_in_bytes`.

**Comment by trel** [comment]
We will not be including specific or generated fields for unixfilesystem.   The context string can hold any additional information today.

We can, however, add the 'comment' and 'info' fields to the zonereport.

**Comment by alanking** [comment]
@Nishant2022 - Please close if complete. Thanks!
