### ISSUE TITLE
Data items with only 1 replica in a replicated resource

### ISSUE THREAD

**Issue by mcv21** [irods/irods#3746]
Hi,
As you know, at Sanger our irods 4.1.10 setup uses replication. We keep finding items being added with only 1 replica, rather than the 2 we would expect. Whilst a rebalance will typically find and fix this, it's obviously quite a significant failure if iRODS isn't making 2 copies to begin with. There seems to be an association with higher use of iRODS (suggesting a race), but we've not managed a straightforward reproducer.

For example, `ils -L`:
```
  srpipe            0 root;replicate;seq-red;red4;irods-seq-i21-bc      3366918 2017-11-30.16:55 & differential_expression.csv
    b4ed6716d2278dc6ad3933aabd04d4f7    generic    /irods-seq-i21-bc/24346/cellranger/cellranger202_count_24346_FUGI_R_D7159524_Schistosoma_mansoni_v7_r12_CDS_UTR/analysis/diffexp/kmeans_8_clusters/differential_expression.csv
```

The logging we get from iRODS doesn't really make it straightforward to follow the path this file took through iRODS; here follows my best guesses - I'll send you the fuller rodslogs from the machines involved under separate cover.

Starting on `irods-seq-i21`:
`stat(1)` gives me a timestamp of 2017-11-30 16:55:15.956244232 +0000
```
Nov 30 16:55:13 pid:2527 NOTICE: Agent process 31595 started for puser=irods and cuser=srpipe from 172.24.64.24
Nov 30 16:55:18 pid:2527 NOTICE: Agent process 31595 exited with status 0
```
That ip is, curiously, `irods-seq-i15`, from where:
```
Nov 30 16:55:12 pid:2350 NOTICE: Agent process 31902 started for puser=irods and cuser=srpipe from 172.17.139.6
Nov 30 16:55:18 pid:31902 NOTICE: Agent exiting with status = 0
```
That ip is `irods-sanger1`, which is the federation master. It's much harder to find something there because the logs are much noisier, but I think:
```
Nov 30 16:55:09 pid:29126 NOTICE: Agent process 8799 started for puser=srpipe and cuser=srpipe from 172.17.168.114
Nov 30 16:55:17 pid:8799 NOTICE: readAndProcClientMsg: received disconnect msg from client
Nov 30 16:55:17 pid:8799 NOTICE: Agent exiting with status = 0
```

I might be off-base with these, but the other `srpipe` log entries from around the same period have the Agent process exiting 0 within a second.

There's nothing obviously complaining in those logs, and yet we have only 1 replica in what is supposed to be a replicated resource. This is quite worrying!

How would you suggest we proceed in trying to debug this? I'm afraid we've not been able to reproduce in our `-dev` zone, so any approach needs to be compatible with our production zone.

Thanks,
Matthew

**Comment by trel** [comment]
This will best be addressed by a combination of:
- https://github.com/irods/irods/issues/3436
- https://github.com/irods/irods/issues/3529
- https://github.com/irods/irods/issues/3480

**Comment by trel** [comment]
I'm planning to close this soon - there is no more direct action to take here.
