### ISSUE TITLE
irods client install with non root privileges

### ISSUE THREAD

**Issue by nief** [irods/irods#3747]
hello,

we have installed the 4.2.1 clients on the machines used by our end users (CentOS7). We usually install them in a distributed file system (we have to offer several version of the iRODS clients as everybody is not using the same version on the server side). We extracted the binaries and shared libs from the package and installed it in <prefix>/irods/4.2.1. We put the libs in <prefix>/irods/4.2.1/lib:
> ls -l <prefix>/irods/4.2.1/lib/
total 4531
drwxr-xr-x 3 nief ccin2p3      25 Nov  8 04:31 irods
lrwxrwxrwx 1 nief ccin2p3      24 Nov 13 23:26 libirods_client.so -> libirods_client.so.4.2.1
-rwxr-xr-x 1 nief ccin2p3 1445863 Jun  8 08:32 libirods_client.so.4.2.1
lrwxrwxrwx 1 nief ccin2p3      24 Nov 13 23:26 libirods_common.so -> libirods_common.so.4.2.1
-rwxr-xr-x 1 nief ccin2p3 1387305 Jun  8 08:31 libirods_common.so.4.2.1
lrwxrwxrwx 1 nief ccin2p3      37 Nov 13 23:26 libirods_plugin_dependencies.so -> libirods_plugin_dependencies.so.4.2.1
-rwxr-xr-x 1 nief ccin2p3  398754 Jun  8 08:31 libirods_plugin_dependencies.so.4.2.1
In irods directory above, the plugins shared libs are stored.
However, when running an icommand, we had errors like this one caused by a hard coded path:
irods::load_plugin(PluginType *&, const std::string &, const std::string &, const std::string &, const std::string &) [PluginType = irods::network] :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message []
                                                [-]     /home/irodsbuild/irods/lib/core/include/irods_load_plugin.hpp:66:irods::error irods::resolve_plugin_path(const std::string &, std::string &) :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message [does not exist [<prefix>/irods/usr/lib/irods/plugins/network]]

It tries to look for <prefix>/irods/usr/lib/irods/plugins/network which does not exist. In order to bypass the problem for the time being, I had to create an ugly workaround:
> ls -l <prefix>/irods
.....
lrwxrwxrwx 1 nief ccin2p3    5 Dec  1 16:19 usr -> 4.2.1
.....
with that symlink, it is solving the problem.
Could it be possible in future release to remove these hardcoded path ?
As we have many instances, we will have to manage several plugins versions as well and that is not doable like this.
Also, for remote installations, it wo't be very flexible for our end users who have non root privileges on the machines they are running (they would have to go through the same steps).
thanks,
JY

**Comment by trel** [comment]
Hi JY, we might have missed updating things for this scenario...

Have you tried to use the client side `irods_plugins_home` setting in `irods_environment.json`?

**Comment by nief** [comment]
thanks Terrell. 
Missed this one. Yes, I just tried it, it is working properly. 
Is it possible to set it this variable using an environment variable ?
It can be more flexible for me as there will be no need for the end user to modify his irods_environment.json when we switch to a new release and, most presumably, newer versions of the plugins.

**Comment by trel** [comment]
I believe you can set it in the environment with the all caps version... `IRODS_PLUGINS_HOME`.  Please confirm.

I'll get the documentation updated since this was lost in the move to 4.2, apparently.

**Comment by nief** [comment]
yes, that's it!
thanks

**Comment by trel** [comment]
closed by https://github.com/irods/irods_docs/commit/0b20307961aad45db25cfe87f1ddeb6a2ddd7f26
