### ISSUE TITLE
datetimef in rule not working as expected 

### ISSUE THREAD

**Issue by kuntzagk** [irods/irods#3767]
- [x] master
- [x] 4-2-stable
- [x] 4-1-stable
-------

I try to convert a string like 2018-01-01 using the datetimef function. I does not work as expected.

Rule:
```
testRule{
     *RetTime = "2018-01-01";
     writeLine("stdout","*RetTime");
     writeLine("stdout",datetimef(*RetTime,"%Y-%m-%d"));
}

OUTPUT ruleExecOut
```

Output:
```
$ irule -sF test.r
2018-01-01
Apr 05 5744 14:57:12
```

If I explicitely cast the datetime back to string I get another result

```
testRule{
     *RetTime = "2018-01-01";
     writeLine("stdout","*RetTime");
     writeLine("stdout",timestr(datetimef(*RetTime,"%Y-%m-%d")));
}
```
Output:
```
$ irule -sF test.r
2018-01-01
Dec 05 5773 22:05:12
```

I would expect to get the original date 2018-01-01.

Tested in 4.1 and 4.2.2

**Comment by trel** [comment]
Well that doesn't look good at all.

**Comment by trel** [comment]
Hao found three uninitialized variables (%H, %M, and %S) when they're not populated by you - will be a quick fix.

This will currently work as expected:
```
testRule{
     *RetTime = "2018-01-01 00:00:00";
     writeLine("stdout","*RetTime");
     writeLine("stdout",datetimef(*RetTime,"%Y-%m-%d %H:%M:%S"));
}
```

**Comment by kuntzagk** [comment]
I'm not sure if this is a symptom of the same bug or a different one.
When I "cast" a datetime to a string I get a time that is off by a few hours.
```
testRule{

*StringTime1 = "2029-07-03-00.00.00"; # Starting time
*DateTime1= datetimef(*StringTime1,"%Y-%m-%d-%H.%M.%S"); # Time as datetime type
*StringTime2 = timestrf(*DateTime1, "%s"); # string with seconds since epoch

writeLine("stdout","*StringTime1 *DateTime1 *StringTime2 ");
}

OUTPUT ruleExecOut
```

Output:
```
$ irule -sF test.r
2029-07-03-00.00.00 Jul 03 2029 00:00:00 1877724000
```

If I compute the last number back to human readable I get "GMT: Monday, July 2, 2029 10:00:00 PM"
(I used https://www.epochconverter.com/ )

regards, Andreas

**Comment by trel** [comment]
Feels like a timezone issue... where are you?  +2?

```
Andreas   2029-07-03-00.00.00 Jul 03 2029 00:00:00 1877724000    GMT: Monday, July 2, 2029 10:00:00 PM
Correct   2029-07-03-00.00.00 Jul 03 2029 00:00:00 1877731200    GMT: Tuesday, July 3, 2029 12:00:00 AM
Terrell   2029-07-03-00.00.00 Jul 03 2029 00:00:00 1877745600    GMT: Tuesday, July 3, 2029 4:00:00 AM
```

**Comment by kuntzagk** [comment]
@trel you're right.  Stupid me. First I mixed am and pm and then I was unable to compute 12-10 and last I did not think about timezones.
