### ISSUE TITLE
delayed rule queue processing slows down as the queue length grows

### ISSUE THREAD

**Issue by tedgin** [irods/irods#3782]
- [x] master
- [x] 4-2-stable
------

I'm using iRODS 4.1.10.

I noticed that as the delayed rule queue length grows, the delayed rule execution rate decreases. Here's a graph showing the converse (as the queue length shrinks, the execution rate increases).

![queue length over time](https://user-images.githubusercontent.com/1766102/34739418-6d6da012-f539-11e7-9d30-70307509a96b.png)

At the time of peak queue length, I stopped rules from being added to the queue.

When our users are really active, the queue length can grow quite large. It grew large enough recently, that we experienced "run away" growth of the queue.  In other words, when user activity returned to normal, the queue kept growing in length.

**Comment by tedgin** [comment]
I forgot to mention that we are running 16 concurrent rule engine server processes.

**Comment by trel** [comment]
Interesting.

Does the concurrency have an effect on this behavior?    2, 4, 8, 16, 32?

Any speculation on the reason the execution time would change (for jobs that are, presumably, equivalent)?

**Comment by tedgin** [comment]
A month ago we increased from 8 to 16, because on occasion the queue would grow large.  For our setup, going to 16 appears to have decreased the number of rules executed per day.  I don't have good numbers yet.

The jobs are almost all small (< 100 kB) file transfers, so they should be roughly equivalent. 

I'm not certain if IES has an internal cache of the rule queue or whether it asks the ICAT for the latest update of the queue every time it executes a delayed rule.  The later would be pretty inefficient.  I know that when the queue was near its peak length (`1/6/18 00:00` on the graph above), it was querying the ICAT for the entire queue about 1 to 2 times per second. Each query took between 1 and 3 seconds to execute.  Returning the entire queue in sorted order each time would be an order `n` operation I'm guessing since the rules table has an index of the sorting term.  That would imply that the processing of the queue would get slower as the queue grows in length.
