### ISSUE TITLE
"imeta mod"  broken for case of no units in release 4.2.2

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#3787]
- [ ] master
- [x] 4-2-stable
-------

imeta, as used in the irods_training beginner .PDF doc, does not successfully execute a 'mod' operation when the units field of the metadata-to-be-changed is zero-length

**Comment by JustinKyleJames** [comment]
Examples:  

imeta mod -d myfile oldattr oldval n:newattr
imeta mod -d myfile oldattr oldval '' n:newattr
imeta mod -d myfile oldattr oldval '' v:newval
imeta mod -d myfile oldattr oldval '' u:newunit

**Comment by d-w-moore** [comment]
Maybe also ...


  imeta mod -d myfile oldattr oldval oldunit u:


I tried this (which, inasfar as I understand the hypothetically correct behavior of imeta , should actually cause the units on the metadata record to become blank) and it fails under 4.1.0 as well as under 4.2.2  ...  my example session for 4.1.0  is attached


-Dan


________________________________

**Comment by d-w-moore** [comment]
hey Justin,


  here it is ... add it onto the end of your ~/.bashrc and subsequent shells should launch with the git annotated & colorized prompts....


-D


#_______________

function tgrps1 {
  local BOLDRED="\[\033[1;31m\]"
  local GREEN="\[\033[0;32m\]"
  local BOLDYELLOW="\[\033[1;33m\]"
  local BOLDCYAN="\[\033[1;36m\]"
  local NOCOLOR="\[\033[0m\]"
  export GIT_PS1_SHOWDIRTYSTATE=1
  PS1=$BOLDRED'`echo "ERROR($?) " | sed '\''s/^ERROR(0) \$//'\''`'
  PS1+="$GREEN\$(date +%H:%M%p)"
  PS1+="$BOLDYELLOW\$(__git_ps1) "
  PS1+="$BOLDCYAN\u$NOCOLOR@\h:\w \$ "
}
tgrps1



function tgrps1 {
  local BOLDRED="\[\033[1;31m\]"
  local GREEN="\[\033[0;32m\]"
  local BOLDYELLOW="\[\033[1;33m\]"
  local BOLDCYAN="\[\033[1;36m\]"
  local NOCOLOR="\[\033[0m\]"
  export GIT_PS1_SHOWDIRTYSTATE=1
  PS1=$BOLDRED'`echo "ERROR($?) " | sed '\''s/^ERROR(0) \$//'\''`'
  PS1+="$GREEN\$(date +%H:%M%p)"
  PS1+="$BOLDYELLOW\$(__git_ps1) "
  PS1+="$BOLDCYAN\u$NOCOLOR@\h:\w \$ "
}
tgrps1

**Comment by d-w-moore** [comment]
Maybe also ... imeta mod -d myfile oldattr oldval oldunit u: I tried this (which, inasfar as I understand the hypothetically correct behavior of `imeta`, should actually cause the units on the metadata record to become blank) and it fails under 4.1.0 as well as under 4.2.2 ... my example session for 4.1.0 is attached danielm@danielm-VirtualBox:~/.irods$ imeta ls -u alice AVUs defined for user alice#tempZone: None danielm@danielm-VirtualBox:~/.irods$ imeta set -u alice myname myvalue myunits danielm@danielm-VirtualBox:~/.irods$ imeta ls -u alice AVUs defined for user alice#tempZone: attribute: myname value: myvalue units: myunits danielm@danielm-VirtualBox:~/.irods$ imeta mod -u alice myname myvalue myunits u:yourunits danielm@danielm-VirtualBox:~/.irods$ imeta ls -u alice AVUs defined for user alice#tempZone: attribute: myname value: myvalue units: yourunits danielm@danielm-VirtualBox:~/.irods$ imeta mod -u alice myname myvalue yourunits u: ERROR: rcModAVUMetadata failed with error -816000 CAT_INVALID_ARGUMENT danielm@danielm-VirtualBox:~/.irods$ imeta mod -u alice myname myvalue yourunits u:backtomyunits danielm@danielm-VirtualBox:~/.irods$ imeta ls -u alice AVUs defined for user alice#tempZone: attribute: myname value: myvalue units: backtomyunits

**Comment by d-w-moore** [comment]
Maybe also ...
```
 imeta mod -d myfile oldattr oldval oldunit u: 
```
I tried this (which, inasfar as I understand the hypothetically correct behavior of `imeta`, should actually cause the units on the metadata record to become blank) and it fails under 4.1.0 as well as under 4.2.2 ... my example session for 4.1.0 is attached.

```
danielm@danielm-VirtualBox:~/.irods$ imeta ls -u alice
AVUs defined for user alice#tempZone:
None
danielm@danielm-VirtualBox:~/.irods$ imeta set -u alice myname myvalue myunits 
danielm@danielm-VirtualBox:~/.irods$ imeta ls -u alice
AVUs defined for user alice#tempZone:
attribute: myname
value: myvalue
units: myunits
danielm@danielm-VirtualBox:~/.irods$ imeta mod -u alice myname myvalue myunits u
:yourunits
danielm@danielm-VirtualBox:~/.irods$ imeta ls -u alice
AVUs defined for user alice#tempZone:
attribute: myname
value: myvalue
units: yourunits
danielm@danielm-VirtualBox:~/.irods$ imeta mod -u alice myname myvalue yourunits
 u:
ERROR: rcModAVUMetadata failed with error -816000 CAT_INVALID_ARGUMENT 
danielm@danielm-VirtualBox:~/.irods$ imeta mod -u alice myname myvalue yourunits
 u:backtomyunits
danielm@danielm-VirtualBox:~/.irods$ imeta ls -u alice
AVUs defined for user alice#tempZone:
attribute: myname
value: myvalue
units: backtomyunits
danielm@danielm-VirtualBox:~/.irods$ imeta -h
Usage: imeta [-vVhz] [command]

        8<...snip...snip...>8

iRODS Version 4.1.0                May 2015                      imeta
danielm@danielm-VirtualBox:~/.irods$ 

```

**Comment by d-w-moore** [comment]
imeta mod now allows :
 * matching on and changing metadata records with blank units
 * blanking out unit fields which were previously non-blank
