### ISSUE TITLE
Server Negotiation logs CS_NEG warnings with null message

### ISSUE THREAD

**Issue by tedgin** [irods/irods#3789]
I'm using iRODS 4.1.10.  

Looking through our server log files, I'm seeing many  messages of the following form:

```
Jan  1 00:28:54 pid:18904 WARN: CS_NEG :: [(null)]
```

It looks like the warning is generated from the following statement. 

https://github.com/irods/irods/blob/bb48cd38c4a543ad8bf45082fa06b15290378b50/iRODS/server/core/src/irods_server_negotiation.cpp#L200-L203

The macro `PASS` creates an `irods_error` object. The `irods_error::status()` method returns a `bool`.  I'm guessing the code should be calling `irods_error::result()` instead.  

This is only a minor issue, but I thought I would mention it.

**Comment by trel** [comment]
Yes, this was removed in the run-up to 4.2

https://github.com/irods/irods/commit/f41e55e9410eaa1fb00282a3fc349fc48009b87b

PR?

**Comment by tedgin** [comment]
Yet another reason to upgrade.  

No need to fix this on our account.  Fingers crossed, we'll be upgrading to iRODS 4.2 soon.

**Comment by trel** [comment]
Got it - thanks.
