### ISSUE TITLE
Checksum difference between iput & iput -K

### ISSUE THREAD

**Issue by trebunski** [irods/irods#3797]
### iRODS Version, OS and Version
iRODS Version 4.1.8                Feb 2016                     
CentOS release 6.9 (Final)

/etc/irods/server_config.json
...
"default_hash_scheme": "SHA256",
...

~/.irods/irods_environment.json
...
"default_hash_scheme": "SHA256"
...

### What did you try to do?
put same file twice with iput & iput -K

### Expected behavior
Same Checksum between iput & iput -K
It schould be the same BASE64 encoded SHA256 Checksum

### Observed behavior
Checksum(-Type) difference between iput & iput -K
The checksums are correct computed, but one is MD5 another is BASE64 encoded SHA256.

sha2:AnqCgXyxPgse/zyXkojVrDC5fnO6oG0toLllOECdQuI=

b13dfc6936eeed54d6532b5e75f83aa0

### Steps to reproduce
iput  ./basic_test_package.tgz /c/TEST/CheckSumIput
iput -K ./basic_test_package.tgz /c/TEST/CheckSumIput2

ils -L /c/TEST/

 rods              0 demoResc        51994 2018-01-22.16:09 & CheckSumIput
    sha2:AnqCgXyxPgse/zyXkojVrDC5fnO6oG0toLllOECdQuI=    generic    /c/archive/TEST/CheckSumIput
  rods              0 demoResc        51994 2018-01-22.16:13 & CheckSumIput2
    b13dfc6936eeed54d6532b5e75f83aa0    generic    /c/archive/TEST/CheckSumIput2

**Comment by trebunski** [comment]
The problem was:
~/.irods/irods_environment.json use "irods_default_hash_scheme" not "default_hash_scheme" variable name.

**Comment by trel** [comment]
Glad you worked out a solution.

Out of the box, a regular `iput` will not compute a checksum.   There must be something else in your configuration that was requesting an MD5 checksum be calculated and stored.
