### ISSUE TITLE
SHA512 ?

### ISSUE THREAD

**Issue by trebunski** [irods/irods#3800]
Any Plans for implementation of SHA512-Hasher ??

**Comment by trel** [comment]
Not currently, but of course, pull requests and/or conversation are always welcome.

Is there a use case driving your question?   What is the scenario where you have found a SHA512 checksum helpful/necessary?

**Comment by trebunski** [comment]
I do my own research, SHA512 is not realy much slower as SHA256 and all other software (except iRods ;) ) which I use in my project supports SHA512.
There is no real disadvantages of SHA512 over SHA256, and I just want to update my software future-proof.

**Comment by trel** [comment]
It would be an additional strategy for SHA512, similar to the SHA256 we already have:

https://github.com/irods/irods/blob/master/lib/hasher/include/checksum.hpp
https://github.com/irods/irods/blob/master/lib/hasher/include/SHA256Strategy.hpp
https://github.com/irods/irods/blob/master/lib/hasher/src/SHA256Strategy.cpp

And of course, any tests to confirm behavior alongside existing code/checksums.

**Comment by trel** [comment]
We've implemented and merged SHA-512 as part of https://github.com/irods/irods/issues/5392

It is not yet implemented for iput, iget, ichksum, etc... that would still be new work.

Closing as duplicate.
