### ISSUE TITLE
GSI zone authentication 

### ISSUE THREAD

**Issue by browe-fs** [irods/irods#3807]
### iRODS Version, OS and Version
iRODS  4.2.2
Centos 7

### What did you try to do?
I am trying to use GSI as an authentication method for server to server communication in an irods zone. 

### Expected behavior
The expectations are that the icommands have full functionality while using GSI as an authentication method.

### Observed behavior
The consumer and provider both have the server_config.json variable zone_auth_scheme set to GSI which made me think it was using GSI. The zone was actually using native authentication the whole time. This was discovered when I removed the .irodsA file from /var/lib/irods/.irods and started seeing authentication errors when running iput, iget, irm. 

### Steps to reproduce
Configure GSI certifications and an irods zone for GSI authentication. Remove .irodsA password file. Test icommand functionality when putting and getting to consumer and provider resources. 

Additional information on irod-chat
[https://groups.google.com/forum/#!topic/irod-chat/1Vfre_F_Tsk](url)

**Comment by alanking** [comment]
The last release for the GSI plugin was in 2019 and was compatible with 4.2.8: https://github.com/irods/irods_auth_plugin_gsi/releases/tag/2.6.0

I don't think we can say that we support this plugin anymore. I did some cursory searching for a PAM module for GSI but didn't find anything. If such a module exists, pam_interactive could (potentially) be used instead.

**Comment by trel** [comment]
GSI has been (re-)absorbed by Globus now - so agreed, I think we close this.
