### ISSUE TITLE
"imeta ls -d" core dump

### ISSUE THREAD

**Issue by trel** [irods/irods#3816]
### iRODS Version, OS and Version

4.2.2

### What did you try to do?

```
$ imeta ls -d

Error: Not enough arguments provided to ls

terminating with uncaught exception of type boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_any_cast> >: boost::bad_any_cast: failed conversion using boost::any_cast
Aborted (core dumped)
```
### Expected behavior

no core dump, just a clean error saying missing arguments

**Comment by JustinKyleJames** [comment]
This was fixed with irods/irods_client_icommands#27.  Test cases were added and passed.  Closing this issue.
