### ISSUE TITLE
document how to / tool to decommission a resource

### ISSUE THREAD

**Issue by trel** [irods/irods#3821]
## Use Case

> We had a RAID array fail and lost an entire resource full of files. 

The resource isn't coming back online.  The replicas in the catalog will not be replaced, they are effectively orphan records now.  They need to be removed from the catalog.

## Discussion

1) before
files - good - replicated in both red and green, under a replication resource
catalog - good - has entries for both replicas
system - good - regular operation

2) bad event occurs (use case: RAID array failure)
files - green is online, still good - red is now broken/offline, files are not there
catalog - still has entries for both replicas (but of course, red aren't available, resource still marked 'up')
system - gets/puts routed to lost resource will fail, clients will see errors

3) mark resource down
files - same as above, green good, red gone
catalog - still has entries, but now red resource is marked down
system - gets/puts now work, no routing to bad resource, clients happy, but system has only one good replica

4) bring new resource online, under replication
files - same as above, green good, red gone
catalog - has two entries, red still marked down
system - new files get replicated, existing files still have only one available, routing okay

5) rebalance
files - all files should now be in green and new
catalog - all files should have two entries, new are good x2, existing now have three (x2 good, x1 lost)?
system - not degraded, things route, but perhaps still have extra bad entries in catalog

6) remove replica listings in bad resource from catalog
    $ iquest "select COLL_NAME, DATA_NAME, DATA_PATH, DATA_REPL_NUM where RESC_NAME = 'bad'
    $ foreach badreplica; do irm -U logical_path; done
files - all files only in green and new
catalog - everything has two entries, in green and new
system - good, only have extra leftover resource in the catalog

7) remove bad resource
$ iadmin rmresc bad

Additional steps in there would be to move the bad resource out from the replication parent, but that is very expensive (in time) prior to 4.2 (regex instead of integers to represent parents/hierarchies).

## Proposal

Providing a tool or documentation to decommission the bad resource (step 6 above):

1) Create and support an `iadmin decommission badresc` subcommand.  But this feels too brittle and depends on C++ that could be more easily handled with a rulefile or shell script...

or

2) Document an example for how to do this cleanly.  Perhaps a shell script, python script, or iRODS rulefile that runs a query, reports the work about to be completed, asks for confirmation, and then performs the unregistrations.

**Comment by trel** [comment]
Step 6 (and the proposal) above can be more easily replaced with:

6. $ itrim -M -r -S bad /zoneName

This will recursively trim every user's data objects from source resource 'bad' in the entire 'zoneName', allowing step 7 to remove the bad resource itself.  Additionally, there is a `--dryrun` option.

**Comment by kript** [comment]
Apologies for reopening this, but after a(nother) RAID array failure, we are in the position of needing to recover an entire resource again, and step 6, with or without `--dry-run` don't work in 4.1.12 with composite resource trees;

```
irods-g1-dev@irods-g1-dev:~$ itrim --dryrun -M -r -S irods_r2_dev_sdb /seq-dev
====== This is a DRYRUN ======
ERROR: trimCollUtil: trimDataObjUtil failed for /seq-dev/home/aw7/zH263D14.bam. status = -1816000 status = -1816000 DIRECT_CHILD_ACCESS
ERROR: trimUtil: trim error for /seq-dev, status = -1816000 status = -1816000 DIRECT_CHILD_ACCESS
Total size trimmed = 0.000 MB. Number of files trimmed = 0.
irods-g1-dev@irods-g1-dev:~$ itrim -M -r -S irods_r2_dev_sdb /seq-dev
ERROR: trimCollUtil: trimDataObjUtil failed for /seq-dev/home/aw7/zH263D14.bam. status = -1816000 status = -1816000 DIRECT_CHILD_ACCESS
ERROR: trimUtil: trim error for /seq-dev, status = -1816000 status = -1816000 DIRECT_CHILD_ACCESS
Total size trimmed = 0.000 MB. Number of files trimmed = 0.
```

 #3831 is related. However, it does leave us without a way to decommission a resource short of moving the resource out of the tree and trimming there, which is pessimal for a resource with 12,223 files (albeit not unworkable, unlike our larger zones)

**Comment by trel** [comment]
Morning @kript :)

Good News:
 - You didn't reopen it.  Whew.

Other News:
- There's nothing actionable here?   If there is, we should open a new issue.
