### ISSUE TITLE
Need to grant write permission to irods user on /etc/irods

### ISSUE THREAD

**Issue by phuongdm** [irods/irods#3825]
I tried to install my micro-services (https://github.com/hydroshare/hydroshare-quota) into an iRODS 4.2.2 server and the iRODS server didn't work.  

The error log in the rodsLog file is "Permission denied":
...
terminating with uncaught exception of type boost::filesystem::filesystem_error: boost::filesystem::copy_file: Permission denied: 
...

After grant write permission to irods user (Linux user) on /etc/irods, everything seems OK. 

Just would like to know what happened?

**Comment by trel** [comment]
So, your package that was installed changed the permissions of the /etc/irods directory?

Presumably to `root:root`?

**Comment by phuongdm** [comment]
Yes, thanks. 

However, I'm using the template which I found from irods_training. Could you please help me to change the permission back to irods:irods in the CMakeList.txt file?

This issue didn't appear in 4.2.1 version

**Comment by trel** [comment]
Interesting - not sure why the behavior would be different from 4.2.1 to 4.2.2...

You can run a postinst script to change the permissions... maybe like this:  
  https://github.com/irods/irods_resource_plugin_s3/blob/master/packaging/postinst

**Comment by phuongdm** [comment]
Yeah, I know how to set the permission by shell command :) however just want to know what happened in 4.2.2 while this issue didn't appear in 4.2.1 and it would be better if I could set the permission on the CMakeLists.txt file. So, I only need to install the RPM package, do not need to run chmod/chown command.

In CMakeLists.txt, I only use this macro: `install(FILES hydroshare.re DESTINATION /etc/irods/)`

to  copy my config file to /etc/irods. There is no macro which changes owner/permission of /etc/irods

**Comment by trel** [comment]
Yes, of course.

The RPM and DEB are told to run that `postinst` script after the files are placed on the disk:

https://github.com/irods/irods_resource_plugin_s3/blob/master/CMakeLists.txt#L156

https://github.com/irods/irods_resource_plugin_s3/blob/master/CMakeLists.txt#L165

I'm still not sure why 4.2.2 would be different either.

**Comment by phuongdm** [comment]
Awesome. 

Thank you so much.

**Comment by phuongdm** [comment]
+1

This issue could be closed now.

Thanks again.
