### ISSUE TITLE
The irods package server certificate has expired

### ISSUE THREAD

**Issue by pdonorio** [irods/irods#3830]
I can't install rpms today because https://packages.irods.org/ has an expired SSL certificate.
See screenshot:
https://www.dropbox.com/s/3d7vki0a0eqwf4g/Screenshot%202018-03-05%2011.51.42.png?dl=0

I didn't know where to notify this, hope I can here

**Comment by trel** [comment]
Ah, apologies.  This was issued via our University - we're working to get it updated ASAP.

Thanks.

**Comment by trel** [comment]
For now, we have moved to a LetsEncrypt cert and should be good again.

**Comment by pdonorio** [comment]
Thank you!
