### ISSUE TITLE
Distribution of iRODS packages aside from the latest version and versions <=4.1.11

### ISSUE THREAD

**Issue by colin-nolan** [irods/irods#3836]
It does not seem like it is possible to get an iRODS package that is not either the latest (via apt/yum/etc.) or <=4.1.11 (via ftp).

We used to be able to download packages for any version of iRODS from the FTP server. However, the website implies that this distribution method has been abandoned (likely from 4.1.11 onwards):
> Before the move to APT and YUM repositories, the binary iRODS packages were made available via FTP.

The alternative package distrubtion method via apt/yum/etc appears (unless I am mistaken) to only offer packages from latest version of iRODS, e.g.:
```
$ apt-cache madison irods-icommands
irods-icommands |      4.2.2 | https://packages.irods.org/apt xenial/main amd64 Packages
```

It is often important that we use a particular version of an iRODS package, e.g. we need to match the icommand version with the server version or we want to create a test server that is the same version as our production server. Given that our production servers are not always on the bleeding edge (for example, here at Sanger, we're currently on 4.1.10, not 4.2.2), we cannot just use the system package manager to install whatever the latest version just happens to be in the apt repository.

Please could you ensure that you maintain the distribution of all released versions of iRODS?

**Comment by donsizemore** [comment]
Hello,

FWIW 4.2.0+ versions are available by browsing the repo, e.g.
[https://packages.irods.org/apt/pool/trusty/main/i/irods-icommands/](https://packages.irods.org/apt/pool/trusty/main/i/irods-icommands/)
though you're correct; I only see 4.2.2 for Xenial.

**Comment by colin-nolan** [comment]
@donsizemore this is good to know. 

Has there been an omission in Xenial or is this distro only supported in 4.2.2+?

In addition, where can I find releases `4.1.11 < version < 4.2.0` (I am interested in 4.1.12)?

**Comment by colin-nolan** [comment]
Looking further at this: I don't think 4.1.12 has actually been released. It would be good if someone could confirm where the packages will be once it is?

**Comment by trel** [comment]
The 4.1.x series will still be released FTP-only.   Correct, 4.1.12 is not yet released.

The APT/YUM repositories are only holding 4.2.x and later.

**Comment by trel** [comment]
We didn't have build machines for Xenial until 4.2.2 was ready.  We have no current plans to go back and populate older releases with newer distributions.

**Comment by colin-nolan** [comment]
Thanks for the confirmation @trel.
