### ISSUE TITLE
remove CS_NEG_DONT_CARE as client/server SSL configuration option

### ISSUE THREAD

**Issue by trel** [irods/irods#3837]
In a mixed-deployment zone (both SSL-enabled and non-SSL-enabled servers), the idea has been that setting the server's `irods_client_server_policy` to `CS_NEG_DONT_CARE` would allow the servers to determine whether each connection was encrypted.

This breaks down when parallel transfer (aka large file transfer) is used within the zone - since the servers will redirect any incoming connections to the correct destination server before the parallel transfer portal is setup... any mixed-SSL configurations will make the parallel transfer effectively impossible (and definitely very hard to debug when the failure is unexpected).

This issue proposes to remove the option defined as `CS_NEG_DONT_CARE`.  Either a server is SSL-enabled for all connections, or it is not.

Upside:
 - clearer expectations during planning, configuration, deployment, and behavior
 - easier to debug confusing scenarios

Downside/Unknowns:
 - federation behavior - do all federations need to move to SSL as well?  At the same time?  This is probably untenable as a proposal... can we enforce SSL-everywhere within a zone, but allow non-SSL connections when communicating with federated servers?

**Comment by cookie33** [comment]
At the moment we have the following configuration:
* 1 irods zone federated with 6 other zones (no SSL). They are external via the internet.
* our zone has a gridftp server configured against the irods server with GSI and DSI so we can offer a secure connection to outside users.

We would be very happy if the CS_NEG_DONT_CARE is still available and will not be removed. This so we can enable SSL. This way we can offer following:
* secure SSL connections within the zone with the irods client.
* secure SSL connections between zones if the other zones also have SSL implemented.
* insecure connections for those who have not enabled SSL (either federated zone or client)

If the functionality will be repaired we also have a fallback if/when gridftp is discontinued.

**Comment by trel** [comment]
Okay - then maybe changing the default configuration to be `CS_NEG_REFUSE` (#3461) will be all we can do for now.   Thanks for the input.

Anyone else have a new scenario?

**Comment by cookie33** [comment]
Hi,

Our scenario still exists. We have federations with several zones (and 2 more are in the works):
```
$ ils /
/:
  C- /knmiZone
  C- /replixRZG
  C- /vzRZGE
  C- /vzSARA2
```

We would be very happy if we could enable SSL encryption on our zone and work with the other federations if they have SSL enabled or not.

At the moment we are still running iRODS 4.1.11.
if this is fixed in a 4.2 release we would be very happy.

**Comment by trel** [comment]
I think your scenario is the way it works now - no action is needed to make that possible.

**Comment by cookie33** [comment]
Hm. There was a problem where the files bigger than 32MB would cause a problem with ssl encryption between federations. Is that solved?

**Comment by trel** [comment]
It has not changed.  This is a backwards compatibility and federation issue.

You should be able to stream the large file (aka, not use the parallel transfer) without trouble.

The fix would really be to remove the parallel transfer mechanism in iRODS altogether.  We are investigating that path with our new dstream operator, but it has not landed yet and would require both ends of the connection to have the new code, so wouldn't help with legacy deployments or federation where you are not in control of the other administrative zone.

**Comment by cookie33** [comment]
So if I understand correctly:
 - we have to disable parallel transfer between federations?
 - we can have parallel transfers within the zone?
Than we can set `irods_client_server_policy` to `CS_NEG_DONT_CARE` and enable SSL. And it should work for everybody within the zone and with federated zones. If they use SSL or not with big or small files?

Is this possible to setup?

**Comment by trel** [comment]
@cookie33 I think you should be okay with federation and SSL and large files.

I'm going to close this issue without any action as we cannot get rid of `CS_NEG_DONT_CARE` for the foreseeable future.
