### ISSUE TITLE
rsPhyPathReg should vote on the registration of a replica should a root resource be indicated

### ISSUE THREAD

**Issue by jasoncoposky** [irods/irods#3844]
- [x] master
- [x] 4-2-stable
--------

Currently users may only register replicas directly to a leaf resource, add voting behavior if a root coordinating resource is indicated.

**Comment by trel** [comment]
So registration now works when targeting a root resource or a leaf resource.

What happens when targeting a middle/branch resource?

**Comment by trel** [comment]
confirmed.
