### ISSUE TITLE
clear out old resc_name and resc_hier entries since 4.2 uses resc_id

### ISSUE THREAD

**Issue by trel** [irods/irods#3853]
- [x] master
- [x] 4-2-stable

---
From https://groups.google.com/forum/#!topic/irod-chat/j09x4NJM5bM:

> When I run iquest "SELECT DATA_NAME, COLL_NAME WHERE DATA_RESC_NAME = '${resName}'" I get a list of collections and object (theoretically all on the resource specified via ${resName}).

> If I concatenate each data_name and coll_name, I get an absolute data object path.
If I run ils -L against these paths, I find the objects are not systematically on the resource specified in the iquest command.

> I have had a look in our database, in r_data_main. The dataobjects concerned have data in the resc_hier and resc_name fields of this table and this data is not consistent with the data held in the resc_id field of the same table!

We should clear the resc_name and resc_hier fields on upgrade to 4.2 (and/or every new write to r_data_main).  We hesitated before, as leaving the information there would 'be harmless', but we did not consider this use case of 'old queries' still using resc_name and resc_hier and matching stale information.

**Comment by onmh** [comment]
Quick update on the issue: resc_hier is sometimes NULL and sometimes an empty string ''. It seems, from my tests, that it is NULL for data_repl_num = 0 and a empty string in other cases (replicas 1 through 4 confirmed). The behavior is systematic in our test and production environments.

**Comment by trel** [comment]
Thanks - we'll definitely clear these out.

**Comment by onmh** [comment]
Extra update on the issue: I've set the fields to 'EMPTY_RESC_NAME' for resc_name and NULL for resc_hier via psql update on our production environments and haven't noted any adverse effects.

**Comment by trel** [comment]
ah, very good.
