### ISSUE TITLE
PEP acPreProcForExecCmd, documented in the iRODS 4.0 Microservice Workbook, not implemented in 4.x

### ISSUE THREAD

**Issue by dworkin** [irods/irods#3867]
- [x] master
- [x] 4-2-stable
--------

### iRODS Version, OS and Version
4.2.2

### What did you try to do?
I tried to use the acPreProcForExecCmd PEP.

### Expected behavior
I expected the rule to be executed.

### Observed behavior
The PEP rule was not executed.

### Steps to reproduce
Upon inspecting the source code, I see that iRODS 4.0 forked from iRODS 3.0.  A call to acPreProcForExecCmd was introduced in the irods-legacy repository in commit irods/irods-legacy@9f97dc6ab8710e49cb4da5e3c0789caeb21226d9 on 16 May 2013, and included in release 3.3.

The call to acPreProcForExecCmd was apparently never introduced in the 4.x fork.

**Comment by trel** [comment]
Interesting - thanks.

Will investigate a bit to determine if this slipped through the great merge of 2013... or if we had a reason.

**Comment by trel** [comment]
Additional relevant archaeology:

- May 17, 2013 https://github.com/irods/irods-legacy/commit/b068fd80532bd60c375f0e03f42787dee89b1901
- Sep 19, 2013 https://github.com/irods/irods-legacy/commit/55f417e832d09947853a6eaaabb4277c057ce549
- Sep 19, 2013 https://github.com/irods/irods-legacy/commit/1b67a5fcd471ef7163b2f15d498a079f93128d2c
- Jan 23, 2014 https://github.com/irods/irods-legacy/pull/5
- Jan 23, 2014 https://github.com/irods/irods-legacy/commit/7b92d09d5632dca45b063774c3269ca2b69823f1

**Comment by trel** [comment]
Behold - not an oversight...  just didn't get the 4.0 book or core.re.template updated (apologies).

You can use the dynamic policy enforcement point `pep_api_exec_cmd_pre()` to replicate the earlier behavior in 3.3.

Additionally, all the exec-related api operations now have pre/post PEPs...
https://docs.irods.org/4.2.2/plugins/dynamic_policy_enforcement_points/

```
pep_api_exec_cmd_pre	rsComm_t * rsComm, execCmd_t * execCmdInp, execCmdOut_t execCmdOut
pep_api_exec_cmd_post	rsComm_t * rsComm, execCmd_t * execCmdInp, execCmdOut_t execCmdOut
pep_api_exec_my_rule_pre	rsComm_t * _comm, int * _exec_inp, msParamArray_t _out_arr
pep_api_exec_my_rule_post	rsComm_t * _comm, int * _exec_inp, msParamArray_t _out_arr
pep_api_exec_rule_expression_pre	rsComm_t * _comm, int * _exec_rule
pep_api_exec_rule_expression_post	rsComm_t * _comm, int * _exec_rule
```

**Comment by trel** [comment]
Possible cleanup:

``` diff
diff --git a/packaging/core.re.template b/packaging/core.re.template
index fef6b50..4084071 100644
--- a/packaging/core.re.template
+++ b/packaging/core.re.template
@@ -638,11 +638,8 @@ acBulkPutPostProcPolicy {msiSetBulkPutPostProcPolicy("off"); }
 #acPostProcForDataObjRead(*ReadBuffer) {writeLine("serverLog","TEST:acPostProcForDataObjRead"); }
 # rule below used for testing. dont uncomment this....
 # acPostProcForDataObjRead(*ReadBuffer) {msiCutBufferInHalf(*ReadBuffer); }
-# 55) acPreProcForExecCmd - Rule for pre processing when remotely executing a command
-#     in msiExecCmd_bin
-#     parameter contains the command to be executed, arguments, execution address, hint path.
-#     if a parameter is not provided, then it is the empty string
-# acPreProcForExecCmd(*cmd, *args, *addr, *hint) { }
+# 55) acPreProcForExecCmd (removed) - use dynpep pep_api_exec_cmd_pre() instead
+
 # Rule for pre and post processing when establishing a parallel connection
 # acPreProcForServerPortal(*oprType, *lAddr, *lPort, *pAddr, *pPort, *load) { }
 # acPostProcForServerPortal(*oprType, *lAddr, *lPort, *pAddr, *pPort, *load) { }
diff --git a/plugins/rule_engines/irods_rule_engine_plugin-cpp_default_policy/libirods_rule_engine_plugin-cpp_default_policy.cpp b/plugins/rule_engines/irods_rule_engine_plugin-cpp_default_policy/li
index 8265e87..11a4637 100644
--- a/plugins/rule_engines/irods_rule_engine_plugin-cpp_default_policy/libirods_rule_engine_plugin-cpp_default_policy.cpp
+++ b/plugins/rule_engines/irods_rule_engine_plugin-cpp_default_policy/libirods_rule_engine_plugin-cpp_default_policy.cpp
@@ -686,10 +686,6 @@ irods::error acPostProcForDataObjRead( irods::callback, std::list<boost::any>& )
     return SUCCESS();
 }
 
-irods::error acPreProcForExecCmd( irods::callback, std::list<boost::any>& ) {
-    return SUCCESS();
-}
-
 irods::error acPreProcForServerPortal( irods::callback, std::list<boost::any>& ) {
     return SUCCESS();
 }
@@ -869,7 +865,6 @@ irods::error start(irods::default_re_ctx& _u, const std::string& _instance_name)
     STATIC_PEP(acPostProcForTarFileReg);
     STATIC_PEP(acPostProcForDataObjWrite);
     STATIC_PEP(acPostProcForDataObjRead);
-    STATIC_PEP(acPreProcForExecCmd);
     STATIC_PEP(acPreProcForServerPortal);
     STATIC_PEP(acPostProcForServerPortal);
     STATIC_PEP(acPreProcForWriteSessionVariable);
```

**Comment by trel** [comment]
ah, now that's a bug we can look into...

**Comment by jaking92** [comment]
We need to skip test_acPreProcForExecCmd__3867 when the native rule language rule engine plugin is not being used because it breaks the test suite for the python rule engine plugin (and probably others).

**Comment by trel** [comment]
skipped - closing.
