### ISSUE TITLE
setup script ignores non-standard port value provided in resource setup tests

### ISSUE THREAD

**Issue by kript** [irods/irods#3873]
### iRODS Version, OS and Version

4.1.10
Red Hat 7.4

### What did you try to do?

run `/var/lib/irods/packaging/setup_irods.sh` and provide a non-standard iRODS port (because I want to run HAProxy on the same server and #3872 means I can't have it running just on one IP/interface).

### Expected behavior

iRODS setup script runs successfully

### Observed behavior

```
    Testing resource...

Install problem:
    Cannot put test file into iRODS:
        ERROR: putUtil: put error for /seq/home/irods/irods_put_irods-seq-ies1.internal.sanger.ac.uk.tmp, status = -305111 status = -305111 USER_SOCK_CONNECT_ERR, Connection refused

```
The correct value is set in `~/.irods/irods_environment.json` and `/etc/irods/server_config.json` 
However, as the resource test fails,  the setup script does not write out the authentication file.

### Steps to reproduce

run install script and provide a non-standard port (I used 1246)

### Steps to Workaround

Become the service user for iRODS and run `iinit`.
Stop and restart iRODS

**Comment by kript** [comment]
That's my understanding from the log, yes. Its a perfectly functioning server once you create the authentication file.
Will the setup log contain more info? If so, I can grab it later - I was going on the output to the console.

**Comment by trel** [comment]
This is working as expected in 4.2.5 (current released version).

Closing.
