### ISSUE TITLE
sending 'PING' to 1247 causes -4000 error in log

### ISSUE THREAD

**Issue by kript** [irods/irods#3880]
### iRODS Version, OS and Version

iRODS 4.1.10
Red Hat 7.4

### What did you try to do?

test iRODS 'aliveness' by sending 'PING' to port 1247 as mentioned in [Configuring iRODS for High Availability](https://irods.org/2015/07/configuring-irods-for-high-availability/)

### Expected behavior

iRODS will respond with text beginning with "\<MsgHeader_PI>, server log is silent.

### Observed behavior

iRODS responds with text beginning with "\<MsgHeader_PI>
 
log contains
`ERROR: readWorkerTask - readStartupPack failed. -4000`

### Steps to reproduce

Send PING to default port, watch log.

**Comment by tedgin** [comment]
As a workaround the `tcp-check send` and `tcp-check expect` lines in the HAProxy configuration can be replaced with the following.

```
   tcp-check       send-binary 0000006e
    tcp-check       send <MsgHeader_PI><type>RODS_CONNECT</type><msgLen>216</msgLen><errorLen></errorLen><bsLen></bsLen></MsgHeader_PI><StartupPack_PI><proxyUser>PING</proxyUser><proxyRcatZone></proxyRcatZone><clientUser></clientUser><clientRcatZone></clientRcatZone><relVersion></relVersion><apiVersion></apiVersion><option></option></StartupPack_PI>
    tcp-check       expect string <MsgHeader_PI>\n<type>RODS_VERSION</type>
    tcp-check       send-binary 0000006f
    tcp-check       send <MsgHeader_PI><type>RODS_DISCONNECT</type><msgLen>0</msgLen><errorLen></errorLen><bsLen></bsLen></MsgHeader_PI>
```

This mimics a proper connect and disconnect.

**Comment by trel** [comment]
There is now a better way to monitor the iRODS server (created after those instructions were written).

Please use the 'HEARTBEAT' feature, rather than 'PING'.

https://docs.irods.org/4.2.8/system_overview/tips_and_tricks/#monitoring-status-of-irods-servers

**Comment by trel** [comment]
For anyone finding this later...

The new `HEARTBEAT` syntax for HAProxy would be of the form:

```
backend server
        balance roundrobin
        option tcp-check
        tcp-check connect
        tcp-check send-binary 00000033
        tcp-check send <MsgHeader_PI><type>HEARTBEAT</type></MsgHeader_PI>
        tcp-check expect string HEARTBEAT
        server server1.example.org IP1:1247  check
        server server2.example.org IP2:1247  check
```
