### ISSUE TITLE
replace GenQuery ad-hoc parsing code with flex/bison parser

### ISSUE THREAD

**Issue by trel** [irods/irods#3902]
## Feature

This would replace the existing parsing code with a 'real' parser.  An example implementation can be found at https://github.com/kellerb/genquery-ast-example.

Replacing the parser would close issues:
- #3886 
- #3064
- https://github.com/irods/irods/issues/4697
- #4983 
- https://github.com/irods/irods/issues/5734
- https://github.com/irods/irods/issues/5992

**Comment by trel** [comment]
Should define the parser via ANTLR...
 - https://tomassetti.me/getting-started-antlr-cpp/

**Comment by trel** [comment]
Probably sticking with flex/bison...

**Comment by korydraughn** [comment]
Latest reference implementation for GenQuery replacement can be found here:
- https://github.com/irods/irods_api_plugin_genquery2

**Comment by korydraughn** [comment]
#7570 must be resolved before taking on this issue.

**Comment by korydraughn** [comment]
The GenQuery2 parser was merged into upstream (#7570) but is too new to start replacing code within the server.

GenQuery1 will continue to exist for the duration of the 4.x series _(perhaps 5.x too for backwards compatibility reasons)_. Its usage will be replaced over time as confidence in the new parser grows.

**Comment by korydraughn** [comment]
After some discussion, we've decided to ship #7819 post 4.3.3. We'll also introduce an environment variable to control whether the new parser is used. The environment variable would give admins a way to opt into the new parser (default would be off).

**Comment by korydraughn** [comment]
I'm now starting to wonder if the opt-in solution is worse than switching to the new parser.

My current thoughts ...
- Environment variable can lead to misalignment between client and server
    - Server has environment variable set, client does not
- Do clients have to care about the opt-in flag?
    - Yes, if they have paths with embedded single quotes
- What if the client/server libs always hex-escaped single quotes? Are there any downsides to this?
    - If the client never receives a query with embedded single quotes, things work
        - The paths will not be altered
    - If the client sends a query with embedded single quotes and the server isn't using the new parser, an error will occur
        - The paths must be escaped for things to work
    - If the client sends a query with embedded single quotes and the server is using the new parser, things work
- What does this affect?
    - `iquest`
    - `irods::query`
    - `irods::query_builder`
    - clients using `fillGenQueryInpFromStrCond`
- Isn't this an issue for genquery2 as well?
    - We have to migrate to it eventually
    - And it will require the embedded single quotes to be escaped 
- Possible solutions
    - Use environment variable _(has issues)_
    - Make it a compile-time thing - ship two versions of 4.3.4 _(yuck)_
    - Change the server to always use the new parser _(seems like the right approach, but could be bad if there's a bug)_
        - Does federation block this? 
            - It may not due to the fact that GenQuery1 requires C structs
            - The parsers do not rely on network traffic

**Comment by korydraughn** [comment]
After some discussion, we've decided to do the following:
- Replace the GenQuery1 parser in iRODS 5
- iRODS 4 will remain as is
- `fillGenQueryInpFromStrCond` will be removed
- Deprecate `fillGenQueryInpFromStrCond` in iRODS 4
- Bump all GenQuery1 parser issues to the 5.0.0 milestone

**Comment by korydraughn** [comment]
The work for this issue is now located in PR #8089.
