### ISSUE TITLE
Make child selection consistent in operation replication

### ISSUE THREAD

**Issue by jaking92** [irods/irods#3909]
- [x] master
- [x] 4-2-stable
- [x] 4-1-stable
----

## An example use case
Consider an `iput` of a file to a resource tree like the following:

```
> ilsresc
root:passthru
└── replicate:replication
    ├── pt-seq-green:passthru
    │   └── seq-green:random
    │       ├── pt-green0:passthru
    │       │   └── green0:random
    │       │       ├── green0ufs0
    │       │       └── green0ufs1
    │       └── pt-green1:passthru
    │           └── green1:random
    │               ├── green1ufs0
    │               └── green1ufs1
    └── pt-seq-red:passthru
        └── seq-red:random
            ├── pt-red0:passthru
            │   └── red0:random
            │       ├── red0ufs0
            │       └── red0ufs1
            └── pt-red1:passthru
                └── red1:random
                    ├── red1ufs0
                    └── red1ufs1
> iput -R root test.txt b
> ils -l b
  rods              0 root;replicate;pt-seq-red;seq-red;pt-red0;red0;red0ufs0            5 2018-04-27.12:08 & b
  rods              1 root;replicate;pt-seq-green;seq-green;pt-green1;green1;green1ufs1            5 2018-04-27.12:08 & b
```

## Under the hood
`replRedirect` is called on the operation, which calls `repl_redirect_impl` for each "redirection" below.

First, hierarchies are chosen via a series of votes (the first "voting pool") for a CREATE/WRITE operation, regardless of what the operation actually is (e.g. could be a READ). This is done to get around a problem found in #2789.

*From the example use case:*
Hier chosen for first/initial write/create (the "selected hierarchy"): 
- root;replicate;pt-seq-red;seq-red;pt-red0;red0;red0ufs1
(**NOTE:** This resource does not have a replica)

`write_child_list` (list of children selected to accept replicas for write/create, the first "voting pool"):
- root;replicate;pt-seq-green;seq-green;pt-green1;green1;green1ufs1
(**NOTE:** This resource has replica 1)

Now we start a **second redirection** for the actual operation. In the case of `iput`, it's also a CREATE/WRITE.

*From the example use case:*
Hier chosen for first/initial write/create (the "selected hierarchy"):
- root;replicate;pt-seq-red;seq-red;pt-red0;red0;red0ufs0
(**NOTE:** This resource has replica 0. It is also different from the selected hierarchy from the first redirection above due to the random resource.)

`child_list` (list of children selected to redirect operation to, the second "voting pool"):
- root;replicate;pt-seq-green;seq-green;pt-green1;green1;green1ufs0
(**NOTE:** This resource does not have a replica)

## Problem
When the CREATE/WRITE operation is executed, the `write_child_list` is used for replication, but the "selected hierarchy" (the resource which accepts the initial create/write) is from the **second redirection**. This is inconsistent and has been known to cause confusion. This could also theoretically lead to a situation where the selected hierarchy could also appear in the `write_child_list`.

## Proposal
In order to make things more consistent, we need to make sure to use the selected hierarchy in the **first redirection** when replicating a CREATE/WRITE operation. We could consider consolidating `replRedirect` into a single redirection/vote pool (i.e. one `repl_redirect_impl` call) and use a different property in the context property map for CREATE/WRITE to simplify and to avoid issues with non-CREATE/WRITE operations. Also, some renaming and detailed comments would be in order here.

**Comment by jaking92** [comment]
The test added for this change needs to be skipped when the native rule engine plugin is not in use because the native rule language cannot be interpreted by the alternate rule engine plugin if it is the only one in use (e.g. python).

**Comment by trel** [comment]
skipped on 4-2-stable and master (no rule engine plugins in 4.1.x)
