### ISSUE TITLE
Occasional hangs in test_control_plane

### ISSUE THREAD

**Issue by jaking92** [irods/irods#3911]
### iRODS Version, OS and Version
master/4-2-stable, ub14-psql, cen7-psql, cen7-mysql

### Observed behavior (including steps to reproduce, if applicable)
Sometimes, test suite will seemingly run forever or until aborted. The hang appears to occur in `test_control_plane.TestControlPlane` which may indicate a deadlock somewhere in the control plane. Please investigate.

**Comment by jaking92** [comment]
|branch|CI run|test|
|------------|--------|----|
|master     |[test-cen7-psql](http://172.25.14.125:8080/job/test-cen7-psql/1981/)|`test_shutdown_local_server`
|master     |[test-ub14-psql](http://172.25.14.125:8080/job/test-ub14-psql/2147/)|`test_shutdown_local_server`
|4-2-stable|[test-cen7-mysql](http://172.25.14.125:8080/job/test-cen7-mysql/1986/)|`test_hosts_separator`
|4-2-stable|[test-cen7-mysql](http://172.25.14.125:8080/job/test-cen7-mysql/1988/)|`test_status`

**Comment by trel** [comment]
Probably related to activity on https://github.com/irods/irods/issues/3878.

We can close if we see no new hangs for a while after May 8.

**Comment by trel** [comment]
This appears fixed - closing for 4.2.3.
