### ISSUE TITLE
Throw error when root directory (/) is used as a vault path

### ISSUE THREAD

**Issue by jaking92** [irods/irods#3928]
- [x] master
- [x] 4-2-stable
- [x] 4-1-stable
---
## Feature

Using the root directory as a vault path for a resource is a very bad idea. We should issue a warning to the user when this is done (similar to the warning issued when using `localhost` as a hostname for a resource).

There should also be an error when the root directory is used to update/calculate free space on a resource (see discussion in #3841).

**Comment by jaking92** [comment]
We need to skip test_unix_filesystem_free_space_on_root__3928 when the native rule language rule engine plugin is not being used because it breaks the test suite for the python rule engine plugin (and probably others).

**Comment by trel** [comment]
skipped on 4-2-stable and master (no rule engine plugins in 4.1.x) - closing.
