### ISSUE TITLE
containerize irods

### ISSUE THREAD

**Issue by xu-hao** [irods/irods#3959]
## Feature
Inspired by kubernetes deployment. We want to restart container. Split current post install setup script into:
- Binary or irodsctl script take config files: could include database information.
- Script to setup database only.
- Script to setup container image.

**Comment by xu-hao** [comment]
https://github.com/mjstealey/irods-provider-cockroachdb

**Comment by xu-hao** [comment]
Currently, iRODS requires username and groupname for uid and gid. This prevents registering files in mounted network drives in containers unless a user and group is created in the container to match the uid and gid. This doesn't work if the gid is dynamically allocated.

**Comment by colin-nolan** [comment]
I support this feature request - we have also struggled with setting up iRODS in a container before: https://github.com/wtsi-hgi/docker-icat.

I am not familiar with your point about `irodsctl` but I believe it may be related to the pain of automating the use of `/var/lib/irods/scripts/setup_irods.py`(?). At a minimum, this script should take a config file and, ideally, it should be able to take its configuration entirely from the environment (https://12factor.net/config).

I completely agree with your other points.

**Comment by xu-hao** [comment]
I agree. The script will have the following command line:

```irodsServer [configdir]```

`configdir` will override the normal `/etc/irods`

**Comment by trel** [comment]
No action here - our build and testing environments are now containerized.

**Comment by trel** [comment]
Please see
https://github.com/irods/irods_development_environment
and
https://github.com/irods/irods_testing_environment
for examples/code/usage.
