### ISSUE TITLE
icp fails when the name of the source collection  is a prefix of the target one

### ISSUE THREAD

**Issue by ccacciari** [irods/irods#3962]
- [x] master
- [x] 4-2-stable
-------

## Bug Report
The copy via icp of one collection to another one whose name "extends" the source's name with few character, fails.

### iRODS Version, OS and Version
IRODS v4.2.3, OS: centos 7.5

### What did you try to do?
Copy a collection to another collection, both within the home collection of an irods user.

### Expected behavior
Success without any response:
$ icp -r collection_Z collection_Z1
$

### Observed behavior (including steps to reproduce, if applicable)
$ icp -r collection_Z collection_Z1
remote addresses: 127.0.0.1 ERROR: cpCollUtil: cannot copy collection /cinecaDMPZone2/home/claudio/collection_Z into itself
remote addresses: 127.0.0.1 ERROR: cpUtil: cp error for /cinecaDMPZone2/home/claudio/collection_Z1, status = -339000 status = -339000 SAME_SRC_DEST_PATHS_ERR

**Comment by andrew-irods** [comment]
The issue:  On the client side, when the icp command is run, for the command "icp -r collection_Z collection_Z1", the following is what causes the bug:

~~~
strstr("collection_Z1", "collection_Z")
~~~

This code (cpUtil.cpp - cpCollUtil()), shows the string "collection_Z" to be included within "collection_Z1", which is not the intent.  In addition, the end of the target string ("collection_Z1") should be examined to see if the it ends with a null character ('\0' - "Collection_Z") or a separator ("/" - i.e. "Collection_Z/") which it does not.

The code should be firmed up to include the check for the end of the matched target string, and a test for this case added to irods.

(Note: at this point in the code, the source and target paths have been normalized - are absolute logical paths, so they look like - "/tempZone/home/irods/collection_Z", etc -- with all multiple and trailing separators removed).

**Comment by andrew-irods** [comment]
CI test 1052 passed successfully.  Includes the fix, but not the test case for it yet.

**Comment by andrew-irods** [comment]
Running CI test 1054 right now (includes test case).

**Comment by trel** [comment]
4-2-stable merged, please cherry-pick to master.

**Comment by andrew-irods** [comment]
CI Test 1057 running (master)

**Comment by trel** [comment]
merged - checkbox and close!
