### ISSUE TITLE
NOT IN syntax support in GenQuery

### ISSUE THREAD

**Issue by michael-conway** [irods/irods#3967]
## Feature

- Please describe the feature you are requesting and your use case.

NOT IN is not valid GenQuery syntax 

### iRODS Version, OS and Version

Testing on 4.2.2

### What did you try to do?

iquest "SELECT COLL_NAME, DATA_NAME WHERE COLL_NAME = '/zone1/home/test1/jargon-scratch/GenQueryFunctionalTests/testQueryNotIn' AND DATA_NAME not in 'filea' 'fileb' 'filed' "

results in 

: iquest Error: queryAndShowStrCond failed status = -806000 CAT_SQL_ERR

While same statement as just 'in' works fine

### Expected behavior

Would do the inverse of the 'in'.

### Observed behavior (including steps to reproduce, if applicable)

Run the above query, can use unit tests developed in https://github.com/DICE-UNC/jargon/issues/304 as a reference

**Comment by d-w-moore** [comment]
Mike,
  Looking at the lack of a 'NOT IN' operator in GenQuery ... it may not be an easy thing to add and could take time.  How much are you presently able to work around the issue ? -Dan

**Comment by michael-conway** [comment]
Yes, there is a work-around. Thanks for digging into it!

**Comment by trel** [comment]
Don't think we've ever supported NOT IN.

I believe this is remedied by GenQuery2.

**Comment by korydraughn** [comment]
Yes, NOT IN is supported.

**Comment by trel** [comment]
Excellent.

Closing and pointing to https://github.com/irods/irods_api_plugin_genquery2
