### ISSUE TITLE
setup_irods.py fails due to differences C and python Obfuscation

### ISSUE THREAD

**Issue by wanneut** [irods/irods#3972]
- [x] master
- [x] 4-2-stable
-----

### iRODS Version, OS and Version
iRODS Version 4.2.3
CentOS Linux release 7.5.1804

### What did you try to do?
setup a new iRODS provider

### Expected behavior
Server starts 

### Observed behavior (including steps to reproduce, if applicable)
Putting the test file into iRODS fails:
```
IrodsError: Call to open process with ['iput', '/tmp/tmpMX5HzOdemoResc'] returned an error:
  Options passed to Popen:
  
  Return code: 7
  Standard output:
    Enter your current iRODS password:
  Error output:
    [-] /tmp/tmpIhxPZi/plugins/auth/native/libnative.cpp:342:irods::error native_auth_client_response(irods::plugin_context &, rcComm_t *) :  status [CAT_INVALID_AUTHENTICATION]  errno [] -- message [Call to rcAuthResponseFailed.]
    
     failed with error -826000 CAT_INVALID_AUTHENTICATION
```

### Problem
Problem seems to me, that the C++ implementation used in libnative.cpp and the python implementation in password_obfuscation.py calculate different obfuscated passwords for some passwords.
An example for such an password is:
vulgarizationRockefellerromanticallycartoonbijective

Btw: Is there any real reason, for doing that?
UID and timestamp are also transmitted in NFS3. So it provides no additional security for that scenario. If you still want to keep that property, you can just use a well known encryption function from a library.
This code makes the Program less readable; adds a few lines of input handling from unauthenticated users (which can have bugs) and prevents users from using passwords in their native language (where they have a much lager Vocabulary.)
I see no reason for a modified crypto-function of the millennium before last.

**Comment by tempoz** [comment]
That password is longer than the acceptable maximum size for iRODS, I'll change the python script to mimic the size limit and output an error.

To your aside: No, there is no reason for doing it other than compatibility. I think it's generous to even refer to it as crypto, it's little more than a decoder ring.

**Comment by trel** [comment]
@tempoz appears this just needs to be cherry-picked to master(s) and closed?
