### ISSUE TITLE
Investigate boost-like irods::filesystem

### ISSUE THREAD

**Issue by andrew-irods** [irods/irods#3973]
This issue holds a collection design ideas, references to existing code, and other items that describe or are factors in the design of system objects that deal with collection paths.

The intent is for the design to follow the ideas found in boost::filesystem.

**Separator**
* The file get_virtual_path.cpp/.hpp defines and gets the std::string separator ("/") with irods::get_virtual_path_separator().
* The code in general has hard-coded "/" all over the place.

**Validation**
In dataObjOpr.cpp, validate_logical_path() - determines if a logical path is created at the root level.

=====================================================
Additional items will be added before this line over time.

**Comment by korydraughn** [comment]
This can likely be closed now that irods::filesystem exists.

**Comment by trel** [comment]
Agreed.  Closing.

**Comment by trel** [comment]
Was included in 4.2.6 via https://github.com/irods/irods/issues/4267
