### ISSUE TITLE
iRODS and Ubuntu 18, a match made in heaven

### ISSUE THREAD

**Issue by kellerb** [irods/irods#3977]
## Feature

- Please describe the feature you are requesting and your use case.

The feature I am requesting is Ubuntu 18-native iRODS packages.
My use case is the installation of iRODS packages built on and by an Ubuntu 18 system.

Asking for a friend

**Comment by theazgra** [comment]
Can I ask what is the reason that irods is not avaible for newer versions of Ubuntu than 16? Not mocking, just really curios.

**Comment by trel** [comment]
No worries.

We just haven't gotten it into our CI system, yet.   We're working to move our continuous integration system to Docker and Ubuntu18 will be there ASAP.

iRODS itself works fine with Ub18, and passes all the tests at the bench.

**Comment by mam288** [comment]
Are Ubuntu 18 iRODS packages available yet?

**Comment by trel** [comment]
Not yet - but I believe you can use the packages from Ubuntu16 until we get Ubuntu18 packages out.

You can do that by pointing your apt listing at 'xenial', rather than 'bionic':
```
# /etc/apt/sources.list.d/renci-irods.list
deb [arch=amd64] https://packages.irods.org/apt/ xenial main
```

I've just installed them in a docker container and it appears to work as expected.

```
irods@140792983a92:~$ cat VERSION.json
{
    "catalog_schema_version": 6, 
    "commit_id": "db085559893dabcb8e3acd30dbd7c4b65bc110dc", 
    "configuration_schema_version": 3, 
    "installation_time": "2019-02-27T08:33:02.096451", 
    "irods_version": "4.2.5"
}
 
irods@140792983a92:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

irods@140792983a92:~$ ils -L
/tempZone/home/rods:
  rods              0 demoResc          224 2019-02-27.08:37 & testfile
        generic    /var/lib/irods/Vault/home/rods/testfile

```

**Comment by mam288** [comment]
Thank you!!

**Comment by jdkruzr** [comment]
Just wanted to second this -- would be really good if we could get this updated. I fear Unknown Consequences™ if I leave this set to Xenial.

**Comment by trel** [comment]
we're working on it - but it will be delivered by our new CI infrastructure.   once we get it into production, we can release existing versions for new operating systems.

**Comment by kript** [comment]
Another :+1 for us, since we will likely be deploying Ubuntu 18.04 from now on Because Reasons.

**Comment by trel** [comment]
We're so close...

**Comment by jdkruzr** [comment]
Will you be able to skip straight to 20.04?! 🤞🏻

**Comment by trel** [comment]
Just tried it tonight, and we've got some python/python2/python3 things to work out - and that clang didn't build out of the box.

But they should be pretty straightforward.

Adding an OS now won't be as complicated.  We've also tried Centos8 recently, same story, things have moved.
