### ISSUE TITLE
irods chksum differs from commandline on Linux

### ISSUE THREAD

**Issue by joergsteinkamp** [irods/irods#3985]
### iRODS Version, OS and Version
iRODS 4.2.3 (compiled with clang-5.0 instead of 3.8)
Linux 4.16.0-0.bpo.2-amd64 #1 SMP Debian 4.16.12-1~bpo9+1 (2018-06-03) x86_64 GNU/Linux

### What did you try to do?
Comparing checksum produced with ichksum and proposed command line (https://docs.irods.org/4.2.2/system_overview/tips_and_tricks/#confirming-checksums)

### Expected behavior
Should be identical

### Observed behavior
The checksum differed in the last two characters, indicating an differing output from 'xxd'. I had to remove the trailing control character with tr to achieve identical results:
```
sha256sum foo | xxd -r -p | tr -d '\272' | base64
```
Drawback: I tested it with two files only

Kind regards
Jörg

**Comment by trel** [comment]
Interesting - I have just tested again manually (with packaged release) and it still works as expected.

Do you think this is a difference in a newer `xxd`?
Or because of the newer `clang` (seems unlikely)?

**Comment by trel** [comment]
Some quick sleuthing suggests a difference in shell could be the cause?

I have been running the example code in vanilla bash.

**Comment by joergsteinkamp** [comment]
It must be from my shell (or xxd?), which are from the standard Debian packages. The above happens with the environment variable LANG=de_DE.UTF-8. If I unset LANG or set it to "en_US.UTF-8" I have to remove a trailing '\332' to get identical strings. I don't understand it, it's neither a line break, carriage return nor a null value. I'll test it on a Mac the next few days and let you know what happened.

**Comment by trel** [comment]
Curious.   Yes, please follow up.  Thanks!

**Comment by joergsteinkamp** [comment]
I've got it: It's my check256sum! It also prints the filename behind the checksum. If I modify my command to 
```
sha256sum foo | sed -e 's/ .*//' | xxd -r -p | base64
```
it's the correct string. Sadly there is no command line option to omit the filename behind the checksum for check256sum. Maybe you should update the documentation and add half a sentence.
