### ISSUE TITLE
Documentation of keep-alive behaviour over long running connections

### ISSUE THREAD

**Issue by kript** [irods/irods#3986]
- [x] main (irods_docs)
---
### iRODS Version, OS and Version

iRODs 4.1.10
Red Hat 7.4

### What did you try to do?

upload a large file (> 4G) through an HA system using HAProxy to manage connections.

### Expected behavior

`iput` completes successfully

### Observed behavior (including steps to reproduce, if applicable)

Without significantly increasing the timeouts on our HA proxy  the upload fails (consistently on very large files e.g. >=50G) while a large `iput` was being done (>4G), giving a `SYS_HEADER_READ_LEN_ERR`, which we believe was due to the control session timing out.

We started with timeouts of 60s for client and server, and ended up with;

```
defaults
    mode                    tcp
    log                     global
    option                  dontlognull
    option dontlog-normal
    option tcplog
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         5s
    timeout client          3660s
    timeout server          3660s
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn 19500
```

On its own, using `-T` did not fix the issue.

With a combination of these changes and using `-T` we could avoid the READ_LEN error above and the iput completed successfully, otherwise this was not always the case.

However, this lead me to the realisation that its not clear which part of the connection the `-T` applies to for the `iput`, out of the following options;

- The control connection to federation mater from the iput (actually not used here but I'm interested to know)
- the control connection from client to IES
- the control connection from IES to initial iRES
- the control connection from initial iRES to replica iRES

Its not clear which part of the connection that `-T` applies to as the man page says only `-T  renew socket connection after 10 minutes`, and whether is applies at application or socket level?

That, in turn, made me wonder what keep-alive options were available for the API (with special regard for [baton](http://wtsi-npg.github.io/baton/), especially as `baton-do` can hold connections open for several hours (@keithj can provide more details) .

As well as answering the above, can we get documentation of all of the above added to the docs.irods.org site please for 4.1.X and 4.2.X?

Thanks,

John

**Comment by keithj** [comment]
With respect to `baton`, it copies the pattern I observed in using the `icommands` without the `-T` option i.e. after a connection has been open for a while we see a message about the connection being restored, periodically. `baton` unconditionally sets `NO_RECONN` as if it were always run without `-T`.

**Comment by michael-conway** [comment]
Yes, I long struggled with this one too, since the parallel transfer is
being carried out on these ephemeral ports with no further communication on
1247 until the transfer has completed. I had wondered if there was a way to
send some sort of ping on 1247 during the transfer, otherwise the parallel
threads are moving data only to send opr complete on 1247 and find that the
whole thing falls over.

**Comment by kript** [comment]
gentle ping to get this assigned (I know you're all busy!)

**Comment by kript** [comment]
I believe that #3824 is also related here

**Comment by kript** [comment]
From a recent UGM talk, it was suggested that the irodsAgent doesn't use TCP keepalive's. 
This seems to match the above behaviour, but is contraindicated by https://github.com/irods/irods/commit/5721f237d47a194ce8d39fd0851757dcda3eb2d0#diff-540dddbc43910e92731b260cb598ba67 and https://github.com/irods/irods/commit/5721f237d47a194ce8d39fd0851757dcda3eb2d0#diff-540dddbc43910e92731b260cb598ba67

and I see established connections on our IES. I also see them from icommands, but I don't see it being invoked in the source (but I may be exposing my misunderstanding of how this works).

**Comment by alanking** [comment]
Between irods/irods_docs#209 and #5218, I think this is covered. Please open a new issue if more / clarified documentation is needed.
