### ISSUE TITLE
irsync/icp/iput -r with multiple source directories on the command line, have problems

### ISSUE THREAD

**Issue by andrew-irods** [irods/irods#3997]
- [x] master
- [x] 4-2-stable
-----

## Bug Report

(The description has been expanded to include iput and icp with the -r flag.  Please extrapolate the description below to include those icommands)

When running **irsync -r** with multiple source directories, and a single target collection, there are problems that are either related to unclear documentation, or to unfinished functionality.  Some of the behavior is simply buggy.

### iRODS Version, OS and Version
4-2-stable/Ubuntu 16.04 - relevant to other current irods versions, and all platforms.

### Description

The best way to highlight the problems is to show them:

**Setup:**

Two physical directories with two files each:

~~~
$ ls -l
total 8
drwxrwxr-x 2 akelly akelly 4096 Jun 27 13:09 dir1
drwxrwxr-x 2 akelly akelly 4096 Jun 27 13:09 dir2
$ ls -l *
dir1:
total 0
-rw-rw-r-- 1 akelly akelly 2 Jun 27 13:09 file1
-rw-rw-r-- 1 akelly akelly 2 Jun 27 13:09 file2

dir2:
total 8
-rw-rw-r-- 1 akelly akelly 2 Jun 27 13:09 file1
-rw-rw-r-- 1 akelly akelly 2 Jun 27 13:09 file2
$ 
$ ils -lr
/tempZone/home/rods:
~~~ 

**First Step**

With no collections in the catalog:

~~~
$ irsync -r dir1 dir2 i:coll1
remote addresses: 127.0.0.1 ERROR: resolveRodsTarget: target /tempZone/home/rods/coll1 does not exist status = -310000 USER_FILE_DOES_NOT_EXIST
remote addresses: 127.0.0.1 ERROR: rsyncUtil: resolveRodsTarget status = -310000 USER_FILE_DOES_NOT_EXIST
$ 
~~~

irsync is complaining that the target collection does not exist.  Fair enough, we did not create one. However:

~~~
$ ils -lr
/tempZone/home/rods:
  C- /tempZone/home/rods/coll1
/tempZone/home/rods/coll1:
$ 
~~~
The error emitted is the first problematic behavior.  And, It seems that inspite of the error, the target collection **was** created, and is empty.** (this is the second problematic behavior).

**Next Step**

Since the target collection now exitsts, let's try the same irsync command again:

~~~
$ irsync -r dir1 dir2 i:coll1
$
$ ils -lr
/tempZone/home/rods:
  C- /tempZone/home/rods/coll1
/tempZone/home/rods/coll1:
  C- /tempZone/home/rods/coll1/dir1
/tempZone/home/rods/coll1/dir1:
  rods              0 demoResc            2 2018-06-27.13:20 & file1
  rods              0 demoResc            2 2018-06-27.13:20 & file2
  C- /tempZone/home/rods/coll1/dir2
/tempZone/home/rods/coll1/dir2:
  rods              0 demoResc            2 2018-06-27.13:20 & file1
  rods              0 demoResc            2 2018-06-27.13:20 & file2
~~~ 
The two physical directories were copied into irods, **under** coll1.

### Expected behavior

Modified description:
The behavior described above (dir1 and dir2 being created under coll1) is the correct behavior.  That should be documented better.  The only bug here is in the error message being displayed, even as the target collection is created, as described above.

The inappropriate error message only shows up when there are more than one source directory on the command line.  When there is only one source directory, and a single non-existent target collection, the collection is created silently, and the contents of the source directory is copied directly under the new target collection. 

See issue #2010 for a more complete description of what should happen under various scenarios.

See also comments below on how things should work.
----

(Original Paragraph):
Not sure.  The precise desired behavior should be better described in the documentation, and the functionality of the code should be changed if need be, to match the docs.  There should be no error emitted if this use case is legal.

**Comment by andrew-irods** [comment]
**When target_collection does not exist:**
~~~
iput -r dir1 dir2 ...  target_collection
irsync -r dir1  dir2 ...  i:target_collection
icp -r some_collection1 some_collection2 ...  target_collection
~~~
The icommand should create the target_collection silently, and recursively copy the full source directories (and collections for icp) into it.  In other words, the collections dir1, dir2, dir3, etc are created under target_collection, including their contents recursively.  The same is true for icp -- the collections some_collection1, some_collection2, etc are created under target_collection recursively.

**When target_collection does exist:**
If target_collection already exists, the same actions take place as described above, with the exception of the creation of target_collection, which already exists.

**Comment by andrew-irods** [comment]
CI Build 1198 passed - initial implementation.  Does not include all tests for this issue.

**Comment by andrew-irods** [comment]
CI build 1230 (master) - running

**Comment by andrew-irods** [comment]
CI build 1239 passed (master branch).

**Comment by trel** [comment]
checkbox and close!
