### ISSUE TITLE
remote microservice broken in iRODS 4.2.3

### ISSUE THREAD

**Issue by cookie33** [irods/irods#3998]
- [x] master
- [x] 4-2-stable

---
## Bug Report

When doing a `remote` microservice something is not properly handled/terminated. Because the next simple command fails and gives some errors in the iRODS logfile.
 
### iRODS Version, OS and Version

iRODS 4.2.3, Centos 7.5

### What did you try to do?

Run a test script to do remote execution. The test script `test_remote_6 .r` is
```
test {
   remote("sara-irods4.irods.surfsara.nl","<ZONE>tempZone</ZONE>") { writeLine("serverLog", " -- Remote Execution in Local Zone");  }
   writeLine("stdout", "Success!");
}
OUTPUT ruleExecOut
```

### Expected behavior

screen shows:
```
$ irule -F test_remote_6.r 
Success!
$
```

irods logfile contains:
```
Jun 28 12:11:11 pid:23182 NOTICE: writeLine: inString =  -- Remote Execution in Local Zone
```

### Observed behavior (including steps to reproduce, if applicable)

test run:
```
$ irule -F test_remote_6.r 

$
```
irods logfile contains:
```
Jun 28 12:30:29 pid:25034 NOTICE: writeLine: inString =  -- Remote Execution in Local Zone
Jun 28 12:30:29 pid:25034 remote addresses: 127.0.0.1, 145.100.4.16 ERROR: addMsParam: NULL msParamArray or label input
Jun 28 12:30:29 pid:25034 remote addresses: 127.0.0.1, 145.100.4.16 ERROR: addMsParam: NULL msParamArray or label input
```

We are missing the out of "Succes!" on the terminal where the rule was run.
We are also surprised by the extra ERROR data in the irods logfile

**Comment by cookie33** [comment]
See also #3722. There the `remote` microservice was fixed.

**Comment by xu-hao** [comment]
This bug was introduced in a recent refactoring to allow python rule engine to access `ruleExecOut` from `msParamArray` in `rei`. `remoteExec` needs to be updated to reflect that: 

https://github.com/irods/irods/blob/4-2-stable/plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/functions.cpp#L1920

**Comment by trel** [comment]
We have a candidate fix - it's under review:
  https://github.com/irods/irods/pull/4011

**Comment by beheerderdag** [comment]
Hi @trel, 
Is this slotted for 4.2.5? 
At the moment this bug is a blocker for us. Our b2safe instances still running 4.1.11 and we would like to move to a 4.2.x version soon.

**Comment by trel** [comment]
Yes, this will be in 4.2.5.   Awaiting confirmation on #4011 and we'll get it merged.

**Comment by alanking** [comment]
Reopening because the following results in a stacktrace as of this change:
```
main() {
  delay("<PLUSET>1s</PLUSET>") {
      remote("remote.example.org", "tempZone") {
        writeLine("serverLog","On remote server");
      }
  }
}
OUTPUT ruleExecOut
```
Need test for remote in delay and delay in remote. Applies to 4-2-stable and master.
