### ISSUE TITLE
clang: turn on -Wdeprecated-declarations so that deprecation warnings are enabled

### ISSUE THREAD

**Issue by andrew-irods** [irods/irods#4002]
## Feature

In order for deprecation messages to be embedded in the source code, and displayed as an allowed warning in the build output, the **-Wdeprecated-declarations** option for clang has to be used in the cmake compile rules for clang++.

Use in a program would look like this:

~~~
[[deprecated("isPathSymlink() will be deprecated in the future - to be replaced by an improved mechanism.")]]
int isPathSymlink( rodsArguments_t* rodsArgs, const char* myPath )
{
. . . 
~~~

## References:

https://en.cppreference.com/w/cpp/language/attributes 

https://josephmansfield.uk/articles/marking-deprecated-c++14.html

**Comment by trel** [comment]
We already compile with `-Wall` and `-Werror`...
https://github.com/irods/irods/blob/4-2-stable/CMakeLists.txt#L61

So as long as we don't call the deprecated function ourselves, we should still be able to compile?

And other code that uses our `irods-dev` and `irods-runtime` packages should see the warnings if they are using this function...

**Comment by andrew-irods** [comment]
Agreed - maybe not such a great idea after all.

**Comment by trel** [comment]
Closing - no action necessary.
