### ISSUE TITLE
repl to resource with existing replica does nothing

### ISSUE THREAD

**Issue by alanking** [irods/irods#4010]
- [x] master
- [x] 4-2-stable

---
### iRODS Version, OS and Version
4.2.3, Ubuntu 16.04

### What did you try to do?
`irepl` data object from storage resource to its own parent resource (in this case, in a replication hierarchy)

### Expected behavior
Replication resource will replicate to each of its children. All other operations are replicated in a replication resource (create, write, etc.).
```
$ ils -l
/tempZone/home/rods:
  rods              0 pt0;repl;ufs2            0 2018-07-02.13:51 & test_file.txt
$ ilsresc
demoResc:unixfilesystem
pt0:passthru
└── repl:replication
    ├── ufs1:unixfilesystem
    └── ufs2:unixfilesystem
$ irepl -R pt0 test_file.txt 
$ ils -l
/tempZone/home/rods:
  rods              0 pt0;repl;ufs2            0 2018-07-02.13:51 & test_file.txt
  rods              1 pt0;repl;ufs1            0 2018-07-02.13:52 & test_file.txt
```

### Observed behavior (including steps to reproduce, if applicable)
Nothing happens. Repl logic short-circuits resource plugins by detecting the good replica and determining that there is nothing to do.
```
$ ils -l
/tempZone/home/rods:
  rods              0 pt0;repl;ufs2            0 2018-07-02.13:51 & test_file.txt
$ ilsresc
demoResc:unixfilesystem
pt0:passthru
└── repl:replication
    ├── ufs1:unixfilesystem
    └── ufs2:unixfilesystem
$ irepl -R pt0 test_file.txt 
$ ils -l
/tempZone/home/rods:
  rods              0 pt0;repl;ufs2            0 2018-07-02.13:51 & test_file.txt
```

**Suggested approach:** Arguably, you could fix this specific scenario with a rebalance, but this could be expensive. As such, we might want to only replicate one data object in some cases. We should pass off `resolveSingleReplCopy`/`HAVE_GOOD_COPY` logic in _rsDataObjRepl to the resource plugins so that their policies can be enforced.

**Comment by tledoux** [comment]
As discussed earlier, this bug is quite annoying when you need to enforce the replication logic on one specific data object, without going to the overall rebalance approach.
Hope to see it fix in a soon to come release. Thanks

**Comment by alanking** [comment]
Related to #3217

**Comment by alanking** [comment]
This has been determined to be "working as designed". Resource hierarchies encode the administrator's policy, so allowing this behavior would be circumventing that policy. See: https://docs.irods.org/4.2.8/plugins/composable_resources/#replication

Suggested workaround - hierarchy manipulation (admin only):
 - Remove from the hierarchy the leaf resource which is to receive the replica (`iadmin rmchildfromresc`)
 - Replicate to the target resource (`irepl -R <target resource>`)
 - Add target leaf resource back to the hierarchy (`iadmin addchildtoresc`)

This workaround allows "repair" of a particular data object in a replicating resource hierarchy without the invocation of a full rebalance.

---

As of 4.2.9, an alternate workaround:
 - Physical move to a different leaf resource in the same replicating hierarchy (`iphymv -R <target resource>`)
 - Replication is triggered automatically to other children in the replicating hierarchy

**Comment by alanking** [comment]
The situation covered above refers to the creation of new replicas. This is still being considered "working as designed". 

However, updating an existing stale replica in a replication resource hierarchy is allowed up through 4.2.8. Consider the following:
```
$ ils -l
/tempZone/home/rods:
  rods              0 repl;ufs0           10 2021-02-11.15:49 X foo
  rods              1 repl;ufs1           10 2021-02-11.15:50 & foo
```
Replication to the replicating node should update the stale replica:

```
$ irepl -R repl foo
$ ils -l
/tempZone/home/rods:
  rods              0 repl;ufs0           10 2021-02-11.15:50 & foo
  rods              1 repl;ufs1           10 2021-02-11.15:50 & foo
```

Up until now, this was achieved by using `resolveSingleReplCopy`:
https://github.com/irods/irods/blob/9eb6c23df45cdedff8ee9c3af71a65d304635037/server/api/src/rsDataObjRepl.cpp#L386-L394

`rsDataObjRepl` has been updated to use hierarchy resolution and `rsDataObjOpen` like other APIs in the server, so this is no longer the case in master/4-2-stable. However, if write operations voted higher for stale replicas instead of good replicas, this would allow for updating existing stale replicas in this situation.

This is different from allowing new replicas to be created because the action is a result of the hierarchy resolution in a more general sense, not a policy override.

**Comment by alanking** [comment]
The referenced commits allow for updating existing replicas by replicating to from a replication hierarchy to itself. As noted in the commit message and the comment above, this does not allow for new replications, by design. See workaround(s) suggested above for single-object rebalances.
