### ISSUE TITLE
During iput -r, symlinks that resolve to regular files are translated to data objects using the wrong name

### ISSUE THREAD

**Issue by andrew-irods** [irods/irods#4013]
- [x] master
- [x] 4-2-stable
-----
## Bug Report

While a physical directory is being traversed in order to copy the files into the vault, if a symlink is encountered which is valid, and pointing to a regular file, iput would attempt to create a data object by the same (short) name as the symlink-target, instead of using the actual symlink filename.

So, in a directory, if you have a regular file called, say, "file1", and a symlink called "sym1" pointing to it, iput -r (of the parent directory) would try and create the data object "file1" twice - once for "file1" itself, and one for "sym1" - instead of creating the data object called "sym1" under the target collection.

It would then error out, with (-312000 OVERWRITE_WITHOUT_FORCE_FLAG), since "file1" already exists. 

Unless, of course, the symlink target was outside of the directory where the original file resides, or if, indeed, the "-f" flag was specified, in which case iput would create the data object under the wrong name, silently.

### iRODS Version, OS and Version
4.2.2, 4.2.3, and the now-current 4-2-stable / Ubuntu 16.04 (and all other OS's)

### Description
Create a directory, tmp, with a regular file, and two symbolic links pointing to that file:

~~~
$ ls -l tmp
total 4
-rw-rw-r-- 1 akelly akelly 29 Jul  6 16:56 file
lrwxrwxrwx 1 akelly akelly  4 Jul  6 16:57 link1 -> file
lrwxrwxrwx 1 akelly akelly  4 Jul  6 16:57 link2 -> file
~~~

There's nothing in irods' vault:

~~~
$ ils -l
/tempZone/home/rods:
~~~

And here's the bug:

~~~
$ iput -r tmp
remote addresses: 127.0.0.1 ERROR: putDirUtil: put tmp/file failed. status = -312000 status = -312000 OVERWRITE_WITHOUT_FORCE_FLAG
remote addresses: 127.0.0.1 ERROR: putDirUtil: put tmp/file failed. status = -312000 status = -312000 OVERWRITE_WITHOUT_FORCE_FLAG
remote addresses: 127.0.0.1 ERROR: putUtil: put error for /tempZone/home/rods/tmp, status = -312000 status = -312000 OVERWRITE_WITHOUT_FORCE_FLAG
~~~

The error messages don't tell the complete story.  The collection /tempZone/home/rods/tmp is where the error occured, but the specific errors listed above come from trying to recreate the "file" data object three times. Once for itself, and then once for "link1", and then once for "link2".

### Expected behavior
Here is what should happen:

~~~
$ iput -r tmp
Running sanity check... pre-flight complete... transferring data...
~~~

(The extra output above is ok - it's from the new version of iput)

~~~
$ ils -l
/tempZone/home/rods:
  C- /tempZone/home/rods/tmp  

$ ils -l tmp
/tempZone/home/rods/tmp:
  rods              0 demoResc           29 2018-07-06.18:22 & file
  rods              0 demoResc           29 2018-07-06.18:22 & link1
  rods              0 demoResc           29 2018-07-06.18:22 & link2
~~~

And that is correct.

**Comment by andrew-irods** [comment]
CI build 1156 running

**Comment by andrew-irods** [comment]
CI Build 1165 (4-2-stable) and 1168 (master) passed.

**Comment by trel** [comment]
merged - please update checkmarks and close
