### ISSUE TITLE
Delay rule:  value too long for type character varying

### ISSUE THREAD

**Issue by acnewton** [irods/irods#4020]
### iRODS Version, OS and Version

irods_version - 4.2.3

### What did you try to do?

I tried to have a delayed rule execute a block of code (a lot of writeLine).

### Expected behavior
It would execute the delayed rule via:
irule -F delayedWriteLine.r

### Observed behavior (including steps to reproduce, if applicable)

[irods@irods-centos ~]$ irule -F delayedWriteLine.r 
remote addresses: 145.100.58.73 ERROR: rcExecMyRule error.  status = -806000 CAT_SQL_ERR
Level 0: DEBUG: 

The serverLog reports the error:
Jul 13 11:34:53 pid:21964 NOTICE: SQL Error message: ERROR: value too long for type character varying(2700);
Error while executing the query

Is there a better way of running a large block of code in a delayed rule (without writing a microservice or using msiExecCmd calling a rule)?

**Comment by trel** [comment]
You are correct - the database column is not long enough to store that much ruletext.

You can shorten the amount of ruletext being stored in the delay codeblock if you can put some of the code into (hopefully generic) helper functions that could be installed in the server's rulebase (in `/etc/irods/*.re`) and then call them from the code in the delay block.

This is a workaround that requires someone with server administrator access to load/save that rule code in the server.

**Comment by acnewton** [comment]
Thanks for the reply and workaround. 
Before, I tried to create a helper function in a *.r file and starting it as:
irule -F delayedWriteLine.r
which didn't work as it doesn't recognize the helper function. 
Now, I created the helper function inside a *.re file which is installed in the server_config.json and it does work!

**Comment by trel** [comment]
Excellent.

We've talked about how to allow longer rules in the catalog, but consistency across multiple database backends was more important than bumping this limit a bit farther (we'd still have a limit, which someone else would still eventually hit).

I'm going to close this, and mark as workaround.

Thanks for the confirmation.
