### ISSUE TITLE
iscan -rd <Collection_Path> doesn't page past missing files

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#4029]
- [x] master
- [x] 4-2-stable
- [x] 4-1-stable

---
### iRODS Version, OS and Version
irods 4.2.3, ubuntu 14.04

### What did you try to do?
Use iscan  over data objects in an iRODS collection in which some number of them have had their counterparts (files in a local filesystem) deleted.  

### Expected behavior
iscan should iterate over all pages of genquery results, even when they contain references to deleted files

(When the counterpart on disk has been deleted, corresponding to an object in the scanned collection, the error returned by statPhysFile() in GIT-ROOT/lib/core/src/scanUtil.cpp is -516002 :
irods error: -516002 UNIX_FILE_STAT_ERR No such file or directory)

### Observed behavior (including steps to reproduce, if applicable)

iscan stops after the first page of genquery results (256) if the above or any non-zero status is returned from the file check in statPhysFile() [ ~line 215 of scanUtil.cpp ]

**Comment by kript** [comment]
Have you tried to reproduce this on the 4.1 branch, do you know?

**Comment by jaking92** [comment]
I ran Dan's script and found that the issue also exists in 4-1-stable.
