### ISSUE TITLE
icp/iput/irsync -r into the "/" collection produces correct behavior, but unclear error message

### ISSUE THREAD

**Issue by andrew-irods** [irods/irods#4030]
- [x] master
- [x] 4-2-stable
-----

## Bug Report

When trying any of the icommands below:

~~~
iput -r dir /
irsync -r dir i:/
icp -r some_collection /
~~~
The command fails appropriately with the following error message:

~~~
remote addresses: 127.0.0.1 ERROR: resolveRodsTarget: mkColl/mkdir for //dir1,status=-130000 status = -130000 SYS_INVALID_INPUT_PARAM
remote addresses: 127.0.0.1 ERROR: putUtil: resolveRodsTarget error, status = -130000 status = -130000 SYS_INVALID_INPUT_PARAM
~~~

Looking at rodsLog for this operation, we find this error message:

~~~
Jul 26 09:28:12 pid:6083 remote addresses: 127.0.0.1 ERROR: [-] /mnt/sdb2/home/andrew/github/irods/server/core/src/dataObjOpr.cpp:55:irods::error validate_logical_path(const std::string &) :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message [a valid zone name does not appear at the root of the object path [//dir1]]
~~~

This information is much clearer, and would be helpful to the user.  Investigate providing this information as part of the error message given to the user on the screen.

### iRODS Version, OS and Version
4-2-stable / All OS's

**Comment by andrew-irods** [comment]
Under development.

New error message will look like this if there's agreement:

~~~
remote addresses: 127.0.0.1 ERROR: resolveRodsTarget: mkColl/mkdir for //dir1,status=-130000 status = -130000 SYS_INVALID_INPUT_PARAM
remote addresses: 127.0.0.1 ERROR: rsyncUtil: resolveRodsTarget status = -130000 SYS_INVALID_INPUT_PARAM
Level 0: status [SYS_INVALID_INPUT_PARAM]  errno [] -- message [a valid zone name does not appear at the root of the object path [//dir1]]
~~~

**Comment by andrew-irods** [comment]
Another enhancement to the behavior of iput with this fix:  whereas iput will continue to push regular files into irods even when there are errors on other files, this will no longer be true for files whose destination is a collection that could not be created.  When this occurs, the put operation into that collection will be aborted.

**Comment by andrew-irods** [comment]
CI build 1277 running

**Comment by andrew-irods** [comment]
CI build 1285 passed (same 2 red dots on topo as build 1284 for irods/master)

**Comment by trel** [comment]
checkbox and close!
