### ISSUE TITLE
irsync fails to transfer regular files to target collection

### ISSUE THREAD

**Issue by andrew-irods** [irods/irods#4048]
- [x] master
- [x] 4-2-stable
-----
## Bug Report

When irsync is called to transfer a regular file into an existing collection, it fails to do so.  This happens with both single as well as multiple source files.

To reproduce:

~~~
$ ls -l 
-rw-rw-r-- 1 akelly akelly    2 Jul 20 15:25 xx1
-rw-rw-r-- 1 akelly akelly    2 Jul 20 15:25 xx2
$
$ $ imkdir target 
$ ils -lr
/tempZone/home/rods:
  C- /tempZone/home/rods/target  
/tempZone/home/rods/target:
$
$ irsync xx1 xx2 i:target
$ ils -lr
/tempZone/home/rods:
  C- /tempZone/home/rods/target  
/tempZone/home/rods/target:
~~~

Nothing happened.  The two files should have been transferred as data objects under collection "target1", named "xx1" and "xx2".

(Same result when only a single file is to be transferred).

### iRODS Version, OS and Version
Reproduced under 4-2-stable (current), as well as 4.2.2.
Reproduced under Ubuntu-16.04 - relevant for all other os's.

**Comment by trel** [comment]
checkbox and close!
