### ISSUE TITLE
pep_resource_open_pre issues 

### ISSUE THREAD

**Issue by beheerderdag** [irods/irods#4054]
We have a custom rule (running with 4.1.x) that uses pep_resource_open_pre. I am trying to test the same rule in 4.2.3. 

Does pep_resource_open_pre work the same way in 4.2.3? I noticed that it requires three arguments now. Previously we had
```pep_resource_open_pre(*OUT)```
Now it is this: 
```pep_resource_open_pre(*INSTANCE, *CONTEXT, *OUT)``` 
How can I make sure this works in 4.2.3? 

When I try an iput with the rule enabled in server_config, I see this: 

``` 
iput -v -R myArchiveResc /tmp/arctest arctest3
remote addresses: 145.100.x.xx ERROR: rcvTranHeader: toread = 24, read = 0
remote addresses: 145.100.x.xx ERROR: rcvTranHeader: toread = 24, read = 0
remote addresses: 145.100.x.xx ERROR: rcvTranHeader: toread = 24, read = 0
remote addresses: 145.100.x.xx ERROR: rcvTranHeader: toread = 24, read = 0
remote addresses: 145.100.x.xx ERROR: rcvTranHeader: toread = 24, read = 0
remote addresses: 145.100.x.xx ERROR: rcvTranHeader: toread = 24, read = 0
remote addresses: 145.100.x.xx ERROR: rcvTranHeader: toread = 24, read = 0
remote addresses: 145.100.x.xx ERROR: rcvTranHeader: toread = 24, read = 0
remote addresses: 145.100.x.xx ERROR: rcvTranHeader: toread = 24, read = 0
remote addresses: 145.100.x.xx ERROR: rcvTranHeader: toread = 24, read = 0
remote addresses: 145.100.x.xx ERROR: rcvTranHeader: toread = 24, read = 0
remote addresses: 145.100.x.xx ERROR: rcvTranHeader: toread = 24, read = 0
 ERROR: rcvTranHeader: toread = 24, read = 0
 ERROR: rcvTranHeader: toread = 24, read = 0
 ERROR: rcvTranHeader: toread = 24, read = 0
 ERROR: rcvTranHeader: toread = 24, read = 0
 ERROR: [-]     /tmp/tmpIhxPZi/lib/core/src/procApiRequest.cpp:178:int sendApiRequest(rcComm_t *, int, void *, bytesBuf_t *) :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message [wrote 0 expected 139]
        [-]     /tmp/tmpIhxPZi/lib/core/src/sockComm.cpp:1257:irods::error sendRodsMsg(irods::network_object_ptr, const char *, bytesBuf_t *, bytesBuf_t *, bytesBuf_t *, int, irodsProt_t) :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message [wrote 0 expected 139]
                [-]     /tmp/tmpIhxPZi/plugins/network/tcp/libtcp.cpp:355:irods::error tcp_send_rods_msg(irods::plugin_context &, const char *, bytesBuf_t *, bytesBuf_t *, bytesBuf_t *, int, irodsProt_t) :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message [wrote 0 expected 139]
                        [-]     /tmp/tmpIhxPZi/lib/core/src/sockComm.cpp:475:irods::error writeMsgHeader(irods::network_object_ptr, msgHeader_t *) :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message [wrote 0 expected 139]
                                [-]     /tmp/tmpIhxPZi/plugins/network/tcp/libtcp.cpp:293:irods::error tcp_write_msg_header(irods::plugin_context &, bytesBuf_t *) :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message [wrote 0 expected 139]

 ERROR: putUtil: put error for /tempZone/home/irsara/arctest3, status = -27000 status = -27000 SYS_COPY_LEN_ERR
```
The rule in question is here: https://github.com/Msaum87/iRODS-DMF-Archive/blob/master/etc/irods/archive.re

**Comment by trel** [comment]
Is this a large file (>32MB)?

Are the ports open from client to target server directly? (large files are redirected to the target server)

**Comment by beheerderdag** [comment]
I did some more tests and gathered some more debug data. Let me know if you need more information. 
I can put both small and large files with just the core.re in place, no issues. 

Then I added this simple rule: 
```
# cat /etc/irods/myRule.re 

pep_resource_open_pre(*INSTANCE, *CONTEXT, *OUT)  { 
   writeLine('serverLog','PEP resource open pre test'); 
}
```
Included in server_config.json:
```
"re_rulebase_set": [
                         "myRule", 
                         "core"
                    ], 
```
I did a iput of a 100MB file and In the server log I saw: 
```
Aug 10 09:27:05 pid:3251 NOTICE: writeLine: inString = PEP resource open pre test
Aug 10 09:27:05 pid:3251 NOTICE: writeLine: inString = PEP resource open pre test
Aug 10 09:27:05 pid:3251 NOTICE: writeLine: inString = PEP resource open pre test
Aug 10 09:27:05 pid:3251 NOTICE: writeLine: inString = PEP resource open pre test
Aug 10 09:27:05 pid:3251 NOTICE: writeLine: inString = PEP resource open pre test
Aug 10 09:27:05 pid:3251 NOTICE: writeLine: inString = PEP resource open pre test
Aug 10 09:27:05 pid:3251 NOTICE: writeLine: inString = PEP resource open pre test
Aug 10 09:27:05 pid:3251 NOTICE: writeLine: inString = PEP resource open pre test
Aug 10 09:27:05 pid:3251 NOTICE: writeLine: inString = PEP resource open pre test
Aug 10 09:27:05 pid:3251 NOTICE: writeLine: inString = PEP resource open pre test
Aug 10 09:27:05 pid:3251 NOTICE: writeLine: inString = PEP resource open pre test
Aug 10 09:27:05 pid:3251 NOTICE: writeLine: inString = PEP resource open pre test
Aug 10 09:27:05 pid:3251 NOTICE: writeLine: inString = PEP resource open pre test
Aug 10 09:27:05 pid:3251 NOTICE: writeLine: inString = PEP resource open pre test
Aug 10 09:27:05 pid:3251 NOTICE: writeLine: inString = PEP resource open pre test
```
So far so good. Now I added our custom surfDMF rule in the server config with changing the pep line to `pep_resource_open_pre(*INSTANCE, *CONTEXT, *OUT)` and this time I saw a stack trace in the log. Please see the attached file. Not sure if something in our rule causing this. As I said this works in 4.1.x. 
[pep_stack_trace.txt](https://github.com/irods/irods/files/2277010/pep_stack_trace.txt)

**Comment by beheerderdag** [comment]
I tried the following with acPostProcForPut and it worked:
```
acPostProcForPut { 
   if($rescName == "arcRescSURF01") {   
    writeLine("serverLog", "acPostProcForPut called for $objPath in $rescName"); 
}
}
```
however, this still does not work with PEP: 
```
pep_resource_open_pre(*INSTANCE, *CONTEXT, *OUT)  { 
   if($rescName == "arcRescSURF01") {   
   writeLine('serverLog', 'NEW resource_open pre .... ');
   }
else { 
       writeLine('serverLog', 'DO NOTHING ');
}
}
```
In the log: 
```
Aug 13 10:21:26 pid:10020 DEBUG: error: unable to read session variable $rescName.
```
I also tried it with `$KVPairs.rescName` then I get the signal 11 and stack trace in the log.  So I might be missing something obvious or something else is broken here.

**Comment by trel** [comment]
We can work on cleaning up the stacktrace separately...

The plugin instance name (in this case, the resource name) is in the `*INSTANCE` variable:

```
pep_resource_open_pre(*INSTANCE, *CONTEXT, *OUT)  { 
   writeLine("serverLog", *INSTANCE);
}
```

Then, issue an iget, and you'll see the resource name appear in the log.

**Comment by beheerderdag** [comment]
ok. Thanks for the clarification. I changed my test rule and this is now working. 
```
pep_resource_open_pre(*INSTANCE, *CONTEXT, *OUT)  { 
   if(*INSTANCE == "arcRescSURF01") {   
   writeLine('serverLog', 'NEW resource_open pre .... *INSTANCE');
  }
else { 
    
   writeLine('serverLog', 'DO NOTHING ');
}
}
```
However, I still need to do some more modifications to the original rule. It seems I get signal 11 every time there are variables like `$KVPairs.physical_path`, `$KVPairs.logical_path`.  How can I use these variables in 4.2.3? 

thanks.

**Comment by jasoncoposky** [comment]
Sharif,

All of that information is now captured at the point of call within the *CONTEXT variable.  Print that out and you will see it as keywords for *CONTEXT.

Thanks,

------
Jason Coposky
Executive Director, iRODS Consortium
RENCI at the University of North Carolina at Chapel Hill
w: (919)445-9675<tel:%28919%29445-9675>
m: (919)522-0517<tel:%28919%29445-9675>
jasonc@renci.org<mailto:jasonc@renci.org>
linkedin<https://www.linkedin.com/in/jason-coposky-06bab01>
twitter<https://twitter.com/jason_coposky>
irods.org<http://irods.org/>

**Comment by beheerderdag** [comment]
Thanks. I was able to get this work. I think now I know how to port my rule to 4.2.x. 
```
pep_resource_open_pre(*INSTANCE, *CONTEXT, *OUT)  { 
   if(*INSTANCE == "arcRescSURF01") {   
   *mypath=*CONTEXT.physical_path; 
   writeLine("serverLog", "*mypath"); 
  }
else { 
    
   writeLine('serverLog', 'DO NOTHING ');
}
}
```
I think simple examples like this in the irods doc would be helpful to understand the data structure.

**Comment by trel** [comment]
part of #4660
