### ISSUE TITLE
Setting AVU value to empty when AVU is shared between objects causes an error

### ISSUE THREAD

**Issue by cjsmeele** [irods/irods#4063]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---
### iRODS Version, OS and Version

iRODS version 4.2.3, on CentOS7

### What did you try to do?

In order:

1. Set the same AVU combination on two different user objects
   (attr=metatest1, value=metatest1_value).
2. Set the value component of that AVU to an empty string for one of
   those two users.

(see further down for the exact commands used)

### Expected behavior

After step 2, one user has AVU attr=metatest1 value=metatest1_value, while the
other user has attr=metatest1 value= (empty).

### Observed behavior (including steps to reproduce, if applicable)

An error is returned by imeta when clearing the value in step 2:

    remote addresses: 127.0.0.1 ERROR: rcModAVUMetadata failed with error -816000 CAT_INVALID_ARGUMENT 

This might be related to #2769.

When two objects share the same AVU combination, emptying the V part for
one object using `imeta set` causes a SQL error. When the AVU is unique
(not shared between multiple objects), no error occurs.

The problem occurs with imeta, but `rsModAVUMetadata` itself, with first
argument `set`, also triggers the error.

#### Steps to reproduce

A minimal example that triggers the problem (using collections instead of user objects):

```
$ imkdir col1
$ imkdir col2
$ imeta set -C col1 metatest1 metatest1_value
$ imeta set -C col2 metatest1 metatest1_value
$ imeta set -C col2 metatest1 ''
remote addresses: 127.0.0.1 ERROR: rcModAVUMetadata failed with error -816000 CAT_INVALID_ARGUMENT 
$ imeta set -C col2 metatest1 '.'
$ imeta set -C col2 metatest1 ''
$
```

As shown, changing the value to anything that isn't empty works without issues,
and the value can be changed to empty afterwards.

In the failure case, the rodsLog contains the following:

```
Aug 15 13:12:42 pid:11433 NOTICE: rsModAVUMetadata: rcModAVUMetadata failed
Aug 15 13:12:42 pid:11433 NOTICE: Warning, pending SQL at cllDisconnect, count: 2
Aug 15 13:12:42 pid:11433 NOTICE: Warning, pending SQL: begin ...
Aug 15 13:12:42 pid:11433 NOTICE: Warning, pending SQL: delete from R_OBJT_METAMAP wh ...
```

To demonstrate that this problem only occurs with identical AVUs that are
shared between two objects, the following works fine:

```
$ imkdir col1
$ imkdir col2
$ imeta set -C col1 metatest1 metatest1_value
$ imeta set -C col2 metatest1 metatest2_value
$ imeta set -C col2 metatest1 ''
$
```

**Comment by MartinFlores751** [comment]
Is there a use case you had in mind for having an empty string?

**Comment by trel** [comment]
having an empty unit is allowed (just setting AV, no U) - so it should be allowed to be set unit to empty after it was already something else...
