### ISSUE TITLE
Unfixed order of roles in iRODS setup script

### ISSUE THREAD

**Issue by abartimmo** [irods/irods#4071]
## BUG
The order of roles (provider or consumer) is not fixed in the iRODS setup script due to the use of set, where a tuple or list should be used:

https://github.com/irods/irods/blob/a257e307348a2c65da2425dcba485a709be54b2a/scripts/setup_irods.py#L168

It will not affect interactive setup but lead to unexpected results for automated setup. The issue has been addressed in the Ansible playbook by modifying the script on-the-fly:

https://github.com/heliumdatacommons/irods-deploy/blob/5ea921db58778c682713ac98e045e7e36fba3655/ansible/irods_icat/roles/install_icat/tasks/main.yml#L20-L25

Related to #118

**Comment by trel** [comment]
The setup script honors the existing setup if it already exists - so a server previously configured in the 'provider' role will have the default input keep it in the 'provider' role.  If the server was already configured for 'consumer', then the default input will keep it as a 'consumer'.

The link you provided is a private repository - and issue 118 is presumably in that repo as well?

What would you propose the iRODS setup script do differently in this case?  A tuple or list?  Can you provide an example or PR?

**Comment by trel** [comment]
Closing - the current behavior is working as designed.   Counter examples always welcome.
