### ISSUE TITLE
resource vote appears to have  little impact

### ISSUE THREAD

**Issue by tsmeele** [irods/irods#4077]
Applies to: iRODS 4.1.8  centos7

Scenario:
We have multiple Unix type resources each as child of a pass thru resource. The pass-thru resources are child of a common random type resource.
One of the Unix type resources is full, so we modified its pass-thru parent to include a context "write=0.1;read=1.0".  A setting of write=0.0 is avoided to still allow an existing data object to be updated.
All other pass-thru's do not have a context set.

I would expect the resource not be voted anymore for any new data object to be written and hence not to grow (much) anymore yet I notice that its usage still expands quite rapidly.

**Comment by trel** [comment]
@JustinKyleJames should be easy enough to test by building a representative tree, putting a number of files into the tree, and checking for data_objects in each resource.

**Comment by alanking** [comment]
If votes other than 0.0 were considered in a random resource hierarchy, it would go against the purpose of the coordinating resource. However, your concern uncovered a limitation in the passthru context string weights. An issue proposing new functionality for the context string to allow for more flexibility has been created: #4548. Once that is implemented, you would be able to set the "create" operation's weight to 0.0 to block create operations on that sub-hierarchy.

For now, we suggest implementing some policy in `pep_resource_resolve_hierarchy_pre` to block create operations on that particular sub-hierarchy. For an example of how this might look, see the training slides for Composable Resources: http://slides.com/irods/ugm2017-composable-resources#/16

Thanks!
