### ISSUE TITLE
irodsServer coredump on startup

### ISSUE THREAD

**Issue by cgrzemba** [irods/irods#4086]
### iRODS Version, OS and Version
rodsServer Release version rods4.2.3 - API Version d
Oracle Linux Server release 7.4

### What did you try to do?
start service

### Expected behavior
deamon runs

### Observed behavior (including steps to reproduce, if applicable)
After it works some time, now it don't starts anymore. Instead coredump

```
bash-4.2$ /usr/sbin/irodsServer -Vsu
Aug 29 10:00:20 pid:14248 NOTICE: Agent factory process pid = [14249]
Aug 29 10:00:20 pid:14248 DEBUG: config file found [/etc/irods/server_config.json]
Aug 29 10:00:20 pid:14249 DEBUG: config file found [/etc/irods/server_config.json]
Aug 29 10:00:20 pid:14248 DEBUG: xmsg_host is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_authentication_scheme is not defined
Aug 29 10:00:20 pid:14248 DEBUG: xmsg_port is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_debug is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_authentication_file is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_ca_certificate_path is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_ca_certificate_file is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_verify_server is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_certificate_chain_file is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_certificate_key_file is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_dh_params_file is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_plugins_home is not defined
Aug 29 10:00:20 pid:14248 DEBUG: resolved plugin home [/usr/lib/irods/plugins/rule_engines/]
Aug 29 10:00:20 pid:14248 DEBUG: load_plugin - calling plugin_factory() in [/usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-python.so]
Aug 29 10:00:20 pid:14248 DEBUG: load_plugin - loaded [irods_rule_engine_plugin-python]
Aug 29 10:00:20 pid:14248 DEBUG: xmsg_host is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_authentication_scheme is not defined
Aug 29 10:00:20 pid:14248 DEBUG: xmsg_port is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_debug is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_authentication_file is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_ca_certificate_path is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_ca_certificate_file is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_verify_server is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_certificate_chain_file is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_certificate_key_file is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_dh_params_file is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_plugins_home is not defined
Aug 29 10:00:20 pid:14248 DEBUG: resolved plugin home [/usr/lib/irods/plugins/rule_engines/]
Aug 29 10:00:20 pid:14248 DEBUG: load_plugin - calling plugin_factory() in [/usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-irods_rule_language.so]
Aug 29 10:00:20 pid:14248 DEBUG: load_plugin - loaded [irods_rule_engine_plugin-irods_rule_language]
Aug 29 10:00:20 pid:14248 DEBUG: xmsg_host is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_authentication_scheme is not defined
Aug 29 10:00:20 pid:14248 DEBUG: xmsg_port is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_debug is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_authentication_file is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_ca_certificate_path is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_ca_certificate_file is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_verify_server is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_certificate_chain_file is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_certificate_key_file is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_dh_params_file is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_plugins_home is not defined
Aug 29 10:00:20 pid:14248 DEBUG: resolved plugin home [/usr/lib/irods/plugins/rule_engines/]
Aug 29 10:00:20 pid:14248 DEBUG: load_plugin - calling plugin_factory() in [/usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-cpp_default_policy.so]
Aug 29 10:00:20 pid:14248 DEBUG: load_plugin - loaded [irods_rule_engine_plugin-cpp_default_policy]
Aug 29 10:00:20 pid:14248 DEBUG: xmsg_host is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_authentication_scheme is not defined
Aug 29 10:00:20 pid:14248 DEBUG: xmsg_port is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_debug is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_authentication_file is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_ca_certificate_path is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_ca_certificate_file is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_verify_server is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_certificate_chain_file is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_certificate_key_file is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_dh_params_file is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_plugins_home is not defined
Aug 29 10:00:20 pid:14248 DEBUG: queZone:  masterServerHost for tempZone is NULL
Aug 29 10:00:20 pid:14248 DEBUG: initServerInfo - queZone failed -21000
Aug 29 10:00:20 pid:14248 DEBUG: config file found [/etc/irods/hosts_config.json]
    LocalHostName:  localhost, wcc1, con105.example.lan, Port Num: 1247.

Aug 29 10:00:20 pid:14248 DEBUG: xmsg_host is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_authentication_scheme is not defined
Aug 29 10:00:20 pid:14248 DEBUG: xmsg_port is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_debug is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_authentication_file is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_ca_certificate_path is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_ca_certificate_file is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_verify_server is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_certificate_chain_file is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_certificate_key_file is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_ssl_dh_params_file is not defined
Aug 29 10:00:20 pid:14248 DEBUG: irods_plugins_home is not defined
Aug 29 10:00:20 pid:14248 DEBUG: resolved plugin home [/usr/lib/irods/plugins/database/]
Aug 29 10:00:20 pid:14248 DEBUG: load_plugin - calling plugin_factory() in [/usr/lib/irods/plugins/database/libmysql.so]
Aug 29 10:00:20 pid:14248 DEBUG: load_plugin - loaded [mysql]
Aug 29 10:00:20 pid:14248 DEBUG1: begin
Aug 29 10:00:20 pid:14248 DEBUG1: SET SESSION autocommit=0
Aug 29 10:00:20 pid:14248 DEBUG1: SET SESSION sql_mode='ANSI,STRICT_TRANS_TABLES'
Aug 29 10:00:20 pid:14248 DEBUG1: SET character_set_client = utf8
Aug 29 10:00:20 pid:14248 DEBUG1: SET character_set_results = utf8
Aug 29 10:00:20 pid:14248 DEBUG1: SET character_set_connection = utf8
Aug 29 10:00:20 pid:14248 DEBUG: [db_open_op:2014] PAM property not found
Aug 29 10:00:20 pid:14248 DEBUG1: select distinct R_ZONE_MAIN.zone_name ,R_ZONE_MAIN.zone_type_name ,R_ZONE_MAIN.zone_conn_string ,R_ZONE_MAIN.r_comment  from  R_ZONE_MAIN 
Zone Info:
    ZoneName: tempZone   Type: LOCAL_ICAT    HostAddr: localhost   PortNum: 1247

reHost:   localhost

Aug 29 10:00:20 pid:14248 DEBUG: config file found [/var/lib/irods/config/lockFileDir]
Aug 29 10:00:20 pid:14248 NOTICE: rodsServer Release version rods4.2.3 - API Version d is up
Aug 29 10:00:20 pid:14252 NOTICE: Starting irodsReServer
Segmentation fault (core dumped)
```
[core_backtrace.txt](https://github.com/irods/irods/files/2331289/core_backtrace.txt)

**Comment by trel** [comment]
Hi @cgrzemba 

You appear to invoke the server manually in the output above - was that done to share in the issue?

Or are you trying to do that 'for real'?  If so, why?

Use the `/var/lib/irods/irodsctl` script instead?

**Comment by cgrzemba** [comment]
Not for real, only because normal startup failed

**Comment by trel** [comment]
Okay - during regular `irodsctl` startup, please check for anything interesting in:
 - `/var/lib/irods/log/rodsLog*`
 - `/var/lib/irods/log/rodsServerLog*`
 - `/var/lib/irods/log/reLog*`

**Comment by cgrzemba** [comment]
hmm, 
irodsctl start
works like expected. 
Try to spool back to the begin of trouble servernot starting, I could extract /etc/hosts as problem:
working: 
172.16.1.105	con105.example.lan wcc1 con105

not working 
172.16.1.105	wcc1 con105.example.lan con105

but this should means the same in the sense of /etc/hosts

from DNS
wcc1.example.lan.	7200	IN	CNAME	con105.example.lan.
con105.example.lan.	7200	IN	A	172.16.1.105

control_log.txt
2018-08-30 13:34:37,594 -   DEBUG -                  controller.py: 102 - Attempting to connect to iRODS server on port 1247. Attempt #100
2018-08-30 13:34:37,594 -    INFO -                  controller.py: 120 - Failure
2018-08-30 13:34:37,594 -   ERROR -               irods_control.py: 119 - Error encountered running irods_control start:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods_control.py", line 116, in main
    operations_dict[operation]()
  File "/var/lib/irods/scripts/irods_control.py", line 70, in <lambda>
    operations_dict['start'] = lambda: irods_controller.start()
  File "/var/lib/irods/scripts/irods/controller.py", line 121, in start
    six.reraise(IrodsError, e, sys.exc_info()[2])
  File "/var/lib/irods/scripts/irods/controller.py", line 115, in start
    raise IrodsError('iRODS server failed to start.')
IrodsError: iRODS server failed to start.
2018-08-30 13:34:37,595 -    INFO -               irods_control.py: 120 - Exiting...

rodsServerLog
Aug 30 15:32:58 pid:24809 DEBUG: queZone:  masterServerHost for tempZone is NULL
Aug 30 15:32:58 pid:24809 DEBUG: initServerInfo - queZone failed -21000
Aug 30 15:32:58 pid:24809 DEBUG: config file found [/etc/irods/hosts_config.json]
    LocalHostName:  localhost, wcc1, Port Num: 1247.

Aug 30 15:32:58 pid:24809 DEBUG: connectToRhostWithTout: myval error, errno = 111
Aug 30 15:32:58 pid:24809 DEBUG: connectToRhostWithTout: myval error, errno = 111
Aug 30 15:32:58 pid:24809 DEBUG: connectToRhostWithTout: myval error, errno = 111
Aug 30 15:32:58 pid:24809 NOTICE: connectToRhost: connect to host con105.contac.lan on port 1247 failed status = -305111 USER_SOCK_CONNECT_ERR, Connection refused
Aug 30 15:32:58 pid:24809  ERROR: _rcConnect: connectToRhost error, server on con105.contac.lan:1247 is probably down status = -305111 USER_SOCK_CONNECT_ERR, Connection refused
Aug 30 15:32:58 pid:24809 NOTICE: getAndConnRcatHost: svrToSvrConnect to con105.contac.lan failed
Aug 30 15:32:58 pid:24809 NOTICE: initZone: rsGenQuery error, status = -305111
Aug 30 15:32:58 pid:24809 SYSTEM FATAL: initServerInfo: initZone error, status = -305111
Aug 30 15:32:58 pid:24809 NOTICE: initServer: initServerInfo error, status = -305111
Aug 30 15:32:58 pid:24809  ERROR: initServerMain: initServer error. status = -305111

**Comment by trel** [comment]
What is returned by:
```
$ hostname
```

This value returned must match the name of your server as entered in `server_config.json` and visible/reachable as resolved via DNS or `/etc/hosts`.

**Comment by cgrzemba** [comment]
there is a discrepancy

    grep -A 2 host /etc/irods/server_config.json 
    "catalog_provider_hosts": [
        "con105.example.lan"
    ], 
                "db_host": "localhost", 
                "db_name": "ICAT", 
                "db_odbc_driver": "MySQL", 

and

    $ hostname
    wcc1

Is there a clean way to change the hostname in relation to the irdos setup?
I like to keep wcc1 in this case.
I guess simply change the catalog_provider_hosts is not enough.

**Comment by trel** [comment]
Ah, very good.

I believe you can update the `catalog_provider_hosts` - and we'll see if anything else has the "con105.example.lan" value.  Other candidates include the value stored in the resource definition in the catalog and the `/etc/hosts` on the other machine.

**Comment by trel** [comment]
Try to see if changing the value takes immediate effect - or whether you need to restart the iRODS server.  I expect this value is read by the main server process and not just the spawned Agents, so you may need to restart the iRODS server itself.
