### ISSUE TITLE
acPostProcForPut {msiSysChksumDataObj; } only checksums replica 0

### ISSUE THREAD

**Issue by bh9** [irods/irods#4106]
### iRODS Version, OS and Version
4.1.12

### What did you try to do?
iput a file
seq-dev.re has `acPostProcForPut {msiSysChksumDataObj; }` and server_config has 
```
   "re_rulebase_set" : [
        {
            "filename": "acAclPolicy"
        },
        {
            "filename": "seq-dev"
        },
        {
            "filename": "4110additionalPEPDefinitions"
        },
        {
           "filename" : "core"
        }
   ],
```
so the file should be checksummed
### Expected behavior
Both replicas are checksummed, input should appear as it would if placed with `iput -k`

### Observed behavior (including steps to reproduce, if applicable)
```
bh9@irods-sanger1-dev:~$ iput thing
```
```
bh9@irods-sanger1-dev:~$ ils -L thing
  bh9               0 root;replicate;red;red2;irods-seq-i08-fg          373 2018-09-10.12:53 & thing
    fdc45f5eb8963c5a53b71a00a998839a    generic    /irods-seq-i08-fg/home/bh9#Sanger1-dev/thing
  bh9               1 root;replicate;green;green3;irods-seq-sr03-ddn-gg07-18-19-20          373 2018-09-10.12:53 & thing
        generic    /irods-seq-sr03-ddn-gg07-18-19-20/home/bh9#Sanger1-dev/thing
```
Only replica 0 is checksummed, not replica 1

**Comment by alanking** [comment]
Could you try putting a similar policy in place for `acPostProcForRepl` in addition to *Put? I think this should result in the expected behavior.

I also found this behavior a bit surprising, but after thinking about it, `iput -K` "just works" in this case because of the way that particular client is implemented. In the case of `acPostProcFor*`, we are dealing with the rule engine, so dealing with policy is slightly more granular. Hopefully that helps as a way of explanation

**Comment by bh9** [comment]
After changing the .re on the ies, how would we then go about applying the change? Simply touching the server_config wasn't sufficient, and we'd like to avoid a restart if possible

**Comment by trel** [comment]
I believe 4.1.x didn't reload *all* the .re files on each new Agent, just the `core.re`.

Can you add the new `acPostProcForRepl` to `core.re` to confirm that it is firing without a server restart?

**Comment by bh9** [comment]
Added `acPostProcForRepl {msiSysChksumDataObj; }
` to `core.re`, then touched `server_config.json`, but still not checksumming replicate 1

**Comment by trel** [comment]
I've just updated a supplemental `.re` file directly, and the edit was recognized by the next Agent - without touching `server_config.json` or restarting the 4.1.10 server.

initial configuration:
```
irods@host:/etc/irods$ ienv | grep Version
NOTICE: Release Version = rods4.1.10, API Version = d
irods@host:/etc/irods$ ilsresc
demoResc
repl:replication
├── ufs1
└── ufs2
irods@host:/etc/irods$ grep -C3 additional server_config.json 
    ], 
    "re_rulebase_set": [
        {
            "filename": "additional"
        },
        {
            "filename": "core"
irods@host:/etc/irods$ cat additional.re 
acPostProcForPut {msiSysChksumDataObj;}
```
`iput` places checksum only on initial replica:
```
irods@host:/etc/irods$ echo "testfile" > testfile
irods@host:/etc/irods$ iput -R repl testfile
irods@host:/etc/irods$ ils -L
/tempZone/home/rods:
  rods              0 repl;ufs2            9 2018-09-11.09:05 & testfile
    sha2:oe/2PWwMOeTYBLEDbs1pJOff7yzivuvNwxpa1WQJHqo=    generic    /tmp/ufs2Vault/home/rods/testfile
  rods              1 repl;ufs1            9 2018-09-11.09:05 & testfile
        generic    /tmp/ufs1Vault/home/rods/testfile
```

update policy file, and now checksum visible on both replicas:
```
irods@host:/etc/irods$ echo "acPostProcForRepl {msiSysChksumDataObj;}" >> additional.re 
irods@host:/etc/irods$ cat additional.re 
acPostProcForPut {msiSysChksumDataObj;}
acPostProcForRepl {msiSysChksumDataObj;}
irods@host:/etc/irods$ iput -R repl testfile testfile2
irods@host:/etc/irods$ ils -L testfile2
  rods              0 repl;ufs2            9 2018-09-11.09:06 & testfile2
    sha2:oe/2PWwMOeTYBLEDbs1pJOff7yzivuvNwxpa1WQJHqo=    generic    /tmp/ufs2Vault/home/rods/testfile2
  rods              1 repl;ufs1            9 2018-09-11.09:06 & testfile2
    sha2:oe/2PWwMOeTYBLEDbs1pJOff7yzivuvNwxpa1WQJHqo=    generic    /tmp/ufs1Vault/home/rods/testfile2
```

Please confirm that there is not a separate `acPostProcForRepl` defined elsewhere earlier in your policy set.

**Comment by bh9** [comment]
That still didn't work, is it possible that the problem is that the rule is being run by a different host (e.g. the iRES)? And that the change needs to be applied to both the ies and the ires? This difference would be hidden by your test case of a single server representing every role

**Comment by bh9** [comment]
Yes, it is. The ires servers need the change too. Working now

**Comment by trel** [comment]
Correction:  For DataObj operations (logical), the policy is fired on the machine holding your connection.  For file operations, the machine in charge of the storage will fire the policy.
