### ISSUE TITLE
api plugin call post pep is not called when api plugin returns an error code

### ISSUE THREAD

**Issue by xu-hao** [irods/irods#4128]
- [x] master
- [x] 4-2-stable
-----

### iRODS Version, OS and Version

master, 4.2.x, 4-2-stable

### What did you try to do?

log error for api calls in audit plugin
### Expected behavior

audit plugin should call post pep for api plugin

### Observed behavior (including steps to reproduce, if applicable)

 post pep for api plugin not called when api plugin returns an error code

https://github.com/irods/irods/blob/master/lib/core/include/apiHandler.hpp#L174

**Comment by jasoncoposky** [comment]
@HowardLander

Consider adding a third class of dynamic policy enforcement point, for when either the Pre-PEP or API / Plugin operation itself fails, which will allow the audit plugin to have full scope to failures within the system, as well as any possible recovery options.

Possible Candidates:
```
pep_operation_fail()
pep_operation_error()
pep_operation_finally()
```

For full audit visibility, pass the error and any other relevant information through the 'results' string, as part of the plugin context.

**Comment by trel** [comment]
We will move forward with the following plan:

 - Stage 1 - Add `_except` PEPs to the [existing operation flow control](https://docs.irods.org/4.2.4/plugins/dynamic_policy_enforcement_points/#flow-control)

 - Stage 2 - Depending on demand and interesting use cases, add `_finally` PEPs (will create a new issue if this is decided to be a good idea)

<img src="https://user-images.githubusercontent.com/55238/46030712-eac98b00-c0c4-11e8-9661-5ad4d2b646aa.png" alt="proposed_flow_control" width="250"/>

**Comment by trel** [comment]
Merged.

We have not yet opened an issue for `_finally`.
