### ISSUE TITLE
packStruct not following XML encoding standards

### ISSUE THREAD

**Issue by alanking** [irods/irods#4132]
- [x] master
- [x] 4-2-stable
----------

### iRODS Version, OS and Version
4.2.4

### What did you try to do?
Register and get a file with a \` (backtick) in the name with an XML protocol-based client that is not icommands.

### Observed behavior (including steps to reproduce, if applicable)
Run the following python script with [PRC](https://github.com/irods/python-irodsclient):

`test_backtick.py`

```python
import os
from irods.session import iRODSSession
from irods.models import DataObject
try:
    env_file = os.environ['IRODS_ENVIRONMENT_FILE']
except KeyError:
    env_file = os.path.expanduser('~/.irods/irods_environment.json')

with iRODSSession(irods_env_file=env_file) as session:
    test_dir = '/tmp'
    filename = '''aaa`'"<&test&>"'`_file'''
    test_file = os.path.join(test_dir, filename)

    collection = '/tempZone/home/rods'
    obj_path = '{collection}/{filename}'.format(**locals())

    with open(test_file, 'wb') as f:
        f.write(bytes('test string', 'UTF-8'))

    session.data_objects.register(test_file, obj_path)

    obj = session.data_objects.get(obj_path)
    print('path:[{}]'.format(obj.path))

    os.remove(test_file)
```

Result:
```
$ python test_backtick.py
path:[/tempZone/home/rods/aaa''"<&test&>"''_file]
$ ils
/tempZone/home/rods:
  aaa`'"<&test&>"'`_file
```

As seen in the output, the path is not correct. This is because packStruct is encoding \` (backtick) with `&apos;`, which is for apostrophes:
https://github.com/irods/irods/blob/c946c024496bfd2dc51285c9599bd606c1fde8f6/lib/core/src/packStruct.cpp#L1346-L1350
When decoding this on the client side, PRC uses an XML-compliant decoder and interprets `&apos;` as an apostrophe. This works with icommands (with `$irodsProt` == 1) because icommands use the exact same packStruct logic.

We should leave the decoding so that older clients can remain compatible (`xmlStrToStr`) with future servers.

This was in the original code:
https://github.com/irods/irods-legacy/blob/9b6ae3b8a0168b3d322e0aa563b993010e4df88f/iRODS/lib/core/src/packStruct.c#L1463-L1472

**Comment by trel** [comment]
So...

- `strToXmlStr()` should arguably be changed to use `&grave;` on the way in...
and
- `xmlStrToStr()` should handle `&grave;` on the way out, and if talking to a certain age of server/client, also continue to incorrectly convert `&apos;` back to `.

**Comment by stsnel** [comment]
We have also observed encoding issues with data object names that contain other nonstandard characters: ASCII codes 01 through 08, 11, 12 and 14 through 31.

Uploading such files in iRODS using iput works as expected. However, iterating over the data objects in the Python-irodsclient results in an xml.etree.ElementTree.ParseError, because the characters are not encoded in XML.
