### ISSUE TITLE
load resource plugins only when needed

### ISSUE THREAD

**Issue by xu-hao** [irods/irods#4133]
## Feature

We are trying to run an S3 plugin. The plugin reads S3 credential files on initialization. irods loads the plugin on every server. However ,this is only needed for the host for the S3 resource. For hosts without the s3 credentials, it throws an error (https://github.com/heliumdatacommons/MVP-repo/issues/375)

Load resource plugins only when needed. Or specify initialization functions and other function. Initialization functinos are needed for initialization so the plugin writer can push host specific code in other functions that actually need them.

**Comment by jasoncoposky** [comment]
@xu-hao The Impostor resource is loaded in place of the resource plugin for servers which do not host the resource.  The reason the credentials are attempted to be loaded is that the S3 resource plugin must be installed on the server, but it does not have the associated credentials.

**Comment by xu-hao** [comment]
@jasoncoposky thanks for the answer. So we should not install s3 resource plugin where there is no credential?

**Comment by jasoncoposky** [comment]
@xu-hao That is correct, the resources live in the catalog which are read on every server for every agent.  If the plugin is configured in the catalog and available on disk the assumption is that it is to be loaded and initialized.  If it is not installed, we use an 'impostor' plugin which will simply vote to not service the request.  If you need a consistent image everywhere, the S3 plugin will need to be modified on initialization to do host name checks and only properly init when the host names match.

**Comment by HowardLander** [comment]
Jason: is there really no way to handle this issue at a layer above the 
individual drivers?

**Comment by xu-hao** [comment]
@jasoncoposky Thanks!

**Comment by jasoncoposky** [comment]
@HowardLander  - I don't know what you mean by 'individual drivers', per my comment above the impostor is installed if the plugin is not installed.  If the plugin is installed it is initialized.  The options are to not install it, or to modify the S3 plugin to do the host name checks.
