### ISSUE TITLE
Rebalance fails when child resource names are substrings of parent names

### ISSUE THREAD

**Issue by alanking** [irods/irods#4135]
- [x] master
- [x] 4-2-stable
------

### iRODS Version, OS and Version
4.2.4

### Observed behavior (including steps to reproduce, if applicable)
```
$ ilsresc
replroot:replication
└── newrepl:replication
    └── wrep:replication
        ├── ufs1:unixfilesystem
        └── ufs2:unixfilesystem
$ iput -R replroot boo
$ ils -L boo
  rods              0 replroot;newrepl;wrep;ufs2         2394 2018-10-03.10:10 & boo
        generic    /tmp/irods/ufs2vault/home/rods/boo
  rods              1 replroot;newrepl;wrep;ufs1         2394 2018-10-03.10:10 & boo
        generic    /tmp/irods/ufs1vault/home/rods/boo
$ itrim -N1 -n0 boo
Total size trimmed = 0.002 MB. Number of files trimmed = 1.
$ ils -L boo
  rods              1 replroot;newrepl;wrep;ufs1         2394 2018-10-03.10:10 & boo
        generic    /tmp/irods/ufs1vault/home/rods/boo
$ iadmin modresc replroot rebalance
remote addresses: xxx.xxx.xxx.xxx ERROR: rcGeneralAdmin failed with error -154000 SYS_INTERNAL_ERR
```
Different behavior occurs for different flavors of hierarchy. Will fill in details later when a table of scenarios can be generated. It's also possible that this is not an issue specific to replication resources but hierarchy resolution in general.

**Comment by JustinKyleJames** [comment]
This is not just an issue with parent/child.  It is an issue if one standalone resource is a substring of another standalone resource.  For example, if you put a file on myresc1 and then try to replicate it to resc1 the system thinks there is already a good replica on resc1.

**Comment by JustinKyleJames** [comment]
I believe the issue I ran into was caused by this line.

https://github.com/irods/irods/blob/99ccfd2a9a29968b1e24ea2f4899c10a858d2205/server/core/src/dataObjOpr.cpp#L856
