### ISSUE TITLE
implement fallthrough for rule engine plugin framework operations

### ISSUE THREAD

**Issue by trel** [irods/irods#4147]
- [x] master
- [x] 4-2-stable

-----

### iRODS Version, OS and Version
4.2.4

### What did you try to do?

Deploy new C++ rule engine plugin at the 'top' of the `rule_engines` object in `server_config.json` which responds with `SYS_NOT_SUPPORTED` to a given operation.

### Expected behavior

Fallthrough to next rule engine plugin for that operation.

### Observed behavior (including steps to reproduce, if applicable)

Hard stop as soon as `SYS_NOT_SUPPORTED` is observed.

**Comment by alanking** [comment]
Extend functionality to `exec_rule_text` and `exec_rule_expression`

**Comment by trel** [comment]
nope, can't change shipped milestones.  changing back and closing - please open a separate issue for this work.
