### ISSUE TITLE
support policy continuation for a successful PEP

### ISSUE THREAD

**Issue by trel** [irods/irods#4148]
- [x] master
- [x] 4-2-stable

----

## Feature

- [x] Add new positive return code (`RULE_ENGINE_CONTINUE`) (or state) to signal to REPF that it should continue for additional matching policy operations.

    This would be used by a rule engine plugin PEP that satisfies the request, but also expects other rule engine plugins to be able to respond to the PEP request as well.

    This is complementary to #4147 (fallthrough behavior for `SYS_NOT_SUPPORTED`).

- [x] Add state codes to `irods_state_table.h` with NEW_STATE() macro

**Comment by xu-hao** [comment]
These two use cases can be unified in a continuation-passing style implementation.

**Comment by trel** [comment]
@xu-hao, we're going to go with a new return code from plugins, rather than a continue flag within the REPF.

**Comment by xu-hao** [comment]
@trel that's fine by me. I was just making a suggestion.

**Comment by trel** [comment]
No worries - thanks.
