### ISSUE TITLE
msiGetMoreRows and msiGetContInxFromGenQueryOut can return continueIndex=1 when it should be 0

### ISSUE THREAD

**Issue by dworkin** [irods/irods#4157]
- [x] master
- [x] 4-2-stable
-------

## Bug Report

When the number of results in a query is larger than 0 and a multiple of the batch size (normally 256), `continueIndex` will be returned as 1 for the last batch (`msiGetContInxFromGenQueryOut` or a previous `msiGetMoreRows` call), but `msiGetMoreRows` will throw `CAT_NO_ROWS_FOUND` when called after.

### iRODS Version, OS and Version

iRODS 4.2.4, Centos 7.5

### What did you try to do?

```
# as user irods, ipwd = $rodsZoneClient/home/rods
imkdir foo
icd foo
i=0
while [ $i -lt 256 ]
do
    i=`expr $i + 1`
    iput /var/lib/irods/VERSION.json bar$i.json
done
irule 'msiMakeGenQuery("DATA_NAME", "COLL_NAME = '"'/\$rodsZoneClient/home/rods/foo'"'", *query); msiExecGenQuery(*query, *result); *oldIndex=1; msiGetContInxFromGenQueryOut(*result, *index); while (*oldIndex > 0) { *oldIndex=*index; msiGetMoreRows(*query, *result, *index); }' null ruleExecOut
```
### Expected behavior

I did not expect `CAT_NO_ROWS_FOUND` to be thrown.

### Observed behavior (including steps to reproduce, if applicable)

`CAT_NO_ROWS_FOUND` was thrown.

**Comment by trel** [comment]
Another fencepost!

So the expected behavior is rather that `continueIndex` should be smart enough to know there is nothing left and return `0`.

**Comment by d-w-moore** [comment]
Felix (and Ton),
  We'll be looking to solve to this issue forthwith, but in the meantime the solution to the above would likely
be to  - 
   1) surround `msiGetMoreRows(..)` with `errorcode` to trap the error conditions and compare the code returned with CAT_NO_ROWS_FOUND(-808000). So above given example would look like this:
```
# ...
while (*oldIndex > 0) { *oldIndex=*index; 
  *err=errorcode(msiGetMoreRows(*query, *result, *index));
  if (abs(*err) == 808000) { break } # CAT_NO_ROWS_FOUND
}
```      
   2) Or use Language Integrated General Query syntax, which circumvents the problem in question:
```
foreach (*row in select DATA_NAME where COLL_NAME = '/*myZone/home/rods/foo') {
    writeLine('stdout', ' row => ' ++ *row.DATA_NAME)
 }
#...
INPUT *myZone=$"tempZone"
OUTPUT ruleExecOut
```
Similar methods can help if you are using [general queries](https://github.com/irods/python-irodsclient#general-queries) under the python rods client or, as the case may be, by availing oneself of the iterator provided by this upcoming [genquery](https://github.com/irods/irods_rule_engine_plugin_python/pull/14) module if one is writing rule code under the Python RE plugin.

-Dan
[To: @dworkin  @tsmeele ]

**Comment by trel** [comment]
need to repave `rei->status = 0` inside the if statement...
https://github.com/irods/irods/blob/4-2-stable/server/re/src/genQueryMS.cpp#L356

**Comment by d-w-moore** [comment]
I've run our 'repave' above and it passes CI. I've also rewritten the Python GenQuery iterator to accommodate it, and will test that today.
