### ISSUE TITLE
present iRODS error codes to the native rule language namespace

### ISSUE THREAD

**Issue by trel** [irods/irods#4174]
- [x] master
- [x] 4-2-stable
------

## Feature

The iRODS state codes are well named and yet these names are not available within the rule language.

The values of these codes must currently be used directly.

A rule developer should be able to return `SYS_NOT_SUPPORTED` rather than the value defined in `rodsErrorTable.h`.

**Comment by trel** [comment]
@tempoz we'll need to do the same in the PREP.   Issue should be created there as well.

**Comment by xu-hao** [comment]
@trel this can be done easily through a rule base. what do you suggest we name the rule base?

**Comment by xu-hao** [comment]
how about `error`?
