### ISSUE TITLE
itrim exits with succces when it fails to delete a replicate because of replicate count

### ISSUE THREAD

**Issue by keithj** [irods/irods#4188]
irods-icommands 4.1.11

I have a data object with 2 replicates, numbered `0` and `1`. I run  `itrim -n 1 /path/to/data/object`.

What I expect:

`itrim` to exit with an error message and non-zero exit code. The error message to say that it failed to
delete the replicate because the operation would take the total number of replicates below the minimum threshold (in this case the default of 2).

What happens:

`itrim` exits with code `0` and no warning or error messages. It does not delete the replicate.

**Comment by alanking** [comment]
This is fixed as of resolution of 4.2.3 (see #3615):
```
$ ils -l
/tempZone/home/rods:
  rods              0 ufs0         1024 2019-10-02.15:54 & foo
  rods              1 ufs1         1024 2019-10-02.15:55 & foo
$ itrim -n1 foo
remote addresses: 172.17.0.3 ERROR: trimUtil: trim error for /tempZone/home/rods/foo.  status = -402000 USER_INCOMPATIBLE_PARAMS
Total size trimmed = 0.000 MB. Number of files trimmed = 0.
```
