### ISSUE TITLE
Data readable from zero-sized data object

### ISSUE THREAD

**Issue by keithj** [irods/irods#4195]
- [x] master
- [x] 4-2-stable
------

### iRODS Version, OS and Version

4.1.12, Ubuntu Xenial, Ubuntu Precise

### What did you try to do?

Fetch data from a data object having zero size using an

`rcDataObjOpen`, `rcDataObjRead` x n,  `rcDataObjClose`

sequence (C API).

### Expected behavior

1. The data stream should contain zero readable bytes because the IES is canon and says the file has zero bytes.

2. Using another part of the API (the `get` call) will return an empty file, so the two parts of the API are inconsistent in their behaviour. I think that the `get` API is correct because of 1.

### Observed behavior (including steps to reproduce, if applicable)

`rcDataObjOpen`, `rcDataObjRead` x n,  `rcDataObjClose` returned data. The data object is probably in this state due to https://github.com/irods/irods/issues/4170

**Comment by trel** [comment]
How are you confirming you're reading the 'expected' replica?

We have to trust the catalog.  #4170 is about making sure the catalog is correct.

**Comment by keithj** [comment]
This data object has this state:

````
  srpipe            0 root;replicate;seq-red;red3;irods-seq-i16-fg            0 2018-11-24.12:06 & GA20000_fast5_2018-11-22T141103.64.tar
    91bb8a20667a5b2d81e960c54a307c0a    generic    /irods-seq-i16-fg/ont/gridion/GXB01179/48/GA20000/GA20000_fast5_2018-11-22T141103.64.tar
  srpipe            1 root;replicate;seq-green;green2;irods-seq-sr02-ddn-rd10-33-34-35            0 2018-11-26.12:44 & GA20000_fast5_2018-11-22T141103.64.tar
    d41d8cd98f00b204e9800998ecf8427e    generic    /irods-seq-sr02-ddn-rd10-33-34-35/ont/gridion/GXB01179/48/GA20000/GA20000_fast5_2018-11-22T141103.64.tar
````

Both are zero size in the catalog and both are marked as current (the checksums were not there immediately after loading - I ran `ichksum` subsequently).

Whichever replicate I read, I should get zero bytes, if the catalog is to be believed.

**Comment by trel** [comment]
I see - yes, we should honor the catalog - and I agree that in this case, we should read only 0 bytes upon request.

Having a correct catalog, of course, is primary :)

**Comment by alanking** [comment]
The following demonstrates the behavior and will likely serve as the test for the resolution of this issue:

```
$ echo "justindidit" > file.txt
$ iput file.txt foo
$ ils -l foo
  rods              0 demoResc           12 2020-03-04.14:16 & foo
$ iget foo -
justindidit
$ iadmin modrepl logical_path /tempZone/home/rods/foo replica_number 0 DATA_SIZE 0
$ ils -l foo
  rods              0 demoResc            0 2020-03-04.14:16 & foo
$ iget foo -
$ istream read foo
justindidit
```

**Comment by alanking** [comment]
I cannot checkbox this but I believe this is done in both major branches.
