### ISSUE TITLE
iinit --ttl parameter overflow

### ISSUE THREAD

**Issue by kuntzagk** [irods/irods#4198]
Accidentally I found that iinit --ttl parameter should not be higher then 336:

```
[user@irods_client ~]$ iinit --ttl 336
Enter your current PAM password:
[user@irods_client ~]$ ils
/myZone:
  C- /myZone/Directory
  C- /myZone/home
  C- /myZone/test
  C- /myZone/trash
[user@irods_client ~]$ iinit --ttl 337
Enter your current PAM password:
Enter your current iRODS password:
[user@irods_client ~]$ ils
[-]     /tmp/tmpkfeEjV/plugins/auth/native/libnative.cpp:342:irods::error native_auth_client_response(irods::plugin_context &, rcComm_t *) :  status [CAT_INVALID_AUTHENTICATION]  errno [] -- message [Call to rcAuthResponseFailed.]
```

 failed with error `-826000 CAT_INVALID_AUTHENTICATION`

```
$ rpm -q irods-icommands
irods-icommands-4.2.4-1.x86_64
```

**Comment by alanking** [comment]
`pam_password_max_time` has a maximum value of 1209600 (seconds) by default. The value passed to `--ttl` is in hours. 336 hours * 3600 seconds/hour = 1209600 seconds. Anything above that will exceed the maximum default value.

If you can, are you able to see in the logs where authentication may have failed (e.g. "invalid ttl", "failed updating iRODS pam password")? If you change `pam_password_max_time` in the server_config, does the maximum value of `--ttl` also increase?

If so, this is working as expected. Regardless, perhaps we should have a better error message for the user to indicate that authentication failed in this case?

**Comment by trel** [comment]
Just for context:

```
$ iinit -h --ttl
When using regular iRODS passwords you can use --ttl (Time To Live)
to request a credential (a temporary password) that will be valid
for only the number of hours you specify (up to a limit set by the
administrator).  This is more secure, as this temporary password
(not your permanent one) will be stored in the obfuscated
credential file (.irodsA) for use by the other iCommands.

When using PAM, iinit always generates a temporary iRODS password
for use by the other iCommands, using a time-limit set by the
administrator (usually a few days).  With the --ttl option, you can
specify how long this derived password will be valid, within the
limits set by the administrator.
```

**Comment by alanking** [comment]
I think that this may be fixed in 4.3.1. See https://github.com/irods/irods/issues/7274

**Comment by korydraughn** [comment]
Please confirm, update, and close if resolved.

**Comment by alanking** [comment]
Found a test for this:
https://github.com/irods/irods/blob/690ffe58ab6a61766dc5824f313247b3e376f5f7/scripts/irods/test/test_pam_password_authentication.py#L206-L238

The test sets the `password_max_time` and tries to use a `--ttl` value that is greater than that value. An error message now comes back instead of showing the password prompt for native authentication. A similar test was implemented for native authentication.
