### ISSUE TITLE
Open unixfilesystem with O_TRUNC seems to give me an invalid file descriptor

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods#4225]
## Bug Report

When I execute the following rule with a unixfilesystem resource, it gives me a bad file descriptor error on the line where it attempts to write "ABC".

```
myTestRule {

   *obj1='/tempZone/home/rods/foo1'
   *resc1='demoResc'
   *create_flags1='destRescName=*resc1++++forceFlag='
   *open_flags1='objPath=*obj1++++rescName=*resc1++++openFlags=O_TRUNC++++replNum=0'

   msiDataObjCreate(*obj1,*create_flags1,*fd1);
   writeLine("stdout", "fd1=*fd1");
   msiDataObjWrite(*fd1,'12345678901234567890', 20);
   msiDataObjClose(*fd1, *status);

   msiDataObjOpen(*open_flags1, *fd1);
   writeLine("stdout", "fd1=*fd1");
   msiDataObjWrite(*fd1,'ABC', *len);
   msiDataObjClose(*fd1, *status);

} 
OUTPUT ruleExecOut

```
Note that this worked as expected with a cacheless S3 resource so I don't believe it is a problem with the microservices themselves.

### iRODS Version, OS and Version

This was tested on iRODS 4.2.5 on Ubuntu 14.04.

### What did you try to do?

See above

### Expected behavior

I would have expected the file to be truncated and "ABC" written to it.  The final contents of foo1 should be "ABC".

### Observed behavior (including steps to reproduce, if applicable)

The following error is generated.

```
$ irule -F doit3.r
remote addresses: 127.0.0.1 ERROR: rcExecMyRule error.  status = -513009 UNIX_FILE_WRITE_ERR, Bad file descriptor
Level 0: DEBUG: execMicroService3: error when executing microservice
line 14, col 3
   msiDataObjWrite(*fd1,'ABC', 3);
   ^

caused by: DEBUG: msiDataObjWrite: rsDataObjWrite failed, status = -513009
```

**Comment by korydraughn** [comment]
The failure is due to the `openFlags`.  Specifying just `O_TRUNC` is equivalent to `O_RDONLY | O_TRUNC`. The test works when including a write mode.

The issue becomes clear with the merging of #4782. 

Closing.
