### ISSUE TITLE
db_move_object_op uses incorrect ID for permission query

### ISSUE THREAD

**Issue by jasoncoposky** [irods/irods#4229]
The query here binds the object ID but the query itself references the coll_id, which yields CAT_NO_ROWS_FOUND.

https://github.com/irods/irods/blob/master/plugins/database/src/db_plugin.cpp#L11633

An audit of the rest of the operation would be suggested.

**Comment by trel** [comment]
Jan 2, 2019 says the timestamp... so...

https://github.com/irods/irods/blob/0031ad6c7fdfe993c745d9b7ae9b47319d4e2323/plugins/database/src/db_plugin.cpp#L11633

**Comment by korydraughn** [comment]
Maybe, but the logic appears to be correct to me. The variable says `objIdString`, but it is a copy of `_target_coll_id`. The copy operation happens just a few lines above.
https://github.com/irods/irods/blob/0031ad6c7fdfe993c745d9b7ae9b47319d4e2323/plugins/database/src/db_plugin.cpp#L11627
If the value of `_target_coll_id` is a collection id, then the SQL checks out.

**Comment by trel** [comment]
okay, if we cannot understand the bug report as is, I think we close it for now.

**Comment by korydraughn** [comment]
I agree.
