### ISSUE TITLE
Simultaneous msiDataObjRepl and msiDataObjRename can cause inconsistencies

### ISSUE THREAD

**Issue by dworkin** [irods/irods#4236]
- [x] master
- [x] 4-2-stable
----------

### iRODS Version, OS and Version

iRODS 4.2.4, CentOS 7.3

### What did you try to do?

We use delayed rules to create replications. When the dataobj being replicated is renamed by msiDataObjRename at the same time (in our tests we typically rename a dataobj, then rename it once more to back to the original) we see inconsistencies appear in the database, typically two different revisions that refer to the same file.

It appears that msiDataObjRename does not do sufficient locking and/or rollback in the various stages of its execution.

### Observed behavior (including steps to reproduce, if applicable)

```
/tempZone/home/research-mdtestvault:
  functionalad      0 irodsResc;dev001;dev001_p2;dev001_2         3653 2018-12-05.02:47 & yoda-metadata.xml
        generic    /var/lib/irods/Vault1_2/home/research-mdtestvault/yoda-metadata.xml
  functionalad      1 irodsRescRepl;dev002;dev002_p1;dev002_1         3653 2018-12-05.14:05 & yoda-metadata.xml
        generic    /var/lib/irods/Vault2_1/home/research-mdtestvault/yoda-metadata.xml
  functionalad      2 irodsRescRepl;dev002;dev002_p2;dev002_2         3571 2018-12-05.02:23   yoda-metadata.xml
        generic    /var/lib/irods/Vault2_2/home/research-mdtestvault/yoda-metadata.xml
  functionalad      3 irodsRescRepl;dev002;dev002_p1;dev002_1         3653 2018-12-05.14:05 & yoda-metadata.xml
        generic    /var/lib/irods/Vault2_1/home/research-mdtestvault/yoda-metadata.xml
```

Here, revisions 1 and 3 refer to the same file.

**Comment by alanking** [comment]
DataObjRename should be modified such that a locked data object cannot be renamed.

**Comment by alanking** [comment]
Leaving a note here that if the replications are asynchronous, logical locking will only protect as long as the replica is being written to. The same applies to synchronous replication via the replication resource. In this case, the lock will need to be maintained over the entire operation, including the `fileModified` event which triggers the synchronous replication. In any case, disallowing renames on locked data objects is a critical first step.

**Comment by alanking** [comment]
Changes made for #5589 actually resolves this. Forgot to tag in the commit message.

**Comment by trel** [comment]
that's only for master so far... still awaiting the 4-2-stable commit(s)

**Comment by trel** [comment]
checkboxed
