### ISSUE TITLE
Run iCAT as foreground process

### ISSUE THREAD

**Issue by paulspeijers** [irods/irods#4238]
## Feature
We would like to run iCAT as a foreground process within Docker as part of our Kubernetes cluster. How can I do that? If not possible, could you change the software so I can do this more easily?

One of the prerequisites for Docker is that each container runs a single process in the foreground. That way, Kubernetes can determine the state of the process and act appropriately which improves robustness. For instance, it can restart the container when it has been stopped or killed, or scale up or down when necessary.

Currently, without Docker, we run iRODS as a service as follows:
/etc/rc.d/init.d/irods, which calls
/var/lib/irods/irodsctl, which calls
/var/lib/irods/scripts/irods_control.py, which spawns a background process for iCAT.

I could break into irods_control.py and trigger the function that runs in the background myself, but then I would miss all the error handling and other functionality offered by the other scripts. So, I'd rather not break into this black box.

Edit currently and formerly published or archived collections
Update web portal frameworks and libraries

### iRODS Version, OS and Version
iRODS 4.2.2, CentOS 7.6

**Comment by paulspeijers** [comment]
Hi @trel. Thanks for your suggestion. We will give it a go, and we will let you know.
Does the same command also apply to the iRODS resource servers?

**Comment by trel** [comment]
I hope/expect so - it's the same codepath to launch, and from there the server checks its config and picks a different role (consumer).

**Comment by bramru** [comment]
Hi @trel , i'm working together with Paul on this.

Proposed solution does not seem to work in our case. Please find below the steps we have performed and the problem we run into. Do you have any suggestions to get this working?

Our goal is to run the actual irodsServer as the main process in a container based on CentOS (using RPM) We have this working if we use the standard: /var/lib/irodsctrl start and then either use: sleep or tail to stop container execution from finishing.

If in the same container I start this irodsServer directly in the /usr/sbin folder. (with irods user) 
It seems like it's working. But if i connect to irods i get the following error:

`Enter your current iRODS password:[-] 
/tmp/tmp0dyJrt/plugins/auth/native/libnative.cpp:342:irods::error native_auth_client_response(irods::plugin_context &,
rcComm_t *) :  status [CAT_INVALID_AUTHENTICATION]  errno [] -- message [Call to rcAuthResponseFailed.]
 
 failed with error -826000 CAT_INVALID_AUTHENTICATION
`

If I start the irodsServer with -uV options,I see it complains about missing quite a bit:
`sh-4.2$ /sbin/irodsServer -uV
Feb  1 12:38:18 pid:22 NOTICE: Agent factory process pid = [23]
Feb  1 12:38:18 pid:22 DEBUG: config file found [/etc/irods/server_config.json]
Feb  1 12:38:18 pid:23 DEBUG: config file found [/etc/irods/server_config.json]
Feb  1 12:38:18 pid:22 DEBUG: xmsg_host is not defined
Feb  1 12:38:18 pid:22 DEBUG: irods_authentication_scheme is not defined
Feb  1 12:38:18 pid:22 DEBUG: xmsg_port is not defined
Feb  1 12:38:18 pid:22 DEBUG: irods_debug is not defined
Feb  1 12:38:18 pid:22 DEBUG: irods_log_level is not defined
Feb  1 12:38:18 pid:22 DEBUG: irods_authentication_file is not defined
Feb  1 12:38:18 pid:22 DEBUG: irods_ssl_ca_certificate_path is not defined
Feb  1 12:38:18 pid:22 DEBUG: irods_plugins_home is not defined
Feb  1 12:38:18 pid:22 DEBUG: captured env [irods_zone_name]-[rdmtst]
Feb  1 12:38:18 pid:22 DEBUG: resolved plugin home [/usr/lib/irods/plugins/rule_engines/]
Feb  1 12:38:18 pid:22 DEBUG: load_plugin - calling plugin_factory() in [/usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-irods_rule_language.so
]
Feb  1 12:38:18 pid:22 DEBUG: load_plugin - loaded [irods_rule_engine_plugin-irods_rule_language]
Feb  1 12:38:18 pid:22 DEBUG: xmsg_host is not defined`

My guess is the python code starting the irodsServer in irodsctl does some work to setup the environment. 
Thanks for your help!

**Comment by trel** [comment]
Well, that is a bit noisy, but I think it's working (our `-V` options have always been lower priority fixes)...

I've just been able to stand up the resource server via `./irodsServer -uV` and connect both to it and the provider, manually.

There could be some ENV shenanigans at the Docker layer, definitely.

**Comment by bramru** [comment]
Had some time today, so I tried the same in a VM without docker.
The same result as running in a docker container unfortunately.
@trel  Are you trying this in CentOS 7 as well?

If im running iRODS with systemd it runs fine. I can also connect to iRODS.

If I run it in the foreground the daemon seems to start fine:

```
[root@centos7a sbin]# su - irods -c 'cd /usr/sbin; ./irodsServer -u'
Feb  3 17:32:36 pid:5647 NOTICE: Agent factory process pid = [5648]
    LocalHostName:  localhost, centos7a.bram.local, Port Num: 1247.

Zone Info:
    ZoneName: testZone   Type: LOCAL_ICAT    HostAddr: localhost   PortNum: 1247

reHost:   localhost

Feb  3 17:32:36 pid:5647 NOTICE: rodsServer Release version rods4.2.2 - API Version d is up
Feb  3 17:32:36 pid:5650 NOTICE: Starting irodsReServer
Feb  3 17:32:36 pid:5647 NOTICE: >>> control plane :: listening on port 1248
```

Then if try to connect I get the same error as in the docker container.

```
[root@centos7a scripts]# ils
 ERROR: _rcConnect: connectToRhost error, server on localhost:1247 is probably down status = -305111 USER_SOCK_CONNECT_ERR, Connection refused
[root@centos7a scripts]# ils
[-]	/tmp/tmp0dyJrt/plugins/auth/native/libnative.cpp:342:irods::error native_auth_client_response(irods::plugin_context &, rcComm_t *) :  status [CAT_INVALID_AUTHENTICATION]  errno [] -- message [Call to rcAuthResponseFailed.]

 failed with error -826000 CAT_INVALID_AUTHENTICATION
[root@centos7a scripts]# ils
[-]	/tmp/tmp0dyJrt/plugins/auth/native/libnative.cpp:342:irods::error native_auth_client_response(irods::plugin_context &, rcComm_t *) :  status [CAT_INVALID_AUTHENTICATION]  errno [] -- message [Call to rcAuthResponseFailed.]

 failed with error -826000 CAT_INVALID_AUTHENTICATION
```

**Comment by trel** [comment]
Yes, I was able to get this to work in CentOS7, with a non-standard user/password rodsadmin account...

```
[root@c8e251ce6841 ~]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 

[root@c8e251ce6841 ~]# su - irods -c 'ienv | grep user'
irods_user_name - bobby

[root@c8e251ce6841 ~]# su - irods -c 'cd /usr/sbin; ./irodsServer -u'
Feb  5 02:42:33 pid:1229 NOTICE: Agent factory process pid = [1230]
    LocalHostName:  localhost, c8e251ce6841, Port Num: 1247.

Zone Info:
    ZoneName: tempZone   Type: LOCAL_ICAT    HostAddr: X.X.X.X   PortNum: 1247

reHost:   X.X.X.X

Feb  5 02:42:33 pid:1229 NOTICE: rodsServer Release version rods4.2.4 - API Version d is up
Feb  5 02:42:33 pid:1229 NOTICE: >>> control plane :: listening on port 1248
```

Your `CAT_INVALID_AUTHENTICATION` error means that the server came up, but not authenticating correctly to the catalog provider.

Can you connect to the provider with just the iCommands on that consumer docker container?  That will allow you to confirm the authentication is working without worrying about a second (consumer) server.

**Comment by bramru** [comment]
@trel, thanks for your help.
Together with a colleague i figured out the problem.

If you start the irods server directly the environment variable: IRODS_DATABASE_USER_PASSWORD_SALT was not set for the irods user.

This meant that the irods could not calculate password hashes correctly and thus i got: CAT_INVALID_AUTHENTICATION

If i set the IRODS_DATABASE_USER_PASSWORD_SALT i can login and run the other icommands.

**Comment by trel** [comment]
Ah, nice find.

If there is nothing actionable here, we can close this issue?

**Comment by bramru** [comment]
Are there more of these kind of environment variables that the irodsctl python script normally handles for the irodsServer?

**Comment by trel** [comment]
Yes, but no, not the python script.

The server itself is the one checking those variables.  All the environment variables available in `irods_environment.json` can also be set via shell environment variables:

https://docs.irods.org/4.2.4/system_overview/configuration/#irodsirods_environmentjson

>Other individual environment variables can be set by using the UPPERCASE versions of the variables named above, for example:
> 
> export IRODS_LOG_LEVEL=7
