### ISSUE TITLE
Enable iCAT logging to system out

### ISSUE THREAD

**Issue by paulspeijers** [irods/irods#4239]
## Feature
We would like to have iCAT logging to system out (and/or system err), as well as to the files it logs to currently.

We would like to run iCAT within a Docker as part of our Kubernetes cluster. Kubernetes supports all presentation, rotation and a lot of other functionality of logging to system out and system err by default.

It would be good when all kind of logging, from rodsLog, reLog and rodsServerLog would be outputted to the System out. 

We would still like iCAT to log to the log files as well, because we're using Filebeat to scan the logfiles, parse them using LogStash and output them to Elastic Search.

### iRODS Version, OS and Version
iRODS 4.2.2, CentOS 7.6

**Comment by trel** [comment]
This is a very reasonable request - thanks for bringing it up.

However, we're not planning to touch the logging system for 4.2.x at this time.

With the overhaul of the logging system for 4.3, this will just be a syslog configuration and should be very easy to manipulate, outside of the iRODS server config itself.

**Comment by korydraughn** [comment]
Now that #4474 has been merged into master (4.3), I believe this can be closed.

The changes in that PR provide options for writing to stdout. However, doing so will stop iRODS from writing to rsyslog (these options are mutually exclusive).
