### ISSUE TITLE
Document REBALANCE_ALREADY_ACTIVE_ON_RESOURCE behaviour

### ISSUE THREAD

**Issue by bh9** [irods/irods#4254]
- [x] irods_docs master
- [x] irods_docs 4-2-stable
- [x] irods_client_icommands master
- [x] irods_client_icommands 4-2-stable
-------

The rebalance_operation AVU that is set on rebalance start and removed on rebalance finish should be documented and should probably be in the `iadmin` manpage.

**Comment by trel** [comment]
Ah, very good - will do.

This work was done for https://github.com/irods/irods/issues/3683 and is already visible in the commit message https://github.com/irods/irods/commit/49215d3ba303fa1cbcc81caf062bd315938f1b30
