### ISSUE TITLE
Remote microservice does not error correctly with invalid hostname

### ISSUE THREAD

**Issue by alanking** [irods/irods#4260]
- [x] main
- [x] 4-2-stable
---
### iRODS Version, OS and Version
master

### What did you try to do?
```
#my_rule.r
my_rule {
    remote("badhostname", "<ZONE>tempZone</ZONE>") {
        writeLine("stdout", "Remote block");
    }
}
INPUT null
OUTPUT ruleExecOut
```

### Expected behavior
```
$ irule -F my_rule.r 
remote addresses: 172.17.0.3 ERROR: rcExecMyRule error.  status = -303000 USER_RODS_HOSTNAME_ERR
```

### Observed behavior (including steps to reproduce, if applicable)
```
$ irule -F my_rule.r
Remote block
```
In the rodsLog:
```
Feb  8 21:53:56 pid:168 remote addresses: 127.0.0.1, 172.17.0.3 ERROR: getaddrinfo_with_retry address resolution timeout [nonexistent-host] [ai_flags: [2] ai_family: [0] ai_socktype: [0] ai_protocol: [0]]
Feb  8 21:53:56 pid:168 remote addresses: 127.0.0.1, 172.17.0.3 ERROR: [-]      /irods/server/core/src/rodsConnect.cpp:138:rodsServerHost_t *mkServerHost(char *, char *) :  status [SYS_GET_HOSTNAME_ERR]  errno [] -- message [queueAddr failed]

Feb  8 21:53:56 pid:168 remote addresses: 127.0.0.1, 172.17.0.3 ERROR: resolveHost: mkServerHost error
```

**Comment by alanking** [comment]
Changing expected behavior to:
```bash
$ irule -F my_rule.r 
remote addresses: 172.17.0.3 ERROR: rcExecMyRule error.  status = -17000 SYS_GET_HOSTNAME_ERR
```

**Comment by trel** [comment]
only thing better might be to print out the bad hostname that was attempted?     not critical.

**Comment by alanking** [comment]
As it turns out, the error code returned nowadays is actually `SYS_INVALID_SERVER_HOST`, so that seems appropriate as well.

We can add the hostname to the rError stack. Here's what I've got with my current test...
```
Assert Command: irule -r irods_rule_engine_plugin-irods_rule_language-instance -F /tmp/irods-testing-ov7y9g7f/test_remote_returns_appropriate_error_on_bad_hostname__issue_4260.r
Expecting STDERR: ['SYS_INVALID_SERVER_HOST']
  stdout:
    | Level 0: DEBUG:
    |
  stderr:
    | remote addresses: 172.24.0.3 ERROR: rcExecMyRule error.  status = -21000 SYS_INVALID_SERVER_HOST
Output found
```
We can add something to the effect of:
```
Failed to resolve hostname: [badhostname]
```
Does that seem good?

If I don't target the rule engine plugin instance, no error is returned and it fails silently (I think that's expected... @korydraughn?).

**Comment by korydraughn** [comment]
yes. that is expected.

**Comment by korydraughn** [comment]
an error code should appear in log file, but that may depend on the log level (and log category for 4.3).

**Comment by trel** [comment]
> Failed to resolve hostname: [badhostname]

yes please, if easy.  could help some poor soul who's doing multiple remote calls in the same rule...

**Comment by alanking** [comment]
Okay, so should we move this to the 4.2.12 milestone?

**Comment by trel** [comment]
yes, please.
