### ISSUE TITLE
Having at least 256 rules in the queue prevents new rules from being processed

### ISSUE THREAD

**Issue by tedgin** [irods/irods#4266]
- [x] master
- [x] 4-2-stable
------

### iRODS Version, OS and Version

iRODS Version 4.1.10, CentOS 6.

### What did you try to do?

I have a rule queue with 256 rules to be scheduled to execute tomorrow at 1 am.  A user performs a task that generates a delayed rule that should execute as soon as possible.  

### Expected behavior

I expect the new delayed rule generated by the user's task to execute before the 256 existing rules.

### Observed behavior (including steps to reproduce, if applicable)

Nothing happens until the next day at 1 am.  At that time the 256 rules executed followed by the user's rule.

This happens because the irodsReServer pulls the first `MAX_SQL_ROWS` (256) rules from the ICAT.  The query that selects the rules sorts them by `rule_exec_id`.  Since Ids are generated in increasing order, this means that the 256 oldest rules (by create time) are returned even if none of them will be executed. This prevents delayed rules that could be executed now from being processed.

The example I give is contrived.  My real example that I actually experienced is a little more complicated.  I had 200k rules queued up from over the previous week that all send requests to a remote service. The service was having issues, hence the rule pile up.  Interspersed in the queue were several hundred rules unrelated to this service.  All but two rules were scheduled to executed 1 second after creation. The maintainer of the service took it down for maintenance. Instead of having all of the service related rules fail, I set their execution time to be 1 hour after the scheduled end of the maintenance time. I expected the remaining several hundred rules to be begin to be executed, but they weren't. irodsReServer would check the queue every 30 seconds and find no rules it could execute.

**Comment by trel** [comment]
Confirmed.

This is related to https://github.com/irods/irods/issues/3782 and https://github.com/irods/irods/issues/4250.

We are actively refactoring the irodsReServer for 4-2-stable and 4.3.0 (https://github.com/irods/irods/issues/4251) and this issue has already been fixed under bench testing.
