### ISSUE TITLE
The writeLine microservice does not handle "stdout" and "stderr" properly

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#4279]
- [x] master
- [x] 4-2-stable

When writeLine is given **stdout** or **stderr**, it tries to append the message to a buffer within the request.  This is a problem if the request does not originate from a real client (e.g. rule execution server).

Instead, writeLine should send the message to the log when handling requests that do not come from real clients.

**Comment by alanking** [comment]
Related to #4018?
