### ISSUE TITLE
Document output of ils

### ISSUE THREAD

**Issue by kript** [irods/irods#4305]
- [x] master
- [x] 4-2-stable
----------

## Feature

Please document the results of the `ils -l` and `ils -L` options, and what the fields mean. 
Related to #2384 #2385 #2840

### iRODS Version, OS and Version

iRODS 4.1.12 (icommands in this case)
Ubuntu 12.04

### What did you try to do?

Look at [iRODS Documentation](https://docs.irods.org/4.1.12/icommands/user/#ils)

### Expected behavior

Something like (but better!);

> Row 1:
> Owner
 >Replica number (this is an integer that bears no relation to the actual number of replicas, it’s just a unique reference for the replica no of an object)
> Compound Resource Path ( replicas are stored in resources, resources are stored in ‘trees’, which are DAG’s)
> Replica size 
> Date stamp of last modification 
> & - this is only present if the replica is an up to date or good copy. [1]
> Filename
> Row 2: (present with -L)
> Checksum (where it comes from, why it might not be present, or link to same in docs elsewhere)
> Generic – ???
> Path to the replica of the object on the underlying filesystem that makes up the resource within iRODS.

### Observed behavior (including steps to reproduce, if applicable)

> -l  long format
> -L  very long format

**Comment by trel** [comment]
definitely getting this updated as part of the intermediate replicas and logical locking work.
