### ISSUE TITLE
new api plugin - create proxy data object

### ISSUE THREAD

**Issue by trel** [irods/irods#4332]
## Feature

Create new api plugin to create a proxy data object that has not yet been registered in the catalog, and return a valid file descriptor, to be used for holding an in-flight data transfer.

**Comment by trel** [comment]
to be used with #4331

**Comment by korydraughn** [comment]
This looks like it isn't needed anymore.

Can this be closed?

**Comment by trel** [comment]
awaiting word/resolution on #4331

**Comment by korydraughn** [comment]
this can be closed now?

**Comment by alanking** [comment]
I think we ended up going in a different direction for this, yeah

**Comment by trel** [comment]
agreed.    labels/milestone/close.
