### ISSUE TITLE
Remove audit trails

### ISSUE THREAD

**Issue by alanking** [irods/irods#4337]
- [x] master
---
This has been replaced by the Audit Rule Engine Plugin: https://github.com/irods/irods_rule_engine_plugin_audit_amqp

**Comment by alanking** [comment]
All instances of "audit" that I see in a grep are related to `R_OBJT_AUDIT` and so are immaterial, as far as I can tell.

@trel or @korydraughn can speak more to removing unused tables/columns, but we rarely if ever do this, even for removed features.

The `AUDIT_RULE` and `DONT_AUDIT_RULE` enum values are/were used to instruct the rule engine plugin how to execute rules in such a way that the auditing machinery would know to audit the rules/microservices being executed. Since these are no longer being used due to the removal of audit trails, I think you're right in that we can probably remove the template parameter for the `rule_execution_manager_pack` enum. I've created an issue for that here: https://github.com/irods/irods/issues/7402

**Comment by korydraughn** [comment]
@alanking is correct. We normally avoid removing database tables/columns. However, removing `R_OBJT_AUDIT` sounds safe.

There's no guarantee that'll happen anytime soon since the existence of that table doesn't hurt the system. I've created #7403 to address this.
