### ISSUE TITLE
Add intermediate replica status

### ISSUE THREAD

**Issue by alanking** [irods/irods#4343]
- [x] master
- [x] 4-2-stable
---
## Feature

Provide a new state for the `data_is_dirty` column in the R_DATA_MAIN table to represent the intermediate state of newly created data objects.

The states will be defined as follows:

- 0: stale replica, to be represented by 'X' in `ils` (currently blank)
- 1: good replica, to be represented by '&' in `ils` (no change)
- 2: intermediate replica, to be represented by '?' in `ils` (new)

```
# Intermediate state of an iput to a replication resource with 3 leaves
$ ils -l
/tempZone/home/rods:
  rods              0 repl;ufs0           0 2019-04-08.15:38 ? foo 
  rods              1 repl;ufs1           0 2019-04-08.15:38 ? foo 
  rods              2 repl;ufs2           0 2019-04-08.15:38 ? foo 

# After initial put is complete and before synchronous replication has completed
$ ils -l
/tempZone/home/rods:
  rods              0 repl;ufs0       12345 2019-04-08.15:38 & foo 
  rods              1 repl;ufs1           0 2019-04-08.15:38 ? foo 
  rods              2 repl;ufs2           0 2019-04-08.15:38 ? foo

# After replication has succeeded
$ ils -l
/tempZone/home/rods:
  rods              0 repl;ufs0       12345 2019-04-08.15:38 & foo 
  rods              1 repl;ufs0       12345 2019-04-08.15:38 & foo 
  rods              2 repl;ufs0       12345 2019-04-08.15:38 & foo 
```
```
# Indicating one stale replica for data object
$ ils -l
/tempZone/home/rods:
  rods              0 resc1       54321 2019-04-08.15:38 & bar 
  rods              1 resc2       12345 2019-04-08.15:38 X bar
```

**Comment by kript** [comment]
Can I ask that if this gets implemented documentation is added to the man pages for `ils` as well as the general docs, for all three states, please?

**Comment by alanking** [comment]
The following should return an error called `USER_INTERMEDIATE_REPLICA_ACCESS`:
```
$ ils -l
/tempZone/home/rods:
  rods              0 repl;ufs0       12345 2019-04-08.15:38 & foo 
  rods              1 repl;ufs1           0 2019-04-08.15:38 ? foo 
  rods              2 repl;ufs2           0 2019-04-08.15:38 ? foo
$ iget -n1 foo # nope
$ iput -f -n1 foo # also nope
```

**Comment by alanking** [comment]
Proposal: Atomic creation of all replicas as required by the resource hierarchy prior to data movement will require a change in `irods::resolve_resource_hierarchy` and its associated resource plugin operation. Currently, this operation only returns a resolved hierarchy. This proposal would allow for resources involved in the "voting" process to request additional behavior per their policy implementations. For the case of an `irods::CREATE_OPERATION`, which needs to instantiate all of its intermediate replicas first, the following steps should occur:
1. The resource hierarchy resolution vote determines how many replicas are required and performs a hierarchy resolution for each of the replica-receiving children
3. Once all hierarchies have been resolved, it will return a `std::vector<irods::hierarchy_parser>` to its parent/calling procedure

This behavior could be expanded to include other opinions besides required replicas such as attendant metadata annotation on replica creation, setting ACLs, etc.

Example:
```
$ ilsresc
root:passthru
└── r1:replication
    ├── r2:replication
    │   ├── r3:random
    │   │   ├── u5:unixfilesystem
    │   │   └── u6:unixfilesystem
    │   ├── r4:random
    │   │   ├── u7:unixfilesystem
    │   │   └── u8:unixfilesystem
    │   ├── u0:unixfilesystem
    │   └── u1:unixfilesystem
    ├── u2:unixfilesystem
    ├── u3:unixfilesystem
    └── u4:unixfilesystem
$ iput -R root foo
```
 - `root` is a passthru and requires its child to receive a replica
     - `r1` requires **4 children** to receive replicas (`r2`, `u2`, `u3`, `u4`)
        - `r2` requires **4 children** to receive replicas (`r3`, `r4` `u0`, `u1`)
            - `r3` requires **1 child** to receive a replica (random)
                - return: <`r3;u6`>
            - `r4` requires **1 child** to receive a replica (random)
                - return: <`r4;u7`>
            - return: <`r2;r3;u6`, `r2;r4;u7`, `r2;u0`, `r2;u1`>
        - return: <`r1;r2;r3;u6`, `r1;r2;r4;u7`, `r1;r2;u0`, `r1;r2;u1`, `r1;u2`, `r1;u3`, `r1;u4`>
    - return: <`root;r1;r2;r3;u6`, `root;r1;r2;r4;u7`, `root;r1;r2;u0`, `root;r1;r2;u1`, `root;r1;u2`, `root;r1;u3`, `root;r1;u4`>

The high-level procedure can then iterate over this vector and create an intermediate replica on each leaf resource.

**Comment by alanking** [comment]
This should address #4464

**Comment by alanking** [comment]
Created #4767 and repurposed #3848 for some of the work encompassed here.
