### ISSUE TITLE
microservice msiDataObjGet doesn't end

### ISSUE THREAD

**Issue by JEREM-M** [irods/irods#4358]
[reLog.2019.04.19.log](https://github.com/irods/irods/files/3098565/reLog.2019.04.19.log)
[rodsLog.2019.04.19.log](https://github.com/irods/irods/files/3098566/rodsLog.2019.04.19.log)

### iRODS Version, OS and Version

IRODS : 4.2.5
Jargon-core : 4.3.0.2

### What did you try to do?

Getting a stored zip file by invoking  a rule via jargon.
The problem appears only for this specific file.
The rule call the microservice msiDataObjGet. When used we have the following result : the zip file is put in the destination folder but we never get a response from the service thus locking the process.
Logs files  contain no errors.

We suspect the problem is caused because IRODS try to read the content inside the zip file.

You can find the log file joined to this issue.

If we use the rule directly without jargon, the process ends properly.

**Comment by trel** [comment]
So, this is a jargon issue?   Rather than an iRODS server issue?

**Comment by GwenLdR** [comment]
Yes that seems the most likely assumption.
Should we also open this issue on the jargon github ?

**Comment by trel** [comment]
I’ll move it now...

**Comment by JEREM-M** [comment]
Update on this issue : 
The problem appear when doing a parallel transfer on a file weighing more than 32Mo.
And it's effectively a jargon issue.
I will close this one.

Thanks.
