### ISSUE TITLE
Some test_icommands_file_operations tests fail in Cen7 due to journald message suppression

### ISSUE THREAD

**Issue by alanking** [irods/irods#4359]
- [x] master
---
Need to create a suitable journald/rsyslog configuration to accommodate our test suite and/or adjust categorical log levels such that all messages appear in the log as expected.
Remove 30 second sleep added to alleviate this when resolved.
Note: 30 second sleep is to match the default rate limiting window in journald.

**Comment by korydraughn** [comment]
Now that iRODS has an option that makes testing more stable (#4472), I think this issue is safe to close.
