### ISSUE TITLE
Can create resource hierarchy cycles

### ISSUE THREAD

**Issue by trel** [irods/irods#4363]
- [x] master
- [x] 4-2-stable
-------

### iRODS Version, OS and Version

4.2.5

### What did you try to do?

Add a child resource to self as parent (mistakenly)

### Expected behavior

See an error message saying
```
Cannot add child [<resc_name>] to parent [<resc_name>]
```

### Observed behavior (including steps to reproduce, if applicable)

Child was added successfully.

Resource now invisible to `ilsresc`

**Comment by alanking** [comment]
Apparently, you can also add a child as a parent to its parent or grandparent (and so on) and it is hidden from ilsresc:
```
$ ilsresc
test_passthru0:passthru
└── test_passthru1:passthru
    └── test_ufs:unixfilesystem
$ iadmin addchildtoresc test_ufs test_passthru0
```
In other words, we should probably rename this issue to address general hierarchical cycles.

**Comment by trel** [comment]
agreed.

**Comment by alanking** [comment]
This should be addressed with the following logic:
1. Child-to-be must be a root (aka no parent)
2. Parent-to-be must not have child-to-be as its root

Pseudocode:
```
if !child_to_be.parent.empty:
    return CHILD_HAS_PARENT
if parent_to_be.root == child_to_be:
    return HIERARCHY_ERROR
addchildtoresc()
```

Needs two tests based on this simple case:
```
A
└── B
```
1. Add A as a child of A
2. Add A as a child of B
