### ISSUE TITLE
iput fails uploading large file

### ISSUE THREAD

**Issue by kript** [irods/irods#4401]
### iRODS Version, OS and Version

iRODS 4.1.12
Ubuntu 12.04

### What did you try to do?

upload a > 600GB file with `iput` using `-T` and `--retries` to maintain a connection

### Expected behavior

File uploads successfully.

### Observed behavior (including steps to reproduce, if applicable)

```
 line 198: 27948 Segmentation fault      iput -fKT --wlock --retries 3 -N 3 -X "${tmp_restart}" --lfrestart "${tmp_lfrestart}" --metadata "imirror_src;${local_file};;" "${local_file}" "${irods_file}" > "${tmp_iputfail}" 2>&1

New restartFile /tmp/tmp.kTbtamx2xY/tmp.Kor2ZNFSKJ opened
cliReconnManager: Reconnecting clientState = 0
The client/server socket connection has been renewed
[ The above two lines appear 145 further times ]
ERROR: putUtil: put error for /humgen/scratch119-backup/sga/trio/input/NA12878/all.fa, status = -4000 status = -4000 SYS_HEADER_READ_LEN_ERR
```
Referencing #3986 and #4170.
This is an intermittent issue, but in this case I can confirm we have no bandwidth issues between the servers.

Its hard to pull out a specific log from the server, as we have ~10 of these running at any one time

**Comment by trel** [comment]
I think this is a candidate for closing.   Much has improved since May 2019.

**Comment by korydraughn** [comment]
Agreed. Please close.
