### ISSUE TITLE
imeta qu ignores the -z option

### ISSUE THREAD

**Issue by bitkid** [irods/irods#4426]
- [x] master
- [x] 4-2-stable
------

## Bug Report
i have 2 zones

```
[root@4ea265da3717 tmp]# iadmin lz
awszone2
awszone1
```
one is a remote zone

```
[root@4ea265da3717 tmp]# iadmin lz awszone1
zone_id: 10074
zone_name: awszone1
zone_type_name: remote
zone_conn_string: icat.awszone1.*************
r_comment:
create_ts: 2019-06-14.11:36:05
modify_ts: 2019-06-14.11:36:05
```
```
[root@4ea265da3717 tmp]# imeta -z awszone1
imeta>ls -d somefile
AVUs defined for dataObj somefile:
Dataobject /awszone2/home/sadatgus/somefile does not exist
or, if 'strict' access control is enabled, you may not have access.
```
shouldn't `imeta` search in /awszone1/somePath?
it's also not possible to find the file with `imeta -z awszone1 qu -d prefix = s` (as an example)
what's the correct way to search files within a federation across zones by meta data?

i can get the file with `iget` from the other zone (so the federation setup works).

### iRODS Version, OS and Version
4.2.6 centos 7

### What did you try to do?
query meta data across zones.

**Comment by bitkid** [comment]
btw i can list the meta data from the file in the remote zone when i use the full path so
imeta ls -d /awszone1/home/*/54762d24-8e9c-11e9-8589-0242ac17000b works

**Comment by JustinKyleJames** [comment]
According to the docs, the imeta -z option only applies for queries (qu) and for resources.  If you are doing a listing of metadata on a certain file in a certain collection, it will use the zone from the path.


I don't think it was the intent of the -z option to back up and change the path from /awszone2/home/sadatgus/somefile to /awszone1/home/sadatgus/somefile.


As for the qu question, do you have an AVU with attr=prefix and value=s?


________________________________

**Comment by bitkid** [comment]
i can find it with that query when i am connected to awszone1 but i cant find it when i am connected to awszone2 allthough i did a ichmod own to sadatgus#awszone2. as i said i can download it from the remote zone but i cant find it wit imeta qu.

**Comment by bitkid** [comment]
just a general question .. it should be possible to query meta data across zones? any settings needed for that?

**Comment by bitkid** [comment]
what is also quite surprising (and what's not really covered by the documentation). just giving read access on a file to remote users doesn't make it possible to list the meta data for that file. i had to give read access to the folder (collection) where the file is located that this works. 

`imeta ls -d /zone1/home/sadatgus/fileName` returns `Dataobject /zone1/home/sadatgus/fileName does not exist`.

`ichmod read sadatgus#zone2 /zone1/home/sadatgus/` made it work

**Comment by d-w-moore** [comment]
Confirmed `imeta -z` is being ignored.

**Comment by jasoncoposky** [comment]
This is due to the move to boost::program_options, zoneArguments was ignored:
https://github.com/irods/irods_client_icommands/blob/master/src/imeta.cpp#L35

**Comment by trel** [comment]
@kript @bh9 fixed
