### ISSUE TITLE
Delay server should store rei context in catalog

### ISSUE THREAD

**Issue by alanking** [irods/irods#4428]
## Feature

The `rei` context will need to be stored in the catalog with the rule, rather than stored in a file on the `irodsDelayServer` filesystem in `/var/lib/irods/config/packedRei/`.

**Comment by alanking** [comment]
Consider using the `nlohmann::json` library for serialization/de-serialization of the `rei` context rather than the special packedRei instructions in use now.

**Comment by trel** [comment]
also considering pulling this back to 4.2.x

**Comment by trel** [comment]
part of https://github.com/irods/irods/issues/3049
