### ISSUE TITLE
irods-server package assumes epel-release package is installed

### ISSUE THREAD

**Issue by tedgin** [irods/irods#4450]
### iRODS Version, OS and Version
iRODS 4.2.6, CentOS 7.6

### What did you try to do?

I tried to install the irods-server package.

```
sudo yum install irods-server
```

### Expected behavior

I expected irods-server to be installed.

### Observed behavior (including steps to reproduce, if applicable)
It errored out, saying that python-psutil and python-jsonschema are required.

To work around this, install epel-release before installing irods-server.

Either the irods-server package needs to identify epel-release as a prerequisite or the installation documentation needs to say the epel-release needs to be installed first.

**Comment by trel** [comment]
Can't declare a dependency on the other repo/package AND packages that it provides at the same time.  This will be a fix in the installation section of the docs.
