### ISSUE TITLE
add --test option to ./irodsctl start

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#4472]
## Feature
Tests that read the log file and make assertions based on the contents of the log file have a high failure rate in **master** due to rsyslog buffering the output.

The iRODS server needs a new option that instructs it to run in a mode suitable for testing.

## Proposal
Server: `./irodsServer -t`
Control script: `./irodsctl start --test`

**Comment by trel** [comment]
Can we get away with not running the ./irodsServer in a different mode?   And only add options to the control script and/or the test scripts?   If the server is in a different mode, are we leaving ourselves open to be testing a different mode than people are running in production?

**Comment by trel** [comment]
Since test mode is only writing things down in an *additional* location, this should be fine.   I retract my hesitation.
