### ISSUE TITLE
open(O_TRUNC), close() truncates object leaving iCAT data size unchanged

### ISSUE THREAD

**Issue by cjsmeele** [irods/irods#4483]
- [x] master
- [x] 4-2-stable
------

### iRODS Version, OS and Version

iRODS 4.2.6, CentOS 7

### What did you try to do?

Truncate an existing data object by opening with O_WRONLY | O_CREAT | O_TRUNC and then immediately closing it (as is done by Davrods when overwriting a file to be empty).

### Expected behavior

The object becomes empty and its size is reported as '0' by `ils`.

### Observed behavior (including steps to reproduce, if applicable)

The object becomes empty (`iget` produces 0 bytes), however `ils` reports the old object size.
Replicas are not in use.

To reproduce, create a non-empty file via Davrods, and overwrite it to become completely empty (no end-of-line character at the end of the file).

This minimal Python iRODS client example, which uses the same flags for opening, also demonstrates the issue:

```python
from irods.session import iRODSSession

session = iRODSSession(
    host     = 'localhost',
    port     = 1247,
    user     = 'rods',
    password = 'rods',
    zone     = 'tempZone',
)

f = session.data_objects.open('/tempZone/home/rods/xyz.txt', 'w')
f.write(b'bla bla bla')
f.close()

f = session.data_objects.open('/tempZone/home/rods/xyz.txt', 'w')
f.close()
```

This produces a file that is reported by `ils` to be 11 bytes, while `iget /tempZone/home/rods/xyz.txt - | wc -c` reports 0 characters.

**Comment by trel** [comment]
related to work for #4331
