### ISSUE TITLE
Recommended Rule Language

### ISSUE THREAD

**Issue by kroonma** [irods/irods#4496]
## Question

Hello, I'm rather new to iRODS, if there's a better channel (mailing list?) to ask this question, please let me know.

The [documentation on rule engines](https://docs.irods.org/4.2.6/plugins/pluggable_rule_engine/) refers to the [iRODS Rule Language](https://docs.irods.org/4.2.6/plugins/irods_rule_language/) as "legacy". Does legacy mean it is soon to be deprecated? If so, what is the recommended language/engine for writing rules?

An additional question: is there a formal syntax description (e.g. BNF) available for the irods rule language?

**Comment by kroonma** [comment]
I found a google chat group -- I suppose that's a better place to ask this question.

**Comment by trel** [comment]
No worries - welcome!   We'll answer there.
