### ISSUE TITLE
iput -k fails to add checksum for zero-length files

### ISSUE THREAD

**Issue by kjsanger** [irods/irods#4502]
### iRODS Version, OS and Version

iRODS 4.1.12, Ubuntu Precise, Bionic

### What did you try to do?

`iput -k zero_length_file`

### Expected behavior

The file appears in iRODS with a checksum calculated, stored in the database and visible by `ils -L zero_length_file`

### Observed behavior (including steps to reproduce, if applicable)

The file is in iRODS, yet no checksum has been calculated.  This also affects other applications calling `rcDataObjPut` with `REG_CHKSUM_KW` (tested). Altering the file to add a single byte causes the checksum to be calculated as expected.

**Comment by trel** [comment]
Works for me in 4.2.6.

Anything else I should do to reproduce this?

```
$ touch empty
$ iput -k empty
$ ils -L empty
  rods              0 demoResc            0 2019-09-10.17:45 & empty
    sha2:47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=    generic    /var/lib/irods/Vault/home/rods/empty

$ ienv | grep version
irods_version - 4.2.6
```

**Comment by kjsanger** [comment]
Your example has just indicated a difference to me ... the server here is configured to use MD5 checksums.

**Comment by kjsanger** [comment]
... and it doesn't affect 4.2.5 configured to use MD5 checksums. So it looks like 4.1.12 only.

**Comment by trel** [comment]
It looks like the fix for https://github.com/irods/irods/issues/3883 took care of this use case.
