### ISSUE TITLE
Add iunreg iCommand

### ISSUE THREAD

**Issue by alanking** [irods/irods#4506]
- [x] master
- [x] 4-2-stable
---
## Feature

Related to #3821 and #3451 (commit https://github.com/irods/irods/commit/344426eca96285984bbd01ff06f7e5d73fc02f09).

With the deprecation of `irm -n`, `irm -U -n` is no longer recommended. We need a way to trim a specific replica from the catalog without touching physical storage (aka unregister).

Expected example usage with `-n` (`REPL_NUM_KW`):
```
$ ils -l foo
$ ils -l
/tempZone/home/rods:
  rods              0 demoResc        6 2019-09-12.14:03 & foo
  rods              1 ufs1            6 2019-09-12.14:03 & foo
  rods              2 ufs2            6 2019-09-12.14:03 & foo
$ itrim -U -n1 foo
$ ils -l
/tempZone/home/rods:
  rods              0 demoResc        6 2019-09-12.14:03 & foo
  rods              2 ufs2            6 2019-09-12.14:03 & foo
```

Expected example usage with `-S` (`RESC_NAME_KW`) where all replicas under the named source resource are eligible for trimming:
```
$ ils -l foo
$ ils -l
/tempZone/home/rods:
  rods              0 demoResc        6 2019-09-12.14:03 & foo
  rods              1 repl;ufs1       6 2019-09-12.14:03 & foo
  rods              2 repl;ufs2       6 2019-09-12.14:03 & foo
$ itrim -U -N1 -S repl foo
$ ils -l
/tempZone/home/rods:
  rods              0 demoResc        6 2019-09-12.14:03 & foo
```

Expected example usage with `-S` (`RESC_NAME_KW`) where some - but not all - replicas under the named source resource are eligible for trimming:
```
$ ils -l foo
$ ils -l
/tempZone/home/rods:
  rods              0 demoResc        6 2019-09-12.14:03 & foo
  rods              1 repl;ufs1       6 2019-09-12.14:03 & foo
  rods              2 repl;ufs2       6 2019-09-12.14:03 & foo
$ itrim -U -S repl foo
$ ils -l
/tempZone/home/rods:
  rods              0 demoResc        6 2019-09-12.14:03 & foo
  rods              2 repl;ufs2       6 2019-09-12.14:03 & foo
```
Even when the target resource is marked down, the eligible replica(s) should be unregistered without complaint.

**Comment by tsmeele** [comment]
Ideally this command option to unregister is authorized similar to ireg:
```
By default, only rodsAdmin users are allowed to register files or directories.
More permissive registration policies can be set in the server's rule base
using the acNoChkFilePathPerm() rule.
```

**Comment by trel** [comment]
You're requesting that unregistering a replica require admin privileges by default, rather that just 'own' permission on the data object?

I don't think that is equivalent to how `irm -U -n` works today.

**Comment by tsmeele** [comment]
Yes it is, and the requirement prevents cluttering up the resource vault without the admin being aware.  The irm -U documentation mentions:
```
The -U option allows the unregistering of the data object or collection
without deleting the physical file. Normally, a normal user cannot
unregister a data object if the physical file is located in a resource
vault. The acNoChkFilePathPerm rule allows this check to be bypassed.
```

**Comment by trel** [comment]
Well, there it is.

https://docs.irods.org/4.2.6/icommands/user/#irm

That's what I get for replying from my phone.

**Comment by alanking** [comment]
While the comment from the `irm` documentation may have been true at one point in time, it has not been true since 4.0.3 at the latest:

```
$ ienv
NOTICE: Release Version = rods4.0.3, API Version = d
NOTICE: irodsHost=localhost
NOTICE: irodsPort=1247
NOTICE: irodsUserName=alice
NOTICE: irodsZone=tempZone
NOTICE: created irodsHome=/tempZone/home/alice
NOTICE: created irodsCwd=/tempZone/home/alice
$ iquest "select USER_TYPE where USER_NAME = 'alice'"
USER_TYPE = rodsuser
------------------------------------------------------------
$ iput /var/lib/irods/VERSION foo
$ ils -L foo
  alice             0 demoResc           67 2019-09-16.16:08 & foo
        demoResc    generic    /var/lib/irods/iRODS/Vault/home/alice/foo
$ irm -U foo
$ ils
/tempZone/home/alice:
$ ls -l /var/lib/irods/iRODS/Vault/home/alice/foo
-rw------- 1 irods irods 67 Sep 16 16:08 /var/lib/irods/iRODS/Vault/home/alice/foo
```

Original implementation of `irm -U`: https://github.com/irods/irods-legacy/commit/19f0782a1e6fddd8bef0299bb9e79a445ffa2ac2

**Comment by tsmeele** [comment]
When users are able to unregister replica files then the iRODS catalog administration becomes out of sync with actual vault content. This means that the "managed" resource is no longer properly managed. The status of the remaining file is at best an orphan yet could represent actual data accidentally unregistered by a less informed user.

On another note, wouldn't it make sense to create a separate 'iunreg' command as the opposite of ireg instead of adding this feature to itrim?

**Comment by trel** [comment]
I believe your claim is correct - however, an administrator can scan the resource with `iscan` to find any deltas on the storage and catalog.  I believe this has always been true (regarding `irm -U`... (we're searching the history to find if this is indeed a regression).

I think we do want an 'unreg' option for `itrim` (which operates on replicas, not data objects) since we still want all the other features it provides.

**Comment by alanking** [comment]
We are convinced - the parity is more elegant than a `-U` on `itrim`.

-| ↔️ | logical | physical
:--- |:---:|:---:|:---:
**data objects** | iput ↔️ irm | :heavy_check_mark: | :heavy_check_mark:
**replicas** | irepl ↔️ itrim | :heavy_check_mark: | :heavy_check_mark:
**replicas** | ireg ↔️ iunreg | :heavy_check_mark: | :x:

The proposed `iunreg` command would have identical options to `itrim` but an additional hard-coded `oprType` of `UNREG_OPR`.

**Comment by alanking** [comment]
For complete separation of concerns, in addition to allowing unregistering specific replicas (a la `itrim`), `iunreg` will also replace the `-U` option of `irm` (which is to be deprecated).
```
$ iunreg -n0 foo # unregisters single replica (0)
$ iunreg foo # unregisters all replicas
```
