### ISSUE TITLE
Create and package irods-devConfig.cmake and irods-runtimeConfig.cmake

### ISSUE THREAD

**Issue by jasoncoposky** [irods/irods#4522]
## Feature

In order to declare package dependencies for external projects, the iRODS packaging for these libraries should include Config.cmake files for the use of the find_package() directive within CMake.

**Comment by trel** [comment]
@SwooshyCueb was this closed because the work is being handled by/in other issues?   Should it be in the 4.3.0 milestone?

**Comment by SwooshyCueb** [comment]
Closed because it was already done

**Comment by SwooshyCueb** [comment]
iRODS has generated CMake configuration files since before I started working on it. If you don't want to put it in an old milestone, 4.3.0 will do

**Comment by trel** [comment]
Got it - 4.3.0 it is.   If you find where it happened, please link back - but not critical.   Thanks.

**Comment by SwooshyCueb** [comment]
Just did a git blame and it actually predates the creation of this issue quite a bit:
https://github.com/irods/irods/commit/f5d99a58e49cf1f04af34af8df0461a1a87963fc#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR1409-R1414
Looks like the first release to have this functionality was 4.2.0

**Comment by trel** [comment]
Very good.

Curious then was cap'n coposky was looking for...

The world may never know.
