### ISSUE TITLE
Remove unnecessary parameter from irods::filesystem::get_metadata function

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#4532]
- [x] master
- [x] 4-2-stable

## Code Refactor
The `_metadata` parameter is not used by this function and should be removed.
https://github.com/irods/irods/blob/1172f44fd6a6d3ce598e89c31e553919e3a31b8f/lib/filesystem/include/filesystem/filesystem.hpp#L107-L109

**Comment by trel** [comment]
4.2 covered by https://github.com/irods/irods/commit/4930ab8bc64920c8c1c99d0941f6f19d93eada36
