### ISSUE TITLE
ilocate search patterns can't include spaces

### ISSUE THREAD

**Issue by anderbubble** [irods/irods#4540]
- [x] master
- [x] master icommands
- [x] 4-2-stable
- [x] 4-2-stable icommands
----

### iRODS Version, OS and Version

```
$ rpm -qa | grep -i irods
irods-externals-avro1.7.7-0-1.0-1.x86_64
irods-externals-clang-runtime3.8-0-1.0-1.x86_64
irods-externals-boost1.60.0-0-1.0-1.x86_64
irods-externals-libarchive3.3.2-0-1.0-1.x86_64
irods-icommands-4.2.6-1.x86_64
irods-externals-zeromq4-14.1.3-0-1.0-1.x86_64
irods-runtime-4.2.6-1.x86_64
irods-server-4.2.6-1.x86_64
irods-externals-jansson2.7-0-1.0-1.x86_64
irods-database-plugin-postgres-4.2.6-1.x86_64
irods-externals-libarchive3.1.2-0-1.0-1.x86_64
```

### What did you try to do?

```
$ touch "file with spaces"
$ iput "file with spaces"
$ ilocate "file with spaces"
```

### Expected behavior

```
$ touch "file with spaces"
$ iput "file with spaces"
$ ilocate "file with spaces"
/civilfritz.net/home/janderson/file with spaces
$ ilocate "%file with spaces%"
/civilfritz.net/home/janderson/file with spaces
$ ilocate "%spaces%"                                                                                                                                                                                       
/civilfritz.net/home/janderson/file with spaces
```

### Observed behavior (including steps to reproduce, if applicable)

```
$ touch "file with spaces"
$ iput "file with spaces"
$ ilocate "file with spaces"
ERROR: Couldn't locate file
$ ilocate "%file with spaces%"
ERROR: Couldn't locate file
$ ilocate "%spaces%"                                                                                                                                                                                       
/civilfritz.net/home/janderson/file with spaces
```

**Comment by trel** [comment]
well, that's been there [a long time](https://github.com/irods/irods-legacy/commit/7b5a9e62dcb7ecd901d56e6c5f04572d2c48248f)...

candidate fix, please evaluate...

```diff
diff --git a/bin/ilocate b/bin/ilocate
index 31b98c8..adc4079 100755
--- a/bin/ilocate
+++ b/bin/ilocate
@@ -60,7 +60,7 @@ do
        shift
 done
 
-for inputstr in $*
+for inputstr in "$*"
 do
        echo "$inputstr" | egrep -q "[^\]%|^%"  # egrep ensures '%' isn't meant as a literal
        if [ $? -eq 0 ]
```

**Comment by anderbubble** [comment]
Confirmed that the fix succeeds in my environment. Pleased to see tests added as well!

**Comment by stsnel** [comment]
@trel 
Suggestion: perhaps "$@" could be used here instead of "$*", in case users provide multiple search pattern arguments.

**Comment by trel** [comment]
Hi @stsnel - can you share an example of when "$@" would work better?  A test that would fail with "$*"?

Since this is just a wrapper around `iquest`, I'm considering deprecating this bash tool...

**Comment by stsnel** [comment]
Hi Terrell, 

For example, consider a zone with these data objects: 
/testZone/home/rods/foo
/testZone/home/rods/bar

The old version of ilocate would print both data objects if a user entered "ilocate foo bar".

The new version with "$*" would fail, however:
```
[vagrant@provider ~]$ ilocate foo bar
ERROR: Couldn't locate foo bar
```

Using "$@" instead of "$*" ensures that such queries with multiple search patterns still work. Users can search for data object names containing spaces using quoted search patterns. For example: ilocate "data object with space.txt"

**Comment by anderbubble** [comment]
I absolutely agree with using `"$@"`. That's what I always do in my scripts, so I wasn't confident to say that `"$*"` behaved differently.

**Comment by trel** [comment]
Sold - will update the PR.  Thanks.
