### ISSUE TITLE
imeta add -C <collection>/ fails because of trailing /

### ISSUE THREAD

**Issue by tedgin** [irods/irods#4559]
- [x] master
- [x] 4-2-stable
------

### iRODS Version, OS and Version

imeta 4.1.10 running on Ubuntu 18.04.  iRODS server 4.1.10 running on CentOS 7

### What did you try to do?

I tried to add an AVU triple to collection with the collection name having a trailing / appended to it, e.g., `imeta add -C cyverse.dev/ a v u`.

### Expected behavior

Since the collection exists in the current working collection, and I own it, I expected the AVU to be added to it. Since `ils` can handle trailing slashes, I assumed `imeta` would too.

### Observed behavior (including steps to reproduce, if applicable)

```
rods@dev ~? ils cyverse.dev/
/cyverse.dev/home/rods/cyverse.dev:
  r
  C- /cyverse.dev/home/rods/cyverse.dev/home
rods@dev ~? imeta add -C cyverse.dev/ a v u
ERROR: Level 0: collection '/cyverse.dev/home/rods/cyverse.dev/' is unknown
ERROR: rcModAVUMetadata failed with error -814000 CAT_UNKNOWN_COLLECTION 
Level 0: collection '/cyverse.dev/home/rods/cyverse.dev/' is unknown
```

**Comment by trel** [comment]
reproduced in 4.2.6

needs more `irods::filesystem`
