### ISSUE TITLE
Simultaneous transfers (& uploads?) are limited by the requirement to update the R_RESC_MAIN entry

### ISSUE THREAD

**Issue by bh9** [irods/irods#4584]
In attempting to retire a few old 25TB resources, by using iphymv to move files out of, and back into the composite tree, then mitigating #4212, we discovered that a lot of the iphymvs fail because they are unable to get a lock on the resource's entry in R_RESC_MAIN. This lock is only necessary because each time a replica is moved, the resource that is gaining the replica has to have its object_count incremented and the the resource that is losing it needs to have it decremented. 
While quickly being able to see the number of objects in a resource is nice, it doesn't allow for great handling of scale. We started hitting it with ~4 simultaneous replica moves from 1 resource to another, but it should be possible to reproduce this by doing small simultaneous uploads as well.  
Note: the parallel approach was only necessary because at the rate transfer started, it was going to take 2 months to retire each resource

**Comment by trel** [comment]
The `object_count` is no longer used, since 4.2.0.

We moved away from it for the reason you provided, as well as performance.
