### ISSUE TITLE
Quota value in bytes and / or in number of inodes ?

### ISSUE THREAD

**Issue by sviscapi** [irods/irods#4593]
## Feature

Dear iRODS team,

Would it be possible to add a new quota limit based on the number of inodes used on a resource or in total ?

Best regards,

Samuel from CINES

https://www.cines.fr/en/

**Comment by trel** [comment]
Hi Samuel,

Yes, this is being worked on now as 'Logical Quotas'.

You can find the new rule engine plugin here - it has not been released yet.

https://github.com/irods/irods_rule_engine_plugin_logical_quotas

**Comment by sviscapi** [comment]
Thank you Terrell for your quick reply, that's really appreciated.

Cheers, Samuel
