### ISSUE TITLE
rsDataObjWrite does not update bytesWritten correctly in L1 descriptors

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#4598]
- [x] master
- [x] 4-2-stable

## Bug Report
When L1 descriptors are initialized, `bytesWritten` is set to `-1`.
https://github.com/irods/irods/blob/d788d847476b0ef58031405d5afbc5f8b0ba43d9/server/core/src/objDesc.cpp#L159-L162

Because `bytesWritten` is initialized to `-1`, the following block will always cause the L1 descriptor's information to be incorrect.
https://github.com/irods/irods/blob/d788d847476b0ef58031405d5afbc5f8b0ba43d9/server/api/src/rsDataObjWrite.cpp#L174-L176

### Solution
`rsDataObjWrite` needs to assign or add `bytesWritten` based on the value of `L1desc[l1descInx].bytesWritten`. See below.
```c++
if (bytesWritten > 0) {
    if (auto& bw = L1desc[l1descInx].bytesWritten; bw == -1) {
        bw = bytesWritten;
    }
    else {
        bw += bytesWritten;
    }
}
```

**Comment by PaulVanSchayck** [comment]
Sorry for stalking you on this commit. This seems like a pretty fundamental bug/change. What is the impact of this bug and the change? (In fact the code of rsDataObjWrite() hadn't been touched in many years)

We have seen occasional cases (with the S3 plugin for example) where rsDataObjClose() would report size in vault to be 0, when the file on disk (or as reported by S3) is in fact correct. Could this change impact that in any way?

**Comment by korydraughn** [comment]
This change is primarily for REP/PEP code and should not have any negative impact on existing deployments. This change only makes it so that rsDataObjWrite updates the L1 descriptor state.
