### ISSUE TITLE
setup_irods.py is no longer idempotent in 4.2.X

### ISSUE THREAD

**Issue by bh9** [irods/irods#4602]
- [x] master
- [x] 4-2-stable
-----

### iRODS Version, OS and Version
4.2.6 Ubuntu Xenial

### What did you try to do?
Run setup_irods.py on a configured zone, to set the server_config.json up correctly

### Expected behavior
setup_irods.py notices that the database has already been set up, so doesn't attempt to set it up, instead just modifying the relevant entries in the server_config

### Observed behavior (including steps to reproduce, if applicable)
setup_irods attempts to create a new zone, and fails because it tries to name it the same thing as the previous one, thus violating a unique constraint

**Comment by trel** [comment]
4-2-stable PR at https://github.com/irods/irods/pull/5295 - works at the bench - awaiting @bh9 @kript review

**Comment by kript** [comment]
Any chance of getting this in 4.2.9? 🙏

**Comment by trel** [comment]
Yeps.

**Comment by trel** [comment]
hmm, feels like an enhancement... but also, a bit of a regression from 4.1... okay, marking it as bug.
