### ISSUE TITLE
Add command (istream) that allows streaming data in/out of iRODS

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#4626]
- [x] master
- [x] 4-2-stable

---

## Feature
A new icommand that allows users to stream data in and out of iRODS.

### Optional Command Flags
--offset, -o:  The absolute position within the data object to read from or write to.
--count, -c:  The number of bytes to read/write
--append, -a:  Append to the data object (Implies --no-trunc).
--no-trunc:  Do not truncate the data object.

### Read
```bash
$ istream read -o 200 /tempZone/home/rods/file > file
```
### Write
```bash
$ cat file | istream write --offset 10 --count 100 /tempZone/home/rods/file
```

**Comment by kript** [comment]
Intriguing!  If there could be documentation with this tool that also covers what happens under situations like;

1. the stream is broken at the client end
2. when information like file size and/or checksum (if appropriate) is updated 
3. Does the tool go direct to the resource server or via Provider? Under which circumstances?
4. Can you use it to create in iRODS that didn't occur before?

**Comment by korydraughn** [comment]
1. We haven't decided on what should happen here just yet.  Based on the changes coming in 4.2.8, I would expect the replica (being written to) to be marked as intermediate or stale.
2. Information such as file size and checksum will be available following a successful close of the data object.
3. We are discussing this and have not reached any decision yet.
4. This tool will create new data objects (on write) as long as `--no-trunc` is not passed.

**Comment by korydraughn** [comment]
In regards to question 3.  The following is from the istream help text.
```bash
If the target data object does not reside on the connected server,
istream will not attempt to redirect to the server hosting the replica.
Traffic will always flow through the connected server.
```
This is in line with how iRODS has always handled streaming.
