### ISSUE TITLE
Opening a data object with the truncation flag should update the catalog

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#4628]
- [x] master
- [x] 4-2-stable
---
Opening a data object with the truncation flag (e.g. `std::ios_base::trunc` or `O_TRUNC`) should be reflected in the catalog immediately by setting the size to zero.

REPs such as [logical_quotas](https://github.com/irods/irods_rule_engine_plugin_logical_quotas) require this behavior in order to operate correctly.

**Comment by trel** [comment]
duplicate of #4483
