### ISSUE TITLE
Server leaks memory via (python-)rule genqueries and built-in microservices

### ISSUE THREAD

**Issue by cjsmeele** [irods/irods#4649]
- [x] master
- [x] 4-2-stable
------

## Bug Report

Memory allocated via genquery and certain microservices is not freed, when called through the Python rule engine. Equivalent operations from the iRODS rule language appear either not to leak or to leak less memory.

This makes it difficult to have long-running Python rules, or to use a single iRODS session for multiple (Python) rule calls.

### iRODS Version, OS and Version

iRODS 4.2.7, CentOS 7

### What did you try to do?

Call a long-running Python rule containing various queries or MSI calls, or alternatively call multiple Python rules using a single iRODS connection (via N `rcExecMyRule` API calls).

### Expected behavior

`irodsServer` memory consumption remains near-constant across rule calls. Completing e.g. a python-rule-initiated query frees related resources (either immediately or at some memory usage threshold).

### Observed behavior (including steps to reproduce, if applicable)

`irodsServer` memory consumption increases after MSI calls and does not decrease. Completion of the rcExecMyRule API call does not free allocated server resources either: repeatedly calling (Python) rules using the same iRODS session eventually results in an OOM-kill for the server process handling those requests.

### Reproducing

For example, the following two rules are functionally identical: They both execute 1000 genqueries. However, by checking irodsServer memory consumption (`watch -n.1 'ps -o pid,start,rss,args --sort start_time,-rss -C irodsServer'`) the Python variant can be seen to cause memory usage to increase steadily over time (~3MB/s). In contrast, the memory usage of the iRODS rule language variant appears to remain constant (and lower).

```python
import time
import genquery
def dummy(rule_args, callback, rei):
    for i in range(1000):
        # Some query that has 0 results.
        for x in genquery.row_iterator('COLL_NAME', "COLL_NAME = 'unicorn'", genquery.AS_LIST, callback):
            pass
        time.sleep(0.01)
```

```
dummyR() {
    for (*i = 0; *i < 1000; *i = *i + 1) {
        foreach (*row in SELECT COLL_NAME WHERE COLL_NAME = 'unicorn') { nop; }
        msiSleep('0', '10000');
    }
}
```

Calling the same Python rule multiple times sequentially (via multiple `rcExecMyRule` API calls) multiplies memory consumption. Only closing the connection releases the allocated resources.

Another example:
A data object is repeatedly opened and closed. The close is expected to free the resources related to the handle.

```python
# (this assumes a data object /tempZone/home/rods/x.txt exists and is
# readable by the client)
import time
def dummy(rule_args, callback, rei):
    for i in range(10000):
        handle = callback.msiDataObjOpen('objPath=/tempZone/home/rods/x.txt', 0)['arguments'][1]
        callback.msiDataObjClose(handle, 0)
        time.sleep(0.01)
```

```
dummyR() {
    for (*i = 0; *i < 10000; *i = *i + 1) {
        msiDataObjOpen("objPath=/tempZone/home/rods/x.txt", *fd);
        msiDataObjClose(*fd, *status);
    }
}
```

**Comment by trel** [comment]
We have confirmed this behavior - we see the leaking.

We ran with the python rule engine plugin through valgrind, but valgrind was very unhappy.

Thinking through another way to get a leak report... otherwise, we're back to visual inspection...

**Comment by alanking** [comment]
It seems that, at time of writing, the version of Valgrind in the Ubuntu 16.04 Universe (3.11.0) has a limit on the size of a symbol. This can be exceeded (fairly easily) by "heavily templated C++ code" (characteristic of the python rule engine plugin).

The issue was reported here...
http://valgrind.10908.n7.nabble.com/Assertion-eltSzB-lt-ddpa-gt-poolSzB-failed-td56128.html

...and fixed in Valgrind 3.12.0.
https://bugs.kde.org/show_bug.cgi?id=359133

So I downloaded the Valgrind 3.15.0 tar file, extracted, built, and installed it...
```
$ valgrind --version
valgrind-3.11.0
$ wget https://sourceware.org/pub/valgrind/valgrind-3.15.0.tar.bz2
$ tar xjvf valgrind-3.15.0.tar.bz2
$ cd valgrind-3.15.0
$ ./configure
$ make -j
$ make install
$ valgrind --version
valgrind-3.15.0
```

This allowed me to run irodsServer as irods under Valgrind with PREP installed and configured:
```
$ cd /usr/sbin
$ valgrind --tool=memcheck --leak-check=full --trace-children=yes --num-callers=200 --time-stamp=yes --track-origins=yes --keep-stacktraces=alloc-and-free --freelist-vol=10000000000 --show-possibly-lost=yes --log-file=/var/lib/irods/valgrind_out_%p.txt ./irodsServer
```

I ran the genquery python rule so graciously provided by @cjsmeele and reduced the loop to 1 iteration. Here is the result of the agent process from the report:
```
==00:00:00:41.911 10675== LEAK SUMMARY:
==00:00:00:41.911 10675==    definitely lost: 181,162 bytes in 47 blocks
==00:00:00:41.911 10675==    indirectly lost: 140 bytes in 8 blocks
==00:00:00:41.911 10675==      possibly lost: 1,072 bytes in 2 blocks
==00:00:00:41.911 10675==    still reachable: 2,753,520 bytes in 3,611 blocks
==00:00:00:41.911 10675==         suppressed: 0 bytes in 0 blocks
```
Here is the full report: [prep_leak.txt](https://github.com/irods/irods/files/4077163/prep_leak.txt)

**Comment by d-w-moore** [comment]
Tried this as well, on the msiFreeBuffer suggestion from the chats, and it still leaks.
My invocation was: ` irule "myrule('10000', '<full-path-to-soe-data-object>')" null null`
watched with `ps -O rss -C irodsServer `
```
def myrule(a,c,e):                                                                   |#Test Rules
 for x in range(int(a[0])):                                                        |printHello { print_hello; }
  c.msiSleep('0','1000')                                                           |#zzz(*x) { writeLine('stdout',type(*x) }
  x = irods_types.RodsObjStat()                                                    |#
  c.msiFreeBuffer(x)                                                               |#
  y = c.msiObjStat(a[1],x)['arguments'][1]                                         |# These are sys admin rules for creating and deleting users and renaming
  c.msiFreeBuffer(y)                                                               |# the local zone.
  c.writeLine('serverLog',`x`)   
```

**Comment by alanking** [comment]
#4654 provides a change which appears to fix the "definitely lost" leak(s). There are still smaller leaks which can be addressed separately.

**Comment by trel** [comment]
this is proving elusive - bumping.

**Comment by alanking** [comment]
Using 4.2.10, I ran this test again to see where things stand in more recent versions. It seems the leaking is reduced, but there is still a significant "definitely lost" chunk:
```
==00:00:00:22.422 2000== LEAK SUMMARY:
==00:00:00:22.422 2000==    definitely lost: 82,386 bytes in 22 blocks
==00:00:00:22.422 2000==    indirectly lost: 102 bytes in 6 blocks
==00:00:00:22.422 2000==      possibly lost: 1,072 bytes in 2 blocks
==00:00:00:22.422 2000==    still reachable: 35,505,350 bytes in 5,815 blocks
==00:00:00:22.422 2000==         suppressed: 0 bytes in 0 blocks
```

Full report attached here: [valgrind_out_2000.txt](https://github.com/irods/irods/files/7583903/valgrind_out_2000.txt)

**Comment by alanking** [comment]
I managed to whittle down the leak down to this:
```
==00:00:00:36.715 8301== LEAK SUMMARY:
==00:00:00:36.715 8301==    definitely lost: 193 bytes in 8 blocks
==00:00:00:36.715 8301==    indirectly lost: 55 bytes in 2 blocks
==00:00:00:36.715 8301==      possibly lost: 1,072 bytes in 2 blocks
==00:00:00:36.715 8301==    still reachable: 34,645,112 bytes in 5,704 blocks
==00:00:00:36.715 8301==         suppressed: 0 bytes in 0 blocks
```
This is through a combination of https://github.com/irods/irods/pull/6034 and https://github.com/irods/irods_rule_engine_plugin_python/pull/90

Full report attached here: [valgrind_out_8301.txt](https://github.com/irods/irods/files/7645215/valgrind_out_8301.txt)

**Comment by trel** [comment]
nice.    once we get things merged and confirmed, that should be good enough for this release (4.2.11).

we'll create another issue to track the remaining work.

**Comment by alanking** [comment]
I created #6044 for the remaining leaks which need to be fixed. I think this can be checkboxed and closed (I can't do the checkboxes).

**Comment by trel** [comment]
awesome.   closing.
