### ISSUE TITLE
upgraded server has no default log rotation settings

### ISSUE THREAD

**Issue by trel** [irods/irods#4663]
### iRODS Version, OS and Version

4.2.7

### What did you try to do?

upgrade to 4.2.7 and see logs rotated

### Expected behavior

logs to be rotated by default

### Observed behavior (including steps to reproduce, if applicable)

logs were not rotated... need some default settings injected during upgrade if they don't exist

**Comment by kript** [comment]
Is there a suggested workaround for those of us up grading to 4.2.7 shortly?

**Comment by kript** [comment]
Actually, conversation here reveals were not quite clear whats meant by this - 4.1.X does log rotation, when upgrading to 4.2.x should this continue to work as it has before, or stop because the logs are in a new place?

**Comment by trel** [comment]
Upon reflection/testing - they do appear to be rotating as before in 4.2.

Logs in 4.2 are now in /var/lib/irods/log/ (as rodsLog*, rodsServerLog*, and reLog*) and still rotated and named as in 4.1 (by default, using a new name every 5 days).

This has been reworked in 4.3/master to use spdlog, syslog, and logrotate (see #4075).

@korydraughn Kory, can you confirm I've got this correct?

@ilarik, can you provide any context to the original upgrade issue you saw with logs?  Apologies if I've captured the story incorrectly.

---

Perhaps this issue should be recategorized to only apply to upgrades from 4.2 to 4.3/master?  Need to test whether this block of json (perhaps set to `info`, rather than `warn`) is being properly injected into `server_config.json` on upgrade from 4.2 to 4.3/master.
https://github.com/irods/irods/commit/17b218fb5fd1ce7cde48e4018b30cd946815678a#diff-a54752d7570607f8549d3c94f5e703cbR21
```
    "log_level": {
        "agent": "warn",
        "api": "warn",
        "authorization": "warn",
        "database": "warn",
        "legacy": "warn",
        "microservice": "warn",
        "network": "warn",
        "resource": "warn",
        "rule_engine": "warn",
        "server": "warn"
    },
```

**Comment by korydraughn** [comment]
You are correct. 4.3's logging was reworked to use syslog, etc. 4.2's logs are still under /var/lib/irods/log.

The log levels should be injected correctly. The code below was merged following the logging reimplementation. This code runs every time the server is started/restarted.
https://github.com/irods/irods/blob/b2f12f3d311ebfec776868d6fb9c28c9fd0b1dbb/scripts/irods/controller.py#L35-L65

**Comment by trel** [comment]
Ah, very good.   I thought those 'warn's seemed wrong, 'info' is right.

And the rotation logic itself hasn't changed in 4.2, as far as I know.

Will leave this open for a few days, but then can close if nothing new comes to light.

**Comment by trel** [comment]
Closing.   Nothing to see here...
