### ISSUE TITLE
add new msiTouch microservice

### ISSUE THREAD

**Issue by trel** [irods/irods#4669]
- [x] master
- [x] 4-2-stable
-----

## Feature

related to itouch https://github.com/irods/irods_client_icommands/issues/16

msiTouch( logicalPath, update, time, sourceResc, targetResc )
 - logicalPath (required) - STR_MS_T - iRODS path of data object replica(s) to be touched
 - update (optional) - STR_MS_T - update 'access' time, 'modify' time, or 'both' (default='both')
 - time (optional) - STR_MS_T - if set, set update time to pattern of 'YYYYMMDDhhmmss' or 'now' (default='now')
 - sourceResc (optional) - STR_MS_T - if set, set update time from replica timestamps on this resource
 - targetResc (optional) - STR_MS_T - if set, only touch timestamps for replica on this resource (default=touch all replicas)

 note: return ERROR if 'time' and 'sourceResc' are both set

----
### reproduces/provides similar functionality to the unix touch command:

duplicate settings from another replica
 - `touch -r FROMFILE TOFILE`

update atime to now
 - `touch -a FILE`

update atime to string
 - `touch -a -t YYYYMMDDhhmmss FILE`

update mtime to now
 - `touch -m FILE`

update mtime to string
 - `touch -m -t YYYYMMDDhhmmss FILE`

update both to now
 - `touch FILE`

update both to string
 - `touch -t YYYYMMDDhhmmss FILE`

**Comment by korydraughn** [comment]
The [irods_console](https://github.com/korydraughn/irods_console/blob/master/src/touch.cpp) project has a version of `touch` that might be helpful for this.

**Comment by trel** [comment]
Ah, I knew that was somewhere :)

**Comment by trel** [comment]
We decided to support `-s, --seconds-since-epoch` in the `itouch` command.   This is intentional to avoid timezone shenanigans/pitfalls implicit in using the `YYYYMMDDhhmmss` format.  Should consider a similar decision here.

**Comment by d-w-moore** [comment]
Do we want to skip testing this under Python REP ? It currently fails [here](https://github.com/irods/irods/blob/5648b74805edea97830dbaf66dc524cca7508898/scripts/irods/test/test_all_rules.py#L1087) for Python RE plugin test, because  during that test Python RE is set up as the only active one.

**Comment by trel** [comment]
ah, sure, let's skip it unless irods rule language for now

**Comment by d-w-moore** [comment]
I'll get a pull request together as I discover any others needing skipping.
