### ISSUE TITLE
iquest fails when select is used in argument string

### ISSUE THREAD

**Issue by AJdeMooij** [irods/irods#4697]
- [x] master
- [x] 4-2-stable
--------

If the character sequence "select" (in lower case) is used in an iquest command, iquest fails with status -110700 (no column names found).

``` bash
$ iquest "SELECT COLL_NAME WHERE COLL_NAME = 'safe_word'"
CAT_NO_ROWS_FOUND: Nothing was found matching your query

$ iquest "SELECT COLL_NAME WHERE COLL_NAME = 'SELECT'"
CAT_NO_ROWS_FOUND: Nothing was found matching your query

$ iquest "SELECT COLL_NAME WHERE COLL_NAME = 'select'"
ERROR: iquest Error: queryAndShowStrCond failed status = -1107000 NO_COLUMN_NAME_FOUND
```

Further testing shows that escaping any character in the word 'select', except for the first, can be used as a workaround:

``` bash
$ iquest "SELECT COLL_NAME WHERE COLL_NAME = '\select'"
ERROR: iquest Error: queryAndShowStrCond failed status = -1107000 NO_COLUMN_NAME_FOUND

$ iquest "SELECT COLL_NAME WHERE COLL_NAME = 's\elect'"
CAT_NO_ROWS_FOUND: Nothing was found matching your query

$ iquest "SELECT COLL_NAME WHERE COLL_NAME = 'selec\t'"
CAT_NO_ROWS_FOUND: Nothing was found matching your query
```

The problem does not occur when using general queries in irules.

**Comment by trel** [comment]
part of https://github.com/irods/irods/issues/3902

**Comment by trel** [comment]
workaround is to use lowercase `select` in the general query - https://github.com/irods/irods/issues/3613#issuecomment-317453126

**Comment by trel** [comment]
moving this to 4.2.9 - we can fix this on the client side.

**Comment by logansjohnson** [comment]
This also happens with "insert" within an IN paramater but not with simply a =, the same escaping trick @AJdeMooij suggested works here as well.  Thanks @AJdeMooij ! 

`$ iquest "select COLL_NAME WHERE COLL_NAME IN ('insert')"
 ERROR: iquest Error: queryAndShowStrCond failed status = -816000 CAT_INVALID_ARGUMENT`

`$ iquest "select COLL_NAME WHERE COLL_NAME = 'insert'"
CAT_NO_ROWS_FOUND: Nothing was found matching your query`

**Comment by erwinvanwieringen** [comment]
Contrary to what is stated above, i think the problem also occurs when using the general query microservices. This can be shown by using the test rulemsiMakeGenquery.r rule:

    $ irule -r irods_rule_engine_plugin-irods_rule_language-instance -F rulemsiMakeGenQuery.r "*Coll='/tempZone/home/rods/non_existing/%%'"
    Number of files in /tempZone/home/rods/non_existing/%% is 0 and total size is 0

    $ irule -r irods_rule_engine_plugin-irods_rule_language-instance -F rulemsiMakeGenQuery.r "*Coll='/tempZone/home/rods/select/%%'"
    remote addresses: 131.224.35.42 ERROR: rcExecMyRule error.  status = -1107000 NO_COLUMN_NAME_FOUND
    Level 0: DEBUG: execMicroService3: error when executing microservice
    line 11, col 2
      msiMakeGenQuery("DATA_ID, DATA_SIZE",*Condition,*GenQInp);
      ^

I also had this problem when using the genquery python module. Does this suggest that the problem cannot be fixed on the client side? And would it maybe help to change the SELECT string in the  _makeQuery function in genQueryMS.cpp to lowercase?

**Comment by PaulVanSchayck** [comment]
We also just stumbled upon this, and spent a few hours troubleshooting this. Also a case where a filename contained "select" in the filename. And was later inserted into a query.

In this case using the python rule engine to create the genquery. Also there, just like in @erwinvanwieringen case, the `Query` class is using msiMakeGenQuery() internally. So, I've no way to include the lowercase `select` at the start of the query already. 

Really can't see a workaround right now. Indeed changing `SELECT` to `select` in _makeQuery() in genQueryMS.cpp may be a solution. Not entirely sure, and not sure about implications

**Comment by trel** [comment]
That is compelling.  We'll talk through the implications of changing this to use lowercase.

https://github.com/irods/irods/blob/6b03483bb84487bc724a0a44f62e80a2582cb02c/server/re/src/genQueryMS.cpp#L200-L210

**Comment by trel** [comment]
we'll lowercase.   thanks all.

**Comment by PaulVanSchayck** [comment]
Thanks Terrell. That's nice :) The workaround we have now is ugly. I'll post it once it's in our public github. 

May I also echo the need for a proper genquery parser in 4.3.0. While testing this issue further, I also saw a number of other weird corner cases when dealing with quotes inside of quotes.

**Comment by trel** [comment]
Definitely - we have it implemented and mostly/completely working against master for https://github.com/irods/irods/issues/3902 - it is slated for 4.3.0.
