### ISSUE TITLE
Add ability to modify any R_DATA_MAIN column with 'iadmin modrepl'

### ISSUE THREAD

**Issue by alanking** [irods/irods#4740]
- [x] master
- [x] 4-2-stable
---
## Feature

`isysmeta` should be able to modify any column for a given row of R_DATA_MAIN. As such, the command would require the following to be provided:

- subcommand (mod, ls, etc.)
- path to data object (or data id?)
- replica number or hierarchy/leaf resource
For mod:
- column name (e.g. DATA_STATUS)
- the value to inject

The motivation for this feature is the need for the ability for administrators to modify replica status in the event that intermediate replicas (#4343) cannot mark themselves as good or stale on close. #4331 should handle this in the future, but a direct modification of the catalog could be a helpful tool regardless.

**Comment by trel** [comment]
I'd suggest that maybe there should be no default behavior (aka replica 0).

Force the admin to know/mean what they're doing.

**Comment by alanking** [comment]
Agreed. I've adjusted the description to remove the suggestion of a default value for replica number and separated the requirement of column name and value for the mod subcommand only. Thanks!

**Comment by alanking** [comment]
`isysmeta` uses `rcModDataObjMeta` which does not require admin privileges. As such we are tweaking this slightly to be a new `iadmin` subcommand called `modrepl`. Usage:
```
iadmin modrepl logical_path [ --replica_number, -n | --resource, -R ] ATTR_NAME VALUE
```
The replica number or resource hierarchy will be required in order to specify a row to modify. ATTR_NAME will be the GenQuery attribute to modify (e.g. `DATA_REPL_STATUS` -- maps to column `data_is_dirty`) and VALUE will be the value to insert in that column. The `ADMIN_KW` will be used to enforce permissions

**Comment by trel** [comment]
Related work will involved updating 'iadmin ls' to present the current information / GenQuery attributes for a particular logical_path / replica.

Together, these will provide tools for both inspection and modification of replica information to an administrator.
