### ISSUE TITLE
iquest should return either zero or CAT_NO_ROWS_FOUND, not both

### ISSUE THREAD

**Issue by bh9** [irods/irods#4745]
- [x] main
- [x] 4-2-stable
--------

### iRODS Version, OS and Version
4.1.12 on Ubuntu 12.04

### What did you try to do?
construct an iquest which returns nothing

### Expected behavior
iquest returns one of 
1. an error code along with the provided stderr message
2. success and empty stderr
3. an error message which makes it clear that there was success even though there's no output (e.g. CAT_SUCCESS_BUT_WITH_NO_INFO, -819000)

### Observed behavior (including steps to reproduce, if applicable)
iquest returns 0, but sends the following to stderr:
`CAT_NO_ROWS_FOUND: Nothing was found matching your query`  
  
  
The standard unix approach is to choose option 1, e.g.
```
~$ grep fail .irods/irods_environment.json
~$ echo $?
1
```
where irods_environment.json doesn't have anything matching fail, so grep returns 1 (an error) rather than 0. From grep's man page:
```
EXIT STATUS
       The  exit status is 0 if selected lines are found, and 1 if not found.  If an error occurred the exit status
       is 2.  (Note: POSIX error handling code should check for '2' or greater.)
```

**Comment by trel** [comment]
Agreed, we should go with option 1...

`iquest` should have a return code of 1 when `CAT_NO_ROWS_FOUND`.
