### ISSUE TITLE
iRODS should fail to create collection named ".."

### ISSUE THREAD

**Issue by tedgin** [irods/irods#4750]
- [x] master
- [x] 4-2-stable
------
### iRODS Version, OS and Version

iRODS 4.1.10, CentOS 7

### What did you try to do?

One of our users attempted to create a collection named `..`.  

### Expected behavior

I expected the user to receive an error.

### Observed behavior (including steps to reproduce, if applicable)

The collection was created without error, and subcollections and data objects were added to it.  On the resource servers, all hosting `unixfilesystem` resources, the `..` was interpreted as the parent directory. This means that all of the files were placed in the wrong spot.  Subsequent attempts to work with the data objects all failed.

I don't know how the user created this. I couldn't using iCommands.  I'm guessing the user was using an application built on Jargon or python-irodsclient. 

A check should be made on the server side to prevent `..` collections from being created.

**Comment by d-w-moore** [comment]
Confirmed this behavior also occurs in iRODS 4.2.7 under Ubuntu 16.04

**Comment by trel** [comment]
How did you reproduce it?

**Comment by d-w-moore** [comment]
The following script reproduces it - just install the python irods client and run the following as the rods admin:
`python dotdot.py '..'`


Where the script `dotdot.py` as detailed in the last part of this comment.
You can then see in response to an ` ils -l `:
```
/tempZone/home/rods:
  C- /tempZone/home/rods/..
```  
and `iquest "select COLL_ID,COLL_NAME where COLL_NAME like '%/rods%'"` will show
``` 
------------------------------------------------------------
COLL_ID = 10020
COLL_NAME = /tempZone/home/rods/..

```
```
#!/usr/bin/env python2
# 'dotdot.py'
import os
import sys
import ssl
import irods.exception
import unittest
import time
from sys import argv

from irods.session import iRODSSession


try:
    env_file = os.environ['IRODS_ENVIRONMENT_FILE']
except KeyError:
    env_file = os.path.expanduser('~/.irods/irods_environment.json')
ssl_context = ssl.create_default_context( purpose=ssl.Purpose.SERVER_AUTH,
                                          cafile=None, capath=None, cadata=None)
ssl_settings = {'ssl_context': ssl_context}
session = iRODSSession(irods_env_file=env_file)

if __name__ == '__main__':

   home_col = "/" + session.zone + "/home/" + session.username 

   if len(sys.argv) > 1:
       relpath = sys.argv[1]
       session.collections.create( home_col + "/" + sys.argv[1] )
```

**Comment by d-w-moore** [comment]
Also, and probably related:
```
$ ils -l
/tempZone/home/rods:

$ iquest "select COLL_ID,COLL_NAME where COLL_NAME like '%/rods%'"
COLL_ID = 10011
COLL_NAME = /tempZone/home/rods
------------------------------------------------------------
COLL_ID = 10012
COLL_NAME = /tempZone/trash/home/rods
------------------------------------------------------------

$ python dotdot.py '/'

$ ils -l
/tempZone/home/rods:
  C- /tempZone/home/rods/  

$ iquest "select COLL_ID,COLL_NAME where COLL_NAME like '%/rods%'"
COLL_ID = 10011
COLL_NAME = /tempZone/home/rods
------------------------------------------------------------
COLL_ID = 10016
COLL_NAME = /tempZone/home/rods/
------------------------------------------------------------
COLL_ID = 10017
COLL_NAME = /tempZone/home/rods//
------------------------------------------------------------
COLL_ID = 10012
COLL_NAME = /tempZone/trash/home/rods
------------------------------------------------------------
```

**Comment by trel** [comment]
Okay, so the server needs to perform a few additional sanity checks on the incoming request.

**Comment by d-w-moore** [comment]
In summary, until this is fixed, there's still the possibility (inclusive from iRODS 4.1.10  and latest, 4.2.7 , possibly others) of creating collections with rogue names.  ("Rogue" because icommands will not address them in the same way the client created them; `iput` and `imv`  will process path elements such as ".." in the same way the Unix shell would do it.)
One way to correct that  is with the script included here. (Lop off the ".txt" extension and `chmod +x the` script before running)
[find_and_rename_collection.py.txt](https://github.com/irods/irods/files/4281864/find_and_rename_collection.py.txt)
