### ISSUE TITLE
REPF should support skipping operations

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#4752]
- [x] master
- [x] 4-2-stable
---
## Feature
In the current iRODS implementation, the most common [flow of operations](https://docs.irods.org/4.2.7/plugins/dynamic_policy_enforcement_points/#flow-control) is:
1. Pre-PEP
2. Operation
3. Post-PEP

The REPF needs to grow the ability to skip steps. This is required in order to implement features such as hard-links.

### REPF Changes
- New Code: `RULE_ENGINE_SKIP_OPERATION`.
- The new code should only be returned from Pre-PEPs.
- If a Pre-PEP returns the code, the following occurs:
  + Steps 2 and 3 are skipped.
  + The **finally**-PEP is executed immediately.

**Comment by trel** [comment]
two things...

1 - returning `RULE_ENGINE_SKIP_OPERATION` from non pre-PEPs should not be allowed?

2 - need to create an issue to add the `_finally` PEPs

**Comment by korydraughn** [comment]
If a plugin does return the skip code from a non pre-PEP, what should happen?

Based on the current implementation, it is likely that the skip code would be interpreted as success and things would operate just fine (on the server-side).

**Comment by trel** [comment]
I think a `RULE_ENGINE_SKIP_OPERATION` returned from a non-pre-pep should be an error.

Throw a generic `RULE_ENGINE_ERROR` with a helpful message?   The administrator should definitely be told what's going on and be given enough information to fix it.
