### ISSUE TITLE
iRODS, POSIX, and open(O_RDONLY | O_TRUNC)

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#4782]
- [x] master
- [x] 4-2-stable
---
## Question
What should iRODS do if a client attempts to open an existing data object with `O_RDONLY | O_TRUNC`?

The following statements are from the [Linux Programmer's Manual for open()](http://man7.org/linux/man-pages/man2/open.2.html):
```bash
O_TRUNC
              If the file already exists and is a regular file and the
              access mode allows writing (i.e., is O_RDWR or O_WRONLY) it
              will be truncated to length 0.  If the file is a FIFO or ter‐
              minal device file, the O_TRUNC flag is ignored.  Otherwise,
              the effect of O_TRUNC is unspecified.

NOTES
       The (undefined) effect of O_RDONLY | O_TRUNC varies among
       implementations.  On many systems the file is actually truncated.
```

Based on the **NOTES** section, POSIX leaves the behavior of `open()` up to the implementation to do whatever it wants when given this combination of flags.

Truncating a data object even though it was opened in read-only mode seems incorrect. iRODS should clearly specify the behavior of this operation.

## Possible Answer
iRODS returns an error if this combination of open flags are encountered.

**Comment by jasoncoposky** [comment]
+1 for an error, data loss should not be possible for a read-only data object.

**Comment by trel** [comment]
agreed, error.
