### ISSUE TITLE
irmdir should remove collection even if a sibling exists

### ISSUE THREAD

**Issue by tsmeele** [irods/irods#4788]
- [x] master
- [x] 4-2-stable
------

### iRODS Version, OS and Version
iRODS 4.2.7 Centos 7

### What did you try to do?
[vagrant@provider ~]$ echo hello > testfile
[vagrant@provider ~]$ imkdir foo
[vagrant@provider ~]$ imkdir foot
[vagrant@provider ~]$ iput testfile foot/testfile
[vagrant@provider ~]$ irmdir foo
Failed to remove [/testZone/home/rods/foo]: Collection is not empty

### Expected behavior
foo is removed

### Observed behavior (including steps to reproduce, if applicable)
error 'collection not empty'

**Comment by tsmeele** [comment]
workaround exists:
imv foo bar
irmdir bar

**Comment by trel** [comment]
a substring bug.

**Comment by tsmeele** [comment]
don't spoil the wonders for the developers ;)
