### ISSUE TITLE
Returning RULE_ENGINE_SKIP_OPERATION from non-pre-PEPs should generate an error

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#4800]
- [x] master
- [x] 4-2-stable
---
`RULE_ENGINE_SKIP_OPERATION` only makes sense when returned from a pre-PEP.

Returning this code from any other PEP should at least cause the server to log it as an error. This allows users to continue to use the system without disruption.

Should doing this cause errors to be returned to the client?

**Comment by trel** [comment]
I don't think this should get back to the client.

This represents a configuration error in the server... an admin should see a high quality ERROR in the log and take action.
