### ISSUE TITLE
locking/disabling iRODS user accounts

### ISSUE THREAD

**Issue by carsten-jahn** [irods/irods#4804]
## Feature

A feature for temporarily or permanently disabling an iRODS user, without deleting the account, would be useful in my opinion. The user would be prevented from logging in or doing any work in iRODS until the account is enabled again.

Of course the iRODS password could be set to something unknown, but if PAM authentication is used, this is pointless.

I searched the documentation, e.g. `iadmin moduser`, but did not find anything related to such a feature. But please comment if I overlooked it.

**Comment by jasoncoposky** [comment]
@carsten-jahn please reference this policy I developed for DIRISA:
https://github.com/jasoncoposky/irods_deployment_csir/blob/master/policy/prevent_disabled_users.re

**Comment by datavisyn-ro-b** [comment]
Hi @jasoncoposky , thanks for the policy example, I does exactly what I wanted...!  (When testing it, I found that probably the PEP used is not supported on the iRODS version that we're running on this particular instance (still 4.1.11) and I had to remove users from iRODS groups instead.)

**Comment by carsten-jahn** [comment]
Hi @jasoncoposky , thanks for the policy example, I does exactly what I wanted...! (When testing it, I found that probably the PEP used is not supported on the iRODS version that we're running on this particular instance (still 4.1.11) and I had to remove users from iRODS groups instead.)
