### ISSUE TITLE
Users of type groupadmin can use igroupadmin to modify members in groups they do not belong

### ISSUE THREAD

**Issue by darthtux** [irods/irods#4823]
I created a user of type groupadmin and was able to user igroupadmin to add my user to a group that I did not belong.  From the documentation on page:  https://docs.irods.org/master/icommands/groupadmin/#igroupadmin  This should not be possible.

> users of type 'groupadmin' can atg and rfg for groups they are members of.

    [darthtux@echo-ln ~]$ iuserinfo darthtux
    name: darthtux
    id: 10018
    type: groupadmin
    zone: echo
    info: 
    comment: 
    create time: 01583850196: 2020-03-10.09:23:16
    modify time: 01585057256: 2020-03-24.08:40:56
    member of group: darthtux 
    member of group: public

    [darthtux@echo-ln ~]$ igroupadmin atg proja darthtux

    [darthtux@echo-ln ~]$ iuserinfo darthtux
    name: darthtux
    id: 10018
    type: groupadmin
    zone: echo
    info: 
    comment: 
    create time: 01583850196: 2020-03-10.09:23:16
    modify time: 01585057256: 2020-03-24.08:40:56
    member of group: darthtux
    member of group: public
    member of group: proja

**Comment by trel** [comment]
Was there anyone else in the `proja` group already?

If not, then I believe this is behaving as expected...

From https://docs.irods.org/master/icommands/groupadmin/#mkgroup:

> (when the group is empty groupadmins are allowed to add themselves.)

**Comment by darthtux** [comment]
There was not anyone else in proja.  Thank you very much for your answer!
