### ISSUE TITLE
Add library that provides a standard way to become a different user

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#4836]
- [x] master
- [x] 4-2-stable
---
## Feature
When implementing new API plugins / Rule Engine plugins / etc., sometimes the plugin needs to temporarily become a different user to carry out operations.

iRODS should provide a library that simplifies switching user identities in a safe way.

### Proposed API - scoped_client_identity (or scoped_client_username)
The API works exactly like `std::lock_guard` from C++11.

`scoped_client_identity` will take in a `rsComm_t` and the name of the user to become. It then sets `rsComm_t::clientUser::userName` to the new username. On destruction, the original username is restored.

This allows developers to limit the username substitution to the smallest scope possible. Even when exceptions are thrown, the username will always be restored.
```c++
void delay_server(rsComm_t& comm)
{
    // The delay server is retrieving information to execute a rule.
    // "comm" is currently using the service account to do this.
    const auto info = get_rule_info(comm);

    {
        // Become the user (i.e. info.username) that scheduled the rule.
        irods::experimental::scoped_client_identity sci{comm, info.username};
        execute_rule_as_user(comm, info.rule);
    }

    // "comm" has already been restored to the service account's
    // username at this point.
    do_more_work(comm);
}
```

**Comment by trel** [comment]
I like `scoped_client_identity` over `scoped_client_username`.
