### ISSUE TITLE
`isysmeta ls -l` and RESC_NAME (not!) being EMPTY_*

### ISSUE THREAD

**Issue by mcast** [irods/irods#4854]
- [x] master
- [x] 4-2-stable
-------

## Support request
I'm looking at how my code uses `isysmeta ls -d $ifile` and I'm suspicious of the returned `resc_name` field, after reading https://docs.irods.org/4.2.7/getting_started/upgrading/#updating-stale-information-in-unused-catalog-columns .

The essence of the question is, can I continue to rely on the output under iRODS 4.2.7 ?
* Is it taking a DATA_RESC_ID and looking up the name of the corresponding resource?
* Or is it fetching a deprecated field and only appearing to work correctly?

My suspicion is not helped by the fact that when I look at a newly installed 4.2.7 zone, I don't see any those EMPTY_* values but I do see apparently 4.1-compatible output values.  I see #3853 but possibly I have misunderstood something about the deprecation of the fields? I haven't become familiar with the underlying data schema and was hoping I would not need to do that - please let me know if you think that is unreasonable of me. Also I haven't looked at the source, and trying to justify this to myself on the grounds of efficiency. 🙄 

I looked at https://docs.irods.org/4.2.7/icommands/user/#isysmeta but it doesn't say much about the providence of the returned data.

-- 
Thanks & keep well,
m

**Comment by trel** [comment]
at first glance, we're resolving it transparently from the `resc_id` and it is dependable.

will follow up with more confidence.

**Comment by mcast** [comment]
That would certainly be the nice backwards-compatible way to do it - thank you.

Possibly a useful outcome of this ticket would be more detail in the deprecation note, about which views of the data are valid and which aren't?

**Comment by trel** [comment]
definitely

**Comment by mcast** [comment]
Does this backward-compatibility also apply to the iquest DATA_RESC_HIER field?

This is the main item on my list for "things known to need fixing before moving to 4.2.7" but I have not yet seen that it works any differently in the two 4.2.7 zones I can see.

I was expecting to need to switch to DATA_RESC_ID , because it's only the tail of DATA_RESC_HIER that I need. But also it would be possible to reconstruct the whole DATA_RESC_HIER from DATA_RESC_ID...

**Comment by trel** [comment]
Yes, everything should be derived from `resc_id` now.    And we traverse the hierarchies where needed internally.   But yes, you're asking all the right questions, keep going.   We'll get it documented.

**Comment by mcast** [comment]
Well it looks like you've done a great chunk of my work for me already 😀 so all I really need is to be sure that I'm not using something that's broken.

Is there any value (e.g. for efficiency on iCAT, or ease of future upgrades) in my migrating to `resc_id` ?

My code uses only icommands and [baton](https://github.com/wtsi-npg/baton) for the front door to iRODS, plus an NFS back door to files in `unixfilesystem` vaults..

**Comment by trel** [comment]
I don't think there's an immediate need, but you might want to not depend on legacy columns for the long term.

I'd estimate you can worry about this later when there are no major migrations afoot or fires to be put out (as if).

**Comment by trel** [comment]
Also note, baton may, itself, not need to be maintained in the long term.

See `istream` in 4.2.8+ (https://github.com/irods/irods/issues/4626)

**Comment by trel** [comment]
We moved to `resc_id` for performance, the string comparisons were brutal.   Now we're comparing against indexed `int`s, much better.

**Comment by mcast** [comment]
> I don't think there's an immediate need, but you might want to not depend on legacy columns for the long term.

Thank you, this should take some urgency out / leave flexibility in our upgrade process.

> Also note, baton may, itself, not need to be maintained in the long term.
> 
> See istream in 4.2.8+ (#4626)

I see the [current interface](https://github.com/irods/irods_client_icommands/blob/38bd0904cef079f57615c62f93819df97e8a4eac/src/istream.cpp) offers read/write of data, and I hope it will suit us to look at that for something like an https backend. Latency of open & seek would be a great concern.

I doubt we would ever use it for writing, because we need great certainty that the put data is what was generated and this is done in batch processing. Our simplified workflow is
1. generate data, option to note its md5 during production
2. `iput` the data to a temporary filename
3. apply metadata (for which baton is useful)
4. double-check the md5 (currently doesn't consult the early value from 1.)
5. `imv` file into its resting place

Then it gets read back for various purposes, or perhaps replaced if there is re-work.

Of the baton tool set, the parts I use are `baton-list` and `baton-metamod`.

> We moved to resc_id for performance, the string comparisons were brutal. Now we're comparing against indexed ints, much better.

That makes perfect sense, it just wasn't obvious to me that the legacy external presentation was being deliberately preserved rather than somehow failing to be marked invalid.

On the subject of metadata, performance and ints... I wrote #4855 in case you find the information or idea useful.

**Comment by kript** [comment]
> Also note, baton may, itself, not need to be maintained in the long term.
> 
> See `istream` in 4.2.8+ (#4626)

I think you meant [tears ](https://github.com/whitwham/tears)rather than baton, there?

**Comment by trel** [comment]
ah, yes, indeed.

**Comment by trel** [comment]
Will document a bit more about the usage of `resc_id`.
