### ISSUE TITLE
itrim - deprecate "-N" option (i.e. minimum number of replicas to keep)

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#4860]
- [x] 4-2-stable
---
## Discussion
`itrim` is required when a user wants to delete replicas. The current implementation allows the user to specify the minimum number of replicas to keep. This seems wrong. If a user needs to use `itrim`, then it is expected that that user knows which replicas they want to delete.

`itrim` should not be allowed to make decisions about which replicas to delete. This can lead to unexpected data loss if the wrong replicas are deleted. Therefore, users should be required to specify exactly which replicas to delete.

**Comment by trel** [comment]
Yes, please mark the `-N` option as deprecated - eventually, there will no longer be the option of 'trimming down to N' replicas.   At that time, `-N` will be removed.
