### ISSUE TITLE
rsDataObjCopy() fails to close source replica on failure to create destination replica

### ISSUE THREAD

**Issue by trel** [irods/irods#4862]
- [x] master
- [x] 4-2-stable
------

## Bug

In investigating the original request below... this has been reclassified as a bug.

The lack of proper cleanup in `rsDataObjCopy()` allowed the backstop value of open file descriptors to be hit. The `NUM_L1_DESC` mentioned below does not need to be changed - it is serving its purpose.

## Feature

The value for `NUM_L1_DESC` needs to be a configuration knob available in `server_config.json`'s `advanced_settings`

https://github.com/irods/irods/blob/e3871db09bd6307b7709a5a438cfc2ad09efc357/server/core/include/objDesc.hpp#L24

It is a limiting factor in large installations with multiple concurrent users and jobs.

Additional associated settings may need to be pulled out at the same time for the other layers involved. (NUM_FILE_DESC is also 1026)

https://github.com/irods/irods/blob/e3871db09bd6307b7709a5a438cfc2ad09efc357/server/core/include/fileOpr.hpp#L16

Separately, the default value could/should be increased.

**Comment by kript** [comment]
Could you document what this does, please? I'm not sure if it applies to us or not!

**Comment by trel** [comment]
After a bit more investigation and digging, it appears it may not be helpful to pull this out and create a new configuration knob.  (As the adage goes, "1026 should be enough for anybody").

We suspect, but have not yet concluded, that the offending installation has implemented server-side policy that is opening files without closing them cleanly.  This would lead to large recursive put and copy operations running out of file descriptors.  We think (and are working to prove) that well-behaved policy only needs the number of defined file descriptors to be large enough to support any concurrently open files (which, is usually... one).

Also note that increasing this number makes every irodsAgent a bit more heavyweight, so we'd like to avoid it if we can.

**Comment by alanking** [comment]
Steps to reproduce:
1. Make a big set of files (small or large files) - more than 1023.
2. Do not set a default resource. I did this by not calling msiSetDefaultResc from acSetRescSchemeForCreate in my rulebase and being a rodsuser with no default resource set in the irods_environment.
```
# ienv | grep version
irods_version - 4.2.7
# ls -l lots | wc -l
2002
# iput -R dst-pt -r lots iput_lots
Running recursive pre-scan... pre-scan complete... transferring data...
# icp -r iput_lots icp_lots
remote addresses: 127.0.0.1 ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/mob/iput_lots/file_0000. status = -32000 status = -32000 SYS_INVALID_RESC_INPUT
...
remote addresses: 127.0.0.1 ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/mob/iput_lots/file_1022. status = -32000 status = -32000 SYS_INVALID_RESC_INPUT
remote addresses: 127.0.0.1 ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/mob/iput_lots/file_1023. status = -18000 status = -18000 SYS_OUT_OF_FILE_DESC
...
remote addresses: 127.0.0.1 ERROR: getCollUtil: getDataObjUtil failed for /tempZone/home/mob/iput_lots/file_2000. status = -18000 status = -18000 SYS_OUT_OF_FILE_DESC
```
The `icp` will fail with `SYS_OUT_OF_FILE_DESC`. Note the lack of a specified resource. The first 1,023 files will fail with `SYS_INVALID_RESC_INPUT`. After this, the agent will run out of L1 descriptors. The lack of default resource is not specifically what triggers this issue - if 1,023 destination data objects fail to be created, this is the result on any additional data objects.

**Comment by trel** [comment]
So, a fix for this scenario in the server code would clean up those opened L1 descriptors, and then report all 2002 failed copies back to the client since each data object copy had `SYS_INVALID_RESC_INPUT`.

**Comment by d-w-moore** [comment]
Test passes for NREP but fails for PREP. Possibly a blocker for 4.2.8, or should we skip? 
Seeing as my attempt at fixing using this in `core.py`:
```
  filemode = ('a' if 'python' in self.plugin_name else 'w')
```
at/near this line:
https://github.com/irods/irods/commit/2c973857ca59eed12126f5b2a4fbfc7496273fed#r39160755

wasn't quite enough to make this test pass, I'm officially asking for help from mr @alanking :)

**Comment by d-w-moore** [comment]
ah yes, need to remove the unlink
of course.
