### ISSUE TITLE
parallel transfers not consulting the values held in hosts_config.json

### ISSUE THREAD

**Issue by trel** [irods/irods#4866]
- [x] master
- [x] 4-2-stable
------

### iRODS Version, OS and Version

4.2.7

### What did you try to do?

parallel transfer to a resource on a server with a name defined in `hosts_config.json`

### Expected behavior

file appears on correct resource

### Observed behavior (including steps to reproduce, if applicable)

```
$ iput /tmp/random-file
remote addresses: 10.225.160.101 ERROR: connectToRhostPortal: connectTo Rhost dtn6 port 20068 error, status = -305113
remote addresses: 10.225.160.101 ERROR: putUtil: put error for /tempZone/home/testuser/random-file, status = -305113 status = -305113 USER_SOCK_CONNECT_ERR, No route to host
```

`dtn6` was not correctly dereferenced from the local `hosts_config.json`.

Note that small files (<32MB) work correctly when sent to the same location.

**Comment by trel** [comment]
From internal discussion...

> https://github.com/irods/irods/blob/master/server/core/src/miscServerFunct.cpp#L246   
>
> get_canonical_name could perhaps get a bit smarter as well

**Comment by trel** [comment]
@kript ping

**Comment by kript** [comment]
Great, thanks!. Is there a workaround for 4.2.7?

**Comment by trel** [comment]
apparently, parallel transfer has *never* consulted the local `hosts_config.json` information... so, the workaround would be to get the alias information into either `/etc/hosts` on each server, or DNS proper.

**Comment by bh9** [comment]
Then this isn't the issue we're seeing, because both `/etc/hosts` and DNS have the correct values

**Comment by trel** [comment]
Have also just noted that any additional aliases in `/etc/hosts` are not walked (we use the first `addrinfo`)...

This could be a separate issue to be created (or a design feature, aka, how do we pick one, if not the first, how do we retry?).

http://man7.org/linux/man-pages/man3/getaddrinfo.3.html

> The getaddrinfo() function allocates and initializes a linked list of
       addrinfo structures, one for each network address that matches node
       and service

If the first entry in `/etc/hosts` matches the hostname being used, then it should resolve correctly.  Will discuss more in a call soon as well.
