### ISSUE TITLE
Add library that increases operational durability

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#4867]
- [x] master
- [x] 4-2-stable
---
## Feature
The majority of iRODS API calls do not provide any durability. When an operation fails, the clients and servers do not attempt to retry the operation. Having a retry mechanism that can help with this situation is necessary.

## Proposed API - with_durability
The API takes a set of options and a function-like object. It then invokes the function-like object and on failure, continues to retry based on the options passed.

**Options** include the following:
- retries [integer]
- delay [duration]
- delay multiplier [float]

The API must be generic so that it can be applied to many situations. To accomplish this, the function-like object must return an indicator that instructs the API of what happened. The indicator value is also returned from `with_durability`. This allows the application to respond in an appropriate manner.

**Indicator** values include the following:
- ready: The function-like object was never invoked.
- success: The function-like object succeeded. Does not continue to retry.
- failure: The function-like object failed. Continues to retry.
- exception: The function-like object failed with an exception. Continues to retry.
- stop: The function-like object was stopped manually. Does not continue to retry.

### Example
```c++
// On failure, retry up to three times and sleep longer in between failures.
result res = with_durability(retries{3}, delay{1s}, delay_multiplier{2.f}, [&] {
    return connect_to_server_in_unreliable_network()
        ? result::success   // with_durability returns immediately.
        : result::failure;  // with_durability continues based on the retry options.
});

if (res != result::success) {
    // Handle failure case. Maybe terminate immediately.
}
```

**Comment by korydraughn** [comment]
This should help resolve #3480.

**Comment by korydraughn** [comment]
Q. Should exceptions be thrown if the options contain values less than zero?

Q. Should the options be checked at all? If so, when?
- On construction of the options object?
- When an already constructed options object is updated?
- Just before the function-like object is invoked?

**Comment by trel** [comment]
> Q. Should exceptions be thrown if the options contain values less than zero?
 Yes, invalid parameters should be an error.   Alan did this for his other retry checks.

I think they should be checked on construction - Is there a reason waiting would be good?

**Comment by korydraughn** [comment]
It is more of a concern around heavy usage of this library. If it is called frequently, then we need to evaluate who is in charge of checking values. I doubt we want to check them when calling with_durability because of the potential for heavy usage. Depending on where the options come from, the checking may not need to be part of the library at all. Instead, the user of it must verify the inputs.

**Comment by korydraughn** [comment]
Currently, the options object checks the values on construction. The values can change after construction though which means something has to check them again. The current implementation does not check them again because I started wondering who should be responsible for the checks.

**Comment by korydraughn** [comment]
Fyi, durability_options objects can be shared between invocations of with_durability.
