### ISSUE TITLE
iquest cannot match names containing apostrophes via = operator

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#4887]
- [x] master
- [x] 4-2-stable
-------

### iRODS Version, OS and Version
iRODS 4.2.7 , Ubuntu16

### What did you try to do?

With a data object called `c7'txt`  (apostrophe actually embedded in the name) in the catalog,
select  that data object, using an iquest genquery, by name.

### Expected behavior
Using either the equals (`=`) or like operator, one should be able to produce a match using the object's entire name (without wildcarding with `_` or  `%`)  by escaping the apostrophe ( `\'` ).

### Observed behavior (including steps to reproduce, if applicable)

```
$ iquest "select DATA_NAME , DATA_ID where DATA_NAME = 'c7\'txt'"
CAT_NO_ROWS_FOUND: Nothing was found matching your query
```
whereas  the following *does* work (changing the operator to 'like' instead of '=') :
```
$ iquest "select DATA_NAME , DATA_ID where DATA_NAME like 'c7\'txt'"
DATA_NAME = c7'txt
DATA_ID = 10032

```

**Comment by trel** [comment]
it goes deeper... can't match on collections at all...


 case  | type  | operator | spaces | escapes | result
| --- | --- | --- | --- | --- | --- |
1 | data object | `=` | no spaces | no escapes | SUCCESS
2 | data object | `=` | no spaces | escapes | CAT_NO_ROWS_FOUND
3 | data object | `=` | spaces | no escapes | SUCCESS
4 | data object | `=` | spaces | escapes | CAT_NO_ROWS_FOUND
5 | data object | `like` | no spaces | no escapes | SUCCESS
6 | data object | `like` | no spaces | escapes | SUCCESS
7 | data object | `like` | spaces | no escapes | SUCCESS
8 | data object | `like` | spaces | escapes | SUCCESS
9 | collection | `=` | no spaces | no escapes | CAT_NO_ROWS_FOUND
10 | collection | `=` | no spaces | escapes | CAT_NO_ROWS_FOUND
11 | collection | `=` | spaces | no escapes | CAT_NO_ROWS_FOUND
12 | collection | `=` | spaces | escapes | CAT_NO_ROWS_FOUND
13 | collection | `like` | no spaces | no escapes | CAT_NO_ROWS_FOUND
14 | collection | `like` | no spaces | escapes | CAT_NO_ROWS_FOUND
15 | collection | `like` | spaces | no escapes | CAT_NO_ROWS_FOUND
16 | collection | `like` | spaces | escapes | CAT_NO_ROWS_FOUND

1
```
$ iquest "select DATA_NAME, DATA_ID where DATA_NAME = 'a2'txt'"
DATA_NAME = a2'txt
DATA_ID = 13579
```

2
```
$ iquest "select DATA_NAME, DATA_ID where DATA_NAME = 'a2\'txt'"
CAT_NO_ROWS_FOUND: Nothing was found matching your query
```

3
```
$ iquest "select DATA_NAME, DATA_ID where DATA_NAME = 'spaces n' 'postrophes'"
DATA_NAME = spaces n' 'postrophes
DATA_ID = 13582
```

4
```
$ iquest "select DATA_NAME, DATA_ID where DATA_NAME = 'spaces n\' \'postrophes'"
CAT_NO_ROWS_FOUND: Nothing was found matching your query
```

5
```
$ iquest "select DATA_NAME, DATA_ID where DATA_NAME like 'a2'txt'"
DATA_NAME = a2'txt
DATA_ID = 13579
```

6
```
$ iquest "select DATA_NAME, DATA_ID where DATA_NAME like 'a2\'txt'"
DATA_NAME = a2'txt
DATA_ID = 13579
```

7 
```
$ iquest "select DATA_NAME, DATA_ID where DATA_NAME like 'spaces n' 'postrophes'"
DATA_NAME = spaces n' 'postrophes
DATA_ID = 13582
```

8
```
$ iquest "select DATA_NAME, DATA_ID where DATA_NAME like 'spaces n\' \'postrophes'"
DATA_NAME = spaces n' 'postrophes
DATA_ID = 13582
```

9
```
$ iquest "select COLL_NAME, COLL_ID where COLL_NAME = 'nope's'"
CAT_NO_ROWS_FOUND: Nothing was found matching your query
```

10
```
$ iquest "select COLL_NAME, COLL_ID where COLL_NAME = 'nope\'s'"
CAT_NO_ROWS_FOUND: Nothing was found matching your query
```

11
```
$ iquest "select COLL_NAME, COLL_ID where COLL_NAME = 'let's go'"
CAT_NO_ROWS_FOUND: Nothing was found matching your query
```

12
```
$ iquest "select COLL_NAME, COLL_ID where COLL_NAME = 'let\'s go'"
CAT_NO_ROWS_FOUND: Nothing was found matching your query
```

13
```
$ iquest "select COLL_NAME, COLL_ID where COLL_NAME like 'nope's'"
CAT_NO_ROWS_FOUND: Nothing was found matching your query
```

14
```
$ iquest "select COLL_NAME, COLL_ID where COLL_NAME like 'nope\'s'"
CAT_NO_ROWS_FOUND: Nothing was found matching your query
```

15
```
$ iquest "select COLL_NAME, COLL_ID where COLL_NAME like 'let's go'"
CAT_NO_ROWS_FOUND: Nothing was found matching your query
```

16
```
$ iquest "select COLL_NAME, COLL_ID where COLL_NAME like 'let\'s go'"
CAT_NO_ROWS_FOUND: Nothing was found matching your query
```

**Comment by korydraughn** [comment]
While this is not a perfect solution, I wanted to document this for other people who may find this useful.

Following this [stackoverflow](https://stackoverflow.com/a/16605140/5818611) post, I was able to find data objects with single quotes in the name using the following:
```bash
$ iquest $'select DATA_NAME where DATA_NAME = \'ab\'c.txt\''
DATA_NAME = ab'c.txt
------------------------------------------------------------
```

Of course this is bash specific.

**Comment by korydraughn** [comment]
This has been resolved in master and 4-2-stable. Apostrophes do not require escaping. Collections also work.
```bash
$ ils -l
/tempZone/home/kory:
  kory              0 demoResc        49122 2021-01-28.08:13 & c7'txt
  C- /tempZone/home/kory/col'd 
  C- /tempZone/home/kory/dir ''.d'
$ iquest "select DATA_NAME where DATA_NAME = 'c7'txt'"
DATA_NAME = c7'txt
------------------------------------------------------------
$ iquest "select COLL_NAME where COLL_NAME = '/tempZone/home/kory/col'd'"
COLL_NAME = /tempZone/home/kory/col'd
------------------------------------------------------------
$ iquest "select COLL_NAME where COLL_NAME = '/tempZone/home/kory/dir ''.d''"
COLL_NAME = /tempZone/home/kory/dir ''.d'
------------------------------------------------------------
```

**Comment by trel** [comment]
Please track/note when this was fixed before closing.

**Comment by korydraughn** [comment]
This issue assumes that embedded single quotes in data object and collection names need to escaped when using iquest and the equals operator. This is not true. This [comment](https://github.com/irods/irods/issues/4887#issuecomment-769085378) proves that. I've tested this against iRODS v4.2.8 and v4.2.7. Therefore, this issue can be closed.

**Comment by trel** [comment]
it was such a good table.
