### ISSUE TITLE
iphymv must require enough arguments to target a specific replica

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#4896]
- [x] master
- [x] 4-2-stable
---
## Bug Report
`iphymv` makes no sense when invoked without specifying enough arguments to identify a specific replica. Users can run `iphymv <data_object>` and it doesn't complain. This should generate an error.

### Solution
Make the server require the (source resource or replica number) and destination resource. If both arguments are not specified, return an error.

**Comment by alanking** [comment]
I believe this has been resolved as of this commit: https://github.com/irods/irods/commit/4c434c3579e2b9b5041afc8fff8aeda6e887f1fb

From the commit message...

> rsDataObjPhyMv now requires a leaf resource or full resource hierarchy
> for both source and destination replicas. test_iphymv has been added
> to the list of tests run by CI.
