### ISSUE TITLE
key_value_proxy::handle's API needs to be adjusted

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#4903]
- [x] master
- [x] 4-2-stable
---
## API Design 
The `key_value_proxy::handle` interface needs to be adjusted. The following member functions do not follow common patterns and help to create code that is harder to understand.
- `operator=()`
- `const std::string&()`
- `operator==()`

For example, the only way to extract the value from a handle is via an implicit cast.
```c++
const std::string& value = handle;
```
It would be better if the handle provided a `value()` function that just returns a const reference to a string. Then we could write code like the following.
```c++
auto value = handle.value();
```

## Solution
- `operator=()` should be replaced with named functions that tell the reader what is happening (e.g. `set_value(string)`).
- `const std::string&()` should be replaced with a `value()` function. Implicit casts can lead to bugs.
- `operator==()` should compare handles, not handles and values of handles.

**Comment by alanking** [comment]
Handled by resolution of #4972

**Comment by trel** [comment]
so we close this when we close 4972?

**Comment by alanking** [comment]
I think so. This was discussed and resolved as part of the review process for that issue.

**Comment by trel** [comment]
awesome.  leaving open until then.

**Comment by alanking** [comment]
This can now be closed (cannot checkbox :)).
