### ISSUE TITLE
please  further document PAM Auth plugin settings

### ISSUE THREAD

**Issue by kript** [irods/irods#4904]
## Feature

Apologies if this is the wrong place; I couldn't find an auth_pam repo.

I went looking at the docs for [PAM auth](https://docs.irods.org/4.2.7/plugins/pluggable_authentication/#pam-pluggable-authentication-module) to see what options were available, but it only mentions;

- pam_password_length
- pam_no_extend
- pam_password_min_time
- pam_password_max_time

Its not clear how these should be used (apart from in `server_config.json`), and the[ JSON schemas](https://schemas.irods.org/configuration/v3/server_config.json) didn't appear to reference them.

In addition; is it possible to have no max time; i.e. infinite session?

cheers!

**Comment by trel** [comment]
Will do - in the mean time... here's how the tests use these four settings:

https://github.com/irods/irods/blob/0fecafd81aa03a5bc9fa58c00d3bb3622e69129b/scripts/irods/test/test_auth.py#L166-L176

It does not appear, upon first look, that we support an infinite session.

**Comment by trel** [comment]
Also, note, these are the default values if they are not defined in `server_config.json`.

**Comment by kript** [comment]
Can you expand on what is meant by `no_extend` and I take it the values are in seconds?
Also, is there a way to do auto-renewal, perhaps via `iinit`?

**Comment by kript** [comment]
More thoughts, sorry - is there a way to see when an authentication token can expire, both fo the user and the administrator? Would it be queryable via an iquest?

**Comment by kript** [comment]
Also, some documentation on the `irodsPamAuthCheck` would be appreciated, as beyond the entry in the manual it's hard to know how to use it;

```
$ /usr/sbin/irodsPamAuthCheck
Usage: irodsPamAuthCheck username [extra-arg-activates-debug-mode]
# which extra-arg?
$ man irodsPamAuthCheck
No manual entry for irodsPamAuthCheck
See 'man 7 undocumented' for help when manual pages are not available.
#can we have a man page for it pls?
$ /usr/sbin/irodsPamAuthCheck -h
# it hangs at this point, on a server without the plugin installed
```

**Comment by kript** [comment]
Also (finally)? the presence of `no_extend` implies the ability _to_ extend a session?

**Comment by kript** [comment]
> Also (finally)? the presence of `no_extend` implies the ability _to_ extend a session?

presumably by `iinit --ttl <hours> <userid>`?

**Comment by bh9** [comment]
The biggest issue with irodsPamAuthCheck is that it waits for a line feed before it returns anything. Also, the debug seems to suggest that whatever you put in before that line feed is interpreted as a password

**Comment by alanking** [comment]
This section was added for the 4.3.1 documentation to reflect the new way to configure authentication (see #7274)...

https://docs.irods.org/4.3.1/system_overview/configuration/#authentication-configuration

It includes descriptions of the existing options as well as `pam_password_length`, which has been removed.

---

`irodsPamAuthCheck` did not receive any additional documentation, so that remains to be done.

**Comment by alanking** [comment]
`irodsPamAuthCheck` now has more words in the documentation around its behavior and usage. As we have no plans to update the application, that's all we are going to do at this time. Please open another issue if we want to document other things or modify the auth checker.
