### ISSUE TITLE
Client parallel transfer fails because short hostname cannot be resolved

### ISSUE THREAD

**Issue by peterverraedt** [irods/irods#4911]
- [x] master
- [x] 4-2-stable
----------

### iRODS Version, OS and Version

* irods 4.2.8
* Centos 7

### What did you try to do?

In our setup, we currently have 

* a irods provider reachable at a public address `irods.example.com`
* multiple irods consumers with storage resources, let's say `irods-storage-{1,2}.some.domain`
* a replicated resource on the `irods-storage-{1,2}.some.domain` servers
* `some.domain` is included in the search domain (`/etc/resolv.conf`) on the provider server, so all three servers can resolve each others short hostnames
* `hostname` returns the short hostname correctly

And a client, let's say `client.other.domain` without `some.domain` in the search domain, but able to resolve the fqdns `irods-storage-{1,2}.some.domain` and connect to the associated ips in dns. 

The client has `irods.example.com` as the `irods_host`. When doing a iput or iget of a sufficiently large file that is stored on the replicated resource, the server `irods.example.com` tells the client to connect directly to `irods-storage-1`.

### Expected behavior

The client should be able to connect to the storage servers without setting (too much) further configuration.

### Observed behavior

The server only provides the short hostname of `irods-storage-1`. The `iput` or `iget` command therefore fails because the short hostname cannot be resolved. This means that irods is unusable from outside, without adding `some.domain` to the search domain.

Adding `/etc/irods/hosts_config.json` to the client with

```json
{
  "schema_name": "hosts_config",
  "schema_version": "v3",
  "host_entries": [
    {
      "address_type" : "remote",
      "addresses" : [
        {"address" : "actual ip"},
        {"address" : "irods-storage-1.some.domain"},
        {"address" : "irods-storage-1"}
      ]
    }
  ]
}
```
works since 4.2.8, but root access on the client system to set this up cannot always be assumed. 

A feature to be able to provide `host_config.json` on the client that would be used when running icommands should be added - preferably this file should also be read from `$HOME/.irods/hosts_config.json`.

### Workarounds

Making sure that `hostname` returns the fqdn on `irods-storage-{1,2}.some.domain` instead of the short hostname, will make that in negotiating the parallel file transfer to these storage servers also returns fqdns to the client.

**Comment by trel** [comment]
We are working to resolve this - we expect there are too many (~6-7) `gethostname()`'s sprinkled around... and those locations should all, instead, be referencing an already-properly-resolved iRODS-aware hostname available to them.

**Comment by kript** [comment]
This also happens in 4.2.7, and we see it in a similar situation. No chance of this being fixed in 4.2.9 is there? 🧞 🤞 🙏

**Comment by trel** [comment]
Is that a genie?   We're going to look into duplicate/incomplete work being done by `gethostname()`.

**Comment by trel** [comment]
We have brainstormed a per-server hostname cache that would be consulted before reaching out to `gethostname()`.

This approach would solve this shortname issue by incorporating a server's `hosts_config.json` information before handing that back to the client AND significantly reduce the number of times iRODS servers hit DNS overall.
