### ISSUE TITLE
iRODS doesn't handle or report failure of one irodsServer process

### ISSUE THREAD

**Issue by mcv21** [irods/irods#4947]
### iRODS Version, OS and Version
iRODS 4.2.7
Ubuntu 18.04

### What did you try to do?
With iRODS 4.2.7, iRODS starts up two irodsServer processes, one of which opens rodsServerLog, one of which opens rodsLog. If the latter crashes, iRODS doesn't appear to mark anything amiss.

### Expected behavior
I would expect in this case (similar to the case where the process with rodsServerLog open) iRODS would flag the problem, exit, and allow systemd to restart it if appropriate.

### Observed behavior (including steps to reproduce, if applicable)
In fact, `systemctl status` and `irodsctl status` simply report the one continuing process.
To reproduce:
1. note status of irods:
```
root@irods-cgp-sr15-dev:~# systemctl status irods
● irods.service - iRODS 4.X Open Source Data Management Software for user irods-
   Loaded: loaded (/etc/systemd/system/irods.service; enabled; vendor preset: en
   Active: active (running) since Wed 2020-05-20 14:52:18 BST; 30s ago
     Docs: https://ssg-confluence.internal.sanger.ac.uk/display/ISG/iRODS
  Process: 1615 ExecStop=/bin/bash -c irodsctl stop (code=exited, status=0/SUCCE
  Process: 1654 ExecStart=/bin/bash -c irodsctl start (code=exited, status=0/SUC
 Main PID: 1662 (irodsServer)
    Tasks: 11 (limit: 8601)
   CGroup: /system.slice/irods.service
           ├─1662 /usr/sbin/irodsServer
           └─1663 /usr/sbin/irodsServer
```
2. use `lsof` to determine which process has rodsLog open (typically the process that isn't the main PID)
```
root@irods-cgp-sr15-dev:~# lsof /var/lib/irods/log/rodsLog.2020.05.16 
COMMAND     PID      USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
irodsServ  1663 irods-cgp    0w   REG  253,0     3189 14238783 /var/lib/irods/log/rodsLog.2020.05.16
```
3. Send that process an ABRT signal (so here `kill -ABRT 1663`)
4. Observe `systemctl status` and `irodsctl status`:
```
root@irods-cgp-sr15-dev:~# kill -ABRT 1663
root@irods-cgp-sr15-dev:~# systemctl status irods
● irods.service - iRODS 4.X Open Source Data Management Software for user irods-
   Loaded: loaded (/etc/systemd/system/irods.service; enabled; vendor preset: en
   Active: active (running) since Wed 2020-05-20 14:52:18 BST; 2min 8s ago
     Docs: https://ssg-confluence.internal.sanger.ac.uk/display/ISG/iRODS
  Process: 1615 ExecStop=/bin/bash -c irodsctl stop (code=exited, status=0/SUCCE
  Process: 1654 ExecStart=/bin/bash -c irodsctl start (code=exited, status=0/SUC
 Main PID: 1662 (irodsServer)
    Tasks: 11 (limit: 8601)
   CGroup: /system.slice/irods.service
           └─1662 /usr/sbin/irodsServer
```
```
irods-cgp@irods-cgp-sr15-dev:~$ /var/lib/irods/irodsctl status
irodsServer :
  Process 1662
```

**Comment by trel** [comment]
Yes, in 4.2.x...  https://docs.irods.org/4.2.7/system_overview/process_model/
- The first PID is the main /usr/sbin/irodsServer (writes to `rodsServerLog`).
- The second PID is a fork, which we refer to as the Agent Factory (writes to `rodsLog`).
- The Agent Factory forks each Agent when API requests arrive (writes to `rodsLog`).

Note: Logging behavior has been consolidated all to write to `syslog` in the master branch (for 4.3)

Agreed, we need a smarter watcher for the Agent Factory process.  Perhaps even just a thread in the main process...

**Comment by trel** [comment]
related to https://github.com/irods/irods/issues/4977

**Comment by trel** [comment]
closed as part of https://github.com/irods/irods/issues/4977
