### ISSUE TITLE
new minor issue

### ISSUE THREAD

**Issue by mcast** [irods/irods#4948]
I have a minor security issue to raise, possibly you would want it hidden until you've had time to evaluate it. Would it suit to add @kript and @bh9, then make the issue private?

**Comment by trel** [comment]
I am not sure how to make an issue private on GitHub.  Let's get on a call...

**Comment by mcast** [comment]
Thanks Trel. My mistake, it is Gitlab that [has a Confidentiality option](https://docs.gitlab.com/ce/user/project/issues/confidential_issues.html) for issues. I use both, feature blurred in my head.

**Comment by trel** [comment]
closing - handled offline - nothing to do here.
