### ISSUE TITLE
key_value_proxy does not support const keyValPair_t's

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#4972]
- [x] master
- [x] 4-2-stable
---
### iRODS Version, OS and Version
iRODS v4.2.8

### What did you try to do?
I tried to construct a `key_value_proxy` using a `const keyValPair_t`.

### Expected behavior
It would compile and enforce only read access to the underlying object.

### Observed behavior (including steps to reproduce, if applicable)
Compiler errors.

### Solution
- Change the implementation to a template and adjust the implementation based on the constness.
- Implement a new class that is identical to `key_value_proxy`, but accepts `const keyValPair_t`.

**Comment by alanking** [comment]
I cannot checkbox this, but I believe this is now done in both major branches.
