### ISSUE TITLE
Add facility for asynchronous tasks in the main server

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#4977]
## Feature
Responsible for launching tasks before the agent factory is created. For example:
- Agent Factory Watcher
- Delay Server Watcher
- Garbage Collection
- Latency Map Maintainer
- Monitoring CPU/RAM usage (part of https://github.com/irods/irods/issues/3610?)
- Removing expired DNS cache entries
- Removing expired Hostname cache entries

Consider a facility for plugins to register additional tasks.
- Timing
- Assertion tests
- Failure logs

For example:
- Logical Quotas to register an integrity check on the AVUs it cares about

**Comment by trel** [comment]
for finding this issue later.... keywords... sleeper, sweeper

**Comment by epsilon-phase** [comment]
use cases to consider:

1. Jobs that run only on a single machine
2. Jobs that run on any machine(it doesn't care)
3. Jobs that run on every machine

3 seems to be the most important here since this is mostly cleanup focused

**Comment by epsilon-phase** [comment]
Okay, so one of those things we could imitate is the cron file format, like 
```
*   *   1    *    echo hi
```

Or we could use json as is used elsewhere in irods.

```javascript
{
     "Name":"echo",
     "interval":{
           "hour":1
// Could have seconds, minutes, days, weeks, etc
     }
}
```

**Comment by trel** [comment]
cron defines when something fires.

if we go with a 'sleep' or 'interval'-based solution, it would define the time from one process ending until the next one begins.

interval is better to prevent overlapping runs of the same 'job'... but harder for admins to predict when it fires.

**Comment by epsilon-phase** [comment]
Yeah, that's a good point. That definitely requires some additional capabilities over the interval and seems like it probably ends up satisfying both kinds of processes

-------- Original Message --------

**Comment by trel** [comment]
another good thing about an interval, it can be specified with only a number of seconds, no other units needed.

predictability for the admin probably isn't too high of a priority, as these tasks are/will-be(?) more in the mental category of 'recurring' and not as much about exactly 'when'.

regardless, a nice pros/cons list to be considered.

**Comment by alanking** [comment]
More stuff for later...

- Lock checker: Checks for locked data objects and checks to see if the agent holding the lock is still there. If not, unlocks the data object.
- Settings refresher: Some settings require a server restart to apply. If the facility exists as a thread in the main server process, it could update the settings in the main server process. If the facility exists as a forked process, it might be a bit harder to implement this.

**Comment by korydraughn** [comment]
for DNS and hostname cache cleanup:
- https://github.com/irods/irods/blob/a4ab0e15c49a34446e4bc23108c009f8a0091531/lib/core/include/hostname_cache.hpp#L70
- https://github.com/irods/irods/blob/a4ab0e15c49a34446e4bc23108c009f8a0091531/lib/core/include/dns_cache.hpp#L77

default to every 10 minutes

**Comment by trel** [comment]
As this restarting of the irodsReServer / delayServer will now be automatic... it needs to be released alongside #5249.  

This work is merged into master at the moment, and may remain master-only, which would mean 4.3.0.

**Comment by trel** [comment]
the facility now exists.

need to open new issues for any specific tasks that need to be added.    then can close this issue.

**Comment by trel** [comment]
I've created the additional issues - closing this as complete.

#5815
#5816
#5817
#5818

**Comment by trel** [comment]
also related https://github.com/irods/irods/issues/4711
