### ISSUE TITLE
istream: option to specify resource

### ISSUE THREAD

**Issue by stefan-wolfsheimer** [irods/irods#5000]
- [x] master
- [x] 4-2-stable
------
## Feature

istream is very useful in combination with other unix program. Thanks for adding this tool to the icommands.

Unfortunately, it lacks the option to define the target resource for write streams.

Something like
`istream -R <resource> write <target_object>`
would be nice.

Is it feasible to add that feature?

**Comment by korydraughn** [comment]
Absolutely! This will be available in the next release.
