### ISSUE TITLE
RULE_ENGINE_SKIP_OPERATION should not skip Post-PEPs

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#5002]
- [x] master
- [x] 4-2-stable
---
## Observation
`RULE_ENGINE_SKIP_OPERATION` should do as its name says. It should only skip the operation. Post-PEPs should be allowed to fire. This is necessary so that plugins such as Hard Links can run alongside other plugins that depend on the Post-PEP.

**Comment by trel** [comment]
marking as bug - even though it was a design decision at the time.
