### ISSUE TITLE
Use of microservices in dynamic PEPs breaks large file transfers across federation

### ISSUE THREAD

**Issue by alanking** [irods/irods#5017]
- [x] master
- [x] 4-2-stable
---

### iRODS Version, OS and Version
4.2.8

### What did you try to do?
Put a large file across federation while connected server is configured with a rulebase which includes `pep_api_data_obj_put_post` and calls any microservice.

### Expected behavior
Things just work.

### Observed behavior (including steps to reproduce, if applicable)
Include the following stanza in a configured rulebase on the catalog provider for the home zone:
```
pep_api_data_obj_put_post(*INSTANCE_NAME, *COMM, *DATAOBJINP, *BUFFER, *PORTAL_OPR_OUT) {
    msiObjStat("/remoteZoneHint/path/to/whatever", *out);
}
```
Put a large file across federation to the remote zone, connected and authenticated in the  home zone:
```
$ ienv | grep zone
irods_zone_name - otherZone
$ iput big /tempZone/home/rods#otherZone/foo1
remote addresses: 172.22.0.3 ERROR: connectToRhostPortal: connectTo Rhost icat.tempZone.example.org port 20080 error, status = -305111
remote addresses: 172.22.0.3 ERROR: putUtil: put error for /tempZone/home/rods#otherZone/foo1, status = -305111 status = -305111 USER_SOCK_CONNECT_ERR, Connection refused
```

If the microservice is called from a different dynamic or static PEP, things work as expected. This has been demonstrated on 4.2.7 as well.

Please investigate - this is likely a parsing/memory layout issue in the NREP.

**Comment by alanking** [comment]
After some investigation, we have a better handle on the problem now: The dynamic PEP in the rulebase for the home zone catalog service provider fires before returning to the client, and then executes the microservice.

If this happens to be a data object or catalog operation in the remote zone, the same agent will reach out to the remote catalog service provider using a new connection on the zone port. The agent process standing up the parallel transfer portal in the remote zone CSP times out when `select`ing on the socket (because the portal information has not been returned to the client yet), fails, and services the request for the post-PEP. The home zone CSP then returns to the client with the portal information for the parallel transfer, the client arrives to connect to the portal, and the remote server refuses the connection because by this point the portal has gone away.

Still investigating a fix which can allow the home zone CSP in this scenario to continue issuing requests to the remote zone CSP so that the parallel transfer can complete in this scenario

Additionally, it seems that the failure to complete the parallel transfer fails to trigger `pep_api_data_obj_put_except` because the error is not bubbled up to the API handler properly

**Comment by alanking** [comment]
This is issue is going to be very difficult to solve in the current implementation of the parallel transfer mechanism for puts and gets. The connection facilities for the server-side APIs reuse connections even over federation. Here is the output from the log when running the scenario above with a similar rulebase:

```json
{
    "log_category":"agent",
    "log_facility":"local0",
    "log_level":"info",
    "log_message":"I'm an agent!",
    "server_host":"icat.tempZone.example.org",
    "server_pid":29160,
    "server_timestamp":"2020-07-23T17:44:13.187950",
    "server_type":"agent"
} 
{   
    "log_category":"legacy",
    "log_facility":"local0",
    "log_level":"error",
    "log_message":"acceptSrvPortal() -- select timed out",
    "request_api_name":"DATA_OBJ_PUT_AN",
    "request_api_number":606,
    "request_api_version":"d",
    "request_client_user":"rods",
    "request_host":"172.24.0.3",
    "request_proxy_user":"rods",
    "request_release_version":"rods4.3.0",
    "server_host":"icat.tempZone.example.org",
    "server_pid":29160,
    "server_timestamp":"2020-07-23T17:45:13.545251",
    "server_type":"agent"
}   
{   
    "log_category":"legacy",
    "log_facility":"local0",
    "log_level":"info",
    "log_message":"svrPortalPut: acceptSrvPortal error. errno = 0",
    "request_api_name":"DATA_OBJ_PUT_AN",
    "request_api_number":606,
    "request_api_version":"d",
    "request_client_user":"rods",
    "request_host":"172.24.0.3",
    "request_proxy_user":"rods",
    "request_release_version":"rods4.3.0",
    "server_host":"icat.tempZone.example.org",
    "server_pid":29160,
    "server_timestamp":"2020-07-23T17:45:13.545660",
    "server_type":"agent"
}   
{   
    "log_category":"legacy",
    "log_facility":"local0",
    "log_level":"info",
    "log_message":"writeLine: inString = i'm pep_api_data_obj_put_post on the remote catalog service provider (CSP)",
    "request_api_name":"OBJ_STAT_AN",
    "request_api_number":633,
    "request_api_version":"d",
    "request_client_user":"rods",
    "request_host":"172.24.0.3",
    "request_proxy_user":"rods",
    "request_release_version":"rods4.3.0",
    "server_host":"icat.tempZone.example.org",
    "server_pid":29160,
    "server_timestamp":"2020-07-23T17:45:13.576469",
    "server_type":"agent"
}
{
    "log_category":"legacy",
    "log_facility":"local0",
    "log_level":"error",
    "log_message":"[-]  /irods_source/server/core/src/rsApiHandler.cpp:559:int readAndProcClientMsg(rsComm_t *,int) :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']
            [-] /irods_source/lib/core/src/sockComm.cpp:201:irods::error readMsgHeader(irods::network_object_ptr, msgHeader_t *, struct timeval *) :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']
                 [-]    /irods_source/plugins/network/tcp/libtcp.cpp:194:irods::error tcp_read_msg_header(irods::plugin_context &, void *, struct time val *) :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [only read [0] of [4]]",
   "request_api_name":"OBJ_STAT_AN",
   "request_api_number":633,
   "request_api_version":"d",
   "request_client_user":"rods",
   "request_host":"172.24.0.3",
   "request_proxy_user":"rods",
   "request_release_version":"rods4.3.0",
   "server_host":"icat.tempZone.example.org",
   "server_pid":29160,
   "server_timestamp":"2020-07-23T17:45:13.577521",
   "server_type":"agent"
}
{
    "log_category":"legacy",
    "log_facility":"local0",
    "log_level":"error",
    "log_message":"Agent [29160] exiting with status = -4000",
    "request_api_name":"OBJ_STAT_AN",
    "request_api_number":633,
    "request_api_version":"d",
    "request_client_user":"rods",
    "request_host":"172.24.0.3",
    "request_proxy_user":"rods",
    "request_release_version":"rods4.3.0",
    "server_host":"icat.tempZone.example.org",
    "server_pid":29160,
    "server_timestamp":"2020-07-23T17:45:13.578387",
    "server_type":"agent"
}
{
    "log_category":"legacy",
    "log_facility":"local0",
    "log_level":"error",
    "log_message":"Agent process [29160] exited with status [96]",
    "server_host":"icat.tempZone.example.org",
    "server_pid":29135,
    "server_timestamp":"2020-07-23T17:45:13.629868",
    "server_type":"agent_factory"
}
```

The log messages show that the stat from the PEP uses the same agent PID as the put. This is the cause of the hang - a deadlock, of sorts.

One solution we thought about was spinning up a new agent for every client call over federation, but this could be problematic for successive operations such as open/write/close.

For now, the plan is to document this behavior for troubleshooting purposes. In a scenario such as this, policy implementers should carefully consider which servers should control certain PEPs and what they are doing. More updates to follow, probably.

**Comment by trel** [comment]
ping for @kript @bh9

**Comment by alanking** [comment]
Should this be closed? The limitation has been documented

**Comment by trel** [comment]
Is this part documented/handled?    Could use this issue for that work or make a new one if it's still something that needs to be investigated.

> Additionally, it seems that the failure to complete the parallel transfer fails to trigger pep_api_data_obj_put_except because the error is not bubbled up to the API handler properly

Except for that...  I think yes, we're done here.

**Comment by alanking** [comment]
Okay, we can add a test for parallel transfer with an except PEP

**Comment by alanking** [comment]
We have a test for this already, it seems: https://github.com/irods/irods/blob/5f4a213c79711fab65375ad3da9b89aa5184377c/scripts/irods/test/rule_texts_for_tests.py#L258-L262 https://github.com/irods/irods/blob/32cc2bd18e43aaaa42f002d07996343a05066646/scripts/irods/test/test_native_rule_engine_plugin.py#L170-L171

However, this does not go across federation. Need to whip up something similar to make sure federation is also triggering this behavior.

**Comment by alanking** [comment]
Added test and fixed a few other federation issues. As the labels suggest, we will not be fixing this particular issue, but it has been documented. Closing.
