### ISSUE TITLE
A msiDataObjCreate followed by msiDataObjClose leaves object in intermediate state

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods#5018]
- [x] master
- [x] 4-2-stable
-------

## Bug Report

When running the following rule, the file (f1) was left in an intermediate state.

```
test_open_write_close {{
    msiDataObjCreate("/tempZone/home/rods/f1", "destRescName=demoResc", *fd)
    msiDataObjClose(*fd, *status)

}}
INPUT null
OUTPUT ruleExecOut
```

### iRODS Version, OS and Version

iRODS on 4-2-stable branch
Ubuntu 16.04

### What did you try to do?

Ran the rule listed above.

### Expected behavior

A zero length object (f1) is created and at the end has a good (&) state.

### Observed behavior (including steps to reproduce, if applicable)

The object has an intermediate (?) state.

**Comment by trel** [comment]
This was 4-2-stable?   No intermediates in 4.2.8 ... right?

**Comment by alanking** [comment]
I can't add checkboxes, but this is fixed now. Here is the related test:

https://github.com/irods/irods/blob/d2bf2063c2992da52c7ee234bb381fbb4de5de80/unit_tests/src/test_rc_data_obj.cpp#L28-L51

Should I add one specifically for the microservice before we close?

**Comment by trel** [comment]
Yes, please add a microservice test as well - thanks.

**Comment by alanking** [comment]
Cannot checkbox, but tests are added

**Comment by trel** [comment]
done - thanks.
