### ISSUE TITLE
imeta qu should return non-zero on Unrecognised input

### ISSUE THREAD

**Issue by bh9** [irods/irods#5021]
- [ ] master
- [ ] 4-2-stable
------

### iRODS Version, OS and Version
4.2.7, Ubuntu 18.04

### What did you try to do?
`imeta qu -d any invalid input`

### Expected behavior
A non-zero return code to tell me that my query was not valid

### Observed behavior (including steps to reproduce, if applicable)
imeta prints `Unrecognized input` to stdout and returns code 0 (success)

**Comment by trel** [comment]
A bit of a mess, indeed.

```
$ ienv | grep version
irods_version - 4.2.8

$ imeta qu -d any invalid input ; echo $?
No rows found
0

$ imeta qu -d ; echo $?

Error: Not enough arguments provided to qu

0

$ imeta qu -d a ; echo $?

Error: Not enough arguments provided to qu

0

$ imeta qu -d a b ; echo $?

Error: Not enough arguments provided to qu

0

$ imeta qu -d a b c ; echo $?
rcGenQuery failed with error -816000 CAT_INVALID_ARGUMENT 
4

$ imeta qu -d a b c d ; echo $?
Unrecognized input
0
```

**Comment by bh9** [comment]
Further, all of those error messages go to stdout, rather than stderr (not sure about the CAT_INVALID_ARGUMENT)

I'm attempting to produce a script which behaves like imeta but uses the indexing plugin instead, so I'm trying to find edge cases and see if I can get the script to act the same. My script would currently output `Unrecognized input` for all the above cases

**Comment by trel** [comment]
Cursory peek suggests we just need to keep the return value...

```diff
diff --git a/src/imeta.cpp b/src/imeta.cpp
index 3a4aa2d..e95ed24 100644
--- a/src/imeta.cpp
+++ b/src/imeta.cpp
@@ -2159,7 +2159,7 @@ int main( int argc, const char **argv )
         // No command entered; run in interactive mode
         do_interactive();
     } else {
-        do_command( command_to_be_parsed[0], { ++command_to_be_parsed.begin(), command_to_be_parsed.end() });
+        lastCommandStatus = do_command( command_to_be_parsed[0], { ++command_to_be_parsed.begin(), command_to_be_parsed.end() });
     }
 
     printErrorStack( Conn->rError );
```

**Comment by SwooshyCueb** [comment]
The suggested change does fix the return code for most of the cases above, but "No rows found" still returns 0.
I think `any invalid input` is being interpreted as a valid query (maybe it is? I'll find out tomorrow), but just has zero results. I imagine we still want to return 0 for an empty results list?

**Comment by trel** [comment]
Well... it's being interpreted as a valid query (which I'm pretty sure it's not... `invalid` is not a valid operator).

Oh wait!!!

```
$ imeta qu -d a badoperator 13 ; echo $?
rcGenQuery failed with error -816000 CAT_INVALID_ARGUMENT 
4
19:33PM tgr@bison:~ $ imeta qu -d a invalid 13 ; echo $?
No rows found
0
```

The string invalid is apparently being matched as an operator because it has the string 'in' in it.  This is a manifestation of https://github.com/irods/irods/issues/3064 and cannot be fixed here.


That said...

I believe the return code of 0 when there are legitimately zero results is a bit of a philosophical question...  `grep` gives an error code if it cannot find something requested, but databases do not.

@bh9 What would you want in this case?  I think I feel strongly both ways.

**Comment by trel** [comment]
Also, error messages *are* going to `stderr`...

Sending `stderr` to `/dev/null`...
```
$ imeta qu -d a badoperator 13 2> /dev/null ; echo $?
4
```

'No rows found' goes to `stdout`... (which is correct if the return code `0` is correct)
```
$ imeta qu -d a '<' 13 2> /dev/null ; echo $?
No rows found
0
```

**Comment by bh9** [comment]
Looking further, the errors which go to stdout are just these 2:
```
bh9@deskpro110321:~/ansible$ imeta qu -d a 2> /dev/null

Error: Not enough arguments provided to qu

bh9@deskpro110321:~/ansible$ imeta qu -d a b c d 2> /dev/null
Unrecognized input
```
so just the ones which return 0

**Comment by trel** [comment]
Okay, so `Error: Not enough arguments provided to qu` and `Unrecognized input` should both go to `stderr` and not return code `0`.   They are both errors.

**Comment by SwooshyCueb** [comment]
This one's fixed in both branches, so if someone could check the boxes for me, I'd appreciate it

**Comment by trel** [comment]
done
