### ISSUE TITLE
iscan limits output filenames to 256 characters

### ISSUE THREAD

**Issue by bh9** [irods/irods#5022]
- [x] master
- [x] 4-2-stable
-----
### iRODS Version, OS and Version
4.2.7, ubuntu 18.04

### What did you try to do?
Calculate the space taken up by unregistered files with
`iscan -r $resource | sed 's/is not registered in iRODS//g' | xargs du -sk`

### Expected behavior
iscan outputs the entire file path so the output is actually of use for later operations

### Observed behavior (including steps to reproduce, if applicable)
iscan limits the output path to 256 characters, meaning the du fails with `No such file or directory`

**Comment by trel** [comment]
ah, possible solution is to bump that length...

```
$ grep -rI LONG_NAME_LEN . | grep scanUtil
./lib/core/src/scanUtil.cpp:42:        char inpPath[ LONG_NAME_LEN ];
./lib/core/src/scanUtil.cpp:68:    char fullPath[LONG_NAME_LEN] = "\0";
./lib/core/src/scanUtil.cpp:88:        snprintf( fullPath, LONG_NAME_LEN, "%s",

$ grep -rI LONG_NAME_LEN . | grep 256
./lib/core/include/rodsDef.h:56:#define LONG_NAME_LEN        256
```


but to what?


perhaps `MAX_NAME_LEN` ?

```
./lib/core/include/rodsDef.h:57:#define MAX_PATH_ALLOWED 1024
./lib/core/include/rodsDef.h:60:#define MAX_NAME_LEN   (MAX_PATH_ALLOWED+64)
```
