### ISSUE TITLE
lib/core/include/irods_configuration_parser.hpp includes json.hpp which is not in repository

### ISSUE THREAD

**Issue by RubenGarcia** [irods/irods#5029]
### iRODS Version, OS and Version
iRODS 4.2.8
Debian GNU/Linux 9.12 (stretch)

### What did you try to do?
Compile openid plugin from
https://github.com/RubenGarcia/irods_auth_plugin_openid

### Expected behavior
Correct compilation

#### - 2 

 /opt/irods-externals/cmake3.11.4-0/bin/cmake -DCMAKE_INSTALL_PREFIX:PATH=/ ../irods_auth_plugin_openid/

#### - 3

make

#### - 4

Scanning dependencies of target openid_client
[ 25%] Building CXX object CMakeFiles/openid_client.dir/src/libopenid.cpp.o
In file included from /home/debian/irods_auth_plugin_openid/src/libopenid.cpp:14:
In file included from //usr/include/irods/irods_client_server_negotiation.hpp:7:
In file included from //usr/include/irods/irods_server_properties.hpp:14:
//usr/include/irods/irods_configuration_parser.hpp:16:10: fatal error: 'json.hpp' file not found
#include "json.hpp"
         ^~~~~~~~~~
1 error generated.
CMakeFiles/openid_client.dir/build.make:62: recipe for target 'CMakeFiles/openid_client.dir/src/libopenid.cpp.o' failed
make[2]: *** [CMakeFiles/openid_client.dir/src/libopenid.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/openid_client.dir/all' failed
make[1]: *** [CMakeFiles/openid_client.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by RubenGarcia** [comment]
`
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 8b15622..6aaa82e 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,6 +1,6 @@
 cmake_minimum_required(VERSION 3.5.0 FATAL_ERROR) #CPACK_DEBIAN_<COMPONENT>_PACKAGE_NAME

-find_package(IRODS 4.2.3 EXACT REQUIRED)
+find_package(IRODS 4.2.8 EXACT REQUIRED)

 set(CMAKE_C_COMPILER ${IRODS_EXTERNALS_FULLPATH_CLANG}/bin/clang)
 set(CMAKE_CXX_COMPILER ${IRODS_EXTERNALS_FULLPATH_CLANG}/bin/clang++)
`

**Comment by RubenGarcia** [comment]
[irods-4.2.8-patch.txt](https://github.com/irods/irods/files/5015704/irods-4.2.8-patch.txt)

**Comment by RubenGarcia** [comment]
I could not find any information on
https://docs.irods.org/4.2.8/developers
regarding the need to install an external json library, and a google search indicated multiple possible libraries.

**Comment by trel** [comment]
I believe you may need...

```
include_directories(${IRODS_EXTERNALS_FULLPATH_JSON}/include)
```

**Comment by RubenGarcia** [comment]
After adding the line suggested by trel, the file compiles. 
The next issue is.

debian@new-irods:~/build$ make
-- Configuring done
-- Generating done
-- Build files have been written to: /home/debian/build
Scanning dependencies of target openid_client
[ 25%] Building CXX object CMakeFiles/openid_client.dir/src/libopenid.cpp.o
[ 50%] Linking CXX shared module libopenid_client.so
[ 50%] Built target openid_client
Scanning dependencies of target openid_server
[ 75%] Building CXX object CMakeFiles/openid_server.dir/src/libopenid.cpp.o
/home/debian/irods_auth_plugin_openid/src/libopenid.cpp:2271:14: error: no member named 'random_shuffle' in namespace
      'std'
        std::random_shuffle( ports.begin(), ports.end(), rng );
        ~~~~~^
1 error generated.
CMakeFiles/openid_server.dir/build.make:62: recipe for target 'CMakeFiles/openid_server.dir/src/libopenid.cpp.o' failed
make[2]: *** [CMakeFiles/openid_server.dir/src/libopenid.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/openid_server.dir/all' failed
make[1]: *** [CMakeFiles/openid_server.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by RubenGarcia** [comment]
This looks like a missing include in
