### ISSUE TITLE
Separate authentication step in connection pool

### ISSUE THREAD

**Issue by alanking** [irods/irods#5060]
- [x] main
- [x] 4-3-stable
---
## Feature

The connection pool currently requires the user to pass iRODS environment information so that the connections in the pool can be pre-authenticated. The connection pool should just connect to iRODS on construction and then authenticate when the connection is actually used.

The constructor should be adjusted like so:

```
connection_pool(const int _size,
                const std::string& _host,
                const int _port,
                const int _refresh_time);
```

And a new member method for authentication needs to be added which would be called when the connection is retrieved for use. Something like this:
```
auto login(const std::string& _username,
           const std::string& _password,
           const std::string& _zone) -> void;
```

Optionally/for consideration: a connection pool can be configured to stay authenticated from creation as it exists now, or defer authentication as described above.

**Comment by korydraughn** [comment]
I think providing a way to defer authentication is the best way to accomplish this (as you stated in your last statement). That way, we maintain backwards compatibility and provide new functionality at the same time.

**Comment by korydraughn** [comment]
This also applies to client_connection.hpp.
