### ISSUE TITLE
Merge the update_collection_mtime REP into the server

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#5063]
- [x] master
- [x] 4-2-stable
---
## Feature
This brings a piece of functionality that should be in the server by default. See [update_collection_mtime REP](https://github.com/irods/irods_rule_engine_plugin_update_collection_mtime).

### Optional
New installations will have the mtime plugin configured by default and upgrades will have it added to the config.

**Comment by trel** [comment]
Would it even be a plugin anymore?    Just absorb the functionality, no reason to worry about upgrades or plugin configs...

**Comment by korydraughn** [comment]
Depends on what we want to do. That would take a little longer than the plugin approach, but it is possible. Adding it directly into the server would be the best way to add this to me.

**Comment by trel** [comment]
agreed - let's just absorb it - no more plugin.
