### ISSUE TITLE
CAT_NO_ROWS_FOUND in log for successful iput of new file

### ISSUE THREAD

**Issue by alanking** [irods/irods#5064]
- [x] master
- [x] 4-2-stable
---
### iRODS Version, OS and Version
master/4-2-stable

### Observed behavior (including steps to reproduce, if applicable)
On successful `iput`, the server log will contain an error message like this:
```
/irods_source/server/core/src/irods_file_object.cpp:336:irods::error irods::file_object_factory(rsComm_t *, dataObjInp_t *, irods::file_object_ptr, dataObjInfo_t **) :  status [CAT_NO_ROWS_FOUND]  errno [] -- message [failed in call to getDataObjInfoIncSpecColl for [/tempZone/home/rods/foo] CAT_NO_ROWS_FOUND ]
```

This is simply a failure to find information in the catalog for a data object that does not yet exist. This is actually a good failure in the case of creating a new data object, so this error message should be elided in such cases.

**Comment by kjsanger** [comment]
This is a different issue from the one discussed last week with @bh9 involving `CAT_NO_ROWS_FOUND` during replication, is that correct? Thanks.

**Comment by trel** [comment]
Yes, this is a bit of noise in the unreleased 4-2-stable branch code - different from last week's connection-reuse issue.

**Comment by kjsanger** [comment]
Is there an issue open for the one we discussed? If not, would you like us to open one?

**Comment by alanking** [comment]
Hi @kjsanger - I have just opened #5072 to capture the issue to which you were referring.
