### ISSUE TITLE
iput -K ignores server-side default_hash_scheme

### ISSUE THREAD

**Issue by bh9** [irods/irods#5075]
### iRODS Version, OS and Version
4.2.7 Ubuntu 18.04

### What did you try to do?
iput -K to ensure the file is checksummed and that the file checksummed by the server is the same as the one checksummed by the client

### Expected behavior
Since every server has irods_default_hash_scheme set to MD5 in their service account irods_environment.json and default_hash_scheme set to MD5 in their server_config.json, we would expect both replicas to be MD5 checksummed

### Observed behavior (including steps to reproduce, if applicable)
Replica 0 is SHA256 checksummed, and replica 1 is MD5 checksummed
```
bh9@deskpro110321:~$ iput -K thing /seq/home/bh9#Sanger1/thing4
bh9@deskpro110321:~$ ils -L /seq/home/bh9#Sanger1/thing4
  bh9               0 root;replicate;seq-red;red5;irods-seq-i27-sdc          373 2020-08-25.15:35   thing4
    sha2:BSD1pzfTGxMmCqBLd/PeuMdimcerZELODNRtKiHQ1KU=    generic    /irods-seq-i27-sdc/home/bh9#Sanger1/thing4
  bh9               1 root;replicate;seq-green;green6;irods-seq-sb10-sde          373 2020-08-25.15:35 & thing4
    fdc45f5eb8963c5a53b71a00a998839a    generic    /irods-seq-sb10-sde/home/bh9#Sanger1/thing4
```
  
Note: this seems to be because the hash scheme is being decided without consulting the server, as changing the user's irods_environment.json to include `"irods_default_hash_scheme": "MD5"` causes both replicas to be MD5 checksummed

**Comment by trel** [comment]
So, one of the rows in this table is not true?

https://docs.irods.org/4.2.7/system_overview/configuration/#checksum-configuration

This is the use case you're describing?



Sender | Receiver | Result
-- | -- | --
SHA256 | MD5, Compatible | Success with SHA256

**Comment by trel** [comment]
If you would rather see a `USER_HASH_TYPE_MISMATCH` error, you can set the servers to 'Strict' mode...

**Comment by bh9** [comment]
That is the case we're describing. It is a change from 4.2, so we weren't expecting it

**Comment by trel** [comment]
To clarify for future readers... this is in 4.2.

This could be the relevant change from 4.1 behavior...  https://github.com/irods/irods/issues/3321
