### ISSUE TITLE
build a relocatable userspace tarball of the icommands

### ISSUE THREAD

**Issue by NickHastings** [irods/irods#5082]
- [x] master
- [x] 4-2-stable
--------

### iRODS Version, OS and Version
4-2-stable. OS agnostic.

### What did you try to do?
Tried to build without using fpm.

### Expected behavior
Expect to to be able to build using system supplied dependencies rather than need to use the packages provided by irods-externals and fpm. This was the case with irods-legacy. If this is still possible I haven't been able to find documentation describing the procedure. This problem cascades down to installing irods_client_icommands since the build system for it seems to insist on the packages from irods and irods-external to be installed by the package manager. Perhaps this issue should be raised for irods_client_icommands instead of irods, but it seems to me to be a problem that exists in the overall infrastructure of irods.

**Comment by trel** [comment]
Hi Nick,

The current dependency model of iRODS has it depend on a large number of upstream projects (we need to talk to many types of systems).  Many of those upstream projects are not packaged by the systems that people run them on in a new enough version.  We need(ed) newer dependencies on older operating systems.  The only way to provide that combination is to build the dependencies ourselves.  The only sane way to provide that combination for others is to build and package the dependencies and serve them from our own package repository.

There is a way to build and install everything yourself, what we call a "non-package-install".  The most current instructions, such as they are, are here:  https://docs.irods.org/4.2.8/getting_started/installation/#non-package-install-run-in-place

Since many in our community are running iRODS at HPC centers and large universities or research institutes with long timelines, they are generally conservative about running newer operating systems.  We have tried, and continue to try, to thread the needle of modern software practices and tooling on these older platforms.

If there a particular use case you think we can help you with, we'd be happy to hear more about it.

**Comment by kript** [comment]
Not to hijack this thread, so I hope you dont mind me butting in, but a couple of thoughts around this, as another HPC sysadmin;

1. I've started putting some (very little!) time into getting a docker container to run the icommands as a drop in replacement for end users, with the aim of then developing a Singularity one, as like many HPC places, Singularity is OK on our clusters, but Docker is not. If that's the same for you as well @NickHastings might be something to consider collaborating on?

2. I wonder @trel if this also suggests an HPC Working Group, to address areas like this? I've seen a few requests like this on the mailing list and my recollection was a few were from HPC sysadmins/users trying to get icommands working without either root priv or the desire/ability to install a number of additional packages.

**Comment by NickHastings** [comment]
Hi Terrell,

thanks for the quick reply.

> The current dependency model of iRODS has it depend on a large number of upstream projects (we need to talk to many types of systems). Many of those upstream projects are not packaged by the systems that people run them on in a new enough version. We need(ed) newer dependencies on older operating systems.

Yes this is a very common situation.

> The only way to provide that combination is to build the dependencies ourselves. The only sane way to provide that combination for others is to build and package the dependencies and serve them from our own package repository.

Surely there is also the possibility that whoever is installing iRODs is capable of installing its dependencies. 

Using a traditional build and install either in /opt, /usr/local, ~/opt or ~/.local would have also been an option.  Eg. ```cmake -CMAKE_INSTALL_PREFIX=FOO && make && make install" (or the autotools or ninja/meson equivalents) can allow people to install irods and its dependencies in a familiar fashion.

Additionally, many people don't have root access or don't want to give root access to build scripts. 
 
> There is a way to build and install everything yourself, what we call a "non-package-install". The most current instructions, such as they are, are here: https://docs.irods.org/4.2.8/getting_started/installation/#non-package-install-run-in-place

Thanks for the link! Unfortunately that build seems to require downloading and building of very specific versions of things like autoconf, cmake, libssl, clang, libboost, imagemagick, etc that are all available independently from iRODs. I appreciate that you are trying to make installation easy for some older/incomplete systems but it seems to be making things overly complicated for  those running more conventional setups.

> Since many in our community are running iRODS at HPC centers and large universities or research institutes with long timelines, they are generally conservative about running newer operating systems. We have tried, and continue to try, to thread the needle of modern software practices and tooling on these older platforms.

Understood, I deploy software on a range of platforms and deal with similar issues.

> If there a particular use case you think we can help you with, we'd be happy to hear more about it.

I will try to work through the Non-Package Install and let you know.

Cheers,

Nick.

**Comment by NickHastings** [comment]
Hi @kript,

> Not to hijack this thread, so I hope you dont mind me butting in, but a couple of thoughts around this, as another HPC sysadmin;
> 
> 1. I've started putting some (very little!) time into getting a docker container to run the icommands as a drop in replacement for end users, with the aim of then developing a Singularity one, as like many HPC places, Singularity is OK on our clusters, but Docker is not. If that's the same for you as well @NickHastings might be something to consider collaborating on?

I'm only using the client commands not setting up a server so this is not really something that I need right now. FWIW I do however use singularity but not docker.

Cheers,

Nick.

**Comment by kript** [comment]
On 1 September 2020 at 00:21:27, Nick Hastings (notifications@github.com) wrote:

Hi @kript,

Not to hijack this thread, so I hope you dont mind me butting in, but a couple of thoughts around this, as another HPC sysadmin;

I've started putting some (very little!) time into getting a docker container to run the icommands as a drop in replacement for end users, with the aim of then developing a Singularity one, as like many HPC places, Singularity is OK on our clusters, but Docker is not. If that's the same for you as well @NickHastings might be something to consider collaborating on?
I'm only using the client commands not setting up a server so this is not really something that I need right now. FWIW I do however use singularity but not docker

The icommands in docker and then singularity was what I was looking at as well (for similar reasons I guess!), if I get anything working I’ll update you here.



John

**Comment by NickHastings** [comment]
Hi,

> The icommands in docker and then singularity was what I was looking at as well (for similar reasons I guess!), if I get anything working I’ll update you here. John

I just had a go at this as I thought it should be pretty trivial. I made a def file `CentOS7-icommands.def`, containing:
```
Bootstrap: docker
From: centos:7

%post
	yum update -y
	yum install -y wget
	rpm --import https://packages.irods.org/irods-signing-key.asc
	wget -O /etc/yum.repos.d/renci-irods.yum.repo https://packages.irods.org/renci-irods.yum.repo
	yum install -y irods-icommands
```
And discovered that irods-icommands has unsatisfied depencies:
```
# singularity build CentOS7-icommands.sif  CentOS7-icommands.def
INFO:    Starting build...
Getting image source signatures
Copying blob 75f829a71a1c [--------------------------------------] 0.0b / 0.0b
Copying config 52d3d92454 done  
Writing manifest to image destination
Storing signatures
2020/09/03 08:35:41  info unpack layer: sha256:75f829a71a1c5277a7abf55495ac8d16759691d980bf1d931795e5eb68a294c0
INFO:    Running post scriptlet
+ yum update -y
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
 * base: ftp.nara.wide.ad.jp
 * extras: ftp.nara.wide.ad.jp
 * updates: ftp.nara.wide.ad.jp
base                                                                                            | 3.6 kB  00:00:00     
extras                                                                                          | 2.9 kB  00:00:00     
updates                                                                                         | 2.9 kB  00:00:00     
(1/4): base/7/x86_64/group_gz                                                                   | 153 kB  00:00:00     
(2/4): extras/7/x86_64/primary_db                                                               | 206 kB  00:00:00     
(3/4): base/7/x86_64/primary_db                                                                 | 6.1 MB  00:00:01     
(4/4): updates/7/x86_64/primary_db                                                              | 4.5 MB  00:00:02     
No packages marked for update
+ yum install -y wget
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: ftp.nara.wide.ad.jp
 * extras: ftp.nara.wide.ad.jp
 * updates: ftp.nara.wide.ad.jp
Resolving Dependencies
--> Running transaction check
---> Package wget.x86_64 0:1.14-18.el7_6.1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=======================================================================================================================
 Package                 Arch                      Version                               Repository               Size
=======================================================================================================================
Installing:
 wget                    x86_64                    1.14-18.el7_6.1                       base                    547 k

Transaction Summary
=======================================================================================================================
Install  1 Package

Total download size: 547 k
Installed size: 2.0 M
Downloading packages:
warning: /var/cache/yum/x86_64/7/base/packages/wget-1.14-18.el7_6.1.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
Public key for wget-1.14-18.el7_6.1.x86_64.rpm is not installed
wget-1.14-18.el7_6.1.x86_64.rpm                                                                 | 547 kB  00:00:00     
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Importing GPG key 0xF4A80EB5:
 Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
 Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
 Package    : centos-release-7-8.2003.0.el7.centos.x86_64 (@CentOS)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : wget-1.14-18.el7_6.1.x86_64                                                                         1/1 
install-info: No such file or directory for /usr/share/info/wget.info.gz
  Verifying  : wget-1.14-18.el7_6.1.x86_64                                                                         1/1 

Installed:
  wget.x86_64 0:1.14-18.el7_6.1                                                                                        

Complete!
+ rpm --import https://packages.irods.org/irods-signing-key.asc
+ wget -O /etc/yum.repos.d/renci-irods.yum.repo https://packages.irods.org/renci-irods.yum.repo
--2020-09-02 23:35:51--  https://packages.irods.org/renci-irods.yum.repo
Resolving packages.irods.org (packages.irods.org)... 152.54.5.168
Connecting to packages.irods.org (packages.irods.org)|152.54.5.168|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 207
Saving to: '/etc/yum.repos.d/renci-irods.yum.repo'

100%[=============================================================================>] 207         --.-K/s   in 0s      

2020-09-02 23:35:52 (6.56 MB/s) - '/etc/yum.repos.d/renci-irods.yum.repo' saved [207/207]

+ yum install -y irods-icommands
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: ftp.nara.wide.ad.jp
 * extras: ftp.nara.wide.ad.jp
 * updates: ftp.nara.wide.ad.jp
renci-irods/7/x86_64/signature                                                                  |  819 B  00:00:00     
Retrieving key from https://packages.irods.org/irods-signing-key.asc
Importing GPG key 0xACF9B42B:
 Userid     : "iRODS Consortium <info@irods.org>"
 Fingerprint: 9014 ff9f 75c6 6c77 1f1c b574 bd92 5dbd acf9 b42b
 From       : https://packages.irods.org/irods-signing-key.asc
renci-irods/7/x86_64/signature                                                                  | 2.9 kB  00:00:00 !!! 
renci-irods/7/x86_64/primary_db                                                                 |  72 kB  00:00:01     
Resolving Dependencies
--> Running transaction check
---> Package irods-icommands.x86_64 0:4.2.8-1 will be installed
--> Processing Dependency: irods-runtime = 4.2.8 for package: irods-icommands-4.2.8-1.x86_64
--> Processing Dependency: irods-externals-zeromq4-14.1.6-0 for package: irods-icommands-4.2.8-1.x86_64
--> Processing Dependency: irods-externals-nanodbc2.13.0-0 for package: irods-icommands-4.2.8-1.x86_64
--> Processing Dependency: irods-externals-fmt6.1.2-1 for package: irods-icommands-4.2.8-1.x86_64
--> Processing Dependency: openssl for package: irods-icommands-4.2.8-1.x86_64
--> Processing Dependency: irods-externals-boost1.67.0-0 for package: irods-icommands-4.2.8-1.x86_64
--> Processing Dependency: irods-externals-avro1.9.0-0 for package: irods-icommands-4.2.8-1.x86_64
--> Processing Dependency: irods-externals-libarchive3.3.2-1 for package: irods-icommands-4.2.8-1.x86_64
--> Processing Dependency: irods-externals-json3.7.3-0 for package: irods-icommands-4.2.8-1.x86_64
--> Processing Dependency: irods-externals-clang-runtime6.0-0 for package: irods-icommands-4.2.8-1.x86_64
--> Processing Dependency: irods-externals-catch22.3.0-0 for package: irods-icommands-4.2.8-1.x86_64
--> Running transaction check
---> Package irods-externals-avro1.9.0-0.x86_64 0:1.0-1 will be installed
---> Package irods-externals-boost1.67.0-0.x86_64 0:1.0-1 will be installed
---> Package irods-externals-catch22.3.0-0.x86_64 0:1.0-1 will be installed
---> Package irods-externals-clang-runtime6.0-0.x86_64 0:1.0-1 will be installed
---> Package irods-externals-fmt6.1.2-1.x86_64 0:1.0-1 will be installed
---> Package irods-externals-json3.7.3-0.x86_64 0:1.0-1 will be installed
---> Package irods-externals-libarchive3.3.2-1.x86_64 0:1.0-1 will be installed
---> Package irods-externals-nanodbc2.13.0-0.x86_64 0:1.0-1 will be installed
---> Package irods-externals-zeromq4-14.1.6-0.x86_64 0:1.0-1 will be installed
---> Package irods-runtime.x86_64 0:4.2.8-1 will be installed
--> Processing Dependency: python-jsonschema for package: irods-runtime-4.2.8-1.x86_64
--> Processing Dependency: python-psutil for package: irods-runtime-4.2.8-1.x86_64
--> Processing Dependency: python-requests for package: irods-runtime-4.2.8-1.x86_64
---> Package openssl.x86_64 1:1.0.2k-19.el7 will be installed
--> Processing Dependency: make for package: 1:openssl-1.0.2k-19.el7.x86_64
--> Running transaction check
---> Package irods-runtime.x86_64 0:4.2.8-1 will be installed
--> Processing Dependency: python-jsonschema for package: irods-runtime-4.2.8-1.x86_64
--> Processing Dependency: python-psutil for package: irods-runtime-4.2.8-1.x86_64
---> Package make.x86_64 1:3.82-24.el7 will be installed
---> Package python-requests.noarch 0:2.6.0-9.el7_8 will be installed
--> Processing Dependency: python-urllib3 >= 1.10.2-1 for package: python-requests-2.6.0-9.el7_8.noarch
--> Running transaction check
---> Package irods-runtime.x86_64 0:4.2.8-1 will be installed
--> Processing Dependency: python-jsonschema for package: irods-runtime-4.2.8-1.x86_64
--> Processing Dependency: python-psutil for package: irods-runtime-4.2.8-1.x86_64
---> Package python-urllib3.noarch 0:1.10.2-7.el7 will be installed
--> Processing Dependency: python-six for package: python-urllib3-1.10.2-7.el7.noarch
--> Processing Dependency: python-ipaddress for package: python-urllib3-1.10.2-7.el7.noarch
--> Processing Dependency: python-backports-ssl_match_hostname for package: python-urllib3-1.10.2-7.el7.noarch
--> Running transaction check
---> Package irods-runtime.x86_64 0:4.2.8-1 will be installed
--> Processing Dependency: python-jsonschema for package: irods-runtime-4.2.8-1.x86_64
--> Processing Dependency: python-psutil for package: irods-runtime-4.2.8-1.x86_64
---> Package python-backports-ssl_match_hostname.noarch 0:3.5.0.1-1.el7 will be installed
--> Processing Dependency: python-backports for package: python-backports-ssl_match_hostname-3.5.0.1-1.el7.noarch
---> Package python-ipaddress.noarch 0:1.0.16-2.el7 will be installed
---> Package python-six.noarch 0:1.9.0-2.el7 will be installed
--> Running transaction check
---> Package irods-runtime.x86_64 0:4.2.8-1 will be installed
--> Processing Dependency: python-jsonschema for package: irods-runtime-4.2.8-1.x86_64
--> Processing Dependency: python-psutil for package: irods-runtime-4.2.8-1.x86_64
---> Package python-backports.x86_64 0:1.0-8.el7 will be installed
--> Finished Dependency Resolution
Error: Package: irods-runtime-4.2.8-1.x86_64 (renci-irods)
           Requires: python-psutil
Error: Package: irods-runtime-4.2.8-1.x86_64 (renci-irods)
           Requires: python-jsonschema
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
FATAL:   While performing build: while running engine: exit status 1
singularity build CentOS7-icommands.sif CentOS7-icommands.def  5.67s user 1.12s system 30% cpu 21.882 total
```
I tried the same thing with Ubuntu using the following def file:
```
# cat Ubuntu1804-icommands.def
Bootstrap: docker
From: ubuntu:18.04

%post
	apt update
	apt upgrade -y
	apt install -y gnupg wget
	wget -qO - https://packages.irods.org/irods-signing-key.asc | apt-key add -
        echo "deb [arch=amd64] https://packages.irods.org/apt bionic main" > /etc/apt/sources.list.d/renci-irods.list
	apt update
	apt install -y irods-icommands
```
Then built an image with
```
# singularity build Ubuntu1804-icommands.sif Ubuntu1804-icommands.def
```
I won't post the output here since it seemed to work.

I also note that I tried with Debian 9 using the same Ubuntu bionic repo but it failed because irods wanted libssl1.0 but Debian 9 ships with libssl1.1.

I guess an issue should probably be raised about the missing python dependencies on CentOS7. A quick google indicates that they may be from https://centos.pkgs.org/7/springdale-computational-x86_64/python-jsonschema-2.5.1-3.sdl7.noarch.rpm.html but I didn't look very far into it.

Cheers,

Nick.

**Comment by trel** [comment]
no dependencies missing - just not discoverable without the centos7 package `epel-release` installed first.

this gives access to `python-psutil` and `python-jsonschema`.

**Comment by trel** [comment]
the libssl1.1 on debian issue ->   https://github.com/irods/irods/pull/4999

**Comment by NickHastings** [comment]
Repo at https://github.com/NickHastings/icommands-images

**Comment by trel** [comment]
Renaming this issue to be about providing a method for building a userspace relocatable tarball of the icommands.

**Comment by trel** [comment]
I think we did it.   Closing!
