### ISSUE TITLE
Add PUT KW during iput.

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods#5097]
## Feature

Add a keyword that indicates that the client is doing a PUT request.

This is needed by the S3 plugin to determine on writes whether we should use a cache file.  If this keyword is set the plugin will not use cache.  The expectation is that the client is following some rules:

1. If it is a single thread put, all bytes must be written in sequential order starting from the beginning.
2. If it is multiple threaded:
- Each thread writes a full part in sequential order.
- The file must be broken up into parts in a similar manner as is done with iput so that the parts numbers can be determined by the offset.

**Comment by trel** [comment]
is this still needed?

**Comment by JustinKyleJames** [comment]
I don't believe this is needed as the plugin is using different criteria to determine if there is a full file put.  Closing this issue.
