### ISSUE TITLE
imeta addw returns non-zero on seeming success

### ISSUE THREAD

**Issue by bh9** [irods/irods#5101]
- [ ] master
- [ ] 4-2-stable
------
### iRODS Version, OS and Version
4.2.7 Ubuntu 18.04

### What did you try to do?
add metadata to every object in a collection with 
`$ imeta addw -d /archive/HCA/10X/WSSS_END9263313/starsolo/% sample WSSS_END9263313`

### Expected behavior
All the objects have the metadata set and return code is 0

### Observed behavior (including steps to reproduce, if applicable)
All the objects have the metadata set, but the return code is 4
Output suggests setting was successful:
```
AVU added to 3 data-objects
```

**Comment by SwooshyCueb** [comment]
This one's fixed in both branches, so if someone could check the boxes for me, I'd appreciate it

**Comment by trel** [comment]
done
