### ISSUE TITLE
Do we need an imeta addw for collections?

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#5131]
## Feature

The metadata modify API can be invoked with an operation of `rmw` to delete wildcarded set of Attr/Value/Units fields by wildcard, and this works for both data objects and collections:
```
imeta rmw -d data % % %
imeta rmw -C coll  % % %
```
The operation `addw` can be used to add the same AVU to multiple data objects (matching a wildcard but limited to the same parent collection)  but, as the imeta manpage explains, this applies only to data objects ("-d").  It does not work for collections("-C"):
```
$ imeta addw -d test% x y z                           
AVU added to 3 data-objects
$ imkdir coll-a coll-b coll-c
$ imeta addw -C coll-% a b c
remote addresses: 127.0.0.1 ERROR: rcModAVUMetadata failed with error -808000 CAT_NO_ROWS_FOUND 
AVU added to -808000 data-objects
```
(The second command does not in fact change any data objects' metadata, despite that last cryptic message).

### Expected behavior

What is expected is up for opinions (@trel  @jasoncoposky @alanking @korydraughn ?):  If implemented should a command like `imeta addw -C /tempZone/home/rods/%  myA myV myU` have (A) a recursive effect (as genquery matching would have it) or (B) only affect the collections nested directly under the parent mentioned? Or (C) is there no real necessity for this ? I would lean toward (B) or (C) since (B) would reflect similar behavior as with the data object name matching in `imeta rmw -d %pattern% ...`

**Comment by trel** [comment]
- A) definitely not
- B) seems reasonable (and like you said, would mirror rmw behavior) - need to think through some horrible edge cases a bit more...
- C) status quo

Without a direct use case from the community, I vote C) for now... and we leave this open for future searchers to find.

Separately, we should clean up that mess of an error message returned from your `imeta addw -C` above.

**Comment by d-w-moore** [comment]
Also, is any of this covered by the new atomic metadata operations? Does it let us apply an AVU to multiple objects simultaneously?

**Comment by trel** [comment]
no - multiple operations on a single entity (collection or data object) are the only thing supported at this time within a single transaction.

**Comment by korydraughn** [comment]
`imeta addw` is deprecated. See #6416.

Closing as there's nothing actionable here.
