### ISSUE TITLE
Consider adding overloads to the replica library that accept leaf resource names instead of replica numbers

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#5142]
- [x] master
- [x] 4-2-stable
---
## Feature
The replica library allows devs to update specific replicas using the correct replica number. However, there are many times when devs only have resource names. In this case, the resource name must be resolved to a replica number. It would be great if the replica library accepted leaf resource names given how often this scenario is encountered.

**Comment by alanking** [comment]
This can be closed. I can't checkbox
