### ISSUE TITLE
Consider adding functions that allow leaf resource names to be converted to replica numbers and vice versa

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#5143]
- [x] master
- [x] 4-2-stable
---
## Feature
These conversions occur frequently and people handle this differently all of the time. It would be nice if these very common operations were provided as functions.

## Proposed API Functions
These are only ideas. These would throw exceptions if the conversion cannot be done. As an alternative, these could return `std::optional`s.
- `auto to_leaf_resource(conn, path, replica_number) -> string`
- `auto to_replica_number(conn, path, leaf_resource_name) -> int`

**Comment by alanking** [comment]
This can be closed. I can't checkbox
