### ISSUE TITLE
Add functions to replica library that allow checking if a replica exists

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#5151]
- [x] master
- [x] 4-2-stable
---
## Feature
It would be helpful if the library provided functions that check existence of replicas.

## Proposed API Functions
- `auto replica_exists(conn, path, replica_number) -> bool`
- `auto replica_exists(conn, path, leaf_resource_name) -> bool`

**Comment by alanking** [comment]
This can be closed. I can't checkbox
