### ISSUE TITLE
resource_id information missing from izonereport json

### ISSUE THREAD

**Issue by trel** [irods/irods#5159]
### iRODS Version, OS and Version

4.2.8

### What did you try to do?

`izonereport > json.file`

visually inspect `json.file` to see resource hierarchy

### Expected behavior

enough information to reconstruct the hierarchies in the Zone

### Observed behavior (including steps to reproduce, if applicable)

Each resource reports a `parent_id`, but the resources themselves do not have their `resource_id` - so there is not enough information to reconstruct/represent/understand the resource hierarchies

**Comment by korydraughn** [comment]
resolved by #5170
