### ISSUE TITLE
zonereport does not include resc_id information

### ISSUE THREAD

**Issue by trel** [irods/irods#5170]
- [x] master
- [x] 4-2-stable
-------

### iRODS Version, OS and Version
4.2.8

### What did you try to do?

izonereport - and then construct the resource hierarchies from the included information

### Expected behavior

izonereport should provide `resc_id` information for each named/included resource

### Observed behavior (including steps to reproduce, if applicable)

`parent_id` is provided, but no `resc_id` - so it's impossible to know how to build the tree(s)

**Comment by SwooshyCueb** [comment]
Just to make sure I'm on the same page, `parent_id` is currently provided as `parent_resource`, yes?

**Comment by trel** [comment]
that is correct - in 4.1, all resources were communicated by string name, and in 4.2, we moved to integers for a variety of performance and consistency reasons.

we now provide the id, rather than the names when populating the zonereport.

**Comment by SwooshyCueb** [comment]
#5173 is merged, master can be checked off

**Comment by trel** [comment]
got it
