### ISSUE TITLE
Default number of threads advanced setting should be "default" on upgrade

### ISSUE THREAD

**Issue by jasoncoposky** [irods/irods#5171]
- [ ] master
- [ ] 4-2-stable
-----

Given the results of a 2016 investigation (https://irods.org/uploads/2016/09/russell2016-iRODS-networking-419.pdf) it was concluded that 3 threads were the optimal value given a 10gb network link.

The upgrade script mechanism can query the advanced setting in /etc/irods/server_config.json and change it automatically.  If it is not 16 then do not change the value.

**Comment by SwooshyCueb** [comment]
I'm in favor of pushing this to 4.2.10 or the 4.2 backlog if nobody else thinks they can get to it before the 4.2.9 deadline.

**Comment by trel** [comment]
Agreed - don't want to rush out a default setting change before a release.

**Comment by trel** [comment]
Change in decision - we won't change this setting on upgrade.   Experts can change this setting as needed.

New installs already default to "default" as of 4.2.9.
