### ISSUE TITLE
Request for icommands to be built for Ubuntu 20.04

### ISSUE THREAD

**Issue by edwins** [irods/irods#5174]
Howdy,

If there's a better place to post this request, I'm happy to repost elsewhere. 

We (CyVerse) have users as well as internally managed systems that are using Ubuntu 20.04 or derivative distros (e.g. Linux Mint). Could https://packages.irods.org/ be updated with Ubuntu 20.04 packages, specifically irods-icommands? Ubuntu 20.04 was released in April 2020.

Also, another consideration might be to have separate statically-linked binaries that might alleviate the pressure to update distro-specific binaries whenever there is a new version. 

Thank you,
Edwin

**Comment by your-highness** [comment]
Any update on the Ubuntu 20.04 support via packages.irods.org ?

**Comment by trel** [comment]
No, but if you're interested in building it yourself, you can try the existing PR

https://github.com/irods/irods/pull/4999/files

**Comment by your-highness** [comment]
Thanks @trel . Will do. I missed #4999 when checking open issues.

**Comment by trel** [comment]
We do have too many :)

**Comment by korydraughn** [comment]
@trel Should this be closed now that 4.3 supports Ubuntu 20 and Python 3?

**Comment by trel** [comment]
Yes, closing.   Thanks.
