### ISSUE TITLE
parallel transfer in a network with firewalls drops 'long idle' connections

### ISSUE THREAD

**Issue by trel** [irods/irods#5218]
### iRODS Version, OS and Version

4.2.8

### What did you try to do?

From this discussion:
    https://groups.google.com/g/irod-chat/c/gSV93IXaXjY

A parallel transfer in a network with firewalls that are dropping 'long idle' connections

 
### Expected behavior

iRODS moves the file, nobody complains, transfer successful

### Observed behavior (including steps to reproduce, if applicable)

When a large file transfer occurs, it happens point-to-point between the source and destination, but the initial connection that setup/configured the direct parallel transfer portal sits idle while the transfer is occurring between the other two machines.

If a firewall is configured to drop idle connections, the successful Agent cannot notify the original caller that the file has completed... its connection is gone.

A possible solution to this is for the iRODS server(s) to tickle the initial connection, possibly with 'TCP Keepalive' packets.

**Comment by kript** [comment]
This seems to me a much nicer write up of #3986 along with possibly #5217 . 
We have done some tuning of this with `net.ipv4.tcp_keepalive_time` , from our docs, which helps, but does not avoid the control connection timing out (because it doesn't seem to use the keep alives);


> If a machine needs to communicate across a firewall with a protocol that will have long periods of inactivity then it is likely that a session timeout will occur on the firewall. Most 'long lived' protocols have a built in keep alive (eg ssh) however some of these require the keep alive to be enabled
>
> This is because the default TCP session timeout is 30 minutes, this is an idle timeout not an absolute timeout.
>
>It is unwise to change this on the firewall as this would delay stale session clean up & the session table is a finite size.
>
>The correct way to avoid this issue is to use TCP Keepalives, these are on by default in the linux kernel but have a very long interval (2 hours). Tuning this to 20 minutes avoids the firewall session timeout.
>
`sysctl -w net.ipv4.tcp_keepalive_time=1200`
>add the appropriate entry to the sysctl.conf file too.
>
>Under Windows this TCP Keepalives are off by default they need to be enabled on a per-interface basis with the following registry entry:-
`\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Paramters\Interfaces\{Interface UUID}`

**Comment by kript** [comment]
Might be worth adding something around the above to the best practices section of the docs?

**Comment by trel** [comment]
yes, and i think we've just gotten confirmation in the google group as well.   will definitely write this up more cleanly as a best practice or tips and tricks.

**Comment by trel** [comment]
to be clear, this setting would need to be set on the provider?   all the iRODS servers interacting with the aggressive firewall?

and... this is a kernel setting... so there is nothing that the iRODS server code, itself, can/should do?  this is now a documentation issue only?

**Comment by trel** [comment]
From the thread:

> For our configuration, we fixed
it   by  tuning   the  `net.ipv4.tcp_keepalive_time`
parameter  to  5mn.   The connection between  the
catalog provider and the catalog consumer is thus
maintained  over a  long  transfer.  The  firewall
probably killed  the connection in these first 5
inactive minutes.

**Comment by trel** [comment]
another case has been confirmed to have been healed with this approach.

using https://tldp.org/HOWTO/html_single/TCP-Keepalive-HOWTO/#usingkeepalive

```
# cat /proc/sys/net/ipv4/tcp_keepalive_time
7200
# echo 600 > /proc/sys/net/ipv4/tcp_keepalive_time
# cat /proc/sys/net/ipv4/tcp_keepalive_time
600
```
and then to make it rebootable... added to `/etc/sysctl.d/99-sysctl.conf`:
```
net.ipv4.tcp_keepalive_time = 600
```

will definitely document this as a best practice and link from the troubleshooting section.
