### ISSUE TITLE
leftover 'temporary' rulefile.re.[pid] causing stacktraces once PIDs wrap

### ISSUE THREAD

**Issue by trel** [irods/irods#5224]
- [x] master
- [x] 4-2-stable
-----

### iRODS Version, OS and Version
4.2.7

### What did you try to do?
with an additional non-core.re rulebase configured (in this example... `training.re`)...

interact with iRODS, creating an Agent, which happens to re-use an old PID

### Expected behavior

no surprises - things just run

### Observed behavior (including steps to reproduce, if applicable)

`SYS_INTERNAL_ERR` sent to the client...

rodsLog has...
```
Nov  3 02:48:23 pid:24762 NOTICE: proc_results_for_rebalance: creating new replica for data id [39104] from [replResc;child1] on [replResc;child2]
terminating with uncaught exception of type boost::filesystem::filesystem_error: boost::filesystem::copy_file: File exists: "/etc/irods/training.re", "/etc/irods/training.re.18125"
Caught signal [6]. Dumping stacktrace and exiting
```

It seems the iRODS server should remove all leftover *.re.[pid] files on startup (based on its currently configured `re_rulebase_set`...   nobody else should be needing them at that time.

**Comment by stsnel** [comment]
@trel I think this issue is also described in https://github.com/irods/irods/issues/4080 . Maybe these issues can be merged?

**Comment by trel** [comment]
Indeed!  I thought we had already fixed this, but couldn't find it when I went looking...

The partial fix is mentioned in that issue:
    https://github.com/tempoz/irods/commits/cache_fix

We'll leave these both open for now as they have a slightly different focus - but they can both be fixed at the same time.

**Comment by kript** [comment]
any chance of a fix in 4.2.9? We get this too.

**Comment by trel** [comment]
yes, quite possible.

**Comment by trel** [comment]
this is handled with a regex removal for now.

a more complete solution (tempfiles only, no actual pidfiles) can occur later with #4080.
