### ISSUE TITLE
unix vault security: mkdir before iCAT access control?

### ISSUE THREAD

**Issue by mcast** [irods/irods#5235]
### iRODS Version, OS and Version

Client & server all iRODS 4.2.7 / Ubuntu Bionic 18.04; most recently I spoke to @bh9 about our system and this issue.

### What did you try to do?

1. trying to `iput -R res_foo file place somewhere`,
2. physical `mkdir` on `res_foo` seems to happen first?
    * At least, I see it can fail `status = -520013 UNIX_FILE_MKDIR_ERR, Permission denied`
    * With the zones I have available here, it's not easy for me to view the inside to see a successful `mkdir` triggered this way
3. `iput` begins the write, but stops with `status = -818000 CAT_NO_ACCESS_PERMISSION`

I'm reporting this because

* the order of security checks seems to be wrong
* I think it's a tiny (tending towards nothing) security risk
    * all I can do is a physical `mkdir` on my chosen resource, provided the `imkdir` was already done by someone with permission
* in an installation with very large number of collections, there may be a minor DoS attack possible
    * by provoking physical `mkdir` on every iRES for all collections, when those directories otherwise have no reason to be created
    * as far as I know, nothing causes `rmdir` on `unix file system` vaults
    * we're left with an entirely empty directory tree which simply wastes time each time it is fully traversed

### Expected behavior

Permission to `iput` to be checked *before* calling the `mkdir`.

### Observed behavior (including steps to reproduce, if applicable)

Permission to `iput` is checked *after* calling the `mkdir`; or it seems this way when a secondary error is provoked in `mkdir` by (?) incorrect iRES filesystem permissions.

**Comment by trel** [comment]
Will definitely investigate.   Quite possibly we're stomping/ignoring the 'mkdir' error incorrectly - or the two calls, like you said, are just in the wrong order.

The reason iRODS doesn't reach back out and 'clean' up directories on physical media is that that media could be very far away and slow down other synchronous processing.  Additionally, this would be resource-plugin-specific as object storage doesn't even have directories...

Agreed there could be a little standalone utility that could do that work...  what do you do now to 'check and clean' the empty directory tree?

**Comment by bh9** [comment]
> what do you do now to 'check and clean' the empty directory tree?  

we don't, we just leave them

**Comment by trel** [comment]
got it.

**Comment by mcast** [comment]
> The reason iRODS doesn't reach back out and 'clean' up directories on physical media is that that media could be very far away and slow down other synchronous processing.

It makes sense that `irmdir` doesn't need to / may not want to `rmdir`.

For me, the time `rmdir` should happen is when removing the last file from a directory in the `unix file system` vault. Possibly it will be immediately followed by a re-`mkdir` if there is an `iput`, but that seems like it ought to be a smaller inefficiency.

> Additionally, this would be resource-plugin-specific as object storage doesn't even have directories...

That's a good reason to put the resource-plugin-specific tidying up in the resource plugin :-)

> Agreed there could be a little standalone utility that could do that work... what do you do now to 'check and clean' the empty directory tree?

We have so far refrained from creating that utility, partly for the development cost and partly for the rule of "don't write in storage managed by another piece of code".

We are left with some large and deep directory trees on some physical storage. They only bother me when I remember they exist, so I try to forget them. It now turns out that the broom which sweeps those away is the hardware refresh cycle!

**Comment by trel** [comment]
> hardware refresh cycle

now we're talkin'!

also... apparently `find` is our friend.

```
find ROOTDIR -type d -empty -delete
```

**Comment by trel** [comment]
regarding the empty directory cleanup... https://github.com/irods/irods/issues/3124

**Comment by trel** [comment]
> by provoking physical mkdir on every iRES for all collections, when those directories otherwise have no reason to be created

The `mkdir` is only attempted on the selected storage resource, not all storage resources... so I'm not sure of this part of the claim...

**Comment by trel** [comment]
Investigating further...  I'm not seeing the particular behavior you initially reported...

As rods user (rodsadmin, but ... shouldn't matter?)
```
$ ienv | grep user
irods_user_name - rods
```
On 4.2.8
```
$ imiscsvrinfo | grep relVersion
relVersion=rods4.2.8
```

Resource with vault path that won't work...
```
$ ilsresc -l badresc | grep vault
vault: /badroot
```
---

Putting a file into an existing collection without iRODS permissions...
```
$ iput -R badresc badfile /tempZone/home/bob
remote addresses: 127.0.1.1 ERROR: putUtil: put error for /tempZone/home/bob/badfile, status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
Level 0: no permission to update collection '/tempZone/home/bob'
```
rodsLog...
```
Nov  6 13:43:43 pid:10434 remote addresses: 127.0.0.1, ::1 ERROR: [-]   /irods_git_repo/server/api/src/rsRegDataObj.cpp:85:int _rsRegDataObj(rsComm_t *, dataObjInfo_t *) :  status [CAT_NO_ACCESS_PERMISSION]  errno [] -- message [_rsRegDataObj - Failed to register data object "/tempZone/home/bob/badfile" - CAT_NO_ACCESS_PERMISSION ]

Nov  6 13:43:43 pid:10434 NOTICE: _l3DataPutSingleBuf: rsRegDataObj for /tempZone/home/bob/badfile failed, status = -818000
Nov  6 13:43:43 pid:10434 remote addresses: 127.0.0.1, ::1 ERROR: _rsDataObjClose - getSizeInVault failed [-516002]
```

No `mkdir` attempted, as expected.

---
Putting a file into a new collection without iRODS permissions...
```
$ iput -R badresc badfile /tempZone/home/bob/newcoll/childcoll/
remote addresses: 127.0.1.1 ERROR: putUtil: put error for /tempZone/home/bob/newcoll/childcoll, status = -814000 status = -814000 CAT_UNKNOWN_COLLECTION
Level 0: collection '/tempZone/home/bob/newcoll' is unknown
```
rodsLog...
```
Nov  6 13:57:52 pid:12362 remote addresses: 127.0.0.1, ::1 ERROR: [-]   /irods_git_repo/server/api/src/rsRegDataObj.cpp:85:int _rsRegDataObj(rsComm_t *, dataObjInfo_t *) :  status [CAT_UNKNOWN_COLLECTION]  errno [] -- message [_rsRegDataObj - Failed to register data object "/tempZone/home/bob/newcoll/childcoll" - CAT_UNKNOWN_COLLECTION ]

Nov  6 13:57:52 pid:12362 NOTICE: _l3DataPutSingleBuf: rsRegDataObj for /tempZone/home/bob/newcoll/childcoll failed, status = -814000
Nov  6 13:57:52 pid:12362 remote addresses: 127.0.0.1, ::1 ERROR: _rsDataObjClose - getSizeInVault failed [-516002]
```

No `mkdir` attempted, it appears the logical path was checked prior to the permission check.

---

Putting a file into a new collection with iRODS permissions...
```
$ iput -R badresc badfile /tempZone/home/rods/new/coll/
remote addresses: 127.0.1.1 ERROR: putUtil: put error for /tempZone/home/rods/new/coll, status = -814000 status = -814000 CAT_UNKNOWN_COLLECTION
Level 0: collection '/tempZone/home/rods/new' is unknown
```
rodsLog...
```
Nov  6 14:01:46 pid:13002 remote addresses: 127.0.0.1, ::1 ERROR: [-]   /irods_git_repo/server/api/src/rsRegDataObj.cpp:85:int _rsRegDataObj(rsComm_t *, dataObjInfo_t *) :  status [CAT_UNKNOWN_COLLECTION]  errno [] -- message [_rsRegDataObj - Failed to register data object "/tempZone/home/rods/new/coll" - CAT_UNKNOWN_COLLECTION ]

Nov  6 14:01:46 pid:13002 NOTICE: _l3DataPutSingleBuf: rsRegDataObj for /tempZone/home/rods/new/coll failed, status = -814000
Nov  6 14:01:46 pid:13002 remote addresses: 127.0.0.1, ::1 ERROR: _rsDataObjClose - getSizeInVault failed [-516002]
```

No `mkdir` attempted, same error stack as above without permissions.

---

I think I'm seeing the result of the work done in https://github.com/irods/irods/issues/4410.

The catalog is now checked (registration) before anyone touches any storage.

So... this is fixed in 4.2.8 already?

**Comment by mcast** [comment]
> > * in an installation with very large number of collections, there may be a minor DoS attack possible
> >     * by provoking physical mkdir on every iRES for all collections, when those directories otherwise have no reason to be created
>
> The `mkdir` is only attempted on the selected storage resource, not all storage resources... so I'm not sure of this part of the claim...

In answering the question "if this is a security problem, what's the worst that could happen?", I imagine that [Mallory](https://en.wikipedia.org/wiki/Alice_and_Bob#Cast_of_characters) could, over time, cause `mkdir` of millions of pointless empty directory *per iRES*.

One of our large zones has almost 4.8E6 collections across (?) 262 iRES partitions; but with provoking `mkdir` at 5Hz it would take 8 years to populate them all!

> I think I'm seeing the result of the work done in #4410.  
> The catalog is now checked (registration) before anyone touches any storage.  
> So... this is fixed in 4.2.8 already?

If so, that would be great ✅.   However it's rather hard for me to verify because I don't have direct vault write access (yet) and I don't have control of version rollout.

Do you have a 4.2.7 handy to check that your method above reproduces the `status = -520013 UNIX_FILE_MKDIR_ERR` ?  I'm only guessing about the sequence of events that causes it.

**Comment by trel** [comment]
In a container, running vanilla 4.2.7...
```
irods@12f7caa3f5be:~$ imiscsvrinfo | grep relVersion
relVersion=rods4.2.7

irods@12f7caa3f5be:~$ iadmin mkresc badresc unixfilesystem $(hostname):/badroot
Creating resource:
Name:           "badresc"
Type:           "unixfilesystem"
Host:           "12f7caa3f5be"
Path:           "/badroot"
Context:        ""

irods@12f7caa3f5be:~$ echo "bad" > badfile

irods@12f7caa3f5be:~$ iadmin mkuser bob rodsuser

irods@12f7caa3f5be:~$ iput -R badresc badfile /tempZone/home/bob
remote addresses: 172.17.0.2 ERROR: putUtil: put error for /tempZone/home/bob/badfile, status = -520013 status = -520013 UNIX_FILE_MKDIR_ERR, Permission denied
```

rodsLog...
```
Nov 13 03:27:07 pid:556 remote addresses: 127.0.0.1, 172.17.0.2 ERROR: [-]      /irods/server/core/src/fileOpr.cpp:252:int mkFileDirR(rsComm_t *, size_t, const std::string &, const std::string &, int) :  status [UNIX_FILE_MKDIR_ERR]  errno [Permission denied] -- message [fileMkdir for [/badroot]]
        [-]     /irods/server/drivers/src/fileDriver.cpp:290:irods::error fileMkdir(rsComm_t *, irods::first_class_object_ptr) :  status [UNIX_FILE_MKDIR_ERR]  errno [Permission denied] -- message [failed to call 'mkdir']
                [-]     /irods/plugins/resources/unixfilesystem/libunixfilesystem.cpp:989:irods::error unix_file_mkdir(irods::plugin_context &) :  status [UNIX_FILE_MKDIR_ERR]  errno [Permission denied] -- message [Mkdir error for "/badroot", errno = "Permission denied", status = -520013.]

Nov 13 03:27:07 pid:556 remote addresses: 127.0.0.1, 172.17.0.2 ERROR: mkFileDirR failed in mkDirForFilePath with status -520013
Nov 13 03:27:07 pid:556 remote addresses: 127.0.0.1, 172.17.0.2 ERROR: Unable to make directory: "/badroot/home/bob/badfile"
Nov 13 03:27:07 pid:556 remote addresses: 127.0.0.1, 172.17.0.2 ERROR: _rsDataObjClose - getSizeInVault failed [-516002]
```
hit the original `UNIX_FILE_MKDIR_ERR` mentioned in the original description...

----

Then... I upgraded to 4.2.8 in the same container... 
```
irods@12f7caa3f5be:~$ imiscsvrinfo | grep relVersion
relVersion=rods4.2.8
```

and tried again...
```
irods@12f7caa3f5be:~$ iput -R badresc badfile /tempZone/home/bob
remote addresses: 172.17.0.2 ERROR: putUtil: put error for /tempZone/home/bob/badfile, status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
Level 0: no permission to update collection '/tempZone/home/bob'
```
rodsLog...
```
Nov 13 03:31:08 pid:728 remote addresses: 127.0.0.1, 172.17.0.2 ERROR: [-]      /irods_git_repo/server/api/src/rsRegDataObj.cpp:85:int _rsRegDataObj(rsComm_t *, dataObjInfo_t *) :  status [CAT_NO_ACCESS_PERMISSION]  errno [] -- message [_rsRegDataObj - Failed to register data object "/tempZone/home/bob/badfile" - CAT_NO_ACCESS_PERMISSION ]

Nov 13 03:31:08 pid:728 NOTICE: _l3DataPutSingleBuf: rsRegDataObj for /tempZone/home/bob/badfile failed, status = -818000
Nov 13 03:31:08 pid:728 remote addresses: 127.0.0.1, 172.17.0.2 ERROR: _rsDataObjClose - getSizeInVault failed [-516002]
```
No `mkdir` attempted.

I think we did it.

**Comment by mcast** [comment]
Thanks for fixing it before I reported it 😀 . I'm not sure what our upgrade schedule is but it does demonstrate that being behind can make extra work...  just as being always up-to-date can. 🤷‍♂️
