### ISSUE TITLE
Failed to update irods_environment.json on brand-new iinit

### ISSUE THREAD

**Issue by alanking** [irods/irods#5239]
- [x] master
- [x] 4-2-stable
---
When `iinit`'ing for the first time, an error message appears after successfully authenticating with the server:

```
# iinit
 ERROR: environment_properties::capture: missing environment file. should be at [/root/.irods/irods_environment.json]
One or more fields in your iRODS environment file (irods_environment.json) are
missing; please enter them.
Enter the host name (DNS) of the server to connect to: localhost
Enter the port number: 1247
Enter your irods user name: bobby
Enter your irods zone: otherZone
Those values will be added to your environment file (for use by
other iCommands) if the login succeeds.

Enter your current iRODS password:
Failed to update [/root/.irods/irods_environment.json]
```

Everything works fine and the `irods_environment.json` file is properly formatted. Please prevent this message from appearing to the user.

**Comment by SwooshyCueb** [comment]
I'm in favor of pushing this to 4.2.10 or the 4.2 backlog if nobody else thinks they can get to it before the 4.2.9 deadline.

**Comment by trel** [comment]
This one throws new users off and makes training sessions awkward.    Should try and get this one done.

**Comment by trel** [comment]
checkboxed
