### ISSUE TITLE
irods-icommands installation fails on Ubuntu20

### ISSUE THREAD

**Issue by ReneKat** [irods/irods#5246]
Hello there,
I'm uncertain if this is the right location for this error.
I am trying to install irods-icommands using instructions at: https://cyverse-data-store-guide.readthedocs-hosted.com/en/latest/step2.html

However, the version is for ubuntu14 and has an outdated dependency libssl1.0.0 which was updated to libssl1.1 in Ubuntu20. 

The error is: 
The following packages have unmet dependencies:
 irods-icommands : Depends: libssl1.0.0 but it is not installable
E: Unable to correct problems, you have held broken packages.

I have libssl1.1 installed however, I'm uncertain how to force the install using the updated dependency. 
Thanks for any advice! 
Best,
Rene

**Comment by your-highness** [comment]
See also https://github.com/irods/irods/issues/4883#issuecomment-731210617

**Comment by korydraughn** [comment]
@trel Should this be closed now that support for Ubuntu 20 is available for 4.3?

**Comment by trel** [comment]
Yes, closing.
