### ISSUE TITLE
Allow migration of the delay server

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#5249]
## Feature
The delay server should be runnable on any iRODS server. To allow this, the following changes need to be made:
- Store which server is responsible for running the delay server in the catalog.
  - This information will be stored in `r_grid_configuration` and manipulated via `iadmin`.
  - Option Name: `delay_server_hostname`
  - Option Value: **the hostname of the computer responsible for the delay server**
- The delay server needs to be updated to do the following:
  1. Check if it is still labeled as the delay server.
  2. If the server is still labeled as the delay server, then it should proceed as normal.
  3. If the server is no longer labeled as the delay server, then it should exit gracefully. Rules that are being executed will be allowed to finish. Pending rules will not be executed.

The solution assumes that the administrator will make sure no rules are being processed by the old delay server before standing up the new delay server.

**Comment by kript** [comment]
Can I ask when the delay server does its validity check? On startup, or every X mins? 
I can see value in an HA situation to be able to drain and migrate over, and also one may not want to restart the service to change the state of the delay server and interrupt other processes.

**Comment by korydraughn** [comment]
We haven't discussed all of the details yet, but here are a few possibilities for when the validity check could occur:
- Check during server startup
- Check after the delay server wakes up, but before looking up the next set of rules to execute
- Check before executing a pending rule
- Check every _X_ minutes

We are considering real-time migration, but haven't looked deeply into it just yet.

**Comment by trel** [comment]
Option 1 would be ... nearly useless for handsfree operation.

Option 2 would work most of the time, but introduces a window where the delay_server value in the catalog has been changed, but the now-old delay server is still doing the work it previously pulled from of the queue (it does not remove it from the queue in the catalog until it has succeeded).  Any new delay server that has stood up could get and operate on the same work elsewhere.  I think we want to avoid this situation.

Option 3 would be the safest, but also the most expensive (more network/database traffic).

Option 4 is ... the same as Option 2?

Can we find an option 2.5?  Should we mark the jobs that have been pulled by the delay server as 'taken by [hostname]'... preventing another server from picking them up?   When the outgoing delay server cleanly exits, those jobs are removed (like normal) or updated to no longer be marked as 'taken'.  Any jobs that are left orphaned in the 'taken' state (because of an error in the delay server or elsewhere) could be cleaned up after a day or so (another knob?) if they have not been completed/removed.

**Comment by jasoncoposky** [comment]
I believe option 2.5 would add considerably more network traffic than just checking once a sleep cycle, as it would be a round trip for each job not just checking ownership once.

**Comment by trel** [comment]
Agreed, but still less traffic than... Option 3?

**Comment by trel** [comment]
With a bit more whiteboarding and brainstorming....

Problem:  With a single source of truth in the database holding the hostname of the delay server,
there is a window of time where server B comes up, and potentially grabs the same jobs as
an 'outgoing' server A.

We need a method for handing off the responsibility more cleanly, to avoid the overlap.

There are two universes of solutions...
1) Multiple Delay Server Coordination
2) Leader/Successor handoff of 'single' delay server

We're leaning heavily towards 2) below... Leader/Successor

--------

1) Multiple Delay Server Coordination

 - database holds list of hostnames of delay servers
 - all irods servers ask periodically if they are a delay server
   - if no
     - gracefully complete any active jobs if necessary
     - stop delay server if necessary
   - if yes
     - start the delay server if necessary
     - grab N unclaimed rules whose time has come (N to be defined/determined per zone/server/algorithm?)
       - annotate in the database that those rules have been claimed by me
     - process the rules

 - PROS:
    - single source of truth, multiple/scalable servers
    - makes implicit remote() unnecessary #4429  

 - CONS:
     - this is poor man's CELERY
        -  job schedulers are hard
        -  surely some dark corners we don't want to implement/learn/debug
 
 - PROBLEM:
    - lots of database traffic
    - how to handle a rule that was grabbed, but never completes (timing out)
    - how do you know if it is hung, or just a long-running job (aka really big checksum)?
    - did server A just go away?
      - perhaps a monitor would inform the database that the delay server is 'gone'
      - any 'owned by A' jobs are marked as available/ready again


--------



2) Leader/Successor handoff of 'single' delay server

 - catalog holds two hostnames, leader and successor
   - iadmin set_delay_server hostname -> updates successor only
 - all irods servers ask periodically for leader and successor (via #4977 async facility)
   - if self is leader
     - if successor is defined
        - if necessary, gracefully complete current jobs and exit
     - else
        - if necessary, start delay server
        - grab and process delay rules, same as today
   - else if self is successor
     - run health check on the leader stats (utility function that calculates based on db stats)
     - if leader is dead
         - promote self to leader in db
         - exit
     - else
         - check on the leader directly (ping?  grid-status?)
         - populate stats in the db (JSON?)
         - exit
   - else
     - self is not leader or successor
     - if necessary, gracefully complete current jobs and exit

        
  PROS:
   - single source of truth in catalog
   - still uses implicit remote()
   - easier to model than concurrent/parallel/celery
   - double-executes are no worse than today if the delay server dies halfway through a job
     - really busy leader looks like a dead leader
     - if delay server dies while a remote executor is working... that job does not get removed from the catalog
   
  CONS:
   - ALL servers periodically checking on whether they are leader/successor
      - but just equivalent of a genquery every check, not too much extra load
   - unknown complexities?

**Comment by kript** [comment]
Would the [raft consensus protocol ](https://raft.github.io/) be of use here, rather than ‘rolling your own’ as it were?

**Comment by trel** [comment]
But... we're not?    We have a central point of control, the database, where the truth lives.   This is not a distributed decision making situation...

**Comment by kript** [comment]
It both is and isn’t I would say. 

It’s true there is a single source of truth, so in CAP theorem it’s highly consistent, but not highly available, which is fine if that’s an explicit design goal, but it’s not clear from the discussion points that is is?

For example, raft could be used for (1). Also, switching delay servers in (2) is a manual operation requiring automation for HA operation ( eg custom commands for pacemaker et al), whereas each provider could become the delay server, in an automatic situation, although there are edge cases I suppose around not wanting all providers to be able to do this ( perhaps due to firewall, location or similar restrictions).

**Comment by trel** [comment]
I see what you're saying - we're definitely way over in 'C' land, yes.   But that said... we're not designing a distributed data store... and definitely don't need availability of the delay_server.

I think this is the set of design goals...
- we're not a fully distributed system, and don't want to become one(?)
- clear point of control / truth
- easy to reason about (and therefore... fix) if/when it goes sideways
- the delay server *itself* is not required to be immediately/always available/active

With the leader/successor protocol above, we would be prioritizing:
- the single source of truth (probably in the `r_grid_configuration` table)
- the single point of control (`iadmin set_delay_server <hostname>`)
- no special hats to wear, all servers running the same code (already true)
- arriving in a steady state relatively quickly
    - the "quickly" knob here would be the "utility function" which determines when the successor declares the leader dead and then promotes itself to leader (for example, it could be 3 consecutive failed pings over 5 minutes, or anything else that is deemed a good signal of the server being 'gone').

For your scenario of detecting *when* to run `iadmin set_delay_server <hostname>`... I think that's out of scope of this protocol itself.   We are looking to add some basic monitoring to the iRODS grid (so the ZMT can draw some green circles or something), but we should have a design session around those goals as well - we don't want to start logging too much timeseries data and/or providing graphs or other things that existing monitoring/dashboarding tools do very well.

**Comment by trel** [comment]
- entertain the periodic time to be set to `0` - aka don't ever check to see if I'm the leader or successor.
