### ISSUE TITLE
Delegate more CMake work to irods-dev package

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#5250]
- [ ] master
- [ ] 4-2-stable
----
There's a lot of [common functionality](https://github.com/irods/irods_capability_publishing/pull/18#issuecomment-726911773) that could be moved to the cmake files provided by `irods-dev`

Additionally, we could benefit from changing our import targets to include the proper [include directories](https://github.com/irods/irods_rule_engine_plugin_update_collection_mtime/issues/21) and such.

**Comment by trel** [comment]
definitely.    consolidate all the things.

**Comment by SwooshyCueb** [comment]
The vast majority of the remaining work for this is likely not going to make it into 4-2-stable, so I'm closing it in favor of #5669, #5712, and #5717
