### ISSUE TITLE
ichksum -aK on mismatched replicas

### ISSUE THREAD

**Issue by bh9** [irods/irods#5251]
### iRODS Version, OS and Version
4.2.7, Ubuntu 18.04 (with 16.04 packages)

### What did you try to do?
We're attempting to fix a number of unchecksummed files and identify if any have corrupted since they were uploaded. Reading the ichksum man page, I saw 
```
       -a     checksum  all  replicas.  ils  -L should be used to list the values of all replicas If used together
              with -K, and the replicas have different checksums, an error message is displayed, but  no  checksum
              is updated in the catalog.

       -K     verify  the  checksum value in iCAT. If the checksum value does not exist, compute and register one.
              If the catalog checksum exists and the file checksum differs, returns USER_CHKSUM_MISMATCH and  does
              not update in the catalog.
```
I produced a test for this, by creating a replicated object without checksums, then modified one of the replicas on disk to simulate a corruption:
```
bh9@deskpro110321:~$ ils -L ichksumtests/ichksum-case-10
  irods-ires        0 root;replicate;green;green3;irods-seq-sr02-ddn-rd10-21-22-23         1523 2020-11-17.11:59 & ichksum-case-10
        generic    /irods-seq-sr02-ddn-rd10-21-22-23/home/irods-ires/ichksumtests/ichksum-case-10
  irods-ires        1 root;replicate;red;red2;irods_r2_dev_sdb         1523 2020-11-17.11:59 & ichksum-case-10
        generic    /irods_r2_dev_sdb/home/irods-ires/ichksumtests/ichksum-case-10
```
Where `/irods_r2_dev_sdb/home/irods-ires/ichksumtests/ichksum-case-10` has a single character change:
```
irods-r2-dev@irods-r2-dev:~$ head -n1 /irods_r2_dev_sdb/home/irods-ires/ichksumtests/ichksum-case-10
localhoot provider-build
```
```
irods-g2-dev@irods-g2-dev:~$ head -n1 /irods-seq-sr02-ddn-rd10-21-22-23/home/irods-ires/ichksumtests/ichksum-case-10
localhost provider-build
```

### Expected behavior
The man page entry for `-a` says that using `-aK` should report if the checksums differ, and not update their checksums in the catalog, so I would expect an error message, and a non-zero return code

### Observed behavior (including steps to reproduce, if applicable)
`ichksum` returns 0, and updates the checksums in the catalog, producing a pair of replicas with mismatched checksums:
```
bh9@deskpro110321:~$ ichksum -aKMv --verify ichksumtests/ichksum-case-10
    ichksum-case-10    9e0d157af0519e85e2978b2a1d84ef9f
   ichksum-case-10            1.170 sec
Total checksum performed = 1, Failed checksum = 0
bh9@deskpro110321:~$ echo $?
0
bh9@deskpro110321:~$ ils -L ichksumtests/ichksum-case-10
  irods-ires        0 root;replicate;green;green3;irods-seq-sr02-ddn-rd10-21-22-23         1523 2020-11-17.11:59 & ichksum-case-10
    9e0d157af0519e85e2978b2a1d84ef9f    generic    /irods-seq-sr02-ddn-rd10-21-22-23/home/irods-ires/ichksumtests/ichksum-case-10
  irods-ires        1 root;replicate;red;red2;irods_r2_dev_sdb         1523 2020-11-17.11:59 & ichksum-case-10
    f7e942df3b637d4b7c5d69943c15906f    generic    /irods_r2_dev_sdb/home/irods-ires/ichksumtests/ichksum-case-10
```

**Comment by korydraughn** [comment]
The behavior of these options feel wrong. IMO, if verification flags are present (e.g. `-K` and/or `--verify`), then no replicas should be updated. The state of the replica should be checked and nothing else.

Thoughts?

**Comment by korydraughn** [comment]
Currently, the implementation will compute and register checksums before looking at verification flags. Instead, the flags need to be considered before computing any checksums. These changes would likely change the behavior of `ichksum`, but make more sense in that users would have clear control over when checksums are computed vs checked/verified.

**Comment by trel** [comment]
Agreed.

Proposed reworking of the options...

1. Deprecate/elide/remove `--verify` and make `-K` check both size and re-calculated checksum from vault. Should only save newly calculated checksum from vault to catalog if one was not already present for that replica (just like without the `-K` option).
2. Overwriting checksums in the catalog should only happen with `-f`
3. Using both `-n` and `-R` should return `-402000 USER_INCOMPATIBLE_PARAMS`
