### ISSUE TITLE
ichksum --verify doesn't verify size of unchecksummed replicas

### ISSUE THREAD

**Issue by bh9** [irods/irods#5252]
### iRODS Version, OS and Version
4.2.7, Ubuntu 18.04 (using 16.04 packages)

### What did you try to do?
While trying to establish if we could use ichksum to safely checksum all our unchecksummed files, I wanted to check if it would pick up unchecksummed files with the wrong size and a different checksum to the other replica (see #5251), so I created a replicated unchecksummed object, checksummed one replica, and truncated the other replica:
```
bh9@deskpro110321:~$ ils -L ichksumtests/ichksum-case-8
  irods-ires        0 root;replicate;green;green8;irods-seq-sr02-ddn-rd10-9-10-11         1523 2020-11-17.11:58 & ichksum-case-8
    9e0d157af0519e85e2978b2a1d84ef9f    generic    /irods-seq-sr02-ddn-rd10-9-10-11/home/irods-ires/ichksumtests/ichksum-case-8
  irods-ires        1 root;replicate;red;red2;irods_r2_dev_sdb         1523 2020-11-17.11:58 & ichksum-case-8
        generic    /irods_r2_dev_sdb/home/irods-ires/ichksumtests/ichksum-case-8
```
where `/irods_r2_dev_sdb/home/irods-ires/ichksumtests/ichksum-case-8` is not the right length:
```
irods-r2-dev@irods-r2-dev:~$ wc -c  /irods_r2_dev_sdb/home/irods-ires/ichksumtests/ichksum-case-8
605 /irods_r2_dev_sdb/home/irods-ires/ichksumtests/ichksum-case-8
```
```
irods-g2-dev@irods-g2-dev:~$ wc -c /irods-seq-sr02-ddn-rd10-9-10-11/home/irods-ires/ichksumtests/ichksum-case-8
1523 /irods-seq-sr02-ddn-rd10-9-10-11/home/irods-ires/ichksumtests/ichksum-case-8
```

### Expected behavior
`--verify` checks that the length is not the same, and the checksum is not added to the catalog, a USER_FILE_SIZE_MISMATCH error is returned, and ichksum returns -3

### Observed behavior (including steps to reproduce, if applicable)
While the replica has no checksum, `--verify` does not check the size, but once there is a checksum, `--verify` does return the USER_FILE_SIZE_MISMATCH and rc 3
```
bh9@deskpro110321:~$ ichksum -aKMv --verify ichksumtests/ichksum-case-8
    ichksum-case-8    9e0d157af0519e85e2978b2a1d84ef9f
   ichksum-case-8             1.123 sec
Total checksum performed = 1, Failed checksum = 0
bh9@deskpro110321:~$ echo $?
0
bh9@deskpro110321:~$ ils -L ichksumtests/ichksum-case-8
  irods-ires        0 root;replicate;green;green8;irods-seq-sr02-ddn-rd10-9-10-11         1523 2020-11-17.11:58 & ichksum-case-8
    9e0d157af0519e85e2978b2a1d84ef9f    generic    /irods-seq-sr02-ddn-rd10-9-10-11/home/irods-ires/ichksumtests/ichksum-case-8
  irods-ires        1 root;replicate;red;red2;irods_r2_dev_sdb         1523 2020-11-17.11:58 & ichksum-case-8
    0bd44920171a07041f0911d4dbc18247    generic    /irods_r2_dev_sdb/home/irods-ires/ichksumtests/ichksum-case-8
bh9@deskpro110321:~$ ichksum -aKMv --verify ichksumtests/ichksum-case-8
remote addresses: 172.30.157.14 ERROR: chksumDataObjUtil: rcDataObjChksum error for /seq-dev/home/irods-ires/ichksumtests/ichksum-case-8 status = -401000 USER_FILE_SIZE_MISMATCH
remote addresses: 172.30.157.14 ERROR: chksumUtil: chksum error for /seq-dev/home/irods-ires/ichksumtests/ichksum-case-8, status = -401000 status = -401000 USER_FILE_SIZE_MISMATCH
Total checksum performed = 1, Failed checksum = 1
bh9@deskpro110321:~$ echo $?
3
bh9@deskpro110321:~$ ils -L ichksumtests/ichksum-case-8
  irods-ires        0 root;replicate;green;green8;irods-seq-sr02-ddn-rd10-9-10-11         1523 2020-11-17.11:58 & ichksum-case-8
    9e0d157af0519e85e2978b2a1d84ef9f    generic    /irods-seq-sr02-ddn-rd10-9-10-11/home/irods-ires/ichksumtests/ichksum-case-8
  irods-ires        1 root;replicate;red;red2;irods_r2_dev_sdb         1523 2020-11-17.11:58 & ichksum-case-8
    0bd44920171a07041f0911d4dbc18247    generic    /irods_r2_dev_sdb/home/irods-ires/ichksumtests/ichksum-case-8
```

**Comment by korydraughn** [comment]
### Proposed Solution
Adjust the checksum implementation to match the following:
- When `-aK` is passed, the server reports a warning to the client for each replica that does not have a checksum.
- Make `--verify` not require `-K`.
- Make `--verify` always do the size comparison.

**Comment by trel** [comment]
I propose in... https://github.com/irods/irods/issues/5251#issuecomment-735818619:

- deprecate/elide/remove `--verify` option (`-K` should be doing this work already)

In the case of 'no replica in the catalog`, `ichksum` should(?) still populate the checksum field with a newly-calculated value?   Just like without the `-K` option?   Rather than give a warning/error?   I think I feel strongly both ways.

**Comment by jasoncoposky** [comment]
Yes, a checksum should be computed and registered according to the help text:

```
 -K  verify the checksum value in iCAT. If the checksum value does not exist,
     compute and register one. If the catalog checksum exists and the file checksum
     differs, returns USER_CHKSUM_MISMATCH and does not update in the catalog.
```

The suggestion was that a warning be issued for the given replica that a checksum cannot be verified as that replica did not previously have a checksum registered.
