### ISSUE TITLE
Mark queued delay rules as in-flight

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#5258]
- [ ] master
- [ ] 4-2-stable
---
## Feature
In order to implement #5249, we have to enable a way for delay servers to communicate ownership of queued rules to other delay servers. The plan is to use a column in `r_rule_exec` as a lock. The column would contain the hostname of the delay server that has queued up the rule. This ties the rule to the delay server and informs other delay servers that they should not attempt to queue up and process that rule.

### Q. What happens if rules have been locked, but the owning delay server crashes?
On restart of a delay server, it is allowed to queue up locked rules if it owns them.

**Comment by trel** [comment]
It is future / admin work to clean up / 'unlock' any locked rules for the scenario where a delay server has crashed and it is not coming back and/or the delay server is moving.

**Comment by korydraughn** [comment]
The implementation of the leader-successor algorithm removes the need for this because the successor never stands up a delay server until the leader's has shut down completely.

See #5249 for details.

**Comment by trel** [comment]
see https://github.com/irods/irods/issues/5249#issuecomment-892832496
