### ISSUE TITLE
Overwriting replication with existing checksum results in USER_CHKSUM_MISMATCH

### ISSUE THREAD

**Issue by alanking** [irods/irods#5263]
- [x] master
- [x] 4-2-stable
---
### iRODS Version, OS and Version
master/4-2-stable

### What did you try to do?
Replicate from a replica with a checksum over an existing replica with a different checksum.

### Expected behavior
The replica is overwritten and the checksum is written appropriately.

### Observed behavior (including steps to reproduce, if applicable)
```
$ ils -L foo
/tempZone/home/rods:
  rods              3 bonnieresc          283 2020-11-20.17:11 & foo
    sha2:v1V1tZf14zkTm+u8pM4vRDKCDZ90aZMrH/r6l1OUdDM=    generic    /var/lib/irods/bonnievault/home/rods/foo
  rods              4 alanresc       185622 2020-11-20.17:11 X foo
    sha2:P91+meT34kk/GbsxD3l/7ClMhZcXcE2BSwxpnJ4KdmM=    generic    /var/lib/irods/alanvault/home/rods/foo
$ irepl -R alanresc foo
remote addresses: 172.17.0.3 ERROR: replUtil: repl error for /tempZone/home/rods/foo, status = -314000 status = -314000 USER_CHKSUM_MISMATCH
$ ils -L foo
/tempZone/home/rods:
  rods              3 bonnieresc          283 2020-11-20.17:11 & foo
    sha2:v1V1tZf14zkTm+u8pM4vRDKCDZ90aZMrH/r6l1OUdDM=    generic    /var/lib/irods/bonnievault/home/rods/foo
  rods              4 alanresc       185622 2020-11-20.17:11 X foo
    sha2:P91+meT34kk/GbsxD3l/7ClMhZcXcE2BSwxpnJ4KdmM=    generic    /var/lib/irods/alanvault/home/rods/foo
```

The issue appeared in the commit which introduced intermediate replicas (master: 008ae8caad934b5920d6e7497a3b4dfee74deb99 ). This is a blocker for 4.2.9 and must be resolved as soon as possible.

**Comment by trel** [comment]
Clearly this should be allowed and should work as you describe.

The slightly different scenario when both source and destination replica are marked 'good' AND have different checksums should be considered as well.  It's not clear to me what the expected correct behavior would be in that case (since... the catalog is clearly incorrect to begin with).

**Comment by alanking** [comment]
I don't think that scenario possible through any existing APIs (could be wrong about that). Even if the scenario were to come up, I think either the server should do nothing, or both get marked stale as they are no longer known to be good as the truth has been lost. Thoughts?

**Comment by trel** [comment]
for that scenario...

1) server should definitely throw an error into the log and back to any client.

2) additionally marking them both stale could leave 'no' good replicas of that data object in the system, which would be a separate surprise for a user, but definitely not 'incorrect', as you say.   are there any other codepaths that will leave no good replicas?

**Comment by alanking** [comment]
Update: I have discovered that the source replica must be smaller in size than the destination replica in order to trip this:

```
$ ils -L
/tempZone/home/rods:
  rods              0 bonnieresc          283 2020-11-20.22:31 & foo
    sha2:v1V1tZf14zkTm+u8pM4vRDKCDZ90aZMrH/r6l1OUdDM=    generic    /var/lib/irods/bonnievault/home/rods/foo
  rods              1 alanresc          283 2020-11-20.22:31 & foo
    sha2:v1V1tZf14zkTm+u8pM4vRDKCDZ90aZMrH/r6l1OUdDM=    generic    /var/lib/irods/alanvault/home/rods/foo
$ iput -KfR bonnieresc VERSION.json foo                                
$ ils -L
/tempZone/home/rods:
  rods              0 bonnieresc       215853 2020-11-20.22:31 & foo                       
    sha2:9OuoGovNg7XDn1TtrUBPJlo1B5DPH/tl6cR2OSglsSk=    generic    /var/lib/irods/bonnievault/home/rods/foo
  rods              1 alanresc          283 2020-11-20.22:31 X foo                         
    sha2:v1V1tZf14zkTm+u8pM4vRDKCDZ90aZMrH/r6l1OUdDM=    generic    /var/lib/irods/alanvault/home/rods/foo
$ irepl -R alanresc foo
$ ils -L
/tempZone/home/rods:
  rods              0 bonnieresc       215853 2020-11-20.22:31 & foo                       
    sha2:9OuoGovNg7XDn1TtrUBPJlo1B5DPH/tl6cR2OSglsSk=    generic    /var/lib/irods/bonnievault/home/rods/foo
  rods              1 alanresc       215853 2020-11-20.22:31 & foo                         
    sha2:9OuoGovNg7XDn1TtrUBPJlo1B5DPH/tl6cR2OSglsSk=    generic    /var/lib/irods/alanvault/home/rods/foo
```

**Comment by trel** [comment]
subtle.   edge case on an edge case.

**Comment by kript** [comment]
> I don't think that scenario possible through any existing APIs (could be wrong about that). Even if the scenario were to come up, I think either the server should do nothing, or both get marked stale as they are no longer known to be good as the truth has been lost. Thoughts?

I regret to report that we have seen this, but we are not sure how we got into that situation in production.
If I remember correctly its posibly to synthetically create it by the judicous (malicous?) use of `ireg`'s file that have different checksums/sizes.

**Comment by alanking** [comment]
Well, thanks a lot @kript ;) Uncovered a new issue with `irepl`: https://github.com/irods/irods/issues/5265

If you can reproduce the marked-good scenario, we can file a separate issue for that. I wasn't able to do it locally, but if you can provide more detailed instructions, we can look into it.

**Comment by kript** [comment]
Glad I could help (I think! 😇 ).

It was a while back (early 4.1.x? 4.1.9?), but I think the reproducer was something like;

1. upload a file, have it replicate and generate checksums as expected.
2. manually make a copy of the file on another resource filesystem, changed in some way.
3. `ireg` the file as a replica of the original object
4. see replicas that have the same object but different checksums

**Comment by alanking** [comment]
Are we considering the cases mentioned above for this issue (i.e. two marked-good-yet-different replicas)? It seems like a separate issue to me, but I am willing to leave this open

**Comment by trel** [comment]
separate issue.

**Comment by alanking** [comment]
Great, thanks
