### ISSUE TITLE
ireg --repl overwrites catalog system metadata for existing replicas

### ISSUE THREAD

**Issue by alanking** [irods/irods#5265]
- [x] 4-2-stable
- [x] master
---
### iRODS Version, OS and Version
4.2.8

### What did you try to do?
Register a file of different size/contents as a replica of an existing data object

### Expected behavior
The new replica is created with the correct system metadata and the existing replicas are marked as stale

### Observed behavior (including steps to reproduce, if applicable)
The new replica is created with the correct system metadata and the existing replicas are marked as stale, but the size and checksum of the other replica are also (incorrectly) updated:
```
$ iput -K putme foo
irods@0d12777695a2:~$ ils -L foo
  rods              0 demoResc            5 2020-11-23.14:28 & foo
    sha2:rBafn7fLSNQxRm17O/LcPh0uetZjD2t2ehrBgBxJazU=    generic    /var/lib/irods/Vault/home/rods/foo
$ ireg --repl /var/lib/irods/regme /tempZone/home/rods/foo
$ ils -L foo
  rods              0 demoResc           10 2020-11-23.14:28   foo
    sha2:McLJaz700UZ/WaQ4dGrd7Dy7iUa2hpKluDLEdFSpULw=    generic    /var/lib/irods/Vault/home/rods/foo
  rods              1 demoResc           10 2020-11-23.14:28 & foo
    sha2:McLJaz700UZ/WaQ4dGrd7Dy7iUa2hpKluDLEdFSpULw=    generic    /var/lib/irods/regme
$ ls -l /var/lib/irods/Vault/home/rods/foo
-rw------- 1 irods irods 5 Nov 23 14:28 /var/lib/irods/Vault/home/rods/foo
```

Thanks, @kript, for finding this

**Comment by trel** [comment]
claiming to have worked in 4.2.7

so we need a test and a fix.

**Comment by alanking** [comment]
After some discussion, we have determined that the real bug here is the fact that multiple replicas can be registered in the same resource for a given data object (in the example above, `demoResc` has 2 replicas).

In light of this, the expected behavior is that `ireg --repl` to a resource with an existing replica should emit an error like `SYS_COPY_ALREADY_IN_RESC`.

This is also broken in 4.1.12, but in a different way:
```bash
$ ils -L foo
  rods              0 demoResc          476 2021-08-17.18:41 & foo
        generic    /var/lib/irods/iRODS/Vault/home/rods/foo
$ echo "muchsmaller" > smaller # smaller is of size 12
$ ireg --repl /var/lib/irods/smaller /tempZone/home/rods/foo
$ ils -L foo
  rods              0 demoResc          476 2021-08-17.18:41 & foo
        generic    /var/lib/irods/iRODS/Vault/home/rods/foo
  rods              1 demoResc          476 2021-08-17.18:47 & foo
        generic    /var/lib/irods/smaller
```
