### ISSUE TITLE
setup_irods.py should use systemctl to start irods

### ISSUE THREAD

**Issue by mcv21** [irods/irods#5275]
- [x] master
- [x] 4-2-stable
-------

## Bug Report

iRODS 4.2.7, Ubuntu 18.04

### What did you try to do?

We use systemd to manage our irods systems; after an initial install, we want to be able to e.g. `systemctl restart irods`. The problem is that setup_irods.py starts the server on an initial install by calling irodsctl directly, so systemd does not know about the running irods-server.

That means that when you `systemctl restart irods` systemd doesn't know there's an existing server it should stop before trying to start a new one, so it tries to start a new one which fails because there is already a server running.

### Expected behavior

Instead, setup_irods.py should `systemctl start irods` on systemd systems.

### Observed behavior (including steps to reproduce, if applicable)

```
root@irods-cgp-ig01:~# systemctl restart irods
Job for irods.service failed because the control process exited with error code.
See "systemctl status irods.service" and "journalctl -xe" for details.
```

**Comment by trel** [comment]
We designed the `./irodsctl` method to be ready for HPC / non-package-install configurations.

Is there a good way/indicator for iRODS to know that it is part of a systemd configuration (aka, a packaged installation on a systemd OS)?

Can you run `systemctl stop irods`, then `start`?  Rather than `restart` directly?   Does that behave cleanly enough?

**Comment by mcv21** [comment]
systemctl stop doesn't work, no:
```
irods@irods-seq-sb12:~$ /var/lib/irods/irodsctl start
Validating [/usr/local/iRODS/.irods/irods_environment.json]... Success
Validating [/var/lib/irods/VERSION.json]... Success
Validating [/etc/irods/server_config.json]... Success
Validating [/etc/irods/host_access_control_config.json]... Success
Validating [/etc/irods/hosts_config.json]... Success
Starting iRODS server...
Success
irods@irods-seq-sb12:~$ logout
root@irods-seq-sb12:~# systemctl stop irods
root@irods-seq-sb12:~# ps wuax | grep irods
irods    32145  0.7  0.0 718612 52888 ?        Ssl  15:08   0:00 /usr/sbin/irodServer
irods    32146  0.0  0.0  88736 11132 ?        S    15:08   0:00 /usr/sbin/irodServer
```
[so starting at this point fails because there's still a running server]

To answer your other question, the canonical answer is to check for the existence of the directory `/run/systemd/system` - cf http://manpages.ubuntu.com/manpages/xenial/en/man3/sd_booted.3.html]

**Comment by trel** [comment]
Two questions...

1) Does `systemctl stop irods` not, itself, use `/var/lib/irods/irodsctl stop` to stop any/all running irods processes?  Why are those processes still alive?  What *did* `systemctl stop irods` do?

2) But knowing `/run/systemd/system` exists on the current OS just tells us that the OS runs systemd, not that iRODS *should* be configured to leverage it?   The counter-scenario, I think... is a non-package-install on a systemd OS... where a single user is running iRODS in their namespace and has no permission to do administrator things...

**Comment by mcv21** [comment]
1. yes, it does, but only if it thinks there is a running process to kill; so if the irods server is started other than by systemd, it will do nothing. This is a consequence of systemd's approach to managing daemons where it keeps track of the spawned process(es).

2. Presumably you could check for being not-root and/or allow a command-line argument to setup_irods.py?

**Comment by trel** [comment]
Alternately... perhaps `setup_irods.py` should not result in a running iRODS server?   Would that also solve this use case?

**Comment by mcv21** [comment]
Yes, though I think some of the tests that `setup_irods.py` runs need a running server? So it could start the server, run the tests, and then stop the server again.

**Comment by trel** [comment]
Very good - we'll start down that road and see if we find any surprises.    This has been very helpful.
