### ISSUE TITLE
inconsistent naming in ACL's

### ISSUE THREAD

**Issue by kript** [irods/irods#5276]
### iRODS Version, OS and Version

4.2.8
Ubuntu 18.04

### What did you try to do?

replica a permission set for testing, which includes the 'modify' ACL for a user account

### Expected behavior

ils a collection, see ACL list something like ` user#zone:modify`
replicate permission on another collection with 
`ichmod modify <user> <object>`

### Observed behavior (including steps to reproduce, if applicable)

```
remote addresses: 172.30.157.13 ERROR: rcModAccessControl failure  status = -816000 CAT_INVALID_ARGUMENT
remote addresses: 172.30.157.13 ERROR: Level 0: access level 'modify' is invalid
```

ichmod man page says that the ownership rights are 'null', 'read', 'write' and 'own'

`ichmod write <user> <object>` gives modify rights

Can we have the man pages and documentation use consistent language please?

**Comment by trel** [comment]
Agreed on the inconsistency - this is due to currently exposing only a simplified subset of the entire original iRODS permissions model (https://github.com/irods/irods/issues/844).

After granting `write`, you will see `user#zone:modify object` - note the 'object' at the end.

**Comment by trel** [comment]
this will be resolved (in part, or completely) by https://github.com/irods/irods/pull/6134
