### ISSUE TITLE
"iput -rbK <collection>" does not honor -K flag

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#5288]
- [x] master
- [x] 4-2-stable
---
### iRODS Version, OS and Version
Likely all versions

### What did you try to do?
Recursively put a directory of files in iRODS and compute checksums (i.e. `iput -rbK <collection>`).

### Expected behavior
I expected the checksums to be computed and stored in the catalog.

### Observed behavior (including steps to reproduce, if applicable)
The files were uploaded, but did not have any checksum information.
```bash
Running recursive pre-scan... pre-scan complete... transferring data...
/tempZone/home/kory/test_col.d:
  kory              0 demoResc            6 2020-12-07.12:47 & bar
        generic    /var/lib/irods/Vault/home/kory/test_col.d/bar
  kory              0 demoResc            6 2020-12-07.12:47 & foo
        generic    /var/lib/irods/Vault/home/kory/test_col.d/foo
```

This behavior can be reproduced using the following script.
```bash
#! /bin/bash

set -x

the_dir=test_col.d

irm -rf $the_dir
rm -rf $the_dir
mkdir $the_dir

echo 'hello' > $the_dir/foo
echo 'world' > $the_dir/bar

iput -rbK $the_dir .

ils -L $the_dir
```

**Comment by trel** [comment]
duplicate of #3282
