### ISSUE TITLE
istream should honor client-side irods_default_resource

### ISSUE THREAD

**Issue by trel** [irods/irods#5294]
- [x] master
- [x] 4-2-stable
-----

### iRODS Version, OS and Version

4-2-stable

### What did you try to do?

istream into a data object on a client-defined default resource

### Expected behavior

the new data object appears on the client-defined default resource

### Observed behavior (including steps to reproduce, if applicable)

data object appears on the server-defined default resource (demoResc)

```
$ ilsresc
demoResc:unixfilesystem
pt:passthru
└── replresc:replication
    ├── ufs1:unixfilesystem
    └── ufs2:unixfilesystem
$ grep default ~/.irods/irods_environment.json
"irods_default_resource": "pt",
$ echo "perhaps" | istream write newfile
$ ils -l newfile
  rods              0 demoResc            8 2020-12-09.20:38 & newfile
```

**Comment by korydraughn** [comment]
is it safe to assume that the default resource must always be a root resource name?

**Comment by korydraughn** [comment]
does this apply to reads and writes or just to writes?

**Comment by trel** [comment]
> is it safe to assume that the default resource must always be a root resource name?

correct - no direct child access.

> does this apply to reads and writes or just to writes?

just writes.   reads are determined by the voting mechanism entirely.

**Comment by trel** [comment]
checkboxes checked.
