### ISSUE TITLE
HPC application access to iRODS data w/o PAM password

### ISSUE THREAD

**Issue by BlakeGFitch** [irods/irods#5307]
People like to access iRODS data via SSSD/PAM credentials in, for example, metalnx. What is the best way to allow access to iRODS data in scripted batch jobs? Is there a sense of providing an application key for access?

What is best practice for avoiding passwords in files when accessing iRODS data from cluster applications?

**Comment by trel** [comment]
You can issue tickets (kind of like guest passes) for access to particular users on particular files for particular number of uses or amount of data for a period of time...

https://docs.irods.org/4.2.8/icommands/tickets/

**Comment by BlakeGFitch** [comment]
cool! Thank you!
