### ISSUE TITLE
New data object does not follow O_RDWR semantics

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#5315]
- [x] master
- [x] 4-2-stable
------

### iRODS Version, OS and Version
Ubuntu 18.04
iRODS build: 4-2-stable as of Dec. 19, 2020 (SHA = 426b449e1cf9f434d384d3eb4988b7866aba03fe )
                                                                       (SHA for **icommands** is dc4f1aa75023bc8a38be6a9033ee2d9601d80e61)
### What did you try to do?
Rely on a common POSIX behavior for a newly created data object descriptor, namely if the new  data object was opened using a mode  of ( O_RDWR | O_CREAT | O_TRUNC ), one should be able to write bytes to it and then seek back and read the same bytes out again.

### Expected behavior

Doing this in the Python iRODS Client: 
```python
 with session.data_objects.create('/tempZone/home/rods/newobj.dat').open('w+') as f:
    f.write('abcd')
    f.seek(-2,SEEK_CUR)
    buf =  f.read(2)
```
should place "cd" in string variable `buf`.  With release 4.2.8 of iRODS, this is what happens.

### Observed behavior

On 4-2-stable, no bytes can be  read and `buf` gets a value of `""` (empty)

Full PRC program to reproduce:
```python
#!/usr/bin/env python
import os
import atexit

from irods.session import iRODSSession

def get_session():
    try:
        env_file = os.environ['IRODS_ENVIRONMENT_FILE']
    except KeyError:
        env_file = os.path.expanduser('~/.irods/irods_environment.json')
    session = iRODSSession(irods_env_file=env_file)
    atexit.register (lambda *_: session.cleanup())
    return session

if __name__ == '__main__':
    import sys
    s = get_session()
    path = '/{0.zone}/home/{0.username}/abc'.format(s)
    
    if s.data_objects.exists(path):
      s.data_objects.unlink(path, force=True)

    with s.data_objects.create(path).open('w+') as o:
        o.write('abcd')
        new_pos = o.seek(-2,os.SEEK_CUR)
        print('seeking to {} prior to reading'.format(new_pos))
        buf = (o.read(1024))
        print(repr(buf)) ; print (len(buf))

```

**Comment by korydraughn** [comment]
This appears to have been resolved.

I ran this script using PRC v0.8.6 against iRODS v4.2.8 and **cd** and **2** were printed to the terminal.

**Comment by korydraughn** [comment]
This issue is not unique to the PRC. dstream and likely all clients also have this issue.
