### ISSUE TITLE
imeta command returns 0 exit code on invalid input

### ISSUE THREAD

**Issue by erwinvanwieringen** [irods/irods#5316]
- [x] master
- [x] 4-2-stable
-----------

some examples with irods client commands 4.2.8:

> wierinve@host>imeta ls ; echo $?
> 
> Error: No object type descriptor (-d/C/R/u) specified
> 
> 0
> wierinve@host>imeta non_existing_subcommand ; echo $?
> unrecognized subcommand 'non_existing_subcommand', try 'imeta help'
> 0
> wierinve@host>

Since these are errors, imeta should return a non-zero exit code.

**Comment by SwooshyCueb** [comment]
I'm in favor of pushing this to 4.2.10 or the 4.2 backlog if nobody else thinks they can get to it before the 4.2.9 deadline.

**Comment by trel** [comment]
Agreed - silly error, but out of time.

**Comment by trel** [comment]
checkboxed.
