### ISSUE TITLE
Does not build against libc++ 11.0 (-Wdeprecated-declarations)

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#5317]
- [x] master
- [x] 4-2-stable
----
In C++17, `template<> struct std::allocator<void>` and `std::allocator::allocate( size_t n, const void * hint )` were deprecated. libc++ started enforcing this deprecation in 11.0.

Unfortunately, the boost 1.67 headers are littered with references to these, resulting in build failures due to multiple instances of the following errors:
- `error: 'allocator<void>' is deprecated [-Werror,-Wdeprecated-declarations]`
- `error: 'allocate' is deprecated [-Werror,-Wdeprecated-declarations]`

**Comment by trel** [comment]
So... this goes away with a bump to our boost version?

We can/will do that on master for 4.3.0, I presume.

**Comment by SwooshyCueb** [comment]
I'm not sure. I've done a little more research. Let me give you some more background.

In  C++17, `template<> struct std::allocator<void>` was deprecated in favor of `template< class T >struct std::allocator`. In other words, it wasn't the *template initialization* `std::allocator<void>` that was deprecated, but the *explicit template specialization* of `std::allocator<void>`. In C++20, it's removed.  
In C++17, `pointer std::allocator::allocate( size_type n, const void * hint = 0 )` was *replaced* with `T* std::allocate( std::size_t n )` and `T* std::allocator::allocate( std::size_t n, const void * hint)`, the latter of which is deprecated. In effect, the second optional argument of the original function is deprecated. In C++20, the two-argument function is removed completely.

To my understanding, the `std::allocator<void>` template specialization deprecation *should not affect existing code*. To back that up, when, in 2018, MSVC started throwing warnings about `std::allocator<void>` in boost, the boost team decided that this was improper behavior on MSVC's part (see chriskohlhoff/asio#290), and [Microsoft agrees with them but, get this, *decided it wasn't worth fixing*](https://developercommunity.visualstudio.com/solutions/502232/view.html). Therefore, I have good reason to believe that Clang's warnings about `std::allocator<void>` are *also* improper behavior. The official guidance on dealing with this warning in MSVC, specifically, is to define `_SILENCE_CXX17_ALLOCATOR_VOID_DEPRECATION_WARNING`. But that doesn't do anything for us, as libc++ doesn't look for this define and doesn't seem to have anything equivalent.

*However*, the warnings about `T* std::allocator::allocate( std::size_t n, const void * hint)` are valid, and were [fixed](https://github.com/boostorg/format/commit/5884c3d8140cdcd2d1bef374fcc216244d5faaa5) in boost 1.75.


Either way, I do think it's a good idea to bump the versions of some of our packages.

I've already got a solution/workaround for the time being (and for stable) that I'm prettying up for a PR.

**Comment by trel** [comment]
Okay - so we'll plan to bump boost to the most recent agreeable version as we round the corner on 4.3.0.   We will not bump boost for 4.2.x unless something shipped is truly broken and needs the update.

**Comment by trel** [comment]
reversing auto-close...
