### ISSUE TITLE
Set FILE_PATH_KW in finalize_destination_data_object_for_put_or_copy

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods#5323]
- [x] master
- [x] 4-2-stable
-----

## Feature

Set the FILE_PATH_KW in finalize_destination_data_object_for_put_or_copy so that this gets updated if the file path is updated during processing.  This is needed for DECOUPLED naming in cacheless S3.

**Comment by trel** [comment]
i think we're good - please checkbox and close

**Comment by JustinKyleJames** [comment]
This has been tested in 4-2-stable and 4.3.  Closing.
