### ISSUE TITLE
ifsck should continue not terminate when hitting a permission error

### ISSUE THREAD

**Issue by kript** [irods/irods#5358]
- [x] master
- [x] 4-2-stable
---------

### iRODS Version, OS and Version

4.2.7
Ubuntu 18.04

### What did you try to do?

run `ifsck` on a directory that contains a subdirectory to which the user running `ifsck` has no access ( `lost+found` owned by root in this case)

### Expected behavior

`ifsck`  reports the permision denied and continues.

### Observed behavior (including steps to reproduce, if applicable)

```
terminating with uncaught exception of type boost::filesystem::filesystem_error: boost::filesystem::directory_iterator::construct: Permission denied: "/irods-cgp-sb02-sdf/lost+found"
```

Related to #5296

**Comment by trel** [comment]
is this a regression?    did it always stop?    or is just the uncaught exception itself, new?

**Comment by mcast** [comment]
On Thu, Jan 21, 2021 at 05:32:25AM -0800, Terrell Russell wrote:

> is this a regression?    did it always stop?    or is just the uncaught exception itself, new?

It seems to have been a latent bug, provoked by different permissions
on `/$VAULT/lost+found/` on recently added hardware.

The first record I have of this was only 2020-10-16 on host
`irods-cgp-sr15-dev` and I'm fairly sure that it was already v4.2.7 .

...so in short, I don't really know but I suspect it's an old bug and
a new feather to tickle it.


-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by kript** [comment]
> It seems to have been a latent bug, provoked by different permissions on `/$VAULT/lost+found/` on recently added hardware. 

Yes, thats the most likely difference; we changed how we built systems around this time, including deploying filesystems for resources. I went back and checked and all the systems built the new way have a root owned 'lost+found', so we'll change the group permissions as a workaround for now.

**Comment by mcv21** [comment]
...one could make a case it should leave lost+found at the top level alone anyway, since that's a bit of filesystem internals :)

**Comment by mcast** [comment]
On Fri, Jan 22, 2021 at 12:42:27AM -0800, Matthew Vernon wrote:

> ...one could make a case it should leave lost+found at the top level
> alone anyway, since that's a bit of filesystem internals :)

For exactly that, maybe `&& owned by root`, yes it would be a nice
touch.  (@kript's pointer to #5296 got eaten by formatting)

If it could be an ordinary iRODS collection, pathologically named
(whether for research or to cause trouble) then no, it shouldn't be
auto-ignored.


-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by trel** [comment]
checkboxed.
