### ISSUE TITLE
iphymv (et al?) should exit with more specific values

### ISSUE THREAD

**Issue by mcv21** [irods/irods#5360]
- [x] master server
- [x] master icommands
- [x] 4-2-stable server
- [x] 4-2-stable icommands
--------

## Feature

We would like to use some icommands in an automated fashion; doing so usefully involves knowing what the cause of a failure was. The easiest way to do this is to inspect the return value (i.e. what was passed to `exit();` mod 255).

Currently iphymv only uses a few non-zero values - `1` for usage error or environment error, `2` for no input or connection error, 7 for login error, and 3 for all other errors. It would be nice to use the space more systematically and to differentiate more failure modes (rather than us as users having to parse whatever appears on stderr).

Less abstractly, we're using `iphymv` to migrate data off old hardware onto new hardware, and there are (at least) 3 failures it would be nice to differentiate between since we want to handle them differently:

1. No space left on destination (stop this migration, move to next target)
2. Network failures of various sorts (try exponential back-off a few times then give up)
3. checksum error or file not found on filesystem (give up on this object, move on to the next)

Having to do this with ad-hoc parsing of stderr from iphymv is a pain, and doing it based on `$?` would be much nicer :)

**Comment by alanking** [comment]
I am finally swinging around to look at this.

What specific error code(s) correspond(s) with each item in your list? And what return code(s) would you expect upon receipt of said error code(s)?

I would guess at least some of the following may apply, though I imagine there are more...

1. `USER_FILE_TOO_LARGE` (maybe `UNIX_FILE_GET_FS_FREESPACE_ERR`?)
2. `SYS_GET_HOSTNAME_ERR`, `SYS_SVR_TO_SVR_CONNECT_FAILED`, `SYS_INVALID_SERVER_HOST`, etc.?
3. `USER_CHKSUM_MISMATCH`, `UNIX_FILE_OPEN_ERR` (with UNIX code of 2)

It's difficult for us to classify some iRODS error codes as some of them are so generic (e.g. "user errors", "system errors", etc.) that it's difficult to define a range of errors to catch. So, if you have some specific errors you are sniffing or encounter a lot, that could be helpful in developing this enhancement. There are some that are grouped nicely, however, for example:

https://github.com/irods/irods/blob/d6c0eb90d5425242ddcf4a95a08cd58d7904a6d2/lib/core/include/rodsErrorTable.h#L313-L341

On the subject of UNIX exit codes, after poking around a bit, there does not appear to be any kind of standard for UNIX exit codes save for an attempt by the Open BSD group, which states "A few programs exit with the following non-portable error codes. Do not use them." (https://man.openbsd.org/sysexits.3) So any ideas on what we should return for each case?

**Comment by alanking** [comment]
Reference script graciously provided by OP: https://github.com/wtsi-ssg/irods_migrate/blob/main/irods_backoff_move.sh

**Comment by alanking** [comment]
I have some tests written to hit the various exit codes. The tests have uncovered an issue in `iphymv` which will be addressed as part of this issue. I will also write tests for other operations (`irepl`, `iput`, `icp`, etc.) to ensure that everything behaves consistently in the face of failures. Hopefully this will contribute positively to the effort described in this issue to allow for retries.

**Comment by trel** [comment]
all checkboxed.
