### ISSUE TITLE
setup_irods.py: log level and days per log arguments not converted to string

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#5361]
- [ ] master
- [ ] 4-2-stable
----
Both `setup_irods.py` and `irods_control.py` accept arguments as defined in `irods/start_options.py`.

However, `irods_control.py` stringifies its log level and days per log arguments:
https://github.com/irods/irods/blob/ee116cbc7cf90f6b0960e596b0b7ebf97877393b/scripts/irods_control.py#L102-L107
and `setup_irods.py` does not:
https://github.com/irods/irods/blob/ee116cbc7cf90f6b0960e596b0b7ebf97877393b/scripts/setup_irods.py#L428-L433

This causes python to get angry when these arguments are passed to `setup_irods.py` because of non-string values in the subprocess environment dict.

**Comment by trel** [comment]
sorry, this one auto-closed as well.
