### ISSUE TITLE
scripts: output verbosity quirkiness

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#5363]
- [ ] master
- [ ] 4-2-stable
----
Both `setup_irods.py` and `irods_control.py` accept arguments as defined in `irods/start_options.py`.

`irods/start_options.py` defines a couple of arguments for controlling the amount of output from the script:
> https://github.com/irods/irods/blob/ee116cbc7cf90f6b0960e596b0b7ebf97877393b/scripts/irods/start_options.py#L2-L8

Both `setup_irods.py` and `irods_control.py` handle this by first (before the arguments have even been parsed) registering a tty log handler that accepts entries with a level of `logging.WARNING` or higher:
> https://github.com/irods/irods/blob/ee116cbc7cf90f6b0960e596b0b7ebf97877393b/scripts/setup_irods.py#L418
> https://github.com/irods/irods/blob/ee116cbc7cf90f6b0960e596b0b7ebf97877393b/scripts/irods_control.py#L62

After the arguments have been parsed, if the `verbose` option was set, another tty log handler is registered that accepts entries with a level of `logging.INFO` or higher, up to but not including `logging.WARNING`:
> https://github.com/irods/irods/blob/ee116cbc7cf90f6b0960e596b0b7ebf97877393b/scripts/setup_irods.py#L425-L426
> https://github.com/irods/irods/blob/ee116cbc7cf90f6b0960e596b0b7ebf97877393b/scripts/irods_control.py#L99-L100

There is no functionality for enabling entries with a level lower than `logging.INFO` to be output from these scripts. It would be very helpful to be able to be able to further increase the verbosity of these scripts beyond this point.

Additionally, the `--quiet` option is essentially useless, only serving to cancel out any `--verbose` arguments that precede it. It doesn't actually make the scripts any quieter.
Moreover, using the same variable (`verbose`) for both `--quiet` and `--verbose`, and using `store_false` and `store_true`, respectively, as their actions is a potential trip-hazard. The former sets the default value of `verbose` to True, and the latter sets the default value of `verbose` to False. Presently, the latter takes precedence because it is added last, but should the implementation of the `argparse` module change, this might not work any more.

It is also worth mentioning here that the third argument to `register_tty_handler` is named `maxlevel`, which is a bit of a misnomer, as the actual maximum level is *one less* than what is passed in:
> https://github.com/irods/irods/blob/ee116cbc7cf90f6b0960e596b0b7ebf97877393b/scripts/irods/log.py#L53-L54

**Comment by trel** [comment]
checkboxed and closing.
