### ISSUE TITLE
irodsctl status does not print any messages to the terminal

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#5383]
- [ ] master
- [x] 4-2-stable
----------

### iRODS Version, OS and Version
Tested against tip of master and 4-2-stable on Ubuntu 16

### What did you try to do?
Ran ./`irodsctl start` and `./irodsctl stop` under the iRODS service account.

### Expected behavior
Expected to see startup and shutdown messages.

### Observed behavior (including steps to reproduce, if applicable)
Nothing is printed to the terminal.

**Comment by korydraughn** [comment]
To see these messages, the verbose flag must be passed (e.g. `./irodsctl start -v`).

**Comment by trel** [comment]
@korydraughn @SwooshyCueb I feel `./irodsctl status` should still go to stdout?     If agree, let's reopen and rename this issue.

**Comment by trel** [comment]
Presumably this happened due to https://github.com/irods/irods/issues/5363
