### ISSUE TITLE
Add support for SHA1, SHA512, and ADLER32 in lib/hasher hash strategies.

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods#5392]
- [x] master
- [x] 4-2-stable
-----

## Feature

Add support for SHA1, SHA512, and ADLER32 in lib/hasher hash strategies for use in Globus client.

The changes for this enhancement will not add these for ichksum, iput -k, etc, but that support could easily be added in the future by using these new hashing strategy classes.

**Comment by trel** [comment]
reopening for an incoming tweak due to initialization order.
