### ISSUE TITLE
VERIFY_CHKSUM_KW failure leaves a current data object in a bad state

### ISSUE THREAD

**Issue by kjsanger** [irods/irods#5400]
- [x] master
- [x] 4-2-stable
----------

### iRODS Version, OS and Version

4.2.7, Linux, Ubuntu bionic

### What did you try to do?

`rcDataObjPut` a file whose MD5 is `6a57b28b63eede75341f2e06b428cf7a`
to a replication resource using `VERIFY_CHKSUM_KW` while intentionally passing
an incorrect checksum of `My hovercraft is full of eels`.

### Expected behavior

The put to fail with `USER_CHKSUM_MISMATCH` and the data object either not be created
or be created with a stale state.

### Observed behavior (including steps to reproduce, if applicable)

The put fails with `USER_CHKSUM_MISMATCH` and a data object is created with no
checksum and size 0 bytes. The data object is marked as current (`&` with `ils -L`).

Moreover, any client subsequently running `ichksum` on the data object will generate a 
checksum of `6a57b28b63eede75341f2e06b428cf7a` (MD5, or equivalent for other
schemes), rather than the checksum of a file of size 0 bytes.

This leaves a data object having "no contents" while paradoxically having a correct
checksum that doesn't match the retrievable data.

Data file:

[eels.txt](https://github.com/irods/irods/files/5944428/eels.txt)

C program:

````
#include <rodsClient.h>

/*
Tested on iRODS 4.2.7

This program puts a new data object using rcDataObjPut with the
VERIFY_CHKSUM_KW parameter set to an intentionally incorrect
checksum. This simulates a checksum verification failure.

On a replication resource, one replica is left in a current (&) state
having size 0 bytes and no checksum.

I would expect there to be either no data object at all, or for the
data object to be marked stale.

Moreover, any client subsequently running ichksum on the data object
will generate a checksum of 6a57b28b63eede75341f2e06b428cf7a (MD5, or
equivalent for other schemes), rather than the checksum of a file of
size 0 bytes.

This leaves a data object having "no contents" while paradoxically
having a correct checksum that doesn't match the retrievable data.
*/

int main(int argc, char *argv[]) {
    setenv(SP_OPTION, "verify-reproc", 1);

    char* local_file = "eels.txt";

    // Real checksum is "6a57b28b63eede75341f2e06b428cf7a";
    char *local_checksum = "My hovercraft is full of eels";
    char *remote_path = "/testZone/home/irods/eels.txt";

    int status;

    rodsEnv env;
    rErrMsg_t errmsg;
    rcComm_t *conn = NULL;

    status = getRodsEnv(&env);
    if (status != 0) {
        fprintf(stderr, "Failed to load iRODS environment\n");
        return 1;
    }

    conn = rcConnect(env.rodsHost, env.rodsPort, env.rodsUserName,
                     env.rodsZone, NO_RECONN, &errmsg);
    if (!conn) {
        fprintf(stderr, "Failed to connect\n");
        return 1;
    }

    fprintf(stderr, "Connected to %s:%d zone %s as %s\n",
            env.rodsHost, env.rodsPort, env.rodsZone,
            env.rodsUserName);

    init_client_api_table();
    status = clientLogin(conn, "", "");
    if (status != 0) {
        fprintf(stderr, "Failed to login\n");
        return 1;
    }

    dataObjInp_t obj_inp;
    memset(&obj_inp, 0, sizeof obj_inp);

    obj_inp.openFlags  = O_WRONLY;
    obj_inp.createMode = 0750;
    snprintf(obj_inp.objPath, MAX_NAME_LEN, "%s", remote_path);

    addKeyVal(&obj_inp.condInput, DEF_RESC_NAME_KW, env.rodsDefResource);
    addKeyVal(&obj_inp.condInput, VERIFY_CHKSUM_KW, local_checksum);
    status = rcDataObjPut(conn, &obj_inp, local_file);
    if (status != 0) {
        char *err_subname;
        const char *err_name = rodsErrorName(status, &err_subname);
        fprintf(stderr, "Failed to put data object: error %d %s\n",
                status, err_name);

        if (status == USER_CHKSUM_MISMATCH) {
            fprintf(stderr, "Got the expected failure\n");
            status = 0;
        } else {
            fprintf(stderr, "Did not reproduce the expected failure\n");
        }
    }

    rcDisconnect(conn);

    if (status == 0) {
        return status;
    }

    return 1;
}
````

Makefile:
````
CC = gcc 
CFLAGS = -g -std=c99 -Wall -Werror 
LIBS = -lirods_client -lirods_common -lstdc++ -lssl -lcrypto -lgssapi_krb5 -lpthread -ldl -lm -lrt -ljansson

PREFIX = /opt/irods
CPPFLAGS = -I$(PREFIX)/include -I$(PREFIX)/include/irods
LDFLAGS = -L$(PREFIX)/lib -L$(PREFIX)/lib/irods/externals

all: verify-repro

verify-repro: verify-repro.c
	$(CC) $($CFLAGS) $(CPPFLAGS) -o verify-repro verify-repro.c $(LDFLAGS) $(LIBS)

test: verify-repro
	./verify-repro

clean:
	rm verify-repro

.PHONY: all test clean
````

Example:

````
$ make -f Makefile.repro test PREFIX=/home/keith/.local/miniconda/envs/baton-dev
gcc   -I/home/keith/.local/miniconda/envs/baton-dev/include -I/home/keith/.local/miniconda/envs/baton-dev/include/irods -o verify-repro verify-repro.c -L/home/keith/.local/miniconda/envs/baton-dev/lib -L/home/keith/.local/miniconda/envs/baton-dev/lib/irods/externals -lirods_client -lirods_common -lstdc++ -lssl -lcrypto -lgssapi_krb5 -lpthread -ldl -lm -lrt -ljansson

./verify-repro
Connected to localhost:1247 zone testZone as irods
Failed to put data object: error -314000 USER_CHKSUM_MISMATCH
Got the expected failure

$ ils -L
/testZone/home/irods:
  irods             0 replResc;unixfs2            0 2021-02-08.14:58 & eels.txt
        generic    /var/lib/irods/iRODS/VaultRy/home/irods/eels.txt

$ ichksum eels.txt
    eels.txt    6a57b28b63eede75341f2e06b428cf7a
Total checksum performed = 1, Failed checksum = 0

$ ils -L
/testZone/home/irods:
  irods             0 replResc;unixfs2            0 2021-02-08.14:58 & eels.txt
    6a57b28b63eede75341f2e06b428cf7a    generic    /var/lib/irods/iRODS/VaultRy/home/irods/eels.txt
````

**Comment by kjsanger** [comment]
This may also be revealing a bug `ichksum` because it should respect the catalog when performing the checksum.

**Comment by kjsanger** [comment]
Further to this, if you happen to have done an `ichksum` so that the file now looks like this:

```
$ ils -L
/testZone/home/irods:
  irods             0 replResc;unixfs2            5 2021-02-08.15:34 & eels.txt
    6a57b28b63eede75341f2e06b428cf7a    generic    /var/lib/irods/iRODS/VaultRy/home/irods/eels.txt
```
and you follow up by overwriting with the file again using the same program (with an additional ` addKeyVal(&obj_inp.condInput, FORCE_FLAG_KW, "");` on the put operatiion i.e. still passing an incorrect checksum, then no `USER_CHKSUM_MISMATCH` is raised. This is not what I would expect - the checksum I'm passing from the client side does not match either the actual data or the 0 bytes file the catalog expects, so the upload should fail.

**Comment by trel** [comment]
I believe we've probably plugged this inconsistency with https://github.com/irods/irods/pull/5287 which represents a refactor of the checksum API itself.  That commit closed #5251 and #5252 (both in the 4.2.9 milestone).

To be sure, you/we should run your same test above against a tip-of-4-2-stable build.

**Comment by kjsanger** [comment]
Do you have a nightly build or similar packages that I can use for that?

**Comment by trel** [comment]
yes, email headed your way with a build.

**Comment by kjsanger** [comment]
(I didn't set up a replication resource in this case - I don't think this changed the behaviour.)

On the test build there is a difference in that the initial failed upload gives a stale object:

```
$ make PREFIX=/usr test
./verify-repro
Connected to localhost:1247 zone testZone as irods
Failed to put data object: error -314000 USER_CHKSUM_MISMATCH
Got the expected failure

ubuntu@kdj-irods-test:~$ ils -L
/testZone/home/irods:
  irods             0 demoResc            0 2021-02-09.15:50 X eels.txt
        generic    /var/lib/irods/Vault/home/irods/eels.txt
```

However, `ichksum` will still operate on it:

```
ubuntu@kdj-irods-test:~$ ichksum eels.txt 
    eels.txt    6a57b28b63eede75341f2e06b428cf7a
ubuntu@kdj-irods-test:~$ ils -L
/testZone/home/irods:
  irods             0 demoResc            0 2021-02-09.15:50 X eels.txt
    6a57b28b63eede75341f2e06b428cf7a    generic    /var/lib/irods/Vault/home/irods/eels.txt
```

So without clients defensively checking for staleness before they do anything, we can still
reach a bad state of an accessible object with a "correct" checksum that doesn't match the
retrievable data:

```
ubuntu@kdj-irods-test:~$ iget eels.txt - | md5sum
d41d8cd98f00b204e9800998ecf8427e  -
```

Also, after the `ichksum`,  the subsequent overwrite behaviour remains i.e. forced overwrites
with an incorrect client-side checksum are successful (no error). These also now change the
state of the object from stale to current.

```
$ ils -L
/testZone/home/irods:
  irods             0 demoResc            5 2021-02-09.16:00 & eels.txt
    6a57b28b63eede75341f2e06b428cf7a    generic    /var/lib/irods/Vault/home/irods/eels.txt
```

**Comment by kript** [comment]
Should API client be passing a keyword  to check the equivalent of `-f` from `iput`/`iget` which IIRC is what's needed to access a stale replica.

I do realise I am unclear as to how iRODS behaves if there are _only_ stale replicas, my assumption was it should error, but that's not what we see here.

**Comment by trel** [comment]
> I do realise I am unclear as to how iRODS behaves if there are _only_ stale replicas, my assumption was it should error, but that's not what we see here.

iRODS replicas/resources 'vote' - and stale replicas vote `0.5` (good vote `1.0` by default).  So, in the case that only stale replicas exist, one will still win the vote and be eligible for a 'get'.

**Comment by kjsanger** [comment]
I found this comment in a github issue:

"Operations that target multiple replicas will only affect replicas that
are marked good. This means intermediate, locked, and stale replicas
will be ignored.

Operations that target a specific replica are allowed to operate on
stale replicas."

My interpretation of this that I would expect the single stale replica in this case to be effectively "invisible" to the client. As no specific replica is targeted, I expect it shouldn't be get-able, checksum-able or require a force to overwrite.

**Comment by trel** [comment]
I don't see anything wrong with the @kjsanger write-up.
 - The initial put left a stale replica in the system.
 - The checksum calculated against the file on disk and saved the result in the catalog.
 - The `iget` retrieved the highest voting replica (the only replica)
 - The subsequent `iput -f` worked as expected?  I think?

**Comment by kjsanger** [comment]
As you've said yourself, the catalog is canon and that file is empty.

**Comment by trel** [comment]
> My interpretation of this that I would expect the single stale replica in this case to be effectively "invisible" to the client. As no specific replica is targeted, I expect it shouldn't be get-able, checksum-able or require a force to overwrite.

Ah, but the concept of 'default resource' has kicked in and *is* specifying a particular replica.

**Comment by kjsanger** [comment]
Is there any documentation on this?

**Comment by trel** [comment]
Okay, so you're saying because the catalog has a zero as length... the `ichksum` should not calculate against the full content of the replica on disk?

**Comment by kjsanger** [comment]
That's what I would expect from previous conversations. E.g. I shouldn't be able to iget the data if it's 0 bytes in the catalog. Streaming the data from the file is currently possible when it has 0 bytes, but that has been flagged as a bug to be fixed.

**Comment by kjsanger** [comment]
> > My interpretation of this that I would expect the single stale replica in this case to be effectively "invisible" to the client. As no specific replica is targeted, I expect it shouldn't be get-able, checksum-able or require a force to overwrite.
> 
> Ah, but the concept of 'default resource' has kicked in and _is_ specifying a particular replica.

This behaviour also happens on a replication resource where the can be 2 replicates and I'm not adressing for one or the other. If there's just one stale replicate, is that still addressing a specific one?

**Comment by kjsanger** [comment]
If this a valid data object because it's stale on a default resource and the checksum is good, I should be able it `iget` it, shouldn't I?

```
$ ils -L
/testZone/home/irods:
  irods             0 demoResc            0 2021-02-09.18:04 X eels.txt
    6a57b28b63eede75341f2e06b428cf7a    generic    /var/lib/irods/Vault/home/irods/eels.txt
```

But I can't because the inconsistency of size and checksum means `iget -K` always fails:

```
$ iget -K eels.txt
remote addresses: 127.0.0.1 ERROR: rcDataObjGet: checksum mismatch error for foo, status = -314000 status = -314000 USER_CHKSUM_MISMATCH
remote addresses: 127.0.0.1 ERROR: getUtil: get error for foo status = -314000 USER_CHKSUM_MISMATCH
```

**Comment by trel** [comment]
>  If there's just one stale replicate, is that still addressing a specific one?

One is selected for 'get', so big picture, yes.   Which one is targeted is determined by which one won the vote - which takes into consideration staleness, locality of reference, any passthru weighting, and status of the resource itself (up/down).  If you have one good and one stale in a tree, the good one will win the vote and be targeted.

**Comment by trel** [comment]
> Which is paradoxical because ichksum has just told me that it's fine.

I believe this is because the `iget -K` option is confirming on the client side against the data it received... which in this case would be zero bytes.

I think making `ichksum` only calculate on the size of bytes in the catalog (like you mention above) will align the expectations with the code.

**Comment by kjsanger** [comment]
>     * The subsequent `iput -f` worked as expected?  I think?

Except that I was still passing an intentionally bad checksum and asking for verification, so that should always fail. It appears to ignore the request to verify when forcing.

**Comment by trel** [comment]
> It appears to ignore the request to verify when forcing.

This is quite possible.    Let's confirm/deny that and leave this issue to address this use case.

We'll open another issue for the "`ichksum` only should be calculating against the size of bytes in the catalog, not the whole file on disk" discussion.

**Comment by kjsanger** [comment]
> > Which is paradoxical because ichksum has just told me that it's fine.
> 
> I believe this is because the `iget -K` option is confirming on the client side against the data it received... which in this case would be zero bytes.
> 
> I think making `ichksum` only calculate on the size of bytes in the catalog (like you mention above) will align the expectations with the code.

Yes, that would resolve the paradox of the checksum being fine the client want to look at the data. Opening the box and the cat's always dead.

**Comment by trel** [comment]
poor cat.

**Comment by trel** [comment]
It is done - https://github.com/irods/irods/issues/5401

**Comment by trel** [comment]
The remaining work on this issue is:

> > * The subsequent `iput -f` worked as expected?  I think?

> Except that I was still passing an intentionally bad checksum and asking for verification, so that should always fail. It appears to ignore the request to verify when forcing.
