### ISSUE TITLE
"Rule Engine Plugin returned [0]" being logged as an error

### ISSUE THREAD

**Issue by trel** [irods/irods#5413]
- [x] master
- [x] 4-2-stable
----------

### iRODS Version, OS and Version

4.2.8

### What did you try to do?

call a rule in the server

### Expected behavior

success, return code of `0`, and quiet continuation

### Observed behavior (including steps to reproduce, if applicable)

rodsLog:
```
Feb 15 14:56:14 pid:24560 remote addresses: x.x.x.x, ::1 ERROR: Rule Engine Plugin returned [0].
```

Coming from this function:

https://github.com/irods/irods/blob/56525f3756daed4c342bd85ff6fd34c4b0bf6625/server/re/include/irods_re_plugin.hpp#L442-L450

Solution appears to be wrapping this logic to only print if the `e.code()` is negative.

**Comment by korydraughn** [comment]
Checking for non-negative codes will also allow us to correctly ignore the following:
```c++
NEW_STATE(RULE_ENGINE_SKIP_OPERATION,        5001000)
```
