### ISSUE TITLE
Undocumented new dynamic PEPs pep_api_replica_[open|close]_[pre|post|except|finally]

### ISSUE THREAD

**Issue by ilarik** [irods/irods#5418]
### iRODS Version, OS and Version

iRODS 4-2-stable, all operating systems.

### What did you try to do?

The latest behaviour, when building from 4-2-stable, and supposedly from 4.2.9 onwards, seems to be that when using the `istream` tool (or more generally the new iRODS `dstream` API?), the PEPs have changed from `pep_api_data_obj_[open|close]_[...]` to `pep_api_replica[open|close]_[...]`. 

### Expected behavior

Preferably both preserve compatibility against 4.2.8 and document the changes (and the best practice migration path), or at the very least the latter.

### Observed behavior (including steps to reproduce, if applicable)

When doing `istream read VERSION.json` this can be trapped with the following rules:

```
pep_api_replica_open_post(*INSTANCE_NAME, *COMM, *INPUT, *OUTPUT)
{
        writeLine("serverLog", "pep_api_replica_open_post: INPUT=*INPUT");
}

pep_api_replica_close_post(*INSTANCE_NAME, *COMM, *INPUT)
{
        writeLine("serverLog", "pep_api_replica_close_post: INPUT=*INPUT");
}
```
which outputs the following (and only the following) into the `serverLog`:

```
Feb 18 11:24:45 pid:22402 NOTICE: writeLine: inString = pep_api_replica_open_post: INPUT=create_mode=384++++data_size=0++++num_threads=0++++obj_path=/tempZone/home/rods/VERSION.json++++offset=0++++open_flags=0++++opr_type=0++++resc_hier=demoResc++++selected_hierarchy=demoResc
Feb 18 11:24:45 pid:22402 NOTICE: writeLine: inString = pep_api_replica_close_post: INPUT=[BytesBuf*] not supported
```
This of course implies that the fixes and workarounds for issue #5417 are a moot point for these PEPs since the parameters passed to the rules have differing data types. Perhaps also the workflow outlined in https://github.com/KTH-PDC/irods-microservices/blob/master/example-dynpeps.re also becomes invalid.

**Comment by trel** [comment]
Related to https://github.com/irods/irods_docs/issues/82

**Comment by trel** [comment]
Closing for 4.2.9 release.  These PEPs are now documented.

We are working on a larger writeup of how the streaming API triggers the POSIX semantics (open/read/write/close) rather than the object semantics (put/get) of iRODS.
