### ISSUE TITLE
iphymv from incorrect source resource gives incorrect SYS_LIBRARY_ERROR

### ISSUE THREAD

**Issue by trel** [irods/irods#5454]
- [ ] master
- [ ] 4-2-stable
------

### iRODS Version, OS and Version

4.2.8

### What did you try to do?

Accidentally `iphymv` from a correctly-spelled resource that did not have a source replica.

### Expected behavior

Probably, it should return `REPLICA_NOT_IN_RESC`

### Observed behavior (including steps to reproduce, if applicable)

```
$ ils -l foo
  rods              0 demoResc     12726358 2021-03-03.19:05 & foo

$ iphymv -S anotherResc -R demoResc foo
remote addresses: 127.0.1.1 ERROR: phymvUtil: phymv error for /tempZone/home/rods/foo, status = -167000 status = -167000 SYS_LIBRARY_ERROR
```
rodsLog:
```
Mar  3 19:05:30 pid:26994 remote addresses: 127.0.0.1, ::1 ERROR: [rsDataObjPhymv] - [unmatched '}' in format string]
```

**Comment by alanking** [comment]
This is fixed and covered by a test in 4-2-stable:
https://github.com/irods/irods/blob/f300d12f871d1688aa44e4df6acde4d7ae604faf/scripts/irods/test/test_iphymv.py#L430
