### ISSUE TITLE
optimization/atomicity when manipulating resource hierarchies

### ISSUE THREAD

**Issue by trel** [irods/irods#5481]
## Feature

When performing 'tree surgery', there is a small window of time when a connecting client will get and use an 'incorrect/incomplete' resource hierarchy from the database.

Use case
 - Changing the parent of a storage resource
 - Requires both an `iadmin modresc rmchildfromresc` AND an `iadmin modresc addchildtoresc`

Consider atomic resource management operations - within a single transaction - similar to atomic metadata operations.

Alternatively, something similar to the replica state table's 'publish_to_catalog'...

**Comment by korydraughn** [comment]
Given that we are working on an API that executes multiple unrelated database operations in a single transaction, we started discussing a new `iadmin` sub-command that resolves this issue.

`iadmin` would grow a new sub-command called `setparentresc` and it would set the parent of a resource atomically. We are still discussing the syntax for this command. Currently, we have the following proposals: 
- `iadmin setparentresc <child-resc> <parent-resc>`
    - This syntax is about the order of the parameters in regards to the sub-command. This syntax implies that staying consistent with `addchildtoresc` and `rmchildfromresc` is incorrect due to the name of the sub-command.
- `iadmin setparentresc -p <parent-resc> -c <child-resc>`
    - This syntax is based on information from https://clig.dev/#arguments-and-flags
- `iadmin setparentresc <parent-resc> <child-resc>`
    - This syntax is all about being consistent with `addchildtoresc` and `rmchildfromresc`

Thoughts? @kript @bh9

**Comment by korydraughn** [comment]
@kript @bh9 Do you have any preference on this?

**Comment by bh9** [comment]
Maybe a slight preference for the first?

**Comment by trel** [comment]
I still think the third is best.

I see these three commands (`addchildtoresc`, `rmchildfromresc`, `setparentresc`) as a family, and feel that consistency reduces chances that they are held incorrectly by the administrator.

**Comment by korydraughn** [comment]
Handled by #5934

**Comment by trel** [comment]
We chose not to implement `setparentresc` and instead... just allowed overwriting with `addchildtoresc`.
