### ISSUE TITLE
A force-put (e.g. iput -f) should erase the existing checksum

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#5496]
- [x] master
- [x] 4-2-stable
---
## Feature
Erasing the checksum is necessary so that the catalog stays consistent. Right now, a force-put overwrites the replica and recalculates the checksum if one exists.

**This is a change in behavior!**

**Comment by trel** [comment]
Note, this is `iput -f` without the `-k` or `-K` options.

Either of those options would calculate and store the new checksum in the catalog.

**Comment by korydraughn** [comment]
Should writing to an existing replica cause the checksum to be erased? For example, using `istream` to overwrite part of a replica.

IMO, yes because the checksum will be incorrect if the data actually changed.

**Comment by trel** [comment]
Yes, we don't want incorrect information in the catalog.

And we shouldn't assume the user wants to calculate a checksum on an arbitrarily large file.

**Comment by korydraughn** [comment]
This also affects bulk put.
