### ISSUE TITLE
Delayed Execution Frequency is improperly parsed

### ISSUE THREAD

**Issue by jasoncoposky** [irods/irods#5503]
- [x] master
- [x] 4-2-stable
---------

The use of the various options for the execution frequency is improperly parsed, leaving jobs permanently in the delayed execution queue.

Using an option such as `<EF>DOUBLE UNTIL SUCCESS OR 10 TIMES</EF>` fails due to this line [advancing the character pointer past the beginning of the string](https://github.com/irods/irods/blob/f20668202d5304ee7db22a8b1dd1322d7d34be6a/lib/core/src/rcMisc.cpp#L1699) which causes the [`strstr`](https://github.com/irods/irods/blob/f20668202d5304ee7db22a8b1dd1322d7d34be6a/lib/core/src/rcMisc.cpp#L1794) call to fail as the contents of `t` is `"OUBLE UNTIL SUCCESS OR 10 TIMES"`.

**Comment by trel** [comment]
checkboxed.
