### ISSUE TITLE
JSON in text rendered byteBuf tags suffers XML pollution in new APIs

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#5520]
- [x] 4-2-stable
- [x] master
---
Subsequent pull request for removal of unnecessary connection pool object:
- [x] #5543 (4-2-stable)
- [x] #5544 (master)
---

Related to irods/python-irodsclient issue [260](https://github.com/irods/python-irodsclient/issues/260) but more general since it potentially affects any client attempting to use the iRODS text-oriented (XML) protocol.
## Bug Report
All versions and OS'es.

### What did you try to do?
From a client that uses the XML protocol , call an API which accepts a JSON string as input and/or sends one as output , confirmation of success, or reporting of errors.

In this example we show how the atomic metadata API (20002) would fail for any client using  XML protocol (ie irodsProt=1 for icommands) when  manipulating AVUs containing certain characters ( < , > and  & ) that are obligatorily escaped within XML.  _(Because the JSON-encoded request occurs within a **bytesBuf** XML tag we must avoid using these characters in a naked, un-escaped fashion.)_

### Expected behavior

Such client and its XML driver may reasonably expect that these XML-specific characters are -- perforce -- to be escaped by the sender and de-escaped by the receiver, when embedded via  JSON formatted text in an RODS_API_REQUEST .  Thus when trying to, for example, attach an AVU via atomic metadata and having a literal attribute of ">pb&j<" it would send `&gt;PB&amp;J&lt;` to encode that attribute, also (quite reasonably) expecting the iRODS will perform the appropriate de-escaping transformation. 

### Observed behavior (including steps to reproduce, if applicable)

What results when using the API 20002 is that the AVU field is set to contain exactly:
```
&gt;PB&amp;J&lt;
```
meaning that the server has not  performed the desired de-escaping of the JSON text.

### Possible solution
For atomic metadata (already released with 4.2.8) introduce a second, possibly "wrapped" version of this api assigned a different number (`25002`?), with the input/output JSON values being hardened by enclosing them in a binBytesBuf tag (which does automatic base64 encoding, and would make XML escaping unnecessary).

For API's to be released soon, force them to use BinBytesBuf tags when going over XML.

**Comment by d-w-moore** [comment]
With regard to the new JSON style APIs 20000-20007 and 120000 (ADAPTER_APN):

I've seen the CI test suite pass (including running the unit tests) with the packing instructions in the `apidef`s set to "BinBytesBuf_PI" (where they had been "BytesBuf_PI") and just now have also looked the source for those APIs and they follow the same common pattern we noted last week:
   - use of the BytesBuf / BinBytesBuf `len` field rather than depending on a terminating NUL
   - placing a terminating NUL in the string buffer sent back to the client(s)  (which in the XML_PROT case gets base64 encoded at the end of the JSON string returned from the API call) in case of any "casual presumption" those clients might have of expecting a terminating NUL.

It looks good for the strategy of blanket conversion of BytesBuf_PI to BinBytesBuf_PI for the input/output parameters in these APIs.

So I am thinking that adding a simple unit test through a "string echo" test API (run on some JSON input that includes &,< and > characters ) is a good-enough test around this issue, as long as the  test API is designed to this very same pattern.

Thoughts? @trel @jasoncoposky @korydraughn @alanking

**Comment by trel** [comment]
Do we need a new standalone test API endpoint just for this if we already have APIs with this pattern?    Can't we just use those - and exercise the same codepath - and convince ourselves that we're safe?

**Comment by d-w-moore** [comment]
It would be less redundant to exercise the same codepath, yes.

**Comment by d-w-moore** [comment]
I will look over the existing unit tests ....  I don't think any of them yet exercise a client-server exchange using XML_PROT.

**Comment by trel** [comment]
checkbox and close!
