### ISSUE TITLE
Update test_delay_queue_with_long_job to deal in whole seconds

### ISSUE THREAD

**Issue by alanking** [irods/irods#5526]
- [x] master
- [x] 4-2-stable
---
As of #5511, `PLUSET` will no longer actually support fractional seconds. The tests in `test_delay_queue` should be updated to support whole seconds. Bonus points for fleshing out test intent in comments

**Comment by d-w-moore** [comment]
Just to be clear PLUSET did not actually supported fractional seconds prior to #5511, just maintained that appearance. It merely accepted them and truncated silently via `atoi`.  ("0.1s" was parsed and stored as an integer delay of 0 seconds) 

The merge of #5511 will continue this behavior but you will note that the more ridiculous intervals 0.1h (or 0.1y for that matter) will not be allowed as that introduces the possibility of much larger round-down discrepancies than 1/10 second.

The odd behavior of the `test_delay_queue` tests wrt fractional seconds probably have to do with their internal caching of floating point numbers.

**Comment by alanking** [comment]
I have updated this test with some new comments as well as making the intervals a little more flexible for use in topology testing. PR coming soon
