### ISSUE TITLE
Second forced (overwrite) recursive iget places copy of collection inside previous copy of collection

### ISSUE THREAD

**Issue by cbcunc** [irods/irods#5527]
### What did you try to do?

```iget -rf``` followed by a later identical ```iget -rf```

### Expected behavior

Overwrite of the directory which is a copy of the collection as per iget help:

```
-f  force - write local files even it they exist already (overwrite them)
-r  recursive - retrieve subcollections
```

### Observed behavior (including steps to reproduce, if applicable)

The overwrite does not occur. Instead a copy of the collection is placed inside the previous copy of the collection:

```
[hydro-service@tds-proxy ~]$ iget -rf /hydrotestZone/home/betaDataProxy/f203458dcdde4cc8982a4a02aec9de8f test
[hydro-service@tds-proxy ~]$ ls -l
total 90924
...
drwxr-x---  3 hydro-service service accounts       99 Apr  7 14:09 test
...
[hydro-service@tds-proxy ~]$ ls -l test
total 20
-rw-r----- 1 hydro-service service accounts   55 Apr  7 14:09 bagit.txt
drwxr-x--- 3 hydro-service service accounts   70 Apr  7 14:09 data
-rw-r----- 1 hydro-service service accounts  429 Apr  7 14:09 manifest-md5.txt
-rw-r----- 1 hydro-service service accounts 4593 Apr  7 14:09 readme.txt
-rw-r----- 1 hydro-service service accounts  146 Apr  7 14:09 tagmanifest-md5.txt
[hydro-service@tds-proxy ~]$ iget -rf /hydrotestZone/home/betaDataProxy/f203458dcdde4cc8982a4a02aec9de8f test
[hydro-service@tds-proxy ~]$ ls -l
...
drwxr-x---  4 hydro-service service accounts      138 Apr  7 14:12 test
...
[hydro-service@tds-proxy ~]$ ls -l test
total 20
-rw-r----- 1 hydro-service service accounts   55 Apr  7 14:09 bagit.txt
drwxr-x--- 3 hydro-service service accounts   70 Apr  7 14:09 data
drwxr-x--- 3 hydro-service service accounts   99 Apr  7 14:12 f203458dcdde4cc8982a4a02aec9de8f
-rw-r----- 1 hydro-service service accounts  429 Apr  7 14:09 manifest-md5.txt
-rw-r----- 1 hydro-service service accounts 4593 Apr  7 14:09 readme.txt
-rw-r----- 1 hydro-service service accounts  146 Apr  7 14:09 tagmanifest-md5.txt
[hydro-service@tds-proxy ~]$ ls -l test/f203458dcdde4cc8982a4a02aec9de8f
total 20
-rw-r----- 1 hydro-service service accounts   55 Apr  7 14:12 bagit.txt
drwxr-x--- 3 hydro-service service accounts   70 Apr  7 14:12 data
-rw-r----- 1 hydro-service service accounts  429 Apr  7 14:12 manifest-md5.txt
-rw-r----- 1 hydro-service service accounts 4593 Apr  7 14:12 readme.txt
-rw-r----- 1 hydro-service service accounts  146 Apr  7 14:12 tagmanifest-md5.txt
[hydro-service@tds-proxy ~]$
```

**Comment by trel** [comment]
Hm...   Same as linux?

```
$ ls asdfasdfasdf/
apples.txt	bananas.txt
$ cp -rf asdfasdfasdf test
$ ls test/
apples.txt	bananas.txt
$ cp -rf asdfasdfasdf test
$ ls test/
apples.txt	asdfasdfasdf/	bananas.txt
```

**Comment by cbcunc** [comment]
```-f``` is not advertized as overwrite in linux:
```
-f, --force
              if an existing destination file cannot be opened, remove it and try again (this option is ignored when the -n option is also used)
```

**Comment by cbcunc** [comment]
Not that the linux behavior isn't equally ambiguous. It also provide no way to recursively overwrite a copy by a different name and behaves differently upon re-execution.

**Comment by cbcunc** [comment]
If this behavior were changed, it would likely break a lot of pre-existing scripts. I can work around it.

**Comment by cbcunc** [comment]
Yeah, just means target name must be same as collection name. Can follow up with rename.

**Comment by trel** [comment]
Okay - so if no action items here... I'll mark as done?

**Comment by cbcunc** [comment]
I would call it "won't fix" instead of "invalid,", but I'm closing it.

**Comment by trel** [comment]
objection acknowledged - we can focus on the 'resolved' part.  :)

**Comment by cbcunc** [comment]
> cp -rf asdfasdfasdf test

Had to revisit this.

`cp -rf asdfasdfasdf/ test`

does not exhibit the objectionable behavior.

**Comment by alanking** [comment]
With no trailing slash...
```bash
$ ls -l asdfasdfasdf/
total 4
-rw-rw-r-- 1 alanking alanking 6 Jul  1 16:22 hello.txt
$ cp -rf asdfasdfasdf test1
$ ls -l test1
total 4
-rw-rw-r-- 1 alanking alanking 6 Jul  1 16:22 hello.txt
$ cp -rf asdfasdfasdf test1
$ ls -l test1
total 8
drwxrwxr-x 2 alanking alanking 4096 Jul  1 16:22 asdfasdfasdf
-rw-rw-r-- 1 alanking alanking    6 Jul  1 16:22 hello.txt
```

With trailing slash...
```bash
$ ls -l asdfasdfasdf/
total 4
-rw-rw-r-- 1 alanking alanking 6 Jul  1 16:22 hello.txt
$ cp -rf asdfasdfasdf/ test2
$ ls -l test2
total 4
-rw-rw-r-- 1 alanking alanking 6 Jul  1 16:24 hello.txt
$ cp -rf asdfasdfasdf/ test2
$ ls -l test2
total 8
drwxrwxr-x 2 alanking alanking 4096 Jul  1 16:24 asdfasdfasdf
-rw-rw-r-- 1 alanking alanking    6 Jul  1 16:24 hello.txt
```

Still seems the same to me... Am I missing something?

**Comment by cbcunc** [comment]
```
(base) cbc@RENCI_V7C4Y96JLW itest % mkdir asdfasdfasdf
(base) cbc@RENCI_V7C4Y96JLW itest % touch asdfasdfasdf/apples.txt
(base) cbc@RENCI_V7C4Y96JLW itest % touch asdfasdfasdf/bananas.txt
(base) cbc@RENCI_V7C4Y96JLW itest % cp -rf asdfasdfasdf/ test
(base) cbc@RENCI_V7C4Y96JLW itest % ls test
apples.txt	bananas.txt
(base) cbc@RENCI_V7C4Y96JLW itest % cp -rf asdfasdfasdf/ test
(base) cbc@RENCI_V7C4Y96JLW itest % ls test
apples.txt	bananas.txt
(base) cbc@RENCI_V7C4Y96JLW itest % cp -rf asdfasdfasdf test
(base) cbc@RENCI_V7C4Y96JLW itest % ls test
apples.txt	asdfasdfasdf	bananas.txt
(base) cbc@RENCI_V7C4Y96JLW itest %
```

**Comment by alanking** [comment]
What shell are you using? I am using `bash` and was not able to reproduce that behavior on Ubuntu 22.04 or Centos 7.

**Comment by d-w-moore** [comment]
I see the same behavior in linux, with or without trailing slash on the destination:
```
% cp -rf a test
% ls test
apples	bananas
% cp -rf a test
% ls test
a  apples  bananas
% rm -fr test
% cp -rf a test/
% ls test
apples	bananas
% cp -rf a test/
% ls test
a  apples  bananas
```
And that time, I was using c-shell (csh/tcsh) as I believe Chris is doing.
Bottom line, if you copy a directory into a directory recursively, Linux doesn't seem to care if -f (force) is used, it'll simply duplicate the source directory inside the destination directory, rather than displacing the destination as perhaps one might expect from the advertised forced file-replacement aspect of  the " -f " option in the cp command.

OTOH:
   - files are not the same as directories.
   - Linux seems to operate in the least destructive way (ie not deleting the contents of a large directory by mistake, opting instead to copy the source item into the destination directory alongside everything else pre-exising.

I don't know if I'm making sense here, but the Linux behavior is sensible to me.  I cannot produce any directory-overwriting behavior under Linux (if that's our model for iRODS), so I'm not sure there's anything to be emulated.

**Comment by d-w-moore** [comment]
In short, it looks as if the `iget` command does the expected thing for both destination files and folders where copy semantics are concerned, if what we expect is for iRODS to follow Linux's example in terms of the end result.

**Comment by d-w-moore** [comment]
> Not that the linux behavior isn't equally ambiguous. It also provides no way to recursively overwrite a copy by a different name and behaves differently upon re-execution.

One possible workaround would be to rename any previously existing  directory whose name matches the destination argument, prior the copy.  This could be put into a shell function or alias.

**Comment by d-w-moore** [comment]
> > cp -rf asdfasdfasdf test
> 
> Had to revisit this.
> 
> `cp -rf asdfasdfasdf/ test`
> 
> does not exhibit the objectionable behavior.

@cbcunc FWIW, I couldn't verify.  I tried to reproduce, as you describe it, cp -fr without the objectionable behavior,  varying the first parameter to be both with trailing slash and then without, and could not reproduce it unfortunately. I used both bash and csh in my attempts.  Should we get on a screen share?
