### ISSUE TITLE
imeta addw gives non-zero error code on successful upload

### ISSUE THREAD

**Issue by kript** [irods/irods#5541]
### iRODS Version, OS and Version

4.2.7
Ubuntu 18.04 using 16.04 packages

### What did you try to do?

add metadata to a file with `imeta addw`

### Expected behavior

error code zero on successful addition

### Observed behavior (including steps to reproduce, if applicable)

```
$ imeta addw -d /seq-dev/home/jc18#Sanger1-dev/Iamhere.txt target mapcloud
AVU added to 1 data-objects
$ echo $?
4
$ imeta ls -ld /seq-dev/home/jc18#Sanger1-dev/Iamhere.txt
AVUs defined for dataObj /seq-dev/home/jc18#Sanger1-dev/Iamhere.txt:
attribute: study
value: I3573_PWGS_WGS of S. Typhimurium ST313
units:
time set: 2020-05-07.14:04:54
----
attribute: target
value: mapcloud
units:
time set: 2021-04-07.14:38:14
```

**Comment by trel** [comment]
duplicate of your own https://github.com/irods/irods/issues/5102 ?

**Comment by trel** [comment]
ah, which was a near winner, but lost out to #5101 itself.

**Comment by kript** [comment]
Oops, apologies, thought I'd searched first.
