### ISSUE TITLE
Investigate locking objects BEFORE creating new replicas

### ISSUE THREAD

**Issue by alanking** [irods/irods#5542]
- [x] master
- [x] 4-2-stable
---
In developing write locks for logical locking (see #5539), an issue was discovered in the interface which makes it difficult to lock a data object before creating a new replica for it. The lock and unlock interfaces require a target replica because one only locks a data object when a replica is being opened for read or write. If the replica does not yet exist, this interface breaks.

Locking a data object before the new replica is created is important, however, because the whole point of logical locking is to prevent race conditions in the creation, writing, and reading of replicas in a data object. The gap between creating the new replica and locking the data object could lead to issues.

Please investigate the issue and implement locking of the data object *before* the creation of new replicas. This would look something like this:

0. Create new lock interface which does not require a target replica (lock_for_create?)
1. Insert existing data object into RST
2. Write-lock data object
3. Create new replica (starts in intermediate status)
4. Insert new replica into RST

Should anything go wrong with these steps, we would also require an unlock interface which does not require a target replica.

**Comment by trel** [comment]
`lock_before_create` and `unlock_after_create`?

**Comment by alanking** [comment]
`lock_before_create` seems fine.

`unlock_after_create` is problematic because the unlock counterpart to the new lock interface would exist for the case where registering the new replica fails (i.e. the creation of the replica, so, still "before"). After registration, the replica information for the new replica will be known (replica number is issued by the catalog) and we can use the other interfaces.

So maybe `unlock_before_create` would be appropriate?

**Comment by trel** [comment]
that could work.

since it's not before/after... perhaps... like you initially said... just `lock_for_create` and `unlock_for_create`?

you have similarly named functions for the other operations?

**Comment by alanking** [comment]
I can only see the use for lock/unlock functions of this nature which will immediately publish the results to the catalog, so it would actually be no-target-replica-versions of `lock_and_publish`/`unlock_and_publish`. Ultimately, the publishing and non-publishing interfaces call out to the same implementation but I didn't see the point in making the non-publishing versions at this juncture.

I'm actually a fan of the `before_create` variant. So perhaps `lock_before_create_and_publish` and `unlock_before_create_and_publish`?

**Comment by trel** [comment]
big fan of using more words.
