### ISSUE TITLE
iadmin rmresc gives misleading error

### ISSUE THREAD

**Issue by kript** [irods/irods#5545]
- [x] master
- [x] 4-2-stable
---------

### iRODS Version, OS and Version

4.2.7
Ubuntu 18.04

### What did you try to do?

`iadmin rmresc` on a resource which was empty, but part of a tree.

### Expected behavior

Resource was removed _or_ error indicating that the resource would need to be removed from the tree first.

### Observed behavior (including steps to reproduce, if applicable)

```
$ iadmin rmresc irods-seq-sr02-ddn-re12c-13-to-18
remote addresses: 172.17.158.16 ERROR: rcGeneralAdmin failed with error -835000 CAT_RESOURCE_NOT_EMPTY
Level 0: resource 'irods-seq-sr02-ddn-re12c-13-to-18' has a parent or child
```
Should this instead be `CAT_INVALID_ARGUMENT` perhaps? 
Note that `iadmin help rmresc` does not state a requirement that the resource should not be part of a tree to be removed.

**Comment by trel** [comment]
agreed, we can try to separate these two error cases a bit more.

and we'll update the docs.

**Comment by trel** [comment]
Proposed change in error code:
```diff
--- a/plugins/database/src/db_plugin.cpp
+++ b/plugins/database/src/db_plugin.cpp
@@ -4347,7 +4347,7 @@ irods::error db_del_resc_op(
                   "resource '%s' has a parent or child",
                   _resc_name );
         addRErrorMsg( &_ctx.comm()->rError, 0, errMsg );
-        return ERROR( CAT_RESOURCE_NOT_EMPTY, "resource not empty" );
+        return ERROR( CHILD_EXISTS, "resource has a parent or child" );
     }
 
```

@kript does that seem sufficient?

**Comment by kript** [comment]
LGTM, thanks.
