### ISSUE TITLE
Voting on OPEN ignores pre-existing replicas not on default resource 

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#5548]
- [x] master
- [x] 4-2-stable
-————

### iRODS Version, OS and Version
iRODS 4-2-stable 69cc129bfd78281f26825966c5361d009c168890
Ubuntu 18.04

### What did you try to do?
   - create a new resource, **test_resource** , which is not the default resource, and create a data object on that resource.
   - open and write N bytes into that data object.
   - make sure the file size increases by N bytes

### Expected behavior
The pre-existing replica (zero-length at the time of creation) should now have the same number of bytes in it as were just written.

### Observed behavior (including steps to reproduce, if applicable)
   - we end up with a new replica on the default resource, which receives the written bytes, while the pre-existing replica gets none. 
   - the two replicas have different size but are both marked valid:
   ```
   rods              0 test_resource            0 2021-04-21.12:56 & test1
   rods              1 demoResc            4 2021-04-21.12:56 & test1
   ```
This means that the server's voting mechanism is not working as expected for an OPEN operation.
(In the below reproduction of the issue, we find that this behavior can be corrected by supplying a `DEST_RESC_NAME_KW` in the client's `open('w+')` call.)

To reproduce:

Copy/paste [`demo.py`](#demopy-script) from the script listed below, into the current working directory.
With PRC installed, run `python demo.py -b`

When the program halts at the python debugger (Pdb) prompt, examine the object `test1` using `ils -L` in a different shell / window. (You will see the  above-mentioned two valid replicas of different lengths).

At the interrupted program (Pdb) prompt, hit 'c' to continue the demo test.
The message indicating the failed test condition will print.
```
(Pdb) c
after writing the dummy_str of length 4
the desired condition obj.size == len(dummy_str) is False
```

On an alternative run using `-r` to cause the test program to hint the resource name of `test_resource` as an option in the OPEN call, we can see that the expected test condition will be fulfilled, and (if `-b` is used to inspect during  program pause) there will only be one replica present post-WRITE, as one would expect.
```
$ python demo.py  -r 
after writing the dummy_str of length 4
the desired condition obj.size == len(dummy_str) is True
```
---
<A id="demopy-script"></A>
### demo.py script
```
#!/usr/bin/env python
  
from __future__ import print_function
import os, sys, atexit
from irods.session import iRODSSession
import getopt
import pdb
import irods.keywords as kw

def get_session(auto_cleanup = True):
    try:
        env_file = os.environ['IRODS_ENVIRONMENT_FILE']
    except KeyError:
        env_file = os.path.expanduser('~/.irods/irods_environment.json')
    session = iRODSSession(irods_env_file=env_file)
    if auto_cleanup:
        atexit.register (lambda *_: session.cleanup())
    return session

if __name__ == '__main__':

    # get commandline options '-r' and '-b'
    (cmd_switches, cmd_args) = getopt.getopt(sys.argv[1:],'rb')
    breakpoint = resource_specific = False
    for sw,val in cmd_switches:
        if sw == '-b':   breakpoint = True
        elif sw == '-r': resource_specific = True

    # setup
    sess = get_session(auto_cleanup = True)
    resc_name = 'test_resource'
    resc_type = 'unixfilesystem'
    resc_class = ''
    resc_host = sess.host
    resc_path = '/tmp/' + resc_name
    dummy_str = b'blah'
    coll_path = '/{0.zone}/home/{0.username}'.format(sess)
    obj_name = 'test1'
    obj_path = '{coll_path}/{obj_name}'.format(**locals())

    # make new resource
    sess.resources.create(resc_name, resc_type, resc_host, resc_path,
                          resource_class = resc_class)

    # create file on new resource
    resource = sess.resources.get(resc_name)
    obj = sess.data_objects.create(obj_path, resc_name)

    # direct to resource by name if '-r' supplied on cmdlnie
    open_options = {}
    if resource_specific:  open_options[kw.DEST_RESC_NAME_KW] = resc_name

    # write something to the file; 
    with obj.open('w+', **open_options) as obj_desc:
        obj_desc.write(dummy_str)

    if breakpoint:          # <-- breakpoint for inspecting objects in another
        pdb.set_trace()     #      window, if desired

    # refresh object (size has changed)
    obj = sess.data_objects.get(obj_path)

    # check file length
    testCondition = "obj.size == len(dummy_str)"
    print ( "after writing the dummy_str of length", len(dummy_str) )
    print ( "the desired condition", testCondition, "is", eval(testCondition))

    # clean up
    obj.unlink(force=True)
    resource.remove()
```

**Comment by d-w-moore** [comment]
This issue could have been moot / inappropriately filed if I had the setting `"default_resource_name": "demoResc"` defined in `/etc/irods/server_config.json` at the time? Which maybe overrides the voting mechanism ... @trel @alanking opinion?

**Comment by alanking** [comment]
Just to boil this down a little...

`DATA_OBJ_OPEN_APN` was invoked on a logical path with no existing replicas and the `DEST_RESC_NAME_KW` was provided in the `dataObjInp_t` with a value of `test_resource` which is not the default resource, `demoResc`. The creation of the first replica of the data object correctly targeted the non-default resource as evidenced by the 0-length replica 0 on `test_resource`, but the subsequent write targeted the default resource `demoResc`... which surprisingly created the new replica there and wrote the bytes there.

**Comment by d-w-moore** [comment]
@alanking Possible that an OPEN needs RESC_NAME_KW instead of DEST_RESC_NAME_KW to properly specify target (root) resource.

**Comment by d-w-moore** [comment]
@trel @alanking  @korydraughn  - I'm not able to reproduce this now, on a bare docker container and fresh iRODS install.

What I do see - and likely it's the same behavior as the "issue" I thought I'd captured here - may not even be an issue. 

More like a manifestation of DATA_OBJ_OPEN_AN's essentially sane compromise with POSIX semantics.

Upshot, if you don't introduce O_CREAT (which PRC uses when opening with "a" or "w", though not with "r+". (Consistent with POSIX), you're ok. The affected replica is the one already in existence, as desired / expected.

Testing with PRC v1.0.0 and  irods 4.2.10:

```
$ cat > open.py
import sys,getopt
from irods.test.helpers import make_session
import irods.keywords as kw

optItems,arg = getopt.getopt(sys.argv[1:],'R:')
optD = dict(optItems)

data_path = arg[0]
open_mode = arg[1]

if '-R' in dict(optD):
    open_options = {kw.DEST_RESC_NAME_KW: optD['-R']}
else:
    open_options = {}

with make_session() as ses:
     o = ses.data_objects.open( data_path , open_mode , **open_options)
     o.write(b'contents111\n')
     o.close()

$ #----------------------------------------------------
$ iadmin mkresc test_resc unixfilesystem                                                  # ---- CREATE resource ----
$ irm -fr testFile ; truncate -s0 testFile ; iput -f -R test_resc testFile ; ils -L # --- INITIAL condition for TEST
/tempZone/home/rods:
  rods              0 test_resc            0 2021-09-14.20:24 & testFile
        generic    /tmp/test_resc/home/rods/testFile
$ python open.py testFile "a"                                      #<----- use (a)ppend mode 
$ ils -L
/tempZone/home/rods:
  rods              0 test_resc            0 2021-09-14.20:24 & testFile
        generic    /tmp/test_resc/home/rods/testFile
  rods              1 demoResc           12 2021-09-14.20:24 & testFile
        generic    /var/lib/irods/Vault/home/rods/testFile
```
This is not outright unreasonable as we did not target a replica. Repeating the test from "INITIAL condition" but targetting the existing replica via "-R test_resc" results in:
```
$ ils -L
/tempZone/home/rods:
  rods              0 test_resc           12 2021-09-14.20:37 & testFile
        generic    /tmp/test_resc/home/rods/testFile
```
The same result can be achieved without even targetting a replica , but instead switching the open mode from "a" to "r+".

I think what we're seeing here is probably the best-to-be-expected intersection / interaction of POSIX Unix open behavior with the iRODS universe (aka having multiple replicas of a "file" will demand either specifying which replica we want to use, or leaving out the O_CREAT).

I vote "no bug".

**Comment by trel** [comment]
agreed with everything here.    also, yes, to your very last point.... the double & with different sizes is definitely a bug.

**Comment by d-w-moore** [comment]
Yes and it only appears to be when it's a new replica. Probably something in the O_CREAT logic that influences the open flags, and on close, the catalog won't get updated for DATA_REPL_STATUS in the replica that already existed.  By stepping through , though, I can see both repl's are at '?' status while the object is open for write.

**Comment by alanking** [comment]
Here is the logic around how to finalize a data object *in general* in `rsDataObjClose`: https://github.com/irods/irods/blob/d192a8afb101b80e06d31b5055e879f03bcd0329/server/api/src/rsDataObjClose.cpp#L361-L376

In this case, the `CREATE_TYPE` is correctly being attributed to the `openType`​ of the L1 descriptor in this operation, so the sibling replicas have their statuses "restored".

Here is the comment which declared the decision that was made to stale sibling replicas when a low-level create/write/close is performed: https://github.com/irods/irods/issues/5187#issuecomment-823304041 The change was applied to `replica_close`, which is what `istream` uses, but it was not reflected in `rsDataObjClose`.

I have not thought through all of the implications of such a change, but I agree that it should at least be consistent. Should be pretty easy to implement.

**Comment by alanking** [comment]
I think I have a fix for the follow-up issue. For posterity...
```python
import sys,getopt
from irods.test.helpers import make_session
import irods.keywords as kw

optItems,arg = getopt.getopt(sys.argv[1:],'R:')
optD = dict(optItems)

data_path = arg[0]
open_mode = arg[1]

if '-R' in dict(optD):
    open_options = {kw.DEST_RESC_NAME_KW: optD['-R']}
else:
    open_options = {}

with make_session() as ses:
     o = ses.data_objects.open( data_path , open_mode , **open_options)
     o.write(b'contents111\n')
     o.close()
```

```bash
$ # with no resource specified
$ irm -fr testFile ; truncate -s0 testFile ; iput -f -R test_resc testFile ; ils -L
/tempZone/home/rods:
  rods              0 test_resc            0 2021-09-15.18:18 & testFile
        generic    /tmp/test_resc/home/rods/testFile
$ python open.py /tempZone/home/rods/testFile "a"
$ ils -L
/tempZone/home/rods:
  rods              0 test_resc            0 2021-09-15.18:18 X testFile
        generic    /tmp/test_resc/home/rods/testFile
  rods              1 demoResc           12 2021-09-15.18:18 & testFile
        generic    /var/lib/irods/Vault/home/rods/testFile

$ # with resource specified
$ irm -fr testFile ; truncate -s0 testFile ; iput -f -R test_resc testFile ; ils -L
/tempZone/home/rods:
  rods              0 test_resc            0 2021-09-15.18:20 & testFile
        generic    /tmp/test_resc/home/rods/testFile
$ python open.py -R test_resc /tempZone/home/rods/testFile "a" 
$ ils -L
/tempZone/home/rods:
  rods              0 test_resc           12 2021-09-15.18:21 & testFile
        generic    /tmp/test_resc/home/rods/testFile
```

**Comment by trel** [comment]
nice.
