### ISSUE TITLE
In PEP pep_database_reg_data_obj_post, DATA_OBJ_INFO's data_owner_name and data_owner_zone fields blank

### ISSUE THREAD

**Issue by tedgin** [irods/irods#5554]
- [x] master
- [x] 4-2-stable
--------

## Bug Report

This may be a feature request. I'm not certain. In the dynamic PEP `pep_database_reg_data_obj_post`, the input parameter `*DATA_OBJ_INFO` has the fields `data_owner_name` and `data_owner_zone`, but it is just teasing me. They are empty.  By this point in the data object creation process, the data owner is known, so the fields should be populated. If these fields are intentionally empty, I would like to change this bug report into a feature request. Having these fields populated is very handy inside policy rules.

### iRODS Version, OS and Version

iRODS 4.2.8, CentOS 7

### What did you try to do?

I have a rule attached to the PEP `pep_database_reg_data_obj_post` that writes `*DATA_OBJ_INFO.data_owner_name` and `*DATA_OBJ_INFO.data_owner_zone` to the server log. I use `iput` to upload a file.

### Expected behavior

I expect to see in the log file that the data owner and zone for the newly created data as me and my zone.

### Observed behavior (including steps to reproduce, if applicable)

Instead I see both values are logged as empty.

**Comment by alanking** [comment]
I believe this will be fixed as of this commit (linked master version but will be included in 4.2.9):
https://github.com/irods/irods/commit/7b910786ed9cf1cef0932ecd3cdab673ca8d38f3

Relevant lines: https://github.com/irods/irods/blob/4c8feea2e1be93de2686991796f2d814698892e5/plugins/database/src/db_plugin.cpp#L2697-L2698

And what it looked like in 4.2.8, for posterity: https://github.com/irods/irods/blob/9eb6c23df45cdedff8ee9c3af71a65d304635037/plugins/database/src/db_plugin.cpp#L2703-L2704

The info was being taken directly from the `RsComm` struct and not reflecting it back into the new replica for the data object (this goes for several other fields as well, including create time).

**Comment by trel** [comment]
Excellent - so sounds like all we need is a tiny PEP test to confirm the desired behavior.

**Comment by trel** [comment]
checkboxed.
