### ISSUE TITLE
upgrade from 4.1 to 4.2.8 fails to move packedRei files

### ISSUE THREAD

**Issue by tedgin** [irods/irods#5577]
- [x] master
- [x] 4-2-stable
--------
### iRODS Version, OS and Version

iRODS 4.1.10 upgrading to iRODS 4.2.8, CentOS 7

### What did you try to do?

After installing the `irods-server` package on the catalog service provider, I attempted to start the service using `irodsctl`.  

### Expected behavior

I expected the iRODS service to start.

### Observed behavior (including steps to reproduce, if applicable)

`./irodsctl start` generated the following error.

```
Traceback (most recent call last):
  File "./scripts/irods_control.py", line 127, in <module>
    sys.exit(main())
  File "./scripts/irods_control.py", line 116, in main
    operations_dict[operation]()
  File "./scripts/irods_control.py", line 70, in <lambda>
    operations_dict['start'] = lambda: irods_controller.start()
  File "/var/lib/irods/scripts/irods/controller.py", line 40, in start
    upgrade_configuration.upgrade(self.config)
  File "/var/lib/irods/scripts/irods/upgrade_configuration.py", line 93, in upgrade
    shutil.move(old_path, new_path)
  File "/usr/lib64/python2.7/shutil.py", line 301, in move
    copy2(src, real_dst)
  File "/usr/lib64/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/var/lib/irods/server/config/packedRei/rei.rods.2310170970'
```

An inspection of `scripts/irods/upgrade_configuration.py` shows that the script attempts to moved all of the REI files in the 4.1 location, `iRODS/server/config/packedRei/`, to the non-existent folder `server/config/packedRei/`. The script should be moving them to the folder `config/packedRei/`.

**Comment by trel** [comment]
both of these lines appear suspect for this 4.1.x upgrade scenario...

https://github.com/irods/irods/blob/23efd5f6812371d3d668c32fd4fa9da37ab41623/scripts/irods/upgrade_configuration.py#L82-L83

not sure... how this ever worked...

@tedgin If you change those two lines before running `./irodsctl start`, does it come up cleanly?

**Comment by tedgin** [comment]
I'm sorry. I can't check that. I deleted the REI files so there's nothing to move any longer. The REI files were periodic rules that I can add back at the end of the upgrade, so it was safe to get rid of them.
