### ISSUE TITLE
Corrupted file replication from coordinating replication resource to unixfilesystem resource will not fail and only lead to error in rodsLog

### ISSUE THREAD

**Issue by PaulVanSchayck** [irods/irods#5592]
- [x] master
- [x] 4-2-stable
---------

### iRODS Version, OS and Version
iRODS: 4.2.8
OS: Ubuntu 18.04 (in Docker)

We first discovered this on our production environment (4.2.6), but now also tested in a minimal Docker environment (4.2.8), with no catalog consumers and a default core.re.

### What did you try to do?
I've got a coordinating replication resource and demoResc

```
$ ilsresc
demoResc:unixfilesystem
replRescUM01:replication
├── UM-hnas-4k:unixfilesystem
└── UM-hnas-4k-repl:unixfilesyste
```

I put a file on `replRescUM01` and checksum it:

```
$ echo "bar" > /tmp/foo
$ iput -R replRescUM01 /tmp/foo
$ ichksum foo
    foo    sha2:fYZelZskZpGMmGOvypQtD7idfJrAyZuvw3SVBN7ZdzA=
$ ils -L foo
  rods              0 replRescUM01;UM-hnas-4k-repl            4 2021-05-04.13:46 & foo
    sha2:fYZelZskZpGMmGOvypQtD7idfJrAyZuvw3SVBN7ZdzA=    generic    /mnt/repl/home/rods/foo
  rods              1 replRescUM01;UM-hnas-4k            4 2021-05-04.13:46 & foo
        generic    /mnt/resc/home/rods/foo
```

I then simulate a corrupted data transfer by modifying the `foo` file on the physical file path of `UM-hnas-4k`. Only modifying one character
```
$ echo "far" > /mnt/repl/home/rods/foo
```
I then replicate to demoResc:
```
$ irepl -R demoResc foo
$ ils -L foo
  rods              0 replRescUM01;UM-hnas-4k-repl            4 2021-05-04.13:46 & foo
    sha2:fYZelZskZpGMmGOvypQtD7idfJrAyZuvw3SVBN7ZdzA=    generic    /mnt/repl/home/rods/foo
  rods              1 replRescUM01;UM-hnas-4k            4 2021-05-04.13:46 & foo
        generic    /mnt/resc/home/rods/foo
  rods              2 demoResc            4 2021-05-04.13:48 & foo
        generic    /var/lib/irods/vault/home/rods/foo
$ cat /var/lib/irods/vault/home/rods/foo
bar
```
The replicated file has the original content (I presume from replica 1)

### Expected behavior
I expect a `USER_CHKSUM_MISMATCH` error. Like I get when replicating this file from one unixfilesystem resource to another  unixfilesystem resource.

### Observed behavior (including steps to reproduce, if applicable)
The `irepl` command returns without error. The file object also is replicated to the destination resource. It's on disk. There is no checksum in the catalog for that object.

This also happens with `msiDataObjRepl`, even with `verifyChksum` enabled. The return value of `*status` is a valid 0.

In the rodsLog I see the following
```
May  4 11:08:29 pid:349 NOTICE: procChksumForClose: chksum mismatch for /nlmumc/home/rods/foo src [sha2:fYZelZskZpGMmGOvypQtD7idfJrAyZuvw3SVBN7ZdzA=] new [sha2:TzQ+Saw8l0J/78ZN4EIl+8QJHR05aXyuliZV1Y5b1bs=]
May  4 11:08:29 pid:349 remote addresses: 172.23.0.2, 172.23.0.3 ERROR: [-]     /irods_git_repo/server/api/src/rsFileCreate.cpp:196:int _rsFileCreate(rsComm_t *, fileCreateInp_t *, rodsServerHost_t *, fileCreateOut_t **) :  status [UNIX_FILE_RMDIR_ERR]  errno [Not a directory] -- m
essage [EEXIST 1 fileRmdir for [/var/lib/irods/vault/home/rods/foo]]
        [-]     /irods_git_repo/server/drivers/src/fileDriver.cpp:352:irods::error fileRmdir(rsComm_t *, irods::first_class_object_ptr) :  status [UNIX_FILE_RMDIR_ERR]  errno [Not a directory] -- message [failed to call 'rmdir']
                [-]     /irods_git_repo/plugins/resources/unixfilesystem/libunixfilesystem.cpp:1020:irods::error unix_file_rmdir(irods::plugin_context &) :  status [UNIX_FILE_RMDIR_ERR]  errno [Not a directory] -- message [Rmdir error for "/var/lib/irods/vault/home/rods/foo", errno
 = "Not a directory", status = -521020.]

May  4 11:08:29 pid:349 remote addresses: 172.23.0.2, 172.23.0.3 ERROR: [-]     /irods_git_repo/server/api/src/rsFileCreate.cpp:210:int _rsFileCreate(rsComm_t *, fileCreateInp_t *, rodsServerHost_t *, fileCreateOut_t **) :  status [UNIX_FILE_CREATE_ERR]  errno [File exists] -- message [EEXIST 2 fileCreate for [/var/lib/irods/vault/home/rods/foo]]
        [-]     /irods_git_repo/server/drivers/src/fileDriver.cpp:38:irods::error fileCreate(rsComm_t *, irods::first_class_object_ptr) :  status [UNIX_FILE_CREATE_ERR]  errno [File exists] -- message [failed to call 'create']
                [-]     /irods_git_repo/plugins/resources/unixfilesystem/libunixfilesystem.cpp:625:irods::error unix_file_create(irods::plugin_context &) :  status [UNIX_FILE_CREATE_ERR]  errno [File exists] -- message [create error for "/var/lib/irods/vault/home/rods/foo", errno = "File exists".]```
```

So, you see the chksum error first. But then followed by an attempted recreate of the file. Which fails, because the file already exists. This seems odd.

Note: We see these `UNIX_FILE_RMDIR_ERR` and `UNIX_FILE_CREATE_ERR` pop up more often when replicating files from a coordinating replication resource. In fact, we found this checksum issue while debugging another replication failure. Could there be a generic code path for coordinating resources that leads to this *double* action being taken?

**Comment by trel** [comment]
Can you provide an `ils -L` for the data object both before and after the `irepl` command?

Pretty sure this is already fixed in 4-2-stable - we'll reproduce and confirm with a new test or pointing to a test already in the test suite.

**Comment by trel** [comment]
Oh, and can you confirm which data is in the newest replica on disk?  the original data, or the corrupted data?

**Comment by PaulVanSchayck** [comment]
I've added the `ils -L` output the original report. The newest replica has the original data, I've also made this explicit in the output. So I presume the data was actually copied from the other replica.

We were surprised by the behavior of calculating the checksum upon replication, but only when there is already checksum available. Without a checksum first calculated, this doesn't happen.

Can you clarify (in the docs) what `verifyChksum` of `msiDataObjRepl()` is supposed to do? Also note that there is no equivalent for `irepl`.

**Comment by trel** [comment]
So the end result is:
1) correct data in new replica (as expected)
2) missing checksums (instead of correctly calculated checksums per replica in the catalog)

Yes, the logging you're seeing is part of the error-recovery path after the initial checksum mismatch on the first attempted replication - I think we've already cleaned that up in 4-2-stable...

The lack of checksums on all the replicas in the catalog I believe has also been reworked in 4-2-stable.

We'll get some links/confirmation here.

Replication of a data object with an existing checksum should verify the checksum after the new write - this is the implicit 'verify' codepath.

**Comment by korydraughn** [comment]
This has been resolved in 4-2-stable.

Will add tests for this.

**Comment by PaulVanSchayck** [comment]
Thanks Kory for that confirmation. Could you maybe, for future reference, and if it's not too much to ask, post the output of the test case I posted above.

**Comment by korydraughn** [comment]
Here are the results running against 4-2-stable (ca8417599c4e2706e058b833f14156ebd47b4db5):
```bash
irods@kdd-ws:~$ bash repl_chksum.sh                                                                                                                                                           
+ irm -f foo
+ ilsresc
demoResc:unixfilesystem
replresc:replication
├── ufs1:unixfilesystem
└── ufs2:unixfilesystem
+ echo bar
+ iput -R replresc foo
+ ichksum foo
    foo    sha2:fYZelZskZpGMmGOvypQtD7idfJrAyZuvw3SVBN7ZdzA=
+ ils -L foo
  rods              0 replresc;ufs1            4 2021-05-04.09:42 & foo
    sha2:fYZelZskZpGMmGOvypQtD7idfJrAyZuvw3SVBN7ZdzA=    generic    /var/lib/irods/ufs1Vault/home/rods/foo
  rods              1 replresc;ufs2            4 2021-05-04.09:42 & foo
        generic    /var/lib/irods/ufs2Vault/home/rods/foo
+ echo far
+ irepl -R demoResc foo
remote addresses: X.X.X.X ERROR: replUtil: repl error for /tempZone/home/rods/foo, status = -314000 status = -314000 USER_CHKSUM_MISMATCH
+ ils -L foo
  rods              0 replresc;ufs1            4 2021-05-04.09:42 & foo
    sha2:fYZelZskZpGMmGOvypQtD7idfJrAyZuvw3SVBN7ZdzA=    generic    /var/lib/irods/ufs1Vault/home/rods/foo
  rods              1 replresc;ufs2            4 2021-05-04.09:42 & foo
        generic    /var/lib/irods/ufs2Vault/home/rods/foo
  rods              2 demoResc            4 2021-05-04.09:42 X foo
    sha2:fYZelZskZpGMmGOvypQtD7idfJrAyZuvw3SVBN7ZdzA=    generic    /var/lib/irods/Vault/home/rods/foo
+ cat /var/lib/irods/ufs1Vault/home/rods/foo
far
```

From the log file:
```bash
May  4 09:42:52 pid:8260 remote addresses: X.X.X.X ERROR: [replicate_data:637] - error finalizing replica; [USER_CHKSUM_MISMATCH: calculate_checksum: chksum mismatch for /tempZone/home/rods/foo src [sha2:fYZelZskZpGMmGOvypQtD7idfJrAyZuvw3SVBN7ZdzA=] new [sha2:KYjs0R2lI9O5J1YHC8lVmNWlLIftIkEoLcX1oQbkpVQ=]

], ec:[-314000]
May  4 09:42:52 pid:8260 remote addresses: X.X.X.X ERROR: [replicate_data_object:738] - failed to replicate [/tempZone/home/rods/foo]
May  4 09:42:52 pid:8260 NOTICE: rsDataObjRepl - Failed to replicate data object. status:[-314000]
```

**Comment by trel** [comment]
checkboxed.

**Comment by PaulVanSchayck** [comment]
Thanks for getting this fixed/tested/clarified.

One thing I'm left wondering is if we need to document somewhere this implicit checksum taking place. This implicit checksum was entirely new for me. Perhaps in the verifyChecksum documentation of msiDataObjRepl? Or somewhere else? Happy to write a PR.

**Comment by trel** [comment]
@PaulVanSchayck I've created https://github.com/irods/irods/issues/5927 to follow up on this question.
