### ISSUE TITLE
iphymv error when moving replica into a composite tree

### ISSUE THREAD

**Issue by kript** [irods/irods#5635]
### iRODS Version, OS and Version

4.2.7 
Ubuntu 18.04

### What did you try to do?

`iphymv` a replica from a resource outside the tree into the root of the tree which has a replication resource.
The Zone has SSL enabled.

### Expected behavior

Possibly triple replica, but file is removed from old resource and at least two replicas created, one on each side of the replication heirachy. Two replicas on one side would be acceptable as this behaviour isn't fixed until 4.2.9, I believe?

### Observed behavior (including steps to reproduce, if applicable)

Replica is moved, two replicas are created on one side of the tree (both on the same resource) and one on the other side.
The `iphymv` command errors with an SSL handshake error.

#### iphymv error

```
$ iphymv -V -M -S irods-seq-sr03-ddn-re12b-16-to-21 -R root /seq/ont/gridion/GXB01179/BT_Pooled_Muscle/GA20000/GA20000_fast5_2019-05-30T110507.0.tar
remote addresses: 10.160.2.33 ERROR: phymvUtil: phymv error for /seq/ont/gridion/GXB01179/BT_Pooled_Muscle/GA20000/GA20000_fast5_2019-05-30T110507.0.tar, status = -154000 status = -154000 SYS_INTERNAL_ERR
 ERROR: [-]     /irods/lib/core/src/rcConnect.cpp:285:int rcDisconnect(rcComm_t *) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [failed to call 'client stop']
        [-]     /irods/lib/core/src/sockComm.cpp:101:irods::error sockClientStop(irods::network_object_ptr, rodsEnv *) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [failed to call 'client stop']
                [-]     /irods/plugins/network/ssl/libssl.cpp:644:irods::error ssl_client_stop(irods::plugin_context &, rodsEnv *) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [error shutting down the SSL connection]

$ ils -L /seq/ont/gridion/GXB01179/BT_Pooled_Muscle/GA20000/GA20000_fast5_2019-05-30T110507.0.tar
  srpipe            0 root;replicate;seq-green;green5;irods-seq-sr09-sdd   7952400384 2021-04-13.16:44 & GA20000_fast5_2019-05-30T110507.0.tar
    8d4c565343847fe8bda298049cd76ba3    generic    /irods-seq-sr09-sdd/ont/gridion/GXB01179/BT_Pooled_Muscle/GA20000/GA20000_fast5_2019-05-30T110507.0.tar.0
  srpipe            1 root;replicate;seq-green;green5;irods-seq-sr09-sdd   7952400384 2021-04-13.16:44 & GA20000_fast5_2019-05-30T110507.0.tar
    8d4c565343847fe8bda298049cd76ba3    generic    /irods-seq-sr09-sdd/ont/gridion/GXB01179/BT_Pooled_Muscle/GA20000/GA20000_fast5_2019-05-30T110507.0.tar
  srpipe            2 root;replicate;seq-red;red6;irods-seq-ig01-sdg   7952400384 2021-05-12.13:49 & GA20000_fast5_2019-05-30T110507.0.tar
    8d4c565343847fe8bda298049cd76ba3    generic    /irods-seq-ig01-sdg/ont/gridion/GXB01179/BT_Pooled_Muscle/GA20000/GA20000_fast5_2019-05-30T110507.0.tar
```

#### Provider logs

```
May 12 13:48:36 pid:39004 NOTICE: remoteFileCreate: rcFileCreate failed for /irods-seq-sr09-sdd/ont/gridion/GXB01179/BT_Pooled_Muscle/GA20000/GA20000_fast5_2019-05-30T110507.0.tar
May 12 13:48:36 pid:39004 NOTICE: chlModDataObjMeta cmlExecuteNoAnswerSql(rollback) succeeded
May 12 13:48:36 pid:39004 remote addresses: 10.160.2.33, 172.17.10.135, 172.17.158.17, 172.17.72.39 ERROR: [-]   /irods/server/api/src/rsModDataObjMeta.cpp:164:int _rsModDataObjMeta(rsComm_t *, modDataObjMeta_t *) :  status [CAT_NO_ACCESS_PERMISSION]  errno [] -- message [_rsModDataObjMeta - Failed to modify the database for object "/seq/ont/gridion/GXB01179/BT_Pooled_Muscle/GA20000/GA20000_fast5_2019-05-30T110507.0.tar" - CAT_NO_ACCESS_PERMISSION ]
May 12 13:48:36 pid:39004 NOTICE: _rsModDataObjMeta - Failed updating the database with object info.
May 12 13:48:36 pid:39004 remote addresses: 10.160.2.33, 172.17.10.135, 172.17.158.17, 172.17.72.39 ERROR: chkAndHandleOrphanFile:575 rsModDataObjMeta of /irods-seq-sr09-sdd/replica/ont/gridion/GXB01179/BT_Pooled_Muscle/GA20000/GA20000_fast5_2019-05-30T110507.0.tar.1496475244 error. stat = -818000
May 12 13:48:36 pid:39004 NOTICE: remoteFileCreate: rcFileCreate failed for /irods-seq-sr09-sdd/ont/gridion/GXB01179/BT_Pooled_Muscle/GA20000/GA20000_fast5_2019-05-30T110507.0.tar
May 12 13:48:37 pid:39004 NOTICE: remoteFileRename: rcFileRename failed for /irods-seq-sr09-sdd/orphan/ont/gridion/GXB01179/BT_Pooled_Muscle/GA20000/GA20000_fast5_2019-05-30T110507.0.tar.0.1401958723
May 12 13:48:37 pid:39004 NOTICE: renameFilePathToNewDir:rsFileRename from /irods-seq-sr09-sdd/ont/gridion/GXB01179/BT_Pooled_Muscle/GA20000/GA20000_fast5_2019-05-30T110507.0.tar.0 to /irods-seq-sr09-sdd/orphan/ont/gridion/GXB01179/BT_Pooled_Muscle/GA20000/GA20000_fast5_2019-05-30T110507.0.tar.0.1401958723 failed,stat=-528002
May 12 13:48:37 pid:39004 remote addresses: 10.160.2.33, 172.17.10.135, 172.17.158.17, 172.17.72.39 ERROR: chkAndHandleOrphanFile:637 renameFilePathToNewDir failed for file: /irods-seq-sr09-sdd/ont/gridion/GXB01179/BT_Pooled_Muscle/GA20000/GA20000_fast5_2019-05-30T110507.0.tar.0 - status = -528002 UNIX_FILE_RENAME_ERR No such file or directory
```

Related to #4212 possibly? Possibly part of the intermediate replicas fix?

**Comment by kript** [comment]
BTW Both replicas appear correct;

```
$ ls -lah /irods-seq-sr09-sdd/ont/gridion/GXB01179/BT_Pooled_Muscle/GA20000/GA20000_fast5_2019-05-30T110507.0.tar.0
-rw------- 1 irods irods 7.5G May 12 13:48 /irods-seq-sr09-sdd/ont/gridion/GXB01179/BT_Pooled_Muscle/GA20000/GA20000_fast5_2019-05-30T110507.0.tar.0
$ md5sum !$
md5sum /irods-seq-sr09-sdd/ont/gridion/GXB01179/BT_Pooled_Muscle/GA20000/GA20000_fast5_2019-05-30T110507.0.tar.0
8d4c565343847fe8bda298049cd76ba3  /irods-seq-sr09-sdd/ont/gridion/GXB01179/BT_Pooled_Muscle/GA20000/GA20000_fast5_2019-05-30T110507.0.tar.0
$ ls -lah /irods-seq-sr09-sdd/ont/gridion/GXB01179/BT_Pooled_Muscle/GA20000/GA20000_fast5_2019-05-30T110507.0.tar
-rw------- 1 irods irods 7.5G Apr 13 16:44 /irods-seq-sr09-sdd/ont/gridion/GXB01179/BT_Pooled_Muscle/GA20000/GA20000_fast5_2019-05-30T110507.0.tar
$ md5sum !$
md5sum /irods-seq-sr09-sdd/ont/gridion/GXB01179/BT_Pooled_Muscle/GA20000/GA20000_fast5_2019-05-30T110507.0.tar
8d4c565343847fe8bda298049cd76ba3  /irods-seq-sr09-sdd/ont/gridion/GXB01179/BT_Pooled_Muscle/GA20000/GA20000_fast5_2019-05-30T110507.0.tar
```

**Comment by trel** [comment]
I think @alanking already has a test for this in 4-2-stable...

**Comment by alanking** [comment]
I don't have a test specifically around SSL errors and `iphymv` but I did add a test for failure to unlink the source replica in a phymv: https://github.com/irods/irods/blob/4c4a337659d1b81052625c55b820cc7d0ce38248/scripts/irods/test/test_iphymv.py#L335

A few things that have changed for 4.2.9 which may affect this report:

1. `iphymv` no longer allows targeting non-leaf resources (e.g. `-R root`).
2. Multiple replicas on a single resource is no longer a valid concept and should not be possible in 4.2.9 (as far as I know).
3. As the test linked above demonstrates, if the source replica fails to physically unlink for some reason, the source replica will remain in the catalog with the next available replica number and marked as stale. The destination replica will be finalized as per usual.

Was there any information in the log around the `SYS_INTERNAL_ERR` shown in the output for the `iphymv`? This typically indicates some kind of serious error occurring in the agent servicing the request.

**Comment by kript** [comment]
Its wasn't an SSL error per se, we got that because the server dropped the connection when it couldn't create two replicas on the same resource with the same name, I think.

**Comment by alanking** [comment]
Do you suspect any concurrency? In the case of concurrency, if two phymvs show up to the database for the same path at the same time, there isn't much we can do about that. If one attempted phymv happens distinctly before the other, then logical locking would prevent this situation.

Otherwise, I'd be inclined to think this has to do with the hierarchy resolution logic of the replication resource plugin getting tangled in the fact that this is a phymv, which is why we decided to enforce storage resources only for phymvs moving forward.

Do know of any way to reproduce this?

**Comment by kript** [comment]
> Do you suspect any concurrency? In the case of concurrency, if two phymvs show up to the database for the same path at the same time, there isn't much we can do about that. If one attempted phymv happens distinctly before the other, then logical locking would prevent this situation.
> 

Concurrency is unlikely here;  while we were draining other resources using iphymv, the resource that received two copies is a relatively new one, so would be being drained. I'll double-check to be sure though.

> Otherwise, I'd be inclined to think this has to do with the hierarchy resolution logic of the replication resource plugin getting tangled in the fact that this is a phymv, which is why we decided to enforce storage resources only for phymvs moving forward.
> 

Yes, that seems likely.

> Do know of any way to reproduce this?

We have more resources to clear up, if we hit it again I'll update this, but otherwise, I don't have a reliable reproducer. I'll check if our iphymv based migration script hits this though..

**Comment by trel** [comment]
Agreed.   Nominate for closing.
