### ISSUE TITLE
Remove /tmp/mysql.sock dependency from mysql testing input file

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#5668]
- [x] master
- [x] 4-2-stable
---
## Feature
The dependency on mysql.sock makes it difficult to connect to a containerized MySQL database from the host. For development purposes, this situation can be resolved by updating the `localhost_setup_mysql.input` file to use the IP address instead of localhost for the database information. MySQL will choose to use mysql.sock if localhost is used.
https://github.com/irods/irods/blob/aaeaa4cbf4b2446b9d96a46c1c707c537c2ee814/plugins/database/packaging/localhost_setup_mysql.input#L5

**Comment by trel** [comment]
so this isn't `setup_irods.py` itself...

**Comment by korydraughn** [comment]
No. This is specifically for development/testing purposes and only requires a change to the input file fed to the setup script.

**Comment by korydraughn** [comment]
I can pull the commit out of my current PR and create a new PR with just that change if that makes sense.
