### ISSUE TITLE
Codespell report for "iRODS" (on fossies.org)

### ISSUE THREAD

**Issue by jschleus** [irods/irods#5698]
The FOSS server [fossies.org](https://fossies.org) - supporting also the [iRODS](https://fossies.org/iRODS) project - offers among others a feature named "[Source code misspelling reports](https://fossies.org/features.html#codespell)". Such reports are normally only generated on request, but as Fossies administrator I have just created for testing purposes such a [codespell](https://github.com/codespell-project/codespell) based analysis for the iRODS GitHub "master" version:

 &nbsp;https://fossies.org/linux/test/irods-master.tar.gz/codespell.html

That version independent URL hopefully always redirects to the report for the latest "master" version identified by the short GitHub commit ID and a year-month-day string (YYMMDD) representing the according git pull date (mostly = commit date). The data are residing within a special restricted "test" folder that isn't really integrated into the standard Fossies services and should also not be accessible to search engines. The report should be available at least for some weeks and is continuously updated (currently with a half-hourly refresh rate).

Although after a first review some obviously wrong matches ("False Positives") are already filtered out (ignored) please inform me if you find more of them so that I can exclude them if applicable.

OK, no errors were found in the code itself and most errors are "only" in comments and are therefore not directly visible and relevant to the user, but some are also in output strings. Particularly striking seemed to me the spelling of the variable [${langauge}](https://fossies.org/linux/test/irods-master.tar.gz/codespell.html#langauge).

Just for information there are also three supplemental pages showing some used "codespell" [configuration details](https://fossies.org/linux/test/irods-master.tar.gz/codespell_conf.html), all obvious [false positives](https://fossies.org/linux/test/irods-master.tar.gz/codespell_fps.html) and an [misspelling history](https://fossies.org/linux/test/irods-master.tar.gz/codespell_hist.html) (log).

Spelling corrections certainly have a low priority, but they may also contribute to the overall quality of a software project.

**Comment by trel** [comment]
This is great - thanks!

**Comment by trel** [comment]
@jschleus I notice two false positives

- iput
- Wan

Can you please run this again against 'master' and link any new results?     Thanks!

**Comment by trel** [comment]
Ah, missed this part...
> "The report should be available at least for some weeks and is continuously updated (currently with a half-hourly refresh rate)."

I'll wait a few minutes and refresh.

**Comment by jschleus** [comment]
Yes, the report was in the meantime refreshed. Great, looks much better!

What do you mean with the two mentioned false positives? The according matches are visible in the above mentioned [false positives report](https://fossies.org/linux/test/irods-master.tar.gz/codespell_fps.html).

**Comment by trel** [comment]
I was... already looking at that page, apologies.  We'll get the others cleaned up.

**Comment by trel** [comment]
The only one remaining is 'attribte' which should be ignored as it's an intentional misspelling in a test.

Then we'll be all clean!

**Comment by jschleus** [comment]
Although I try at least in principle to discover also such difficult cases, I have overlooked "attribte".

But now, at least from a "codespell" point of view, everything looks perfect!

**Comment by trel** [comment]
Awesome.    Thanks again!
