### ISSUE TITLE
rsDataObjRead( ) cannot read from an object with size in [2G,4G]

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#5709]
- [x] 4-2-stable
- [x] master
---
## Bug Report
iRODS 4.2.9

### What did you try to do?
read from a large data object 2100 * (1024 * 1024) bytes long

### Expected behavior
The traditional behavior is to emulate POSIX. An attempt to read 1 or more bytes (just after an open-for-read) should succeed in that some, if not all, of the requested number of bytes will be read.
In 4.2.9 (but not in 4.2.8), an attempt (seen in https://github.com/irods/python-irodsclient/issues/280 and also when using msiDataObjRead()) to read from the object will return an empty buffer if the object is between 2 and 4 Gigabytes in size. 

### Observed behavior (including steps to reproduce, if applicable)
Within this rule code for example, the writeLine( ) call will produce a value of 0 in the server log:
```
                                                                        
       msiDataObjOpen("objPath=<PATH_TO_A_3Gb_DATA_OBJECT>", *fd); 
        *len = 2048;    
        msiDataObjRead(*fd, *len, *buf);                              
        writeLine("serverLog", "--bytes read-- ");   writeLine("serverLog", *buf);  
                      
```
More info at: https://github.com/irods/irods/pull/5708#issuecomment-864604941

**Comment by d-w-moore** [comment]
Solution in progress : https://github.com/irods/irods/pull/5708

**Comment by trel** [comment]
checkboxed - please close if complete.
