### ISSUE TITLE
Public header naming/organization needs work

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#5712]
# The Current State of Affairs

At present, the directory structure of the iRODS project is as follows:
```
|-- cmake
|-- configuration_schemas
|-- doxygen
|-- irods_schema_messaging
|-- lib
|   |-- api
|   |   |-- include
|   |   |   `-- headers
|   |   `-- src
|   |       `-- source code
|   |-- core
|   |   |-- include
|   *   |   `-- headers
|       `-- src
|           `-- source code
|-- packaging
|-- plugins
|   |-- api
|   |   |-- include
|   |   |   `-- headers
|   |   `-- src
|   |       `-- source code
|   |-- auth
|   |   |-- native
|   *   |   `-- source code
|       |-- osauth
|       |   `-- source code
|       `-- pam
|           `-- source code
|-- scripts
|-- server
|   |-- api
*   |   |-- include
    |   |   `-- headers
    |   `-- src
    |       `-- source code
    |-- auth
    |   `-- src
    |       `-- source code
    |-- core
    |   |-- include
    *   |   `-- headers
        `-- src
            `-- source code
```

Each of these `include` directories are passed to the compiler as a toplevel include directory. While our public headers all live in folders named `include`, they are still organized in that they are separated by component. However, for packaging and installation, we throw them all into a single install directory (with a few exceptions) and pass it to the compiler.

# The Problem

This is bad for a couple of different reasons:

1. Considering we have many public headers with generic/generic-ish names (I compiled a list of some of them before I left for the funeral, but I seem to have misplaced it), this can cause problems when building against irods from a project that has, uses, or depends on another project that has or uses an include file with the same filename.
2. It loses the organization from the repository directory structure.

# Solutions

There are a couple of ways we could solve this.

## Option 1: The Easy Solution

Simply ensure that no public headers have generic filenames.

## Option 2: The Other One

Reorganize the directory structure of the project and of the installed public headers.

I'm in favor of this option. I feel like having better organized public headers would benefit us in the long run.

### How This Might Look

The new directory structure of the project might follow this pattern that looks like this:
```
|-- cmake
|-- configuration_schemas
|-- doxygen
|-- includes
|   `-- irods
|       |-- lib
|       |   |-- api
|       |   |   `-- public headers
|       |   |-- core
|       |   *   `-- public headers
|       |-- pugins
|       |   |-- api
|       |   |   `-- public headers
|       |   |-- database
|       |   *   `-- public headers
|       |-- server
|       |   |-- api
|       |   |   `-- public headers
|       |   |-- core
|       |   *   `-- public headers
|-- irods_schema_messaging
|-- lib
|   |-- api
|   |   |-- source code
|   |   `-- private headers
|   |-- core
|   *   |-- source code
|       `-- private headers
|-- packaging
|-- plugins
|   |-- api
|   *   |-- source code
|       `-- private headers
|-- scripts
|-- server
*   |-- api
    |   |-- source code
    |   `-- private headers
    |-- auth
    |   `-- source code
    |-- core
    *   |-- source code
        `-- private headers
```

The `include/irods` directory would be installed as `${CMAKE_INSTALL_INCLUDEDIR}/irods`, and only `${CMAKE_INSTALL_INCLUDEDIR}` would be passed to the compiler as a toplevel include directory.

The include directives for public headers would look like this:
```c++
#include <irods/lib/core/irods_tcp_object.hpp>
#include <irods/server/core/irods_logger.hpp>
```

The CMake `target_include_directories` calls would look like this:
```cmake
target_include_directories(
  tgtname
  PUBLIC
  "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>"
  "$<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}/include>"
  "$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>"
)
```

My understanding is that this will also make it a lot easier to build against an iRODS build that has not been installed.

**Comment by trel** [comment]
I recommend 4.3.0 as milestone - potentially too disruptive on a stable branch.
