### ISSUE TITLE
Add full utf8 support to mysql

### ISSUE THREAD

**Issue by peterverraedt** [irods/irods#5715]
## Feature

- Add full support for utf8 encoding of mysql database, by changing the database scheme slightly.

## Current problems

- When setting the database charset to utf8mb4, irods will fail to set up properly because the odbc configuration is not set up for utf-8.
- Even if the above is fixed, database creation will fail because table column sizes or index sizes are exceeding the maximum supported values.

## Fixes to implement

We do, after a clean installation of irods, the following fixes that create full support for mysql with a utf8 charset. Some indexes are changed from layout, but that should be ok in light of the list of all indices.

```bash
# Fix mysql indices to use with utf8 encoding
SQL=/var/lib/irods/packaging/sql/icatSysTables.sql

# remove coll_name from index and don't create a unique index
sed -i '/idx_coll_main2/d' $SQL
echo "create index idx_coll_main2 on R_COLL_MAIN (parent_coll_name (767));" >> $SQL

sed -i '/idx_data_main2/d' $SQL
echo "create unique index idx_data_main2 on R_DATA_MAIN (coll_id,data_name (515),data_repl_num,data_version);" >> $SQL

sed -i '/idx_data_main4/d' $SQL
echo "create index idx_data_main4 on R_DATA_MAIN (data_name (515));" >> $SQL

sed -i '/idx_grid_configuration/d' $SQL
echo "create unique index idx_grid_configuration on R_GRID_CONFIGURATION (namespace (383), option_name (383));" >> $SQL

# Replace varchar(2700) by TEXT in R_RULE_MAIN
sed -i '8s/varchar(2700)/TEXT/g' $SQL

# Set Charset=UTF8 in /var/lib/irods/.odbc.ini
sed -i "s/'FOUND_ROWS': '1',/'FOUND_ROWS': '1', 'Charset': 'UTF8',/" /var/lib/irods/scripts/irods/database_connect.py
```

It i an easy exercise to adapt the corresponding source files.

**Comment by korydraughn** [comment]
This is great! We'll need to test all the things to make sure there aren't any regressions or behavior issues.

Are there any drawbacks/concerns around these changes?

**Comment by peterverraedt** [comment]
Unicity of file names (data_name) is only checked for the first 515 characters now, instead of the current 767, but that is the only real change in indexing behaviour. 

For R_COLL_MAIN, the indices
```
create unique index idx_coll_main3 on R_COLL_MAIN (coll_name);
create unique index idx_coll_main2 on R_COLL_MAIN (parent_coll_name,coll_name);
```
are changed to
```
create unique index idx_coll_main3 on R_COLL_MAIN (coll_name);
create index idx_coll_main2 on R_COLL_MAIN (parent_coll_name);
```
as the uniqueness of the (coll_name, parent_coll_name) pair is obviously implied by the uniqueness of coll_name only. This saves us from restricting coll_names to 383 characters and keeps the current limit of 767 there.

Please do test, but the only thing I noticed was that filenames like `ċ.file` are now supported and not before :-).

Adding the Charset=UTF8 does not impact anything if the mysql database has another charset (e.g. latin1), as long as only ASCII-data is inserted to irods, but I guess that mimicks the earlier behaviour (it works for ASCII but not for non-ASCII).
