### ISSUE TITLE
failed to start irods server after compiled 

### ISSUE THREAD

**Issue by peggy0135** [irods/irods#5718]
after I followed the guide in "https://docs.irods.org/4.2.9/getting_started/installation/#catalog-service-provider" and compiled the source code on centos8. It didn't show any error messages or something failed, except some dependency problem (fixed by myself, I think).

when I tried to start the irods server by "python setup_irods.py", it failed.
Then I checked the log,
it just showed as below.
"""
2021-06-25 07:21:59,046 -   ERROR -               irods_control.py: 127 - Error encountered running irods_control start:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods_control.py", line 124, in main
    operations_dict[operation]()
  File "/var/lib/irods/scripts/irods_control.py", line 70, in <lambda>
    operations_dict['start'] = lambda: irods_controller.start()
  File "/var/lib/irods/scripts/irods/controller.py", line 123, in start
    six.reraise(IrodsError, e, sys.exc_info()[2])
  File "/var/lib/irods/scripts/irods/controller.py", line 98, in start
    env=self.config.execution_environment)
  File "/var/lib/irods/scripts/irods/lib.py", line 134, in execute_command
    check_command_return(args, out, err, returncode, **kwargs)
  File "/var/lib/irods/scripts/irods/lib.py", line 117, in check_command_return
    indent(err))]))
IrodsError: Call to open process with ['/usr/sbin/irodsServer'] returned an error:
  Options passed to Popen:
    cwd: /usr/sbin
    env: HIDDEN
  Return code: 127
  Standard output:
    
  Error output:
    /usr/sbin/irodsServer: error while loading shared libraries: libavrocpp.so.1.9.0.0: cannot open shared object file: No such file or directory
2021-06-25 07:21:59,047 -    INFO -               irods_control.py: 128 - Exiting...
"""
even I tried to "ldconfig", it is still not working.

Is there anything detailed, that I missed? what should I do with it?
Thank you

**Comment by alanking** [comment]
Do you have the iRODS external package `avro1.9.0-0` installed and located in `/opt/irods-externals`? The reason it did not resolve for Centos 8 is probably because we have not released packages for that platform. As for Centos 7, we have released packages for 4.2.9 (including externals).

> It didn't show any error messages or something failed, except some dependency problem (fixed by myself, I think).

I feel that the above line may hold the answer. I'm not sure how you were able to build the software without this dependency installed as it is a linked dependency. Can you please describe what you did in more detail at this stage?

**Comment by peggy0135** [comment]
sorry I am curious that it's bind with the path("/opt/irods-externals")?
because that in doc the path is under "/tmp".
about the avro1.9.0-0, should I install with the rpm file which was built ?
Thank you

**Comment by alanking** [comment]
The instructions for building on that page are for building a "non-package install", which means that you can run the server application out of a directory.

Based on the error message in the original post, it looks like you are attempting to run a packaged installation. The externals path is configured via a CMake variable: `-DIRODS_EXTERNALS_PACKAGE_ROOT`. What did you use for this when building? If none is provided, the default is in `/opt/irods-externals`, I think.

**Comment by peggy0135** [comment]
yes, I did provide the path "IRODS_EXTERNALS=/root/externals".
I tried to install the rpm file "irods-externals-avro1.9.0-0-1.0-1.x86_64.rpm" with rpm local install.
But the process of "setup_irods.py" showed as below:
----------------------------------------------------------------------------------------------------------------------------------------------
/usr/sbin/irodsServer: error while loading shared libraries: libavrocpp.so.1.9.0.0: cannot open shared object file: No such file or directory
2021-06-29 00:09:35,778 -    INFO -                  controller.py: 122 - Failure
2021-06-29 00:09:35,778 -   ERROR -               irods_control.py: 127 - Error encountered running irods_control start:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods_control.py", line 124, in main
    operations_dict[operation]()
  File "/var/lib/irods/scripts/irods_control.py", line 70, in <lambda>
    operations_dict['start'] = lambda: irods_controller.start()
  File "/var/lib/irods/scripts/irods/controller.py", line 123, in start
    six.reraise(IrodsError, e, sys.exc_info()[2])
  File "/var/lib/irods/scripts/irods/controller.py", line 98, in start
    env=self.config.execution_environment)
  File "/var/lib/irods/scripts/irods/lib.py", line 134, in execute_command
    check_command_return(args, out, err, returncode, **kwargs)
  File "/var/lib/irods/scripts/irods/lib.py", line 117, in check_command_return
    indent(err))]))
IrodsError: Call to open process with ['/usr/sbin/irodsServer'] returned an error:
  Options passed to Popen:
    cwd: /usr/sbin
    env: HIDDEN
  Return code: 127
  Standard output:
    
  Error output:
    /usr/sbin/irodsServer: error while loading shared libraries: libavrocpp.so.1.9.0.0: cannot open shared object file: No such file or directory
2021-06-29 00:09:35,778 -    INFO -               irods_control.py: 128 - Exiting...
----------------------------------------------------------------------------------------------------------------------------------------------

and the Validation progress showed:
----------------------------------------------------------------------------------------------------------------------------------------------
WARNING: Validation failed for /var/lib/irods/.irods/irods_environment.json -- jsonschema not installed
Warning encountered in json_validation for /var/lib/irods/.irods/irods_environment.json, skipping validation...
WARNING: Validation failed for /var/lib/irods/VERSION.json -- jsonschema not installed
Warning encountered in json_validation for /var/lib/irods/VERSION.json, skipping validation...
WARNING: Validation failed for /etc/irods/server_config.json -- jsonschema not installed
Warning encountered in json_validation for /etc/irods/server_config.json, skipping validation...
WARNING: Validation failed for /etc/irods/host_access_control_config.json -- jsonschema not installed
Warning encountered in json_validation for /etc/irods/host_access_control_config.json, skipping validation...
WARNING: Validation failed for /etc/irods/hosts_config.json -- jsonschema not installed
Warning encountered in json_validation for /etc/irods/hosts_config.json, skipping validation...
Warning encountered in validation:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/controller.py", line 43, in start
    self.config.validate_configuration()
  File "/var/lib/irods/scripts/irods/configuration.py", line 284, in validate_configuration
    lib.indent(*skipped)))
IrodsWarning: Skipped validation for the following files:
  /var/lib/irods/.irods/irods_environment.json
  /var/lib/irods/VERSION.json
  /etc/irods/server_config.json
  /etc/irods/host_access_control_config.json
  /etc/irods/hosts_config.json
----------------------------------------------------------------------------------------------------------------------------------------------
Thank you

**Comment by peggy0135** [comment]
also I try to add the path of  libavrocpp.so.1.9.0.0 ("/root/externals/avro1.9.0-0/lib") in "/etc/ld.so.conf" and ldconfig after edited.
but it still not work.

**Comment by peggy0135** [comment]
steps I did:
1. got into /root/externals
2. ./install_prerequisites.py, but failed with rvm, ruby, fpm,gem
3. make
4. export PATH=$IRODS_EXTERNALS/cmake3.11._____:$PATH
5. export IRODS_INSTALL_DIR=/
6. mkdir build
7. cd build
8. cmake -DCMAKE_INSTALL_PREFIX=$IRODS_INSTALL_DIR -DIRODS_EXTERNALS_PACKAGE_ROOT=$IRODS_EXTERNALS ../
9. make non-package-install-postgres, but fail with some of the .so files. so I went to the path and "make" manually
10. got the "irods_client_icommands" from github, mkdir build, cd build
11. cmake -DCMAKE_INSTALL_PREFIX=$IRODS_INSTALL_DIR -DIRODS_DIR=$IRODS_INSTALL_DIR/usr/lib/irods/cmake ../
12. make install
13. export LD_LIBRARY_PATH=$IRODS_INSTALL_DIR/usr/lib
14. export PATH=$IRODS_INSTALL_DIR/usr/bin:$IRODS_INSTALL_DIR/usr/sbin:$PATH
15. after the setup_irods.py the irods server still fail to start to restart
Is there anything I missed or misunderstand??
Thank you

**Comment by peggy0135** [comment]
it works when I changed the "irods-externals" out of "/root"
I am not sure it is correct. So I will observe the server for several days and try on centos8
.

**Comment by korydraughn** [comment]
> 2. ./install_prerequisites.py, but failed with rvm, ruby, fpm,gem

For step 2, you should use these changes for irods/externals: https://github.com/irods/externals/pull/123/files

**Comment by peggy0135** [comment]
currently, it looks fine on centos7 and centos8
But about the part of the validation, is that alright with the warning, or is there anything I missed?

**Comment by alanking** [comment]
If things are working fine that warning is probably okay. The warning messages are saying that `jsonschema` python package needs to be installed, so the warning should go away once that is installed.

**Comment by trel** [comment]
Closing - no action necessary.
