### ISSUE TITLE
Recursive irepl silences failures

### ISSUE THREAD

**Issue by alanking** [irods/irods#5726]
### iRODS Version, OS and Version
4.2.8 (earlier?)

### What did you try to do?
`irepl -r` on a collection which would result in failure.

### Expected behavior
Not sure!

When running `irepl` with the recursive flag on a collection, any errors encountered are kept quiet. This has been the case as early as 4.2.8, but possibly earlier. Is this the expected behavior? If not, should the user expect a message for every encountered error (up to the size limit of the rError stack)?

### Observed behavior (including steps to reproduce, if applicable)
```
$ ils -l .
/tempZone/home/rods:
  rods              0 demoResc          283 2021-06-25.15:08 & foo
$ irepl -r -S another -R another .
$ echo $?
0
$ ils -l .
/tempZone/home/rods:
  rods              0 demoResc          283 2021-06-25.15:08 & foo
```
There is no replica on resource `another`, so the replication fails. However, no error message is printed and the return code is 0.

**Comment by trel** [comment]
Alternatively, there was no work to be done, so it successfully replicated all the found/zero replicas on `another`...

**Comment by alanking** [comment]
This would normally result in an error without the `-r`:
```bash
$ ils -l .
/tempZone/home/rods:
  rods              0 demoResc          283 2021-09-13.16:37 & foo
$ irepl -r -S another -R another .
$ echo $?
0
$ irepl -S another -R another foo
remote addresses: 192.168.48.3 ERROR: replUtil: repl error for /tempZone/home/rods/foo, status = -168000 status = -168000 SYS_REPLICA_INACCESSIBLE
Level 0: SYS_REPLICA_INACCESSIBLE: hierarchy descending from specified source resource name [another] does not have a replica or the replica is inaccessible at this time


$ echo $?
3
```

**Comment by alanking** [comment]
For posterity, the recursive flag no longer silences error messages. Still leaving this open for discussion.

**Comment by trel** [comment]
This changed in... 4.2.9?

**Comment by alanking** [comment]
Yes, I believe the behavior changed in 4.2.9.

**Comment by alanking** [comment]
I am of the opinion that this should be closed as resolved/invalid. Thoughts?

**Comment by trel** [comment]
Yes, this seems done.   Initial request for less silence has been fulfilled.   Any new issues can be opened against a newer version of iRODS.
