### ISSUE TITLE
Replacement for NEWLY_CREATED_COPY #define removed in 4.2.9

### ISSUE THREAD

**Issue by kjsanger** [irods/irods#5730]
### iRODS Version, OS and Version

4.2.9, Linux

### What did you try to do?

Compile a C client against iRODS 4.2.8 and 4.2.9

### Expected behavior

Compile cleanly for both versions

### Observed behavior (including steps to reproduce, if applicable)

Fails to compile on 4.2.9 because #define `NEWLY_CREATED_COPY` has been removed
from `lib/core/include/objInfo.h`

What's the best way now to GenQuery select the latest replicate from C?

e.g. https://github.com/wtsi-npg/baton/blob/ac3d2e7c461dd53dc6a541ec87de7a41aaa715d8/src/query.c#L366-L378

Thanks.

**Comment by alanking** [comment]
`NEWLY_CREATED_COPY` was the replica status of value 1. This value is now known as `GOOD_REPLICA`. Using this macro name will allow the client to compile.

Short answer to the query question: it depends on what is meant by "latest"
 - The most-recently-touched replica
 - The most-recently-created replica
 - The replica at the top of the returned list when selecting marked-good replicas
 - Something else?

I wanted to expand on this a little bit here here... Up until 4.2.8, an `&` could indicate a newly created (in-flight!) replica *or* an at-rest, "good" replica. From 4.2.9 onward, the `&` only indicates an at-rest, "good" replica, but a `?` indicates a newly created replica whose data are still in flight.

So, if the query is expecting both types of replica (as `NEWLY_CREATED_COPY` conflates the definitions from the catalog's standpoint), there will need to be an additional `WHERE` clause which allows for replicas with status `INTERMEDIATE_REPLICA`.

**Comment by kjsanger** [comment]
Thanks for the quick reply - I'm interested only in `GOOD_REPLICA` and I can confirm that resolves the compile error. Please feel free to close.
