### ISSUE TITLE
4.2.9 C API includes C++ headers

### ISSUE THREAD

**Issue by kjsanger** [irods/irods#5731]
- [x] master
- [x] 4-2-stable
-------

### iRODS Version, OS and Version

4.2.9

### What did you try to do?

Compile a C client against 4.2.9

### Expected behavior

Compile cleanly

### Observed behavior (including steps to reproduce, if applicable)

Seems to be including C++-specific headers:

```
ERROR:root:In file included from write.c:22:
ERROR:root:/opt/conda/conda-bld/baton-pkg_1625581138871/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/irods/checksum.hpp:8:10: fatal error: cstdio: No such file or directory
ERROR:root:    8 | #include <cstdio>
ERROR:root:      |          ^~~~~~~~
ERROR:root:compilation terminated.
ERROR:root:make[2]: *** [Makefile:676: write.lo] Error 1
ERROR:root:make[1]: *** [Makefile:479: all-recursive] Error 1
ERROR:root:make: *** [Makefile:388: all] Error 2
```

**Comment by trel** [comment]
Three things...

1) You can work around this in the near term with a forward declaration of `chksumLocFile`, same as...

https://github.com/irods/irods/blob/32cc2bd18e43aaaa42f002d07996343a05066646/lib/hasher/include/checksum.hpp#L24

You began linking against it here (~4 months ago):
https://github.com/wtsi-npg/baton/commit/86ab02720c02997f709ebaaec8d8a4bc25262c53#diff-ac2b16ad23e0d1236267855db34c222593e541b67af86077f29cc7d4809539daR74

2) We will rename checksum.hpp to be checksum.h (by moving its C++ includes into checksum.cpp)

3) We will include checksum.h in https://github.com/irods/irods/blob/4-2-stable/test/c_api_test/test.c
