### ISSUE TITLE
Packaging: Conflicting packages should be marked as such so that package managers do the right thing

### ISSUE THREAD

**Issue by bh9** [irods/irods#5748]
- [ ] master
- [ ] 4-2-stable
---------

## Feature
irods-database-plugin-oracle and irods-database-plugin-postgres conflict, so they should be marked as conflicts in the packages. Attempting to install a suitably marked package while something it conflicts with will, by default, result in the conflict being dealt with by the package manager choosing the one being installed over the one on the system
Currently, attempting to install irods-database-plugin-postgres over irods-database-plugin-oracle results in a dpkg error when trying to overwrite `/var/lib/irods/packaging/sql/icatDropSysTables.sql`

**Comment by trel** [comment]
need to confirm the mysql package does the same - they should each three declare conflicts with the other two.

**Comment by bh9** [comment]
I can confirm that the mysql package also conflicts on that file, and that none of the 3 packages have Conflicts declared

**Comment by trel** [comment]
Got it, thanks.

Each of the three packages should add four lines (two DEBIAN and two RPM).

https://cmake.org/cmake/help/v3.11/module/CPackDeb.html?highlight=conflicts#variable:CPACK_DEBIAN_PACKAGE_CONFLICTS
and
https://cmake.org/cmake/help/v3.11/module/CPackRPM.html#variable:CPACK_RPM_PACKAGE_CONFLICTS

**Comment by kript** [comment]
A perhaps heretical opinion - why should they conflict at all? Each one could use its own uniquely named SQL file etc al.

If we were able to have both installed, our migration from Oracle to PostgreSQL would be a matter of changing the server_config.json, rather than removing one package and installing another, for example.

**Comment by trel** [comment]
That could also work... want to make sure we don’t end up with multiple sources of truth though.

**Comment by trel** [comment]
Also will note this is a new use case - to help support migration of one database flavor to another.

**Comment by SwooshyCueb** [comment]
I'm going to extend the scope of this issue to include removing development-only dependencies from non-development packages. We've got a couple of header-only package dependencies where they don't need to be and as part of this I'd like to make a consistency sweep for that.

**Comment by trel** [comment]
hmm, perhaps that's... different enough from the conflicting files issue?       yes, they're both packaging...

thoughts on milestone, @SwooshyCueb ?

**Comment by SwooshyCueb** [comment]
That's fair.

I don't think this is a destructive change, and it seems trivial, so I'm thinking 4.2.11

**Comment by trel** [comment]
Very good.

I see the new issue for development / non-development separation is https://github.com/irods/irods/issues/5758

So this issue is now just about the conflicting files.  Excellent.

**Comment by SwooshyCueb** [comment]
Upon further investigation, changing the packages to be side-by-side installable would be enough of a change that I don't think it makes sense to do in stable. I'm going to open a new issue to make them side-by-side installable in 4.3
