### ISSUE TITLE
Installation documentation lacks information

### ISSUE THREAD

**Issue by CvR42** [irods/irods#5757]
### iRODS Version, OS and Version

4.2.10

### What did you try to do?

Install iRODS

### Expected behavior

Produce a working iRODS installation

### Observed behavior (including steps to reproduce, if applicable)

Examples in the documentation fail, I don't learn how to get a working iRODS installation.

Following the instructions in https://docs.irods.org/4.2.10/getting_started/installation/ and reaching the 'iRODS Setup' section, and particularly while running `python /var/lib/irods/scripts/setup_irods.py`, the reader (well, ok, this reader) is left with a number of unanswered questions:

1. Exactly what is the purpose of the 'Service Account', and what is the difference with the 'iRODS Administrator'?
2. Is there a reason in one place the phrase 'Account Name' is used, and in the other the word 'Username'. Just inconsistent terminology or is the difference important in some way?
3. What should be done with the different keys and salts that are asked? I'm assuming keys should be kept but kept secret, whereas the salt is just a random string I can forget immediately after. (And why not just generate it on the spot then without even asking?)
4. After the `setup_irods.py` script has completed what should be done next? The documentation shows running `ienv`, but if I do that I get a complaint about a missing `irods_environment.json` file. I'm guessing I should do an `iinit` first, but what user name should I use for that? Service Account? iRODS Administrator? Something else? And what is the password?

At this point the installation process has derailed completely, and I have no idea how to proceed except trying to find alternative documentation.

**Comment by trel** [comment]
Thanks for the feedback - sorry for the confusion.  We can definitely add a link to the Beginner Training that spells a bit more of this out in detail.

https://github.com/irods/irods_training/blob/master/beginner/irods_beginner_training_2019.pdf

iRODS runs as a service on a machine, and needs a unix/linux account to do that.

The iRODS administrator account lives in the database and has control over the logical zone.

The keys and salts are secrets, and need to be consistent across machines for them to securely communicate with one another within the same zone.

Once you complete setup, the service account has a configured administrative user and is already 'logged in'.  You would switch to that service account (usually with `sudo su - irods`) and then `ienv` and `ils` will show the expected already-logged-in output.
