### ISSUE TITLE
icommands have a hidden dependency on irods-server package

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#5776]
- [x] master
- [x] 4-2-stable
---
### What did you try to do?
I ran `itouch` in a docker container that only has the icommands installed.

### Expected behavior
I expected the icommand to execute without any issues.

### Observed behavior (including steps to reproduce, if applicable)
I got the following message: 
```bash
remote addresses: 127.0.0.1 ERROR: procApiRequest: apiTableLookup of apiNumber 20007 failed
```
This happened because the API plugins are not installed. The API plugins are provided by the `irods-server` package. Installing them fixes the issue.

## The Question
Should the icommands have a dependency on the irods-server package or should the API plugins be moved into another package (e.g. irods-runtime)?

**Comment by trel** [comment]
definitely seems like they should just be in `irods-runtime` instead...  we have other precedent for this?

**Comment by korydraughn** [comment]
I'm not sure. I know that the API plugins provide client-side and server-side shared libraries so it does seem that putting them in `irods-runtime` makes the most sense.

**Comment by trel** [comment]
let's do that.

**Comment by d-w-moore** [comment]
I'll retry this on this tip of 4-2-stable then.  But in my case the irods-server package was installed, so not sure if this is the same issue.
