### ISSUE TITLE
upgrade from iRODS 4.1.11 to 4.2.8 and then 4.2.10 leaves you with two versions of irods-externals-nanodbc2

### ISSUE THREAD

**Issue by cookie33** [irods/irods#5779]
### iRODS Version, OS and Version

irods 4.2.10

### What did you try to do?

upgrade from iRODS 4.1.11 to 4.2.8
upgrade from iRODS 4.2.8 to 4.2.10

### Expected behavior

a single package of irods-externals-nanodbc2

### Observed behavior (including steps to reproduce, if applicable)

Now we have two packages installed right next to each other:
```
# rpm -qa | grep irods | sort
irods-database-plugin-postgres-4.2.10-1.x86_64
irods-devel-4.2.10-1.x86_64
...
irods-externals-avro1.9.0-0-1.0-1.x86_64
irods-externals-boost1.67.0-0-1.0-1.x86_64
irods-externals-catch22.3.0-0-1.0-1.x86_64
irods-externals-clang-runtime6.0-0-1.0-1.x86_64
irods-externals-fmt6.1.2-1-1.0-1.x86_64
irods-externals-json3.7.3-0-1.0-1.x86_64
irods-externals-libarchive3.3.2-1-1.0-1.x86_64
irods-externals-nanodbc2.13.0-0-1.0-1.x86_64
irods-externals-nanodbc2.13.0-1-1.0-1.x86_64
...
irods-icommands-4.2.10-1.x86_64
irods-runtime-4.2.10-1.x86_64
irods-server-4.2.10-1.x86_64
...
```

The packages are:
```
irods-externals-nanodbc2.13.0-0-1.0-1.x86_64
irods-externals-nanodbc2.13.0-1-1.0-1.x86_64
```

Should this be possible?

And the packages contain:
```
# rpm -ql irods-externals-nanodbc2.13.0-0-1.0-1.x86_64
/opt/irods-externals/nanodbc2.13.0-0/include/nanodbc/nanodbc.h
/opt/irods-externals/nanodbc2.13.0-0/lib/libnanodbc.so
/opt/irods-externals/nanodbc2.13.0-0/lib/libnanodbc.so.2.13.0

# rpm -ql irods-externals-nanodbc2.13.0-1-1.0-1.x86_64
/opt/irods-externals/nanodbc2.13.0-1/include/nanodbc/nanodbc.h
/opt/irods-externals/nanodbc2.13.0-1/lib/cmake/nanodbc/nanodbc-config-noconfig.cmake
/opt/irods-externals/nanodbc2.13.0-1/lib/cmake/nanodbc/nanodbc-config.cmake
/opt/irods-externals/nanodbc2.13.0-1/lib/libnanodbc.so
/opt/irods-externals/nanodbc2.13.0-1/lib/libnanodbc.so.2.13.0
```

**Comment by cookie33** [comment]
As a side note.
When going from iRODS 4.1.11 to 4.2.10 in one go you end up with one single package:
```
irods-externals-nanodbc2.13.0-1-1.0-1.x86_64
```
But it is still possible to install the old version next to it.

**Comment by trel** [comment]
This is by design - we want externals packages to be independently installable.

We repackaged the same nanodbc2.13.0 more correctly (giving the `1-1` versioning).

You can simply remove the unused-by-iRODS-4.2.10 `irods-externals-nanodbc2.13.0-0-1.0-1.x86_64` package.

**Comment by SwooshyCueb** [comment]
A quick note on this:

Package managers worth their salt will mark nanodbc as automatically installed as a dependency. Once they are no longer required (i.e. once all packages depending on it are no longer installed) the package manager will recognize that it is automatically removable, and the administrator can remove it when doing housekeeping. In particular, apt will even tell you what packages can be automatically removed whenever you install anything via apt-get.
