### ISSUE TITLE
Add settings refresher to main server

### ISSUE THREAD

**Issue by trel** [irods/irods#5816]
- [x] main
- [x] 4-3-stable
---
## Feature

From https://github.com/irods/irods/issues/4977#issuecomment-866237596

Some settings require a server restart to apply.

If the facility exists as a thread in the main server process, it could update the settings in the main server process. If the facility exists as a forked process, it might be a bit harder to implement this.

new advanced setting to determine how often to run... default... 600 seconds?

**Comment by alanking** [comment]
@epsilon-phase - Please cherry-pick to 4-3-stable. Thanks!
