### ISSUE TITLE
Add facility for manually refreshing server_config in running irodsServer

### ISSUE THREAD

**Issue by alanking** [irods/irods#5821]
## Feature

Similar to `apachectl --graceful`, it would be nice to have a way to reload the server config in memory for a running `irodsServer` (grandpa) without restarting the process (and subsequently its children).

Most applications/services respond to `SIGHUP`. The original `irodsServer` could be targeted with this signal which is then forwarded to the agent factory (and the delay server?) so that future agents will have the updated configuration.

**Comment by trel** [comment]
The server already handles `SIGHUP`, but just exits...

https://github.com/irods/irods/blob/fa596d4aba8ca0b18db8089de332e41a9946a641/server/core/src/rodsServer.cpp#L396

**Comment by kript** [comment]
In 4.1.x, couldn't we just 'touch' `core. re` and it would reload? Or am I confusing this with the config re-read now done by each agent on start? I guess I am saying I expected that behaviour to persist in 4.2.x - does it not?

**Comment by trel** [comment]
You are correct - and yes, it still works that way.   But only for the settings that are read by each new Agent.

There are a few settings that the AgentFactory itself (or perhaps the delay server) read earlier and it's 'too late'.

This SIGHUP response/reload would allow the main server to be refreshed without a restart (which today requires killing/bouncing the server or gracefully waiting for all open connections to close on their own).

An additional bonus of this is that containers running iRODS could use the main server as their `ENTRYPOINT`, which makes docker-compose projects much cleaner to build and maintain.

this is also related to yesterday's https://github.com/irods/irods/issues/5816

closing this issue would also fix https://github.com/irods/irods/issues/5290

**Comment by kript** [comment]
> You are correct - and yes, it still works that way. But only for the settings that are read by each new Agent.
> 
> There are a few settings that the AgentFactory itself (or perhaps the delay server) read earlier and it's 'too late'.

Can you elaborate (apart from the SSL one)? I'm thinking user/group (and perhaps..databases, but surely that's a step too far!)?

> An additional bonus of this is that containers running iRODS could use the main server as their `ENTRYPOINT`, which makes docker-compose projects much cleaner to build and maintain.
> 

:heart:  As I've had to fettle with containerised iRODS recently I definitely approve of this plan :+1:

**Comment by trel** [comment]
Yes, enumerating which ones 'matter' in this regard has been a long-standing... opportunity.

**Comment by korydraughn** [comment]
This seems like it can be closed now that #6456 has been merged.

**Comment by trel** [comment]
I think that is correct - will be in 4.3.1.
