### ISSUE TITLE
Investigate delay server order of operations for executing rules

### ISSUE THREAD

**Issue by alanking** [irods/irods#5822]
- [x] master
- [x] 4-2-stable
---
As of iRODS 4.2.5, the delay server adopted a single-producer-multi-consumer model for processing delayed rules. A single thread queried the catalog for all of the information from `R_RULE_EXEC` and placed the context in an in-memory queue. The consumers would pull things from the in-memory queue and execute the rule directly based on what was pulled from the catalog.

As of iRODS 4.2.9, the delay server changed the model for processing delayed rules such that the in-memory delay queue holds only the IDs for the delayed rules which are ready to be executed. The consumers pull these IDs from the in-memory queue and query the catalog for the information in `R_RULE_EXEC` based on the rule ID that it fetched.

The new approach reduces the amount of memory that the delay queue is using, but increases the amount of time is spent querying for information from the catalog. In other words, each consumer is responsible for fetching and storing its own context which increases the number of queries by N. In the old approach, a single query would have fetched this information from the catalog, and this query is already necessary in order to populate the in-memory delay queue with the rule IDs which are ready to be executed.

We should investigate whether the number of queries is causing a significant impact on performance for processing large numbers of delayed rules. This is a time vs. space trade-off, as per usual.

**Comment by trel** [comment]
Also consider how this plays in 4-2-stable vs master...

master has recently introduced 'implicit remote()' #4429 to have the running of the delay rules be shared across a subset of the iRODS servers in the Zone.

**Comment by trel** [comment]
additional investigation... consider a new server_config.json value to control the number of delay rules to 'hold' in the delay server's in-memory queue.

Alternatively, this should be defined as `maximum_size_of_delay_queue_in_bytes` to be more kind/relevant to the system administrator.  A default of `0`, meaning no limit defined. Provide documentation for helping calculate 'good' numbers for this for sysadmins.

**Comment by trel** [comment]
checkboxed.
