### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by joergsteinkamp** [irods/irods#5825]
## Feature

Since Python 2 allready reached its End-Of-Life a while ago, distributors start removing it from their distribution. There is still a minimal version of python 2.7 shipped with the current stable Debian/Ubuntu. However, without required packages. Due to security reasons, we would like to keep our systems as up to date as possible.

### iRODS Version, OS and Version

iRODS 4.2.10 on Debian 11 (bullseye)

### What did you try to do?

I was able to compile all iRODS packages (with minor code changes). But could not install and run it due to out-dated OS-dependencies. The Debian/Ubuntu packages

- python-requests
- python-psutils

do not exsist any more in the distribution repository and they are required by iRODS.

This was also partly requested here: [https://github.com/irods/irods/issues/5174](https://github.com/irods/irods/issues/5174)

Thanks & kind regards
Jörg

**Comment by trel** [comment]
Yes, we are targeting 'native/packaged' Python3 support for 4.3.0 (working to get it ready/out ASAP).

This clean break will allow us to support a number of OS distributions that now ship with Python3 by default.  We'll update the dependencies in the master branch.

**Comment by korydraughn** [comment]
Related to #6069

**Comment by korydraughn** [comment]
Handled by #6069
