### ISSUE TITLE
Add configurable hostnames option to run_tests.py

### ISSUE THREAD

**Issue by alanking** [irods/irods#5842]
- [x] master
- [x] 4-2-stable
---
## Feature

Topology tests being run via `scripts/run_tests.py` are assuming the following hostnames for participating host machines: https://github.com/irods/irods/blob/7ae077171bd842dd091d472bf1734562c2cdf7a1/scripts/run_tests.py#L49-L55

There should be a configuration option which allows the user to map hostnames to the usual machines in topology tests. I propose something like the following:
```
--hostnames-for-topology ICAT_HOSTNAME HOSTNAME_1 HOSTNAME_2 HOSTNAME_3
```
where `ICAT_HOSTNAME` corresponds to `irods.test.settings.ICAT_HOSTNAME` and `HOSTNAME_<N>` corresponds to `irods.test.settings.HOSTNAME_<N>`.

Should no `--hostnames-for-topology` be specified, the historical hostnames will be used (`icat.example.org`, `resource<N>.example.org`). Additionally, the option will be ignored if `--topology_test` option is not present.

**Comment by trel** [comment]
`ICAT` should be the database (hostname)... and we should move to provider/consumer naming...  maybe that should be a separate issue from this one...

**Comment by trel** [comment]
do we need to be more explicit about the roles... rather than just positional.   i.e. b/c we want to test with two providers in HA...

**Comment by alanking** [comment]
If we want to run tests outside of the historical configurations ("core" tests, "unit" tests, topology, federation) I think we should consider writing a new script for running tests and possibly even building up a new, separate set of test suites for different configurations.

I thought about adding an option for each "role" in the topology configuration since we can't really change the configuration without a massive overhaul of many of the tests (`test_resource_types` in particular expects exactly 1 CSP and exactly 3 CSCs). Would that be preferable?

That being said, I think we should maintain the older naming conventions by default in case we need to use some older infrastructure for running tests (i.e. CI) which operates on certain assumptions baked into the tests. Willing to be convinced.

**Comment by alanking** [comment]
Speaking of federation, there should probably be an option for the otherZone CSP hostname.

**Comment by alanking** [comment]
Should I leave this open for federation hostname options, or just close this as is?

**Comment by trel** [comment]
let's get this one closed, and open a new issue for federation hostname planning/options.

**Comment by alanking** [comment]
Created #5856 for the federation work. Closing
