### ISSUE TITLE
ichksum --verify exits with code 0 when physical size does not match size in catalog

### ISSUE THREAD

**Issue by kjsanger** [irods/irods#5843]
- [x] master
- [x] 4-2-stable
---------

### iRODS Version, OS and Version

iRODS 4.2.10, Ubuntu bionic

### What did you try to do?

Ran `ichksum --verify` on a data object where I had simulated on-disk corruption by modifying one of the two replicas in the vault.

### Expected behavior

`ichksum` to identify the difference in file size and exit non-zero, with any error message going to STDERR.

### Observed behavior (including steps to reproduce, if applicable)

`ichksum` identified the difference in file size, printed the error message to STDOUT, rather than STDERR and exited with code 0.

```
$ ichksum --verify README.md
Level 0: ERROR: Physical size does not match size in catalog for replica [1].
Level 1: WARNING: No checksum available for replica [0].
Level 2: WARNING: No checksum available for replica [1].
(partisan) keith@tao:~/dev/work/python/partisan$ echo $?
0
```

**Comment by kjsanger** [comment]
Here's a case where I'm poking a different code path where the "corrupt" file is the correct length and both replicates have checksums:

```
$ ichksum --verify /testZone/home/irods/READ_THEN_DESTROYME.md
Level 0: verifyDataObjChksum: computed checksum [d44c4851bbeeaae0c45e6155c114b9c6] != catalog value [60509d877b79b3437a5c63533da4bdb1] for [/testZone/home/irods/READ_THEN_DESTROYME.md] hierarchy [replResc;unixfs1] replica number [1]
Level 1: ERROR: Computed checksum does not match what is in the catalog for replica [1].
(partisan) keith@tao:~/dev/work/python/partisan$ echo $?
0
```

**Comment by trel** [comment]
got it - again working correctly, reported well this time... but error code should be more helpful/non-zero.

**Comment by kjsanger** [comment]
What prompted me to look at results from `ìchksum` was that I had some `baton` tests failing where I'm calling `rcDataObjChksum` on various "bad" data objects with the `VERIFY_CHKSUM_KW` set, expecting it to return non-zero, which it never did.

**Comment by kjsanger** [comment]
The docs suggest that `<0` should be returned in these cases:

https://github.com/irods/irods/blob/32cc2bd18e43aaaa42f002d07996343a05066646/lib/api/include/dataObjChksum.h#L90-L99

**Comment by trel** [comment]
checkboxed.
