### ISSUE TITLE
pluggable APIs fail in userspace-tarball versions of icommands

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#5845]
- [ ] master
- [ ] 4-2-stable
-------

Versions
---
iRODS release **4.2.10** and **master**
ubuntu 18.04

Bug
---
Certain operations (seemingly the pluggable APIs ie those >=20000) that are key to certain icommands ( `itouch`, `istream` at least) appear to fail in the userspace-tarball versions of those icommands.

To reproduce
---
In the following excerpt, non-userspace versions of these icommands are in `/usr/bin` and the userspace versions have been expanded in `~/irods-icommands-4.2.10/usr/bin/` : 
```
~$ ils
/tempZone/home/rods:
  33meb
  profi
~$ ./irods-icommands-4.2.10/usr/bin/itouch a
remote addresses: 127.0.0.1 ERROR: procApiRequest: apiTableLookup of apiNumber 20007 failed
~$ /usr/bin/itouch b
~$ ils
/tempZone/home/rods:
  33meb
  b
  profi
~$ ./irods-icommands-4.2.10/usr/bin/istream  write b <<<"somestring"
remote addresses: 127.0.0.1 ERROR: procApiRequest: apiTableLookup of apiNumber 20003 failed
Error: Cannot open data object.
~$ /usr/bin/istream  write b <<<"somestring"
~$ iget b -
somestring

```

Notably, icommands that don't involve the APNs >= 20000 seem to run fine:
```
~$ ./irods-icommands-4.2.10/usr/bin/ils
/tempZone/home/rods:
  33meb
  b
  profi
```

**Comment by korydraughn** [comment]
I don't know if #5776 fixes it, but it is most likely the same issue. The tarball needs to pull in the API plugin libs.

**Comment by d-w-moore** [comment]
I pulled in the fix for #5776 , but it does not seem to fix this, so somehow not the same issue I guess.  (That one hinges on irods-server not being installed, in other wordds just a question of which package furnishes the api plugins.

But for the issue at hand, everything is on one computer, and `irods-server` is installed.

**Comment by trel** [comment]
tarball shouldn't require any packages (user doesn't have sudo) - @korydraughn is right, this is just about getting the userspace tarball more populated.

**Comment by d-w-moore** [comment]
Affirmative, since this doesn't really seem to be about files not existing or being in the wrong places either. It's probably the process of finding the plugin from inside a client that goes astray. (`ldd` does not return `not found` for either the tarball or package version of `itouch`.

**Comment by d-w-moore** [comment]
oh right. I get it... so we need a userspace version of API plugins too?
