### ISSUE TITLE
Compound resource with archive-only replica results in SYS_REPLICA_DOES_NOT_EXIST

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#5847]
- [x] master
- [x] 4-2-stable
---
### iRODS Version, OS and Version
iRODS 4.2.9

### What did you try to do?
I ran `icp <data_object> <new_data_object>`.

`<data_object>` has a single replica in the archive resource of a compound resource.

### Expected behavior
I expected the replica on the archive resource to be staged to the cache resource and then copied into the collection.

### Observed behavior (including steps to reproduce, if applicable)
I received the following ...

From the terminal:
```bash
$ icp aaa ccc                                                      
remote addresses: XXX.XXX.XXX.XXX ERROR: cpUtil: cp error for /tempZone/home/kory/ccc, status = -164000 status = -164000 SYS_REPLICA_DOES_NOT_EXIST
```

From the log file:
```
Sep 13 18:29:57 pid:615 remote addresses: 127.0.0.1, XXX.XXX.XXX.XXX ERROR: [rsDataObjOpen_impl:949] - requested replica does not exist [path=[/tempZone/home/kory/aaa], hierarchy=[compResc;cacheResc]]
Sep 13 18:29:57 pid:615 remote addresses: 127.0.0.1, XXX.XXX.XXX.XXX ERROR: [open_source_data_obj:100] - failed to open source object [irods error=[SYS_REPLICA_DOES_NOT_EXIST], system error=[], path=[/tempZone/home/kory/aaa]]
```

**Comment by trel** [comment]
Originally found via Metalnx https://github.com/irods-contrib/metalnx-web/issues/222
