### ISSUE TITLE
irods recompile and delete directly from filesystem

### ISSUE THREAD

**Issue by yr-wang-hit** [irods/irods#5857]
## Feature

A bit silly questions maybe.

I installed irods4.2.8 from source and follow the instructions by the irods official doc.
I find that when I install irods(aka, make non-package-install-postgres) as root user, 
It should not be installed under the directory /root and aiming to start the service(init.d/irods start) 
will issue a permission denied error(the script su another user to start the service). Isn't that the case?
so What is the best practice to place the install directory and Vault directory to start the service both from [init.d/irods start] and[systemctl start irods.service] successfully?

Another critical feature is to mitigate metadata and data when recompile and reinstall irods service. When fixing some irods bugs or changing the install position and recompiling the source code, we need to reinstall irods, isn't it? (python $IRODS_HOME/var/lib/irods/script/setup_irods.py to reinstall it). But the metadata database is not empty and the prompt will warn you that maybe you need to drop it and recreate it. That is not what I want if I try to keep the data. The install process seems to crash if I continue the install script with the error ["violate the unique restriction"] or ["database already used by irods"]. suck problems, How to fix it? Sometimes, odbc will report error "odbcinst -r -i ... failed..." WTF!

Another question is about delete from the Vault directory directly. What happens when I delete files from filesystem but not the irods interface? What exactly the "ireg" is doing? And how to distinguish the usage of iput and ireg?

Thanks in advance.

**Comment by trel** [comment]
There's a lot going on here.   I think working through the Beginner Training will answer a number of your questions.

The non-package-install option is designed for non-root users.  If you have root access, we definitely recommend using the provided packaging.

Moving/Changing the install location is definitely not something iRODS is designed to accomodate.  The catalog holds many physical paths in the database and without informing/updating the catalog, everything in the system will now be in an incorrect location.

If you remove data from a storage system that iRODS is managing, then iRODS will not be able to read that data anymore when it comes looking for it.  If storage is 'under management', then it is assumed nobody else will be touching that data.

`ireg` adds an entry in the catalog to a (usually) non-vault location where the iRODS service account can get at the data.  An `iput` will move data, and then register it.  An `ireg` is 'just step 2'.

We might be able to help a bit more if you explain your use case for compiling the server yourself.  There may be better ways to manage that process (and any subsequent upgrades/recompiles).

**Comment by yr-wang-hit** [comment]
Thanks a lot, trel.

The recompiling issue means that we want to patch the official irods code corresponding to our own use case.
It's convenient to install it through package indeed. But What if we want to update the code?

But I decide to install it through package.

As you said
"If storage is 'under management', then it is assumed nobody else will be touching that data."
it seems that the Vault should have a restricted write/read mode to keep data safe.

**Comment by trel** [comment]
> The recompiling issue means that we want to patch the official irods code corresponding to our own use case.
It's convenient to install it through package indeed. But What if we want to update the code?

I understand the need/requirement to recompile the code - but if you have root access... you can compile the packages yourself, and install them... still using a protected service account of your choosing, and using your own source code edits.

If there is a use case that we're not understanding, please explain and we'll be happy to help work out a good solution.

> it seems that the Vault should have a restricted write/read mode to keep data safe.

Yes, that is most certainly a correct assessment.   In a packaged install, the Vault is owned and operated by the service account only - other unix users cannot see/touch the Vault(s).

```
$ sudo ls -al /var/lib/irods/Vault
total 12
drwx------  3 irods irods 4096 Sep 28  2020 .
drwxr-xr-x 15 irods irods 4096 Sep 15 15:34 ..
drwxr-x---  3 irods irods 4096 Sep 28  2020 home
```

**Comment by yr-wang-hit** [comment]
Thanks trel!

I will be more grateful if there is an example of packaging the source code to rpm packages.

Thanks a lot.

**Comment by trel** [comment]
You just need to create a build directory, jump in, run `cmake ..` and then `make package` on CentOS7.   Anything else is outside of what we have tested, but may run fine.  Happy to hear feedback about the process.

If you're not using the packaged externals either, you'll need to build them first.

**Comment by yr-wang-hit** [comment]
Thanks a lot trel, everything goes well as you said.

Another problem is that when I install irods as "consumer" (aka, resource server.), I find the install process will stuck and it seems it cannot talk to icat server. I have "telnet" the process located on icat server and can communicate successfully. I wonder if it needs to configure the "host_config.json" or "host_access_control.json" to make resource server talk to irods icat server. without "python setup_irods.py" to install the resource server, I can execute command like "ils" on resource server but I cannot use the physical resource on it like "irepl -R some_resc(located on resource server) file.txt".


Thanks a lot.

**Comment by trel** [comment]
If `ils` is behaving, then getting the storage to behave is pretty close.

If you can share the error messages from the `iput` command and from `/var/lib/irods/log/rodsLog.2021.09.21`, we should be able to see the reason the `iput` is failing.

**Comment by yr-wang-hit** [comment]
Thanks a lot trel, you are so kind.
Everything goes well now with your help.
And I'll happily play with irods and metalnx.

Thanks again.

**Comment by trel** [comment]
Excellent.
