### ISSUE TITLE
use of RUNPATH may prevent plugin components with externals lib dependencies from loading

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#5860]
- [x] master (irods/externals)
- [x] 4-2-stable (irods/externals)
-----
Changes to plugins' CMakeLists.txt file which cause RUNPATH rather than RPATH to be set in shared objects may result in failure to load on Ubuntu 16.

### iRODS Version, OS and Version
iRODS 4.2.10, running https://github.com/irods/irods_capability_indexing/commit/1bada02b0492f7f8da699bda9b2e4fbec05307dd
on a `ubuntu:16.04` based docker container  (it's unknown which if any other plugins are affected).

### What did you try to do?

Run the indexing plugin test suite

### Expected behavior

Passing tests

### Observed behavior (including steps to reproduce, if applicable)
the `libirods_rule_engine_plugin-elasticsearch.so` component could not be loaded due to dependencies on libjsoncpp.so.19  (located in `/opt/irods-externals/elasticlient0.1.0-1/lib`, installed on the system at the time) that were not loading in Ubuntu 16 probably due to ELF not working well with the RUNPATH field of .so objects on that Ubuntu release.
All tests failed due to inability to communicate with elasticsearch  (the purpose  of   `libirods_rule_engine_plugin-elasticsearch.so` when successfully loaded by an iRODS agent process).

These messages were seen in the rodsServerLog:
```
Sep 16 14:26:44 pid:4798 remote addresses: 10.10.0.2 ERROR: [-] /root/github/irods/server/re/include/irods_re_plugin.hpp:362:irods::error irods::rule_engine_plugin_manager<std::__1::t
uple<> >::resolve(std::string &, const std::string &, pluggable_rule_engine<T> *&) [T = std::__1::tuple<>] :  status [PLUGIN_ERROR]  errno [] -- message [failed to open shared object 
file [/usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-elasticsearch.so] :: dlerror: is [libjsoncpp.so.19: cannot open shared object file: No such file or directory]]
        [-]     /root/github/irods/lib/core/include/irods_load_plugin.hpp:176:irods::error irods::load_plugin(PluginType *&, const std::string &, const std::string &, const std::strin
g &, const Ts &...) [PluginType = irods::pluggable_rule_engine<std::__1::tuple<> >, Ts = <std::__1::basic_string<char>>] :  status [PLUGIN_ERROR]  errno [] -- message [failed to open 
shared object file [/usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-elasticsearch.so] :: dlerror: is [libjsoncpp.so.19: cannot open shared object file: No such file or
 directory]]

Sep 16 14:26:44 pid:4798 remote addresses: 10.10.0.2 ERROR: [-] /root/github/irods/server/re/include/irods_re_plugin.hpp:387:auto irods::rule_engine_manager<std::__1::tuple<>, RuleExe
cInfo *>::rule_engine_manager(rule_engine_plugin_manager<std::__1::tuple<> > &, std::vector<re_pack_inp<tuple<> > > &, microservice_manager<RuleExecInfo *> &)::(anonymous class)::oper
ator()(re_pack_inp<T> &) const [T = std::__1::tuple<>, C = RuleExecInfo *] :  status [PLUGIN_ERROR]  errno [] -- message [failed to open shared object file [/usr/lib/irods/plugins/rul
e_engines/libirods_rule_engine_plugin-elasticsearch.so] :: dlerror: is [libjsoncpp.so.19: cannot open shared object file: No such file or directory]]
        [-]     /root/github/irods/server/re/include/irods_re_plugin.hpp:401:irods::error irods::rule_engine_manager<std::__1::tuple<>, RuleExecInfo *>::init_rule_engine(re_pack_inp<T
> &) [T = std::__1::tuple<>, C = RuleExecInfo *] :  status [PLUGIN_ERROR]  errno [] -- message [failed to open shared object file [/usr/lib/irods/plugins/rule_engines/libirods_rule_en
gine_plugin-elasticsearch.so] :: dlerror: is [libjsoncpp.so.19: cannot open shared object file: No such file or directory]]
                [-]     /root/github/irods/lib/core/include/irods_load_plugin.hpp:176:irods::error irods::load_plugin(PluginType *&, const std::string &, const std::string &, const st
d::string &, const Ts &...) [PluginType = irods::pluggable_rule_engine<std::__1::tuple<> >, Ts = <std::__1::basic_string<char>>] :  status [PLUGIN_ERROR]  errno [] -- message [failed 
to open shared object file [/usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-elasticsearch.so] :: dlerror: is [libjsoncpp.so.19: cannot open shared object file: No such
 file or directory]]
```

**Comment by d-w-moore** [comment]
I was able to get  tests running again by changing `enable-new-dtags ` to `disable-new-dtags ` in the macro definitions of CMAKE_{MODULE,SHARED}_LINKER_FLAGS_INIT macros in `CMakeLists.txt`

**Comment by d-w-moore** [comment]
@SwooshyCueb  I was able to get your suggestion of turning on the origin flag for elasticlient.so library and using $ORIGIN in the RUNPATH, which solves everything it seems on Ubuntu.  Will test on CentOS too, of course 

Upshot, please ignore the above posted comment to this issue.  After discussion and perhaps investigation of any other libraries (I know of none right off) that may exhibit the same problems we could close  this issue. (@trel)

**Comment by trel** [comment]
Okay, so the fix will be to update the elasticlient externals package build process... resulting in a new externals package.

**Comment by d-w-moore** [comment]
Done.

**Comment by trel** [comment]
please cherry-pick to irods/externals master branch as well.

**Comment by d-w-moore** [comment]
Yes, will do.
