### ISSUE TITLE
multiple irepls to the same tree - launched after the first completes 

### ISSUE THREAD

**Issue by mcast** [irods/irods#5867]
## Bug Report

This looks like more of a bug.  (Sorry, first posting was an exact dup of #5866 and now I'm editing to fix)

#5866 is about when the extra `irepl`s are launched before any complete. This is what happens if they're launched later.

### iRODS Version, OS and Version
iRODS 4.2.7 on Ubuntu Bionic.

### What did you try to do?

1. Background: we have two independent resource tree roots, "red" and "green",
    1. each of which contains (after complications) a nested collection of `type: random` resources containing `type: unixfilesystem`.
    2. We `iput -R green ...` and then later `irepl -R red ...` to reach two copies.
2. `iput -R green ...` a 13 GiB file in the usual way
3. `irepl -R red ...` once, in the usual way. We now have two replicas in green & red.
4. `irepl -R red ...` again, for some inexplicable reason such as failing to notice that it's already done. (For internal readers: https://gitlab.internal.sanger.ac.uk/casm/cgpDataOut/-/issues/133 )

I wanted to know what can happen. To be clear,

1. one green copy, one red copy
2. another `irepl -R red ...` launched after the other has completed and the second replica is visible to `ils`
3. wait...

### Expected behavior
The iCAT seems to reject the extra copy, but after the work has been done. If the third `irepl` is going to be a no-op, shouldn't it either complete instantly or raise an "already done it" error?

### Observed behavior (including steps to reproduce, if applicable)
The third `irepl` takes a significant length of time to complete, so I believe it's doing...  something.

I don't see any resulting files, not dotfiles in the unixfilesystem nor `/$ZONE/orphan/...` files.

## Change requested?
Again documentation makes sense, but here I think if the extra copy is going to be thrown away then better to not make it in the first place.

**Comment by mcast** [comment]
(edited the description after accidentally pressing submit too early)

**Comment by trel** [comment]
is it spending that time calculating checksums?   to confirm the data is identical... and then it can 'throw it away'?

I would expect the target resource to 'vote' and determine that there is already a replica there, as you expected... but if the calculation is requested/required, then that's my first guess of what's happening.

**Comment by mcast** [comment]
On Mon, Sep 20, 2021 at 11:32:42AM -0700, Terrell Russell wrote:

> is it spending that time calculating checksums?  to confirm the data
> is identical... and then it can 'throw it away'?

Possibly..?  I have no visibility into what's happening here, except
that it takes about a minute.


> I would expect the target resource to 'vote' and determine that
> there is already a replica there, as you expected... but if the
> calculation is requested/required, then that's my first guess of
> what's happening.

The main thing is that it doesn't seem to do Anything Bad, which is
what I wanted to know.

Beyond that, the main reason to know what it's actually doing with the
time is the chance of finding a bug hiding under that particular rock.

-- 
Matthew


-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by trel** [comment]
I don't think there's anything actionable here at the moment.   Willing to close if others agree.
