### ISSUE TITLE
irods Server automatically open multi-hundred processs a night

### ISSUE THREAD

**Issue by yr-wang-hit** [irods/irods#5880]
### Observed behavior
version: irods4.2.8 os: redhat7.4

After deploying irods4.2.8 on our test environment, we observed irods will automatically open multi-hundred process a night
and the service will be unavailable.

when we tape "ps -aux | grep irods"
there are multi-hundred pairs such like:

irods:  /usr/sbin/irodsServer
postgres: irods ICAT ::1(44224) idle.

I have observed this many times but this time the service is down and I cannot ignore it.
even if the service is running, multiple-hundred idle process will consume all the resource on the server.
What is the reason and How to prevent this?

Thanks a lot.

**Comment by trel** [comment]
The iRODS Rule Execution Server (ReServer or Delay Server) will wake up and check for any rules that need to run, by default, every thirty seconds.  But this will happen all the time, not just at night.

Can you find out any more information about the client that is initiating those irodsServer Agent processes?

What is the output from `ips`?   That will show you some client connection information on active irodsAgent processes.

**Comment by yr-wang-hit** [comment]
yeah, A night indicates a duration and not always at night.
after I "systemctl restart irods.service" The process will become "normal"
As a new bee of irods , I always take the normal circumstance as three processes:
/usr/sbin/irodsReServer  and two /usr/sbin/irodsServer.
As you said, irods will automatically wake up some processes to check the delay rules to execute.
But It seems more reasonable to me to wake up a process during a period and kill itself afterwards. but not to
keep it to consume the server resource. multi-hundred processes of irods on a server seems awkward.
I just worry about the stability of irods service if it will down unexpectedly like this morning(for you it's night).

ips will get the result of [username#zonename server] normally.  

Thanks a lot.

**Comment by yr-wang-hit** [comment]
I have no idea if it is related to metalnx.

**Comment by alanking** [comment]
We have definitely seen Metalnx keep a connection held open indefinitely, but I don't know that I've seen or seen reported that multiple connections are being held open.

**Comment by yr-wang-hit** [comment]
I have found the bug, it is due to configuring metalnx [job] parameter incorrectly.

Each Metalnx seems holding one connection to irods server indefinitely, as alan said. And ips cannot recognize it 

leaving UNKNOWN connection type.

Thanks trel and alan and I will close the issue.
