### ISSUE TITLE
irods-runtime deb package must declare relationship with earlier irods-server package due to moved files

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#5909]
Upgrading the irods deb packages from any pre-#5835/#5836 package to a post-#5835/#5836 on a system with irods-server installed will fail, as files previously in the irods-server package now live in the irods-runtime package, and dpkg is not smart enough to recognize this on its own.

The proper way to handle this is to declare that the irods-runtime package both breaks and replaces pre-#5835/#5836 irods-server:
https://www.debian.org/doc/debian-policy/ch-relationships.html#overwriting-files-and-replacing-packages-replaces

The obvious solution would be to use `irods-server (<< 4.2.11)`, but this is problematic because 4-2-stable still builds packages versioned 4.2.10.
Instead, we should bump the debian revision part of our package version string. (Note that this needs to be undone for 4.2.11, preferably in the same commit that bumps the version number.)

**Comment by trel** [comment]
Just also noting here we need to do the same/equivalent in RPM land.

**Comment by SwooshyCueb** [comment]
Just to confirm, you're saying that upgrading the RPM packages fails for the same reason? I can't seem to reproduce this on my end

**Comment by trel** [comment]
No, not that I've seen it happen, just that we need to confirm that it's behaving as intended.  Since RPM installs 'both' at the same time before removing the original... maybe it's already smart enough to know what to do.  If it's working... carry on.
