### ISSUE TITLE
clarify msiDataObjRepl's verifyChksum when source replica already has checksum in catalog

### ISSUE THREAD

**Issue by trel** [irods/irods#5927]
- [x] master
- [x] 4-2-stable
-------

## Feature

`msiDataObjRepl` should be more specific/thorough in its description of how the `verifyChksum` keyword is used.   If we determine that `msiDataObjRepl` has a bug in that it is not honoring the `verifyChksum` keyword correctly, then we should turn this issue into a bug report.

There is an 'implicit' verification happening when the source replica already has a checksum.

This can be surprising/problematic when writing to a tape resource... aka, it is written to tape, then read from tape to verify the contents were written correctly... which can be very expensive/slow.

The checksum API was reworked for clarity and consistency in https://github.com/irods/irods/commit/2a0460718f7142bf494c1030b7d7617e1e60ba20 in 4.2.9.

Comments requesting this clarification issue are from:
 - https://groups.google.com/g/irod-chat/c/dKIB_jrPQkU/m/CivEkWZSAgAJ
 - https://github.com/irods/irods/issues/5592#issuecomment-842177531

**Comment by trel** [comment]
@alanking Am I reading this correctly, that `verifyChksum` / `VERIFY_CHKSUM_FLAG` / `VERIFY_CHKSUM_KW` is ... not considered by `rsDataObjRepl() -> replicate_data_object() -> replicate_data() -> finalize_destination_replica()` ?

https://github.com/irods/irods/blob/f79ff76e1b3d1c677cbe54ce2aa3c5a0ad03d63b/server/api/src/rsDataObjRepl.cpp#L217-L225

It appears to only care whether the source already had a checksum?

---

If so, and we want to 'restore' the functionality of `msiDataObjRepl`'s `verifyChksum` parameter... this issue should be marked as a bug.

**Comment by alanking** [comment]
I think you are reading that correctly, yes.

Will need to make (yet) another matrix for these options to make sure it is understood what they all mean.

**Comment by trel** [comment]
Okay, marking as bug, and bumping to 4.2.12.

**Comment by alanking** [comment]
As noted above, there are at least the following explicit ways to indicate a desire to verify the checksum for a given replica:
 - `VERIFY_CHKSUM_KW`
https://github.com/irods/irods/blob/bc6f9f1cdef6c4ec01ea14402428988892615321/lib/core/include/rodsKeyWdDef.h#L14
 - `VERIFY_CHKSUM_FLAG`
https://github.com/irods/irods/blob/bc6f9f1cdef6c4ec01ea14402428988892615321/lib/core/include/msParam.h#L116
 - `VERIFY_CHKSUM`
https://github.com/irods/irods/blob/bc6f9f1cdef6c4ec01ea14402428988892615321/server/core/include/objDesc.hpp#L29

Regarding `rsDataObjRepl`'s treatment (or lack thereof) of the `VERIFY_CHKSUM_KW`, I found that the finalize logic for replication and phymv operations was implemented this way *intentionally* (notice the comment):
https://github.com/irods/irods/blob/9eb6c23df45cdedff8ee9c3af71a65d304635037/server/api/src/rsDataObjClose.cpp#L830-L833

This has always been the case: https://github.com/irods/irods-legacy/blob/ff4eaa47a34f1bb5990d5560f825975c26bab118/iRODS/server/api/src/rsDataObjClose.c#L858-L860

So the behavior shown in the comment above that exists in 4.2.9+ is simply carrying forward the existing behavior (I *think*).

---

After some discussion, a proposal has been made that the existing behavior should be maintained (that is, checksum verification happening every time there is a checksum on the source replica), but the `NO_COMPUTE_KW` will be considered by `rsDataObjRepl` and `rsDataObjPhymv` in order to bypass the checksum calculation. The benefit to this is backward compatibility and minimal changes needed in the main codebase.

The alternative would be to *never* verify the checksum unless the `VERIFY_CHKSUM_KW` is provided through the `dataObjInp_t`. The benefit to this is clarity through explicit specification.

@trel, how does this sound to you?

**Comment by trel** [comment]
I think the proposal (not the alternative) is the way to go.

`NO_COMPUTE_KW` is an elegant solution:
 - keeps backwards compatibility (and mental model of data object being 'safe', aka all replicas, if any replica has checksum)
 - affords tape-based resources to specifically request *not* to verify on write (b/c expensive)


Is the following the... desired behavior?

| Case | Method | Source | Destination | via |
| --- | --- | --- | --- | --- |
| 1 | `msiDataObjRepl` | none | none | implicit |
| 2 | `msiDataObjRepl` | none | checksum | `VERIFY_CHKSUM_KW` |
| 3 | `msiDataObjRepl` | checksum | none | `NO_COMPUTE_KW` |
| 4 | `msiDataObjRepl` | checksum | checksum | implicit |
| 5 | `rsDataObjPhymv` | none | none | implicit |
| 6 | `rsDataObjPhymv` | none | checksum |  `VERIFY_CHKSUM_KW` |
| 7 | `rsDataObjPhymv` | checksum | none | `NO_COMPUTE_KW` |
| 8 | `rsDataObjPhymv` | checksum | checksum | implicit |

I guess an argument for `msiDataObjRepl` to be included could be made... should be duplicate of cases 1-4, but via `verifyChksum`?

Any other cases to consider/add?

**Comment by alanking** [comment]
This looks reasonable to me. The only operations which have historically demonstrated this behavior are replicate and phymv so I don't think we need to cover any other operations.

The other case to consider is sync-to-archive and stage-to-cache. At the moment, checksum verification on replications resulting from sync-to-archive operations cause the archive resource plugins to return a `DIRECT_ARCHIVE_ACCESS` and then the destination replica just takes the checksum value of the source replica. Do we want to change this in any way?

**Comment by trel** [comment]
I think that logic does and should continue to live in the archive-class plugin(s)... not in the server itself.

If anything, it could/would use the `NO_COMPUTE_KW` when writing that archive replica?   If that's interesting/possible/good, we should make a separate issue for it.


So, no, I don't think there's anything else to be done here except the repl and phymv.

**Comment by alanking** [comment]
Right, I was thinking that the sync to archive operation in the compound resource could pass `NO_COMPUTE_KW` to the finalize call after the replication. I will make a new issue for that

**Comment by trel** [comment]
Upon further discussion....

## msiDataObjRepl()

| Case | verifyChksum | source | result | aka |
| --- | --- | --- | --- | --- |
| aa | 0 | none | case 1 below | none |
| bb | 0 | checksum | case 3 below | `NO_COMPUTE_KW` |
| cc | 1/empty | none | case 2 below | `VERIFY_CHKSUM_KW` b/c interpretation (source interrogation should happen in API, not out here)..... peek into db and use `REG_CHKSUM_KW` (-k) OR ERROR `CAT_NO_CHECKSUM_FOR_REPLICA`... DEFINITELY NOT GOING TO IGNORE AND NO_OP |
| dd | 1/empty | checksum | case 4 below | `VERIFY_CHKSUM_KW` (-K) |

but case cc is tricky so we could...

w.  use verify out here, interrogation happens in API (no extra db hit), but feels weird that API would be 'ignoring'/reinterpreting a verify request into a reg request

x.  use reg out here (-k)... requires db hit to detect the source info, but cleanest interface/explanation for users... posssibly not viable due to not yet knowing which replica would be the source.

y.  add support for forceChksum/`FORCE_CHKSUM_FLAG` to msi - semantically more correct b/c not using the word 'verify'... but more `USER_UNSUPPORTED_PARAMS` would have to be detected out here in msi.  uses reg out here, but without the db hit.

z.  add verifyChksum = 2 ... kind of like y, but with less new flag.  still uses the confusing 'verify' for 'reg'... uses reg out here, but without the db hit.


so assuming case y....

| Case | forceChksum | verifyChksum | source | API case | aka |
| --- | --- | --- | --- | --- | --- |
| a | none | none | none | 1 | nada |
| b | none | none | checksum | 4 (implicit) | `VERIFY_CHKSUM_KW` |
| c | none | 0 | none | 1 | nada |
| d | none | 0 | checksum | 3 | `NO_COMPUTE_KW` |
| e | none | 1/present | none | ERROR | early bail `CAT_NO_CHECKSUM_FOR_REPLICA` |
| f | none | 1/present | checksum | 4 | `VERIFY_CHKSUM_KW` |
| g | 1/present | none | none | 2 | `REG_CHKSUM_KW` |
| h | 1/present | none | checksum | 4 | `VERIFY_CHKSUM_KW` |
| i | 1/present | 0 | none | 2 | `REG_CHKSUM_KW` |
| j | 1/present | 0 | checksum | ERROR | `USER_INCOMPATIBLE_PARAMS` |
| k | 1/present | 1/present | none | ERROR | early bail `CAT_NO_CHECKSUM_FOR_REPLICA` |
| l | 1/present | 1/present | checksum | 4 | `VERIFY_CHKSUM_KW` |


------

## API

| Case | Function | Source | Destination | via | result |
| --- | --- | --- | --- | --- | --- |
| 1 | `rsDataObjRepl` | none | none | n/a (implicit) | nada |
| 2 | `rsDataObjRepl` | none | checksum | `REG_CHKSUM_KW` | calculate, save in db |
| 3 | `rsDataObjRepl` | checksum | none | `NO_COMPUTE_KW` | no compute, no db |
| 4 | `rsDataObjRepl` | checksum | checksum | `VERIFY_CHKSUM_KW` (implicit) | calculate, compare, save in db |
| 5 | `rsDataObjPhymv` | none | none | n/a (implicit) | nada |
| 6 | `rsDataObjPhymv` | none | checksum |  `REG_CHKSUM_KW ` | calculate, save in db |
| 7 | `rsDataObjPhymv` | checksum | none | `NO_COMPUTE_KW` | no compute, no db |
| 8 | `rsDataObjPhymv` | checksum | checksum | `VERIFY_CHKSUM_KW` (implicit) | calculate, compare, save in db |

phmv is identical to repl, except for trimming the source and sets the replica number


----
This implies that the `REG_CHKSUM_KW` is now going to be supported in `rsDataObjRepl` and `rsDataObjPhymv`

**Comment by alanking** [comment]
To clarify a bit on how the keywords ought to interact with the replication/phymv APIs, here's yet another table:
| Case | `VERIFY_CHKSUM_KW` | `REG_CHKSUM_KW` | `NO_COMPUTE_KW` | Source | Result |
| ----- | ----- | ----- | ----- | ----- | ----- |
| 1 | 0 | 0 | 0 | none | no checksum |
| 2 | 0 | 0 | 1 | none | no checksum |
| 3 | 0 | 1 | 0 | none | checksum, no compare |
| 4 | 0 | 1 | 1 | none | `USER_INCOMPATIBLE_PARAMS` |
| 5 | 1 | 0 | 0 | none | `CAT_NO_CHECKSUM_FOR_REPLICA` |
| 6 | 1 | 0 | 1 | none | `USER_INCOMPATIBLE_PARAMS` |
| 7 | 1 | 1 | 0 | none | `USER_INCOMPATIBLE_PARAMS` |
| 8 | 1 | 1 | 1 | none | `USER_INCOMPATIBLE_PARAMS` |
| 9 | 0 | 0 | 0 | checksum | checksum, verified (current behavior) |
| 10 | 0 | 0 | 1 | checksum | no checksum |
| 11 | 0 | 1 | 0 | checksum | `SYS_NOT_ALLOWED` (with a lengthy error message) |
| 12 | 0 | 1 | 1 | checksum | `USER_INCOMPATIBLE_PARAMS` |
| 13 | 1 | 0 | 0 | checksum | checksum, verified |
| 14 | 1 | 0 | 1 | checksum | `USER_INCOMPATIBLE_PARAMS` |
| 15 | 1 | 1 | 0 | checksum | `USER_INCOMPATIBLE_PARAMS` |
| 16 | 1 | 1 | 1 | checksum | `USER_INCOMPATIBLE_PARAMS` |

The table above about how the microservice arrives at its various flags (as well as its own set of incompatible parameters) still seems to hold here.

**Comment by trel** [comment]
so pretty.

**Comment by alanking** [comment]
I think this can be checkboxed and closed now.

**Comment by trel** [comment]
bueno.
