### ISSUE TITLE
Cannot enact data object parallel transfers via a ticket. 

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#5932]
### iRODS Version, OS and Version

iRODS [4-2-stable](https://github.com/irods/irods/commit/b0b252fbba40c6744f64e488cae123408cf1382d)
Ubuntu 18.04

### What did you try to do?
parallel data get

### Expected behavior
Be able to  access a replica simultaneously across different threads (ie parallel transfer) with ticket activated in session.
Using: [PRC](https://github.com/d-w-moore/python-irodsclient/tree/tickets_DEBUG)

### Observed behavior (including steps to reproduce, if applicable)
`SYS_REPLICA_DOES_NOT_EXIST` thrown by server. Likely because permissions on replica not recognized through activated ticket (?)

**Comment by d-w-moore** [comment]
This, it turns out, is almost certainly not an iRODS server issue, but a byproduct of https://github.com/irods/python-irodsclient/issues/455 . This issue is addressed by a commit in https://github.com/irods/python-irodsclient/pull/458

**Comment by korydraughn** [comment]
Should this be part of the 4.3.1 milestone?

**Comment by d-w-moore** [comment]
> Should this be part of the 4.3.1 milestone?

I think so, going along with PRC's client redirection for data open and (multi-1247) put/get and our fixes for #7250 having been proven crucial to those client functions working with tickets.

**Comment by alanking** [comment]
To be clear, this is referring to "multi-1247" parallel transfer, not the "traditional/high port" parallel transfer?

**Comment by korydraughn** [comment]
I'm pretty sure this is related to multi-1247 parallel transfer since the PRC is mentioned.

@d-w-moore Thoughts?

**Comment by d-w-moore** [comment]
@alanking , @korydraughn  , all , yes - this is multi-1247 related.  It is also resolved by the "new low-level ticket API" commit within the [resource redirect PR](https://github.com/irods/python-irodsclient/pull/458). It improved session/connection tracking,  Whereas before,  connections could be picked up from the idle pool which haven't had the session ticket applied, this is no longer possible.  I'd wager at higher than 99% this is the actual problem, and #5932 (this issue) is not a server problem at all.  Will close when 100% verified thru testing.

**Comment by trel** [comment]
dan's commit being referenced... https://github.com/irods/python-irodsclient/pull/458/commits/2b53968d0f9a1da1d9be4a199f468aa275b45130

**Comment by korydraughn** [comment]
@d-w-moore Are you still working on this?

**Comment by d-w-moore** [comment]
I could've been clearer yes.  This is not an issue with iRODS itself but rather with the PRC. It's being resolved with the commit @trel reference above (or equivalent if I've rebased or squashed since). Now 100% certain! : )

**Comment by trel** [comment]
So do we need any checkboxes here?

**Comment by alanking** [comment]
Because this is a PRC issue, I don't think we need checkboxes.

**Comment by trel** [comment]
Gotcha.  Thanks.
