### ISSUE TITLE
Allow "iadmin addchildtoresc" to update the parent of a child atomically

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#5934]
## Feature
`iadmin addchildtoresc` will result in a `CHILD_HAS_PARENT` error if the child resource already has a parent resource. Given that this operation is just an update of a single column, there is no risk around allowing `addchildtoresc` to **overwrite** the previous value of `r_resc_main.resc_parent`. This change would make performing tree surgery more atomic.

**Comment by kript** [comment]
> We talked about the `-f` option... but it seems since this is already an admin operation, we should trust the admin to know what they're doing? And if we don't do a 'parent check' before changing the value, then... we're good to go?
> 
> If someone has coded against an error that is no longer going to be sent, then... that's fine?

Normally I'd agree, but in this case, it changes the existing behaviour when adding to an existing relationship from a fail with an error to a silent success. I worry it could catch someone out, even while I see the utility of it!

**Comment by trel** [comment]
I think we're going to move forward on this - it's designed to reduce the number of states the catalog and the admin have to consider and it reduces the window where incoming connections get (about to be) stale information.
