### ISSUE TITLE
Packages should generate their own filenames

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#5937]
- [x] 4-2-stable
- [x] master
-----
At present, irods generates the `IRODS_PACKAGE_FILE_NAME_SUFFIX` variable and stores it in the project configuration. This variable is pulled in by other projects to name their packages.
Since we are moving towards proper package versioning, this won't work any more, as changes to the package revision string would affect the package names of unrelated packages.
Instead, packages should generate their own filenames. This can be done by setting `CPACK_RPM_FILE_NAME` to `RPM-DEFAULT` and `CPACK_DEBIAN_FILE_NAME` to `DEB-DEFAULT`.

**Comment by trel** [comment]
moving back to 4.2.11 - done before deadline.
