### ISSUE TITLE
problems for automatically extract metadata from another host

### ISSUE THREAD

**Issue by yr-wang-hit** [irods/irods#5943]
Hi, I tried to understand irods rule invoking mechanism from the 2017 beginner tutorial.

the code seems to have bugs when we invoke "iput -R rootResc stickers.jpg' 

https://github.com/yr-wang-hit/irods_training/blob/605bc905c3f396a5d337348b51b9bedeb497c5a5/beginner/core.py#L11

the problem is that if the data is put to another resource server other than the one I invoke the command, we cannot find the 
data at local physical path and it will fail. We have badly need to automatically extract information(aka metadata, readme ,etc) from data at the point of iput(implement the acPreProcForPut and acPostProcForPut), I know it can be done by RPC or some other things, But I don't know if there is off-the-shelf solution.

Thanks a lot.

**Comment by yr-wang-hit** [comment]
sorry to response too late.
I have implemented the function as moore said.
It indeed invoked the action only on host where resource physically resides.
BUT it seems to invoke twice and the second time it will fail because of
metadata redundantly inserting. It seems to be invoked incorrectly or we should
implement another PEP point.

I will be graceful if there is a documentation or audit tools to tell the users which PEPs has been invoked on which server 
when they tape icommand such like "iput -R rootResc a.jpg".

Thanks.

**Comment by alanking** [comment]
Using `pep_resource_close_post` is going to conflate the logical and physical layers for this particular use case. AVUs are associated with data objects which are logical entities whereas the `resource_close` plugin operation is executing on every close of a replica in a resource which is a physical entity. This means that the PEP will fire for any physical operation within this logical entity such as, for instance, a replication or an open for read.

I would recommend using an API PEP such as `pep_api_data_obj_put_post` with the `remote` directive as described before. The policy will execute on the client-connected server, but the policy to execute will be redirected to the server specified in the `remote` directive.

**Comment by yr-wang-hit** [comment]
Thanks for your helpful advice. @alanking  But how to get the physical host IP address from the parameters?
What is the difference between an API PEP like `pep_api_data_obj_put_post` and traditional PEP like `pep_resource_close_post` and something like `acPreProcForPut`?

Thanks again.

**Comment by alanking** [comment]
Of course!

You can get the hostname or IP of the resource in question via GenQuery. The attribute to select is `RESC_LOC`. There are other ways to get at this information but this is the most straightforward.

`pep_*_<pre|post|except|finally>` indicates a dynamic PEP. You can read about those here: https://docs.irods.org/4.2.10/plugins/dynamic_policy_enforcement_points/ `acPreProcForPut` is an example of a legacy static PEP. It is recommended to use dynamic PEPs over static PEPs.

**Comment by d-w-moore** [comment]
@yr-wang-hit  Truly sorry to have led you down a bit of a wrong path!  I think @alanking is onto the correct answer, and as he said above, RESC_LOC should contain that host IP or DNS name for the remote call. ALso, the `DATA_PATH` column of the GenQuery result can also be passed as a parameter to the remote rule to tell it the physical (filesystem) path _**on that remote machine,**_ for use in file operations such as Python's file `open`, etc....  You can experiment with the GenQuery syntax at the command line using `iquest`  to see how this works, for example:
```
$ iquest "%s/%s is on host '%s' at: '%s'" "select COLL_NAME, DATA_NAME, RESC_LOC, DATA_PATH where DATA_PATH like '%.jpg' "
```

**Comment by d-w-moore** [comment]
@yr-wang-hit The General Query (ie GenQuery) facility used in the iquest command is also available [in the Python rule engine](https://github.com/irods/irods_rule_engine_plugin_python#genquerypy) as well as [in the  iRODS rule language](https://docs.irods.org/4.1.5/manual/rule_language/#language-integrated-general-query).

**Comment by yr-wang-hit** [comment]
Thanks  @d-w-moore  and  @alanking , both your advices are valueable, I will give a try.
By the way, There is another question to consult you.

imagine the situation that multi-resource servers manage a single big physical storage(maybe ceph or glusterfs) . if we
create multiple resources using `iadmin mkresc` command in grid, how to distribute the IO streaming pressure to different resource servers?
for example, if we create 3 resources named ` r1 `, ` r2 `, ` r3 ` and have 2 resource servers ` server1 ` ,  ` server2 `
if we invoke some command like ` iput -R r1 a.txt `(maybe on a remote client) , what is the default policy to distribute the IO 
into the irods data grid? and how to balance the IO pressure so we can horizentally scaling the data grid by expanding the physical storage resource(create new resources) and adding resource servers?

Thanks a lot.

**Comment by d-w-moore** [comment]
@yr-wang-hit This has traditionally been handled by switching into a parallel transfer mode when large files are transferred using iput and iget.  Of course, this requires that the high ports (typically in the range 20000-20199) should be available on all resource servers, but we are working on getting versions of iput and iget (as well as calls within the Python iRODS Client library) that will manage this by initiating multiple threads of transfer from the client through port 1247 only.

**Comment by trel** [comment]
To balance IO pressure against many servers, you could arrange your iRODS resources under a `random` resource.

A more complete solution would be to have those iRODS resources (under the `random`) use a `detached` mode so that any server could answer the API request to access (put or get) the files that may reside on the single big physical storage.  You can read a bit of that discussion / proposal in https://github.com/irods/irods/issues/4421.

Is there anything actionable in this issue?  If not, we can close it soon.

**Comment by yr-wang-hit** [comment]
Thanks a lot and I will close the issue.
