### ISSUE TITLE
Deprecate all static policy enforcement points (PEPs)

### ISSUE THREAD

**Issue by alanking** [irods/irods#5951]
## Enhancement

Static PEPs are known to be problematic/inconsistent and cannot be fixed due to deployed code depending on the existing behavior. As they cannot be fixed, we are moving toward supporting only dynamic PEPs. Static PEPs should be deprecated and eventually removed (#5952).

Proposed solution:
1. In `applyRule`, lookup the rule name in the `static_policy_enforcement_points` map and log a warning if found for the administrator. Existing behavior will be upheld, but things will get noisy as static PEPs are executed.
2. The `core.re.template` and existing training should be updated to not call or depend on static PEPs. Otherwise, new, default installations will get really noisy.

**Comment by trel** [comment]
if anything, we should log a debug, rather than a warning.

but this is probably just a documentation exercise.

**Comment by korydraughn** [comment]
Handled as documentation.
