### ISSUE TITLE
Fix delay hints parser for "DOUBLE" directives

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#5964]
- [x] main
- [ ] 4-3-stable
---
## Bug Report
The delay hint `DOUBLE` directives produce non-deterministic results.
https://github.com/irods/irods/blob/970a4286ef2096a59707f415a00bf7e07f2dbbeb/lib/core/src/rcMisc.cpp#L1666-L1708

**Comment by MartinFlores751** [comment]
Closing. Merged in main and 4-3-stable.
