### ISSUE TITLE
`imkdir -p` noisy in logs when collection exists.

### ISSUE THREAD

**Issue by kript** [irods/irods#5979]
### iRODS Version, OS and Version

4.2.7
Ubuntu 18.04

### What did you try to do?

`imkdir -p /zone/collection/subcollection`

but as part of a parallel script uploading files single via `iput`, so twenty files all being uploaded at the same time, all doing `imkdir -p` at the rough same time.

### Expected behavior

first `imkdir` succeeds, the others are silent as collection then exists.
Having said that, this is pretty obviously a race condition. I'm not sure what the _right_ answer is here, so I thought I'd log the ticket.

### Observed behavior (including steps to reproduce, if applicable)

```
Oct 21 11:43:07 pid:1635 NOTICE: bindVar[1]=/humgen/projects/EXAMPLE
Oct 21 11:43:07 pid:1635 NOTICE: bindVar[2]=/humgen/projects/EXAMPLE/it3
Oct 21 11:43:07 pid:1635 NOTICE: bindVar[3]=mercury
Oct 21 11:43:07 pid:1635 NOTICE: bindVar[4]=humgen
Oct 21 11:43:07 pid:1635 NOTICE: bindVar[5]=
Oct 21 11:43:07 pid:1635 NOTICE: bindVar[6]=
Oct 21 11:43:07 pid:1635 NOTICE: bindVar[7]=
Oct 21 11:43:07 pid:1635 NOTICE: bindVar[8]=01634812986
Oct 21 11:43:07 pid:1635 NOTICE: bindVar[9]=01634812986
Oct 21 11:43:07 pid:1635 NOTICE: _cllExecSqlNoResult: SQLExecDirect error: -1 sql:insert into R_COLL_MAIN (coll_id, parent_coll_name, coll_name, coll_owner_name, coll_owner_zone, coll_type, coll_info1, coll_info2, create_ts, modify_ts) values (nextval('R_ObjectID'), ?, ?, ?, ?, ?, ?, ?, ?, ?)
Oct 21 11:43:07 pid:1635 NOTICE: SQLSTATE: S1010
Oct 21 11:43:07 pid:1635 NOTICE: SQLCODE: 0
Oct 21 11:43:07 pid:1635 NOTICE: SQL Error message: [unixODBC][Driver Manager]Function sequence error
Oct 21 11:43:07 pid:1635 NOTICE: SQLSTATE: 23505
Oct 21 11:43:07 pid:1635 NOTICE: SQLCODE: 1
Oct 21 11:43:07 pid:1635 NOTICE: SQL Error message: ERROR: duplicate key value violates unique constraint "idx_coll_main3";
Oct 21 11:43:07 pid:1635 NOTICE: chlRegColl cmlExecuteNoAnswerSql(insert) failure -809000
Oct 21 11:43:07 pid:1635 NOTICE: chlRegColl cmlExecuteNoAnswerSql(rollback) succeeded
```

**Comment by trel** [comment]
Within the server log... that function doesn't know *why* it was a duplicate, all it can do is complain.

I'm not sure there is anything to do differently here...

**Comment by trel** [comment]
revisiting, still think there's nothing to do - will close shortly without new insight/information.

**Comment by trel** [comment]
The server is doing all it can in the face of concurrent identical requests.   This could be mitigated on the client side by batching any 'similar-enough' requests to fire a single initial `imkdir -p`, and then fire off the concurrent `iput` commands... but that reduces independence/idempotence as the cost of cleaner logs.
