### ISSUE TITLE
provide client connection information to acPreConnect

### ISSUE THREAD

**Issue by trel** [irods/irods#5985]
- [x] main
- [x] 4-3-stable
---
## Feature

User requested to be able to determine whether to use SSL or not based on the incoming network connection (internal network or external).  Original thread at https://groups.google.com/g/irod-chat/c/3afhUiB2A0k.

This would be done within `acPreConnect()`, however, there is no connection information available to that PEP to make an internal/external determination.  It is handed a manufactured, empty `rei`.

https://github.com/irods/irods/blob/f615a350dc0b787e9140a61c501fdd7e765b40dc/server/core/src/irods_server_negotiation.cpp#L97-L110

Enhancement would be to inject the client connection information so that at least `$clientAddr` is available within `acPreConnect()`.

The `core.dvm` currently maps that as:
```
clientAddr||rei->rsComm->clientAddr
```

**Comment by trel** [comment]
also need to consider ramifications, if any... for the python rule engine plugin... i think injecting the code into the rei in the server will be enough.

**Comment by alanking** [comment]
Please cherry-pick to 4-3-stable, @MartinFlores751. Thanks!

**Comment by MartinFlores751** [comment]
Merged in main and 4-3-stable. Closing.
