### ISSUE TITLE
Eliminate calls to python scripts from native code

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#5987]
I have identified four places we are calling python scripts from native code in irods.
https://github.com/irods/irods/blob/7518787686ff61fe87fde2b96e1d70c91389c0fa/server/api/src/rsServerReport.cpp#L254-L257
https://github.com/irods/irods/blob/7518787686ff61fe87fde2b96e1d70c91389c0fa/server/api/src/rsServerReport.cpp#L265-L268
https://github.com/irods/irods/blob/7518787686ff61fe87fde2b96e1d70c91389c0fa/server/core/src/irods_server_control_plane.cpp#L206-L210
https://github.com/irods/irods/blob/7518787686ff61fe87fde2b96e1d70c91389c0fa/server/core/src/irods_server_control_plane.cpp#L356-L360
These calls should be replaced with C/C++ implementations of the required functionality or removed altogether.

- `rsServerReport.cpp`: Call to `system_identification.py` with arg `os_distribution_name`
- `rsServerReport.cpp`: Call to `system_identification.py` with arg `os_distribution_version`
- [x] `irods_server_control_plane.cpp`: Call to `kill_pid.py`
- irods_server_control_plane.cpp`: Call to `pid_age.py`

**Comment by korydraughn** [comment]
The files/functions referenced by this issue were removed by #7988.
- `pid_age.py`
- `kill_pid.py`
- `irods_server_control_plane.cpp` _(the control plane has been removed entirely)_
- `get_script_output_single_line`

We'll leave the files in iRODS 4.

**Comment by trel** [comment]
So this should be moved to 5.0.0?

**Comment by korydraughn** [comment]
Well, I'm not sure it should be 5.0.

The commit appears to be part of 4-3-stable.

**Comment by trel** [comment]
Oh I see.  Interesting.

Yes - agreed.  Leave this the way it is.

**Comment by SwooshyCueb** [comment]
the only commit referencing this issue in 4-3-stable only removes calls to one python script. The majority of this issue has not been addressed in 4-3-stable.

**Comment by korydraughn** [comment]
Correct. Renaming this issue so it's specifically about `kill_pid.py`.
