### ISSUE TITLE
Info about iRODS version

### ISSUE THREAD

**Issue by gmuscianisi** [irods/irods#6005]
Dear all, 

I would like to know which version of iRODS can be installed on server with CentOS 7.2.1511 as base OS. 

Thanks in advance. Best regards. Giusy

**Comment by korydraughn** [comment]
iRODS 4.2.x supports Ubuntu 16, Ubuntu 18, and CentOS 7.

The latest release is 4.2.10 which you can install from https://packages.irods.org.

For more information, see https://docs.irods.org.
