### ISSUE TITLE
An error occurred using icommand

### ISSUE THREAD

**Issue by mofisl** [irods/irods#6007]
## Feature

- Please describe the feature you are requesting and your use case.
Dear scientific researcher:
         An error occurred when I used the icommand connection
         After iinit, enter the password

OR

## Bug Report
ERROR: connectToRhost: readVersion to data.cyverse.org failed, msg=
[-]	iRODS/lib/core/src/sockComm.cpp:615:readVersion :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message []
	[-]	iRODS/lib/core/src/sockComm.cpp:199:readMsgHeader :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']
		[-]	libtcp.cpp:197:tcp_read_msg_header :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [only read [0] of [4]]

 status = -4000 SYS_HEADER_READ_LEN_ERR
ERROR: _rcConnect: connectToRhost error, server on data.cyverse.org:1247 is probably down status = -4000 SYS_HEADER_READ_LEN_ERR

### iRODS Version, OS and Version

irods-icommands-4.1.10-centos-6

### What did you try to do?

I need icommand to download the genetic data from cyverse's public database

**Comment by trel** [comment]
This appears to be a networking or versioning or configuration issue between you and CyVerse.

Please work with their support to get you connected: https://cyverse.org/get-help
