### ISSUE TITLE
controller.py loses track of descendant processes if grandpa goes away

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#6014]
When `controller.py` tries to stop the server, it will check the pidfile for grandpa's pid, and use this to find grandpa and descendants that match our server executables. If the server fails to shut down gracefully in a timely manner, it will kill all these processes manually. However, if grandpa shuts down but the descendants do not, `controller.py` loses track of them and assumes everything is all shut down.

**Comment by trel** [comment]
two commits have landed in master/main.

@korydraughn @SwooshyCueb should this move to 4.3.0?    or important to get into the 4.2.x series?

**Comment by korydraughn** [comment]
I think this is a 4.3 thing. The shutdown process needs to be reviewed. It feels wrong to have a script kill child processes when the server is perfectly capable of doing that.

**Comment by SwooshyCueb** [comment]
Yeah should probably be 4.3.

If there are any child processes left for the script to kill after a successful graceful shutdown, that's probably a bug. Under normal circumstances, the server *does* clean up its own children (or it's supposed to, anyway, by my understanding). The child-killing functionality in the script only kicks in if something goes wrong or the shutdown times out.

**Comment by trel** [comment]
sold.
