### ISSUE TITLE
Add new options for build/test hooks

### ISSUE THREAD

**Issue by alanking** [irods/irods#6020]
- [x] irods-auth-plugin-krb (main)
- [x] irods-auth-plugin-krb (4-2-stable)
- [x] irods-microservice-plugins-curl (main)
- [x] irods-microservice-plugins-curl (4-2-stable)
- [x] irods-resource-plugin-s3 (main)
- [x] irods-resource-plugin-s3 (4-2-stable)
- [x] irods-rule-engine-plugin-audit-amqp (main)
- [x] irods-rule-engine-plugin-audit-amqp (4-2-stable)
- [x] irods-rule-engine-plugin-indexing (main)
- [x] irods-rule-engine-plugin-indexing (4-2-stable)
- [x] irods-rule-engine-plugin-logical-quotas (main)
- [x] irods-rule-engine-plugin-logical-quotas (4-2-stable)
- [x] irods-rule-engine-plugin-metadata-guard (main)
- [x] irods-rule-engine-plugin-metadata-guard (4-2-stable)
- [x] irods-rule-engine-plugin-python (main)
- [x] irods-rule-engine-plugin-python (4-2-stable)
- [x] irods-rule-engine-plugin-unified-storage-tiering (main)
- [x] irods-rule-engine-plugin-unified-storage-tiering (4-2-stable)
---
## Feature

Add an option to the build hook to specify where build artifacts should go. If nothing is provided, the existing behavior (a temporary directory) should be executed. `--output_root_directory` is currently the only option and it determines to where built packages will be copied.

This should be done for all currently supported plugins as well.

**Comment by trel** [comment]
please make some checkboxes for the list of plugins we shouldn't miss...

**Comment by trel** [comment]
bueno.

**Comment by alanking** [comment]
Please close #6083 when closing this.

**Comment by trel** [comment]
ah, yes, i see.
