### ISSUE TITLE
`ilsresc` silently defaults to local zone when given non-existent zone.

### ISSUE THREAD

**Issue by kript** [irods/irods#6022]
- [x] main
- [x] 4-2-stable
---------

### iRODS Version, OS and Version

4.2.7 

### What did you try to do?

`ilsresc -z ThisZoneDoesntExist`

### Expected behavior

error message saying "ThisZoneDoesntExist"... doesn't exist.

### Observed behavior (including steps to reproduce, if applicable)

Resources from 'home' Zone displayed instead.

**Comment by kjsanger** [comment]
Also present in 4.2.10 and recent HEAD of 4-2-stable.

**Comment by trel** [comment]
Agreed - this should produce an error.

**Comment by korydraughn** [comment]
Based on the code, the argument passed via the `-z` flag is never used. The resolved path of `.` is used as the zone hint.
https://github.com/irods/irods/blob/abb809040485326855ffffbda1883dc99a432379/lib/core/src/lsUtil.cpp#L40
Not only that, but the zone hint is changed for each path.

**Comment by korydraughn** [comment]
@kript Just to clarify, both `ils` and `ilsresc` have a problem when using the `z` option?

**Comment by korydraughn** [comment]
My guess is that the `ils` is a typo since it does not advertise a `-z` option.

**Comment by kript** [comment]
yeah, I'm a muppet - its just `ilsresc`

**Comment by trel** [comment]
updated the original text.

**Comment by trel** [comment]
checkboxed.
