### ISSUE TITLE
ifsck help implies multiple paths on command line allowed

### ISSUE THREAD

**Issue by tedgin** [irods/irods#6051]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---

In version 4.2.8, `ifsck -h` output implies that multiple paths to check may be provided on the command line, but if `ifsck` is provided multiple paths, it generates an error message saying only one is allowed.

```bash
[irods@r03c06u25-ds20 ~]$ ifsck -h
Usage: ifsck [-hKrR] srcPhysicalFile|srcPhysicalDirectory ... 

...
```
```bash
[irods@r03c06u25-ds20 ~]$ ifsck /irods_vault/ds20/home/tedgin/multiqc.html /irods_vault/ds20/home/tedgin/ssa01.png
remote addresses: 206.207.252.77 ERROR: fsckObj: gave 2 input source path, should give one and only one
```

**Comment by trel** [comment]
We're running through testing for 4.2.11 at the moment.   If we find something else we need to fix, I'll pull this in as well.

**Comment by tedgin** [comment]
That works for me.  I guess it depends on whether or not `ifsck` was intended to allow multiple paths as input.

**Comment by trel** [comment]
Right.

It's a lot easier to reason about results and return codes with a single input.

**Comment by tedgin** [comment]
Yep!
