### ISSUE TITLE
Stopping already stopped service returns error

### ISSUE THREAD

**Issue by scimerman** [irods/irods#6053]
- [x] master
- [x] 4-2-stable
--------

https://github.com/irods/irods/blob/32cc2bd18e43aaaa42f002d07996343a05066646/packaging/irods#L53

The sysv init script on our irods give a non-zero return value if the stopped service is tried to be stopped again. 
```
    $ service irods stop
    No iRODS servers running.
    rm: cannot remove ‘/var/lock/subsys/irods’: No such file or directory
```
I don't think this should return an error, as it only makes more problems with the rest of automation systems...
I think this is a small bug with an easy fix, so I would suggest instead
`    if [ "$DETECTEDOS" = "RedHatCompatible" -o "$DETECTEDOS" = "SuSE" ]; then`
to
`    if [ "$DETECTEDOS" = "RedHatCompatible" -o "$DETECTEDOS" = "SuSE" ] && [ -e /var/lock/subsys/irods ]; then`
this already works nicely on one of my system.

**Comment by trel** [comment]
Thanks for the report!

Can you share your OS/Version for this machine as well as what version of iRODS you're running?

**Comment by scimerman** [comment]
We are running irods-server-4.2.10-1.x86_64 on top of our CentOS Linux release 7.9.2009 (Core).

**Comment by trel** [comment]
Ah, I see... so... can you confirm the following tweak also works to avoid this issue?

```diff
--- a/packaging/irods
+++ b/packaging/irods
@@ -51,7 +51,7 @@ start)
 stop)
     su $SU_SHELL_OPTS $IRODS_SERVICE_ACCOUNT_NAME -c "$IRODS_CTL stop"
     if [ "$DETECTEDOS" = "RedHatCompatible" -o "$DETECTEDOS" = "SuSE" ] ; then
-        rm /var/lock/subsys/irods
+        rm -f /var/lock/subsys/irods
     fi
     ;;
 restart)
```

**Comment by scimerman** [comment]
Sure thing. Here it goes.
```
[root@umcg-icat01 ~]# sed -n "51,56p" /etc/init.d/irods
stop)
    su $SU_SHELL_OPTS $IRODS_SERVICE_ACCOUNT_NAME -c "$IRODS_CTL stop"
    if [ "$DETECTEDOS" = "RedHatCompatible" -o "$DETECTEDOS" = "SuSE" ]; then
        rm -f /var/lock/subsys/irods
    fi
    ;;
[root@umcg-icat01 ~]# service irods stop
No iRODS servers running.
[root@umcg-icat01 ~]# service irods stop
No iRODS servers running.
```
I can confirm that your solution works just as well :+1:

**Comment by trel** [comment]
Excellent.  Thanks.
