### ISSUE TITLE
Do not create "rodsadmin" group on new installs

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#6063]
## Bug Report
Having a user type and group called **rodsadmin** is very confusing and can lead users to making incorrect assumptions about the system.

The purpose of the **rodsadmin** group is not known and does not provide any special properties as far as the system is concerned.

On upgrade of an existing deployment, this group will be left in place.

**Comment by trel** [comment]
It appears to never have been populated automatically - I think we can not create it on install any longer.

https://github.com/irods/irods_rule_engine_plugin_logical_quotas/issues/46#issuecomment-994985761

**Comment by trel** [comment]
Yes, this is correct.   Any user can be of type 'rodsadmin'.

You can make any groups you want for the users, but being in a group never conveyed any permissions/power, directly.    This new install makes that clearer.
