### ISSUE TITLE
exception failure when talking cross federation to a client zone whose SSL certificate has expired

### ISSUE THREAD

**Issue by kript** [irods/irods#6068]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---
### iRODS Version, OS and Version

4.2.7
Ubuntu 18.04

### What did you try to do?

run `ils /remotezone` when the remote zone has an expired SSL certificate

### Expected behavior

A message that indicates SSL connection to the remote zone has failed.

### Observed behavior (including steps to reproduce, if applicable)

```
ils /<remoteZone>/home/me
terminating with uncaught exception of type irods::experimental::filesystem::filesystem_error: cannot get status: Unknown error -2103000
Aborted (core dumped)
```

**Comment by trel** [comment]
It got so close...

```
$ ierror 2103000
irods error: -2103000 SSL_HANDSHAKE_ERROR 
```

Just apparently core dumped before getting the error back out.
