### ISSUE TITLE
itree fails with exception on relative path '..' or '../some/path'

### ISSUE THREAD

**Issue by stsnel** [irods/irods#6075]
- [x] main - server
- [x] main - icommands
- [x] 4-2-stable - server
- [x] 4-2-stable - icommands
--------

In iRODS 4.2.11 on Ubuntu 18.04, the itree command fails with an exception when it is run against relative path ".." or "../some/path"

**Observed behaviour**

> $ itree ..
> terminating with uncaught exception of type irods::experimental::filesystem::filesystem_error: could not open collection for 
> reading: Unknown error -310000
> Aborted (core dumped)

**Expected behaviour**

itree shows the tree of the relative path

**Notes**

* itree also fails with the same exception when it runs against "./some/path" or a non-existing path, but that's more of a cosmetic thing.
* It's a very useful command, thanks for adding it!

**Comment by korydraughn** [comment]
need to check the **4-2-stable - server** checkbox
