### ISSUE TITLE
Bump externals in jenkins CI hook scripts

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#6083]
Several repositories specify the externals packages they need in a CI hooks script. Now that we have updated many of our externals packages, these scripts should also be updated.

**Comment by alanking** [comment]
I *think* this has been completed for most of the repositories. The work for #6020 has proven that all of the shipped plugins build for main after their externals were bumped. What else should we do?

**Comment by trel** [comment]
I think we're good if the dots are happy.

**Comment by alanking** [comment]
Okay, then I think we should consider this tied to the other issue and close them together.

**Comment by trel** [comment]
#6020 is currently in the 4.2.12 milestone, rather than 4.3.0.    so if we tie them together, they should be in the same one?   or we just close each, independently... at the same time?

**Comment by alanking** [comment]
Yep, that

**Comment by trel** [comment]
okay... "close each, independently... at the same time".    sold.
