### ISSUE TITLE
Prevent checksum verification in sync-to-archive operations

### ISSUE THREAD

**Issue by alanking** [irods/irods#6089]
- [x] main
- [x] 4-2-stable
---
When replication occurs in a sync-to-archive operation, a checksum verification will be performed for replicas whose source replica contains a checksum. This will fail for most actual archive resources with `DIRECT_ARCHIVE_ACCESS`, and the checksum from the source replica will be applied to the destination replica (even if it is not true).

The `NO_COMPUTE_KW` should be used when finalizing the replica to indicate that a checksum should not be computed for the destination replica. Should a checksum be desired, policy can be defined to calculate or simply apply a checksum value to the replica's system metadata.

See this thread: https://github.com/irods/irods/issues/5927#issuecomment-1004941707

**Comment by trel** [comment]
moving to 4.2.12 as it's immediately useful/helpful for tape-based workflows.

**Comment by korydraughn** [comment]
Re-opened to fix test ...

test_isysmeta.py needs: `from __future__ import print_function`

**Comment by alanking** [comment]
Did you mean to open #6181?

**Comment by korydraughn** [comment]
i opened this one because of this commit: a5529aa4434a72df53f34e552bbc38576a521693

**Comment by korydraughn** [comment]
You're right. I need to re-open the one you referenced.

Thanks.

**Comment by alanking** [comment]
All referenced tests pass on main, last I tried it
