### ISSUE TITLE
admin replication of user data and checksum computation

### ISSUE THREAD

**Issue by ciklysta** [irods/irods#6118]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---
## Bug Report

Irods version 4.2.11, centos7

I have two resources
- _OldResource_
- _NewResource_

There is a lot of old data on _OldResource_ that I want to replicate to _NewResource_. Along that process I want to add checksums for further checks.

Those data objects are owned by a normal user and don't have checksums in the catalog:
```
# ils -A /nkZone/file.zip
  /nkZone/file.zip
        ACL - ltp-dev#nkZone:own
```

Our policy has changed and from now on, we want to compute checksums for all new objects (new objects are saved to _NewResource_). I have created this rule:
```
acPostProcForPut {
    msiDataObjChksum($objPath, "", *chkSum);
}
```

If I try to replicate an object from _OldResource_ to _NewResource_ as an admin
```
irepl -M -S OldResource -R NewResource /nkZone/file.zip
```
It replicates the data correctly, but doesn"t compute the checksum as intended (and violates the rule).

It returns
```
line 709, col 4, rule base core
    msiDataObjChksum($objPath, "", *NewChkSum);
    ^

caused by: DEBUG: msiDataObjChksum: rsDataObjChksum failed for /nkZone/file.zip, status = -818000
```

If I run `irepl` under the user that owns the file, checksum is correctly computed and stored. It seems the information that a superuser executes given action, is not propagated downwards to all subsequent rules and some acl check doesn't pass.

**Comment by trel** [comment]
Yes, this is a permissions issue...
```
$ ierror 818000
irods error: -818000 CAT_NO_ACCESS_PERMISSION
```

Confirmed with the dynamic PEP as well...

```
pep_api_data_obj_repl_post(*INSTANCE_NAME, *COMM, *DATAOBJINP, *TRANSFER_STAT){
    msiDataObjChksum(*DATAOBJINP.obj_path, "", *chkSum);
}
```


A workaround could be to run `ichksum -M` directly on the items needing checksums rather than depending on the PEP.

**Comment by trel** [comment]
This could be just that `msiDataObjChksum()` needs to learn to honor the admin keyword (`irodsAdmin`).

**Comment by alanking** [comment]
`msiDataObjChksum` now supports the `ADMIN_FLAG` ("irodsAdmin"). It is up to the policy implementer to specify this, in much the same way that `ichksum` requires the `-M` option. Closing.
