### ISSUE TITLE
iCommands fail to build on main

### ISSUE THREAD

**Issue by alanking** [irods/irods#6120]
### iRODS Version, OS and Version
main

### What did you try to do?
Build iCommands

### Expected behavior
Built iCommands

### Observed behavior (including steps to reproduce, if applicable)
CMake displays the following message for each of the ~50 iCommands:
```
CMake Error at CMakeLists.txt:194 (add_executable):
  Target "<icommand name here>" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```

**Comment by alanking** [comment]
Simply adding this line to the `CMakeLists.txt` seems to fix the issue. @SwooshyCueb, does this seem like a reasonable fix?

**Comment by SwooshyCueb** [comment]
Looks good to me
