### ISSUE TITLE
Add support for ADMIN_KW to filesystem metadata API functions

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#6124]
- [x] main
- [x] 4-2-stable
---
## Enhancement
https://github.com/irods/irods/blob/74caef2e2cc6b0589d1601c6c822304541c591af/lib/filesystem/include/filesystem/filesystem.hpp#L218-L220
https://github.com/irods/irods/blob/74caef2e2cc6b0589d1601c6c822304541c591af/lib/filesystem/include/filesystem/filesystem.hpp#L230

**Comment by korydraughn** [comment]
This requires changes to the packing instruction, rs* API call, chl* API call, and database plugin.

**Comment by trel** [comment]
can we do that without breaking 4.2.11 and prior clients?

**Comment by korydraughn** [comment]
Yes. It would be accomplished in the same way as the Ticket API.

We append a new KeyValPair to the input structure and packing instruction. Then we update the internal server calls to accept a KeyValPair.

Communication with old servers is fine because they ignore the new arguments.

**Comment by trel** [comment]
good ol' KeyValPair.
