### ISSUE TITLE
rodsadmin can downgrade their own user type

### ISSUE THREAD

**Issue by trel** [irods/irods#6127]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---
### iRODS Version, OS and Version

4.2.11

### What did you try to do?

modify the user type of the logged-in rodsadmin user, expecting it not to work.

### Expected behavior

it should be prevented, expected a `SYS_NOT_SUPPORTED` error

### Observed behavior (including steps to reproduce, if applicable)

it totally worked... and then of course, was locked out of doing rodsadmin things.

```
$ iadmin lz
tempZone
$ iadmin moduser $(jq -r '.irods_user_name' .irods/irods_environment.json) type rodsuser
$ echo $?
0
$ iadmin lz
remote addresses: 127.0.0.1 ERROR: rcSimpleQuery failed with error -13000 SYS_NO_API_PRIV
```

bonus surprise points for downgrading the rodsadmin account that is configured to run the iRODS server itself.

**Comment by trel** [comment]
bonus surprise now covered by https://github.com/irods/irods/issues/6128

**Comment by phdavis1027** [comment]
Addresed by PR #309 in the icommands repo
