### ISSUE TITLE
rodsadmin should not be allowed to downgrade user type of another rodsadmin operating an irods-server

### ISSUE THREAD

**Issue by trel** [irods/irods#6128]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---
## Feature

The `iadmin moduser` command / API should not be allowed to downgrade a fellow `rodsadmin` account if that account is currently operating an irods-server in the same Zone.

This would require the 'modify user' operation to reach out to all other servers in the Zone to produce a list of rodsadmin accounts operating those servers.  If the to-be-downgraded rodsadmin account is in that list, the operation is stopped/prevented, perhaps with `SYS_NOT_ALLOWED`.

**Comment by alanking** [comment]
@korydraughn - We should probably pull this into 4.2.12 or 4.3.1.
