### ISSUE TITLE
`iexit full` can remove `.irodsA` file for service account

### ISSUE THREAD

**Issue by alanking** [irods/irods#6136]
- [x] main (iexit)
- [x] 4-3-stable (iexit)
- [x] 4-2-stable (iexit)
- [x] main (irods_docs)
- [x] 4-2-stable (irods_docs)
---
It is possible to run `iexit full` as the iRODS service account. This removes the `.irodsA` file. The environment of the service account is the means by which the server communicates with itself, authenticated as the "main" `rodsadmin` iRODS user using the `.irodsA` file.

If `iinit` is run again before restarting the server, the service account's iRODS user can authenticate again and things return to normal. If the server is restarted after running `iexit full`, the server will stand up, but new connections cannot be established with it.

Should an administrator get into this situation, `iinit` can be run as usual and the password entered to generate the `.irodsA` file again after waiting for the connection to fail. The server can then be restarted and things will return to normal.

So, two things need to happen:
1. This situation should be documented in the Troubleshooting section of the documentation.
2. `iexit` should detect this situation and prevent it from happening.

**Comment by alanking** [comment]
@SwooshyCueb - Are you planning to update the documentation for this issue? If not, I can take that piece. Up to you.

**Comment by SwooshyCueb** [comment]
@alanking I'll let you handle that, thanks.

Also, I just noticed I forgot to put a newline at the end of the `fprintf` in the catch block of `iexit` so let's untick those boxes until I get PRs in to fix that.

**Comment by SwooshyCueb** [comment]
We can tick the boxes and close this issue now

**Comment by korydraughn** [comment]
One of the `iexit` tests is failing. I have the fix in my JSON PR. Let's leave this open until the JSON microservice PR is merged into 4-2-stable.

**Comment by SwooshyCueb** [comment]
roger dodger

**Comment by korydraughn** [comment]
Then again, I'm going to add a new test that shows that a warning is produced when `iexit full` is run.

**Comment by korydraughn** [comment]
This can now be closed. Go team!
