### ISSUE TITLE
fatal error when building in rocky linux

### ISSUE THREAD

**Issue by peggy0135** [irods/irods#6157]
## Feature

I tried to build with 4-2-stable source code but when I tried to "make non-package-install-postgres"
but I got messages bellow

[  0%] Building CXX object CMakeFiles/irods_plugin_dependencies_functions.dir/lib/core/src/apiHandler.cpp.o
In file included from /root/irods/lib/core/src/apiHandler.cpp:3:
In file included from /root/irods/lib/core/include/apiHandler.hpp:12:
In file included from /root/irods/server/re/include/irods_re_namespaceshelper.hpp:4:
In file included from /root/irods/lib/core/include/irods_server_properties.hpp:6:
/root/irods/lib/core/include/irods_configuration_parser.hpp:19:10: fatal error: 'json.hpp' file not found
#include "json.hpp"
         ^~~~~~~~~~
1 error generated.
make[3]: *** [CMakeFiles/irods_plugin_dependencies_functions.dir/build.make:76: CMakeFiles/irods_plugin_dependencies_functions.dir/lib/core/src/apiHandler.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:1090: CMakeFiles/irods_plugin_dependencies_functions.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:685: CMakeFiles/non-package-install-postgres.dir/rule] Error 2
make: *** [Makefile:215: non-package-install-postgres] Error 2

PS: I tried to install the package "irods-externals-json3.10.4-0-1.0-1.x86_64.rpm" in irods-external to solve it but it did not work
Is there anything I did wrong or missed?

Thank you.

**Comment by trel** [comment]
4-2-stable doesn't build on rocky linux.

we are targeting rocky linux 8 with the main branch, which will become 4.3.0

**Comment by peggy0135** [comment]
Thank you, that's my misunderstanding that use the new version for porting
