### ISSUE TITLE
build error on rocky linux

### ISSUE THREAD

**Issue by peggy0135** [irods/irods#6158]
I tried to build with the main branch. When I tried to use the main branch "irods-externals" and main branch "irods", I got the messages bellow. I tried to fixed it with installing the "irods-externals-fmt8.1.1-0-1.0-1.x86_64.rpm" and "irods-externals-spdlog1.9.2-1-1.0-1.x86_64.rpm" but still not working.
Is it a problem with c++11 because I build "irods-externals" with c++11 (followed the README on github)
Thank you.

```
Consolidate compiler generated dependencies of target irods_server
[ 37%] Building CXX object CMakeFiles/irods_server.dir/server/core/src/catalog_utilities.cpp.o
In file included from /root/irods/server/core/src/catalog_utilities.cpp:5:
In file included from /root/irods/server/core/include/miscServerFunct.hpp:137:
In file included from /root/irods/lib/core/include/irods_plugin_base.hpp:12:
In file included from /root/irods/server/re/include/irods_re_namespaceshelper.hpp:4:
In file included from /root/irods/lib/core/include/irods_server_properties.hpp:15:
In file included from /tmp/irods-externals/fmt8.1.1-0/include/fmt/format.h:48:
/tmp/irods-externals/fmt8.1.1-0/include/fmt/core.h:1727:3: error: static_assert failed due to requirement 'formattable' "Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt"
  static_assert(
  ^
/tmp/irods-externals/fmt8.1.1-0/include/fmt/core.h:1853:23: note: in instantiation of function template specialization 'fmt::detail::make_arg<true, fmt::basic_format_context<fmt::appender, char>, fmt::detail::type::custom_type, const irods::experimental::catalog::entity_type &, 0>' requested here
        data_{detail::make_arg<
                      ^
/tmp/irods-externals/fmt8.1.1-0/include/fmt/core.h:1872:10: note: in instantiation of function template specialization 'fmt::format_arg_store<fmt::basic_format_context<fmt::appender, char>, irods::experimental::catalog::entity_type>::format_arg_store<const irods::experimental::catalog::entity_type &>' requested here
  return {std::forward<Args>(args)...};
         ^
/tmp/irods-externals/fmt8.1.1-0/include/fmt/core.h:3119:28: note: in instantiation of function template specialization 'fmt::make_format_args<fmt::basic_format_context<fmt::appender, char>, const irods::experimental::catalog::entity_type &>' requested here
  return vformat(fmt, fmt::make_format_args(args...));
                           ^
/root/irods/server/core/include/irods_logger.tpp:136:70: note: in instantiation of function template specialization 'fmt::format<const irods::experimental::catalog::entity_type &>' requested here
            const auto msg = {log::key_value{tag::log::message, fmt::format(_format, std::forward<Args>(_args)...)}};
                                                                     ^
/root/irods/server/core/src/catalog_utilities.cpp:120:37: note: in instantiation of function template specialization 'irods::experimental::log::logger<irods::experimental::log::category::database>::impl<irods::experimental::log::level::error>::operator()<const irods::experimental::catalog::entity_type &>' requested here
                log::database::error("Invalid entity type [entity_type => {}]", _entity_type);
                                    ^
1 error generated.
make[3]: *** [CMakeFiles/irods_server.dir/build.make:2106: CMakeFiles/irods_server.dir/server/core/src/catalog_utilities.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:1100: CMakeFiles/irods_server.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:747: CMakeFiles/non-package-install-postgres.dir/rule] Error 2
make: *** [Makefile:215: non-package-install-postgres] Error 2
```

**Comment by korydraughn** [comment]
The CMakeLists.txt file for the server needs a tweak to the version of the expected fmt library.

Change the following line so that it references the same version number as the irods-externals-fmt package you built (i.e. `FMT fmt8.1.1-0`).
https://github.com/irods/irods/blob/ed6328646cee87182098d569919004049bf4ce21/CMakeLists.txt#L25

**Comment by peggy0135** [comment]
I tried , but not working

my modified CMakeLists.txt:
IRODS_MACRO_CHECK_DEPENDENCY_SET_FULLPATH_ADD_TO_IRODS_PACKAGE_DEPENDENCIES_LIST(ARCHIVE libarchive3.5.2-0)
IRODS_MACRO_CHECK_DEPENDENCY_SET_FULLPATH_ADD_TO_IRODS_PACKAGE_DEPENDENCIES_LIST(AVRO avro1.11.0-1)
IRODS_MACRO_CHECK_DEPENDENCY_SET_FULLPATH_ADD_TO_IRODS_PACKAGE_DEPENDENCIES_LIST(BOOST boost1.78.0-0)
IRODS_MACRO_CHECK_DEPENDENCY_SET_FULLPATH_ADD_TO_IRODS_PACKAGE_DEPENDENCIES_LIST(FMT fmt8.1.1-0)
IRODS_MACRO_CHECK_DEPENDENCY_SET_FULLPATH_ADD_TO_IRODS_PACKAGE_DEPENDENCIES_LIST(NANODBC nanodbc2.13.0-1)
IRODS_MACRO_CHECK_DEPENDENCY_SET_FULLPATH_ADD_TO_IRODS_PACKAGE_DEPENDENCIES_LIST(ZMQ zeromq4-14.1.8-0)

IRODS_MACRO_CHECK_DEPENDENCY_SET_FULLPATH_ADD_TO_IRODS_DEVELOP_DEPENDENCIES_LIST(CATCH2 catch22.13.8-0)
IRODS_MACRO_CHECK_DEPENDENCY_SET_FULLPATH_ADD_TO_IRODS_DEVELOP_DEPENDENCIES_LIST(CPPZMQ cppzmq4.8.1-1)
IRODS_MACRO_CHECK_DEPENDENCY_SET_FULLPATH_ADD_TO_IRODS_DEVELOP_DEPENDENCIES_LIST(JSON json3.10.4-0)
IRODS_MACRO_CHECK_DEPENDENCY_SET_FULLPATH_ADD_TO_IRODS_DEVELOP_DEPENDENCIES_LIST(SPDLOG spdlog1.9.2-1)

**Comment by korydraughn** [comment]
Please share the build error you received.

**Comment by peggy0135** [comment]
hi @korydraughn 
do you mean this message below or what steps I tried?

[ 54%] Building CXX object CMakeFiles/irods_server.dir/server/core/src/catalog_utilities.cpp.o
In file included from /root/irods/server/core/src/catalog_utilities.cpp:5:
In file included from /root/irods/server/core/include/miscServerFunct.hpp:137:
In file included from /root/irods/lib/core/include/irods_plugin_base.hpp:12:
In file included from /root/irods/server/re/include/irods_re_namespaceshelper.hpp:4:
In file included from /root/irods/lib/core/include/irods_server_properties.hpp:15:
In file included from /tmp/irods-externals/fmt8.1.1-0/include/fmt/format.h:48:
/tmp/irods-externals/fmt8.1.1-0/include/fmt/core.h:1727:3: error: static_assert failed due to requirement 'formattable' "Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt"
  static_assert(
  ^
/tmp/irods-externals/fmt8.1.1-0/include/fmt/core.h:1853:23: note: in instantiation of function template specialization 'fmt::detail::make_arg<true, fmt::basic_format_context<fmt::appender, char>, fmt::detail::type::custom_type, const irods::experimental::catalog::entity_type &, 0>' requested here
        data_{detail::make_arg<
                      ^
/tmp/irods-externals/fmt8.1.1-0/include/fmt/core.h:1872:10: note: in instantiation of function template specialization 'fmt::format_arg_store<fmt::basic_format_context<fmt::appender, char>, irods::experimental::catalog::entity_type>::format_arg_store<const irods::experimental::catalog::entity_type &>' requested here
  return {std::forward<Args>(args)...};
         ^
/tmp/irods-externals/fmt8.1.1-0/include/fmt/core.h:3119:28: note: in instantiation of function template specialization 'fmt::make_format_args<fmt::basic_format_context<fmt::appender, char>, const irods::experimental::catalog::entity_type &>' requested here
  return vformat(fmt, fmt::make_format_args(args...));
                           ^
/root/irods/server/core/include/irods_logger.tpp:136:70: note: in instantiation of function template specialization 'fmt::format<const irods::experimental::catalog::entity_type &>' requested here
            const auto msg = {log::key_value{tag::log::message, fmt::format(_format, std::forward<Args>(_args)...)}};
                                                                     ^
/root/irods/server/core/src/catalog_utilities.cpp:120:37: note: in instantiation of function template specialization 'irods::experimental::log::logger<irods::experimental::log::category::database>::impl<irods::experimental::log::level::error>::operator()<const irods::experimental::catalog::entity_type &>' requested here
                log::database::error("Invalid entity type [entity_type => {}]", _entity_type);
                                    ^
1 error generated.
make[3]: *** [CMakeFiles/irods_server.dir/build.make:2106: CMakeFiles/irods_server.dir/server/core/src/catalog_utilities.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:1100: CMakeFiles/irods_server.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:747: CMakeFiles/non-package-install-postgres.dir/rule] Error 2
make: *** [Makefile:215: non-package-install-postgres] Error 2

**Comment by korydraughn** [comment]
the errors have to do with the logger not being compatible with the changes to fmt.

try compiling this PR: #6153 

it contains updates to the logger and a few other things.

**Comment by peggy0135** [comment]
thank you,
I am still trying with #6153

**Comment by peggy0135** [comment]
"[100%] Built target non-package-install-postgres"

but just need to complie some plugin or .so file manually
I will keep trying
Thank you.
