### ISSUE TITLE
Package unit tests

### ISSUE THREAD

**Issue by alanking** [irods/irods#6164]
- [x] main
- [x] 4-2-stable
---
## Feature

Inspired by https://github.com/irods/irods_testing_environment/issues/28

Open questions...
1. Where should the unit tests go? `$IRODS_HOME/unit_tests`?
2. What should be in the package? Just the executables? Should there be a script for running the list of tests, a la `scripts/run_tests.py`?
3. What should the package be named? `irods-unittests`?

**Comment by trel** [comment]
cool.
