### ISSUE TITLE
`iadmin rum` functionality can be invoked by non-admins

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#6183]
- [x] main
- [x] 4-2-stable
---
## Bug Report
Removing unused AVUs is an admin-level operation as it affects an entire zone. rodsusers cannot invoke this operation via the `iadmin` command because it is protected by the API lookup routines. However, a rodsuser can invoke the operation via `irule` and `msiDeleteUnusedAVUs()`.

See https://github.com/irods/irods/pull/6156#discussion_r807273133

**Comment by trel** [comment]
curious that it's not listed as "admin only"...

https://docs.irods.org/4.2.11/doxygen/

and https://docs.irods.org/4.2.11/doxygen/icatGeneralMS_8cpp.html#af794fdfe6a14287c27da788dd5a8d4a1 says:

> See 'iadmin help rum'. Do not call this directly.

**Comment by korydraughn** [comment]
Yes, it also contains a note stating to not invoke the msi directly.

**Comment by korydraughn** [comment]
And I see you already quoted that part.
