### ISSUE TITLE
add delay server memory usage default to server_config.json on upgrade

### ISSUE THREAD

**Issue by trel** [irods/irods#6193]
- [x] main
- [x] 4-2-stable
----------

## Feature

`maximum_size_of_delay_queue_in_bytes` should be added to the advanced_settings of server_config.json on upgrade if not already present.   It should have a default value of `0` (unlimited).

Follow up for https://github.com/irods/irods/issues/5822 (was added in 4.2.11)

Without adding it to the `server_config.json` on upgrade, this is what is produced in the 4.2.11 reLog.

```
WARNING: iRODS Exception:
    file: /repos/irods/lib/core/include/irods_configuration_parser.hpp
    function: T &irods::configuration_parser::get(const irods::configuration_parser::key_path_t &) [T = int]
    line: 108
    code: -1800000 (KEY_NOT_FOUND)
    message:
        key "maximum_size_of_delay_queue_in_bytes" not found in map.
stack trace:
--------------

Dumping stack trace
<0>	Offset: 0x6e 	Address: 0x7fbab0d318be	irods::exception::exception(long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
<1>	Offset: 0x956	Address: 0x42dad6	int& irods::configuration_parser::get<int>(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)
<2>	Offset: 0x8f 	Address: 0x42d02f	int& irods::get_advanced_setting<int>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
<3>	Offset:      	Address: 0x41dcf1	irodsReServer(main+0x231) [0x41dcf1]
<4>	Offset:      	Address: 0x7fbaaf469555	/lib64/libc.so.6(__libc_start_main+0xf5) [0x7fbaaf469555]
<5>	Offset:      	Address: 0x41d9fa	irodsReServer() [0x41d9fa]

WARNING: Could not retrieve delay queue byte limit from configuration. Delay server will use as much memory as necessary.
```

**Comment by kript** [comment]
Will this be handled on an upgrade from <= 4.2.10 to 4.3.x as well?

**Comment by trel** [comment]
Yes.   General approach, unless it doesn't make sense for a particular fix/feature, anything we add to 4.2.x makes it into 4.3.x at the same time.

**Comment by korydraughn** [comment]
The option doesn't necessarily need to be defined. The option will default to zero (unlimited memory) if it isn't defined.

Removing the following line would stop the exception from being logged.
https://github.com/irods/irods/blob/a86b0ed40bcb2bd23cf526a52244286b78285468/server/delay_server/src/irodsReServer.cpp#L689
The warning message would still be logged, but one could argue that it isn't needed.

**Comment by trel** [comment]
Rather than adding the entry to server_config.json, if missing, on upgrade?

Removes the scenario where it's not defined - makes things easier to identify/diagnose for all later versions.

**Comment by korydraughn** [comment]
I'm not against adding it on upgrade, but given that the option has a default value, I see less value in adding it.

> Removes the scenario where it's not defined - makes things easier to identify/diagnose for all later versions.

The issue doesn't feel like an error to me. It is more about the server log being noisy and presenting the information as if an error really occurred when it didn't.

The idea of having a default value conflicts with touching the server config on upgrade imo. The default value keeps us from needing to touch the server config and gives the admin the opportunity to add the option if they need to.

**Comment by trel** [comment]
If we don't add it... then new installations drift over time from upgraded ones.      I see zero downside to adding it?    And 'hidden default' if we don't add it.

Separately... when the setting is missing, I definitely agree it's currently too noisy, it should only be a warning, and not show the diagnostic stacktrace... rather than removing the warning altogether.

**Comment by kript** [comment]
> If we don't add it... then new installations drift over time from upgraded ones. I see zero downside to adding it? And 'hidden default' if we don't add it.
> 
There are already some changes when one upgrades (e.g. plugin settings somewhere between 4.1.7 to 4.1.11), so anything that means the administrator doesn't need to change the config file on upgrade and thus allowing a hands-free upgrade via the package would be my preference, particularly because our installs (and a number of other people IIRC), template the `server_config.json` to manage it via configuration management tools like ansible. 
If the upgrade process changes the file, it will be reverted at the next config management run, unless the template is changed.

I _think_ I would prefer a silent default, with documentation in docs.irods.org/man pages detailing all the settings and indicating which ones are optional and what they're used for.


> Separately... when the setting is missing, I definitely agree it's currently too noisy, it should only be a warning, and not show the diagnostic stacktrace... rather than removing the warning altogether.

If that warning appears in the rodsServerLog on standup/restart of the server, that's completely fair. If it repeats in the rodsLog/reLog every time there is an operation that uses it (every rule invocation?), then this would be not only noisy but also potentially alarming - not every administrator ~stalks~ lurks on the issues, or even knows to search them, after all! :blush:

**Comment by korydraughn** [comment]
Related to #6288
