### ISSUE TITLE
system vs local #include consistency

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#6211]
At present, throughout our repositories, we are not consistent about how we are `#include`-ing local vs system/internal vs external includes.

For example, we currently `#include` irods headers as both local and system headers:
https://github.com/irods/irods/blob/2b7a502715897fcd8d32859e0aa30db3e43bad45/lib/core/include/irods_exception.hpp#L11
https://github.com/irods/irods/blob/2b7a502715897fcd8d32859e0aa30db3e43bad45/lib/core/include/irods_load_plugin.hpp#L6-L12

For another example, we do the same for boost headers:
https://github.com/irods/irods/blob/2b7a502715897fcd8d32859e0aa30db3e43bad45/lib/core/include/irods_load_plugin.hpp#L23-L24
https://github.com/irods/irods/blob/2b7a502715897fcd8d32859e0aa30db3e43bad45/lib/core/src/irods_parse_command_line_options.cpp#L3-L4

How headers are `#include`d and how include directories are passed to the compiler affect how warnings and errors are generated from those headers. Generally speaking, internal headers should be included using quotes, and external headers should be included using angle brackets. Moreover, headers from the irods development package should only be included using quotes in the irods repository itself. Otherwise, they should be included using angle brackets.

**Comment by trel** [comment]
this bit of 'best practice' should definitely also make it into our developer docs.
