### ISSUE TITLE
Object library target irods_plugin_dependencies_functions has public non-target dependency

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#6218]
A public non-target dependency on libfmt was added to object library target `irods_plugin_dependencies_functions`:
https://github.com/irods/irods/blob/e53e8daa66005cc2fd6617979339ac6d1d0f30ab/CMakeLists.txt#L1158-L1162

Non-target library dependencies should not be added to object library targets.
Additionally, non-target irods-externals dependencies should never be public.
The proper thing to do here is to add `${IRODS_EXTERNALS_FULLPATH_FMT}/lib/libfmt.so` as a *`PRIVATE`* dependency to `irods_plugin_dependencies`.

**Comment by trel** [comment]
another fine 'best practice' for developer docs.    or perhaps a more strongly worded 'do and do not' section of the same.
