### ISSUE TITLE
Can't execute a long python rule by irule

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods#6223]
- [x] main
- [x] 4-3-stable
-------

### iRODS Version, OS and Version
iRODS Version 4.2.10 and centos7
iCommand 4.2.10 and centos7/ubuntu18

### What did you try to do?
As a rodsadmin, tried to execute a long python rule by irule. The file size is 23564 bytes.
`irule -r irods_rule_engine_plugin-python-instance -F test.r`

### Expected behavior
The rule execution should be successful.

### Observed behavior (including steps to reproduce, if applicable)
`ERROR: rcExecMyRule error.  status = -308000 USER_PACKSTRUCT_INPUT_ERR` on the terminal.
`ERROR: unpackNonpointerItem: strlen of myRule > dim size`  and ` NOTICE: rsApiHandler: unpackStruct error for apiNumber 625` in logs.

Once I had the file size (test.r) decreased to 20000 bytes, then the script worked and the execution was successful.

The lines writing errors to logs are here []()https://github.com/irods/irods/blob/ed6328646cee87182098d569919004049bf4ce21/lib/core/src/packStruct.cpp#L1949 but I couldn't understand the size limit well.

I couldn't find anything documented. Perhaps this might be a normal behavior, if so, could this be added to iCommands doc?

**Comment by trel** [comment]
We'll test / confirm - and get it documented if this is an existing hard limitation.

**Comment by d-w-moore** [comment]
Working on Reproducing right now....

**Comment by d-w-moore** [comment]
It comes down to this definition: https://github.com/irods/irods/blob/2b7a502715897fcd8d32859e0aa30db3e43bad45/lib/api/include/execMyRule.h#L10

and the constant `META_STR_LEN` is hard-set to (1024*20), and probably couldn't change without breaking some promised interfaces.

That said, most use cases demanding large rule files can probably be refactored.  Rules might be placed in the core.py rule base to serve up large blobs or strings (or paths to files in the local filesystem that might contain them) and thereby make them available  via  callback.ruleXXX( ) calls in the rule file.

**Comment by mstfdkmn** [comment]
Agreed. Basically we do work like what you suggest. I encountered this issue when testing something by using a local test file instead of changing the rule in server, and tried to understand it since no relevant information exist in `irule -h`. Thanks for clarifying it.

**Comment by trel** [comment]
We can document this limitation in the `irule` help text - that's a good idea.
