### ISSUE TITLE
/var/lib/irods/log/proc files not getting cleaned up (main only)

### ISSUE THREAD

**Issue by alanking** [irods/irods#6231]
### iRODS Version, OS and Version
4.3.0/main, ubuntu:18.04

### What did you try to do?
```bash
$ ips ; ips
```

### Expected behavior
```bash
$ ips ; ips
Server: <hostname>
     1889 rods#tempZone  0:00:00  ips  <ip address>
Server: <hostname>
     1891 rods#tempZone  0:00:00  ips  <ip address>
```

### Observed behavior (including steps to reproduce, if applicable)
```bash
$ ips ; ips
Server: <hostname>
    23986 rods#tempZone  0:00:03  irodsReServer  <ip address>
    23990 rods#tempZone  0:00:00  ips  <ip address>
Server: <hostname>
    23993 rods#tempZone  0:00:00  ips  <ip address>
    23986 rods#tempZone  0:00:03  irodsReServer  <ip address>
    23990 rods#tempZone  0:00:00  ips  <ip address>
```
Each agent PID has a file in `/var/lib/irods/log/proc` associated with it that has the contents from `ips` in it.

Interestingly, the agent PIDs themselves are not actually kept alive and the connections seem to be getting cleaned up. Here is the `ps` output on the affected server above:
```bash
$ ps aux | grep irodsServer
irods    23968  0.0  2.3 990964 93004 ?        Ssl  22:22   0:00 /usr/sbin/irodsServer
irods    23969  0.1  0.5 261516 20404 ?        S    22:22   0:00 /usr/sbin/irodsServer
irods    24029  0.0  0.0  14860  1016 pts/0    S+   22:25   0:00 grep irodsServer
```
So the effect is basically that `ips` thinks there are more connected clients than in reality. Also a lot of files will accumulate in log/proc.

This has been tested in and outside of a container. This problem does not affect 4-2-stable.

**Comment by trel** [comment]
looking relevant...

https://github.com/irods/irods/commit/764f30a81961bd09192dc02b387673dcad2bb1d0
