### ISSUE TITLE
Nonexistent #include: icatStruct.hpp

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#6236]
`icatGlobalsExtern.hpp` `#include`s `icatStruct.hpp`, which does not exist.
https://github.com/irods/irods/blob/c1c3c6ca2ddf7ef70b8c68f05121e5e78c022cac/server/icat/include/irods/icatGlobalsExtern.hpp#L12

I would hazard a guess that this is supposed to be `icatStructs.hpp`:
https://github.com/irods/irods/blob/c1c3c6ca2ddf7ef70b8c68f05121e5e78c022cac/server/icat/include/irods/icatStructs.hpp

**Comment by trel** [comment]
Since initial commit in 2007...

https://github.com/irods/irods-legacy/blame/ff4eaa47a34f1bb5990d5560f825975c26bab118/iRODS/server/icat/include/icatGlobalsExtern.h#L12

**Comment by SwooshyCueb** [comment]
Since it seems that `icatGlobalsExtern.hpp` is not used by *anyone*, including us, it's a candidate for torching.
On the off chance it *is* being used somewhere, I'm going to add a [`#warning`](https://gcc.gnu.org/onlinedocs/cpp/Diagnostics.html) marking the header as obsoleted, and open an issue to remove it completely in a future release.
