### ISSUE TITLE
setup of iRODS with existing non-local service account

### ISSUE THREAD

**Issue by trel** [irods/irods#6246]
- [x] main
- [x] 4-2-stable
---
### iRODS Version, OS and Version

4.2.11

### What did you try to do?

install iRODS with an existing non-local (AD-defined, in this case) service account name

### Expected behavior

correctly detect the non-local account, and install correctly.

### Observed behavior (including steps to reproduce, if applicable)

error returned from setup script since the named account could not be created locally (name collision)

See report and discussion here from @aghsmith:  https://groups.google.com/g/irod-chat/c/7DaQzFMLGgY

**Comment by trel** [comment]
reopening - needs milestone decision (and then possible cherry-pick).

**Comment by alanking** [comment]
Oh, good catch. I didn't see that it was linked.

**Comment by alanking** [comment]
I can cherry-pick the relevant changes to 4-2-stable
