### ISSUE TITLE
When composable resources voting and individual resource status conflicts, users don't get their data

### ISSUE THREAD

**Issue by kript** [irods/irods#6260]
- [x] main
- [x] 4-3-stable
---
### iRODS Version, OS and Version

4.2.7
Ubuntu 18.04

### What did you try to do?

`iget` a file where one replica out of two is stored on a resource that is marked down but the composable tree is configured with a higher read priority for that branch of the tree.

local resource branch (with marked down resource): `resc_context: write=1;read=1`
remote resource branch (with accessible replica):  `write=0.1;read=0.1`

### Expected behavior

The replica from the marked up resource is provided.

### Observed behavior (including steps to reproduce, if applicable)

The voting logic from the passthru over-rides the resource marked down and the `iget` attempts to retrieve the replica from that resource, resulting in a `HIERACHY_ERROR`.

The only way for the user to retrieve that file is to directly target the replica with `-n` which requires a level of understanding of the state and make up of the underlying infrastructure that is not fair to expect of an end user (how do they know the other replicas isn't also unavailable in some way).

Sadness and service desk tickets then follow.

**Comment by kript** [comment]
The errors make more sense, indeed, however... I was expecting *not* to get an error at all, and for iRODS to retrieve the file from the only replica it could when a plain `iget` was run. 
Of course, when you go directly to the resource, handling the errors is on you, but at the moment, if we mark a resource down in 'local resource branch', the the user is _unable_ to retrieve the file without going to the replica on the non-downed resource.

I didn't describe this very well, I realise!

**Comment by alanking** [comment]
>  I was expecting not to get an error at all, and for iRODS to retrieve the file from the only replica it could when a plain iget was run.

When using `iget` with no replica or resource specified, I was able to retrieve the object from the not-marked-down resource in 4.2.11, as demonstrated above.

> Of course, when you go directly to the resource, handling the errors is on you, but at the moment, if we mark a resource down in 'local resource branch', the the user is unable to retrieve the file without going to the replica on the non-downed resource.

In 4.2.9, the `iget -R` option started being treated as a directive rather than a preference: https://github.com/irods/irods/issues/4475

If the resolved resource is marked down or otherwise votes 0, this is now treated as an error and the file will not be retrieved.

Does this align with your expectations?

**Comment by alanking** [comment]
That's fair. The resolved hierarchy is referring to the hierarchy which won the vote. As it is not pointing at the resource specified, which is printed right next to it with the label "resource name", we return an error. Perhaps "resource name" could be rephrased to "requested resource" or something along those lines to reduce confusion?

**Comment by kript** [comment]
> If the resolved resource is marked down or otherwise votes 0, this is now treated as an error and the file will not be retrieved.
> 
> Does this align with your expectations?

Not quite.. I would expect that iRODS would choose the only available good replica available to it, even though the tree suggests otherwise, as long as it wasn't specifically directed by `-R` or `-n`

**Comment by trel** [comment]
> Not quite.. I would expect that iRODS would choose the only available good replica available to it, even though the tree suggests otherwise, as long as it wasn't specifically directed by `-R` or `-n`

But... in 4.2.9+ it did/does choose the only available good replica available to it.

Yes?

**Comment by kript** [comment]
ah, I had missed that, thanks.

What workaround do we have until we upgrade to >= 4.2.9?

I can ATM only think of reorganising the tree so we had a separate passthru for each server (or heavens forbit each resource), which we could set read/write to 0 on, but that's a lot of tree surgery for us...

**Comment by trel** [comment]
Yes, upgrading fixes https://github.com/irods/irods/issues/4475 which is the source of the problem.

Agreed, a passthru above each resource (or sub-tree of resources) is the best workaround until you upgrade.

**Comment by alanking** [comment]
This sounds like it has been resolved. Should this be closed?

**Comment by korydraughn** [comment]
What do you feel resolved it?

**Comment by trel** [comment]
remaining work was updating an error message i think...

> Perhaps "resource name" could be rephrased to "requested resource"

**Comment by alanking** [comment]
D'oh, missed that. Thanks.

**Comment by alanking** [comment]
I've updated the log message. Closing.
