### ISSUE TITLE
Consider moving the `irods-grid` icommand into the server

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#6265]
`irods-grid` is a special command.

- It doesn't have the same properties as a normal icommand.
- It doesn't authenticate with the server as an iRODS user.
- It uses a different set of credentials to connect to the server.
- It connects to the server via port 1248.

Given the points above and the fact that 4.3 doesn't require icommands to be installed, `irods-grid` should be a part of the server packages.

**Comment by SwooshyCueb** [comment]
Likewise. I'm on it.

**Comment by SwooshyCueb** [comment]
Should we still include irods-grid in the icommands tarball package?

**Comment by SwooshyCueb** [comment]
Also, should we move it to `/usr/sbin` or just keep it in `/usr/bin`? The former would probably be easier as it wouldn't require declaring funky package relationships like we had to do when we moved the auth plugins

**Comment by trel** [comment]
> Should we still include irods-grid in the icommands tarball package?

I think no.  Doesn't use the iRODS protocol.   Should only come with the server (now that we've separated these).

> should we move it to `/usr/sbin`

Feels correct.   Cleaner separation, agreed.
