### ISSUE TITLE
`iqstat -a <rule_id>` should return `INCOMPATIBLE_PARAMS`

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#6267]
- [ ] main
- [ ] 4-3-stable
- [ ] 4-2-stable

## Bug Report
Observed on iRODS 4.2.7.

**Comment by d-w-moore** [comment]
Since we've decided to keep the` iqstat -a <RULEID> `functionality (where -a means include all valid irods users in the query), maybe we can close this issue ?

**Comment by alanking** [comment]
I think I agree. We can close this as resolved/invalid in light of decision made for #6740. Thoughts, @korydraughn?
