### ISSUE TITLE
Consider forking the control plane instead of running it in a thread

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#6270]

**Comment by trel** [comment]
This would simplify the process model by making the control plane similar to the other tasks that need to be monitored/restarted by the main iRODS server.

**Comment by korydraughn** [comment]
After spending time attempting to externalize the control plane and discussing what is needed to accomplish that, we've decided to keep it as an internal thread.

We can revisit externalizing the control plane at a later date if it is needed.
