### ISSUE TITLE
Update `get_script_output_single_line()` to use Boost.Process

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#6273]
- [x] main
- [x] 4-3-stable
---
https://github.com/irods/irods/blob/a86b0ed40bcb2bd23cf526a52244286b78285468/server/core/src/miscServerFunct.cpp#L2974-L2978

**Comment by alanking** [comment]
@epsilon-phase - Since we have some more time, go ahead and cherry-pick this to 4-3-stable. Thanks
