### ISSUE TITLE
CPack fails to byte-compile python3 syntax on Centos 7

### ISSUE THREAD

**Issue by alanking** [irods/irods#6294]
### iRODS Version, OS and Version
main only, Centos 7

### What did you try to do?
I added some python3-only syntax to a packaged python file and tried to build on Centos 7. Specifically, I added an f-string to a test suite.

### Expected behavior
Assuming everything is good, the build and package steps should succeed.

### Observed behavior (including steps to reproduce, if applicable)
I see the following errors at the end of my build (below is output from the Kerberos plugin, but it applies to everything we do):
```
stdout: Consolidate compiler generated dependencies of target krb_client
Consolidate compiler generated dependencies of target krb_server
[ 50%] Built target krb_client
[100%] Built target krb_server
Run CPack packaging tool...
CPack: Create package using RPM
CPack: Install projects
CPack: - Run preinstall target for: irods-kerberos
CPack: - Install project: irods-kerberos []
CPack: Create package

stderr: CPackRPM: Will use GENERATED spec file: /irods_plugin_build/_CPack_Packages/Linux/RPM/SPECS/irods-auth-plugin-krb.spec
CPackRPM:Debug: You may consult rpmbuild logs in:
CPackRPM:Debug:    - /irods_plugin_build/_CPack_Packages/Linux/RPM/rpmbuildirods-auth-plugin-krb.err
CPackRPM:Debug: *** + umask 022
+ cd /irods_plugin_build/_CPack_Packages/Linux/RPM/BUILD
+ mv /irods_plugin_build/_CPack_Packages/Linux/RPM/irods-kerberos-4.3.0.0-Linux /irods_plugin_build/_CPack_Packages/Linux/RPM/tmpBBroot
+ exit 0
+ umask 022
+ cd /irods_plugin_build/_CPack_Packages/Linux/RPM/BUILD
+ '[' /irods_plugin_build/_CPack_Packages/Linux/RPM/irods-kerberos-4.3.0.0-Linux '!=' / ']'
+ rm -rf /irods_plugin_build/_CPack_Packages/Linux/RPM/irods-kerberos-4.3.0.0-Linux
++ dirname /irods_plugin_build/_CPack_Packages/Linux/RPM/irods-kerberos-4.3.0.0-Linux
+ mkdir -p /irods_plugin_build/_CPack_Packages/Linux/RPM
+ mkdir /irods_plugin_build/_CPack_Packages/Linux/RPM/irods-kerberos-4.3.0.0-Linux
+ '[' -e /irods_plugin_build/_CPack_Packages/Linux/RPM/irods-kerberos-4.3.0.0-Linux ']'
+ rm -rf /irods_plugin_build/_CPack_Packages/Linux/RPM/irods-kerberos-4.3.0.0-Linux
+ mv /irods_plugin_build/_CPack_Packages/Linux/RPM/tmpBBroot /irods_plugin_build/_CPack_Packages/Linux/RPM/irods-kerberos-4.3.0.0-Linux
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-compress
+ /usr/lib/rpm/redhat/brp-strip /usr/bin/strip
+ /usr/lib/rpm/redhat/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
error: Bad exit status from /var/tmp/rpm-tmp.6ZMzHF (%install)
    Bad exit status from /var/tmp/rpm-tmp.6ZMzHF (%install)
 ***
CPackRPM:Debug:    - /irods_plugin_build/_CPack_Packages/Linux/RPM/rpmbuildirods-auth-plugin-krb.out
CPackRPM:Debug: *** Building target platforms: x86_64
Building for target x86_64
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.93Trz2
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.6ZMzHF
Compiling /irods_plugin_build/_CPack_Packages/Linux/RPM/irods-kerberos-4.3.0.0-Linux/var/lib/irods/scripts/irods/test/test_irods_auth_plugin_krb.py ...
  File "/var/lib/irods/scripts/irods/test/test_irods_auth_plugin_krb.py", line 48
    d['KerberosServicePrincipal'] = f'irods/{hostname}.example.org@EXAMPLE.ORG'
                                                                              ^
SyntaxError: invalid syntax



RPM build errors:
 ***
CMake Error at /opt/irods-externals/cmake3.21.4-0/share/cmake-3.21/Modules/Internal/CPack/CPackRPM.cmake:1885 (message):
  RPM package was not generated!
  /irods_plugin_build/_CPack_Packages/Linux/RPM
Call Stack (most recent call first):
  /opt/irods-externals/cmake3.21.4-0/share/cmake-3.21/Modules/Internal/CPack/CPackRPM.cmake:1956 (cpack_rpm_generate_package)


CPack Error: Error while execution CPackRPM.cmake
CPack Error: Problem compressing the directory
CPack Error: Error when generating package: irods-kerberos
make: *** [package] Error 1
```

As you can see, the build completes successfully and I have demonstrated that the python is valid via other platforms, so it is just a matter of centos:7 using python2 by default.

I found a few links for how to get around this and the experience of others (even inside Fedora):

https://cmake.org/pipermail/cmake/2016-January/062657.html
https://lists.fedoraproject.org/pipermail/devel/2010-April/135366.html
https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#Bytecompiling_with_the_correct_python_version

As we lean into python3, this will become more relevant. For now, we can work around it by avoiding python3 syntax.

**Comment by alanking** [comment]
The merged commit should fix this issue for all of our repositories since it's in the common CPack definitions, right? If so, I think that this can be closed.

**Comment by SwooshyCueb** [comment]
AFAIK, none of the other repos are actually using the common cpack definitions yet. We pushed touching all the repos off to 4.3.1.
I think for affected repos, we can go ahead and use the module.
But the question is, which repos are affected?

**Comment by d-w-moore** [comment]
ok I see. we're waiting on a proof of the pudding.  I'll go ahead and test this in https://github.com/irods/irods_rule_engine_plugin_python/pull/114 , which is one repo affected by this.

**Comment by alanking** [comment]
That sounds good to me. Please report back when you've confirmed and then I think we can just make issues for individual repositories as needed. Thoughts?

**Comment by d-w-moore** [comment]
Good, yes, in process of testing.

**Comment by alanking** [comment]
Yup, my bad. I thought this would take effect in all the repositories, but didn't realize that was a piece of work for the future. Thanks for doing that :)
