### ISSUE TITLE
server-side irods_environment.json doc and validation schema bugs

### ISSUE THREAD

**Issue by tedgin** [irods/irods#6298]
- [x] 4-2-stable
- [x] main
------

### iRODS Version, OS and Version
iRODS 4.2.8 and CentOS 7

_At least the doc bugs are present in iRODS 4.2.11._

### What did you try to do?

Using the documentation https://docs.irods.org/4.2.8/system_overview/configuration/#irodsirods_environmentjson, I created an iRODS server with the following fields among others set in `irods_environment.json`.

```json
{
    "irods_control_plane_key": "OMITTED",
    "irods_control_plane_port": 1248,
    "irods_encryption_algorithm": "AES-256-CBC",
    "irods_encryption_num_hash_rounds": 16,
    "schema_name": "service_account_environment",
    "schema_version": "v3"
}
```

It the file didn't set the four undocumented fields `irods_server_control_plane_encryption_algorithm`, `irods_server_control_plane_encryption_num_hash_rounds`,  `irods_server_control_plane_key`, and `irods_server_control_plane_port`.

I attempted to stop the server using `irods-grid shutdown --hosts=128.196.65.86`.

### Expected behavior

I expected iRODS to be stopped on 128.196.65.86.

### Observed behavior (including steps to reproduce, if applicable)

Instead, it fails, reporting that the four undocumented fields weren't set.

```
[-]	/tmp/tmpTBvaqa/src/irods-grid.cpp:350:irods::error get_and_verify_client_environment(rodsEnv &) :  status [USER_INVALID_CLIENT_ENVIRONMENT]  errno [] -- message [missing environment entries: irods_server_control_plane_key, irods_server_control_plane_encryption_num_hash_rounds, irods_server_control_plane_encryption_algorithm, irods_server_control_plane_port]
```

`irods-grid` works as expected if the missing values are added.

The four fields are missing from the validation schema `service_account_environment.json` as well.

Since there can be only one control plane port and key for an iRODS grid, are the fields `irods_control_plane_key` and `irods_control_plane_port` used?

**Comment by trel** [comment]
The code is emitting the correct diagnosis and remedy.

---
The docs are missing the word `server`!

```
"irods_control_plane_key" -> "irods_server_control_plane_key"
"irods_control_plane_port" -> "irods_server_control_plane_port"
```
---
And the schema too!

https://github.com/irods/irods/blob/24e1d3db8726a43b60121b3b00981a5e035a3336/configuration_schemas/v3/service_account_environment.json#L15-L16

---

And yes, both are missing the other two required fields...

```
irods_server_control_plane_encryption_algorithm
irods_server_control_plane_encryption_num_hash_rounds 
```
---

And the server environment should require all four as well...

https://github.com/irods/irods/blob/24e1d3db8726a43b60121b3b00981a5e035a3336/configuration_schemas/v3/service_account_environment.json#L39-L42

---
I'm not sure about your 'only one control plane port and key' per grid question...
Yes, each client must have all four things defined to fully characterize how to connect to a control plane.

**Comment by trel** [comment]
I think we're also missing `server_control_plane_timeout_milliseconds` from the schema, template, and docs.

**Comment by korydraughn** [comment]
That option seems specific to server_config.json.

`irods-grid` doesn't contain any references to that property.

**Comment by tedgin** [comment]
You can safely ignore my question asking if `irods_control_plane_key` and `irods_control_plane_port` are used.  You answered "no," indirectly.

For posterity, I'll try to restate it better here.  I was wondering if both `irods_server_control_plane_key` and `irods_control_plane_key` are required.  My hunch was that they are not.  A control plane only has one key, so the two parameters would have to have the same value, making them redundant.  I had the same question about `irods_server_control_plane_port` and `irods_control_plane_port`.

**Comment by trel** [comment]
Correct, those were just typos that were missing the word 'server'.

**Comment by korydraughn** [comment]
> That option seems specific to server_config.json.
> 
> `irods-grid` doesn't contain any references to that property.

@trel What were your thoughts on this? **That option** being `server_control_plane_timeout_milliseconds`.

**Comment by trel** [comment]
Right, if that is only a server-side thing - then ... we put it in the schema, but don't make it required.

Does that sound right?

**Comment by korydraughn** [comment]
Yes. I added it to the service account schema as an optional property.

I think we just ignore it for `irods-grid`.

**Comment by trel** [comment]
Gotcha.

**Comment by korydraughn** [comment]
I'm now going to remove `irods_server_control_plane_timeout_milliseconds` from the service account schema because `irods-grid` doesn't use it.

The server uses `server_control_plane_timeout_milliseconds`. It is captured in server_config.json.

**Comment by trel** [comment]
ah, the other side.   right.

**Comment by trel** [comment]
Does this need a 4-3-stable, too?

**Comment by alanking** [comment]
No, the commit in `main` was added before 4-3-stable was created.

**Comment by trel** [comment]
oooh, so fancy.   carry on!
