### ISSUE TITLE
Remove `default_log_rotation_in_days` from server

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#6304]
The following setting shouldn't be needed in 4.3.0 as the server now uses syslog and logrotate to manage log files.
https://github.com/irods/irods/blob/3e4ef34f27d3cd62a8885ea1818ac5987e5c5f75/packaging/server_config.json.template#L16

**Comment by trel** [comment]
was wondering about that a couple days ago.   thanks for catching it.

**Comment by trel** [comment]
definitely could be 4.3.0 i think.   nothing should be using/referencing the setting.

**Comment by mstfdkmn** [comment]
We are testing 4.3.0 and we noticed that we don't see this change in our environment. Do we overlook something? To what extend do you think this will be important if we manually remove it from the server_config.json file?

```
[irods@dev-u0137480 irods]$ imiscsvrinfo
RCAT_ENABLED
relVersion=rods4.3.0
apiVersion=d
rodsZone=u0137480
up 0 days, 7:23

```
```
[irods@dev-u0137480 irods]$ cat server_config.json
{
    "advanced_settings": {
        "default_log_rotation_in_days": 5,
```

**Comment by trel** [comment]
Interesting.

It shouldn't be honored anywhere in 4.3 - and I thought it would have been removed on upgrade (is this an upgraded installation?)...

You should be safe to remove it manually.

**Comment by mstfdkmn** [comment]
Apologizes...that is happening because of a custom configuration that we have for irods setup.

**Comment by trel** [comment]
Ah, very good.  Thanks for the follow up.
