### ISSUE TITLE
Enable use of "-" in Zone names

### ISSUE THREAD

**Issue by kript** [irods/irods#6314]
When trying to upgrade one of our Dev zones from 3.3.1 to 4.1.8, we ran into the following issue when trying to run /var/lib/irods/packaging/setup_irods.sh;

```
Validating [/usr/local/iRODS/.irods/irods_environment.json]... Success
ERROR: Validation Failed for [/etc/irods/server_config.json]
     : against [file:///etc/irods/irods_schemas/v2/server_config.json]
  ValidationError: u'Sanger1-dev' does not match u'^[A-Za-z0-9_\\.]+$'

Failed validating u'pattern' in schema[u'properties'][u'zone_name']:
    {u'maxLength': 63,
     u'pattern': u'^[A-Za-z0-9_\\.]+$',
     u'type': u'string'}

On instance[u'zone_name']:
    u'Sanger1-dev'
Preflight Check problem:
   JSON Configuration Validation failed.
```

We have at least two zones that have dashes in them. Is there a reason that the schema doesn't allow them, or can beget the schema updated? 

Our alternatives appear to be;
1. hacking a copy of the schema to allow dashes
2. turning off schema validation
3. Bringing the 3.3.1 system back up (a bit tricky since we've already run the database upgrade script, but we can rollback to a backup) and renaming the zone.

None of these are ideal, with the last one having the most potential to cause problem (updating ~800 .ienv files is just the start, since our Federation head zone has a dash in it).

Any chance of a fix by Monday? Cheeky I know, but our dev federation master zone is down until we resolve this.

Thanks,

John

**Comment by trel** [comment]
> We cannot loosen this requirement until iRODS v5.0.

Still agree.   Six years on... not convinced there's too much utility in this change/request.

For new installs that *know* they don't have to federate with any 3.x zones, the manual schema override mentioned above is still sufficient/safe.

Closing.
