### ISSUE TITLE
adding 'schema_name' to all schema files

### ISSUE THREAD

**Issue by trel** [irods/irods#6315]
"schema_name": {"type": "string"}

also, rename VERSION.json to version.json

**Comment by trel** [comment]
is this the same as ... #2817 ?

**Comment by korydraughn** [comment]
I believe they are related, but not identical.

#2817 is about the validator.

This issue seems more about adjusting the schemas so that they require the schema name/version fields.

**Comment by trel** [comment]
ah, very good.
