### ISSUE TITLE
Centos 7 requires pyodbc externals package

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#6322]
We currently use pyodbc in one script:
https://github.com/irods/irods/blob/26ee011a37ec75dfcafc6e1ea3915b9603b14aa9/scripts/irods/database_connect.py#L17

The only available pyodbc RPM package for Centos 7 is for Python 2:
https://centos.pkgs.org/7/epel-x86_64/pyodbc-3.0.10-1.el7.x86_64.rpm.html
We cannot declare relationships from an RPM package onto a pip-installed package.

Therefore we must either package pyodbc ourselves (can't go in `/opt`!) or remove the dependency.

**Comment by trel** [comment]
Tough to remove the dependency.

If we know that Python3 is installed on the host (which... I think will be required for iRODS 4.3.0... right?)...

then, can we make the control scripts smart enough to complain loudly if pyodbc isn't installed, and we assume a README-based solution is sufficient?

and then, only if not... we look into packaging pyodbc for cen7 (ew.)

**Comment by korydraughn** [comment]
Before 4.3, iRODS contained a complete copy of pypyodbc. It was a single file that lived in this repo.

I'm against keeping a copy of pyodbc in the repo, but if that is easy to do and we can't resolve this through packaging, then that might be our only option.

Are we just getting lucky that pyodbc is compatible with Python 3? I believe it is, but we should confirm that.

The commit containing the switch to pyodbc (including packaging edits) is here: https://github.com/irods/irods/commit/9215fb2204df1050b2a97f602ba839ea9c36d3c5

**Comment by SwooshyCueb** [comment]
pyodbc is compatible with Python 3. We currently install it with pip in the development environment.

Related: irods/irods_development_environment#45

**Comment by SwooshyCueb** [comment]
Both AlmaLinux 8 and Rocky Linux 8 have `python3-pyodbc`.
I do not like the idea of having users manually install pyodbc from pip, but I like the idea of automating a pip package installation even less.
I think in the interest of getting 4.3 out the door, we can check-and-scream for now, and look into rolling our own package later.

**Comment by trel** [comment]
Maybe we can include pyodbc *in our server package* for cen7 only?

**Comment by SwooshyCueb** [comment]
pyodbc is a native library. I think that's probably a bad idea.

**Comment by korydraughn** [comment]
After some discussion, we've decided that this will be handled via documentation for 4.3.0.

The plan is to provide a proper package for 4.3.1.
