### ISSUE TITLE
skip tests requiring NREP when NREP status not known

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#6344]
- [x] main
- [x] 4-2-stable
---
## Feature
When irods/irods core tests are being run and the primary rule plugin is not NREP, we should skip tests requiring NREP.

The core tests record only which plugin is in first place, and if that is not NREP,  an implicit assumption in many tests is that  there is only one rule plugin configured, i.e. the one with primary placing.

The notable example is Python RE Plugin, whose core testing uses irods/irods test suite and  depends on PREP being the only exclusive rule language plugin active.

**Comment by alanking** [comment]
Please checkbox and close if complete. Thanks!
