### ISSUE TITLE
chown_directories_for_postinstall.py stomps on msiExecCmd_bin ownership

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#6352]
The post-installation script for the server is careful to avoid stomping on file/dir ownership in `msiExecCmd_bin`:
https://github.com/irods/irods/blob/bb30c55ff041564daa84938ebba121a6e801d7a9/packaging/postinstall.sh#L59

But `chown_directories_for_postinstall.py` doesn't care.

**Comment by trel** [comment]
yes, needs to be more... discriminating.     probably by just skipping this one subdirectory.
