### ISSUE TITLE
`iadmin suq` help text for docs.irods.org is confusing

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#6363]
- [x] main
- [x] 4-3-stable

----

```
suq User ResourceName-or-'total' Value (set user quota)
Set a quota for a particular user for either a resource or all iRODS
usage (total).  Use 0 for the value to remove quota limit.  Value is
in bytes.  As with other sub-commands, 'user' is of the form
userName[#zone] where the local zone is default.
Also see sgq, lq and cu.
```
should be ...
```
suq User ResourceName Value (set user quota)
Set a quota for a particular user for a resource.  Use 0 for the value
to remove quota limit.  Value is in bytes.  As with other sub-commands,
'user' is of the form userName[#zone] where the local zone is default.
Also see sgq, lq and cu.
```
The icommand requires a resource name.

**Comment by trel** [comment]
this might be going away / renamed due to #4481 ?

**Comment by korydraughn** [comment]
Does that mean https://github.com/irods/irods/issues/2556 no longer needs to be investigated?

**Comment by korydraughn** [comment]
Ok. I'm going to bump that issue to 4.3.1 for now.

**Comment by trel** [comment]
I don't think there's anything to do here...

The `iadmin suq` help text now reads...

```
 suq User ResourceName-or-'total' Value (set user quota)

Setting user quotas greater than zero is no longer supported in iRODS.

This sub-command exists so that administrators have a way to remove
existing user quotas.  Pass 0 as the value to do this.

Also see sgq, lq, and cu.
```

Which... I think is correct since 4.3.0 (#4481).

Candidate for closing.

**Comment by korydraughn** [comment]
At the very least, the first line should be changed so it's clear what should be passed.

The use of `-or-` is very confusing. We should list the alternatives or explain in the body that "total" can be passed as the resource name.

**Comment by trel** [comment]
Fair enough - will need to do the same for `iadmin sgq` for consistency.
