### ISSUE TITLE
`ils` terminates with uncaught exception on `SSL_HANDSHAKE_ERROR`

### ISSUE THREAD

**Issue by alanking** [irods/irods#6365]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---
### iRODS Version, OS and Version
4.2.11

### What did you try to do?
Run `ils` with SSL misconfigured in the client environment. The target collection was in a remote zone, but I don't think that matters. Noting here in case it does.

### Expected behavior
An error with exit and maybe a non-zero return code.

### Observed behavior (including steps to reproduce, if applicable)
```bash
$ ils -AL /zoneB/home/rods#zoneA
terminating with uncaught exception of type irods::experimental::filesystem::filesystem_error: cannot get status: Unknown error -2103000
Aborted (core dumped)
```

**Comment by korydraughn** [comment]
Possibly related to #6068

**Comment by alanking** [comment]
After looking into this some more, I believe the error occurs in the server-to-server connection that occurs when going over the federation. If the SSL is misconfigured in the local zone, no connection is possible in the first place and this particular exception is not thrown. Therefore, this is a federation-only issue. Adding a tag.

**Comment by alanking** [comment]
Oh, and duplicate. :)
