### ISSUE TITLE
`ifsck` generates only chkObjConsistency

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods#6367]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---
### iRODS Version, OS and Version
4.2.10 Centos7

### What did you try to do?
I run `ifsck -r /myLocal/home/user/abc` in order to verify the local directory <abc> against the iRODS collection <abc>.

Also I run` ifsck -K /myLocal/home/user/test.txt` to check the local file's content by its checksum in iRODS.

**Note:**
Sizes of objects on both side are the same.
Checksums are verified manually and the same.

### Expected behavior
A message to detect if an object has been corrupted or modified outside the iRODS framework on the local filesystem

### Observed behavior (including steps to reproduce, if applicable)
```
ERROR chkObjConsistency: rcGenQuery failed: status [-808000] genQueryOut [0x17a2cf0] file [/myLocal/home/user/abc/test1.txt]
ERROR chkObjConsistency: rcGenQuery failed: status [-808000] genQueryOut [0x17a2cf0] file [/myLocal/home/user/abc/test2.txt]
ERROR chkObjConsistency: rcGenQuery failed: status [-808000] genQueryOut [0x17a2cf0] file [/myLocal/home/user/abctest3.txt]
```

for the second option (checksum):
`ERROR chkObjConsistency: rcGenQuery failed: status [-808000] genQueryOut [0x1e9e330] file [/myLocal/home/user/test.txt]
`

I hope I am not missing anything here. Thanks.

**Comment by trel** [comment]
`ifsck` checks local physical paths, not logical paths.
```
Usage: ifsck [-hKrR] srcPhysicalFile|srcPhysicalDirectory ... 
```

`iscan` might be what you're looking for...
```
Usage: iscan [-rhd] srcPhysicalFile|srcPhysicalDirectory|srcDataObj|srcCollection
```

**Comment by mstfdkmn** [comment]
Sorry! I mistyped above. I will update my first post. It doesn't check the local path either.

Also, I was about to create a separate issue for 'iscan' because it shows '...is not registered in iRODS' although the object exists in iRODS).

**Comment by trel** [comment]
Oh, I see it too... I think this is a regression...

**Comment by JustinKyleJames** [comment]
This seems to happen when there is a new file in the in the recursive path that is not registered.  For example, someone came in and added a file after the recursive registration was performed.

I am guessing we need a more direct error message.

**Comment by JustinKyleJames** [comment]
I am not sure what the behavior should be when a file is not registered.  I went back to 4.2.8 and the behavior is the same as described above.

I can catch the CAT_NO_ROWS_FOUND error and generate a more specific response.  Here is an example of such a response.

```
$ ifsck -r /tmp/dir1
CORRUPTION: local file [/tmp/dir1/subdir1/f3] is not registered in iRODS.
```

Thoughts?

**Comment by korydraughn** [comment]
From this morning's discussion:
- The message you have presented is good and helps the user know what is happening
- `CORRUPTION` should be changed to `WARNING`

**Comment by korydraughn** [comment]
Also, make sure no verification operations (i.e. checksums, size) are run on the non-existent object.

**Comment by alanking** [comment]
@JustinKyleJames - Please close if complete. Thanks!

**Comment by JustinKyleJames** [comment]
Closing.
