### ISSUE TITLE
Remove support for password argument from `iinit`

### ISSUE THREAD

**Issue by alanking** [irods/irods#6382]
- [x] main
---
`iinit` allows the user to supply a password as an argument which will be used in lieu of the password prompt. This should be removed as it is insecure and does not add anything that cannot be accomplished through other means (i.e. scripting).

**Comment by kript** [comment]
Could the docs be updated with an example/suggested way of providing the password now this is removed, please?

**Comment by alanking** [comment]
The password is still taken via stdin at a prompt for the native and pam_password plugins as per usual and can be piped in like so:
```bash
$ echo $MY_IRODS_PASSWORD | iinit
```
I can add this to the help text.
