### ISSUE TITLE
More bad path assumptions

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#6386]
While working on 6383, I noticed a few other places we're making potentially bad assumptions about paths.

Hardcoded `/var/lib/irods` in `irods_logger.cpp`:
https://github.com/irods/irods/blob/0830ad132243bfc3d9c793eb8525a71fefbf9c8c/lib/core/src/irods_logger.cpp#L34

Hardcoded `var/lib/irods` in `procLog.cpp`:
https://github.com/irods/irods/blob/0830ad132243bfc3d9c793eb8525a71fefbf9c8c/server/core/src/procLog.cpp#L29

Hardcoded `/var/lib/irods` in `irods_resource_manager.cpp`:
https://github.com/irods/irods/blob/0830ad132243bfc3d9c793eb8525a71fefbf9c8c/server/core/src/irods_resource_manager.cpp#L44

Hardcoded `var/lib/irods` in `osauth.h`:
https://github.com/irods/irods/blob/0830ad132243bfc3d9c793eb8525a71fefbf9c8c/lib/core/include/irods/osauth.h#L9

Hardcoded `etc` in `osauth.h`:
https://github.com/irods/irods/blob/0830ad132243bfc3d9c793eb8525a71fefbf9c8c/lib/core/include/irods/osauth.h#L11

Hardcoded `var/lib/irods` in `execCmd.h`:
https://github.com/irods/irods/blob/0830ad132243bfc3d9c793eb8525a71fefbf9c8c/lib/api/include/irods/execCmd.h#L8

(macro from `execCmd.h` is used in `rsExecCmd.cpp`):
https://github.com/irods/irods/blob/0830ad132243bfc3d9c793eb8525a71fefbf9c8c/server/api/src/rsExecCmd.cpp#L372-L374

This will cause problems with non-package installs and installations with non-standard paths.
Required for #6284

**Comment by korydraughn** [comment]
Consider the following as well.
https://github.com/irods/irods/blob/0830ad132243bfc3d9c793eb8525a71fefbf9c8c/server/core/src/irods_signal.cpp#L27-L32
https://github.com/irods/irods/blob/0830ad132243bfc3d9c793eb8525a71fefbf9c8c/server/main_server/src/rodsServer.cpp#L371-L373
https://github.com/irods/irods/blob/0830ad132243bfc3d9c793eb8525a71fefbf9c8c/server/main_server/src/rodsServer.cpp#L340-L345

**Comment by SwooshyCueb** [comment]
More to investigate:
https://github.com/irods/irods/blob/0830ad132243bfc3d9c793eb8525a71fefbf9c8c/server/re/include/irods/reIn2p3SysRule.hpp#L24
https://github.com/irods/irods/blob/0830ad132243bfc3d9c793eb8525a71fefbf9c8c/server/re/include/irods/reIn2p3SysRule.hpp#L26
