### ISSUE TITLE
Consider making `iinit` prompt user about use of SSL

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#6398]
- [x] main
- [x] 4-3-stable
---
See candidate PR: https://github.com/irods/irods_client_icommands/pull/56

**Comment by alanking** [comment]
Other things to consider:
 - Should the user be prompted for the other SSL configurations, such as the location of the certificate chain file, certificate key file, and dhparam file? The linked PR only sets the default values for configuration related to encryption.
 - Should we allow the user to specify the authentication scheme they wish to use?
 - Should we save the environment file if authentication fails? We currently save the user's password (if entered) if authentication fails, but not the environment (forcing the user to re-enter all the information). This could serve as the default behavior with a possible option to use an existing environment and just skip to the password prompt (if applicable for the given authentication scheme).

**Comment by trel** [comment]
Consider an option to `iinit`... perhaps `iinit --ssl` that will change the required prompts/inputs.  This will allow `iinit` to get a bit smarter in 4.3.x without affecting existing deployed input scripts.  With `iinit --sal`, all necessary and sufficient SSL-related inputs can be provided, perhaps with good defaults.

The auth scheme might be for later (perhaps https://github.com/irods/irods_client_cli).

Saving information in a failure mode should be smarter - agreed.

**Comment by alanking** [comment]
Thinking about tests for https://github.com/irods/irods_client_icommands/pull/338...

We're adding `--with-ssl` and `--prompt-auth-scheme` as well as the ability for the client environment file to update each time `iinit` is run, regardless of whether authentication succeeds.

- Use `--prompt-auth-scheme` with default (no input), valid, and invalid authentication schemes
- Use `--with-ssl` with default (no input), non-default, and invalid values
- Make sure irods_environment.json file is saved when authentication succeeds and when it fails
- Make sure that values loaded from an existing environment appear as default values in the prompts
