### ISSUE TITLE
iquest wrongly gives valid answer to incorrect or impossible cross-zone query

### ISSUE THREAD

**Issue by davebiffuk** [irods/irods#6402]
### iRODS Version, OS and Version

4.2.7, Ubuntu 18.04

### What did you try to do?

I tried to use iquest to query (a) a non-local zone, (b) a non-existent zone.

### Expected behavior

iquest should report that cross-zone queries are not possible, or that the zone does not exist; and exit with an error message and non-zero return code.

### Observed behavior (including steps to reproduce, if applicable)

iquest gave what looks like a valid answer (apparently the answer for the local zone) and a zero return code implying success.

```
# this is the local zone
irods@irods-seq-indexing:~$ iquest -z seq "%d" "SELECT sum(DATA_SIZE) WHERE META_DATA_ATTR_NAME = 'tier:single-copy' AND META_DATA_ATTR_VALUE = '1' AND DATA_RESC_HIER like 'noReplRoot;%'"
Zone is seq
72270472958750
# this is a non-local zone
irods@irods-seq-indexing:~$ iquest -z seq-dev "%d" "SELECT sum(DATA_SIZE) WHERE META_DATA_ATTR_NAME = 'tier:single-copy' AND META_DATA_ATTR_VALUE = '1' AND DATA_RESC_HIER like 'noReplRoot;%'"
Zone is seq-dev
72270472958750
irods@irods-seq-indexing:~$ echo $?
0
# this is a nonexistent zone
irods@irods-seq-indexing:~$ iquest -z this_is_not_a_zone "%d" "SELECT sum(DATA_SIZE) WHERE META_DATA_ATTR_NAME = 'tier:single-copy' AND META_DATA_ATTR_VALUE = '1' AND DATA_RESC_HIER like 'noReplRoot;%'"
Zone is this_is_not_a_zone
72270472958750
irods@irods-seq-indexing:~$ echo $?
0
```

**Comment by trel** [comment]
might already be fixed... on 4.2.11...
```
$ iquest -z doesnotexistZone "%d" "SELECT sum(DATA_SIZE)"
Zone is doesnotexistZone
 ERROR: iquest Error: queryAndShowStrCond failed status = -26000 SYS_INVALID_ZONE_NAME
```

**Comment by trel** [comment]
Confirmed - fixed in 4.2.11 - https://github.com/irods/irods/issues/6022

**Comment by davebiffuk** [comment]
Super - thank you - apologies for not spotting that when I skimmed the closed issues.

**Comment by trel** [comment]
Definitely no worries.
