### ISSUE TITLE
Add timestamps to messages in reLog files

### ISSUE THREAD

**Issue by tedgin** [irods/irods#6420]
## Feature

It's hard to coordinate messages in reLog with other log files, because the messages don't have timestamps. Please have a timestamp written to each message written to an reLog file.

**Comment by tedgin** [comment]
Since this won't be an issue in 4.3, I'm happy if you want to close this feature request.

**Comment by trel** [comment]
Gotcha - we'll let it ride for now - 4.2.12 has a few things in it - and this *shouldn't* be too hard to add.

Thanks.

**Comment by korydraughn** [comment]
Adding the timestamp to the delay server log file is not trivial.

Potential solutions include:
- Setting the `ProcessType` of the delay server to `RE_SERVER_PT` and possibly adjusting several locations in the codebase
- Or, introduce a new logging function that is a stripped down version of `rodsLog`
  - While this is easier to implement, it's not worth it as doing this could introduce more bugs if not handled properly

Closing as this has already been resolved in 4.3.
