### ISSUE TITLE
Inconsistent errors for `irm` of object with own permission in collection with read permission

### ISSUE THREAD

**Issue by alanking** [irods/irods#6428]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---
### iRODS Version, OS and Version
4.2.11/pre-4.3.0

### What did you try to do?
`irm` a data object as a `rodsuser` with own permission on the object but "read object" permission on the parent collection:
```bash
$ ils ../public/testdir -AL
/tempZone/home/public/testdir:
        ACL - alice#tempZone:read object   rods#tempZone:own
        Inheritance - Disabled
  rods              0 demoResc          283 2022-06-01.15:00 & foo
        generic    /var/lib/irods/Vault/home/public/testdir/foo
        ACL - alice#tempZone:own   rods#tempZone:own
$ irm ../public/testdir/foo
```

### Expected behavior
Consistent behavior when connected to any server in a given zone

### Observed behavior (including steps to reproduce, if applicable)
On the catalog service consumer:
```bash
$ irm ../public/testdir/foo
remote addresses: 127.0.0.1 ERROR: rmUtil: rm error for /tempZone/home/public/testdir/foo, status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION
$ ils ../public/testdir -AL
/tempZone/home/public/testdir:
        ACL - alice#tempZone:read object   rods#tempZone:own
        Inheritance - Disabled
$ ils ../../trash/home/alice/public/testdir -AL
/tempZone/trash/home/alice/public/testdir:
        ACL - alice#tempZone:own
        Inheritance - Disabled
  rods              0 demoResc          283 2022-06-01.15:11 & foo
        generic    /var/lib/irods/Vault/trash/home/alice/public/testdir/foo
        ACL - alice#tempZone:own   rods#tempZone:own
```
And in the log file:
```
Jun  1 15:11:33 pid:690 remote addresses: 127.0.0.1, 192.168.96.3 ERROR: cannot set mtime: Unknown error -818000
Jun  1 15:11:33 pid:690 remote addresses: 127.0.0.1, 192.168.96.3 ERROR: rsMvDataObjToTrash: rcDataObjRename error for /tempZone/trash/home/alice/public/testdir/foo, status = -818000
```

When connected to the catalog service provider...
```bash
$ ils -AL ../public/testdir
/tempZone/home/public/testdir:
        ACL - alice#tempZone:read object   rods#tempZone:own   
        Inheritance - Disabled
  rods              0 demoResc          283 2022-06-01.16:54 & foo
        generic    /var/lib/irods/Vault/home/public/testdir/foo
        ACL - alice#tempZone:own   rods#tempZone:own
$ irm ../public/testdir/foo
$ echo $?
0
$ ils ../../trash/home/alice/public/testdir -AL
/tempZone/trash/home/alice/public/testdir:
        ACL - alice#tempZone:own
        Inheritance - Disabled
  rods              0 demoResc          283 2022-06-01.17:00 & foo
        generic    /var/lib/irods/Vault/trash/home/alice/public/testdir/foo
        ACL - alice#tempZone:own   rods#tempZone:own
```

So, everything is the same, but an error message is returned when connected to the catalog service consumer. Do we expect an error message or not?

Found when running `test_ichmod.Test_ichmod.test_ichmod_access_levels` from a catalog service consumer.

**Comment by alanking** [comment]
The failure appears to be occurring when the collection mtime is being updated after the rename operation. The reason the failure only occurs when connected to the catalog service consumer is because `scoped_privileged_client` is being used to elevate the client privileges in order to update the collection mtime regardless of their permissions on the collection. When the connection is redirected to the catalog service provider, a new `rsComm` is created for the server-to-server connection and this connection appears to not be privileged anymore.

This problem likely exists for all of the APIs which have a collection mtime update block like this, but it's hard-ish to hit because it's an unusual use case:
https://github.com/irods/irods/blob/2e82164055d1e6c2a3c64eedc534b45c9449df07/server/api/src/rsDataObjRename.cpp#L434-L461

**Comment by korydraughn** [comment]
I'm thinking we can fix this by changing the code to use the service account user to update the mtime.

A few things need to happen:
- Use `scoped_client_identity` to become the service account user
- `last_write_time` of the filesystem library grows support for the admin tag

That way, updating the mtime for the parent collection is always handled by the administrator.

**Comment by trel** [comment]
well, 'the administrator' is just the `rodsadmin` defined in that server's service account... if there are more than one `rodsadmin` in the zone... does this matter?

**Comment by korydraughn** [comment]
No. It doesn't matter.

However, I'm now starting to think we are better off creating a new connection using the local admin instead of `scoped_client_identity` because connections established via redirection aren't disconnected until the agent ends.

**Comment by trel** [comment]
> creating a new connection 

I think that sounds more safe in the long run.

**Comment by alanking** [comment]
I'm going to reopen this because this issue still exists when the collection is in a remote zone. The collection mtime is updated by the remote unlink API call, so we just need to elide the collection mtime update for remote collections (very similar to #6842).
