### ISSUE TITLE
`iget -r` cannot be combined with `-n`

### ISSUE THREAD

**Issue by kript** [irods/irods#6444]
### iRODS Version, OS and Version

4.2.7
Ubuntu 18.04

### What did you try to do?

` iget -KVr -n 10 <collection>`

### Expected behavior

An error telling me those options don't combine (yes, you an I know this, but the documentation isn't obvious for new users).

### Observed behavior (including steps to reproduce, if applicable)

```
remote addresses: 10.160.2.32 ERROR: getCollUtil: getDataObjUtil failed for <collection>. status = -164000 status = -164000 SYS_REPLICA_DOES_NOT_EXIST
```

**Comment by trel** [comment]
Well, they *can* combine?     But in this case, there was not a `replica number 10` for every object under that collection?

**Comment by kript** [comment]
Huh, OK, I didn't think that would work, but yes, in this case, the user was doubly confused, possibly copy-pasting from some instructions (maybe mine!).
