### ISSUE TITLE
metadata.hpp contains definitions that should be in a cpp file somewhere.

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#6445]
- [x] main
- [x] 4-3-stable
---
[`metadata.hpp`](https://github.com/irods/irods/blob/f6eb6c72786288878706e2562a370b91b7d0802e/lib/core/include/irods/metadata.hpp) is full of function definitions that should be moved to a `.cpp` file and replaced with declarations. In its current state, including the header more than once in a single library or executable will result in linker errors due to overlapping symbol definitions.

**Comment by phdavis1027** [comment]
Addressed by PR #6446
