### ISSUE TITLE
iput numThreads

### ISSUE THREAD

**Issue by xkdzml** [irods/irods#6447]
Can I use multi threads when I run iput?

I want to change the number of threads during iput execution, what should I do?

```
iput -N 32 data
```
Is this the right way to use it?

I wonder if you currently support multi-threads.

**Comment by trel** [comment]
Yes, that is correct.  But it will be limited by the maximum set in the server's policy (usually 16 by default).

Tests have shown that for most connections, `N=3` will provide the maximum throughput.

**Comment by xkdzml** [comment]
Does that mean that even if I give you a large value of N, I will use 3 threads?
(Tests have shown that for most connections, ```N=3``` will provide the maximum throughput.)

**Comment by trel** [comment]
No, the number of threads to use is a negotiation between the client and the server.   The request from the client is considered by the server, and honored if the server's policy allows it.  Otherwise, the server will set the default and the maximum accordingly.

If you ask for 32, and the default max is 16, then the server will use 16.

If you don't ask, then the server will probably choose 3.

**Comment by trel** [comment]
The `-N` option affects how many threads are used for a single transfer.

In this case, the `-N` will be used for each of the files uploaded during the recursive put.  There is currently no option for controlling how many files are uploaded concurrently during a recursive `iput -r`.

So the speed up you will see from the `-N` option will be limited to 'large' files that individually complete their upload faster than if you had used `-N1` or `-N2`.  But each file in the `data` directory will still be uploaded serially.

**Comment by trel** [comment]
That should work.

If you're having trouble with parallel transfer, it suggests a firewall issue - ports 20000-20199 need to be opened (by default) for the non-streaming transfer to succeed.

**Comment by xkdzml** [comment]
I checked that the port was used without any problems using ```netstat-nap``` when sending from A to A. 
But there was an error when I sent it from A to B.

I attached the error and ```netstat -nap``` execution below.
## error
```
syslab@cluster1:~$ iput data.json 
remote addresses: 165.194.35.82 ERROR: getaddrinfo_with_retry address resolution timeout [cluster2] [ai_flags: [0] ai_family: [2] ai_socktype: [0] ai_protocol: [0]]
remote addresses: 165.194.35.82 ERROR: putUtil: put error for /tempZone/home/alice2/data.json, status = -303000 status = -303000 USER_RODS_HOSTNAME_ERR
```
## A-->A
```
root@cluster2:/home/syslab# netstat -nap | grep 20021                                         
tcp        0      0 0.0.0.0:20021           0.0.0.0:*               LISTEN      56089/irodsServer   
tcp        0      0 127.0.0.1:35764         127.0.1.1:20021         ESTABLISHED 56088/iput           
tcp        0   3392 127.0.0.1:35770         127.0.1.1:20021         ESTABLISHED 56088/iput           
tcp        0   3392 127.0.0.1:35766         127.0.1.1:20021         ESTABLISHED 56088/iput           
tcp        0      0 127.0.1.1:20021         127.0.0.1:35764         ESTABLISHED 56089/irodsServer   
tcp        0      0 127.0.1.1:20021         127.0.0.1:35766         ESTABLISHED 56089/irodsServer   
tcp        0      0 127.0.1.1:20021         127.0.0.1:35770         ESTABLISHED 56089/irodsServer   
tcp        0      0 127.0.0.1:35768         127.0.1.1:20021         ESTABLISHED 56088/iput           
tcp        0     24 127.0.1.1:20021         127.0.0.1:35768         ESTABLISHED 56089/irodsServer
```
## A-->B
```
root@cluster2:/home/syslab# netstat -nap | grep 20137                                         
tcp        0      0 0.0.0.0:20137           0.0.0.0:*               LISTEN      56151/irodsServer
```

**Comment by xkdzml** [comment]
When sending data from client A to server B, it was possible only when N is 1.

This is an output sentence when the value of N is given as 4 and checked by -V.

The value of addr came out as a value("server_name") other than the ip address(xxx.xxx.xx.xx).

So, I hardcoded irods server ip address as ```rodsHost = "xxx.xxx.xxx.xxx"``` inside of ```connectToRhostPortal```function in ```SockComm.cpp```, and it proceeded without a problem even when the value of N was not 1.

I think irods server is passing hostname itself rather than server's ip address, resulting that client can't resolve hostname (machine name of linux)

I wonder if it's a problem with irods or setting.

**Comment by korydraughn** [comment]
iRODS is very sensitive to hostnames. This feels like a hostname resolution issue.

Can that hostname be resolved by the client?

You could also try using the `host_resolution` option in the server. See https://docs.irods.org/4.3.0/system_overview/configuration/#host-resolution.

**Comment by trel** [comment]
Marking this as resolved - no action necessary in the server at this time.
