### ISSUE TITLE
Scope error for constants in `irods/apiNumber.h`

### ISSUE THREAD

**Issue by dworkin** [irods/irods#6448]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---
### iRODS Version, OS and Version

irods-dev 4.3.0, CentOS7

### What is wrong?

in `irods/apiNumber.h`, constants are defined which should be `static`. This matters when the file is included (for example, through `irods/rodsClient.h`) in multiple C source files, leading to a clash at link time.

**Comment by dworkin** [comment]
Fixed in pull request #6449.

**Comment by alanking** [comment]
I will take care of cherry-picking to the other branches. Thanks!
