### ISSUE TITLE
Reference custom plugin rules in custom rule playbook

### ISSUE THREAD

**Issue by ll4strw** [irods/irods#6458]
In my  `custom.re` rule playbook I would like to call a rule defined in a custom plugin (a `.so` file) which is defined in my server conf with a particular `instance_name`. Is it possible? I tried to call directly the external rule but I get the error

```
error: cannot find rule for action
```

Is there a sort of `import/include` directive I could use? I am aware of the existance of the `@include "definitions"` directive which can read rules from an external rule file, but it does not work for me. On the command line I could execute 
```
irule -r custom-plugin ...
```
to reference a function from it (is it actually possible to pass multiple `-r` options??).

For info, in my server config I have my custom plugin loaded first and then my custom irods-rule-language file
```
"rule_engines": [
{"instance_name": "custom-plugin",....},
{"instance_name": "irods_rule_engine_plugin-irods_rule_language-instance",
..
"re_rulebase_set": [
     "custom",
     "core"
      ],
..
}
]
```

**Comment by korydraughn** [comment]
Yes, this is possible.

To make this work, your plugin must implement `exec_rule_text()`. You can use the Logical Quotas REP as a reference for achieving this. See the following:
- https://github.com/irods/irods_rule_engine_plugin_logical_quotas/blob/df75c52f6d8aa89a2b452aeb56626c2f944b5986/src/main.cpp#L360
- https://github.com/irods/irods_rule_engine_plugin_logical_quotas/blob/df75c52f6d8aa89a2b452aeb56626c2f944b5986/src/main.cpp#L331
- https://github.com/irods/irods_rule_engine_plugin_logical_quotas/blob/df75c52f6d8aa89a2b452aeb56626c2f944b5986/src/main.cpp#L220

If you want to invoke rules within your plugin from a delay rule, you'll also need to implement `exec_rule_expression()`. The Logical Quotas REP supports both of these functions and demonstrates how someone can support these through a single function.

Keep in mind that the implementation for your plugin could be very different from the Logical Quotas implementation depending on how your plugin accepts input. Logical Quotas accepts JSON as input. If your plugin also accepts JSON, you should be able to use the same pattern as the Logical Quotas REP.

> to reference a function from it (is it actually possible to pass multiple -r options??).

No, it is not possible to use multiple `-r` options.

**Comment by korydraughn** [comment]
> Thanks for the quick reply. So I should be able to call in my custom.re any rules within the logical_quotas plugin because that plugin implements exec_rule_text() and provided my plugin also implements that method then I should be able to do the same.

Correct.

> As a practical example using the logical_quotas plugin that you mention, would the following work?

No. The README for the Logical Quotas REP shows how to invoke rules defined by the plugin. That information should be near the bottom of the README. It demonstrates two ways to do this. One via the plugin itself and another via the Native REP.
