### ISSUE TITLE
remote( ) microservice does not honor INST_NAME

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#6465]
- [x] NREP (main)
- [x] NREP (4-3-stable)
- [x] NREP (4-2-stable)
- [x] PREP (main)
- [x] PREP (4-2-stable)
- [x] Documentation (main)
- [x] Documentation (4-2-stable)
---
## Bug Report
iRODS 4.3.0 , Ubuntu 18.04

### What did you try to do?
Execute some iRODS native rule text remotely when a plugin _other than the native rule plugin_ is first in the  **_rule_engines[]_** part of the server configuration.
This should be possible by using INST_NAME tag in the hints argument to remote( ), and should cause *only* the targeted RE instance to see the request.

If we configure Python as the first RE plugin (for our purposes here, `/etc/irods/core.py `can be empty but must exist):
```
$ irule -a
Level 0: Available rule engine plugin instances:
        irods_rule_engine_plugin-python-instance
        irods_rule_engine_plugin-irods_rule_language-instance
        irods_rule_engine_plugin-cpp_default_policy-instance

```
and run the following command:
```
$ irule -r irods_rule_engine_plugin-irods_rule_language-instance "remote('localhost','<INST_NAME>irods_rule_engine_plugin-irods_rule_language-instance</INST_NAME>'){writeLine('serverLog','REMOTE')}" null null
``` 
### Expected behavior
We expect to see:  
   1.  the string "REMOTE" to appear in the irods.log
   2.  no errors being logged.

### Observed behavior (including steps to reproduce, if applicable)
We do indeed see "REMOTE" appearing in the `/var/log/irods/irods.log`, but we also see the Python RE plugin trying to interpret the rule text:
```
{
  "log_category": "legacy",
  "log_facility": "local0",
  "log_level": "error",
  "log_message": "[exec_rule_text:695] Improperly formatted rule text in Python rule engine plugin",
  "request_api_name": "EXEC_MY_RULE_AN",
  "request_api_number": 625,
  "request_api_version": "d",
  "request_client_user": "rods",
  "request_host": "127.0.0.1",
  "request_proxy_user": "rods",
  "request_release_version": "rods4.3.0",
  "server_host": "thinkpad-t14-gen2",
  "server_pid": 21775,
  "server_timestamp": "2022-07-06T17:44:13.266Z",
  "server_type": "agent"
}
{
  "log_category": "legacy",
  "log_facility": "local0",
  "log_level": "info",
  "log_message": "writeLine: inString = REMOTE\n",
  "request_api_name": "EXEC_MY_RULE_AN",
  "request_api_number": 625,
  "request_api_version": "d",
  "request_client_user": "rods",
  "request_host": "127.0.0.1",
  "request_proxy_user": "rods",
  "request_release_version": "rods4.3.0",
  "server_host": "thinkpad-t14-gen2",
  "server_pid": 21775,
  "server_timestamp": "2022-07-06T17:44:13.266Z",
  "server_type": "agent"
}
```
Note the first log entry is made by exec_rule_text( ) in the Python plugin, complaining of ill-formatted text.  If INST_NAME were working as intended, the Python plugin should not be seeing any text from the irule invocation.

**Comment by d-w-moore** [comment]
This may be, at its heart, the same issue as what py_remote encounters in this comment attached to question/issue #6461.
It's plausible because both of these are essentially pass-throughs for `rsExecMyRule`  : 

   - [Native rule msvc smsi_remoteExec used by remote( )](https://github.com/irods/irods/blob/a86b0ed40bcb2bd23cf526a52244286b78285468/plugins/rule_engines/irods_rule_language/src/functions.cpp#L1889) 
   - [Python RE plugin microservice used by py_remote](https://github.com/irods/irods_rule_engine_plugin_python/blob/3ef376d5558c43ab8a790f684bbf84226c05fc28/irods_rule_engine_plugin-python.cxx#L398)

**Comment by d-w-moore** [comment]
Confirmed as early as  iRODS v4.2.8 that this is still an issue. Is my thinking wrong on this, @trel @alanking @korydraughn ?  A remote( ) hint would have to have an INST_NAME tag available, else you'd probably always be sending the right code to the wrong plugin... particularly a risk if the plugins in question were not prepared to handle the "garbage" (ie mismatched) rule string input.

**Comment by korydraughn** [comment]
`remote` probably doesn't support the `INST_NAME` hint.

@d-w-moore The code you referenced looks like it is the correct place to add support for the hint. Please look into the following code blocks:
- https://github.com/irods/irods/blob/a86b0ed40bcb2bd23cf526a52244286b78285468/plugins/rule_engines/irods_rule_language/src/functions.cpp#L1909-L1913
- https://github.com/irods/irods/blob/a86b0ed40bcb2bd23cf526a52244286b78285468/plugins/rule_engines/irods_rule_language/src/functions.cpp#L1940

See if you can extract the `INST_NAME`. If it is there, try adding it into the `rsExecMyRule` input object.

**Comment by korydraughn** [comment]
Oh, right. You're going to want to touch the function that is for remote(). 

Carry on.

**Comment by alanking** [comment]
I added a list of tasks which seems to cover the scope of the work. Let me know if it needs to be adjusted (or adjust it yourself if you have the ability to do so)
