### ISSUE TITLE
PAM auth does not work after upgrading to 4.3.0-1

### ISSUE THREAD

**Issue by darthtux** [irods/irods#6472]
### iRODS Version, OS and Version
iRODS version 4.3.0-1.x86_64
running on Centos 7

### What did you try to do?
After upgrading from iRODS version 4.2.11-1 users using PAM can no longer authenticate.  

[root@elite .irods]# iinit
Enter your current iRODS password:
Error occurred while authenticating user [rods] [PLUGIN_ERROR_MISSING_SHARED_OBJECT: [-]	/usr/include/irods/irods_load_plugin.hpp:157:irods::error irods::load_plugin(PluginType *&, const std::string &, const std::string &, const std::string &, const Ts &...) [PluginType = irods::experimental::auth::authentication_base, Ts = <char [14]>] :  status [PLUGIN_ERROR_MISSING_SHARED_OBJECT]  errno [] -- message [shared library does not exist [/usr/lib/irods/plugins/auth/libirods_auth_plugin-pam_interactive_client.so]]

] [ec=-1827000] failed with error -1827000 PLUGIN_ERROR_MISSING_SHARED_OBJECT 

### Expected behavior
Users can authenticat and use iRODS

### Observed behavior (including steps to reproduce, if applicable)
I took a working system using PAM authentication and updated it to 4.3.0-1

**Comment by korydraughn** [comment]
Please list the contents of the following directory:
- /usr/lib/irods/plugins/auth

**Comment by darthtux** [comment]
[root@elite auth]# ls -lhA    /usr/lib/irods/plugins/auth
total 2.5M
-rwxr-xr-x. 1 root root 326K Jun  9 21:50 libirods_auth_plugin-native_client.so
-rwxr-xr-x. 1 root root 435K Jun  9 21:54 libirods_auth_plugin-native_server.so
-rwxr-xr-x. 1 root root 325K Jun  9 21:50 libirods_auth_plugin-pam_password_client.so
-rwxr-xr-x. 1 root root 411K Jun  9 21:54 libirods_auth_plugin-pam_password_server.so
-rwxr-xr-x. 1 root root 138K Jun  9 21:49 libnative_client.so
-rwxr-xr-x. 1 root root 196K Jun  9 21:54 libnative_server.so
-rwxr-xr-x. 1 root root 137K Jun  9 21:50 libosauth_client.so
-rwxr-xr-x. 1 root root 196K Jun  9 21:54 libosauth_server.so
-rwxr-xr-x. 1 root root 149K Jun  9 21:50 libpam_client.so
-rwxr-xr-x. 1 root root 218K Jun  9 21:54 libpam_server.so

**Comment by korydraughn** [comment]
If you're using icommands, replace the use of "PAM" in your irods_environment.json file with "pam_password".

**Comment by darthtux** [comment]
Thanks that fixed it!  

I wonder if an update to PAM section of the docs would help others with this same issue?  The latest docs still list PAM not pam_password.  https://docs.irods.org/4.3.0/plugins/pluggable_authentication/

**Comment by darthtux** [comment]
Oh wait it looks like I can make a documentation suggestion through a Git PR.  Ill send one over shortly.

**Comment by korydraughn** [comment]
You can link the PR to this issue.

Please use the following commit message structure:
```
[irods/irods 6472] A brief description of the change ...
```
We avoid including the "#" character until we are satisfied with the changes.

**Comment by darthtux** [comment]
[irods/irods_docs 143] Update PAM documentation

**Comment by korydraughn** [comment]
You can link against this issue.

To do that, use `[irods/irods 6472]`. That lets github know that the issue is in the irods/irods repo.

You can run `git commit --amend` to update the commit message.

Once people agree on the wording, we let you know via the PR and you can then add the "#" so the github creates the references.

**Comment by alanking** [comment]
Thanks!
