### ISSUE TITLE
Rocky 9 released on July 14th

### ISSUE THREAD

**Issue by donsizemore** [irods/irods#6481]
## Feature

Rocky 9 offers clang 13 as on Rocky 8; an iRODS build may not require nearly as much retooling as the jump from CentOS 7 to RHEL 8 derivatives. It does offer Python-3.9 and OpenSSL 3.0 out of the box, though.

I mostly like the idea of installing an OS which reaches EOL after I'll be eligible for retirement.

**Comment by korydraughn** [comment]
This was included in 4.3.1. See #7191.
