### ISSUE TITLE
Delayed rules do not honor remote user ownership

### ISSUE THREAD

**Issue by alanking** [irods/irods#6482]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---
### iRODS Version, OS and Version
4.2.11

### What did you try to do?

- Created 2 zones: zoneA and zoneB
- Created a rodsuser in zoneB named alice (alice#zoneB) and a rodsuser in zoneA named alice#zoneB
- Implemented the following rule in core.re in zoneA:
```
pep_api_data_obj_put_post(*INSTANCE_NAME, *COMM, *DATAOBJINP, *BUFFER, *PORTAL_OPR_OUT)
{
    delay("<PLUSET>31s</PLUSET>") {
        writeLine('serverLog', 'pep_api_data_obj_put_post... but delayed');
    }
    writeLine('serverLog', 'pep_api_data_obj_put_post... enqueued delayed rule');
}
```
As alice#zoneB in zoneB, I ran the following:
```
$ iput localfile /zoneA/home/public/foo
```

The put to zoneA completes successfully and of course the PEP in zoneA caused a delayed rule to be enqueued in zoneA:
```
$ iqstat -al
Pending rule-executions
id: 10028
name:   
        writeLine('serverLog', 'pep_api_data_obj_put_post... but delayed');
    
rei_file_path: EMPTY_REI_PATH
user_name: alice
address: 
time: 1658327271 : 2022-07-20.14:27:51
frequency: 
priority: 5
estimated_exe_time: 
notification_addr: 
last_exe_time: 
exec_status: 
```

### Expected behavior
See my writeLine call in the rodsLog and the delayed rule is removed from the queue.

### Observed behavior (including steps to reproduce, if applicable)
In the logs I see this:
```
Jul 20 14:27:20 pid:557 NOTICE: writeLine: inString = pep_api_data_obj_put_post... enqueued delayed rule
Jul 20 14:28:08 pid:607 NOTICE: writeLine: inString = pep_api_data_obj_put_post... but delayed
Jul 20 14:28:08 pid:607 remote addresses: 192.168.160.3, 192.168.160.4 ERROR: rsRuleExecDel: rcRuleExecDel failed, status = -350000
Jul 20 14:28:38 pid:613 NOTICE: writeLine: inString = pep_api_data_obj_put_post... but delayed
Jul 20 14:28:38 pid:613 remote addresses: 192.168.160.3, 192.168.160.4 ERROR: rsRuleExecDel: rcRuleExecDel failed, status = -350000
Jul 20 14:29:08 pid:615 NOTICE: writeLine: inString = pep_api_data_obj_put_post... but delayed
Jul 20 14:29:08 pid:615 remote addresses: 192.168.160.3, 192.168.160.4 ERROR: rsRuleExecDel: rcRuleExecDel failed, status = -350000   
Jul 20 14:29:38 pid:617 NOTICE: writeLine: inString = pep_api_data_obj_put_post... but delayed
Jul 20 14:29:38 pid:617 remote addresses: 192.168.160.3, 192.168.160.4 ERROR: rsRuleExecDel: rcRuleExecDel failed, status = -350000   
... and so on, forever ...
```
The delayed rule is stuck in the queue.

The user_name listed in the `iqstat` output is "alice" even though we would expect this to be "alice#zoneB". So, alice#zoneB is executing the rule, but fails to remove the rule because the owner of the delayed rule is alice (implicitly, alice#zoneA, who does not exist).

Delayed rules should account for remote zones when considering the owner at the time it is enqueued.

**Comment by cgrzemba** [comment]
I think the delayed rule execution was working in version 4.2.10

**Comment by alanking** [comment]
Ooh, you're right, @cgrzemba 

I performed the steps above on 2 4.2.10 zones and got a different result.

The `iqstat` output looks identical to 4.2.11:
```
Pending rule-executions
id: 10022
name: 
        writeLine('serverLog', 'pep_api_data_obj_put_post... but delayed');
    
rei_file_path: EMPTY_REI_PATH
user_name: alice
address: 
time: 1658342981 : 2022-07-20.18:49:41
frequency: 
priority: 5
estimated_exe_time: 
notification_addr: 
last_exe_time: 
exec_status: 
```

In the log:
```
Jul 20 18:49:10 pid:442 WARNING: Microservice parameter type is not supported. Ignoring parameter.
Jul 20 18:49:10 pid:442 WARNING: Microservice parameter type is not supported. Ignoring parameter.
Jul 20 18:49:10 pid:442 WARNING: Microservice parameter type is not supported. Ignoring parameter.
Jul 20 18:49:10 pid:442 NOTICE: writeLine: inString = pep_api_data_obj_put_post... enqueued delayed rule
Jul 20 18:50:10 pid:490 NOTICE: writeLine: inString = pep_api_data_obj_put_post... but delayed
```
The output stops there, and the delayed rule is removed from the queue, as one would expect.

So we need to figure out what changed in 4.2.11. Good catch.

**Comment by cgrzemba** [comment]
It seems to work if i revert
commit 579d0c2958d69e5c510e903907310d374799e866
Author: Kory Draughn <korydraughn@renci.org>
Date:   Thu Oct 28 10:10:03 2021 -0400

    [#5976] Check client's auth info instead of proxy's on delay rule deletion.

But this is surely not right way to fix.

**Comment by cgrzemba** [comment]
I an other test I use this commit and add a log message to the "return USER_ACCESS_DENIED" exit and get:
the clientUser has the authFlag  REMOTE_PRIV_USER_AUTH (4) the proxyUser the authFlag LOCAL_PRIV_USER_AUTH(5)
so the proxyUser passes the if statment 
`if (rsComm->clientUser.authInfo.authFlag < LOCAL_PRIV_USER_AUTH) `
but not the clientUser.

Would it be fine to change the if statemant in the following ?
`if (rsComm->clientUser.authInfo.authFlag < REMOTE_PRIV_USER_AUTH) `

**Comment by alanking** [comment]
Ah, very good find.

The problem seems to be this: As of https://github.com/irods/irods/commit/579d0c2958d69e5c510e903907310d374799e866, delayed rule deletion is now *correctly* checking the permission level of the client user rather than the proxy user. The proxy user is always (or almost always) the service account `rodsadmin` account, which means that user will have permission to remove the delayed rule. Now that we are checking the client user, the usernames don't match because remote users always have the zone name appended but the delayed rule information is dropping the zone name from the username.

The solution, I think, is to write down the user name with the zone name in the delayed rule information in the catalog, and adjust the username check to account for this.

**Comment by korydraughn** [comment]
I have a fix for handling the deletion of delay rules created by remote users.

There is another issue though ... If a delay rule is scheduled as a result of policy, that delay rule will be owned by the user who invoked the policy.

If we allow non-admin users to delete rules created by them, that means the user can delete delay rules created indirectly as a result of policy.

Q. Should non-admin users be allowed to delete delay rules?

**Comment by korydraughn** [comment]
Given that local users can delete delay rules created by them, it makes sense to allow this for remote users as well.

So, to answer the question - Yes, non-admins should be allowed to delete delay rules.

The real problem is about how to capture the origin of a delay rule (i.e. was it created by the policy or by a client).
