### ISSUE TITLE
Investigate specific API endpoint for groupadmin operations

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#6485]
- [ ] main
- [ ] 4-3-stable
---
## Enhancement
This would fix https://github.com/irods/python-irodsclient/issues/374

This may apply to 4.2 series as well.

**Comment by korydraughn** [comment]
@MartinFlores751 New info regarding this issue. Please see https://github.com/irods/python-irodsclient/issues/374#issuecomment-1288138467

If the PRC has access to the `rcUserAdmin` API, then we don't need to introduce a new API plugin. We can tweak the PRC directly.

**Comment by d-w-moore** [comment]
@korydraughn @MartinFlores751 aok.

**Comment by korydraughn** [comment]
@MartinFlores751 With irods/python-irodsclient#408 merged, we can close this, correct?

**Comment by MartinFlores751** [comment]
> @MartinFlores751 With [irods/python-irodsclient#408](https://github.com/irods/python-irodsclient/pull/408) merged, we can close this, correct?

Correct, this issue was resolved in the PR you linked. Closing now.
