### ISSUE TITLE
Adding a duplicate AVU should result in an error

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#6504]
- [x] main
- [x] 4-3-stable
---
## Bug Report
Returning `SUCCESS()` has changed the behavior of the metadata API. It should return an error indicating the AVU already exists.
https://github.com/irods/irods/blob/ed98d6d66e861f6ace4f72769e8f251856153f4f/plugins/database/src/db_plugin.cpp#L9486-L9491
Doing this will create a problem for `iput --metadata`. See #6409 for details.

This change in behavior is not good for existing deployments that rely on duplicate AVUs producing an error.

**Comment by d-w-moore** [comment]
The problem doesn't appear in the history of 4-2-stable or any of its releases, at least up to the present-day tip of that branch e99cf5579134ee776f6291509b7b03b0b771b5ef

**Comment by trel** [comment]
Right, it was only changed in main for 4.3.0.
