### ISSUE TITLE
UseLibCXX: CMake version and LINK_LANGUAGE generator expression

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#6511]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---
This affects 4-2-stable, 4-3-stable, and main.

Related issue: #6500 

See the following lines:
https://github.com/irods/irods/blob/e99cf5579134ee776f6291509b7b03b0b771b5ef/cmake/Modules/UseLibCXX.cmake#L20-L26

This statement about `LINK_LANGUAGE` is incorrect. `LINK_LANGUAGE` wasn't added until 3.18. The version guards here need to be fixed.

**Comment by alanking** [comment]
I added checkboxes but don't want to make any assumptions. Please checkbox and close if finished. Thanks!
