### ISSUE TITLE
Sporadic test failures: `prepareServerSharedMemory` errors on server start sometimes

### ISSUE THREAD

**Issue by alanking** [irods/irods#6521]
- [ ] main
- [ ] 4-3-stable
---
### iRODS Version, OS and Version
tip of main at time of writing, but unlikely the cause (f0cb9c769c49e7ecfc24fc936da1ac0ac84af0c4)

### What did you try to do?
Run test suite

### Expected behavior
Success

### Observed behavior (including steps to reproduce, if applicable)
Sporadic failures caused by the failure sometimes failing to start. In the logs, there are errors from `prepareServerSharedMemory`:
```json
{
  "log_category": "legacy",
  "log_facility": "local0",
  "log_level": "error",
  "log_message": "prepareServerSharedMemory: failed to prepare shared memory. Exception caught [Connection refused]",
  "server_host": "9c7086fa90e2",
  "server_pid": 11800,
  "server_timestamp": "2022-08-05T15:30:34.236Z",
  "server_type": "server"
}
{
  "local_hostname": "localhost, 9c7086fa90e2",
  "log_category": "server",
  "log_facility": "local0",
  "log_level": "info",
  "port": "1247",
  "server_host": "9c7086fa90e2",
  "server_pid": 11800,
  "server_timestamp": "2022-08-05T15:30:34.261Z",
  "server_type": "server"
}
{
  "log_category": "server",
  "log_facility": "local0",
  "log_level": "info",
  "server_host": "9c7086fa90e2",
  "server_pid": 11800,
  "server_timestamp": "2022-08-05T15:30:34.283Z",
  "server_type": "server",
  "zone_info.host": "localhost",
  "zone_info.name": "tempZone",
  "zone_info.port": "1247",
  "zone_info.type": "LOCAL_ICAT"
}
{
  "log_category": "server",
  "log_facility": "local0",
  "log_level": "info",
  "log_message": "rodsServer Release version rods4.3.0 - API Version d is up",
  "server_host": "9c7086fa90e2",
  "server_pid": 11800,
  "server_timestamp": "2022-08-05T15:30:34.283Z",
  "server_type": "server"
}
{
  "log_category": "legacy",
  "log_facility": "local0",
  "log_level": "info",
  "log_message": ">>> control plane :: listening on port 1248\n",
  "server_host": "9c7086fa90e2",
  "server_pid": 11800,
  "server_timestamp": "2022-08-05T15:30:34.285Z",
  "server_type": "server"
}
{
  "log_category": "legacy",
  "log_facility": "local0",
  "log_level": "error",
  "log_message": "prepareNonServerSharedMemory: failed to get shared memory object [irods_re_cache_shared_memory_irods_rule_language_rule_engine_pid11800_c3dc4760aa001c2a8821f5d44b3e9e71e139fff09fb6864bdef2681fda18e1fd54dc86b3638240d4]. Exception caught [Invalid argument]",
  "server_host": "9c7086fa90e2",
  "server_pid": 11813,
  "server_timestamp": "2022-08-05T15:30:34.400Z",
  "server_type": "agent"
}
{
  "log_category": "legacy",
  "log_facility": "local0",
  "log_level": "error",
  "log_message": "prepareServerSharedMemory: failed to prepare shared memory. Exception caught [File exists]",
  "server_host": "9c7086fa90e2",
  "server_pid": 11813,
  "server_timestamp": "2022-08-05T15:30:34.435Z",
  "server_type": "agent"
}
```
Sometimes things continue to work but it seems that sometimes it prevents the server from coming up and it is stuck, causing all tests that follow to fail.

Have not observed this issue on 4.3.0 as released.

**Comment by alanking** [comment]
I have now observed this on a test run against 4.3.0 as released. Trying on 4-2-stable shortly

**Comment by kript** [comment]
I had seen this on the irods_demo environment - https://github.com/irods/irods_demo/pull/23

**Comment by alanking** [comment]
Linking #4675 as well, which is linked to that issue. Thanks!

**Comment by alanking** [comment]
Also, https://github.com/irods/irods/pull/6407 may fix this issue as well.

**Comment by alanking** [comment]
Still seeing this issue in main along with #6954, resulting in test failures every time I run tests.

**Comment by korydraughn** [comment]
I'll try running tip of main and seeing if I can reproduce this.

Is there a test that triggers this consistently?

**Comment by alanking** [comment]
Nope, seems to be pretty unrelated to the test in which the issue occurs. Please let us know if you get through a run without seeing this or #6954. Not entirely convinced that my workstation is not at fault...

**Comment by korydraughn** [comment]
I ran the core tests against tip of main and all tests passed on the first run.

Rerunning again.

**Comment by korydraughn** [comment]
All core tests passed again on the first run.

Also, happy to report that the testing environment is doing great.
- First run w/ concurrency level of 5 (10 containers) took ~1hr 49mins
- Second run w/ concurrency level of 6 took ~1hr 35mins

This was Ub20/Postgres10.

If I come across this issue in the future, I'll post what I find here.

**Comment by alanking** [comment]
Thanks for the update. I guess we can just leave this open for now and keep track of it.

**Comment by alanking** [comment]
I think we can go ahead and close this. I do not see this problem anymore because it has been completely eclipsed by the problems stemming from #6954.
