### ISSUE TITLE
Adjust clang-format and clang-tidy configuration

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#6527]
- [ ] main
- [ ] 4-3-stable
----
After going through the documentation for `clang-tidy` and `clang-format` and discussing it with @korydraughn, I put together [a document](https://gist.github.com/SwooshyCueb/bfea07c5176f74378f87821f1ba38392) going over some changes I think we need to make to our configurations. Opinions are welcome.

I will begin submitting PRs tomorrow/Monday to adjust our configurations.

**Comment by korydraughn** [comment]
After running experiments based on the changes presented, here are my thoughts.

---

The comments that follow are specific to clang-format. I have not reviewed the clang-tidy changes, but they seem reasonable.

### Goals of the formatting style
- Maximum readability
- Formatting should help guide the reader's eyes
- Code should appear as if one person wrote it

### Response to changes

#### Tabs vs Spaces
- After seeing how the different options for `UseTab` work, the best setting seems to be `ForIndentation`
- `ForIndentation` resulted in the code always being formatted correctly regardless of the tab size. Things were aligned correctly using spaces
    - This option appears to align perfectly with Markus' opinion
- All tools I used (e.g. tig, github code viewer) produced the expected results
- I'm a spaces man, but I can also understand the case for developers that rely on visual aids

#### Access Specifiers (e.g. `public`, `protected`, and `private`)
- I'm not a fan of indenting these, but if the team likes it, I think one or two spaces for indentation is okay
- The indentation of the content for each access specifier should not be affected by this change
- Testing out the changes resulted in the contents of the access level being indented even more which is very weird to see
- We can use the `AccessModifierOffset` to control indentation (e.g. `-3` for one space indentation based on current config)
    - This may depend on the settings for indentation width, etc
- Things to think about:
    - Is code folding out-of-scope for the formatter?
        - I don't think this is something the formatter should be concerned with. Vim supports various different schemes around folding and even allows custom folding strategies. I imagine other editors provide similar controls
        - I feel this is a situation where IDEs and editors can be improved
        - I'm willing to be convinced on this topic though

#### Argument Packing
- I think setting `AllowAllArgumentsOnNextLine` to `true` is okay
- I'm not sure about changing `BinPackArguments` to `true`
    - For me, this depends on the context and I'm not sure if clang-format can be configured to consider the context
    - This may also indicate that the design of an interface needs some work (i.e. use a `struct` as the input type)
- I'm willing to be convinced

#### Brace Wrapping
- `class`, `struct`, `union`, `enum`, and `enum class`
    - I feel that these should always break before the opening curly brace
    - In my mind, these keywords feel very similar and should be treated the same
    - Figure 1 below captures my personal mental model around this
- For namespaces, see figure 2 below

#### Figure 1 - Mental Model for classes, structs, unions, enums, and enum classes
Notice the labels on the left hand side of the source.
```cpp
HEADER     keyword name
SEPARATOR  {
BODY           // Stuff
FOOTER     };
```
#### Figure 2 - Namespaces
I prefer all of them except `B`. If I had to rank them in order of preference, they'd be ranked as follows:
1. `A`
2. `C`, `D`
3. `F`
```cpp
namespace A // Good
{
    struct data_object;
}

namespace B // Bad
{
struct data_object;
}

namespace C { // Okay
    struct data_object;
}

namespace D { // Okay

    struct data_object;

}

namespace F { // Okay until there's a nested namespace.

struct data_object;

}
```

#### Line Width
The current line width is set to 120 characters. How do we feel about this?

Decreasing it would remove the need for a horizontal scroll bar.

**Comment by SwooshyCueb** [comment]
> #### Tabs vs Spaces
> * After seeing how the different options for `UseTab` work, the best setting seems to be `ForIndentation`
> * `ForIndentation` resulted in the code always being formatted correctly regardless of the tab size. Things were aligned correctly using spaces
>     * This option appears to align perfectly with Markus' opinion

Yeah it's gonna either be `ForIndentation` or `AlignWithSpaces`. I haven't done testing with this myself, yet. Did `AlignWithSpaces` produce undesirable formatting for you?

> #### Access Specifiers (e.g. `public`, `protected`, and `private`)
> * I'm not a fan of indenting these, but if the team likes it, I think one or two spaces for indentation is okay
> * The indentation of the content for each access specifier should not be affected by this change
> * Testing out the changes resulted in the contents of the access level being indented even more which is very weird to see
> * We can use the `AccessModifierOffset` to control indentation (e.g. `-3` for one space indentation based on current config)  
>     * This may depend on the settings for indentation width, etc

I'm not a fan of half-indentation, and I'm not sure how it would work with tab-indentation. If we're not giving access modifiers their own indentation level, then they should be on the same level as record members, IMO. `IndentAccessModifiers` to `false`, and `AccessModifierOffset` to 0.

> * Is code folding out-of-scope for the formatter?
>     * I don't think this is something the formatter should be concerned with. Vim supports various different schemes around folding and even allows custom folding strategies. I imagine other editors provide similar controls
>     * I feel this is a situation where IDEs and editors can be improved
>     * I'm willing to be convinced on this topic though

In this particular case, I'm not fond of the not-my-problem/out-of-scope approach to this problem. Given that preprocessor directives breaking code-folding has consistently been a problem across various editors and IDEs for as long as I've been coding, I don't think this problem is going away any time soon, and implementing a few formatting-based workarounds is entirely reasonable, in my opinion.

> #### Argument Packing
> * I think setting `AllowAllArgumentsOnNextLine` to `true` is okay
> * I'm not sure about changing `BinPackArguments` to `true`
>     * For me, this depends on the context and I'm not sure if clang-format can be configured to consider the context
>     * This may also indicate that the design of an interface needs some work (i.e. use a `struct` as the input type)
> * I'm willing to be convinced

I haven't done much testing yet, but my understanding is that setting `BinPackArguments` to `true` *allows* but does not *enforce* packed arguments, therefore allowing the developer to choose whether or not to pack arguments themselves based on context.

> #### Brace Wrapping
> * `class`, `struct`, `union`, `enum`, and `enum class`
>     * I feel that these should always break before the opening curly brace
>     * In my mind, these keywords feel very similar and should be treated the same

I'm fine with this. As I've said previously, I don't feel as strongly towards brace wrapping in these cases as I do with control statements.

> #### Figure 2 - Namespaces
> 
> I prefer all of them except `B`. If I had to rank them in order of preference, they'd be ranked as follows:
> 
> 1. `A`
> 2. `C`, `D`
> 3. `F`
> 
> ```c++
> namespace A // Good
> {
>     struct data_object;
> }
> 
> namespace B // Bad
> {
> struct data_object;
> }
> 
> namespace C { // Okay
>     struct data_object;
> }
> 
> namespace D { // Okay
> 
>     struct data_object;
> 
> }
> 
> namespace F { // Okay until there's a nested namespace.
> 
> struct data_object;
> 
> }
> ```

I don't like `B` or `F`, but I'd be fine with `F` if the namespace declaration was inside precompiler conditional blocks like `extern "C"`. My preference here is `C` or `D`, but namespace declarations happen infrequently enough that I'm fine with `A`.

> #### Line Width
> 
> The current line width is set to 120 characters. How do we feel about this?
> 
> Decreasing it would remove the need for a horizontal scroll bar.

I think 120 is fine. If viewing code on GitHub is problematic with 120 column lines, I would suggest the Stylus browser extension and the following userstyles:
- [GitHub Wide](https://uso.kkx.one/style/108591)
- [GitHub Gist Wide](https://uso.kkx.one/style/108592)

**Comment by korydraughn** [comment]
> Yeah it's gonna either be `ForIndentation` or `AlignWithSpaces`. I haven't done testing with this myself, yet. Did `AlignWithSpaces` produce undesirable formatting for you?

Yes. I was expecting `AlignWithSpaces` to be the correct choice, but it caused the code to be formatted differently when changing the tab width. `ForIndentation` worked across tools (i.e. tig, GitHub) and always maintained the correct formatting.

> I'm not a fan of half-indentation, and I'm not sure how it would work with tab-indentation. If we're not giving access modifiers their own indentation level, then they should be on the same level as record members, IMO. `IndentAccessModifiers` to `false`, and `AccessModifierOffset` to 0.
>
> In this particular case, I'm not fond of the not-my-problem/out-of-scope approach to this problem. Given that preprocessor directives breaking code-folding has consistently been a problem across various editors and IDEs for as long as I've been coding, I don't think this problem is going away any time soon, and implementing a few formatting-based workarounds is entirely reasonable, in my opinion.

After some discussion, @JustinKyleJames also felt indenting the access modifiers was good and helped with readability. That's two votes for indenting them so let's go with your original suggestion of `IndentAccessModifiers` being set to `true` and `AccessModifierOffset` not being defined.

I just tried this out and I was surprised at the results. The access modifiers were not indented after running clang-format. I wrote a class which contained access modifiers and I wrote a struct that did not contain access modifiers. The struct's data members were indented two levels as I expected. The class was not touched which was unexpected. Perhaps, I'm misunderstanding something with these options. I'll look into this more.

> I haven't done much testing yet, but my understanding is that setting `BinPackArguments` to `true` allows but does not enforce packed arguments, therefore allowing the developer to choose whether or not to pack arguments themselves based on context.

Let's also give your suggestions regarding `AllowAllArgumentsOnNextLine` and `BinPackArguments` a try.

> I'm fine with this. As I've said previously, I don't feel as strongly towards brace wrapping in these cases as I do with control statements.

Let's leave these options as is for now then.

> I don't like `B` or `F`, but I'd be fine with `F` if the namespace declaration was inside precompiler conditional blocks like `extern "C"`. My preference here is `C` or `D`, but namespace declarations happen infrequently enough that I'm fine with `A`.

Let's leave this option as is too.

> I think 120 is fine. If viewing code on GitHub is problematic with 120 column lines, I would suggest the Stylus browser extension and the following userstyles:
>
> - GitHub Wide
> - GitHub Gist Wide

I wasn't aware of these. I'll look into them.

---

Moving forward, I think we apply all of the changes to irods/irods except the tab based changes. For new repos, we try using the changes suggested and see how we feel.

**Comment by SwooshyCueb** [comment]
> Yes. I was expecting `AlignWithSpaces` to be the correct choice, but it caused the code to be formatted differently when changing the tab width. `ForIndentation` worked across tools (i.e. tig, GitHub) and always maintained the correct formatting.

I'm going to do some testing of my own here. The value name and the documentation are unclear and I just need to see the results for myself before I feel comfortable giving my approval to one or the other.

> After some discussion, @JustinKyleJames also felt indenting the access modifiers was good and helped with readability. That's two votes for indenting them so let's go with your original suggestion of `IndentAccessModifiers` being set to `true` and `AccessModifierOffset` not being defined.
>
> I just tried this out and I was surprised at the results. The access modifiers were not indented after running clang-format. I wrote a class which contained access modifiers and I wrote a struct that did not contain access modifiers. The struct's data members were indented two levels as I expected. The class was not touched which was unexpected. Perhaps, I'm misunderstanding something with these options. I'll look into this more.

I re-read the `clang-format` documentation for `IndentAccessModifiers` and realized I missed a crucial (and disgusting) part (emphasis mine):

> **When `true`**, access modifiers get their own indentation level. As a consequence, **record members are always indented 2 levels below the record, regardless of the access modifier presence.** Value of the `AccessModifierOffset` is ignored.

Icky. I am very much against record members being two indentation levels below the record when access modifiers are *not* present. `IndentAccessModifiers` will have to be `false`.

I still think access modifiers should be indented a level below the record rather than having them on the same indentation level as the record. This means setting `AccessModifierOffset` to `0`. With `IndentAccessModifiers` set to `false`, this means that access modifiers will be on the same indentation level with record members, which I disprefer but am fine with.

----

I've updated the document, and I've added a couple of sections for how some indentation-related style options should be configured for tab-indented and space-indented codebases.

**Comment by korydraughn** [comment]
Yes, please continue to investigate the formatting options.

I'll review the updated gist and report my thoughts.

**Comment by SwooshyCueb** [comment]
In my testing, setting `UseTabs` to `ForIndentation` causes continuation indentation to use spaces regardless of whether or not alignment is required, but `AlignWithSpaces` only uses spaces for continuation indentation when alignment *is* required. (`ForContinuationAndIndentation` causes indentation *and* alignment to use tabs on continuation lines.)
Can you provide an example of where `AlignWithSpaces` caused alignment issues in your testing? @korydraughn

**Comment by SwooshyCueb** [comment]
Also, I think I might be changing my mind about `AlignAfterOpenBracket`. I think `Align` might be the more sensible default here. I really wish this style option was more granular. Will continue to play around with it.

**Comment by korydraughn** [comment]
Is there anything left to do for this issue?

**Comment by trel** [comment]
just some checkboxes and a label?

**Comment by SwooshyCueb** [comment]
I need to open another issue for the stuff we left for later. Once I've gotten around to that we can close this one.

**Comment by SwooshyCueb** [comment]
Wait, actually, we still need to update the other repositories. So this one's staying open for a bit anyway

**Comment by korydraughn** [comment]
> Also, I think I might be changing my mind about `AlignAfterOpenBracket`. I think `Align` might be the more sensible default here. I really wish this style option was more granular. Will continue to play around with it.

Somehow I feel I missed this. Did we discuss this?

`Align` was my first pick as well. Are you still in favor of switching back to it?

**Comment by korydraughn** [comment]
All repositories have been updated and changes are starting to settle.

If more changes are needed, we can open individual issues.

Closing.
