### ISSUE TITLE
reFuncDefs.hpp is a private header, inaccessible when compiling plugins such as the Python RE plugin

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#6545]
reFuncDefs.hpp is in a private include subdirectory. `./plugins/rule_engines/irods_rule_language/include/irods/private/re/reFuncDefs.hpp` .... Does this mean it should be absent from irods-dev, and therefore also not accessible when compiling plugins such as (in the present case) the Python RE plugin?

I do not know the answer and therefore defer to @alanking  and/or @SwooshyCueb

_Originally posted by @d-w-moore in https://github.com/irods/irods_rule_engine_plugin_python/pull/128#discussion_r951978816_

**Comment by d-w-moore** [comment]
getTaggedValues is now used in the Python RE plugin. Presently it may be used there, but `irods-dev` doesn't include private header files from irods core, so we now can only by achieve this by  copying the[ function prototype](https://github.com/irods/irods/blob/fc0653187ec7a308a466529aa76917c723c06995/plugins/rule_engines/irods_rule_language/include/irods/private/re/reFuncDefs.hpp#L121) from within reFuncDefs.h, which makes for a multiple source of truth.

**Comment by SwooshyCueb** [comment]
Correct, private headers are not to be packaged.

The rule engine plugin headers are in need of refactoring. The function declaration in question `getTaggedValues` should be moved to a server header. I'll take a look tomorrow and see if there's anything else immediately obvious that can be moved to a server include instead.

**Comment by SwooshyCueb** [comment]
Related issue: #6210
