### ISSUE TITLE
Document detached mode for unixfilesystem resources

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods#6557]
- [x] main

*4-3-stable branch does not yet exist for irods_docs repository

---
We need to add documentation around the detached mode setting for unixfilesystem resources.

Here are some notes that should be in the document:

1. A context string setting of host_mode=detached will set the resource into detached mode.
2. A separate optional context string setting of host_list will contain a comma separated list of hosts.
- If host_list does not exist but host_mode=detached, all hosts are assumed to be able to service requests for the resource.
- If host_list does exist, only the hosts in this list will be able to service requests for the resource.
- If a host list exists and the current host is not in the list, redirects will go to the host listed in the resource host field as usual.  If that host is down the request will fail even if other hosts in host_list are up.
3. The path to the resource vault path must be identical on every host that services requests for the resource.  This vault path must be in a mount to a common filesystem.
4. Registrations outside the vault are not allowed as we can't enforce that the path being registered is shared by all hosts that service requests for the resource.

These rules will be updated as needed.

**Comment by trel** [comment]
directly related to / part of #4421

**Comment by alanking** [comment]
@JustinKyleJames: Please checkbox and close if finished. Thanks!

**Comment by korydraughn** [comment]
@JustinKyleJames Can this be closed?
