### ISSUE TITLE
Is these Iget and Iput speed correct?

### ISSUE THREAD

**Issue by dekisugi123** [irods/irods#6558]
I got 2 SSD with read and write speed around 2500 MB/s. They are mounted as /mnt/client and /mnt/server.
I create a vault in /mnt/server and create resource threre. iRODS is run in local host.

I got the this speed with N = 4, file size = 25 GB : 

`iput speed = 974.424 MB/s`
`iget speed = 887.365 MB/s
`
Do you think this speed is normal or I can do something to optimize it further more?

**Comment by korydraughn** [comment]
How did you get those stats?

**Comment by dekisugi123** [comment]
I get this with -V

**Comment by korydraughn** [comment]
The numbers reported by `iput` and `iget` are surprising given your SSD speed.

We need to understand how those numbers are calculated before doing any optimizations.

**Comment by korydraughn** [comment]
What version of iRODS and OS are you running?

**Comment by dekisugi123** [comment]
I am using iRODS 4.3 and Ubuntu 20.04.1. May be it is fast because I ran it on localhost?

**Comment by trel** [comment]
Can you confirm your numbers above?

```
iput speed = 974,424 MB/s
iget speed = 887,365 MB/s
```
which is... 974 GB/s and 887 GB/s ?

Or... are we confusing commas and periods as separators?

My local `iput -V` output shows a decimal, rather than a comma...

**Comment by dekisugi123** [comment]
It is 974 GB/s and 887 GB/s.

**Comment by trel** [comment]
So fast!

(we'll investigate)

**Comment by korydraughn** [comment]
I've verified that the math is correct. We suspect the speeds reported by you are because the transfers are all local (no remote network involved) and the OS is being very smart.
