### ISSUE TITLE
client_user option in icommand 

### ISSUE THREAD

**Issue by yr-wang-hit** [irods/irods#6561]
In Python-irods client, there is usage like:

> with iRODSSession(host='localhost', port=1247, user='rods', password='1234', zone='tempZone', client_user='bob', client_zone='possibly_another_zone') as session:

Administrator can get permissions acting like client_user to put data into his/her collection and the data owner is the client_user.
If there is way to do the same thing in icommand?

imagine we have a user ` tom `, his home collection is /zone1/home/tom and admin name is ` rods `, then...
> ichmod -M write rods /zone1/home/tom

> iput a.log /zone1/home/tom

Now the owner of the file a.log in irods vault is ` rods ` instead of ` tom `.

Thanks.

**Comment by yr-wang-hit** [comment]
I'm sorry and I have found the answer
> The admin can also alias as any user via the 'clientUserName' environment
variable.

in the example we can just export clientUserName=tom to solve the problem.

**Comment by trel** [comment]
Excellent.
