### ISSUE TITLE
Segmentation fault in ils and tickets access

### ISSUE THREAD

**Issue by ll4strw** [irods/irods#6562]
- iRODS Server v 4.30, OS Rocky8
- iRODS icommands v 4.3.0, OS Centos 7 

I observe the following strange behaviour. Not sure it is my set up or something else.

A collection owner issues a ticket and communicates it to an anonymous user

```
iticket create read /my/collection/
ticket:FZYSqrV3VqTCn8d
```

Then the anonymous user can issue the following icommand to analyze the contents of the collection

```
 ils -t FZYSqrV3VqTCn8d   /my/collection/
```

However if the anonymous user tries listing with that ticket a collection for which he has no access and then again the right collection, he gets a seg fault randomly

```
ils -t FZYSqrV3VqTCn8d /another/unreadable/collection
remote addresses: x.x.x.x ERROR: lsUtil: srcPath  /another/unreadable/collection does not exist or user lacks access permission

# after a few attempts
ils -t FZYSqrV3VqTCn8d  /my/collection/
Segmentation fault (core dumped)

```

with the iRODS server logging

```
{
  "log_category": "legacy",
  "log_facility": "local0",
  "log_level": "error",
  "log_message": "[-]\t/irods_source/server/core/src/rsApiHandler.cpp:560:int readAndProcClientMsg(rsComm_t *, int) :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']\n\t[-]\t/irods_source/lib/core/src/sockComm.cpp:198:irods::error readMsgHeader(irods::network_object_ptr, msgHeader_t *, struct timeval *) :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']\n\t\t[-]\t/irods_source/plugins/network/src/tcp.cpp:190:irods::error tcp_read_msg_header(irods::plugin_context &, void *, struct timeval *) :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [only read [0] of [4]]\n\n",
  "request_api_name": "",
  "request_api_number": 110000,
  "request_api_version": "d",
  "request_client_user": "anonymous",
  "request_host": "x.x.x.x",
  "request_proxy_user": "anonymous",
  "request_release_version": "rods4.3.0",
  "server_host": "server",
  "server_pid": 103164,
  "server_timestamp": "2022-08-26T08:41:11.341Z",
  "server_type": "agent"
}
{
  "log_category": "legacy",
  "log_facility": "local0",
  "log_level": "error",
  "log_message": "Agent [103164] exiting with status = -4000",
  "request_api_name": "",
  "request_api_number": 110000,
  "request_api_version": "d",
  "request_client_user": "anonymous",
  "request_host": "x.x.x.x",
  "request_proxy_user": "anonymous",
  "request_release_version": "rods4.3.0",
  "server_host": "server",
  "server_pid": 103164,
  "server_timestamp": "2022-08-26T08:41:11.362Z",
  "server_type": "agent"
}
{
  "log_category": "legacy",
  "log_facility": "local0",
  "log_level": "error",
  "log_message": "Agent process [103164] exited with status [1]",
  "server_host": "server",
  "server_pid": 3842968,
  "server_timestamp": "2022-08-26T08:41:11.381Z",
  "server_type": "agent_factory"
}

```
To be honest I am not sure the sequence of commands is actually important because this happens randomly.

Is it a network-related problem? The same error occurs when I execute ``ils -At FZYSqrV3VqTCn8d /my/collection/``.

**Comment by trel** [comment]
So, the server is saying the client went away - which makes sense if the client (`ils`) experienced a segfault.

Ticket state is kept in the server, so it's possible that the order matters.

Thanks for the report - we'll reproduce.

**Comment by trel** [comment]
Well... me too.  :)

**Comment by alanking** [comment]
I cannot reproduce this on Rockylinux 8 running Almalinux 8 packages nor on Almalinux 8 running Almalinux 8 packages.

**Comment by trel** [comment]
iCommands were in CentOS7

**Comment by trel** [comment]
network problem or not... we should never segfault.     yes, a reproducible example would be great.

**Comment by kript** [comment]
@ll4strw  - any chance of sharing that configuration? We're looking at deploying an _identical_ setup (apart from using Ubuntu) and it would be great not to have to reinvent the wheel! Perhaps in a ghist/different repo? Or even better as an MR into https://github.com/kript/unofficial_irods_documentation?

**Comment by MartinFlores751** [comment]
I attempted to reproduce the issue with the following script ran multiple times:
```bash
for i in {0..100}
do
    ils -t <token here> /tempZone/home
    ils -t <token here>  /tempZone/home/rods
    echo
done
```

This script was run as an anonymous iRODS user on Ubuntu 20.04 on the main branch of both iRODS and icommands.

A brief snippet of output is as follows:
```
...
remote addresses: 127.0.0.1 ERROR: lsUtil: srcPath /tempZone/home does not exist or user lacks access permission
/tempZone/home/rods:

...
```

Thinking that this was similar to #6775, I attempted to recreate the issue there as well, with no success.

**Comment by korydraughn** [comment]
Are you able to reproduce it using 4.3.0 and EL8?

**Comment by korydraughn** [comment]
@MartinFlores751 Given no one has been able to reproduce this and your recent attempt didn't achieve the reported outcome, this is ok to close.

Users can always open new issues.
