### ISSUE TITLE
`irods-icommands` package missing dependencies on Almalinux 8

### ISSUE THREAD

**Issue by alanking** [irods/irods#6564]
- [x] main
- [x] 4-3-stable
---
### iRODS Version, OS and Version
4.3.0, Almalinux 8

### What did you try to do?
Install `irods-icommands` package on Almalinux 8 container:
```bash
$ history
    1  sudo rpm --import https://packages.irods.org/irods-signing-key.asc
    2  wget -qO - https://packages.irods.org/renci-irods.yum.repo | sudo tee /etc/yum.repos.d/renci-irods.yum.repo
    3  dnf update
    4  dnf install irods-icommands
    5  iinit
    6  history
```

### Expected behavior
Once installed, I can run `iinit` to connect to and authenticate with a server somewhere.

### Observed behavior (including steps to reproduce, if applicable)
```
$ iinit
iinit: error while loading shared libraries: libirods_client.so.4.3.0: cannot open shared object file: No such file or directory
```

The client library was not installed alongside the iCommands package. Seems there's just a little gap in the packaging for this platform that needs to be filled in. This problem is not exhibited on Ubuntu 20.04.

**Comment by aghsmith** [comment]
I have found the same problem when installing on RHEL8. In this case, I manually installed the appropriate rpm by downloading it from the repo manually. Is there a recommended work around e.g. installing some other rpm with the requisite library?

**Comment by alanking** [comment]
I believe that manually installing the `irods-runtime` package is all that is required to work around this.

**Comment by aghsmith** [comment]
Thanks Alan, installing the irods-runtime package fixed the problem. In fact I'd also made an error in set up of the repo, and I was able to do the install in RHEL8 using yum and the repo without the need for a manual install.

**Comment by alanking** [comment]
@SwooshyCueb - I checked the boxes but wanted to confirm with you before closing. Please close if complete. Thanks!

**Comment by SwooshyCueb** [comment]
I could've sworn I already closed this issue, and now I'm afraid that I closed a different issue by mistake. Please be on the lookout for any issues that I closed in the past hour or so that should still be open.
