### ISSUE TITLE
Support interactive PAM authentication plugin

### ISSUE THREAD

**Issue by ll4strw** [irods/irods#6576]
- [x] `iinit` - main
- [x] `iinit` - 4-3-stable
---
## Feature request
Our pam module implements the following authentication flow 
https://oauth.net/2/device-flow/
which lets users authenticate on the web (including MFA where applicable) to complete the login process. I am looking at employing this module to secure iRODS authentications via its pam plugin. However, by glancing at 

https://github.com/irods/irods/blob/6b8d2dc56af72c81a568e22df78eac7b9cd745ef/plugins/auth/src/pam_password.cpp#L43

it looks like the plugin always prompts for a passwd which would make it incompatible with my device-flow module.

My question is whether it would be possible to implement in  iRODS  a sort of keyboard-interactive authentication scheme similar to the one defined in RFC-4256 for SSH which would make the process more flexible.

**Comment by alanking** [comment]
Let's reopen this to track work on integrating the interactive PAM plugin as it seems we do not currently have one of those.

**Comment by alanking** [comment]
We have determined that the only change(s) required to support pam_interactive are in `iinit` at this point.

The plugin can be released separately from the server as it is polished, assuming no changes are needed in the auth plugin framework. It is currently being developed separately here: https://github.com/stefan-wolfsheimer/irods_auth_pam_interactive

So, once the `iinit` changes are in, I think we can close this.

**Comment by trel** [comment]
Agreed
