### ISSUE TITLE
clang-tidy complains about array to pointer decay whenever irods_error macros are used

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#6580]
- [x] main
- [x] 4-3-stable

---

Wherever one of the macros from `irods_error.hpp` is used, `clang-tidy` will complain about `__PRETTY_FUNCTION__` being decayed from an array to a pointer due to the `cppcoreguidelines-pro-bounds-array-to-pointer-decay` check.

**Comment by alanking** [comment]
Please add a label or two as appropriate. Thanks!

**Comment by SwooshyCueb** [comment]
I'm not sure any of the labels we have apply to this issue
