### ISSUE TITLE
DataObjectManager.open promoting mode 'w' to mode 'w+' when opening existing data object

### ISSUE THREAD

**Issue by tedgin** [irods/irods#6600]
- [x] main
- [x] 4-3-stable
-------

I'm using python-irodsclient version 1.1.4 with iRODS 4.2.10. I use `irods.manager.DataObjectManager.open` to open a data object using open mode `w` and implicitly allow the data object to be created, If the data object already exists, the library appears to change the open mode to `w+`. This changes the access to the data object from write-only to read-write.  

Here's an example. I run the following Python script.

```python
import os
from irods.session import iRODSSession

OBJ = "/tempZone/home/centos/demo-obj"
ENV = os.path.expanduser('~/.irods/irods_environment.json')

with iRODSSession(irods_env_file=ENV) as session:
    if session.data_objects.exists(OBJ):
        session.data_objects.unlink(path=OBJ, force=True)

    # data object is created during this call   
    session.data_objects.open(path=OBJ, mode='w')

    # data object is exists when this is called
    session.data_objects.open(path=OBJ, mode='w')
```

I have the following rule attached `pep_api_data_obj_open_post`.

```
pep_api_data_obj_open_post(*Instance, *Comm, *DataObjInp) {
  writeLine(
    'serverLog',
    'pep_api_data_obj_open_post: DataObjInp.obj_path = "' ++ *DataObjInp.obj_path ++ '"' );
  writeLine(
    'serverLog',
    'pep_api_data_obj_open_post: DataObjInp.open_flags = "' ++ *DataObjInp.open_flags ++ '"' );
}
```

When I run the script the rule writes the following to the rodsLog.

```
Sep 15 23:01:20 pid:5260 NOTICE: writeLine: inString = pep_api_data_obj_open_post: DataObjInp.obj_path = "/tempZone/home/centos/demo-obj"
Sep 15 23:01:20 pid:5260 NOTICE: writeLine: inString = pep_api_data_obj_open_post: DataObjInp.open_flags = "577"
Sep 15 23:01:21 pid:5260 NOTICE: writeLine: inString = pep_api_data_obj_open_post: DataObjInp.obj_path = "/tempZone/home/centos/demo-obj"
Sep 15 23:01:21 pid:5260 NOTICE: writeLine: inString = pep_api_data_obj_open_post: DataObjInp.open_flags = "578"
```

The flag set `577` translates to `O_WRONLY | O_CREAT | O_TRUNC`, which is the definition of open mode `w` with create allowed.  The flag set `578` translates to `O_RDWR | O_CREATE | O_TRUNC`, which is the definition of open mode `w+` with create allowed.

**Comment by korydraughn** [comment]
Testing was performed using branch created from main.

**Comment by trel** [comment]
we need any new test(s) for this?   to assert what Tony was seeing - that requested perms appear correctly in a log?

not convinced we do - but would make regression visible if we ever touch these again.

**Comment by korydraughn** [comment]
Sure. Will think about how to accomplish that.

**Comment by alanking** [comment]
Unit test that checks the openFlags? Or attempts to read?

**Comment by trel** [comment]
Fair enough.   Thanks.

Yes, the fix is / will be that we don't manipulate the open modes - they'll remain as requested by the client/user.

**Comment by korydraughn** [comment]
@alanking Please check the boxes. Thanks.

**Comment by alanking** [comment]
Done
