### ISSUE TITLE
Deprecate support for RBUDP

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#6610]
- [x] main (irods)
- [x] main (icommands)
- [x] 4-3-stable (irods)
- [x] 4-3-stable (icommands)
---
## Question
Does anyone use RBUDP for data movement?

If no one relies on it, we should remove it.

**Comment by alanking** [comment]
Given the response (or lack thereof), I vote that we deprecate this in 4.3.2 and remove in 5.0.0. Thoughts?

**Comment by trel** [comment]
Agreed.

**Comment by alanking** [comment]
Before we move forward, actually, I just noticed that @tedgin has a couple of RBUDP-related issues open. Linking them here and soliciting comments :)

https://github.com/irods/irods/issues/3532
https://github.com/irods/irods/issues/5651

And another issue from "outside": https://github.com/irods/irods/issues/2347

**Comment by korydraughn** [comment]
I agree. Deprecate and remove it.

**Comment by trel** [comment]
We'll rename this issue to 'deprecate RBUDP' and create a new issue for removal in 5.0.0.

Thanks!

**Comment by JustinKyleJames** [comment]
What does deprecation look like?  Should this be a warning message written to the logs?  Documentation change?

**Comment by trel** [comment]
Yes, for now, information in the help text is probably enough.   Could also put something in the logs for the administrator to let them know about any usage - but not as sure about that part.  It will make it into the release notes because of the issue number itself.

**Comment by trel** [comment]
look at the work done in #7591 as a model as well

**Comment by alanking** [comment]
@JustinKyleJames - Please close if complete. Thanks

**Comment by JustinKyleJames** [comment]
Closing this issue.
