### ISSUE TITLE
Possible segmentation fault.

### ISSUE THREAD

**Issue by QuarkDoe** [irods/irods#6611]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---
## Bug Report
Depending on the version of the compiler and standard libraries, `int freeL1desc_struct(l1desc& _l1desc)` may cause segmentation fault.
It will be caused by the call `_l1desc.replica_token.clear()`;
The root of the problems lies in the use of an object of type `string` initialized via `memset` in `int initL1desc()`.

Sample code reproducing the problem.
https://godbolt.org/z/EvqTb19Yo

### iRODS Version, OS and Version
iRODS 4.2.11, 4.3+, main branch
Gentoo Linux, compiled by clang 14.0.6

### What did you try to do?
run `iget <somefile>`

**Comment by korydraughn** [comment]
Thanks for the report.

We'll make sure to fix that for the next release.

**Comment by korydraughn** [comment]
@alanking Please add checkboxes for this when you get a chance. Thanks.

**Comment by alanking** [comment]
Done
