### ISSUE TITLE
iquest: problems with numeric relops

### ISSUE THREAD

**Issue by mcast** [irods/irods#6612]
Re: command such as `iquest '%s %s/%s' "select DATA_SIZE, COLL_NAME, DATA_NAME where DATA_SIZE n> '4096' and DATA_SIZE n< '8192'"` ,

I believe this is a mixture of
1. documentation request for existing relops
2. request for additional numeric relop `nbetween`

I don't remember how I discovered the numeric relative-operators, but I can find no documentation for them (looked in 4.2.7, 4.2.11, 4.3.0).

What I think I wanted is `...where DATA_CREATE_TIME nbetween '$YEAR_AGO' '$NOW'`

so I'm using `iquest '%s %s' "select sum(DATA_SIZE), count(DATA_NAME) where DATA_CREATE_TIME n> '1632301281' and DATA_CREATE_TIME n< '1663837283'"`

Is there documentation I have failed to find?

Would a new operator be useful to other people?

**Comment by trel** [comment]
The related GenQuery work will address #6168
