### ISSUE TITLE
closeAllL1desc should not call PEPs

### ISSUE THREAD

**Issue by dworkin** [irods/irods#6622]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---
`msiExecCmd` sets up communication pipes, forks, closes excess file descriptors and executes a program.

The file descriptors are closed by `closeAllL1desc`, which is called from nowhere else. It starts at `L1` to discover the descriptors, and then goes back up to `L3` to close them. However, this has all sorts of effects -- apart from closing the file descriptors -- that are unwanted at this point. It is not appropriate that `pep_resource_close_pre` is called because the relevant resource is still open in the parent process, and it's not appropriate to run _any_ rules in a forked process.

We ran into this because `msiExecCmd` was called from python code, and then `invoke_policy_enforcement_point` would call `rule_exists` in the python plugin, which deadlocks because it tries to do
```
std::lock_guard<std::recursive_mutex> lock{python_mutex};
```
from a forked process.

**Comment by dworkin** [comment]
[This code](https://github.com/irods/irods/blob/main/server/api/src/rsFileClose.cpp#L93-L100) tries to deal with an earlier version of this problem and may be superfluous after the pull request is merged, assuming that it really only deals with the `msiExecCmd` case.

**Comment by dworkin** [comment]
An earlier incarnation of this issue is #1713.

**Comment by trel** [comment]
*much* earlier :)
