### ISSUE TITLE
iscan documentation implies that it accepts multiple paths as command line arguments

### ISSUE THREAD

**Issue by tedgin** [irods/irods#6626]
- [ ] main
- [ ] 4-3-stable
- [ ] 4-2-stable
---
I'm using version 4.2.8 of iCommands.

The help output of iscan implies that it accepts multiple paths as command line arguments, but it fails when multiple commands are provided.

```console
ipc_admin@prod ~? ifsck -h
Usage: ifsck [-hKrR] srcPhysicalFile|srcPhysicalDirectory ... 
 ...
ipc_admin@prod ~? xargs -d '\n' iscan -d < object-list.txt 
remote addresses: 206.207.252.35 ERROR: scanObj: gave 24 input source path, should give one and only one
```

Please remove the `...` from the usage line of the help output so that it is clear iscan only supports one path as an argument.

**Comment by trel** [comment]
see https://github.com/irods/irods/issues/6051

**Comment by tedgin** [comment]
Oops!  sorry about that.  I'll close this as a duplicate.
