### ISSUE TITLE
iRODS errors codes attached or pointing to their documentation

### ISSUE THREAD

**Issue by fj-morales** [irods/irods#6631]
- [x] main
---
## Feature

Hi, I'm new to iRODS and when faced to the task of debuging a new issue it's tricky to understand what the error codes mean and how to solve them. For example, I've recently encounter a file in a locked state (error: LOCKED_DATA_OBJECT_ACCESS), it takes a while to figure out where to find the right mix of commands to execute to bring a file out of that state. As pointed by a colleague within my organization, the solution is in https://docs.irods.org/4.2.11/system_overview/troubleshooting/#data-object-stuck-in-locked-or-intermediate-status. However, the error code is not explicitly mentioned in this page, which makes difficult if not impossible to find the solution out of the error. Thus, it will be helpul to explicitly link the error codes and potential workarounds either with examples in the command line or poiting to an external web URL.

By the way, the same goes for the meaning of the columns shown with **iquest attrs** command 

Thanks!

**Comment by alanking** [comment]
I agree that this would be helpful. I can think of 3 things that we could potentially do:

1. Add mentions of error codes in the relevant troubleshooting sections (maybe even "tags" for the docs?).
2. Point to documentation from iCommand help text. Some of this stuff is more appropriate for a proper man page, but we don't really have those. i don't think everything is necessarily appropriate for the help text, though, as things will get really noisy.
3. Point to documentation from Doxygen. Similar issue as iCommands help text, IMO, but to a lesser degree. Don't want to obscure the usage details for a particular API behind a bunch of details about the overall system.

Now that I've written them out, I feel that your suggestion - point 1 - is the most helpful and arguably the only one we should do.

I think `iquest attrs` could probably use a dedicated page in the docs.

@trel / @korydraughn - Any thoughts on this?

**Comment by alanking** [comment]
Okay, so the tasks here are:

1. Add mention/description of `LOCKED_DATA_OBJECT_ACCESS` and `INTERMEDIATE_REPLICA_ACCESS` in Troubleshooting for "Data object stuck in locked (or intermediate) status"
2. Add new page for columns available to `iquest` (aka `iquest attrs`)
