### ISSUE TITLE
Investigate main server process memory leak

### ISSUE THREAD

**Issue by alanking** [irods/irods#6634]
- [x] main
- [x] 4-3-stable
---
### iRODS Version, OS and Version
4.3.0, CentOS 7 (not relevant; noted for posterity)

### What did you try to do?
From iRODS chat: https://groups.google.com/g/irod-chat/c/hnfJz8X5IdA/m/Qff6l_9DAwAJ

Leave iRODS server running overnight with something to do:
```bash
$ until false; do iput -vf foo ; done
```

### Expected behavior
`irodsServer` uses the same amount of memory as it did at the beginning

### Observed behavior (including steps to reproduce, if applicable)
At server start:
```bash
$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
<snip>
irods      421  0.3  0.0 919056 80956 ?        Ssl  20:32   0:18 /usr/sbin/irodsServer
irods      422  0.2  0.0 136200 12920 ?        S    20:32   0:11 /usr/sbin/irodsServer
irods      435  0.0  0.0 201440 31000 ?        Sl   20:32   0:01 irodsDelayServer
```
~14 hours later:
```bash
$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
<snip>
irods      421  0.7  0.0 1377592 251336 ?      Ssl  Oct11   7:54 /usr/sbin/irodsServer
irods      422  0.7  0.0 136200 12920 ?        S    Oct11   7:56 /usr/sbin/irodsServer
irods      435  0.0  0.0 267520 55736 ?        Sl   Oct11   0:14 irodsDelayServer
```
The RSS went from 80956 to 251336, which is leaking about ~12MB/hour.

Please investigate.

**Comment by trel** [comment]
Ah, very nice.   Will also look at https://github.com/WuBingzheng/libleak perhaps.

**Comment by trel** [comment]
We've tried to make the [development](https://github.com/irods/irods_development_environment) and [testing](https://github.com/irods/irods_testing_environment) environments more friendly to others.

I don't expect we'll be releasing debug builds publicly.  That's a bit of overhead for arguably little return, but of course, all things are up for discussion...

**Comment by korydraughn** [comment]
Before closing this issue, I'm going to run iRODS overnight to see how the memory turns out.

Will post results tomorrow.

**Comment by korydraughn** [comment]
### Initial memory stats
```bash
irods@821b4a8bbcf0:~$ date
Thu Jan  5 00:06:22 UTC 2023
irods@821b4a8bbcf0:~$ ps aux 
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
<snip>
root           7  0.0  0.0   2516   580 ?        S    00:01   0:00 sleep 2147483647d
irods       1622  0.3  0.0 821524 67312 ?        Ssl  00:01   0:00 /usr/sbin/irodsServer
irods       1623  0.1  0.0  95508 13704 ?        S    00:01   0:00 /usr/sbin/irodsServer
irods       1636  0.0  0.0  89652 32360 ?        Sl   00:01   0:00 irodsDelayServer
<snip>
```

### Workload to test memory (each command is run in a separate terminal)
```bash
until false; do iput -vf version.json foo > /dev/null; sleep 1; done
```
```bash
irule -r irods_rule_engine_plugin-irods_rule_language-instance 'delay("<EF>1</EF><INST_NAME>irods_rule_engine_plugin-irods_rule_language-instance</INST_NAME>") { writeLine("serverLog", "MY DELAY RULE"); }' null null
```

### Memory stats roughly 13 hrs later
```bash
irods@821b4a8bbcf0:~$ ps aux 
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
<snip>
irods       1622  0.3  0.0 887060 68664 ?        Ssl  00:01   2:41 /usr/sbin/irodsServer
irods       1623  0.2  0.0  95508 13704 ?        S    00:01   2:16 /usr/sbin/irodsServer
irods       1636  0.0  0.0 352988 38972 ?        Sl   00:01   0:41 irodsDelayServer
<snip>
irods@821b4a8bbcf0:~$ date
Thu Jan  5 13:10:58 UTC 2023
```

### Other Information
- The `iput` was launched first and ran by itself for a few minutes before the delay rule was added
- `iput` never caused a memory leak
- The memory started to grow once the delay rule was executed

### Takeaway
While the test is not exhaustive, the main server process and agent factory process appear to be stable. The delay server needs a bit more work to determine what is happening.

**Comment by trel** [comment]
awesome.

irodsDelayServer now showing 32360 -> 38972, which is growing about 0.5MB/hour.

if it's firing every 30s ... that's `(38972 - 32360) / (13h*60m/h*2/m)` or ~4.2kB per irodsDelayServer wakeup.

**Comment by korydraughn** [comment]
I'm going to see if I can decrease the rate of growth more.

Will report what I find.
