### ISSUE TITLE
Deprecate SimpleQuery

### ISSUE THREAD

**Issue by alanking** [irods/irods#6638]
- [x] main
- [x] 4-3-stable
---
To be removed in https://github.com/irods/irods/issues/5247

Includes a client API (`rcSimpleQuery`), server-side "shortcut" API call (`rsSimpleQuery`), and database high-level operation (`chlSimpleQuery`).

See #6624 for more details about how we got here...

**Comment by alanking** [comment]
I think deprecating the database high-level operation is a bit much.

Do I need to add anything to do the docs, or will our note about this deprecation just be part of the release notes? There is not currently any mention of it in the docs that I have been able to find.

**Comment by korydraughn** [comment]
Why do you feel deprecating the high-level op is too much?
Is it not specific to the simple query api?

I think a line in the release notes is good enough until we formalize more rules around deprecation.

**Comment by trel** [comment]
We have had a deprecation section in the release notes for the last few cycles - so work that is done in an issue will have a home in the notes.

This is that issue - so I think we're good on that front.

**Comment by alanking** [comment]
I guess I'm not sure where the line is for deprecating an API. I'm okay to deprecate `chlSimpleQuery`, but then I was wondering what other bits of machinery would need to be deprecated? I guess it all feeds back into the discussion around our deprecation model.

I figured that deprecating the user API and the internal server shortcut function would cover all known existing cases, and precisely *because* the `chl` operation is specific to SimpleQuery, it is kind of tied into the deprecation of the other bits. However, I can see the case for the other way.

Here's what I can find related to SimpleQuery:
 - `rcSimpleQuery`
 - `rsSimpleQuery`
 - `chlSimpleQuery`
 - `simpleQueryInp_t`
 - `simpleQueryOut_t`
 - `db_simple_query_op`
 - `DATABASE_OP_SIMPLE_QUERY`
 - `call_simpleQueryInp_simpleQueryOut`
 - `SIMPLE_QUERY_AN`(??)

Not sure if API numbers can be deprecated, but the rest of it seems like fair game. Thoughts?

**Comment by korydraughn** [comment]
Marking all types and functions that are highly specific to an API seems appropriate to me. The line gets a bit more blurry when things start to appear in different APIs. For the things you listed, I think adding a deprecation attribute is good.

I'm not sure you can mark a macro as deprecated. If we can't, we can leave a comment stating it is and @trel can highlight that in the release notes.

**Comment by trel** [comment]
Agreed
