### ISSUE TITLE
Memory leak in PackStruct unit test

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#6645]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---
## Bug Report
This `at_scope_exit` object needs to free the memory pointed to by `packed_result->buf` as well.
https://github.com/irods/irods/blob/4e35db0579fc31384b8b5e2241e803c333686a6a/unit_tests/src/test_packstruct.cpp#L20

**Comment by trel** [comment]
Is this related to the indexing plugin's repeated usage of delayExec() which is leaking ~100bytes per invocation?

**Comment by korydraughn** [comment]
No. The unit test had a real bug. This was found because of the indexing plugin investigation.

**Comment by trel** [comment]
Got it.
