### ISSUE TITLE
Deadlock in MySQL database plugin on many concurrent inserts

### ISSUE THREAD

**Issue by alanking** [irods/irods#6670]
- [x] main
- [x] 4-3-stable
---
> The mysql function R_ObjectId_nextval() is not safe for parallel database updates, that some of our users can trigger by opening a large number of parallel connections. This can be simulated by
> 
> ```
> (for i in $(seq 0 10); do echo 'echo "SELECT R_ObjectID_nextval();" |
> mysql -h (...) -u(...) -p(...) irods'; done) | parallel -j 10
> ```
> 
> This results in "Deadlock found when trying to get lock; try restarting transaction". After restricting the delete to only remove the row that that instance of the function has inserted, the deadlock is avoided.
> 

_Originally posted by @peterverraedt in https://github.com/irods/irods/pull/6632#issue-1404529039_

There are undocumented issues with
* users doing parallellism using python threads, and in each thread opening an irods client to upload "many small files"
* globus transfers of directories with many files to/from an irods endpoint.

I can confirm that the first exactly leads to the deadlocks that the above snippet procudes, the logs include the specific query. For globus we yet have to confirm that this issue is playing a role.

Since the R_ObjectId_seq_tbl table should always be empty, the change does not affect anything as long as the calls to R_ObjectId_nextval() are not interleaved. So the only effect plays when calls to R_ObjectId_nextval() are interleaved, in which case we now avoid deadlocks:

If two of such transactions are happening at the same time, the delete statement from the first will also attempt to remove the inserted value of the second, if mysql is in "TRANSACTION ISOLATION LEVEL READ COMMITTED;" as recommended, and this cases it to wait for the second transaction to be committed first. However, that second transaction will not commit but instead it tries to delete the row that the first (already waiting) transaction has inserted but not yet commited. This is the deadlock.

So I don't see any downsides. Also, if a row would survive somehow in the R_ObjectId_seq_tbl table, it also would have no effect, because the table is never queried except for LAST_INSERT_ID().

_Originally posted by @peterverraedt in https://github.com/irods/irods/issues/6632#issuecomment-1276548278_

**Comment by korydraughn** [comment]
This needs to be cherry-picked to 4-3-stable and 4-2-stable.

I'll go ahead and handle that.

**Comment by alanking** [comment]
Don't forget that we also need to handle upgrades. We can go ahead and cherry-pick of course, just posting a reminder

**Comment by korydraughn** [comment]
Forgot about that.

We can leave this open.

**Comment by korydraughn** [comment]
Based on the discussion starting at https://github.com/irods/irods/pull/6699#issuecomment-1309495791, we've decided to make this a 4.3 only issue.

@alanking Please remove the 4-2-stable checkbox.
