### ISSUE TITLE
`iadmin mkzone` should report an error when given invalid connection information

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#6675]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---
### iRODS Version, OS and Version
4.3.0, Ubuntu 20.04 (likely applies to previous releases as well)

### What did you try to do?
Create a remote zone without a port number.
```bash
iadmin mkzone bad_zone remote bogus
```

Create a remote zone without a hostname. _(This is more difficult to recover from. Use a test machine for this case!)_
```bash
iadmin mkzone bad_zone remote ':9999'
```

### Expected behavior
An error because zone connection info must be passed using the following form: `<hostname>:<port>`

### Observed behavior (including steps to reproduce, if applicable)
iRODS creates the zone without error.

---
This applies to `iadmin modzone <zone> conn <connection-info>` as well.

**Comment by korydraughn** [comment]
This is more about, did the admin provide a non-empty hostname and port in the expected format. This also means that the input arguments fit in the space allocated for hostnames and port numbers.

**Comment by alanking** [comment]
@SwooshyCueb - Please close if complete. Thanks!

**Comment by alanking** [comment]
Actually, hold off. Maybe need to change those log levels: https://github.com/irods/irods/pull/7077#issuecomment-1526124463

@korydraughn to confirm

**Comment by korydraughn** [comment]
Yeah, let's just create new PRs that use `LOG_ERROR` and `log_db::error`. The PRs can point to this issue.
