### ISSUE TITLE
irodsDelayServer does not start because FQDN is configured as delay_server leader

### ISSUE THREAD

**Issue by erwinvanwieringen** [irods/irods#6687]
- [x] main
- [x] 4-3-stable
------

### iRODS Version, OS and Version
iRODS 4.3.0 on RHEL7

### What did you try to do?
ON 'Fresh' iRODS 4.3.0 installation, with only 1 provider and no consumer, see that the delay server is started when irods is started

### Expected behavior
I expect an irodsDelayServer process when irods is started

### Observed behavior (including steps to reproduce, if applicable)
There is no irodsDelayServer process running. This seems to be caused by the fact that the initial delay_server leader is set to the FQDN of my iRODS host, while the code uses the (short) hostname for comparison. See command output below:
```
-bash-4.2$ hostname -f
irodshost.sub.domain.nl

-bash-4.2$ /var/lib/irods/irodsctl start

-bash-4.2$ ps -ef | grep Server
irods     4193     1  1 11:08 ?        00:00:00 /usr/sbin/irodsServer
irods     4194  4193  0 11:08 ?        00:00:00 /usr/sbin/irodsServer
irods     4215  3577  0 11:08 pts/1    00:00:00 grep --color=auto Server

-bash-4.2$ iadmin get_delay_server_info
{
    "leader": "irodshost.sub.domain.nl",
    "successor": ""
}

-bash-4.2$ iadmin set_delay_server irodshost

-bash-4.2$ ps -ef | grep Server
irods     4193     1  0 11:08 ?        00:00:00 /usr/sbin/irodsServer
irods     4194  4193  0 11:08 ?        00:00:00 /usr/sbin/irodsServer
irods     4255  4193  0 11:09 ?        00:00:00 irodsDelayServer
irods     4271  3577  0 11:09 pts/1    00:00:00 grep --color=auto Server

-bash-4.2$ iadmin get_delay_server_info
{
    "leader": "irodshost",
    "successor": ""
}
```
(actual hostname modified in this example)

**Comment by korydraughn** [comment]
You're correct. The implementation for delay server migration only considers the name returned by `gethostname`.

We'll take care of it.

**Comment by trel** [comment]
Is the current behavior wrong?

What should it use for the initial population of the 'leader' instead... trust the hostname given to the setup script?

**Comment by korydraughn** [comment]
This is solved by using the host resolution config when the migration check is run. It requires admins to define hostname aliases/IPs.

I thought about the initial population logic and decided we shouldn't change anything there. The change has to be handled by the migration logic.

**Comment by trel** [comment]
Oh, I see - just use more of the mechanisms we already have in place to define these types of scenarios.

But the initial population would still use the FQDN, which seems correct/good in most cases.

@erwinvanwieringen would still have a two-step process if he's not using FQDNs in his network/configuration.

**Comment by korydraughn** [comment]
Correct

**Comment by korydraughn** [comment]
@erwinvanwieringen I'm curious to know if you've tried including the FQDN in the /etc/hosts file?

**Comment by korydraughn** [comment]
@trel Please add the check boxes for main and 4-3-stable to this issue. Thanks.

**Comment by trel** [comment]
done, and checked 'main'.

**Comment by korydraughn** [comment]
@trel @alanking Please check the box for 4-3-stable so I can close this. Thanks.
