### ISSUE TITLE
Re-enable `test_auth`

### ISSUE THREAD

**Issue by alanking** [irods/irods#6693]
- [x] main
- [x] 4-3-stable
- [x] testing environment (configure pam)
---
`test_auth` is currently being skipped due to yet-unexplained failures. Please investigate.

**Comment by korydraughn** [comment]
Reopening as test is failing with SSL_HANDSHAKE_ERROR when running iinit.

**Comment by alanking** [comment]
The issue is that the test was actually passing on Ubuntu 18.04, but not 20.04.

The OpenSSL version installed for Ubuntu 18.04 in the testing environment is:
```
$ openssl version
OpenSSL 1.1.1  11 Sep 2018
```
The OpenSSL version installed for Ubuntu 20.04 in the testing environment is:
```
$ openssl version
OpenSSL 1.1.1f  31 Mar 2020
```
Apparently, something changed between these two versions such that a numbits value of 1024 for the `genrsa` command used to generate the certificate chain file is no longer sufficient for performing the SSL handshake between the client and the server.

If the value of numbits used to generate the certificate chain file is bumped to 2048, the test passes on both platforms.

I have confirmed that the SSL issues do not seem to manifest on Centos 7, which uses an even older version of OpenSSL. However, the test seems to fail for a different reason -- the PAM password is not being accepted. Investigating.

**Comment by alanking** [comment]
Awaiting merge of irods/irods_testing_environment#132 before closing.

**Comment by trel** [comment]
https://github.com/irods/irods_testing_environment/pull/132 is now merged.

**Comment by alanking** [comment]
Yes, confirmed that this works on all of our platforms. Closing.
