### ISSUE TITLE
msiSetDefaultResc / acSetRescSchemeForCreate no longer force Resource write when incorrect resource given

### ISSUE THREAD

**Issue by kript** [irods/irods#6711]
### iRODS Version, OS and Version

4.2.11
Ubuntu 18.04

### What did you try to do?

On 4.2.7 running as a rodsuser

`iput -K -f -R root <file>`

On a Zone which has the following rules set;

```
acSetRescSchemeForCreate {
    msiSetDefaultResc("green","null");
}
```

In this Zone there is no `root` resource, and this rule ensured (inadvertently) that the upload succeeded. 
This was direct to the Zone, not through federation.

### Expected behavior

After the upgrade, the rule continued to force end users to use a specific resource tree.

### Observed behavior (including steps to reproduce, if applicable)

After upgrading to 4.2.11, the upload failed with `SYS_RESC_DOES_NOT_EXIST`.

Normal uploads that don't specify an incorrect resource succeed.

**Comment by trel** [comment]
This is working as designed.

This update was part of https://github.com/irods/irods/issues/4084 for 4.2.9.

Diff for the docs: https://github.com/irods/irods_docs/commit/d2631f0c11212072910b8187d80f2f9b241de71a

---

Note the difference in the last row of the tables in 4.2.7:
https://docs.irods.org/4.2.7/system_overview/configuration/#default-resource-configuration
vs 4.2.11
https://docs.irods.org/4.2.11/system_overview/configuration/#default-resource-configuration

The newer behavior is what you describe:


version | client | server | result | if does_not_exist
-- | -- | -- | -- | --
4.2.7 | iput -R 'myResc' foo | msiSetDefaultResc('svr', 'null') | 'myResc' | 'svr
4.2.11 | iput -R 'myResc' foo | msiSetDefaultResc('svr', 'null') | 'myResc' | SYS_RESC_DOES_NOT_EXIST

**Comment by trel** [comment]
Closing - already documented and working as expected.
