### ISSUE TITLE
Rename base64_encode and base64_decode

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods#6716]
- [x] main
- [x] 4-3-stable
- [x] irods_client_globus_connector (main)
---
I have found when testing the Globus plugin (client to iRODS) that we appear to be linking to a version of base64_encode and base64_decode that is not the intended version.  These function names are too generic and should be placed into a namespace or something.

### Background

I first ran into this when calculating checksums for Globus.  I ended up creating my own local versions of these functions with an irods::globus namespace.

However, in 4.3 in the client authentication code these methods are also called.  The authentication was failing (due to json.dump() crash) because it seems that the wrong versions were again being picked up.  When I rebuilt the server changing the names of these function, authentication began working.

**Comment by alanking** [comment]
@JustinKyleJames - Please close if complete. Thanks!

**Comment by JustinKyleJames** [comment]
This has been merged into main and 4-3-stable and implemented in the Globus plugin.  Closing.
