### ISSUE TITLE
Failure to install `irods-auth-plugin-krb` on *Ubuntu 18.04*

### ISSUE THREAD

**Issue by wuffi** [irods/irods#6737]
### iRODS Version, OS and Version

I'm trying to install *IRODS* on *Ubuntu 18.04* (*Bionic*; AMD64) according to the instructions on <http://packages.irods.org>.

### What did you try to do?

`sudo apt install -y irods-auth-plugin-krb`

### Expected behavior

Successful installation without errors.

### Observed behavior (including steps to reproduce, if applicable)

Installation stops with the error message.
```
Depends: irods-runtime (= 4.2.6)
```
The available version of `irods-runtime` for *Ubuntu 18.04*, however, is `4.3.0-1~bionic`.

**Comment by alanking** [comment]
As @trel stated, the legacy Kerberos plugin has not been released for the 4.3 series and there are no plans to do so. For iRODS version 4.3.3 (and beyond), the Kerberos plugin can now be replaced by using `pam_interactive` and configuring the `pam_krb5` module in the PAM stack.

**Comment by korydraughn** [comment]
This issue seems like it can be closed.

Thoughts?

**Comment by korydraughn** [comment]
This issue has been addressed.

Closing.
