### ISSUE TITLE
client_connection.hpp causes duplicate definitions of irods::experimental::defer_connection

### ISSUE THREAD

**Issue by epsilon-phase** [irods/irods#6741]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---
When you are building an application with the client libraries that uses multiple files, including client_connection.hpp creates multiple definitions of defer_connection

**Comment by korydraughn** [comment]
This is fixed by #6673. I'll pull those fixes out inti a separate PR.

**Comment by trel** [comment]
4-3-stable was fixed by #6822
