### ISSUE TITLE
C client fails to build against iRODS 4.3.0 release

### ISSUE THREAD

**Issue by kjsanger** [irods/irods#6747]
### iRODS Version, OS and Version

iRODS 4.3.0, Ubuntu focal

### What did you try to do?

Compile a C client (https://github.com/wtsi-npg/baton) against the 4.3.0 irods-dev Debian package.

### Expected behavior

The client builds.

### Observed behavior (including steps to reproduce, if applicable)

Clashes from `irods/apiNumber.h` at link time when including via `irods/rodsClient.h`. An example error is:

```
/usr/bin/ld: .libs/operations.o:/usr/include/irods/apiNumberData.h:4: multiple definition of `FILE_CREATE_AN'; .libs/baton.o:/usr/include/irods/apiNumberData.h:4: first defined here
```

**Comment by alanking** [comment]
Well, would you look at that...

I was able to build baton against the `irods-{dev,runtime}` built from the main branch. That fix will be included in 4.3.1. Thanks!

**Comment by trel** [comment]
delightful - so we can close this?

**Comment by alanking** [comment]
Yes, I suppose we can.
