### ISSUE TITLE
Investigate updating CRON task configurations on configuration reload

### ISSUE THREAD

**Issue by alanking** [irods/irods#6759]
## Feature

See #6342

Once the CRON task configurations have been updated, the server is required to be restarted. This can be avoided by using `irods::experimental::json_events`, which responds to changes to specified configuration(s) and runs a function in response to a configuration reload.

The `json_event` function should update the CRON task in question such that the `interval_` reflects the new value in the configuration. This would require the CRON manager to be able to identify the tasks and remove or modify them.

Please investigate.

**Comment by alanking** [comment]
Should we pull this into 4.3.1 or 4.3.2? Seems like it would be nice...

**Comment by korydraughn** [comment]
Let's aim for 4.3.1. If we can't get it in on time, then we bump it.

**Comment by trel** [comment]
I like it... for consistency and not requiring downtime.

**Comment by korydraughn** [comment]
Noting here that iRODS 5 does not use the CRON manager anymore.

**Comment by trel** [comment]
Right - this is not worth doing for 4.3.x since it's already been removed / made moot in 5+.

I vote to close as `resolved/invalid`.

**Comment by korydraughn** [comment]
Agreed.

Closing.
