### ISSUE TITLE
iput cannot create a new object with a ticket

### ISSUE THREAD

**Issue by trel** [irods/irods#6763]
### iRODS Version, OS and Version

4.3.0

### What did you try to do?

- create a write ticket via iticket
- use `iput -T` to add a new data object using that ticket
 
### Expected behavior

a new object, i believe, with the ownership set to the user of the ticket (perhaps just 'anonymous')

### Observed behavior (including steps to reproduce, if applicable)

`CAT_NO_ROWS_FOUND`

**Comment by korydraughn** [comment]
Duplicate of #5913

**Comment by trel** [comment]
#5913 was closed in 4.2.12, so should be fixed for 4.3.1 for 'free'.    Need to confirm.

**Comment by korydraughn** [comment]
Confirmed this issue has been resolved by running the python test for #5913 against tip of main (4487206).

4-3-stable branch (d5315ae) is identical in content.
