### ISSUE TITLE
Error for password too long only occurs for passwords between 43 and 45 characters.

### ISSUE THREAD

**Issue by luijs** [irods/irods#6764]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---
## Bug Report

Error for password too long only occurs for passwords between 43 and 45 characters.

### iRODS Version, OS and Version

irods version 4.3.0-1
icommands version 4.3.0-1
ubuntu 20.04(on both client and provider host), 

### What did you try to do?

I random;y mashed my keyboard to get a long password, and it wasn't accepted by irods, with a weird error message. After tinkering I found out it was too long. However, the message PASSWORD_EXCEEDS_MAX_SIZE is not given that often.

### Expected behavior
iadmin moduser testuser password 1234567890123456789012345678901234567890123456
remote addresses: 10.4.203.69 ERROR: rcGeneralAdmin failed with error -903000 PASSWORD_EXCEEDS_MAX_SIZE

### Observed behavior (including steps to reproduce, if applicable)

iadmin moduser testuser password 1234567890123456789012345678901234567890123456
remote addresses: X.X.X.X ERROR: rcGeneralAdmin failed with error -850000 CAT_PASSWORD_ENCODING_ERROR
Level 0: Error with password encoding.  This can be caused by not connecting directly to the ICAT host, not using password authentication (using GSI or Kerberos instead), or entering your password incorrectly (if prompted).

**Comment by JustinKyleJames** [comment]
The code in db_mod_user_op first checks if the password is greater than MAX_PASSWORD_LEN - 5 (greater than 45).  In that case it generates the CAT_PASSWORD_ENCODING_ERROR.

If that succeeds it checks if the password is greater than MAX_PASSWORD_LEN - 8 (greater than 42).  In that case it generates PASSWORD_EXCEEDS_MAX_SIZE.

Therefore, anything of 46 chars or more will generate the encoding error.  Anything between 43 and 45 (inclusive) generates the max password size error.  This was verified with testing.

One possible solution is to simply return PASSWORD_EXCEEDS_MAX_SIZE on the first check.  I am not sure if there are possible scenarios where the first check would fail when the password entered is not too large.

Another solution is to perform the check in the iadmin code and reject anything > 42 chars immediately.

**Comment by korydraughn** [comment]
@JustinKyleJames What's the status of this issue?

Is this issue complete for 4-2-stable?
Are we a couple cherry-picks away from closing it?

**Comment by JustinKyleJames** [comment]
closing
