### ISSUE TITLE
`create_metadata` access level includes more access than its scope

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods#6770]
### iRODS Version, OS and Version
iRODS 4.3.0, centos7

### What did you try to do?
I tried to only add metadata on an object that I have `create_metadata` access level. After that, I did try to remove and modify any available metadata (both attached by myself or by someone else).

> The iRODS Permission Model is linear with 10 levels.
> A granted ACCESS_LEVEL also includes access to all lower ACCESS_LEVELs.

I guess this seems to be against what our interpretation is and the documentation implies above.

### Expected behavior
I expected not be able to remove or modify any available metadata

### Observed behavior (including steps to reproduce, if applicable)
I did add metadata as expected but also I was able to remove and to modify metadata attached on the object that I only have `create_metadata` access level.

Permissions:
```
[user1@dev-u0137480 ~]$ ils -A test.txt
  /u0137480/home/group1/test.txt
        ACL - user1#u0137480:own   user2#u0137480:create_metadata
```

Existing metadata:
```
[user1@dev-u0137480 ~]$ imeta ls -d test.txt
AVUs defined for dataObj /u0137480/home/group1/test.txt:
attribute: atr
value: val
units:
----
attribute: atr1
value: val1
units:
```
As user2 delete metadata:
`[user1@dev-u0137480 ~]$ imeta rm -d test.txt atr1 val1`

As user2 modify metadata:
```
[user1@dev-u0137480 ~]$ imeta mod -d test.txt atr val n:atr v:val1
[user1@dev-u0137480 ~]$ imeta ls -d test.txt
AVUs defined for dataObj /u0137480/home/group1/test.txt:
attribute: atr
value: val1
units:
```

**Comment by trel** [comment]
We'll try to reproduce.   The tests we already have should cover this case.

**Comment by mstfdkmn** [comment]
Tested by a user who has `own` access on the object. So, you can please close this.

**Comment by trel** [comment]
Perfect - thanks.
