### ISSUE TITLE
`modify_metadata` access let user remove metadata

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods#6771]
## Bug Report
I hope I am not missing something with the permission model. Another similar observation here too.

### iRODS Version, OS and Version
iRODS 4.3.0, centos7

### What did you try to do?
I tried to remove metadata attached on an object that I have only the `modify_metadata` access level.

### Expected behavior
Not to be able to remove any existing metadata on the object that I have the `modify_metadata` access level

### Observed behavior (including steps to reproduce, if applicable)
```
[user1@dev-u0137480 ~]$ ils -A test.txt
  /u0137480/home/group1/test.txt
        ACL - user1#u0137480:own   user2#u0137480:modify_metadata
[user1@dev-u0137480 ~]$ imeta ls -d test.txt
AVUs defined for dataObj /u0137480/home/group1/test.txt:
attribute: atr1
value: val2
units:
[user1@dev-u0137480 ~]$ imeta rm -d test.txt atr1 val2
[user1@dev-u0137480 ~]$ imeta ls -d test.txt
AVUs defined for dataObj /u0137480/home/group1/test.txt:
None
```

**Comment by trel** [comment]
You are linux user `user1`, but the commands above are as iRODS user `user2`?

**Comment by mstfdkmn** [comment]
Hi Terrell, I am very sorry that I might have made mistakes in this one, #6770 and #6772. Because, normally in the terminal where the linux user1 exists should have run the irods user1, and in the terminal where the linux user2 exists should have run the irods user2. I will need to test them again. But I can update these next week.

**Comment by mstfdkmn** [comment]
My apologizes! I quickly checked my terminal history and also tested one of the case mentioned here and unfortunately it seems that I runned the same user who had `own` access in my both terminal and eventually resulted in reporting these.:(
You can please close the last three issues.

**Comment by trel** [comment]
ah, very good.

please leave a comment on each - just to make sure.
