### ISSUE TITLE
itree --pattern and --ignore should mimic "tree" command more closely

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#6791]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---
## Bug Report
irods 4.2.11

### What did you try to do?
use `--pattern` (aka `-P`) and `--ignore` (`-I`) to control data objects listed in the manner of the Linux `tree` command.

### Expected behavior
Mimic tree behavior.

### Observed behavior (including steps to reproduce, if applicable)
```
$ mkdir -p tmp/coll ; touch tmp/coll/{x,y,z}{1,2}; iput -r tmp
$ tree tmp -P "X*"
tmp
└── coll
    ├── x1
    └── x2

$ itree tmp -P "x*"
tmp
  coll
Found 1 collections and 0 data objects
$ $ itree tmp -P'x.*'
tmp
  coll
    x1
    x2
```
Evidently itree uses regexes instead of file glob patterns.
So we might do one or two things along the lines of these fixes/enhancements:
   1. add a --regex-type option declaring what kind of patterns we want to use (filename-glob, regex, extended-regex)
   1. multiple search patterns could be encoded as '|'-separated expressions in an extended regex.(see the mention of  allowing "more than one argument"  at the end of the problem description for #6627)

**Comment by d-w-moore** [comment]
There may be heavy overlap here with #6628 - there's confusion there, as well , centered around regexes vs globbing.

**Comment by alanking** [comment]
@d-w-moore - Please close if complete. Thanks!
