### ISSUE TITLE
allow itree options specifying multiple match/ignore patterns

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#6806]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---
## Feature
Since`itree` already includes regex matching, and [this pull request](https://github.com/irods/irods_client_icommands/pull/340) currently plans to continue that option with the command-line switches  `--pattern-regex` and `--ignore-regex`, and since the extended regex syntax includes an OR-selector via "ptn1|ptn2|...", it seems that one way to accommodate this capability (requested at the end of [this comment](https://github.com/irods/irods/issues/6627#issue-1402401130)) might be by the addition of another switch(`--regex-extended-syntax`?)
This may be preferable to allowing multiple --ignore* and --pattern* invocations,as this would run counter to usage in the `tree` command whose example we are ostensibly following.

**Comment by alanking** [comment]
@d-w-moore - Please close if complete. Thanks!
