### ISSUE TITLE
Being stuck to names in access_type

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods#6809]
- [x] main
- [x] 4-3-stable
---
## Feature

Can iRODS clients use only the access type names available here when granting access? They are already listing them when they query available permissions on an object.
https://github.com/irods/irods/blob/2f602874739f3d0d15551127cddbac181fb88e27/server/core/include/irods/catalog_utilities.hpp#L125-L145

This is requested to clear any possible confusion around the new ACLs and to teach them to our users easily. What I mean is that it could be useful not to use/show `write` and `read` anywhere. Instead we can only use `modify_object` and `read_object`.

**Comment by korydraughn** [comment]
You're free to use any public permission exposed by the system. You'll need to refer to the help text of `ichmod` to see which permissions are public.

We cannot remove access to the read/write variants as that would break backwards compatibility.

Keep in mind that if you choose to only use the new variants, you will not be able to communicate with legacy systems because those systems don't know what `modify_object` and `read_object` are.

**Comment by mstfdkmn** [comment]
Okay thanks. You mean that the latest/newest version of iCommands can talk to an older irods and so that `ichmod`should be able to accept `read` and `write` as input. But I still dont understand why someone who interacts with 4.3.0 should see `read` and `write` in `ichmod -h`. For those who want to use against the legacy servers are able to enter `read/write` regardless of what is documented in `ichmod -h`, thus only a note specifying this can exist. I guess users should not be encouraged to use old ones (read/write) if only the new ones (read_object/writes_object) will at the end exist.

**Comment by korydraughn** [comment]
> You mean that the latest/newest version of iCommands can talk to an older irods and so that ichmod should be able to accept read and write as input.

Correct.

> But I still dont understand why someone who interacts with 4.3.0 should see `read` and `write` in `ichmod -h`. For those who want to use against the legacy servers are able to enter `read/write` regardless of what is documented in `ichmod -h`, thus only a note specifying this can exist. I guess users should not be encouraged to use old ones (read/write) if only the new ones (read_object/writes_object) will at the end exist.

Are you saying the help text shouldn't list `read`/`write` as permission values in a pure 4.3.0 environment? If we removed those values from the help text, where would users find information about them? 

We can always improve the documentation around this. Do you feel the current documentation for permissions lead to confusion?

Remember, `read` and `write` will continue to be supported in the 4.x series for backwards compatibility.

**Comment by mstfdkmn** [comment]
What I meant is that if someone uses iCommands 4.3.0 `ichmod -h` should output something like:

```
...
The iRODS Permission Model is linear with 10 levels.
A granted ACCESS_LEVEL also includes access to all lower ACCESS_LEVELs.

 - 'own'
 - 'delete_object'
 - 'modify_object'
 - 'create_object'
 - 'delete_metadata'
 - 'modify_metadata'
 - 'create_metadata'
 - 'read_object'
 - 'read_metadata'
 - 'null'

Note that if used against legacy servers (iRODS pre4.3.0), only the following access levels are allowed:

- 'own'
- 'write'
- 'read'
- 'null'

Granting 'own' to ...
```

**Comment by korydraughn** [comment]
I see. This is about improving the help text / documentation.

We'll adjust it so that it is clearer.
