### ISSUE TITLE
Allow usage of client-side and server-side dstream library implementations in the same translation unit

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#6829]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable

**Comment by alanking** [comment]
We may need to re-open this or make a new issue to address some CMake compatibility problems presented by commit b7bb3f402e88c1f444262d02272ce200a85004cd.

https://github.com/irods/irods/blob/b4aaa2ba07c8d7cd822fa1a4ba360ba7bb33135a/CMakeLists.txt#L1

The minimum required CMake listed for building iRODS is 3.7. However...
https://github.com/irods/irods/blob/b4aaa2ba07c8d7cd822fa1a4ba360ba7bb33135a/plugins/microservices/msi_tests/CMakeLists.txt#L7-L10
The CMakeLists in plugins/microservices/msi_tests uses `add_compile_definitions`, which is new in CMake 3.12: https://cmake.org/cmake/help/latest/command/add_compile_definitions.html

We either need to bump the minimum required CMake version to 3.12, or make accommodations for 3.7.

**Comment by korydraughn** [comment]
How... did it compile for me then? I'm pretty sure I used the development environment to compile those changes.

What message are you getting from CMake?

**Comment by alanking** [comment]
I used the default CMake in the `irods_core_builder.ubuntu16.Dockerfile`, which is 3.11.4: https://github.com/irods/irods_development_environment/blob/224706f9f00c27d99be152660fb0c340dcfaf082/irods_core_builder.ubuntu16.Dockerfile#L82

This is, of course, also not 3.7, but we should probably get all of that squared up regardless.

**Comment by korydraughn** [comment]
But... Ubuntu 16 is not supported anymore.

Why compile against that OS?

**Comment by alanking** [comment]
4.2.11 was released for xenial: https://packages.irods.org/apt/pool/xenial/main/i/irods-server/

Are we not releasing 4.2.12 on this platform?

**Comment by korydraughn** [comment]
Correct. Ubuntu 16 is no longer supported.

Users need to consider upgrading their OS for later releases of iRODS.
