### ISSUE TITLE
Rule engine framework should stop if the rule execution returns a success?

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods#6830]
### iRODS Version, OS and Version
iRODS 4.3.0 and 4.2.11; centos7

### What did you try to do?
I tried to call a python rule in core.py and a native rule in custom.re (or the same in core.re) by both the `irule` and the `PRC` clients without specifying a rule engine instance.

Also, I did try the same cases via a rule file (.r).

### Expected behavior
I expected consistent behaviors. 

### Observed behavior (including steps to reproduce, if applicable)
showing my configuration:
```
-bash-4.2$ irule -a
Level 0: Available rule engine plugin instances:
        irods_rule_engine_plugin-irods_rule_language-instance
        irods_rule_engine_plugin-cpp_default_policy-instance
        irods_rule_engine_plugin-python-instance
```

core.re:
```
myTestRule() {
  writeLine("serverLog","TEST");
}
```
core.py:
```
def testZone(rule_args, callback, rei):
    callback.writeLine("serverLog", "Hello, the zone - {} - is being tested.".format(rei.rsComm.proxyUser.rodsZone))
```

First the results of the direct call of the python rule (testZone) by irule (the PRC results is the same so not shown here):
```
-bash-4.2$ irule testZone null null
rsyslogd stdout | 2023-01-06T15:45:19.159779+01:00 dev-u0137480-instance1 rodsServer[3455]: u0137480_instance1 - NOTICE: writeLine: inString = Hello, the zone - u0137480_instance1 - is being tested.
rsyslogd stdout | 2023-01-06T15:45:19.160113+01:00 dev-u0137480-instance1 rodsServer[3455]: u0137480_instance1 - NOTICE: writeLine: inString = Hello, the zone - u0137480_instance1 - is being tested.
```
As seen executed two times successfully both by the python rule engine and the native rule engine.

the results of the direct call of the native rule (myTestRule) by irule:

```
-bash-4.2$ irule myTestRule null null
rsyslogd stdout | 2023-01-06T15:52:59.625864+01:00 dev-u0137480-instance1 rodsServer[3478]: u0137480_instance1 - NOTICE: writeLine: inString = TEST
rsyslogd stdout | 2023-01-06T15:52:59.626372+01:00 dev-u0137480-instance1 rodsServer[3478]: u0137480_instance1 - remote addresses: 10.0.2.100, 2a02:2c40:0:51:177:0:a:c6f6 ERROR: caught python exception: AttributeError: 'module' object has no attribute 'myTestRule'
```
 Called two times by both the python rule engine and the native rule engine.

Now calling the same rules by a rule file.

test_native.r file contains:
```
myCaller {
  myTestRule;
}
INPUT null
OUTPUT ruleExecOut
```
test_py.r file contains:
```
def main(rule_args, callback, rei):
    callback.testZone()

INPUT null
OUTPUT ruleExecOut
```

Showing the result of python rule by calling it via the rule file:
```
-bash-4.2$ irule -F test_py.r
rsyslogd stdout | 2023-01-06T16:01:09.025262+01:00 dev-u0137480-instance1 rodsServer[3513]: u0137480_instance1 - NOTICE: execMyRule @external#012def main(rule_args, callback, rei):#012    callback.testZone()#012#012 Failed with status -1201000
rsyslogd stdout | 2023-01-06T16:01:09.025603+01:00 dev-u0137480-instance1 rodsServer[3513]: u0137480_instance1 - remote addresses: 10.0.2.100, 2a02:2c40:0:51:177:0:a:c6f6 ERROR: [addMsParamToArray] - type is null for [ruleExecOut]
rsyslogd stdout | 2023-01-06T16:01:09.026092+01:00 dev-u0137480-instance1 rodsServer[3513]: u0137480_instance1 - NOTICE: writeLine: inString = Hello, the zone - u0137480_instance1 - is being tested.
```
As seen called three times by irods_rule_language, cpp_default_policy and python; succeeded only by the python rule engine.

Showing the result of the native rule by calling it via the rule file:
```
-bash-4.2$ irule -F test_native.r
rsyslogd stdout | 2023-01-06T16:05:32.992137+01:00 dev-u0137480-instance1 rodsServer[3523]: u0137480_instance1 - NOTICE: writeLine: inString = TEST
rsyslogd stdout | 2023-01-06T16:05:32.992506+01:00 dev-u0137480-instance1 rodsServer[3523]: u0137480_instance1 - remote addresses: 10.0.2.100, 2a02:2c40:0:51:177:0:a:c6f6 ERROR: [addMsParamToArray] - type is null for [ruleExecOut]
rsyslogd stdout | 2023-01-06T16:05:32.992911+01:00 dev-u0137480-instance1 rodsServer[3523]: u0137480_instance1 - remote addresses: 10.0.2.100, 2a02:2c40:0:51:177:0:a:c6f6 ERROR: caught python exception:   File "<string>", line 1#012    myCaller {#012             ^#012SyntaxError: invalid syntax
```
Called three times by irods_rule_language, cpp_default_policy and python; succeeded only by the native rule engine.

Could you please confirm if these behaviors are correct? Because a bit confused with the questions below.
- Should a python rule be called by the native iRODS rule language if its instance is not specified?
- Is it correct that the cpp_default_policy instance call rules if they are only called by a rule file (not directly) when its turn comes on (according to its order in server_config.json)?
- Is it correct python rules can only be called by the python rule engine and irods_rule_language (not by cpp_default_policy)?

**Comment by mstfdkmn** [comment]
Hi Kory,
No, I don't have, you had answered my questions. Sorry for that I hadn't sent you a reply yet.

**Comment by korydraughn** [comment]
All good.

Thanks for the update. Closing.
