### ISSUE TITLE
How to use spLogSql

### ISSUE THREAD

**Issue by kript** [irods/irods#6839]
- [x] main (irods_docs)
- [x] 4-2-stable (irods_docs)
-------

## Bug Report

This might not be a bug, just a not-reading-the-docs-correctly, moment, but

### iRODS Version, OS and Version

4.2.7
Ubuntu 18.04
PostgreSQL

### What did you try to do?

log the SQL from an `imeta` query by enabling `spLogSql` in the service accounts irods_enviornment.json file as implied by [Debugging levels documentation](https://docs.irods.org/4.2.7/system_overview/troubleshooting/#debugging-levels) and restarted the service

### Expected behavior

see the SQL from the imeta command in rodsLog or RodsServerLog (not sure which)

### Observed behavior (including steps to reproduce, if applicable)

No SQL logged.

Given https://github.com/irods/irods/issues/5734 I am not sure if I should be providing this to the server another way, so I thought I'd ask and perhaps see if the docs could be updated with the appropriate procedure.

**Comment by alanking** [comment]
Did you use `irodsctl` to restart the server? In other words, was the `spLogSql` environment variable active for the session in which you restarted the server?

**Comment by kript** [comment]
Sorry, forgot to include the config I used!

```
$ diff ~/.irods/irods_environment.json ~/.irods/irods_environment.json__b420230112 
31,32c31
<     "schema_version": "v3",
<     "spLogSql": 1
---
>     "schema_version": "v3"
```

**Comment by trel** [comment]
Ah, it's an actual service account environment variable.... ala...

```
irods $ export spLogSql=1
irods $ ./irodsctl restart
```

rather than putting it into the `~/.irods/irods_environment.json` file.

---

I think it might also work if set in 'environment_variables' in `/etc/irods/server_config.json`...

**Comment by alanking** [comment]
Right, the documentation could probably stand to be a little clearer here... @trel beat me to it on the explanation. :p

In 4.3.0 (or... perhaps it's 4.3.1), this can be configured as a log "category" as described here: https://github.com/irods/irods_docs/blob/f45ee07719b459fcb653eeb4d422bd4be003fc8c/docs/system_overview/troubleshooting.md#log-categories-and-levels

**Comment by kript** [comment]
for the benefit of other readers of this issue, my changes to `server_config.json`;

```
$ diff -c3 /etc/irods/server_config.json /etc/irods/server_config.json_b420230112 
*** /etc/irods/server_config.json	2023-01-12 16:01:15.934775671 +0000
--- /etc/irods/server_config.json_b420230112	2023-01-12 14:32:54.115094194 +0000
***************
*** 19,25 ****
      "default_resource_name": "demoResc", 
    "environment_variables": {
      "ADR_BASE": "/usr/lib/oracle/11.1/client64/log/diag",
-     "spLogSql": "1",
      "LC_ALL": "en_GB.UTF-8",
      "NLS_LANG": "AMERICAN_AMERICA.AL32UTF8",
      "ORACLE_HOME": "/usr/lib/oracle/11.1/client64"
--- 19,24 ----
```

and after a restart of the service, I get SQL in `rodsServerLog` Thanks folks!

**Comment by kript** [comment]
Sorry, I should say, the SQL turned up in `rodsLog`

**Comment by alanking** [comment]
Glad to hear.

Should we add the "environment_variables" trick to this section of the documentation?

**Comment by kript** [comment]
I think that would be nice, along with some examples of how the config is applied for each of them would make it much easier for people to 'get the gist' as it were.

**Comment by trel** [comment]
yes, we can point out that the logging things can be added to server_config.json.
