### ISSUE TITLE
Test failure: `test_federation.Test_ICommands.test_icp`

### ISSUE THREAD

**Issue by alanking** [irods/irods#6842]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---
Commit 99eab888f79f99aeb4560f76585b152a2165b36f causes copies across zones to produce an error message because the copy API is attempting to modify the collection mtime over the federation using the new client connection of the local zone rodsadmin. This causes `test_federation.Test_ICommands.test_icp` to fail.

If I revert that commit, the test passes again. So, we need to only use the privileged client connection when redirecting within a zone. A zone hint check similar to those found in `rsDataObjPut` and `rsDataObjOpen` should be used to determine which connection method to use:
https://github.com/irods/irods/blob/7a8ea89af09a3ab222f8009825dda0b207328735/server/api/src/rsDataObjPut.cpp#L685-L694

In addition to this, the copy API should not be updating the collection mtime at all. The open API already updates the collection mtime for the destination data object, except in the case of a cross-federation open. This means that the collection mtime is already being updated by the open API in the remote zone, so the open API call from the local zone does not need to reach out and update it, and neither does the copy API.

At the time of writing, the linked commit has not been merged into 4-2-stable, but the branch will require a similar fix, so I will put this in the 4.2.12 milestone.

**Comment by trel** [comment]
nice find and proposed fix.
