### ISSUE TITLE
izonereport is not listing all the resources

### ISSUE THREAD

**Issue by trel** [irods/irods#6855]
### iRODS Version, OS and Version

4.2.11

### What did you try to do?

Wanted to see all the resources in the zone via `izonereport`.

### Expected behavior

Expected to see the same list as `ilsresc`:

```
$ ilsresc
aaa:unixfilesystem
bbb:unixfilesystem
demoResc:unixfilesystem
└── tmpresc:unixfilesystem
```

Perhaps with the addition of `bundleResc` for completeness.

### Observed behavior (including steps to reproduce, if applicable)

Missing `bbb` and `tmpresc`:

```
$ izonereport | jq .zones[0].icat_server.resources[].name
"bundleResc"
"demoResc"
"aaa"
```

**Comment by Nishant2022** [comment]
I was unable to replicate this in 4.2.11. When looking at the full zone report I saw all resources created. Can you give more information on how the zone was configured?

Were there any consumer servers? If there were, were some resources created on a consumer? If so, then the resources created on the consumer should show up in the consumer server information meaning it wouldn't show up in the icat_server resources.

Perhaps a better jq command could be:
```
izonereport | jq '.zones[0].icat_server.resources[].name, .zones[0].servers[].resources[].name' 
```

**Comment by trel** [comment]
Ohhh, perhaps, indeed, they were just on different hosts... I don't remember.

I do think the following should be sufficient once `icat_server` is removed/deprecated in the next version:
   `izonereport | jq ' .zones[0].servers[].resources[].name'`

Thanks.   Willing for this to be closed as resolved/invalid if that is the case.

**Comment by Nishant2022** [comment]
In 4.3.0 I set up resources to look like the resource tree from https://docs.irods.org/4.3.0/plugins/composable_resources/

Excluding demoResc, there are 23 resources: 14 storage and 9 coordinating resources.
With an iRODS configuration with 1 provider and 4 consumers, we should expect 28 resources: 

- demoResc for the provider
- 1 default unixfilesystem resource for each of the 4 consumers
- the 23 additional resources.

```
# Getting coordinating and storage resources separately after flattening icat
$ izonereport |  jq '.zones[0].servers[].resources[].name, .zones[0].coordinating_resources[].name'
"test3"
"ufs6"
"ufs3"
"test"
"95c3a58bcac0Resource"
"ufs11"
"ufs8"
"ufs5"
"ufs2"
"test2"
"c74cd791131eResource"
"test1"
"ufs10"
"ufs1"
"ufs7"
"ufs4"
"demoResc"
"cdda8c978c92Resource"
"bdbc833c3de3Resource"
"repl1"
"pt3"
"pt2"
"pt1"
"repl2"
"deffy"
"randy"
"repl3"
"pt4"

$ izonereport |  jq '.zones[0].servers[].resources[].name, .zones[0].coordinating_resources[].name' | wc -l
28
```

All resources are accounted for and listed in the zonereport.

**Comment by korydraughn** [comment]
I believe this issue is safe to close.
