### ISSUE TITLE
izonereport should calculate and report checksums

### ISSUE THREAD

**Issue by trel** [irods/irods#6856]
- [x] main
- [x] 4-3-stable
---
## Feature

`izonereport` currently (4.2.11 and 4.3.0) generates an unpopulated field for `checksum_sha256` for every plugin:

```
  "plugins": [
    {
      "checksum_sha256": "",
      "name": "replication",
      "type": "resource",
      "version": ""
    },
```

This field should be populated with a freshly calculated sha256 checksum for every plugin shared object on the server.

**Comment by alanking** [comment]
@Nishant2022 - Please close if complete. Thanks!
