### ISSUE TITLE
izonereport should flatten the list of servers in a zone

### ISSUE THREAD

**Issue by trel** [irods/irods#6857]
- [x] main
- [x] 4-3-stable
---
The `izonereport` schema currently assumes a single catalog provider in each zone (labeled `icat_server`) with all other servers in the zone being listed in the `servers` array.

This should be collapsed/flattened into *only* the `servers` array.

- The role of each server is already captured in `catalog_service_role`.
- A zone can have more than one catalog service provider.

**Comment by alanking** [comment]
@Nishant2022 - Please close if complete. Thanks!
