### ISSUE TITLE
I want to encrypt my resource storage.

### ISSUE THREAD

**Issue by Narushima2030** [irods/irods#6881]
I would like to use the resource as an external data center to store data, and I would like to encrypt the data during communication like SSL transport encryption, is this possible?
https://github.com/irods/contrib/tree/master/microservices/administration/msiencrypt_replica
Should I encrypt the data before transmission as in the following example?

**Comment by alanking** [comment]
The linked irods/contrib microservice seems to be encrypting data which is at rest on the destination resource. This would be encryption *after* transfer, and could be implemented as a synchronous or asynchronous policy for uploading data to that resource.

You can use SSL to encrypt the data as it is sent over the network (see https://docs.irods.org/4.3.0/system_overview/ssl/), but I feel like this may not be what you're asking?

By the way, it's perfectly fine to make an issue here for questions like this, but the iRODS community is more responsive in our Google Group: https://groups.google.com/g/irod-chat As a developer, I am not the best person to answer this question, but the folks participating there should have lots of suggestions and maybe even reference implementations.

Hope that helps!

**Comment by Narushima2030** [comment]
Thank you for your response.
And thank you for adding the label.

I will look for a way to do encrypted communication in a way that takes as little time as possible to transfer when the external storage is set to RESOURCE.

We will be conversing via Google Groups chat.

**Comment by trel** [comment]
Closing - thank you.
