### ISSUE TITLE
igroupadmin mkuser doesn't properly set new user's password

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#6887]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
----

### iRODS Version, OS and Version
4.2.11, Ubuntu 18

### What did you try to do?
Create a user with pre-defined password using `igroupadmin mkuser NEW_USER  INITIAL_PASSWORD`

### Expected behavior
New user should be able to log in.

### Observed behavior (including steps to reproduce, if applicable)

We can't even `iinit` with the chosen password, let alone log in. (In the sample session, we're the admin user , but the results for a groupadmin have been tested and  are the same if they were to attempt the `mkuser` subcommand.)
```
irods:~$ igroupadmin  mkuser alibaba opensesame
irods:~$ iadmin lu
rods#tempZone
alibaba#tempZone
irods:~$ logout
ubuntu:~$ rm -fr ~/.irods
ubuntu:~$ iinit
 ERROR: environment_properties::capture: missing environment file. should be at [/home/daniel/.irods/irods_environment.json]
One or more fields in your iRODS environment file (irods_environment.json) are
missing; please enter them.
Enter the host name (DNS) of the server to connect to: localhost
Enter the port number: 1247
Enter your irods user name: alibaba
Enter your irods zone: tempZone
Those values will be added to your environment file (for use by
other iCommands) if the login succeeds.

Enter your current iRODS password:
[-]	/repos/irods/plugins/auth/native/libnative.cpp:342:irods::error native_auth_client_response(irods::plugin_context &, rcComm_t *) :  status [CAT_INVALID_USER]  errno [] -- message [Call to rcAuthResponseFailed.]

 failed with error -827000 CAT_INVALID_USER 

```

**Comment by d-w-moore** [comment]
Note it's possible that the password setting/encoding is not the problem here.  If a user is created with a known password, but the password entry is botched during iinit, the error message is actually what you'd expect from an incorrect password:
```
[-]	/repos/irods/plugins/auth/native/libnative.cpp:342:irods::error native_auth_client_response(irods::plugin_context &, rcComm_t *) :  status [CAT_INVALID_AUTHENTICATION]  errno [] -- message [Call to rcAuthResponseFailed.]
```

**Comment by alanking** [comment]
Please checkbox and close if finished. Thanks!
