### ISSUE TITLE
extra data at end of returned obj from pep_api_atomic_apply_metadata_operations_post

### ISSUE THREAD

**Issue by trel** [irods/irods#6892]
### iRODS Version, OS and Version

4.2.11

### What did you try to do?

use the returned `obj` from `pep_api_atomic_apply_metadata_operations_post()`

### Expected behavior

parseable - usable object

### Observed behavior (including steps to reproduce, if applicable)

From discussion:
  https://groups.google.com/g/irod-chat/c/FpYwVH2JVo8/m/-KDUf-VeCAAJ

> ```
> import json
> import session_vars
> 
> def pep_api_atomic_apply_metadata_operations_post(rule_args, callback, rei):
>     var_map = session_vars.get_map(rei)
>     username = var_map["client_user"]["user_name"]
>     obj = str(rule_args[2].buf)
>     print('obj', obj)
>     obj_dict = json.loads(obj)
>     print('dict', obj_dict)
> ```
> 
> I see the error... and some extra data... notice the 'ypea' garbage at the end of the printout of 'obj'...
> 
> ```
> ('obj', '{"entity_name": "/tempZone/home/alice/mustafa.txt", "operations": [{"attribute": "atr1", "operation": "add", "value": "val1"}, {"attribute": "atr2", "operation": "add", "value": "val2"}, {"attribute": "atr3", "operation": "add", "value": "val3"}], "entity_type": "data_object"}ypea')
> ```

**Comment by mstfdkmn** [comment]
That was seen with the 4.2.11 version. I tested it with 4.3.0 and I can state that you cannot see the garbage at the end of the output of the python print. But if the callback for the `writeLine` function is used, you can see it this time at the end of the value of the `operations` key. An example for what I mean:

```
def pep_api_atomic_apply_metadata_operations_post(rule_args, callback, rei):
    var_map = session_vars.get_map(rei)
    username = var_map["client_user"]["user_name"]
    obj = str(rule_args[2].buf)
    callback.writeLine("serverLog","obj: " + obj)
    #print('obj', obj) 
```

`irods stdout | {"log_category":"legacy","log_facility":"local0","log_level":"info","log_message":"writeLine: inString = obj: {\"entity_name\": \"/u0137480_instance1/home/rods/test.txt\", \"entity_type\": \"data_object\", \"operations\": [{\"operation\": \"add\", \"attribute\": \"atr1\", \"value\": \"val1\"}, {\"operation\": \"add\", \"attribute\": \"atr2\", \"value\": \"val2\"}, {\"operation\": \"add\", \"attribute\": \"atr3\", \"value\": \"val3\"}]}\u0001\n","request_api_name":"","request_api_number":20002,"request_api_version":"d","request_client_user":"rods","request_host":"10.0.2.100","request_proxy_user":"rods","request_release_version":"rods4.3.0","server_host":"dev-u0137480-instance1.irods.t.icts.kuleuven.be","server_pid":2892,"server_timestamp":"2023-02-06T12:00:54.697Z","server_type":"agent"}`

**Comment by trel** [comment]
Oh!  We'll get this sorted out.  Thank you.

**Comment by mstfdkmn** [comment]
The result of `print(rule_args[2].buf.__sizeof__())` is 96 and the result of `print(len(rule_args[2].buf))` is 283. Hope this iis what you would like to see. If you need something else please let me know.

To be sure this time my test script is
```
avus = [('atr1', 'val1'), ('atr2', 'val2'), ('atr3', 'val3')]
with iRODSSession(irods_env_file=env_file) as session:
    obj = session.data_objects.get("/u0137480_instance1/home/rods/test.txt")
    obj.metadata.apply_atomic_operations(*[AVUOperation(operation='add', \
                                  avu=iRODSMeta("{}".format(str(meta[0])), "{}".format(str(meta[1])))) for meta in avus])
```

**Comment by mstfdkmn** [comment]
And the result of json object

```
obj = str(rule_args[2].buf)
obj_dict = json.loads(obj)
print(len(obj_dict))
```
results in `irods.exception.UnknowniRODSError: None` in the client side and gives the following output in the logs:

`irods stdout | {"log_category":"legacy","log_facility":"local0","log_level":"error","log_message":"caught python exception: Traceback (most recent call last):\n  File \"/etc/irods/core.py\", line 16, in pep_api_atomic_apply_metadata_operations_post\n    obj_dict = json.loads(obj)\n  File \"/usr/lib64/python3.6/json/__init__.py\", line 354, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib64/python3.6/json/decoder.py\", line 342, in decode\n    raise JSONDecodeError(\"Extra data\", s, end)\njson.decoder.JSONDecodeError: Extra data: line 1 column 284 (char 283)\n","request_api_name":"","request_api_number":20002,"request_api_version":"d","request_client_user":"rods","request_host":"10.0.2.100","request_proxy_user":"rods","request_release_version":"rods4.3.0","server_host":"dev-u0137480-instance1.irods.t.icts.kuleuven.be","server_pid":6038,"server_timestamp":"2023-02-06T15:37:48.467Z","server_type":"agent"}`

**Comment by d-w-moore** [comment]
@mstfdkmn - just change
```
     obj = str(rule_args[2].buf)
```
to
```
     obj = str(rule_args[2].buf)[:rule_args[2].len]
```
using the .len property that @korydraughn  alluded to, above.

When moving to 4.3.0 the solution will be a little more involved, and you will probably need to use the `get_bytes` method of the BytesBuf structure. (As `str` in Python3 takes on a different meaning, and no longer respects a series of bytes as input.)

**Comment by mstfdkmn** [comment]
Thanks @d-w-moore, with your suggestion:

for 4.3.0:
```
def pep_api_atomic_apply_metadata_operations_post(rule_args, callback, rei):
    obj = rule_args[2].get_bytes()
    print(obj)

irods stdout | [123, 34, 101, 110, 116, 105, 116, 121, 95, 110, 97, 109, 101, 34, 58, 32, 34, 47, 117, 48, 49, 51, 55, 52, 56, 48, 95, 105, 110, 115, 116, 97, 110, 99, 101, 49, 47, 104, 111, 109, 101, 47, 114, 111, 100, 115, 47, 116, 101, 115, 116, 46, 116, 120, 116, 34, 44, 32, 34, 101, 110, 116, 105, 116, 121, 95, 116, 121, 112, 101, 34, 58, 32, 34, 100, 97, 116, 97, 95, 111, 98, 106, 101, 99, 116, 34, 44, 32, 34, 111, 112, 101, 114, 97, 116, 105, 111, 110, 115, 34, 58, 32, 91, 123, 34, 111, 112, 101, 114, 97, 116, 105, 111, 110, 34, 58, 32, 34, 97, 100, 100, 34, 44, 32, 34, 97, 116, 116, 114, 105, 98, 117, 116, 101, 34, 58, 32, 34, 97, 116, 114, 49, 34, 44, 32, 34, 118, 97, 108, 117, 101, 34, 58, 32, 34, 118, 97, 108, 49, 34, 125, 44, 32, 123, 34, 111, 112, 101, 114, 97, 116, 105, 111, 110, 34, 58, 32, 34, 97, 100, 100, 34, 44, 32, 34, 97, 116, 116, 114, 105, 98, 117, 116, 101, 34, 58, 32, 34, 97, 116, 114, 50, 34, 44, 32, 34, 118, 97, 108, 117, 101, 34, 58, 32, 34, 118, 97, 108, 50, 34, 125, 44, 32, 123, 34, 111, 112, 101, 114, 97, 116, 105, 111, 110, 34, 58, 32, 34, 97, 100, 100, 34, 44, 32, 34, 97, 116, 116, 114, 105, 98, 117, 116, 101, 34, 58, 32, 34, 97, 116, 114, 51, 34, 44, 32, 34, 118, 97, 108, 117, 101, 34, 58, 32, 34, 118, 97, 108, 51, 34, 125, 93, 125]
    
```

**Comment by d-w-moore** [comment]
@mstfdkmn Yes, exactly. You'd need to do something like this:
```
my_json_var = bytes(rule_args[2].get_bytes()).decode('utf8')
```
to get a string  that you can then deserialize using `json.loads(my_json_var)`.

**Comment by korydraughn** [comment]
I believe this issue can be closed now.

@mstfdkmn Do you agree?

**Comment by mstfdkmn** [comment]
As far as I have tested with irods4.3.0 which we run, yes. Thanks.

**Comment by korydraughn** [comment]
Great.
