### ISSUE TITLE
Removing collections without forcing throws `specificQuery status = -853000` in logs

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods#6900]
- [x] main (code change only)
- [x] 4-3-stable (code change only)
- [x] 4-2-stable (docs only)
---
### iRODS Version, OS and Version
4.2.11 centos7, 4.3.0 almalinux8

### What did you try to do?
I tried to remove a collection (no matter that collection has any content) without using `f` option by `irm r` and PRC. Meaning I tried to move it to my trash.

### Expected behavior
I expected that collection to be removed without any noise.

### Observed behavior (including steps to reproduce, if applicable)
I observed that collection is removed (moved to the trash collection) with info level logs outputs concerning with `specificQuery`.

client:
```
imkdir test
irm -r test
```
logs of 4.3.0:
```
irods stdout | {"log_category":"legacy","log_facility":"local0","log_level":"info","log_message":"_rsSpecificQuery: specificQuery status = -853000","request_api_name":"RM_COLL_AN","request_api_number":679,"request_api_version":"d","request_client_user":"rods","request_host":"10.0.2.100","request_proxy_user":"rods","request_release_version":"rods4.3.0","server_host":"dev-u0137480-instance1.irods.t.icts.kuleuven.be","server_pid":84121,"server_timestamp":"2023-02-10T09:57:23.821Z","server_type":"agent"}
irods stdout | {"log_category":"legacy","log_facility":"local0","log_level":"info","log_message":"rsSpecificQuery: rcSpecificQuery failed, status = -853000","request_api_name":"RM_COLL_AN","request_api_number":679,"request_api_version":"d","request_client_user":"rods","request_host":"10.0.2.100","request_proxy_user":"rods","request_release_version":"rods4.3.0","server_host":"dev-u0137480-instance1.irods.t.icts.kuleuven.be","server_pid":84121,"server_timestamp":"2023-02-10T09:57:23.821Z","server_type":"agent"}
irods stdout | {"log_category":"legacy","log_facility":"local0","log_level":"info","log_message":"Note: DataObjInCollReCur specific-Query failed (not defined?), running standard query, status=-853000","request_api_name":"RM_COLL_AN","request_api_number":679,"request_api_version":"d","request_client_user":"rods","request_host":"10.0.2.100","request_proxy_user":"rods","request_release_version":"rods4.3.0","server_host":"dev-u0137480-instance1.irods.t.icts.kuleuven.be","server_pid":84121,"server_timestamp":"2023-02-10T09:57:23.821Z","server_type":"agent"}
```

logs of 4.2.11:
```
rsyslogd stdout | 2023-02-10T10:39:18.558994+01:00 dev-u0137480 rodsServer[10946]: u0137480 - NOTICE: _rsSpecificQuery: specificQuery status = -853000
rsyslogd stdout | 2023-02-10T10:39:18.559092+01:00 dev-u0137480 rodsServer[10946]: u0137480 - NOTICE: rsSpecificQuery: rcSpecificQuery failed, status = -853000
rsyslogd stdout | 2023-02-10T10:39:18.559143+01:00 dev-u0137480 rodsServer[10946]: u0137480 - NOTICE: Note: DataObjInCollReCur specific-Query failed (not defined?), running standard query, status=-853000

```

What is the DataObjInCollReCur specific query? Should we add it? Does it hurt anything if we dont add?

**Comment by korydraughn** [comment]
That specific query has been around for a while. It was installed as part of schema upgrade 3. See https://github.com/irods/irods/blob/aea8436ad097e561222cba5f101fa5788d01e1fa/scripts/irods/database_upgrade.py#L24

For some reason, it was removed if the system was backed by MySQL. It's not clear why though. See https://github.com/irods/irods/blob/aea8436ad097e561222cba5f101fa5788d01e1fa/scripts/irods/database_upgrade.py#L31-L32

@trel Do you know why it was removed?

Given that you've switched to Almalinux, you'll can consider restoring it. If I had to guess, I'd say that specific query was used to identify ALL data objects under a collection.

You can try running that query in the database manually to see what it produces before restoring it in the system.

**Comment by trel** [comment]
The `WITH` statement (common table expression) was not supported by MySQL at that time.   https://github.com/irods/irods/issues/2483

https://github.com/irods/irods/commit/94228e46807c6ad9d273368a41f828b2dcfa6040

I believe we could revisit this now...
 - MySQL added support in MySQL 8 - https://dev.mysql.com/doc/refman/8.0/en/with.html
 - MariaDB added support in 10.2.1 - https://mariadb.com/kb/en/common-table-expressions/

**Comment by korydraughn** [comment]
According to https://endoflife.date/mysql, MySQL 5.7's EOL is 2023-10-21.

I see two paths forward:
- We add the specific query if the MySQL database is v8 or later
- Or, we declare that 4.3.1 (and 4.2.12) only support MySQL 8 moving forward

**Comment by trel** [comment]
And MySQL 8 was released 08 Apr 2018 (nearly 5y ago) - so I think option b) is fine (MySQL8 / MariaDB 10 are minimums).

And we add the SpecificQuery back in by default (and during any upgrade).

**Comment by korydraughn** [comment]
Seems you have a trailing parenthesis at the end of your query.

**Comment by mstfdkmn** [comment]
> Seems you have a trailing parenthesis at the end of your query.

I am still getting a syntax error. Could you help me to get to it please?

```
MySQL [irods]> WITH coll AS (   SELECT     coll_id,     coll_name   FROM     r_coll_main   WHERE     R_COLL_MAIN.coll_name = '/u0137480_instance1/home/rods/myCol'     OR R_COLL_MAIN.coll_name LIKE '/u0137480_instance1/home' ) SELECT   DISTINCT d.data_id,   (     SELECT       coll_name     FROM       coll     WHERE       coll.coll_id = d.coll_id   ) coll_name,   d.data_name,   d.data_repl_num,   d.resc_name,   d.data_path,   d.resc_hier FROM   R_DATA_MAIN d WHERE   d.coll_id = ANY(     ARRAY(       SELECT         coll_id       FROM         coll     )   ) ORDER BY   coll_name,   d.data_name,   d.data_repl_num,   '1388534400';
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ARRAY(       SELECT         coll_id       FROM         coll     )   ) ORDER BY  ' at line 1
```

`insert into R_SPECIFIC_QUERY (alias, sqlStr, create_ts) values ('DataObjInCollReCur', 'WITH coll AS (SELECT coll_id, coll_name FROM r_coll_main WHERE R_COLL_MAIN.coll_name = ? OR R_COLL_MAIN.coll_name LIKE ?) SELECT DISTINCT d.data_id, (SELECT coll_name FROM coll WHERE coll.coll_id = d.coll_id) coll_name, d.data_name, d.data_repl_num, d.resc_name, d.data_path, d.resc_hier FROM R_DATA_MAIN d WHERE d.coll_id = ANY(ARRAY(SELECT coll_id FROM coll)) ORDER BY coll_name, d.data_name, d.data_repl_num', '1388534400');`

**Comment by korydraughn** [comment]
Does MySQL support arrays?

You may need to remove the use of `ARRAY()` from the query.

What happens if you run the following:
```sql
insert into R_SPECIFIC_QUERY (alias, sqlStr, create_ts) values ('DataObjInCollReCur', 'WITH coll AS (SELECT coll_id, coll_name FROM r_coll_main WHERE R_COLL_MAIN.coll_name = ? OR R_COLL_MAIN.coll_name LIKE ?) SELECT DISTINCT d.data_id, (SELECT coll_name FROM coll WHERE coll.coll_id = d.coll_id) coll_name, d.data_name, d.data_repl_num, d.resc_name, d.data_path, d.resc_hier FROM R_DATA_MAIN d WHERE d.coll_id = ANY(SELECT coll_id FROM coll) ORDER BY coll_name, d.data_name, d.data_repl_num', '1388534400');
```

**Comment by mstfdkmn** [comment]
Thanks it works as expected.

**Comment by mstfdkmn** [comment]
The query suggested has some side effect. The problem is that if a collection contains data objects and if that collection is wanted to be removed not forcefully (without using -f option), then the collection and its objects are logically deleted but they stay physically in the storage. And it throws `SYS_RESC_DOES_NOT_EXIST` error.

```
[irods@dev-u0137480-instance1 irods]$ iput -r test_col
Running recursive pre-scan... pre-scan complete... transferring data...
[irods@dev-u0137480-instance1 irods]$ ils
/u0137480_instance1/home/rods:
  C- /u0137480_instance1/home/rods/test_col
[irods@dev-u0137480-instance1 irods]$ ls /vault/home/rods/test_col/
test.txt  test1.txt  test2.txt
[irods@dev-u0137480-instance1 irods]$ irm -r test_col
[irods@dev-u0137480-instance1 irods]$ ils
/u0137480_instance1/home/rods:
[irods@dev-u0137480-instance1 irods]$ ls /vault/home/rods/test_col/
test.txt  test1.txt  test2.txt
```
logs:
```
irods stdout | {"log_category":"legacy","log_facility":"local0","log_level":"error","log_message":"[-]\t/irods_source/server/core/src/physPath.cpp:863:int syncDataObjPhyPathS(rsComm_t *, dataObjInp_t *, dataObjInfo_t *, char *) :  status [SYS_RESC_DOES_NOT_EXIST]  errno [] -- message [failed to resolve resource [resource_property_create_path]]\n\t[-]\t/irods_source/server/core/include/irods/irods_resource_backport.hpp:46:irods::error irods::get_resource_property(rodsLong_t, const std::string &, T &) [T = int] :  status [SYS_RESC_DOES_NOT_EXIST]  errno [] -- message [failed to resolve resource [resource_property_create_path]]\n\t\t[-]\t/irods_source/server/core/src/irods_resource_manager.cpp:102:irods::error irods::resource_manager::resolve(rodsLong_t, irods::resource_ptr &) :  status [SYS_RESC_DOES_NOT_EXIST]  errno [] -- message [no resource found for name [0]]\n\n","request_api_name":"RM_COLL_AN","request_api_number":679,"request_api_version":"d","request_client_user":"rods","request_host":"10.0.2.100","request_proxy_user":"rods","request_release_version":"rods4.3.0","server_host":"dev-u0137480-instance1.irods.t.icts.kuleuven.be","server_pid":185080,"server_timestamp":"2023-02-15T09:50:05.743Z","server_type":"agent"}
irods stdout | {"log_category":"legacy","log_facility":"local0","log_level":"error","log_message":"[-]\t/irods_source/server/core/src/physPath.cpp:863:int syncDataObjPhyPathS(rsComm_t *, dataObjInp_t *, dataObjInfo_t *, char *) :  status [SYS_RESC_DOES_NOT_EXIST]  errno [] -- message [failed to resolve resource [resource_property_create_path]]\n\t[-]\t/irods_source/server/core/include/irods/irods_resource_backport.hpp:46:irods::error irods::get_resource_property(rodsLong_t, const std::string &, T &) [T = int] :  status [SYS_RESC_DOES_NOT_EXIST]  errno [] -- message [failed to resolve resource [resource_property_create_path]]\n\t\t[-]\t/irods_source/server/core/src/irods_resource_manager.cpp:102:irods::error irods::resource_manager::resolve(rodsLong_t, irods::resource_ptr &) :  status [SYS_RESC_DOES_NOT_EXIST]  errno [] -- message [no resource found for name [0]]\n\n","request_api_name":"RM_COLL_AN","request_api_number":679,"request_api_version":"d","request_client_user":"rods","request_host":"10.0.2.100","request_proxy_user":"rods","request_release_version":"rods4.3.0","server_host":"dev-u0137480-instance1.irods.t.icts.kuleuven.be","server_pid":185080,"server_timestamp":"2023-02-15T09:50:05.743Z","server_type":"agent"}
irods stdout | {"log_category":"legacy","log_facility":"local0","log_level":"error","log_message":"[-]\t/irods_source/server/core/src/physPath.cpp:863:int syncDataObjPhyPathS(rsComm_t *, dataObjInp_t *, dataObjInfo_t *, char *) :  status [SYS_RESC_DOES_NOT_EXIST]  errno [] -- message [failed to resolve resource [resource_property_create_path]]\n\t[-]\t/irods_source/server/core/include/irods/irods_resource_backport.hpp:46:irods::error irods::get_resource_property(rodsLong_t, const std::string &, T &) [T = int] :  status [SYS_RESC_DOES_NOT_EXIST]  errno [] -- message [failed to resolve resource [resource_property_create_path]]\n\t\t[-]\t/irods_source/server/core/src/irods_resource_manager.cpp:102:irods::error irods::resource_manager::resolve(rodsLong_t, irods::resource_ptr &) :  status [SYS_RESC_DOES_NOT_EXIST]  errno [] -- message [no resource found for name [0]]\n\n","request_api_name":"RM_COLL_AN","request_api_number":679,"request_api_version":"d","request_client_user":"rods","request_host":"10.0.2.100","request_proxy_user":"rods","request_release_version":"rods4.3.0","server_host":"dev-u0137480-instance1.irods.t.icts.kuleuven.be","server_pid":185080,"server_timestamp":"2023-02-15T09:50:05.743Z","server_type":"agent"}
```

We tried the improved query below but we still get the same `SYS_RESC_DOES_NOT_EXIST ` error.

`insert into R_SPECIFIC_QUERY (alias, sqlStr, create_ts) values ('DataObjInCollReCur', 'SELECT DISTINCT d.data_id, c.coll_name, d.data_name, d.data_repl_num, d.resc_name, d.data_path, d.resc_hier FROM R_DATA_MAIN d INNER JOIN R_COLL_MAIN c ON d.coll_id = c.coll_id AND (c.coll_name = ? OR c.coll_name LIKE ?) ORDER BY coll_name, d.data_name, d.data_repl_num', '1388534400');`

Could you l tell us what else we can do?

**Comment by korydraughn** [comment]
Do you see the test.txt data objects in the catalog anywhere? Perhaps in a trash collection?

The error message you're seeing feels like a real bug. We'll see if other databases result in the same error and let you know what we find.

**Comment by mstfdkmn** [comment]
No, I don't see it anywhere. I tested it again after I deleted everything but I got the same error.

```
[irods@dev-u0137480-instance1 irods]$ ils /u0137480_instance1/trash/home/rods
/u0137480_instance1/trash/home/rods:
```
```
MySQL [irods]> SELECT * FROM R_DATA_MAIN;
Empty set (0.001 sec)

```

**Comment by korydraughn** [comment]
I tried running `irm -r` on an empty collection and a non-empty collection against a PostgreSQL-backed iRODS 4.3.0 server and the log was quiet. The collection and data objects appeared in the trash collection as expected.

I'll try reproducing this with MySQL 8 and let you know what I find.

**Comment by korydraughn** [comment]
I was able to reproduce the `SYS_RESC_DOES_NOT_EXIST` error using Almalinux 8.

PostgreSQL doesn't produce this error.

The error message stems from the following:
https://github.com/irods/irods/blob/f6eb6c72786288878706e2562a370b91b7d0802e/server/core/src/physPath.cpp#L858-L864

Which indicates that `dataObjInfo->rescId` is potentially zero in the Almalinux deployment.

https://github.com/irods/irods/blob/f6eb6c72786288878706e2562a370b91b7d0802e/server/core/include/irods/irods_resource_backport.hpp#L35-L47
https://github.com/irods/irods/blob/dfaaba690f00e128b98a9a9a0cfa49305686ee9a/server/core/src/irods_resource_manager.cpp#L90-L106

So, the actual issue seems to be due to the resource id not being resolvable to a resource object.

> What is the DataObjInCollReCur specific query?

I'm pretty sure this specific query exists for performance reasons (i.e. GenQuery isn't fast enough).

Overall, the error message doesn't appear to be an issue, but we'll investigate and report our findings.

**Comment by korydraughn** [comment]
I've confirmed that the resource ID passed for resolution is non-zero 4.3/Ub20/PostgreSQL, but zero for 4.3/Alma8/MySQL8.

I'm not sure why that is. One difference in my testing is that I'm running the Ub20 deployment on my host OS and I'm running the Alma8 deployment in docker containers. I don't expect that to be an issue though.

I'll continue to investigate.

**Comment by korydraughn** [comment]
The resource ID being zero appears to be specific to MySQL. 4.3/Alma8/PostgreSQL works as expected and the log remains quiet.

My guess is that the resource manager is either clearing the ID or it is failing to retrieve the ID from the catalog on agent start.

**Comment by korydraughn** [comment]
Turns out the query was slightly incorrect. The reason why we are seeing `SYS_RESC_DOES_NOT_EXIST` is because the specific query is returning the resource hierarchy string instead of the resource ID.

Change the specific query to the following and the error messages should go away.
```bash
WITH coll AS (SELECT coll_id, coll_name FROM R_COLL_MAIN WHERE R_COLL_MAIN.coll_name = ? OR R_COLL_MAIN.coll_name LIKE ?) SELECT DISTINCT d.data_id, (SELECT coll_name FROM coll WHERE coll.coll_id = d.coll_id) coll_name, d.data_name, d.data_repl_num, d.resc_name, d.data_path, d.resc_id FROM R_DATA_MAIN d WHERE d.coll_id = ANY(SELECT coll_id FROM coll) ORDER BY coll_name, d.data_name, d.data_repl_num
```

**Comment by korydraughn** [comment]
Then again, this is more of a documentation exercise. The system isn't broken, it's just missing a specific query.

**Comment by mstfdkmn** [comment]
Many thanks for clarifying this. Everything with the suggested query seems to work normal now.

**Comment by korydraughn** [comment]
Excellent!

**Comment by korydraughn** [comment]
@trel Do document/list the specific queries that should exist in a deployment anywhere? Perhaps in docs.irods.org?

I don't think we do.

**Comment by trel** [comment]
The answer is a combination of...

The initial install (db schema version 1):

https://github.com/irods/irods/blob/a23bec30efa5d7a75bc421875a416a9097b311f3/plugins/database/src/icatSysInserts.sql#L188-L190

Plus anything added during 'upgrade' (now at db schema version 9):
(search for R_SPECIFIC_QUERY)

https://github.com/irods/irods/blob/main/scripts/irods/database_upgrade.py

**Comment by korydraughn** [comment]
The plan is:
- For 4.2.12, add documentation to the troubleshooting section
- For 4.3.1, the upgrade script will add the specific query if the alias, `DataObjInCollReCur`, doesn't exist
  - This will require a bump to the database schema version
  - We need to make sure the database schema versions between 4.2 and 4.3 align

**Comment by korydraughn** [comment]
Changing milestone to 4.3.1 so that 4.2.12 isn't blocked by documentation work.

**Comment by korydraughn** [comment]
Changing milestone back to 4.2.12 since the work for 4.2 and 4.3 is in a PR.
