### ISSUE TITLE
A policy option for group admins not to manage all existing groups

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods#6902]
## Feature

- Please describe the feature you are requesting and your use case.

We have been following the discussions/developments (irods/PRC) about the group admin roles. We wanted to request this earlier but since we decided to implement our own solution this request postponed. Therefore Looking at the recent discussions we would like to add the following:

In most of our use cases we dont want `groupadmins` should be able to manage groups that are not member of. A groupdmin should be able to only manage (add/remove/list users, promote users to up to his level etc.) his/her own group. As known currently any groupadmin can intervene other groups  in addition to his/her own ones (membership).

I guess this policy should exists for many use cases and it has its own logic too. But for alternative needs may we request an option in the core policy so that admin can select/activate which ever suits.

**Comment by trel** [comment]
- A `groupadmin` can administer any group of which it is a member.
- A `groupadmin` cannot administer other groups.
- A `groupadmin` can only add themselves to a group with no members.

I think this current default behavior aligns with your request(s) in this issue.

**Comment by mstfdkmn** [comment]
Sorry, that is correct. I updated myself...What we need is that a user can be groupadmin of a group but at the same time in the same zone that user could be a regular user (rodsuser right) of another group.

And in my opinion this cannot be something iRODS should handle. So you can please close this as invalid. Thanks.

**Comment by trel** [comment]
Understood.  Yes, for that scenario to work, iRODS would need to keep the annotation of the 'manager(s)' of a group *on* the group, rather than what we have now, which is an annotation/distinction on the user.  That would be a big change and very surprising to existing deployments.
