### ISSUE TITLE
`imv` for collections should not trigger `pep_api_data_obj_rename_*`

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods#6914]
### iRODS Version, OS and Version
4.2.11 centos7, 4.3.0 almalinux8

### What did you try to do?
I tried to move a collection into another collection (also I tried to rename a collection) to trigger a right PEP to get right data.

### Expected behavior
After moving a collection is ensured, I didnt expect to see `pep_api_data_obj_rename_*` is triggered, rather I expected to see either `pep_api_coll_rename_*`  which doesnt exist or `pep_database_rename_coll_*` which has not been triggered.

### Observed behavior (including steps to reproduce, if applicable)

`pep_api_data_obj_rename_*` which is triggered doesnt provide needed data (collection path etc.) and throws specificQuery errors in logs.

client:
```
[irods@dev-u0137480-instance1 irods]$ ils
/u0137480_instance1/home/rods:
C- /u0137480_instance1/home/rods/test
[irods@dev-u0137480-instance1 irods]$ imv test test1`
```

core.py:
```
def pep_api_data_obj_rename_post(rule_args, callback, rei):
    print("pep_api_data_obj_rename_post")
    print(str(rule_args[2].destDataObjInp.objPath))
    print(str(rule_args[2].srcDataObjInp.objPath))
```

logs:
```
irods stdout | {"log_category":"legacy","log_facility":"local0","log_level":"info","log_message":"_rsSpecificQuery: specificQuery status = -853000","request_api_name":"DATA_OBJ_RENAME_AN","request_api_number":627,"request_api_version":"d","request_client_user":"rods","request_host":"10.0.2.100","request_proxy_user":"rods","request_release_version":"rods4.3.0","server_host":"dev-u0137480-instance1.irods.t.icts.kuleuven.be","server_pid":191815,"server_timestamp":"2023-02-15T17:03:07.838Z","server_type":"agent"}
irods stdout | {"log_category":"legacy","log_facility":"local0","log_level":"info","log_message":"rsSpecificQuery: rcSpecificQuery failed, status = -853000","request_api_name":"DATA_OBJ_RENAME_AN","request_api_number":627,"request_api_version":"d","request_client_user":"rods","request_host":"10.0.2.100","request_proxy_user":"rods","request_release_version":"rods4.3.0","server_host":"dev-u0137480-instance1.irods.t.icts.kuleuven.be","server_pid":191815,"server_timestamp":"2023-02-15T17:03:07.838Z","server_type":"agent"}
irods stdout | {"log_category":"legacy","log_facility":"local0","log_level":"info","log_message":"Note: DataObjInCollReCur specific-Query failed (not defined?), running standard query, status=-853000","request_api_name":"DATA_OBJ_RENAME_AN","request_api_number":627,"request_api_version":"d","request_client_user":"rods","request_host":"10.0.2.100","request_proxy_user":"rods","request_release_version":"rods4.3.0","server_host":"dev-u0137480-instance1.irods.t.icts.kuleuven.be","server_pid":191815,"server_timestamp":"2023-02-15T17:03:07.838Z","server_type":"agent"}
irods stdout | pep_api_data_obj_rename_post
irods stdout | /u0137480_instance1/home/rods/test1
irods stdout | /u0137480_instance1/home/rods/test
```

Also, I dont see any API pep for renaming collections [here](https://docs.irods.org/4.3.0/plugins/dynamic_policy_enforcement_points/) and I observed that the database related PEPs for renaming have not been triggered.

**Comment by korydraughn** [comment]
Based on the following code, the reason you see `pep_api_data_obj_rename_*` is because renaming/moving collections and data objects is performed by `rcDataObjRename()`.
https://github.com/irods/irods/blob/f6eb6c72786288878706e2562a370b91b7d0802e/lib/core/src/mvUtil.cpp#L60-L84

As for the database PEP, try looking for `pep_database_rename_object_*`.

The API name isn't great, but the results are expected.

You have to lookup the object type for each logical path to determine whether you're dealing with data objects and/or collections.

> doesnt provide needed data (collection path etc ...

You have the absolute for each object. Is that not what you're looking for?

If you need the parent path of a logical path, you can use [msiSplitPath](https://docs.irods.org/4.3.0/doxygen/msiHelper_8cpp.html#a5de988327f1dfe917bcc0bfbac1087ec).

**Comment by mstfdkmn** [comment]
> If you need the parent path of a logical path, you can use [msiSplitPath](https://docs.irods.org/4.3.0/doxygen/msiHelper_8cpp.html#a5de988327f1dfe917bcc0bfbac1087ec).

I guess this msi is not recommended to be used with the PREP because I see only a pythonic approach in the rule example [here](https://github.com/irods/irods_rule_engine_plugin_python/blob/main/python_rules/rulemsiSplitPath.r).

But okay, I think we have our solution similar to what you described.

```
def pep_api_data_obj_rename_pre(rule_args, callback, rei):

    global obj_id
    obj_id = get_id(callback, str(rule_args[2].srcDataObjInp.objPath))
    print("pep_api_data_obj_rename_pre")

def pep_api_data_obj_rename_post(rule_args, callback, rei):

    source_path = str(rule_args[2].srcDataObjInp.objPath)
    destination_path = str(rule_args[2].destDataObjInp.objPath)
    if coll_exists(callback, destination_path):
        delete_doc_for_col(source_path, obj_id, callback, rei)
        get_doc_for_coll(destination_path, callback, rei) 
    else:
        delete_doc_data_obj(rule_args, callback, rei, data_id, source_path)
        get_doc_for_data_object(rule_args, callback, rei, destination_path)
    print("pep_api_data_obj_rename_post")

def coll_exists(callback, path):
    return len(list(row_iterator(
               "COLL_ID", f"COLL_NAME = '{path}'",
               AS_LIST, callback))) > 0
```

**Comment by korydraughn** [comment]
Very good. Closing as resolved.
