### ISSUE TITLE
msiAddKeyValToMspStr appending ++++ to blank strings causing -315000 error.

### ISSUE THREAD

**Issue by Urvika-gola** [irods/irods#6918]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---
## Bug Report

**Details:** 

Creating a key value pair of `irodsAdminRmTrash` to be used in `msiRmColl` microservice.

1. The `*Flag` controlling options in the form `keyword=value` is set to empty string (In our use case: It's being done to reuse the variable name and flush its content before use due to nested structure)
  `*Flag = "";`
2. If this `*Flag` is used as the msKeyValStr argument in `msiAddKeyValToMspStr`, the result appends '`++++`' to the beginning of the the `*Flag`.
  `msiAddKeyValToMspStr("irodsAdminRmTrash", "", *Flag);`  
3. iRODS should detect if `msKeyValStr` is an empty string and should not append '`++++`' to an empty string, that causes wrong format of the flag.
Instead of `++++irodsAdminRmTrash=`, it should have `irodsAdminRmTrash=`

### iRODS Version, OS and Version
iRODS Version - 4.2.8
OS and Version - CentOS Linux release 7.9.2009 (Core)

### What did you try to do?
1. Flush the contents of the string `msKeyValStr` argument i.e. `*Flag`.
2. Add the `irodsAdminRmTrash` key value pair using 'msiAddKeyValToMspStr'.
3. Use this key value pair in `msiRmColl`.
```
  *Flag = "";
  msiAddKeyValToMspStr("irodsAdminRmTrash", "", *Flag);
  msiRmColl("*Coll, *Flag, *Status);
```

### Expected behavior
The admin should be able to remove the collection at `*Coll`. 

### Observed behavior (including steps to reproduce, if applicable)
The admin is unable to remove the collection as a result of the following observed behavior:
`DEBUG: msiRmColl: input keyWd -  error. status = -315000`
That is `USER_BAD_KEYWORD_ERR`.

**Comment by trel** [comment]
Thank you - this code has probably always had this bug.

https://github.com/irods/irods/blame/4.3.0/lib/core/src/msParam.cpp#L1451

**Comment by alanking** [comment]
Is it possible to avoid the `*Flag = "";` line? In other words, does just calling these lines work?
```python
msiAddKeyValToMspStr("irodsAdminRmTrash", "", *Flag);
msiRmColl("*Coll, *Flag, *Status);
```

Or, what happens if you give it a dummy value, e.g. `*Flag = "dummy=";`?

Trying to see if a workaround exists, for now.

**Comment by korydraughn** [comment]
Is the leading double quote supposed to be on the first argument?

Saw that in the original post too.

**Comment by trel** [comment]
@korydraughn you mean in the `msiRmColl` line?   Yes, that leading double quote seems... extra/incorrect.

**Comment by korydraughn** [comment]
I tried the workarounds presented by @alanking on 4.2.8/Cen7/Postgres and they resolved the issue with the key value pairs. However, `msiRmColl()` continues to fail.

I'm going to try this on a 4.2.11 and 4.3.0 server and see if the issue exists there.

**Comment by korydraughn** [comment]
The issue still exists in 4.3.0.

**Comment by Urvika-gola** [comment]
> Is it possible to avoid the `*Flag = "";` line? In other words, does just calling these lines work?
> 
> ```python
> msiAddKeyValToMspStr("irodsAdminRmTrash", "", *Flag);
> msiRmColl("*Coll, *Flag, *Status);
> ```
> 
> Or, what happens if you give it a dummy value, e.g. `*Flag = "dummy=";`?
> 
> Trying to see if a workaround exists, for now.

The point 1 in Details section briefly point out why am I using `*Flag = "";`

**Comment by korydraughn** [comment]
Are you saying those lines allowed you to remove the collection?

**Comment by Urvika-gola** [comment]
> Are you saying those lines allowed you to remove the collection?

No, I meant that my workaround would be to avoid using `*Flag = "";`.
I was using `*Flag = "";` due to a nested structure of the code as highlighted in point 1 of details section.

Instead, now I use different variable names for different code flows rather than resetting it to empty string and reusing the same variable.

**Comment by korydraughn** [comment]
@MartinFlores751 Please close if complete.
