### ISSUE TITLE
When requesting a replica from a stale archive, we are getting the good cache version.

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods#6926]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---

### iRODS Version, OS and Version

Tested on 4.2.11 with Ubuntu 18.

### Description

When requesting a replica from a stale archive, we are getting the good cache version.

We can't get the stale archive as the only way to get it would be to repave the good cache file.  In this case we should get an error.

There is some overlap between this and issue #6896 but I think this is a unique subset of that which needs tested.  Specifically, we need to verify with the fix for #6896 that the good cache replica is not repaved which would be really bad.

### Test Setup

```
$ iput -R comp_resc smallerfile test.txt
$ iadmin modresc comp_resc context "auto_repl=off"
$ iput -R comp_resc largerfile test.txt
$ ils -l
/tempZone/home/rods:
  rods              0 comp_resc;s3_cache_resc           30 2023-02-21.20:18 & test.txt
  rods              1 comp_resc;s3_archive_resc           15 2023-02-21.20:17 X test.txt
  C- /tempZone/home/rods/dir1  
```

### Observed Behavior

```
$ iget -n 1 test.txt - 
this is a test.  updated file
```

### Expected Behavior

In this case since we asked for the archive but we can't get the archive without repaving the good cache file, we should get an error.

**Comment by JustinKyleJames** [comment]
We have decided that asking for a specific replica from either cache or archive should always give an error.  You can't specify a replica that is under a compound resource.

**Comment by alanking** [comment]
@JustinKyleJames - Please close if complete.

**Comment by JustinKyleJames** [comment]
Closing
