### ISSUE TITLE
Update mock archive to use irv::calculate()

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods#6947]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---

Update mock archive to use irv::calculate().  Also allow WRITE_OPERATION in resolve hierarchy.

There are two reasons for this.

1. Existing resources have been updated to use this routine so this brings the mock archive in line with other resources.
2. The disabling of the resolve_hierarchy for write is causing test to fail.  It is wrong to reject voting on a write even if archive resources can't be written to directly.

**Comment by alanking** [comment]
@JustinKyleJames - Please close if complete.

**Comment by JustinKyleJames** [comment]
Closing
