### ISSUE TITLE
clang-tidy: demote cert-err58-cpp to warning

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#6971]
- [x] main
- [x] 4-3-stable
---
With our current `clang-tidy` configuration, static `const std::string`s are always flagged as errors due to `cert-err58-cpp`.
We cannot replace every instance of a static `const std::string` definition with `const std::string_view`, so this becomes rather obnoxious.
Let's demote `cert-err58-cpp` to a warning to make this easier to deal with.

**Comment by korydraughn** [comment]
Related to #6527.
