### ISSUE TITLE
TLS issue in c# client 

### ISSUE THREAD

**Issue by ThomasOverbergh** [irods/irods#6988]
*Not in the right place, but hoping someone could help out.*

I am trying to get the C# irods-client running. (https://github.com/UtrechtUniversity/irods-Csharp  **BRANCH(!!)**:  [request_server_negotiation](https://github.com/UtrechtUniversity/irods-Csharp/tree/request_server_negotiation))

#
With the python client using openSSL I can connect. 
Using the same settings in the C# client, the connection stops at the TLS client hello. 
I don’t get a server response hello...

(Running on Windows 11 operating system that supports by TLS1.3)

**Comment by alanking** [comment]
The iRODS Consortium does not maintain the C# client and it does not appear that there is anything to do for this repository regarding your question.

I've left a comment with some questions to consider here: https://github.com/UtrechtUniversity/irods-Csharp/issues/1#issuecomment-1479985023 Let's continue the conversation there!
