### ISSUE TITLE
Compound Resource - Use replica status when deciding whether to stage to archive

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods#7002]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---
The voting from the children is not a good way to determine whether a file needs to be staged from archive to cache.  Instead use the replica status.

**Comment by alanking** [comment]
@JustinKyleJames - This is directly related to/in service of #6502 and #6926, right?

**Comment by alanking** [comment]
@JustinKyleJames - Please close if complete.

**Comment by JustinKyleJames** [comment]
closing
