### ISSUE TITLE
Automated irods installation not deterministic provider and consumer irods roles

### ISSUE THREAD

**Issue by fj-morales** [irods/irods#7023]
- [x] main
- [x] 4-3-stable
------

Hi, 

I've been testing an irods resource server 4.3.0 installation and I've come accross the issue that the consumer and provider roles that can be picked up are not always given in the same order, for example when running:

`python3 /var/lib/irods/scripts/setup_irods.py -v`

The output can be:

The iRODS service account name needs to be defined.
iRODS user [irods]: 
iRODS group [irods]: 

+--------------------------------+
| Setting up the service account |
+--------------------------------+

Existing Group Detected: irods
Existing Account Detected: irods
Setting owner of /var/lib/irods to irods:irods
Setting owner of /etc/irods to irods:irods
rsyslog already configured.
logrotate already configured.
iRODS server's role:
**1. consumer
2. provider**

or 

**1. provider
2. consumer**

This is an inconvenient when automating the installation since it requires to know in advance what is the order of the options. For example using:

`python3 /var/lib/irods/scripts/setup_irods.py -v < /tmp/setup_irods_input`

The offending line seems to be the following, where the options are put in a python set, that when read, can output the elements in any order.
https://github.com/irods/irods/blob/95dac9a16094d33f4a534572e223440370045b76/scripts/setup_irods.py#L201

Thanks for your attention to this ticket.

**Comment by alanking** [comment]
@trel - Please close if complete. Thanks
