### ISSUE TITLE
`msiSetKeyValuePairsToObj` can crash agents

### ISSUE THREAD

**Issue by alanking** [irods/irods#7027]
- [x] main
- [x] 4-3-stable

I was writing a test for the changes in #7012 wherein a rule was being invoked that uses `msiSetKeyValuePairsToObj`. I observed agents crashing while trying to get the rule to work. Agents should never crash, no matter how bad someone is at writing rules.

I don't know what I did to make the agent crash, but please investigate the microservice for potential bugs. There are several C-style casts and no pointer checking, so that might be a good place to start.

**Comment by korydraughn** [comment]
@FifthPotato Please close if completed.
