### ISSUE TITLE
Split `lib.get_resource_parent` into `get_resource_parent_name` and `get_resource_parent_id`

### ISSUE THREAD

**Issue by alanking** [irods/irods#7029]
- [x] main
- [x] 4-3-stable
---
See https://github.com/irods/irods/pull/6923#discussion_r1160188748

**Comment by korydraughn** [comment]
@Nishant2022 Please close if complete.

**Comment by Nishant2022** [comment]
I am unable to close issues.

**Comment by alanking** [comment]
@Nishant2022 - How about now?
