### ISSUE TITLE
`clientLogin` family of functions must not print messages to stdout / stderr

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#7048]
- [x] main
- [x] 4-3-stable
---
## Refactor
The `clientLogin` family of functions use the following to print errors to the terminal. This isn't good for client applications running as servers (e.g. the C++ REST API). For client applications which produce structured log messages, this is bad because the messages produced by these functions can break log file parsers.
https://github.com/irods/irods/blob/25d8f67df6c123ee6f0b3fe4695e4042b52cdb59/lib/core/src/clientLogin.cpp#L134-L155
https://github.com/irods/irods/blob/25d8f67df6c123ee6f0b3fe4695e4042b52cdb59/lib/core/src/clientLogin.cpp#L515

These functions must never write to the terminal. Instead, they should simply return the error as an integer value.

**Comment by Nishant2022** [comment]
Should they log instead?

**Comment by korydraughn** [comment]
These may not be able to log anything without linking to the logging libraries and we really don't want that.

Let's simply return the error and not print anything to the terminal.
