### ISSUE TITLE
Metadata harvesting rule breaks iRODS server due to Python import errors.

### ISSUE THREAD

**Issue by ndusek** [irods/irods#7056]
Hello,

I am working through the most recent [iRODS beginner training](https://github.com/irods/irods_training/blob/main/beginner/irods_beginner_training_2022.pdf) on Ubuntu 20.04. Everything works great until I get to the example in Chapter 8 on Workflow Automation.

After adding these lines in the appropriate place in `/etc/irods/server_config.json`:

```
	    {
                "instance_name": "irods_rule_engine_plugin-python-instance",
                "plugin_name": "irods_rule_engine_plugin-python",
                "plugin_specific_configuration": {}
            },
```

And after placing the [core.py](https://raw.githubusercontent.com/irods/irods_training/ugm2022/beginner/core.py) and [training.re](https://raw.githubusercontent.com/irods/irods_training/ugm2022/beginner/training.re) scripts in `/etc/irods`, running the following command returns an error saying iRODS is down:

```
iput stickers.jpg
```

```
remote addresses: 127.0.0.1 ERROR: connectToRhost: error returned from host localhost status = -38000 SYS_AGENT_INIT_ERR
 ERROR: _rcConnect: connectToRhost error, server on localhost:1247 is probably down status = -38000 SYS_AGENT_INIT_ERR
```

(I know you're not supposed to use `localhost` in the config, but I'm doing this all on one VM, and all the other examples worked fine this way.)

When I look in `/var/log/irods/irods.log`, I see the following Python error (reformatted from the JSON for readability):

```
caught python exception: Traceback (most recent call last):
  File "/usr/lib/python3.8/decimal.py", line 3, in <module>
    from _decimal import *
ImportError: /usr/lib/python3.8/lib-dynload/_decimal.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyFloat_Type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/etc/irods/core.py", line 3, in <module>
    import exifread
  File "/usr/lib/python3/dist-packages/exifread/__init__.py", line 6, in <module>
    from .classes import *
  File "/usr/lib/python3/dist-packages/exifread/classes.py", line 5, in <module>
    from .utils import Ratio
  File "/usr/lib/python3/dist-packages/exifread/utils.py", line 5, in <module>
    from fractions import Fraction
  File "/usr/lib/python3.8/fractions.py", line 6, in <module>
    from decimal import Decimal
  File "/usr/lib/python3.8/decimal.py", line 8, in <module>
    from _pydecimal import *
  File "/usr/lib/python3.8/_pydecimal.py", line 440, in <module>
    import contextvars
  File "/usr/lib/python3.8/contextvars.py", line 1, in <module>
    from _contextvars import Context, ContextVar, Token, copy_context
ImportError: /usr/lib/python3.8/lib-dynload/_contextvars.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyContextVar_Type
```

From this, I deduce that the `/etc/irods/server_config.json` is correct and that when I try to `iput stickers.jpg` the `core.py` rule is being called as expected. But something with the python library chain is hosed up on Ubuntu 20.04.

To be fair, this doesn't look like a problem with iRODS. On the other hand though, I am following the standard tutorial and Ubuntu 20.04 is a supported version (based on the iRODS apt repo listing) so everything should work as expected.

Is there another python dependency that I'm missing that should have been installed when I installed `python3-exif`? Any other ideas?

**Comment by trel** [comment]
close https://github.com/irods/irods_rule_engine_plugin_python/issues/136 before closing this issue.
