### ISSUE TITLE
clang-tidy: demote cppcoreguidelines-pro-bounds-array-to-pointer-decay to warning

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7058]
- [x] main
- [x] 4-3-stable
---
Related: #6972

With our current `clang-tidy` configuration, any time a `type[]` is implicitly cast to a `type*`, it is flagged as an error due to `cppcoreguidelines-pro-bounds-array-to-pointer-decay`. While I do think this check is useful, I believe that, in the case of `char[]` to `char*`, it is obnoxious. Let's demote it to a warning.

**Comment by korydraughn** [comment]
Related to #6527.
