### ISSUE TITLE
clang-tidy: demote readability-function-cognitive-complexity to warning

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7060]
- [x] main
- [x] 4-3-stable
---
With our current `clang-tidy` configuration, any function that `clang-tidy` deems to be too complex is flagged as an error due to `readability-function-cognitive-complexity`. I think it's a useful check, but complex problems often require complex solutions, and we have a lot of complex problems to solve in the iRODS project. Let's demote this check to a warning to make it less obnoxious.

**Comment by korydraughn** [comment]
Related to #6527.
