### ISSUE TITLE
itree tests for #6627 fail, error message differs from what is expected

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7064]
While running tests for #7005, I ran into (probably) unrelated test failures in both of the tests for #6627 in `test_itree.Test_ITree`.

On lines 111 and 121, `itree` is run on a data object and a nonexistent path, respectively, expecting `does not refer to a collection` to appear in stderr:
https://github.com/irods/irods/blob/25d8f67df6c123ee6f0b3fe4695e4042b52cdb59/scripts/irods/test/test_itree.py#L111-L112
https://github.com/irods/irods/blob/25d8f67df6c123ee6f0b3fe4695e4042b52cdb59/scripts/irods/test/test_itree.py#L121-L122
However, the error messages are `Error:could not open collection for reading: CAT_UNKNOWN_COLLECTION` and `Error:could not open collection for reading: USER_FILE_DOES_NOT_EXIST`, respectively.

**Comment by korydraughn** [comment]
This is probably safe to close due to the fact that recent PRs have passed all unit/core tests.

As of 1ee08cd, there are no known issues with the itree tests.

@SwooshyCueb Any thoughts?

**Comment by SwooshyCueb** [comment]
Yeah this one hasn't come up again. Let's close it
