### ISSUE TITLE
`iticket` does not support relative paths containing `./` and/or `../`

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#7103]
- [x] main
- [x] 4-3-stable
---
## Bug Report
`iticket` returns a ticket string and an error when given a relative path containing `./` and/or `../`.
```bash
$ iticket create read .
ticket:foRaIwOGSNHaAXK                                                                         
remote addresses: [IP REDACTED] ERROR: rcTicketAdmin failed with error -814000 CAT_UNKNOWN_COLLECTION
```

Attempting to list the ticket information produces no output.
```bash
$ iticket ls foRaIwOGSNHaAXK
$ 
```

**Comment by alanking** [comment]
@Nishant2022 - Please close if complete. Thanks!
