### ISSUE TITLE
irodsDelayServer did not start

### ISSUE THREAD

**Issue by peggy0135** [irods/irods#7106]
Hi @trel , 
 Recently I tried to set up the irods in my enviroment. But I am facing some trouble.

## Bug Report
Beacuse I need to use storage tiering with my customized rule, so I really need the irodsDelayServer. 

iRODS Version: iRODS 4.3.0
 OS Version: I tried with rocky 8.4 and 8.8
 postgresql: I tried with 9.6, 10, 11, 13

What did you try to do?
when I tried to set up with "python3 /var/lib/irods/scripts/setup_irods.py"
I saw "Error encountered in graceful shutdown." during the validation.
Then I switch to user irods and start "./irodsctl start", and check status.
I got the result below every time I tried:
   [irods@localhost ~]$ ./irodsctl start
   [irods@localhost ~]$ ./irodsctl status
   irodsServer :
     Process 23420
     Process 23421
   [irods@localhost ~]$

Is there anything went wrong or something I missed??
Thank you.

**Comment by peggy0135** [comment]
> Q. Is there anything in the log file? Q. Is the delay server set to the correct machine? (i.e. `iadmin get_delay_server_info`) Q. What inputs did you pass to setup? _Please mask sensitive data before posting._ Q. Is there anything special about the environment you're running iRODS in?

1. 
   in setup_log.txt:
       ERROR -                  controller.py: 229 - Error encountered in graceful shutdown.
       irods.exceptions.IrodsError: The iRODS server did not stop within 20 seconds of receiving SIGTERM.
   in control_log.txt:
       2023-05-31T07:32:05.897Z -   ERROR -                  controller.py: 229 - Error encountered in graceful     shutdown.
       irods.exceptions.IrodsError: The iRODS server did not stop within 20 seconds of receiving SIGTERM.
       2023-05-31T07:38:48.953Z -   ERROR -               irods_control.py: 127 - Error encountered running irods_control start:
pyodbc.OperationalError: ('08001', '[08001] could not connect to server: Connection refused\n\tIs the server running on host "localhost" (::1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to server: Connection refused\n\tIs the server running on host "localhost" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\n (101) (SQLDriverConnect)')
       six.reraise(IrodsError, e, sys.exc_info()[2])
irods.exceptions.IrodsError: pyodbc encountered an error connecting to the database:
       2023-06-01T01:05:33.946Z -   ERROR -                  controller.py: 229 - Error encountered in graceful shutdown.
irods.exceptions.IrodsError: The iRODS server did not stop within 20 seconds of receiving SIGTERM.
2. iadmin get_delay_server_info:
        {
            "leader": "localhost",
            "successor": ""
        }
3.  for setting up, I only use "python3 /var/lib/irods/scripts/setup_irods.py" and 99% follow the guide from slides and doc.
4. nothing special, I think. run the postgresql on the same server with iRODS. just need to use the storage tiering function.

**Comment by korydraughn** [comment]
I suspect the use of `localhost` is an issue for the delay server.

Start the server and run the following:
```bash
iadmin set_delay_server $(hostname)
```

**Comment by peggy0135** [comment]
> I suspect the use of `localhost` is an issue for the delay server.
> 
> Start the server and run the following:
> 
> ```shell
> iadmin set_delay_server $(hostname)
> ```

Thank you @korydraughn 
It works,
the hostname really matters.
