### ISSUE TITLE
Investigate use of unattended_installation.json.in and if it should be removed

### ISSUE THREAD

**Issue by Nishant2022** [irods/irods#7111]
- [ ] main
- [ ] 4-3-stable

---

### Investigation

Currently there is a file: `unattended_installation.json.in` in the list of configuration schemas that does not appear to have a use. The only reference to it is in the CMakeList.txt in the server directory.

**Comment by trel** [comment]
This is used to help people provide a json file of information to the setup script, rather than answering questions or jamming a file into stdin.

**Comment by korydraughn** [comment]
@Nishant2022 See https://docs.irods.org/4.3.0/getting_started/installation/#unattended-install

**Comment by Nishant2022** [comment]
Clearly the file has a use. I checked it and the schema seems fine and does not need modification.

**Comment by trel** [comment]
thanks!
