### ISSUE TITLE
Metadata should be added only on data objects in `&` status

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods#7118]
### iRODS Version, OS and Version
4.3.0 almalinux8
iCommands 4.3.0

### What did you try to do?
Tried to add metadata on an object which is still being written - literally yet in `?` status. 

### Expected behavior
I guess no metadata should be added on an object as long as it is not in `good` status and the writing process is not completed yet - no transaction for metadata.
Thus expected to see either `-406000 LOCKED_DATA_OBJECT_ACCESS` or `-817000 CAT_UNKNOWN_FILE`.

### Observed behavior (including steps to reproduce, if applicable)
Metadata is added on a data object which is still being written.

To reproduce: 
A client may upload a large file and another client can try to add metadata.

```
root@010f175da147:/tmp# imeta ls -d /gbiomed/home/u0137480/test_globus/10GB.bin
AVUs defined for dataObj /gbiomed/home/u0137480/test_globus/10GB.bin:
None
root@010f175da147:/tmp# ils -L 10GB.bin
  u0137480          0 default;netapp            0 2023-06-09.14:11 ? 10GB.bin
        generic    /data/home/u0137480/test_globus/10GB.bin
root@010f175da147:/tmp# imeta add -d /gbiomed/home/u0137480/test_globus/10GB.bin atr val
root@010f175da147:/tmp# imeta ls -d /gbiomed/home/u0137480/test_globus/10GB.bin
AVUs defined for dataObj /gbiomed/home/u0137480/test_globus/10GB.bin:
attribute: atr
value: val
units:
root@010f175da147:/tmp# ils -L 10GB.bin
  u0137480          0 default;netapp            0 2023-06-09.14:11 ? 10GB.bin
        generic    /data/home/u0137480/test_globus/10GB.bin


```

**Comment by korydraughn** [comment]
Hmm, I see what you're getting at, but not allowing this could hurt flexibility IMO.

You can always detect data in flight using GenQuery so I'm not convinced this behavior needs to change.

Q. What is the motivation behind this?
Q. Has this behavior caused issues for your deployment in some way?

**Comment by trel** [comment]
Replicas have statuses, rather than data objects...  what about replicas that are stale?   Do you expect those to prevent addition of metadata?   How about editing or removing of existing metadata?

**Comment by mstfdkmn** [comment]
Indeed, the current situation is the functionality that it should be...Replicas have status and metadata is added on data objects, and this provides flexibilities in writing rules, managing data etc.

You can please close this. I encountered this while working on something else and hence created but was surprised then.

**Comment by trel** [comment]
Thanks Mustafa.   Closing.
