### ISSUE TITLE
test_delay_in_dynamic_pep__3342 fails in lib.delayAssert

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7121]
I ran into a test failure with `test_delay_in_dynamic_pep__3342` while working on PREP.
(This test fails regardless of whether or not PREP is configured, so it's not a PREP issue.)

The test is running in an Ubuntu 20.04 container, using postgres.

Here's some of the test output. I've put a more complete log [here](https://gist.github.com/SwooshyCueb/48b3af7b9863431bf7e58c7c08dc6b5b).

```
======================================================================
FAIL: test_delay_in_dynamic_pep__3342 (irods.test.test_icommands_file_operations.Test_ICommands_File_Operations)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_icommands_file_operations.py", line 799, in test_delay_in_dynamic_pep__3342
    lib.delayAssert(
  File "/var/lib/irods/scripts/irods/lib.py", line 565, in delayAssert
    raise AssertionError
AssertionError
```

**Comment by SwooshyCueb** [comment]
I have been unable to reproduce this test failure, leading me to believe that I was running a cron-disabled build of the server at the time. I'm going to leave this issue open until I can get around to doing some more testing, but I'm bumping it off 4.3.1

**Comment by korydraughn** [comment]
Sounds like you're thinking this may not be a real failure.

I haven't seen this test fail during any recent test runs.

**Comment by alanking** [comment]
I ran the test manually in a Debian 11 container from the testing environment with a build based on https://github.com/irods/irods/commit/084e1dabe017abb71f7658f8280d0361bf8a2cb1 and it passed 20 times. I can run it more times if desired, just takes a while.

**Comment by SwooshyCueb** [comment]
Nah, I think we can close this
