### ISSUE TITLE
Ticket modification time is not changing

### ISSUE THREAD

**Issue by ganning127** [irods/irods#7125]
- [x] main
- [x] 4-3-stable

---

### iRODS Version, OS and Version
- on the irods_demo repository
- 4.3.0

### What did you try to do?
Tried to modify a ticket, but the ticket modification time isn't changing. The modification time stays the same as the ticket create time.

### Expected behavior
After modifying the ticket, the modification time should be updated. 

### Observed behavior (including steps to reproduce, if applicable)
<img width="1044" alt="Screenshot 2023-06-16 at 12 38 26 PM" src="https://github.com/irods/irods/assets/62436772/9dc198db-3c1c-4620-8d47-ed2df79daec7">

`integer91` is just a `.txt` file with a random string in it.

**Comment by trel** [comment]
Good find.  Should be pretty easy to fix.

Think of the other things that can be modified - will need a test for each/all.

**Comment by alanking** [comment]
@Nishant2022 - Please close if complete. Thanks!
