### ISSUE TITLE
Add/Document special macro for hiding code from clang-tidy checks

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#7140]
- [ ] main
- [ ] 4-3-stable
---
## Feature
Certain parts of the codebase should be ignored by clang-tidy (e.g. library_features.h).

We can use macros to achieve this. To see the proposed solution, see PR #7047.

**Comment by korydraughn** [comment]
After some discussion, we've decided against this as this behavior can be controlled via clang-tidy comments. We just have to bump the compiler to a version which supports `// NOLINTBEGIN` and `// NOLINTEND`.

**Comment by trel** [comment]
removing checkboxes...
