### ISSUE TITLE
Add missing optional configurations to server_config.json on server upgrade

### ISSUE THREAD

**Issue by alanking** [irods/irods#7143]
## Feature

Whenever a new configuration value is added to the server configuration, we should add it to existing server configuration files on servers that upgrade to the version which introduced the configuration (or any version thereafter). Historically, optional configuration values have not been added on server upgrade. Optional configurations were internally given a default value when missing.

This was proposed as part of https://github.com/irods/irods/pull/6762.

**Comment by korydraughn** [comment]
I think this is already implemented for upgrades in 4.3.

Am I misunderstanding the issue?

**Comment by korydraughn** [comment]
On upgrade, If the option is part of the schema and is missing in the config file, it will be added. If the config contains unknown options, those will be carried forward unchanged.

**Comment by alanking** [comment]
That was not my experience. Adding the new configurations to the schema and the template did not add them to the existing configuration file when I upgraded from 4.3.0 as released to a custom build (even when I bumped the server version number).

If this is not the case, then we can close this, or, use this issue to document how to add configuration values for developers.

**Comment by korydraughn** [comment]
Ok. What I'm referring to may be specific to the schema version bump logic.

The pieces are there. Just have to pull them out for this issue.

**Comment by alanking** [comment]
Right, that would be what you described here: https://github.com/irods/irods/pull/6762#issuecomment-1343417857

I've actually already done the work, but wanted to make this as a space for discussion (besides just an issue to link to) before I push because I wanted to make sure this is what we wanted. These words are how I understood the proposal in that PR.

Please let me know if I've misunderstood.
