### ISSUE TITLE
``msiCollRsync`` as irods admin?

### ISSUE THREAD

**Issue by ll4strw** [irods/irods#7144]
- ``irods v4.3.0``
- ``Rocky Linux v8``
- ``acAclPolicy {msiAclPolicy("STRICT"); }``

Not sure if this is intended or not, but I am trying to rsync (same zone, IRODS_TO_IRODS) a collection to our data vault via  ``irule`` executed as an irods admin and I get  ``msiCollRsync status = -818000 CAT_NO_ACCESS_PERMISSION`` unless I make the source collection readable by the irods admin.
I tried with both plugins ``irods_rule_engine_plugin-irods_rule_language-instance`` and ``irule  -r irods_rule_engine_plugin-python-instance``.

Is this intended? I thought the best way to make <i>immutable</i> copies of existing data_objects or collections  was to create them as an irods admin, possibly via irules. But how efficient/convenient is to ichmod a source collection/data_object prior to an irsync? The docs state that "with STRICT access control, a rodsadmin can still execute microservices and queries to access system-wide information". Thanks.

**Comment by korydraughn** [comment]
rodsadmin users aren't allowed to manipulate other user's things as they want. So, in many cases, rodsadmin users are like rodsusers. The only exception is that rodsadmin users can **grant** themselves permission to do whatever they want and they have unrestricted access to query any information in the system.

So the behavior you're seeing is intended.

**Comment by korydraughn** [comment]
If you have other questions, feel free to open more issues.
