### ISSUE TITLE
Refactor parameters for resource functions in lib.py

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#7152]
- [x] main
- [x] 4-3-stable
- [x] Update other repos using these functions
---
## Refactor
The following python functions need to be changed so that the `user` parameter is the first parameter passed.
https://github.com/irods/irods/blob/1028d2e0b76a9b896df39e325aa9cc8f1c4f811f/scripts/irods/lib.py#L594
https://github.com/irods/irods/blob/1028d2e0b76a9b896df39e325aa9cc8f1c4f811f/scripts/irods/lib.py#L604
https://github.com/irods/irods/blob/1028d2e0b76a9b896df39e325aa9cc8f1c4f811f/scripts/irods/lib.py#L607
https://github.com/irods/irods/blob/1028d2e0b76a9b896df39e325aa9cc8f1c4f811f/scripts/irods/lib.py#L610
https://github.com/irods/irods/blob/1028d2e0b76a9b896df39e325aa9cc8f1c4f811f/scripts/irods/lib.py#L613
https://github.com/irods/irods/blob/1028d2e0b76a9b896df39e325aa9cc8f1c4f811f/scripts/irods/lib.py#L616
https://github.com/irods/irods/blob/1028d2e0b76a9b896df39e325aa9cc8f1c4f811f/scripts/irods/lib.py#L619

So, three changes here ...
- Make `user` parameter the first parameter
- Rename `user` parameter to `session`
- Update all tests to reflect changes

### Example
https://github.com/irods/irods/blob/1028d2e0b76a9b896df39e325aa9cc8f1c4f811f/scripts/irods/lib.py#L622

**Comment by korydraughn** [comment]
The reason for this change is so the functions in question align with newer functions introduced after these.

The order of the parameters for the functions in question is awkward and does not make sense. The example presented in the issue uses a signature that is better from a usage standpoint.

**Comment by trel** [comment]
fair enough.

**Comment by korydraughn** [comment]
Good idea. Will add a checkbox for that.

**Comment by Nishant2022** [comment]
All instances of the lib.py resource functions within the iRODS organization should now have been updated.

@korydraughn please mark that other repos have been updated.

**Comment by korydraughn** [comment]
Done.

**Comment by Nishant2022** [comment]
Awesome.
