### ISSUE TITLE
Type of the `size_` member of `irods::file_object` can lead to errors

### ISSUE THREAD

**Issue by alanking** [irods/irods#7154]
- [x] main
- [x] 4-3-stable
- [x] unit test (main)
- [x] unit test (4-3-stable)

---

## Bug Report

https://github.com/irods/irods/blob/1028d2e0b76a9b896df39e325aa9cc8f1c4f811f/server/core/include/irods/irods_file_object.hpp#L106-L108
https://github.com/irods/irods/blob/1028d2e0b76a9b896df39e325aa9cc8f1c4f811f/server/core/include/irods/irods_file_object.hpp#L137-L139
https://github.com/irods/irods/blob/1028d2e0b76a9b896df39e325aa9cc8f1c4f811f/server/core/include/irods/irods_file_object.hpp#L170

Data size members of most if not all other structs (particularly input structs used by clients) use `rodsLong_t`. `rodsLong_t` resolves to a signed value, so passing a negative value and then putting that size into an `irods::file_object` will cause the value to wrap (`size_t` is unsigned).

This has been demonstrated to cause problems due to usage such as that seen in https://github.com/irods/python-irodsclient/issues/462, wherein -1 is passed as a data size to the open API.

The type deduced from this call will be `size_t` which means that if the value stored is negative, this code produces incorrect behavior:
https://github.com/irods/irods/blob/1028d2e0b76a9b896df39e325aa9cc8f1c4f811f/server/core/src/voting.cpp#L97-L100

**Comment by korydraughn** [comment]
`rodsLong_t` is essentially an alias for `int64_t`.

Several things rely on `rodsLong_t` for the file size, etc. The safest path forward is to use that IMO. It also means if the type of `rodsLong_t` changes in the future, all locations using that type alias will be updated too.

A signed 64 bit number gives us a wide range of values. I don't think we have to worry about exhausting the range just yet. Also, introducing `int128_t` into the codebase may be problematic depending on the target platform.

**Comment by alanking** [comment]
Wonder if it would be worth adding a unit test which calls `rcDataObjOpen` with a negative size (a la PRC) to make sure things are functioning as they should. Just noting it here.

**Comment by korydraughn** [comment]
I agree.

**Comment by alanking** [comment]
Apologies, I never gave a description of the "errors" that this issue "can lead to", so I will do so here.

The check in the code snippet linked above can lead to a `USER_FILE_TOO_LARGE` error when the `DataObjInp::dataSize` is set to -1. This is because the `> 0` check fails due to the wraparound of the unsigned value. The wrapped-around value is very large, of course, so the free space with the provided `dataSize` would be incorrectly reported as too low for the "minimum free space for create" in the context string.

The test should configure some high-but-not-too-high value for minimum free space for create (see https://docs.irods.org/4.3.0/plugins/composable_resources/#unixfilesystem) as well as the free space on the resource. Then the test calls `rcDataObjOpen` with a `dataSize` of -1 in the input to demonstrate the problem, which should be fixed by the changing of the type.

I believe that this can be done using C client calls. Configuring the free space on the resource doesn't appear to be supported in the administration library because updating the free space seems to be relegated to a microservice rather than an API. However, we can execute rules, so that might not be so bad.

It's a bit of a lift, so I wouldn't be opposed to punting on this for now since we have demonstrated the fix manually. Thoughts?

**Comment by Nishant2022** [comment]
I took a look at what I would have to do for this. I do not think I will be able to finish it in the time that I have left. Maybe we open a new issue for the test you're looking for?

**Comment by korydraughn** [comment]
@alanking See if you can put together a test for the case you've described. If you can put together a test, then we can add two additional checkboxes for testing. If not, then we punt the test to a later day (before releasing 4.3.1 though).

Thoughts?

**Comment by alanking** [comment]
Assigning myself for the other part. Although, it may be easier to just write a python test with `istream` as suggested here: https://github.com/irods/irods/issues/7160#issuecomment-1642343084 Will think on that.
