### ISSUE TITLE
Provide a mechanism for plugins to tell the server what flags to pass to `dlopen()`

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7158]
- [x] main
- [x] 4-3-stable
---
Related: irods/irods_rule_engine_plugin_python#136

Currently, we pass `RTLD_LAZY | RTLD_LOCAL` to `dlopen()` when loading plugins. We need to provide a mechanism that plugins can use to tell the server if different flags are required.

The current plan is to use `DT_FLAGS_1` for this purpose.

**Comment by korydraughn** [comment]
Is there documentation you can link to this issue people interested in reading about `DT_FLAGS_1`?

**Comment by SwooshyCueb** [comment]
Ehhh sorta?
So the `DT_FLAGS_1` dynamic table entry is an extension to ELF that is not in the LSB Specification or the System V ABI. My understanding is that Sun was the only vendor to ever use it, so [what little documentation there is](https://docs.oracle.com/cd/E19957-01/806-0641/chapter6-42444/index.html) doesn't actually reflect how it is used (or rather, not used) in Linux today. 
However, everything you need to parse a `DT_FLAGS_1` dynamic table entry is in `elf.h` (both glibc's and muslc's), and there are arguments that can be passed to `bfd` and `lld` (the most common linkers in use on Linux (and FreeBSD)) that can direct the linker to create a `DT_FLAGS_1` dynamic table entry and set certain flags. The one we're concerned with is `DT_1_GLOBAL`, which is supposed to tell the runtime linker to always load the library's symbols in the global namespace, but almost no implementation actually respects. The argument to pass to the build-time linker is `-z global` (or `-Wl,z,global` if calling via clang or gcc).

**Comment by SwooshyCueb** [comment]
Moved the documentation task to irods/irods_docs#207. This issue and related issues can be closed now
