### ISSUE TITLE
`DataObjInp::dataSize` should be initialized to -1

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#7160]
- [x] dstream (main)
- [x] dstream (4-3-stable)
- [x] test (main)
- [x] test (4-3-stable)
---
## Question / Investigation
The dstream library used by `istream` and other projects initializes `DataObjInp::dataSize` to 0.
https://github.com/irods/irods/blob/124c9eae12062e50ad73d0436ba1eb76b63149af/lib/core/include/irods/transport/default_transport.hpp#L343

The Python iRODS client initializes the `DataObjInp::dataSize` member to -1.

These values can trigger different behavior. For that reason, we need to investigate which one is the correct default.

### Proposed Solution
The correct default is -1 because it signals that the size is unknown and/or not set.

0 is an invalid default because it is in the range of valid file sizes.

Related to #7154.

**Comment by trel** [comment]
Are there any backwards compatibility considerations here?

If we change the dstream default to -1... and use a binary built with this new irods-dev... to talk to any server older than 4.3.1... it will be angry because of https://github.com/irods/irods/issues/7154.   Am I understanding/projecting correctly?

**Comment by korydraughn** [comment]
Only if tracking freespace is enabled via `msi_update_unixfilesystem_resource_free_space` and a `minimum_free_space_for_create_in_bytes` is set.

**Comment by trel** [comment]
right, and there's no way to 'know' about those ahead of time... so we tell people to upgrade and the problem goes away - same as the original issue.

yes, -1 feels the best default moving forward.

**Comment by alanking** [comment]
This would also possibly invalidate the "unit test" I suggested here: https://github.com/irods/irods/issues/7154#issuecomment-1640532703 A python test would be much easier to write using `istream` and `iadmin` and a configured rulebase.

**Comment by alanking** [comment]
Let's leave this open for now as I'm still thinking about what to do about a test for this and #7154.
