### ISSUE TITLE
No microservice available for removing user from group

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#7165]
- [x] main
- [x] 4-3-stable
---
## Bug Report
We have `msiAddUserToGroup`. It only makes sense to provide `msiRemoveUserFromGroup`.

Perhaps we add an `msi_remove_user_from_all_groups`? _(This would be a performance optimization)_

**Comment by trel** [comment]
We definitely need `msiRemoveUserFromGroup`, rather surprised we don't already have that.

---

Alternatively... `msiRemoveUserFromGroups` could take a list?
