### ISSUE TITLE
Creating a data object containing a single quote in the name using itouch results in SYS_NO_GOOD_REPLICA

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#7169]
## Bug Report

We need to investigate why `SYS_NO_GOOD_REPLICA` is returned for this case. The data object appears to have been created successfully.
```
irods@cc9948e56928:~$ ils
/tempZone/home/rods:
irods@cc9948e56928:~$ itouch "just testin'"
Level 0: SYS_NO_GOOD_REPLICA: No good replicas found.


irods@cc9948e56928:~$ ils
/tempZone/home/rods:
  just testin'
irods@cc9948e56928:~$ ils -l
/tempZone/home/rods:
  rods              0 demoResc            0 2023-07-05.12:24 & just testin'
```

**Comment by alanking** [comment]
Related: Related: https://github.com/irods/irods/issues/5727

**Comment by FifthPotato** [comment]
Verified that this is due to the genQuery issue. Throws on line 384 of `plugins/api/src/touch.cpp`

https://github.com/irods/irods/blob/198873a0c2ac137ec6cbe18bff314bc34b8db311/plugins/api/src/touch.cpp#L373-L385

Above it, you see a genQuery. I tested as follows:
```
root@bde8b726cabd:/# iquest "select DATA_MODIFY_TIME, DATA_REPL_NUM where COLL_NAME = '/tempZone/home/rods' and DATA_NAME = 'testin'' and DATA_REPL_STATUS = '1'"             
CAT_NO_ROWS_FOUND: Nothing was found matching your query
```

```
root@bde8b726cabd:/# iquest "select DATA_MODIFY_TIME, DATA_REPL_NUM where COLL_NAME = '/tempZone/home/rods' and DATA_REPL_STATUS = '1' and DATA_NAME = 'testin''"             
DATA_MODIFY_TIME = 01694509324
DATA_REPL_NUM = 0
------------------------------------------------------------
```

Since swapping the where clauses caused the embedded quote to stop malfunctioning (exactly as the other embedded quote issues behaved) this is identical to the others.

**Comment by korydraughn** [comment]
Great investigative work.

Bumping. This will be fixed once the GenQuery2 parser is available.

**Comment by trel** [comment]
Swapping was demonstrated to 'work' in https://github.com/irods/irods/issues/5727.

But depending on this buggy behavior is not healthy.

Yes, GenQuery2 is the answer.

**Comment by korydraughn** [comment]
Related #3902

**Comment by korydraughn** [comment]
4.3.2 will make GenQuery2 available for use, but will not replace any GenQuery1 logic until 4.3.3 or later.

GenQuery2 needs time in the hands of the community before replacing GenQuery1 usage.

Bumping.

**Comment by trel** [comment]
Candidate for bumping again, since we're still not replacing any GenQuery1 logic in 4.3.3?

**Comment by alanking** [comment]
Agreed, this should probably be bumped. This could be fixed by https://github.com/irods/irods/pull/7819 (maybe), but we are not including those changes in 4.3.3.

**Comment by trel** [comment]
bumping
