### ISSUE TITLE
Individual CRON manager tasks should be disable-able

### ISSUE THREAD

**Issue by alanking** [irods/irods#7170]
## Feature

There is no way to disable a particular CRON manager task. We should use a special value for this because the intervals used for individual CRON manager tasks are measured in seconds.

Currently, non-negative values are being considered. CRON manager tasks can be run on every iteration by setting the interval time to 0. We should use a negative value (i.e. -1) or repurpose 0 for this.

Note: There is no configuration for the interval of the CRON manager itself.

**Comment by korydraughn** [comment]
iRODS 5 no longer uses the CRON manager so this issue may be unnecessary.

**Comment by trel** [comment]
Agreed - motion to close this as `resolved/invalid`.

However, we'll need to consider something similar in server_config.json for each of the 'child tasks' of the main server in 5+.

**Comment by korydraughn** [comment]
Correct.

Closing.
