### ISSUE TITLE
Investigate `test_control_plane` failing.

### ISSUE THREAD

**Issue by Nishant2022** [irods/irods#7172]
When running the core tests, `test_control_plane` fails, specifically the `test_shutdown_local_server` and `test_shutdown_local_server_using_hostname_alias_defined_in_server_config__issue_5700` functions. 

They fail because `lib.get_file_size_by_path(IrodsConfig().server_parent_log_path)` throws an error.

`test_control_plane` did pass in topology testing though. The two functions that are causing problems were not skipped and ran successfully.

**Comment by SwooshyCueb** [comment]
I am currently running the python suite in a development environment Ubuntu 20.04 runner, and `test_control_plane` passed for me. The only test that was skipped was `test_empty_message` due to lack of `pyzmq`

**Comment by korydraughn** [comment]
Agreed. I've also seen all of the reported tests pass.

Let's leave the issues around testing open until the non-testing issues are resolved.

**Comment by Nishant2022** [comment]
Perhaps it's a resource limited test. I ran the tests on a RENCI VM with 4 cores and 16 GB of ram. I also believe there is a storage issue because the only tests that would fail were ones trying to access logs. However it may just be some quirk of the machines I used.

**Comment by korydraughn** [comment]
At this point, we're confident this is likely due to the hardware. The test passes consistently on a large enough computer.

Closing.
