### ISSUE TITLE
Investigate `OPENSSL_API_COMPAT` format inconsistency

### ISSUE THREAD

**Issue by alanking** [irods/irods#7175]
https://www.openssl.org/docs/man3.0/man7/OPENSSL_API_COMPAT.html describes two forms of defining `OPENSSL_API_COMPAT`:

1. **0xMNNFF000L**
2. **mmnnpp**

The second is the newer, recommended form, and the one which is being used in the `CMakeLists.txt` for https://github.com/irods/irods/pull/6620.

The first is the only one which works for https://github.com/irods/libs3/pull/22 for all platforms. I got the following message on Ubuntu 22.04 when attempting to compile libs3 with the second form:
```
error: #error "OPENSSL_API_COMPAT expresses an impossible API compatibility level"
```

So, the first form works fine for all platforms when compiling libs3. The second form works for all platforms when compiling iRODS. Not sure why yet.

_Originally posted by @alanking in https://github.com/irods/irods/issues/6620#issuecomment-1623738155_

---

Please investigate why there is a discrepancy between the form used in irods/irods and the form used in irods/libs3 in the main branch.

**Comment by alanking** [comment]
I think I understand what went wrong here...

The recommended form for specifying the `OPENSSL_API_COMPAT` macro is **mmnnpp**.

The value to provide for compatibility with version 1.1.0 should be **10100**.

I was providing **101000** in #6620 and irods/libs3#22, which would indicate compatibility with version 10.10.0. :( This fully explains the error messages and indicates that we can use the recommended form for all platforms.

The only thing I don't understand now is why some platforms were okay with the 10.10.0 compatibility.

**Comment by korydraughn** [comment]
That is surprising, but it doesn't sound like something we have to concern ourselves with.

Of course, it doesn't hurt to the reason. Knowing may help us in the future. Up to you if you want to investigate.

**Comment by alanking** [comment]
I don't think that investigating the issue any further is worth the time. The recommended form of the macro works as expected for all platforms and any further investigation would be debugging my dumb typo. Closing as resolved/invalid.
