### ISSUE TITLE
Investigate how to disassociate a ticket from a connection

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#7179]
- [x] main
- [x] 4-3-stable
---
## Investigation
iRODS allows tickets to be used on a connection to grant access to collections and data objects. Current support allows associating a ticket with a connection, but once done, is it possible to disassociate the ticket later?

We need to investigate whether a ticket can be detached from a connection. This is important for applications wanting to use connection pooling.

This is especially important for applications like the iRODS HTTP API.

**Comment by korydraughn** [comment]
This is supported. I've captured this behavior in a unit test.

This is achieved via the same mechanism for enabling a ticket on a connection. Instead of passing a ticket string, you'd just pass an empty string. For example:
```cpp
ticketAdminInp_t input;
memset(&input, 0, sizeof(ticketAdminInp_t));
input.arg1 = "session";
input.arg2 = ""; // This is normally set to the ticket string.
input.arg3 = ""; // This is for safety purposes in the face of redirects.

// Call rcTicketAdmin().
```

I expect it will be merged soon.

**Comment by trel** [comment]
oh, very nice.

**Comment by alanking** [comment]
Please remember to add a label on this. Maybe "testing"?
