### ISSUE TITLE
setSessionTicket can result in segmentation fault

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#7185]
- [x] main
- [x] 4-3-stable
---
### iRODS Version, OS and Version
4.3.0+ , ubuntu 18.04

### What did you try to do?
call setSessionTicket on a connection pointer.

### Expected behavior
set the session ticket

### Observed behavior (including steps to reproduce, if applicable)
Blows up with a segmentation fault -- but not all the time -- when calling from [this code,](https://github.com/d-w-moore/irods_project_template_cpp_client/blob/202c6d2b67bae1cd1c46b1a829328ee0053f201e/src/main.cpp#L41) per the [usage in lsUtil](https://github.com/irods/irods/blob/ef676952df59d31aabf2db4ec65efea8ccbbbc48/lib/core/src/lsUtil.cpp#L32). Not sure why it doesn't seem to blow up there...
Looking into `setSessionTicket` it's evident packstruct is eventually getting called on an uninitialized structure, so the segmentation fault maybe is not surprising.

**Comment by alanking** [comment]
It seems pretty clear, but just making sure that we are talking about a segmentation fault on the client side, right?

**Comment by korydraughn** [comment]
It's clear the input struct for `rcTicketAdmin` is not initialized appropriately.

To avoid further issues, avoid using the Util functions designed for the iCommands.

In the meantime, we'll fix the initialization issue for all implementations of `setSessionTicket`.
