### ISSUE TITLE
Add support for AlmaLinux 9 and Rocky Linux 9

### ISSUE THREAD

**Issue by montesmariana** [irods/irods#7191]
- [x] irods_development_environment
- [x] irods_testing_environment
- [x] GitHub Actions
---
Hi all,

Would it be possible to create an iCommands distribution for Rocky Linux 9?

Thank you!

**Comment by alanking** [comment]
Making a note here that SHA1 has been deprecated in RHEL9, so our signing key can no longer be imported by `rpm`:
```bash
$ rpm --import https://packages.irods.org/irods-signing-key.asc
warning: Signature not supported. Hash algorithm SHA1 not available. 
error: https://packages.irods.org/irods-signing-key.asc: key 1 import failed.
```
Here is a suggestion elsewhere on how to re-sign the keys: https://github.com/elastic/elasticsearch/issues/85876#issuecomment-1669726248

For now, there is a workaround:
```bash
$ update-crypto-policies --set LEGACY
$ rpm --import https://packages.irods.org/irods-signing-key.asc
```

**Comment by alanking** [comment]
The main thrust for this work has been completed. If we run into issues with the new platform(s), we can open new issues for those issues.
