### ISSUE TITLE
Clang-Tidy: Demote `modernize-use-auto` to a warning

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#7217]
- [x] main
- [x] 4-3-stable
---
## Build Tools
Using explicit types is **never** a bad thing. If anything, they help detect bugs when modifying code.

The decision to use explicit types vs type deduction is a decision that should be left up to the implementer unless the code has special requirements/constraints.

**Comment by SwooshyCueb** [comment]
Honestly it might be a good idea to disable this one entirely. It can get quite noisy, potentially drowning out other check failures.

**Comment by trel** [comment]
is it worth it to gather some stats on the current codebase at the moment before making this decision?

**Comment by korydraughn** [comment]
I'm fine with disabling this one based on the original reason for demotion.

> is it worth it to gather some stats on the current codebase at the moment before making this decision?

I don't think so.

What kind of stats are you thinking of?
Does disabling the check raise any concerns?

**Comment by trel** [comment]
just a count, perhaps.   in reference to 'noisy'.

no, no concerns at all.

**Comment by korydraughn** [comment]
I don't feel it is necessary, but if you'd like a count, we can try and capture that.

I'm going to go ahead and disable this check entirely. It doesn't add any value to the implementation.
