### ISSUE TITLE
Redesign/Refactor/Simplify main server logic

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#7229]
## Redesign / Refactor
The startup logic for the iRODS server is complicated and difficult to reason about.

Due to a mixture of forking and multi-threading, adding new features to the main server process is tricky. We need to simplify how startup is carried out so that iRODS is in a better position to take on future requirements.

A simpler architecture could be:
- Main iRODS process forks child processes
    - Perhaps this becomes pluggable
- Main iRODS process makes sure all child processes are running, forking new ones if they disappear
- Child processes have one job
    - e.g. Agent factory, Delay server, Control plane, etc
- Agent factory manages port 1247
- Control plane manages port 1248
- Access to global state must be through interfaces or services
    - i.e. Dependency injection
- Initialization of global state must be deterministic
- Everything must be ASan, Ubsan, Tsan friendly

Things to consider:
- How should child processes communicate?
- How should the main server process relay information to children?
- How should child processes relay information to main server process?
- Where does the CRON manager run?
- Who is responsible for the CRON manager?
- How should monitoring be supported?
- What should be monitored?
- What things are considered iRODS 5.0 territory?

To keep things interesting, it must still be backwards compatible with 4.3.

**Comment by korydraughn** [comment]
This is likely an iRODS 6.0 thing, but definitely worth considering at some point.
- https://unixism.net/2019/04/linux-applications-performance-introduction/

That is, we investigate changing the process model to pre-forked or pre-threaded. If we do this, the performance should improve, but we have to make sure there are no memory leaks. That means incorporating Asan and other tools during testing.

**Comment by korydraughn** [comment]
This comment is mostly so others have some idea about what's happening regarding iRODS 5.

### Current Status

- The iRODS 5 server is runnable _(not for production use yet)_
- Startup is faster
- Ownership of components, memory, etc is now clearer
  - e.g. The main server process watches children and handles delay server migration
  - e.g. The agent factory is in charge of all information required by `ips`
  - e.g. The agent factory manages port 1247
- Signal handling for `SIGINT,` `SIGTERM,` and `SIGHUP` are working as intended
  - Signals are sent to child processes appropriately
  - The agent factory and delay server now respond to `SIGHUP,` but only if the main server process sent it
- The main server process and agent factory no longer rely on multiple threads
- The need for a control plane has been removed (so far)
- We've successfully avoided creating dependencies on Python for startup
- The server always performs a graceful shutdown
  - It never sends `SIGKILL`. `SIGKILL` is either sent by the admin or the OS

Things we plan on implementing, but haven't gotten to yet:
- JSON schema validation on startup (as demonstrated in the HTTP API)
  - We're looking at possibly using the jsoncons library for validation. It's very similar to the nlohmann JSON library, but is more efficient and has JSON schema validation.
- Putting files in more appropriate places
  - e.g. `/usr/share` could hold test scripts and other files that aren't needed for running the server
  - e.g. `/var/run` for PID files
  - e.g. `/var` for other files that change frequently
- Removing the version.json file and embedding the build information into the binary

When it comes to cloud-friendliness, we're considering one of the following _(this also applies to non-package installs)_:
- iRODS 5 accepts a path to a single configuration file which defines everything it needs
  - That is, the directory for storing stacktrace files, `ips` info, etc.
  - This file would contain all options from server_config.json too
- Alternatively, iRODS 5 accepts a path to a directory which has the expected directory structure. The following would be required to exist _(not exhaustive)_:
  - `<config_root>/server_config.json`
  - `<config_root>/process_data/` _(holds info for `ips`)_
  - `<config_root>/service_account.config`
  - `<config_root>/core.*`
  - `<config_root>/stacktraces/`
  - `<config_root>/version.json` _(assuming we don't embed this info into the binary)_
  - `<config_root>` can live anywhere on the computer
    - Perhaps it is created by running the server application or another application
      - e.g. `irodsServer --init-directory /path/to/non/existent/directory`
      - e.g. `cp -r /usr/share/irods/config-template /path/to/non/existent/directory`

Here are some goals we believe are possible, but won't know for sure until the work is closer to completion:
- Making non-package installation a matter of just configuration
  - That is, no special build steps or documentation needed
- Running multiple versions of iRODS on the same computer
  - Likely requires adding the version number to the binary name (e.g. irodsServer-5.0.0)
- Running multiple instances of iRODS on the same computer

### Current Challenge

The primary challenge at the moment is figuring out how to best handle reloading of the configuration.

Here are a few questions we're thinking about:
- Should a reload involve all configuration options or a subset?
  - Keep in mind there's a lot of global state in iRODS
    - e.g. NREP, PREP, plugins, shared memory, resource manager, etc
- Should a reload affect long-running connections? In what way?
  - e.g. The HTTP API's connection pooling, Metalnx, etc

#### Idea A

The simplest way to handle this is to do the following:
- Shutdown the listening port
- Stop the delay server from fetching new work from the catalog
- Launch a new agent factory and delay server
- Let the original agent factory and delay server complete outstanding work gracefully

The only issue with the described solution is - the presence of long-lived connections (i.e. the HTTP API and Metalnx). These client applications cannot detect reloads of the iRODS server.
- Perhaps we add an endpoint that allows client applications such as these to ask the server when it last rebooted?
- Or maybe the iRODS server kills all agents forcing the client applications to refresh their connections?

How important is it that the iRODS server let clients finish their work? _Keep in mind that a client can open a connection and do nothing. This could make graceful shutdown last forever._

#### Idea B

The alternative solution to the reload challenge is we make reloads apply to a safe subset of configuration options. _This doesn't seem that easy either since we have to know how each option is used throughout the server._

---

Knowing which options admins tweak frequently and whether those tweaks occur at scheduled times of the day would help us determine the best course of action. Feel free to leave feedback here or send me an email.

**Comment by trel** [comment]
> Or maybe the iRODS server kills all agents forcing the client applications to refresh their connections?

Can we 'inform' agents that they should let go of any work within X seconds?   So we're not issuing a KILL, but rather asking nicely, allowing them to cleanup anything that may need to be handled before exiting cleanly.

**Comment by korydraughn** [comment]
Yes. What you've described is exactly what's been implemented as of today.

Here are the high-level details:
- `SIGTERM` instructs the server to stop as fast as possible
  - Socket operations are interrupted as soon as possible, but gracefully
  - All agents terminate normally
    - It's possible that operations 
- `SIGQUIT` instructs the server to stop gracefully
  - Gives agents _N_ seconds to complete servicing of client requests
    - Where _N_ is defined in server_config.json as `graceful_shutdown_timeout_in_seconds`
  - The server stops once either of the following conditions is satisfied:
    - All agents have terminated
    - The graceful timeout limit has been exceeded
  - After _N_ seconds, if agents are still around, the server performs a `SIGTERM`-like stop operation
- `SIGHUP` instructs the server to validate and reload the configuration
  - If the new configuration passes validation, the agent factory is instructed to carry out `SIGTERM` behavior
  - This could be changed to follow the `SIGQUIT` behavior, but there doesn't appear to be any reason to do that
  - Lastly, because the number of requests from a client is unknown, the best we can do is gracefully terminate the agent

**Comment by trel** [comment]
> Where N is defined in server_config.json as graceful_shutdown_timeout_in_seconds

consider whether this should be a zone-wide setting.    a server-level setting is fine, allows different values on different servers...

**Comment by korydraughn** [comment]
A zone-wide option makes sense. A local override makes sense too.

A few questions to think about ...
- On a technical level, when is the option fetched from the database?
- Does this require finding the provider or should all servers have database credentials?
  - Should the presence of database credentials influence how the server retrieves the option?
  - Keep in mind that with the current design, database access only happens through the agent factory
- What is the order of operations if/when the database holds zone-wide _startup_ options?
  - Server reads local config today and begins the startup process. When is the database visited? Before or after the agent factory is launched?
  - When is the server considered ready to serve client requests? Does this matter?

**Comment by korydraughn** [comment]
After some discussion, we're going to keep the graceful options as server-level options _(reduces complexity)_. We'll also adjust the reload logic to perform `SIGQUIT` behavior instead of `SIGTERM` behavior. A new config option will be exposed to allow admins to control the grace period for terminating agents following a config reload (i.e. `SIGHUP`).

Now, the more I think about a second config option, the more I feel it isn't necessary. A reload in iRODS 5 is a graceful shutdown + forking of new agent factory and delay server.

Thoughts?

**Comment by trel** [comment]
> Now, the more I think about a second config option, the more I feel it isn't necessary. A reload in iRODS 5 is a graceful shutdown + forking of new agent factory and delay server.

A reload  will trigger the `SIGQUIT` behavior for the existing agent factory, which will use the `graceful_shutdown_timeout_in_seconds` timeout before using `SIGTERM`.

I think that may not be 'enough' time to let a busy server finish all its work.

Some use cases:

| Case | Goal    | Solution |
| ------ | ---- | ------- |
|  1  |  admin wants to shut it all down immediately  |  `SIGTERM` |
|  2  |  admin wants to issue a graceful shutdown, no limit, let all processes complete  |  `SIGQUIT`, but... no limit?  |
|  3 |  admin wants to issue a graceful shutdown, but with reasonable N seconds, then 'kill'  |  `SIGQUIT` |
|  4 |  admin wants to reload, losing no active processes, all work completes  |  `SIGHUP` |

I'm not sure your proposal a few lines up satisfies all four cases...

And... are there other cases that we want?

**Comment by trel** [comment]
After discussion... it is the design goal to only support cases 1, 3, and 4.

Case 2 is moot:

 - Case 2-1 ... clients may never let go (by design).... e.g. iRODS HTTP API and iRODS S3 API (they use connection pooling to keep connections hot and ready)

 - Case 2-2 ... clients may let go at *some point* in the future ... e.g. a really big transfer could take a couple days to complete

We cannot distinguish on the server side between 2-1 and 2-2... so all we can do is send an error to the clients that will let them take care of any re-connecting / re-trying / re-transferring they may need to do.  The bookkeeping is on the client.  We have to let go on the server side, cleanly.

---

The responsibility for handling the new ERROR code is being shifted to the clients.

**Comment by trel** [comment]
The `graceful_shutdown_timeout_in_seconds` configuration setting will require the administrator to define the timeout well BEFORE the 'runtime' event of sending a signal to reload/shutdown.  This value will be read at server startup.

This may not prove as flexible as desired by the administrators - but we can add an API call or other logic on top of the signals... later.  This should probably be a new issue so we don't lose track of the idea.

**Comment by korydraughn** [comment]
More updates ...

To run multiple instances of iRODS 5 on the same computer, the following must be true:
- Must use different catalog/database (catalog can exist in same database system)
- Must use different directory for `ips` data files (`<prefix>/tmp/irods/proc`)
- Must use different PID file
- Must use different stacktrace directory
- Must use different (hostname/IP, port) tuple for listening socket
- Must use different log directory for setup files
- Must use different version.json file

The conversation in #7427 is highly related to the work for this issue. For example, the following bullet item from https://github.com/irods/irods/issues/7427#issuecomment-2420657588 will need more a bit more thought.
> - To start the server, users are required to pass a configuration directory holding server_config.json and version.json

That bullet item stems from the offline discussion which led to that comment. The idea from the offline discussion is:
- `<prefix>/etc/irods/`: Passed to the server binary on startup
- `<prefix>/etc/irods/`: Defined by the NREP's `plugin_specific_configuration` stanza

The NREP's configuration would restore the ability to accept relative paths for rulebase files. Those relative paths would be resolved using a new property. Below is an example of what the new configuration could look like.
```js
{
    "instance_name": "irods_rule_engine_plugin-irods_rule_language-instance",
    "plugin_name": "irods_rule_engine_plugin-irods_rule_language",
    "plugin_specific_configuration": {
        "rulebase_directory": ".",  // <-- THIS WOULD BE REQUIRED AND USED FOR FILE RESOLUTION
        "re_data_variable_mapping_set": [
            "core.dvm"
        ],
        "re_function_name_mapping_set": [
           "core.fnm"
        ],
        "re_rulebase_set": [
            "core.re"
        ],
        "regexes_for_supported_peps": [
            "ac[^ ]*",
            "msi[^ ]*",
            "[^ ]*pep_[^ ]*_(pre|post|except|finally)"
        ]
    },
    "shared_memory_instance": "irods_rule_language_rule_engine"
}
```

The issue is that the version.json file does not live in `<prefix>/etc/irods`. Now, all of this is solved by introducing a directory which symlinks the relevant files. That's not ideal though. This situation isn't a real blocker either. It's just something we need to keep in mind.

Here's two ideas that could help with this:
- Make users pass the config and version file via required flags (e.g. `--config-file` and `--version-file`)
- Or, embed the version info into the binary removing the need for the version.json file

**Comment by trel** [comment]
> embed the version info into the binary removing the need for the version.json file

we could do that - the server knows about itself and its requirements (e.g. database schema needed)

but we would have to replace the install history somewhere else if we wanted to keep that functionality.

Could also just live in the catalog…

**Comment by korydraughn** [comment]
Right. Nothing relies on the history (stored in the previous_version stanza) so we can store/change that however we like.

**Comment by trel** [comment]
i like it.   could even be worth a new table... a generic 'zone history' table of some kind...
