### ISSUE TITLE
Auth tests: Either skip or error (rather than fail) when irodsauthuser not present

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7243]
- [x] main
- [x] 4-3-stable

---

In #7189, we changed the auth tests to fail if the linux user `irodsauthuser` does not exist with the proper password. We did this by calling `TestCase.fail()` in the `setUp()` method.

This does not track with the implied meaning of a test failure.

Excluding edge-cases, a test result should follow this pattern:
- **Success**: The test ran without any issues and passed.
- **Failure**: The test ran without any issues but did not pass.
- **Error**: The test encountered some test-related or environment-related issue and therefore it cannot be determined whether the test passes.
- **Skip**: The test was skipped for one of the following reasons:
    - A known issue prevents the test from passing and/or running properly
    - It was determined that the testing conditions either makes the test irrelevant or un-runnable (wrong rule engine plugin, no `sudo` installed, etc)

Failing the test due to a missing linux user does not match this pattern. The test should either be skipped (by calling `TestCase.skipTest()`) or should return an error result (raise any exception besides `AssertionException` or `SkipTest`) instead.

**Comment by alanking** [comment]
Agreed. I think I am leaning toward raising an `Exception` because, in my opinion, we should avoid skipping tests if we can. `EnvironmentError` looks like a pretty good candidate...

**Comment by trel** [comment]
Agreed.
