### ISSUE TITLE
Bump Boost library dependency to 1.81

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#7247]
- [x] main
- [x] 4-3-stable
---
## Build / Tools
Bumping the Boost version to 1.81 or later will expose new libraries and enhancements.

More importantly, this will give the HTTP API access to the new Boost.URL library.

**Comment by SwooshyCueb** [comment]
I am in favor of this for Boost.URL, however I think in general we should try to avoid bumping our boost version, as it will mean a larger irods-externals footprint for distros that don't have the minimum version we need. We will not only have to package boost, but any other dependency that uses boost. (I recall there being at least one.) At present, only Debian 12 has boost 1.81.

I think that past 1.81, we should put a moratorium on bumping the minimum required version of boost unless absolutely necessary.

**Comment by korydraughn** [comment]
The latest version of Boost isn't a hard requirement.

Moving to Boost 1.81 sounds perfectly reasonable to me.

**Comment by trel** [comment]
Agreed - 1.81 seems good - HTTP API not having to do this itself is handy/good.

**Comment by SwooshyCueb** [comment]
Let's change the issue title to "Bump Boost library dependency to 1.81"

**Comment by SwooshyCueb** [comment]
Quick note for whoever picks up this issue, all externals that use boost will need their `consortium_build_number`s bumped

**Comment by trel** [comment]
right, good point.   as long as they don't move up in version themselves.
