### ISSUE TITLE
with ticket activated, data object OPEN locks up on other clients after rcGetHostFor(Put|Get)

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#7250]
- [x] main
- [x] 4-3-stable
---
### iRODS Version, OS and Version

iRODS, 4-3-stable (https://github.com/irods/irods/tree/bb7798a61226618e647d7d12700c2121c956e15a)
Ubuntu 18.04

### What did you try to do?

On attempting to implement client redirection to resource server in the python-irodsclient, the following actions caused a lockup:
  1) connection **_A_** activates ticket **_T_** ( allowing access to data object **_D_**) and performs rcGetHostForGet with DastaObjInp initialized for **_D_**
  2) connection **_B_** is made based on parameters of connection **_A_** (hostname could be different, eg based on rcGetHostForGet output, but need not be)
  3) connection **_B_** also activates ticket **_T_**
  4) DATA_OBJ_OPEN_AN is attempted on connection **_B_** (with read flags) to open data object **_D_**

### Expected behavior

Data Open should succeed.

### Observed behavior (including steps to reproduce, if applicable)

On an update to the ticket object row in the ICAT, we lock up during an `_rsGenQuery`.  This shows a DB handle is in conflict between different processes. Note the max uses count must be set on the ticket to reproduce the issue.

Debugging showed the locking up to happen in this call chain, as connection **_B_** is trying to open the data object:

```
rsDataObjOpen
get_data_object_info_for_open
resolve_resource_ hierarchy
file_object_factory
getDataObjInfoIncSpecColl
chl_gen_query_impl
checkCondInputAccess
cmlCheckTicketRestrictions
----------------------------------------
REPO_ROOT/plugins/database/src/mid_level_routines.cpp                                                                 │
  >│1573                status =  cmlExecuteNoAnswerSql(                                                                                                │
   │1574                              "update R_TICKET_MAIN set uses_count=? where ticket_id=?", icss );                                                │
   │1575                if ( status != 0 ) 
```

**Comment by d-w-moore** [comment]
Watch this space for C++ and possibly Python examples for reproducing.

**Comment by trel** [comment]
Debugging session revealed a lack of 'commit' to close out the transaction from connection 1, blocking connection 2.

**Comment by d-w-moore** [comment]
Updated title and description since the issue manifested only when tickets were activated for both sessions. Also, it must be the same ticket, and not two different tickets offering access to the same data object.

**Comment by d-w-moore** [comment]
```
On single-node iRODS system:

as irods service account user, do:
        $ itouch '~/file_for_bob.txt'
        $ iticket create read '~/file_for_bob.txt' bob_ticket
        $ iticket mod bob_ticket uses 10000                     # <-- appears to be central; lockup doesnt reproduce without it.

as ubuntu user (auth'd to irods as user bob):

        $ git clone http://github.com/d-w-moore/python-irodsclient
        $ cd python_irodsclient
        $ git checkout demo_irods_issue_7250
        $ pip3 install -e .
        $ python3 ../irods7250.py -v -t bob_ticket /tempZone/home/rods/file_for_bob.txt                  # <-- locks up 
        $ python3 ../irods7250.py -v -g `hostname` -t bob_ticket /tempZone/home/rods/file_for_bob.txt    # <-- does not lock up 
```

**Comment by trel** [comment]
4.3.1-ish in this case means within ~25 commits of 4.3.1, but not yet released.

**Comment by korydraughn** [comment]
Just noting that triggering this does not require changing user accounts or being any particular type of user. It is the presence of the same ticket on two connections and the call to `rcGetHostFor*`.

The unit test in PR #7253 triggered the behavior using only the service account.
