### ISSUE TITLE
add API like GET_HOST_FOR_* but exposing resource hierarchy

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#7256]
- [x] add APIs (main)
- [x] add unit tests (main)
- [x] add APIs (4-3-stable)
- [x] add unit tests (4-3-stable)
## Feature

(* is GET or PUT).

For the PRC (and other clients), the hostname may not be enough information for directly connecting to the resource that hosts a data object. Once the client has created a connection to the correct server host, in accessing the data object we also need to apply the correct resource hierarchy keyword to prevent another potential redirect from there.

Suggest the new APIs be called `GET_RESCINFO_FOR_*`

**Comment by trel** [comment]
decision is to add a single new endpoint, and the operation be a keyword...

`GET_RESOURCE_INFO_FOR_OPERATION`

```
 GET_RESOURCE_INFO_FOR_OPERATION_KW - The OPERATION string: "CREATE", "WRITE", "OPEN", or "UNLINK".
```
