### ISSUE TITLE
NO_NEXT_RESC_FOUND when uploading data object using PRC if resource has minimum free space set

### ISSUE THREAD

**Issue by stsnel** [irods/irods#7275]
### iRODS Version, OS and Version

iRODS 4.2.12, on either CentOS 7 or Ubuntu 18.04 LTS
Python-irodsclient 1.1.8

### What did you try to do?

I am trying to upload a data object using Python-irodsclient:

```
# Boilerplate code to set up a session for the rods user account omitted

 with session.data_objects.open("/tempZone/home/rods/prc-with-max.txt", 'w') as obj_desc:
        obj_desc.write("foo".encode("utf-8"))
```

The resource tree looks like this:

```
demoResc:unixfilesystem
irodsResc:random
├── dev001_p1:passthru
│   └── dev001:unixfilesystem
└── dev002_p1:passthru
    └── dev002:unixfilesystem
```

The rods user `irods_environment.json`, as well as `core.re` have the default resource set to `irodsResc`.

Both unixfilesystem resources in the irodsResc tree have minimum free space set to 1 MB, and currently available space set to 100 GB:

```
vagrant@provider:~$ ilsresc -l dev001
resource name: dev001
id: 10019
zone: tempZone
type: unixfilesystem
location: provider.local
vault: /mnt/loop0/Vault
free space: 107374182400
free space time: 01692778116: 2023-08-23.08:08:36
status: 
info: 
comment: 
create time: 01692776843: 2023-08-23.07:47:23
modify time: 01692779275: 2023-08-23.08:27:55
context: minimum_free_space_for_create_in_bytes=1024768
parent: 10017
parent context: 

vagrant@provider:~$ ilsresc -l dev002
resource name: dev002
id: 10020
zone: tempZone
type: unixfilesystem
location: provider.local
vault: /mnt/loop1/Vault
free space: 107374182400
free space time: 01692778116: 2023-08-23.08:08:36
status: 
info: 
comment: 
create time: 01692776858: 2023-08-23.07:47:38
modify time: 01692779280: 2023-08-23.08:28:00
context: minimum_free_space_for_create_in_bytes=1024768
parent: 10018
parent context: 
```

### Expected behavior

Writing a 3-byte file using Python-irodsclient should succeed, since the amount of free space set for the resources is much more than the configured minimum space for creating data objects on the resources.

The `minimum_free_space_for_create_in_bytes` setting should affect all data object uploads in the same way, irrespective of whether one uses iCommands or Python-irodsclient.

### Observed behavior (including steps to reproduce, if applicable)

Running the Python script to upload the data object fails:

```
Traceback (most recent call last):
  File "./test-script.sh", line 106, in <module>
    with session.data_objects.open("/tempZone/home/rods/prc-with-max.txt", 'w') as obj_desc:
  File "/home/vagrant/.local/lib/python3.6/site-packages/irods/manager/data_object_manager.py", line 340, in open
    desc = conn.recv().int_info
  File "/home/vagrant/.local/lib/python3.6/site-packages/irods/connection.py", line 133, in recv
    raise get_exception_by_code(msg.int_info, err_msg)
  File "/home/vagrant/.local/lib/python3.6/site-packages/irods/exception.py", line 171, in get_exception_by_code
    exc_class = iRODSExceptionMeta.codes[ rounded_code( code ) ]
KeyError: -1805000

vagrant@provider:~$ ierror -1805000
irods error: -1805000 NO_NEXT_RESC_FOUND 
```

rodsLog says:

```
Aug 23 08:40:16 pid:15592 remote addresses: 10.0.2.15, 127.0.0.1 ERROR: [-]     /irods_source/server/core/src/irods_resource_redirect.cpp:165:irods::error (anonymous namespace)::request_vote_for_file_object(rsComm_t *, const std::string &, const std::string &, irods::file_object_ptr, std::string &, float &) :  status [NO_NEXT_RESC_FOUND]  errno [] -- message [failed in call to redirect host [provider.local]  hier [] vote [0]]
        [-]     /irods_source/plugins/resources/random/librandom.cpp:832:irods::error random_file_resolve_hierarchy(irods::plugin_context &, const std::string *, const std::string *, irods::hierarchy_parser *, float *) :  status [NO_NEXT_RESC_FOUND]  errno [] -- message [Failed getting next valid child.]
                [-]     /irods_source/plugins/resources/random/librandom.cpp:760:irods::error get_next_valid_child_resource(irods::plugin_context &, const std::string *, const std::string *, irods::hierarchy_parser *, float *) :  status [NO_NEXT_RESC_FOUND]  errno [] -- message [No valid child found.]

Aug 23 08:40:16 pid:15592 remote addresses: 10.0.2.15, 127.0.0.1 ERROR: [rsDataObjOpen_impl:919] - [NO_NEXT_RESC_FOUND: [-]     /irods_source/server/core/src/irods_resource_redirect.cpp:165:irods::error (anonymous namespace)::request_vote_for_file_object(rsComm_t *, const std::string &, const std::string &, irods::file_object_ptr, std::string &, float &) :  status [NO_NEXT_RESC_FOUND]  errno [] -- message [failed in call to redirect host [provider.local]  hier [] vote [0]]
        [-]     /irods_source/plugins/resources/random/librandom.cpp:832:irods::error random_file_resolve_hierarchy(irods::plugin_context &, const std::string *, const std::string *, irods::hierarchy_parser *, float *) :  status [NO_NEXT_RESC_FOUND]  errno [] -- message [Failed getting next valid child.]
                [-]     /irods_source/plugins/resources/random/librandom.cpp:760:irods::error get_next_valid_child_resource(irods::plugin_context &, const std::string *, const std::string *, irods::hierarchy_parser *, float *) :  status [NO_NEXT_RESC_FOUND]  errno [] -- message [No valid child found.]



] [error_code=[-1805000], path=[/tempZone/home/rods/prc-with-max.txt], hierarchy=[]
```

After increasing the debug level, the rodsLog says that the passthrough resources voted `original vote [0.0], weighted vote [0.0]` for the CREATE operation.

The passhthrough resources don't have a context string set. I can also reproduce this problem on an environment that has the default `pep_resource_resolve_hierarchy_pre` version from core.re.

Other things I have tried:
* Uploading a file using iput works as expected (no error message; data object ends up on irodsResc)
* Setting `minimum_free_space_for_create_in_bytes` to other values, such as `1` does not make uploads work when using PRC.
* After removing the minimum size for create from the unixfilesystem resources by setting their context to " " the upload using python-irodsclient works as expected (no error messages; data object ends up on irodsResc)

So the necessary conditions appear to be both using Python-irodsclient and setting `minimum_free_space_for_create_in_bytes` on unixfilesystem resources.

**Comment by trel** [comment]
also... related to https://github.com/irods/irods/issues/3841 ?

**Comment by stsnel** [comment]
I considered #3841 before submitting this issue, but I thought this was different, because I couldn't reproduce the issue we're seeing on our environments using `iput`. This issue is also not intermittent.

Creating a data object directly on a unixfilesystem resource that has `free_space` and `minimum_free_space_for_create_in_bytes` configured results in a `irods.exception.USER_FILE_TOO_LARGE` when using PRC. It looks like this is indeed a symptom of https://github.com/irods/irods/issues/7154 and https://github.com/irods/python-irodsclient/issues/462 . 

Thank you for the information 👍  Knowing the root cause, I think we will be able to work around it.

**Comment by trel** [comment]
Since #7154 is closed - closing this issue as well.

The workaround for using Python is to set the filesize to 0 when talking to a pre-4.3.1 iRODS server.

**Comment by stsnel** [comment]
Information for other people who encounter the same issue:

We ended up using the following solution for the time being: https://utrechtuniversity.github.io/yoda/design/processes/automatic-resource-balancing.html

It basically involves keeping track of which resources are (almost) full in a Redis key-value store. Our `pep_resource_resolve_hierarchy_pre` checks the resource information in Redis when a new data object is created, and changes votes so that new data objects get created on resources that have enough free space.

**Comment by kript** [comment]
Apologies for commenting on a closed Issue, but I just came across this and would it be possible to get some further clarification please?

 I _think_ that this affects *all* versions of iRODS before 4.3.1 but was introduced at least after 4.2.7 (since I've been able to use the PRC on a 4.2.7 system but not tried the most recent PRC version). It would be really good to know;

1. what version this got introduced in.
2. If the version of the PRC is related (i.e. can you use an earlier one? I think not but...)
3. If other API's (e.g. C) are affected.

@trel  does mention that

> The workaround for using Python is to set the filesize to 0 when talking to a pre-4.3.1 iRODS server.

However, the documentation for the PRC doesn't mention this as of a few minutes ago, and its not clear to me what affect setting the file size will have on other operations that might depend on it (e.g. it might try and create a file on a resource without sufficient space, or fail to recognise a partial upload?). Could we get an update to the PRC docs to mention this workaround please (especially if its only affecting the PRC, but even if it affects the other API's too).

Thanks!
