### ISSUE TITLE
Long running agents spawned via a connection pool do not see changes to resources

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#7287]
- [x] main
- [x] 4-3-stable
---
## Enhancement
The experimental iRODS HTTP API uses a connection pool to improve performance. The problem is what to do when a resource in the zone is modified.

When a resource is modified via icommands or any other client, agents which existed before the update never adjust their state to reflect the change. The only way to deal with this today is by shutting down the agent and spawning a new one (i.e. disconnect -> connect).

What we'd like is for the agents to automatically update when a resource changes, but we're a long way from that. For now, we can push this responsibility to the connection pool.

### Solution
Add the following options to the connection pool:
- `refresh_connections_after_n_retrievals`
    - An integer representing the max number of times a connection can be fetched from the pool before refreshing/replacing it
- `refresh_connections_after_resource_updates`
    - A boolean which instructs the connection pool to track the latest mtime across all resources
    - Each fetch of a connection causes the pool to check if the mtime has changed. If it has, then the connection is refreshed/replaced before handing to the caller

The connection pool already supports a refresh time, so we don't need to introduce a time-based option. However, we may consider moving the option into the options data type with the ones presented above.

**Comment by trel** [comment]
What are the defaults going to be set to for these two values?

**Comment by korydraughn** [comment]
- `refresh_connections_after_n_retrievals`
    - Data type is `std::optional<std::int16_t>`
    - Defaults to `std::nullopt` (not set)
- `refresh_connections_after_resource_updates`
    - Data type is `bool`
    - Defaults to `false`

Both options are disabled to maintain backwards compatibility.

**Comment by trel** [comment]
disabled?   does that mean...
- `refresh_connections_after_n_retrievals` will default to '0' or 'never' or 'off'?
- 'refresh_connections_after_resource_updates' will default to '0' or 'off' or 'no'?

**Comment by trel** [comment]
oh, you wrote the defaults.   ignore me.
