### ISSUE TITLE
Process stash 'erase_if' function should indicate number of elements removed

### ISSUE THREAD

**Issue by MartinFlores751** [irods/irods#7296]
- [x] main
- [x] 4-3-stable
---
## Feature

https://github.com/irods/irods/blob/21253de25be97fdc5ca6c458fab0759c0ee9cfc2/lib/core/src/process_stash.cpp#L59-L66

Currently, `process_stash::erase_if(...)` does not give any indication of elements being removed from the stash.

Consider returning the number of elements removed, which is returned by `std::erase_if`.

**Comment by korydraughn** [comment]
Don't forget to update the documentation once this change is implemented.

**Comment by trel** [comment]
Yes, this seems very nice and expected.

**Comment by MartinFlores751** [comment]
https://github.com/irods/irods/blob/21253de25be97fdc5ca6c458fab0759c0ee9cfc2/lib/core/src/process_stash.cpp#L53-L57

While working on the code, I noticed that we could update `process_stash::erase(...)` to return a boolean, indicating if an element was removed or not.

After a brief exchange, @korydraughn agreed we should update this function in this issue.

**Comment by alanking** [comment]
@MartinFlores751 - Please close if complete. Thanks
