### ISSUE TITLE
Consider adding new database column for storing the fractional part of R_RESC_MAIN.modify_ts

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#7303]
- [x] main
- [x] 4-3-stable
---
## Enhancement
This or some other solution needs to be implemented so the connection pool has a better chance at detecting changes to resources within the same second. The new column could be in milliseconds or microseconds.

The issue described happens when resources are modified via a script or some other automated tool.

See https://github.com/irods/irods_client_http_api/pull/82#issue-1881947566 for more details.

**Comment by trel** [comment]
you have a proposed name and type for this column?

**Comment by korydraughn** [comment]
The name I'm thinking of is something like the following:
- `modify_ts_fractional_millis`
- `modify_ts_millis`

I'm not tied to these names. They are just what come to mind on a first attempt.

The data type would be `varchar(3)` if we store milliseconds. It would be `varchar(6)` if microseconds is preferred.

The column would default to `'0'`.

**Comment by trel** [comment]
`modify_ts_millis` seems good to me - unless we go with microseconds.    I can't imagine a time when milliseconds will be insufficient, we're talking about network and api and database calls, not local memory reads and writes.

I think default `'000'` makes more sense than `'0'`.

**Comment by korydraughn** [comment]
I agree that milliseconds seem good enough.

Why `'000'`?

I'm starting to think using an integer would be better.

**Comment by trel** [comment]
these are on the right side of the decimal... so if you want to just concatenate...

**Comment by korydraughn** [comment]
I can't see a huge reason to use an integer so going with `varchar(3)` and `'000'` as a default.

**Comment by trel** [comment]
seems good.    let's see how it works and reserve the right to change our minds of course.
