### ISSUE TITLE
UseLibCXX.cmake: bump required CMake version

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7320]
- [ ] main
- [ ] 4-3-stable

-------

I was tipped off by https://github.com/irods/irods_rule_engine_plugin_python/issues/162#issuecomment-1719290143 that our version check in `UseLibCXX.cmake` is too low. We use the `LINK_LANGUAGE` generator expression, which was introduced in CMake 3.18.

**Comment by SwooshyCueb** [comment]
Looks like we're already doing version checks for 3.18:
https://github.com/irods/irods/blob/380184c5d9c35d13f575ef4abfd00264a970168b/cmake/Modules/UseLibCXX.cmake#L39
https://github.com/irods/irods/blob/380184c5d9c35d13f575ef4abfd00264a970168b/cmake/Modules/UseLibCXX.cmake#L61
And 3.8:
https://github.com/irods/irods/blob/380184c5d9c35d13f575ef4abfd00264a970168b/cmake/Modules/UseLibCXX.cmake#L80

**Comment by trel** [comment]
So the 3.8 check is sufficient?   That is less than 3.18?

**Comment by SwooshyCueb** [comment]
The checks should be sufficient to allow usage of this module all the way down to Cmake 3.6.

**Comment by trel** [comment]
Got it.  Clicked through and read more.
