### ISSUE TITLE
Unable to install irods-database-plugin-postgrescat

### ISSUE THREAD

**Issue by LIN810116** [irods/irods#7333]
### iRODS Version, OS and Version
iRODS: 4.3
OS: Ubuntu 20.04 amd64 5.4.0-162-generic

### What did you try to do?
I think I have added the key and repository to my apt list. I have done:
```
wget -qO - https://packages.irods.org/irods-signing-key.asc | sudo apt-key add -
echo "deb [arch=amd64] https://packages.irods.org/apt/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/renci-irods.list
sudo apt-get update
```
However, when I ran `sudo apt-get -y install irods-server irods-database-plugin-postgrescat`. I got an error saying `Unable to locate package irods-database-plugin-postgrescat`
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package irods-database-plugin-postgrescat
```
I think the irods-server was successfully installed, but the installation of irods-database-plugin-postgrescat failed.

```
apt list irods-server
Listing... Done
irods-server/focal,now 4.3.0-1~focal amd64 [installed]
```

Wondering if anyone has seen/experienced something similar before?

**Comment by korydraughn** [comment]
The database plugin name you're using is incorrect.

Try `irods-database-plugin-postgres`.

**Comment by LIN810116** [comment]
oh sorry, my silly mistake, it worked!!

@korydraughn Thank you so much for your super quick response
