### ISSUE TITLE
https://packages.irods.org/irods-signing-key.asc uses deprecated hash algorithm

### ISSUE THREAD

**Issue by alanking** [irods/irods#7349]
Making a note here that SHA1 has been deprecated in RHEL9, so our signing key can no longer be imported by `rpm`:
```bash
$ rpm --import https://packages.irods.org/irods-signing-key.asc
warning: Signature not supported. Hash algorithm SHA1 not available. 
error: https://packages.irods.org/irods-signing-key.asc: key 1 import failed.
```
Here is a suggestion elsewhere on how to update the keys: https://github.com/elastic/elasticsearch/issues/85876#issuecomment-1669726248

For now, there is a workaround:
```bash
$ update-crypto-policies --set LEGACY
$ rpm --import https://packages.irods.org/irods-signing-key.asc
```

_Originally posted by @alanking in https://github.com/irods/irods/issues/7191#issuecomment-1737989308_

**Comment by SwooshyCueb** [comment]
I'm shocked I haven't run into this while working on the development environment.

**Comment by SwooshyCueb** [comment]
My understanding is that this is how elasticsearch solved this issue without rotating keys: https://github.com/chrisberkhout/sha1-key-fix/blob/master/SHA1KeyFix.ipynb
(We already discussed this, just posting it here for my own benefit.)

**Comment by trel** [comment]
initial success on rocky9 (manipulate, import, compare, confirm).

cursory investigation says it's using `algo 8 / sha256` instead of `algo 10 / sha512`... unclear the reason...

**Comment by trel** [comment]
We updated the key within a day or so of the Oct 4 comment above.   Have had multiple releases since then - things seem to be solved/working.   Closing.

If seen again, we shall open a new issue with new information.
