### ISSUE TITLE
Proposal: .9x versioning for main branch

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7361]
This is one of two related proposals meant to address related problems.

At present, we increment the version number of the main branch to that of the next major release once it has diverged significantly from the current stable series branch. This means that the major release itself may not have a higher version number than a development build from the same branch from before the release. This poses a problem for packaging, as it may not result in a release taking priority over an older development build. In our stable series branches, we avoid this by incrementing version numbers just before release.

I am proposing that instead of incrementing to the next major release on significant divergence from stable, we follow the example set by Gnome and increment to a minor release with a value of .90 (ex: 4.3.90) and increment to the next major version just before release.

With this change to our versioning, downstream projects being developed side-by-side with iRODS will still have a version number to target, but we will not run into the version number precedent issue described above.

This change also comes with some additional benefits:
- If a downstream project that inherits iRODS' version number is built against the main branch rather than a release, it will be evident in the version number.
- When a user reports an issue with iRODS (or a downstream project that inherits iRODS' version number), we can tell from the version number whether they are using a development build from the main branch.

**Comment by trel** [comment]
This makes sense to me and I don't see any real downsides.

We could implement this *today* on main, I think, without any issues?   Thought experiments welcome.

**Comment by SwooshyCueb** [comment]
I think we should continue to track the version of the stable branch until main has diverged. AFAIK right now main and 4-3-stable are exactly or almost exactly the same in terms of content.

**Comment by trel** [comment]
I think that's where I am as well.

I think we wait until at least 4.3.1 is out before we touch this though...

**Comment by SwooshyCueb** [comment]
For 5.0, we can reclaim a dot, and do this for the stable branches as well, avoiding the need for even/odd versioning

**Comment by SwooshyCueb** [comment]
If we decide to move forward with .9x versioning (and it seems like we will), we should write our own CMake package version file template that will match .9x versions as belonging to the next major release (i.e. 4.4(/5.0) will match for downstream projects looking for a minimum of 4.3.90).

**Comment by trel** [comment]
Also want to note that the reclaiming of a dot is interesting/good for the .90 scenario... because the plugins don't need / can't use the extra dot (they're the end of the line, nobody is using them to build against).

**Comment by korydraughn** [comment]
And development builds (i.e. those that have .90 in the package name) are not a concern for the upgrade process.

Given we do not make development builds public via the package repository, there's no way for a user to accidentally install a development build without compiling it themselves. For that reason, the packaging is not required to handle upgrades from a development build.

**Comment by SwooshyCueb** [comment]
> And development builds (i.e. those that have .90 in the package name) are not a concern for the upgrade process.
> 
> Given we do not make development builds public via the package repository, there's no way for a user to accidentally install a development build without compiling it themselves. For that reason, the packaging is not required to handle upgrades from a development build.

I know this might seem pedantic, but I think I need to clarify some nuance on the off chance that we make decisions later based on our reasoning here.

In our discussion this morning, it wasn't decided that packaging shouldn't handle upgrades from from a development build to a later release in terms of version number comparison. Rather, it was discovered that it simply wouldn't be an issue, as reclaiming a dot allows us to use .9x development versions on both main *and* stable series branches *without the version number ever going backwards*.

**Comment by trel** [comment]
Yes - agreed.

.90 on main would be in the second slot and never cause an issue.  At least I think that would be the plan.

.90 on a stable branch would appear in the newly freed third slot (after 5.0).  As soon as a release happens on the stable branch, the second slot would move ahead and be ‘greater’ than the moments-before development version.

**Comment by korydraughn** [comment]
After some discussion, we've decided to make iRODS 5.0 the next major release.

This means the 4.4 milestone will be renamed to 5.0.

This decision enables the following:
- Completes our federation promise for compatibility with iRODS 3
- Allows us to start a new conversation about backwards compatibility
- Allows us to make improvements to packaging

**Comment by trel** [comment]
This is now... done?   As part of https://github.com/irods/irods/issues/7531?

Should we move this back to the 4.3.2 milestone as it has happened in this timeframe?

**Comment by korydraughn** [comment]
That sounds correct to me.

@SwooshyCueb Thoughts?

**Comment by SwooshyCueb** [comment]
Considering the first .9x version is for 5.0, I don't think it makes sense to put this in a 4.3.x milestone

**Comment by trel** [comment]
Ah, I see.

So, follow up question... is there more work to be done?   If not, can we close it in the 5.0.0 milestone?

**Comment by SwooshyCueb** [comment]
No, I think we can close it
