### ISSUE TITLE
CMake: Package version file

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7364]
~~We should include a CMake package version file with our CMake configuration files.~~ We already provide a CMake package version file, but it only matches exact version numbers:
https://github.com/irods/irods/blob/37321ca23dd4380e5880523820761b876c34f4c5/CMakeLists.txt#L282-L286

Let's change `ExactVersion` to `SameMinorVersion` This should allow us to use `find_package` with a minimum version of iRODS.
https://cmake.org/cmake/help/v3.11/module/CMakePackageConfigHelpers.html#generating-a-package-version-file

**Comment by SwooshyCueb** [comment]
I'm going to try and get this into 4.3.1, as it seems pretty trivial.

**Comment by trel** [comment]
Nice.   I thought that when I first clicked the link you provided...

**Comment by trel** [comment]
Please add two checkboxes.
