### ISSUE TITLE
`ibun` commands seems not triggering any pep?

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods#7378]
### iRODS Version, OS and Version
4.3.0, almalinux8

### What did you try to do?
I tried to capture some useful information (the object path, client information, user name etc.) when an `ibun` command is executed for both untarring and bundling/adding.

### Expected behavior
I expected to see some related PEPs to be triggered.

### Observed behavior (including steps to reproduce, if applicable)
No pep is triggered except `pep_api_struct_file_bundle_post`. This pep is triggered when a new object is added/bundled to a tar file, and it doesn't contain information about source and target.

```
[mustafa@dev-u0137480 ~]$ iput -Dtar test.tar
[mustafa@dev-u0137480 ~]$ ibun -x test.tar test_collection
[mustafa@dev-u0137480 ~]$ ibun -cDtar test2.tar test_collection
[mustafa@dev-u0137480 ~]$ ils
/u0137480/home/mustafa:
  test.tar
  test2.tar
  C- /u0137480/home/mustafa/test_collection
```

**Comment by trel** [comment]
The PEPs do fire - but there is no serialization information yet available (see https://github.com/irods/irods/issues/7413).

Closing this issue as resolved/invalid.
