### ISSUE TITLE
`istream read/write` doesn't trigger `pep_api_data_obj_open_*`

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods#7379]
### iRODS Version, OS and Version
4.3.0, almalinux8

### What did you try to do?
I tried to capture the object path when the `istream read/write` command is executed. 

### Expected behavior
I expected to see `pep_api_data_obj_open_*` is triggered. Or, depending on the read or write operation I expected to see both `pep_api_data_obj_read_*` and `pep_api_data_obj_write_*` contain the "obj_path" key.

### Observed behavior (including steps to reproduce, if applicable)
`pep_api_data_obj_read_*` and `pep_api_data_obj_write_*` are fired but dont not contain the object path info. Nor `pep_api_data_obj_open_*` is fired.

**Comment by korydraughn** [comment]
`istream` uses `pep_api_replica_open_*` and `pep_api_replica_close_*`.

`pep_api_data_obj_write_*` should be firing.

Give those a try and let us know what happens.

**Comment by mstfdkmn** [comment]
Thanks, indeed with my quick test `pep_api_replica_open_post` is fired by `istream read`.

**Comment by korydraughn** [comment]
Did you confirm `pep_api_data_obj_write_*` is firing?

**Comment by mstfdkmn** [comment]
Yes, I am confirming it is firing together with `pep_api_replica_open_post` when `istream write` is executed. Actually I should not have reported this because in another project I already used relevant PEPs for istream operations. So, this can be closed pls.

**Comment by mstfdkmn** [comment]
Hi, the API names (or index numbers) that the `istream read/write` commands contact is not available in https://github.com/irods/irods/blob/a020cff829247b939584437623a5ca950b72e363/lib/api/include/irods/apiNumberData.h. 

I see `pep_api_replica_open_post` includes `20003` as the api index number. Could you verify this?

Also I could not find a database peps triggered by istream operations. Is there one?
