### ISSUE TITLE
Setup script does not work for Postgres 15

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods#7382]
I inadvertently installed Postgres 15 on a debian 12 container.  The setup script failed with the following error:

```
pyodbc.ProgrammingError: ('42501', '[42501] ERROR: permission denied for schema public;\nError while executing the query (1) (SQLExecDirectW)')
```

It looks like I am running up against the change described here.  https://www.cybertec-postgresql.com/en/error-permission-denied-schema-public/

I know we are not yet supporting Postgres 15 but I am writing this so we know about the changes required when we do support it.

**Comment by trel** [comment]
good find.   date on that is nov 2022.
