### ISSUE TITLE
`pep_*_get_grid_configuration_value_*` not available in documentation

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods#7385]
### iRODS Version, OS and Version
4.3.0, almalinux8

### What did you try to do?
I see `pep_*_get_grid_configuration_value_*`  in the output of the iRODS Audit Rule Engine Plugin.

### Expected behavior
I expected to see these PEPs are documented in https://docs.irods.org/4.3.0/plugins/dynamic_policy_enforcement_points/

### Observed behavior (including steps to reproduce, if applicable)

Could this be documented? Also can you explain for what these can be used? Is it because `irods-grid` was removed by 4.3.0 or for the delay server? Thanks.

**Comment by alanking** [comment]
I think this is is a subset of https://github.com/irods/irods_docs/issues/212
