### ISSUE TITLE
test_password_extend_lifetime_set_to_false_invalidates_other_authentications_on_expiration can fail when run with the Python REP on Ubuntu 22.04 

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#7390]
- [x] main
- [x] 4-3-stable
---
## Bug Report
https://github.com/irods/irods/blob/97eb33f130349db5e01a4b85e89dd1da81460345/scripts/irods/test/test_pam_password_authentication.py#L563-L566

The assertion above sometimes fails with the following:
```
Level 0: Error occurred while authenticating user [irodsauthuser] [CAT_INVALID_AUTHENTICATION: failed to perform request
```

The failure feels very related to timing.

**Comment by trel** [comment]
sometimes it passes?   usually?

**Comment by korydraughn** [comment]
It's been passing, but there's no reason to think it can't fail because the test relies on sleeping to lead to certain assertions.

**Comment by trel** [comment]
ah, then most certainly your assessment is correct.

**Comment by alanking** [comment]
Even if I can reproduce this, I'm not sure if I can do anything about it. The test is inherently timing-based as it is testing for a password expiration. I would like to propose linking this issue with https://github.com/irods/irods/issues/7344 as it seems to be the cause of the problem.

A possible workaround for the time being would be to accept either error message in this test and fix it properly in #7344, putting back the correct assertions. See also: 
https://github.com/irods/irods/blob/06ed23911a6fc3f6f4a35d81cf917bfa3e366a1a/scripts/irods/test/test_pam_password_authentication.py#L328-L329
https://github.com/irods/irods/blob/06ed23911a6fc3f6f4a35d81cf917bfa3e366a1a/scripts/irods/test/test_pam_password_authentication.py#L454-L456
https://github.com/irods/irods/blob/06ed23911a6fc3f6f4a35d81cf917bfa3e366a1a/scripts/irods/test/test_pam_password_authentication.py#L570-L572
https://github.com/irods/irods/blob/06ed23911a6fc3f6f4a35d81cf917bfa3e366a1a/scripts/irods/test/test_native_authentication.py#L172-L173
https://github.com/irods/irods/blob/06ed23911a6fc3f6f4a35d81cf917bfa3e366a1a/scripts/irods/test/test_native_authentication.py#L265-L267
https://github.com/irods/irods/blob/06ed23911a6fc3f6f4a35d81cf917bfa3e366a1a/scripts/irods/test/test_native_authentication.py#L346-L348

**Comment by korydraughn** [comment]
Agreed. Let's move forward with your proposal.

**Comment by alanking** [comment]
The requirement for the test has been loosened so it should not fail on this message anymore. #7344 will address the underlying issue.
