### ISSUE TITLE
irods_performance2.pdf hyperlink in https://irods.org/faq/ cannot be found

### ISSUE THREAD

**Issue by yr-wang-hit** [irods/irods#7391]
irods faq irods_performance2.pdf hyperlink cannot be found: 
https://irods.org/faq/
``
How does iRODS transfer performance compare
with FTP or other protocol
For files larger than 32MB (by default, but configurable), iRODS uses multiple threads to transfer data in parallel. This provides iRODS with a significant speed advantage over FTP, which only uses a single thread for transfers. For transferring large files, iRODS can be comparable or even faster than GridFTP. Download [irods_performance2.pdf](https://openwiki.uninett.no/_media/norstore:irods:irods_performance2.pdf)
``

**Comment by trel** [comment]
Ah, good find.

The internet archive has one saved link...

https://web.archive.org/web/20180924230713/https://openwiki.uninett.no/_media/norstore:irods:irods_performance2.pdf

We'll get the website updated - thanks!

**Comment by trel** [comment]
Done!
