### ISSUE TITLE
After upgrade to iRODS 4.3.1 there are warnings about sql logging in the logfiles

### ISSUE THREAD

**Issue by cookie33** [irods/irods#7393]
### iRODS Version, OS and Version

iRODS 4.3.1
CentOS Linux release 7.9.2009 (Core)

### What did you try to do?

Upgrade iRODS 4.3.0 to iRODS 4.3.1

### Expected behavior

After starting iRODS no errors in the iRODS logfiles.

### Observed behavior (including steps to reproduce, if applicable)

The logfile shows following error:
```
{"log_category":"server","log_level":"warn","log_message":"Cannot get log level for log category [sql]. Defaulting to [info].","server_host":"irodstest1.xx.yy.zz","server_pid":23466,"server_timestamp":"2023-10-24T13:28:01.015Z","server_type":"agent","server_zone":"frank"}
```

This happens because the file: `/etc/irods/server_config.json` does not contain:
```
    "log_level": {
         ....
        "sql": "info"
    }, 
```
There is no line with the setting for `sql`.

please add it to the upgrade procedure. Or add it to the documentation to do this during the upgrade

After adding the line manually the error disappeared.

**Comment by trel** [comment]
Thanks!

The message is just a warning.

We'll include this in the documentation.

**Comment by trel** [comment]
Have updated the docs in https://github.com/irods/irods_docs/commit/70413688db92dbe4286d13145742ba37ef2fa1ff for #2790 

We do not plan to touch the configuration file directly for this setting.  The warning was designed to be sufficient for the administrator to correct the missing value.
