### ISSUE TITLE
Atomic ACLs API endpoint needs to consider the zone of the user

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#7408]
- [x] main
- [x] 4-3-stable
---
## Bug Report
The API endpoint needs to allow clients to pass the zone of the user to distinguish users with similar names. The new JSON structure should look like the following:
```
{
    "entity_name": "string",
    "zone": "string",
    "acl": "string"
}
```

Now the question becomes, should `zone` be optional or required?

If it's optional, then not providing the zone or passing an empty string should be treated as if the client passed the local zone. If zone is required, then it's an error to pass an invalid zone.

### Related
https://github.com/irods/irods/blob/27577616cad4c529625676e82ed96e9d3b14fe16/plugins/api/src/atomic_apply_acl_operations.cpp#L381

https://github.com/irods/irods/blob/27577616cad4c529625676e82ed96e9d3b14fe16/plugins/api/src/atomic_apply_acl_operations.cpp#L354-L367

**Comment by trel** [comment]
I’d say required… except that we’ve already shipped this for a while?

**Comment by korydraughn** [comment]
Because this has already shipped, it must be optional.

If the zone isn't provided, assume the local zone. If it is provided, use it for queries.

**Comment by korydraughn** [comment]
One thing we need to consider with this is how the inclusion of a zone argument will play with legacy iRODS server. Seems there might be a possibility for the ACLs of the wrong user (w/ identical username) to be updated when crossing over a federated boundary.

**Comment by korydraughn** [comment]
@FifthPotato Checkboxes are checked. Please close if complete.
