### ISSUE TITLE
Don't put libraries into `/usr/lib` if that's not where they go

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7410]
Related: #4232 

Currently, we install libraries and plugins into `/usr/lib` regardless of distribution. We should instead follow the standard practice for the distribution. For example, Debian/Ubuntu expects libraries and plugins to be in `/usr/lib/<triplet>` and EL expects `/usr/lib<qual>`.

**Comment by korydraughn** [comment]
Can you provide an example for `<triplet>` and `<qual>`?

**Comment by SwooshyCueb** [comment]
Some examples for Ubuntu/Debian:
`/usr/lib/x86_64-linux-gnu`
`/usr/lib/aarch64-linux-gnu`
`/usr/lib/s390x-linux-gnu`
`/usr/lib/riscv64-linux-gnu`
`/usr/lib/powerpc64le-linux-gnu`

Some examples for EL:
`/usr/lib64`
`/usr/lib32`
`/usr/libx32`
