### ISSUE TITLE
serialize StructFileExtAndRegInp in the rule engine framework

### ISSUE THREAD

**Issue by trel** [irods/irods#7413]
- [x] main
- [x] 4-3-stable
-----

## Feature

Tried to see the file information about a structfile getting extracted via `ibun -x` by using `pep_api_struct_file_ext_and_reg_post`.

in core.re:
>   writeLine("serverLog",*STRUCTINP);

Got this in the log...
>  {"log_category":"legacy","log_level":"info","log_message":"writeLine: inString = [StructFileExtAndRegInp*] not supported\n","request_api_name":"STRUCT_FILE_EXT_AND_REG_AN","request_api_number":665,"request_api_version":"d","request_client_user":"rods","request_host":"127.0.0.1","request_proxy_user":"rods","request_release_version":"rods4.3.1","server_host":"xxx.xxx.xxx.xxx","server_pid":560320,"server_timestamp":"2023-11-08T12:18:46.835Z","server_type":"agent","server_zone":"tempZone"}

The key part being ... `[StructFileExtAndRegInp*] not supported`

**Comment by trel** [comment]
This is a subset of https://github.com/irods/irods/issues/5955, I believe.

However, this structure was requested / hit directly by a member so I created a separate issue.

**Comment by trel** [comment]
This will help with both `ibun -c` AND `ibun -x`:
```
pep_api_struct_file_bundle_pre [StructFileExtAndRegInp*] not supported
pep_api_struct_file_ext_and_reg_pre [StructFileExtAndRegInp*] not supported
```

**Comment by korydraughn** [comment]
@FifthPotato Please close if completed.
