### ISSUE TITLE
re-remove resolveHostByDataObjInfo declaration

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7418]
- [x] main
- [x] 4-3-stable

-----------

Related: #3474

`resolveHostByDataObjInfo` hasn't been defined in many, many years, but the declaration stuck around for a while.
It was removed in b15dfaddca43d33d601044953de455138c456ecb in 2017, but later in 2021, it was re-added in b9ee67f818975f84cc0d4ae531602c0883eb714a.
Let's get rid of it again.

**Comment by korydraughn** [comment]
@SwooshyCueb Please close if completed.
