### ISSUE TITLE
Messages by python print in PEPs cannot be sent to standard output

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods#7420]
### iRODS Version, OS and Version
iRODS 4.3.1, almalinux8

### What did you try to do?
First of all I am not sure whether this is a bug report or not, or this should be here or in [this](https://github.com/irods/irods_rule_engine_plugin_python) repo.

I tried to print/stdout (send to irods' logs) a message when a pep is triggered.
### Expected behavior
Messages (a string) printed when a pep is fired be forwarded to the standard output, so I expected to see that messages in irods log.

### Observed behavior (including steps to reproduce, if applicable)
No message can be seen in irods log although a said pep is triggered. 

For example when the PEP below in core.py is triggered by an `iput` operation we expect to be able to see the text in iords' logs.
```
def pep_api_data_obj_put_post(rule_args, callback, rei):
    print(f"Hello, the zone - {rei.rsComm.proxyUser.rodsZone} - is being tested by put.")
```
Some input:
- We could see this text in irods logs in pre 4.3.1 irods release (at least in last 5 releases except 4.2.12).  I mean a text message was able to be sent to irods logs when the print function is called by a PEP.
- When a custom rule in core.py is called by "irule", the print function can still send messages to irods log.
```
def test_zone(rule_args, callback, rei):
    print(f"Hello, the zone - {rei.rsComm.proxyUser.rodsZone} - is being tested.")
```
`irule -r irods_rule_engine_plugin-python-instance test_zone null null
`
- The `writeLine` msi works as expected in the PREP,
```
def pep_api_data_obj_put_post(rule_args, callback, rei):
    callback.writeLine("serverLog", f"Hello, the zone - {rei.rsComm.proxyUser.rodsZone} - is being tested.")
```
I am wondering if this is something that you can also observe. It was easy to use while testing things with PEPs.

**Comment by korydraughn** [comment]
I've observed that `print` in 4.2.12 also results in messages appearing in the log _(this is expected)_.

The reason why the 4.2 series and 4.3 series differ is likely due to the daemonization of the server. In 4.2, the standard streams are redirected to the log file. In 4.3, we use syslog and redirect the standard streams to `/dev/null`.

This isn't a bug IMO.

The recommended way to handle this is by using `callback.writeLine`. To make things more convenient, you can wrap `callback.writeLine` in your own version of `print`.

**Comment by korydraughn** [comment]
You are correct. To invoke other rules, you have to use `callback`.

Closing.

**Comment by alanking** [comment]
I wonder if we need to update any READMEs to reflect this information (even if it's the information about all standard streams redirecting to `/dev/null` and a "let the reader understand")?

**Comment by korydraughn** [comment]
That sounds like a good idea for the PREP.

I'm not sure we need to document that for the main server since it's pretty normal for daemon processes to close the standard streams.

**Comment by alanking** [comment]
I created https://github.com/irods/irods_rule_engine_plugin_python/issues/180 for the documentation effort.
