### ISSUE TITLE
fails to create init service on CENTOS 8, 9

### ISSUE THREAD

**Issue by Cotagge** [irods/irods#7436]
## Bug Report
after install, post_install.sh is trying to run chkconfig, wich fails, up tu centos 6, there is no chkconfig. In centos 7 nad more, there is systemd services. In centos 7 it works so-so, but in 8 and 9, there is correct way to make systemd servie, not init.d/irods service.

# setup runlevels and aliases (use os-specific tools)
if [ "$DETECTEDOS" == "Ubuntu" ] ; then
    update-rc.d irods defaults
elif [ "$DETECTEDOS" == "RedHatCompatible" ] ; then
    /sbin/chkconfig --add irods
elif [ "$DETECTEDOS" == "SuSE" ] ; then
    /sbin/chkconfig --add irods
fi
### iRODS Version, OS and Version
Centos9 , irods 4.3.1

### What did you try to do?
try to install chkgconfig, which fails - know bug, so i follow guide at redhat, wich is just rm -rf /etc/init.d , then agains run install of chkconfig.

I've also tried to create /etc/systemd/system/irods/service  something like

[Unit]
Description=iRODS server

[Service]
ExecStart=/var/lib/irods/irodsctl start
ExecStop=/var/lib/irods/irodsctl stop
ExecReload=/var/lib/irods/irodsctl restart
User=irods
Group=irods
Restart=always

[Install]
WantedBy=multi-user.target

and systemctl daemon-reload, but it not works just with this

### Expected behavior

yum install irods , systemctl enable irods without error

**Comment by SwooshyCueb** [comment]
We do not currently install a systemd unit file. We have plans to in the future, but no ETA just yet.
There's a number of reasons we don't currently ship a unit file. One of the bigger and easier to explain reasons: our current setup process has the user pick the service account/group. That might not match what we put in the unit file. Having the setup script generate a unit file isn't a great idea either, as when we do eventually ship our own unit file, we'd have to figure out how to deal with existing unit files, and it wouldn't be pretty.
My current plan is to move us to a nginx-style package where we ship a default configuration and create default service account/group as part of package installation, and a systemd unit file that relies on these defaults. There's a lot of yak shaving between here and there though.

**Comment by trel** [comment]
related / part of https://github.com/irods/irods/issues/2774
