### ISSUE TITLE
Review server post-install script for EL7+

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7437]
- [x] main
- [x] 4-3-stable

-----

According to #7436, we're calling `chkconfig` on EL in the server post-install script, but `chkconfig` doesn't exist any more. Maybe we should be using `systemctl` instead, even though we still use an `init.d` script?

**Comment by cbcunc** [comment]
https://groups.google.com/g/irod-chat/c/uZpNuQn6ytw
