### ISSUE TITLE
modDataObjMeta ignores ADMIN_KW

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#7438]
## Bug Report

iRODS 4.3.1 
First observed here: https://groups.google.com/g/iROD-Chat/c/K6J5vIWpoic

### What did you try to do?

Use ADMIN_KW in the iRODS modDataObjMeta API.

### Expected behavior

The following code (using python-irodsclient), when run by a **rodsadmin**, would reasonably be expected to work ( ie force the catalog's `DATA_SIZE` column for the data object to a value of  8)
```
data_object = session.data_objects.get("/path/to/non_owned/data_object")
options = {    irods.keywords.ADMIN_KW: "" }
session.data_objects.modDataObjMeta(
    {"objPath": data_object.path},
    {"dataSize": 8},
    **options)
```

### Observed behavior (including steps to reproduce, if applicable)
The call results in `irods.exception.CAT_NO_ACCESS_PERMISSION` and fails to change DATA_SIZE for the data object, regardless of the use of `ADMIN_KW`.

In any case, if the above code is run by a **rodsadmin** having ownership of the targeted data object, the code does succeed in changing DATA_SIZE to the desired value.  (A normal rodsuser gets SYS_NO_API_PRIV, also as expected.)

**Comment by d-w-moore** [comment]
> What you're describing works using `iadmin modrepl`. The admin does not need permissions on the object to change replica information. I was able to create a new data object as **john** (i.e. a rodsuser) and then change the replica information as **rods** (i.e. a rodsadmin) without needing to change permissions.
> 
> The icommand requires the user to pick a specific replica. Have you tried including a replica number or resource hierarchy in your test?

They're different api's altogether,  I think... so, not sure that would work. But if true it sounds like we should deprecated modDataObjMeta

**Comment by d-w-moore** [comment]
I see now that `iadmin modrepl` does call `rcModDataObjMeta`.  So, I"ll check into it further and see what errors might be in the iRODS server log when we fail to update the data object.

**Comment by trel** [comment]
Yes, same call - so same effects should be possible via PRC.

**Comment by alanking** [comment]
I was able to modify the system metadata on a user's data object as a rodsadmin by running the following:
```python
>>> from irods.session import iRODSSession
>>> with iRODSSession(irods_env_file='/var/lib/irods/.irods/irods_environment.json', **dict()) as session:
...     data_object = session.data_objects.get('/tempZone/home/alan/foo')
>>> data_object.id
10018
>>> data_object.size
100
>>> with iRODSSession(irods_env_file='/var/lib/irods/.irods/irods_environment.json', **dict()) as session:
...     session.data_objects.modDataObjMeta({"objPath": data_object.path}, {"dataSize": 8, "irodsAdmin": "yes"})
>>> with iRODSSession(irods_env_file='/var/lib/irods/.irods/irods_environment.json', **dict()) as session:
...     data_object = session.data_objects.get('/tempZone/home/alan/foo')
... 
>>> data_object.id
10018
>>> data_object.size
8
```

The ADMIN_KW needs to go into the `meta_dict`, *not* the `**options` parameter. The `**options` parameter is placed inside the `condInput` for the `DataObjInfo`, but the `ADMIN_KW` used by the API comes out of the `regParam`.

Here's the definition of the PRC call, for reference:
https://github.com/irods/python-irodsclient/blob/ed2e73cb79dcf08efedeed4a19f3e2a43db90f9c/irods/manager/data_object_manager.py#L679-L728

Therefore, modDataObjMeta is honoring the ADMIN_KW when passed in through the correct dict.
