### ISSUE TITLE
Voting for write should prefer good replicas

### ISSUE THREAD

**Issue by alanking** [irods/irods#7476]
- [x] main
- [x] 4-3-stable
- [x] irods_docs
---
Currently, hierarchy resolution for the `irods::WRITE_OPERATION` prefers stale replicas:
https://github.com/irods/irods/blob/29f4802edf1066fe10d6654289838743aa2e0803/server/core/src/voting.cpp#L214-L217

This was done this way to get around the limitation in the replication API that does not allow replicating over top of a good replica (see https://docs.irods.org/4.3.1/system_overview/data_objects/#replicate) and the way that interacts with certain situations in a replication resource hierarchy. In order for write operation voting to prefer good replicas, the rules of replication need to change in order to accommodate.

This implies a change in the linked documentation, so I'm going to put the documentation tag on this.

Maybe closely linked to https://github.com/irods/irods/issues/6940 as well...

**Comment by trel** [comment]
The main use case for this change is appending to an existing data object.  Appending or truncating a stale replica could lead to data loss.

**Comment by alanking** [comment]
Appending to objects will be tested as part of #7475, I imagine. Closing.
