### ISSUE TITLE
irods setup fails with MySQL ODBC connector 8.1-8.3

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7495]
irods setup fails when using the MySQL ODBC driver version 8.1.0 or greater:
```
...
Executing SQL statement:
select R_OBJECTID_nextval();
with the following parameters:
()
Executing SQL statement:
insert into R_ZONE_MAIN values (?,?,'local','','',?,?);
with the following parameters:
(0, 'tempZone', '01707768185', '01707768185')
Executing SQL statement:
select R_OBJECTID_nextval();
with the following parameters:
()
Executing SQL statement:
insert into R_USER_MAIN values (?,?,?,?,'','',?,?);
with the following parameters:
(0, 'public', 'rodsgroup', 'tempZone', '01707768185', '01707768185')
Executing SQL statement:
select R_OBJECTID_nextval();
with the following parameters:
()
Executing SQL statement:
insert into R_USER_MAIN values (?,?,?,?,'','',?,?);
with the following parameters:
(0, 'rods', 'rodsadmin', 'tempZone', '01707768185', '01707768185')
Executing SQL statement:
insert into R_USER_GROUP values (?,?,?,?);
with the following parameters:
(0, 0, '01707768185', '01707768185')
Executing SQL statement:
insert into R_USER_GROUP values (?,?,?,?);
with the following parameters:
(0, 0, '01707768185', '01707768185')
Rolling back database changes...
Error encountered running setup_irods:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/database_connect.py", line 251, in execute_sql_statement
    return cursor.execute(statement, params)
pyodbc.IntegrityError: ('23000', "[23000] [MySQL][ODBC 8.3(w) Driver][mysqld-8.3.0]Duplicate entry '0-0' for key 'R_USER_GROUP.idx_user_group1' (1062) (SQLExecDirectW)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/irods/scripts/setup_irods.py", line 523, in main
    setup_server(irods_config,
  File "/var/lib/irods/scripts/setup_irods.py", line 134, in setup_server
    database_interface.setup_catalog(irods_config, default_resource_directory=default_resource_directory, default_resource_name=default_resource_name)
  File "/var/lib/irods/scripts/irods/database_interface.py", line 27, in setup_catalog
    database_connect.setup_database_values(irods_config, cursor, default_resource_directory=default_resource_directory, default_resource_name=default_resource_name)
  File "/var/lib/irods/scripts/irods/database_connect.py", line 429, in setup_database_values
    execute_sql_statement(cursor,
  File "/var/lib/irods/scripts/irods/database_connect.py", line 253, in execute_sql_statement
    six.reraise(IrodsError,
  File "/var/lib/irods/scripts/irods/six.py", line 671, in reraise
    raise value.with_traceback(tb)
  File "/var/lib/irods/scripts/irods/database_connect.py", line 251, in execute_sql_statement
    return cursor.execute(statement, params)
irods.exceptions.IrodsError: pyodbc encountered an error executing the statement:
        insert into R_USER_GROUP values (?,?,?,?);
('23000', "[23000] [MySQL][ODBC 8.3(w) Driver][mysqld-8.3.0]Duplicate entry '0-0' for key 'R_USER_GROUP.idx_user_group1' (1062) (SQLExecDirectW)")
Exiting...
```

This has been observed with a post-#7485 build of irods in the following environments:
- Ubuntu 22.04 container with MySQL 8.0.36 from the MySQL apt repos running in the same container, using the MySQL ODBC driver 8.1.0 from the MySQL apt repos
- Ubuntu 22.04 container with MySQL 8.0.36 from the MySQL apt repos running in the same container, using the MySQL ODBC driver 8.2.0 from the MySQL apt repos
- Ubuntu 22.04 container with MySQL 8.0.36 from the MySQL apt repos running in the same container, using the MySQL ODBC driver 8.3.0 from the MySQL apt repos
- Ubuntu 22.04 container with MySQL 8.0.29 from docker hub running in a separate container, using the MySQL ODBC driver 8.3.0 from the MySQL apt repos
- Ubuntu 22.04 container with MySQL 8.3.0 from docker hub running in a separate container, using the MySQL ODBC driver 8.3.0 from the MySQL apt repos
- Ubuntu 22.04 container with MariaDB 10.6.17 from docker hub running in a separate container, using the MySQL ODBC driver 8.3.0 from the MySQL apt repos

**Comment by korydraughn** [comment]
Looks like a sequence number issue.

**Comment by SwooshyCueb** [comment]
So it seems like this might not be a problem with 8.4, as I did not run into any problems with setup when testing a testing environment project I'm making for 8.4. So far I've only tested with Debian 12. If this is indeed only a problem with 8.1, 8.2, and 8.3, I'd say we can just document that iRODS is incompatible with these versions of the ODBC connector and call it a day, since they're not (supposed to be) GA, much less LTS.
I'll do some more testing.

**Comment by SwooshyCueb** [comment]
Further testing confirms that iRODS seems to work just fine with version 8.4 of the ODBC plugin and MySQL 8.4 or 8.0.
Attempting to set up iRODS with version 8.4 of the ODBC plugin pointed at a MariaDB server doesn't work, so until we get iRODS working with the MariaDB ODBC driver, MariaDB users will need to stick with version 8.0 of the MySQL ODBC driver.

I'm going to run the full test suite against MySQL 8.4, if it passes, I think we should document that iRODS is not compatible with MySQL 8.1, 8.2, or 8.3, and test against 8.4 for some distros for the 4.3.3 release. Thoughts?

**Comment by korydraughn** [comment]
8.1-8.3 will be EOL this year, correct? If so, then yeah, stating they aren't supported sounds reasonable.

Just so it's clear, are you referring to ODBC drivers which ship with the distro or ones provided by Oracle?

Looks like the MySQL downloads page doesn't list 8.1-8.3 under GA, which is even more reason to not worry about those versions.

**Comment by SwooshyCueb** [comment]
> 8.1-8.3 will be EOL this year, correct? If so, then yeah, stating they aren't supported sounds reasonable.
>
> Looks like the MySQL downloads page doesn't list 8.1-8.3 under GA, which is even more reason to not worry about those versions.

Yeah, to my understanding, they weren't ever meant for use in production and no updates are planned.

> Just so it's clear, are you referring to ODBC drivers which ship with the distro or ones provided by Oracle?

I don't think any of the distros we support ship the MySQL ODBC driver. I've been getting them from Oracle/MySQL.
