### ISSUE TITLE
CMake: administration object library linkage to nlohmann-json should probably be public

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7508]
The object libraries defined in `lib/administration` link to `nlohmann_json::nlohmann_json`, but they do so using `PRIVATE`:
https://github.com/irods/irods/blob/e6df49f58759d6609650b82ce4a907d82ee10881/lib/administration/resource/CMakeLists.txt#L12-L16
https://github.com/irods/irods/blob/e6df49f58759d6609650b82ce4a907d82ee10881/lib/administration/ticket/CMakeLists.txt#L11-L15
https://github.com/irods/irods/blob/e6df49f58759d6609650b82ce4a907d82ee10881/lib/administration/user/CMakeLists.txt#L12-L16
https://github.com/irods/irods/blob/e6df49f58759d6609650b82ce4a907d82ee10881/lib/administration/user/CMakeLists.txt#L47-L53
https://github.com/irods/irods/blob/e6df49f58759d6609650b82ce4a907d82ee10881/lib/administration/zone/CMakeLists.txt#L12-L16

This is likely a mistake. If it is not, the reason for the `PRIVATE` linkage should be documented.

**Comment by SwooshyCueb** [comment]
Given that the headers never include or reference nlohmann-json, `PRIVATE` is correct.

**Comment by alanking** [comment]
> If it is not, the reason for the PRIVATE linkage should be documented.

Should we leave comments in the actual CMakeLists files explaining why they are `PRIVATE` before we close this?

**Comment by SwooshyCueb** [comment]
> > If it is not, the reason for the PRIVATE linkage should be documented.
> 
> Should we leave comments in the actual CMakeLists files explaining why they are `PRIVATE` before we close this?

Might be a good idea, yeah
