### ISSUE TITLE
`test_pam_password_authentication` fails in high-concurrency situations

### ISSUE THREAD

**Issue by alanking** [irods/irods#7522]
- [ ] main
- [ ] 4-3-stable

---

I have observed `test_pam_password_authentication` failing when concurrently running alongside other tests on my workstation.

This is yet another manifestation of #6954, as per usual. Interestingly, and much like #7521, it never recovers. Normally, I wouldn't mind this so much but it does cause all of the following tests (with no observed recovery) to fail.

I suspect it has a high probability of occurring in this test due to the high number of times the server is required to restart as configuration values are changed.

**Comment by alanking** [comment]
Oh, forgot to note that the test passes consistently when run at the bench in a clean environment. Not sure if there's much to do here, but wanted to capture it in an issue.

**Comment by korydraughn** [comment]
Having this issue is good enough for now. I'm hopeful that iRODS 5.0 resolves this or helps unveil the issue.

**Comment by korydraughn** [comment]
Sounds good.

**Comment by alanking** [comment]
I haven't observed this in some time, so I'm going to close this as not planned. We can open a new issue if it reappears.
