### ISSUE TITLE
Bump version number

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7531]
With irods/irods_api_plugin_genquery2#92 and irods/irods_client_http_api#259, we now have downstream projects that sniff for version 4.3.1, as tip of main and tip of 4-3-stable have diverged enough to warrant conditionals in the buildsystem.

The 4-3-stable branch should be bumped to 4.3.2.
The main branch should be bumped to 4.90.0, as the next major release will be 5.0.

We have a number of downstream projects that specify `EXACT` when calling `find_package(IRODS`. They will need to be changed to not pass `EXACT`.

**Comment by alanking** [comment]
I believe we need to do some of this work for indexing as well. Not sure if that was in the plans or not, but just writing it down here.

**Comment by korydraughn** [comment]
Yes. Once my PRs land in indexing, @SwooshyCueb will be free to update things as needed.

**Comment by alanking** [comment]
Don't forget to update indexing when the time comes. Should we open issues in that repo for this and possibly an equivalent to #7220?

**Comment by SwooshyCueb** [comment]
I was planning on taking care of that as part of #7265

**Comment by alanking** [comment]
Okay, sounds good.

**Comment by korydraughn** [comment]
Given that the indexing plugin is lagging behind the other projects, I think it's fine to link against #7265 since it covers many things.
