### ISSUE TITLE
Adjust CMake package version file for new versioning scheme and .9x versions

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7532]
First, a quick recap of some decisions that we made regarding iRODS version numbers.

The next major release of iRODS is going to be 5.0.

Prior to iRODS 5.0, major releases incremented the second part of the version number, and minor releases incremented the third part. For example, 4.3.0 was a major release, and 4.3.1 was a minor release of 4.3.
Starting with iRODS 5.0, major releases will increment the first part of the version number, and minor releases will increment the second part. For example, 5.0 will be a major release, and 5.1 will be a minor release of 5. We may even decide to have patch releases; 5.0.1 would be a patch release of 5.0.

We have also decided to use .9x version numbers for development builds of iRODS. For example, 4.97 would be a development version between 4.3 and 5.0, and 5.92 would be a development version between 5 and 6.0.
Starting with iRODS 5.0, this will extend to minor releases as well. For example, 5.1.94 would be a development version between 5.1 and 5.2.0.

Thusly, our CMake package version file needs to be adjusted to account for the changes in versioning.

Requirements for the new CMake package version file:
- An iRODS installation should match as exactly compatible if the find_package()-calling project is searching for the exact same version.
- An iRODS installation should match as compatible if the find_package()-calling project is searching for a version range containing the version of the iRODS installation.
- An iRODS installation without a .9x version should match as potentially compatible if the find_package()-calling project is searching for an earlier version of the same major release or a .9x version of the previous major release.
- An iRODS installation with a .9x version in the second part of the version number should match as potentially compatible if the find_package()-calling project is searching for the next major release or any earlier version of the same major release.
- An iRODS installation with a .9x version in the third part of the version number should match as potentially compatible if the find_package()-calling project is searching for the next minor release or any earlier version of the same major release.

Some examples:
- An iRODS installation of version 4.3.2 should match as potentially compatible when a project is searching for
    - any 4.3.x version earlier than or equal to 4.3.2
- An iRODS installation of version 4.3.2 should NOT match as potentially compatible when a project is searching for
    - any 4.2.x version or earlier
    - any version newer than 4.3.2
- An iRODS installation of version 5.3 should match as potentially compatible when a project is searching for
    - any 4.9x version
    - any 5.x version earlier than or equal to 5.3
- An iRODS installation of version 5.3 should NOT match as potentially compatible when a project is searching for
    - any version earlier than 4.90
    - any version newer than 5.3
- An iRODS installation of version 5.0 should match as potentially compatible when a project is searching for
    - any 4.9x version
    - 5
- An iRODS installation of version 5.0 should NOT match as potentially compatible when a project is searching for
    - any version earlier than 4.90
    - any version newer than 5.0
- An iRODS installation of version 4.93 should match as potentially compatible when a project is searching for
    - any 4.3.x version
    - any 4.9x version earlier than or equal to 4.93
    - 5
- An iRODS installation of version 4.93 should NOT match as potentially compatible when a project is searching for
    - any 4.9x version newer than 4.93
    - or any version later than 5.0. including minor versions like 5.1 or patches like 5.0.1
- An iRODS installation of version 5.97 should match as potentially compatible when a project is searching for
    - any 5.x version earlier than or equal to than 5.97
    - 6
- An iRODS installation of version 5.97 should NOT match as potentially compatible when a project is searching for
    - any 5.x version newer than 5.97
    - or any version later than 6.0 including minor versions like 6.1 or patches like 6.0.1
- An iRODS installation of version 5.0.92 should match as potentially compatible when a project is searching for
    - any 5.0.x version earlier than or equal to than 5.0.92
    - 5.1
- An iRODS installation of version 5.0.92 should NOT match as potentially compatible when a project is searching for
    - any 5.0.x version newer than 5.0.92
    - or any version later than 5.1 including patches like 5.1.1

**Comment by trel** [comment]
amazing.


> - An iRODS installation of version 5.3 should match as potentially compatible when a project is searching for
>    - any 4.9x version

is this correct?

**Comment by SwooshyCueb** [comment]
> > * An iRODS installation of version 5.3 should match as potentially compatible when a project is searching for
> >   
> >   * any 4.9x version
> 
> is this correct?

Yes. 4.9x is development version of 5. If 5.0 matches for 5.3, so should 4.9x.

**Comment by trel** [comment]
got it.    i think.   i'm sure i'll ask again with the same example in 6-8 months.
