### ISSUE TITLE
deprecate GeneralUpdate API endpoint

### ISSUE THREAD

**Issue by trel** [irods/irods#7554]
- [x] main
- [x] 4-3-stable
---
Before removing GeneralUpdate in #2956 - we need to declare it deprecated.

Need discussion/investigation about what will get removed and if there is any calling code within the server.

**Comment by alanking** [comment]
> NTS: Investigate deprecating `rxGeneralRowInsert` and `rxGeneralRowPurge` as well.


Do we have an issue or issues for this?

**Comment by korydraughn** [comment]
We don't. Will create. Thanks for the reminder.
