### ISSUE TITLE
Absorb GenQuery2 parser into iRODS server

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#7570]
- [x] main
- [x] 4-3-stable
---
## Enhancement

The first step to replacing the original GenQuery parser is to make it available in the next release of iRODS. This means the following:
- Exposing a new API endpoint
- Exposing new microservices
- Adding options to `iquest` to allow use of the new parser
    - Or, providing a new icommand (i.e. `iquery`)

The new parser would exist as an alternative to GenQuery1 until the issues are worked out.

All APIs would continue to use GenQuery1.

This work would result in the GenQuery2 repo being archived.

**Comment by korydraughn** [comment]
This work is now complete.

For those running GenQuery2 built from https://github.com/irods/irods_api_plugin_genquery2, you need to do the following before upgrading to 4.3.2.
- Uninstall the GenQuery2 package
- Remove the GenQuery2 rule engine plugin from your server_config.json
    - iRODS 4.3.2 does not require the need for a rule engine plugin
- Replace all calls to the GenQuery2 microservices with the 4.3.2 variants

If this isn't done, the upgrade process will halt and report conflicts with the GenQuery2 package. This is intentional and serves as a means for telling the admin they need to examine their deployment.

Use of the GenQuery2 repo/package with 4.3.2 and later should be avoided.

**Comment by alanking** [comment]
I'm guessing we will add something like that to the release notes?

**Comment by korydraughn** [comment]
Absolutely.
