### ISSUE TITLE
`msiSetKeyValuePairsToObj` doesn't trigger `pep_api_mod_avu_metadata_*`

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods#7574]
### iRODS Version, OS and Version
4.3.1, almalinux8

### What did you try to do?
I set metadata by `msiSetKeyValuePairsToObj`. I  tried it both via a PEP and via a .r file.

### Expected behavior
I expected to see `pep_api_mod_avu_metadata_*` are triggered.

### Observed behavior (including steps to reproduce, if applicable)
Metadata is attached but the said PEP is not triggered.

An example for core.py:
```
def pep_api_data_obj_put_post(rule_args, callback, rei):
    callback.writeLine("serverLog", f"{rule_args[2].dataSize}")
    avu = callback.msiString2KeyValPair("mg.usage.data.bytes" + "=" + f"{rule_args[2].dataSize}", irods_types.KeyValPair())["arguments"][1]
    callback.msiSetKeyValuePairsToObj(avu, "/u0137480/home/projectA", "-C")

def pep_api_mod_avu_metadata_post(rule_args, callback, rei):
    callback.writeLine("serverLog", f"pep_api_mod_avu_metadata_post")
```

**Comment by trel** [comment]
This is working as expected.

Microservices within the iRODS server will not trigger API PEPs - you're not traversing that boundary into iRODS, you're already inside.

**Comment by alanking** [comment]
Related discussion (different microservice) here: https://github.com/irods/irods/issues/7496

**Comment by korydraughn** [comment]
Closing.
