### ISSUE TITLE
Setup iRODS Consumer with no local resource

### ISSUE THREAD

**Issue by 0x010C** [irods/irods#7590]
- [x] main
- [x] 4-3-stable

---

### iRODS Version, OS and Version
iRODS 4.3.1 on Debian 12

### What did you try to do?
I wanted to setup a new iRODS Consummer without any local resource. So after installing irods-server package, I run the setup_irods.py script, choosing "no" when asked for a "Local storage on this server" and giving my already existing resource for the "Default resource".
```
$ sudo /var/lib/irods/scripts/setup_irods.py
iRODS user [irods]:
iRODS group [irods]:
iRODS server's role:
1. provider
2. consumer
Please select a number or choose 0 to enter a new value [1]: 2
Local storage on this server [yes]: no
Default resource [demoResc]: mainResc
...
```

### Expected behavior
I would have expected the script to setup an iRODS server configured without a local resource.

### Observed behavior (including steps to reproduce, if applicable)
```
Traceback (most recent call last):
  File "/var/lib/irods/scripts/setup_irods.py", line 537, in <module>
    sys.exit(main())
             ^^^^^^
  File "/var/lib/irods/scripts/setup_irods.py", line 523, in main
    setup_server(irods_config,
  File "/var/lib/irods/scripts/setup_irods.py", line 141, in setup_server
    irods.lib.execute_command(['iadmin', 'mkresc', default_resource_name, 'unixfilesystem', ':'.join([irods.lib.get_hostname(), default_resource_directory]), ''])
                                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 1: expected str instance, NoneType found
```
Note that using the non-interactive --json_configuration_file option of setup_irods.py, if the "default_resource_directory" field is left empty the result is the same.

**Comment by trel** [comment]
Hmm, interesting - that definitely should work.  We'll work to reproduce this ASAP.

**Comment by alanking** [comment]
I was able to reproduce this. I'll post a fix here so that you can modify the setup script in order to proceed. It will of course be included in 4.3.2 as well.

**Comment by alanking** [comment]
We just need to check for `NoneType` on `default_resource_directory` before attempting to create local storage. This is how `setup_storage()` returns the fact that the user answered "no" (or... rather, anything other than "yes" or "y", case-insensitive) to the question about "Local storage on this server". Here's the diff that fixed it for me:
```diff
diff --git a/scripts/setup_irods.py b/scripts/setup_irods.py
index da9b7ef2d..0aad6dd4a 100755
--- a/scripts/setup_irods.py
+++ b/scripts/setup_irods.py
@@ -137,7 +137,10 @@ def setup_server(irods_config, json_configuration_file=None, test_mode=False):
     IrodsController(irods_config).start(test_mode=test_mode)
 
     # create local storage resource for consumer (provider was configured directly in database_interface.setup_catalog above)
-    if irods_config.is_consumer:
+    if irods_config.is_consumer and default_resource_directory is not None:
         irods.lib.execute_command(['iadmin', 'mkresc', default_resource_name, 'unixfilesystem', ':'.join([irods.lib.get_hostname(), default_resource_directory]), ''])
 
     # update core.re with default resource
```

Let us know if that resolves the issue.

**Comment by 0x010C** [comment]
@alanking Using your patched version of setup_irods.py, it works now as expected (executing it manually or with the non-interactive --json_configuration_file option). Thanks :)

**Comment by alanking** [comment]
Thanks for the confirmation, @0x010C!
