### ISSUE TITLE
Add usage examples to writeLine() doxygen comments.

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods#7630]
- [x] main
- [x] 4-3-stable
---

Add usage examples to writeLine() doxygen comments.

Possible example:

```
\code{.py}
writeLine("stdout", "This shows up on stdout");
writeLine("stderr", "This shows up on stderr");
writeLine("serverLog", "This shows up in the server log");
writeLine("/tempZone/home/alice/foo", "This is written to the data object /tempZone/home/alice/foo, I guess");
\endcode
```

Not sure if this should follow a `\usage` tag or if the .py should be updated to .re.  (Guessing .py would format it correctly but is a little confusing.)

**Comment by korydraughn** [comment]
In newer/updated APIs, we've used `\b Example` to label example code. See dataObjChksum.h for an example.

Doxygen doesn't know what `.re` is so we chose `.py` since it gives us code highlighting and python code highlighting fit the NREP pretty well.

**Comment by alanking** [comment]
@JustinKyleJames - Checkbox and close if complete. Thanks

**Comment by JustinKyleJames** [comment]
Closing
