### ISSUE TITLE
Log becomes noisy when logger falls back to default log level

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#7687]
- [x] main
- [x] 4-3-stable

## Enhancement

When a log instruction is executed, it looks for a specific log category for additional information. If the target log category isn't defined in server_config.json under `/log_level`, the logger writes a warning to the log file about it missing and then proceeds to use the `info` log level for the message.

This creates a lot of unnecessary noise in the log file for something the admin may not care about.

Let's change the warning to a trace level message. That way, the log stays quiet.

**Comment by alanking** [comment]
Is `trace` a little *too* hidden? Maybe `debug`?

**Comment by trel** [comment]
or just pull the 'warning' down to 'info' itself?

**Comment by alanking** [comment]
Oh, I misread the issue. Yes, `info` seems appropriate, too

**Comment by korydraughn** [comment]
- `debug` is for viewing information such as input/output values of APIs, etc
- `info` is the default log level for new installations, so the message would still appear if that is used

The log message that is produced due to the lack of a log category isn't that helpful. It could be removed entirely.

I don't think it offers that much benefit to the admin, but setting it to `trace` seemed appropriate given the reasons above.

How do you feel about removing the log message entirely?

The behavior of the logger would then be a documentation exercise. We may already include documentation about the fallback behavior.

**Comment by korydraughn** [comment]
If `info` is what we want, that means we have to change the default log level to `warn` to get the desired outcome.

Thoughts?

**Comment by trel** [comment]
> to get the desired outcome

you're defining the desired outcome as 'not as noisy as today'... right?

i think the logger is doing its job - letting the admin know that there is a config that is not complete and how to 'fix' it.  it's noisy, but i think that's... okay?  it will only be 'noisy' after a config is changed to be incorrect/missing or an upgrade is performed and the config is no longer in a complete state.

without this information getting to the admin... the config is likely to stay incomplete for longer.

**Comment by korydraughn** [comment]
Yes, that is all true.

The issue has more to do with the introduction of the GenQuery2 API. Right now, tip of main/4-3-stable does not contain any logic for adding the missing genquery2 log category. As a result, each use of the GenQuery2 API will cause the logger to print the warning about the missing log category.

The warning message was added to encourage the admin to add the missing log categories. Keep in mind, a missing log category is not an error. The iRODS server will simply use default values. That made me wonder how useful the warning message actually is. Because the logger handles the situation gracefully, why should the admin care about a missing log category?

Now if we decide to leave the logger as is _(which is fine)_, we're back to considering a schema version change or modifying the setup script to add the missing property regardless of an upgrade. The question then becomes ... should setup always add missing configuration properties?

**Comment by trel** [comment]
> we're back to considering a schema version change or modifying the setup script to add the missing property regardless of an upgrade

I'm not sure ... this is true?   Why do we have to touch anything?    The admin will (most probably) see the newly noisy logs, and quickly update the config after an upgrade.   New installs will have the config (I think?  They certainly *should*).

We could definitely bump the schema, but... that's a 'lot' of work for no substantial/breaking change?

**Comment by korydraughn** [comment]
> I'm not sure ... this is true? Why do we have to touch anything? The admin will (most probably) see the newly noisy logs, and quickly update the config after an upgrade.

We don't have to do anything. The server has fallback logic and will run just fine. It just feels weird/incomplete to release a new version of the server and require the admin to touch up the config following an upgrade.

> New installs will have the config (I think? They certainly should).

According to the plan at https://github.com/irods/irods/pull/7672#issuecomment-2051765888, new installs will have the configuration option.

> We could definitely bump the schema, but... that's a 'lot' of work for no substantial/breaking change?

I agree.

Given what's been said so far and after re-reading the plan in the linked comment, I think the original plan is still a good approach.

@trel Are you having second thoughts about it?

**Comment by korydraughn** [comment]
Reminder created at #7700.

**Comment by korydraughn** [comment]
Closing this. Going to link to the GenQuery2 API issue for the server_config.json.template change.
