### ISSUE TITLE
status of irodsDelayedServer not shown.

### ISSUE THREAD

**Issue by DOC-MEX** [irods/irods#7692]
## Feature

- Please describe the feature you are requesting and your use case.
When requesting the status using irodsctl, I get a response onlt from the irodsServer, but the IrodsDelayed server is not being shown. What does that mean?  

sudo su irods -c "/var/lib/irods/irodsctl status"
**irodsServer :**
  Process 4754
  Process 4755

olvera@opendata-20:~$ ienv
irods_version - 4.3.1
irods_session_environment_file - /home/olverac/.irods/irods_environment.json.9323
irods_environment_file - /home/olverac/.irods/irods_environment.json
irods_host - opendata-20
irods_port - 1247
irods_zone_name - tempZone
irods_user_name - user1

olvera@opendata-20:~$ ils
/tempZone/home/user1:

I have installed irods before and usually, when I check the status I get something like this:|
irodsServer :
  Process 3040
  Process 3041
irodsDelayServer :
  Process 3058

### iRODS Version, OS and Version
4.3.1 Ubuntu 20

### What did you try to do?
restart service

**Comment by korydraughn** [comment]
What does `iadmin get_delay_server_info` print to the terminal?

What does `hostname` print to the terminal for the iRODS server?

**Comment by DOC-MEX** [comment]
Yes that was the problem!  _iadmin get_delay_server_info_ showed a slightly different name to the _hostname_ command. 
It seems that was something added by the admin of the network to the file /etc/hosts  when he created the VM I'm using. I requested to setup the machine with only one name, and   I can see the irodsDelayServer  when I check the status.
