### ISSUE TITLE
Consider using `sigaction` instead of `signal` for setting up signal handlers

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7748]
We use `signal()` to set up our signal handlers in `rodsServer.cpp`:
https://github.com/irods/irods/blob/e4b4e8a7266360bb38ee97d7f2eda69249567dff/server/main_server/src/rodsServer.cpp#L521-L530
We should consider using `sigaction` instead: https://stackoverflow.com/a/232711/6278710

**Comment by SwooshyCueb** [comment]
duplicate of #6731

**Comment by korydraughn** [comment]
This has been handled by #7988.

Let's leave the signal handling as is for the 4-3-stable branch.

Closing.
