### ISSUE TITLE
Add functionality for disabling certain signal handlers for debugging

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7750]
We install signal handlers to dump stack traces if the agent factory process crashes.
https://github.com/irods/irods/blob/e4b4e8a7266360bb38ee97d7f2eda69249567dff/server/core/src/irods_signal.cpp#L83-L98
This is good, and in my opinion we should be doing this sort of thing in more places. However, this functionality should be able to be switched off entirely, as it overrides any signal handlers injected by `LD_PRELOAD`ed debug-assist libraries.

I think the most straightforward way to implement this is to check an environment variable before installing the signal handlers.

**Comment by trel** [comment]
> we should be doing this sort of thing in more places

I thought we had it in the 'one' place we needed it.  Are there others?

**Comment by SwooshyCueb** [comment]
> > we should be doing this sort of thing in more places
> 
> I thought we had it in the 'one' place we needed it. Are there others?

As far as I'm aware, only the agent factory sets a signal handler for `SIGSEGV`. I think this carries forward to the agents themselves since they're `fork`ed, but grandpa doesn't have any handling for `SIGSEGV`.

**Comment by trel** [comment]
Ah - gotcha.   Thanks.
