### ISSUE TITLE
Disable-by-default `irodsServerMonPerf`

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7760]
- [x] main
- [x] 4-3-stable

---

`msiServerMonPerf` is a microservice that invokes `irodsServerMonPerf`, a *perl* script that hasn't seen a lot of love in recent years. Unless I'm mistaken, this is the only perl in the entire irods project. It's very stinky, and has very little documentation as to what it does, how it works, how to use it, etc. It can also be broken in various ways that cause `msiServerMonPerf` to fail silently.

Let's consider taking one or more of the following actions:
- Deprecate `msiServerMonPerf` in 4.3 and remove both `msiServerMonPerf` and `irodsServerMonPerf` in 5.0.
- Replace `msiServerMonPerf` and/or `irodsServerMonPerf` with something better.
- Disable `msiServerMonPerf` by default.

**Comment by trel** [comment]
At minimum, we will move `irodsServerMonPerf` to be a template file (off by default).

**Comment by alanking** [comment]
`irodsServerMonPerf` is now disabled by default. #7757 and #7842 will address issues with the script and microservice. Closing this one.
