### ISSUE TITLE
`irods_server_properties.cpp`: ambiguous calls to `log_server::debug`

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7768]
The function `irods::server_properties::reload` in `irods_server_properties.cpp` has two logging calls at the end:
https://github.com/irods/irods/blob/e4b4e8a7266360bb38ee97d7f2eda69249567dff/lib/core/src/irods_server_properties.cpp#L294-L296

Newer versions of clang throw an error for both of these calls:
```
/irods/lib/core/src/irods_server_properties.cpp:294:9: error: call to object of type 'const impl<level::debug>' is ambiguous
  294 |         log_server::debug("Before patch ==> {}", [this] { return std::make_tuple(config_props_.dump()); });
      |         ^~~~~~~~~~~~~~~~~
/irods/lib/core/include/irods/irods_logger.hpp:487:18: note: candidate function [with Args = <(lambda at /irods/lib/core/src/irods_server_properties.cpp:294:50)>]
  487 |             auto operator()(fmt::format_string<Args...> _format, Args&&... _args) const -> void
      |                  ^
/irods/lib/core/include/irods/irods_logger.hpp:581:18: note: candidate function [with _invocable:auto = (lambda at /irods/lib/core/src/irods_server_properties.cpp:294:50)]
  581 |             auto operator()(const std::string_view _format, std::invocable auto&& _invocable) const -> void
      |                  ^
/irods/lib/core/src/irods_server_properties.cpp:296:9: error: call to object of type 'const impl<level::debug>' is ambiguous
  296 |         log_server::debug("After patch ==> {}", [this] { return std::make_tuple(config_props_.dump()); });
      |         ^~~~~~~~~~~~~~~~~
/irods/lib/core/include/irods/irods_logger.hpp:487:18: note: candidate function [with Args = <(lambda at /irods/lib/core/src/irods_server_properties.cpp:296:49)>]
  487 |             auto operator()(fmt::format_string<Args...> _format, Args&&... _args) const -> void
      |                  ^
/irods/lib/core/include/irods/irods_logger.hpp:581:18: note: candidate function [with _invocable:auto = (lambda at /irods/lib/core/src/irods_server_properties.cpp:296:49)]
  581 |             auto operator()(const std::string_view _format, std::invocable auto&& _invocable) const -> void
      |                  ^
2 errors generated
```

**Comment by SwooshyCueb** [comment]
GCC 11+ and Clang 15+ both exhibit this behavior when building against libstdc++.
(libc++ has not been evaluated yet)

Adding `requires (sizeof...(Args) != 1 || !std::is_invocable_v<std::tuple_element_t<0, std::tuple<Args...>>>)` to the declaration of the [first overload](https://github.com/irods/irods/blob/e4b4e8a7266360bb38ee97d7f2eda69249567dff/lib/core/include/irods/irods_logger.hpp#L486-L493) of `irods::experimental::log::logger::impl::operator()` appears to fixe the problem for Clang 16+ and all versions of GCC. However, with this change, Clang 15 and earlier will throw an error.

Small demonstration: https://godbolt.org/z/PGrzsjs35 (comment and uncomment line 22)

We might have to add a/some specialization(s) in order to make Clang 15 happy, or we can just declare irods incompatible with Clang 15.

I have also not mapped out how different Clang and libstdc++ version combinations might play into this, but I think it is unlikely that it makes any difference.

**Comment by korydraughn** [comment]
Which OS will this be an issue for? I'm trying to determine whether this should be in one of the 4.3.x milestones.

**Comment by SwooshyCueb** [comment]
> We might have to add a/some specialization(s) in order to make Clang 15 happy, or we can just declare irods incompatible with Clang 15.

I've been playing around with this.
The workaround would have to be overload-based, not specialization-based, as function template specializations must be full, not partial.
And I think I've found a workable solution https://godbolt.org/z/a9jj5dzn8

> Which OS will this be an issue for? I'm trying to determine whether this should be in one of the 4.3.x milestones.

If we were to switch to distro-provided clang today, this would affect Ubuntu 22.04, 24.04, EL8, EL9, and Debian 12.

**Comment by korydraughn** [comment]
Concepts to the rescue!

**Comment by korydraughn** [comment]
On line 36 of the potential solution, when is `__clang__ == 0` true?

**Comment by SwooshyCueb** [comment]
When being built with a different compiler, such as gcc

**Comment by SwooshyCueb** [comment]
Here's the fix in my PR https://github.com/irods/irods/pull/7771/commits/48f9356de5f5452d1c6df197c8dbbe8d1ec3e012
