### ISSUE TITLE
Automating Data Removal

### ISSUE THREAD

**Issue by GokulVijayakumarRam** [irods/irods#7772]
I have an iRODS 4.3.1 running in an ubuntu 22.04 server.

We are continuously adding data to the server.
Along with the required data we have some intermediate data that we need to remove periodically.
Is there any methods or suggestions to setup a cronjob kind of function, that will parse through all the folders inside irods, identify the unwanted files using pattern matching and remove them every month?

Please let me know if this is possible

Thanks and regards 
Gokul

**Comment by trel** [comment]
Looks identical to the thread here...  https://groups.google.com/g/irod-chat/c/j-C6JXon19g


Yes, you can write a rule to do anything you want in the system.   And put it into the delay queue to run forever.

https://docs.irods.org/4.3.1/plugins/pluggable_rule_engine/

https://docs.irods.org/4.3.1/doxygen/reDataObjOpr_8cpp.html#ab42c46a53d55d454da12f7a5376ba974

You could write this rule in the iRODS Rule Language or Python.
