### ISSUE TITLE
large files do not transfer well between 4.2.8 and 4.2.9+

### ISSUE THREAD

**Issue by iychoi** [irods/irods#7798]
Hi, 

I'm using icommands 4.3.0.

When copying a file larger than 2GB using `icp` fails with following error.
```
ubuntu@irodsfs-test:/data$ icp /iplant/home/iychoi/test_2GB.bin /iplant/home/iychoi/tt/test_2GB.bin
remote addresses: 206.207.252.46 ERROR: cpUtil: cp error for /iplant/home/iychoi/tt/test_2GB.bin, status = -27000 status = -27000 SYS_COPY_LEN_ERR
```

However, `iput` worked correctly.

The file I tried has 2147483648 bytes which is 1 byte larger than int max (2147483647). So I guess `signed int32` data type was used in offset/size calculation in the iRODS API for copying. This is just my guess.

Thanks,
Illyoung Choi

**Comment by trel** [comment]
Yes, this feels like a pre-4.2.9 vs post-4.2.9 world are different enough in this case that this is not something we can fix here.

Considering closing as no action seems plausible.   Except perhaps an issue rename to provide better context.

**Comment by korydraughn** [comment]
Agreed. I think this should be renamed and closed.

**Comment by trel** [comment]
renamed.  closing.
