### ISSUE TITLE
`constexpr` function `is_irods_error_category` in `system_error.cpp` calls non-`constexpr` function `std::error_code::category()`

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7808]
The function `is_irods_error_category` in `system_error.cpp` is defined in an anonymous namespace as such:
https://github.com/irods/irods/blob/6d1637f6e5c48620abd075871da0cf46d5abb1e6/lib/core/src/system_error.cpp#L17-L20
It is a `constexpr` function, however, it calls [`std::error_code::category()`](https://en.cppreference.com/w/cpp/error/error_code/category), which is *not* `constexpr`. My understanding is that this means that calls to this function cannot be evaluated at compile-time, which defeats the purpose of `constexpr`.

**Comment by korydraughn** [comment]
Agreed. Let's drop that `constexpr`.
