### ISSUE TITLE
Logger timestamp generation needs some love

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7812]
While waiting on new externals to land in the package repositories, I decided to try building irods with gcc, to see if anything has changed since the last time I tried. The (unrelated to this issue) huge number of `-Wchanges-meaning` warnings coming from `irods_logger.hpp` got me looking at how we might consolidate the many specializations of `irods::experimental::log::logger_config` (also unrelated to this issue), and the timestamp generation function caught my attention.
https://github.com/irods/irods/blob/6d1637f6e5c48620abd075871da0cf46d5abb1e6/lib/core/include/irods/irods_logger.hpp#L621-L646

I'm not a fan of this implementation.

It first tries to populate a `std::timespec`, and then turns the seconds value from that into a `std::chrono::duration`, which it then turns into a `std::chrono::time_point`, which it then turns into a `std::time_t`, which it then turns into a `std::tm*`. It then formats that to YYYY-mm-ddTHH:MM:SS by writing to a `std::stringstream` using `std::put_time`. Then, to get the milliseconds, it turns the nanoseconds value from the `std::timespec` into another `std::chrono::duration`, which it then casts to a different kind of `std::chrono::duration`. Then, it uses fmt to combine the `std::string` generated from the `std::stringstream` with the tick count from that last `std::chrono::duration` (formatting it so that it pads out to three digits).
If it *fails* to populate the `std::timespec`, it falls back to a completely `<chrono>`-based implementation. It fetches the current `std::chrono::time_point` from `std::chrono::system_clock`, immediately reduces it to second-precision by turning it into a `std::time_t`, and turns that into a `std::tm*`. As before, it uses a `std::stringstream` to format the `std::tm*` via `std::put_time`, but this time it fills in the missing milliseconds with zeros.

Defaulting to a `std::timespec`-based solution is definitely the way to go, as a `<ctime>`-based solution is definitely more efficient than just about anything else available to us at present. However, any performance we gained, we throw away with the needless type conversions, the `std::stringstream`-based formatting, and the involvement of `<chrono>`. The fallback `<chrono>`-based implementation has its own set of problems, though. It tosses away the high precision data from the `std::chrono::system_clock` and again uses `std::stringstream`-based formatting.

After playing with [various single-path implementations](https://godbolt.org/z/vTG94E7Tv), I think I've come up with a [decent improvement](https://godbolt.org/z/T6Torhcvx). If fmt 10+ is available at compile-time, a very simple `<chrono>`- and fmt-based implementation will be used. Otherwise, an improved `<ctime>` implementation will be used. The new implementation tries twice to populate the `std::timespec` using different methods. It then `static_casts` the seconds value directly to a `std::time_t` and calculates the millisecond value from the nanosecond value using arethmetic. The `std::time_t` gets turned into a `std::tm*`, which is formatted into a preallocated buffer via `std::strftime`. The buffer and the millisecond value are then used to get the final timestamp, similar to how the previous implementation does.
Should both methods of populating the `std::timespec` fail, it falls back to a `<chrono>`-based implementation that preserves millisecond-level precision.

I'll get this in a PR soon.

**Comment by trel** [comment]
would be very cool to have timing/speed measurements before and after.

also, timing a timestamp is fun.

**Comment by SwooshyCueb** [comment]
> would be very cool to have timing/speed measurements before and after.

See the godbolt links

**Comment by trel** [comment]
oh wow.   an order of magnitude faster, almost across the board.    very nice.

**Comment by SwooshyCueb** [comment]
> oh wow. an order of magnitude faster, almost across the board. very nice.

Yes indeed, and I bet I can make it even faster if I can get all the formatting done in a single `fmt` call for each path.

**Comment by korydraughn** [comment]
Very nice.

**Comment by SwooshyCueb** [comment]
The references to this issue today can be ignored, was meant for #7821
