### ISSUE TITLE
Regression: Replication fails for users in groups with permissions on data object but with no permissions for the user itself

### ISSUE THREAD

**Issue by alanking** [irods/irods#7816]
- [x] main
- [x] 4-3-stable

---

### iRODS Version, OS and Version
4.3.2

### What did you try to do?
Give `modify_object` permission to a group - let's call it `group_a`. As a user - let's say `alice` - with no permissions on the object but is a member of `group_a`, attempt to replicate the data object to another resource.

### Expected behavior
Replication occurs successfully.

### Observed behavior (including steps to reproduce, if applicable)
Replication fails with error `SYS_USER_NO_PERMISSION`.

This is due to a permissions check in the replication API which assumes that because `alice` has no permissions on the data object, `alice` cannot replicate the data object. The permissions check needs to take `alice`'s groups into account as well. Here is the check:
https://github.com/irods/irods/blob/cf4744ecd539f3ea3847f957d8d1121a468100d9/server/api/src/rsDataObjRepl.cpp#L480-L536

This behavior changed as a result of addressing #7444 and #7465.

Thanks to @deanlinssen for the help in finding this.

**Comment by trel** [comment]
So we didn't have a test for this case...    good find!
