### ISSUE TITLE
Engine rules applied to incorrect icommand.

### ISSUE THREAD

**Issue by DOC-MEX** [irods/irods#7818]
## Feature

Tests using default rule engine. 

### iRODS Version, OS and Version
irods_version - 4.3.2, Ubuntu 22

### What did you try to do?
added two rules to add metada when using iput and ireg:

```
acPostProcForPut {
    *A = $objPath;
    msiGetSystemTime(*Time, "unix");
    *formattedTime = timestrf(datetime(double(*Time)), "%Y-%m-%d");

    writeLine("serverLog", "-A file has been uploaded using IPUT: *A");

    *attribute = "submission_date";
    *value = *formattedTime;
    *AVU = *attribute ++ "=" ++ *value;
    msiString2KeyValPair(*AVU, *KVP);

    msiAssociateKeyValuePairsToObj(*KVP, *A, "-d");
    writeLine("serverLog", "(IPUT) Metadata successfully added to *A");
}
```

```
acPostProcForFilePathReg {
    *A = $objPath;
    msiGetSystemTime(*Time, "unix");
    #writeLine("serverLog", "Debug: Time = *Time");

    *formattedTime = timestrf(datetime(double(*Time)), "%Y-%m-%d");
    #writeLine("serverLog", "Debug: formattedTime = *formattedTime");

    writeLine("serverLog", "An item has been REGISTERED: *A");

    *attribute = "REGISTRATION_date";
    *value = *formattedTime;
    *AVU = *attribute ++ "=" ++ *value;
    #writeLine("serverLog", "Debug before msiString2KeyValPair: *AVU = *AVU");

    msiString2KeyValPair(*AVU, *KVP);
    msiAssociateKeyValuePairsToObj(*KVP, *A, "-d");
    writeLine("serverLog", "(IREG) Metadata successfully added to *A");
}
```

### Expected behavior
Execute acPostProcForPut rule when the iput is used,  or execute acPostProcForFilePathReg when ireg is used.

### Observed behavior (including steps to reproduce, if applicable)

when I use iput I can see in the logs messages and in the metadata check that the 2 rules were applied instead only one.
```
iput test.txt
imeta ls -d test.txt
AVUs defined for dataObj /zone_C/home/grassroots/test.txt:
attribute: REGISTRATION_date
value: 2024-06-18
units: 

attribute: submission_date
value: 2024-06-18
units: 

```
This problem does not occured when I only test "ireg" like this
```
ireg /home/olverad/test_REGISTER.txt /zone_C/home/grassroots/test_REGISTER.txt
 imeta ls -d test_REGISTER.txt 
AVUs defined for dataObj /zone_C/home/grassroots/test_REGISTER.txt:
attribute: REGISTRATION_date
value: 2024-06-18
```

So the question is why the rule for **acPostProcForFilePathReg** is executed when I use **iput**?

**Comment by trel** [comment]
This is expected behavior and functioning as designed.

A put of a file into an iRODS namespace involves two steps:
 1. data movement into managed storage, and then
 2. registration into the catalog

A registration of an existing file into an iRODS namespace only performs the second step.

**Comment by DOC-MEX** [comment]
I see! that makes sense. Thank you for the clarification.
