### ISSUE TITLE
Change log message from notice/info level to debug/trace level for GenQuery1 ticket setup

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#7820]
- [x] main
- [x] 4-3-stable
---
## Enhancement
The following line is triggered every time the ticket API is invoked. This happens on nearly every API operation for the HTTP API and it doesn't provide much value. The log level for this message should be changed to debug or trace.
https://github.com/irods/irods/blob/cf4744ecd539f3ea3847f957d8d1121a468100d9/plugins/database/src/general_query.cpp#L2306

**Comment by trel** [comment]
definitely.   since it has a value in it, feels like debug.
