### ISSUE TITLE
Centos 7 builds failing due to mirrorlist.centos.org shutting down

### ISSUE THREAD

**Issue by alanking** [irods/irods#7865]
- [x] GitHub Actions (main)
- [x] GitHub Actions (4-3-stable)
- [x] irods_development_environment
- [x] irods_testing_environment

---

Centos 7 builds have been failing in GitHub Actions for a few days now because apparently mirrorlist.centos.org has been shut down. This can be worked around by updating repository configurations to ignore the mirrorlist. See https://serverfault.com/a/1161847 for additional details.

We need to update at least the following things to ignore mirrorlist.centos.org:
 - GitHub Actions builder for Centos 7 in this repo
 - The core builder and plugin builder for Centos 7 in the development environment
 - The Dockerfile common to the Centos 7 Compose projects in the testing environment

**Comment by SwooshyCueb** [comment]
I'll see if I can't fix this today
