### ISSUE TITLE
`pep_api_obj_stat_*`  is fired only by `ils`

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods#7899]
### iRODS Version, OS and Version

4.3.2, almalinux8

### What did you try to do?
I am trying to capture status information of objects when triggered by a query policy.

### Expected behavior
Expected to see `pep_api_obj_stat_*` are invoked by queries executed over clients.

### Observed behavior (including steps to reproduce, if applicable)
That is triggered only by the `ils` command and it is fired always two times.

**Comment by trel** [comment]
What client command did you run where you expected to see a `stat` API call?

**Comment by mstfdkmn** [comment]
Any commands that will list the content of a collection. That is;
- `walk()` method in the PRC
- `gocmd ls` from the go commands
- sftp

Anyways I think this is not the correct PEP I need to use in my policy implementation. Thanks.

**Comment by trel** [comment]
Okay - so I think there is nothing to do here for now.  Closing.
