### ISSUE TITLE
`pep_api_gen_query_*` is continuously being fired by delayServer

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods#7901]
### iRODS Version, OS and Version
4.3.2, almalinux8

The delay server agent continuously triggers `pep_api_gen_query_*`. Is this normal/expected?

**Comment by korydraughn** [comment]
That's expected for the most part because the delay server is a client that relies on genquery to fetch the list of delay rules to execute.

Are you seeing something unusual?

**Comment by mstfdkmn** [comment]
Ah okay that is how he delay server captures delay rules.

> Are you seeing something unusual?

No I was thinking to use this PEP but not aware that it is linked to queries made for all entities (more than collection and data objects).
