### ISSUE TITLE
Document MariaDB compatibility situation

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7905]
At present, we do support MariaDB, but not the MariaDB ODBC driver. We should document this, and the recommended character set, collation, etc configuration for MariaDB.

I'm putting this in the 4.3.3 milestone, but it is not a blocker for testing.

**Comment by korydraughn** [comment]
This issue needs to remain open until we confirm the tests pass using the proposed character set and collation.

**Comment by alanking** [comment]
To be explicitly clear, the MariaDB projects in the testing environment are using configurations which match the documentation in irods/irods_docs#271: https://github.com/irods/irods_testing_environment/commit/b75ae8b95a03890269888a95e5b52029904455fe So, those pieces are in place.

**Comment by korydraughn** [comment]
@SwooshyCueb Please close if completed.
