### ISSUE TITLE
Add support for remaining permission levels to atomic ACLs API

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#7913]
- [x] main
- [x] 4-3-stable
---
## Enhancement

The `rx_atomic_apply_acl_operations` API needs to accept the following permissions, just like `ichmod`:
- read_metadata
- read_object
- create_metadata
- modify_metadata
- delete_metadata
- create_object
- modify_object
- delete_object

**Comment by alanking** [comment]
Boxes checked. @FifthPotato - Please close if complete. Thanks
