### ISSUE TITLE
Null access on a collection doesnt block users seeing sub collections and their sub items 

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods#7924]
### iRODS Version, OS and Version
4.3.2, almalinux8

### What did you try to do?
I removed all available permissions on a collection.

### Expected behavior
Users should not able to see items on which they have enough permissions in that collection.

### Observed behavior (including steps to reproduce, if applicable)
Users cannot see the data objects that they have permission (any level - read/write/own) whereas they can see collections that they have permission (any level).

what rodsadmin sees:
```
[irods@dev-u0137480 irods]$ ils -A /u0137480/home/projectA/collA
/u0137480/home/projectA/collA:
        ACL -
        Inheritance - Disabled
  testfile
        ACL - mustafa#u0137480:own
  C- /u0137480/home/projectA/collA/jef
```
```
[irods@dev-u0137480 irods]$ ils -A /u0137480/home/projectA/collA/jef
/u0137480/home/projectA/collA/jef:
        ACL - rods#u0137480:own   mustafa#u0137480:modify_object
        Inheritance - Disabled
  rules_global_vsc.py
        ACL - mustafa#u0137480:read_object
```

what rodsuser sees:

collection that the user has null access and its data objects;
```
[mustafa@dev-u0137480 ~]$ ils /u0137480/home/projectA/collA
remote addresses: 10.0.2.100 ERROR: lsUtil: srcPath /u0137480/home/projectA/collA does not exist or user lacks access permission
[mustafa@dev-u0137480 ~]$ ils /u0137480/home/projectA/collA/testfile
remote addresses: 10.0.2.100 ERROR: lsUtil: srcPath /u0137480/home/projectA/collA/testfile does not exist or user lacks access permission
```

sub-items;
```
[mustafa@dev-u0137480 ~]$ ils /u0137480/home/projectA/collA/jef
/u0137480/home/projectA/collA/jef:
  rules_global_vsc.py
```

I think users should be able to encounter the same principle always; either should not see the sub collection in the collection on which they have null access level or they should be able to see the data objects in that collection. Which one do you think is a bug? Or this is an expected behavior? Could you try to reproduce this (to eliminate any possible impact of our policies in case there is)?

**Comment by korydraughn** [comment]
First, `/u0137480/home/projectA/collA/rules_global_vsc.py` does not exist.

The behavior you're seeing is intentional/expected.

Access to collections and data objects is enforced by the immediate parent collection. Not ancestor collections.

**Comment by mstfdkmn** [comment]
> First, /u0137480/home/projectA/collA/rules_global_vsc.py does not exist.

Yes I had realized it and already corrected above, that was a wrong copy/paste

> Access to collections and data objects is enforced by the immediate parent collection.

Thanks. It looks a bit confusing but okay. I was thinking if you don't have access to a directory in a path you should not be able to list sub items of that directory. (For instance here `/a/b/c/data`, the simple logic says if I cannot access to "b" then I should not see the "c/data" because when I don't have access to "c", I cannot see "data").

This could be please closed.
