### ISSUE TITLE
`iput -k` doesn't populate checksum info in relevant PEPs triggered

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods#7936]
### iRODS Version, OS and Version
4.3.2, almalinux9
iCommands 4.3.2

### What did you try to do?
I try to calculate a checksum on the data server-side by the `-k` flag.

### Expected behavior
I expect to see the checksum info that is calculated and stored in the catalog in one these PEPs (`pep_database_reg_data_obj_post`, `pep_api_data_obj_put_post` or `pep_database_mod_data_obj_meta_post`)

### Observed behavior (including steps to reproduce, if applicable)

- `iput -k file` doesnt populate the checksum information in one of the relevant fields (`verifyChksum`, `checksum`, `chksum`) whereas `iput -K file` does and `verifyChksum` in the `pep_api_data_obj_put_post` contains the calculated checksum information.

- `pep_database_mod_data_obj_meta_post` is not invoked

So, I am not able to capture the checksum information if it is calculated by the `-k` flag. Is there a way to fetch this information? Thanks.

**Comment by alanking** [comment]
You could try looking at `pep_database_data_object_finalize_post` to see if the checksum is in there (I think it should be in both the `-k` and `-K` cases).

Where are you getting the calculated checksum information in `pep_api_data_obj_put_post`? The `DataObjInp`? Are you sure that the value is coming from the server's checksum calculation? What if it is the checksum calculation that occurs on the client side in order for it to "verify" the checksum (which is what `-K` does)?

If you wanted to be super sure of the value, you could try using a tool like https://github.com/irods/mungefs to corrupt the checksum value on the server side and this would reveal what value you're looking at. I am guessing that it is the checksum calculated on the client side, but could be wrong about that.

**Comment by mstfdkmn** [comment]
Thanks @alanking , yes `pep_database_data_object_finalize_post` contains the checksum information. This pep seems triggered always three times. But okay, this issue could be closed on my end.
