### ISSUE TITLE
controlled_user_connection_list.users inconsistency, optional or required?

### ISSUE THREAD

**Issue by tedgin** [irods/irods#8017]
- [x] main
- [x] 4-3-stable

---

### iRODS Version, OS and Version

iRODS 4.3.1 Ubuntu 18.04

### What did you try to do?

I created a standalone iRODS server, and I didn't provide a `users` field in the `controlled_user_connection_list` object in `server_config.json`. The server started, but when I tried to upload a file, the server generated the following error.

```
iRODS Exception:
    file: /irods_source/server/core/src/initServer.cpp
    function: std::set<std::string> construct_controlled_user_set(const nlohmann::json &)
    line: 864
    code: -167000 (SYS_LIBRARY_ERROR)
    message:
        Encountered exception while processing [controlled_user_connection_list]. [json.exception.out_of_range.403] key 'users' not found
```

The `server_config.json.in` schema states that this field is optional, but the iRODS server assumes that the field has been provided. 

Either the schema should require the field, or the server should allow it to be undefined.

**Comment by korydraughn** [comment]
Seems appropriate to require the `users` property.

We'll get that fixed up.

**Comment by tedgin** [comment]
It appears that the server expects `controlled_user_connection_list` has the `control_type` field set as well. If it isn't set, the server fails to start without giving a reason.

**Comment by korydraughn** [comment]
That's certainly not good. We'll work on improving that as well.

**Comment by alanking** [comment]
controlled_user_connection_list.users is now required. I think this can be closed, right, @FifthPotato?

**Comment by FifthPotato** [comment]
> controlled_user_connection_list.users is now required. I think this can be closed, right, @FifthPotato?

Yep!
