### ISSUE TITLE
Remove `plugin_home` property from irods_environment.json

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#8019]
Requires that #8018 be resolved first.

- Remove warning message when `plugin_home` is used
- Remove all mentions of `plugin_home` from documentation (irods/irods_docs)

**Comment by trel** [comment]
I notice this says https://github.com/irods/irods/issues/8018 should be closed first.   But it is not.

**Comment by korydraughn** [comment]
Will adjust that wording.
