### ISSUE TITLE
Incorrect use of `std::tolower` to convert strings to lowercase

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#8045]
- [x] main
- [x] 4-3-stable
---
## Bug Report

There are several instances throughout the code base where `::tolower` is passed to `std::transform` without forcing the byte passed to be `unsigned char`.

Please update all instances of this pattern to use the following:
```cpp
std::transform(..., [](unsigned char _c) { return std::tolower(_c); });
```

**Comment by SwooshyCueb** [comment]
I was actually reading about this last week on Raymond Chen's blog: https://devblogs.microsoft.com/oldnewthing/20241007-00/?p=110345
We might not want to be using `std::tolower` at all in some/many/all cases, as it can fall over when multi-byte characters are encountered.

Chen's solution is predictably Windows-centric (and his alternate solution is to use icu, yuck!), but I think [boost.locale](https://beta.boost.org/doc/libs/1_81_0/libs/locale/doc/html/conversions.html) might be suitable for our usage.

**Comment by korydraughn** [comment]
I agree. The proposed solution fixes our use of the C++ stdlib, but still has issues.

Please open an issue to investigate unicode-related improvements and link it to this one.

**Comment by SwooshyCueb** [comment]
I'll open an issue for `std::tolower`/`std::toupper` specifically, and an issue to investigate Unicode-related improvements more broadly.

**Comment by korydraughn** [comment]
Go for it.
