### ISSUE TITLE
Remove unused server_status.json.in file

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#8058]
iRODS does not use server_status.json.in for anything, therefore it should be removed.

https://github.com/irods/irods/blob/40f563a74f52e49646239a7756a9b5b5a5cbc1d8/schemas/configuration/v5/server_status.json.in

**Comment by trel** [comment]
this was used by the control plane... yes?

**Comment by korydraughn** [comment]
Correct. I don't think this file was actually used. It just described the structure. I suspect the plan was to eventually do validation using this.

**Comment by trel** [comment]
Agreed.   Don’t need it anymore.
