### ISSUE TITLE
How to find timestamp of password used

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods#8071]
## Question

Hello, we need to determine the last timestamp when a specific password was used. Is there a method to find this information? We initially thought `pep_auth_agent_verify_pre` might contain it, but it hasn’t been triggered. Could you suggest a PEP that can intercept the password?

**Comment by alanking** [comment]
The short answer is... you cannot detect when a particular native password is being used from a PEP. The PEP will only be able to know whether the authentication attempt was successful.

The API which performs the "auth checks" in the native authentication plugin is `rsAuthCheck`, so `pep_api_auth_check_*` may be a good place to start. This is used for both unexpiring iRODS passwords and temporary passwords employed by other schemes.

If you can describe what you're trying to do in more detail, perhaps we can help a solution.

**Comment by mstfdkmn** [comment]
I was not able to invoke "pep_api_auth_check_*" either.

> If you can describe what you're trying to do in more detail, perhaps we can help with a solution.

As my colleague has implemented a different approach to address their requirements, this issue can now be closed. Thanks.

**Comment by alanking** [comment]
> I was not able to invoke "pep_api_auth_check_*" either.

Ah, my mistake. The API PEP would not occur in this case because the invocation occurs inside of the server (i.e. not crossing the API plugin boundary). `pep_database_check_auth_*` should be firing, though.
