### ISSUE TITLE
deb package should be lintian clean

### ISSUE THREAD

**Issue by trel** [irods/irods#837]
_Originally Opened: @trel (2012-06-13 09:46:11_)

not just error-free, we should get E-iRODS to be lintian clean in order to be eligible for upstream inclusion.
## 

From: https://code.renci.org/gf/project/e-irods/tracker/?action=TrackerItemEdit&tracker_item_id=837

**Comment by mcv21** [comment]
This will also require source packages to be produced (and buildable against the rest of the distribution)

**Comment by trel** [comment]
closing as resolved as we're producing packages via CPack now.
