### ISSUE TITLE
turn on and support unicode

### ISSUE THREAD

**Issue by trel** [irods/irods#975]
_Originally Opened: @trel (2012-09-14 21:40:02_)

via email on 9/14/2012:

checkin referenced below is here:
  https://github.com/irods/irods-legacy/commit/ea2485dc24

-------- Original Message --------
Subject: Re: [iROD-Chat:8630] Spaces and other &quot;strange&quot; characters in
file names
Date: Fri, 14 Sep 2012 17:49:13 +0200
From: Jean-Yves Nief
Reply-To: irod-chat@googlegroups.com
To: irod-chat@googlegroups.com
CC: Chris Smith

the fix is in svn:
server/drivers/src/univMSSDriver.c
As for files with other kind of special characters, accentuated letters
or other charset than the US/english one (chinese, japanese, arabic...),
the iRODS servers have to be configured with the support for UTF8. You
have to uncomment:
#UNI_CODE=1
in config/config.mk
But one has to make sure also that the client is encoding the file names
in UTF8 so all the chain including client, data servers, databases are
dealing with it in a consistent way.
cheers,
JY

Jean-Yves Nief wrote:
&gt; he will test it first and indeed it will be committed in svn
&gt; JY
&gt;
&gt; Chris Smith wrote:
&gt;&gt; I wouldn't mind seeing a correction for this as well, if it's shareable.
&gt;&gt;
&gt;&gt; Thanks,
&gt;&gt;
&gt;&gt; -- Chris
&gt;&gt;
&gt;&gt;
&gt;&gt; On Tue, Sep 11, 2012 at 7:03 AM, Jean-Yves Nief &lt;nief@cc.in2p3.fr&gt; 
&gt;&gt; wrote:
&gt;&gt;&gt; hello,
&gt;&gt;&gt;
&gt;&gt;&gt;         I will sent you offline a correction for this later.
&gt;&gt;&gt; cheers,
&gt;&gt;&gt; JY
&gt;&gt;&gt;
&gt;&gt;&gt;
&gt;&gt;&gt; Pontus Freyhult wrote:
&gt;&gt;&gt;&gt;    Hi all,
&gt;&gt;&gt;&gt;
&gt;&gt;&gt;&gt; I've recently joined Uppmax to work with their iRODS systems.
&gt;&gt;&gt;&gt;
&gt;&gt;&gt;&gt; One of the first thing I started I looking at was our integration 
&gt;&gt;&gt;&gt; with a
&gt;&gt;&gt;&gt; dCache system, which uses the univMSS driver, we had some strange 
&gt;&gt;&gt;&gt; errors
&gt;&gt;&gt;&gt; occurring.
&gt;&gt;&gt;&gt;
&gt;&gt;&gt;&gt; After a short round of investigation, it seems neither the univMSS
&gt;&gt;&gt;&gt; driver, nor the underlying base functionality it uses (code to launch
&gt;&gt;&gt;&gt; another process) to start the generic (installation adaptable) part 
&gt;&gt;&gt;&gt; are
&gt;&gt;&gt;&gt; designed to handle file names with spaces.
&gt;&gt;&gt;&gt;
&gt;&gt;&gt;&gt; Am I missing something or are our users really the first ones that 
&gt;&gt;&gt;&gt; want
&gt;&gt;&gt;&gt; to do that? I haven't done a very thorough examination yet, but I
&gt;&gt;&gt;&gt; suspect there should be the same kind of issues for anything trying to
&gt;&gt;&gt;&gt; call externals working on $objPath or similar.
&gt;&gt;&gt;&gt;
&gt;&gt;&gt;&gt; I'm also a bit worried about what can possibly be done by using other
&gt;&gt;&gt;&gt; characters (if they finally end up in a script parser), but haven't 
&gt;&gt;&gt;&gt; been
&gt;&gt;&gt;&gt; able to think out a really problematic example yet (the univMSS driver
&gt;&gt;&gt;&gt; generic template doesn't quote the parameters it receives as much 
&gt;&gt;&gt;&gt; as it
&gt;&gt;&gt;&gt; should, but I haven't managed to trick it into doing something really
&gt;&gt;&gt;&gt; bad yet (I think I've gotten to naughty, though).
&gt;&gt;&gt;&gt;
&gt;&gt;&gt;&gt; We've temporarily set up a rule to block what we feel are problematic
&gt;&gt;&gt;&gt; names, but we would like to see this fixed anyway so we can at least
&gt;&gt;&gt;&gt; allow spaces. While the code and fix seem straight forward enough, I
&gt;&gt;&gt;&gt; wouldn't mind knowing the overall system a bit more before if I 
&gt;&gt;&gt;&gt; were to
&gt;&gt;&gt;&gt; do it (so, if anyone would care to fix it, we'd be thrilled).
&gt;&gt;&gt;&gt;
&gt;&gt;&gt;&gt;    /Pontus

--

From: https://code.renci.org/gf/project/e-irods/tracker/?action=TrackerItemEdit&tracker_item_id=975

**Comment by kript** [comment]
Apologies if I'm being dense, but is this issue saying that iRODS 4.1.7 doesn't support Unicode?

**Comment by Pete-C** [comment]
Hello Guys,This is pretty urgent for us. Our sample set include a positive phi sample. This is often added by lab staff as 
Φ. We also have other similar data with other such symbols that we need to survive and work after our 3.3.x upgrade
 


    On Monday, 7 December 2015, 8:55, John Constable <notifications@github.com> wrote:
 

 Apologies if I'm being dense, but is this issue saying that iRODS 4.1.7 doesn't support Unicode? —

**Comment by jasoncoposky** [comment]
We have unicode tested via both the python client API as well as the HPSS plugin.

**Comment by Pete-C** [comment]
Fantastic, so if it's all there that's one more off our list. Many thanks for the update and the quick update.Pete 


    On Monday, 7 December 2015, 16:23, Jason M. Coposky <notifications@github.com> wrote:
 

 We have unicode tested via both the python client API as well as the HPSS plugin.—

**Comment by trel** [comment]
https://github.com/irods/python-irodsclient/blob/master/irods/test/unicode_test.py
